### ISSUE TITLE
Feature Sweep: Revenue Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1038]
The feature sweep task involves revisiting a developed feature, and analyzing the components and functionality to ensure they match up with the original designed experience. Ideally you should perform a Feature Sweep using a device and/or browser that you typically do not work with. Try Browser Stack, or an emulator, try to _feel_  experience through a different lens.

Prior to opening up additional issues, lets use this issue to discuss and log findings of your sweep - please share your browser/device config with your findings too.

## Revenue Report Sweep

Original Revenue Post: p6riRB-3dN-p2

**Comment by LevinMedia** [comment]
Heavy QA for data accuracy
