### ISSUE TITLE
Orders Report: Advanced Filter for categories?

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#1047]
Determine if an Advanced Filter should be added to the Orders Report.

### Why?

It would be useful to link the orders count from the table in Categories Report to the Orders Report showing only orders including (or excluding) a particular category.

**Comment by timmyc** [comment]
@LevinMedia two pennies for your thoughts here. Seems reasonable, do we have REST API support already though?

**Comment by psealock** [comment]
>do we have REST API support already though?

We don't. @peterfabian was headed in that direction, but I told him not to 😞, oops sorry about that. If we go forward with this Advanced Filter, I'll create another issue.

**Comment by LevinMedia** [comment]
I think we should add it, however I think some of the other API work should take priority over this.

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
