### ISSUE TITLE
Product review placeholder image

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1067]
**Describe the bug**
The placeholder image looks odd with the white background when an image is not set.  Almost looks like 2 misaligned images.

**To Reproduce**
1.  Add a product with no image.
2.  Open the "Reviews" tab from the wc-admin header.
3.  Note the placeholder image with the adjacent user avatar.

**Expected behavior**
Expected a border, slight gray background, or different placeholder image.  @LevinMedia what do you think?  Does this look okay to you or are changes warranted?

**Screenshots**
<img width="260" alt="screen shot 2018-12-11 at 3 07 14 pm" src="https://user-images.githubusercontent.com/10561050/49842233-ac0abd80-fdf5-11e8-89d2-cf6893f1fb73.png">

**Comment by LevinMedia** [comment]
<img width="1023" alt="screen shot 2018-12-12 at 3 37 26 pm" src="https://user-images.githubusercontent.com/4500952/49905771-f30fa780-fe23-11e8-8e7d-ddaed7e91605.png">

In cases where a product image hasn't been set, let's add a `$core-grey-dark-500` color overlay to the product image with 10% opacity.

**Comment by Aljullu** [comment]
@LevinMedia I was taking a look at this issue and it looks like the placeholder image we use has a white background:

https://github.com/woocommerce/woocommerce/blob/master/assets/images/placeholder.png

Do you know if we have a similar asset with gray or transparent background?

**Comment by LevinMedia** [comment]
Heya! I don't think we do... I could always create one. I ran into the same problem while designing, my proposed solution was using a grey color overlay on the image:

`In cases where a product image hasn't been set, let's add a $core-grey-dark-500 color overlay to the placeholder product image with 10% opacity.`

Would you prefer a transparent png?

**Comment by Aljullu** [comment]
@LevinMedia my bad, I read it too fast. :man_facepalming: 

> Would you prefer a transparent png?

No need for that, thank you!
