### ISSUE TITLE
Before and after endpoint param defaults to 1 week

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1103]
**Describe the bug**
When either the before or after param is set (and not both) the data is limited to 1 week in the other direction.

**To Reproduce**

1. Make a request to any endpoint in our REST API.
2. Set either the before or after param (not both).
3. Note that the returned response will be limited to one week of data.

**Expected behavior**
Expected setting an after data would return all data after a specified date.  E.g., setting 2018-07-04 00:00:00 would return all data after July 4th to date.

Does it make sense to change it this way or is there a reason we'd prefer to keep it at 1 week?  Any performance implications from changing this?

/cc @peterfabian

**Comment by timmyc** [comment]
This is a tough one as if we are too _generous_ with returning a large data set, it could really hammer a site from a performance standpoint. I.E. if I submit a request with a `before` of today - and I have years worth of data, that would be an expensive operation, as would the inverse of that of setting an `after` param for a date years ago on an established site.

I suppose I think we should just be explicit in what would be returned in this scenario in the REST API documentation. Or even go so far to require both params to be set?

**Comment by joshuatf** [comment]
I think being explaining this in the REST API docs is enough.  

It would be ideal if we could return everything after or before without limits, but you're right in that this could result in huge data sets and if someone really needs that timeframe, they can explicitly request it.

**Comment by peterfabian** [comment]
Side note: attempt to centralize this in #1515 if we want to change it for all. 

Btw, I don't think it would be too bad even for large sites without the weekly default, as one can only get 100 results per page and `totals` is calculated entirely in the database. I don't think there's much difference between the queries with and without the time constraint. Maybe worth a try if this bugs us.

**Comment by psealock** [comment]
I believe we are happy with the defaults. We can re-open if this becomes an issue
