### ISSUE TITLE
Feature Sweep: Product Report

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#1138]
The feature sweep task involves revisiting a developed feature, and analyzing the components and functionality to ensure they match up with the original designed experience. Ideally you should perform a Feature Sweep using a device and/or browser that you typically do not work with. Try Browser Stack, or an emulator, try to feel experience through a different lens.

Prior to opening up additional issues, lets use this issue to discuss and log findings of your sweep - please share your browser/device config with your findings too.

**Comment by LevinMedia** [comment]
**Bug:**

Chart not filling zeros

<img width="1280" alt="screen shot 2018-12-19 at 7 24 45 pm" src="https://user-images.githubusercontent.com/4500952/50262047-127a7780-03c4-11e9-9599-cc4d897a6a75.png">

---

**Missing Features**

Requires data segmentation:

1. Unable to visualize product comparisons in graph
2. Unable to visualize variations comparisons in graph while viewing a single product
3. Unable to visualize comparison when filtering by "Top products by net revenue", "Top products by items sold", "Top variations by items sold", and "Top variations by gross revenue"

Misc: 

Add categories to the tabular data (Open PR #1131)

The comparison chart should have a select menu in its header when filtering by "Top products by items sold" and "Top products by gross revenue". Same goes when a user is viewing a single product and able to select "Top variations by gross revenue" and "Top variations by items sold"

<img width="1073" alt="screen shot 2018-12-19 at 7 50 51 pm" src="https://user-images.githubusercontent.com/4500952/50262779-c4677300-03c7-11e9-978d-68c999ddcd80.png">

When selecting one or the other filters, we should automatically select the appropriate summary number, so the graph reflects the right data (We're automatically sorting the tabular data by the appropriate row.

---

**Enhancement**

Add the ability to filter by category. (display all products in a single, or multiple categories) This would allow for deep linking opportunities from the category report (category name, and items sold columns in tabular data) as noted in #1046

For now we should remove the "Product category comparison" option from the filter list.

**Comment by LevinMedia** [comment]
**Bug:**

Chart not filling zeros

<img width="1280" alt="screen shot 2018-12-19 at 7 24 45 pm" src="https://user-images.githubusercontent.com/4500952/50262047-127a7780-03c4-11e9-9599-cc4d897a6a75.png">

**Comment by LevinMedia** [comment]
**QA**

Ensure refunds are appropriately accounted for per p7bje6-1dV-p2

**Comment by LevinMedia** [comment]
**Missing Features**

Requires data segmentation:

1. Unable to visualize product comparisons in graph
2. Unable to visualize variations comparisons in graph while viewing a single product
3. Unable to visualize comparison when filtering by "Top products by net revenue", "Top products by items sold", "Top variations by items sold", and "Top variations by gross revenue"

Misc: 

Add categories to the tabular data (Open PR #1131)

The comparison chart should have a select menu in its header when filtering by "Top products by items sold" and "Top products by gross revenue". Same goes when a user is viewing a single product and able to select "Top variations by gross revenue" and "Top variations by items sold"

<img width="1073" alt="screen shot 2018-12-19 at 7 50 51 pm" src="https://user-images.githubusercontent.com/4500952/50262779-c4677300-03c7-11e9-978d-68c999ddcd80.png">

When selecting one or the other filters, we should automatically select the appropriate summary number, so the graph reflects the right data (We're automatically sorting the tabular data by the appropriate row.

**Comment by LevinMedia** [comment]
**Misc:** 

Add categories to the tabular data (Open PR #1131)

**Comment by LevinMedia** [comment]
**Feature** 

The comparison chart should have a select menu in its header when filtering by "Top products by items sold" and "Top products by gross revenue". Same goes when a user is viewing a single product and able to select "Top variations by gross revenue" and "Top variations by items sold"

<img width="1073" alt="screen shot 2018-12-19 at 7 50 51 pm" src="https://user-images.githubusercontent.com/4500952/50262779-c4677300-03c7-11e9-978d-68c999ddcd80.png">

When selecting one or the other filters, we should automatically select the appropriate summary number, so the graph reflects the right data (We're automatically sorting the tabular data by the appropriate row.

**Comment by LevinMedia** [comment]
**Enhancement**

Add the ability to filter by category. (display all products in a single, or multiple categories) This would allow for deep linking opportunities from the category report (category name, and items sold columns in tabular data) as noted in #1046

For now we should remove the "Product category comparison" option from the filter list.

**Comment by LevinMedia** [comment]
**Bug**

Product SKUs not hooked up in tabular data, also affects single product view

<img width="1492" alt="screen shot 2018-12-20 at 8 03 22 pm" src="https://user-images.githubusercontent.com/4500952/50324192-7a978f00-0492-11e9-857b-343376bf54e2.png">

**Comment by timmyc** [comment]
@LevinMedia SKU bug has been fixed, and currently on the variations view, we don't show a SKU column - should that be changed?

![image](https://user-images.githubusercontent.com/22080/51063113-6a189700-15ae-11e9-9473-2c7908e15f2f.png)
