### ISSUE TITLE
REST API:  Handle Custom Product Tables

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#1143]
In reworking the Categories Report query, I came across this comment:

```
// Group by category without a helper table, worst case we add it and change the SQL afterwards.
// Other option would be a join with wp_post and taxonomies, but a) performance might be bad, b) how to handle custom product tables?
```
https://github.com/woocommerce/wc-admin/pull/1135#pullrequestreview-186836637 satisfies the performance question, but the custom product tables question remains and this issue will serve as a place to track that question. 

Also, what affect will that have on the Products Report Query?

**Comment by joshuatf** [comment]
@peterfabian I think you might have left this comment.  Do you have more info on this?

I think it may be referring to [this plugin](https://github.com/woocommerce/woocommerce-product-tables-feature-plugin) and I would imagine that would change how most of our data stores handle population.

**Comment by peterfabian** [comment]
I don't have much more info, besides the fact that our plugin won't work with custom product table plugin (exactly the one linked by @joshuatf ) and we should probably think about how we could make it work or if that's something for future version.

**Comment by claudiosanches** [comment]
> we should probably think about how we could make it work or if that's something for future version.

We need update the Product Tables plugin and hook into reports Data Store to make it work.
When getting any data from the `WC_Product` class should be just fine, but since we are doing directly queries we should update that plugin too.

My advice is to close this issue for now and open another in Product Tables plugin repository.

**Comment by timmyc** [comment]
> My advice is to close this issue for now and open another in Product Tables plugin repository.

Closing in favor of https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/issues/147
