### ISSUE TITLE
Single Date Picker: A11y review

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#1145]
https://github.com/woocommerce/wc-admin/pull/1069 is getting merged although it has dependencies relating to the following upstream Gutenberg changes, mostly involving passing through props to various child components.

* https://github.com/WordPress/gutenberg/pull/12855 
* https://github.com/WordPress/gutenberg/pull/12933
* https://github.com/WordPress/gutenberg/pull/12962
* https://github.com/WordPress/gutenberg/pull/12963

Upon completion of these, the `<DatePicker />` needs a full a11y review.

**Comment by timmyc** [comment]
Any more work to be done here @psealock ?
