### ISSUE TITLE
IE11 build requires checking new packages and adding to babel list

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1176]
In https://github.com/woocommerce/wc-admin/pull/1170 we implemented a solution that uses babel to make vendor packages compatible with IE11.  This current solution requires checking IE11 each time to see if they need to be added to the list.

I'm not sure if this is the best approach or if someone with more webpack knowledge has a better solution here, but here are a couple alternatives and advantages/disadvantages:

* Use babel on all node_modules - Time consuming operation and may cause more headache depending on type of script used.
* Babel everything but only on build and not dev - We lose the ability to actively see development changes in IE11.

If the current method is the best option, we can close this issue.

**Comment by timmyc** [comment]
@ryelle any thoughts or opinions on this one?

**Comment by Aljullu** [comment]
> * Use babel on all node_modules - Time consuming operation and may cause more headache depending on type of script used.

It looks like this is the solution they are using in `wp-calypso`:

https://github.com/Automattic/wp-calypso/pull/30196

**Comment by timmyc** [comment]
If I'm reading the Calypso PR correctly, it seems they have gone with a similar approach implemented in #1176 correct @joshuatf @Aljullu - if so I say we close this out. Not certain how often we will be adding dependencies to wc-admin to make the current solution a nuisance or not.

**Comment by Aljullu** [comment]
> If I'm reading the Calypso PR correctly, it seems they have gone with a similar approach implemented in #1176 correct @joshuatf @Aljullu - if so I say we close this out.

Sounds good to me.

> Not certain how often we will be adding dependencies to wc-admin to make the current solution a nuisance or not.

At this point, we are not adding as many dependencies as we were some months ago, so I would suggest taking one of this two approaches:
* Testing WooCommerce Admin in IE11 before every release, making sure it loads and it's not a blank screen.
* Or, testing WooCommerce Admin in IE11 every time we add a new dependency. Maybe we should add a comment in the PR template to make sure we don't forget to do that?

**Comment by timmyc** [comment]
I think both of those suggestions are great. Doing a smoke test on IE11 prior to each release and a step when adding new dependencies. +1 on the PR template modification.

I've updated the Field Notes page with the release instructions on the p2 to test IE11, along with testing database migrations.

**Comment by timmyc** [comment]
I'm closing this out now that we have the stopgap in place of testing on IE11 prior to each release.
