### ISSUE TITLE
Report columns should be able to use the table name

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1308]
Various joins cause ambiguous columns across most data stores.  In order to circumvent this, we added overrides for individual columns in the construct method.

```php
	/**
	 * Constructor
	 */
	public function __construct() {
		global $wpdb;
		$table_name = $wpdb->prefix . self::TABLE_NAME;
		// Avoid ambigious columns in SQL query.
		$this->report_columns['order_id']     = $table_name . '.' . $this->report_columns['order_id'];
		$this->report_columns['date_created'] = $table_name . '.' . $this->report_columns['date_created'];
		$this->report_columns['customer_id']  = $table_name . '.' . $this->report_columns['customer_id'];
	}
```

This has resulted in more overhead and some code duplication that may cause difficult in debugging down the road.

A cleaner method might be to filter these prior to them becoming `$selections` and allowing `{$table_name}` inside the report column item value.  For example:

```php
	protected $report_columns = array(
		'order_id'       => "{$table_name}.order_id",
	);
```

If that's not possible, making `$report_columns` into a static function so that we can make use of the global `$wpdb` might also be a good option.

**Comment by rrennick** [comment]
Addressed in #2961 and follow ups.
