### ISSUE TITLE
Data store refactor and pattern changes

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1320]
Each data store has a number of reusable methods inherited from `WC_Admin_Reports_Data_Store`.  These work well, but there are a few places we're starting to repeat ourselves and use different patterns that make DRYing it up difficult.

Should we consider making these patterns consistent and extracting repeated areas in each data store to parent methods?  This is a potentially big refactor, so before starting I think we should consider whether or not this is worth the time.

Here's an example of a discussion around an area that would be difficult to DRY up without refactoring first - https://github.com/woocommerce/wc-admin/pull/1285#discussion_r247804092

### Potential updates

Here are a few areas we might want to touch on.  I think that separating these into child issues might make this more manageable if we choose to do these.

- [ ] **Standardize sql query params**
Under `get_sql_query_params()` we use multiple patterns to add where and from filters:

```
$sql_query_params['where_clause'] .= " AND ( {$order_status_filter} )";
```
```
$where_subclause = implode( " $operator ", array_filter( array( $where_subclause, $order_status_filter ) ) );
```
```
$products_where_clause .= " AND ( {$order_status_filter} )";
```
```
$where_filters[] = $order_status_filter;
```
```
$sql_query_params['where_clause'] .= " AND ( {$order_status_filter} )";
$sql_query_params['where_clause'] .= ' AND variation_id > 0';
```
If we standardize these a bit more, we can reduce mental overhead and handle a lot of the common filter queries in a parent method.

Maybe instead of using strings here, we could use an array and join by the operator:
```php
$sql_query_params['where'] = array(
    "( {$order_status_filter} )",
    "variation_id > 0"
);
```

Note that with the above, we may need to consider how this works with default excluded status conditions that should not use the `OR` operator if `match` is set to `ANY` in the query param.

Also we have `get_sql_query_params()` and `update_sql_query_params()` - both do the same thing, but the latter updates in place and also handles totals and intervals.
- [ ] **Ambiguous columns** - https://github.com/woocommerce/wc-admin/issues/1308
- [ ] **DRY up get_data**
The selection query can be extracted out to handle selections if sql params are standardized so we're not repeating the same thing in every data store.
```php
    "SELECT
            {$selections}
        FROM
            {$table_name}
            {$sql_query_params['from_clause']}
        WHERE
            1=1
            {$sql_query_params['where_time_clause']}
            {$sql_query_params['where_clause']}
        ORDER BY
            {$sql_query_params['order_by_clause']}
        {$sql_query_params['limit']}
        ",
```
The same can be probably be done for this piece of logic and cache checking:
```php
			$total_pages = (int) ceil( $db_records_count / $sql_query_params['per_page'] );
			if ( $query_args['page'] < 1 || $query_args['page'] > $total_pages ) {
				return $data;
			}
```

It might be nice if the `get_data()` method is handled as a parent method and any changes to this data are applied in an optional method call to the child class if defined.
- [ ] **Commonly used filter queries**
Commonly used filters for query params include:
* `get_status_subquery()`
* `get_included_products()`
* `get_included_coupons()`
* `get_included_orders()`
* `get_excluded_coupons()`
* `get_excluded_products()`
* `get_excluded_orders()`

The condition strings for these have already been extracted to `WC_Admin_Reports_Data_Store`, however, if we standardize the sql params (task from above), we could have these directly append conditions to the `where_clause` and `from_clause` so we're not repeating this kind of logic in every data store:

```php
$order_status_filter = $this->get_status_subquery( $query_args );
if ( $order_status_filter ) {
	$sql_query_params['from_clause']  .= " JOIN {$wpdb->prefix}posts ON {$order_coupon_lookup_table}.order_id = {$wpdb->prefix}posts.ID";
	$sql_query_params['where_clause'] .= " AND ( {$order_status_filter} )";
}
```

### Should this be prioritized? Why?
If we decide to move forward with it, then yes.  It will make maintaining and adding new data store features much easier.

**Comment by peterfabian** [comment]
I agree it would be nice. The 'design' was quite ad-hoc as new issues were requested and those were treated mostly as add-ons. Also, now that we'll include segmenting which adds even more queries, it's becoming quite unpleasant to look at. 
Maybe there's a better balance in the spectrum between 'methods doing what I need in this piece of code' and 'general SQL generator' that could improve the readability and maintainability of this code.

**Comment by joshuatf** [comment]
>The 'design' was quite ad-hoc as new features were requested and those were treated mostly as add-ons (especially advanced filters).

And you did a fantastic job improvising and setting up a framework that worked well for all of these.

>I would maybe suggest we review it after segmenting is added, as I'd hope that would stabilize the amount of different database operations and patterns of db query uses for some time.

Do you think that once we get https://github.com/woocommerce/wc-admin/pull/1286 merged in that will be enough to identify any changes needed and we can add to sprint 12?   Or should we wait until we get segmenting in place for all data stores before making any changes here?

/cc @peterfabian @timmyc

**Comment by timmyc** [comment]
I think this would be valuable to do sooner than later, so sprint 12 makes sense to me.
