### ISSUE TITLE
Activity Panel: Implementation of useful Inbox notices

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1431]
Right now, only a handful of notices are implemented in core (store notice, best sales). To properly implement the Inbox feature, we need more useful and timely information.

This issue can serve as a master issue for implementing a MVLP level amount of useful notices for core. This issue can be closed when that criteria is met.

A document for these was started. See p6q8Tx-PA-p2 #comment-2827. This is not a final list.

> We need to come back to it and make it definitive to move forward.

**Comment by josemarques** [comment]
@warrendholmes and I are working to finalize that list. We'll have that by next week.

**Comment by timmyc** [comment]
also adding @laurendavissmith to the convo as the extendables have already implemented some for bookings, but not sure if they have plans for other inbox notifs elsewhere.

**Comment by timmyc** [comment]
I'm closing this out in favor of the individual issues that exist for the remaining notifs.
