### ISSUE TITLE
Table search: Reuse autocompleter API calls to get matching items id

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1453]
When doing a search in the table query, the autocompleter returns the ids of the matching items. It would be good to use those ids to populate the report without requiring a new API call.

Two things must be taken into account:
- Searches might be performed without having displayed the autocompleter. For example, when reloading the page or modifying the `search` parameter in the URL.
- The autocompleter limits the number of results to 10, but we would like to display more matches in the table.

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
