### ISSUE TITLE
Table search: Increase the limit of 10 results

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1454]
Coming from https://github.com/woocommerce/wc-admin/pull/1381#discussion_r252481505.

When loading a report with a table search active, we are limiting the number of results to 10. We would like to increase that number and consider adding a UI message if we can't load all of them.

![image](https://user-images.githubusercontent.com/22080/60995573-99168800-a307-11e9-986d-33944266cc0d.png)

**Comment by timmyc** [comment]
Also wanted to capture @jeffstieler's thoughts [from here](https://github.com/woocommerce/wc-admin/pull/1534#issuecomment-463250441)

```
in addition to increasing the `LIMIT` on these queries, I think the way we populate the report table for "all values that include" needs to change. The table is given the `<= 10` IDs from the fuzzy search query rather than the search term itself.
```

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
