### ISSUE TITLE
Component: Order Print Menu

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#150]
Child issue of #144 

**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/console/14683254/305328642/preview)

![image](https://user-images.githubusercontent.com/22080/42241446-75763b24-7ebf-11e8-9864-005464a29d5b.png)

This is the first area of `wc-admin` to included an extensibility option. As such, this might be a great opportunity to look back at both #13 and #16 and see which route might be the best one to take here.

The extensibility here is for developers to add an option(s) to the Print menu shown within the order card, which will just be a simple `<a>` link with a target URL and a label.

__Tasks__
- The Print Menu should leverage the `EllipsisMenu` component
-  It should only be shown if an extension has added an option(s) to the menu

**Comment by psealock** [comment]
@pmcpinto Is this still a priority?

**Comment by timmyc** [comment]
I think with the upcoming proposed changes to the Activity Panels, this one feels safe to close out. I still think it is a great extensibility target for WCS though.
