### ISSUE TITLE
Update WordPress.org readme.txt before feature plugin release

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1536]
In https://github.com/woocommerce/wc-admin/pull/1521, I added a basic `readme.txt`. This file is used for displaying plugin information on WordPress.org.

Before releasing to WordPress.org, we need to update the plugin name, description, add some installation steps, and perhaps some screenshots. Some of this is pending the discussion at p8eNEx-3Dl-p2.

**Comment by justinshreve** [comment]
@timmyc I've added this to the Sprint 13 backlog since we should update some of this prior to release.

**Comment by timmyc** [comment]
Closing this out as #1724 took care of this.
