### ISSUE TITLE
Per product low stock threshold

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1553]
While working on the stock report in #1535, Paul pointed out that setting a products low stock threshold does not actually mark that product as "low stock" in the new reports UI. After digging, this is true of all current screens in core as well. The product listing, current report, and WordPress dashboard widget don't count theses as "low stock". Getting a list of these products would also be made easier with a piece of meta as I noted here https://github.com/woocommerce/wc-admin/pull/1535#issuecomment-463277399.

Is this something that is OK to fix post v1?

**Comment by timmyc** [comment]
I think this is fine to handle post v1 or see if it comes up from users at all.

**Comment by psealock** [comment]
I haven't looked into why, but I just noticed that we accurately indicate "Low" stock for individually managed products in the Product Report, but not in the Stock Report

Product Report.

<img width="986" alt="Screen Shot 2019-04-05 at 3 06 13 PM" src="https://user-images.githubusercontent.com/1922453/55599483-90686000-57b4-11e9-98cb-74d91db93a54.png">

Stock Report

<img width="744" alt="Screen Shot 2019-04-05 at 3 05 44 PM" src="https://user-images.githubusercontent.com/1922453/55599492-978f6e00-57b4-11e9-8888-4d712970ec1d.png">

Now that we're highlighting Stock with an Activity Panel https://github.com/woocommerce/woocommerce-admin/pull/1998, it might be a good idea to look into this one further.

**Comment by psealock** [comment]
Incidentally, the "Long Sleeve Tee" does show up in #1998 in the Stock Activity Panel as requiring attention.

**Comment by timmyc** [comment]
> I haven't looked into why, but I just noticed that we accurately indicate "Low" stock for individually managed products in the Product Report, but not in the Stock Report

Yeah seems like we need to have consistency here.
