### ISSUE TITLE
Order Card: Expanded Design + Fulfill

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#157]
Child issue of #144 

**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/console/14683254/305328642/preview)

![image](https://user-images.githubusercontent.com/22080/42249752-db14e418-7ee1-11e8-9995-63bd50b3ca72.png)

Likely best implemented after #156 - this is the view that is exposed/expanded when "Begin Fulfillment" is clicked in the collapsed Order card view. This issue also involves implementing the fulfillment API call, and the animations seen [here](https://cloudup.com/iu0dLQhLecj)

**Comment by psealock** [comment]
this is now a button "Begin fulfillment"
