### ISSUE TITLE
Chart: Oddities in Narrow Viewports

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1574]
**Describe the bug**
When viewing a chart in a narrow/mobile viewport, there are a few things that look a tad bit off:

![chart-small-viewport-oddities](https://user-images.githubusercontent.com/22080/52832970-b5333780-308f-11e9-9295-1d004c59dbdd.png)

- In the screenshot above, having "Items Sold" displayed two times, in such close proximity to each other seems redundant. Is the text in the summary number good enough to convey what is being shown in the chart in a small window like this?
- The interval selection drop down gets really lost when it is wrapped onto a new line. It is visually hard to tell that it can be adjusted in this view also.

**To Reproduce**

1. Use a device or an emulator, and open any report with a chart

/cc @LevinMedia @josemarques

**Comment by joshuatf** [comment]
@LevinMedia Should we just drop the second "Items Sold" line here and add some "default" styling to the dropdown?

<img width="400" alt="Screen Shot 2019-03-22 at 5 10 25 PM" src="https://user-images.githubusercontent.com/10561050/54812176-72cfcc80-4cc5-11e9-976b-89e794120408.png">

**Comment by LevinMedia** [comment]
If we can drop the chart header label small screens, and move the interval select up to take it's place, that'd be great. 

I noticed that at least when simulating in chrome dev tools, the arrows to the right of the "By day" label disappear regardless of what screen size you're looking at... 

No dev tools:

<img width="2022" alt="Screen Shot 2019-03-22 at 8 10 08 AM" src="https://user-images.githubusercontent.com/4500952/54832830-2f03a580-4c7a-11e9-8066-c720f79dd592.png">

Dev tools active:

<img width="2022" alt="Screen Shot 2019-03-22 at 8 09 56 AM" src="https://user-images.githubusercontent.com/4500952/54832985-75590480-4c7a-11e9-8dc1-8cb87642526a.png">

I think it's fine if it has the arrows next to the label.

**Comment by joshuatf** [comment]
@timmyc Just to double check, that select box styling only occurred in Chrome emulation mode, right?

**Comment by timmyc** [comment]
Correct @joshuatf
