### ISSUE TITLE
User profile information not used for customers

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1579]
User first names and last names that are stored in `wc_customer_lookup` pull information from the billing information on creation.  While this mostly okay, there are cases where the billing info may not be present and shipping or user profile fields could be used as a backup.

This is a follow-up/enhancement to the issue outline here - https://github.com/woocommerce/wc-admin/issues/1428

**Steps to reproduce**

1.  Install the checkout field editor plugin and set billing name fields to optional.
2. Create a new user with first and last names filled out.
3.  Don't fill out the name during checkout.
4.  Note that order information is nameless in reporting.

**Describe the solution you'd like**
Would be great if we can pull in this order, cycling to the next if one is not found:
* Billing
* Shipping
* User profile

**Comment by timmyc** [comment]
The solution seems reasonable to me - as long as we include a filter that can be hooked into to derive the customer name, that seems like it would allow any extension to add custom logic here and update customer names in the analytics accordingly.
