### ISSUE TITLE
Choosing a product category changes the date range the product report 

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#1588]
**Describe the bug**
When you choose a product category on the product report, it changes the date range on the graph.

**To Reproduce**

1. Go to dashboard
2. Change the date range to year to date
3. Click on a product to load the report for that product
4. Click on one of the product's categories
5. See the date on the chart

**Expected behavior**
The chart should keep the selected date range.

**Screenshots**
<img width="1092" alt="screen shot 2019-02-15 at 11 42 15 am" src="https://user-images.githubusercontent.com/343847/52867405-400b4500-3117-11e9-817d-99f078ff5ec1.png">

<img width="1081" alt="screen shot 2019-02-15 at 11 42 36 am" src="https://user-images.githubusercontent.com/343847/52867254-e4d95280-3116-11e9-9804-f0d202426a6b.png">

**Desktop (please complete the following information):**

* OS: MacOS
* Browser chrome
* Version 72.0.3626.96

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by timmyc** [comment]
I'm no longer able to reproduce this issue @rrennick so I'm going to close this out.
