### ISSUE TITLE
Design: Summary Number Component Updates / Enhancements

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#160]
Add new states to component design: p6riRB-3iy-p2

- [ ] When there is no data to display (zero state)
- [x] Neutral change for the comparison period

**Comment by psealock** [comment]
I think its ok to close this one.

>When there is no data to display (zero state)

While loading:

<img width="327" alt="Screen Shot 2019-10-07 at 11 33 08 AM" src="https://user-images.githubusercontent.com/1922453/66277111-53615f80-e8f6-11e9-8da2-ff18fb3657de.png">

And when there is no data:

<img width="880" alt="Screen Shot 2019-10-07 at 11 32 50 AM" src="https://user-images.githubusercontent.com/1922453/66277113-59efd700-e8f6-11e9-9b22-0d41e61292b2.png">
