### ISSUE TITLE
Question: Coupons Endpoint - should search include description?

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#1611]
**Describe the bug**

Found as part of #1525.

The coupons report endpoint `search` parameter searches the coupon description - should it?

This can lead to somewhat confusing results since the description isn't shown in the report table.

**To Reproduce**

1. Go to Coupons Report
2. Search for a term that's in a coupon description, but not it's code (like "woo" on WCCOM data)
3. See results that don't appear to contain the search term

**Expected behavior**

Perhaps the `199...` coupon shouldn't be there? _(See screenshot below)_

**Screenshots**

![screen shot 2019-02-18 at 1 03 39 pm](https://user-images.githubusercontent.com/63922/52974180-ebb5ce80-337d-11e9-9a9e-6bbafe2e01b0.png)

**Comment by joshuatf** [comment]
Agreed.  This will also block results in the autocomplete since the API is returning a larger data set and the autocomplete list is filtering it by coupon code matching.
