### ISSUE TITLE
Customer Report: Broken filters

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1617]
Using `master`, I can't get the following advanced filters to work on the customers report:

* Username
* Country
* Name
* Email

Other number/date based filters seem to work.

**To Reproduce**
* Go to the customers report.
* Try adding one of the above filters, autocompleting a name, and hitting filter.
* Notice that the results do not change / the same number of customers is returned.

**Comment by psealock** [comment]
Some prior art here:
https://github.com/woocommerce/wc-admin/issues/1387
