### ISSUE TITLE
Changing excluded statuses settings invalidates customer type data

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1637]
**Describe the bug**
Changing excluded statuses invalidates data for new/returning customers since these take into account whether a customer has made a "successful" order or not.

While we could regenerate all report order data when these settings are changed, as @timmyc [noted](https://github.com/woocommerce/wc-admin/issues/1473#issuecomment-461857770) this could quickly get out of hand.  A better approach may just be to add a note in the help text that report order should be regenerated to fix customer data.

**To Reproduce**

1. Create 2 orders with a new customer.
2. Set those order statuses to a non-excluded status.
3.  Note the 2nd order should count as "returning."
4.  Change the excluded statuses to include the statuses from the 2 orders.
5.  Note the customer has now not technically made a successful order and should not be considered "returning" but the data still shows them as a returning customer.

**Expected behavior**
Expected to see the correct data for customer types.

**Comment by timmyc** [comment]
Thinking the documentation approach might be the best route to take here, and/or an alert informing users that existing report data will need to be updated upon changing of excluded statuses.

**Comment by chihsuan** [comment]
I'm closing this since the last comment is over 6 months old.

>  If we haven’t fixed it in the last six months, we probably won’t care about it for the next six months either. -- p90Yrv-2Bc-p2
