### ISSUE TITLE
Table Header Issues in Mobile Safari

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1649]
**Describe the bug**
When viewing wc-admin in Mobile Safari ( emulator os 10.1 ), I'm seeing some display issues in the header of tables:

__Orders__
![image](https://user-images.githubusercontent.com/22080/53117888-c3a2a880-3500-11e9-85c8-76b8fd68fe63.png)

__Products__
![image](https://user-images.githubusercontent.com/22080/53117924-d7e6a580-3500-11e9-9086-361d2bd7b6a8.png)

__Customers__
![image](https://user-images.githubusercontent.com/22080/53117989-f3ea4700-3500-11e9-9df1-ba87fdb64b94.png)

**To Reproduce**
Using an iOS device or the simulator that ships with xcode, open up any of the reports noted above and view the table header area.

* Device: iPhone
* OS: 10.1
* Browser mobile safari

**Comment by joshuatf** [comment]
Unassigning myself since we're putting grid related issues on hold for the time being.

**Comment by timmyc** [comment]
Doing a bit of cleanup
