### ISSUE TITLE
Date ranger picker layout broken in iOS

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1654]
**Describe the bug**
In iOS <10.3, the date range presets and date inputs don't layout correctly since grid styles are not supported.

**To Reproduce**

1. Go to any report with a date picker.
2.  Open the date picker.
3.  Note layout issues with presets and date inputs.

**Expected behavior**
Expected the usual styling here.

**Screenshots**
<img width="405" alt="screen shot 2019-02-21 at 3 28 53 pm" src="https://user-images.githubusercontent.com/10561050/53151247-ab5c8780-35ed-11e9-9c2d-f1af1c637201.png">
<img width="411" alt="screen shot 2019-02-21 at 3 28 33 pm" src="https://user-images.githubusercontent.com/10561050/53151249-ab5c8780-35ed-11e9-941a-980beb15d8aa.png">

**Smartphone (please complete the following information):**

* OS: iOS 10.2
* Browser: Safari

**Comment by timmyc** [comment]
Closing as a won't fix.
