### ISSUE TITLE
Advanced filter remove button placement in iOS

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1655]
**Describe the bug**
In iOS <10.3 the remove button is incorrectly positioned (probably due to grid styles being used).  We might consider using flexbox or absolute positioning and padding here.

**To Reproduce**

1. Add an advanced filter in iOS 12.
2. Note the remove button position.

**Expected behavior**
Expected similar styling to other browsers.

**Screenshots**
<img width="406" alt="screen shot 2019-02-21 at 3 34 16 pm" src="https://user-images.githubusercontent.com/10561050/53151546-756bd300-35ee-11e9-91f0-ecfcb1482461.png">

**Smartphone (please complete the following information):**

* OS: iOS 10.2
* Browser: Safari

**Comment by timmyc** [comment]
Since we haven't had any user reports of these older mobile safari bugs, i'm going to close them out.
