### ISSUE TITLE
Analytics Copy Cleanup

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#1677]
As it stands, some of the data is labeled one way in one report, and another way in another report. The reality is not as bad as that last sentence sounds, it’s mostly situations where we have a label like “Orders” in one place and “Orders Count” in another. These labels should be as short and concise as possible, so in that case, “Orders” would be the preferred label.

This list should serve as a source of truth, if anyone has suggestions for relabeling, please provide feedback here. This list should be applied to all reports, and the dashboard. 

- **Gross Revenue (G. Revenue, G. Rev):**  All the money
- **Net Revenue (N. Revenue, N. Rev):**  All the money – Refunds – Coupons – Total Tax – Shipping
- **Orders**: A count of orders
- **Products Sold:** A count of products sold
- **Items Sold:** A count of individual items sold
- **Average Order Value (Avg. Order Value, AOV):** Net Revenue / Orders
- **Average Items Per Order (Avg. Items Per Order):** Items Sold / Orders
- **Refunds:** A monetary value for refunds issued
- **Refunded Orders:** A count of refunded orders
- **Coupons:** A monetary value for coupons used
- **Discounted Orders:** A count of orders that included at least one coupon
- **Total Tax:** A monetary value for Order Tax + Shipping Tax
- **Order Tax:** A monetary value for taxes collected on an order
- **Shipping Tax:** A monetary value for taxes collected on shipping charges
- **Shipping:** A monetary value for shipping charges
- **Downloads:** A count of downloaded products
- **Customers:** a count of people who have made a purchase and or registered an account with a store. Tracked by Billing email. (The new reports count all users of a store as a “Customer”, not just people who have register an account)
- **Total Spend:** The total amount a customer has spent at a store

In a convo with @timmyc - he had suggested making the labels driven by the API, similar to what we did in the the performance endpoint. That way we can update labels in one spot, and it _**magically**_ changes everywhere.

**Comment by dreiris** [comment]
- Just do a find/replace. 
- Assign David as PR reviewer
