### ISSUE TITLE
Incorrect coupon display

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-admin#1695]
**Describe the bug**
The orders report needs to be more clear about what "coupons" counts in the bottom information table.

**To Reproduce**

1. Place an order using a coupon - you'll need to add a coupon if you don't have a test coupon.
2. Go to the new Orders report
3. Take a look at the bottom row https://cloudup.com/cj6Pjc0paCk - That should be : R100 in coupons

**Expected behavior**
I would have expected a count of coupons used or the total coupon amount used.

**Screenshots**

https://cloudup.com/cj6Pjc0paCk

**Comment by joshuatf** [comment]
@warrendholmes I think that figure is meant to show the count of distinct coupons used.  Were you:

* Expecting to see the total number of coupons used (non-distinct)?
* Expecting clearer language (e.g., `100 unique coupons`)?
* Seeing a number that did not match your stats?

**Comment by warrendholmes** [comment]
@joshuatf I'm pretty sure it should be the total amount of coupon, in this case it should be ZAR 100. ZAR being South African rands.

**Comment by joshuatf** [comment]
@warrendholmes Sorry, you're correct.  I was looking at the coupons data store.  Agreed that this should include the currency for coupons in the summary . numbers.
