### ISSUE TITLE
Check definition of new/returning customer in segmentation

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#1713]
**Describe the bug**
When segmentation was implemented, the SQL code to count number of new and returning customers was not finalised yet, so I created this issue to check if segmentation SQL code is using a correct definition of new/returning customer consistent with the rest of REST API.

**Comment by timmyc** [comment]
@peterfabian @joshuatf I feel like this has already been taken care of, but wanted to see if either of you have any thoughts.

**Comment by peterfabian** [comment]
You are asking some tricky questions here, @timmyc :) Unfortunately I haven't been following this repo very closely after end of February, so not sure if this has been sorted out...

**Comment by timmyc** [comment]
🧹 tidying up.
