### ISSUE TITLE
Update Text Domain

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1735]
Background: p90Yrv-Ze-p2

Per the feedback from the .org review, we either need to change our slug name to `wc-admin`, or update the textdomain to `woocommerce-admin`.

This task would touch many files 😱 - and would cause conflicts in some open prs too. Any thoughts?

**Comment by jeffstieler** [comment]
Only open PRs that should conflict are https://github.com/woocommerce/wc-admin/pull/1750 and https://github.com/woocommerce/wc-admin/pull/1653
