### ISSUE TITLE
Add "Remind me later" ability to StoreAlert Component

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1756]
The original designs for StoreAlerts (#115) contain a "remind me later" action. 

<img width="1409" alt="screen shot 2019-03-05 at 3 17 26 pm" src="https://user-images.githubusercontent.com/689165/53905001-769cf700-4015-11e9-9041-10ff5df7db87.png">

The WC_Notes class looks like it has a date_reminder field and a way to resurface these later, but no UI or method exists so notes can easily expose the dropdown. There is also no way for specific notice to mark a notice as "snoozable". This might require a new db field. Finally, the REST API also needs updated to allow for filtering snoozed notes out. Right now the date field does nothing. Some of these might be good to handle if we are refactoring the note class a bit.

- [ ] `WC_Admin_Note` should gain a way of marking that a note should have a reminder.
- [ ] The `StoreAlert` component should output a dropdown containing options for reminding later.
- [ ] An action should be dispatched to update the note `date_reminder` field when selected.

@LevinMedia  What should the options be for the "remind me later" dropdown across these notes?

Note: Despite the screenshot, the historical processing note should not have the remind me later dropdown. Notices should have the option of showing it, and [according to Slack](https://a8c.slack.com/archives/C9K5T0XSP/p1552419050100300), we will use it in major update notices.

**Comment by LevinMedia** [comment]
@justinshreve 

Any time a "remind me later" shows up I think the defaults should be as follows:

- Later Today
- Tomorrow
- Next Week
- Next Month

In the future we may want to consider adding a custom date / time, but I don't think that's necessary at this point. 

cc: @jameskoster
