### ISSUE TITLE
Missing styles: preset / custom split button in the date range picker

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#1757]
**Describe the bug**
Lost our styling on the preset / custom split button in the date range picker

**To Reproduce**

1. on the latest version of master
2. visit any report
3. click the date range picker
4. note the split button for preset / custom ranges is no longer styled

**Screenshots**

<img width="574" alt="screen shot 2019-03-06 at 3 11 47 pm" src="https://user-images.githubusercontent.com/4500952/53920655-aef70200-4022-11e9-9e23-95f31e9267e8.png">

Was able to reproduce in Desktop chrome, Safari and Firefox, no other browsers tested

similar to, but different than #1654

**Comment by psealock** [comment]
Gutenberg moved classnames around in 5.1 and this was the fix https://github.com/woocommerce/wc-admin/pull/1717.

Perhaps it was premature because if you don't have the latest Gutenberg, this is what you'll see. I upgraded wp core to 5.2 and it doesn't have the GB change.
