### ISSUE TITLE
Android: bad UI when focusing inputs in date range picker

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1767]
**To Reproduce**
1. Go to any report.
2. Open the date picker.
3. Switch to the _Custom tab_.
4. Focus on an input field.
5. Notice the UI looks bad.

**Screenshots**
<img src="https://user-images.githubusercontent.com/3616980/54047953-b6f8a280-41d8-11e9-8389-593b187adfaf.png" width="300" />

**Smartphone:**
* Device: LG G6
* OS: Android 8.0
* Browser: Firefox 67.0a1 & Chrome

**Comment by Aljullu** [comment]
@LevinMedia & @josemarques any idea how we can improve this? Tapping on the input fields of the date picker opens the keyboard, which completely breaks the layout.

Should we make them un-focusable on mobile? Or do you have a better idea?

**Comment by LevinMedia** [comment]
@Aljullu  This seems to only be affecting android, at least the version you reported above... I tested on iOS safari and chrome, and it didn't break the layout. 

that said... 

when focusing on any input on a mobile device, (regardless of whether it was the date range picker) the screen zooms in a bit. Perhaps it could be related? I'd prefer if the screen wasn't able to pinch or zoom on a mobile device. Maybe if the zoom is removed, the bug you reported will resolve itself?

![IMG_5703](https://user-images.githubusercontent.com/4500952/55340970-9ed41600-545a-11e9-9583-be7eb9bfd272.jpeg)

^ zoomed UI on focus

**Comment by Aljullu** [comment]
Thanks for the input @LevinMedia! I think those two issues are not related. I created a PR that will fix the layout on Android (#1996), but it shouldn't change the zoom behavior in iOS. In case we do want to remove it anyway, probably we should create a separate issue.
