### ISSUE TITLE
Variations Search: Results not displayed

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#1773]
**Describe the bug**

When looking at Comparison of Variations in the Product Report, the search box doesn't show results.

**To Reproduce**

1. Show > Single Product > Choose variable product.
2. Enter Comparison mode and search for a known name of a variation, or simply the product name.
3. See no results appear in the dropdown. Open network requests and confirm that `/products/<id>/variations?search=...` returns results.

**Expected behavior**

I'd expect the search dropdown to be populated with those results.

**Screenshots**

![Screen Shot 2019-03-11 at 4 28 41 PM](https://user-images.githubusercontent.com/1922453/54098894-68871600-441b-11e9-907e-01cad4ed02a5.png)

**Comment by Aljullu** [comment]
Autocompleter seems to be working fine for me:
![image](https://user-images.githubusercontent.com/3616980/54124574-120ddd80-4403-11e9-91f2-2fae8d42b7aa.png)

I agree, however, it would be nice to include product's name in the variation label. That could be done passing down a prop with the product name or including the product name in the variations endpoint.

**Comment by joshuatf** [comment]
I believe this is related to https://github.com/woocommerce/wc-admin/issues/1739
