### ISSUE TITLE
Variation Names Incorrect in Chart and Table

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#1774]
**Describe the bug**

Variation names are rendering as just the Product Name, if at all

**To Reproduce**

1. Create an order with variations or use a previously recorded order and go to step 4.
1. Create a product with variations (I've only tested with ones I created, not wc-smooth-generator).
2. Create an order with one or more variations.
4. Products Report > Show > Single Product > your variable product.
5. See the variation names incorrectly rendered in the Chart and Table.

**Expected behavior**

I expect to see `Belt - green, large buckle`.

**Screenshots**

![Screen Shot 2019-03-11 at 4 36 57 PM](https://user-images.githubusercontent.com/1922453/54099130-9882e900-441c-11e9-91d0-18bfcee852df.png)

**Additional context**

Variations created manually, not with wc-smooth-generator

**Comment by psealock** [comment]
I just created a brand new variable product with variation and an order. Names are being rendered correctly. Perhaps there is an issue with my local setup.

**Comment by Aljullu** [comment]
@psealock do you think what you are seeing here is the same as #1044?

**Comment by psealock** [comment]
I don't think thats the same, but I am going to close this because I can only reproduce with wc-smooth-generator created variable products, which is an issue already noted.
