### ISSUE TITLE
Component: Inbox Card Read

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#178]
Child issue of #176 
**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/console/14671248/305076999/preview)

![image](https://user-images.githubusercontent.com/22080/42402854-23b5fec6-8132-11e8-8643-13942d8a01b0.png)

See design link above for mobile + desktop viewport styling/spacing

Since this issue is quite small feature wise ( not showing the un-read indicator ), lets also use this issue to add in the functionality to mark an inbox message as read. Per the designs an inbox message is "read" as soon as it is shown in the viewport, or the action is taken.

**Comment by ryelle** [comment]
@timmyc As we don't have a notifications API yet (to persist that a notice has been seen), I'm assuming the result of this issue should be a callback that fires based on this logic:

- If a notice has an action, trigger callback when action button is clicked
- If a notice does not have an action, trigger callback when the action is within the viewport

Does that sound right, or should this wait for an API backend?

**Comment by ryelle** [comment]
Hm, just saw "‘Read’ status will be calculated client side using dates, and will use the existing users API to store any data relevant to the current user as user meta." – I think we still have a conflict around how this will work, since I assumed `read`/`unread` would be triggered by the API's `status` property.

> To handle this we will track the last ‘date’ read up to in user meta via the existing users REST API endpoint. Any notices added since the last ‘read’ date will be marked as such. It is assumed that the dashboard app will be aware of the current user ID.

Assuming the last read date would be "the last time the user opened the Inbox", we can POST a setting to the user's options when they open each tab, but then we'll also need to read from that endpoint to get the "last opened" date each time they open a tab so we can update the read state of all messages.

**Comment by jameskoster** [comment]
I'm trying to better understand the problem here so that we can work out the right solution.

Are we saying that the issue is the persistence of the "unread" status between tab views?

If it would be simpler to just say _every time the Inbox is opened, mark all items as read_, I think that would be fine.

> Specifically thinking of if a user has many items in the inbox, and say the first page of items returned from the API will not fit in the viewport... or if viewing on a mobile browser.

The purpose of the "unread" styling is to indicate which content the user should concentrate on. IE keep scrolling until you see no more red dots.

**Comment by timmyc** [comment]
> I'm trying to better understand the problem here so that we can work out the right solution.

Sorry, here is kind of what I'm fearing is the problem. The inbox is designed to show the newest items up top ( i.e. Today ), and older items scrolling below. We intend to track "read" status of inbox items by setting a timestamp on the user meta of the last time they viewed / opened the inbox tab and compare that timestamp to the date/time an inbox item/notif was added to determine if it has been "read".

So consider a scenario where there are more notifs that would be considered "unread" based on that criteria, than we can display in the viewport. Potentially users might actually only see the newer notifs that are above-the-fold, and never actually view ones from prior days. But since we then record the timestamp of the inbox tab being opened as all notifs prior to that time as being "read" they could/would likely not actually in the viewport.

@ryelle does that align with your concerns?

**Comment by jameskoster** [comment]
Since the unread items have styling to differentiate them, I'd imagine folks would simply keep scrolling until they've seen them all. I'm not too worried about folks missing items below the fold - that seems unlikely to me.

**Comment by timmyc** [comment]
> If this is going to be a big issue

So true, we could be creating issues out of nothing at this point. @ryelle so do you think we are okay moving forward or do you have other concerns i have yet to point out?

**Comment by timmyc** [comment]
Yep that all sounds pretty spot on to me @ryelle 

> When the user opens the inbox, we need to request the list of items, and the user meta, then also post back the new time (3x API calls each time the inbox is opened)

Yeah that is kind of a bummer about the 3 calls - we could consider updating the timestamp in user meta when the component un-mounts. But that could also result in some miss-match of if notices were actually "read".

> The notice object's status property is not actually related to read/unread

Correct that is my understanding too... and from @mikejolley's spec post ( p7bje6-13D-p2 ):

> status (?) – naming tbd – could also just be whether actioned or not.

Almost feels like that field should just be a `bool` for actioned. /cc @claudiosanches

**Comment by jameskoster** [comment]
> What about informational notices that don't have actions? It would seem strange to me to have some greyed-out notices and some regular notices in the list

Good point. It would probably make sense to apply the `actioned` styled to info notices once they're read. IE grey bg. I'll update the Sketch/Invision docs accordingly.

**Comment by psealock** [comment]
This is done in the new inbox.
