### ISSUE TITLE
Unused product category filter in API

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1789]
It looks like `get_included_products_array()` is no longer being used after [removing redundant report filters](https://github.com/woocommerce/wc-admin/issues/1678).

Should we remove this or leave it in the event we need it in the future?

**Comment by Aljullu** [comment]
That method seems to be used in [class-wc-admin-reports-variations-data-store.php](https://github.com/woocommerce/wc-admin/blob/master/includes/data-stores/class-wc-admin-reports-variations-data-store.php#L222) and [class-wc-admin-reports-products-data-store.php](https://github.com/woocommerce/wc-admin/blob/master/includes/data-stores/class-wc-admin-reports-products-data-store.php#L285). Are we planning to remove it from there?

**Comment by joshuatf** [comment]
Whoops, I phrased this incorrectly.  I was referring to the categories sections of `get_included_products_array()` as it pertains to the products data store since we no longer filter by categories.

```php
		if ( isset( $query_args['categories'] ) && is_array( $query_args['categories'] ) && count( $query_args['categories'] ) > 0 ) {
			$included_products = $this->get_products_by_cat_ids( $query_args['categories'] );
			$included_products = wc_list_pluck( $included_products, 'get_id' );
		}
```

However, that bit can still be used in the categories report and I don't think removing the category params from the product data store alone really reduces that much overhead so I'll go ahead and close this.
