### ISSUE TITLE
REST API: Issue when sorting the variation products via SKU in products analytics tabs in single product

### ISSUE THREAD

**Issue by ronakganatra9** [woocommerce/woocommerce-admin#1801]
**Describe the bug**
When We have multiple orders of the same product with different variation and that both products have different SKUs at that time there is a bug in REST API so when We click on sort by SKU on the product single page on analytics at that time it gives 400 error because there is not SKU parameter in REST API.
filter=single_product page.

File wc-includes/api/class-wc-admin-rest-reports-variations-controller.php

Line 287:
$params['orderby']       = array(
			'description'       => __( 'Sort collection by object attribute.', 'wc-admin' ),
			'type'              => 'string',
			'default'           => 'date',
			'enum'              => array(
				'date',
				'net_revenue',
				'orders_count',
				'items_sold',
			),
			'validate_callback' => 'rest_validate_request_arg',
		);

It does not take sku option from order by params so it gives 400 error in the rest API response.
![wc-admin](https://user-images.githubusercontent.com/24435113/54335072-dca90000-464d-11e9-8427-de42006f77cf.png)

Also, the query is not set for the filter by SKU in variation in the data store files.

**To Reproduce**

1. Create a product with 2 or more variation or choose the product which has 2 or more variations.
2. Assign different SKUs to all variants
2. Place different orders of that same product with different variations.
3. Go, WooCommerce admin on analytics menu and click on products
4. Where you will see the product name(which you have ordered with different variation) and Item sold columns 
![screenshot-localhost-2019 03 14-12-11-09](https://user-images.githubusercontent.com/24435113/54344301-8d22fe00-4666-11e9-9fb1-3dec859c2192.png)

5. Click on that product
6. You will be able to see all products with variation
Like
![screenshot-localhost-2019 03 14-14-37-46](https://user-images.githubusercontent.com/24435113/54344390-c22f5080-4666-11e9-9841-85808132b24e.png)

7. Now you will be able to see both variations have different SKUs.
8. Click on SKU column to sort it.
9. You will see the following error,
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/24435113/54344517-0b7fa000-4667-11e9-8775-3dd3dfa99e3c.gif)

10. The columns will become empty and in REST API response it wil return 400 error.
**Expected behavior**
It should Filter according to SKU in Ascending, descending flow.

**Screenshots**
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/24435113/54344517-0b7fa000-4667-11e9-8775-3dd3dfa99e3c.gif)

**Desktop (please complete the following information):**

* OS: Ubuntu
* Browser Chrome

**Additional context**
I have fixed it and attached a PR on it.

**Comment by jeffstieler** [comment]
Hi @ronakganatra9 thank for the bug report.

I'm having trouble reproducing this.. as far as I can tell, SKU isn't a sortable column in the Variations table. See: https://github.com/woocommerce/woocommerce-admin/blob/master/client/analytics/report/products/table-variations.js#L39-L43

**Comment by ronakganatra9** [comment]
Hi @jeffstieler ,

Thanks for testing. In 0.8.0 Build there is an SKU was sortable so I found that bug and fixed it. But after checking here I have seen that someone from the team has removed isSortable. So, We can count it as an enhancement or feature if we can.

Let me know your thoughts on the same.

Thanks,
Ronak
