### ISSUE TITLE
When loading a report and switching to another tab immediately, the report never finishes loading

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1814]
**To Reproduce**
1. Go to any report.
2. Refresh the page and as fast as you can, switch to another tab.
3. Once the report tab has finished loading, switch back to it.
4. Notice it never finishes loading.

**Screenshots**
_(First tab is `wc-admin`, second tab is `wordpress.org`)_
![loading](https://user-images.githubusercontent.com/3616980/54459041-ce4e0780-4765-11e9-8039-74d6300a88ce.gif)

**Comment by jeffstieler** [comment]
Might have been introduced in https://github.com/woocommerce/woocommerce-admin/pull/1732.
