### ISSUE TITLE
Activity Panel: Persist Inbox Last View Time

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1817]
Child Task of #176

The designs of he Activity Panel Inbox call for an "unread" indicator to be shown in two places, the first being in the Inbox Panel Launcher itself:

<img width="525" alt="unread-notices" src="https://user-images.githubusercontent.com/22080/54482903-b333d400-4807-11e9-8cb6-449f3e8476e4.png">

And the second spot, which you can not see in the current implementation is on each inbox notif card, from the [invision design](https://automattic.invisionapp.com/d/main#/console/14671248/305076999/preview):

![image](https://user-images.githubusercontent.com/22080/54482908-cf377580-4807-11e9-9344-43f15f2e4baf.png)

It has been quite sometime, but we have had some discussion in the past around how the "read state" should be tracked. I believe what we finally landed on ( need to find a citation of this but /cc @justinshreve @jameskoster @allendav for any other memories ) was:

- We should persist a timestamp, likely on user meta, that records the last time the Inbox Panel is opened.
- This timestamp, could then be utilized to properly set the `unread` prop on the [Inbox Panel tab](https://github.com/woocommerce/woocommerce-admin/blob/master/client/header/activity-panel/index.js#L99) by comparing that time against the `date_created` of admin notes.
- Likewise, when the inbox is opened, ActivityCard's could then have their `unread` [prop](https://github.com/woocommerce/woocommerce-admin/blob/master/client/header/activity-panel/activity-card/index.js#L55) set based upon the "last viewed inbox" timestamp.

__Questions / Thoughts__
- How do we handle the event where the number of inbox notifs shown in the inbox can not all be viewed without scrolling? Do we need to listen to scroll events and set the last viewed timestamp based upon the oldest card that gets scrolled into view?
- If I recall, we also talked about the notion of - even if a card is shown in the view, does that really mean it has been read? Since the notes schema is not setup in such a way that we can track reads-per-user, I believe we felt the time-based unread approach was okay. But just wanted to verify that.
- Since all Activity Panels need to have an `unread` prop set, should we consider creating a REST endpoint specific to this bit of user data? I imagine that would be helpful to support a similar interface within the core mobile apps eventually... and would prevent the need of doing multiple API requests ( Inbox, Orders, Reviews, Stock ) to properly display the unread status.

**Comment by joshuatf** [comment]
>How do we handle the event where the number of inbox notifs shown in the inbox can not all be viewed without scrolling? Do we need to listen to scroll events and set the last viewed timestamp based upon the oldest card that gets scrolled into view?

Personally, I would expect that if it was opened, all would be marked as read, even if not in view.  I **think** most notification behavior uses the same concept and doesn't tack individually reads like emails, but I supposed "Inbox" is somewhat of a hybrid.

>If I recall, we also talked about the notion of - even if a card is shown in the view, does that really mean it has been read? Since the notes schema is not setup in such a way that we can track reads-per-user, I believe we felt the time-based unread approach was okay. But just wanted to verify that.

I think time-based is a great way of handling this, provided we don't need to mark individual items read.

>Since all Activity Panels need to have an unread prop set, should we consider creating a REST endpoint specific to this bit of user data? I imagine that would be helpful to support a similar interface within the core mobile apps eventually... and would prevent the need of doing multiple API requests ( Inbox, Orders, Reviews, Stock ) to properly display the unread status.

I think if we're just talking about read/unread status, a timestamp in the user meta should be enough, which we can access through the WP REST API in a single call unless I'm misunderstanding this one.
