### ISSUE TITLE
Activity Panel: z-index conflict with Editor

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1829]
**Describe the bug**
When editing a product, if an activity panel is opened, there is a z-index conflict that has the editor/tinymce header floating above the Activity Panel

![bug-z-index-product-editor](https://user-images.githubusercontent.com/22080/54554650-35400c00-4972-11e9-8565-15f1eb318ed2.png)

**To Reproduce**

1. Edit a product
2. Expand any Activity Panel

**Comment by joshuatf** [comment]
I'm going to grab this one as it appears to be a slightly more complicated Webpack dependency issue.
