### ISSUE TITLE
Task: Move all Note PHP files to sub-folder

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1830]
As we plan to ramp-up development of additional notes to populate the inbox, I'm thinking we should get things a bit more organized in note-land. 

Currently all note-related logic ( outside of data-store and API files ) lives inside the root of the `/includes` folder. To keep things organized, I'm proposing we create a new `/includes/notes` folder and move all related files there.

**Comment by ronakganatra9** [comment]
Should we also include reports in separate reports folder like /includes/reports folder?

**Comment by timmyc** [comment]
> Should we also include reports in separate reports folder like /includes/reports folder?

I don't think we need to move those yet.
