### ISSUE TITLE
Notes: Order Milestone Notifications

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1831]
Somewhat related to, but not totally blocked by #1830 

To build upon the new inbox in WooCommerce Admin, we have set up a list of [new inbox notifs to build out](https://docs.google.com/spreadsheets/d/1iBcjWbQtN1DNZmvCmB4zmgGxiTL99_cJgeC2Ew2FvJE/edit#gid=0) ( Private Spreadsheet ). For this enhancement, we will be implementing a number of "Order Milestone" notifications, which fall into three different notifications as defined in the spreadsheet linked above.

Since they are all based upon the number of orders processed, it seems like they should be able to live within the same logic - so I've grouped them together into this one issue.

- First Order
- 10 orders
- 100, 250, 500, 1k, 5k, 10k, 50k, 100k orders

The message titles, copy, and associated actions are all listed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1iBcjWbQtN1DNZmvCmB4zmgGxiTL99_cJgeC2Ew2FvJE/edit#gid=0).

**Comment by ronakganatra9** [comment]
Hi @timmyc ,

Can I implement customer milestone notifications same as order Milestone?

- First Customer
- 10 Customers
- 100,250,500, 1k customers

Let me know your thoughts on the same.

Thanks & Regards,
Ronak

**Comment by ronakganatra9** [comment]
Hi Team,

I am waiting for your thoughts on my above comment.

Can I implement customer milestone notifications same as order Milestone?

First Customer
10 Customers
100,250,500, 1k customers
Let me know your thoughts on the same.

Thanks & Regards,
Ronak

**Comment by timmyc** [comment]
Hey @ronakganatra9 !
Thanks for your inquiries here. Right now we are currently working on the items listed in the Sprint 15 column on our project board https://github.com/orgs/woocommerce/projects/2

I think the customer milestone is an interesting idea though... What do you think about trying to build it as an extension/plugin? That would be a great way to display the concept, but also would immensely help the WooCommerce Admin project here by showing how to add in custom milestone logic via an extension/plugin.

If you'd like to chat more about this idea, give me a ping on slack, I'd be happy to discuss it further.

**Comment by ronakganatra9** [comment]
Thank you @timmyc for your reply. I have messaged you on slack regarding the same.
