### ISSUE TITLE
Notes: Store Anniversary

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1832]
Somewhat related to, but not totally blocked by #1830 

To build upon the new inbox in WooCommerce Admin, we have set up a list of [new inbox notifs to build out](https://docs.google.com/spreadsheets/d/1iBcjWbQtN1DNZmvCmB4zmgGxiTL99_cJgeC2Ew2FvJE/edit#gid=0) ( Private Spreadsheet ). For this note, we are seeking to implement the Store Anniversary notification that gets sent out once per year, on the anniversary of a store's first order.

Verbiage and details can be found in the [spreadsheet](https://docs.google.com/spreadsheets/d/1iBcjWbQtN1DNZmvCmB4zmgGxiTL99_cJgeC2Ew2FvJE/edit#gid=0) but quickly the idea is to have notes sent:

- Six months after their first order
- Then annually every year on the anniversary of the first order.

A few random thoughts/ideas/questions:
- Could this be chained to the order milestone? #1831 perhaps when that is triggered, it could perhaps `as_schedule_single_action` for the six month inbox note, and a year from the date of the first order.
- What happens if the first order is deleted? :trollface: Do we reset the anniversary date?

**Comment by psealock** [comment]
I think we've satisfied this issue. @timmyc to double check, but I'm closing out anyways.
