### ISSUE TITLE
Product Search: Multiple values for variable products in results

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#1834]
**Describe the bug**

When searching for a product, a product with variations returns one duplicate entry for each variation.

![Screen Shot 2019-03-19 at 1 55 43 PM](https://user-images.githubusercontent.com/1922453/54574430-22523800-4a55-11e9-9069-648148c7d96e.png)

This results in a bad UI

![Screen Shot 2019-03-19 at 1 55 17 PM](https://user-images.githubusercontent.com/1922453/54574436-2d0ccd00-4a55-11e9-912e-1975e6f39377.png)

**To Reproduce**

1. Create/choose a variable product with multiple variations.
2. Product Report > Show > Single Product.
3. Search for the product in question.
4. See the duplicate results in the dropdown and network request.

**Comment by joshuatf** [comment]
@psealock I wasn't able to reproduce this issue, but I do remember a similar issue with variations when working on the search param for product controllers.

The solution (also followed by core) was to [group by ID](https://github.com/woocommerce/woocommerce-admin/blob/627cea3059a433e08e46b30d477de177971fd3c6/includes/api/class-wc-admin-rest-product-variations-controller.php#L82).  If you're seeing this for the parent product, maybe we should move this function in the products controller so both products and variations can take advantage of it.
