### ISSUE TITLE
Travis integration is broken if branch name contains a hash (#)

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1843]
In `./install-wp-tests.sh` we are fetching a .zip file using the branch name to generate the URL, but if it contains a hash (`#`) it should be escaped to (`%23`).

This could be noted in this PR: #1842, where Travis was failing even though there were no errors.

**Comment by ronakganatra9** [comment]
I was also confused that why it blocking my changes if there is not any error.

**Comment by Aljullu** [comment]
Right, we even introduced an issue without noticing (#1845). But all should be fixed once that PR and (#1844) get merged. :slightly_smiling_face:
