### ISSUE TITLE
Category Report Data Discrepancies

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#1847]
**Describe the bug**
The summary numbers below the table aren't affected by the query when comparing categories, resulting in a discrepancy with the other totals on the page. 

**To Reproduce**

1. Go to the category report
2. Compare a number of categories
3. Note the summary numbers at the bottom of the table do not match with other totals on the page. 

**Expected behavior**
The numbers should match.  

**Screenshots**

![](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fd1c0hjomoutdrw.cloudfront.net%2Fitems%2F0Y162Y3e2p0Y01033X3U%2F%255B3a021c3b8bb7e5856380d5b5c7932140%255D_Screen%2BShot%2B2019-03-19%2Bat%2B2.48.50%2BPM.png)

**Comment by psealock** [comment]
Closed via #1873
