### ISSUE TITLE
Activity Panel: empty state in reviews panel

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1869]
Noted by @joshuatf [here](https://github.com/woocommerce/woocommerce-admin/pull/1860#pullrequestreview-217103100):
> On a side note, are there plans for adding content here when no reviews exist? Maybe a small message like `You have no product reviews` yet.?

**To Reproduce**

1. In a store with no reviews.
2. Open the _Reviews_ panel.
3. Notice the panel is completely empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/3616980/54747741-fdce9b00-4bcf-11e9-8cc0-cc880233db7a.png)

**Comment by josemarques** [comment]
@Aljullu here's the design for the empty state: 

![Reviews = 0](https://user-images.githubusercontent.com/57050/55250033-4b3caf00-5245-11e9-9048-0dcdd0023eaa.png)
When no products have been reviewed we invite the merchant to learn best products of managing reviews. The CTA links to this page: https://href.li/?https://woocommerce.com/posts/reviews-woocommerce-best-practices/

![Reviews to moderate = 0   Orders  = 1](https://user-images.githubusercontent.com/57050/55250035-4b3caf00-5245-11e9-91b8-42d3439b7a4e.png)
When there are no reviews to moderate and the last review was submitted in less that 30 days.


![Reviews to moderate = 0 | Orders  = 1 | Last review date   30](https://user-images.githubusercontent.com/57050/55250036-4b3caf00-5245-11e9-9ed4-27f75450073c.png)

When there are no reviews to moderate and the last review was submitted in more that 30 days. The CTA links to this page: https://href.li/?https://woocommerce.com/posts/reviews-woocommerce-best-practices/

More context here: https://wp.me/p6riRB-4kT-p2

**Comment by timmyc** [comment]
Sweeping through issues left in the Sprint 16 backlog and looks like this doesn't have a PR assigned to it out so clearing out the Assignee column @Aljullu - but feel free to pick it back up if you'd like

**Comment by Aljullu** [comment]
@timmyc sorry for having this on hold for so long! I was waiting for the discussion in p6riRB-4kT-p2 comments to be resolved first, but it probably makes sense to create a PR with what I have for now and create a follow-up if we want to change which reviews are displayed in the panel.

The new PR can be found here: #2124.
