### ISSUE TITLE
Component: Inbox Card Actioned

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#187]
Child issue of #176 
**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/console/14671248/305076999/preview)
**API Post**: p7bje6-13D-p2

![image](https://user-images.githubusercontent.com/22080/42540921-3afe48d8-8455-11e8-974c-53aeaef5ee28.png)

See design link above for mobile + desktop viewport styling/spacing

This issue should cover creation of the visual state of a inbox item that has been actioned, and also the marking of an item as actioned when the action button is clicked on.

**Comment by ryelle** [comment]
@timmyc I have similar confusion here as I do with the read/unread status in #178, and TBH I don't really know how this is different
