### ISSUE TITLE
Onboarding - Profile Wizard: Extensibility

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1891]
We should aim to make the profile wizard extendable. This includes both the backend and frontend. On the REST API side, an extension should be able to register new fields for saving data. On the frontend, we can use `applyFilters` like we do for reports, to allow extensions to register new steps or remove existing steps.

This task is complete once we have the necessary filters/hooks, and have an example extension.

[Master Thread](https://wp.me/p90Yrv-10i) | [Designs](https://wp.me/p6riRB-416)

**Comment by warrendholmes** [comment]
What's the use case for this?

**Comment by justinshreve** [comment]
> What's the use case for this?

Partner hosts (like WordPress.com) being able to hook into the OBW. Think bundling extensions, and wanting additional information around that during setup.

See #comment-4874 on p6riRB-416-p2.
