### ISSUE TITLE
Onboarding - Profile Wizard: Pass profile data back to WooCommerce.com

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1893]
Per the comments in the design thread, we would like to be able to pass data via the WooCommerce helper back to WooCommerce.com. I believe this is a different need from tracks info, since we want to associate the answers with a connected site/user in marketing, etc.

This task also involves coordinating with Matty/Alpha on the WooCommerce.com side of things.

[Master Thread](https://wp.me/p90Yrv-10i) | [Designs](https://wp.me/p6riRB-4rG)

**Comment by joshuatf** [comment]
@mattyza Do you know what info is needed on the wccom side?  Should we send over the entire profile item data object for use on wccom?

And is there an endpoint that currently exists to send this data?  This information may get a little lengthy for URL params and may be better sent in the body of the page as JSON.

**Comment by mattyza** [comment]
@joshuatf - I've looped you in on a related discussion about the API side of this, here: https://github.com/Automattic/woocommerce.com/issues/6633#issuecomment-566541930

**Comment by joshuatf** [comment]
https://github.com/Automattic/woocommerce.com/pull/6895 unblocks this issue and allows us to send this data to wccom.
