### ISSUE TITLE
Order Status filter: <select> is not vertically aligned when Gutenberg is installed

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1895]
**To Reproduce**
1. Install Gutenberg (https://wordpress.org/plugins/gutenberg/) — tested with 5.2.0 and 5.3.0.
2. Go to the _Orders_ report.
3. Open the _Advanced Filters_.
4. Add an _Order Status_ filter.
5. Notice the select is not correctly aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/3616980/54840318-05279e80-4ccd-11e9-9b33-5506d9cc19da.png)

**Comment by dinhtungdu** [comment]
@Aljullu what is the browser and OS you're testing on?
I tested with current `master` on macOS 10.14.4, Chrome/Firefox/Safari, and none of them has this issue.

Test result on Chrome:
![](https://image.prntscr.com/image/g05yMDc_RpeVU6DENH28ug.png)

Firefox:
![](https://image.prntscr.com/image/eyUsQgK9SJeY1nnqbk76zw.png)

Safari:
![](https://image.prntscr.com/image/jx0HCF_LSualOV0PR93ICw.png)

**Comment by Aljullu** [comment]
@dinhtungdu thanks for testing it! Which version of WooCommerce Admin are you using?

I could reproduce it both in Firefox and Chrome in Fedora (GNU/Linux). But I tested with BrowserStack and could reproduce it also in Edge (Windows 10) and Safari 11 (Mac OS High Sierra):
![image](https://user-images.githubusercontent.com/3616980/55185003-ba59cb00-5193-11e9-94a3-923bfebf917a.png)

**Comment by dinhtungdu** [comment]
@Aljullu I tested with current master branch. I will try BrowserStack as you suggested.

**Comment by Aljullu** [comment]
@dinhtungdu thanks for the input! I was taking a deeper look at this today. It looks like the issue is caused by Gutenberg. When the plugin is installed, it adds a `margin-bottom` to the select. Deactivating Gutenberg fixes the issue.

I updated the issue title and description.
