### ISSUE TITLE
Onboarding - Task List: Levels & Tasks REST API

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1897]
This task involves creating a set of REST API endpoints that define levels, tasks, and subtasks for the user to complete during setup. The details below are my current plans on how I think it should work so it can be extendable, but still power the flows described in the designs. This issue may be broken down into sub-issues in the future, or handled in multiple PRs.

Levels, tasks, and subtasks should be definable via WordPress hooks & filters. Levels and tasks are described in the [task list/home screen thread](https://wp.me/p6riRB-44u). An example for subtasks can be seen in the [add products thread](https://wp.me/p6riRB-45C).

Here are the REST API endpoints that I think are necessary:
```
GET /onboarding/levels - Gets a list of valid levels.
GET /onboarding/tasks - Get a list of valid tasks for the provided `level` query parameter. Contains a list of subtasks for each task.
PUT /onboarding/tasks - Mark a task or subtask as completed. Can accept multiple tasks and subtasks IDs.
```

Below are the fields I think will be necessary to power this, and should be registered via PHP:

Level:
```
slug: A slug for this level.
tasks: An array of task slugs that should be contained in the level.
```

Task:
```
slug: A slug for this task. Extensions should namespace.
label: Label for the task.
description: Description for the task.
illustration: An illustration to be used in the task display.
status: The current status of the task (pulled from the table).
is_visible_conditional: A boolean describing whether the current task should be shown. This value should be filterable, so different combinations of settings can set the state. Example: Checking whether the business is already selling elsewhere and conditionally showing a task to use the same payment provider.
in_progress_conditional: A boolean describing whether a task has been started but is incomplete.
is_completed_conditional: A boolean describing whether the current task is completed. This value should be filterable, so different combinations of settings can set the state. Example: A payment method has been configured and setup.
```

Subtask.
```
slug: A slug for this task.
label: Label for the task.
description: Description for the task.
actions: An array of simple actions that can be completed via the subtask. These can contain a label, display_type (primary, secondary, link) action_type (link, or handler) target (URL or handler - see #XXXX for details about handlers). mark_completed This should be another field attached to actions as a boolean describing if this task should be marked as completed immediately after clicking.
status: The current status of the task (pulled from the table).
is_visible_conditional: If the subtask is visible. Example: The profile step was skipped, so we show different product creation steps.
is_completed_conditional: If the subtask is completed.
```

The first time a task or subtask is loaded via the REST API, entries should be added in the `wp_wc_task_status` table detailed below. Extensions/flows are then responsible for clearing the status if that an update makes change to the logic and want to enable their task again.

See the design thread for more details about levels and tasks.

I would like a quick way to get the number of uncompleted / completed tasks without having to do a bunch of querying, checking of settings, etc. I think it would be useful to introduce a table for tracking tasks status. In the table below `slug` would contain either the task slug, or the task slug and subtask slug. Example :`add-products`, or `add-products/purchase-extension`.  Status would contain `visible`, `hidden`, `in-progress`, `skipped`, and `completed`.

```
CREATE TABLE `wp_wc_task_status` (
  `task_log_id` bigint(20) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
)
```

Using this table, we can figure out if setup is complete by seeing if there are `visible` and `in-progress` tasks.

We should introduce a method like  `maybe_mark_task_completed` that allows us to take the conditional defined in the task or subtask, and update the database if all conditions are met.

Finally, we should have a REST API endpoint that can also kick-off the `maybe_mark_task_completed` method. It should accept multiple task names.

[Designs](https://wp.me/p6riRB-44u)

**Comment by joshuatf** [comment]
@justinshreve What do you think about introducing an `is_required` boolean to the task object?

In p6riRB-44u-p2#comment-5011 there's a discussion around how to "complete" all tasks so this page no longer shows.

>With the exception of the store customization task it’s not actually possible to launch a store unless all tasks are complete. So there wouldn’t be anything else to display here anyway. 

With an `is_required` boolean we can check that all required tasks are complete before considering the onboarding complete.  Thoughts?

**Comment by justinshreve** [comment]
@joshuatf Thanks for catching that comment there. I agree adding a `is_required` boolean makes sense.
