### ISSUE TITLE
gutenberg_get_jed_locale_data() is deprecated

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1916]
**To Reproduce**
1. Go to any page and view the page source (<kbd>Ctrl</kbd>+<kbd>U</kbd>).
2. See there is a notice saying:
> **Notice**:  gutenberg_get_jed_locale_data is **deprecated** since version 5.2.0 with no alternative available.

See https://github.com/WordPress/gutenberg/pull/12559 for more details.

**Comment by psealock** [comment]
This looks like a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/1859

**Comment by Aljullu** [comment]
It is! Thanks @psealock.
