### ISSUE TITLE
Onboarding: Admin notes and notices interrupt layout

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1937]
**Describe the bug**
On all onboarding routes, we might consider hiding notes and notices that dominate the page.  I think these can be safely turned off during onboarding much like the previous OBW.

**To Reproduce**

1. Make sure you have notes or notices.
2. Visit the dashboard with one of the open onboarding PRs.
3. Note the notices.

**Expected behavior**
Expected no notices or distractions on these pages.

**Screenshots**
<img width="1456" alt="Screen Shot 2019-03-28 at 12 28 40 PM" src="https://user-images.githubusercontent.com/10561050/55130349-8495f180-5155-11e9-887d-721058c4033f.png">

**Comment by jeffstieler** [comment]
😂 🐮

**Comment by justinshreve** [comment]
https://github.com/woocommerce/woocommerce-admin/pull/1933#pullrequestreview-234484305

**Comment by joshuatf** [comment]
One small note on this - the issue noted in #1933 is for the layout itself since the default padding does not center content (even without notices), but we can toss this fix in with the notices PR to make things easier.
