### ISSUE TITLE
Reduce the number of performance indicators, charts, and leaderboards on the Dashboard

### ISSUE THREAD

**Issue by josemarques** [woocommerce/woocommerce-admin#1950]
The Dashboard is currently displaying 12 performance indicators and all 14 available charts and 3 leaderboards. This a bit overwhelming upon first impression.

I synced with @LevinMedia and we got to this selection:

Performance Indicators:
- Gross Revenue
- Net revenue
- Amount of Orders
- Average Order Value
- Number of Items Sold
- Total of Refunds

Charts: 
- Net Revenue
- Orders

Leaderboards:
- Top products
- Top categories

**Comment by joshuatf** [comment]
@josemarques Did you want to remove these permanently or hide all others not listed by default, allowing the remainder to be toggled on/off?

**Comment by josemarques** [comment]
@joshuatf sorry for not being clear, the list above are the options to be toggled on by default. Nothing should be removed :).

**Comment by joshuatf** [comment]
@josemarques No worries- figured that was the case, but just wanted to double check.  Thanks for clarifying 😄
