### ISSUE TITLE
Dec and Jan are overlayed on YTD chart

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#1963]
**Describe the bug**
Dec 2018 and Jan 2019 are overlayed on the Year To Date charts for Revenue, Orders & Products

**To Reproduce**

1. Go to Analytics -> Revenue
2. Change the data range to Year to Date
3. See the X-Axis label on the left
4. Switch to Orders or Products

**Expected behavior**
Based on other charts, the Jan 2019 label should be moved right

**Screenshots**
<img width="1083" alt="Screen Shot 2019-04-01 at 4 53 00 PM" src="https://user-images.githubusercontent.com/343847/55355446-afa67b00-549e-11e9-90ec-c7d06cf9b314.png">

**Desktop (please complete the following information):**

* OS: MacOS Mojave 10.14.3
* Browser Chrome
* Version 73.0.3683.86

**Comment by LevinMedia** [comment]
heya @rrennick ! I can't reproduce it on my site, but... if the date range is year to date, The X-axis tick with December 2018 shouldn't be appearing at all, like in this example below:

<img width="3289" alt="Screen Shot 2019-04-02 at 7 57 14 AM" src="https://user-images.githubusercontent.com/4500952/55412861-09e62100-551d-11e9-8a1e-f7d1f4deec70.png">

**Comment by rrennick** [comment]
@LevinMedia Set your TZ to a North American timezone. The time being sent to the API is UTC & somewhere it's being changed to local time (which for me changes `2019-01-01T00:00` into `2018-12-31T20:00`).

**Comment by rrennick** [comment]
Here's a screenshot from React state:
<img width="319" alt="Screen Shot 2019-04-02 at 12 46 22 PM" src="https://user-images.githubusercontent.com/343847/55416572-68bf9080-5545-11e9-8660-44c6ddfa209f.png">

**Comment by rrennick** [comment]
Closing this. I had been working on battery, killed off npm & forgot to start again.
