### ISSUE TITLE
Extensibility: How to support custom report inputs

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1964]
We had some feedback on one of our [release notes posts](https://woocommerce.wordpress.com/2019/02/28/woocommerce-admin-v0-8-0-release-notes/#comment-5512) asking if there would be an option to support adding in a custom form element that influences the data shown on a report.

The example provided is:

![adding-report-option](https://user-images.githubusercontent.com/22080/55357312-904d2500-5481-11e9-9f11-fb64cd6c3eee.png)

Currently the extension is injecting a select drop down onto the sales report, which the value of the select box then manipulates the data returned and displayed in the report. So it seems almost like a report-level display setting, not so much an Advanced Filter.

To provide support for something like this it seems we would need to be able to expose either a slot-fill type mechanism, or add the ability to filter a set of report display options that allow adding primitive report filters ( checkbox, text input, select etc ). And also adjust the call to the data layer to grab the value(s) of these inputs, and pass them along to the API.

From there the already built REST API hooks/filters should allow for extension developers to manipulate the query and data being returned based upon these values.

**Thoughts?**
Curious to hear other's thoughts here, and specifically @LevinMedia and @josemarques for ideas around how to support such extension-based reporting options via design.

**Comment by psealock** [comment]
I think allowing a config object that extension authors can create to output a few simple components, like checkboxes or a select, to modify url parameters will do. We can create a simple UI and request design feedback.

**Comment by psealock** [comment]
After conversing with @LevinMedia, a good approach to this is to use Advanced Filters, which will add extensibility in https://github.com/woocommerce/woocommerce-admin/issues/2803.

Screens which don't have advanced filters by default will still be able to have them added by an extension. Closing this one.
