### ISSUE TITLE
Documentation: Update WCS Labels Example

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1965]
A long-long time ago, on a macbook no longer present in my life, [I developed a "demo" plugin](https://github.com/timmyc/wcs-example-report) that used wc-admin to create a new custom report. This example pre-dates so many awesome things in wc-admin, like namely our npm modules! While we are going to focus more on Extensibility in Q2, I thought it would be a great time to revisit this plugin, and give it a refresh with the latest and greatest wc-admin has to offer.

The ability to add a custom report like this [has been requested via feedback](https://woocommerce.wordpress.com/2019/02/28/woocommerce-admin-v0-8-0-release-notes/#comment-5512) so it would be nice to update the example with all the new good stuff.

Some ideas that could be included in this task, but totally up to whomever takes it on:

- [ ] Get the code to a place where it could be included in WCS itself
- [ ] Create a very basic "hello world" style custom report that can show the basics of how to setup a report page. Include this documentation in our [examples directory](https://github.com/woocommerce/woocommerce-admin/tree/master/docs/examples).
- [ ] Write up a quick tutorial based upon either of these things for the dev blog. Publish. Fame. Riches.

**Comment by psealock** [comment]
>Create a very basic "hello world" style custom report that can show the basics of how to setup a report page. Include this documentation in our examples directory.

I'm looking to do something similar with https://github.com/woocommerce/woocommerce-admin/issues/1964 and I'm thinking a separate repo could be better to hold all the examples. This way, build scripts/webpack can be done once and the whole thing can be cloned into `/plugins` folder for anyone that wants to tinker with working code.

Any thoughts?

**Comment by rrennick** [comment]
I have created https://github.com/Prospress/action-scheduler-admin with a longer term plan of rolling it into AS which will in turn be rolled into WC (maybe 4.0). It will be based on @timmyc 's demo plugin, with a table, rest api use, etc.

 > I'm thinking a separate repo could be better 

Agreed, that allows for faster iteration, community contribution, etc. without interfering with the main plugin development. A few different examples would be good as well. I'm just learning React so more examples will help me as well :)

**Comment by timmyc** [comment]
@rrennick very cool - since AS is based upon a CPT right now guessing it could probably use core REST posts endpoints right? But longer-term I suppose with the ability to use different persistence layers a full set of AS-specific REST endpoints would be needed right?

**Comment by rrennick** [comment]
> I suppose with the ability to use different persistence layers a full set of AS-specific REST endpoints would be needed right?

It would be useful at least. There are open [WIP PRs](https://github.com/Prospress/action-scheduler/pulls) for adding more management features into WP CLI. It would be good to have those available in REST as well.

**Comment by psealock** [comment]
>>I'm thinking a separate repo could be better

>Agreed, that allows for faster iteration, community contribution, etc. without interfering with the main plugin development.

I made something basic in this regard here, https://github.com/psealock/woocommerce-admin-extension-examples, but after some thought I decided to see what a solution in this repo might look like. 

I'd like to be able to reuse parts of the build step and keep the team's notifications around mentions, code reviews and issues intact. I fear that a separate repo will get stale and keeping it updated will be require a context switch.

I'll have a basic demo soon.

**Comment by rrennick** [comment]
> I made something basic in this regard here

Nice. I will probably use some of your config files for the dependency versions.

> I fear that a separate repo will get stale and keeping it updated will be require a context switch.

For the `Hello World` one, a separate repo is probably fine but I had the same concerns for examples that use the REST API and/or WCA components.

**Comment by psealock** [comment]
@rrennick, here is the in-repo version of extension examples https://github.com/woocommerce/woocommerce-admin/pull/2018

**Comment by rrennick** [comment]
This [PR](https://github.com/Prospress/action-scheduler-admin/pull/6) has an example that includes

- REST API endpoint

**Comment by rrennick** [comment]
@timmyc Are you okay with closing this one with the 2 working examples?

**Comment by timmyc** [comment]
Absolutely, excellent work @rrennick and @psealock 🙌
