### ISSUE TITLE
Allow Filtering All Reports by Country

### ISSUE THREAD

**Issue by kwok0781** [woocommerce/woocommerce-admin#1967]
Requesting filters on all reports by country so that we can quickly see P&L based on country.

**Comment by kwok0781** [comment]
Furthermore, can we have a filter at the top of the dashboard so that we can see all stats based on country?  Right now there isn't an easy way to filter by country as there was in the original dashboard (we filtered by currency)

Ideally, it would be good to get a revenue chart where each country is drawn on its own line/bar together in a single chart.  This will allow us to have a side-by-side comparison of a country's performance.  To reduce the number of countries, we could filter out only three or four countries to compare.

**Comment by dreiris** [comment]
Thank you for the feedback and idea! This ticket is being closed and the feature request is being moved to a backlog. The feature will be evaluated with other feature requests and prioritized.
