### ISSUE TITLE
Use `view_woocommerce_reports` check for Menu Item Registraion

### ISSUE THREAD

**Issue by kwok0781** [woocommerce/woocommerce-admin#1968]
By report, please allow us to select the category of user who can see this report. For example, only admins can see P&L reports but an inventory report can be seen by admins and store managers. The permission should be granted per report.

--- Added 2019-04-29 by @timmyc ---

Currently, as @nikonratm [points out below](https://github.com/woocommerce/woocommerce-admin/issues/1968#issuecomment-484265081) the display of the menu items for Analytics/Dashboard is currently scoped to users whom have `manage_options` capabilities.

While on the REST API side of things, we use the [following logic](https://github.com/woocommerce/woocommerce-admin/blob/master/includes/api/class-wc-admin-rest-reports-controller.php#L60) to determine if users can access the reporting endpoints:

`wc_rest_check_manager_permissions( 'reports', 'read' )`

And the legacy reports [also use this capability to register menu items](https://github.com/woocommerce/woocommerce/blob/b95bf94092a2c6fd1de863e4aae92debfcb5fd42/includes/admin/class-wc-admin-menus.php#L71).

Therefore it seems like we should use the same capability for the new Analytics section as well.

**Comment by timmyc** [comment]
@kwok0781 thanks for the feature suggestion. Currently the display of the Dashboard & Analytics menu options are only shown to those with `manage_options`/shop manager capabilities. Furthermore the REST endpoints are secured for the same set of permissions.

We will put this in our backlog and discuss if it is something we can implement.

**Comment by kwok0781** [comment]
Ideally, there would be a separate role for someone who is packing orders. They should only see the orders that they are packing and should not see other’s orders. Also, they should not see any reports unless they are permissioned to do so.
Shop managers should have full access to WooCommerce to run reports and access all orders. They do not have credentials to edit the settings of the Wordpress site since this is only reserved for the administrator role




On Tuesday, April 2, 2019, 8:38 AM, Timmy Crawford <notifications@github.com> wrote:


@kwok0781 thanks for the feature suggestion. Currently the display of the Dashboard & Analytics menu options are only shown to those with manage_options/shop manager capabilities. Furthermore the REST endpoints are secured for the same set of permissions.

We will put this in our backlog and discuss if it is something we can implement.

**Comment by nikonratm** [comment]
Even if we don't get the wishlist of such granular control the plugin is currently written to only allow those with "manage_options" to view reports which doesnt make sense IMHO, I think it should be "manage_woocommerce"? Also simple enough would be to implement a filter for this to allow us to easily change, e.g. in includes/class-wc-admin-loader.php:
```
add_submenu_page(
'woocommerce',
$page_title,
$menu_title,
apply_filters('woocommerce_admin_role_viewreports', 'manage_options'),
...
```

**Comment by timmyc** [comment]
@nikonratm valid point - and really the display of the menu option/reports should match that of the permissions being applied to the REST API endpoints. I'm going to update the original post of this issue to reflect that.

**Comment by jeffstieler** [comment]
@timmyc I just want to double check the task for this issue - we are just changing [this](https://github.com/woocommerce/woocommerce-admin/blob/ee8d805aab6f357dc78e1be7a8ad75bd1cdb74fc/includes/features/analytics/class-wc-admin-analytics.php#L79) to `manage_woocommerce`?

**Comment by nikonratm** [comment]
What about https://github.com/woocommerce/woocommerce-admin/blob/92be0e84fdfb5de75278c6cdbb59cab7e061615c/includes/class-wc-admin-loader.php#L30 & https://github.com/woocommerce/woocommerce-admin/blob/92be0e84fdfb5de75278c6cdbb59cab7e061615c/includes/class-wc-admin-loader.php#L178 ?

**Comment by timmyc** [comment]
@jeffstieler yep that would work along with the items @nikonratm pointed out too.

**Comment by rrennick** [comment]
> I just want to double check the task for this issue - we are just changing this to `manage_woocommerce`?

If we change that to `manage_woocommerce` then all the submenu items require that as well as the cap on the submenu item. If the parent menu isn't accessible none of the submenu items are registered.
