### ISSUE TITLE
Ability to save reports ... this should be the first screen in the reports tab

### ISSUE THREAD

**Issue by kwok0781** [woocommerce/woocommerce-admin#1969]
After we have customized a report, please give us the option to save the report or to make it the default report to display. Every user can save their own reports or to make it shareable to others within their organization.

**Comment by timmyc** [comment]
@kwok0781 can you provide a little bit more detail here? By customizing the report, are you speaking to setting advanced filters for a specific report? Would you want date range selections persisted too? FWIW everytime you apply a filter, or a date range, the arguments are added to the URL as GET params - so you could effectively bookmark any customized report.

But it sounds like you would like to save pre-defined views like this, and have the ability to maybe name them, and have those pre-sets shown on the dashboard maybe?

**Comment by kwok0781** [comment]
Yes, this is correct. I was hoping to save certain preset reports so that they can be easily viewed:
- Daily revenue charted with P&L (average of the entire time period is also shown in the header bar)- avg time between order set to processing until set to completed- Daily traffic visiting Shop pages charted with avg # of pages viewed on WooCommerce - Waterfall chart displaying main shop page -> single item product pages -> add to cart -> checkout initiated -> thank you page
These would be saved individually with variable date filters:
- rolling 30 days- rolling 365 days- YTD

A separate breakdown by country / region would be great as well. 

On Tuesday, April 2, 2019, 8:37 AM, Timmy Crawford <notifications@github.com> wrote:


@kwok0781 can you provide a little bit more detail here? By customizing the report, are you speaking to setting advanced filters for a specific report? Would you want date range selections persisted too? FWIW everytime you apply a filter, or a date range, the arguments are added to the URL as GET params - so you could effectively bookmark any customized report.

But it sounds like you would like to save pre-defined views like this, and have the ability to maybe name them, and have those pre-sets shown on the dashboard maybe?

**Comment by kwok0781** [comment]
The issue with saving a link is that it hardcodes a date window.  Currently this is what I have bookmarked:  wc-admin#/?period=custom&compare=previous_period&after=2019-06-03&before=2019-06-09

However, can WC Admin accept a rolling 14day so that we don't need to keep updating the URL?  For instance:  wc-admin#/?period=custom&compare=previous_period&last14days

**Comment by timmyc** [comment]
Ah gotcha, thanks for the clarification there @kwok0781 - that does seem like it would be a nice feature.

**Comment by dreiris** [comment]
Thank you for the feedback and idea! This ticket is being closed and the feature request is being moved to a backlog. The feature will be evaluated with other feature requests and prioritized.
