### ISSUE TITLE
Dashboard: Add Ability to Register Custom Leaderboards

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1972]
Currently the list of Leaderboards presented in the Dashboard are [hard coded](https://github.com/woocommerce/woocommerce-admin/blob/master/client/dashboard/leaderboards/index.js#L58). Given a number of the extension's we want to add wc-admin support to are seeking to add custom leaderboards ( p75Izm-1Tp-p2 ) - it feels like a good time to start exploring this!

So the long-range goal for this issue is to allow for an entirely new leaderboard to be registered/supported from an extension. I anticipate this taking longer than one sprint to accomplish, but figured we should begin to work towards the end goal.

_Random Thoughts_
- Perhaps we can provide a "core" leaderboard endpoint that accepts date range picker arguments and outputs an object of leaderboard data, keyed by leaderboard "slug". For example if I'm making a leaderboard for "Bookings" I could hook into the API requests to the `/wc/v4/stats/leaderboard` endpoint, and add in my data for the given date range.
- Alternatively, maybe it would be easier to allow leaderboards to register a data callback method which the REST endpoint would use to assemble the data
- Do we want to limit the number of columns in leaderboard tables?
- Should we refactor current leaderboards that are built stand-alone in JS to use the new scheme?

**Comment by joshuatf** [comment]
Thanks for putting those thoughts together, @timmyc!

>Alternatively, maybe it would be easier to allow leaderboards to register a data callback method which the REST endpoint would use to assemble the data

I'm thinking this one to keep things open-ended and allow them to structure the data as they see fit.

>Do we want to limit the number of columns in leaderboard tables?

I think we should not impose limits, provided horizontal scrolling works efficiently on those tables.

>Should we refactor current leaderboards that are built stand-alone in JS to use the new scheme?

I think refactoring the existing ones is a good idea; this cuts down on the number of components we'll need to maintain.
