### ISSUE TITLE
Remove days with no order activity from Revenue Report 

### ISSUE THREAD

**Issue by josemarques** [woocommerce/woocommerce-admin#1997]
The Revenue report currently displays all calendar days of the timeframe selected in the date picker, regardless if there were any type of revenue activity:

![Screenshot 2019-04-04 at 16 15 53](https://user-images.githubusercontent.com/57050/55567113-f1c8fa00-56f4-11e9-9b53-c0acd28758bf.png)

Other similar reports (Orders) only display the days where there something happened with an order. This report should follow the same pattern.

**Comment by psealock** [comment]
This issue was duplicated in https://github.com/woocommerce/woocommerce-admin/issues/2614. Since that one has more information on it, I’ll close this one out.
