### ISSUE TITLE
Refunds should be distinguished from orders in the orders report.

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2002]
Once #2001 is resolved, we should distinguish the refunds from orders in the orders report.  Currently, a refund displayed in the report will look exactly like an order but with a negative value.

It might be a good idea to:
* Note that it's a refund somewhere.
* Link to the parent order that the refund relates to.
* Note the negative amount in red.

Should we show the refund ID and the order ID?  Or just the order id?

Here's a tentative example to describe this, but check with @LevinMedia and @josemarques before implementing.
<img width="1151" alt="Screen Shot 2019-03-25 at 10 26 18 AM" src="https://user-images.githubusercontent.com/10561050/55607011-82fba780-57ad-11e9-8021-7c8f2313ccf6.png">

**Comment by josemarques** [comment]
> Should we show the refund ID and the order ID? Or just the order id?
I don't think there's a good use for the refund ID, the refund should mention the original order ID and link to the original order.
