### ISSUE TITLE
Refund filtering outside of order statuses

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2003]
Once #2001 is merged, we will be able to filter the orders report by various "types" of refunds.  

Orders are given a status of `refunded` in core if they are full refunded, but this does not apply to partially refunded orders.  With the new `parent_id` that connects refunds and orders in the `wc_order_stats` table, we will be able to filter by:

* Order statuses with the `refunded` status (already in place)
* Refunds themselves (only the negative amounts and not the original orders)
* Orders with refunds (the parent order, but not necessarily associated refunds)

Do we want to implement either of the latter 2 options?  I'm not sure where this would fit filter-wise since these are not statuses, but a quick and easy way would be to add this under advanced filters:

<img width="497" alt="screen-shot-2019-03-26-at-2 41 54-pm" src="https://user-images.githubusercontent.com/10561050/55607431-c0ad0000-57ae-11e9-8242-54b0e132ad6a.png">

/cc @josemarques @LevinMedia

**Comment by josemarques** [comment]
I think Order type is confusing when combined with Order Status.

@LevinMedia what do you think about using some like

Refund - Total, Partial

**Comment by LevinMedia** [comment]
I think a new filter to specifically handle refunded orders will work best:

<img width="1292" alt="Screen Shot 2019-04-05 at 8 40 01 AM" src="https://user-images.githubusercontent.com/4500952/55639595-9b080280-577e-11e9-90bd-f79a8de2b229.png">

**Comment by joshuatf** [comment]
That looks good to me if we just want to offer the ability to sort by refunded orders and not show the actual refunds when filtered.

Not sure if users will want to see the refunds along with the orders or be able to just filter down to refunds (not orders). /cc @LevinMedia @josemarques

**Comment by josemarques** [comment]
> Not sure if users will want to see the refunds along with the orders or be able to just filter down to refunds (not orders)
Isn't that that the case when this filter is not applied?  To filter down to just refunder users would apply the "Refunded Orders: All" filter.

**Comment by LevinMedia** [comment]
@joshuatf - Caught up with @josemarques on this. I made some changes to the language in the filter. Essentially, when this filter is applied, you should only see child refund rows, not the original orders. If you're using one of the first three options, your net should always be a negative number. If "none" is selected, all the refund rows are removed, and your net should always be positive.

![55639595-9b080280-577e-11e9-90bd-f79a8de2b229](https://user-images.githubusercontent.com/4500952/57180961-f0a5fc80-6e5b-11e9-808e-5a1eaff1032d.png)
