### ISSUE TITLE
Activity Panel: Notes timezone issues

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2006]
The notes feature does not seem to correctly account for timezones.

The timezone in the database is stored as GMT/UTC.

<img width="531" alt="Screen Shot 2019-04-05 at 10 38 37 AM" src="https://user-images.githubusercontent.com/689165/55636570-1b376380-5791-11e9-84db-02a914495106.png">

To reproduce:
* Pick any note and update the `date_created` value a note in your `wp_wc_admin_notes` table to the current time in UTC. Example, It is currently 14:50 UTC (10:50 AM): `2019-04-05 14:40:10`. You can also test the mobile app note here: #2008.
* Set your browser time to anything other than UTC.
* Refresh the inbox panel, and see the time is wrong. For example, EST shows "4 HOURS FROM NOW".

**Comment by Aljullu** [comment]
@jeffstieler did some changes regarding this in #1872, so this issue might be fixed when that PR is merged.

**Comment by justinshreve** [comment]
🤦‍♂️ Thanks for linking that @Aljullu! Assigning this to you @jeffstieler if you don't mind, since you already have a fix :).

**Comment by Aljullu** [comment]
Now that #1872 was merged, this should be fixed.

**Comment by timmyc** [comment]
While working on #2677 I experienced this bug again, so not sure if it was fixed fully the first time, or perhaps we had a regression sneak in somewhere between here and there.

**Comment by opr** [comment]
Howdy folks, I am seeing this on my local development site and JN. The timezone on my site is set to "London", and when I add a note I see "an hour from now". When the site is UTC+0 it shows correctly.

I also noticed this also happens when creating a new JN site, after setting it up change the site's timezone to something other than UTC+0 and then install WooCommerce.

![image](https://user-images.githubusercontent.com/5656702/132385006-e35ed91b-73f8-4b58-8c3a-2782e2a952f7.png)

If it's helpful, here's the code I'm using to add the note.

```php
$note = new Note();
		$note->set_title(
			__(
				'Introducing the Cart and Checkout blocks!',
				'woo-gutenberg-products-block'
			)
		);
		$note->set_content(
			__(
				"Increase your store's revenue with the conversion optimized Cart & Checkout WooCommerce blocks available in the WooCommerce Blocks extension.",
				'woo-gutenberg-products-block'
			)
		);
		$note->set_content_data(
			(object) array(
				'getting_started' => true,
			)
		);
		$note->set_type( Note::E_WC_ADMIN_NOTE_INFORMATIONAL );
		$note->set_source( 'woo-gutenberg-products-block' );
		$note->set_name( self::SURFACE_CART_CHECKOUT_NOTE_NAME );
		$note->add_action(
			'learn_more',
			'Learn More',
			'https://woocommerce.com/checkout-blocks/'
		);
		$note->save();
```

**Comment by joshuatf** [comment]
I'm able to reproduce this issue.  We store notes in UTC time and the REST response includes the datetimes with `date_created` and `date_created_gmt`.

https://github.com/woocommerce/woocommerce-admin/blob/f78b285418f681829affd61851192e56ef0fb32b/src/API/Notes.php#L452-L453

We then use the date created (the store's timezone) in moment to get the "from now" time, but this appears to expect UTC time which we are not passing it:

https://github.com/woocommerce/woocommerce-admin/blob/f78b285418f681829affd61851192e56ef0fb32b/packages/experimental/src/inbox-note/inbox-note.tsx#L277
