### ISSUE TITLE
Component: Editor

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#201]
Child issue of #199

**Designs**: [inVision Project](https://automattic.invisionapp.com/share/9RMY8JIJAVG#/screens/305602742)

<img width="501" alt="screen shot 2018-07-13 at 12 52 05 pm" src="https://user-images.githubusercontent.com/689165/42703778-9207f078-869b-11e8-8617-3a04262d3bc6.png">

This task involves validating that a small editor can be placed as a component in `wc-admin`. We can reuse editor controls to build a simple mode.

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
