### ISSUE TITLE
Activity panel read times should be in GMT

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2012]
**Describe the bug**
The last read time for reviews and inbox uses the client's time to store a timestamp.  This causes an incorrect unread indicator.

The user meta field `activity_panel_inbox_last_read` should be updated to use GMT times to accurately compare against creation dates.

**To Reproduce**

1. Read notes by opening the notes activity panel and closing it.
2. Add a new note.
3. Refresh the page and notice that the unread indicator is not present to indicate the newly added note.

**Expected behavior**
Expected the unread indicator to be added.

**Comment by Aljullu** [comment]
I think they are different issues, but still wanted to point out that #1872, and now #2013, include some fixes regarding the dates in the Activity Panel. In case those changes are helpful for this issue @joshuatf.

**Comment by joshuatf** [comment]
Thanks for noting those @Aljullu 😄

**Comment by joshuatf** [comment]
This issue does appear to be resolved by #1872 and #2013.
