### ISSUE TITLE
Date Presets: Allow fiscal year

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2016]
Businesses often run on fiscal years which can differ from calendar years. It can be useful to view stats from this perspective. We could offer an option to add a preset in the settings and it  would be reflected here:

<img width="513" alt="Screen Shot 2019-04-07 at 9 12 56 PM" src="https://user-images.githubusercontent.com/4500952/55698279-f3572400-5979-11e9-91a6-6b21083df7d1.png">

>There needs to be an option where a business or website can set the calendar year.  This is how Metorik has it set up and it works brilliantly!

Issue from https://github.com/woocommerce/woocommerce-admin/issues/455#issuecomment-480865915

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
