### ISSUE TITLE
Customers data store does not allow filtering by date

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2017]
**Describe the bug**
`before` and `after` params are not options for the customers controller or endpoint.  The customers report does not currently have a date filter (but may benefit from one? @LevinMedia @josemarques ).

However, in leaderboard reports, this means that customer leaderboard stats will not change based on date.  Even if we're not adding a date range option to the customers report, we should provide these params as options for customers.

The customers data store joins on the order stats, so we can use the order dates to filter.

**To Reproduce**

1. Go to the dashboard.
2. Change the date.
3. Note that the customers leaderboard does not change.

**Expected behavior**
Expected to be able to filter customers by date.

**Comment by josemarques** [comment]
> The customers report does not currently have a date filter (but may benefit from one?
I agree on this one, the customer leaderboard should the top customers in the date range, otherwise it's not very useful. Also it creates a disconnected between the other headboards since those are relative to the date range.
