### ISSUE TITLE
PHP Warning in Leaderboards endpoint

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#2054]
**Describe the bug**

`PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'WC_Admin_REST_Leaderboards_Controller' does not have a method 'get_public_allowed_item_schema' in /srv/www/woocommerce/public_html/wp-includes/rest-api/class-wp-rest-server.php on line 1170`

Introduced in 667376ad786a6478247df5a2aa1376a44c854038, missed in review (whoops!). Perhaps this was meant to mimic `WC_Admin_REST_Reports_Performance_Indicators_Controller`? The function isn't defined in `WC_Admin_REST_Leaderboards_Controller`.

**To Reproduce**

1. Verify that PHP warnings are displayed in your error log
2. Go to the dashboard
3. See warning

_(cc: @joshuatf)_

**Comment by joshuatf** [comment]
Thanks for catching this @jeffstieler!

Oddly I'm not getting an error unless I send an `OPTIONS` request to the allowed endpoints.  The default public schema also appears to be missing the `label` property.
