### ISSUE TITLE
Uncached query strings

### ISSUE THREAD

**Issue by gravnetic** [woocommerce/woocommerce-admin#2055]
The WooCommerce Admin plugin can in some cases cause a 502 (out of memory) because of uncached requests.  The api-fetch.min.js fetch requests on orders, coupons, etc are not cached, probably for a near-time reporting, including query strings. This is eating up a ton of memory.  I don't think that anyone is looking for real-time performance on an admin UI?

One possible solution is to offer a cache time setting (30 seconds, 5 minutes, 1 hour, 1 day, etc).  This would have the additional benefit of setting that performance expectation.  Possibly concatenate requests, cache requests, or figure out how to reduce server strain that this plugin is causing.

**Comment by timmyc** [comment]
Closing in favor of #2020
