### ISSUE TITLE
Review Card: Replying/Approving/Spam

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#206]
Child issue of #199

**Designs**: [inVision Project](https://automattic.invisionapp.com/share/9RMY8JIJAVG#/screens/305602742)

<img width="1073" alt="screen shot 2018-07-13 at 1 03 29 pm" src="https://user-images.githubusercontent.com/689165/42704256-2c9aba20-869d-11e8-85a5-badd7841387a.png">

This issue depends on many of the components outlined in #199. Once those are in place, this task will involve bringing them all together and implementing the replying review card view + API code for replying.

**Comment by psealock** [comment]
The action buttons don't have any functionality hooked up. We should address this

https://github.com/woocommerce/woocommerce-admin/blob/db463abf0d7e5d3df8aa46e91a8966233494d346/client/header/activity-panel/panels/reviews.js#L102-L120

<img width="568" alt="Screen Shot 2019-10-07 at 11 43 40 AM" src="https://user-images.githubusercontent.com/1922453/66277211-bf909300-e8f7-11e9-84ae-95467fbcbe95.png">

**Comment by psealock** [comment]
Instead of enabling the Approve/Spam/Respond/Trash button, lets make the button simply go to the legacy page where the user can manage it.

Be sure to add a Tracks event so usage can be monitored.

The button can say "manage", but we can get feedback on that in the PR.
