### ISSUE TITLE
Blank pages when WooCommerce Branding is activated

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce-admin#2077]
**Describe the bug**

When `WooCommerce Branding` plugin is activated, all the sections on the `WooCommerce Admin` plugin appear to be blank. They show a white screen.

**To Reproduce**

- Install WooCommerce Admin.
- Install WooCommerce Branding.
- Visit any WooCommerce Admin pages.

**Expected behavior**

The WooCommerce Admin page appears as it does without `WooCommerce Branding` activated.

**What happens instead** 

The WooCommerce Admin pages are blank.

**Screenshots**

![Screenshot 2019-04-18 at 14 18 40](https://user-images.githubusercontent.com/18581859/56348821-e4c40480-61e4-11e9-8df7-742b26568bdf.png)

**Desktop (please complete the following information):**

* Device: MacBook Pro
* OS: macOS 10.14.4 - Mac OS Mojave 
* Browser: Google Chrome
* Version: Version 72.0.3683.86 (Official Build) (64-bit) 

**Additional context**

- No errors can be seen on the browser console.
- When `WooCommerce Branding` is deactivated again, the `WooCommerce Admin` pages appear as expected.

**Comment by joshuatf** [comment]
Hey @arunsathiya 👋 - Thanks for noting this!

Looks like the branding plugin replaces `woocommerce_page_` page prefixes with a user defined prefix, causing our `is_admin_page()` check to fail.

I'll see if we can come up with a workaround for this.

**Comment by arunsathiya** [comment]
Thanks for the fix, Joshua! 🙌🏽 💯
