### ISSUE TITLE
Emails Sent to Subscribers on Job Creation

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2092]
**Describe the bug**
From the [support forums](https://wordpress.org/support/topic/wc-admin_proccess_order/) a user reported getting a flood of emails when ActionScheduler jobs were added:

<img width="731" alt="emails" src="https://user-images.githubusercontent.com/22080/56438862-2615ec00-6299-11e9-9e14-337cc86eb9b7.png">

I have requested more information around what plugin might be in use for the email notifs to see if we can re-create.

/cc @rrennick in case you might have seen this before with Action Scheduler.

**Comment by rrennick** [comment]
The forum thread has been updated. I think we can close this one.
