### ISSUE TITLE
License mismatch between package.json and composer.json 

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#2101]
In https://github.com/woocommerce/woocommerce-admin/blob/master/composer.json#L6 the license is `GPL-3.0-or-later`.

In https://github.com/woocommerce/woocommerce-admin/blob/master/package.json#L9 (and child packages' `package.json`) it is `GPL-2.0-or-later`.

**Comment by rrennick** [comment]
Re-opening this as I missed the package.json files in the components folder.
