### ISSUE TITLE
Extension: Add hooks to extend summary numbers on charts

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2110]
Summary numbers and available charts should be extendable.

![Screen Shot 2019-04-25 at 10 54 29 AM](https://user-images.githubusercontent.com/1922453/56699165-88af3200-6748-11e9-8bd9-cdc2483f59f2.png)

**Comment by dreiris** [comment]
This needs to be broken out into smaller stories. This may also be part of merge criteria??

**Comment by psealock** [comment]
>This needs to be broken out into smaller stories.

Good idea, although Summary Numbers and Chart data are constructed from the same endpoint so extending one may extend the other by default. In any case, this issue could use some exploration and potentially be broken up.

>This may also be part of merge criteria??

I would think this would be a "nice to have", but not necessary for inclusion in 3.7.

**Comment by psealock** [comment]
Back due to popular demand https://github.com/woocommerce/woocommerce-admin/issues/6529#issuecomment-872630654

**Comment by kcfgl** [comment]
Hey @psealock just got a notice this one went stale again, so I figured I would check in and see how it’s going. Definitely a very useful feature so I still hope to see it included in a future release. Thanks!!

**Comment by kcfgl** [comment]
@psealock Hey again! I'd love to see the ability to add custom summary numbers. Hopefully this will be re-opened or has been addressed in another ticket. Thanks!
