### ISSUE TITLE
Month to Due Checkbox is not working properly

### ISSUE THREAD

**Issue by parmarhardip** [woocommerce/woocommerce-admin#2111]
**Describe the bug**
Analytic in all the "Month to due" checkbox does not properly work.

**To Reproduce**

1. Go to 'install new WoCoommerce and WooCommerce admin plugin'
2. Click on 'Analytic tab'
3. Click Month to due checkbox then the second one tries to uncheck the checkbox.

**Expected behavior**
Checkbox unchecked and checked when select and unselect.

**Video**
[https://www.screencast.com/t/nBDkCgkK52Pf](https://www.screencast.com/t/nBDkCgkK52Pf)

**Comment by timmyc** [comment]
Per conversation in #2112 - this is currently working as expected.
