### ISSUE TITLE
WC version notice doesn't match WC version check

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce-admin#2118]
**Describe the bug**
- [The version check checks for WC 3.6](https://github.com/woocommerce/woocommerce-admin/blob/49008986a3cfb77b6bf8f132fc5947d736fe1d6e/woocommerce-admin.php#L115)
- [The notice says you need WC 3.5+](https://github.com/woocommerce/woocommerce-admin/blob/49008986a3cfb77b6bf8f132fc5947d736fe1d6e/woocommerce-admin.php#L82)

**To Reproduce**

1. Use WC 3.5.x
2. Activate wc-admin
3. Error notice displays that you need WC 3.5+, but WC 3.5.x is active.

**Expected behavior**
I'd like to know which WC version I actually need. :P

**Screenshots**
<img width="1042" alt="Screen Shot 2019-04-25 at 10 21 20 AM" src="https://user-images.githubusercontent.com/7317227/56755253-ec832c00-6743-11e9-86e5-e3971fcd7949.png">

**Comment by timmyc** [comment]
Ha I just hit this too, and have a fix in #2117
