### ISSUE TITLE
Dashboard: Add Ability to Remove Section

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2122]
Child Issue of #2009 / Dependent upon #2120 

See #2120 for a bit more background - but again for this enhancement I'm thinking we leverage the existing pattern of the Ellipsis menu to expose the ability to delete/remove a Dashboard section.

- Under the new "Customize" Menu Title section in the ellipsis menu, add an option to Delete the section.
- Thinking we might want to use a confirm dialog to verify removal though not totally certain on that ( /cc @josemarques )
- Until we have a persistence layer that we are writing/reading from for dashboard preferences, lets just have the section removed from display via component state in the dashboard when the delete action happens.

**Comment by josemarques** [comment]
> leverage the existing pattern of the Ellipsis menu to expose the ability to delete/remove a Dashboard section.

This was already present on the block settings menu design, maybe it slipped through:

![Screenshot 2019-04-30 at 22 16 23](https://user-images.githubusercontent.com/57050/56993914-9c69f680-6b95-11e9-83e8-812957237ddf.png)

Here's the updated version with the controls to move the block: 

![Dashboard - Move block](https://user-images.githubusercontent.com/57050/56993950-ad1a6c80-6b95-11e9-8f22-24f6f6cc1ddc.jpg)

**Comment by josemarques** [comment]
> Thinking we might want to use a confirm dialog to verify removal though not totally certain on that

@timmyc 
Since this action is close to the options to move the block up and down there can be a few hits by mistake when trying to perform another action, so that sounds like a good idea.

**Comment by timmyc** [comment]
Thanks @josemarques! Are we calling these areas blocks or sections for the users?

**Comment by josemarques** [comment]
That's good question. We have been using blocks in all the pieces :

![Screenshot 2019-04-30 at 22 36 26](https://user-images.githubusercontent.com/57050/56994980-72fe9a00-6b98-11e9-8490-f39c6da65568.png)

But section actually makes more sense as a combination of a title and a few blocks.

@LevinMedia @jameskoster any thoughts on this?
