### ISSUE TITLE
Onboarding - Profile Wizard: Step 9 - Self Hosted "Cart"

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2161]
On this final screen of the hosted profile wizard, we will display any items for purchase selected in the previous product type or theme steps. 

Each item should be listed again with their title, description, and price, with an option for removal. Learn more links should link to their product pages.

They can choose to skip purchasing, which should "complete" the profiler, and lead them to the task list view.

If they click continue, they should be sent to the cart page on WooCommerce.com, with the products pre-added. See #2160.

<img width="1024" alt="cart-not-hosted-1" src="https://user-images.githubusercontent.com/689165/57140882-d77f4c00-6d86-11e9-80e2-3efbac8484c7.png">

![cart-1](https://user-images.githubusercontent.com/689165/57140885-da7a3c80-6d86-11e9-9577-369dd31768a1.png)

**Comment by joshuatf** [comment]
Unassigning myself for the time being as this step seems like it will most likely be taken care of on the WCCOM side.

**Comment by justinshreve** [comment]
I'm closing this. We can re-open if this ends up happening on our side.
