### ISSUE TITLE
Onboarding - Profile Wizard: Implement Tracks

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2163]
We will want to add tracks for users who opted in on the first screen. 

The list of events can be found via p1560449057014200-slack-wc-onboarding.

[Master Thread](https://wp.me/p90Yrv-10i) | [Designs](https://wp.me/p6riRB-4rG)

**Comment by pmcpinto** [comment]
Hey Justin, 

Just a heads up that I already finished listing the events for the current Task List mockups. It might be necessary to add/remove something in case we need to do some design tweaks, but currently the list is up to date.
