### ISSUE TITLE
Tracks: Track Start of Import Jobs

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2173]
In order to gauge the number of import jobs that are succeeding/completing/failing I'm proposing we implement tracks for the following events:

- When an import job ( singular job, not batch job ) begins. Event name: `import_job_start`
- When an import job ( again not batch jobs ) completes Event name: `import_job_complete`

For event props, we should pass along the `type` of job - whether it be a customer import or an order import.

We will lean on the presence of `WC_Tracks` which was introduced in 3.6 to record the events via PHP, details can be seen in the [record_event](https://github.com/woocommerce/woocommerce/blob/master/includes/tracks/class-wc-tracks.php#L75) method.

**Comment by Aljullu** [comment]
@timmyc #2057 introduced the ability to delete previous data. Do you think we should track those events too?

> When an import job ( again not batch jobs ) completes Event name: import_job_complete

Should the complete event name or props be different if it fails or succeeds? I guess it might be interesting to distinguish between both cases.

**Comment by timmyc** [comment]
> introduced the ability to delete previous data. Do you think we should track those events too?

Sure that seems like a nice thing to track. Ultimately I think we will be layering many more tracking events throughout the app - for this issue I'm primarily interested in getting a sense of how many imports are happening, and how many are failing by comparing against the completed successful jobs.

> Should the complete event name or props be different if it fails or succeeds?

If we can record an event specific for when a job fails that would be most ideal
