### ISSUE TITLE
Install Nudges

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2174]
The work for this task should be performed in WooCommerce core, and will ideally ship in the next 3.6.x release.

Design thread: p6riRB-3V2-p2

This task involves creating a new `WC_Admin_Notice` akin to the one that was used to promote the blocks project - to prompt users to install and test out WC Admin:

![image](https://user-images.githubusercontent.com/22080/57262489-1f210480-7021-11e9-841b-2033325a2d1d.png)

[Here is the PR](https://github.com/woocommerce/woocommerce/pull/22982/files) where the Blocks plugin notif was removed to help kick-start the development of this feature.

The notif should only be shown if the site is running WordPress 5.0 or greater.

**Comment by rrennick** [comment]
> The work for this task should be performed in WooCommerce core

Both `README.md` and `readme.txt` in this repo need to be updated to remove the BETA software warning before the version of WC is releases.

**Comment by timmyc** [comment]
Correct, thanks for the reminder @rrennick - working on getting things up and running on woocommerce.com this week :)

**Comment by rrennick** [comment]
I was looking at the admin notice PR and wondered whether we should add some screenshots, etc. to the plugin repo so people can get a feel for the level of reporting they would be adding to their stores. Secondly, once the screenshots were there a link to the screenshots page/tab could be added to the nudge.

**Comment by timmyc** [comment]
@rrennick the original designs of the nudge called for a screenshot to be shown when the nudge was being viewed on the legacy reporting pages. I could update the PR with that.

**Comment by rrennick** [comment]
> I could update the PR with that.

That would work.
