### ISSUE TITLE
After Updating Stock - Product Still Remains in Stock Panel

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2175]
**Describe the bug**
When updating a product that is either out of stock, or below the low stock inventory threshold to a level that is above the low-stock threshold - the product still appears in the Stock Panel until you refresh the page.

**To Reproduce**

1. Set your low stock threshold to 2
2. Edit a product so the stock level is 1
3. Visit the dashboard, note the indicator is shown for the Stock Panel
4. Expand the panel, then modify the stock of the product you updated in step 2 to a number greater than the low stock threshold
5. Note the product is still shown after updating the stock to a value greater than the low stock threshold

**Expected behavior**
After updating inventory to a level above the low stock threshold, I anticipated the product to no longer be shown. The product is no longer shown after you refresh the page.

**Comment by mikejolley** [comment]
After speaking to @timmyc this likely needs some design input since removing the updated product right away could be disruptive and unexpected.

Another idea would be to refresh the stock panel if opened/reopened. I'm not sure how to make that happen though with limited react experience so perhaps if we do go this route someone can pair with me so I can understand how its done @timmyc @justinshreve?

**Comment by jeffstieler** [comment]
:wave: @josemarques 😄

**Comment by timmyc** [comment]
I chatted briefly with @josemarques about this today, and he is planning on giving an update tomorrow - but it is sounding like we are going to leverage the the "toast" style notification ([Woo core component demo)(https://wp-storybook.netlify.com/?selectedKind=Components%7CNotice&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel) we have on the settings page whenever an action like updating stock or responding to a review is done via the activity panel.

**Comment by josemarques** [comment]
Sorry for the delay, I got stuck on a snackbar rabit hole. 

Previously we had [discussed](https://github.com/woocommerce/woocommerce-admin/issues/2200#issuecomment-491244012) not using notices on the activity panel but after discussing it with a few people there are a few cases where they are required. Updating stock in one of those cases.

Here's the concept we're looking to implement to update stock:

![stock demo](https://user-images.githubusercontent.com/57050/57851838-7ec59f80-77d9-11e9-82cc-da0b2e091711.gif)

1. After the stock value is updated the card appearance is updated to 70% opacity and remains in the panel. If the update stock value is still under the treshhold the appearance is not changed.

2. A Material style snackbar lets the user know the action was successful

![Stock - updated](https://user-images.githubusercontent.com/57050/57852004-e67bea80-77d9-11e9-8b0b-8cec359e0df1.jpg)

3. When the user dismissed the stock panel the card is remove is the stock value was updated above the threshold.

![Stock - list updated](https://user-images.githubusercontent.com/57050/57852051-07444000-77da-11e9-8817-865a7253e7e6.jpg)
 
For the notices we are using the Material snackbar design aligned to the center to page without the wp-admin sidebar. 

https://material.io/design/components/snackbars.html#

This should override the notices style we were using before, one example is in the Analytics settings:

![Screenshot 2019-05-15 at 10 52 25](https://user-images.githubusercontent.com/57050/57852333-cf89c800-77da-11e9-9789-9440dddd48b3.png)

**Comment by Aljullu** [comment]
I created a follow-up for the snackbar replacement (#2445), so we can focus on the Stock panel in this issue.
