### ISSUE TITLE
Orders match filter doesn't affect the orders table

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2188]
**Describe the bug**
The orders match filter can be change to "Any" to allow any of the rules to apply.  `WC_Admin_Reports_Orders_Data_Store` doesn't take this param into account so all filters must always be matched.

**To Reproduce**

1. Go to the orders report.
2. Change the match filter to "Any" and add several filters.
3. Note the summary numbers are correct, but the table results are not.

**Expected behavior**
Expected the match filter to work for both table and summary numbers.

**Screenshots**
<img width="365" alt="Screen Shot 2019-05-08 at 1 55 11 PM" src="https://user-images.githubusercontent.com/10561050/57352857-397dee00-7199-11e9-8faf-5280658141b2.png">

**Comment by rrennick** [comment]
When I add a filter of all refunds, I get an empty dataset. Am I missing some of my history?

```shell
mysql> select * from wp_wc_order_stats where parent_id != 0;
Empty set (0.00 sec)
```

Orders with YTD date range

<img width="707" alt="Screen Shot 2019-05-14 at 11 16 11 AM" src="https://user-images.githubusercontent.com/343847/57705355-19877800-763a-11e9-82d5-fa1ec0ea14e7.png">

Refunds filter

<img width="763" alt="Screen Shot 2019-05-14 at 11 16 47 AM" src="https://user-images.githubusercontent.com/343847/57705374-24420d00-763a-11e9-9140-54d7207c32f1.png">

**Comment by joshuatf** [comment]
@rrennick I think that's a slightly different issue than the one noted here, but it sounds like your refunds aren't getting stored in the `wc_order_stats` table.  

Can you try running the latest branch of master and make sure you drop `wc_admin_version` from your options table to make any updates to your DB tables?  You can then reimport your data to make sure refunds get imported.

**Comment by rrennick** [comment]
@joshuatf Thanks. I was using refunds for one of my filters in testing a PR for this and getting no results. I'll finish this off then look at repopulating my DB.

**Comment by joshuatf** [comment]
@rrennick Gotcha.  That refunds filter should show the actual refunds (and not the original order with a status of `refunded`).  I'd guess they're not imported yet, but if you run into any more problems with it, feel free to ping me.
