### ISSUE TITLE
Notices: Screen Options Menu Displaced by Alerts

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2192]
When a StoreAlert is being shown on a legacy Woo View ( i.e. the coupons listing page ) - the screen options and help menus from wp-admin are bumped below their standard position:

![store-alert-screen-options](https://user-images.githubusercontent.com/22080/57398704-83100e00-7184-11e9-983e-a95f5d50e443.png)

__To recreate bug__
- Do a clean install of wc-admin to trigger the alert to import historical data
- Visit a legacy Woo Screen ( order listing, coupons listing etc )

**Comment by jeffstieler** [comment]
Should they be attached to the bottom of the WooCommerce Admin nav bar below the panel buttons?

**Comment by timmyc** [comment]
Well we hide them completely on wc-admin powered pages, so not entirely certain. @josemarques thoughts?

**Comment by rrennick** [comment]
Related #2210

**Comment by josemarques** [comment]
> Should they be attached to the bottom of the WooCommerce Admin nav bar below the panel buttons?

@jeffstieler 

This is the best place to display these, they were design to be attached to the wp-admin masterbar, so the admin nav bar is the next best thing.
