### ISSUE TITLE
Activity Panel: Enable Reviews Spam / Approve / Trash actions

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2200]
To finalize the functionality for 3.7 - lets hookup some of the actions that are shown in the Review Panel Card:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/22080/57493191-cc418a00-7278-11e9-8cf7-d22c4fed9656.png">

For this task I am proposing we:

- ~~Remove the Reply option for now, we can revisit if time permits leading up to 3.7~~
- Have the reply option link to the comment UI where a reply can take place
- Hook up the remaining three options: Spam / Approve / Trash to POST to [update product review](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product-review) endpoint and adjust the status of the review accordingly.

**Design Questions**
I'm guessing this might be detailed in a design somewhere, but figured I'd just ask again to verify the proper behavior.

- Upon changing the status of the review, what should take place? Should the review card be removed from view? Do we need to display a notice that the review status has been updated?

/cc @josemarques @LevinMedia

**Comment by josemarques** [comment]
> Remove the Reply option for now, we can revisit if time permits leading up to 3.7

Can we link this option to the screen where replying is possible instead of removing it? Without it this panel becomes less useful. 


> Upon changing the status of the review, what should take place? Should the review card be removed from view? Do we need to display a notice that the review status has been updated?

It should be removed from view. We can use an animation to gracefully remove it from view and not require and additional notification to signal the action is executed.

**Comment by psealock** [comment]
This has been replaced with a "Manage" link instead.
