### ISSUE TITLE
Currency component for negative values

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2202]
In https://github.com/woocommerce/woocommerce-admin/pull/2102#pullrequestreview-234849893 we discussed adding in a component that handles negative currency values.

This would replace the existing `renderCurrency()` wrapper in #2102 that wraps negative values in a span tag.

Additionally, all existing currency values should be replaced with this component to keep currencies consistent across the app.

<img width="742" alt="Screen Shot 2019-05-10 at 2 05 41 PM" src="https://user-images.githubusercontent.com/10561050/57505892-bbeae700-732c-11e9-8124-d56f73b8464f.png">

**Comment by timmyc** [comment]
The currency npm module has a className of `is-negative` which I think satisfies this old issue. closing out.
