### ISSUE TITLE
Inconsistent Help tab behavior, unable to access certain features if Help tab is removed

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce-admin#2210]
**Describe the bug**
- The top bar removes the 'Help' tab on most WooCommerce admin screens
- The Setup Wizard can be run through the 'Help' tab on WooCommerce admin screens
- Helpful WC content is accessed through the 'Help' tab on WooCommerce admin screens

It seems that this only happens on certain pages, though. I'm unsure what the expected behavior is.

On Products, Help tab is available:
<img width="1361" alt="Screen Shot 2019-05-10 at 10 25 22 AM" src="https://user-images.githubusercontent.com/7317227/57545172-67387380-730e-11e9-9303-cc829aeca922.png">

On Orders, it isn't:
<img width="1367" alt="Screen Shot 2019-05-10 at 10 25 13 AM" src="https://user-images.githubusercontent.com/7317227/57545176-699acd80-730e-11e9-90b1-2e1bca6d2b1c.png">

**To Reproduce**

1. Go to Orders admin screen, observe Help tab disappears shortly after page is loaded.
2. Go to Products admin screen, observe Help tab hangs around and is usable.

**Expected behavior**
Either of these 2 would be fine:
- Help tab would be available on WC admin screens
- The ability to re-run the Setup Wizard would be available somewhere (Status > Tools page?). You'd probably also want to expose the WC educational content somehow.

**Comment by rrennick** [comment]
@claudiulodro I do have the screen options & help tab on my orders screen. Can we compare notes on theme, other plugins, etc. ?

<img width="1109" alt="Screen Shot 2019-05-15 at 3 51 26 PM" src="https://user-images.githubusercontent.com/343847/57801126-6ac26500-7729-11e9-8346-6a3659a7f43b.png">

**Comment by claudiulodro** [comment]
OK I've got it worked out. Just tested with only WP 5.2, WC 3.6.2 and latest master branch of wc-admin.

When there is an order, the help tab shows:
<img width="1042" alt="Screen Shot 2019-05-15 at 12 02 19 PM" src="https://user-images.githubusercontent.com/7317227/57801841-90d80d00-7709-11e9-8fe8-4d79b9a3fafc.png">

When no orders have been placed yet it doesn't:
<img width="1044" alt="Screen Shot 2019-05-15 at 12 02 38 PM" src="https://user-images.githubusercontent.com/7317227/57801844-93d2fd80-7709-11e9-88ae-99b3ac86f1c4.png">

I guess that's a much more minor issue than I originally thought. :) Thanks for investigating @rrennick!

**Comment by timmyc** [comment]
@josemarques should we add the help menu and screen options back to wc-admin powered pages?

**Comment by josemarques** [comment]
@timmyc we should be displaying those two options in WooCommerce screens that are not part of wc-admin. 

In WooCommerce-admin we don't plan on using the screen options feature since we have alternative ways to set screen options. 

The help feature is currently the same content for all screens, so it's not super helpful. We'll explore a way to provide Help in WooCommerce-admin in the near future.

**Comment by rrennick** [comment]
> When no orders have been placed yet it doesn't:

It isn't visible when WC Admin is not active so it's being conditionally shown by WC. 

<img width="1137" alt="Screen Shot 2019-08-07 at 12 43 23 PM" src="https://user-images.githubusercontent.com/343847/62637094-34a01600-b911-11e9-841b-af1dedbaa871.png">

Closing.
