### ISSUE TITLE
Merge: Handling WordPress < 5.2

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2237]
While WooCommerce Admin already has logic in place to not run if the dependencies are not satisfied ( WC 3.6 or greater and WP 5.0 or greater ) we need to alter this logic a bit to prepare for merging the code to core. This issue will act as a parent issue for all tasks related to this update.

- [ ] Create conditional function, perhaps which will eventually live in `includes/wc-conditional-functions.php` to determine `wc_admin_enabled()`. The only logic would be checking for WP Version >= 5.0, and PHP must be > 5.4 but I think we should also make this filterable. 
- [ ] if `wc_admin_enabled()` is falsey, Nav/Activity Panels and new Analytics should not be loaded.
- [ ] If a site is running less than 5.0, we should also display an admin notice informing them of the new features they are missing out on: blocks, activity panels, analytics.

**Comment by rrennick** [comment]
Related #2203

**Comment by timmyc** [comment]
Updated to include the need for the PHP > 5.4 check - @peterfabian should that be PHP >= 5.4 or greater than 5.4?

**Comment by peterfabian** [comment]
Traits are supported from PHP 5.4.0 & I'm not aware of any other features that rely on newer PHP versions, so PHP >= 5.4.0 as far as I know.

**Comment by psealock** [comment]
Things have changed since this issue was originally written. Specifically, when we merge in 3.9 here are the supported versions:

WooCommerce: WP 5.3, 5.2, 5.1

wc-admin: WP 5.3, 5.2

We'll need a mechanism to disable wc-admin for sites running WP 5.1

**Comment by rrennick** [comment]
> We'll need a mechanism to disable wc-admin for sites running WP 5.1

Product blocks does that with https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/woocommerce-gutenberg-products-block.php#L19:L21

With that implementation the rest of the changes for this issue would be implemented in WC core.

**Comment by psealock** [comment]
In Core, packages aren't loaded when PHP is less than 5.6. So we're good there:

https://github.com/woocommerce/woocommerce/blob/cd2a63c2936af7d36531c6cc7610eb56f36e2873/woocommerce.php#L30-L38

I'll add a check for WP < 5.2 in `src/Package.php` of this repo because that code is run by Core before initialising the package.
