### ISSUE TITLE
Got error from WP 5.2 after Pluginupdate

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-admin#2242]
Had on a staging site  Wordpress 5.2 installed with Woocommerce Admin 0.11. Today I got a update to Admin 0.12 and I updated my installed version within Updater on site. Afterthan I got a email from my site about a fatal error from WC Admin 0.12. Below is error in detail and partially translated by me:

Details
==============
Error Typ E_COMPILE_ERROR in row 118 of file xxx/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-api-init.php verursacht. Fehlermeldung: require_once(): Failed opening required 'xxx/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-system-status-tools-controller.php' (include_path='.:/usr/share/php:..')

**Comment by rrennick** [comment]
This sounds like the plugin install did not process correctly. 

Can you download the plugin from https://wordpress.org/plugins/woocommerce-admin/ and install it through the uploader to see if you still have the same error?

**Comment by ajgw** [comment]
Hi @rrennick 
It seems to work as normal, no more errors. I was only wondering why I got this email from WP 5.2. Maybe its secure handling of buggy plugins / themes has a bug on this?

**Comment by ajgw** [comment]
Well, I deleted plugin, downloaded it from wordpress.org and installed it again through uploader and got no errors. Thanks.

**Comment by rrennick** [comment]
Awesome, thanks for letting us know.
