### ISSUE TITLE
Settings: Add ability to set default date range selection

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2250]
**Is your feature request related to a problem? Please describe.**

Requested via [the forums](https://wordpress.org/support/topic/request-save-date-range/):

> I would like to save the date range.
For me it’s most interesting to see everything YTD compared to year before.
Everytime I open the dashboard, I need to change it….. I would like to save this setting.

**Describe the solution you'd like**

Seems like either introducing a setting to set the default date range, or persist the one that is selected on the dashboard as the default for there in user meta would work ( I swear we had this at one point! ).

**Comment by rrennick** [comment]
>  I swear we had this at one point!

#1969

**Comment by timmyc** [comment]
Yeah kind of related, but more what I'm thinking of is we used to persist the last date range selected in user meta. Like it was one of the first things we were saving session to session. I could very well be imagining this though.
