### ISSUE TITLE
Card styles in wc-admin should be updated to more closely match Muriel

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2259]
**Describe the bug**
#2252 updates the Card component to use the Muriel design, but also provides a class `woocommerce-analytics__card` to override default Card component styles to keep wc-admin card styles from changing.

/cc @LevinMedia @jameskoster 

We can probably phase out some of the box shadow, border, and padding overrides used in wc-admin, but the default card header font sizes seem out of place.  We have a few options as to how to handle this:

* Continue overriding card header font sizes in wc-admin (seems like this will produce inconsistent UI expectations if all components are overriding).
* Adjust Muriel font sizes to be more in line with our expectations.
* Adjust the card designs in wc-admin to better fit with the default Muriel designs. (It's possible this will naturally occur as we start swapping out new components, but there's going to be an awkward phase between where styling is mismatched between components).

**To Reproduce**

1. Comment out the css for `.woocommerce-analytics__card` in `client/analytics/report/style.scss`.
2. Visit various pages around wc-admin.
3. Note the styling (primarily font size).

**Screenshots**
<img width="1020" alt="Screen Shot 2019-05-20 at 2 09 50 PM" src="https://user-images.githubusercontent.com/10561050/57999713-fad92380-7b08-11e9-9a23-5f534916a87e.png">
<img width="953" alt="Screen Shot 2019-05-20 at 2 09 07 PM" src="https://user-images.githubusercontent.com/10561050/57999714-fad92380-7b08-11e9-9df9-3048a0b733c1.png">

**Comment by jameskoster** [comment]
> Adjust the card designs in wc-admin to better fit with the default Muriel designs

I think this is the way to go, and I believe @LevinMedia has been doing some exploration.

Is it necessary to add/adjust text styles along with the card component? It might be easier to leave it for now and handle text separately?

**Comment by LevinMedia** [comment]
>Is it necessary to add/adjust text styles along with the card component? It might be easier to leave it for now and handle text separately?

@jameskoster - @joshuatf and I were talking about this last night. I was thinking the same thing. [Per the material guidelines](https://material.io/design/components/cards.html#anatomy), The card container is the only required element in a card. All other elements shown in a card are optional. 

I thought we could change the title text size depending on the context of the card - we'd just want to be sure we create some rules around that so we don't end up with 20 different card header text styles.

**Comment by timmyc** [comment]
Ping @LevinMedia and @jameskoster any more input here, is this something we still need to pursue?

**Comment by timmyc** [comment]
scratch that, looks like #2252 did this... i'm going to close this out.
