### ISSUE TITLE
Header Bar Is a Bit Too Tall On Wide But Short Screens

### ISSUE THREAD

**Issue by billrobbins** [woocommerce/woocommerce-admin#2287]
**The header bar is a bit too tall on my MacBook Pro**
When using my external monitor, I have additional vertical space and enjoy having the header bar present in WooCommerce.

But on my MacBook, it occupies about 10% of my available space vertically.  It's not much, but I find myself disabling the plugin to gain that space back.  

Here are some screenshots for comparison.

![With header bar](https://cdn-std.dprcdn.net/files/acc_705319/rX2NWk)
(Link to screenshot:  https://d.pr/rX2NWk)

![Without header bar](https://cdn-std.dprcdn.net/files/acc_705319/DS0vwQ)
(Link to screenshot:  https://d.pr/DS0vwQ)

**Describe the solution you'd like**
It would be nice to have the header bar be shorter if the browser window is not as tall.  There is a media query for the width already.  One for the height would be nice too.  

**Should this be prioritized? Why?**
A few of my teammates have noticed the same thing.  Based on that sample of daily WooCommerce users this could be something that affects a fair number of users once this is part of the core.

**Comment by Aljullu** [comment]
Thanks for the feedback @billrobbins!

@LevinMedia @josemarques what do you think about this? Currently, the header bar height depends on the window width. Would make it sense to make it depend on the window height, instead?

**Comment by josemarques** [comment]
I agree this can be an issue. @Aljullu let's use the height of the mobile design (50px) for narrower screens (under 1280px) .
