### ISSUE TITLE
Add conversion rate data to Dashboard

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#2297]
**Is your feature request related to a problem? Please describe.**

Requested via [the forums](https://wordpress.org/support/topic/conversion-rate-in-woocommerce/):

> I want to suggest that you add the conversion rate in wooocommerce admin because this is a very important metric for the owners of virtual stores.

**Describe the solution you'd like**

Conversion rate would require us having information about visits/sessions, so I guess it would require some of the logic that was considered in @justinshreve's branch `try/premium-stats` and users would need to have Jetpack installed.

**Comment by KZeni** [comment]
I'd like to second this. As an aside, it'd be nice if a transaction and/or customer data would have any/all UTM codes they encountered in a page they visited along the way. This could be surfaced in the reporting by having the visitor's history of encountering some recorded to their customer data (with the UTM specifics) & shown alongside that, and I'd love to see a column for transactions with UTM data a-la how the coupon codes are shown. There could possibly be a section in the reporting for Campaigns which then show which ones resulted in the most visits vs. most transactions, etc.

**Comment by dreiris** [comment]
Thank you for the feedback and idea! This ticket is being closed and the feature request is being moved to a backlog. The feature will be evaluated with other feature requests and prioritized.
