### ISSUE TITLE
Consider showing some of the information of the WooCommerce Dashboard in the WordPress Dashboard

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#2298]
**Is your feature request related to a problem? Please describe.**

Requested via the forums [here](https://wordpress.org/support/topic/decent-addition-but-buried/) and [here](https://wordpress.org/support/topic/viewing-this-on-the-dashboard/):

> Hi, any chance of showing this on the main WP dashboard as a screen option? Pretty sure most shop owners would love to know their figures on the landing page and couldn’t care less about local WP meetings. That would be amazing and hugely beneficial for the first impression of WordPress, when in a shop setting.

**Describe the solution you'd like**

That would consist in showing, in some way, some of the information of the WooCommerce Dashboard in the WordPress Dashboard.

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
