### ISSUE TITLE
Allow specifing the hour in the datepicker

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#2307]
**Is your feature request related to a problem? Please describe.**

Requested via [the forums](https://wordpress.org/support/topic/feature-request-filter-down-to-time-frame/):

> The only thing i would like to see added is the ability to filter down to a specified time frame. For example a client has a store has a cutoff of 5pm EST every day that they ship which is Monday – Friday. In order to get the most accurate report it would be nice to block off a time frame and not only a date. I hope this makes sense. Let me know if its possible to do so Thank you!

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
