### ISSUE TITLE
Orders panel shows no orders message when orders exist

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2309]
**Describe the bug**
A message is shown in the Orders activity panel that the store has not received any orders when it has.

I believe this is due to the before/after params defaulting to a 1 week period so `totalNonActionableOrders` results in `0` if no recent orders have been placed.

https://github.com/woocommerce/woocommerce-admin/blob/4d1e76117ecff27715ea6818008f7919caafe498/client/header/activity-panel/panels/orders.js#L310

Also related - https://github.com/woocommerce/woocommerce-admin/issues/1103

**To Reproduce**

1. Make sure you have orders, but none within the past week.
2. Open the orders activity panel.
3.  Note the message.

**Expected behavior**
Expected to see the message relevant to having previous orders but no actionable statuses:
`Good job, you've fulfilled all of your new orders!`

Or alternatively, a message that mentions there have been no orders within the past week.

**Screenshots**
<img width="652" alt="Screen Shot 2019-05-27 at 11 29 45 AM" src="https://user-images.githubusercontent.com/10561050/58394119-47c27a00-8074-11e9-820a-bc49c00a2efd.png">

**Comment by Aljullu** [comment]
Good catch! A quick solution to this problem would be adding `after: '1970-01-01T00:00:00'` or something similar to the query. But I'm not sure to understand what's the rationale of having default values for `before` & `after`. Couldn't we just remove them and let the client specify them if required?

**Comment by joshuatf** [comment]
Good question, @Aljullu.

>A quick solution to this problem would be adding after: '1970-01-01T00:00:00' or something similar to the query.

I think this is an acceptable solution, but...

>But I'm not sure to understand what's the rationale of having default values for before & after. Couldn't we just remove them and let the client specify them if required?

This feels like the right solution and what I would expect hitting this endpoint.  I think the only major concerns would be whether or not there are performance impacts.  @peterfabian mentioned in https://github.com/woocommerce/woocommerce-admin/issues/1103 that these may be minimal with pagination.

It might be worth doing some tests without those time restraints to see if there are any big performance concerns.

**Comment by jeffstieler** [comment]
> Or alternatively, a message that mentions there have been no orders within the past week.

This message would need to change based on the default date range setting, no?

> It might be worth doing some tests without those time restraints to see if there are any big performance concerns.

What do you think about removing the date range and introducing a `LIMIT` to the query instead?

**Comment by Aljullu** [comment]
> This message would need to change based on the default date range setting, no?

AFAIK the date range setting should not affect what we display in the Activity Panel. If there is an on-hold order from (let's say) one year ago, it should still appear in the Activity Panel.

> What do you think about removing the date range and introducing a LIMIT to the query instead?

I might be wrong, but given that it has pagination by default, that means there is already a `LIMIT` in the query, isn't it?

**Comment by rrennick** [comment]
Couldn't we do `wc_get_orders( array( 'status' => 'processing', 'limit' => 1 ) )` if the current query returns no rows to determine which message to display?

**Comment by rrennick** [comment]
> What do you think about removing the date range

On my REST client the time went from `0.187` to `0.213` when I added `&after=1990-01-01%2000:00:00` to the query string. The default limit of 10 rows should keep this at a low performance hit.

**Comment by jeffstieler** [comment]
Fixed in https://github.com/woocommerce/woocommerce-admin/pull/2659.
