### ISSUE TITLE
Plug in not compatible with SkyVerge WooCommerce Print Invoices/Packing Lists

### ISSUE THREAD

**Issue by siwhyatt** [woocommerce/woocommerce-admin#2315]
After installing and activating the Admin Dashboard, I can no longer print picking and packing lists with WooCommerce Print Invoices/Packing Lists.

The option still appears in the drop down on the orders admin page, but after clicking apply, the link to print does not appear.

Have latest versions of wordpress, woocommerce and WooCommerce Print Invoices/Packing Lists installed.

**Comment by rrennick** [comment]
@siwhyatt Thanks for reporting this.

**Comment by siwhyatt** [comment]
No probs.

Plugin looking good, will certainly give it a try again in the future when
the bugs are ironed out.

Thanks,

Simon

@Simon_Whyatt <https://twitter.com/simon_whyatt>
www.livenowthrivelater.co.uk

**Comment by Aljullu** [comment]
This issue has been reported by another user:

https://wordpress.org/support/topic/looks-nice-but-the-data-are-wrong/#post-11589050

**Comment by timmyc** [comment]
@rrennick did #2320 also fix this issue?

**Comment by rrennick** [comment]
I'm able to print both picking and packing lists in `master`. 

@siwhyatt This should be fixed in version 0.13.0 when it is released. I'm closing the issue. If you still have the issue after updating please let us know.

**Comment by siwhyatt** [comment]
OK, thanks for the update.

I'll give it a try.

Simon

@Simon_Whyatt <https://twitter.com/simon_whyatt>
www.livenowthrivelater.co.uk



[image: photo]
*Simon Whyatt*

www.livenowthrivelater.co.uk
<http://www.facebook.com/LiveNowThriveLater>
<http://es.linkedin.com/pub/simon-whyatt/10/151/111>
<http://twitter.com/Simon_Whyatt>
Read my latest post: Maybe pain isn’t so strange after all?
<http://www.livenowthrivelater.co.uk/2019/05/maybe-pain-isnt-so-strange-after-all/>

**Comment by unfulvio** [comment]
FYI WooCommerce PIP 3.7.1 https://github.com/woocommerce/woocommerce-pip/releases/tag/3.7.1 has improved compatibility with WC Admin

Thanks
