### ISSUE TITLE
postcss.config.js overrides not working 

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2322]
Some of the overrides like `outlines` and `toggle` defined in https://github.com/woocommerce/woocommerce-admin/blob/master/postcss.config.js don't seem to take affect correctly. The blue color is coming through.

<img width="894" alt="Screen Shot 2019-05-28 at 9 09 49 AM" src="https://user-images.githubusercontent.com/689165/58480492-769a2800-8128-11e9-90f8-16d0a3352b77.png">

It also seems like at least `secondary` should be a different color, from the other elements. Right now all colors are set to the same shade.

This also affects Muriel/onboarding styles: 
https://github.com/woocommerce/woocommerce-admin/pull/2313#discussion_r287941495

To Test:
* In a file like `dashboard/index.js` add the following:

`import { Button, FormToggle, FormTokenField } from '@wordpress/components';`

```
	constructor() {
		super();
		this.state = {
			textInput: '',
			selectValue1: '1st',
			selectValue2: '',
			checked: false,
			tokens: [],
			suggestions: [ 'Africa', 'America', 'Antarctica', 'Asia', 'Europe', 'Oceania' ],
		};
	}
	renderDashboardOutput() {
		const { query, path } = this.props;

		return (
			<Fragment>
				<Button isPrimary>Button</Button>
				<Button isTertiary>Button 2</Button>

				<FormToggle
					checked={ this.state.checked }
					onChange={ () => this.setState( state => ( { checked: ! state.checked } ) ) }
				/>

				<FormTokenField
					value={ this.state.tokens }
					suggestions={ this.state.suggestions }
					onChange={ tokens => this.setState( { tokens } ) }
					placeholder="Type a continent"
					isBorderless
				/>
			</Fragment>
		);
....
```
* View the dashboard and note some of the blue styles coming through on the toggle or borderless token input.

**Comment by psealock** [comment]
>It also seems like at least secondary should be a different color, from the other elements. Right now all colors are set to the same shade.

Yes those should be changed, I placed that color as a placeholder in the early days.
