### ISSUE TITLE
Reports: Downloading data returns only current page

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-admin#2338]
**Is your feature request related to a problem? Please describe.**
If I go to an Analytics report which spans across multiple pages, for example Analytics > Products. When I click on the download button I only end up with the current page.

**Describe the solution you'd like**
Even if the report is paginated for display, when it's downloaded I'd expect to get the full report. As far as I know this would be the normal expected behaviour when downloading, but I don't have an example to compare this with.

**Describe alternatives you've considered**
Other alternatives would be to increase the amount of results shown per page. But with larger reports they would still need to be pieced together to get the rull report.

**Comment by psealock** [comment]
Thanks for reporting this one @mikkamp. Its a known issue and will require aggregating data on the server. I'll add this to the backlog so it can be addressed.

**Comment by timmyc** [comment]
Closing in favor of #311
