### ISSUE TITLE
Analytics: When displaying a report, on the date range make the default end date yesterday

### ISSUE THREAD

**Issue by dreiris** [woocommerce/woocommerce-admin#2342]
**Is your feature request related to a problem? Please describe.**
As a user I want accurate data on my reports in Analytics. When the user looks at the data it looks incorrect and they lose trust in the report because the data is not in real-time.

**Describe the solution you'd like**
Given a user is in WooCommerce Admin/Analytics
When the user views a report
Then the default end date is yesterday (today minus one)

Give a user is in WooCommerce Admin/Analytics
When the user views a report AND selects an end date that is equal to today's date
Then display a message "The data for today has not populate yet. For current order data check WooCommerce>Reports>Orders." Or something along those lines.

**Describe alternatives you've considered**
- Show data in real time. Since we're not showing data in real time yet and there's a delay in populating data, changing the date range's end date to yesterday is a short-term fix. When a user selects today's date, displaying a message to indicate that the user does not have today's data will help the user understand why there is a discrepancy from WooCommerce>Reports>Orders. 

**Should this be prioritized? Why?**
- With the current date ranges, it looks like the data is inaccurate and unreliable. If user's don't trust the data, they will not come back to use the features.
- Example: Comparing WooCommerce>Reports>Orders to WooCommerce>Analytics>Orders and there's a discrepancy in the reports (see screenshot attached).

**Additional context**
![image](https://user-images.githubusercontent.com/10272401/58593225-2e116600-821f-11e9-8ace-5f14689f4585.png)

**Comment by timmyc** [comment]
Let's look at some scenarios about where this issue will happen... different hosting configs / load on the store etc.

**Comment by psealock** [comment]
>Describe alternatives you've considered

Maybe we can check for pending scheduled actions and display some kind of notice instead?

**Comment by psealock** [comment]
@dreiris do you think this is still a valid issue? We aren't showing data in real time because Action Scheduler needs to run, but we're not too far off. I think we should still show current day. What do you think?
