### ISSUE TITLE
Facebook for WooCommerce Senkronizasyon sorunu

### ISSUE THREAD

**Issue by cavitkinali** [woocommerce/woocommerce-admin#2346]
Facebook for WooCommerce sorunu. 'Facebook'ta ürünler senkronize edilemedi' hatası. Facebook for WooCommerce ayarlar bölümünden, 'ürünleri senkronize et' işaretledim fakat sorun yine çözülmedi.

![Adsız](https://user-images.githubusercontent.com/51189177/58614071-08886900-82c0-11e9-8198-497a966ed681.png)

**Comment by dougaitken** [comment]
Hi @cavitkinali 

This isn't related to the WooCommerce plugin or the WooCommerce Admin plugin.

Please report this to the Facebook team over here - `https://github.com/facebookincubator/facebook-for-woocommerce`
