### ISSUE TITLE
Fatal error when trying to activate WooCommerce Bookings (resolved by enabling with WooCommerce Admin disabled)

### ISSUE THREAD

**Issue by gluetooth** [woocommerce/woocommerce-admin#2351]
**Describe the bug**
With WooCommerce Admin enabled, WooCommerce Bookings won't activate (see the error message below). I have managed to activate the plugin by first disabling WooCommerce Admin, activating WooCommerce Bookings and then re-activating WooCommerce Admin. 

Does it seem like the WooCommerce Admin needs to check that the class exists before trying to use it?

**To Reproduce**
Steps to reproduce the behaviour:

1. Install and activate WooCommerce Admin
2. Upload WooCommerce Bookings
3. Click activate on WooCommerce Bookings

`Fatal error: Uncaught Error: Class 'WC_Bookings_Inbox_Notice' not found in /home/user/website.com/wp-content/plugins/woocommerce-bookings/woocommerce-bookings.php:69 Stack trace: #0 /home/user/website.com/wp-includes/class-wp-hook.php(286): woocommerce_bookings_activate('') #1 /home/user/website.com/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /home/user/website.com/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /home/user/website.com/wp-admin/plugins.php(177): do_action('activate_woocom...') #4 {main} thrown in /home/user/website.com/wp-content/plugins/woocommerce-bookings/woocommerce-bookings.php on line 69`

**Expected behaviour**
I expected the WooCommerce Bookings plugin to successfully activate.

**Comment by rrennick** [comment]
I'll leave this open for a follow up check but this will be fixed in the next release of the Bookings extension. 

There were instances where this error occurred without WCA being active so it's not clear that WCA is doing something that it shouldn't.

**Comment by joshuatf** [comment]
I think this error is stemming from Bookings and not wc-admin.  The class `WC_Bookings_Inbox_Notice` is used in Bookings before it's loaded.  The reason this occurs with wc-admin active is it adds in the admin notes feature via the `WC_Admin_Notes` class.

@gluetooth Using v1.14.5 of WC Bookings seems to resolve this for me.  Can you confirm this works for you as well?

**Comment by timmyc** [comment]
I'm not able to recreate this fatal when using Bookings v1.14.5 and WooCommerce Admin 0.13.2 so am going to close this out. @gluetooth feel free to reopen the issue if you are still having problems.
