### ISSUE TITLE
Fatal Error: Unhandled wc_get_order returning false

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2363]
**Describe the bug**

There are several instances of unexpected returned values of `wc_get_order` function calls.

This one can create the following fatal error. It should return `-1` for no order found.

https://github.com/woocommerce/woocommerce-admin/blob/af6a19c7016901cc647a77e83d8a8276a1e52590/includes/data-stores/class-wc-admin-reports-coupons-data-store.php#L359-L366

```
PHP Fatal error: Uncaught Error: Call to a member function get_type() on boolean in \plugins\woocommerce-admin\includes\data-stores\class-wc-admin-reports-coupons-data-store.php:362
```
Another potential instance here,

https://github.com/woocommerce/woocommerce-admin/blob/e79d8e058bd920f7f02d721d7f279e08ef1c0c47/includes/api/class-wc-admin-rest-reports-controller.php#L184

And there are two additional potential problems reported in this support comment, https://wordpress.org/support/topic/php-fatal-error-call-to-a-member-function-get_type-on-boolean/

**To Reproduce**

I'm not sure the best way to force these errors besides manipulating the code such that `wc_get_order` returns false.

**Expected behavior**

Errors and false returns from `wc_get_order` function calls should be handled gracefully.

**Comment by NicolasDorier** [comment]
We have this problem as well, it goes away as soon as we disable the plugin.

**Comment by pavlenex** [comment]
Happening [here](https://github.com/btcpayserver/woocommerce-plugin/issues/28) as well.
