### ISSUE TITLE
wc_admin_unsnooze_admin_notes is not removed after uninstalling the plugin

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#2364]
Reported by a user in the support forums:

> I disabled the WC Admin plugin but the wc_admin_unsnooze_admin_notes task continued to run and created over 100 rows in the posts table.

https://wordpress.org/support/topic/looks-nice-but-the-data-are-wrong/#post-11603273

**Comment by ConstantinSummer** [comment]
Hey - indeed - I have unsintall wp admin and still I get scedule actions by wc_admin_unsnooze_admin_notes ten of them every hour.. Please advice..

**Comment by psealock** [comment]
I just had a look over the code, and it should be functioning. Do you, by chance remember what version wc-admin you were running?

You can go to Tools > Scheduled Actions > Pending and remove recurring jobs if wp-admin is already removed.

I hope that helps.

**Comment by flaviuscalin** [comment]
Why is this plugin schedule and publish this post every hour: wc_admin_unsnooze_admin_notes ?

It creates hundreds and hundreds of entrys in posts table, and spams emails with safety plugins that notify about post updates. 

I DO NOT want to disable notifications about post updates, as it is a good safety measure. 

This plugin is non usable for this reasons.

**Comment by jeffstieler** [comment]
Hello @flaviuscalin,

> It creates hundreds and hundreds of entries in posts table, and spams emails with safety plugins that notify about post updates.

WooCommerce Admin uses Action Scheduler for background job processing. The current version of Action Scheduler bundled with WooCommerce uses a custom post type to manage the queue. If the safety plugins you're using can filter or exclude certain post types, turn off notifications for the `scheduled-action` post type.

Once Action Scheduler 3.0 is bundled with WooCommerce, or if you'd like to install the [3.0 Release Candidate](https://github.com/woocommerce/action-scheduler/releases), the custom post type will be replaced with dedicated database tables and will no longer trigger the post notifications.

We're sorry for any noise this has caused, but we're limited to the current storage mechanism of custom post types (many plugins and themes use custom post types, but WooCommerce Admin creates a lot more than the typical plugin when using Action Scheduler < 3.0).

**Comment by flaviuscalin** [comment]
Hello @jeffstieler,

Thank you for your response.
It is good to know the issue is about to be solved with an feature update release.

I will deactivate it for now, and reactivate when the new scheduler is out. 

Thank you.
