### ISSUE TITLE
No data population

### ISSUE THREAD

**Issue by SQLGuruZA** [woocommerce/woocommerce-admin#2370]
**Describe the bug**
Installed the Woo Admin plugin last week. Tried importing older orders, nothing displays on any dashboard. Have had new orders since the install, these new orders also not showing. Have tried using the "delete previously imported data" and selected Import everything - dashboard remains empty.

**Expected behaviour**
I would expect there to be some information displayed in all graphs.

**Settings**
WooCommerce Admin: 0.12.0
OS: 10.12.6 OS Sierra
Google Chrome: v74.0.3729.169(64 bit)
Wordpress Version: 5.1.1
WooCommerce: 3.6.4
Wordpress Theme: Porto
PHP Version: 7.2
mySQL: 5.6

**Comment by timmyc** [comment]
Hello there @SQLGuruZA - I'm sorry you are having problems importing historical data. By chance do you see any import jobs queued up inside the scheduled actions tab at `/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending` ? Also would you be willing to send along a system status report from `/wp-admin/admin.php?page=wc-status&tab=status`?

**Comment by SQLGuruZA** [comment]
**SCHEDULED ACTIONS**
<img width="1168" alt="Screen Shot 2019-06-06 at 18 17 35" src="https://user-images.githubusercontent.com/22474740/59049216-ce066980-8887-11e9-99f8-4def0d447d48.png">


**SYSTEM STATUS REPORT**


### WordPress Environment ###

WordPress address (URL): http://qcumber.co.za
Site address (URL): http://qcumber.co.za
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: ❌ 5.1.1 - There is a newer version of WordPress available (5.2.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_ZA
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.19-1+0~20190531112732.22+jessie~1.gbp75765b
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.40-MariaDB-1~jessie
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
Total Database Size: 488.68MB
Database Data Size: 308.37MB
Database Index Size: 180.31MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.13MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
smackuci_events: Data: 0.02MB + Index: 0.00MB
smackuci_history: Data: 0.02MB + Index: 0.00MB
wp_categorymeta: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 8.52MB + Index: 10.09MB
wp_eum_logs: Data: 0.02MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_member_catmeta: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 53.19MB + Index: 3.09MB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB
wp_portfolio_catmeta: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 142.69MB + Index: 122.30MB
wp_posts: Data: 78.59MB + Index: 29.25MB
wp_product_catmeta: Data: 0.02MB + Index: 0.00MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.05MB + Index: 0.00MB
wp_revslider_slides: Data: 0.05MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_sfa_abandoned_carts: Data: 0.33MB + Index: 0.00MB
wp_termmeta: Data: 0.11MB + Index: 0.11MB
wp_terms: Data: 0.08MB + Index: 0.09MB
wp_term_relationships: Data: 1.48MB + Index: 1.52MB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB
wp_ultimate_csv_importer_log_values: Data: 0.02MB + Index: 0.00MB
wp_ultimate_csv_importer_manageshortcodes: Data: 0.02MB + Index: 0.00MB
wp_ultimate_csv_importer_shortcodes_statusrel: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 0.20MB + Index: 0.20MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 9.52MB + Index: 11.58MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfblockediplog: Data: 0.06MB + Index: 0.00MB
wp_wfblocks7: Data: 0.05MB + Index: 0.05MB
wp_wfconfig: Data: 1.28MB + Index: 0.00MB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB
wp_wffilemods: Data: 3.52MB + Index: 0.00MB
wp_wfhits: Data: 1.02MB + Index: 0.20MB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB
wp_wfissues: Data: 0.02MB + Index: 0.06MB
wp_wfknownfilelist: Data: 1.52MB + Index: 0.00MB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB
wp_wflocs: Data: 0.02MB + Index: 0.00MB
wp_wflogins: Data: 0.05MB + Index: 0.03MB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB
wp_wfsnipcache: Data: 1.52MB + Index: 0.52MB
wp_wfstatus: Data: 0.11MB + Index: 0.09MB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB
wp_wpi_object_log: Data: 0.02MB + Index: 0.06MB
wp_yoast_seo_links: Data: 0.11MB + Index: 0.06MB
wp_yoast_seo_meta: Data: 1.48MB + Index: 0.00MB

### Post Type Counts ###

attachment: 769
block: 27
customize_changeset: 1
faq: 6
jetpack_migration: 2
nav_menu_item: 31
page: 17
post: 10
product: 400
product_variation: 70062
revision: 13
scheduled-action: 160028
shop_coupon: 7
shop_order: 51
shop_order_refund: 1
wpcf7_contact_form: 7
wpi_object: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (33) ###

Antispam Bee: by pluginkollektiv – 2.9.1
Contact Form 7: by Takayuki Miyoshi – 5.1.3
Display PHP Version: by David Gwyer – 1.5
Duplicate Page: by mndpsingh287 – 3.5
Dynamic Featured Image: by Ankit Pokhrel – 3.7.0
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.8
Instagram Slider Widget: by jetonr – 1.4.3
Jetpack by WordPress.com: by Automattic – 7.4
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.2
Kadence WooCommerce Email Designer: by Kadence Themes – 1.2.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.16 – Not tested with the active version of WooCommerce
Porto Theme - Functionality: by P-Themes – 1.3.10
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Slider Revolution: by ThemePunch – 5.4.8
Easy Updates Manager: by Easy Updates Manager Team – 8.0.5
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.15

Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.6.0
Woo Attributes Coupon: by Gaurav Nagpal – 2.2.0
Woo Discount Rules: by Flycart Technologies LLP – 1.7.15
WooCommerce Admin: by WooCommerce – 0.12.0
WooCommerce - Store Exporter: by Visser Labs – 2.0.2 – Not tested with the active version of WooCommerce
WooCommerce PayFast Gateway: by WooCommerce – 1.4.12
WooCommerce: by Automattic – 3.6.4
Wordfence Security: by Wordfence – 7.3.2
Yoast SEO: by Team Yoast – 11.3 – Not tested with the active version of WooCommerce
WP-Invoice: PDF: by Usability Dynamics
Inc. – 2.1.5

WP-Invoice: by Usability Dynamics
Inc. – 4.2.2

WP Sitemap Page: by Tony Archambeau – 1.6.1
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.0
WPSSO Schema JSON-LD Markup: by JS Morisset – 1.45.2
WPSSO Core [Main Plugin]: by JS Morisset – 4.31.2
YITH WooCommerce Ajax Product Filter: by YITH – 3.6.4
YITH WooCommerce Ajax Search: by YITH – 1.6.7

### Inactive Plugins (3) ###

Facebook for WooCommerce: by Facebook – 1.9.12 – Not tested with the active version of WooCommerce
WooCommerce Product Feed: by WebAppick – 3.0.36
WP Ultimate CSV Importer: by smackcoders – 5.6.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #207 - /shop/
Basket: #208 - /cart/
Checkout: #209 - /checkout/
My account: #210 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: https://www.portotheme.com/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 4.11.4
Parent Theme Author URL: http://www.portotheme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/content-product.php
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php


### Action Scheduler ###

Complete: 159,880
Oldest: 2019-05-09 08:50:50 +0200
Newest: 2019-06-06 17:19:27 +0200

Pending: 2
Oldest: 2019-06-06 18:19:27 +0200
Newest: 2019-06-13 08:58:09 +0200

Canceled: 145
Oldest: 2019-05-28 08:05:06 +0200
Newest: 2019-06-06 15:11:06 +0200

In-progress: 0
Oldest: –
Newest: –

Failed: 1
Oldest: –
Newest: –

`

**Comment by SQLGuruZA** [comment]
Any ideas yet as to why this might be happening??
I had our host increase our shared hosting RAM to 256Mb today, thinking it might just be that. I have used the "delete previously imported data" and selected Import everything again, still dashboard remains empty.

**Comment by rrennick** [comment]
@SQLGuruZA Check to see if you have pending scheduled actions with the group `wc-admin-data`.

**Comment by SQLGuruZA** [comment]
Actually, now that I check again (it is def different this time), yes - I have approx 225 scheduled tasks for group wc-admin-data

**Comment by rrennick** [comment]
@SQLGuruZA If they are pending then you will need to run them. Unless you have a large number of scheduled actions, the pending actions are an indicator that WP CRON isn't running.

**Comment by SQLGuruZA** [comment]
OK, I will give that a bash... I checked earlier, now there are around 178,129 items queued

**Comment by timmyc** [comment]
@SQLGuruZA if you have access to your server via ssh and can run WP CLI commands, that will help process the jobs quite a bit faster - [here are some docs](https://actionscheduler.org/wp-cli/) on how to do that.

**Comment by timmyc** [comment]
@SQLGuruZA just checking in to see if you are still having issues - or if we can help out further.

**Comment by kathl1** [comment]
I have the same problem. I don't understand the docs you have shared though. Why aren't they running like the other Cron Tasks?

**Comment by timmyc** [comment]
> I have the same problem. I don't understand the docs you have shared though. Why aren't they running like the other Cron Tasks?

@kathl1 by default ActionScheduler attempts to use WPCron to process the job queue - but some hosts or some users decided to disable WPCron. If that is the case, another worker process will need to be setup to process the job queue. The documentation [linked above](https://actionscheduler.org/wp-cli/) shows you how to run those processes via WP CLI.

A quick way to tell if this might be the case for you is by visiting `/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending` on your install and seeing if there are many pending jobs there.

**Comment by kathl1** [comment]
Wp Cron is not disabled by me or the host. Like I said other Cron actions are being executed.

**Comment by timmyc** [comment]
> Like I said other Cron actions are being executed.

Sorry I misunderstood you @kathl1 - so if you visit the ActionScheduler status page: `/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending` are all the jobs there still showing as "Pending" or have any completed?

**Comment by kathl1** [comment]
I do have several completed.

**Comment by timmyc** [comment]
> I do have several completed.

Thats good to hear, that means WP Cron is processing the jobs in ActionScheduler - how many pending jobs are there still? If you do have ssh access to your hosting env, running the jobs processor via WP CLI will run the jobs much quicker than the standard WPCron setup. In my testing I was able to populate 4k orders + 4k customers on some really slow shared hosting in under 5 minutes via WP CLI.

**Comment by kathl1** [comment]
1464... I can have acces but I have never done it before.

**Comment by timmyc** [comment]
@kathl1 understood! Well let me know if I can provide any assistance there. You can just let the wpcron based job runner process all the historical data import, but it will just take time depending on how many orders/customers you have on your install.

**Comment by kathl1** [comment]
So I am werking these manually step by step... if i understanding correctly it is importing every order seperatly. Is it correct that the argument the order is mentioned which is being imported? I do see the number of complete increasing but the pending number stays the same, it seems to recreate every time I complete one...

**Comment by rrennick** [comment]
> Is it correct that the argument the order is mentioned which is being imported?

Yes, that's correct.

> it seems to recreate every time I complete one...

How many orders do you have in your store & how many pending actions?

**Comment by timmyc** [comment]
Since the OP @SQLGuruZA hasn't commented back, I'm going to close this issue out. @kathl1 please feel free to open a new issue if you still need more assistance.
