### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WC_Admin_Loader' not found

### ISSUE THREAD

**Issue by anshu-mwb** [woocommerce/woocommerce-admin#2372]
**Describe the bug**
After Activating WooCommerce Plugin as well as WooCommerce Admin when you deactivate WooCommerce Plugin the Fatal Error is displaying.
Here is the Fatal Error-
Fatal error: Uncaught Error: Class 'WC_Admin_Loader' not found ...wp-content/plugins/woocommerce-admin/woocommerce-admin.php on line 137

**To Reproduce**
1. Just need to activate WooCommerce Plugin
2. Then Activate WooCommerce Admin Plugin
3. Now, Deactivate WooCommerce Plugin. 

On Deactivating WooCommerce plugin. You will get the Fatal Error.

**Expected behavior**
On deactivating the WooCommerce Plugin. It should deactivate without any Error message.

**Desktop:**

* OS: Linux mint 18
* Browser Mozilla Firefox
* Version: 67

**Comment by timmyc** [comment]
Thanks for the bug report @anshu-mwb - looks like this bug was fixed in #2226 and is no longer present in `master`. We should hopefully have a new release out with this fix included later this week.
