### ISSUE TITLE
I recently had an order in PHP and it completely messed up my WCAdmin charts

### ISSUE THREAD

**Issue by kwok0781** [woocommerce/woocommerce-admin#2381]
I had a user in the Philippines place an order to be shipped to Singapore.  Both billing and shipping addresses are in Singapore but since she was placing the order while she was in the Philippines, my Aelia currency converter charged her in PHP (Philppine Peso)

The order was billed for PHP2,278 and the payment gateway processed the payment in PHP2,278.  The reports in the original core WC shows the correct currency conversion.  However, the reports in WCAdmin seem to be showing SGD2,278 which is the incorrect amount.

**Comment by timmyc** [comment]
@kwok0781 a fix for this will need to be implemented in the Aelia extension itself - much like how they have added support for the existing Woo Core reports.
