### ISSUE TITLE
Please create a new role for fulfilment associate

### ISSUE THREAD

**Issue by kwok0781** [woocommerce/woocommerce-admin#2382]
Currently there is only a role for shopkeeper.  This person has full access to all orders

It would be great to have a role for fulfilment/packing. This user would only see orders in their territory (US fulfilment should only see US orders, UK Fulfilment should only see UK orders, etc.).  The fulfilment role should not have permission to change settings in WooCommerce. They should not be able to edit orders outside of their territory and they should not be able to see reports outside of their territory (and we should also have the option to disable them from seeing reports all together).

**Comment by dreiris** [comment]
Hello! Thank you for the feedback and idea! This ticket is being closed and the feature request is being moved to a backlog. The feature will be evaluated with other feature requests and prioritized.
