### ISSUE TITLE
Shop Managers should have access to the dashboard, activity panel, and analytics.

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-admin#2386]
**Is your feature request related to a problem? Please describe.**

The shop manager role should have access to all the new features in WooCommerce Admin.

Shop manager currently have access to reports in WooCommerce https://docs.woocommerce.com/document/roles-capabilities/. Removing their access would be a departure, I'm sure this is just an oversight.

**Comment by rrennick** [comment]
This sounds like a regression on #2211.

**Comment by jeffstieler** [comment]
I don't think #2211 was ever released: https://github.com/woocommerce/woocommerce-admin/compare/v0.12.0...master

**Comment by timmyc** [comment]
Correct Shop Managers can access the Dash/reports in `master` and will be released in v0.13.0, likely tomorrow.

**Comment by squaremunkeygist** [comment]
Only admin roles seem to have access to new woo analytics. Is there a possibility to have a user role to just have access the woo analytics without having complete admin rights or at least have access to this in the user roles plugins like members or user role editor.

**Comment by rrennick** [comment]
Shop managers will have access to the new dashboard and analytics in version 0.13.0 when it is released.

**Comment by fluxpixel** [comment]
Just updated to 0.16.0 today and this problem still remains. It makes no sense to block reports to shop manager role

**Comment by rrennick** [comment]
Have you edited your shop manager role permissions? The capability required for accessing WC Admin is `view_woocommerce_reports`.

**Comment by fluxpixel** [comment]
Thanks for the hint @rrennick . I was giving permissions to the analytics tab but there´s also a dashboard tab inside the shop. After giving permissions to the dashboard tab the analytics is now working for shop manager. Cheers
