### ISSUE TITLE
Fatal Error on frontend: undefined function get_current_screen

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-admin#2390]
Seeing a fatal error on all front-end pages with the current master.

> PHP Fatal error:  Uncaught Error: Call to undefined function get_current_screen() in /woocommerce-admin/includes/page-controller/class-wc-admin-page-controller.php:220

**To Reproduce**

Turn on debug mode:

```php
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG', true );
```

1. Load any frontend page
2. See error in the footer, and/or in your `wp-content/debug.log` file.

**Comment by rrennick** [comment]
I wasn't successful in reproducing this in my install. @ryelle What theme & other plugins did you have active?

**Comment by ryelle** [comment]
Looks like it's only happening when WooCommerce Blocks is active, and specifically [this branch.](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/613)

**Comment by ryelle** [comment]
I'm guessing it's because we're now calling `apply_filters( 'woocommerce_components_settings', $settings )` [on the frontend,](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/613/files#diff-c4deece14f2cd904e2689e9b910a1d04R57) which is unexpected.

I think I can change this so we don't need `wcSettings` on the frontend - I'm pretty sure the frontend script doesn't need to rely on any woocommerce components. I'll close this if that's the case 👍

**Comment by ryelle** [comment]
Verified that this was due to trying to set `wcSettings` on the frontend, which we shouldn't need to do since the @woocommerce/* packages should stay as "admin-only" use. Closing this as it's not really an issue with woocommerce-admin.
