### ISSUE TITLE
thousands of scheduled actions 

### ISSUE THREAD

**Issue by ErikMWP** [woocommerce/woocommerce-admin#2392]
**Describe the bug**
Action Scheduler contains 178.880 completed action statusses, mostly wc-admin-notes or wc-admin-data scheduled actions.

Similarly WP-Postmeta, WP-Post and WP-Comments contain 100'000-500'000 rows of action scheduler items. Despite wc-admin plugin deleted data/actions are not deleted.

How to remove these actions and/or rows from my installation.

**Comment by lukecav** [comment]
Do you want to delete all Scheduled Action posts and comments?

`wp post list --field=ID --post_type=scheduled-action --posts_per_page=1000 --post_status=trash | xargs wp post delete --force`

`wp post list --field=ID --post_type=scheduled-action --posts_per_page=1000 --post_status=cancel | xargs wp post delete --force``

**Comment by rrennick** [comment]
@ErikMWP If you are okay with removing all of your completed and cancelled scheduled actions you can use 

`add_filter( 'action_scheduler_retention_period', '__return_zero' );` 

Then remove that line when the WooCommerce Admin actions have been deleted.

**Comment by ErikMWP** [comment]
@lukecar @rrennick thank you both for the feedback. I'll try both suggestions and provide feedback.

**Comment by timmyc** [comment]
@ErikMWP I'm going to close out this issue since we haven't heard back from you. Please feel free to re-open if you are still having problems.
