### ISSUE TITLE
Revenue count and order count are incorrect when 2 or more coupons applied to an order

### ISSUE THREAD

**Issue by stevezehngut** [woocommerce/woocommerce-admin#2400]
Description: The gross revenue and order count are not calculated correctly. This happens when more than one coupon is applied to an order. 

To Reproduce:
The following steps assume that WooCommerce and WooCommerce Admin are installed. I am using Stripe Gateway, but any gateway will do. I started with a fresh install.
1. Create a simple product called "widget" with a price of $10.
2. Create a coupon called "oneoff" with a "fixed cart discount" and a value of $1.
3. Create another coupon called "twooff" with a "fixed cart discount" and a value of $2.
4. Add a single "widget" to an empty cart with no coupon added. The cart total is $10. Complete the purchase.
5. Add a single "widget" to an empty cart with one "oneoff" coupon added. The cart total is $9. Complete the purchase.
6. Add a single "widget" to an empty cart with one "oneoff" coupon and one "twooff" coupon added. The cart total is $7. Complete the purchase.
7. Go to WooCommerce -> Orders. The total of the three orders is $26 ($10+$9+$7)
8. Complete all orders.
9. Go to Analytics->Revenue. The gross revenue displays as $33. In the revenue table, it displays 4 orders.
10. Go to Analytics->Orders. The orders count displays as 4. The net revenue displays as $33. In the orders table, it displays 3 orders and the net revenue adds up to $26.

Expected behavior: The gross revenue and net revenue should be $26. The order count should be 3, not 4.

Screenshots: attached

Desktop:
OS: Mac 10.14.5
Browser: Chrome
Version: 74.0.3729.169

WordPress: version 5.2.1
WooCommerce: Version 3.6.4
WooCommerce Admin: Version 0.12.0

Additional context:
The SQL query that gets generated in class-wc-admin-reports-orders-data-store.php looks similar to this:

_SELECT
	SUM( CASE WHEN wp_wc_order_stats.parent_id = 0 THEN 1 ELSE 0 END ) as orders_count, 
	SUM(wp_wc_order_stats.num_items_sold) as num_items_sold, 
	SUM(wp_wc_order_stats.gross_total) AS gross_revenue, 
	SUM(discount_amount) AS coupons, 
	COUNT(DISTINCT coupon_id) as coupons_count, 
	ABS( SUM( CASE WHEN wp_wc_order_stats.gross_total < 0 THEN wp_wc_order_stats.gross_total END ) ) AS refunds,
	SUM(wp_wc_order_stats.tax_total) AS taxes, 
	SUM(wp_wc_order_stats.shipping_total) AS shipping, 
	SUM(wp_wc_order_stats.net_total) AS net_revenue
FROM
	wp_wc_order_stats
LEFT JOIN
	wp_wc_order_coupon_lookup ON wp_wc_order_coupon_lookup.order_id = wp_wc_order_stats.order_id
WHERE
	1=1
AND wp_wc_order_stats.date_created <= '2019-06-10 23:59:59' 
AND wp_wc_order_stats.date_created >= '2019-06-10 00:00:00'
AND ( wp_wc_order_stats.status NOT IN ( 'wc-trash','wc-pending','wc-failed','wc-cancelled' ) )_

I believe the problem exists . in the LEFT JOIN. The way this SQL query is written, the join creates an extra row because there are two records in the wp_wc_order_coupon_lookup table.

**Comment by stevezehngut** [comment]
Screenshots
![screencapture-wooadmin-dev-wp-admin-admin-php-2019-06-11-22_03_13](https://user-images.githubusercontent.com/4950846/59326328-1912e900-8c9b-11e9-966e-f8b1d5684108.png)
![screencapture-wooadmin-dev-wp-admin-admin-php-2019-06-11-22_03_27](https://user-images.githubusercontent.com/4950846/59326333-1ca67000-8c9b-11e9-8b3a-bda33cb7634c.png)

**Comment by stevezehngut** [comment]
Just to give a bit more detail, the order with the additional coupon is being counted twice. If you add an order with three coupons, the order will be counted three times.

**Comment by psealock** [comment]
Thanks reporting @stevezehngut! And for the great detail and steps to reproduce. I'll add it to our backlog so we can address it soon.

**Comment by joshuatf** [comment]
Thanks for the awesome outline @stevezehngut!  I was able to reproduce the issue and it seems like all stat numbers are thrown off when multiple coupons are in any given order.

This may be more complicated than the quick fix I was hoping it would be and I don't think I can tackle this today, so I'll leave some notes here and unassign myself for now in case any else wants to take a stab at this:

### The issue

An `INNER JOIN` is only going to grab orders that have coupons and excluded orders without coupons, so the existing `LEFT JOIN` is probably correct.  However, that will return the same order row twice (and all of its aggregated stats) for any order that contains multiple coupons.

Removing the join or creating a subquery is tempting, but the join is also useful to filter orders that include/exclude given coupon filters.

### Possible Solution

It might be possible to map and aggregate the results in PHP.  If we `GROUP by order_id` we'll get accurate stats for the totals.  Then in PHP we can loop over, sum/avg/count stats and return that object.

However, this will create some difficulties with the intervals that rely on aggregated data grouped by time intervals.
