### ISSUE TITLE
Changing revenue per page clears some row

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2406]
**Describe the bug**
Changing the rows per page on the revenue report existing rows with revenue were set to zero.

**To Reproduce**

1. Go to Analytics -> Revenue
2. Change the date range to include visible rows with revenue
3. Change Per Page to 50
4. Check the original visible rows with revenue.

**Expected behavior**
Existing rows should not be affected by pagination changes.

**Screenshots**
On Load
<img width="1137" alt="Screen Shot 2019-06-12 at 11 32 25 AM" src="https://user-images.githubusercontent.com/343847/59371559-bca3de00-8d1b-11e9-9d96-2e31f885ce7e.png">

After changing per page
<img width="1138" alt="Screen Shot 2019-06-12 at 11 32 55 AM" src="https://user-images.githubusercontent.com/343847/59371575-c9c0cd00-8d1b-11e9-846a-840d16a209a8.png">

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Chrome
* Version 74.0.3729.169

**Comment by joshuatf** [comment]
I wasn't able to reproduce this issue in my environment.  Any other factors you can think of to recreate this @rrennick?

**Comment by rrennick** [comment]
The affected order was a subscription renewal order. I'll do some further investigation.

**Comment by rrennick** [comment]
I'm going to close this one. I haven't been able to reproduce it with newly imported analytics data.
