### ISSUE TITLE
Widget on the initial dashboar and conversion rate.

### ISSUE THREAD

**Issue by brunoborges92** [woocommerce/woocommerce-admin#2415]
There are two features that are very important, the first is the addition of a Widget in the initial wordpress dashboard, the second would be to add the conversion rate of the requests, just like other ecommerce templates have.

**Comment by timmyc** [comment]
This feature would be dependent upon having Jetpack or a similar stats solution in place that tracks the number of visitors to the site. 

> addition of a Widget in the initial wordpress dashboard

@brunoborges92 can you expand on this a bit further? What widget are you looking to add to the default wp-admin dashbaord?

**Comment by brunoborges92** [comment]
@timmyc It would be something like the current woocommerce standard that shows the net sales of the month https://ibb.co/BjLLFsv but showing the net sales of the current month and the previous month, and the number of net sales of the day and yesterday.

**Comment by timmyc** [comment]
Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
