### ISSUE TITLE
Dashboard and all other section are blank

### ISSUE THREAD

**Issue by relogical** [woocommerce/woocommerce-admin#2416]
After upgrading to the latest version today the dashboard in Analytics loads but after it loads it flickers with data and then becomes blank. Here is the error from my error file:

WordPress database error Unknown column 'is_primary' in 'field list' for query SELECT action_id, name, label, query, status, is_primary
FROM _VZC_wc_admin_note_actions
WHERE note_id = 7 made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WC_Admin_REST_Admin_Notes_Controller->get_items, WC_Admin_Notes::get_notes, WC_Admin_Note->__construct, WC_Data_Store->read, WC_Admin_Notes_Data_Store->read, WC_Admin_Notes_Data_Store->read_actions

**Comment by psealock** [comment]
Thanks for opening the issue @relogical. A fix has been made and released with `0.13.2` a few hours ago.
