### ISSUE TITLE
Order import count discrepancies

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2427]
**Describe the bug**
On historical import, I'm seeing 284 orders to be imported.  After importing, I see 275 that were imported.  In my WooCommerce Orders page, I see 215.

At first glance, this may be due to the order status and/or refunds which are also stored in the order stats table.  But the estimated number should probably match up or come close to the actual number imported.

**To Reproduce**

1. Delete all import data.
2. Import orders.
3. Note the amount to be imported.
4. Note the actual number imported.
5. Note the number of orders at `wp-admin/edit.php?post_type=shop_order`

**Expected behavior**
Expected to see an accurate number of orders to be imported.

**Screenshots**
<img width="638" alt="Screen Shot 2019-06-14 at 4 53 49 PM" src="https://user-images.githubusercontent.com/10561050/59497855-d5042c00-8ec6-11e9-8b42-385a1549f422.png">
<img width="594" alt="Screen Shot 2019-06-14 at 5 07 25 PM" src="https://user-images.githubusercontent.com/10561050/59497903-ecdbb000-8ec6-11e9-9ddf-d0de56ae5f3a.png">
<img width="310" alt="Screen Shot 2019-06-14 at 5 07 13 PM" src="https://user-images.githubusercontent.com/10561050/59497904-ecdbb000-8ec6-11e9-99cd-f247c5b69d05.png">

**Comment by rrennick** [comment]
The WC orders table only has a count of original orders. The import screen shows a count of orders + number of orders with refunds. 

Possibly a wording change would better address this as the order stats record count in my install matches the number shown on the progress bar.
