### ISSUE TITLE
Add product ID Column to Products and Stock Report

### ISSUE THREAD

**Issue by apkruger** [woocommerce/woocommerce-admin#2430]
This is **NOT** a Bug or Problem but a **feature request**.

**Problem:**
We have a store with lots of products and variations and have lots of different providers we purchase our products from, some of the providers offer a similar "Name/SKU" but the product is different so we use the Product "ID" to calculate sales or do product stock reports so that we can re-order or workout which providers product sells better.

**Requested Option:**
Will it be possible to add the "ID" Column as an Option to display/download in the below reports.

- Products Report:
Under the Products report, an admin must also be able to select the "ID" (Column) as an additional field to display when viewing or when downloading the report.

- Stock Report:
Under the Stock report, an admin must also be able to select the "ID" (Column) as an additional field to display when viewing or downloading the report.

**Current Method we are using**
We currently have to extract the products and variations in different methods and using vlookup to generate our reports. It would be a great feature for us if this could be added.

**Could this be a bigger Feature for more people?**
Maybe this feature could be extended and offer the Woocommerce admin an option to add a few extra Default Database Columns to any report during the Analytics installation "Setup" or "Settings". 

**Appreciation:**
I know this is a low down feature in your priorities but appreciate the effort in the already great Woocommerce Admin Interface, this is really making our lives easier. Great Work!!
![add-id-as-option-to-columns](https://user-images.githubusercontent.com/44058773/59506015-72e7fe80-8ea7-11e9-893b-d09e5aa030e9.png)
![id-for-products-report](https://user-images.githubusercontent.com/44058773/59506047-898e5580-8ea7-11e9-8e60-f86838f335b8.png)
![id-for-stock-report](https://user-images.githubusercontent.com/44058773/59506055-90b56380-8ea7-11e9-90c8-7fbca2f79189.png)

**Comment by psealock** [comment]
Thanks for writing this feature request @apkruger. Including the ID is not currently on our design roadmap. However, the tables are missing the ability to be extended, which will allow you to add columns of your choosing.

I'm moving this issue to the backlog so that we can address the extensibility issue and provide an example of how you might add an ID column.

**Comment by apkruger** [comment]
@psealock thank you very much for your feedback, appreciate your time. Looking forward to using the table extended feature and sample extension for the future :)

**Comment by apkruger** [comment]
@psealock sorry to bug you, I just wanted some advice. I see you have already logged an issue regarding the "Extend columns" #2440 and completed some work. I don't know how the Development/QA and release process work with Woocommerce but wanted to get some idea of timelines. We recently purchased a reporting Plugin (https://codecanyon.net/item/advanced-woocommerce-reporting-/12042129). The only issue I had with the Codecanyon plugin was that it did not show the ID's. The developer now quoted us $110 US to add the ID's, which I thought is a bit much.

During this process, I found the Woocommerce Admin plugin and asked the ID question. I would like to ask if you can give me any idea how long you think it will take before your change makes it into a production release because if it is not too long, I will postpone the extra development costs on our current plugin and wait for table option to be available.

Sorry for the long text but would appreciate your advice.

**Comment by psealock** [comment]
All good @apkruger. I got feedback in the pull request (https://github.com/woocommerce/woocommerce-admin/pull/2440#pullrequestreview-250883307) that the functionality already exists. I'll update the example in the code to use the functionality already present, you can follow along on that progress.

That should help you create your own extension right away when you need it.

**Comment by apkruger** [comment]
Great thanks @psealock, appreciate the help! After some data validation last night we found the Codecanyon Plugin we purchased is really inconsistent so really happy I managed to speak to you! 
Do you work on Woocommerce full time and do you perhaps do private work dev work, would really like to hire someone that knows Woocommerce as we need some basic report work done, that is if you have spare time available. If you are able and interested my email is andrek @ madbox.co.za or if you know of someone that can help us.

**Comment by psealock** [comment]
@apkruger I'm all set on the job front, but thank you!

I added an example extension that adds an ID column to the products report, as well as a product rating, in https://github.com/woocommerce/woocommerce-admin/pull/2440. The filter it uses already exists, so you can use that code as an example to extend the product table in your project.

I'm glad this is helpful!

**Comment by apkruger** [comment]
Great, thanks again Paul! And congrats with Cricket victory over SA, unfortunately, we all sad :(
