### ISSUE TITLE
Min/Max Quantities for products

### ISSUE THREAD

**Issue by KhalilGit** [woocommerce/woocommerce-admin#2434]
Please add min/max product quantity functionality within woocommerce instead of a premium extension as doesn't worth $29.00 for a single site. Please review this.

**Comment by timmyc** [comment]
Hello there @KhalilGit - I believe you are asking about this extension: https://woocommerce.com/products/minmax-quantities/

This code repository is for the WooCommerce Admin extension and issues/feature ideas related to it: https://wordpress.org/plugins/woocommerce-admin/

I'm going to close out this issue as it is not relevant to the work happening here.
