### ISSUE TITLE
Replace current notices with snackbars

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#2445]
From https://github.com/woocommerce/woocommerce-admin/issues/2175#issuecomment-493070920

> For the notices we are using the Material snackbar design aligned to the center to page without the wp-admin sidebar. 
> 
> https://material.io/design/components/snackbars.html#
> 
> This should override the notices style we were using before, one example is in the Analytics settings:
> 
> ![Screenshot 2019-05-15 at 10 52 25](https://user-images.githubusercontent.com/57050/57852333-cf89c800-77da-11e9-9789-9440dddd48b3.png)

Gutenberg `<Snackbar>` component can be found here:

https://github.com/WordPress/gutenberg/tree/master/packages/components/src/snackbar

**Comment by justinshreve** [comment]
This is something that we need for the onboarding task list as well.
