### ISSUE TITLE
Settings: Form is confusing, no warning if settings not saved

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2449]
With the addition of the Historical Data Import to the settings page, the form for the settings seems a bit confusing to me now:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/22080/59690965-21858b00-9197-11e9-99b3-39df9554af83.png">

Due to the way the fieldsets on this page are structured - to me it seems like the save/reset buttons are just for the Default Date range. 

Perhaps if we created another `woocommerce-section-header` for the historical data import, it might visually make the action buttons appear tied more to all the settings.

Another item noted in testing is if you modify a setting and do not save - you can navigate away from the page and not be warned that your changes have not been saved.

**Comment by timmyc** [comment]
@jameskoster any thoughts here?

**Comment by jameskoster** [comment]
> Perhaps if we created another woocommerce-section-header for the historical data import, it might visually make the action buttons appear tied more to all the settings.

The the lack of separation between the settings and the importer is the main issue here.

Until we take a broader look at setting screen designs I think adding a header for the importer, or even just a horizontal rule beneath the save buttons would help a lot.
