### ISSUE TITLE
Analytics: Allow Compare To Date to be Optional

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2451]
From [the forums](https://wordpress.org/support/topic/feature-request-make-compare-to-optional/) a few users have asked for the "Compare To" part of the date picker to be optional.

> Although there is one small tweak I’d like to suggest. Please make the “compare to” option in the date picker optional. I love having this feature sometimes, but I don’t understand why it is always visible.

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
