### ISSUE TITLE
Settings: Allow header bar to be disabled

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2453]
Requested via [the fourms](https://wordpress.org/support/topic/remove-sticky-header-5/)

> Hi, is there a way to remove the sticky breadcrumbs header?

![image](https://user-images.githubusercontent.com/22080/60993433-4dfa7600-a303-11e9-9c0e-8d9fc941772e.png)

**Comment by timmyc** [comment]
Given that the nav header and activity panels are a central part of the new design/experience, I feel we should icebox this request and see how often it is requested.

**Comment by dreiris** [comment]
Since the nav header and activity panels are a central part of the new design/experience, we will not make disabling the header an option.
