### ISSUE TITLE
Stock Panel Collapsed

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#246]
Child Issue of #245 

Time to get the Stock Panel showing some actual good stuff! I believe most of the child components are available to present some real data within the stock panel.

Designs: [inVision](https://automattic.invisionapp.com/d/main#/console/14698454/305632621/preview)

![image](https://user-images.githubusercontent.com/22080/43349993-996197de-91b8-11e8-9c3f-ac844c131591.png)

This issue involves building out a Stock Panel card in the "collapsed" state for all viewport sizes.

**Comment by timmyc** [comment]
@Aljullu - sorry if I missed a PR on this one, but it appears this still needs to be worked on? Do you want to keep this assigned or free it up while you are working on negative charts? Or is there a blocker that I don't know about on this issue ( likely )?

**Comment by Aljullu** [comment]
@timmyc I started looking into this, but during my porter week couldn't do much. After it, I saw @jeffstieler started working on #247, so in order to avoid making duplicate work, I left this one on hold.

I'm completely ok if somebody else wants to take it. :+1:
