### ISSUE TITLE
Out of stock products are not appearing in the Stock Activity Panel

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#2466]
Reported in the forums: https://wordpress.org/support/topic/show-all-product-in-stock-o/

**To Reproduce**
1. Change a product stock level to 1 and its low stock threshold to 5.
2. Reload the page and verify it appears in the Stock Activity Panel.
3. Change the stock level of the same product to 0.
4. Reload the page and notice it doesn't appear in the Stock Activity Panel anymore.

**Expected behavior**
Out of stock products should appear in the Stock Activity Panel.

**Additional context**
I guess this bug is related to this line:
https://github.com/woocommerce/woocommerce-admin/pull/2191/files#diff-012c0dbbe65e527ee16ac3c5f83ab6cfR134
So, when fixing this issue, we should make sure we don't break the fixes introduced in that PR.

**Comment by psealock** [comment]
I can reproduce this one. It seems only low-stock is showing up, not zero stock
