### ISSUE TITLE
Stock Panel Update Inventory

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#247]
Child issue of #245 

Designs: [inVision](https://automattic.invisionapp.com/d/main#/console/14698454/305632621/preview)

![image](https://user-images.githubusercontent.com/22080/43350036-f3d9347e-91b8-11e8-9bda-a53fbf367511.png)

This task involves building out the state/view of the stock panel card where users can update inventory. This task should also involved building out the requisite API calls to actually update the product/variant inventory.

**Comment by jeffstieler** [comment]
This issue also includes hooking up the stock panel to display low/out of stock items. Dependent on https://github.com/woocommerce/woocommerce-admin/pull/1866

**Comment by timmyc** [comment]
Thanks for adding that in @jeffstieler, and sorry for botching that on issue creation
