### ISSUE TITLE
posts from the Action Scheduler with the post title of wc-admin_import_order floods reported

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce-admin#2473]
https://wordpress.org/support/topic/database-flooding/
https://wordpress.org/support/topic/over-170-000-scheduled-action-created/

Two mentions where a flood of the `wc-admin_import_order` posts are being created on sites where WooCommerce Admin is installed.

**Comment by rrennick** [comment]
@lukecav The code in your response won't remove the scheduled actions

```
wp post delete $(wp post list --post_type='wc-admin_import_order' --post_status=trash --format=ids --force)
```

Scheduled actions post type is `scheduled-action`. The post title for the target actions is `wc_admin_import_order`.

```
wp post delete $(wp post list --post_type='scheduled-action' --post_title='wc_admin_import_order' --format=ids) --force
```

If possible, can you edit your post and update the command?

**Comment by lukecav** [comment]
Could not edit the response so left one after with the corrected WP-CLI command.

**Comment by rrennick** [comment]
I'm closing this one as there are Action Scheduler PRs already in progress to mitigate this in the future. See #1528

**Comment by mujuonly** [comment]
Is this issue resolved?

**Comment by rrennick** [comment]
@mujuonly As of version 3.0 Action Scheduler no longer uses the posts table.
