### ISSUE TITLE
Onboarding - Task List: Store Connection

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2476]
Blocked by https://github.com/woocommerce/woocommerce-admin/issues/2445

The “Connect your store to WooCommerce.com” step should display if the merchant purchased extensions during the profiler step, but did not connect their store.

We can look at `woocommerce_onboarding_profile_properties` to see if they purchased products / themes, and if  `items_purchased` is false.

The actual implementation of this onboarding step will be handled on WooCommerce.com since it deals with sign-in/authentication/and the installation worker.

We need to work with Alpha / WCCOM to make sure they get passed to the right connection flow, and make it back to the task list after.

This task also involves showing a Snackbar notification after successful connection.

<img width="822" alt="Screen Shot 2019-06-21 at 4 12 11 PM" src="https://user-images.githubusercontent.com/10561050/59908176-5f0c4180-943f-11e9-831c-503928d6c6c1.png">

**Comment by justinshreve** [comment]
This is no longer blocked by the snackbar issue.
