### ISSUE TITLE
Onboarding - Task List: Installing Extensions

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2477]
After a store is successfully connected (i.e., store owner has logged in), they are redirected back to their site to install extensions.

This step will involve receiving extension data, downloading to the site, and activating those extensions.

Alpha has a near working implementation of this so this may just be a matter of hooking things up to that API.

@mattyza When you have a working example of this, would you mind posting a link to that code here?

<img width="780" alt="Screen Shot 2019-06-21 at 4 18 39 PM" src="https://user-images.githubusercontent.com/10561050/59908681-8b748d80-9440-11e9-87ac-6814af601763.png">

**Comment by mattyza** [comment]
Sure thing, @joshuatf. We're looking to start the build on this screen in the next 2 weeks.

**Comment by pmcpinto** [comment]
@joshuatf I just noticed that there was this issue after I created a similar for this Task: https://github.com/woocommerce/woocommerce-admin/issues/2669

I'm going to delete the one that I created and add here the acceptance criteria as a comment. I think it might help. Sounds good?

**Comment by joshuatf** [comment]
@pmcpinto Sounds good!  Go for it.

**Comment by pmcpinto** [comment]
**Acceptance Criteria:**
- If the user clicks on "Purchase extensions later" in the Cart [step](https://www.figma.com/file/b0b2CrxPZz0i1aAPuv985tvK/Store-Profiler?node-id=1150%3A1386), it's necessary to add an additional task to the task list.
- In the Task List, if the user clicks in the "Purchase and Install extensions" task he should be directed again to the cart step.
- If the user completes the checkout that Task should be removed from the List
- If the user [empties the cart](https://www.figma.com/file/xyKPRZ73kKhDyNjwbFvBJR/Task-List?node-id=1218%3A47) and returns to the Task list, that task sould be removed from the List

**Links:**
Figma [mockup](https://www.figma.com/file/xyKPRZ73kKhDyNjwbFvBJR/Task-List?node-id=1091%3A45562)

**Comment by mattyza** [comment]
> @mattyza When you have a working example of this, would you mind posting a link to that code here?

@joshuatf - Alpha have a working version of the install screen [here](https://github.com/Automattic/woocommerce.com/blob/master/plugins/wccom-plugins/in-app-purchase/templates/install.php). We're working on triggering the actual install at the moment, and will look into a video walkthrough once the installation is hooked up.
