### ISSUE TITLE
Onboarding - Task List: Manage Connection

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2478]
After a connection has been made, a popover component is shown under the user avatar in the header.

@jameskoster Where should the "Manage Connection" button link to?

<img width="409" alt="Screen Shot 2019-06-21 at 4 28 19 PM" src="https://user-images.githubusercontent.com/10561050/59909150-98de4780-9441-11e9-85a8-979249878d7a.png">

**Comment by jameskoster** [comment]
I think we can leave/close this for now. Depending on where we go with the navigation implementation will impact how that feature behaves.
