### ISSUE TITLE
Onboarding - Task List: Configure Shipping

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2482]
This step involves first saving a store address, if one is not already set.  If a store address is already step, this part of the step is skipped and continues to the shipping step.

<img width="623" alt="Screen Shot 2019-06-21 at 4 50 07 PM" src="https://user-images.githubusercontent.com/10561050/59910534-bbbe2b00-9444-11e9-96df-a80a15d1d4dc.png">

The next part of the step involves setting shipping zones and prices.  This will 2 shipping options:
* The store's country
* Rest of the world

@jameskoster this interface only provides flat rate shipping options unless they manually go to a separate settings page, right?

<img width="747" alt="Screen Shot 2019-06-21 at 4 54 00 PM" src="https://user-images.githubusercontent.com/10561050/59910786-32f3bf00-9445-11e9-82f8-702c75d3af7d.png">

**Comment by jameskoster** [comment]
> @jameskoster this interface only provides flat rate shipping options unless they manually go to a separate settings page, right?

Correct. This is what we've done on Store on WP.com and our data suggests that it's adequate. Only ~2.5% of customer actually go and create custom shipping rules during setup.
