### ISSUE TITLE
Core: Add wc-admin as Featured Extension in OBW

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2485]
The goal of this issue is to encourage more usage of WooCommerce Admin with inclusion of the plugin as a "Recommended Feature"

<img width="723" alt="recommended-features" src="https://user-images.githubusercontent.com/22080/59940013-69faae00-940e-11e9-8c38-963c2040fdb4.png">

This work will happen in the Woo core repository, but figured tracking in an issue here might make the most sense. For design/text details please refer to related conversation here p90Yrv-16T-p2

**Comment by psealock** [comment]
This is being worked on in https://github.com/woocommerce/woocommerce/pull/24058

**Comment by psealock** [comment]
https://github.com/woocommerce/woocommerce/pull/24058 has been merged, so I’ll close this one out.
