### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kenflobooking** [woocommerce/woocommerce-admin#2500]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Should this be prioritized? Why?**

**Additional context**

**Comment by arunsathiya** [comment]
It looks like this was submitted in error, with the default placeholder template. I am closing this report.

Feel free to submit new bug reports/feature requests from [this page](https://github.com/woocommerce/woocommerce-admin/issues/new/choose), and while doing so, make sure to fill in the details as well. Thank you!
