### ISSUE TITLE
Permission Error when accessing reports

### ISSUE THREAD

**Issue by ThomasSultana** [woocommerce/woocommerce-admin#2504]
Hi, Im having an issue on a multisite environment. The WooCommerce Admin plugin is not displaying the report pages to admins. (Super admins work fine).

The error im receiving is: "Sorry, you are not allowed to access this page.". Which is displayed using the `wp_die` function. This triggers because the `user_can_access_admin_page` function is returning false. I looked into that function and found the following:

```
$hookname = get_plugin_page_hookname( $plugin_page, $parent );

if ( ! isset( $_registered_pages[ $hookname ] ) ) {
    return false;
}
```

The issue is that $hookname is returning: `admin_page_wc-admin` whilst inside the `$_registered_pages` array the matching page is registered as `woocommerce_page_wc-admin`.

When im logged in as a super admin the `$hookname` is returning `woocommerce_page_wc-admin`. Which is correct and matches the `$_registered_pages` array.

The url im using to access the reports is: /wp-admin/admin.php?page=wc-admin#/analytics/revenue

The Menu items appear so i can click on a report from the menu however i then get the above error.

**Comment by rrennick** [comment]
@ThomasSultana Thanks for reporting this. I'll see if I can reproduce this in my dev install.

**Comment by rrennick** [comment]
> The WooCommerce Admin plugin is not displaying the report pages to admins.

I tested the latest version with an Administrator account (not a super admin) on my install and the account has access to the Analytics pages.

The code you referenced looks like it's the core WP menu handling. Can you provide us with more information

- where you are encountering this: main site or sub site
- does the Admin account have access to all the WC core admin screens
- could you provide the active plugin list from the status report on the site where you have the issue

**Comment by ThomasSultana** [comment]
@rrennick Firstly thanks for investigating this. Please find replies below:

1. Sub Site.
2. Yes the admin can see all the WC core admin screens including settings. Just that once they are clicked it takes me to the error page. 
3.

### Active Plugins (44) ###

Gravity Forms: by rocketgenius – 2.4.9.5
Conditional Payments for WooCommerce: by Lauri Karisola / WooElements.com – 1.0.3
Gravity Forms User Registration Add-On: by rocketgenius – 4.1.1
Mollie Payments for WooCommerce: by Mollie – 5.1.8
Multiple Roles: by Florian TIAR – 1.2.0
Payment Gateways by User Roles for WooCommerce: by Algoritmika Ltd – 1.1.1
reBusted!: by Simon Prosser – 1.1
Tawk.to Live Chat: by Tawkto – 0.3.8
WooCommerce Blocks: by Automattic – 2.1.0
WooCommerce Admin: by WooCommerce – 0.14.0
WooCommerce Shipment Tracking: by WooCommerce – 1.6.12 – Not tested with the active version of WooCommerce
Custom Product Tabs for WooCommerce: by YIKES Inc. – 1.6.10
Child Theme Configurator: by Lilaea Media – 2.4.4
WooCommerce: by Automattic – 3.6.4
WooCommerce Multilingual: by OnTheGoSystems – 4.6.5
WP All Export Pro: by Soflyy – 1.5.4
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.0.6 – Not tested with the active version of WooCommerce
WP All Import Pro: by Soflyy – 4.5.5
WPML Media: by OnTheGoSystems – 2.4.1
WPML Multilingual CMS: by OnTheGoSystems – 4.1.3
WPML String Translation: by OnTheGoSystems – 2.9.1
WPML Translation Management: by OnTheGoSystems – 2.7.2
Classic Editor: by WordPress Contributors – 1.5
Elementor: by Elementor.com – 2.5.16
Meta Box: by MetaBox.io – 4.18.1
MB Settings Page: by MetaBox.io – 1.3.4
Meta Box Group: by MetaBox.io – 1.2.17
Meta Box Columns: by MetaBox.io – 1.2.3
Meta Box Tabs: by MetaBox.io – 1.1.1
Storefront Footer Text: by Wooassist – 1.0.1
Force Login: by Kevin Vess – 5.3
MultiSite Clone Duplicator: by Julien OGER, Pierre DARGHAM, David DAUGREILH
GLOBALIS media systems – 1.5.3
MB User Meta: by MetaBox.io – 1.2.2
Homepage Control: by WooThemes – 2.0.3
User Role Editor: by Vladimir Garagulya – 4.51.1
User Switching: by John Blackbourn & contributors – 1.5.1
Disable Real MIME Check: by Sergey Biryukov – 1.0
Adminimize: by Frank Bültge – 1.11.4
Enable Media Replace: by ShortPixel – 3.2.9
WPML All Import: by OnTheGoSystems – 2.0.8
Mailgun: by Mailgun – 1.7.1
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.5 – Not tested with the active version of WooCommerce
MB Admin Columns: by MetaBox.io – 1.4.2
Admin Menu Editor: by Janis Elsts – 1.9

I realise i have many plugins. I haven't tested disabling all plugins and see what could be causing this - if you'd prefer I do that let me know. Ill just need to get a staging environment setup first.

**Comment by rrennick** [comment]
> Yes the admin can see all the WC core admin screens including settings. Just that once they are clicked it takes me to the error page.

Can you deactivate WooCommerce Admin and see if the screens still error? Checking that in your staging environment would be fine.

**Comment by timmyc** [comment]
Due to lack of response, I'm going to close this issue, but please feel free to re-open or create a new issue if you still are having issues @ThomasSultana
