### ISSUE TITLE
Stock Movement Report

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2506]
**Is your feature request related to a problem? Please describe.**
Support thread: https://wordpress.org/support/topic/product-movment/

**Describe the solution you'd like**
A chronological stock change report by product. This would require a custom table to record the stock changes. A consideration for this would be how long to retain the data/

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
