### ISSUE TITLE
IE 11: Dashboard spacing is off

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2508]
**Describe the bug**

In IE, the spacing is off between dashboard elements.

**To Reproduce**

1. Visit the dashboard in IE.
2. See spacing off between charts.

**Screenshots**

![Screen Shot 2019-06-26 at 11 56 18 AM](https://user-images.githubusercontent.com/1922453/60141438-9dbc4600-9809-11e9-8733-b963b1487425.png)

**Additional Context**

Testing done with Browserstack

**Comment by timmyc** [comment]
@psealock just confirming this was in IE11.

**Comment by psealock** [comment]
yes, IE 11. Title changed

**Comment by psealock** [comment]
Fixed
