### ISSUE TITLE
Options left behind after deactivate/delete

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2511]
**Describe the bug**
When deactivating/deleting the plugin, it appears we are not clearing out the options used by wc-admin, as when I reinstall a fresh copy, I am not prompted to import historical data, and my prior dashboard customizations are still there.

**To Reproduce**

1. Install the latest version from .org
2. Make some dashboard customizations
3. Import historical data
4. Deactivate / Delete
5. Reinstall, and note you are not prompted to import historical data, and the dashboard is still customized

**Expected behavior**
For all data/options to be removed upon delete.

**Comment by joshuatf** [comment]
@timmyc Do you still think we should tackle this issue?

I'm also curious what we should do for certain items like onboarding data and feature flags.  Should we re-run the onboarding wizard when a plugin is deactivated and re-activated?

**Comment by timmyc** [comment]
Let's close it out, thanks Josh.
