### ISSUE TITLE
WCAdmin visible to non-admin users

### ISSUE THREAD

**Issue by adriannees** [woocommerce/woocommerce-admin#2516]
I run a multivendor marketplace and have this installed on my staging site. I logged in as a vendor (they have access to wp-admin to upload products) and vendors are able to see the woocommerce admin bar. I'm not sure what the permissions are set to allow to see the admin bar but these users have the following (in addition to the WC Vendors permissions): 
 assign_product_terms
 delete_posts
 delete_products
 delete_published_products
 edit_product
 edit_products
 edit_published_products
 import
 manage_product
 publish_products
 read
 read_products
 upload_files

**Comment by rrennick** [comment]
The WC Admin screens use `view_woocommerce_reports` for user capability checking. You can use the `woocommerce_admin_analytics_menu_capability` to change the capability required. More detailed info is on #2211

**Comment by rrennick** [comment]
Closing.
