### ISSUE TITLE
Analytics: Expanded Customer Report Filters & Columns

### ISSUE THREAD

**Issue by derekakelly** [woocommerce/woocommerce-admin#2523]
**Is your feature request related to a problem? Please describe.**
No this is not related to a problem that I could find.

**Describe the solution you'd like**
I'd like to see these added to both the filters & columns 
1. Last Order
2. First Order

I'd like to be able to filter the customer report by order dates. It would be very useful to be able to lookup all customers who had an order between Date X and Date Y.

I'd also like to see the complete Shipping & Billing addresses available in the columns.

**Should this be prioritized? Why?**
After our customers subscribe they rarely log back in to make adjustments. So, their last order date is much more important than their last active date.

Customers that make purchases as a guest will never have a sign up date, so having their first order date would be more useful.

Thanks for your time!
-Derek

**Comment by psealock** [comment]
Thanks for the suggestion. We are considering adding some kind of time filter to the Customers Report.

As far as adding columns, this can be done by an extension. Here is some sample code for adding columns to the Products report. If you go through the process of extending the Customers Report, I'd be curious how it goes and any feedback you might have.

**Comment by dreiris** [comment]
Hello! Thank you for the feedback and idea! This ticket is being closed and the feature request is being moved to a backlog. The feature will be evaluated with other feature requests and prioritized.
