### ISSUE TITLE
Implement Autocomplete Component

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2527]
For long `Select` components like country/state selection, we would like to implement an autocomplete like the one that WooCommerce core uses.

`@wordpress/components` has a component named "Autocomplete", that is used for things like the block inserter or `@mentions` -- however, it requires the use of a trigger character/word. This isn't quite what we need.

One option is to use one of the packages listed here:
https://material-ui.com/components/autocomplete/

See the discussion in p1561568187019900-slack-wc-onboarding

**Comment by oliviertassinari** [comment]
> One option is to use one of the packages listed here:
https://material-ui.com/components/autocomplete/

@justinshreve Notice that Material-UI is moving away from third-party integration to provide its own solution: https://deploy-preview-17037--material-ui.netlify.com/components/autocomplete/
This is part of the "Material-UI" as material to build UI (and not only Material Design) effort.
