### ISSUE TITLE
Uncaught TypeError: Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by jerbiun** [woocommerce/woocommerce-admin#2536]
**Describe the bug**
Error in console that lead to an empty dashboard (no data are displayed)

 
**Screenshots**
![r7myWU](https://user-images.githubusercontent.com/16406245/60330058-eb63ba80-9991-11e9-8881-cf6b975ab960.png)

**Additional context**
i wasnt able to reproduce the bug .. it comes after i add some custom stauts for woocommerce and delete them

**Comment by rrennick** [comment]
Can you describe the steps you followed with the custom statuses?

**Comment by rrennick** [comment]
Forum post for 0.14.0 https://wordpress.org/support/topic/erro-javascript-in-new-update-pt_br/#post-11679044.

**Comment by jerbiun** [comment]
@rrennick yes i did update to last version 0.14.0 but style have the error.
for the custoom statuses i used a plugin and delete it 
after i backup my site i delete all plugins expet WooCommerce and Woocommerce Admin 
 i delete all my order too but style have the error.

**Comment by rrennick** [comment]
Can you provide a link to the custom status plugin? It's quite possible that deleting the plugin didn't remove the statuses from the database.

**Comment by jerbiun** [comment]
this is the plugin 
https://wordpress.org/plugins/custom-order-statuses-woocommerce/

**Comment by rrennick** [comment]
@jerbiun Thanks :)

**Comment by manojhl** [comment]
I'm also getting the same error on wc-admin pages. 

Tried disabling all other plugins, but still having the same issue

![image](https://user-images.githubusercontent.com/4166764/60410371-9aa2ca80-9bfa-11e9-8b48-06c533fb764f.png)

### wp-core ###

version: 5.2.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 311
dotorg_communication: true

### wp-plugins ###

Advanced Order Export For WooCommerce: version: 2.1.1, author: AlgolPlus
Akismet Anti-Spam: version: 4.1.2, author: Automattic
Google Apps Login: version: 3.2, author: Lever Technologies
Jetpack by WordPress.com: version: 7.4.1, author: Automattic
Query Monitor: version: 3.3.6, author: John Blackbourn
SendGrid: version: 1.11.8, author: SendGrid
SOFT79 Cart Links for WooCommerce: version: 1.1.4, author: Soft79
Stag Custom Sidebars: version: 1.2, author: Ram Ratan Maurya
StagTools: version: 2.3.1, author: <a href="https://twitter.com/mauryaratan/">Ram Ratan Maurya</a>, <a href="https://codestag.com/">Codestag</a>
User Role Editor: version: 4.51.1, author: Vladimir Garagulya
User Switching: version: 1.5.1, author: John Blackbourn & contributors
W3 Total Cache: version: 0.9.7.5, author: Frederick Townes
WooCommerce: version: 3.6.4, author: Automattic
WooCommerce Admin: version: 0.14.0, author: WooCommerce
WooCommerce Coupon Exclusions: version: 1.2.0, author: itthinx
WooCommerce Extended Coupon Features FREE: version: 3.1.0, author: Soft79
WooCommerce Free Gift Coupons: version: 2.1.1, author: Kathy Darling (latest version: 2.2.2)
WooCommerce Sequential Order Numbers: version: 1.8.3, author: SkyVerge
WooCommerce Stripe Gateway: version: 4.2.2, author: WooCommerce
WooCommerce Subscriptions: version: 2.5.6, author: Prospress Inc.
WooCommerce Subscriptions CSV Importer and Exporter: version: 2.0.1, author: Prospress Inc
WP Full Stripe: version: 4.0.3, author: Mammothology
WP Mail Logging: version: 1.9.1, author: Christian Zöller
Yoast SEO: version: 11.5, author: Team Yoast

### wp-server ###

server_architecture: Linux 3.10.0-514.6.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.2.19 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 600
memory_limit: 512M
max_input_time: 60
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.65.0 OpenSSL/1.0.2r
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

**Comment by jerbiun** [comment]
hey .. i found the bug its about 2 options in the wp_option table : 
- woocommerce_actionable_order_statuses
- woocommerce_excluded_report_order_statuses
i delete them and the bug is gone ....
related to Analytics Settings of the plugin  "Excluded Statuses:" and "Actionable Statuses:" it seems they cant be empty must check some status

**Comment by timmyc** [comment]
@jerbiun yes! So bummed I missed your comment, but I found it yesterday too - fix in progress here https://github.com/woocommerce/woocommerce-admin/pull/2577

**Comment by rrennick** [comment]
Since #2577 has been merged I'll close this one. The fix for this will be in the next release of WooCommerce Admin.
