### ISSUE TITLE
WC-Admin Inbox message: Facebook extension

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2538]
**User Story**
As a store manager
I want to receive inbox notification about extensions that can be useful to my business
So I can quickly install them from the inbox notification

**Hypothesis**
The Inbox feature on the new WC-Admin can be a useful tool to suggest extensions that can be helpful for our merchants' business. In this initial test, we'll start with just the Facebook extension, as it will also allow us to verify if an inbox notification can be an effective alternative to the recommendation step during the onboarding.

**Acceptance criteria**
- Display the inbox message about the Facebook extension
- Allow the user to automatically install the extension when clicking in the "install now" button
- Display the message just for users that have at least one product, don't have the extension installed and the store was created +3 days ago.

The details about the inbox message are in the WC-admin Inbox messages file (line 19).

**Additional context**
In terms of event tracking, the events "wcadmin_activity_panel_open" and "wcadmin_inbox_action_click" that are in plans to be implemented on this sprint must be enough. But I'll double check it.

**Comment by dreiris** [comment]
How do we determine the age of the store so that we can prompt the store with the notification after 3 days?

**Comment by jeffstieler** [comment]
> How do we determine the age of the store so that we can prompt the store with the notification after 3 days?

I'm not sure if we can determine the age of the store, but we do know the date that WooCommerce Admin was installed. Is that an acceptable alternative?

**Comment by jeffstieler** [comment]
> Display the inbox message about the Facebook extension

Do we have the copy for this?

**Comment by pmcpinto** [comment]
Hey Jeff,

Here it goes my feedback:

> I'm not sure if we can determine the age of the store, but we do know the date that WooCommerce Admin was installed. Is that an acceptable alternative?

Yes, WC Admin install data works perfectly.

> Do we have the copy for this?

It should be: Grow your business by targeting the right people and driving sales with Facebook. You can install now this free extension. [Learn more](https://woocommerce.com/products/facebook/).

I added the copy and the info about this notification in the google sheet that contains all the notifications info. I'll send you the link to the sheet on Slack.

Thanks

**Comment by jeffstieler** [comment]
Which [icon](http://automattic.github.io/gridicons/) should we use for this note?
