### ISSUE TITLE
Net profit Report

### ISSUE THREAD

**Issue by mohamadengs** [woocommerce/woocommerce-admin#2540]
This is not related to a problem.

I love the new extension (woocommerce admin) with all the new features. But it is frustrating to see only the net revenue without the ability to get net profits. It really gives me anxiety.

The solution is simple: with every product pricing in addition to the product price and sale price there should be a place to input the product net costs on us (sellers) so that you can use this information to generate a new column in the reports with net profits.

Alternatively you can provide a whole new tab in the product edit tab that can be called “product information” for example that can be more specialized with ability to input product  shipping import cost (on us sellers to get the products to us before selling), custom duties, import taxes, original product value. So that you can use these information to generate better reports with net profits and more.

This should be prioritized because it is very annoying to see the new net revenue report with all additional options without the ability to see your net profits. It feels like something is broken and that is frustrating.

**Comment by timmyc** [comment]
@mohamadengs thanks for the feedback! There is an extension that allows you to add Cost of Goods to your products, and it updates the legacy reports with the data: https://woocommerce.com/products/woocommerce-cost-of-goods/

We will reach out to Sky Verge, the plugin author, to see what their plans might be for adopting the new wc-admin reports with this data.

**Comment by timmyc** [comment]
Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
