### ISSUE TITLE
Blank Screen on all Analytics Pages if User is Not Role Administrator

### ISSUE THREAD

**Issue by BCwhoLikesPHP** [woocommerce/woocommerce-admin#2545]
The issue I am having is that Users other than Administrators, like Shop Manager or even a custom Role that has been assigned all Woocommerece priveledges, are not able to see any Analytics screens. In version 0.13.2 Even the Dashboard Screen would not display if directly linked too and the link in the menu did not display. I updated to version 0.14.1 and now a direct link to the Dashboard works displaying stats on the summary page but all the other analytics pages simply display as blank and nothing happens when the link is clicked and an ajax refresh is attempted.

I have tried this with Microsoft Edge, Chrome, and Opera Browsers on Desktop with Windows 10.

**Comment by rrennick** [comment]
Thanks for reporting this. That sounds like you have a script error/conflict. Can you check your browser console and see if there are any errors reported?

**Comment by timmyc** [comment]
@BCwhoLikesPHP just checking in here, is there any error messages being shown in your JavaScript console? And confirming that the dashboard is working, and report pages are not?

**Comment by rrennick** [comment]
Closing this for lack of feedback. If you encounter a blank screen on an WC Admin page and have errors in your browser console, please post that info here and we will re-open the issue.

**Comment by fluxpixel** [comment]
Hi there. I´m having this problem. It´s not a js problem it´s permissions problem I get

You do not have sufficient permissions to access this admin page.
Reason: The "Store Name → Dashboard" menu item is disabled for the "shop_manager" role.

**Comment by amalinaaziz** [comment]
any update on the issue? i am facing the same thing with error in my browser console as follows

> [Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (reviews, line 0)

**Comment by rrennick** [comment]
> i am facing the same thing with error with plugin version 0.25.1 in my browser console as follows

@amalinaaziz Can you navigate to a non-WC Admin page then go back to the WC Admin page then check for the error?

**Comment by amalinaaziz** [comment]
Not sure what are the exact changes that I did but it's related user role and capabilities and it's showing now.

**Comment by rrennick** [comment]
@amalinaaziz Thanks for letting us know. The default capability required to access analytics is `view_woocommerce_reports`.
