### ISSUE TITLE
Tracks: Current onboarding even tracking fixes

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2549]
We need to update some of the events that are being tracked in the current onboarding:

- **wcadmin_obw_ready_marketing_signup** (line 11): this event seems to be broken, you can check the activity on Tracks.

- **wcadmin_obw_recommended** (line 13): considering that we're going to show the new WC Admin as a recommendation, we need to add it as an event property (setup_wcadmin). Also, in this event it's missing the event property for the Facebook extension. I added that property with the name setup_facebook.

- **wcadmin_obw_ready_view** (line 14): we need to add this event for when the user views that last step of the onboarding flow (Ready!). Currently, we're only tracking if the user clicks in one of the options on that step, which makes it difficult to understand if they arrive at that step and drop.

I marked the 3 events with the "Under development" status in the event tracking list.

**Comment by timmyc** [comment]
Closing this out as it has merged to `master` in core, and will ship in 3.7 ( if not sooner )
