### ISSUE TITLE
Leaderboards: Urls refresh page and don't persist queries

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2553]
**Is your feature request related to a problem? Please describe.**

Leaderboard urls are constructed on the server. This makes makes for a page refresh and omission of persistedQueries like "before" and "after".

**Describe the solution you'd like**

Urls constructed in JS so we can take advantage of our `<Link />` component to avoid page refresh. Also, current time related and persisted queries to be included in the link.

**Comment by joshuatf** [comment]
@psealock Is this still an issue?  When I change the queries on the leaderboards page, they seem to be reflected in the URL and we then also use them to fetch leaderboard data in https://github.com/woocommerce/woocommerce-admin/blob/b2e41ef3fc2f2d6ef955cda1c1b1d7675707e32b/packages/data/src/items/utils.js#L28

Is this resolved or did I misunderstand?

**Comment by psealock** [comment]
Thanks @joshuatf, I just checked and this looks to be resolved.
