### ISSUE TITLE
Placeholder for no theme info

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2558]
**Is your feature request related to a problem? Please describe.**
Add a placeholder when the onboarding theme remote lookup fails. Follow up to https://github.com/woocommerce/woocommerce-admin/pull/2543#discussion_r299232165

**Describe the solution you'd like**
Add alternate handling for the theme selection screen. Could we ask the design team for suggestions.

**Comment by joshuatf** [comment]
@jameskoster When the theme lookup at WCCOM fails, do we want to render anything in place here (aside from installed themes)?

**Comment by jameskoster** [comment]
Why would it fail? Is it something that a refresh would fix?

**Comment by joshuatf** [comment]
@jameskoster It mostly happens when you have a local environment setup for WCCOM, however it's possible the server was unreachable (down) or a path changed.

It's not very likely to happen in the real world, but refreshing will not fix it.

**Comment by jameskoster** [comment]
If a refresh won't fix it then displaying anything at all seems pointless. As you said we'll have the installed / active theme to fall back on, so I don't think it's a big deal.

**Comment by joshuatf** [comment]
Okay, sounds reasonable to me.  Closing this issue.
