### ISSUE TITLE
Customer-centric report of all orders

### ISSUE THREAD

**Issue by jfarsen** [woocommerce/woocommerce-admin#2576]
I was surprised to see there is no way to view a Customer and all his orders anywhere, be it in WooCommerce or this new Admin.

The ability to view a Customer's purchase history through the dashboard would be very beneficial to admins / shop managers.

I tried filtering to a single Customer in the Customers tab, but the line only provide a tally of the orders, not the list.

Can this be added?

ps. I can see a few plugins trying to fill this gap, but shouldn't this basic capability be in the Admin plugin or even in the WooCommerce core itself?

**Comment by timmyc** [comment]
@jfarsen one idea on this topic that has been discussed is to add a customer filter to the Orders report, which would then show a full history of orders filtered by a given customer. Would that be a good solution for you?

**Comment by jfarsen** [comment]
Hi @timmyc, that’s could be one way to tackle it, albeit in my mind not as cleanly as a separate URL which would provide an at-a-glance view of a client’s relationship / orders/ profile with the store.

I can see filters as being more versatile and powerful, but the end result you describe is not “as customer-centric” as what I was eluding to ... my 2 CAD cents :)

**Comment by timmyc** [comment]
> my 2 CAD cents :)

C'mon that feedback is worth _at least_ a toonie!

> albeit in my mind not as cleanly as a separate URL

All the filters on reports append query strings to the URL, so theoretically, the orders report filtered by a specific customer would be a bookmarkable, unique URL.

Thanks @jfarsen !

**Comment by dreiris** [comment]
Hello! Thank you for the feedback and idea! This ticket is being closed and the feature request is being moved to a backlog. The feature will be evaluated with other feature requests and prioritized.
