### ISSUE TITLE
npm package page bad documentation link

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#2578]
https://www.npmjs.com/package/@woocommerce/components "the full Component documentation"

links to https://woocommerce.github.io/wc-admin/#/components/

it should link to https://woocommerce.github.io/woocommerce-admin/#/components/

**Comment by timmyc** [comment]
Hmmmm, it seems to be pointed at the right page for me [code is here](https://github.com/woocommerce/woocommerce-admin/blob/master/packages/components/README.md) i'm going to close this out Allen, perhaps that change finally got pushed up in the release that Paul did yesterday.
