### ISSUE TITLE
Text field hover / focus styles

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#2581]
On hover let's set the border color to gray 400.

Also, I'm only seeing the focus border styles when I start typing in an input - they should be applied whenever the input is focussed.

**Comment by justinshreve** [comment]
The focus style is fixed in Calypso version of the component that will be exported here https://github.com/Automattic/wp-calypso/pull/34277.

We could also fix it in Newspack (https://github.com/Automattic/newspack-plugin/issues/75) if we think the calypso ui version will be awhile.

**Comment by justinshreve** [comment]
It looks like there is some activity on the Gutenberg issue that is preventing us from using the updated version of the component. 

We could fix this now but creating a local copy of the component or by making a fix in the newspack-components we are both moving away from -- but I think it makes more sense to wait and switch to the fixed version. Is it OK to move this one to the backlog @pmcpinto / @dreiris until that time?

**Comment by pmcpinto** [comment]
@justinshreve

> but I think it makes more sense to wait and switch to the fixed version

Ok, I just moved this issue to the backlog

**Comment by justinshreve** [comment]
Considering the Calypso/Gutenberg issues haven't had any traction, I think we should fix any issues we have in a local component for the purposes of A/B testing. So I've removed the `Blocked` label.
