### ISSUE TITLE
Card padding & input margin offset

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#2583]
Card padding should consistently be 16px. As we've added a top margin to inputs this makes the effective top/bottom card spacing 30px on some screens:

![30](https://cldup.com/DEaP3d11CD-2000x2000.png)

On that note, I noticed the input top/bottom margin is 14px - it should be 16px to align with our 8px baseline grid #designerpedantics

**Comment by joshuatf** [comment]
@jameskoster Does that top/bottom margin for inputs only apply to wc-admin or most of our projects?  It seems like that `14px` is explicity set in newspack components and I'm wondering if we should update with a variable there or only change it here.

**Comment by jameskoster** [comment]
Assuming they're using Muriel their inputs should be aligned to the same 8px baseline grid. It might be worth checking why they used 14px values. I'm now wondering if the borders are effectively adding 2px to that and creating a 16px spacing.

I can't access the Profiler atm to double check this :D
