### ISSUE TITLE
Tab component 

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#2588]
The label should be centrally justified. Looks like this is a result of that Figma bug you mentioned @joshuatf.

**Comment by joshuatf** [comment]
I think this is resolved by https://github.com/woocommerce/woocommerce-admin/pull/2556 - can you confirm things look okay @jameskoster ?

**Comment by jameskoster** [comment]
I may not have pulled that change. 

I can't access the wizard again to check now though. I can see `wc_onboarding_profile` in options.php but for some reason I can't see it in the database. So I'm unable to remove it to access the wizard again.

**Comment by timmyc** [comment]
I was trying to verify the justification of the tab text, but am hitting the following error on the theme step:

![image](https://user-images.githubusercontent.com/22080/60919112-bf75ee00-a249-11e9-8ce2-0fcb91301641.png)

@joshuatf is there another setup step I'm missing here to test out the theme step? ( sorry obw noob question )

> I can't access the wizard again to check now though. I can see wc_onboarding_profile in options.php but for some reason I can't see it in the database. So I'm unable to remove it to access the wizard again.

Yeah this is a bit of a dance we have to do to get the wizard to work again, to set the options to the proper values. Should we create a tool that is only exposed in dev mode to re-enable the OBW for testing like this? Its not like the current OBW where you can still go and work on it even after you have completed the process... or maybe in dev env we just allow the OBW to be served up if the `step` argument is there?

**Comment by jameskoster** [comment]
> or maybe in dev env we just allow the OBW to be served up if the step argument is there?

Something like that would be handy :)

**Comment by joshuatf** [comment]
>@joshuatf is there another setup step I'm missing here to test out the theme step? ( sorry obw noob question )

You're doing everything the right way.  The theme step should be fixed after https://github.com/woocommerce/woocommerce-admin/pull/2627 is merged.  Was a conflict between the recent Snackbar merge and Uploader component.

>Should we create a tool that is only exposed in dev mode to re-enable the OBW for testing like this?

Like a fixed button the says "Start OBW" only in dev mode?  I don't mind dropping the `wc_onboarding_profile` option from `wp_options` if I've already completed, but I'm also not opposed to adding a button if it makes the dev flow and/or design review easier for everyone.

@jameskoster Here's the updated tab style:

<img width="847" alt="Screen Shot 2019-07-10 at 5 19 14 PM" src="https://user-images.githubusercontent.com/10561050/60957750-c11ddf80-a337-11e9-9f30-330231c50438.png">

**Comment by timmyc** [comment]
> Like a fixed button the says "Start OBW" only in dev mode? I don't mind dropping the wc_onboarding_profile option from wp_options if I've already completed, but I'm also not opposed to adding a button if it makes the dev flow and/or design review easier for everyone.

Yeah maybe we have a button that is shown on the dash that says "Start OBW" we can feature flag it too to make certain it doesn't leak out there in builds. This would be a bit more approachable then finding the fields in the options table and deleting, or like I have been doing , using Postman to send an API request to clear it out.

**Comment by jameskoster** [comment]
Tabs look good 👍 

Could we filter this button for the OBW restart?

![obw](https://cldup.com/vpkh32dHak-2000x2000.png)
