### ISSUE TITLE
stylelint is not running on commit

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2601]
It doesn't look like some of the linters, specifically `stylelint` are getting ran on pre-commits.

Both Josh and I created new PRs that had some CSS issues in it, which caused the CI tests to fail. Our pre-commit hooks should catch that.

**Comment by timmyc** [comment]
Hmmm I did update some linter dependencies this week, I wonder if that might be related.

**Comment by joshuatf** [comment]
I think (at least in my case) the pre-commit hook was actually formatting my passing CSS to a style that did not pass.

I had to commit with `--no-verify` to prevent the lint fixes.

**Comment by psealock** [comment]
@joshuatf Do you happen to remember what `scss` files you touched? I’m trying to run prettier on files to see if I can re-create, but no luck so far.

**Comment by joshuatf** [comment]
@psealock It was in mixins and breakpoints.  If I recall correctly, it had mostly to do with the if/else line break formatting.  Here's the PR where it occurred - https://github.com/woocommerce/woocommerce-admin/pull/2596/files

**Comment by psealock** [comment]
### Steps to reproduce

1. Using a [prettier plugin](https://prettier.io/docs/en/editors.html) for your editor, format `client/stylesheets/abstracts/_mixins.scss`.
2. `npm run lint` and see it fail

We can update a few things, but the problem remains. Calypso simply skips prettier for sass files in https://github.com/Automattic/wp-calypso/pull/29697.

https://github.com/Automattic/wp-calypso/blob/master/bin/pre-commit-hook.js#L62-L78

That seems drastic, considering it only affects a few files. My opinion is to wait and suffer with the issue when editing files like the one above. When Prettier [fixes its sass problems](https://github.com/prettier/prettier/issues?q=is%3Aopen+is%3Aissue+label%3Alang%3Acss%2Fscss%2Fless), we should update to wp-prettier (we are currently on calypso-prettier which is outdated):

https://github.com/Automattic/wp-prettier

**Comment by psealock** [comment]
This has been fixed
