### ISSUE TITLE
Orders moving to cancelled when paid

### ISSUE THREAD

**Issue by stevebrewcon** [woocommerce/woocommerce-admin#2603]
Customer makes an order and pays for it. The orders screen shows cancelled when it is not cancelled.

Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.

**To Reproduce**

Make an order. This happens with Barclaycard and Paypal

**Comment by rrennick** [comment]
This repo is for issues related to the new WooCommerce dashboard.

For PayPal, contact support at https://woocommerce.com/contact-us/. For Barclaycard, contact that plugin's support.
