### ISSUE TITLE
Update Travis to handle WooCommerce dependencies

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2642]
**Describe the bug**

Travis CI tests have been failing lately. This is because WooCommerce Core now has a new build step to install dependencies as of https://github.com/woocommerce/woocommerce/pull/23957.

**To Reproduce**

See the build step fail on any recent PR. Errors largely include missing classes on unit tests.

**Expected behavior**

Unit tests should run.

There is a PR in progress https://github.com/woocommerce/woocommerce-admin/pull/2640, but its late Friday for me, so I'm not going to assign myself to this issue in case anyone wants to take it on before I get back on Monday.

**Comment by jeffstieler** [comment]
Fixed in https://github.com/woocommerce/woocommerce-admin/pull/2640.
