### ISSUE TITLE
Table Footer Z-Index issue when viewing table columns menu

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#2647]
**Describe the bug**
Table footer is positioned on top of columns popover

**To Reproduce**
View a report with a limited number of rows. Click the kebab menu item in the top left corner of the table to expand the menu. Note the table footer sits on top of the menu. 

**Expected behavior**
The columns menu should rest above the table footer. 

**Screenshots**
<img width="1724" alt="Screen Shot 2019-07-12 at 8 52 14 AM" src="https://user-images.githubusercontent.com/4500952/61141524-9c824e80-a482-11e9-8864-956033245950.png">

**Comment by timmyc** [comment]
Thanks for the report @LevinMedia - I saw this one yesterday too!

**Comment by rrennick** [comment]
Related #2772
