### ISSUE TITLE
Question: Routes for Pages with a List vs a Single Item

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#2651]
Let's say we had a list of things on a wc-admin powered page and we wanted to let people click on a list item to see a detailed view of that item on its own page. I assume we'd need to tweak the path,

e.g. for something like viewing a thing with ID 101 we would navigate from a list view at

`/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fthings`

to 

`/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fthings%2F101`

Is that the pattern you'd recommend? I didn't see a direct analog in wc-admin already.

cc @LevinMedia

**Comment by psealock** [comment]
>Is that the pattern you'd recommend? I didn't see a direct analog in wc-admin already.

If you want to work within the current system, the path would have to look like this:

```
/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fthings&id=99
```

If you want the id to be in the `path` parameter for reasons such as inclusion in the breadcrumbs, we'd need to make some modifications to the controller, which are certainly possible.

![Screen Shot 2019-07-15 at 11 36 54 AM](https://user-images.githubusercontent.com/1922453/61190757-72849280-a6f5-11e9-8b69-68911e1d7d82.png)

**Comment by allendav** [comment]
Thanks @psealock - we'd like the breadcrumbs to look like this when viewing an individual record - note that we don't want to show the ID in the breadcrumbs:

<img width="229" alt="Screen Shot 2019-07-15 at 4 31 06 PM" src="https://user-images.githubusercontent.com/1595739/61255585-0b2f0880-a71e-11e9-95b2-b9c990a24032.png">

So, am I correct in understand that that would NOT require a controller mod?

fyi @LevinMedia

**Comment by psealock** [comment]
>So, am I correct in understanding that that would NOT require a controller mod?

Correct!

You'll want to add an object like this to the `woocommerce_admin_pages_list` filter.

https://github.com/woocommerce/woocommerce-admin/blob/697b8a77e4ae78612a39bfead8f807d10a5efca0/client/layout/controller.js#L65-L76

Although, the breadcrumb component makes the assumption that `WooCommerce` will be the first breadcrumb, so some modification will be required to have `WooPayments` appear first.

**Comment by allendav** [comment]
OK. I think this question issue can be closed. If we need WooPayments to appear first, we'll open another issue for that. Thank you @psealock !

**Comment by dechov** [comment]
For reference, we currently have WooCommerce / Payments first, consistent with other WooCommerce screens such as Analytics:

<img width="373" alt="Screen Shot 2019-07-17 at 7 49 53 PM" src="https://user-images.githubusercontent.com/1867547/61419505-89311200-a8cc-11e9-887a-93ee25115dee.png">
