### ISSUE TITLE
Currency Display Issue

### ISSUE THREAD

**Issue by jam05pgs** [woocommerce/woocommerce-admin#2652]
**Describe the bug**
After installing Woocommerce Admin i am facing an issue, when i go to analytics dashboard the currency column is showing currency values as <span class=”currency”>$</span>0 on every occurrence of displaying amounts.

**To Reproduce**

1. Go to Admin Dashboar 
2. Click on Analytics 
3. Scroll down to Revenue

**Expected behavior**
Should Display like $20.00

**Screenshots**
![currency-display-issue](https://user-images.githubusercontent.com/52879963/61181652-c5e9d880-a642-11e9-9ac4-ab4bd138405f.png)

**Comment by psealock** [comment]
Hi @jam05pgs,

Are you setting the currency to HTML via the `woocommerce_currency_symbols` filter?

If so, here is an explanation why its not a good idea for this app to render third party HTML, https://github.com/woocommerce/woocommerce-admin/issues/2615#issuecomment-509800127.

If you are using the `currency` class to make style changes, maybe there is another CSS class you can  target?

**Comment by jam05pgs** [comment]
I have not customize anything just default worpress, default woocommerce and default wooommerce admin that's it.

Let me know if you need admin access.

**Comment by psealock** [comment]
I wonder if there is a plugin modifying the currency symbol. In the console, you can paste this to see what the currency symbol is:

```js
wcSettings.currency.symbol  // should be "$"
```

If there is html in that setting, it would be the cause and something is altering it. Under WooCommerce > Status > System Status, you can copy the report and paste it here if you'd like so I can see what plugins might be causing the issue. 

Thanks!

**Comment by jam05pgs** [comment]
When i enter in console wcSettings.currency.symbol  

it display "$"

I have disabled all plugins one by one and found there was no issue with any plugin and then i disable the theme and enable default theme the issue was not there anymore.

It seems (confirmed) the issue is somewhere in the theme, how can i track what file having issue?

**Comment by psealock** [comment]
That seems odd to me because the currency value is gathered from `wcSettings.currency.symbol`. 

https://github.com/woocommerce/woocommerce-admin/blob/e79d8e058bd920f7f02d721d7f279e08ef1c0c47/packages/currency/src/index.js#L23

Which theme are you using?

**Comment by rrennick** [comment]
Closing this issue for lack of feedback.
