### ISSUE TITLE
Onboarding: Error on Proceed without Jetpack or WooCommerce Services

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2670]
**Describe the bug**

On the Onboarding flow, when clicking on "Proceed without Jetpack or WooCommerce Services", an error occurs and no navigation takes place.

![Screen Shot 2019-07-19 at 1 46 35 PM](https://user-images.githubusercontent.com/1922453/61503618-8fd69b00-aa2c-11e9-95aa-959eb6e94136.png)

**To Reproduce**

1. `/wp-admin/admin.php?page=wc-admin`
2. Click "Proceed without Jetpack or WooCommerce Services"
3. See error in the console.

**Expected behavior**

Page should navigate to next screen.

**Comment by justinshreve** [comment]
I can't seem to reproduce this @psealock. Maybe it was fixed in the past week. Can you try to reproduce again with the latest `master`?

**Comment by justinshreve** [comment]
I did notice that the URL updates to `/wp-admin/admin.php` which is incorrect. (If the user refreshed, they would not be on the dashboard). Will fix.
