### ISSUE TITLE
Multi-currency native in WooCommerce

### ISSUE THREAD

**Issue by kwok0781** [woocommerce/woocommerce-admin#2675]
It would be great if WooCommerce support multi-currency out of the box so that we don't need to rely on 3rd party plugins to present our store in a user's local currency.  This is a core feature of any eCommerce platform that seemed to be overlooked by WooCommerce

**Comment by rrennick** [comment]
> This is a core feature of any eCommerce platform that seemed to be overlooked by WooCommerce

WooCommerce core development is managed through https://github.com/woocommerce/woocommerce . I suggest you create an issue there requesting the feature.
