### ISSUE TITLE
Footer message overlaps buttons in Category Edit page

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#2682]
It has been reported twice in the support forums:

> Category edit page update button is unclickable with the woocommerce footer message “If you like WooCommerce please leave us a ★★★★★ rating. A huge thanks in advance!” on top.

https://wordpress.org/support/topic/category-page-update-button-unclickable-with-woocommerce-footer-on-top/

https://wordpress.org/support/topic/breaks-the-catagory-edit-page/

## Screenshots

Without WooCommerce Admin:

![1](https://user-images.githubusercontent.com/3616980/61620089-6a39d380-ac70-11e9-8613-949874d52eb9.png)

With WooCommerce Admin:

![2](https://user-images.githubusercontent.com/3616980/61620096-6d34c400-ac70-11e9-9ff6-0bcbcd7747ef.png)

I was unable to reproduce it, but maybe somebody else from the team can? :thinking:

**Comment by GeoJunkie** [comment]
This was also reported in 7108910-hc. WooCommerce Admin was also installed. While researching, I found that it's also been reported in other tickets: 2149679-zen, 1369456-zen, 2235613-zen, 2235338-zen

**Comment by fhaps** [comment]
For the record, I saw this in 3151481-hc. It turned out to be a conflict between WC Admin and a plugin called Smush Pro.
