### ISSUE TITLE
Onboarding - Profile Wizard: Setting store for client option

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2686]
We added a checkbox on the [Store Details step](https://www.figma.com/file/b0b2CrxPZz0i1aAPuv985tvK/Store-Profiler?node-id=1150%3A680) in order to understand if the store is being setup by a merchant or a dev/designer

The event "wcadmin_storeprofiler_store_details_continue" was updated to contain the property

**Comment by adnoh** [comment]
is there any documentation for what this is used for? I see the usecase and can dig throught the code - but is there a wiki or official documentation what consequences it has when you tick that box? Thanks
