### ISSUE TITLE
Onboarding - Profile Wizard: user selects a free theme and doesn't have any product to buy

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2707]
In the Theme Selection [step](https://www.figma.com/file/b0b2CrxPZz0i1aAPuv985tvK/Store-Profiler?node-id=1276%3A26318), if the user selects a free theme and it doesn't have any product to purchase he should be redirected to the Task List. During the redirect/store install it's necessary to show this [screen](https://www.figma.com/file/b0b2CrxPZz0i1aAPuv985tvK/Store-Profiler?node-id=2712%3A32)

**Comment by joshuatf** [comment]
@pmcpinto Do we want to show this screen even if they've chosen an already active and installed theme or go directly to the task list?

**Comment by pmcpinto** [comment]
> @pmcpinto Do we want to show this screen even if they've chosen an already active and installed theme or go directly to the task list?

@joshuatf thanks for raising that, in this case I think that it won't be necessary to show the screen.
