### ISSUE TITLE
Historical Import: Done screen shown right away

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2709]
**Describe the bug**

When I start an import of historical data, the "done" screen is shown immediately asking if I want to re-import the data.

![Screen Shot 2019-07-29 at 1 07 36 PM](https://user-images.githubusercontent.com/1922453/62015712-0e3bf580-b202-11e9-9061-6b0a068b3daa.png)

When I refresh, I get the status bars of the in-progress import

![Screen Shot 2019-07-29 at 1 07 54 PM](https://user-images.githubusercontent.com/1922453/62015721-26137980-b202-11e9-9199-a893a8ba0aed.png)

**To Reproduce**

1. Deactivate plugin, create an order, re-activate plugin (or some other way to create importable data, such as deleting previous data).
1. Analytics > Settings > Import Historical Data.
2. Click on "Start".
3. See the finished screen appear.
4. Refresh the page and see the jobs in progress.

**Comment by rrennick** [comment]
@psealock Can you re-check this one? I didn't have the finished screen appear.

**Comment by psealock** [comment]
Indeed, I can no longer reproduce. Closing...
