### ISSUE TITLE
Reorganize class files for PSR-4 autoloading

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#2712]
Reorganize class files into the `/src/` directory and add namespaces for PSR-4 autoloading.

Group classes by function/feature/report type.

- [x] Core WC subclasses https://github.com/woocommerce/woocommerce-admin/pull/2728
- [x] Page controller https://github.com/woocommerce/woocommerce-admin/pull/2730
- [x] Admin Notes https://github.com/woocommerce/woocommerce-admin/pull/2731
- [x] Features https://github.com/woocommerce/woocommerce-admin/pull/2736
- [x] Export https://github.com/woocommerce/woocommerce-admin/pull/2734
- [ ] Onboarding
- [x] Sync https://github.com/woocommerce/woocommerce-admin/pull/2739
- [x] Theme Upgrader https://github.com/woocommerce/woocommerce-admin/pull/2740

**API endpoints**

- [ ] Admin Notes
- [ ] Coupons
- [ ] Customers
- [ ] Countries
- [ ] Download IPs
- [ ] Leaderboards
- [ ] Onboarding
- [ ] Orders
- [ ] Categories
- [ ] Reviews
- [ ] Variations
- [ ] Products
- [ ] Settings
- [ ] Taxes
- [ ] Themes

**Reporting classes**

- [ ] Categories
- [ ] Coupons
- [ ] Customers
- [ ] Downloads
- [ ] Exports
- [ ] Imports
- [ ] Orders
- [ ] Performance Indicators
- [ ] Reviews
- [ ] Products
- [ ] Revenue
- [ ] Stock
- [ ] Taxes
- [ ] Variations

**Additional context**

https://github.com/woocommerce/woocommerce-admin/issues/2635

**Comment by psealock** [comment]
@jeffstieler Just double checking here, is this one closed by https://github.com/woocommerce/woocommerce-admin/pull/2717?

**Comment by jeffstieler** [comment]
> is this one closed by #2717?

Yep! Closing.
