### ISSUE TITLE
Refactor feature flags into autoloaded classes

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#2713]
Remove feature flag "loader" classes and instead add conditional logic to the Composer autoloader.

**Additional context**

#2635

**Comment by jeffstieler** [comment]
@psealock are you OK with closing this? I don't think it provides much value.

**Comment by psealock** [comment]
>I think we can drop #2713

So we'd leave `inlcudes/feature-config.php` as is? Is there a benefit to moving that logic to Composer? It seems to be ok to me, but just want to make sure I'm not missing anything. cc @jeffstieler

**Comment by psealock** [comment]
>@psealock are you OK with closing this? I don't think it provides much value.

Oh, just saw this (didn't refresh page). Yup, makes sense to close this one out.
