### ISSUE TITLE
Safari/FF: Clicking on product name does not select the product

### ISSUE THREAD

**Issue by JScott-MSI** [woocommerce/woocommerce-admin#2729]
**Describe the bug**
Clicking on product search result name does not select the product

**To Reproduce**
If you are in the Products view and select Show: Single Product, type in the product name. Once the search results are shown, if you click directly on the underlined text the product is not selected, you have to click somewhere in the white space around the text.

**Expected behavior**
Clicking on the result text should load the product

**Screenshots**
![Click-on](https://user-images.githubusercontent.com/52297130/62235189-4584e080-b381-11e9-9ba3-57735ea3ecf7.jpg)

**Desktop (please complete the following information):**

* OS: MacOS Mojave
* Browser - Firefox, Safari

**Comment by rrennick** [comment]
I'm not able to reproduce this with the current version of WC Admin using the latest version of Chrome. Can you provide details on OS and browser versions?

**Comment by JScott-MSI** [comment]
Here is a quick screen recording...

https://youtu.be/aipR1odhiig

**Comment by rrennick** [comment]
> However, testing with Chrome does work properly

@JScott-MSI What browser & OS did the issue occur on?

**Comment by rrennick** [comment]
I added OS & browser info to the description.

**Comment by JScott-MSI** [comment]
Safari and Firefox on Mac High Sierra all latest versions — I provided a link to a screen recording in the GitHub thread.

**Comment by psealock** [comment]
I can reproduce this with Firefox. Thanks for the added info @JScott-MSI. I will update the title to reflect this and we will address it soon.
