### ISSUE TITLE
CSV Report doesn't show Coupon data

### ISSUE THREAD

**Issue by phillipcornwell** [woocommerce/woocommerce-admin#2745]
**Describe the bug**
The coupon codes used for orders are not displayed in the CSV.

**To Reproduce**

1. Go to `Orders` report
2. Click on `Download`
3. Open the CSV report
4. Coupon data in the report displayed in the Dashboard shows the coupon used but the CSV does not.

**Expected behavior**
The coupon used in the order should be shown here

**Screenshots**
![Screenshot](https://d.pr/BhDohk+)
Screenshot direct link: https://d.pr/BhDohk

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Chrome 
* Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by psealock** [comment]
Thanks @phillipcornwell, I'll add this to the backlog so we can prioritize it.
