### ISSUE TITLE
Split Testing Implementation

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2759]
**New approach:**

Merging the new onboarding to core in a point release presents significant risks, so the new onboarding to the new WC Admin feature plugin and do a point release where new users would receive the suggestion to install/activate the new WC admin right after they activate the WooCommerce plugin and then go through the new onboarding. 

Phase 1: Split test new onboarding experience pre-installed with WC Admin plugin (10% new users)
Phase 2: Split test new onboarding experience pre-installed with WC Admin plugin (50% new users)
Phase 3: Roll out new onboarding experience on WC Core to 100% new users

The mockup for the new flow after the user activates the WooCommerce plugin can be found [here](https://www.figma.com/file/w7YCgNfdJPFFFsFOmiuneZ/Split-testing?node-id=1%3A2).

More info about the new approach on this P2: p6q8Tx-199-p2

-----------------------
Old approach:
Considering that it's not likely that we're able to test the full onboarding experience in one of our hosting partners, it will be necessary to merge the new onboarding into core but only gradually expose it to new users. This progressive approach would allow us to control the sample size, understand if we're moving the main kpis in the right direction and iterate if needed. The idea is to gradually expose the new onboarding in 3 phases:

Phase 1 - randomly assign the new onboarding to 10-20% of new users
Phase 2 - randomly assign the new onboarding to 50% of new users
Phase 3 - assign the new onboarding to 100% of new users

**Comment by psealock** [comment]
There will be some easier ways to split the population. Location or eCommerce plan perhaps.

If you want true A/B test capabilities, as described above, there is some prior art in Calypso: https://github.com/Automattic/wp-calypso/tree/b20b7ea0812694f4041352a02a9a7fe9848a180a/client/lib/abtest

I'm not sure how easily it can be adapted to our needs, but I would estimate this more like a 5.

**Comment by pmcpinto** [comment]
Hey @psealock, I discussed the possibility of splitting the population based on the location, but using a random generator allows to have better control of the sample size. You can check the chat here: p1564136925007200-slack-wc-onboarding

Unfortunately doing the split testing on the eCommerce plan doesn't serve our needs because it won't allow us to test the new Store Profiler, just the Task List.

> I'm not sure how easily it can be adapted to our needs, but I would estimate this more like a 5.

Their estimation is 3 points, but we don't have that value in our point system. I'm going to switch the estimation tag to 5.

**Comment by pmcpinto** [comment]
Updated the issue description with the new approach of pre-installing the new onboarding in WC-Admin instead of merging it to Core on a point release

**Comment by justinshreve** [comment]
I'm closing this now that the required code is present in WooCommerce 3.9 Beta.
