### ISSUE TITLE
ReportsSync: Refactor

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2765]
The logic to sync lookup tables has reached a point where a refactor can greatly improve the codebase. The code will be easier to read, less error prone, and easier to extend. 

### Current State
https://github.com/woocommerce/woocommerce-admin/blob/af6a49bfda543382d9f268de2ec5bb0ec2c6c419/src/ReportsSync.php

### Proposal
The sync and regeneration of this table currently run on install or category edit.  We should consider moving these into something like `ReportsSync` to allow re-syncing of data and potentially moving the sync into a background process.

If we do this, it may be worthwhile to abstract some of the base logic for syncing and add syncs into individual classes to make this easier to grok and prevent the `ReportsSync` class from becoming too large.  Each individual class could define items or hooks like:

* Dependencies
* Batch sizes
* Batch creation/deletion item retrieval

Fixes here should also address the sync mechanisms of the Category Lookup table introduced in https://github.com/woocommerce/woocommerce-admin/pull/2253.

**Comment by psealock** [comment]
I reworked the description of this issue to reflect a total refactor of the `ReportsSync` class, not just in relation to the Category Lookup table. cc @joshuatf
