### ISSUE TITLE
By overriding wc_get_order, the plugin breaks down following hooks

### ISSUE THREAD

**Issue by Malaiac** [woocommerce/woocommerce-admin#2767]
**Describe the bug**
I maintain a logistics plugin that sends shipping orders via XML to a logistics provider.
The plugin expects $WC_Order = wc_get_order( $order_id ) to return a WC_Order object (or an error)
It seems the plugin "WooCommerce Admin" overrides this function and returns 
a WC_Admin_Order Object

**To Reproduce**
hook on an ajax call using wc_get_order. 
output the return object = not a WC_Order

**Expected behavior**
Unless specified otherwise, wc_get_order should return a WC_Order object

**Comment by rrennick** [comment]
@Malaiac Can you provide some sample code to reproduce this? As a side note, `WC_Admin_Order` inherits `WC_Order` so it has all the `WC_Order` methods & properties.

https://github.com/woocommerce/woocommerce-admin/blob/master/includes/class-wc-admin-order.php#L15

**Comment by Malaiac** [comment]
There was a bit of a misdiagnosis on my part. The returned object does
herit all methods from WC order so this bug can be closed

Le jeu. 8 août 2019 à 13:45, Ron Rennick <notifications@github.com> a
écrit :

**Comment by rrennick** [comment]
@Malaiac Thanks for the quick follow up.
