### ISSUE TITLE
Conflict with Yoast SEO Premium

### ISSUE THREAD

**Issue by rdavey17** [woocommerce/woocommerce-admin#2771]
Hello, I believe I discovered a conflict with this particular plugin and Yoast SEO. Normally when you delete a product and you have Yoast SEO Premium installed, you get prompted to create a redirect in a notice box above the products in the admin area. Unfortunately with this plugin installed at the current version (0.16.0), a class is being applied to that section that is causing it to be hidden. The section is still there, but you cannot see it because of this.

Let me know if I can provide further assistance with getting to the bottom of this, but unfortunately we will need to deactivate the plugin for now until this is resolved. Your help is greatly appreciated!

* OS: MacOS Mojave
* Browser: Chrome
* Version: 75

**Comment by psealock** [comment]
Do you have a screenshot perhaps? I'm unfamiliar with the Yoast SEO plugin.

WC-Admin introduces the Activity Panel for surfacing notifications which extension authors can hook into. Depending on the notice, it may be on the authors of the Yoast plugin to add the notice via the Activity Panel.

**Comment by rdavey17** [comment]
Absolutely, I'll attach two screenshots. One will be with WC Admin disabled in which I put a red box around the notice that usually appears. In the other WC Admin is enabled and I have dev tools up to see that the area is hidden. 

Let me know if I can help any more here. Thanks!

![Screen Shot 2019-08-08 at 8 24 34 PM](https://user-images.githubusercontent.com/20193092/62745939-41109580-ba1b-11e9-9d2d-063fe93ca293.png)
![Screen Shot 2019-08-08 at 8 27 14 PM](https://user-images.githubusercontent.com/20193092/62745941-41a92c00-ba1b-11e9-87af-5808f8d7abca.png)

**Comment by psealock** [comment]
What happens when you click the "Notices" icon in the upper right?

**Comment by rdavey17** [comment]
Well I feel pretty dumb now. That does appear after clicking that. Sorry, I was completely unaware of that as this functionality is very new to me.

**Comment by psealock** [comment]
All good @rdavey17, thanks for bringing it up.
