### ISSUE TITLE
Table Footer Z-Index issue when viewing customers tab under the Analytics

### ISSUE THREAD

**Issue by janakkaneriya007** [woocommerce/woocommerce-admin#2772]
**Describe the bug**
There is z-index in customer tab

**To Reproduce**
1. Go to Analytics->Customer in backend
2. Click on 'Date Range:' OR 'Show:'

**Expected behavior**
Date range box show show clear without cutting

**Screenshots**
![AwesomeScreenshot-woocommercetest-local-wp-admin-admin php-2019-08-09_12_36](https://user-images.githubusercontent.com/34676570/62760763-5ed50d80-baa2-11e9-8494-8f637ad247d1.png)

**Comment by rrennick** [comment]
This is applicable to the table on any screen if you use the dev tools to hide the summary and chart.
