### ISSUE TITLE
Date range has no effect on customer report

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2773]
**Describe the bug**
While trying to reproduce #2772 I found that changing the date range on the customer report did not affect the report. The table always has the full paged list of customers.

**To Reproduce**

1. Go to customer report
2. Select a date range where there are no orders
3. Note number of customers in the table
4. Use `select count(*) from wp_wc_customer_lookup;` & compare to number of customers in table.

**Expected behavior**
Either the date range be removed or the report show customers from the selected date range.

**Screenshots**
<img width="1117" alt="Screen Shot 2019-08-09 at 8 56 12 AM" src="https://user-images.githubusercontent.com/343847/62777332-96808d00-ba83-11e9-8a55-206ae8185fb2.png">

**Comment by jeffstieler** [comment]
According to the original designs - this report wasn't supposed to have a date filter: https://github.com/woocommerce/woocommerce-admin/issues/175

![](https://user-images.githubusercontent.com/22080/49551103-c3502500-f8a2-11e8-8f7e-42e6f3a0cdbb.png)

Seems like removing it makes the most sense.
