### ISSUE TITLE
Not showing any data

### ISSUE THREAD

**Issue by tanny-ro** [woocommerce/woocommerce-admin#2774]
t’s not showing any data.

I have imported historic data but not sure whether it was imported because I didn’t receive any notification.

Also I see pending cron jobs so I contacted server support they said there is nothing with server which is blocking cron jobs to run, this is a plugin issue.

Can you please fix?

Website: https://www.mediachecker.net

----
Is there any way to run all pending job all in together?

**Comment by psealock** [comment]
Have the pending jobs finished? If not, which ones are still pending?

**Comment by rrennick** [comment]
Closing this for lack of feedback. We're happy to re-open if provided details.
