### ISSUE TITLE
customers endpoint provides invalid customer URL

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2781]
**Describe the bug**
Original report: https://github.com/woocommerce/woocommerce-rest-api/issues/22

Inconsistent results on `v4/customers` and `v4/customers/{userid}`. This would be addressed by bringing in the WC REST API as a package and implementing the `v4` endpoints.

**To Reproduce**

1. Activate WooCommerce only
2. Load `/wp-json/wc/v4/customers`

```
{
  "code": "rest_no_route",
  "message": "No route was found matching the URL and request method",
  "data": {
    "status": 404
  }
}
```

3. Activate `woocommerce-rest-api`
4. Load `/wp-json/wc/v4/customers`

```
[
  {
    "id": 51,
    "date_created": "2019-07-08T14:51:49",
    "date_created_gmt": "2019-07-08T17:51:49",
    "date_modified": "2019-07-08T14:52:27",
    "date_modified_gmt": "2019-07-08T17:52:27",
    "email": "holden25@example.org",
    "first_name": "Abbigail",
    "last_name": "Batz",
    "role": "customer",
    "username": "macejkovic.noble",
    "billing": {
...
    },
    "shipping": {
...
    },
    "is_paying_customer": true,
    "avatar_url": "https://secure.gravatar.com/avatar/cd2a899ae34ec17a2ab22e2ee60bd8ec?s=96&d=mm&r=g",
    "meta_data": [
      {
        "id": 2131,
        "key": "wc_last_active",
        "value": "1562544000"
      }
    ],
    "_links": {
      "self": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers/51"
        }
      ],
      "collection": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers"
        }
      ]
    }
  },
```

5. Activate `woocommerce-admin`
6. Load `/wp-json/wc/v4/customers`

```
[
  {
    "id": 51,
    "date_created": "2019-07-08T14:51:49",
    "date_created_gmt": "2019-07-08T17:51:49",
    "date_modified": "2019-07-08T14:52:27",
    "date_modified_gmt": "2019-07-08T17:52:27",
    "email": "holden25@example.org",
    "first_name": "Abbigail",
    "last_name": "Batz",
    "role": "customer",
    "username": "macejkovic.noble",
    "billing": {
...
    },
    "shipping": {
...
    },
    "is_paying_customer": true,
    "avatar_url": "https://secure.gravatar.com/avatar/cd2a899ae34ec17a2ab22e2ee60bd8ec?s=96&d=mm&r=g",
    "meta_data": [
      {
        "id": 2131,
        "key": "wc_last_active",
        "value": "1562544000"
      }
    ],
    "_links": {
      "self": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers/51"
        }
      ],
      "collection": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers"
        }
      ]
    }
  },
```
7. Deactivate `woocommerce-rest-api`
8. Load `/wp-json/wc/v4/customers` (different order)

```
[
  {
    "id": 137,
    "user_id": 141,
    "username": "ekuhlman",
    "name": "Simone Ortiz",
    "email": "frankie39@example.com",
    "country": "LV",
    "city": "Veumbury",
    "state": "NY",
    "postcode": "24473",
    "date_registered": "2019-07-08T14:55:30",
    "date_last_active": "-0001-11-29T19:45:36",
    "orders_count": 0,
    "total_spend": 0,
    "avg_order_value": 0,
    "date_last_order": null,
    "date_registered_gmt": "2019-07-08T17:55:30",
    "date_last_active_gmt": "-0001-11-30T00:00:00",
    "_links": {
      "customer": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers/141"
        }
      ]
    }
  },
```

9. Repeat with customer URL `https://ron.localhost/wp-json/wc/v4/customers/51`

REST API active - data is the same as the collection endpoint
WC Admin without REST API active is a 404

**Expected behavior**
- The single customer endpoint should exist without the REST API plugin being active
- WC Admin implementation of the `customers` endpoint should deliver the same as or a superset of the REST API endpoint.

**Comment by psealock** [comment]
>This would be addressed by bringing in the WC REST API as a package and implementing the v4 endpoints.

Just making sure I understand here: The WC REST API has the development branch and including it would simply ensure that we'd be using the latest. Is that right?

How does this tie into https://github.com/woocommerce/woocommerce-admin/issues/2181? Portions of the wc-admin api's which will be public (ie, not onboarding) will eventually reside in WC REST API.

**Comment by rrennick** [comment]
> The WC REST API has the development branch and including it would simply ensure that we'd be using the latest.

WooCommerce 3.7 doesn't have the `/v4` endpoints. Activate only WC, then load `/wp-json/wc/v4` in a REST client.

The secondary issue is that both the REST API and WC Admin have a `/wc/v4/customers` endpoint.

**Comment by psealock** [comment]
Would the solution be to rename the endpoint in WC-Admin to something else?

Or, when WC-Admin goes into core, merge the two endpoints such that it includes the parts wc-admin needs, ie `avg_order_value` or `total_spend`? In the meantime, we can make the WC-Admin response include all the details that the REST API also includes for compatibility. Would that work?

**Comment by rrennick** [comment]
> In the meantime, we can make the WC-Admin response include all the details that the REST API also includes for compatibility. Would that work?

I looked at the `v4/products/{product id}` endpoint and that's what it does so we should do that for consistency here.
