### ISSUE TITLE
Additional padding appearing

### ISSUE THREAD

**Issue by CosmikCarrot** [woocommerce/woocommerce-admin#2792]
**Describe the bug**
A large amount of additional padding for users on a different role through iThemes Sync Client Dashboard is present, even though they are on Administrator roles.
See - https://screencast.com/t/IKbJbThcqFB
I’ve figured out that it is this bit of CSS here - https://screencast.com/t/JBWkvT0ta2gj
Is there some CSS I can add just for Admin users that go through the Client Dashboard?
iThemes have confirmed this is a WC issue.

**To Reproduce**

1. Have a user running through iThemes Sync on Administrator role.
2. Click on WC Admin.
3. See padded space.

**Expected behavior**

**Screenshots**
See - https://screencast.com/t/IKbJbThcqFB
I’ve figured out that it is this bit of CSS here - https://screencast.com/t/JBWkvT0ta2gj

**Desktop (please complete the following information):**

* MacOS
* Browser [e.g. Opera]

**Additional context**

**Comment by rrennick** [comment]
This looks like it's an issue in the Sync plugin. Normally the `<div class="wrap">` is inside the `<div id="wpbody-content">`. Have you reported this issue to them as well?

<img width="623" alt="Screen Shot 2019-08-19 at 11 06 19 AM" src="https://user-images.githubusercontent.com/343847/63272144-e88a9500-c271-11e9-85ab-113796b021d3.png">

**Comment by CosmikCarrot** [comment]
Here is a function that has been provided by iThemes to resolve my issue if it helps anyone else.
`function my_custom_admin_css() {
    echo "<style type='text/css'>";
    echo "\n.woocommerce-page #wpcontent, .woocommerce-page.woocommerce_page_wc-admin #wpbody-content {\n";
    echo "\tmin-height: auto\n";
    echo "}\n";
    echo "</style>\n";
}
add_action('admin_head', 'my_custom_admin_css');`
