### ISSUE TITLE
Allow User Role to be selected in Advanced filter under Customer analytics

### ISSUE THREAD

**Issue by JScott-MSI** [woocommerce/woocommerce-admin#2800]
**Is your feature request related to a problem? Please describe.**
Need to be able to see my top Customers, Dealers, Wholesalers, etc.. in the reports. Right now all I can see are all customers together.

**Describe the solution you'd like**
Add Cust Roles as a Filter option

**Should this be prioritized? Why?**
My customers want to be able to see this data

**Comment by rrennick** [comment]
@JScott-MSI Thanks for the suggestion. Could you provide us with some context? WooCommerce core doesn't have dealers, wholesalers, etc.

**Comment by JScott-MSI** [comment]
No, Woo doesn't have those by default, however some of my clients (I create and manage Woocommerce sites for clients) have multiple types of customers, the standard Guest and Customer, but they also have Dealers, Wholesalers, and OEM's who based on their custom cust role get different pricing and price breaks at specific quantities. Typiclly I use the Dynamic Pricing Extension by Woocommerce for these pricing levels. If they are logged in and are a Dealer they see specific Dealer pricing, Wholesale another, etc. The filter should list the user roles that are available so that a report can be generated for that user role type.

**Comment by psealock** [comment]
It seems this should be handled in the extension. Having said that, there is no current way for extensions to hook into advanced filters or sql queries to add a `where` clause.

I created this issue for the Advanced Filters portion, https://github.com/woocommerce/woocommerce-admin/issues/2803. And the SQL queries object issue is already known, https://github.com/woocommerce/woocommerce-admin/issues/2714.

I'm going to close this one out in favour of the two issues above. Upon completion, Dynamic Pricing can update to add filters by user roles.

**Comment by JScott-MSI** [comment]
I'm not sure we're on the same page here... I only mentioned the extension to set the context as was asked. You don't have to be doing what I'm doing in terms of alternate pricing based on user roles, there maybe many other reasons to segment your customers using user roles and wanting to report sales based on a particular segment. This reporting has nothing to do with a specific extension, it has to do with reporting on who/what type of customer is performing best. This analytics has the potential to fill a very big shortcoming in woocommerce, and that is built-in robust reporting. Right now I have to use an Export Orders plugin that allows me to export based on user role and then use a spreadsheet to create my reports. It would be a pity to have to continue to use another plugin because the core analytics doesn't allow selecting user role as an advanced filter.

**Comment by psealock** [comment]
Ok, I see what you're saying. Its just that for most stores, user roles will be the same and a filter here won't be useful. Of course, I could be wrong about that. 

@LevinMedia What do you think? Would an advanced filter in the Customers Report for user roles be something that should live in wc-admin?

**Comment by JScott-MSI** [comment]
I think you'll find that many if not most of the exporting or reporting plugins that have tried to fill the gap, provide the ability to select user role. I use Export Order Items Pro and Woo Import Export neither of which does everything I need by itself. The wc-admin is very promising to me as a robust core reporting solution that can be expanded is sorely needed. If user role is not part of the standard Advanced filter choices, the ability for a developer to extend the filter/query through a filter/hook would be another approach.

**Comment by psealock** [comment]
>I think you'll find that many if not most of the exporting or reporting plugins that have tried to fill the gap, provide the ability to select user role.

That is an argument for advanced filter in Customers Report by user roles instead of being applied by several extensions.

**Comment by psealock** [comment]
>If user role is not part of the standard Advanced filter choices, the ability for a developer to extend the filter/query through a filter/hook would be another approach.

This is the approach we will take for now. If an extension introduces extra roles and wants reporting based off those roles, they can also extend the reports. For example, Dynamic Pricing Extension by Woocommerce.com can create filters for the roles added on the Customer Report as well as others.

#2803 and #2714 will make it possible for extensions to make that happen.
