### ISSUE TITLE
Client side actions for notes

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2804]
Currently the action for any given note either allows a URL or sends a server request via `triggerNoteAction` in wc-api.

Some actions may require more interaction with the page and need to be handled with Javascript.  For example, the plugin installer in this issue  https://github.com/woocommerce/woocommerce-admin/pull/2798#discussion_r314179877 is handled server-side but needs an indicator that the action is pending client-side while the plugin is being installed. 

A quick and easy solution may be to set the button/note/action to pending and have a callback that determines completion.  However, it may be worth also investigation a more JS-hook oriented solution to allow finer control.

<img width="518" alt="Screen Shot 2019-08-16 at 2 20 57 PM" src="https://user-images.githubusercontent.com/10561050/63147551-1c2aac80-c031-11e9-8423-8f1592eb8998.png">
(In the above screenshot, "Install now" has been clicked, but there are no visual cues that the install is currently underway).

**Comment by LevinMedia** [comment]
Per our slack convo: 

We'll introduce a "busy state" on the button that installs the plugin, once it's clicked. After the plugin is installed, we'll update the card with new content. I'll track down who wrote the copy for this and work up the official post install content. 

<img width="908" alt="Screen Shot 2019-10-10 at 11 34 22 AM" src="https://user-images.githubusercontent.com/4500952/66598209-602fbe80-eb55-11e9-99ba-9f7dee87995f.png">
