### ISSUE TITLE
Onboarding - Business Details: 400 error when selecting no other platforms 

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2807]
**Describe the bug**

The `/onboarding/profile` request returns a 400 error:

```
message: "Invalid parameter(s): other_platform"
```

![Screen Shot 2019-08-19 at 5 07 21 PM](https://user-images.githubusercontent.com/1922453/63240531-4506a800-c2a4-11e9-819c-107ad07005fe.png)

**To Reproduce**

Go through the checklist and enter no other platforms on Business Detials. Click continue and see the error.

![Screen Shot 2019-08-19 at 5 09 43 PM](https://user-images.githubusercontent.com/1922453/63240524-3d470380-c2a4-11e9-98b3-8b59f9df9839.png)

**Expected behavior**

I should proceeds to the next screen.

**Comment by joshuatf** [comment]
@psealock I think that may have been resolved by https://github.com/woocommerce/woocommerce-admin/pull/2763 - can you check and see if you still can reproduce this error on the latest master?

**Comment by psealock** [comment]
Yup, fixed on master.
