### ISSUE TITLE
Compare api responses to those in the REST API project

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2809]
**Describe the bug**
While investigating #2781 I compared the WC Admin `/v4/products/{product id}` endpoint to the one in the standalone REST api and found that the related orders list was different between the two results.

We should review each of the common endpoints to ensure that the data being returned is consistent.

## Child Issues

- [ ] https://github.com/woocommerce/woocommerce-admin/issues/2781

**Comment by psealock** [comment]
Good idea. I'll note this issue on the master thread.

**Comment by rrennick** [comment]
Closing in favour of #3205
