### ISSUE TITLE
WooCommerce Admin - Analytics show excluded status in totals at the top

### ISSUE THREAD

**Issue by harwellian** [woocommerce/woocommerce-admin#2810]
Under "Analytics > Taxes" the top totals show dollar amounts and total order counts that include status that are "excluded" in the Analytics settings.

**To Reproduce**

1. Go to Analytics > Settings
2. Exclude 1 or more status
3. Click Save Settings
4. See error in Taxes report

**Expected behavior**
Selected statuses should be excluded from top line

**Screenshots**
![2019-08-19_0849](https://user-images.githubusercontent.com/375905/63270712-50cf7b80-c25e-11e9-8d53-2c20959aabcc.png)
![2019-08-19_0849_001](https://user-images.githubusercontent.com/375905/63270727-54630280-c25e-11e9-8043-7b1ff1b0d1c7.png)

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser chrome
* Version 76.0.3809.100

**Additional context**
In the time period depicted we had 59 orders total, 6 cancelled and 1 failed. Both cancelled and failed are "excluded" from the reports.

**Comment by rrennick** [comment]
This looks like it's a caching issue. If you change the date range on the report after changing the excluded status, the report shows the correct order count and totals.

**Comment by jeffstieler** [comment]
This was fixed in https://github.com/woocommerce/woocommerce-admin/pull/3465.
