### ISSUE TITLE
Add a navigational icon button to the App Bar

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#2811]
We're working on a variety of designs that overlap with wc-admin. Some involve updating existing wc screens, some involve entirely redesigning existing screens, others are introducing new screens altogether. A common theme among all the designs so far is the utilisation of a design pattern that enables users to navigate "back" within a flow.

* WCPay - https://cloudup.com/cg_gIAKfNMS
* WCShip - https://cloudup.com/iDfpEPZlSmo
* On-boarding - https://cloudup.com/cF46ebqdtHx
* Extension purchase flow - https://cloudup.com/iwfUVD3PKhI
* Orders - https://cloudup.com/cmt1l4yEIg2

There's also an existing pattern in Gutenberg: https://cloudup.com/cdbzUKORm2G

Rather than implementing a mish-mash of different versions of this, I think it would make sense to update the existing wc-admin app bar to offer this affordance, in lieu of a larger update in the future.

![design](https://cldup.com/5TtUp6N3fD-3000x3000.png)

This affordance should be optional (not all screens need it) and enable users to navigate "up" a level of navigational hierarchy, or "back" within a flow. Examples:

* Viewing an order details screen, clicking the arrow takes you to the order list.
* Configuring tax during the new on-boarding, clicking the arrow returns you to the configuration task list.

[Updated header bar design in Figma](https://www.figma.com/file/dIrlXkbdtPhQCMepzxmN1uBU/Components-WooCommerce?node-id=46%3A0).

**Comment by psealock** [comment]
Will the back button functionality be preset to go up in hierarchy always or will it sometimes default to browser history?

If the back action is a pre-determined location, I imagine we could expose a hook such that wc-admin pages can take advantage as well as current core pages.

**Comment by jameskoster** [comment]
I think the default behvaiour would be to go up a level in hierarchy. IE going from an order back to the order list.

But it should be possible to override that with a custom url/destination.

**Comment by jameskoster** [comment]
We spoke about the back arrow in more detail at the GM.

The back arrow in the App Bar (https://cloudup.com/cKjAJ7m245R) should be revealed on tertiary screens (IE any screen not represented by a menu item in the navigation).

When clicked it should take the user directly back to the previous screen. Most of the time this will mean going up 1 level in app hierarchy, but not always.

If a user lands on a tertiary screen directly (from an email or something similar) we’ll still display the back arrow, and it will default to taking the user up 1 level in app hierarchy.

**Comment by timmyc** [comment]
Closing this out as the new nav designs make some big changes here.
