### ISSUE TITLE
Customer Analytics Last Active date is off

### ISSUE THREAD

**Issue by derekakelly** [woocommerce/woocommerce-admin#2815]
**Describe the bug**
While viewing the Customer Analytics I noticed that several of the Last Active dates were off by 1 day. It's showing that some customers were last active the day before they signed up. There are also several empty spots.

**To Reproduce**
View customers, and sort by Sign Up

**Expected behavior**
I expected the last active date to match or be after the sign up date.

**Screenshots**
![last active](https://user-images.githubusercontent.com/5824837/63300759-fd355000-c2a6-11e9-99ec-a4dec1b0800d.png)

**Comment by cojennin** [comment]
I was only able to create the off by 1 day issue by doing the following:

1. Set site timezone to UTC+0
2. Create a new customer
3. Set site timezone to UTC-4

When the timezone is set to UTC-4, the customer created when the timezone was set to UTC+0 would now show a `Last Active` date before the `Sign Up` date.

Was this what triggered the issue for you or did you encounter it some other way?

**Comment by derekakelly** [comment]
Hi @cojennin,
I have not adjusted my timezone since my wordpress install was first setup many years ago. Plus, I was only looking at relatively new customers when i discovered the issue.

-Derek
