### ISSUE TITLE
Performance Indicators: Double API requests

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2828]
**Describe the bug**

When viewing the dashboard, the `reports/performance-indicators` endpoint is requested twice with different `before` query parameters.

The first indicates the current time.

```
?before=2019-08-22T12:36:00
```
And the second indicates end of day

```
?before=2018-08-23T23:59:59
```

It appears we can eliminate one request by converging these to the end-of-day time. This is how the other endpoints operate.

**To Reproduce**

1. Visit the dashboard.
2. Make sure you are on a period that includes today, ie today, this week, month to date, etc.
3. See duplicate requests in the Network tab for `reports/performance-indicators`

**Expected behavior**

There should only be one request that matches how we use the `before` parameter by using the end of day time.

**Comment by jeffstieler** [comment]
These requests are for the current year, and the previous year (the default comparison period). I don't think there's any bug here.

**Comment by psealock** [comment]
😳

yeah, that makes total sense now, closing. Thanks @jeffstieler
