### ISSUE TITLE
Onboarding: Lost password flow does not match signup/login

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2831]
The signup and login flows for both the Jetpack and WooCommerce Helper connection processes now match the rest of our onboarding designs.

The one exception to this is the lost password flow, which still looks like WordPress.com and exists on a separate page. The Figma files show a modal-style lost password form design.

Current:

<img width="705" alt="Screen Shot 2019-08-22 at 9 54 13 AM" src="https://user-images.githubusercontent.com/689165/63520522-db181980-c4c2-11e9-94b4-b1fa97bfcf6f.png">

<img width="1131" alt="Screen Shot 2019-08-22 at 9 45 24 AM" src="https://user-images.githubusercontent.com/689165/63519807-95a71c80-c4c1-11e9-8932-b8da3438ef55.png">

Figma:

<img width="816" alt="Screen Shot 2019-08-22 at 9 48 00 AM" src="https://user-images.githubusercontent.com/689165/63520009-f3d3ff80-c4c1-11e9-8d9b-9b2f2a678511.png">

The lost password screen is not part of Calypso, so it looks like we would need to update this on WordPress.com / via WordPress hooks. This would be separate from all the work I've done so far. It also looks like no other application / Automattic service has a branded experience which updates the lost password form.

I'm logging this for now for us to follow-up, but it may be worth discussing the priority of this, since it will take some additional unplanned work. I'd think maybe roughly a 5 or an 8 cc @pmcpinto

**Comment by pmcpinto** [comment]
@justinshreve I think that we should backlog this update, at least until we release the Phase 1.
