### ISSUE TITLE
Causes Sucuri to spam the admin with emails about post update events

### ISSUE THREAD

**Issue by aspiers** [woocommerce/woocommerce-admin#2838]
This plugin does not play nice with Sucuri, which I already had installed.  After installing Woocommerce Admin, I get multiple emails every hour from Sucuri mentioning `Event: Post Update`, e.g.

```
Message: Scheduled-action status has been changed; details: ID: 1846,Old status: new,New status: pending,Title: wc_admin_unsnooze_admin_notes
```

This begs some wider questions around design, e.g. what is the purpose of `wc_admin_unsnooze_admin_notes`?  Does it really need to be run every hour, even on a site which has a blank Woocommerce plugin and no shop set up yet?  Does it make sense for it to be running out of the box?

Perhaps most importantly, should it really be doing things which other plugins detect as updates to blog posts?  I would *much* prefer if Woocommerce plugins didn't touch my blog posts at all, because that's a whole different side to my Wordpress installation than the ecommerce stuff I have planned.  If this plugin is messing around with the `posts` table in my database for no obvious reason, that makes me quite nervous about keeping it running.

## How to reproduce

Simply installing both plugins triggered it for me.

Device / browser information omitted as it is clearly irrelevant.

## Additional context

Woocommerce Admin plugin version: 0.17.0
Woocommerce plugin version: 3.7.0
Wordpress version: 5.2.2

There are quite a few reports online of others experiencing the same issue, e.g.

- https://wordpress.org/support/topic/terrible-plugin-doesnt-play-with-woocommerce-partial-orders-or-publishpress/
- https://wordpress.org/support/topic/message-sending-wc_admin_unsnooze_admin_notes/

**Comment by rrennick** [comment]
@aspiers you can stop these notifications for scheduled actions in your Sucuri settings

- Go to Sucuri -> Settings
- Click the Alerts tab
- Scroll to the bottom of the page
- Exclude the `scheduled-actions` post type

<img width="1067" alt="Screen Shot 2019-08-23 at 3 52 51 PM" src="https://user-images.githubusercontent.com/343847/63616546-2400c880-c5be-11e9-8928-2d42a1d7a2a6.png">

**Comment by aspiers** [comment]
Thanks a lot for the quick and helpful reply!  Although I'm afraid that only partially addresses the issue.  Ideally it would work nicely out of the box without requiring any user intervention, or if that's not realistic then at least these kinds of incompatibilities should be documented with their workarounds.

And then there's all the wider questions I mentioned ...  I would suggest a rethink to see if there's something more proactive that can be done on the design front, otherwise you are likely to keep getting reports like this one.  Thanks again!

**Comment by rrennick** [comment]
> Ideally it would work nicely out of the box without requiring any user intervention, or if that's not realistic then at least these kinds of incompatibilities should be documented with their workarounds.

By default, the Sucuri plugin sends those notifications for any custom post type. You may want to pass your suggestion on to them.

**Comment by toplisek** [comment]
I agree with these issues. Woocommerce plugins involve also blog posts.

Messages can not be blocked inside Sucuri settings. It is the wrong POST field also inside SUCURI. Maybe I'm wrong but wc_admin_unsnooze_admin_notes will not be possible to work.

SUCURI: Only lowercase letters, numbers, underscores and hyphens are allowed. Post Types cannot exceed 20 characters as well.

**Comment by rrennick** [comment]
> Messages can not be blocked inside Sucuri settings.

@toplisek To turn these notifications off see my instructions in https://github.com/woocommerce/woocommerce-admin/issues/2838#issuecomment-524424918

**Comment by toplisek** [comment]
Yes, I tried your instructions. An issue still remains. It contains too many characters.
SUCURI: Only lowercase letters, numbers, underscores and hyphens are allowed. Post Types cannot exceed 20 characters as well.

**Comment by rrennick** [comment]
> It contains too many characters.

`wc_admin_unsnooze_admin_notes` is a hook name not a post type. Per my instructions, exclude the `scheduled-actions` post type.

**Comment by toplisek** [comment]
Sorry for the misunderstanding. As I understand we put STOP ALERTS FROM POST-TYPE: scheduled-actions

Please confirm.

**Comment by rrennick** [comment]
> Please confirm.

Sorry, I inadvertently added an `s`. It's `scheduled-action`.

**Comment by rrennick** [comment]
> Recurrence: Every 1 hour

That's the correct schedule.
