### ISSUE TITLE
Reports API: Use current time for today instead of end-of-day

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2856]
WC-Admin reports use [WP_Object_Cache](https://codex.wordpress.org/Class_Reference/WP_Object_Cache) to cache objects for the duration of a request:

https://github.com/woocommerce/woocommerce-admin/blob/a2424a4d6fa10a5fbe5c6426be518e191876968d/src/API/Reports/Orders/Stats/DataStore.php#L362

Sites that have plugins or other mechanisms to keep those objects between requests are sometimes experiencing odd results in our reports because cached results are being served. For example, Atomic sites use [wp-memcached](https://github.com/Automattic/wp-memcached) to persist objects stored in cache for subsequent requests.

We can address this for requests involving the current day (today, week to date, month to date, etc) by changing the `before` parameter to use the current time instead of end of day.

```
// From this

?before=2018-08-21T23:59:59

// To this

?before=2019-08-21T13:50:00
```
One consideration is zero padding when requesting an interval of `hour`. Currently, we return all hours of the day, which should remain.

![Screen Shot 2019-08-29 at 1 26 14 PM](https://user-images.githubusercontent.com/1922453/63903643-48e3b880-ca62-11e9-9f2a-7c6943272201.png)

Continuing, we may want to make use of `wp_cache_delete` when orders placed in the past are edited or created.

### Additional Context

I don't think removing caching altogether is a good idea. We will need to have caching as a solution to mobile's 5 second timeout problem with Jetpack connected requests. More in p1567040420028900-slack-hogsmeade

**Comment by jeffstieler** [comment]
Looks like we have some prior art to reference: https://github.com/woocommerce/woocommerce-admin/commit/eae74f85e35cb8bfc83c12ecf4a33263104c4083#diff-71321a1ffc66cd298d29c3719d481cd7R177

I haven't thought through all of the potential caveats, but off the cuff - what do you think about baking the logic above into [`appendTimestamp()`](https://github.com/woocommerce/woocommerce-admin/blob/d8809418930c1ad279b5fd5aaa873e654256dc09/packages/date/src/index.js#L58)?

**Comment by psealock** [comment]
In light of this https://github.com/woocommerce/woocommerce-admin/issues/2020#issuecomment-531922459 invalidating caches using the current time is not a good work around. lets go with the solution proposed there and close this issue.
