### ISSUE TITLE
Add custom taxonomies to reports

### ISSUE THREAD

**Issue by Jany-M** [woocommerce/woocommerce-admin#2866]
Is it possible to add custom taxonomies to the reports?
Product categories are not enough, since most ecommerce sites use a granular classification of goods.

It would be great if, from the plugin settings, we could select the taxonomies (related to products) that we want to see in the reports and filters.
Custom coding would also be ok, through the templates functions.

**Comment by rrennick** [comment]
> Is it possible to add custom taxonomies to the reports?

Currently, no. We are in active development of adding extensibility so this could be added via another plugin in the future.

See https://github.com/woocommerce/woocommerce-admin/issues?q=is%3Aopen+is%3Aissue+label%3AExtensibility.

> Custom coding would also be ok, through the templates functions.

Extending WC Admin will typically involve hooks, filters, and/or React code.

**Comment by timmyc** [comment]
Hello @Jany-M 

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
