### ISSUE TITLE
Where is the manual inventory update that used to be a button to sycn woo and square ivnentory?

### ISSUE THREAD

**Issue by zzfranczz** [woocommerce/woocommerce-admin#2869]
**Describe the bug**
Where is the manual inventory update that used to be a button to sycn woo and square ivnentory?
**To Reproduce**
Can not find it anywhere.

**Expected behavior**
Be able to manually sync inventory between Woo and Square.

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by rrennick** [comment]
@zzfranczz Submit a support request at https://woocommerce.com/contact-us/ for assistance with the Square payment gateway.
