### ISSUE TITLE
Deleting read items from WooCommerce Admin Inbox

### ISSUE THREAD

**Issue by jclark12020** [woocommerce/woocommerce-admin#2880]
I am mildly OCD - and want empty inboxes once I have processed everything. How does one empty the new admin panel inbox?

**Comment by psealock** [comment]
Thanks for the question. There is no way at the moment. The idea is that tasks in the inbox may be useful as a reference later, so we will want them around. I think deleting them is valid too. We are internally discussing this as a feature to add however, so I'll close this for now.
