### ISSUE TITLE
Last day of "Week to Date" range has incorrect analytics for the past year period

### ISSUE THREAD

**Issue by lutifyme** [woocommerce/woocommerce-admin#2888]
Description:
When using "Week to Date" range and comparing with 'Previous Year', both Gross Revenue and Net revenue are incorrect for the last date in the range for the past year. For example, if you look at Gross Revenue on Sept 5th 2019, use the 'Week to Date' range and compare it with previous year, analytics for Sept 5th 2018 are incorrect. When using "Month to Date" range the analytics for Sept 5th 2018 are correct.

To reproduce:
1. Make sure you have past data
2. Make some sales
3. Use "Week to Date" range to look at the revenue and compare with last year
4. Write down the revenue for the last date in range of the previous year. For example if testing this on Sept 5th 2019, write down the value for Sept 5th 2018.
5. Use "Month to Date" range
6. The analytics for the last date in range of previous year differs and is the correct one. Using the example from above, Sept 5th 2018 will now display correct analytics.

Expected Behaviour:
In both cases the analytics should match as we are looking at the same date. In our example Sept 5th 2018.

OS: Mojave 10.14.6
Browser: Chrome 76

**Comment by psealock** [comment]
Thanks for the bug report @lutifyme 

I can reproduce this. Today is Sept 23rd and I get different results for Sept 23, 2018 depending on the time range:

### Week to date

![Screen Shot 2019-09-23 at 1 54 26 PM](https://user-images.githubusercontent.com/1922453/65398169-da4c0d80-de09-11e9-9d30-28e4faf149f2.png)

### Month to date

![Screen Shot 2019-09-23 at 1 54 14 PM](https://user-images.githubusercontent.com/1922453/65398182-e3d57580-de09-11e9-8170-315cbcc5d560.png)
