### ISSUE TITLE
Onboarding: Homepage template image replacement

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2902]
In https://github.com/woocommerce/woocommerce-admin/pull/2889 a homepage template function was added that inserts sample content for a homepage.

The images in this content link to a local environment and won't work when added.  We should replace these images with external images URLs (easier) or consider importing images.

`https://local.wordpress.test/wp-content/uploads/2019/05/parallax.jpeg`

<img width="722" alt="Screen Shot 2019-09-06 at 10 13 42 PM" src="https://user-images.githubusercontent.com/10561050/64434661-a4154b00-d0f3-11e9-9d30-1b112f5bcdc6.png">

@jameskoster I know we had some discussion on slack about replacing these images.  What's the verdict on this?

**Comment by justinshreve** [comment]
See p1569434800026500-slack-wc-onboarding and p1569489650028500-slack-wc-onboarding for more discussion about what images to use.

I'm moving this to the backlog until we have a proper answer on implementation.

**Comment by justinshreve** [comment]
List of images: p1571994819021200-slack-wc-onboarding
