### ISSUE TITLE
WC-Admin Inbox message: Add your first product

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2903]
**User Story**
As a merchant
I want to receive suggestions of what I should do after activating the plugin
So I can get my shop up and running as quickly as possible

**Hypothesis**
While we don't deploy the task list, we can use the inbox notifications to guide the user towards the most important actions and we can start with "Adding a product".

**Acceptance criteria**
- Display the inbox message about adding a product
- Redirect the user to the Products' area after he clicks on the button
- Display the message just once, for users that don't have any product:
New users: 1h after registration
Existing users: when they login

The details about the inbox message are in the WC-admin Inbox messages file (line 20)

**Additional context**

It's important to have this deployed in the upcoming WC Admin release, as it would allow us to get useful data before releasing the task list and most likely it's going to increase the number of products added during the first days.

**Comment by jeffstieler** [comment]
> * Display the message just once, for users that don't have any product:
> New users: 1h after registration
> Existing users: when they login

We can't (yet) show notes to specific users: https://github.com/woocommerce/woocommerce-admin/issues/2937

What's the distinction between new/existing users here?

**Comment by pmcpinto** [comment]
> What's the distinction between new/existing users here?

We can use the same distinction that's being applied to the FB notification. I think it's related to the event triggered in the 1st step of the onboarding: `wcadmin_obw_store_setup`

**Comment by pmcpinto** [comment]
> We can't (yet) show notes to specific users: #2937

Ok, so it won't be possible to display the message just for users that don't have any product, correct? Based on this, I'm wondering if it would be more effective to work first on #2937, as it could unlock this and many other notifications.

**Comment by jeffstieler** [comment]
Per our Slack convo:

* No need to check store age ("new vs. existing")
* Just check if there are products

Note content:

**Title:** Add your first product
**Content:** Grow your revenue by adding products to your store. Add products manually, import from a sheet or migrate from another platform 
**CTA:** Add a product (links to `wp-admin/post-new.php?post_type=product`)
