### ISSUE TITLE
Woo Analytics Reporting - Refunds to report in "Products" Section

### ISSUE THREAD

**Issue by Cer983** [woocommerce/woocommerce-admin#2905]
**Is your feature request related to a problem? Please describe.**

I am creating Gross Sales Reports for multiple clients.  The Woo Analytics Reports have the potential to give me exactly what I need.  Currently when I create a product report using Woo Analytics I am not able to include "refunds", which skews my sales numbers.  

**Describe the solution you'd like**
The Analytics "Orders" page DOES show refunds, although the reports do not show me counts of each product so the reports end up being very long.  I would like to see the "refunds" column included in the PRODUCTS page and reports.

**Describe alternatives you've considered**

**Should this be prioritized? Why?**

**Additional context**

**Comment by psealock** [comment]
>I would like to see the "refunds" column included in the PRODUCTS page and reports.

Refunds are related to orders, so how would this work for products? For instance, if an order has several products and a partial refund is issued, how would that be associated with products?

Is there another way to gather the information needed?

**Comment by Cer983** [comment]
Hi Paul,
When we issue a refund for a product we issue it for that specific product
in Woocommerce.  We can dial in to see how much of a refund was given per
product.  We can also designate a refund to be allotted towards shipping,
which I do not need to report.  I'm trying to product a report that I can
send our clients that will show gross sales per product which includes
refunds.

Colleen Ryan

**Comment by Cer983** [comment]
Yes I believe so.

Thank you,
Colleen Ryan

**Comment by rrennick** [comment]
Thanks, closing.
