### ISSUE TITLE
Use a more targeted css selector for padding

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-admin#2923]
**Describe the bug**
On the WooCommerce edit product screen, there are some strange padding issues that are coming from the WC Admin extension. 

**To Reproduce**

1. Go to any edit Product screen. 
2. Click on the **shipping** tab
3. Notice the slight unaligned fields.

If you have WC Subscriptions, this is even more pronounced. See screenshots. 

Looking at the applied styles, there is a `padding: 20px 20px 0;` coming from the `woocommerce-admin/dist/embedded/style.css` file. 

I've tried to find the PR that introduced that style and I think it's this on [#2384/files](https://github.com/woocommerce/woocommerce-admin/pull/2384/files)

**Expected behavior**
The labels and the input fields should be aligned. If I remove or disable WC Admin, the elements look correct and there's no padding applied to the wrap elements. 

I'm not 100% sure what the fix is, if I were to guess, it would be to have a more targeted css selector to apply the padding. 

**Screenshots**

<img width="944" alt="Screen Shot 2019-09-15 at 3 09 36 pm" src="https://user-images.githubusercontent.com/8490476/64926432-596a9180-d7cb-11e9-93c4-312c288c1041.png">

WC Subscriptions:
<img width="1205" alt="Screen Shot 2019-09-15 at 3 13 34 pm" src="https://user-images.githubusercontent.com/8490476/64926438-71421580-d7cb-11e9-888e-281e4c648184.png">

**Comment by psealock** [comment]
Thanks @james-allan for the report. I can reproduce and here is the offending rule:

![Screen Shot 2019-09-25 at 11 15 11 AM](https://user-images.githubusercontent.com/1922453/65557016-e0ff8f80-df85-11e9-9075-f59b5639bf49.png)
