### ISSUE TITLE
Automated hook reference

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2924]
Create a script to scrape wc-admin codebase to compile hook docblocks and publish a reference.

- [ ] PHP reference
- [ ] Javascript reference
- [ ] publish results

Background p90Yrv-17h

**Comment by webkul-amit** [comment]
Hello @psealock ,
in this update do the developers will be able to add custom filter like some sort of new dropdown using react  for filtering data based on custom dropdown value and later adding filter to maupulate data at php end .

**Comment by psealock** [comment]
@webkul-amit Thanks for writing. Reports do have a hook to add an Advanced Filter, similar to the one used in the Orders Report.

![Screen Shot 2019-10-11 at 10 09 52 AM](https://user-images.githubusercontent.com/1922453/66606816-5ff3f980-ec0f-11e9-90e2-7e6a24ab45c0.png)

You can use this to add or append query parameters. We are currently working on adding hooks to modify SQL statements themselves to modify report data. Would this be helpful? If not, can you go into more detail about what you'd like to see?

**Comment by psealock** [comment]
Not stale, thank you
