### ISSUE TITLE
Possibility to show "shiping tax" column in Orders analytics

### ISSUE THREAD

**Issue by benoitfouc** [woocommerce/woocommerce-admin#2931]
Hello, i was trying your plugin many months ago and i tried again  today.
You made a lot of changes and the plugin is better than when I last tested!

Know, i want to know an precise informations :
-what is my NET **revenues** (any periods) for all **new users include NET shipping cost** (without VAT)
And **the same for the returning visitor**.

Can you explain me how can i see this information, because i don’t see the shipping cost (look my screen : https://1drv.ms/u/s!AlTKadrOcs0Xta5ULxCqv7agAhMteA?e=OddoDD).
Can i calculate this ?

Or can i add a column “shipping tax” in the Analytics>Orders page ? Whit this column i can calculate what i want and many types of informations.

thanks

**Comment by timmyc** [comment]
Hello @benoitfouc 

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
