### ISSUE TITLE
poved

### ISSUE THREAD

**Issue by t-brillyth** [woocommerce/woocommerce-admin#2932]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by psealock** [comment]
I'm closing this because there is no content, @t-brillyth. Please open another ticket if you'd like to report a bug.
