### ISSUE TITLE
Change usage tracking auth message in current onboarding

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2934]
Accordingly to the wp.org guidelines, the usage tracking authorization message needs to be opted-out by default. So we need to make the following changes in the Store Setup in the current onboarding:

- Remove the usage track auth message: https://cld.wthms.co/49Ypwm
- When the user click's "Let's go" we then display the following dialog with the checkbox opted-out by default: https://www.figma.com/file/b0b2CrxPZz0i1aAPuv985tvK/Store-Profiler?node-id=3154%3A21
- With this change, the event `wcadmin_obw_store_setup` can only be triggered when the user opts-in in the checkbox and clicks "Continue"

@justinshreve, I would be great to have this deployed on 3.8. Do you think you can make the changes before Oct 1? Thanks.

**Comment by justinshreve** [comment]
This was merged to core and will be a part of 3.8. See https://github.com/woocommerce/woocommerce/pull/24680.
