### ISSUE TITLE
Inbox: Filter notifs by user

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2937]
**Is your feature request related to a problem? Please describe.**

Certain notifications apply only to a specific user. For example, CSV download links delivered by Inbox, https://github.com/woocommerce/woocommerce-admin/issues/2936

**Describe the solution you'd like**

Allow filtering notifications by user.

**Comment by pmcpinto** [comment]
@psealock it would be great to have this feature. One of the ideas for 2020 it's to use the inbox panel to trigger notifications about some specific extensions (tbc) and being able to deliver notifications based on actions would be extremely useful to fine-tune the target audience of each notification.

**Comment by jeffstieler** [comment]
The CSV download notification only needs to filter by user ID. Are there any other use cases we'd like to support?

Perhaps roles, capabilities, user meta values?

**Comment by psealock** [comment]
>Are there any other use cases we'd like to support?

Thinking ahead:
* daily or weekly reports in PDF
* read/unread indicators based on user
* Generally expand the ability of the notification system for extensions

So definitely roles and capabilities. User meta sounds useful, would that be possible?

**Comment by joshuatf** [comment]
Just a heads up that if https://github.com/woocommerce/woocommerce-admin/pull/6167 is merged, we'll have access to roles and capabilities on the front-end.  We can then add a filter to the notes REST API to allow filtering by roles and/or capabilities.

**Comment by pmcpinto** [comment]
Awesome. Thanks for the heads up

**Comment by joelclimbsthings** [comment]
Closing this prior to the merge as per [our guidelines](https://teamisotope.wordpress.com/2021/12/24/issue-triage-grooming-leading-up-to-the-merge%ef%b8%8f/).
