### ISSUE TITLE
Add new properties to the "wcadmin_activity_panel_open" event

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2939]
It's necessary to add two additional properties to the `wcadmin_activity_panel_open` event:

- Messages displayed: we need a property that records the messages that are displayed when the user opens the inbox panel. Without that info it's not easy to have an accurate conv. rate of each message, in order to understand if the user is getting value from them.
- Displayed for more than 4 seconds: this property is useful to indicate that someone could have time to read the notification.

**Comment by psealock** [comment]
>Displayed for more than 4 seconds: this property is useful to indicate that someone could have time to read the notification.

We can do this by adding a timer to check if the panel is still open after 4 seconds, but there is a cost in complexity that comes with that. I just want to make sure you think its a good idea because having an "open for 4 seconds" property with values true or false does seem like low quality data to me. 

What if the inbox contains 20 messages? How can you tell if the one in particular has been read? What if the Inbox is left open on a large screen or maybe the user opens and doesn't read, even after 4 seconds?

**Comment by pmcpinto** [comment]
> What if the inbox contains 20 messages? How can you tell if the one in particular has been read? What if the Inbox is left open on a large screen or maybe the user opens and doesn't read, even after 4 seconds?

Those are good points. Based on that I think we can discard the 4-sec property. @dreiris sounds good to you?

**Comment by psealock** [comment]
Sure, I just changed the priority for visibility during sprint planning.

**Comment by pmcpinto** [comment]
Thanks!

**Comment by jeffstieler** [comment]
> Messages displayed: we need a property that records the messages that are displayed when the user opens the inbox panel. Without that info it's not easy to have an accurate conv. rate of each message, in order to understand if the user is getting value from them.

@pmcpinto we do have the `wcadmin_inbox_action_click` event that fires when note actions are taken - does that satisfy this requirement?

If not, would it be more useful to know what notes are have the "unread" indicator when the panel opens? _(I'll need to double check the feasibility of this, but should be doable)_

**Comment by pmcpinto** [comment]
Hey @jeffstieler, we already have some funnels with `wcadmin_inbox_action_click` and we're keeping an eye on the specific actions that are taken.

The problem is that `wcadmin_activity_panel_open` doesn't give us information about which notifications the users are seeing when they open the panel. For example, we can see how many users clicked on the Facebook notification but we don't have a way to know how many saw that notification, and calculate an accurate conv. rate.

So the ideia would be to have a `note_name` property on `wcadmin_activity_panel_open`, so we could see how many `wcadmin_activity_panel_open` included a specific notice. Having `note_name_unread` instead of `note_name` can be a good option. Let me know what do you think.

Thanks

**Comment by jeffstieler** [comment]
Ok I think I understand what you're after now @pmcpinto.

It seems to me that rather than adding extra props to the `wcadmin_activity_panel_open` event, we should fire a new event for the render/view of each individual note so that conversion can be directly tracked note by note (more akin to JITMs).

How about a `wcadmin_inbox_note_view` event when each note is rendered with at least a `note_name` prop (but probably all the same relevant props from the `wcadmin_inbox_action_click` event)?

**Comment by pmcpinto** [comment]
Hey @jeffstieler, having a new event with all the notes available inside a property sounds like a good idea. And that event would only be triggered when a note is unread like you suggested?

**Comment by jeffstieler** [comment]
> having a new event with all the notes available inside a property sounds like a good idea. And that event would only be triggered when a note is unread like you suggested?

I was thinking that a separate event would fire for each note. (I think that's easier to funnel in Tracks?)

I tihnk it will be possible to only fire the event when the note is unread, and not after.

**Comment by pmcpinto** [comment]
As long as we have each note as a value of a property like `note_name` we can have them all under the same event, as we can create funnels segmented by a specific value of a specific property.

And judging by the Fieldguide, it seems that in this type of situation the Data team prefers to have one event with properties instead of different events:

> Are there any existing events that track the same thing?  If there is a similar event already, consider adding a property to the existing event that distinguishes them.

**Comment by jeffstieler** [comment]
For posterity - we decided over Slack that a JITM style Tracks event is fine. That is: a `wcadmin_inbox_note_view` event with the `note_name` as a prop.

**Comment by jeffstieler** [comment]
Fixed in https://github.com/woocommerce/woocommerce-admin/pull/3096.
