### ISSUE TITLE
Onboarding: change usage tracking auth message in the new onboarding

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2965]
Accordingly to the wp.org guidelines, the usage tracking authorization message needs to be opted-out by default. So we need to make some changes in the new onboarding:

- In the [Welcome Screen](https://www.figma.com/file/b0b2CrxPZz0i1aAPuv985tvK/Store-Profiler?node-id=1250%3A141) we need to remove the checkbox and copy above the button and add the following copy: By connecting your site you agree to our fascinating [Terms of Service](https://en.wordpress.com/tos/) and to share details with WordPress.com
- When the user clicks on "Get started" or on "Proceed without..." we display a modal with the usage tracking auth message ([mockup](https://www.figma.com/file/b0b2CrxPZz0i1aAPuv985tvK/Store-Profiler?node-id=3152%3A25))
- The event tracking `wcadmin_storeprofiler_welcome_clicked` can only be triggered if the user authorizes the usage tracking in the modal (pls confirm if we're able to get the 2 event properties, considering that with this change we can only track after the user clicks on the checkbox and on continue)
- We also need to consider the use case we're the merchant skips that initial screen because he already has Jetpack and/or WCS activated. In that scenario, we need to display the modal after they click on "Continue" in the first screen they see, which is the [Store Details](https://www.figma.com/file/b0b2CrxPZz0i1aAPuv985tvK/Store-Profiler?node-id=1150%3A732)

**Comment by justinshreve** [comment]
Just a note that all of these updates are handled in #2968, except for the TOS link.

That is already present in #2897 (https://github.com/woocommerce/woocommerce-admin/commit/5be65a516aff4a62e0647bc9e0d79d4b076f7a9e).
