### ISSUE TITLE
Order stats status index too long

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2969]
**Describe the bug**
`utf8mb4` requires 4 bytes per character. The `wc_order_stats` `status` field is 200 characters. That totals 800 bytes for `utf8mb4` encoded fields. The MySQL length limit on indexes is `767`. The index needs to be changed to use the first 190 characters of the status field.

Reported in https://wordpress.org/support/topic/import-fails-create-table-error/

**Comment by mikkamp** [comment]
Also causing an issue in 2378328-zen

We used the following query to create the DB table manually with a reduced index size:

```
CREATE TABLE wp_wc_order_stats (
	order_id bigint(20) unsigned NOT NULL,
	parent_id bigint(20) unsigned DEFAULT 0 NOT NULL,
	date_created datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
	date_created_gmt datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
	num_items_sold int(11) DEFAULT 0 NOT NULL,
	gross_total double DEFAULT 0 NOT NULL,
	tax_total double DEFAULT 0 NOT NULL,
	shipping_total double DEFAULT 0 NOT NULL,
	net_total double DEFAULT 0 NOT NULL,
	returning_customer boolean DEFAULT NULL,
	status varchar(200) NOT NULL,
	customer_id BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (order_id),
	KEY date_created (date_created),
	KEY customer_id (customer_id),
	KEY status (status(190))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
