### ISSUE TITLE
WooCommerce Admin plugin needs dynamic filters

### ISSUE THREAD

**Issue by webkul-amit** [woocommerce/woocommerce-admin#2976]
**Is your feature request related to a problem? Please describe.**
No it is not a problem for end user who are using but for developers like me, we needs to customize WooCommerce admin plugin adding custom dropdowns on particular analytics submenu's and later on query related to it as well. so that the data can be manipulative based on filter added.
for eg - i want for a WooCommerce Marketplace plugin i need to add or manipulate data based upon vendor as well.   

**Describe the solution you'd like**
I guess we can achieve this via react Hooks. i will be waiting for solution in core

**Describe alternatives you've considered**
Don't know.

**Should this be prioritized? Why?**
Yes it needs to be prioritized surely cause see there is large community behind as soon as these things are added in core the more will be developer involved and thus will widely used. the problem is none of the developer right can extend the plugin functionalities. due lack of react hooks. 

**Additional context**
negative

**Comment by rrennick** [comment]
@webkul-amit Thanks for submitting the feedback. We already have several extensibility issues (https://github.com/woocommerce/woocommerce-admin/issues?q=is%3Aopen+is%3Aissue+label%3AExtensibility) that we will be implementing through the next few releases.

I'll close this issue. Once the above issues are addressed, if there is something we have missed, please let us know and we can re-open this issue.
