### ISSUE TITLE
Review WC-Admin styles in WP 5.3 Beta 1 environment

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-admin#2978]
I recently updated my development environment to use WP 5.3 Beta 1 and while reviewing some wc-admin pulls today, I noticed that there seem to be some styling issues in the wc-admin with the new WP version. Examples are checkbox contracts seem off, alignment of checked inputs seems off, alignment of some select inputs seem off.

I think wp-admin made some styling tweaks to some admin inputs etc (sorry I don't know the trac tickets offhand) so it'd probably be a good idea to do a review of the wc-admin ui and document what needs fixed.

EDIT: Items to fix:

- [x] Leaderboard title font size
- [x] Bottom border leaderboard title
- [ ] Select field text alignment
- [ ] Input field borders?
~- [ ] Segmented control border~ _This didn't change_

**Comment by psealock** [comment]
Something has also changed with leaderboard tables' title font sizing in the Dashboard.

![Screen Shot 2019-10-10 at 1 49 21 PM](https://user-images.githubusercontent.com/1922453/66530599-ec95ad80-eb64-11e9-9e6c-6c3cd6c5ae03.png)

**Comment by jeffstieler** [comment]
![Screen Shot 2019-11-14 at 10 33 06 AM](https://user-images.githubusercontent.com/63922/68876500-2c9f0180-06ca-11ea-9871-dc3695ce2ab1.png)

It looks like text alignment in select fields is off as well.

Additionally - how should we incorporate (or not) the new border on inputs? You can see several deviations from WP core above (product search and subtotal filters).

**Comment by jeffstieler** [comment]
@psealock it should be noted that the `Card` component styling does specify a `24px`/`1.5rem` font size for its `h2`. It definitely looks off in the leaderboard - perhaps we were relying on a bug before WP 5.3?

![Screen Shot 2019-11-14 at 10 37 28 AM](https://user-images.githubusercontent.com/63922/68877026-0037b500-06cb-11ea-8fda-68f925fc3a4a.png)

**Comment by jeffstieler** [comment]
Missing left/right border on segmented control:

![Screen Shot 2019-11-14 at 10 45 47 AM](https://user-images.githubusercontent.com/63922/68877860-5d803600-06cc-11ea-9f7b-30afef6d0ddf.png)

Another illustration of input styling differences:

![Screen Shot 2019-11-14 at 10 47 50 AM](https://user-images.githubusercontent.com/63922/68877805-4a6d6600-06cc-11ea-8390-f904f4d73119.png)

**Comment by LevinMedia** [comment]
>Additionally - how should we incorporate (or not) the new border on inputs? You can see several deviations from WP core above (product search and subtotal filters).

@jeffstieler lets update the borders that wrap the prefixes and suffixes so that it matches the new higher contrast color in 5.3. Lets also update the corner radiuses to match the new core inputs as well. if it's possible, when there's a prefix or a suffix, can we square off the corners where the prefix or suffix meets the text field?

We should also update our search input to match the border color and radius... as well as adjust the preview text font size / color to match the new text controls.

**Comment by LevinMedia** [comment]
The bit I'm still not sure about is why `TextControl` is styled differently than `TextControlWithAffixes`

In any case, if it's in our control, the text controls should match the text controls in core.

**Comment by nerrad** [comment]
Question:  In fixing things against WordPress 5.3, is there any concern about potentially _breaking_ things against earlier versions of WP (since wc-admin currently requires WP 5.2, that'd only be one older version to check against, but still...)

**Comment by psealock** [comment]
cc @jeffstieler 

>Something has also changed with leaderboard tables' title font sizing in the Dashboard. The border looks off as well.

This is an unrelated change, due to component styles living in the report css file, so the dashboard `Card` didn't get the styles. Fix in https://github.com/woocommerce/woocommerce-admin/pull/3281

**Comment by jeffstieler** [comment]
WP 5.2 on left, 5.3 on right

![Screen Shot 2019-11-25 at 2 29 30 PM](https://user-images.githubusercontent.com/63922/69571426-0ada3000-0f90-11ea-8677-ccd818e73650.png)

**Comment by jeffstieler** [comment]
@LevinMedia 

> The bit I'm still not sure about is why `TextControl` is styled differently than `TextControlWithAffixes`
> 
> In any case, if it's in our control, `TextControl` should match the text controls in core.

Our `TextControl` has Muriel classes on it, so perhaps that's the root of the difference?

The core controls [aren't as stylized](https://developer.wordpress.org/block-editor/components/text-control/) and closer match our `TextControlWithAffixes`.

So.. that said.. do we want to remove the Muriel styles from our `TextControl`, or do we want to make our Muriel-derived styles closer match core (add the border and radius as you've described) and also apply them to `TextControlWithAffixes`?

**Comment by jeffstieler** [comment]
Per Slack convo w/ @LevinMedia:

- `CompareFilter`: add border + border radius (from WP 5.3)
- `DateRangeFilterPicker` & `DropdownButton`: add border + border radius, match chevron
- `Search`: use purple focus from `SearchListControl`, add border + border radius
- `SelectControl` & `TextControl` are both OBW-only (leave alone!)
- `TextControlWithAffixes` - add border + border radius, no radius inboard of affixes
- `StoreAlert` - use WP components for button & dropdown (form select)
- `Pagination` (and `StoreAlert` pagination): remove 3D look, vertical pipe between buttons
