### ISSUE TITLE
Onboarding: WC-Admin Inbox message: Congratulations - your store is ready

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2995]
Once the task list is complete, we are supposed to show a "Congratulations - your store is ready" inbox notification.

https://www.figma.com/file/xyKPRZ73kKhDyNjwbFvBJR/Task-List?node-id=1243%3A164

cc @pmcpinto Do you know what guide this notification should link to?

**Comment by justinshreve** [comment]
Blocked until https://github.com/woocommerce/woocommerce-admin/issues/2685 is complete.

**Comment by pmcpinto** [comment]
I'm not sure what was @jameskoster initial idea for that link. I think it could be interesting to redirect them to the Marketing section of wc.com: https://woocommerce.com/product-category/woocommerce-extensions/marketing-extensions/
