### ISSUE TITLE
Default Dashboard in Days instead of Months

### ISSUE THREAD

**Issue by DarkAllMan** [woocommerce/woocommerce-admin#2996]
I saved my settings to show default “Year to date vs Previous period”
When I choose this setting manually, it shows all data per month, but the default saved settings, shows this per day. This is slow as it needs to load a lot more data!
Is this intended behaviour or a bug?

I would like the default to show per month, when selected YTD.

**Comment by timmyc** [comment]
Hi @DarkAllMan 

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
