### ISSUE TITLE
Order list doesn't show customer name

### ISSUE THREAD

**Issue by alantygel** [woocommerce/woocommerce-admin#3003]
At my Orders Dashboard, the list of orders do not show the customer name. At the Customer column, it shows only "New", although customers are logged in and their names show at Woocommerce.

**To Reproduce**
1. Make an order with a logged in user
2. Go to 'Analytics/Orders'
3. See the list of orders

**Expected behavior**
I expected that customers name would show at customer column.

**Screenshots**
![image](https://user-images.githubusercontent.com/1626935/66277333-17d18180-e873-11e9-8d11-237377b0db6b.png)

For the same order where it shows "New" (novo), the screenshot below shows the name of the customer (Cliente : Patricia Braga).

![image](https://user-images.githubusercontent.com/1626935/66277337-2ae45180-e873-11e9-8999-b08edcc6acca.png)

**Comment by psealock** [comment]
I can toggle the customer column on `main`.

**Comment by alantygel** [comment]
Dear @psealock,

I think my issue was misunderstood. The column customer does show. The content, however, is not the customers name, as I expected, but only a New/Returning indication.

Maybe a screenshot in English can help:

![image](https://user-images.githubusercontent.com/1626935/86281897-a251d200-bbb4-11ea-8065-c6991f0d7be5.png)

Is this correct? If yes, is it possible to add a customers name column?

best,
alan
