### ISSUE TITLE
CSV Download Revenue Report: Fatal Error

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3023]
**Describe the bug**

An emailed CSV download doesn't work for the Revenue Report

![Screen Shot 2019-10-10 at 2 09 17 PM](https://user-images.githubusercontent.com/1922453/66531284-b7d72580-eb67-11e9-897e-0844087993a1.png)

<img width="1381" alt="Screen Shot 2019-10-10 at 2 09 46 PM" src="https://user-images.githubusercontent.com/1922453/66531287-ba397f80-eb67-11e9-8da1-451fe8461097.png">

Looks like there is a controller mapping issue? I see `revenue` isn't mapped.

https://github.com/woocommerce/woocommerce-admin/blob/268e968b9ee7f49656e51389f18e854bca2b34f3/src/ReportCSVExporter.php#L105-L129

**To Reproduce**

1. Revenue Report
2. Make sure there are more than one page of data
3. Click "Download"

**Comment by jeffstieler** [comment]
This is fixed in #2987
