### ISSUE TITLE
Categories: Compare Chart Broken

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3024]
**Describe the bug**

When using the "Compare" functionality on Categories, the chart does not render.

![Screen Shot 2019-10-10 at 3 23 12 PM](https://user-images.githubusercontent.com/1922453/66534220-0db0cb00-eb72-11e9-8600-ee87ebc05fa1.png)

The `/reports/products/stats` endpoint returns a database error `Unknown column wp_term_taxonomy.term_taxonomy_id`

**To Reproduce**

1. Category Report
2. In the table, select 2 or more categories
3. Click "Compare"
4. See the chart not render
5. See `/reports/products/stats` request return an error

**Comment by rrennick** [comment]
This will be fixed in #2961. The error is from a missed term_taxonomy reference in #2253.
