### ISSUE TITLE
Tag versions on WordPress.org

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3025]
We now have 600K+ active installs and should be tagging our releases on WordPress.org to allow users to revert to the previous version in the event we release a version that has a significant bug in it.

Tagging a version requires an extra couple commands in the release process (example version 1.2.3:

```
# from the root of the SVN repo
svn copy trunk tags/1.2.3
svn commit -m 'tagging version 1.2.3'
```

These commands could be added to the end of the release script so that the version is tagged when it's released.

**Comment by psealock** [comment]
Great idea. Can you add a link to the documentation for tagging releases?

**Comment by rrennick** [comment]
> Can you add a link to the documentation for tagging releases?

Instructions added.
