### ISSUE TITLE
Onboarding: Adjust wizard query string and launch Calypso flows

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#3055]
As a part of public user testing and implementing split testing (https://github.com/woocommerce/woocommerce-admin/issues/2759), we need to launch the new onboarding Calypso flows into production.

As a part of this, we will need to adjust the query string we are currently using:

The new feature flagged code uses the same `?from=woocommerce-setup-wizard` query string that the current production version of onboarding users. We need to pick a different query string so both versions of the WooCommerce Calypso flows can be used in production at the same time. https://github.com/Automattic/wp-calypso/blob/809fe3b8ee3b046fcaf569828dee313eefb053ea/client/document/index.jsx#L78-L81

**Comment by justinshreve** [comment]
As a part of this, the default value in the lines below should be switched to `production`:

https://github.com/woocommerce/woocommerce-admin/blob/38c6e92dd7e4cb60d1af791f037e5b2af4cb2b55/src/API/OnboardingPlugins.php#L288

https://github.com/woocommerce/woocommerce-admin/blob/7679c494f6ad443ef31d181c3afd6c08f3ce1030/src/Features/Onboarding.php#L616

**Comment by rrennick** [comment]
@justinshreve Can this be closed?

**Comment by justinshreve** [comment]
@rrennick We still need to enable the new flows in Calypso production, so this issue is only partially handled at the moment. I'll get a PR up for that soon.
