### ISSUE TITLE
Weird Grey Bar

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-admin#3070]
**Describe the bug**
On the "Tell us about your business" section in the new profiler, there's a weird floating grey bar https://cloudup.com/cRmfKvdPlns

**Comment by joshuatf** [comment]
I think @justinshreve may have fixed this in https://github.com/woocommerce/woocommerce-admin/pull/3062 - can you check to see if that PR resolves it for you @warrendholmes?

**Comment by rrennick** [comment]
@warrendholmes I think those were empty image tags for the logos we were waiting for approval to use. I think they should display in 0.21.0.
<img width="474" alt="Screen Shot 2019-10-31 at 4 52 56 PM" src="https://user-images.githubusercontent.com/343847/67981321-20617180-fbff-11e9-911c-8d5e3c8bbf3e.png">

I'll close this. If you still see the grey bars please let us know.
