### ISSUE TITLE
Server-side CSV should respect client-side column visibility

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#3073]
**Is your feature request related to a problem? Please describe.**

The emailed report download contains all columns, not just the ones that are visible based on user preferences.

**Describe the solution you'd like**

The report should only contain the visible columns (in-browser).

**Should this be prioritized? Why?**

I'd say it's not critical, but a nice-to-have.

**Additional context**

https://github.com/woocommerce/woocommerce-admin/issues/2980

**Comment by psealock** [comment]
This was fixed in #2987
