### ISSUE TITLE
Leaderboards: Header styles regression

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3075]
**Describe the bug**

In the dasboard's leaderboards section, table headers have something off in the CSS. As seen below, the title styles on the right are correct.

<img width="899" alt="Screen Shot 2019-10-22 at 9 44 48 PM" src="https://user-images.githubusercontent.com/1922453/67270570-69d20280-f515-11e9-813f-0ae67eaa4824.png">

**To Reproduce**

1. Go to the Dashboard and see Leaderboards section

**Comment by joshuatf** [comment]
FWIW, the left appears to be the default `Card` styling while the right has a class for the tables used in wc-admin.
