### ISSUE TITLE
Inbox notification suggesting to sign up to email marketing

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3079]
In the current onboarding, we have a step where the user can sign up for WC email marketing, which is something that we don't have in the new one.

Displaying an inbox notification about signing up for email marketing seems to be the best option.

@justinshreve I want to check one thing with you before I move forward with creating the notification content, etc:
It's important that the user confirms which email is he going to use to receive our newsletters, so I think there are two options:
- Displaying the email input field in the notification, so the user can add/change the email address and then when he clicks in the button he's just redirected to the Mailchimp page with the captcha
- Not displaying the email input field in the notification and when the user clicks in the button he's redirected to the Mailchimp page where he can add/change the email address (AFAIR they have this option)

Which one do you think it's easier?

**Comment by justinshreve** [comment]
Waiting on a design or alternative way to signup:

p1571764997007800-slack-wc-onboarding

**Comment by joshuatf** [comment]
>Displaying the email input field in the notification, so the user can add/change the email address and then when he clicks in the button he's just redirected to the Mailchimp page with the captcha

I think we may not currently have the ability to control an input within a notification, so the other option to allow editing at Mailchimp may be the best option here.
