### ISSUE TITLE
Store Details step: not able to proceed to the next step after using the autocomplete in some fields

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3081]
I'm getting the following error when I use the autocomplete feature and then click "Continue" to proceed to the next step:

`Uncaught (in promise) TypeError: e.split is not a function
    at Ko (index.js?ver=0.20.1:34)
    at t.<anonymous> (index.js?ver=0.20.1:34)
    at l (index.js?ver=0.20.1:20)
    at Generator._invoke (index.js?ver=0.20.1:20)
    at Generator.e.<computed> [as next] (index.js?ver=0.20.1:20)
    at n (index.js?ver=0.20.1:7)
    at c (index.js?ver=0.20.1:7)
    at index.js?ver=0.20.1:7
    at new Promise (<anonymous>)
    at t.<anonymous> (index.js?ver=0.20.1:7)
`

<img width="1440" alt="Store-Details" src="https://user-images.githubusercontent.com/3380168/67293615-91f13f80-f4dc-11e9-883d-178928ed2435.png">

**Steps to reproduce the behavior:**

- Go to the Store Details step
- Fill address, city and postcode using the autocomplete feature
- Click "Continue", see that nothing happens and check the error in the console

**Expected behavior**
Continue to the next step after filling fields using the Chrome autocomplete

**Comment by joshuatf** [comment]
@pmcpinto I wasn't able to recreate this issue.  A few quick questions to narrow down the source of the issue:

* This appears to be Chrome, what OS was this?
* Can you check to see if similar behavior occurs for you in other browsers?
* If it does not occur in other browsers, can you disable any Chrome extensions to see if this has any affect on the behavior?
* Could you share what was autofilled in your post code field?

**Comment by pmcpinto** [comment]
> This appears to be Chrome, what OS was this?

It was on Chrome v77.0.3865.120 and macOS Mojave 10.14.5

> Can you check to see if similar behavior occurs for you in other browsers?
> If it does not occur in other browsers, can you disable any Chrome extensions to see if this has any affect on the behavior?

I wasn't able to replicate this behavior, including in Chrome. Weird!

> Could you share what was autofilled in your post code field?

It was 1700

Considering that I wasn't able to replicate this, do you think that we should keep this issue open? I plan to do at least one additional round of testing.

**Comment by joshuatf** [comment]
We can keep it open until you test again.  If you're still unable to recreate the issue, feel free to close it out 😄

**Comment by pmcpinto** [comment]
I wasn't able to recreate the issue, so I'm going to close it :)

I'll reopen it if it comes up again
