### ISSUE TITLE
Customize Appearance task: redirect the user to task after creating custom homepage

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3085]
Right now, after the user creates the custom homepage, he's not redirected again to the Customize Appearance task. He needs to click on the WooCommerce Dashboard and then again in the Customize Appearance task to continue that task. 

I'm wondering if we could automatically redirect the user after he publishes the homepage. @jameskoster what do you think?

My video on testing the creating the custom homepage, for reference: https://www.loom.com/share/2e278f30898048c4a3753071b886600b

**Comment by joshuatf** [comment]
@pmcpinto Justin recently added a PR that adds a link to the notice to return to the task.  https://github.com/woocommerce/woocommerce-admin/pull/3061

I think redirecting after publish may be a little confusing for some users, but open to discussion around that.

**Comment by pmcpinto** [comment]
Hey @joshuatf, thanks for the heads up. I agree that the notice seems to be the best option. I'm going to close this issue.
