### ISSUE TITLE
SqlQuery clause refactor to arrays

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3094]
https://github.com/woocommerce/woocommerce-admin/pull/2961 refactors all existing data stores to be more readable and abstract much of the database querying logic to the `SqlQuery` class.

To continue that abstraction, it would be ideal if where and join clauses were in an array format instead of concatenating multiple strings together.

**Benefits**
* Reduced errors from potentially incorrectly concatenated strings.
* Better extensibility and being able to add/remove/update existing clauses.
* Removing duplicated efforts for common clauses (e.g., `where_time` can be placed under `where`).

**Potential Format**
```php
'where' => array(
    'operator' => 'AND|OR',
    'conditions' => array(
        'custom-condition' => 'my_field = "value"',
        'time' => ...,
);
```

This would open the door for a filter or API to modify specific query pieces without attempting to parse the entire statement.

```php
$sql_query->removeWhereQuery( 'custom-condition' );
$sql_query->addWhereQuery( 'my-new-condition', 'property = value' );
```

**Comment by psealock** [comment]
This was fixed, sql parameters are now fully extendable.
