### ISSUE TITLE
WC Admin active time incorrectly calculated

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3098]
**Describe the bug**
The function that checks how long WC Admin has been active for does not seem to be giving accurate times.  This causes notes relying on the plugin being active for some length of time to never be triggered.

https://github.com/woocommerce/woocommerce-admin/blob/7420437ad98e122f9018a75bedd91bb25dc6597d/src/Notes/NoteTraits.php#L24

This appears to be caused by the plugin version not getting updated in the DB causing the install function to be run on every page load:

https://github.com/woocommerce/woocommerce-admin/blob/7420437ad98e122f9018a75bedd91bb25dc6597d/src/Install.php#L57

Additionally, we might want to rethink updating this timestamp as it will get updated on every version change.  

https://github.com/woocommerce/woocommerce-admin/blob/7420437ad98e122f9018a75bedd91bb25dc6597d/src/Install.php#L86

@psealock noted that it may be related to https://github.com/woocommerce/woocommerce-admin/issues/3043

**To Reproduce**

1. Add a version to the option `wc_admin_version` in your `wp_options` table less than the version of WC Admin currently being run.
2. Note that the `wc_admin_install_timestamp` option is updated on every page load.
3. Note that notes requiring a minimum active time are never added (delete them if they already exist to test this).

**Expected behavior**
Expected the install time to match the original install time and active time to return an accurate response.

**Comment by psealock** [comment]
Fix for #3043 is here https://github.com/woocommerce/woocommerce-admin/pull/3113

**Comment by rrennick** [comment]
Closing as fixed.
