### ISSUE TITLE
Onboarding - Set default currency settings based on country

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#3101]
From https://github.com/woocommerce/woocommerce-admin/issues/2768#issuecomment-544628166

> What if instead of asking for the currency upfront we just assume it based on the country and > hard code it?

If the following countries are are selected, we should set smart defaults for the currency, currency position, etc.

* US - dollar
* EU countries - euro
* India - indian rupee
* UK - pound sterling
* Brazil - real
* More 2-3 of the top countries
* Rest of the world - dollar

**Comment by justinshreve** [comment]
Other countries listed here: p1571939906018100-slack-wc-onboarding

**Comment by emanweb** [comment]
What if a store sells in multiple coutries? Will be possible to run reports based on currency?

**Comment by justinshreve** [comment]
Hi @emanweb this issue is for the new onboarding experience that is being built for WooCommerce core, which only supports one set currency out of the box. I've adjusted the title to be a bit clearer about that.

I don't think we currently have plans to run reports based on currency either, since core only supports one currency. Though a multi currency plugin could likely add their own report or hook into reports. cc @psealock
