### ISSUE TITLE
Browser autofill/autocomplete issues when filling out the store details page

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#3102]
Reported at p90Yrv-1iA-p2 #comment-2683:

> Browser autocomplete (in Safari 13.0.2 at least) does not populate the Country/State. Let’s make sure this works with all popular OS/browser autocompletes (FWIW I think this is also broken in the current OBW).

**Comment by justinshreve** [comment]
I was trying to brainstorm ways that this could be fixed.

One method I came up with is to immediately fill in an option if only one result is returned by a result:

Something like adding

```
				if ( filteredOptions.length === 1 ) {
					this.selectOption( filteredOptions[ 0 ] );
					return;
				}
```

right after https://github.com/woocommerce/woocommerce-admin/blob/master/packages/components/src/select-control/index.js#L211-L215.

This seemed to work for me with an Oregon address saved in auto-fill settings. However, I'm not sure if this would work well for other possible combinations. There is also no way to tell an event triggered via autocomplete or a normal user typing -- so this would change the behavior of the component as well (as soon as the results get to 1, that item finishes filling in).

I think the fact country/state is combined could also be an issue here.

cc @joshuatf for other possible ideas.

**Comment by rrennick** [comment]
@justinshreve Just in case it's the same issue- I noticed this today is in the product report with Chrome. When I use the filter to select a single product, it doesn't update the report. If it's not the same issue let me know.

**Comment by justinshreve** [comment]
@rrennick Sounds like a different issue to me. This is an issue specifically with certain browsers autofill behavior and our autocomplete component. Edited the issue title slightly.

**Comment by joshuatf** [comment]
>One method I came up with is to immediately fill in an option if only one result is returned by a result:

@justinshreve I like this solution a lot.  We definitely don't want to make assumptions if there is more than 1 option returned.

> There is also no way to tell an event triggered via autocomplete or a normal user typing

This part is a bit tricky and there doesn't appear to be a straightforward to detect autofilling.  I think we should avoid this behavior for manually entered content.  I whipped together a hacky absolutely positioned input inside this component to try and circumvent this - https://github.com/woocommerce/woocommerce-admin/pull/3105
