### ISSUE TITLE
Document Woo settings affecting calculations

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3108]
As suggested in https://github.com/woocommerce/woocommerce-admin/pull/3095#discussion_r338859557, we should document which WooCommerce settings might affect any of the analytics calculations.

**Comment by pmcpinto** [comment]
@timmyc do you think that we should leave this issue in the backlog?

**Comment by timmyc** [comment]
We still haven't seen a great deal of support volume around this so thinking it is safe to close out.
