### ISSUE TITLE
Gutenberg SASS Variables: Adopt Base Styles package

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3120]
https://github.com/WordPress/gutenberg/pull/17883 Creates a Base Styles package to expose SASS variables. Until now, we have had to copy/paste these into our repo so that postCSS processing could apply Woo themes to Gutenberg SASS files.

https://github.com/woocommerce/woocommerce-admin/blob/b15dfac78a871370d0bd61f06b2160f9a5d0e14a/client/stylesheets/abstracts/_variables.scss#L25

Now that those variables are exposed, we should use them as an import.

**Comment by simison** [comment]
You could prolly replace those `$muriel-` variables with `$studio-` variables from https://github.com/Automattic/color-studio, too.
