### ISSUE TITLE
Onboarding: Theme activation and getter methods

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3123]
https://github.com/woocommerce/woocommerce-admin/issues/2707 adds in a screen to install and activate a theme.  In order to do this, we need a REST API to:

* Get the active theme slug.
* Activate a theme by slug.
* Check if these requests are active (if using wc-api).

We probably don't need an installation method as well since that seems like it will be a part of the wccom checkout flow.

<img width="369" alt="Screen Shot 2019-10-29 at 8 37 14 PM" src="https://user-images.githubusercontent.com/10561050/67767985-87124e00-fa8c-11e9-8e24-4ab422aad308.png">

**Comment by justinshreve** [comment]
@joshuatf I just tested the in-app purchase stuff with a theme and it did indeed install it. It also activated the theme for us, so we might not actually need this piece, at least for the themes from the directory.

Noted that the text reads "extension" but the theme does install: https://github.com/Automattic/woocommerce.com/issues/6617

**Comment by joshuatf** [comment]
Awesome- thanks, Justin.  Closing this issue.

We can re-open if we include more themes other than WC themes and the currently activated theme.
