### ISSUE TITLE
Triggering Notices view when scrolled causes confusion

### ISSUE THREAD

**Issue by garretthyder** [woocommerce/woocommerce-admin#3127]
**Describe the bug**
With the sticky WooAdmin bar the Notices link triggers the show/hide of notices at the top of the screen. If you're already past this section and click 'Notices' nothing aside from the purple underline seems to occur. Yes the notices are displayed above the current screen view but the user doesn't realize this. It would be nice if clicking Notices also scrolls back to the notices so they are placed into view.

As well when notices are visible the 'Help' tab vanishes.

**To Reproduce**

1. Go to any WooCommerce screen.
2. Scroll down a screen.
3. Click the 'Notices' button in the WooAdmin bar.
4. Note nothings seems to happen. The notices do get displayed but the user doesn't realize this.

**Expected behavior**
It would be nice for this action to trigger a scrollback to the notices section.

**Screenshots**
![e01aa8596921b4a3913b75a61e988f41](https://user-images.githubusercontent.com/8726005/67806741-b4410b00-fa50-11e9-8b06-f38617202d9a.gif)

**Desktop (please complete the following information):**

* OS: MacOS Mojave 10.14.5
* Browser: Chrome 77.0.3865.90
* WordPress: 5.2.4
* WooCommerce: 3.7.1
*WooCommerce Admin: 0.20.1

**Comment by psealock** [comment]
@garrett-eclipse Thanks for submitting the issue. Thats a great point, we'll try to address this soon.
