### ISSUE TITLE
request header field x-wp-nonce is not allowed

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-admin#3132]
**Describe the bug**
user in 16309066-HC is unable to use wc-admin and they have heaps of these errors in the console.

**To Reproduce**

Unknown

**Expected behavior**

Requests complete so that wc-admin works

**Screenshots**

https://snipboard.io/vOT1hY.jpg

**Comment by rrennick** [comment]
@WillBrubaker The issue there is that they are logged into `http://` trying to access the API on `https://`. The nonce value from `http://` is being rejected as insecure for the API request. It looks like they have SSL set up so they should be able switch to running the dashboard under SSL.

**Comment by WillBrubaker** [comment]
Thanks for that @rrennick :)
