### ISSUE TITLE
Allow a customer to test an order

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-admin#3137]

**Comment by joshuatf** [comment]
@pmcpinto @warrendholmes Is there anything @justinshreve or I need to help on here?  Or is this covered?

**Comment by pmcpinto** [comment]
Hey @joshuatf this still needs to be scoped. I'll ping you here when we have more info. Thanks!

**Comment by warrendholmes** [comment]
@pmcpinto Perhaps we should use a new label for the backlog of unscoped items?

**Comment by pmcpinto** [comment]
@warrendholmes I agree. Something like needs exploration / needs scoping?

**Comment by warrendholmes** [comment]
@pmcpinto Yep that works.

**Comment by psealock** [comment]
Is this a priority or can we close this issue?

**Comment by timmyc** [comment]
Closing.
