### ISSUE TITLE
Inbox notification about offline payments

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3139]
In the current onboarding we allow merchants to set up offline payments, which is something that's it's not going to happen on the new one. We can instead trigger an inbox notice in order to provide them some guidance. 

Can the notification be triggered depending on the number of active payment methods? I think that it would be better to trigger it only when the user has 0 active payment methods.  

Message content, type and so on TBD

**Comment by joshuatf** [comment]
@pmcpinto Would we want to trigger this after they complete the onboarding profiler?  Or after X number of days without any active payment gateways?

**Comment by pmcpinto** [comment]
> @pmcpinto Would we want to trigger this after they complete the onboarding profiler? Or after X number of days without any active payment gateways?

It would be better to trigger after X number of days without any active payment gateways. I still need to check what's the best timing in terms of days to trigger it.

**Comment by joshuatf** [comment]
@pmcpinto Should we close this issue now that we'll have offline payments directly in the payments task?

**Comment by pmcpinto** [comment]
Yep, I'm going to close it. Thanks!
