### ISSUE TITLE
Removing custom order statuses creates a lot of 404s in WC Admin

### ISSUE THREAD

**Issue by rwkyyy** [woocommerce/woocommerce-admin#3144]
**Describe the bug**
Removing custom statuses from the WooCommerce Orders creates multiple 404s.

**To Reproduce**

1. With WC Admin deactivated, add a custom status
2. Activate WC Admin, do the data migration (import)
3. Disable/remove the custom status
4. List orders (you should see 404's for https://domain.com/wp-json/wc/v4/orders?_fields%5B0%5D=id&page=1&per_page=1&status%5B0%5D=processing&status%5B1%5D=on-hold&status%5B0%5D=custom_status&_locale=user

**Expected behavior**
Some method to detect the order status change so it won't cause this issues

**Screenshots**
N/A

**Desktop (please complete the following information):**

* OS: macOS
* Browser Chrome
* Version 78

**Additional context**
Had a situation on a small store where they wanted to do some clean-ups in the order statuses, we did the cleanups but after a day (or so) we noticed a decrease in performance on the store part of the WP Admin, the solution was to reset and re-import orders.

**Comment by joshuatf** [comment]
Hi @rwkyyy 👋 

I wasn't able to recreate the issue from the instructions above, but I did manage to get a `400` response when setting a custom status to an actionable status (under "Analytics->Settings") and subsequently deleting that custom status.  Does that sound like what happened in your case?

I think it's possible to filter out invalid statuses to avoid those bad calls.  But a re-sync is still probably necessary to fix up old data regarding those order statuses.

**Comment by rwkyyy** [comment]
Hi @joshuatf ,

Yes that's pretty much similar to what happen in our case, only the fact that the developer console was full of 404s (at that version of testing), in conclusion there must be a filter/notice/something that checks for updates on custom order statuses (ideally for post status name, not label).

**Comment by joshuatf** [comment]
@rwkyyy I've got a PR out ( https://github.com/woocommerce/woocommerce-admin/pull/3268 ) that fixes those custom statuses from being added to actionable or excludable statuses.  You're welcome to test this out, but it will also be in master soon.

> there must be a filter/notice/something that checks for updates on custom order statuses (ideally for post status name, not label).

The current PR removes any statuses that aren't available anymore so you won't get those errors you were seeing.  Were you looking for something more elaborate that updates all your data when custom statuses are add or removed?

There's no method in WordPress I'm aware of to watch for add or removed statuses.  But we could store statuses in an option and periodically check if these have changed.  That said, automatically re-syncing data can be somewhat CPU intensive.  If we were to watch for changes, I think a notice to prompt users to re-sync data might be a less costly change.
