### ISSUE TITLE
Improve the Tax task for non-US stores

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3150]
As you can see in the video below it's not that easy for a EU merchant to complete the Tax task:
- First, it was necessary to figure it out that it was required to opt-in on the Enable taxes setting
- Then I would need to figure out that it was necessary to go to Tax Settings - Standard rates and then add a tax rate.

I'm wondering if when the merchant clicks `configure` in the Tax task we could automatically opt-in the Enable taxes setting and redirect him to the Standard rates page.

https://www.loom.com/share/e59ee7e6561e4e22a4c8cac09939c125

**Comment by joshuatf** [comment]
Agreed.  Should be possible to update those settings from the tax task so we can go directly to standard rates.

**Comment by pmcpinto** [comment]
👍In addition to that, I think it would be better to add the following copy: By clicking "Configure" you're enabling tax rates and calculations. More info [here](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-1).
