### ISSUE TITLE
Tax task - automated tax message displayed after setting up taxes manually

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3151]
**Describe the bug**
After manually completing the Tax step if I go back to that step it says that I'm able to automatically calculate taxes, while the first time I started the task it says that I need to calculate them manually

**To Reproduce**

1. Create store with a European address, WCS and Jetpack installed
2. Go to the Tax task and click to configure them manually on settings
3. Configure the taxes on Settings and go back to the task list
4. Enter in the Tax task and see a different message

**Screenshots**
https://www.loom.com/share/ce07ff8682a44f8788d60b5bb17ff3f3

**Desktop (please complete the following information):**

* OS: macOS Mojave 10.14.5
* Browser: Chrome v 78.0.3904.70

**Comment by joshuatf** [comment]
@pmcpinto Thanks for logging the issue!

* What store country were you using?
* If you delete the manually added tax setting, are you able to see the manual tax screen again?  Any other way to recreate the issue if not?
* Jetpack was connected before and after, correct?

**Comment by pmcpinto** [comment]
> What store country were you using?
Portugal

> If you delete the manually added tax setting, are you able to see the manual tax screen again? Any other way to recreate the issue if not?

It still shows the Automated taxes message after deleting the manual tax and disabling tax calculations: https://www.loom.com/share/ccb7b42462554012bc8e8fe819024e51

Let me create a new store, to see if I'm able to replicate the issue. 

> Jetpack was connected before and after, correct?
I think I connected and disconnected Jetpack to check the Welcome screen on the Store Profiler, but Jetpack was connected when I arrived to the task list

**Comment by pmcpinto** [comment]
@joshuatf here it goes the video of a test with a new store: https://www.loom.com/share/9a6b93a1b566454f8726978819a8ea25

As you can see, I have Jetpack and WooCommerce Services installed, store location in Portugal, and it asks me to configure Taxes manually. Unfortunately this time I wasn't able to replicate the automated tax message.

However, I noticed that both stores seem to have the same configuration (Jetpack & WCS installed, Portugal as location) but just one of the stores shows me the Automated Taxes option in settings
- https://cld.wthms.co/6Yl11w
- https://cld.wthms.co/tmQTt9

Maybe there's another setting that can be influencing this?!

**Comment by joshuatf** [comment]
@pmcpinto Here are all the factors required to show the automated tax screen:

* Must set the store to a supported country - see [here])(https://developers.taxjar.com/api/reference/#countries)
* Must have accepted TOS (clicking past the initial step in the profiler should do this for you).
* Must have a complete address filled in (usually handled in the profiler, but there's also a step here to cover that if not filled in).
* Must have all required plugins activated (WooCommerce Services and Jetpack).
* Jetpack must be connected.

Is it possible that any of those changed between your visit to the tax task?

**Comment by pmcpinto** [comment]
@joshuatf sorry for the late reply. So this is weird, today I entered in the same account from last video (testonboarding) and now on this one is also showing me that automated tax message, after setting up them manually:

https://www.loom.com/share/0b94293baba5460f806615b589477548

AFAIR the only thing that I've done between the two recordings was finishing the Shipping task.

Do you want to try to recreate this with a new store?

**Comment by joshuatf** [comment]
@pmcpinto I've tried with a few stores and haven't been able to recreate.  I spun up a fresh store and set the default country to Portugal, but I was instantly taken to the automated taxes "congratulations" screen.

Maybe @justinshreve and I are running newer versions so we can't see the issue.  I just published a new release that seems to work for me.  Can you try this one?  https://github.com/woocommerce/woocommerce-admin/releases/tag/v0.21.0-onboarding

**Comment by pmcpinto** [comment]
Hey @joshuatf, it happened again with the new build. Yesterday it asked me to fill the taxes manually, today I checked the task again and it shows me the automated tax message:

https://www.loom.com/share/29839a4904c9447b9bde0abf7af1417e

I've done the same as in the last time, finish first Tax and then finish Shipping. Do you want me to test it again in a new store?

**Comment by pmcpinto** [comment]
@joshuatf I've done a new test with a brand new store and as you can see in the video it asks to set up the taxes manually and then I set up shipping and nothing changes in the Tax step after complete:

https://www.loom.com/share/1384a96c797845bc9b326830527f28cd


A couple of minutes later I come back to the task and it shows me the automated tax message:

https://www.loom.com/share/1384a96c797845bc9b326830527f28cd

The only thing that I've done between what's happened in the video and the screenshot was testing the Payments task.

**Comment by joshuatf** [comment]
As we discovered in https://github.com/woocommerce/woocommerce-admin/pull/3245, this is an issue with the object caching in Pressable.  Opening an issue there to try and sort this out.
