### ISSUE TITLE
Enable PayPal Checkout button displayed with a wrong color

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3152]
The connect button in the Enable PayPal Checkout step (Payment task) is grey when active, which can misguide users, as the grey color is displayed in inactive buttons:

https://cld.wthms.co/krUwYr

**Comment by joshuatf** [comment]
This appears to be a change to Gutenberg button styling that affects many areas across wc-admin.  

Do we want to override these styles to match our previous styles everywhere?  Or just those in wc-admin?  Or adopt the new styles?

### Current (broken)
<img width="355" alt="Screen Shot 2019-11-01 at 1 51 04 PM" src="https://user-images.githubusercontent.com/10561050/68005019-c0c29f00-fcae-11e9-9307-052af7ff7c69.png">
<img width="285" alt="Screen Shot 2019-11-01 at 1 51 02 PM" src="https://user-images.githubusercontent.com/10561050/68005020-c15b3580-fcae-11e9-896a-7d79bb2f0983.png">

### New styles
<img width="211" alt="Screen Shot 2019-11-01 at 1 50 55 PM" src="https://user-images.githubusercontent.com/10561050/68005028-c61fe980-fcae-11e9-9241-0132091b9a1f.png">
<img width="481" alt="Screen Shot 2019-11-01 at 1 50 53 PM" src="https://user-images.githubusercontent.com/10561050/68005029-c61fe980-fcae-11e9-9d33-fb0294dafff1.png">

**Comment by pmcpinto** [comment]
I think that our previous styles of buttons were more effective. @jameskoster what do you think?

**Comment by joshuatf** [comment]
I can't seem to recreate this issue anymore @pmcpinto.  It's possible another PR resolved the issue.

Can you see if you're still able to see it on the master branch?  And if so, what version of WP are you running?

**Comment by pmcpinto** [comment]
I'm on the Version 5.2.4. But I'm using the last wc-admin build that Justin shared with the new onboarding. So even if another pr solved it I'm not able to check it.

Should we wait for the new build to test it again?

**Comment by joshuatf** [comment]
@pmcpinto Can you try this one and let me know if the issue still exists?  https://github.com/woocommerce/woocommerce-admin/releases/tag/v0.21.0-onboarding

**Comment by pmcpinto** [comment]
Hey @joshuatf, now it's working fine: https://cld.wthms.co/tNscqf

I'm going to close this issue.
