### ISSUE TITLE
[0.21.0] Discrepancies between reports

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce-admin#3157]
**Describe the bug**
We're seeing discrepancies between reports. Not sure which ones are correct.
Here's a few example screenshots, for a month worth of data:

First, notice the net sums being different:
![Screen Shot 2019-11-01 at 12 24 23](https://user-images.githubusercontent.com/890725/68021994-43456180-fca3-11e9-817c-dd3698beaeb1.png)
![Screen Shot 2019-11-01 at 12 24 42](https://user-images.githubusercontent.com/890725/68022006-46d8e880-fca3-11e9-918c-a6d9363e45f9.png)

If we scroll to the bottom of the above pages, we see the following for Orders:
![Screen Shot 2019-11-01 at 12 31 01](https://user-images.githubusercontent.com/890725/68022209-f615bf80-fca3-11e9-9b26-d6b8cb36c5c0.png)
and for Products:
![Screen Shot 2019-11-01 at 12 31 09](https://user-images.githubusercontent.com/890725/68022216-fd3ccd80-fca3-11e9-8f17-1b3d6e1ae2f3.png)

Besides the revenue being different, the items sold is also different.

**Expected behavior**
I expect the math to add up.

**Additional context**
Maybe related to https://github.com/woocommerce/woocommerce-admin/issues/2855 but I think the fix for that was included in 0.21.0.

**Comment by rrennick** [comment]
@larssn Thanks for the report. 

> Maybe related to #2855 but I think the fix for that was included in 0.21.0.

#2918 was the related issue which is still open. We have a few related open issues / pull requests for discrepancies. More recent ones are #3103, #3129, #3009, #2989 .

I'll close this issue as it's already covered in the list above. Once all the above has been addressed we can re-open this if necessary.
