### ISSUE TITLE
Monthly Category Revenue Greater Than Total Monthly Sales

### ISSUE THREAD

**Issue by wazastudio** [woocommerce/woocommerce-admin#3167]
Hi Folks,

Also raised the issue here before finding the github project.
https://wordpress.org/support/topic/monthly-category-revenue-greater-than-total-monthly-sales/

I have a situation where the monthly category sales figures are greater than the total monthly sales.

Images
<a href="https://ibb.co/sQQd68B" rel="noopener noreferrer" target="_blank">Total Monthly Sales</a>
<a href="https://ibb.co/h8jDmy3" rel="noopener noreferrer" target="_blank">Revenue By Category</a>

I think this issue stems from where items are in multiple sub-categories are being counted twice in the parent category, Pharmaceuticals in this example is a parent category and Musculoskeletal System would be a sub category, however – items within Musculoskeletal System will have category paths of

Pharmaceutical and
Pharmaceutical > Musculoskeletal System

Therefore the item is being counted more than once?

Any help figuring this out would really be appreciated

--Terry

**Comment by wazastudio** [comment]
As way of an update the following - you can see from the first image that the NET Revenue for the selected time period for the Pharmaceuticals category is £493.80, however when you click this link and view the items that made up the sales the figure is £246.91 - half of the category amount.

Category revenue overview
https://ibb.co/hfL5CCX

Category breakdown
https://ibb.co/cbqZdLz

**Comment by rrennick** [comment]
@wazastudio Thanks for the report. See my explanation in https://github.com/woocommerce/woocommerce-admin/issues/3009#issuecomment-548805125 on categories totals not matching the table total. 

We currently have a number of PRs pending that address discrepancies in the reports that we hope to have in version 0.22.0. I'll close this issue for now. If you still have discrepancies after that release please let us know. Once those PRs are in place you will need to re-import to affect existing analytics data.
