### ISSUE TITLE
A report showing the past timeframe for all products ordered with details of the variation and quantity

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-admin#3195]
**Is your feature request related to a problem? Please describe.**

It is not possible to view a report of all products including the specific variations sold on a day without accessing each variation report first and manually compiling.

The Product report only shows that there are variations of a product sold but not which variations (#1477).

**Describe the solution you'd like**

A daily report that I can download which lists the quantity sold of every specific product.

Similar to [WooCommerce Sales Report Email](https://woocommerce.com/products/woocommerce-sales-report-email) extension but with more data attached.

I want to know how many of my small black `Tshirt` product I've sold, not just overall.

So instead of this:
```
Tshirt - 120
Belt -75
Cap - 45
```

It would look like this:
```
Tshirt - large black -100
Belt -75
Cap - 45
Tshirt - small black -20
```

In this gif example - https://cld.wthms.co/pwnxEr - I'd expect the report to have two separate lines on the *first screen* for each variation that has been sold.

```
Awesome Steel Bottle - Fugiat
Awesome Steel Bottle - Large
```

**Describe alternatives you've considered**

Current alternatives are to view a report for the timeframe (e.g. past 24hours) and then if a product with variations has been sold, click into the variation and then download that CSV, then repeat this until you have multiple CSV files. 

**Should this be prioritized? Why?**

This is a report which storeowners would find useful and informative for futures sales, merchandising, inventory replenishment, and more.

**Additional context**

Discussed internally here p1572621211207600-slack-wc-admin
Context: 2462743-zen

cc @LevinMedia @timmyc

**Comment by jobthomas** [comment]
Agreed with @dougaitken on this one: there should be at least the option to review variations in the sales report. Some cases:

* Getting an idea in terms of popular variations so they know which variations to focus on for other products
* Getting better/faster idea of which variations they need to stock extra
* Have an option to see the variations connected to their parent product

**Comment by timmyc** [comment]
@warrendholmes where is the best place to log feature requests like this for the new reports?

**Comment by burnaht** [comment]
Really need this working if possible!

**Comment by timmyc** [comment]
cc @pmcpinto

**Comment by fylgjur** [comment]
Another request for this feature in 25397921-hc

**Comment by masteradhoc** [comment]
+1

**Comment by pmcpinto** [comment]
I'm going to close this issue as WooCommerce 4.8 is going to include a new product variations report (see #4330). Feel free to test the WooCommerce 4.8 RC2 available [here](https://developer.woocommerce.com/2020/12/04/woocommerce-4-8-0-release-candidate-2/).
