### ISSUE TITLE
Onboarding: Documentation and user flow

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3198]
As noted by @timmyc, we should document how the new onboarding experience works and how the various pieces of onboarding connect between the store and other sites.

* New REST API endpoints.
* Onboarding filters and hooks.
* WCCOM connection and redirection
* Calypso and Jetpack Connections
* Building the onboarding feature plugin.

**Comment by justinshreve** [comment]
> Building the onboarding feature plugin.

There is already some documentation around this in the feature flags config: https://github.com/woocommerce/woocommerce-admin/blob/master/docs/feature-flags.md#building-custom-plugin-builds.

After the next public release of WooCommerce Admin, it will also be possible to test by running the plugin repo version and setting `WOOCOMMERCE_ADMIN_ONBOARDING_ENABLED`. This is not currently documented anywhere.

**Comment by justinshreve** [comment]
I can start on the documentation for the WCCOM connection and Jetpack/Calypso connections since I've worked on those bits a lot.

Do we think just a new `onboarding` folder in `docs` would be good?

**Comment by joshuatf** [comment]
>Do we think just a new onboarding folder in docs would be good?

I think a single `onboarding.md` file may be enough in the `docs/` folder unless you feel we should split this information up into multiple files.

**Comment by justinshreve** [comment]
Ron raised a good point in the wc-admin meeting today: We should document all the options we use that need reset for a clean slate. Things like the onboarding payments task option, and maybe others like Jetpack TOS.
