### ISSUE TITLE
Move REST API to private endpoints

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3205]
Supersedes #2809, #2181. #2408 proposed to resolve the REST API endpoint conflicts by moving the WC Admin endpoints to a private namespace. The PSR-4 refactor created merge conflicts with moved files.

Spring boarding from #2408, we should implement 2 private namespaces:

- `wc-analytics` for reporting endpoints
- `wc-admin` for updateable uses (eg. settings, product edit, order edit)

**Comment by psealock** [comment]
>Supersedes #2809, #2181. #2408

So with new namespaces, we can leave the API in this repo, right? If thats the plan, should we close out these issues?
