### ISSUE TITLE
Set locale using a filter instead of global

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3217]
**Describe the bug**
https://github.com/woocommerce/woocommerce-admin/blob/master/src/API/OnboardingTasks.php#L118:L120 sets the locale using the global. PHPCS throws an error on modifying a global variable.

We should be able to accomplish setting it to default using a filter.

**To Reproduce**

1. Run `vendor/bin/phpcs src/API/OnboardingTasks.php`

**Comment by rrennick** [comment]
Fixed in #3231

**Comment by joshuatf** [comment]
@rrennick https://github.com/woocommerce/woocommerce-admin/pull/3231 updated the ignore comment only- did we still want to implement this via a filter instead of using global?

**Comment by rrennick** [comment]
@joshuatf I tried setting the locale to `en_US` with a core function `switch_to_locale()` and it broke the unit test for this.  Your PR addressed the initial concern that it was causing the PHPCS tests to fail.

We can re-open to investigate why `false` isn't the same as the default locale.
