### ISSUE TITLE
Customize appearance task - error with header block in homepage

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3219]
When I click to create a homepage I'm getting an error with the header block in the page editor:
- https://cld.wthms.co/wsWF6F

And this is what I see when I click `Resolve`:
- https://cld.wthms.co/VavXjc

If I click `Convert to block` it works fine and I'm able to publish the page

**Comment by justinshreve** [comment]
@pmcpinto What version of WP is this? 5.2 or 5.3? Do you have the Gutenberg plugin installed?

**Comment by joshuatf** [comment]
I'm able to recreate this issue on 5.2.4.  I'll take a stab at fixing this.

**Comment by pmcpinto** [comment]
Hey @justinshreve @joshuatf, I'm using WP 5.3 and I don't have the GB plugin installed.
