### ISSUE TITLE
Test Extension Compatability

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3224]
To prepare for the merge of wc-admin, one task we need to handle is testing wc-admin alongside our Tier 1, and payment extensions. 

### TBD How To Test

I've been combing through P2s today to look at the standard way Extendables, and now Hydra, test out our extensions against new releases of Woo Core, but I haven't come across a definitive ticklist yet. So I will update this issue as I get a better idea of what is typically done. At the very least, installing the extension alongside wc-admin and viewing the site's logs should be a great starting point.

### Extensions To Test

- [x] woocommerce-services
- [x] bookings
- [x] memberships
- [ ] checkout-field-editor
- [ ] fedex-shipping-module
- [ ] follow-up-emails
- [ ] product-add-ons
- [ ] product-csv-import-suite
- [ ] shipment-tracking
- [ ] table-rate-shipping
- [ ] ups-shipping-method
- [ ] usps-shipping-method
- [ ] deposits

### Payment Extensions To Test

- [ ] Affirm
- [ ] Amazon Payments
- [ ] eWay
- [ ] GoCardless
- [ ] PayFast
- [ ] PayPal Advanced
- [ ] PayPal (Express) Checkout
- [ ] PayPal Pro
- [ ] PayPal Pro Hosted
- [ ] Square
- [ ] Stripe

**Comment by justinshreve** [comment]
If the activity panels & breadcrumbs end up staying around, should we also create issues for using the breadcrumb API in these extensions, so things like Bookings get nice navigation structure?

**Comment by timmyc** [comment]
Great question Justin. While I think it would definitely be nice, I'm a bit on the fence with this one as it would be adding extension specific code to wc-admin/core, which I think we should try to avoid. But perhaps we could open PRs on the respective projects to include it there ( on woo-owned extensions ).

**Comment by psealock** [comment]
### Bookings

I created a bookable product and an order for the product using the client interface. No wc-admin errors encountered. The Analytics section is working as it should, reflecting the purchased product. No incompatibilities found.

**Comment by psealock** [comment]
### Memberships

Memberships is also working well, no errors encountered with discount products for members.

Memberships should somehow extend the reports such that discounts due to memberships get reflected either in a new report or Coupons Report.
