### ISSUE TITLE
Home page creation doesn't work with classic editor

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3233]
**Describe the bug**
If the site is set to the classic editor, the onboarding home page designer doesn't work (see screenshots)

**To Reproduce**

1. Go to Settings -> Writing
2. Set the default editor to classic
3. Go to onboarding
4. Add a home page

**Expected behavior**
Probably the best solution is to remove the home page step. It's possible the site has a theme that isn't particularly compatible with blocks.

**Screenshots**
<img width="362" alt="Screen Shot 2019-11-13 at 11 35 09 AM" src="https://user-images.githubusercontent.com/343847/68778789-09148200-060a-11ea-9c3d-955103df62a8.png">
<img width="1049" alt="Screen Shot 2019-11-13 at 11 35 37 AM" src="https://user-images.githubusercontent.com/343847/68778801-0e71cc80-060a-11ea-9ca4-b370963bde3e.png">

**Comment by joshuatf** [comment]
>Probably the best solution is to remove the home page step.

Agreed @rrennick - seems like a smart way to avoid a messy issue.
