### ISSUE TITLE
Payments task - Paypal step - task not being marked as completed after Paypal account creation

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3239]
The Payments task is not being marked as completed after creating a Paypal account:

https://www.loom.com/share/002eba445e1a41e9a8a993f59807fd84

**Comment by justinshreve** [comment]
@pmcpinto I can't seem to reproduce this one.

On that site, could you go under `Settings > Payments > PayPal Checkout > Advanced Settings > Debug Log` and enable logging, and then try going through that connect process again? Do you see any errors under `Status > Logs > PayPal Log`?

**Comment by pmcpinto** [comment]
Hey @justinshreve, here it goes the log:

11-18-2019 @ 10:21:09 - WC_Gateway_PPEC_IPS_Handler::maybe_received_credentials: returned back from IPS flow with parameters: Array
(
    [page] => wc-admin
    [task] => payments
    [paypal-connect-finish] => 1
    [env] => live
    [wc_ppec_ips_admin_nonce] => 2f565034b7
    [merchantId] => d6205124c8b69999ea79c1d68202d29a
    [merchantPayerId] => CS784ZPJHKUA8
    [api_style] => signature
    [api_username] => store_api1.pmcpinto.com
    [api_password] => HXH2LDGK4NA626AS
    [signature] => Aj-dlv26bRPEzhVwYtfCGo2DRaQcAUHqYzOleP14byyTGTmvWkMGNLow
)

11-18-2019 @ 10:21:09 - WC_Gateway_PPEC_Client::_request: remote request to https://api-3t.paypal.com/nvp with params: Array
(
    [METHOD] => GetPalDetails
    [VERSION] => 120.0
    [USER] => store_api1.pmcpinto.com
    [PWD] => HXH2LDGK4NA626AS
    [SIGNATURE] => Aj-dlv26bRPEzhVwYtfCGo2DRaQcAUHqYzOleP14byyTGTmvWkMGNLow
)

11-18-2019 @ 10:21:09 - WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [TIMESTAMP] => 2019-11-18T10:21:09Z
    [CORRELATIONID] => cf7d70781ec65
    [ACK] => Failure
    [VERSION] => 120.0
    [BUILD] => 53802284
    [L_ERRORCODE0] => 10002
    [L_SHORTMESSAGE0] => Restricted account
    [L_LONGMESSAGE0] => Account is restricted
    [L_SEVERITYCODE0] => Error
)

It's weird but not it worked and the step was marked as complete. Do you want me to try to repeat with a new/different account or do we close the issue?

**Comment by justinshreve** [comment]
Was this a fresh PayPal account? I believe PayPal Checkout only works with business accounts, so maybe things were not approved/validated yet? "Account is restricted": https://www.paypal.com/be/smarthelp/article/how-do-i-remove-the-restriction-from-my-account-faq2189

We are relying on the logic of the PayPal plugin to drive the backend connection bits, so I'm not sure there is too much we can do in wc-admin if the redirect is happening correctly (which it looks like it is since the logging fired).

**Comment by pmcpinto** [comment]
> Was this a fresh PayPal account?

yes

> So I think we can close the issue.

Ok, I'm going to close it.
