### ISSUE TITLE
Onboarding: Add notice to complete onboarding profiler / task list

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3242]
In https://github.com/woocommerce/woocommerce-admin/pull/3232 we removed the old notice that prompts the user to finish the setup wizard.

@justinshreve brought up a great point that we might want to do the same for the new onboarding profiler and/or task list.

This is something we can re-evaluate in phase 2 based on how many completed the profiler or task list.

<img width="489" alt="Screen Shot 2019-11-13 at 5 19 54 PM" src="https://user-images.githubusercontent.com/10561050/68828249-06845c00-06e0-11ea-95c0-69f3bb2522cc.png">

**Comment by joshuatf** [comment]
@pmcpinto @jameskoster Do you think we should create this as:
* A standard WP notice?
* An inbox note in wc admin?
* Or both?

**Comment by pmcpinto** [comment]
Hey @joshuatf, can we add event tracking to a wp notice?

**Comment by joshuatf** [comment]
@pmcpinto Most likely, yes.  What did you have in mind?

**Comment by pmcpinto** [comment]
We already have a sense of the conversion rate that we can get using inbox notifications (p6q8Tx-1jR-p2), so I'm thinking that we could use this opportunity to see how the wp notifications work in terms of conversion rate, if we can track the following:
- The user clicks to open the "wordpress notices" in the activity panel and this wp notice it's displayed
- The user clicks to run the profiler or task list
- The user clicks to dismiss the notice

The conv. rate won't be perfect, as the user can also see the wp notice in other places like the wp-admin dashboard, but it can be a good starting point.

**Comment by joshuatf** [comment]
@pmcpinto What if we use a notice style like that of the historical data import?  This will only show on WC pages and can be displayed without the need to click on WP Notices from the activity panel.

<img width="1110" alt="Screen Shot 2020-01-06 at 2 50 05 PM" src="https://user-images.githubusercontent.com/10561050/71800789-fbbcc680-3093-11ea-9270-6231be8ddabb.png">

**Comment by pmcpinto** [comment]
> @pmcpinto What if we use a notice style like that of the historical data import? This will only show on WC pages and can be displayed without the need to click on WP Notices from the activity panel.

👍it seems to be a good option, let's use that one. I think it will be useful to also have a skip button, as we have in the existing onboarding. In terms of copy, I would go with something like:

Title: Welcome to WooCommerce! Set up your store and start selling
Text: We're here to help you going through the most important steps to get your store up and running.
Main cta: Continue Store Setup
Secondary cta: Skip Setup

Thanks!
