### ISSUE TITLE
Woocommerce admin dashboard won't load

### ISSUE THREAD

**Issue by Etsybetsy** [woocommerce/woocommerce-admin#3258]
Hello!

Not sure if anyone else had this issue, but I can't seem to find anything.

I have not been updating the site for quite some time, so I just updated to latest wordpress and latest woocommerce.

When updating the database it had some problem doing it by itself so I ran them manually, I might even have deleted some pending job. Do the pending update jobs come back if I delete them if they are not done?

I have tried the dashboard on Safari and Chrome but the result is the same.

I have PHP 7.0, saw that I should upgrade to 7.2 but does it make so much of a difference?

Anyone have any ideas? I'll attach images of it.

![Skärmavbild 2019-11-15 kl  08 35 25](https://user-images.githubusercontent.com/57789732/68925976-a4316700-0784-11ea-8e73-7823907a5302.png)
![Skärmavbild 2019-11-15 kl  08 39 11](https://user-images.githubusercontent.com/57789732/68925978-a4316700-0784-11ea-9bb3-9ceb4296d0ee.png)

Best regards,
Miska

**Comment by rrennick** [comment]
Hi @Etsybetsy, Github is for reporting bugs vs general support. The support forum is at https://wordpress.org/support/plugin/woocommerce-admin/. You can search there to see if anyone else encountered the same issue with the latest version. If not, you can post a thread for assistance.
