### ISSUE TITLE
Make tracks queue usable outside of WooCommerce Admin

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#3260]
In https://github.com/woocommerce/woocommerce-admin/pull/3250, we added some additional functionality to our tracks implementation that allows you to queue events on the next page load (to avoid race conditions during things like full page redirects).

It was [suggested](https://github.com/woocommerce/woocommerce-admin/pull/3250#issuecomment-554122957) that we make this functionality more widely available (either by implementing it in core's track implementation in a future version) or making our library exportable.

We may need to un-tangle the queue from the page view event if we do this.

**Comment by psealock** [comment]
No longer relevant.
