### ISSUE TITLE
Schema markup error in Search Console

### ISSUE THREAD

**Issue by borombombero** [woocommerce/woocommerce-admin#3263]
Hi,
The website is https://sierraselectricas.com/

Since october, 17th I have this schema markup error “Debe especificarse “offers”, “review” o “aggregateRating””
**Screenshot** http://prntscr.com/psduq4

I don’t have any other schema markup plugin just my theme Rehub and Woocommerce. I think both manage markups by themselves.

I thought that waiting for theme update the problem was fixed but nothing so far but the webdeveloper of my theme told me
"It’s bug of woocommerce comments. Developers are reported and will make fix. Wait woocommerce updates"

Because is a warning from Search Console y can't reproduce the behavior for you just to provide an screenshot 
http://prntscr.com/psdx4j

I've cheked if this problem is normal and I see so many webs haave the same problem

So what is the problem therefore? and its solution?

Regards,

**Comment by rrennick** [comment]
Hi @borombombero, WooCommerce Admin is the plugin for the new WooCommerce dashboard. It does not run on the front end of the site at all. The WooCommerce repo has a few open issues for schema https://github.com/woocommerce/woocommerce/search?q=schema&type=Issues. Check and see if one of those is similar to your issue.
