### ISSUE TITLE
Onboarding: Plugins fail on first install attempt

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3265]
**Describe the bug**
When installing plugins for the first time, a failure usually occurs prompting a retry which then succeeds.

**To Reproduce**

1. On a fresh install, go through the profiler and install Mailchimp/Facebook extensions on the business extensions step.
2. Note the error on first attempt (sometimes?).
3. Note the network error.

**Expected behavior**
Expected plugins to succeed on install and activate the first time.

**Screenshots**
<img width="878" alt="Screen Shot 2019-11-18 at 10 08 01 AM" src="https://user-images.githubusercontent.com/10561050/69020844-e19a2c80-09f0-11ea-885f-f0ad702a062e.png">

**Comment by joshuatf** [comment]
This appears to mostly happen on newer installs, but unclear as to why it's happening.  My first suspicion was the Mailchimp redirect causing some error when making the REST request, but seems like that shouldn't be the case (see - https://github.com/mailchimp/mc-woocommerce/blob/9a8e5f931b7d71e51613af525289b142311507d2/includes/class-mailchimp-woocommerce-options.php#L33 ) and removing any data from `wp_options` doesn't cause the error to resurface.

This also doesn't seem to work on all new installs.  Still unclear as to why that is.

**Comment by justinshreve** [comment]
> This appears to mostly happen on newer installs, but unclear as to why it's happening.

Just curious, have we seen this happen anywhere except a Jurassic Ninja site?

**Comment by justinshreve** [comment]
I managed to get this to fail for me twice earlier on a Jurassic Ninja site, and captured some debug for it using the code in #3272. A full log of some debug can be seen at 231a3-pb.

Both times the install failed, it failed at the unpacking Jetpack. WooCommerce Services installed fine.

```[messages:protected] => Array
[0] => Downloading installation package from https://downloads.wordpress.org/plugin/jetpack.7.9.zip…
[1] => The authenticity of jetpack.7.9.zip could not be verified as no signature was found.
[2] => Unpacking the package…
[3] => Could not copy file. jetpack/3rd-party/3rd-party.php
```

```
[0] => Downloading installation package from https://downloads.wordpress.org/plugin/jetpack.7.9.zip…
[1] => The authenticity of jetpack.7.9.zip could not be verified as no signature was found.
[2] => Unpacking the package…
[3] => Could not copy file. jetpack/json-endpoints/class.wpcom-json-api-add-widget-endpoint.php
```

Since we are using core code directly from our endpoints, these are my current two theories:

1) Something is happening with Jurassic Ninja sites specifically. Maybe related to how quickly we try to install additional plugins after provisioning?

2) The way we issue both install requests back to back could be causing an issue. Though I'm not sure why that would cause an issue with unpacking the package, Maybe we should consider issuing the requests separately (this would slow down the step though).

**Comment by joshuatf** [comment]
AFAIR I've only experienced this on a Jurassic Ninja site.  @pmcpinto have you experienced this outside of a JN site?

`Could not copy file.`

This seems like it's most likely a server permission error lack of disk space.  I wonder if disk space is allocated dynamically for sites, causing this issue.

Either way, if we can get anyone who has experienced this to confirm that no one has seen this outside of JN, I think we can close this issue as this page is responding as expected.

**Comment by pmcpinto** [comment]
> @pmcpinto have you experienced this outside of a JN site?

@joshuatf Nope. In all the tests that I've done, I never had problems with installing plugins.

**Comment by joshuatf** [comment]
This seems very likely a case of a server/environment issue.  Should we remove the debug logging to close this issue @justinshreve?  Or do you think it's better to keep it in place just in case.

**Comment by justinshreve** [comment]
> Should we remove the debug logging to close this issue @justinshreve? Or do you think it's better to keep it in place just in case

I don't think we quite need the level of debugging I have there right now going out in all releases, so I think he can probably roll that back. I'll get a PR up.
