### ISSUE TITLE
Evaluate the weight of @woocommerce/components

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-admin#3289]
I thought I'd initiate this issue to discuss and evaluate the size of `@woocommerce/components` and what can be done to reduce its weight.  Currently, v3.2.0 of the [published package is 2.4mb (minified)!](https://bundlephobia.com/result?p=@woocommerce/components@3.2.0).  This pretty much makes this unusable as an external on the frontend and questionable for usage in the backend as well.  Compare this with `@wordpress/components@8.4.0` which arguably has a roughly equivalent number of components yet [weighs in at about half of woo with 1.1mb](https://bundlephobia.com/result?p=@wordpress/components@8.4.0) (minified, and still large, but less bad).  

**Why?** 

As the external bundle built by this package (on `wc.components`) get's consumed more widely by the WooCommerce ecosystem for extensions etc in the new interface, the size of the bundle increasingly becomes a problem and prohibitive to performant views not needing _all_ the components.

I realize to a degree that the size concerns can be somewhat un-avoidable given what the package contains and the need for keeping everything discoverable and usable.  The same problem exists with the `@wordpress/components` package too.  A couple suggestions:

- identify logical groupings of components and have them live in their own folders within the `@woocommerce/components` package.  The package as a whole can still be published under `@woocommerce/components` (for those consuming directly), but when built to an external, we could export each grouping as it's own bundle.  Thus clients consuming these bundles as external dependencies could just enqueue the bundles they need (reducing overall weight).  As much as possible we should try to keep each grouping contained so that there's less interdependencies.
- alternatively, break up `@woocommerce/components` so it's in similar groupings but each is it's own package.  `@woocommerce/components` then would be a much slimmer package and only very atomic or "leaf" components would go in it.  

Personally I lean more to option 1 than option 2 because those consuming the package directly can just use tree-shaking.  It does complicate the build process a bit for the external bundles but imo it's worth it.  However, even with option 1, I think there's room for evaluating whether some of the components here should live in `@woocommerce/components` or be in more specialized packages.

**Comment by timmyc** [comment]
@senadir did some great exploration on this topic here p90Yrv-1qf-p2

**Comment by timmyc** [comment]
cc @samueljseay as I know this is an area of interest to you.

**Comment by joelclimbsthings** [comment]
Closing this in preparation for the merge, as I believe this is captured by the [issue here](woocommerce/woocommerce#32246) and the [discussion here](https://teamisotope.wordpress.com/2021/06/11/moving-woocommerce-components-forward-a-rough-plan/).
