### ISSUE TITLE
Core Component: Contribute react-dates work up-stream

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#329]
Now that the date picker has stabilized a bit here in the wc-admin project I think it would be a great time to contribute back to the base `@components/date`.

`react-dates` is set to be added as a dependency in https://github.com/WordPress/gutenberg/pull/7621

In 7621, the `DayPickerSingleDateController` is exported to support the use-case of selecting a publish date for a post. In `wc-admin`our current use case is built using the `DayPickerRangeController` - so it kind of feels a good first step would be to add another export to https://github.com/WordPress/gutenberg/blob/fad6a8e137c78d36022ce59a833f98aba0dc1f8c/packages/components/src/date-time/date.js that exports a base example of a date range picker.

Outside of the immediate usage in our own project here, it seems other plugins would benefit from having a core Date Range component - thinking of things like bookings or other date centric product extensions could definitely use this functionality.

@psealock any other key details/learnings from using `react-dates` here in wc-admin that you feel should be contributed back to a core date range selector?

**Comment by aldavigdis** [comment]
I'd recommend holding this off until after WordPress/gutenberg/pull/7621 has been merged.

I have suggested forking `react-dates` and including it in `./packages/`, similar to how MomentJS is included.
