### ISSUE TITLE
Onboarding: Product count dropdown has decimal places

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3312]
**Describe the bug**
On the Business Details step of the profiler, the product count dropdown has decimals.

**To Reproduce**

1. Go to the Business Details step of the profiler.
2. Note the decimals in the dropdown.

**Expected behavior**
Expected integers and no decimals.

**Screenshots**
<img width="555" alt="Screen Shot 2019-11-27 at 9 23 24 PM" src="https://user-images.githubusercontent.com/10561050/69726916-6eb15400-115c-11ea-87ce-3eb5b774051c.png">

**Comment by jeffstieler** [comment]
Introduced in https://github.com/woocommerce/woocommerce-admin/pull/3277.

`numberFormat()` is now bound to the store currency settings, so it has a `precision` value where previously that had to be passed in. The fix in the referenced PR was to switch to using `formatValue( 'number', x )` - I can take care of making that update here.

**Comment by joshuatf** [comment]
Thanks, @jeffstieler!
