### ISSUE TITLE
Onboarding: Currency should update to match store address

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3318]
**Describe the bug**
After selecting a country in the Store Details step of the profiler, the currency in the following steps defaults to WC's default currency of GBP.

**To Reproduce**

1. With a new store, start the profiler.
2. Change the country in the profiler store details step to any country outside the UK.
3. Note that the currency is still in pounds for the Business Details step.

**Expected behavior**
Expected the currency to match the store's default country.

**Comment by joshuatf** [comment]
This appears to be done using locale info in the old OBW - https://github.com/woocommerce/woocommerce/blob/278cf53f2fbfb687514b2c0a008e7c9638f431f8/includes/admin/class-wc-admin-setup-wizard.php#L456

**Comment by justinshreve** [comment]
I already implemented logic to set the currency based on location. seems like maybe there’s an issue with it?

**Comment by rrennick** [comment]
> I already implemented logic to set the currency based on location.

It was working for me when I was doing the i18n fix for the business details dropdown.

**Comment by joshuatf** [comment]
I just ran through with [this release](https://github.com/woocommerce/woocommerce-admin/releases/tag/v0.22.0-onboarding-112519), selecting Canada as my country and was shown GBP for revenue options in the dropdown.

It should already be included in that release, right? /cc @justinshreve @rrennick

**Comment by joshuatf** [comment]
Follow-up: it did update the currencies, but after page refresh.  The global that holds the currency client-side probably isn't updated to reflect the new settings.
