### ISSUE TITLE
Onboarding: Return to task list notices

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3319]
As noted by @msdesign21 :

>Perhaps we keep the notice up longer or there’s a better opportunity for us to celebrate their first product published. Ex. “🎉 Congrats on adding your first product! Continue Setup”

This issue will involve 2 items:
* Updating the success messages to be more upbeat and celebratory 🌮 🎉 
* Seeing if we can extend the time the core notice is displayed on the screen. ⌛️

**Comment by justinshreve** [comment]
> Seeing if we can extend the time the core notice is displayed on the screen.

I looked around, and I'm not sure if this is possible right now. It looks like the notice timout is hard coded, and there are no options for it: https://github.com/WordPress/gutenberg/blob/f4d5d500630e44e4f2b0cb160fed7c0ca2ee353a/packages/components/src/snackbar/index.js#L18.

**Comment by joshuatf** [comment]
Do we think we should update all messages to have this new tone?  Or should this only affect task list completion messages?

For example, we have this message which occurs across different areas of onboarding when plugins are created: `Plugins were successfully installed and activated.`

Would also love to get some input and ideas for the remaining message copy. /cc @jameskoster @pmcpinto @msdesign21

**Comment by pmcpinto** [comment]
> Do we think we should update all messages to have this new tone? Or should this only affect task list completion messages?

I feel that this tone should be exclusive to the task list completion messages, as all the tasks require some work.

All the steps in the store profiler seem to be pretty straightforward, so I wouldn't change the notices there.

> Would also love to get some input and ideas for the remaining message copy.

Some suggestions:
Adding a product: Maria's suggestion looks good
Importing/Migrating products: 🎉Congrats on adding your first batch of products! Continue Setup
Customize appearance: 🎨Your store is looking good. Don't forget to continue personalizing it
Configure shipping: 📦Shipping done! Don't worry, you can always change it later
Configure taxes: You're awesome! One less item on your to-do list ✅
Configure payments: 💰Kat-ching! Your store can now accept payments 💳
Purchase extensions: Purchase completed! A great choice for your store 🙌
