### ISSUE TITLE
Reporting by listing out how many of each product

### ISSUE THREAD

**Issue by klwdp** [woocommerce/woocommerce-admin#3320]
Hi

I would like the following to be added to the Woocommerce Admin plugin.

My client sells food. They need to be able to run a report that lists out how many of each product has been sold in any given week.

Can this be added please?

Thanks

**Comment by rrennick** [comment]
> They need to be able to run a report that lists out how many of each product has been sold in any given week.

You can do that with the existing reports. Go to Analytics -> Products and choose the date range.
