### ISSUE TITLE
Pending wc_admin_unsnooze_admin_notes

### ISSUE THREAD

**Issue by littlepackage** [woocommerce/woocommerce-admin#3360]
**Describe the bug**
It seems like pending wc_admin_unsnooze_admin_notes are not deleted on plugin deactivate, and the job continues hourly, spitting to WP comments. I see many people also complaining about this online the past several months.

**To Reproduce**

1. Deactivate Woo
2. Deactivate Woo Admin
(not necessarily in that order)
3. Several days later find 4000+ approved comments by Author "ActionScheduler" in response to "wc_admin_unsnooze_admin_notes" in WP comments.
4. Reinstall WP. Head over to Status->Scheduled Actions to find wc_admin_unsnooze_admin_notes still pending. 
5. Delete the pending cron
6. Stop getting hourly comment "spam"

**Expected behavior**
wc_admin_unsnooze_admin_notes should be removed when Woo Admin is deactivated.

**Desktop (please complete the following information):**

* OS: Mac 10.15.1
* Browser Firefox 71

**Comment by rrennick** [comment]
This is being discussed in https://github.com/woocommerce/woocommerce/issues/25127. Per my comment https://github.com/woocommerce/woocommerce/issues/25127#issuecomment-559491464 this occurs with any post type with comments when the plugin is deactivated.

Action Scheduler 3.0 https://github.com/woocommerce/action-scheduler/releases moves its data to custom tables so this issue will be resolved when it is included on WooCommerce.

@littlepackage The way to have had those automatically removed by WC Admin would have been to deactivate WC Admin then delete the plugin using the plugin screen. Once it was deleted you could deactivate WooCommerce.

Closing as this is being addressed elsewhere.

**Comment by littlepackage** [comment]
Thanks. But I cannot delete the plugin because it's on a multisite installation where other sites are using it.
