### ISSUE TITLE
Data Layer: Migrate to wp.data

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3384]
Background & Discussion: p90Yrv-1os-p2

As a result of some great discussion on the topic from the team, and others across the Woo Division, we will be migrating our current `fresh-data` data stores to standardize on the `wp.data` package shipped in WordPress core. Per @nerrad's exploration, we will use WordPress 5.3 as a development baseline as he explored already in #3313 

New stores should be created in a new `@woocommerce/data` ( any feedback on the naming there would be appreciated ) package, so they can be exportable/consumable by other development teams throughout the WooCommerce ecosystem.

While the migration to the new data layer would be nice to have prior to core merge, this is not considered a blocker.

**Comment by psealock** [comment]
With all stores having been migrated, we can close this out.
