### ISSUE TITLE
Testing in WooCommerce Core

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3392]
With @psealock's work that brought us to:

https://github.com/woocommerce/woocommerce/pull/25011

It is time to put some various flows through the paces. Here are some scenarios I would like us to test out... please do add more if you think of them. But testing the branch above in the following setups.

- [x] Clean WooCommerce install ( no prior wc-admin present ). Verify wc-admin functionality.
- [x] wc-admin installed, but not activated
- [x] Same as above, but then activate wc-admin
- [x] wc-admin installed, and activated. Like the blocks repository, if this setup is encountered, verify the plugin takes precedence.
- [x] Same as above, but then deactivate and uninstall the wc-admin plugin. Database tables for wc-admin *should not* be dropped, and wc-admin functionality that is now active via woo core should operate as expected.

Mainly I'm very curious to test out db migrations as well. I have a feeling the last test flow above could result in tables being dropped, re-added, but empty which would lead to some 😢

**Comment by jeffstieler** [comment]
> I have a feeling the last test flow above could result in tables being dropped, re-added, but empty which would lead to some 😢

I can confirm - deleting the plugin results in all tables being truncated 😱

**Comment by timmyc** [comment]
> I can confirm - deleting the plugin results in all tables being truncated

Seems like we might be able to add some logic to uninstall to prevent this from happening based off Woo core version

**Comment by jeffstieler** [comment]
> Seems like we might be able to add some logic to uninstall to prevent this from happening based off Woo core version

Was working on this before I saw your comment - chose to look for the plugin files instead of checking version: https://github.com/woocommerce/woocommerce-admin/pull/3546

**Comment by jeffstieler** [comment]
Question - what should happen if someone deletes core WooCommerce, but the WooCommerce Admin feature plugin is active?

Right now, that would cause all WC-Admin tables to be dropped, and then the active plugin would be dormant because its dependencies aren't met.

**Comment by jeffstieler** [comment]
Looks like the `wc_admin_process_orders_milestone` cron hook is getting doubled up when the feature plugin is enabled.

**Comment by jeffstieler** [comment]
I'm not seeing the `wc_admin_daily` event get created (or at least hooked into as far as WP Crontrol is concerned) when WC Admin loads from the core package.

**Comment by jeffstieler** [comment]
#3580 preserves the scheduled actions and cron events when the feature plugin is disabled.

**Comment by psealock** [comment]
@timmyc, with all the bulleted tasks satisfied, I think we can close this one. What do you think?

**Comment by timmyc** [comment]
<3
