### ISSUE TITLE
"Call to undefined function Automattic\WooCommerce\Admin\Features\wc_get_screen_ids()" CRITICAL error during Jetpack Sync

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-admin#3394]
**Describe the bug**
Users receive the following error during Jetpack sync after WooCommerce Admin has been updated to `0.23.0`:

> CRITICAL Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\Features\wc_get_screen_ids() in /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php:616

**To Reproduce**
1) Force Jetpack sync from https://jetpack.com/support/debug/
2) Receive a Critical error:

```
2019-12-08T09:20:45+00:00 CRITICAL Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\Features\wc_get_screen_ids() in /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php:616
Stack trace:
#0 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): Automattic\WooCommerce\Admin\Features\Onboarding->update_help_tab(Object(WP_Screen))
#1 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.3/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /wordpress/core/5.3/wp-admin/includes/class-wp-screen.php(412): do_action('current_screen', Object(WP_Screen))
#4 /wordpress/core/5.3/wp-admin/includes/screen.php(241): WP_Screen->set_current_screen()
#5 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(365): set_current_screen('sync')
#6 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(457): Automattic\Jetpack\Sync\Sender->get_items_to_send(Object(Automattic\Jetpack\Sync\Queue_Buffer), true)
#7 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(326): Automattic\Jetpack\Sync\Sender->do_sync_for_queue(Object(Automattic\Jetpack\Sync\Queue))
#8 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(261): Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays(Object(Automattic\Jetpack\Sync\Queue))
#9 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-actions.php(482): Automattic\Jetpack\Sync\Sender->do_full_sync()
#10 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-actions.php(447): Automattic\Jetpack\Sync\Actions::do_cron_sync_by_type('full_sync')
#11 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): Automattic\Jetpack\Sync\Actions::do_cron_full_sync()
#12 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#13 /wordpress/core/5.3/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#14 /wordpress/core/5.3/wp-cron.php(138): do_action_ref_array('jetpack_sync_fu...', Array)
#15 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php on line 616
```

**System Status**

```
Jetpack by WordPress.com: by Automattic – 8.0
WooCommerce Admin: by WooCommerce – 0.23.0
WooCommerce: by Automattic – 3.8.1
```

**Additional context**
Initially reported here - p1575792461139700-slack-C2C8F5PNJ

Bumping it to Critical due to the scope and because it causes `Your Site is Experiencing a Technical Issue` to be sent to site admins.

**Comment by simplysaru** [comment]
I had the same issue with a customer on live chat today. The customer is hosted on WordPress.com User got an email from us with this message. 


> Error Details
=============
An error of type E_ERROR was caused in line 616 of the file /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php. Error message: Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\Features\wc_get_screen_ids() in /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php:616
Stack trace:
#0 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): Automattic\WooCommerce\Admin\Features\Onboarding->update_help_tab(Object(WP_Screen))
#1 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.3/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /wordpress/core/5.3/wp-admin/includes/class-wp-screen.php(412): do_action('current_screen', Object(WP_Screen))
#4 /wordpress/core/5.3/wp-admin/includes/screen.php(241): WP_Screen->set_current_screen()
#5 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(365): set_current_screen('sync')
#6 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(457): Automattic\Jetpack\Sync\Sender->get_items_to_send(Object(Automattic\Jetpack\Sync\Queue_Buffer), true)
#7 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(326): Automattic\Jetpack\Sync\Sender->do_sync_for_queue(Object(Automattic\Jetpack\Sync\Queue))
#8 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(293): Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays(Object(Automattic\Jetpack\Sync\Queue))
#9 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-actions.php(482): Automattic\Jetpack\Sync\Sender->do_sync()
#10 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-actions.php(437): Automattic\Jetpack\Sync\Actions::do_cron_sync_by_type('sync')
#11 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): Automattic\Jetpack\Sync\Actions::do_cron_sync()
#12 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#13 /wordpress/core/5.3/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#14 /wordpress/core/5.3/wp-cron.php(138): do_action_ref_array('jetpack_sync_cr...', Array)
#15 {main}
  thrown

**Comment by iamgabrielma** [comment]
Another one here: 17183852-hc

**Comment by chickenn00dle** [comment]
Another one here: 2546596-zen

**Comment by psealock** [comment]
`0.23.1` has been released with a fix for this. I'll close, thanks.

**Comment by edwinoonk** [comment]
since this update (and the fix) in the woocommerce app and the dashboard I see all orders but they show up with 0 euros. So I now have x number of sales and 0 turnover in the stats.

**Comment by khaliltws** [comment]
one more here today !
