### ISSUE TITLE
WooCommerce Admin install prompt admin notice displays even if site has wc-admin plugin installed and active

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-admin#3396]
**Describe the bug**
We have an admin notice to encourage merchants to try WooCommerce Admin. If WooCommerce Admin is installed, this probably shouldn't be displayed :)

**To Reproduce**
- Install WooCommerce & WooCommerce Admin on a test site
- See admin notice:

<img width="1625" alt="screen_shot_2019-12-09_at_8 45 48_am" src="https://user-images.githubusercontent.com/4167300/70395161-e33f9900-1a60-11ea-97fb-c4e67e270cd2.png">

**Expected behavior**
No notice if wc-admin is installed, or a more relevant notice.

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Safari
* Version: 13.0.3 (15608.3.10.1.4)

**Additional context**

**Comment by haszari** [comment]
I think this was because I had installed wc-admin using wp-cli using GitHub url. This installed it in a folder with different name:

`wp plugin install https://github.com/woocommerce/woocommerce-admin/releases/download/v0.23.0/woocommerce-admin.zip`

Installed to folder `woocommerce-admin-avs5Va`.

**Comment by joshuatf** [comment]
@haszari Thanks for the issue report!

Since this notice is added via WooCommerce and not directly from this plugin, I opened an issue there so we can follow up on this.  https://github.com/woocommerce/woocommerce/issues/25394

Will close this issue and track there.
