### ISSUE TITLE
Dashboard blank Uncaught TypeError: Io.filter is not a function

### ISSUE THREAD

**Issue by amandasjackson** [woocommerce/woocommerce-admin#3416]
**Describe the bug**
When trying to view the Dashboard located at **WooCommerce>Dashboard** it is blank. Inspecting the page reveals an error `Uncaught TypeError: Io.filter is not a function`

**To Reproduce**
Steps to reproduce the behavior: I cannot reproduce on my test site. This customer has GoDaddy hosting so wondering if this issue is specifically related to that.

I tested on the customer's staging site with only WooCommerce, WC Admin, Jetpack and Storefront theme and the issue persists. 

1. Go to **WooCommerce>Dashboard**
2. View that it is blank on this site and showing the following error `Uncaught TypeError: Io.filter is not a function`

**Expected behavior**
When I view the Dashboard I should see something other than a blank screen

**Screenshots**
![Screenshot](https://d.pr/i/dYWgKT+)
Screenshot direct link: https://d.pr/i/dYWgKT

2547812-zen

**Comment by timmyc** [comment]
Thanks for the report @amandasjackson - `.filter()` is used extensively throughout the code base, including a number of ways which could impact the Dashboard page. Couple of questions:

- Do other report pages under the Analytics menu item work at all?
- Are there any REST API errors under the Network tab when the dashboard loads?
- Is there anyway we could access the staging site and perhaps install a development version of wc-admin?

**Comment by meloyelo51** [comment]
This was actually opened on my behalf from plugin support team.  So the other analytic reports seem to "load" fine...but it's like there's no site data to fill it out.....Everything is $0, 0 orders etc.  Wondering if this where the woocommerce mobile app tried to feed off of refusing to load my site at all when I turn on the advanced reporting beta option. Which fixes itself when I turn it back off.

I am not sure if I am checking exactly what you want in #2, but I can give access to staging site.  All personal info etc has been removed already for previous testing.
![ss 12-18 416pm](https://user-images.githubusercontent.com/32083756/71123961-d97d0a80-21b1-11ea-9ec1-7671d4c44874.PNG)

**Comment by timmyc** [comment]
Thanks for the update @meloyelo51 - that is the correct tab in the console, if you could set the "XHR" filter that would limit it to the API requests. And if you could send along a test login via your original support ticket, I would login and poke around to see what i can see. Apologies again that you are hitting an issue here.

**Comment by meloyelo51** [comment]
test site info added to ticket
#2547812

Thank you so much for looking into it.
I did realize the above errors were actually from the prod site, but still getting io.filter errors in the staging site...not the websockets...or it's something that comes and goes(?)  But not much change on XHR or I'm doing it wrong.

**Comment by amandasjackson** [comment]
Hey @timmyc sorry I missed replying to the ping above! I see you have been working through this with @meloyelo51 but it looks like we did not get login access in time. Please let me know if there is anything further I can do to help.

**Comment by timmyc** [comment]
Thanks @amandasjackson, indeed I have worked with them directly to resolve the issue, but forgot to close the loop here. Essentially, it appears their install of woo core was missing some of the built JS files from the Woo Blocks package which wc-admin requires to interact with Woo settings. Re-installing Woo fixed the problem.

**Comment by meloyelo51** [comment]
Yes, thank you all for the help.

The reinstall itself didn’t actually fix it…but the work around was using the alternate wp-cron function as we think it was being blocked by hosting plan.

**Comment by timmyc** [comment]
Hey @meloyelo51 - indeed there were a couple of different problems at play on your setup. The first though, the error detailed here was resolved by re-installing WooCommerce core, the other issue that you noted above around the job queue not being run definitely seemed to be something with the hosting setup.

**Comment by meloyelo51** [comment]
Ahh yes, I totally forgot about the original problem lol
