### ISSUE TITLE
Changing page capability does not restrict access to unprivileged users

### ISSUE THREAD

**Issue by piotrusin** [woocommerce/woocommerce-admin#3423]
**Describe the bug**
Changing page capability to anything other than view_woocommerce_reports does not restrict access for users without that capability (view_woocommerce_reports).

For example:
add_filter('woocommerce_navigation_connect_page_options', function($options){
	$options['capability'] = 'test_capability';
	return $options;
});

**To Reproduce**
1. Change capability by using the filter:
add_filter('woocommerce_navigation_connect_page_options', function($options){
	$options['capability'] = 'test_capability';
	return $options;
});
2. Log in to user account without "view_woocommerce_reports" capability.

**Expected behavior**
Page shouldn't be available for viewing for users without permissions.

**Comment by jeffstieler** [comment]
Hello @piotrusin,

Which pages are you trying to restrict access to?

The "connect" page functionality is meant to render WooCommerce Admin features on pages that have already been registered with `add_menu_page()` or `add_submenu_page()` - the capability required to view them is set in those calls.

I do see that there isn't a filter in our `PageController::register_page()` method, which calls the `add_menu_page()` or `add_submenu_page()` functions before `connect_page()` which houses the filter you're hooking into.

If you're looking to change the WooCommerce Admin page capabilities, perhaps the [`woocommerce_analytics_report_menu_items`](https://github.com/woocommerce/woocommerce-admin/blob/69e64b109899a2294516a014b857b72b89218773/src/Features/Analytics.php#L148) filter can suffice.

Though, I think the real solution here is to:
* Change the default capability [here](https://github.com/woocommerce/woocommerce-admin/blob/1f261998e7287b77bc13c3d4ee2e84b717da7957/src/PageController.php#L411) to use the [`Loader::get_analytics_capability()`](https://github.com/woocommerce/woocommerce-admin/blob/4864e62a7b561fc3cc65006d9f6ebbf0ffa3b9c4/src/Loader.php#L131) method
* Add a `woocommerce_navigation_register_page_options ` filter

**Comment by rrennick** [comment]
Closing due to lack of feedback.
