### ISSUE TITLE
SelectControl: Bugs/regressions

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3424]
**Describe the bug**

I noticed a bugs and a regression while using the SelectControl component.

* Debounce no longer working and request sent on focus.
* Tabbing to the next element does not always close the dropdown.
* `esc` causes an error.

**To Reproduce**

Go to a report with the comparison box: `/wp-admin/admin.php?page=wc-admin&filter=compare-products&path=%2Fanalytics%2Fproducts`

1. Open the network tab and see a request fired on focus. The results don't populate the dropdown. Maybe that is the intention? A request is fired immediately after each keystroke instead of being debounced. Also, the previous implementation kept the results in component state, which was convenient for coming back with the same query.

2. After entering a query string, tab to the next element on the page. Notice this functioning properly. Try again, but this time with one result already selected. The dropdown should disappear.

![Screen Shot 2019-12-16 at 1 04 06 PM](https://user-images.githubusercontent.com/1922453/70871518-a0536780-2004-11ea-9ee3-9c0f646e48f4.png)

3. Place focus on the input box and enter a search string. Once results populate the dropdown, press `esc` and see an error in the console.

![Screen Shot 2019-12-16 at 1 06 05 PM](https://user-images.githubusercontent.com/1922453/70871534-db559b00-2004-11ea-84c9-3977bcc84b44.png)

**Comment by jeffstieler** [comment]
Started this, but not complete: https://github.com/woocommerce/woocommerce-admin/tree/fix/3424-selectcontrol-regressions
