### ISSUE TITLE
Categories report, sorting by category causes an SQL error

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce-admin#3426]
**Describe the bug**
<img width="455" alt="grafik" src="https://user-images.githubusercontent.com/25877146/70902691-a5f97f00-1ffd-11ea-9d6d-b19e030ea46e.png">

**To Reproduce**

1. Go to Analytics > Categories
2. Click on Category header to sort data

**Desktop (please complete the following information):**

* OS: OSX
* Browser Firefox 
* Version 71

**Comment by thomas-zg** [comment]
[16-Dec-2019 11:18:33 UTC] WordPress database error Unknown column 'xyz_wc_category_lookup.category_tree_id' in 'on clause' for query 
			SELECT
				xyz_wc_category_lookup.category_tree_id as category_id, SUM(product_qty) as items_sold, SUM(product_net_revenue) AS net_revenue, COUNT(DISTINCT xyz_wc_order_product_lookup.order_id) as orders_count, COUNT(DISTINCT xyz_wc_order_product_lookup.product_id) as products_count
			FROM
				xyz_wc_order_product_lookup
				JOIN xyz_terms AS _terms ON xyz_wc_category_lookup.category_tree_id = _terms.term_id JOIN xyz_wc_order_stats ON xyz_wc_order_product_lookup.order_id = xyz_wc_order_stats.order_id LEFT JOIN xyz_term_relationships ON xyz_wc_order_product_lookup.product_id = xyz_term_relationships.object_id LEFT JOIN xyz_wc_category_lookup ON xyz_term_relationships.term_taxonomy_id = xyz_wc_category_lookup.category_id
			WHERE
				1=1
				AND ( xyz_wc_order_stats.status NOT IN ( 'wc-trash','wc-pending','wc-failed','wc-cancelled' ) ) AND xyz_wc_category_lookup.category_tree_id IS NOT NULL AND xyz_wc_order_product_lookup.date_created <= '2018-12-31 23:59:59' AND xyz_wc_order_product_lookup.date_created >= '2018-01-01 00:00:00'
		
				GROUP BY
					xyz_wc_category_lookup.category_tree_id
			
				ORDER BY
					_terms.name desc
			 made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, Automattic\WooCommerce\Admin\API\Reports\Categories\Controller->get_items, Automattic\WooCommerce\Admin\API\Reports\Categories\Query->get_data, WC_Data_Store->__call, Automattic\WooCommerce\Admin\API\Reports\Categories\DataStore->get_data

**Comment by jeffstieler** [comment]
Thanks for the report @thomas-zg !
