### ISSUE TITLE
Onboarding - store profiler: country/state field not being automatically updated when info already exists in the settings

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3447]
When a store already exists it seems that the country/state field isn't being automatically grabbed form WooCommerce > Settings:

![Screen Shot 2019-12-18 at 18 04 48](https://user-images.githubusercontent.com/3380168/71169114-1b5c8e00-2250-11ea-9dba-43255e166830.png)

More info in the P2: pb22l9-5T-p2

This is a low-priority bug

**Comment by joshuatf** [comment]
@pmcpinto Are you able to reproduce this bug?  I've tried a number of country/state options, but no luck yet.

**Comment by pmcpinto** [comment]
I tried a couple of times and I also wasn't able to reproduce it. 

This is just a small detail, so I think we should leave it in a backlog during a couple of weeks, and we then close it if no one has a similar complaint after the 3.9 release. Sounds good?

**Comment by joshuatf** [comment]
Sounds like a good plan @pmcpinto!
