### ISSUE TITLE
Onboarding - store profiler: missing error message when trying to move forward in the product type selection step, without any product selected.

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3448]
Trying to click the Continue button on the Product types tab (without selecting a product type) does not result in an error message:

![Screen Shot 2019-12-18 at 18 18 19 (1)](https://user-images.githubusercontent.com/3380168/71169692-69be5c80-2251-11ea-8384-cbd42cc8de03.png)

This is a low-priority bug

**Comment by joshuatf** [comment]
As of https://github.com/woocommerce/woocommerce-admin/pull/3492 this button disabled state will show up correctly and not be clickable or appear clickable on hover.

When selecting/deselecting options, the error will show.

I think that's enough to resolve this issue, but let me know if you disagree @pmcpinto

**Comment by joshuatf** [comment]
<img width="521" alt="Screen Shot 2019-12-31 at 5 15 06 PM" src="https://user-images.githubusercontent.com/10561050/71616492-721f7b80-2bf1-11ea-8cd9-a9e57a6053de.png">

Quick screenshot for reference.

**Comment by pmcpinto** [comment]
> I think that's enough to resolve this issue, but let me know if you disagree @pmcpinto

Looks good!

**Comment by joshuatf** [comment]
Ok, going to close this issue for now then since now exists in master.
