### ISSUE TITLE
Onboarding - store profiler: allowing the user to skip the Theme selection step

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3450]
During the WC 3.9 testing, it was suggested to allow a user to skip the theme selection step, considering that the user might be using already a theme optimized for WC and doesn't want to switch to a new one (pb22l9-5T-p2)

I noticed that in this step we display the currently active theme, but I'm not sure if we only display it when the user has a Storefront theme or a WP theme like Twenty-Twenty. @justinshreve @joshuatf , can you confirm if we display there any theme that the user has active or just in some specific cases as I mentioned?

**Comment by justinshreve** [comment]
> I noticed that in this step we display the currently active theme, but I'm not sure if we only display it when the user has a Storefront theme or a WP theme like Twenty-Twenty. @justinshreve @joshuatf , can you confirm if we display there any theme that the user has active or just in some specific cases as I mentioned?

We always display the currently active theme as the first item, no matter what theme it is. I confirmed this by installing a random .org theme.

I think the best way to handle this (which we could do now) is to just switch out the 'choose' button on the active theme to say something like "I'll stick with my current theme".

<img width="872" alt="Screen Shot 2019-12-19 at 11 25 28 AM" src="https://user-images.githubusercontent.com/689165/71190312-5eb7fc00-2252-11ea-90e9-c8a57cbfa1fb.png">

**Comment by jameskoster** [comment]
I think this screen is suffering from having multiple primary actions displayed. I tweaked the design a bit to streamline things:

![theme](https://cldup.com/gcytNp7_AS-3000x3000.png)

**Comment by pmcpinto** [comment]
@jameskoster Thanks for tweaking the design. Now it looks more clear, but I prefer the option that you showed with the "Live demo" button below, mainly because some theme names can be long and it will break a bit the layout. Makes sense?

**Comment by jameskoster** [comment]
That's a fair point, I reverted the screenshot :D

**Comment by pmcpinto** [comment]
Thanks :)

**Comment by joshuatf** [comment]
@jameskoster The design above looks a bit different from the current.  

Is this tweaking the design and the button text?  If so, is this ready to go and do you have an updated link to the Figma designs (i15?)?

**Comment by jameskoster** [comment]
@joshuatf you can ignore most of the tweaked visuals for now, and concentrate on:

* Centrally align content inside the theme card
* Active theme should be the only one with primary button
* Primary button label updated to "Continue with my active theme"
* "Choose _theme name_" is now a secondary button
* Live demo is now a tertiary button
