### ISSUE TITLE
Woocommerce Analytics Reports does not email

### ISSUE THREAD

**Issue by jeriy** [woocommerce/woocommerce-admin#3452]
I would like to download an Analytics report for PRODUCTS.  I set it to YEAR to DATE, by month.  I click DOWNLOAD, I get a message that it will email.  I never get an email.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by joshuatf** [comment]
Hi @jeriy 👋  - thanks for reporting this issue.  Could you provide a few more details so we can recreate the issue?

Can you confirm that your WP install is capable of sending emails?  This is a plugin that can help you quickly identify that - https://wordpress.org/plugins/wp-test-email/

Does your store have a lot of products for the dates mentioned?  This process runs in the background to avoid affecting performance on your site and may take a short while to send an email depending on how many products are in that date range.

Any other details you have about your site may help so we can identify the problem.

**Comment by rrennick** [comment]
Closing due to lack of feedback.
