### ISSUE TITLE
Onboarding: Install free themes from dotorg

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3455]
When the last step of the profiler is reached, the user has the option to select a theme.  When selecting a free theme (currently limited to StoreFront), the theme is added to the cart and installed via wccom.

However, if a free theme is chosen, we should not display it in the cart and install from WordPress.org.

#### Steps
1. Visit `wp-admin/admin.php?page=wc-admin&step=theme`
2. Select a free theme.
3. Note the free theme is in the cart items list and only installed if going through the checkout process.

#### Screenshots
<img width="638" alt="Screen Shot 2019-12-20 at 11 31 19 AM" src="https://user-images.githubusercontent.com/10561050/71228150-5c21d900-231c-11ea-8a84-8778f084febf.png">
<img width="1021" alt="Screen Shot 2019-12-20 at 11 31 09 AM" src="https://user-images.githubusercontent.com/10561050/71228151-5c21d900-231c-11ea-8bd2-01434cabbc2e.png">

**Comment by joshuatf** [comment]
Note that this is a follow-up to https://github.com/woocommerce/woocommerce-admin/pull/3444 and should branch from there or wait until it's merged to master.

**Comment by justinshreve** [comment]
> When selecting a free theme (currently limited to StoreFront)

https://woocommerce.com/products/deli/ and https://woocommerce.com/products/boutique/ are both free as well. They are both luckily present in the .org repository too.

https://wordpress.org/themes/deli/
https://wordpress.org/themes/boutique/

**Comment by joshuatf** [comment]
Thanks for noting those, @justinshreve!  Forgot they were in there.
