### ISSUE TITLE
Onboarding - tax step - add an option to not charge sales tax

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#3456]
As title. On the tax step, where we prompt folks to configure their rates, there should be an option to declare that the store doesn't charge sales tax:

![tax](https://cldup.com/efSgEKVoXB-3000x3000.png)

This is fairly important because small stores in parts of Europe aren't required to charge sales tax.

cc @pmcpinto

**Comment by joshuatf** [comment]
@jameskoster If Jetpack is connected and the store is in a TaxJar supported country, the user will get this screen:

<img width="734" alt="Screen Shot 2020-04-20 at 2 29 15 PM" src="https://user-images.githubusercontent.com/10561050/79746866-5d3b3500-8313-11ea-96ae-1c0ebd15f30d.png">

Should this button be added there as well?

**Comment by joshuatf** [comment]
Unassigning this issue until https://github.com/woocommerce/woocommerce-admin/pull/4149 is complete since there is too much overlap.

Dev note: we may need to add a new option, e.g. `woocommerce_task_list_tax_complete` since we'll need a new way to test for task completion aside from `woocommerce_calc_taxes`.

**Comment by jameskoster** [comment]
> Should this button be added there as well?

Yes I think that makes sense!

**Comment by joshuatf** [comment]
I think this is a 1 for someone familiar with the task list.  Maybe 2 if not familiar since a new option will need to be added and this task completion logic will need to be updated.

Estimate: 1

**Comment by psealock** [comment]
Estimate 2: There's a few moving parts here, but Josh is probably right if this is taken by someone who's already familiar with this bit of code.

**Comment by samueljseay** [comment]
@jameskoster Is it possible to get a design provided for the case that @joshuatf presented? I think if we just implement it right now it would be another line of link text under "no thanks I'll configure tax manually". It feels like that could look quite cluttered?

**Comment by jameskoster** [comment]
@samueljseay I think if the buttons are stacked it should be fine:

[Yes please]
No thanks, I'll configure taxes manually
My business doesn't charge sales tax
