### ISSUE TITLE
Onboarding - store profiler - checkout: redirect the user to the Task List after completing checkout

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3463]
Until the work on wc.com side it's finished to improve the checkout experience within the onboarding we should consider implementing a workaround to redirect the user to the Task List after completing the checkout.

**Comment by joshuatf** [comment]
I think we might just consider grabbing all redirects to the plugins page from wccom and send them to the onboarding dashboard if:

* The new onboarding experience is enabled.
* The task list is still enabled.

**Comment by pmcpinto** [comment]
👍I agree that it makes sense to check that first before redirect them to the dashboard
