### ISSUE TITLE
Onboarding - store profiler - purchasing extensions experience: allowing the user to go back and change the products that he wants to buy

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3464]
Currently we don't have any flow that allows the user to go back to the product types step and change his selection after he finishes the store profiler.

We should consider allowing him to do that

**Comment by psealock** [comment]
@pmcpinto Is this still a priority?

**Comment by timmyc** [comment]
Going to close this out.
