### ISSUE TITLE
FEEs - line items for paypal/credit card fees, shipping fees, etc

### ISSUE THREAD

**Issue by splaquet** [woocommerce/woocommerce-admin#3474]
**Is your feature request related to a problem? Please describe.**
Our accountant pointed out that we're not accounting for the fees that are associated with all/each of the orders.  Part of our storefront setup is that we payout based on total NET revenue.  She pointed out how much we were actually losing by not factoring in the various fees that we incur (Shipping Fees, PP/CC fees) into our bottom line.  

**Describe the solution you'd like**
Having the ability to display the (previously mentioned) additional columns into the Revenue page would provide much more accurate dataset of *actual* data.

**Describe alternatives you've considered**
I was thinking about how nice it'd be to have the ability to drag/drop/create our own reporting page.  We're currently using a combination of multiple page exports to produce the data that we need.

**Should this be prioritized? Why?**
YES!  Because for anyone who pays out a third party, based on GROSS or NET revenue, the data is simply not accurate.  Someone is biting the additional fees in the end.  When even 1% matters, that can end up contributing to thousands of dollars in lost revenue.

**Comment by rrennick** [comment]
@splaquet Thanks for the feedback. You could implement a fees column using the extensibility in WC Admin. We have a few examples in https://github.com/woocommerce/woocommerce-admin/tree/master/docs/examples/extensions. For adding a Fees column, the `sql-modification` example would probably be the best starting point.
