### ISSUE TITLE
Onboarding - Task List - Purchase and install task: add event tracking

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3487]
Event tracking related to the "purchase and install" task (#3442):

**Task**
Event name: wcadmin_tasklist_purchase_extension
Event description: when the user clicks to purchase and install extensions
Event properties: none

**Modal**
Event name: wc_admin_tasklist_modal_proceed_checkout
Event description: when the user clicks to proceed to checkout or delay the purchase after seeing the extensions they want to buy
Event properties: extension, theme, purchase_install (true for "purchase & install", false for "I'll do it later")

**Comment by pmcpinto** [comment]
@joshuatf here's the event tracking related to #3442 

Let me know if you have any questions. Thanks.

**Comment by joshuatf** [comment]
@pmcpinto If a user clicks outside the modal, which closes the modal, do we want to trigger the `wc_admin_tasklist_modal_proceed_checkout` event or ignore it?

**Comment by pmcpinto** [comment]
> @pmcpinto If a user clicks outside the modal, which closes the modal, do we want to trigger the wc_admin_tasklist_modal_proceed_checkout event or ignore it?

I think that we should trigger the event with the `purchase_install` property as false. 

Clicking on "I'll do it later" button or outside the modal to close it ends up representing the same behavior on the user side, so it's better to track it
