### ISSUE TITLE
Usage tracking message: WC 3.9-rc2 with wc-admin 0.23.3 still displays the older message

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3523]
I was testing the new onboarding with 3.9-rc2 + wc-admin 0.23.3 and I noticed that it still displays the older usage tracking message:

https://www.loom.com/share/0e777eb888b14ec39e6d7aea6c9337d9

Accordingly to this PR the message was updated on v0.23.2: #3398

**Comment by joshuatf** [comment]
@pmcpinto I tested on a new JN site with WC 3.9-rc2 (downloaded [here](https://github.com/woocommerce/woocommerce/releases/tag/3.9.0-rc.2)) and was able to get the new message.

<img width="670" alt="Screen Shot 2020-01-08 at 3 03 54 PM" src="https://user-images.githubusercontent.com/10561050/71957250-39525880-3228-11ea-89d1-1b023f202958.png">

I let WC install wc-admin and it installed v0.24.0 which may account for the differences.

**Comment by pmcpinto** [comment]
I just tested again using v0.24.0 with WC 3.9-rc2 and I got the new message. I'm going to close this issue.
