### ISSUE TITLE
Note button and link styles differ

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3536]
**Describe the bug**
Styling for buttons and links is different inside notes.  A button is created if a button has an action, but no link.

**To Reproduce**

1. Create or change an existing note to have 2 actions: a link and a button.
2. View the note and styling differences.

**Expected behavior**
Expected these buttons to look similar.

**Screenshots**
<img width="485" alt="Screen Shot 2020-01-08 at 10 48 55 AM" src="https://user-images.githubusercontent.com/10561050/71951093-c4c1ee80-3214-11ea-9538-7a557773cbd3.png">

**Comment by psealock** [comment]
Fixed in wp components update.
