### ISSUE TITLE
Dysplaying price with html tags

### ISSUE THREAD

**Issue by undefence** [woocommerce/woocommerce-admin#3549]
If i put thousands delimeter in WC Settings with tag - In y case '<span class="space"> </span>'

i got uhly prices, needs to render that tags

![Screenshot_1](https://user-images.githubusercontent.com/10356491/72157863-b7eef780-33da-11ea-8a7a-093007db060d.jpg)
![Screenshot_15](https://user-images.githubusercontent.com/10356491/72157864-b8878e00-33da-11ea-9ddb-261a8a59b620.jpg)

**Comment by rrennick** [comment]
Addressed on #3349
