### ISSUE TITLE
Code fragment showing in DevDocs

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3553]
**Describe the bug**
It looks like there is some stray config data being shown in the `<Form>` control in Devdocs.

**Screenshots**
<img width="1029" alt="Screen Shot 2020-01-13 at 2 27 42 PM" src="https://user-images.githubusercontent.com/343847/72281502-17cee380-3611-11ea-968d-0d842d3c8e99.png">

**Comment by joshuatf** [comment]
@rrennick this data is actually intentionally shown to demonstrate the type of data returned from the component. 

Do you think it should be styled differently to distinguish itself from other content?

**Comment by rrennick** [comment]
> Do you think it should be styled differently to distinguish itself from other content?

Maybe a `sample return data` or similar label above it would do the trick.
