### ISSUE TITLE
Use new customer for action scheduler related tests

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3554]
As a followup to #3521, we should update the unit tests involving action scheduler counts to use a unique customer for that test. This will ensure that other tests do not affect the action count.

See https://github.com/woocommerce/woocommerce-admin/pull/3521/commits/516eaed0afc31247d87cc26fe0eece3c13d3940c

**Comment by joshuatf** [comment]
Just skimming through some of the tests, it seems that most tests create a new customer if they need to use that data.

@rrennick Do you recall if any stood out to you as needing new customer entities?

**Comment by rrennick** [comment]
> Do you recall if any stood out to you as needing new customer entities?

@joshuatf I think this issue I found in some cases was that the new customer in the test (email address, etc.) matched the customer info in a previously run test. At the time, when that happened, the import customer action wasn't being scheduled. Depending on what changes have been made to the single import, it might no longer be an issue.

**Comment by joshuatf** [comment]
Ah, gotcha.  Thanks for the info, @rrennick!

cc @louwie17 I think this is similar to the tear down issues we discussed recently in https://github.com/woocommerce/woocommerce-admin/pull/6178.  It would be great if we had some kind of reset between all tests, but maybe that's overkill and this is as simple as being more aware of side effects from one test to another.
