### ISSUE TITLE
Onboarding: Tax step can't be completed without Jetpack connection

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3567]
**Describe the bug**
If Jetpack and WCS are already installed, the "Install" step shown in the design below is not shown.  This leaves only the "Connect" step currently which only provides one option ("Connect") leaving this task incomplete if the user does not connect.

We should do one of the following:
1. Add back in the "Enable automated tax calculations" step (removed since this step has duplicated efforts between the "Good news" screen).
1. Add a button to the "Connect" step to opt out and instead manually configure.
1. Still show the "Install" step even if both plugins are installed, but Jetpack is not connected (feels weird given the next step is "Connect).

I'm leaning towards option 2 above, but open to opinions.  /cc @jameskoster @pmcpinto 

**To Reproduce**

1. Install and activate Jetpack and WCS.
1. Disconnect Jetpack.
1. Visit the tax task.
1. Note the inability to complete the task without connecting Jetpack.

**Expected behavior**
Expected to be able to complete all tasks without connecting Jetpack.

**Screenshots**

#### Original design
<img width="737" alt="Screen Shot 2020-01-15 at 5 23 49 PM" src="https://user-images.githubusercontent.com/10561050/72421892-50f78700-37bc-11ea-9dff-7f1f60f684c5.png">

#### Current when WCS and Jetpack installed but not connected
<img width="722" alt="Screen Shot 2020-01-15 at 4 54 48 PM" src="https://user-images.githubusercontent.com/10561050/72422330-3376ed00-37bd-11ea-9805-b736a50411f4.png">

**Comment by jameskoster** [comment]
Option 2 sounds sensible to me.

**Comment by pmcpinto** [comment]
Hey @joshuatf, the 2nd option seems to be the most appropriate. So just to confirm: with this option we'll display a "Set up taxes manually" button and if the user clicks on it we'll redirect him to the Settings, as we do when they don't want to install JP and WCS, correct?

**Comment by joshuatf** [comment]
That's correct, @pmcpinto- thank you both for your feedback 😄
