### ISSUE TITLE
Import just stopped a day. Now I cant get it to work

### ISSUE THREAD

**Issue by ciszere** [woocommerce/woocommerce-admin#3592]
Hello,

So the admin plugin was awesome when it worked. But suddenly one day it stopped working. I have looked through github too see if i could find a solution. I have tried.

1. Delete and install the plugin again
2. Make a staging site and delete ALL other plugins except woocommerce.
3. Upgrade alla other plugins to latest version. Also my theme (flatsome) and wordpress to latest version, per today.
5. Deleted all posts in the woocommerce - status - scheduled actions.  

Nothing of all these actions will make the plugin work. Can someone please help?

**Comment by joshuatf** [comment]
Hi @ciszere 

Thanks for taking the time to outline some of the steps you've taken.

Can you help me understand the issue a little bitter? 
* Were you running an import and the progress stopped updating?
* Are new orders not being imported?
* What version of WooCommerce Admin and WooCommerce are you running?

**Comment by ciszere** [comment]
Hello Joshua,
Thanks for you help.

1 and 2. When I first started the plugin i imported ALL old orders and they
successfully was added. Then suddenly one day the new orders stopped to
import. I have now tried to delete the plugin and install it again and now
I can not import old orders or new orders. No orders will apparel.
3. Woocommerce - Version 3.8.1
Admin - Version 0.24.0


Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den tis 21 jan. 2020 kl 06:28 skrev Joshua T Flowers <
notifications@github.com>:

**Comment by joshuatf** [comment]
This could be a plugin conflict or something blocking the import from completing.  I'm happy to help you troubleshoot if you'd like.

1. Have you enabled debugging by adding the following to your `wp-config.php`?
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
```
Does the error log show any details after importing?
2. Have you tried disabling all plugins besides WooCommerce and WooCommerce Admin to see if imports begin working?
3. If you update an order by changing the time or status of an order and go to Tools->Scheduled Actions->Pending, do you see this scheduled action? `wc-admin_import_orders`

**Comment by ciszere** [comment]
Hello again,

1. Im not an programer so I dont know what to do with that code :)
2. Yes i have disable ALL plugins except Woocommerce and Wocommerce Admin
and they still dont work
3. Yes i say an other user that had the same issue so yes. As soon as i
update an order there will be an scheduled action. I have tried to delete
all but it doesent help.

Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den tors 23 jan. 2020 kl 09:15 skrev Joshua T Flowers <
notifications@github.com>:

**Comment by joshuatf** [comment]
Hey @ciszere 

>Im not an programer so I dont know what to do with that code :)

Ok, no problem.  I can try and help you out without errors enabled; it just may take a bit longer to find the issue.

>As soon as i
update an order there will be an scheduled action.

So you do so those actions in there as `pending`, but they never run, is that right?  A few more things we can check to limit down what's happening:

* When you check scheduled actions, are there a large number of pending actions?
* Can you check `wp-admin/admin.php?page=wc-status&tab=status` to see if `Wordpress cron` is enabled on your site?
* Could you try activating Action Scheduler 3.0 on your site to see if this helps?  You can download the latest release here - https://github.com/woocommerce/action-scheduler/archive/3.0.1.zip

/cc @rrennick for your thoughts on this.

**Comment by rrennick** [comment]
If a number of plugins were updated then it's possible that one of the updates is causing a cron job to fail and leave that job at the beginning of the cron queue which effectively disables cron. That would cause AS actions to remain in the pending list.

**Comment by ciszere** [comment]
Hello Ron,

I have tried the action Schueder 3.0 but it still does not work. Maybe it's
just easier if you get my login credentials and look for your self? :)

Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den tis 28 jan. 2020 kl 16:03 skrev Ron Rennick <notifications@github.com>:

**Comment by rrennick** [comment]
> Maybe it's just easier if you get my login credentials and look for your self? :)

Github is for reporting bugs vs support. You can manually run actions in the Tools -> Scheduled actions screen. There is an action link that's visible when you hover over the action.

If you are a WooCommerce.com customer you could contact support at https://woocommerce.com/contact-us/.
