### ISSUE TITLE
On Attribute term page back to Attribute links is hidden under WC Admin top bar

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-admin#3599]
**Describe the bug**
I have setup a new attribute and went over to page edit tags of attribute (taxonomy). If I edit an attribute term and save afterwards, there is on top a link back to list of attribute terms. This is overlayed by WC Admin and there be hidden to user.

**Comment by rrennick** [comment]
@ajgw Thanks for the report. Which version of WC Admin are you using?

**Comment by ajgw** [comment]
@rrennick Latest version 0.24.0, WC 3.8.1

**Comment by becdetat** [comment]
Hi @ajgw. I'm having trouble reproducing this. Can you share a screenshot?

**Comment by ajgw** [comment]
Hi @becdetat bug was fixed in 0.25 I think.

**Comment by becdetat** [comment]
Thanks @ajgw, I'll close this ticket then. Thanks for the report.
