### ISSUE TITLE
[WC 3.9 rc4] Onboarding: Can't select newly uploaded theme during Onboarding

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3601]
**Describe the bug**

Can't select newly uploaded theme during Onboarding. 

**To Reproduce**

1. Go through the new onboarding experience (snippet to activate it is [here](https://gist.github.com/justinshreve/6e945dcb4714134156aba1b3c7f086cf) if needed)
2. On the Themes section, upload one of these 3 WooCommerce themes:

https://wordpress.org/themes/acoustics/
https://wordpress.org/themes/newstore/
https://wordpress.org/themes/mismo/

3. Note the message letting you know that the theme was uploaded successfully;
4. Select the newly uploaded theme for your site by clicking the `Choose` button - message saying that the theme is `invalid` will come up. I've tried it with each of the 3 themes above:

Acoustics theme:

![th1](https://user-images.githubusercontent.com/19143190/72814519-129b1580-3c5d-11ea-92d7-769d7ce228e7.jpg)

Newstore theme:

![th2](https://user-images.githubusercontent.com/19143190/72814529-1890f680-3c5d-11ea-890b-2a1ccffa5456.jpg)

Mismo theme:

![th3](https://user-images.githubusercontent.com/19143190/72814545-1e86d780-3c5d-11ea-9438-1406e0e5e83a.jpg)

5. Next, select any other theme from those themes available before you uploaded these new themes and complete the onboarding. 
6. Navigate to `Appearance -> Themes` and try to activate each of these new 3 themes that couldn't be activated during onboarding. You will see that they get activated without any issues:

Acoustics theme:

![a1](https://user-images.githubusercontent.com/19143190/72814838-a79e0e80-3c5d-11ea-9634-52b1d7a57943.jpg)

Newstore theme:

![a2](https://user-images.githubusercontent.com/19143190/72814852-aec51c80-3c5d-11ea-8504-bda44d337e6b.jpg)

Mismo theme:

![a3](https://user-images.githubusercontent.com/19143190/72814875-b5539400-3c5d-11ea-86eb-1f4e533729c4.jpg)

**Expected behavior**

I expected to be able to activate any of these 3 WooCommerce themes during onboarding. 

**Screenshots**

See the screenshots above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 rc4
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com, WooCommerce Beta Tester, WooCommerce Stripe Gateway

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.1
* Browser: Chrome
* Version:  79.0.3945.117 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by psealock** [comment]
I'm getting a 500 error on my local install when trying to upload the plugin. I have Jetpack 8.1 installed and active:

```
[21-Jan-2020 19:45:49 UTC] PHP Warning:  Declaration of Automattic\WooCommerce\Admin\Overrides\ThemeUpgraderSkin::feedback($string) should be compatible with WP_Upgrader_Skin::feedback($string, ...$args) in /srv/www/tangaroa/public_html/wp-content/plugins/wc-admin/src/Overrides/ThemeUpgraderSkin.php on line 0
[21-Jan-2020 19:45:49 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Automattic\Jetpack\Sync\Modules\get_plugins() in /srv/www/tangaroa/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/modules/class-plugins.php:97
Stack trace:
#0 /srv/www/tangaroa/public_html/wp-includes/class-wp-hook.php(290): Automattic\Jetpack\Sync\Modules\Plugins->populate_plugins(true)
#1 /srv/www/tangaroa/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(true, Array)
#2 /srv/www/tangaroa/public_html/wp-admin/includes/class-wp-upgrader.php(487): apply_filters('upgrader_pre_in...', true, Array)
#3 /srv/www/tangaroa/public_html/wp-admin/includes/class-wp-upgrader.php(789): WP_Upgrader->install_package(Array)
#4 /srv/www/tangaroa/public_html/wp-content/plugins/wc-admin/src/Overrides/ThemeUpgrader.php(47): WP_Upgrader->run(Array)
#5 /srv/www/tangaroa/public_html/wp-content/plugins/wc-admin/src/API/Themes.php(89): Automattic\WooCommerce\Admin\Overrides\ThemeUpgrader->install('/srv/www/tangar...')
#6 /srv/www/tangaroa/public_html/ in /srv/www/tangaroa/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/modules/class-plugins.php on line 97
```
I'm not sure if this is related though.

**Comment by timmyc** [comment]
p90Yrv-1uH-p2
