### ISSUE TITLE
Space is missing to separate two sentences in the setup wizard

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce-admin#3604]
**Describe the bug**
When configuring a new store, in the step to set up taxes, a space is missing to separate the phrases "By clicking 'Configure' you're enabling tax rates and calculations." and "More info here." See the screenshot below.

![Screenshot from 2020-01-21 14-49-53](https://user-images.githubusercontent.com/77215/72829365-6574cd00-3c5d-11ea-93db-28cb6c3b8cec.png)

Those two strings are generated here:

https://github.com/woocommerce/woocommerce-admin/blob/ac0eadcaf8828903e9875305cc00c478e7293e19/client/dashboard/task-list/tasks/tax.js#L271

On a related note, for i18n purposes, I wonder if it would be better to combine the two sentences in a single string? Keep in mind that I'm not familiar with how `__()` works in the JS world, so I might be missing something.

**To Reproduce**

1. Go to /wp-admin/admin.php?page=wc-admin&task=tax
2. In the second step, see the string mentioned above.

**Comment by joshuatf** [comment]
Nice catch on this, @rodrigoprimo and thanks for opening an issue!

>I wonder if it would be better to combine the two sentences in a single string?

This should get parsed as a single string when it heads to translation.  I believe the concatenation used here is purely for readability on the dev side.

**Comment by rodrigoprimo** [comment]
> This should get parsed as a single string when it heads to translation. I believe the concatenation used here is purely for readability on the dev side.

Thanks for the clarification.
