### ISSUE TITLE
[WC 3.9 rc4] Onboarding: vertical aligment for text inside buttons seems off

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce-admin#3605]
**Describe the bug**
For at least two buttons that I tested in the new OBW, the vertical alignment of the text that is displayed inside the button seems off. The area below the text is bigger than the area above it, and I expected them to be the same. See screenshots below:

![Screenshot from 2020-01-21 14-26-26](https://user-images.githubusercontent.com/77215/72835803-27ca7100-3c6a-11ea-8076-79a0d312b40d.png)
![Screenshot from 2020-01-21 14-29-46](https://user-images.githubusercontent.com/77215/72835807-29943480-3c6a-11ea-8d1d-30424dfd234f.png)

**To Reproduce**

1. Go to /wp-admin/admin.php?page=wc-admin.
2. Check the vertical alignment of the text in the "Get started" button.
3. Click "Get started" and check the vertical alignment of the text in the "Continue" button inside a modal called "Build a Better WooCommerce".

**Desktop (please complete the following information):**

* OS: Linux
* Browser: Firefox
* Version: 72.0.1

**Comment by timmyc** [comment]
Looks like we have a duplicate report in #3597 going to close this one out.
