### ISSUE TITLE
[WC 3.9 rc4] Setup taxes: currency symbol overlaps with shipping cost value

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce-admin#3606]
**Describe the bug**
The currency symbol and the shipping cost value are overlapping on the "Set up shipping" step of the Dashboard provided by WooCommerce Admin. See screenshot below:

![Screenshot from 2020-01-21 14-42-21](https://user-images.githubusercontent.com/77215/72838292-c9ec5800-3c6e-11ea-9620-3e67d2537a01.png)

**To Reproduce**

1. Set the store currency in /wp-admin/admin.php?page=wc-settings to any currency that has a currency symbol with two or more characters. I tested with Brazilian reais.  
2. Go to /wp-admin/admin.php?page=wc-admin&task=shipping
3. See that, on the second step ("Set shipping costs"), the currency symbol and the shipping cost value are overlapping.

**Desktop (please complete the following information):**

* OS: Linux
* Browser: Firefox
* Version: 72.0.1

**Comment by joshuatf** [comment]
Thanks for reporting this, @rodrigoprimo!  Will put out a fix for this and refactor to use the `TextControlWithAffixes` component.
