### ISSUE TITLE
Extensibility: WCS Labels Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3609]
Many, many, many 🌕 ago, a demo extension was created to show how wc-admin components could be used to build bespoke reports for WooCommerce Extensions. Much has changed between here and there, and for a cool down project we should revisit that initial effort and create a PR that takes a more current approach to building a WCS Shipping Labels report with `wc-admin`.

Prior Art: https://github.com/timmyc/wcs-example-report

The deliverables from this issue could include:

- A Pull Request on WCS with the logic needed to make the report work
- A post on the developer blog detailing how the report was made to help other extension developers
- Possibly new issues listing pain points encountered when developing on top of wc-admin

**Comment by psealock** [comment]
Can we make use of the starter pack? It has some goodies, including built in webpack config and WP Core standards etc.

**Comment by timmyc** [comment]
> Can we make use of the starter pack? It has some goodies, including built in webpack config and WP Core standards etc.

Nuke and pave! I would hope that we leverage all the tools we now have.

**Comment by timmyc** [comment]
closing this out.
