### ISSUE TITLE
Onboarding: Upload theme: add Tracks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3615]
We should add event tracking in the `upload theme` action, so we have a sense of how many users are uploading a theme.

Event name: wcadmin_storeprofiler_store_theme_upload
Properties: theme slug
Recorded properties: theme-slug

Slack thread: C9K5T0XSP/p1579630410046300-slack-wc-admin

**Comment by joshuatf** [comment]
I misspoke in Slack.  I added this event previously. It currently tracks the theme slug after upload completion.

**Comment by pmcpinto** [comment]
@joshuatf thanks for checking that. I wasn't sure if it was already implemented because it still wasn't triggered on Tracks. I'm assuming that this event wasn't tested yet.
