### ISSUE TITLE
PHP warning `A non-numeric value encountered` on order import

### ISSUE THREAD

**Issue by jom** [woocommerce/woocommerce-admin#3624]
**Describe the bug**
During the _Import Historical Data_ process, PHP warnings are thrown.

**To Reproduce**

1. Create products that don't use shipping.
1. Place orders.
1. Run the _Import Historical Data_ tool for a date range that includes those orders.
1. See `A non-numeric value encountered` for line `36`:

https://github.com/woocommerce/woocommerce-admin/blob/034b7a15a36310921e69736498414dd88cf408db/src/Overrides/OrderTraits.php#L25-L37

**Expected behavior**
No PHP warnings to be logged.

**Desktop (please complete the following information):**

* Version [e.g. 22] 0.24.0

Context: VIP Go on an Automattic site.

**Comment by rrennick** [comment]
@jon Thanks for the report :)

**Comment by anacouto** [comment]
I have a similar error when running the _Import Historical Data_ process:
```
E_WARNING: A non-numeric value encountered
in Automattic\WooCommerce\Admin\Overrides\Order::get_item_shipping_amount called at .../woocommerce/packages/woocommerce-admin/src/API/Reports/Products/DataStore.php (412)
```
Which is traced to the same method mentioned above.

Running with WooCommerce version 4.0.1

**Comment by jeffstieler** [comment]
Sorry for the delay in getting to this issue.

I haven't been able to reproduce this. My interpretation of "Create products that don't use shipping" is to create a virtual product. Is that what you did?

**Comment by jom** [comment]
@jeffstieler I bet this was fixed by https://github.com/woocommerce/woocommerce-admin/commit/6b758aa632debd3950ef47380598719b5d38406c. Feel free to close.
