### ISSUE TITLE
Onboarding - customizing appearance - homepage template: small improvements in the layout

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3626]
1. We should remove the widgets displayed in the sidebar, so the page looks more a shop homepage and the most relevant content is full width. This should be applied on both homepages: single product and multiple products:

- The current layout with the widgets: https://d.pr/i/Fg7AlZ
- Just for reference, the homepage that's currently implemented with Storefront looks cleaner, as it doesn't contain those widgets: https://d.pr/i/SQ77Eb

2. Add margin/padding in the header below the hero area. It seems that's missing some margin padding between the hero area and the header below. This happens on both homepages: single product and multiple products:

https://d.pr/i/tGbEOY
https://d.pr/i/dmhdx0

**Comment by joshuatf** [comment]
>We should remove the widgets displayed in the sidebar

@pmcpinto I think this is going to be very theme dependent and something we don't have much control over.

We could remove all the widgets which may collapse the sidebar (again somewhat dependent on the theme), but this may irritate users who are using those widgets elsewhere.

/cc @rrennick For your thoughts.

>Add margin/padding in the header below the hero area

Can do.

**Comment by rrennick** [comment]
> I think this is going to be very theme dependent

Definitely. In addition to your points, not all themes implement full width content layout.

> but this may irritate users who are using those widgets elsewhere.

I'd recommend against removing the widgets when the user continues with their current theme. If they were switching themes it would probably be okay to remove the widgets.

**Comment by pmcpinto** [comment]
Ok makes sense. Can we then just remove the widgets on Storefront? It's already happening when they install the Storefront homepage template

**Comment by joshuatf** [comment]
I believe we can force the homepage to use the full width template included in Storefront.
