### ISSUE TITLE
Activity Panels: W Notice Panel Causing css issues

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3628]
**Describe the bug**
When wc-admin is active, admin alerts created by Jetpack, and WooCommerce are getting some css-bleed.

**To Reproduce**

1. Create a test site on jurassic.ninja
2. Install WooCommerce Services
3. Connect Jetpack
4. Note the JITM message for WCS, and the nudge to use the onboarding wizard look normal:

<img width="1132" alt="Orders ‹ Tasty Stingless — WordPress 2020-01-24 13-07-17" src="https://user-images.githubusercontent.com/22080/73104722-f17c3400-3eab-11ea-87ff-bc0085cd0085.png">

5. Install wc-admin
6. Expand the W notices menu
7. Note the difference in appearance of the alerts

<img width="1146" alt="Orders ‹ Tasty Stingless — WooCommerce 2020-01-24 13-10-24" src="https://user-images.githubusercontent.com/22080/73104737-fb059c00-3eab-11ea-8c9c-02d262ea6311.png">

Thanks @beaulebens for the report.

**Comment by psealock** [comment]
this is fixed.
