### ISSUE TITLE
Onboarding - theme selection step: WC support label on Twenty Twenty theme

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3630]
Currently in the theme selection step, we display an alert message saying that the Twenty Twenty theme doesn't support WC. That alert message should be removed as the theme is compatible with WC, the 3.8.1 release was mostly focused on compatibility improvements: p6q8Tx-1m3-p2

Is it possible to confirm if this is a problem on our side? Maybe it's an issue on the theme. Thanks

<img width="1440" alt="Captura de ecrã 2020-01-27, às 11 03 56" src="https://user-images.githubusercontent.com/3380168/73171230-2e3c6b00-40f8-11ea-94ac-cf78d3847ccd.png">

**Comment by timmyc** [comment]
> Is it possible to confirm if this is a problem on our side? Maybe it's an issue on the theme

Pretty sure this alert is displayed based upon the theme itself declaring support for WooCommerce. So thinking this issue will just be to install v 3.8.1 or newer of the theme, and confirm that the alert is no longer shown.

**Comment by rrennick** [comment]
> Pretty sure this alert is displayed based upon the theme itself declaring support for WooCommerce.

WC core adds theme support for the WP default themes. Versions of WC older than the original release of the default theme won't support that theme.

**Comment by rrennick** [comment]
If we were going to add the support for older versions of WC we would need to back port the compatibility code in WC - https://github.com/woocommerce/woocommerce/tree/master/includes/theme-support. I'm recommending we close this one.

**Comment by pmcpinto** [comment]
Ok, so this will only show in older WC versions, correct?

**Comment by rrennick** [comment]
@pmcpinto Right, older than 3.8.1.

**Comment by pmcpinto** [comment]
Thanks for confirming that. I'm going to close the issue.

**Comment by rrennick** [comment]
Re-opening. This happens with any of the WP default themes. The onboarding support check code searches the theme for `add_theme_support`. WC core adds the `woocommerce` support for the default themes so the default themes all fail the support check.

**Comment by dechov** [comment]
For reference, the old OBW explicitly checks for WP default theme [here](https://github.com/woocommerce/woocommerce/blob/bc4f246dc0cfa04265edf54270696e9ed7e3f466/includes/admin/class-wc-admin-setup-wizard.php#L78-L93).
