### ISSUE TITLE
Onboarding - industry selection step: add CBD as an industry type

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3631]
We need to add CBD as an option in the Industry step (2nd step of the Profiler) in order to have a sense of how many CBD focused stores are being created. It can be placed before "Other". In terms of copy it should be: CBD and other hemp-derived products

https://d.pr/i/Wf7g4N

We should also display an optional input for when the user selects "Other", so we can have a clear picture of what other industries are missing in our listing.

**Comment by octaedro** [comment]
Hi @pmcpinto, I'm working on this issue and I would like to know what you think about the current behavior
1 - The user presses the `Other` option.
2 - an input appears below the `Other` checkbox
3 - The user inserts a text
4 - The user presses the checkbox `Other` and the input disappears
5 - The user presses the checkbox `Other` again and is able to see the same input again.
6 - Should the input that appears the second time be blank or should it have the text the user previously entered?

Thank you!

**Comment by pmcpinto** [comment]
Hey @octaedro, I think it will be better to display the text that was thas previously entered by the user.

**Comment by jeffstieler** [comment]
This was closed by https://github.com/woocommerce/woocommerce-admin/pull/3730.
