### ISSUE TITLE
Onboarding: business step: add Google Ads extension install

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3633]
We'll need to add an option to install [Google Ads](https://woocommerce.com/products/google-ads/) in the business step, similar to what already happens with FB and MC.

This should be included in the next development cycle, so we can already display this option in the onboarding before Q1 ends.

Title: “Drive sales with Google Shopping”
Description: “Get in front of new customers on Google and secure $150 in ads credit with Kliken’s integration.”
Logo: 
![Google-Ads-for-Woo-Logo-374x192px](https://user-images.githubusercontent.com/3380168/74156144-a8e3ab00-4c0d-11ea-92cc-1d1bb60ce7cf.png)

More context about this here: p6q8Tx-1qf-p2

Eventually, in the near future, we should consider moving those marketing extensions to the task list, but as for now let's keep them in the business step.

**Comment by timmyc** [comment]
I feel like this will be a `1`, but estimating at `2` just in case we encounter any oddness with the plugin install flow.
