### ISSUE TITLE
Onboarding - Business details step: improve event tracking prop

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3634]
We provide 5 options in the `Currently selling elsewhere?` field but it seems that in the event tracking prop `already_selling` we only track true and false. It would be more accurate if we have a specific value in that prop for each option that we display.

**Comment by timmyc** [comment]
Pedro is `false` okay to send if no selection is made on the step? At least that would be congruent with the current data being collected.

**Comment by pmcpinto** [comment]
Hey Timmy, they're required to select a value if they want to proceed to the next step. So it would be better to display the options as values of this prop:
No
Yes, on another platform
Etc

Makes sense?
