### ISSUE TITLE
WB

### ISSUE THREAD

**Issue by AleThompson** [woocommerce/woocommerce-admin#3649]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by rrennick** [comment]
@AleThompson I'm going to close this as you have provided no information. If you do have an issue to report, please create a new one and fill out the issue template.
