### ISSUE TITLE
Onboarding - payments task: filter payment gateways if the user selects CBD

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3657]
With the introduction of CBD as an option in the Industry type (#3631), we'll need to filter the payment gateways that we show, considering the Square is the only one that supports CBD (p2y3YZ-3M0-p2). So if the user has Jetpack and WCS installed, selected US as a country and CBD as industry type we should display Square as the main payment gateway. In this case, we can install the plugin but we also need to redirect the user to Square's attestation page: https://squareup.com/t/f_partnerships/d_referrals/p_woocommerce/c_general/o_none/l_us/dt_alldevice/pr_payments/?route=/solutions/cbd

I'm thinking if we should also add Stripe as the second option, because merchants can change their mind and end up selling non-CBD products, and add a tooltip or something saying that only Square supports CBD. @jameskoster what do you think?

**Comment by timmyc** [comment]
Given our discussion today about moving the Jetpack connection flow, does that have any impact on this task?

**Comment by jameskoster** [comment]
Sorry if I'm missing something, but why does Jetpack / WCS need to be installed for us to suggest Square?

**Comment by pmcpinto** [comment]
Yep, I think it won't have any impact on this task.

**Comment by octaedro** [comment]
Hi @pmcpinto,

Currently, to show the Square option we are checking (`selling_venues`) if `Other places the store is selling products` is `brick-mortar` or `brick-mortar-other`.
Should we continue checking this after confirming the industry is `CBD` or we should show the Square option even if the `brick-mortar` or `brick-mortar-other` wasn't selected in `Other places the store is selling products`?

Also, I would like to confirm if I should add the tooltip saying that only Square supports CBD.

Thank you!

**Comment by pmcpinto** [comment]
Hey @octaedro,

If the user selects CBD as industry and US as country we should show Square independently of what they choose in `selling_venues`.

If the user selects any other industry we need to continue doing that check to display Square.

> In this case, we can install the plugin but we also need to redirect the user to Square's attestation page: https://squareup.com/t/f_partnerships/d_referrals/p_woocommerce/c_general/o_none/l_us/dt_alldevice/pr_payments/?route=/solutions/cbd

Just ta friendly reminder that this redirect should only happen when the user selects CBD as industry and US as country.


> I would like to confirm if I should add the tooltip saying that only Square supports CBD.

yes please.

Lmk if you have more questions. Thanks!

**Comment by octaedro** [comment]
@pmcpinto is a tooltip like this ok?

![screenshot-tooltip.png](https://images.zenhubusercontent.com/5e31b25d0dfff084858547a8/8d3fb896-fe0c-462a-8491-a91d738de23d)

I used the text:
`The industries CBD and other hemp-derived products are only supported by Square.`

Tell me if you prefer to change something.

As you mentioned above it will be visible only for `CBD` and with the country code `US`
Thanks!

**Comment by pmcpinto** [comment]
> I used the text: The industries CBD and other hemp-derived products are only supported by Square.

Hey @octaedro, that will be a long tooltip :). I'd suggest simplifying the copy to: Selling CBD products is only supported by Square.

**Comment by octaedro** [comment]
The tooltip copy sounds good to me!

I was looking at the API and at the end of the `Set up payment` process if the user selects Square they are redirected to the `Square` page, that looks like the attestation page. As I understand it looks like we should continue using this URL.
Is this ok?

Thank you Pedro!

**Comment by pmcpinto** [comment]
@octaedro we should redirect the user to the [attestation page](https://squareup.com/t/f_partnerships/d_referrals/p_woocommerce/c_general/o_none/l_us/dt_alldevice/pr_payments/?route=/solutions/cbd) of they select CBD as industry and US as country. Otherwise, we'll redirect them to the same place that we have right now.

**Comment by octaedro** [comment]
Excellent @pmcpinto! Thank you!
