### ISSUE TITLE
Onboarding - business step: add more options in the competitors list and other fixes

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3658]
- We should add the following additional options when the user selects that he's selling on another platform:
Amazon
eBay
Etsy
Squarespace
They should be displayed before the "Other" option

- If the user selects "Other" we should display an option input field, in order to allow him to name the platform that he's using.

- In the first question of this step, we have significant % of users saying that they plan to sell +1000 products, so I'm assuming that they're thinking in terms of the number of units. We could try to make the question more clear, perhaps: How many products do you plan to display?

@jameskoster any idea?

**Comment by octaedro** [comment]
Hi @pmcpinto,
Does this issue need to go into `WC 4.0`.
Thank you!

**Comment by pmcpinto** [comment]
Hey @octaedro, it can wait until the upcoming wc-admin release that probably will happen at the end of this cycle.

**Comment by octaedro** [comment]
@pmcpinto Perfect! Thank you!
