### ISSUE TITLE
Posts of type "wc_admin_unsnooze_admin_notes" are created every hour.

### ISSUE THREAD

**Issue by extrapixel** [woocommerce/woocommerce-admin#3659]
This fills up the posts table. Why? Plugin unusable because of this.

**Comment by extrapixel** [comment]
plus thousands and thousands of comments by "ActionScheduler".... uninstalled.

**Comment by jeffstieler** [comment]
This will be resolved when https://github.com/woocommerce/woocommerce-admin/pull/3662 is included in a release.
