### ISSUE TITLE
[Performance] Use caching to check if someone has physical products

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce-admin#3663]
**Describe the bug**
Query used to fetch data in https://github.com/woocommerce/woocommerce-admin/blob/master/src/Features/OnboardingTasks.php#L174 is pretty heavy. For egs, in my setup of 10k products, I am getting these results:

```
# Query_time: 0.314502  Lock_time: 0.000193 Rows_sent: 1  Rows_examined: 123735
SET timestamp=1580822949;
SELECT   wc_posts.ID FROM wc_posts  LEFT JOIN wc_term_relationships ON (wc_posts.ID = wc_term_relationships.object_id) INNER JOIN wc_postmeta ON ( wc_posts.ID = wc_postmeta.post_id ) WHERE 1=1  AND (
  wc_term_relationships.term_taxonomy_id IN (2,3,4,5)
) AND (
  ( wc_postmeta.meta_key = '_virtual' AND wc_postmeta.meta_value = 'no' )
) AND wc_posts.post_type = 'product' AND ((wc_posts.post_status = 'publish' OR wc_posts.post_status = 'draft' OR wc_posts.post_status = 'pending' OR wc_posts.post_status = 'private')) GROUP BY wc_posts.ID ORDER BY wc_posts.post_date DESC LIMIT 0, 1;
```

As you can see, 300ms for every page refresh while on WooCommerce related admin screens is quite impactful. This query will be slower depending upon how many products are there.

The performance here is slow because to identify if a product is not virtual, this query creates a JOIN between posts and postmeta table.

Please cache the results of this query.

**To Reproduce**

1. Go to WooCommerce dashboard after activating wc-admin plugin.
2. See you query log.

**Desktop (please complete the following information):**

* OS: [e.g. iOS] MacBook Pro
* Browser [e.g. chrome, safari] Firefox
* Version [e.g. 22] 72.02

**Comment by timmyc** [comment]
Hmm not sure why this didn't auto-close when the PR merged.
