### ISSUE TITLE
Filter Products based on Variation Attributes

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce-admin#3665]
**Is your feature request related to a problem? Please describe.**
We use highly structured variable products in our shop, and reporting on sales by attribute terms requires manually counting up the sales of every product variation matching the attribute term. This is onerous.

Imagine a 'Book' product with 'Paperback' and 'Ebook' variations. If you want to report on ebook sales you cannot use the reporting tool to select all ebooks, rather you have to go to every 'Book' product, count the ebook sales individually, and manually aggregate them.

**Describe the solution you'd like**
I want to be able to filter product reports by product variations matching global attribute terms so we can see the performance of variations tied to a global attribute across the catalog all at once.

**Describe alternatives you've considered**
Manually exporting orders and using a spreadsheet to count the variation sales data over a certain period. If there is a better way to do this, I'd love to hear it!

**Should this be prioritized? Why?**
Yes, because many WooCommerce shops use global attributes for common variations of a product that shouldn't be otherwise duplicated in the product database (Music: Physical vs. Digital, Print: Books vs Ebooks or Audiobooks, Clothing: Garment Size, etc.)

This is important reporting data for any shop that uses the same global attribute to define variations across multiple products in their shop.

**Additional context**
I saw this suggested in issue #1562 but it was closed at the time.

Additionally we add categories to the parent variable product to reflect variations, but since the variations themselves can't be associated with categories they aren't at all useful for filtering or reporting. This is more of a WooCommerce core issue, but thought it worth mentioning.

**Comment by timmyc** [comment]
@melek thanks so much for the feature suggestion. Tagging @pmcpinto for thoughts.

**Comment by gbruzzo** [comment]
Hello there, 

We completely support your request - our store is a music store;  products are variations (Vinyl / CD / Download etc), so filtering by variation is absolutely **essential** 

Thank you in advance 

Giacomo Bruzzo

**Comment by benjaminprojas** [comment]
I would also love to see this feature added.

**Comment by gbruzzo** [comment]
This is absolutely crucial - here is a simple example for store managers: 
Go to Orders, select the ones that are processing via a filter, download the CSV. 
=> the CSV will only show the parent product instead of the variation. Say an order contains 5 
Variations of the same parent, the CSV will only show 
'1 x parent, 1 x parent, 1 x parent, 1 x parent, 1 x parent'

This is very disappointing and renders the analytics plugin near useless for store managers whose store uses variations.
 
This is an **essential** development, the ability to drill orders down by variation is really **core** functionality 

Any comments from the developers?

**Comment by rrennick** [comment]
> Any comments from the developers?

Thank you for the feature suggestion. Over the next few weeks our team will be focused on the release of [WooCommerce 4.0](https://woocommerce.wordpress.com/2020/02/10/woocommerce-4-0-beta-1/). 

If this feature is particularly important to you, we wrote a [tutorial](https://woocommerce.wordpress.com/2020/02/20/extending-wc-admin-reports/) on extending WC Admin which would be a good starting point for adding columns to reports.

**Comment by gbruzzo** [comment]
Hi there 

thank you for your feedback. Not satisfactory alas.

**Comment by dougaitken** [comment]
I think this is the same as #3195, am I right @timmyc?

**Comment by timmyc** [comment]
@dougaitken indeed the look to be similar.

**Comment by gbruzzo** [comment]
Maybe related, as it is currently impossible to **drill down orders by variations**

Example 1 : 
Go To Analytics/Orders => Select Advanced Filters => add a filter (Product) => notice how individual variations cannot be added to the filter. **We need to be able to add individual variations to the order filter**

Example 2: 
Go To Analytics/Orders => If you decide to filter by a parent product, the resulting list only shows the parent product and not the variation in the Product(s) column. **We need a Variations Column** 

Example 3: 
Go to to Analytics/Products => show a product that has variations => Select 'All Variations' => all the variations of a given product that were sold are shown. => Now click on the number of orders (Orders column): you are sent back to Analytics / Orders with the parent product in the filter and now way to see exactly what variation was in what order. 

This makes these essential reports alas not useful at all to stores whose 'products' are individual variations, and not parent products. 

Example of such stores: 

- Record label, selling CD / VINYL / DOWNLOAD variants of a given release (release is parent product, but products **actually sold** are variations)
- Clothing shops - sales by COLOUR (different colours make for very different products) 
....

So It is not so much a matter of creating a new report, but being able to **filter orders by individual variation.**, e.g. adding a layer of filtering and making sure all reports tie into each other properly.

**Comment by timmyc** [comment]
I believe this is likely covered by the new [Variations Report](https://docs.woocommerce.com/document/woocommerce-analytics/#variations-report), so going to close this out.
