### ISSUE TITLE
Delete button missing from settings if you've never imported anything

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce-admin#3676]
**Describe the bug**
https://github.com/woocommerce/woocommerce-admin/pull/1291#issuecomment-579291373

The delete button is simply missing when you've never used the import button yet.
So you can't delete non-imported data, without importing first, and then deleting (except via REST of course).

**To Reproduce**
Check a fresh install.

PS.
Sorry I don't have time to fill out the rest of the fields. You can close this if that is unacceptable.

**Comment by rrennick** [comment]
> The delete button is simply missing when you've never used the import button yet.
> Check a fresh install.

The import is for importing analytics data into analytics lookup tables vs importing WooCommerce data. A fresh install does not have any analytics data to delete.
