### ISSUE TITLE
Enabling and disabling the new onboarding wizard options results in blank pages. 

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce-admin#3678]
**Describe the bug**

In short, when the new on-boarding experience is enabled here: 

<img width="780" alt="Screen Shot 2020-02-07 at 14 57 03" src="https://user-images.githubusercontent.com/6198774/74031580-93c30e00-49ba-11ea-8d50-beb9052936b6.png">

Then the page refreshes to a blank page. 

You will then need to navigate back to the setup wizard, where you'll see the following: 

<img width="558" alt="Screen Shot 2020-02-07 at 14 58 21" src="https://user-images.githubusercontent.com/6198774/74031628-adfcec00-49ba-11ea-87ed-acded5777064.png">

Enabling the "Profile setup wizard" or "task list" redirects correctly. However, as soon as you disable the "task list" or "Profile setup wizard" the page refreshes to a blank page (again).

**To Reproduce**

1. Go to the setup wizard
2. Click on "Enable" button for the new onboarding experience. 
3. The page will load blank

4. Go back to the setup wizard
5. Enable the "Profile setup wizard" option (works)
6. Now enable the "task list" option (works)

7. Go back to the setup wizard once again
8. Disable the "profile setup wizard" option (blank page)

9 Go back to the setup wizard
10. Disable the "task list" option (blank page)

**Expected behavior**

I would expect the redirect to be better, like to the WC settings page or something other than a blank page. 

**Desktop (please complete the following information):**

I could replicate this on the most recent versions of WooCommerce core, WordPress, and the Storefront theme, using Chrome browser v9.0.3945.130 (Official Build) (64-bit)

Thanks!

**Comment by rrennick** [comment]
@rynaldos Thanks for reporting this. Can you provide us with context with versions, new/existing install, etc.?

**Comment by rynaldos** [comment]
Howdy @rrennick :) 

Absolutely. 

This is a clean install WP v5.3.2, WC v3.9.1, WC Admin v0.24.0, and Storefront theme v2.5.3 on local MAMP setup (if that makes a difference).

Please shout if anything else is needed.

**Comment by rynaldos** [comment]
Sorry. Original report here: 2676070-zen

**Comment by rrennick** [comment]
> WC Admin v0.24.0

Can you see about updating WC Admin to the latest version?

**Comment by rynaldos** [comment]
> > WC Admin v0.24.0
> 
> Can you see about updating WC Admin to the latest version?

Yes, will have a quick look and see if the issue persists. The new version wasn't available when the issue surfaced :)

**Comment by rynaldos** [comment]
@rrennick 

Wonderful! v0.25.0 works like a charm! Was this a known issue?

**Comment by rrennick** [comment]
@rynaldos Awesome, I'll close the issue. There were a few things we fixed related to ensuring the various methods of starting/re-starting the onboarding worked correctly.
