### ISSUE TITLE
Report table filter shows 'all that include' option even when the input field is empty

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#3682]
**To Reproduce**

1. Go to the _Customers_ report, for example.
2. Click on the _Search by customer name_ input field.
3. Notice an option appears in the dropdown.
4. Clicking it doesn't change anything and the text (_All customers with names that include_) looks a bit weird.

**Expected behavior**
If there isn't any text in the input field, I think the 'all that include' option shouldn't appear.

**Screenshots**
![Peek 2020-02-07 22-56](https://user-images.githubusercontent.com/3616980/74068909-1371cc80-49fd-11ea-813d-818fba08522c.gif)

**Comment by timmyc** [comment]
Looks like this has been fixed up as I can no longer reproduce in `main`
