### ISSUE TITLE
Import Historical Data select text is not correctly aligned

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#3683]
**To Reproduce**
1. Go to _Analytics_ > _Settings_ and scroll down to the _Import Historical Data_ section.
2. Notice the `<select>` text is not correctly aligned. I could verify both with Firefox and Chrome under Linux.

**Expected behavior**
Adding `line-height: 1` seems to fix it.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/74069597-09e96400-49ff-11ea-8390-bd448039c26a.png)

**Comment by edmundcwm** [comment]
I can look into this!

**Comment by rrennick** [comment]
Addressed in #3723
