### ISSUE TITLE
[4.0 beta1]: New OBW: Can't click on little red alert next to the existing theme on the theme selection step

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3689]
**Describe the bug**

Testing 4.0 beta1 pre-public release. New OBW: Can't click on a little red alert next to the existing theme on the theme selection step. 

**To Reproduce**

1. Start new OBW;
2. On the theme selection screen try to click on the red alert next to `Twenty Twenty` - it looks like something is not right with it so there is a need to know what exactly:

![alert](https://user-images.githubusercontent.com/19143190/74146748-b3944500-4bf9-11ea-8b0d-ec0c230d22a2.jpg)

3. When you click on it no message seems to get displayed. Although I noticed that sometimes it does get displayed very quickly for less than a second but I can't get it to show again:

![](http://g.recordit.co/W0E0PrBFHF.gif)

**Expected behavior**

I expected to be able to see a notice when clicking on the red alert icon explaining if there is an issue with the theme. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.0 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.3
* Browser: Chrome
* Version: 80.0.3987.87 (Official Build) (64-bit)

**Additional context**

Beta 4.0 was not released to the public yet - this is found during testing the package we tagged before tagging beta and releasing it to the public.

**Comment by joshuatf** [comment]
@juliaamosova The little red circle with the info icon is used to show which themes don't have WC support.  It should show a tooltip when hovering over it.  Does this not work for you?

* Do you have other plugins installed besides WooCommerce?
* Does this happen when you try a different browser? (I'm wondering if there are any browser extensions that may be interfering)

**Comment by jeffstieler** [comment]
+1 to @joshuatf's questions as I'm not able to reproduce this on a JN site running the [`4.0.0-rc.1`](https://github.com/woocommerce/woocommerce/releases/tag/4.0.0-rc.1) plugin:

![Screen Shot 2020-03-03 at 9 07 08 AM](https://user-images.githubusercontent.com/63922/75794714-6bff6580-5d2e-11ea-82d6-e1a4be947d53.png)

**Comment by juliaamosova** [comment]
@joshuatf @jeffstieler thanks! Good call about browser extensions interfering. Let me test in another browser and I will report back.

**Comment by juliaamosova** [comment]
Noting here that I can't reproduce it in Safari - works as expected there - the notice appears on hover over:

![](http://g.recordit.co/z3p1bF8uW7.gif)

I think this issue can be safely closed. As mentioned above, likely one of my Chrome browser extensions interferes.
