### ISSUE TITLE
[4.0 beta1] New OBW: Can't select Storefront theme (or any other theme?) on the theme selection step

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3690]
**Describe the bug**

Testing 4.0 beta1 pre-public release. New OBW: Can't select Storefront theme (or any other theme?) on the theme selection step. 

**To Reproduce**

1. Start new OBW;
2. On the theme selection screen, try to select Storefront and observe the error: `The response is not a valid JSON response`:

![](http://g.recordit.co/HRqDgmcA2c.gif)

3. Try several times - at some point, I was able to move forward with Storefront but after clicking several times. 

**Expected behavior**

I expected the Storefront theme to be selected without any issues. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.0 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.3
* Browser: Chrome
* Version: 80.0.3987.87 (Official Build) (64-bit)

**Additional context**

Beta 4.0 was not released to the public yet - this is found during testing the package we tagged before tagging beta and releasing it to the public.

**Comment by joshuatf** [comment]
@juliaamosova Thanks for taking the time to create this issue.  This sounds like something on your server is may be throwing an error outside of onboarding.

* Can you check and see the network response when this fails under the "Network" tab in Chrome dev tools?
* What other plugins do you currently have active on this site?
* Do you see any other errors being thrown around your site?  If you have access to the error log on this site, can you check that?

**Comment by jeffstieler** [comment]
+1 to @joshuatf's questions as I'm not able to reproduce this on a JN site running the [`4.0.0-rc.1`](https://github.com/woocommerce/woocommerce/releases/tag/4.0.0-rc.1) plugin.

**Comment by juliaamosova** [comment]
@joshuatf @jeffstieler sorry for the delayed response. This was tested on JN site and I could no longer reproduce this again. Another one that can be safely closed at this point. 

I will look around into error logs in case it happens again and will report back if I will come across it.
