### ISSUE TITLE
[4.0 beta1] New OBW: Can't seem to always move passed the first step in new OBW

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3691]
**Describe the bug**

Testing 4.0 beta1 pre-public release. New OBW: Can't seem to always move passed the first step in new OBW. 

**To Reproduce**

1. I tested on a brand new Jurassic Ninja and I was selected randomly to be a part of new OBW (didn't have to use a snippet to enable it). 
2. Click on `Get started` and observe an error: `There was a problem updating your preferences`

![](http://g.recordit.co/VKf77x3w9R.gif)

3. Note that this doesn't happen if you manually enable new OBW (via snippet) - tried it twice and was successfully able to move forward. 

It is difficult to test again when the new OBW gets enabled randomly since it doesn't happen always. 

**Expected behavior**

I expected to be able to move forward without any issues. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.0 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.3
* Browser: Chrome
* Version: 80.0.3987.87 (Official Build) (64-bit)

**Additional context**

Beta 4.0 was not released to the public yet - this is found during testing the package we tagged before tagging beta and releasing it to the public.

**Comment by joshuatf** [comment]
Thanks for noting this issue, @juliaamosova!

I haven't been able to recreate this on a JN site yet, but let's keep it open to see if it pops again or others chime in.  How often does this happen in your testing?

**Comment by jeffstieler** [comment]
I'm not able to reproduce this on a JN site running the [`4.0.0-rc.1`](https://github.com/woocommerce/woocommerce/releases/tag/4.0.0-rc.1) plugin.

**Comment by juliaamosova** [comment]
@joshuatf @jeffstieler thanks for testing and keeping it open. I was not able to replicate it again ever since on JN or any other site. I think it is safe to close it at this point.
