### ISSUE TITLE
[4.0 beta 1] New OBW: Not able to select any other payment methods other than Stripe & PayPal

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3694]
**Describe the bug**

Testing 4.0 beta1 pre-public release. New OBW: Not able to select any other payment methods other than Stripe & PayPal. Not sure if this is intentional hence reporting. 

**To Reproduce**

1. Start new OBW;
2. On the task list, select to `Set up payments`:

![paymnt1](https://user-images.githubusercontent.com/19143190/74151025-23f39400-4c03-11ea-8a26-313f65e92c2f.jpg)

3. Toggle off both Stripe and PayPal options - there is no way to proceed further without selecting either of them:

![paymnt2](https://user-images.githubusercontent.com/19143190/74151068-3ff73580-4c03-11ea-8eda-61a4f9715e8a.jpg)

**Expected behavior**

I think the best here is to add an option of `COD` and let users proceed with it in case they are not ready / don't want to use Stripe or PayPal. What if they use any other gateway? For example, Authorize.NET. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.0 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.3
* Browser: Chrome
* Version: 80.0.3987.87 (Official Build) (64-bit)

**Additional context**

Beta 4.0 was not released to the public yet - this is found during testing the package we tagged before tagging beta and releasing it to the public.

**Comment by pmcpinto** [comment]
Hey @juliaamosova thanks for your feedback. This option was intentional, but we're considering changing it, in order to allow users to install offline payments (#3461).

@jameskoster, I think this should be considered in your revision of the payments step. Sounds good?

**Comment by juliaamosova** [comment]
> Hey @juliaamosova thanks for your feedback. This option was intentional, but we're considering changing it, in order to allow users to install offline payments (#3461).

Thanks @pmcpinto! Feel free to close my issue in favor of previously submitted. My bad for not checking.

**Comment by jameskoster** [comment]
I covered this in my latest design revisions. We have a chat tomorrow to discuss further. Will share here when we settle on a direction.

**Comment by pmcpinto** [comment]
@juliaamosova, no worries. I'm going to close this one. Thanks again for your feedback
