### ISSUE TITLE
[4.0 beta1] New OBW: Can't use `wp-admin/admin.php?page=wc-setup` to later go back to the OBW

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3695]
**Describe the bug**

Testing 4.0 beta1 pre-public release. New OBW: Can't use `wp-admin/admin.php?page=wc-setup` to later go back to the OBW. Not sure if this is intentional so reporting. 

**To Reproduce**

1. Go through new OBW;
2. After completing it, try to append `wp-admin/admin.php?page=wc-setup` to go back to the beginning of OBW;
3. You don’t get to the beginning of OBW where you can select if you want to proceed with older or new OBW. Instead, you get redirected to `wp-admin/admin.php?page=wc-admin ` and task list: 

![Screen Shot 2020-02-10 at 10 17 10 AM](https://user-images.githubusercontent.com/19143190/74151715-b2b4e080-4c04-11ea-9d3a-6088641d09a8.png)

**Expected behavior**

I expected to be able to go back to the beginning of OBW where I could select if proceed with new or older OBW. Especially in the case like in this issue where I enabled new OBW via snippet as I was not randomly selected for it. 

I also tried to disable the snippet  (on the same existing site) but was still getting the same result as above. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.0 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.3
* Browser: Chrome
* Version: 80.0.3987.87 (Official Build) (64-bit)

**Additional context**

Beta 4.0 was not released to the public yet - this is found during testing the package we tagged before tagging beta and releasing it to the public.

**Comment by rrennick** [comment]
@juliaamosova To go back to the onboarding use WooCommerce -> Status -> Help -> Setup Wizard.

**Comment by juliaamosova** [comment]
Thanks @rrennick! I didn't try `WooCommerce -> Status -> Help -> Setup Wizard` but I see now that it works indeed. 

I thought adding `wp-admin/admin.php?page=wc-setup` was also possible though since it is currently possible with the older onboarding.

**Comment by timmyc** [comment]
thanks for the detailed report @juliaamosova - I _think_ this is working as "designed" right now, which definitely is a bit different from the classic OBW. @pmcpinto any thoughts here? If someone wants to re-use the OBW they have to reluanch it via the help menu as Ron pointed out above... should we allow re-launching it via directly entering the `wp-admin/admin.php?page=wc-setup` URL? 

Outside of testing, I think this is kind of an edge case.

**Comment by joshuatf** [comment]
This does appear to be working as designed since the dashboard and new OBW share the same page/URL currently.

>I think this is kind of an edge case.

I think it probably is as well since most users probably won't be repasting the URL, but I'm open to looking into other places to place the option to toggle the profiler/task list and make them more visible.

**Comment by pmcpinto** [comment]
Thanks for the feedback @juliaamosova

I agree that this looks more as an edge case and I'm assuming that most users won't be using the url to go back to the profiler. 

I think we should keep it in the backlog to evaluate in the future if it makes sense to place the option to return to the store profiler in another place. We have some data showing that a small % of users is doing this in the current obw: pa1C6h-y3-p2

**Comment by Dkwatch12** [comment]
wp-admin/admin.php?page=wc-admin how to slove please help me
