### ISSUE TITLE
Report table filter has an error adding a new term

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#3699]
**To Reproduce**
1. Go to `Analytics > Customers` 
2. Make a search with a valid term, e.g. a registered user's name.
3. Add another term to the search.

I tried to repeat the steps by searching for an unregistered name instead, and the terms were added successfully.

**Expected behavior**
It should add the new term to the search queue but is not happening.

**Screenshots**
![Screen Capture on 2020-02-11 at 11-43-30](https://user-images.githubusercontent.com/1314156/74250136-f3762d80-4cc8-11ea-9b5b-032f57848289.gif)

**Comment by timmyc** [comment]
I can't re-create this issue anymore so I'm going to close this out.
