### ISSUE TITLE
Onboarding - customize appearance: remove redirect to edit the homepage post

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3708]
A significant % of users are dropping in this task after being redirected to edit the homepage post. So as a workaround we should allow them to create a homepage, as it is right now, but keep them in the task instead of redirecting them to the post editor.

We also need to add an event tracking to the new snackbar that displays the link to customize the homepage. It should be triggered when the user clicks to customize: wcadmin_tasklist_appearance_customize_homepage

A detailed explanation of this change is available [here](https://www.figma.com/file/nzAjPR4nqdJTDxH32PT4Qg/On-boarding?node-id=4%3A5728).

**Comment by pmcpinto** [comment]
Hey @joshuatf, just a heads up that we also need to add an event tracking to the [new snackbar](https://www.figma.com/file/nzAjPR4nqdJTDxH32PT4Qg/On-boarding?node-id=4%3A7336) that displays the link to customize the homepage. It should be triggered when the user clicks to customize: wcadmin_tasklist_appearance_customize_homepage

I'm going to add it to the issue description.

**Comment by pmcpinto** [comment]
Hey @joshuatf I'm going to close this issue as it seems that it was already merged. The event tracking is also in place, correct?

**Comment by joshuatf** [comment]
@pmcpinto Ya, that's okay to close this.  The PR went into `vesrion/1.0` so the issue had not auto-closed yet.

The new `wcadmin_tasklist_appearance_customize_homepage` event was included in https://github.com/woocommerce/woocommerce-admin/pull/3727
