### ISSUE TITLE
Onboarding - task list: improve focus on the task list and allow an option to skip it

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3711]
Currently there are a lot of options in the WooCommerce menu that can distract the user and derail him from completing the most important steps to have the store ready. In order to improve the focus on the task list we should:

- Hide all the options in the WC menu and just display the setup option, if the user selects `false` as the value of the event prop `setup_client` in `wcadmin_storeprofiler_store_details_continue`
- If the user has `true` as a value or never triggered that even we'll show the menu as always.
- When the user completes the task list we unlock all the options on the menu.
- We include two links at the bottom of the task list: 
  - One allowing the user to skip the task list, unlocking the menu and hiding the task list.
  - Another one allowing the user to complete the task list later, unlocking the menu and keeping the task list on the menu.

- We need to add tracking to the links, probably one event with an even prop to distinguish them: 
Name: `wcadmin_tasklist_skip`
Event props: completed_tasks: number of tasks completed, completed_tasks_names: name of the tasks that were completed, skip_option: "i'll do this later" or "skip store setup" 

Mockup [here](https://www.figma.com/file/nzAjPR4nqdJTDxH32PT4Qg/On-boarding?node-id=15%3A2338)
[P2](p6riRB-5li-p2)

**Comment by joshuatf** [comment]
>We need to add tracking to this link, with the following name: wcadmin_tasklist_completed (no event props)

@pmcpinto We currently use this same event name when the task list is complete and hidden via the "Is this card useful?"

Are we still keeping that prompt?  And if so, maybe we should pass in a prop of `skipped`?

I also feel like this event name is a tad confusing for both scenarios since users may or may not have completed the task list.  It's more indicative of wanting to hide or keep the task list.  Maybe something like `wcadmin_tasklist_toggle`?

**Comment by pmcpinto** [comment]
@joshuatf, sorry I copied that event name but then I forgot to change it for this user action.

> I also feel like this event name is a tad confusing for both scenarios since users may or may not have completed the task list. It's more indicative of wanting to hide or keep the task list. Maybe something like wcadmin_tasklist_toggle?

I agree, I think it's better to add a new event instead of adding a prop to the existing one: wcadmin_tasklist_skipped

But instead of not having any prop it would be useful to have the following ones:
- completed_tasks: number of tasks completed
- completed_tasks_names: name of the tasks that were completed

It can be helpful to understand if they skipped the task list because they want to go on their own or because they finished some tasks but don't feel that the rest of them are necessary at this stage.

I'm going to update the issue description.

**Comment by pmcpinto** [comment]
Hey @becdetat, just a heads up that I tweaked a bit the logic of hiding the menu options based on the last design iteration (more info on this [p2](https://wp.me/p6riRB-5li)). I updated the issue description.
