### ISSUE TITLE
Onboarding: Add event props to identify stores with WCS and Jetpack installed

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3728]
In order to better identify funnel conversions, we should track if the following are active in a store when a task is being viewed via the `wcadmin_task_view` event:

* WCS is installed
* WCS is active
* Jetpack is installed
* Jetpack is active
* Jetpack is connected

This may be soon replaced by global event props, but this is a good temporary solution until that lands.

See p1581956393013000-slack-wc-onboarding for full discussion.

**Comment by pmcpinto** [comment]
@joshuatf sounds good. I think it would be better to also identify is they have the extensions installed.

**Comment by joshuatf** [comment]
@octaedro Any interest in tackling this issue and adding these event props to `task_view`?

I believe you can find active and installed plugins (and possibly jetpack connection status) preloaded under the onboarding property in the settings global.  `const onboarding = getSetting( 'onboarding', {} );`

**Comment by octaedro** [comment]
Hi @joshuatf, I lost the ping. I had a problem with the git notifications but I solved it.
Yes, I will get started with this issue now :-)

**Comment by pmcpinto** [comment]
@octaedro this issue can be closed, correct?

**Comment by octaedro** [comment]
> @octaedro this issue can be closed, correct?

@pmcpinto yes, I will close it now. The PR associated with it is already merged.
