### ISSUE TITLE
Currency Formats: Add a filter to dynamically change formats in client

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3742]
**Is your feature request related to a problem? Please describe.**

When extending wc-admin reports such that specific currencies are reflected, there is no way to change the currency format for items inside the chart, summary numbers, and table.

![Screen Shot 2020-02-19 at 4 02 15 PM](https://user-images.githubusercontent.com/1922453/74882605-40968580-53d4-11ea-8dba-dc7638a6149e.png)

**Describe the solution you'd like**

A client-side filter would be an excellent way to allow extensions to modify which format is used dynamically.
**Describe alternatives you've considered**

**Should this be prioritized? Why?**

Yes, currency extensions cannot fully alter values and show a currency different than the one in Woo Core settings.

**Comment by tivnet** [comment]
@psealock Paul, until there is a proper solution, is it possible to just remove the currency symbol?

The markup is not the same as the regular WC:

    <span class="woocommerce-summary__item-value">C$200.00</span>

There is no separate `<span>` for the symbol, so it's harder to alter it with JS.

And the view is unpleasant:

![image](https://user-images.githubusercontent.com/1696330/77834191-28bfc900-7119-11ea-89d1-e32ee473f02c.png)

**Comment by psealock** [comment]
Thanks for the question @tivnet. This is the last piece of this and is not yet implemented. Here is the issue to track https://github.com/woocommerce/woocommerce-admin/issues/3742.

**Comment by tivnet** [comment]
@psealock 
Hi Paul, do I understand correctly that the filter tag will be `woocommerce_admin_report_currency`?
Thanks

**Comment by psealock** [comment]
@tivnet It will be unless code review in the pull request says it should be something else. I'll update the example and blog post with a filter that works once that PR is merged.

**Comment by psealock** [comment]
Closed by https://github.com/woocommerce/woocommerce-admin/pull/4027
