### ISSUE TITLE
Filter Orders by Payment Gateway

### ISSUE THREAD

**Issue by benjaminprojas** [woocommerce/woocommerce-admin#3746]
**Is your feature request related to a problem? Please describe.**
When using multiple payment gateways it would be really nice to determine sales totals for periods based on specific gateways. This would help with reporting/auditing of that specific gateway.

**Describe the solution you'd like**
Would love to just see this added as a filter here:
![image](https://user-images.githubusercontent.com/962530/74964265-2616d900-53e1-11ea-9b3f-a092b49d0582.png)

**Describe alternatives you've considered**
It seems there are other add-ons for reporting that do this but I'd really rather not install another plugin...

**Should this be prioritized? Why?**
Only as much as any other feature request is 😉 

**Additional context**
I searched through GH and online to see if anyone has discussed this, but am not seeing anything so if I missed a duplicate, let me know.

**Comment by rrennick** [comment]
The [`sql-modification` example](https://github.com/woocommerce/woocommerce-admin/tree/master/docs/examples/extensions) does this for currency. With small adjustments, it could be used to filter by payment gateway.

**Comment by psealock** [comment]
See also https://woocommerce.wordpress.com/2020/02/20/extending-wc-admin-reports/ for a tutorial on how to add a filter and modify sql parameters.

**Comment by timmyc** [comment]
Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
