### ISSUE TITLE
Product titles include encoded entities

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3747]
**Describe the bug**
Both the stock & product reports use the product title from the product post. Product titles support HTML tags and encoded entities. The encoding is showing in the stock & product reports. See Screenshots

**Expected behavior**
HTML tags should be stripped and encoded entities should be decoded before display.

**Screenshots**
<img width="1142" alt="Screen Shot 2020-02-20 at 2 03 01 PM" src="https://user-images.githubusercontent.com/343847/74964686-354e5480-53ea-11ea-8ffa-9e6b2f4e747c.png">
<img width="641" alt="Screen Shot 2020-02-20 at 2 02 50 PM" src="https://user-images.githubusercontent.com/343847/74964687-367f8180-53ea-11ea-823c-79a78f570c70.png">
<img width="1139" alt="Screen Shot 2020-02-20 at 1 55 08 PM" src="https://user-images.githubusercontent.com/343847/74964688-367f8180-53ea-11ea-8895-d88fe0cecfae.png">

**Comment by psealock** [comment]
I'm not sure if the solution belongs on the front end, but in case it does, just noting that a similar function exists to strip html in currency formats. Maybe it could be a helper function of some kind.

https://github.com/woocommerce/woocommerce-admin/blob/e5c30ded36fa34c080aa7180b929a286baf04a49/packages/currency/src/index.js#L38-L41

**Comment by rrennick** [comment]
> I'm not sure if the solution belongs on the front end, but in case it does

We should be able to strip the tags in PHP but encoded entities like `&amp;` should probably be done in the front end because we want to have the entities display.

**Comment by timmyc** [comment]
Closing this out since it has landed in the version/1.0 branch
