### ISSUE TITLE
[0.26.0] Select Control throws error on OBW

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3754]
**Describe the bug**

In the OBW, bringing focus to the Country/State field throws an error.

![Screen Shot 2020-02-21 at 4 06 27 PM](https://user-images.githubusercontent.com/1922453/75000763-2c31b600-54c4-11ea-9b47-7e0bd7d42212.png)

**To Reproduce**

1. Enable the OBW in the `version/1.0` branch.
2. Go to Store Details, `/wp-admin/admin.php?page=wc-admin&step=store-details`.
3. Focus on the Country/State dropdown.
4. See the error.

This line causes problems because the option does not have `value` property.

https://github.com/woocommerce/woocommerce-admin/blob/8a23c9ad39ea2aec2478bfdff71552bd308311f8/packages/components/src/select-control/list.js#L154

Simply checking for the `value` property does not fix the problem. The component should not make too many assumptions about the shape of the data. A solution needs to make sure not to regress https://github.com/woocommerce/woocommerce-admin/pull/3700.

**Comment by joshuatf** [comment]
>The component should not make too many assumptions about the shape of the data.

Good point.  I think the "All that include" options are also a decision that should be made and controlled outside the component to keep this component from becoming too opinionated.

**Comment by psealock** [comment]
Fixed by https://github.com/woocommerce/woocommerce-admin/pull/3755. I'm not sure why GH isn't closing automatically anymore.
