### ISSUE TITLE
Special characters don't work in product search

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3758]
**Describe the bug**
When using the product search, an apostrophe causes an error in the product query.  The network response shows a SQL error.

These characters probably need to be escaped for use in SQL.

**To Reproduce**

1. Go to the products report.
1. Type a product search query in the search component with an `'` in it.
1. Note the console error.

**Expected behavior**
Expected to be able to search with special characters.

**Screenshots**
<img width="503" alt="Screen Shot 2020-02-21 at 2 35 32 PM" src="https://user-images.githubusercontent.com/10561050/75039139-4c5b7800-54b8-11ea-9e4b-8e669d193d33.png">
<img width="606" alt="Screen Shot 2020-02-21 at 2 35 27 PM" src="https://user-images.githubusercontent.com/10561050/75039142-4cf40e80-54b8-11ea-96bc-45a0d3e5b85e.png">

**Comment by joshuatf** [comment]
Note that this works as expected in the customer search, but worth checking other reports to see if this issue exists in other search APIs.

**Comment by jeffstieler** [comment]
Closed in #3826
