### ISSUE TITLE
[4.0 beta1] Shipping On boarding UX confusion

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-admin#3761]
In the new on boarding steps for shipping, when I see "free shipping" I was initially confused as I was assuming that the free shipping method was going to get created

![](https://d.pr/i/h4DH8N+)
Link to screenshot: https://d.pr/i/h4DH8N

Instead it is a flat rate set to $0.

Also, because of the "free shipping" text, I was hoping that I could include a free shipping **and** be able to add a flat rate in this setup process instead of just one shipping option.

**Comment by pmcpinto** [comment]
> We should consider changing the label to avoid confusion or an enhancement where we can setup a Free shipping method in this task.
 @jameskoster what do you think?

**Comment by jameskoster** [comment]
Any reason not to just create a free shipping method rather than a zero cost flat rate method if the user inputs a "0.00" price for shipping costs?

**Comment by pmcpinto** [comment]
I'm not seeing any benefit of having a zero cost flat rate instead of free shipping.

@joshuatf any additional feedback?

**Comment by joshuatf** [comment]
There's no reason to not create free shipping option over a flat rate; it just complicates some of the logic on the front-end, but I agree it should be fixed.

>Also, because of the "free shipping" text, I was hoping that I could include a free shipping and be able to add a flat rate in this setup process instead of just one shipping option.

I'm afraid that with the current UI that's not possible, but @jameskoster would be the expert here.

**Comment by jameskoster** [comment]
> Also, because of the "free shipping" text, I was hoping that I could include a free shipping and be able to add a flat rate in this setup process instead of just one shipping option.

Over time I think we'll expand this interface and introduce additional layers of complexity, but naturally we'd need to consider all the intricacies of the current shipping settings in order to do so in a successful way. For example if we allow folks to create additional rates, they'd also need to add descriptions and priorities, or conditions around when the different rates are made available to customers. That's not something we had time to do for this project, nor did it align with our goal of ensuring all stores configure at least _some_ shipping rules, and successfully launch.

**Comment by pmcpinto** [comment]
Thanks y'all for your feedback.

@joshuatf when you have time can you just add a rough estimate of how long it will take to implement this change (setting free shipping instead of a zero cost flat rate)? Just so we can evaluate if this should be included in the next cycle.

**Comment by joshuatf** [comment]
Hey @pmcpinto I think this is a 2.  I dabbled in this one a bit while I was on porter duty so I may try and implement a fix this cycle if I get a chance.

**Comment by pmcpinto** [comment]
Ok Joshua, thanks for the heads up!
