### ISSUE TITLE
OBW: Consider changing logic around dismissal of Task List or Payment task

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3766]
In tesing the Task List Payments setup with Stripe, I was faced with the Stripe integration form. Its a long one and I decided to skip it while setting up my store.

![Screen Shot 2020-02-25 at 10 58 43 AM](https://user-images.githubusercontent.com/1922453/75199799-eda04200-57c8-11ea-853a-c8336bbe7fd0.png)

This led me back to the dashboard and Task List with one task remaining.

![Screen Shot 2020-02-25 at 10 20 55 AM](https://user-images.githubusercontent.com/1922453/75199826-ff81e500-57c8-11ea-80cd-04bf70bea139.png)

I think the Stripe form is long enough that a "Skip this step" or enabling the dismissal of the Task List is a good idea. It seems odd to me to withhold the Dashboard from users at this point. It would be frustrating to me to have come all that way and not get to use the app.

So, I just wanted to raise the issue for an opinion. cc @pmcpinto @jameskoster

**Comment by jameskoster** [comment]
Is this based on the new designs? In the redesigned payments task we offer a way to skip the task altogether, or enable offline methods, which would solve this issue. We also have an affordance to capture _why_ people are skipping this step.

We're also adding a way for users to skip the entire task list.

I suppose what I'm saying is that this problem will be solved as we implement the new designs. If it's an easy fix in the interim then I guess it's worthwhile, but probably not worth prioritising.

**Comment by psealock** [comment]
>If it's an easy fix in the interim then I guess it's worthwhile, but probably not worth prioritising.

Sounds good. I'm closing this one.
