### ISSUE TITLE
Stock Report: Backordered Products Not Displayed

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3767]
**Describe the bug**
When a product is negative in inventory, and is set to allow "backorders" the product is not shown on the Stock Report page:

![image](https://user-images.githubusercontent.com/22080/75201474-5fbb4d00-571d-11ea-9d9d-fff6c4b8daf3.png)

![image](https://user-images.githubusercontent.com/22080/75201508-75307700-571d-11ea-8b73-fe6305613c09.png)

**To Reproduce**

1. Setup a product that has inventory control, and allows backorders
2. Have the inventory set to negative ( backordered )
3. View Analytics > Stock Report
4. Select the Backordered filter, note the product is not shown

**Expected behavior**
I expected for the backordered product to be displayed properly in the backordered product filter.

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by octaedro** [comment]
Hi @timmyc,

I'm trying to reproduce the bug but I couldn't. I tried in my local environment and in `jurassic.ninja` with no luck.

Here is what I see:
![Screen Capture on 2020-02-26 at 14-39-22](https://user-images.githubusercontent.com/1314156/75371922-60331f80-58a6-11ea-8706-7eda7b5852db.gif)

**Comment by timmyc** [comment]
interesting, wonder what i have done to break this locally for me. but if you can not reproduce it, lets go ahead and close it out.
