### ISSUE TITLE
[4.0 pre-rc]

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#3769]
**Describe the bug**
As a follwo up on https://github.com/woocommerce/woocommerce-admin/pull/3687, I'm seeing the `Deactivate` notice even after the plugin has been deactivated.

Steps: 
1. Installed WC 3.9.3 with WC Admin 0.23.3, went through the OBW.
2. Updated WC to the version from https://github.com/woocommerce/woocommerce/pull/25701
3. Click on `Deactivate` button.
4. WC Admin plugin is inactive, but notice remains.

**Screenshots**
<img width="1849" alt="Screenshot 2020-02-25 at 14 00 39" src="https://user-images.githubusercontent.com/2207451/75249802-4080f600-57d7-11ea-94e4-e94fc5f90018.png">

**Comment by peterfabian** [comment]
Side note: Seems like my wp cli installed 2 copies side by side, so retesting now with one copy only.

**Comment by rrennick** [comment]
Thanks @peterfabian, confirming I see the same.

**Comment by psealock** [comment]
This was fixed by https://github.com/woocommerce/woocommerce-admin/pull/3770
