### ISSUE TITLE
[4.0 rc1] Retry button disappears in order to proceed without Mailchimp installation if there is an issue installing Mailchimp

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3780]
**Describe the bug**

Retry button disappears in order to proceed without Mailchimp installation if there is an issue installing Mailchimp. This issue is contingent upon this one: https://github.com/woocommerce/woocommerce-admin/issues/3446. In other words, it only happens if you are not able to proceed with the Mailchimp installation and having errors described in https://github.com/woocommerce/woocommerce-admin/issues/3446. 

**To Reproduce**

Noting here that I could reproduce it with a pre-release of 4.0 rc1 just now on a brand new JN site:

- installed Query Monitor plugin
- installed Debug Bar plugin
- uploaded and activated rc1 zip
- I was selected for the new onboarding by default so didn’t have to change anything in that regard
- Next, I proceeded with new onboarding - selected to install WooCommerce Services and connected the site to WP.com account.
- selected all the paid extensions on the screen about what kind of products I want to sell
- On the FB/Mailchimp step - selected both to be installed and got the following error:

<img width="775" alt="Screen Shot 2020-02-26 at 10 10 05 AM" src="https://user-images.githubusercontent.com/19143190/75361768-ce1b1f00-5885-11ea-8c8b-bfe26e942bff.png">

- `Retry` the button disappeared if I toggled off the Mailchimp installation:

![](http://g.recordit.co/g5RPY905u0.gif)

**Expected behavior**

I expected the button to be there even if I toggled off the Mailchimp installation. Right now it looks like there is no way to proceed. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.3
* Browser: Chrome
* Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by timmyc** [comment]
Thanks for logging the issue @juliaamosova - thinking we can force this error state by having the REST API return an error on the mailchimp install test. We definitely want the "Continue without installing" link here to be shown.

**Comment by psealock** [comment]
I can reproduce this locally by forcing an error on the `onboarding/plugins/install` endpoint.

Whats also weird is if I untoggle both facebook and mailchimp, I proceed to the next screen with a success message.

**Comment by psealock** [comment]
Fixed by #3780
