### ISSUE TITLE
[4.0 RC1] Update Country Labeling to Match Core

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3781]
In https://github.com/woocommerce/woocommerce/pull/25530 core updated the labeling of "Country" in the UI to be "Country / Region". We need to update our usage of this label in wc-admin to be in-line with core. 

The areas that @tammullen pointed out where this is currently shown in wc-admin are:

- Site Profiler
- Customer Report

Also thinking we need to update the autocompleter for country too

Since this is just a string update, this fix should target `version/1.0`

**Comment by octaedro** [comment]
Hi @timmyc, I was looking for the label `Country` in the code, I was able to find it in `Customer Report` but I couldn't in the `Site Profiler`. Can you point me in the right direction to find this?
Thank you!

**Comment by timmyc** [comment]
@octaedro sure thing - so I think [this is the label](https://github.com/woocommerce/woocommerce-admin/blob/master/client/dashboard/components/settings/general/store-address.js#L206) that we need to update. But maybe look in that file to make sure there aren't any error messages or other translated strings that contain country. Variable and method names are fine and do not need to be changed.

**Comment by octaedro** [comment]
@timmyc got it! I will replace the text: `Country / State` with  `Country / Region` and I will continue searching.
Thank you!

**Comment by timmyc** [comment]
Closing this out since it has landed in version/1.0
