### ISSUE TITLE
Review tracking JS library used with the WC Analytics module in JP

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3783]
More info soon.

Context here: p90Yrv-1BS-p2

**Comment by psealock** [comment]
@pmcpinto I plan on tackling the issues in the linked p2. Is there anything outside that context that needs addressing as well?

**Comment by pmcpinto** [comment]
Hey @psealock. Nope, I think it will only be necessary to address what was mentioned in the p2. Thanks

**Comment by psealock** [comment]
These two close out the issue

https://github.com/Automattic/analytics/pull/48
https://github.com/Automattic/analytics/pull/47

**Comment by pmcpinto** [comment]
@psealock I'm going to close the issue
