### ISSUE TITLE
Integrate breadcrumb filtering into page registration/connection

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce-admin#3792]
**Describe the bug**
`wc_admin_connect_page()` should be able to include the new WooCommerce admin navigation bar on pages provided by external plugins, with the ability to set their place in the breadcrumb hierarchy by supplying a "parent" argument. See https://woocommerce.wordpress.com/2020/02/27/integrating-the-new-woocommerce-navigation-bar/

However, while plugins can set up their own hierarchy, it doesn't seem to be possible for a third party plugin to specify an existing WC settings page as its parent. 

The issue seems to line in these bits of code:

The settings pages aren't registered as connected pages, so this if() condition triggers: https://github.com/woocommerce/woocommerce-admin/blob/master/src/PageController.php#L148

Breadcrumbs are then generated in completely separate code for the settings pages:
https://github.com/woocommerce/woocommerce-admin/blob/master/includes/connect-existing-pages.php#L15

It looks like the add-ons / reports / settings and status sections aren't special cased, and not connected properly. This means that there is no valid ID for you to pass as a `parent` when trying to connect your page. 

**To Reproduce**
```php
wc_admin_connect_page(
    array(
        'id'        => 'my-id',
        'screen_id' => 'my-screen-id',
        'title'     => 'My screen title',
        'parent'    => 'woocommerce-settings-delivery', // No valid value available to insert here to make this have "WooCommerce » Settings" as the breadcrumb parents
    )
);
```

**Expected behavior**
The settings pages (and potentially other pages) should be properly registered, and exist in the PageController's `$pages` property so that they can be registered as parents.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

WooCommerce `release/4.0` branch at SHA fbdcde54a

**Comment by rrennick** [comment]
> it doesn't seem to be possible for a third party plugin to specify an existing WC settings page as its parent.

Can you clarify what you are trying to do? A third party settings tab is automatically added to the breadcrumb:
<img width="590" alt="Screen Shot 2020-02-27 at 2 42 18 PM" src="https://user-images.githubusercontent.com/343847/75475695-9b4d5580-596f-11ea-99d4-43fc0408591b.png">

**Comment by leewillis77** [comment]
Hi; 

This isn't actually a settings tab in the WooCommerce standard settings page - it's a separate page (for longstanding legacy reasons), but from a breadcrumb point of view it makes sense to have the breadcrumb be "WooCommerce » Settings" which as far as I can tell isn't possible currently. 

So, when trying to add the navigation bar to the page using `wc_admin_connect_page`, but you can't do that and specify the Settings page, or any of it's "tabs" as the parent - there's not a value you can supply as the parent that's been registered in the PageController::$pages array.

**Comment by rrennick** [comment]
@leewillis77 Thanks for the clarification. There is a filter you could use to modify the breadcrumbs in https://github.com/woocommerce/woocommerce-admin/blob/1f261998e7287b77bc13c3d4ee2e84b717da7957/src/PageController.php#L179:L185 .

**Comment by leewillis77** [comment]
I did see that, but if I use that I then have to calculate what the breadcrumbs would be myself (potentially duplicating code in the process).

Surely it would be simpler if the pages currently handled by wc_admin_get_core_pages_to_connect() were properly registered with the page controller?

**Comment by rrennick** [comment]
@leewillis77 Thanks for the info and feedback. Given how close we are to the release of WC4.0, we are focused on bug fixes for current functionality and we won't be looking at this in the immediate future. However, we are evaluating our next iteration of navigation and can take this into consideration.
