### ISSUE TITLE
Downloads Report: Data not respecting Time Zone

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3802]
**Describe the bug**

Downloads aren't reflected in Downloads Report besides the Summary Numbers. The Chart and Table don't show any data.

**To Reproduce**

1. Set your store time zone to a location one day ahead (Fiji or New Zealand).
1. Create a downloadable product. See settings at WooCommerce > Settings >Products > Downloadable Products
2. Use a payment gateway or Stripe, COD won't work (unless maybe you can mark it as paid?).
3. Purchase product
4. Download.
5. See the Download Report after the scheduled action has run.
6. Notice the Summary Number shows the correct download count, but the chart and table are not populated.
7. See the downloads appear "Yesterday"

**Screenshots**

![Screen Shot 2020-03-03 at 12 03 36 PM](https://user-images.githubusercontent.com/1922453/75726577-9b6e9c00-5d47-11ea-884a-63fb4cc13668.png)

![Screen Shot 2020-03-03 at 12 03 45 PM](https://user-images.githubusercontent.com/1922453/75726586-9e698c80-5d47-11ea-992a-118514a53950.png)

**Comment by jeffstieler** [comment]
@psealock why was https://github.com/woocommerce/woocommerce-admin/pull/3806 abandoned?

**Comment by psealock** [comment]
Good question. I don't remember.
