### ISSUE TITLE
[4.0 rc1] WC-Admin: Import Historical data task - when navigating away a message that not saved changes may be lost comes up

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3803]
**Describe the bug**

Upon starting the Import Historical data task and navigating away, a message that not saved changes may be lost comes up. Tested on the JurassicNinja site. 

**To Reproduce**

1. Upon upgrading to 4.0, a notice comes up to import historical data. Proceed with that notice:

<img width="1438" alt="Screen Shot 2020-03-02 at 6 16 10 PM" src="https://user-images.githubusercontent.com/19143190/75727622-5bf67000-5cb3-11ea-805b-88b1cae5403a.png">

2. Run the import. It says on the page that navigating away won't interrupt the import and no data will be lost:

![import](https://user-images.githubusercontent.com/19143190/75726326-1edcae80-5cb0-11ea-9ebb-1e07fd03de5e.jpg)

3. Upon clicking away (for example, to `Products` section), the pop-up window comes up prompting that any unsaved data will be lost if I navigate away: 

![import2](https://user-images.githubusercontent.com/19143190/75727727-a11aa200-5cb3-11ea-9059-f11b819a6095.jpg)

**Expected behavior**

I expected no pop-up window to come up. 

<hr>

Note that I've tried to reproduce it but I can no longer do that. I also thought that this pop-up was due to some of the unsaved settings in the `Analytics Settings` part of the same page with the `Save` button but I've tried also to make changes there without saving and navigate away - I actually got no pop-up letting me know that my unsaved changes won't be saved. This is the section I am referring to:

<img width="796" alt="Screen Shot 2020-03-02 at 6 31 13 PM" src="https://user-images.githubusercontent.com/19143190/75727849-02db0c00-5cb4-11ea-9607-2e557c8aae49.png"> 

For now, I am not sure what caused the pop-up. I will test again tomorrow on other sites to see if I can reproduce. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.3
* Browser: Chrome
* Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by rrennick** [comment]
@juliaamosova Have you been able to reproduce this? I tried both another analytics screen and the products list and didn't get the warning in either case.

**Comment by juliaamosova** [comment]
@rrennick I have not been able to reproduce it ever since - I paid attention to it every time I tested but no luck. I think we can safely close this issue for now. I will comment on it again in case I come across it.
