### ISSUE TITLE
[4.0 rc1] WC-Admin: Import Historical data task - not able to rebuild data after deleting previously built data

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3804]
**Describe the bug**

WC-Admin: Import Historical data task - not able to rebuild data after deleting previously built data. Tested on one of my Pressable test sites. 

**To Reproduce**

1. Upon upgrading to 4.0, a notice comes up to import historical data. Proceed with that notice:

<img width="1438" alt="Screen Shot 2020-03-02 at 6 16 10 PM" src="https://user-images.githubusercontent.com/19143190/75727622-5bf67000-5cb3-11ea-805b-88b1cae5403a.png">

2. Run the import. Wait for it to be completed: 

![tart](https://user-images.githubusercontent.com/19143190/75728498-f8ba0d00-5cb5-11ea-938d-da9b2f8067d9.jpg)

3. Click on `Delete previously imported data`- note the message letting you know that data is being deleted. Wait until it is deleted:

![delete1](https://user-images.githubusercontent.com/19143190/75728426-babce900-5cb5-11ea-9189-2c68111719f8.jpg)

4. When data is deleted, you are presented with an option to start an import again. Start it by clicking the `Start` button:

![tart](https://user-images.githubusercontent.com/19143190/75728650-83027100-5cb6-11ea-8250-7ba6ebad8b83.jpg)

5. Note that typically after clicking `Start` button, that button changes to `Stop import` but in 50% of cases for me it remains `Start`. And if I click on it again, I am getting an error message letting me know that the data can not be rebuilt:

![deleter2](https://user-images.githubusercontent.com/19143190/75728960-5b5fd880-5cb7-11ea-86d9-9e090abc9726.jpg)

**Expected behavior**

I expected to be able to successfully rebuilt the data. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.3
* Browser: Chrome
* Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by rrennick** [comment]
@juliaamosova Thanks for the report. Can you clarify the steps you took for this?

> When data is deleted, you are presented with an option to start an import again.

My start button was not enabled automatically when the delete was complete.

**Comment by timmyc** [comment]
So I tested this out again, and agree that it is a bit buggy, but I also feel like this is pretty edge case to import / delete / import again in order like that. And since we haven't had any bug reports from the wild around this, I'm going to close this as a won't fix.

My fix was refreshing the page and the import behaves as expected. I just don't know if we can justify fixing this particular flow because it feels like it isn't one that would be encountered.

**Comment by juliaamosova** [comment]
Sounds good @timmyc thanks! Sorry, I didn't follow-up on it earlier @rrennick.
