### ISSUE TITLE
Small RTL issues

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#3811]
**Describe the bug**
When testing 4.0-rc.1, I noticed some RTL issues, mostly of cosmetic character:

- Notice carousel is incorrect and 
- arrows in the Performance section are pointed in the opposite direction
![Screenshot 2020-03-03 at 17 11 13](https://user-images.githubusercontent.com/2207451/75795583-cfab8200-5d72-11ea-9144-b4394b9bb11f.png)

The loading icon is incorrect: small dot is rotating outside the large circle:
![Screenshot 2020-03-03 at 17 11 51](https://user-images.githubusercontent.com/2207451/75795744-084b5b80-5d73-11ea-8f4b-a826c53e3d2a.png)

There might be other errors I haven't noticed, but I thought I'd mention these just in case.

**Desktop (please complete the following information):**

* OS: macOS 10.14.6
* Browser Chrome 80.0.3987.122

**Comment by Aljullu** [comment]
> The loading icon is incorrect: small dot is rotating outside the large circle:

I remember fixing this one some time ago (https://github.com/WordPress/gutenberg/pull/14418). Might it be related to an old version of Gutenberg?
