### ISSUE TITLE
Activity Panels: JITM Alerts Hidden by Nav Bar

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3813]
**Describe the bug**
The new navigation bar is obscuring JITM messages that are loaded async. Full report and background on p6q8Tx-1BW-p2

![image](https://user-images.githubusercontent.com/22080/75807173-c94ce400-5d39-11ea-8d2d-e1dfcfafdadf.png)

**Comment by rrennick** [comment]
Addressed in #3827
