### ISSUE TITLE
Orders closed via cron status import do not update in Analytics (order status)

### ISSUE THREAD

**Issue by rwkyyy** [woocommerce/woocommerce-admin#3821]
**Describe the bug**
Orders go to status "processing" then are exported and sent to the shipping depo, from there daily (in night time), orders are updated from courier based on their status (delivered, failed, etc.)

The issue is that when they change to status "completed" this status update is not reported in reports; basically all reports for the past few months are "processing" although they are all "completed"

This issue is with a single store that has this type of automation.

**To Reproduce**
N/A

**Expected behavior**
Expecting orders in reports to show as "completed"

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Imports are done with WP All Import and the feature "wp_insert_post" is disabled, can this be the culprit?
Also, is there any way to re-sync the order status in the reports?

**Comment by rwkyyy** [comment]
Update:
Apparently after going to **settings** and selecting last 90 days and start, a button "delete previously imported data" became clickable so I used it and now it's re-importing the orders via Action Scheduler, first results look good, the orders seem to have the right status.

Still not having to always delete and re-import data would be great.

**Comment by rrennick** [comment]
@rwkyyy On the import screen there is a "Skip already imported" checkbox that is checked by default. If you uncheck that then you do not need to delete the existing data.
