### ISSUE TITLE
PHP Warning: A non-numeric value encountered in NoteTraits.php on line 34

### ISSUE THREAD

**Issue by Phil-A-Delphia** [woocommerce/woocommerce-admin#3829]
I'm receiving the following warning each time I start WordPress:

Woocommerce Admin PHP Warning: A non-numeric value encountered in [MyPath]\wp-content\plugins\woocommerce-admin\src\Notes\"NoteTraits.php on line 34"

My WP configuration is as follows:
WordPress Version: 5.3.2
Woocommerce Version: Version 3.9.3
OS: Windows: NT 10.0 x64
Web server: Apache/2.4.41 (Win64) OpenSSL/1.1.1d PHP/7.4.2
PHP version: 7.4.2 (Supports 64bit values)
Database: MySQL 8.0.19 x64

**Comment by jeffstieler** [comment]
Closed in https://github.com/woocommerce/woocommerce-admin/pull/3855.
