### ISSUE TITLE
[4.0 rc1] WC-Admin: Inbox - New Features - `Learn more` button links to wc dev blog

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3833]
**Describe the bug**

Currently, when clicking on `Inbox/New Feature(s)/Learn more` links to the WC dev blog url: https://woocommerce.wordpress.com/. 

**To Reproduce**

1. Update to WC 4.0 rc1
2. Click on `Inbox/New Features(s)/Learn more`:

![new_features](https://user-images.githubusercontent.com/19143190/76017804-32c12400-5eed-11ea-89a2-9b4e79ff036e.jpg)

3. Button click currently goes to woocommerce dev blog url: https://woocommerce.wordpress.com/ which currently looks like this:

<img width="1440" alt="Screen Shot 2020-03-05 at 2 18 09 PM" src="https://user-images.githubusercontent.com/19143190/76017902-60a66880-5eed-11ea-9738-5a800a827194.png">

**Expected behavior**

IMO, we should link to the WC Admin documentation. It is possible that it is already planned but I couldn't find an issue so decided to log it. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.3
* Browser: Chrome
* Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by pmcpinto** [comment]
I agree that it makes sense to change the link to the WC Admin documentation and probably we should consider removing this notification on 4.1 or 4.2.

cc @timmyc and @jameskoster for additional feedback

**Comment by jameskoster** [comment]
+1 on linking to docs, and removing ASAP.

**Comment by pmcpinto** [comment]
Let's remove it on 4.1 if possible.

**Comment by timmyc** [comment]
I think we can get this note removed during the cooldown period.

**Comment by timmyc** [comment]
This inbox note has been removed, so I'm going to close this out.
