### ISSUE TITLE
Report Tables: Partial string search doesn't display all results.

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#3834]
**Describe the bug**

Performing a partial string search in a report table only shows the first "page" of items returned from the API, which results in the appearance of "missing" items.

**To Reproduce**

1. The screenshots below should be illustrative enough

**Expected behavior**

I expect the report table to include all partial matches, paginated.

**Screenshots**

Example (WCCOM):

![Screen Shot 2020-03-05 at 12 49 41 PM](https://user-images.githubusercontent.com/63922/76019965-d60b3c80-5edf-11ea-9f79-36fb3bdc830b.png)

(Note the two coupons beginning with `wc` that have orders)

Searching:

![Screen Shot 2020-03-05 at 12 50 36 PM](https://user-images.githubusercontent.com/63922/76020028-ef13ed80-5edf-11ea-9def-763f65cd5b87.png)

(Note the two coupons aren't in the results)

After selecting the partial search:

![Screen Shot 2020-03-05 at 12 51 39 PM](https://user-images.githubusercontent.com/63922/76020101-12d73380-5ee0-11ea-8a68-74a2c1f8eb75.png)

**Comment by chihsuan** [comment]
Closing this since this bug is over 6 months old.
