### ISSUE TITLE
Correct accounting of returns

### ISSUE THREAD

**Issue by ciszere** [woocommerce/woocommerce-admin#3835]
**Is your feature request related to a problem? Please describe.**
So I love this new analytics plugin but come on. We need to make sure that the returns are registered in the correct way. In accounting, a return of an order shall be registered on the same day as the initial purchase took place. Today the returns are messing all the numbers up because if I make let's say 20 return on a single day. they all are affection the numbers on this specific day. That's not accurate to actual sale. Also, it's not legal to do this in accounting (At least here in Sweden)

**Describe the solution you'd like**
 Let's say a customer buys on 1 of February, and then make a return the 1 of mars. then the return shall be registered on 1 of February and not affect the numbers on 1 of mars. Shall be an easy fix? 

**Describe alternatives you've considered**
OR at least a possible setting to choose what type of accounting you want to do. 

**Should this be prioritized? Why?**
For now, your numbers will be totally wrong compared to actually Accounting numbers. Also, i believe this is a really easy fix?

**Additional context**
Nope, you are doing a great work :)

**Comment by rrennick** [comment]
@ciszere We appreciate you posting detailed feedback.

> In accounting, a return of an order shall be registered on the same day as the initial purchase took place.
> it's not legal to do this in accounting (At least here in Sweden)

I'm not familiar with how financial filing may be distinct in Sweden. Do you have a reference that you can provide for that requirement? (I've been doing some corporate bookkeeping for most of the last 25 years and that's definitely not how returns are filed in my tax jurisdiction.)

**Comment by ciszere** [comment]
Hello again,

Thanks for your answer :)

Okey i understand, and you are probably right also, so maybe the
bookkeeping is different in our countries. This is just what my bookkeeper
told me here in Sweden..

But lets take this example. On black friday our sales skyrocket with 500%
(this also means that the returns went up 500% in the next 3 weeks (Since
that's our return policy). and after black friday ( in december) The sales
went down, due to the high black friday sale.

So when registered all the return in december. (It was more returns than
sales) the report system just showed negative results. So it was hard for
us to show how sales actually was in december. In this case ( My bookeeker
said) it should be better to register the return to the right month
(November/black friday). This way we would see how many "sales" we actually
got in December.

But im not a bookkeeper and cannot say how things really should work.

Anyway, this function will help me a lot here in Sweden. Then it's up
to you what you think :) I understand that you have a lot of functions to
add. So i'm just trying to help :)


Thanks for the answer

Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den mån 9 mars 2020 kl 19:56 skrev Ron Rennick <notifications@github.com>:

**Comment by joshuatf** [comment]
Thanks for the feedback here @ciszere!

>So when registered all the return in december. (It was more returns than
sales) the report system just showed negative results. So it was hard for
us to show how sales actually was in december.

From our research this does appear to typically be the correct way of recording the sales for accounting and tax purposes.

If you have any further reading we can do on the differences in Sweden, this may be something we can add in the future.  Please let me know if so and I'll look into it!
