### ISSUE TITLE
[4.0 rc1] WC-Admin: Inbox - Connect to wc.com - `Connect` notice is available only once. Disappears after clicked but still not connected to wc.com 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3836]
**Describe the bug**

Currently, if you click on `Inbox/Connect to wc.com/Connect`, the notice disappears even though the user still didn't connect to wc.com.  

**To Reproduce**

1. Update to 4.0 rc1;
2. Click on `Inbox/Connect to wc.com/Connect`:

![connect1](https://user-images.githubusercontent.com/19143190/76020457-6ef68380-5ef1-11ea-89eb-5ab79d0a2db2.jpg)

3. It takes you to the page to connect to wc.com account but if you get distracted and navigate away, it is easy to forget that it needs to be done;

4. If you click on `Inbox/Connect to wc.com/Connect`, it will show you that Inbox is empty even though you didn't connect to wc.com account yet:

![connect2](https://user-images.githubusercontent.com/19143190/76020748-fd6b0500-5ef1-11ea-8739-cfc25bbe6cfd.jpg)

**Expected behavior**

Maybe there is an action scheduled to show the notice again in some time but I feel like we should not hide it until the user actually connects to wc.com account. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.3
* Browser: Chrome
* Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by timmyc** [comment]
Thanks for the report @juliaamosova - I see a few different options to explore here, and will leave it up to the dev who gets this to determine which path(s) to explore:

- Option 1: See if there is any hook or action we can use on the local site after the initial WCCOM connection is established. If so, possibly use that to mark this inbox notif as actioned. This seems like the cleanest approach if possible.
- Option 2: Use Julia's recommendation of making this inbox notif re-appear if the connection isn't established.
