### ISSUE TITLE
Report Table: products without value are disappearing when ordering

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#3840]
**Describe the bug**
In the products' report, some products are disappearing from the table when they don't have a value to order by.

**To Reproduce**

0. To reproduce this bug it's necessary to have at least 2 products, one with a valid `SKU` value and another one without `SKU`.
1. Go to `Analytics` | `Products` (URL: `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts`)
2. Click on the table header `SKU` to order the item list by `SKU`.
3. The list items that don't have `SKU` value will disappear.

**Expected behavior**
The list should keep the same filtered items. 

**Screenshots**
![Screen Capture on 2020-03-05 at 16-40-41](https://user-images.githubusercontent.com/1314156/76036004-ae3cc880-5f21-11ea-85cf-9c00321f9320.gif)

**Comment by psealock** [comment]
Fixed by #3845
