### ISSUE TITLE
Constant not defined when calling `get_active_version()` on WP 5.2

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#3841]
**Describe the bug**
`\Automattic\WooCommerce\Admin\Composer\Package::get_active_version()` will cause a PHP notice in case when wc-admin plugin is not installed && package is inactive (either when running on WP 5.2 or when disabled via filter on later WP), as `WC_ADMIN_VERSION_NUMBER` is not defined.

**To Reproduce**

1. Use WP 5.2 and install WC 4.0-rc
2. Try to call `\Automattic\WooCommerce\Admin\Composer\Package::get_active_version()`
3. You should see PHP notice about the undefined constant.

Discovered while testing 4.0 on WP 5.2. The use in system status was fixed in https://github.com/woocommerce/woocommerce/pull/25830, but I think it should be fixed in this repo as well.

**Comment by psealock** [comment]
I have a fix https://github.com/woocommerce/woocommerce-admin/pull/3851 to make sure `get_active_version` doesn't reference constants that may not be defined. With the exception of Woo Core, would anyone need to use this function? Should we ask extension developers to use `get_active_version` as THE way to determine if a site has at wc-admin active?

If so, I can add some documentation too.

**Comment by peterfabian** [comment]
Maybe @allendav would be able to say if their plugin is using some parts from wc-admin, if they check for wc admin version? I could see it being useful for extensions built on top of WC Admin, so in my view, having THE way to determine currently loaded version makes sense.

**Comment by psealock** [comment]
>I could see it being useful for extensions built on top of WC Admin, so in my view, having THE way to determine currently loaded version makes sense.

I agree, in the fix's testing instructions I re-create this exact scenario, https://github.com/woocommerce/woocommerce-admin/pull/3851.

**Comment by psealock** [comment]
This was fixed by https://github.com/woocommerce/woocommerce-admin/pull/3851
