### ISSUE TITLE
Offer "npm run build" instructions earlier

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-admin#3843]
**Describe the bug**
When installing WC Admin, I can see the notice to run `composer install` in the right folder. 

![](https://d.pr/i/pcIM6n+)
If the image does not load, please click this link: https://d.pr/i/pcIM6n.

However, when I do so, I get the following error when trying to activate the plugin:

```
Warning: require_once(/Users/jobthomas/Sites/firstpr/wp-content/plugins/woocommerce-admin//includes/feature-config.php): failed to open stream: No such file or directory in /Users/jobthomas/Sites/firstpr/wp-content/plugins/woocommerce-admin/src/FeaturePlugin.php on line 69

Fatal error: require_once(): Failed opening required '/Users/jobthomas/Sites/firstpr/wp-content/plugins/woocommerce-admin//includes/feature-config.php' (include_path='.:/usr/local/Cellar/valet-php@7.4/7.4.3/share/valet-php@7.4/pear') in /Users/jobthomas/Sites/firstpr/wp-content/plugins/woocommerce-admin/src/FeaturePlugin.php on line 69

There has been a critical error on your website. Please check your site admin email inbox for instructions.
```

Only after running `npm run build` do I get rid of the fatal error. At that point, I see the instructions for `npm install` and `npm run build`. 

![](https://d.pr/i/NoKQF6+)
If the image does not load, please click this link: https://d.pr/i/NoKQF6.

### Suggested improvement 

Offer the second notification with the first one already.

**Comment by jobthomas** [comment]
Maybe it's worth actually just linking to the instructions in the readme file here on this repo.

**Comment by timmyc** [comment]
Since we do have the instructions listed on the home of the repo - I feel this doesn't really need further action: https://github.com/woocommerce/woocommerce-admin#development

Closing out.

**Comment by jobthomas** [comment]
@timmyc should you not move it altogether then (this notice): I was following the instructions there when hitting a fatal error. This suggestion is to just make it more clear in the notice within the dashboard.

**Comment by timmyc** [comment]
Ah I see what you are saying now @jobthomas - just the addition of the `composer` part of the setup commands would help.

**Comment by jobthomas** [comment]
Exactly - sorry for not being more clear earlier.
