### ISSUE TITLE
Chart Image is very small on every Woocommerce Admin Menu

### ISSUE THREAD

**Issue by maximus13k** [woocommerce/woocommerce-admin#3849]
**Describe the bug**

**To Reproduce**

1. Go to 'Woocommerce Menu'
2. Click on 'Dashboard'
3. See error

**Expected behavior**
The Charts were not visible, they are too small.

**Screenshots**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser [chrome}
* Version [e.g. 22]

![image](https://user-images.githubusercontent.com/61938818/76163641-64025400-617a-11ea-8785-ef6052925b4e.png)
![Chart Error](https://user-images.githubusercontent.com/61938818/76163651-9449f280-617a-11ea-9875-1ae89d385677.png)

**Comment by jeffstieler** [comment]
Thanks for the report @maximus13k.

I'm unable to reproduce this on a Windows 7 machine running Chrome:

![Screen Shot 2020-03-09 at 10 20 09 AM](https://user-images.githubusercontent.com/63922/76234630-9732fa80-61ef-11ea-983c-2ce3cfc2eedf.png)

Are you seeing any errors in the console (developer tools)?

If not, are you able to perform a plugin conflict test by disabling all plugins other than WooCommerce and WooCommerce Admin one by one?

**Comment by tonydjukic** [comment]
Confirming that I'm seeing the same issue in Safari and Chrome on a Mac.  Error console is empty and the issue persists with default theme and all other plugins except WooCommerce deactivated.

**Comment by jeffstieler** [comment]
Nice sleuthing @tonydjukic! Any chance you have links to those tutorials or the plugin?

Thank you.

**Comment by tonydjukic** [comment]
I actually searched the other night but everything I find now seems to have an updated logic to the way it instructs the admin to display SVGs.  Everything I find now is `width:100%` rather than the specificity.  

I only know it exists because I had used the tutorial myself and ended up with that code snippet running on a local test site and I actually wrote that code to replace a plugin that added SVG support and did the same thing.  I remember thinking "Why have an entire plugin just for these 10-12 lines of code?"  The one thing I'm sure of is that the <style> code it injected into the wp_head was identical (except for the actual pixels) between the plugin and the tutorial and that's what I posted above.

I deleted the plugin ages ago and the code snippet was added at the same time - it's a site I use to test new stuff I'm curious about that isn't project specific, so it's a bit of a 'wild west' of code chunks.  Sorry.

**Comment by becdetat** [comment]
Hi @maximus13k 

I'm just circling back to you on this issue. I'm unable to reproduce the issue without adding some conflicting CSS such as @tonydjukic mentions. As requested by @jeffstieler, can you perform a plugin conflict test by disabling all plugins other than WooCommerce and WooCommerce Admin one by one?

Thanks
Rebecca

**Comment by maximus13k** [comment]
Hi Rebecca..

I've tried disabling the other plug-in one by one but there's no result, the graphic still shows very small in the top left corner..

Thanks..

**Comment by becdetat** [comment]
@maximus13k can you provide a system status report? Under WooCommerce -> Status -> Get system report. Just copy the output here. Thanks.

**Comment by maximus13k** [comment]
`
### WordPress Environment ###

WordPress address (URL): https://na7uku.com
Site address (URL): https://na7uku.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: id_ID
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix) OpenSSL/1.0.2g
PHP Version: 7.2.28
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.29-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_4e572eef5b_
Total Ukuran Database: 29.30MB
Ukuran Data Database: 23.17MB
Ukuran Indeks Database: 6.13MB
wp_4e572eef5b_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_4e572eef5b_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_4e572eef5b_woocommerce_order_itemmeta: Data: 0.50MB + Index: 0.44MB + Engine InnoDB
wp_4e572eef5b_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_4e572eef5b_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_actionscheduler_actions: Data: 1.30MB + Index: 0.50MB + Engine InnoDB
wp_4e572eef5b_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_actionscheduler_logs: Data: 1.34MB + Index: 0.42MB + Engine InnoDB
wp_4e572eef5b_cf_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_cf_form_entries: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_4e572eef5b_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_cf_form_entry_values: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_4e572eef5b_cf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_cf_queue_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_cf_queue_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_cf_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_cf_tracking_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_comments: Data: 1.17MB + Index: 0.33MB + Engine InnoDB
wp_4e572eef5b_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_options: Data: 4.03MB + Index: 0.16MB + Engine InnoDB
wp_4e572eef5b_postmeta: Data: 10.17MB + Index: 2.78MB + Engine InnoDB
wp_4e572eef5b_posts: Data: 3.42MB + Index: 0.23MB + Engine InnoDB
wp_4e572eef5b_rednao_wc_invoice: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_rednao_wc_invoices_created: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_rednao_wc_invoices_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_sp_email_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_usermeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_4e572eef5b_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_4e572eef5b_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4e572eef5b_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_4e572eef5b_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_4e572eef5b_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4e572eef5b_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_4e572eef5b_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4e572eef5b_wfpklist_template_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 148
custom_css: 4
customize_changeset: 14
elementor_library: 7
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 3
page: 22
post: 13
product: 41
product_variation: 88
revision: 349
shop_coupon: 21
shop_order: 380
shop_order_refund: 2
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

AW WooCommerce Kode Pembayaran ( Free Version ): oleh AgenWebsite – 1.1.4 – Tidak dites dengan versi WooCommerce yang aktif
Classic Editor: oleh WordPress Contributors – 1.5
Elementor: oleh Elementor.com – 2.9.6
Loco Translate: oleh Tim Whitlock – 2.3.1
Official Facebook Pixel: oleh Facebook – 2.0.1
WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels (Basic): oleh WebToffee – 2.6.3
UpdraftPlus - Backup/Restore: oleh UpdraftPlus.Com
DavidAnderson – 1.16.22

WooCommerce Blocks: oleh Automattic – 2.5.14
WooCommerce Konfirmasi Pembayaran: oleh AgenWebsite – 1.0.7 – Tidak dites dengan versi WooCommerce yang aktif
WooCommerce: oleh Automattic – 4.0.1
Woo WA Premium: oleh QODR – 0.3.6-beta – Tidak dites dengan versi WooCommerce yang aktif
WP Fastest Cache: oleh Emre Vona – 0.9.0.4
WP Mail SMTP: oleh WPForms – 1.9.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: IDR (Rp)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #183 - /?page_id=183
Keranjang Belanja: #187 - /?page_id=187
Checkout: #188 - /?page_id=188
Akun saya: #190 - /?page_id=190
Ketentuan dan Syarat: #2981 - /?page_id=2981

### Theme ###

Name: AdoraID WP Child
Version: 0.8.1
Author URL: https://www.tokopress.id
Child Theme: ✔
Parent Theme Name: AdoraID WP
Parent Theme Version: 2.2.0
Parent Theme Author URL: https://www.tokopress.id
WooCommerce Support: ✔

### Templates ###

Overrides: adoraid-wp/woocommerce/emails/customer-completed-order.php
adoraid-wp/woocommerce/emails/customer-on-hold-order.php
adoraid-wp/woocommerce/emails/customer-processing-order.php
adoraid-wp/woocommerce/emails/plain/customer-completed-order.php
adoraid-wp/woocommerce/emails/plain/customer-on-hold-order.php
adoraid-wp/woocommerce/emails/plain/customer-processing-order.php


### Action Scheduler ###

Batal: 1
Oldest: 2020-03-01 08:14:43 +0000
Newest: 2020-03-01 08:14:43 +0000

Selesai: 1.646
Oldest: 2020-02-23 09:01:50 +0000
Newest: 2020-03-25 06:14:58 +0000

`

**Comment by becdetat** [comment]
Thanks @maximus13k .

I couldn't find the issue with any of your plugins but I suspect it is caused by your theme. I hopped on to xxx and inserted an SVG using the developer tools, and it was sized at 16x16 pixels. I found this CSS inserted in the header:

```
svg { width: 1em; height: 1em; fill: currentColor; display: inline-block; vertical-align: middle; margin-top: -2px; }
```

1 em is 16 pixels.

Can you try temporarily use the 2020 or Storefront theme to see if the charts show correctly? If that's the case you will need to contact the theme developers for a fix.

**Comment by maximus13k** [comment]
Okay Rebecca..

I'll try to change the theme and see if the problem persists.. 

Thank you
Best Regards

**Comment by maximus13k** [comment]
Probelm solved, it is a theme issue.. when i change the theme.. the graphic displayed nicely.. thanks rebecca..

Best regards
