### ISSUE TITLE
WP Notification panel: reassessment

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3853]
It was decided to remove the WP Notification panel as for WooCommerce 4.0: #3827
At this moment the WP notifications will be automatically visible in all the non-wcadmin pages. 

We should reconsider introducing the panel, depending on how the [WP Notify project](https://make.wordpress.org/core/tag/feature-notifications/) is going to evolve

**Comment by joshuatf** [comment]
@pmcpinto Should we keep this issue open or is safe to close at this point?

**Comment by pmcpinto** [comment]
Yes. I'll close it.
