### ISSUE TITLE
Stock panel not returned to empty state after being cleared

### ISSUE THREAD

**Issue by ObliviousHarmony** [woocommerce/woocommerce-admin#3856]
**Describe the bug**
Once the user has addressed all of the stock problems, closing and opening the panel will give an empty list instead of the friendly message that you would expect.

**To Reproduce**

1. Set a product's stock to the warning threshold
2. Open the stock pane and set the stock to number that won't trigger the warning
3. Close the panel and re-open it, note that it is empty

**Expected behavior**
The empty state should be shown once all of the stock issues have been addressed.

**Screenshots**
![](https://d.pr/i/gEZZqL+)

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Chrome
* Version: 80

**Comment by psealock** [comment]
This sounds like state not being updated to `wcSettings`. If its not addressed before hand, this should be resolved in the wp.data refactor to using data stores.

**Comment by timmyc** [comment]
I can no longer reproduce this on `main`. Closing.
