### ISSUE TITLE
[4.0 rc2] WC Admin: Inbox - Add your first product

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3858]
**Describe the bug**

Currently, in WC Admin / Inbox there is a notification prompting users to create their first product when products have already been created. 

**To Reproduce**

1. On a brand new installation, I run WooCommece Core e2e tests for a smoke test to test pre-release of 4.0. E2E tests create new products on the site. 
2. Click on `Inbox` and you will see that there is a prompt to create first products but I already have products created:

![product](https://user-images.githubusercontent.com/19143190/76326617-4a1e5980-62bf-11ea-8875-3b8faf0ed97f.jpg)

**Expected behavior**

I expected not to see the prompt to create the first products because I already created them. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.3
* Browser: Chrome
* Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by pmcpinto** [comment]
I'm going to close this issue, as in the meantime that notification was already removed. Thanks
