### ISSUE TITLE
Looker dashboard: Start & Manage 

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3859]
We’re now in the position of fine-tuning the Looker dashboard for the Start & Manage focus, considering that:
- There’s was an initial spike focused on exploring Looker, where Joshua implemented an excellent dashboard
- In our roadmap, we already defined the most relevant metrics for the Start & Manage focus.

This [doc](https://docs.google.com/document/d/1ULD7t2j3chSHCAuWUV5MCONkOLyzYHGsRWRMRKiSh04/edit?usp=sharing) contains more info about the dashboard. Feel free to add any questions/feedback there.

**Comment by pmcpinto** [comment]
@joshuatf here's the issue about the Looker dashboard. I think we can use the google doc for any preliminary questions, feedback, etc.

cc @deltaWhiskey, as maybe we'll need some input/help from you :)

**Comment by joshuatf** [comment]
These are now merged on Looker.  Closing this issue.
