### ISSUE TITLE
Woocommerce Admin crashing website

### ISSUE THREAD

**Issue by snowloversglobal** [woocommerce/woocommerce-admin#3861]
Last night my website crashed. After talking to the SiteGround team it seems the woocommerce admin plugin is causing this error....

Stack trace: #0 /home/customer/www/snowloversglobal.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin') #1 /home/customer/www/snowloversglobal.com/public_html/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes.php(121): WC_Data_Store::load('admin-note') #2 /home/customer/www/snowloversglobal.com/public_html/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Deactivate_Plugin.php(59): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes_with_name('wc-admin-deacti...')

I have had to disable the plugin as it crashes the site if activated.

**Comment by jeffstieler** [comment]
Hello @snowloversglobal,

I'm currently working on a fix for the issue, but in the meantime - if you don't mind WooCommerce Admin being active on all of your sites, network activate it and the problem should be resolved.

**Comment by nsberrow** [comment]
So done with this plugin, happened again today.

**Comment by jeffstieler** [comment]
Hi @nsberrow,

Are you experiencing the exact same error as above, or a different one? If it's different, do you mind sharing the error with us so we can look for a solution?

Thank you.
