### ISSUE TITLE
Error installing woocommerce services - No Error message

### ISSUE THREAD

**Issue by anjanesh** [woocommerce/woocommerce-admin#3871]
There was an error installing woocommerce services - please try again

**Screenshots**
https://imgur.com/a/eSVpNMe

**WordPress Environment**
PHP Version 7.3.15
WordPress 5.3.2
WooCommerce 4.0.0

**Comment by NaelG** [comment]
@anjanesh (same problem)
 Have you found any solution to install woocommerce even with this error ?

**Comment by anjanesh** [comment]
@NaelG I am still waiting for a fix for the setup.

**Comment by MatteoBaioni** [comment]
I have the same problem. Were you able to solve?

**Comment by NaelG** [comment]
> I have the same problem. Were you able to solve?

Not yet on my side

**Comment by brandonkramer** [comment]
Got the same problem, only got it working by installing Jetpack and WooCommerce services by the plugin directory

**Comment by Wikisaqui** [comment]
I had the same issue, and found two possible triggers to the problem:

1. The Woocommerce services folder is already created. 
Solution: go to wp-content/plugins and delete the folder. Retry the installation.

2. For some reason sometimes, you have to install jetpack before installing woocommerce.
Solution: Activate the jetpack plugin. Retry the installation.

Hope it woeks for you gusy too!

**Comment by timmyc** [comment]
There has been considerable changes to the plugin install flow mentioned here, so I'm going to close this out as there haven't been any recent reports of problems with the WooCommerce Services install in this step.
