### ISSUE TITLE
Move plugin information and Jetpack status out of onboarding settings

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3881]
Currently the wc-api includes selectors such as `isJetpackConnected` and `getActivePlugins` that exist under onboarding.

These are selectors that may benefit a whole host of areas outside of onboarding.  While it's possible to use these selectors without onboarding being active, they have potential to throw errors with data not being preloaded.

This issue will involve:
* Moving these selectors out of onboarding since they are not onboarding specific.
* Moving the preloaded settings data out onboarding and (possibly?) always preload this data or create a flag/filter to easily do so.
* Updating all references to existing settings getters (e.g., `const { activePlugins = [] } = getSetting( 'onboarding', {} );` ) to the new namespace or (preferably) use the `getActivePlugins` selector to retrieve via the API.
* Removing preloaded settings introduced in https://github.com/woocommerce/woocommerce-admin/pull/3839

Related to shared settings: https://github.com/Automattic/woocommerce-shipping-issues/issues/28

**Comment by psealock** [comment]
It would be great to get this merged before starting on this project so refactors can happen at the same time. https://github.com/woocommerce/woocommerce-admin/pull/3313

**Comment by psealock** [comment]
@joshuatf, I'm looking into making a new data store at `/packages/data/src/plugins` and moving plugin related information out of `window.wcSettings.oboarding` and into `window.wcSettings.plugins` in case that data needs to be available on load.

This offers lots of reusability for clients, but how about the onboarding API on server? Should the new plugin data store gather data from `/onboarding/plugins` endpoint? I think to make it truly reusable, we'd need to create a plugins endpoint that onboarding can make use of. Thoughts?

**Comment by psealock** [comment]
Also, Onboarding trims the list of `activePlugins` according to `get_allowed_plugins`. I'm trying figure out the best way to handle this and it depends on the goal of moving this info out of Onboarding.

It seems to me that if a plugins data store is to be truely agnostic, then `get_allowed_plugins` will need to be done client side. Otherwise, if plugins data store is Ok with working under the guidelines of Onboarding, then we can just have it operate off of `/onboarding/plugins`.
