### ISSUE TITLE
Github releases include files that should be ignored

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3889]
Github releases include many files that should not be there.

For .org releases, it complicates the copy/paste, making the process more error prone.

For Core releases, it means users need to download unneeded files, increasing the plugin bundle size.

## Included now

![Screen Shot 2020-03-13 at 5 02 17 PM](https://user-images.githubusercontent.com/1922453/76588802-e610c500-654c-11ea-8217-3a3a9ea02c1d.png)

## What should be included

![Screen Shot 2020-03-13 at 4 57 27 PM](https://user-images.githubusercontent.com/1922453/76588815-f032c380-654c-11ea-96ff-c72c1753acf7.png)

It looks like some ignored files weren't included in https://github.com/woocommerce/woocommerce-admin/pull/3823. Perhaps this is a good case for explicitly including files instead of excluding files?

**Comment by pmcpinto** [comment]
I'm closing this one as it seems that it was fixed by #3890
