### ISSUE TITLE
Preloaded settings with a boolean don't get preloaded

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3893]
**Describe the bug**
Found when testing https://github.com/woocommerce/woocommerce-admin/pull/3796 an option that is `false` will not get preloaded since it doesn't pass the condition to check if it's set.

https://github.com/woocommerce/woocommerce-admin/blob/e3d5c325dbeb64a6c4510d240b951565f3c7ed57/client/wc-api/options/selectors.js#L35

We can do one of or both of the following:
* Change settings like `woocommerce_task_list_do_this_later` to `yes|no` settings and default to `no` instead of `false`.
* Change the condition to allow `false` values to be preloaded.

**To Reproduce**

1. Make sure the task list is enabled.
1. Make sure the option `woocommerce_task_list_do_this_later` is not in your DB.
1. Note that requests to fetch this option occur even though it's added to the preload filter.

**Expected behavior**
Expected this option to be preloaded.

**Comment by psealock** [comment]
This may be fixed by the settings refactor, which handles preload settings in new data stores.

**Comment by joshuatf** [comment]
Nice- was wondering if that may be the case.  Will put this on hold until that gets merged and we can retest then.

**Comment by psealock** [comment]
We fixed instances of this issue in OBW
