### ISSUE TITLE
Onboarding: Remove plugin installation step from profiler

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3894]
From discussion in p6riRB-5li-p2 we should remove the final plugins step from the profiler and install plugins in the background.

Following the benefits screen, the installation should then occur in the background if the user has opted into the plugin installation.

https://github.com/woocommerce/woocommerce-admin/pull/3888 will introduce inbox notices if installation fails, prompting the user to re-attempt installation.

/cc @pmcpinto if you have any additional thoughts to add to this issue.

<img width="583" alt="Screen Shot 2020-03-13 at 2 00 46 PM" src="https://user-images.githubusercontent.com/10561050/76623089-0fbcf280-6533-11ea-82c0-11e2ea599c9e.png">

**Comment by pmcpinto** [comment]
Hey @joshuatf thanks for the ping. I think you covered everything.
