### ISSUE TITLE
Tracks: review duplicated events (php and js)

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3906]

**Comment by psealock** [comment]
Hi @pmcpinto, is this an issue? Any more info?

**Comment by pmcpinto** [comment]
Hey @psealock, Timmy noticed possible duplicate tracks recorded on page views, an example is Order Listing Page. @timmyc can you provide more context on this? Thanks

**Comment by timmyc** [comment]
Doh, missed this one. iirc I wasn't able to consistently reproduce this.
