### ISSUE TITLE
Onboarding: Add event when task is completed and task list is completed

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3907]
We should record an event `wcadmin_task_completed` when a task is marked complete in the task list.  This will only be responsible for checking task completion when done in the task list and will not check if a task has been completed outside the task list.

Event name: `task_completed`
Event prop: `task name`

We should pass `completeTask()` as a prop to each task so that we can easily record this event and return to the task list so that we can remove calls like:

`getHistory().push( getNewPath( {}, '/', {} ) );`

Additionally, we should add `tasklist_completed` when a user completes all tasks.  Note that this may not always trigger since it's possible to complete the task list outside of wc-admin.

**Comment by pmcpinto** [comment]
Hey @joshuatf can we also add the one that we talked about to trigger when all the tasks are completed? It can have the following name: `wcadmin_tasklist_finished`

So it doesn't conflict with `wcadmin_tasklist_completed`

Thanks

**Comment by pmcpinto** [comment]
> Additionally, we should add tasklist_completed when a user completes all tasks. Note that this may not always trigger since it's possible to complete the task list outside of wc-admin.

We already have an event with the name `wcadmin_tasklist_completed` that's triggered when the user clicks in one of the options available to close the task list. I suggest setting the name of this new event as `wcadmin_tasklist_finished`.

Thanks
