### ISSUE TITLE
Create new feature flag for WcPay

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3946]
Child task of #3930 

In order to have the ability to toggle the WcPay appearance in the Setup Checklist across our various install points, we should create a new [Feature](https://github.com/woocommerce/woocommerce-admin/blob/master/docs/features/feature-flags.md) for this functionality in wc-admin. That way if things aren't quite ready yet for whatever reason, we can keep it turned off in builds until things are 100% ready to go.

**Comment by pmcpinto** [comment]
@timmyc can we close this one?

**Comment by timmyc** [comment]
Indeed!
