### ISSUE TITLE
Add wcpay to Payments Checklist

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3948]
Child task of #3930
Dependent upon #3946 

This task involves actually adding wcpay to the payment option to the payment step of the setup checklist:

![image](https://user-images.githubusercontent.com/22080/77107577-2608f980-69de-11ea-812c-78ad3a9dd5e2.png)

**We are currently still in the process of getting the wc-pay plugin officially posted to .org.** As such this step will need to be built in such a way that we can test with a pre-installed version of the plugin.

For this I think it would be good to base much of the [flow that we have in place for Square](https://github.com/woocommerce/woocommerce-admin/blob/master/client/dashboard/task-list/tasks/payments/square.js), since it has similar steps:

- **For US Based Stores Only That Are Jetpack Connected** ( for the time being )
- If the Feature Flag setup in #3946 is enabled....
- Display the new wc-pay banner shown in [the designs](https://www.figma.com/file/7qfNr9GA1E7yGdKnMHgrGk/Payments-onboarding-with-Jetpack-requirement?node-id=29%3A1310)
- Install and Activate the wcpay extension
- Use `WC_Payments_Account::get_connect_url()` to get the correct url to then have the user click and continue through the setup flow

- Edit (2020 Mar 20) if the user has selected the “I’m setting up this is store for someone else” option in the profiler, we’ll include another line of text in the WooCommerce > Setups > Payments card to guide them to the developer tools.

**Comment by LevinMedia** [comment]
when the merchant is returned to the payment task screen, the design of the payment option changes to match the other cards on the screen. 

<img width="709" alt="Screen Shot 2020-03-19 at 3 44 52 PM" src="https://user-images.githubusercontent.com/4500952/77121587-c2d89080-69f8-11ea-9291-cf063b478c76.png">

**Comment by timmyc** [comment]
> when the merchant is returned to the payment task screen, the design of the payment option changes to match the other cards on the screen.

But only if they have gone through the setup of WCPay correct? If they view the payment task, go eat a burrito, log back in, it should still be purple right?

**Comment by allendav** [comment]
Adding to the main description that if the user has selected that they are setting up the store for someone else, that the payment card should include a link to developer mode information for wcpay.

**Comment by joshuatf** [comment]
Currently we have a recommended ribbon for Stripe.  Will we keep this or only add the above recommended design for WCPay and remove the ribbon from Stripe?
/cc @jameskoster @LevinMedia 

![Screen Shot 2020-03-23 at 1.20.37 PM.png](https://images.zenhubusercontent.com/5d7fd4b446611c000130d6f9/5df8b9d0-b64f-42e4-9b1f-2c033468b335)

**Comment by allendav** [comment]
FYI. I intend on not showing WCPay if `hasCbdIndustry` is true

**Comment by jameskoster** [comment]
> Currently we have a recommended ribbon for Stripe. Will we keep this or only add the above recommended design for WCPay and remove the ribbon from Stripe?

We should only recommend Stripe to stores where WCPay is not available. The "Ribbon" design should match the latest design in the OP, for both methods :)

**Comment by allendav** [comment]
Closing - all done
