### ISSUE TITLE
Default theme colors in cart

### ISSUE THREAD

**Issue by ericmicali** [woocommerce/woocommerce-admin#3949]
When this plugin is activated, and using the Divi Theme, when you visit the Cart page of the website, the default theme colors show throughout the page (secondary menu, widgets, etc.).  Once I deactivated the plugin, it went back to normal.

**Comment by timmyc** [comment]
Hello @ericmicali - Could you include a screenshot of the problem, along with System Status Report from WooCommerce?

Instructions on how to do that [can be seen here](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/)

**Comment by ericmicali** [comment]
Hi @timmyc - thanks for getting back to me! It appears the issue is resolved.  Not sure if it's because of a plugin update or not, but I'm not noticing the issue anymore.  I appreciate the followup.
