### ISSUE TITLE
Copypasta in Dashboard, Task List, Square

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#3959]
**Describe the bug**

The square component references stripe settings in 4 places in square.js, e.g.:

https://github.com/woocommerce/woocommerce-admin/blob/b355b6aa5489992e2765567e2b6fbc52d754d9e6/client/dashboard/task-list/tasks/payments/square.js#L50

https://github.com/woocommerce/woocommerce-admin/blob/b355b6aa5489992e2765567e2b6fbc52d754d9e6/client/dashboard/task-list/tasks/payments/square.js#L124

**To Reproduce**

N/A

**Expected behavior**

Expected to see square settings referenced

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Comment by allendav** [comment]
Also observed in bacs, where PayFast is incorrectly included:

https://github.com/woocommerce/woocommerce-admin/blob/c5b6c7edcf1928c4bb0d5453c075da1beec2b933/client/dashboard/task-list/tasks/payments/bacs.js#L20

https://github.com/woocommerce/woocommerce-admin/blob/c5b6c7edcf1928c4bb0d5453c075da1beec2b933/client/dashboard/task-list/tasks/payments/bacs.js#L202

**Comment by timmyc** [comment]
Looks like the Square bits were fixed up https://github.com/woocommerce/woocommerce-admin/pull/4061 - have a PR open for the BACS one.
