### ISSUE TITLE
Add 'guest' as a customer type in the Order filters

### ISSUE THREAD

**Issue by bernattorras** [woocommerce/woocommerce-admin#3960]
**Context**
As explained in this [WooCommerce issue](https://github.com/woocommerce/woocommerce/issues/25992), a customer wanted to find a way to get all their "guest" orders after some of their customers got deleted by inactivity. 

In addition to this case, I think that it could also be a good thing to be able to filter in the analytics to get a better picture of the number of orders that are placed by guest customers. 

**Suggestion**
I'd add "Guest" as a new customer type in the Order filters to make shop administrators able to get the analytics of this kind of orders too. 

![https://d.pr/i/1swqBX](https://d.pr/i/1swqBX+) 
Full Size: https://d.pr/i/1swqBX

**Comment by rrennick** [comment]
@bernattorras Thanks for submitting the request. I've added this to our feature request list. If someone wanted to write this as an extension [this tutorial](https://woocommerce.wordpress.com/2020/02/20/extending-wc-admin-reports/) is a good starting point.
