### ISSUE TITLE
PHP Error in Products Screen After Update

### ISSUE THREAD

**Issue by PWDAZ** [woocommerce/woocommerce-admin#3962]
After upgrading from 3.9 to 4.01 I have the following error sitting at the top of my Products page. It's a pretty bare bones dev site and I don't have steps to recreate other than just rolling back plugins and upgrading again which I did but the error still persists.

Notice: Undefined property: stdClass::$tco-data in /home/chaseb49/public_html/examples/f4lo/wp-admin/includes/class-wp-posts-list-table.php on line 294

**Comment by rrennick** [comment]
@PWDAZ Do you have a plugin with the initials `TCO` or one where the author initials would be the same?

**Comment by PWDAZ** [comment]
No I do not. Here's all the plugins currently installed as well as where the error shows up.

![64000c477c2f0834a32813946bfd61ad](https://user-images.githubusercontent.com/17669641/77452106-cbdbb000-6db2-11ea-9270-ffe559d50638.png)

![bc06f77515709fcc84a5bdacf267230b](https://user-images.githubusercontent.com/17669641/77452239-ef065f80-6db2-11ea-96f9-c4a7d30ea7d6.png)

**Comment by PWDAZ** [comment]
The error persists after deactivating all plugins except for WooCommerce.

**Comment by rrennick** [comment]
@PWDAZ What's your theme info?

**Comment by PWDAZ** [comment]
Currently using "Pro" from theme.co. The child theme is a blank child theme for future modifications. Can confirm the error is gone when switching to "Twenty Twenty". Interesting as I have multiple other sites using Pro v3.2.3 and WooCommerce v4.0.1 and they don't appear to have the same error.

![57d1f7ba49995d0c762d66ca130970e5](https://user-images.githubusercontent.com/17669641/77466128-0c452900-6dc7-11ea-82a3-c3bd92fc187b.png)

**Comment by rrennick** [comment]
@PWDAZ Glad you found it.
