### ISSUE TITLE
Onboarding: Business details: change Google Ads title and increase logo size

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3971]
Some people can be confused with the term "Google Shopping". We should change it in the copy to "Google Ads".

Title: Drive sales with Google Ads
Plugins disclaimer: The following plugins will be installed for free: Facebook for WooCommerce, Mailchimp for WooCommerce, Google Ads

Also, the logo is super small if we compare it with Facebook and Mailchimp logos. Is it possible to increase its size?

**Comment by pmcpinto** [comment]
@timmyc  this needs to be shipped in wc-admin 1.1, as the name of the extension is Google Ads. Can you assign this one to someone? Thanks

**Comment by timmyc** [comment]
Original implementation in #3725
