### ISSUE TITLE
No effect clicking on wc-settings wc-hide-notice=update _wc_notice_nonce

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-admin#3973]
Just updated WC 3.9.3 to 4.0.1 and went fine til database updated. I got a notice in WC screens which told me that database update is finished. In notice the button "Thanks" does not work. If I click on it, a page reload is done but notice still comes up.

Any idea how to close/hide notice?

**Comment by rrennick** [comment]
@ajgw When you click the notice button are there any errors logged to your browser console?

**Comment by rrennick** [comment]
@ajgw I was able to reproduce this in my install. As a work around you should be able to go to the Plugins page and dismiss the notice there.

**Comment by ajgw** [comment]
Well @rrennick, I checked my Javascript console in Safari Browser but did not get any error. Instead after opening console and clicking on button I got a blank window with a formatted notice which told me "action failed …" (it was a message in german language). And after clicking button few times, notice is now gone. Seems there was a timer setup? Thanks.

**Comment by rrennick** [comment]
@becdetat The note action link has a nonce which expires in 12 - 24 hours. If that is expired it causes

> I got a blank window with a formatted notice which told me "action failed …"

When I got back to the dev install above, I wasn't able to reproduce the button not working (got the action failed instead). I suspect that the conditions to reproduce involve the nonce being expired. Then a sequence of navigation (eg. started update, go orders to look at what needs fulfillment, notice changes from in progress to complete).

We should look removing the nonce from the URL but that may require a second PR in WC core.

**Comment by becdetat** [comment]
I've created a PR in WC Core which seems to fix the problem: https://github.com/woocommerce/woocommerce/pull/26031

I don't see what would need to be done in wc-admin to fix this as the note is created and managed in WC core, unless I'm missing something @rrennick ...

**Comment by rrennick** [comment]
@becdetat Nice :) When you do a PR in another repo that addresses the issue you can close the one in WC Admin.

**Comment by heArt-coder** [comment]
Hi! Having the same problem.
![image](https://user-images.githubusercontent.com/2024154/77921708-c990be80-72a8-11ea-88c5-7bff81c6eb83.png)

![image](https://user-images.githubusercontent.com/2024154/77921809-e75e2380-72a8-11ea-9c43-efef37c59b81.png)

**Comment by becdetat** [comment]
Hi @heArt-coder

Thanks for reporting the issue. It should be fixed in an upcoming WooCommerce release. You can check out the fix [here](https://github.com/woocommerce/woocommerce/pull/26031) if you want.

Rebecca
