### ISSUE TITLE
Cannot receive download e-mail (e.g. stock) from WooCommerce Analytics

### ISSUE THREAD

**Issue by bobmulder** [woocommerce/woocommerce-admin#3981]
**Describe the bug**
I am thankful for this plugin, however I don't understand how the following should work. In WC Admin I can get an overview of the whole stock. Nice. When I click the 'Download' button I get a popup that I'll receive an e-mail with the download. The e-mail is never received, and I have no idea what this feature should be doing either...

**To Reproduce**

1. Go to Analytics -> Stock
2. Click on Download
3. See popup
4. Watch your inbox for a long long time :)

**Expected behavior**
I expect to receive an e-mail or a download in the browser.

**Additional context**
I am using the latest version of WC Admin

**Comment by psealock** [comment]
Hi @bobmulder, thanks for the bug report. Can you confirm the email address in your settings is set and working correctly? Cheers

**Comment by bobmulder** [comment]
Thanks for your reply, @psealock! I can confirm the e-mail address is valid in my settings! Also, FYI, I have a cron-job running every 5 minutes, so that can't be the issue either. 

If there's anything I can do, please let me know :)

**Comment by bobmulder** [comment]
Hi @psealock, were you able to reproduce this bug?

**Comment by psealock** [comment]
Hi @bobmulder I just tested the Stock report email locally as well as on a site on wordpress.com infrastructure. Both worked as they should with emails coming within a minute or so.

Are there any details about your hosting you can share? I'm also wondering if there are any conflicting plugins you may have. If you disable everything except for Woocommerce and Woocommerce-Admin (if you have it), does the problem perisist?

**Comment by bobmulder** [comment]
Thank you for reproducing @psealock! This is some sort of relief that it must be on my side ;P

I will do some checks with only woocommerce enabled. My hosting must be okay since the webshop is running for +100 customers and a lot of e-mails per day ;P

I'll get you posted!

**Comment by timmyc** [comment]
Since we haven't heard back @bobmulder - I'm going to close this out.
