### ISSUE TITLE
Update routine uses undefined constant

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#3982]
**Describe the bug**
```
CRITICAL Uncaught Error: Undefined class constant ‘QUEUE_GROUP’ in /wp-content/plugins/woocommerce/packages/woocommerce-admin/includes/wc-admin-update-functions.php:70
```

The `QUEUE_GROUP` was removed in a previous PR. This error would only occur when a site with a 0.24 or older WCA deactivated with WC4.0.X installed (or WCA 1.0.X).

**Expected behavior**
Update the function to use either the group string or pull it from the current sync code. Since this action is no longer scheduled and all existing instances of the action use the same group, the string should be fine.

**Comment by ntpixels** [comment]
also reported in a live chat; more information in 2815798-zen

**Comment by StSaens** [comment]
I created issue #502
As per your reply I installed the standalone WP-admin plugin (I tried that one many months before and quickly de-activated & uninstalled it, so it was no long installed on my site). But I am still seeing this error. What should I do?

**Comment by rrennick** [comment]
> As per your reply I installed the standalone WP-admin plugin

Which version of WooCommerce Admin did you install? This error occurs with the latest version. If that is the version you installed go to https://wordpress.org/plugins/woocommerce-admin/advanced/ and download version 0.24.1 from the Previous Versions section. Install and activate that version using the plugin uploader.

**Comment by StSaens** [comment]
I picked the latest. Your 0.24.1 is not listed.
It doesn't matter. It's my staging so I'll wait until the next official release/update and see how it fares. 

Thanks for all the work!

**Comment by rrennick** [comment]
@StSaens Sorry, should have been 0.24.0.
