### ISSUE TITLE
Dashboard reports don't load

### ISSUE THREAD

**Issue by memerson75** [woocommerce/woocommerce-admin#3989]
None of the reports screens under Analytics (e.g.: Analytics > Orders) are loading. The Analytics > Settings tab does load. The filters will show for a second, then the screen is blank with the exception of navigation links at the top. The console shows "TypeError: Cannot read property 'setProperty' of undefined"

<img width="1039" alt="Screen Shot 2020-03-24 at 21 34 32" src="https://user-images.githubusercontent.com/32335937/77492583-48a07580-6e17-11ea-981b-6115ebfceb2c.png">
<img width="1202" alt="Screen Shot 2020-03-24 at 21 36 44" src="https://user-images.githubusercontent.com/32335937/77492699-96b57900-6e17-11ea-8083-25bb642b8e5b.png">

This is on MacOS, and the same behavior and errors are seen in Chrome and Firefox. I noticed this behavior months ago, and waited, hoping a plugin update would resolve it. I just updated to Wordpress 5.3.2, WooCommerce 4.0.1 and WooCommerce Admin 1.0.3, and the issue is the same. I do not have WooCommerce Blocks installed (this was an issue for another person).

I tried disabling other plugins - no change. I tried clearing the browser cache - no change. I tried importing historical data in Analytics > Settings - no change.

**Comment by DOSEOFiNSANiTY** [comment]
Having the same problem in my post, they mentioned it possibly being something Hosting setup related. Waiting on a response back. They mentioned clearing your browser cache. Fixed for some people but I see you have already tried that... By chance, what theme are you using?

**Comment by memerson75** [comment]
Glad to hear I'm not the only one, and thanks for the comment! I'm using Woodmart theme and Siteground hosting.

**Comment by rrennick** [comment]
@memerson75 Siteground was the host where we tracked it back to the hosting.

**Comment by memerson75** [comment]
Interesting - was a fix figured out with Siteground or is it still an open issue?

**Comment by rrennick** [comment]
@memerson75 Unless the hosting company contacts us directly we are not usually involved in resolving the hosting issue.

**Comment by DOSEOFiNSANiTY** [comment]
I will contact Siteground in a moment and discuss it with one of the business profile reps. Maybe we will see something figured out here.

Thanks for providing additional info on this one @memerson75

**Comment by memerson75** [comment]
@DOSEOFiNSANiTY I reached out to Siteground today and they were not helpful. They are saying they are getting different errors on those pages than the ones I see and are giving the usual "disable other plugins" answer. I pasted the errors below, subbing in xxx for our domain. Let me know if you get any better resolution on your end. 

TypeError: &quot;this.style is undefined&quot;
    fa https://xxx.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=1.0.3:34
    each https://xxx.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=1.0.3:34
    style https://xxx.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=1.0.3:34
    Mc https://xxx.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=1.0.3:34
    value https://xxx.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=1.0.3:34
    value https://xxx.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=1.0.3:34
    value https://xxx.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=1.0.3:34
    Ti https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:148
    unstable_runWithPriority https://xxx.com/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26
    Ma https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52
    Ia https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:140
    ze https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:118
    mg https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:53
    unstable_runWithPriority https://xxx.com/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26
    Ma https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52
    mg https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52
    V https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52
    Sb https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:213
    enqueueSetState https://xxx.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:203
    setState https://xxx.com/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:21
    value https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    o https://xxx.com/wp-includes/js/dist/data.min.js?ver=4.9.2:1
    o https://xxx.com/wp-includes/js/dist/data.min.js?ver=4.9.2:1
    setState https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    setState https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    Qs https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    p https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    dataReceived https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    dataReceived https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    e https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    s https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    _invoke https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    t https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:27
    r https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:7
    i https://xxx.com/wp-content/plugins/woocommerce-admin/dist/app/index.js?ver=1.0.3:7

**Comment by DOSEOFiNSANiTY** [comment]
Good news @memerson75 !

I just heard back from my rep in the IT side and he said the following...

![Siteground](https://user-images.githubusercontent.com/35680555/77614197-fccafa80-6f02-11ea-9fa8-69c846939361.PNG)

Looks like we finally have a solution to this headache.

NOTE: I still had the issue after his message, the problem was browser cache, however using the browser tool to do it did not work for me. I had to use CCleaner to get it. Simple way to handle the problem and still retain your autofilling form data :P

**Comment by memerson75** [comment]
@DOSEOFiNSANiTY - thank goodness SOMEONE at Siteground figured it out! The combination of turning off https enforce and clearing my cache worked for me too. What a relief, and hopefully helpful to someone else.
