### ISSUE TITLE
woocommerce_admin_get_feature_config doesnt work

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce-admin#4003]
i unset activity-panels using 'woocommerce_admin_get_feature_config' hook, but the activity panels still showing in my dashboard

**Comment by becdetat** [comment]
Unfortunately the activity panels are currently shown or hidden depending on a client-side value loaded from a static JSON configuration file, which can't be changed using the hook. See https://github.com/woocommerce/woocommerce-admin/blob/0c44db342f2a1f15fde92831c25a6cbe8bdbbbfc/webpack.config.js#L204.
