### ISSUE TITLE
Admin notifications not displaying on several WooCommerce screens

### ISSUE THREAD

**Issue by jrodger** [woocommerce/woocommerce-admin#4005]
**Describe the bug**
When running WooCommerce Admin 0.26.1 admin notifications were wrapped up and accessible through the 'W' icon on screens with the nav bar. Clicking the icon revealed the messages:
![image](https://user-images.githubusercontent.com/686419/77641372-e1d4a680-6f53-11ea-8bdc-42856104ae78.png)

For the WooCommerce settings screen when running 1.0.0 and up the 'W' icon has been removed but the notifications are still hidden:
![image](https://user-images.githubusercontent.com/686419/77641489-0cbefa80-6f54-11ea-8e47-d8fba4ad4167.png)

The notifications are present in the mark-up (just hidden with CSS).

**To Reproduce**

1. Install WooCommerce Admin 0.26.1 and navigate to the WooCommerce settings screen
2. Click on the 'W' icon
3. See admin notifications
4. Install WooCommerce Admin 1.0.0 or up and navigate to the WooCommerce settings screen
5. There is no way to see the admin notifications (but you can check the page source to ensure they are being sent to the browser)

**Expected behavior**

Where the 'W' icon has been removed, admin notifications should be visible.

This looks like a side-effect of the change in https://github.com/woocommerce/woocommerce-admin/pull/3827, perhaps just affecting more screens than intended?

Interestingly, the order screen behaves fine. So perhaps this is an issue limited to the settings screen for some reason?

**Additional context**

* Browser: Chrome 80
* WC 3.9.2
* WP 5.3.2

**Comment by rrennick** [comment]
Screens affected seem to be `Reports`, `Settings`, `Status`, and `Extensions`.

**Comment by mattsherman** [comment]
`Customers` also is affected.

**Comment by mattsherman** [comment]
@timmyc @jameskoster Should the admin notices be visible on both legacy (embedded) WooCommerce pages (Orders, Products, etc.) and `woocommerce-admin` pages (Dashboard, Reports, Analytics), or just legacy pages?

**Comment by rrennick** [comment]
@mattsherman Legacy pages.

**Comment by timmyc** [comment]
Yes the current solution was to keep notices hidden on wc-admin pages: Analytics Dashboard, All items under Analytics Menu ( Reports + Settings ), and the Customers Report/Page.

Long term I feel we might need a solution to toggle them again ( @jameskoster  ) but this route was taken based upon the pattern used in Jetpack pages.

All other Woo legacy pages impacted here: Settings, Status **should show** admin alerts.

**Comment by jameskoster** [comment]
For the wc-admin screens, I'm inclined to say we should just continue to align with Jetpack, probably until the [notifications feature](https://make.wordpress.org/core/tag/feature-notifications/) is added to core.

**Comment by mattsherman** [comment]
@jameskoster I'm not terribly familiar with how Jetpack handles admin notifications. What exactly are you proposed we do with this issue? From what I have observed in Jetpack, it hides admin notifications on some screens (Dashboard, Settings, VaultPress) and shows them on others (Site Stats, Akismet Anti-Spam).

@pmcpinto @timmyc What are your thoughts on how we should handle this?

**Comment by pmcpinto** [comment]
Hey @mattsherman, I think that the idea is to display the notifications in the following screens that are not part of the new wcadmin experience: Reports, Settings, Status, and Extensions. 
All the other non-wcadmin screens already display the notifications

**Comment by mattsherman** [comment]
> Hey @mattsherman, I think that the idea is to display the notifications in the following screens that are not part of the new wcadmin experience: Reports, Settings, Status, and Extensions. 
> 
> All the other non-wcadmin screens already display the notifications

Okay, that was my original understanding and how I implemented things in #4019.

**Comment by rrennick** [comment]
> All the other non-wcadmin screens already display the notifications

@pmcpinto Some notices were also being hidden in #3964.
