### ISSUE TITLE
Improve check for isConfigured for WooCommerce Payments

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#4014]
Replace the simple plugin activation check here

https://github.com/woocommerce/woocommerce-admin/pull/3978/files#diff-9aee137ae7c9cbd12ab43fc8f26e4ebfR98

with this

https://github.com/Automattic/woocommerce-payments/issues/538

**Comment by timmyc** [comment]
@allendav should this ship in v1.1, or can it wait?

**Comment by joshuatf** [comment]
I think this issue is resolved by https://github.com/woocommerce/woocommerce-admin/pull/4145
