### ISSUE TITLE
Help meta link is not visible on Orders screen

### ISSUE THREAD

**Issue by mattsherman** [woocommerce/woocommerce-admin#4020]
**Describe the bug**

The Help meta link is not visible on the Orders screen. It briefly appears and then disappears. It is visible on other legacy/embedded screens and should be on Orders as well.

**To Reproduce**

1. Go to Orders screen
4. See Help meta link briefly appear and then disappear

**Expected behavior**

The Help meta link should be visible as it is on other embedded/legacy screens.

**Screenshots**

![Help meta link disappears on Orders screen.gif](https://images.zenhubusercontent.com/5e78cac2867c853084b981b0/529a783f-3c95-4844-a23e-29b4835c4032)

**Desktop (please complete the following information):**

* OS: macOS
* Browser Firefox
* Version 74.0

**Comment by becdetat** [comment]
@mattsherman I can't reproduce this, either in Firefox or Chrome. In your gif there is a light grey bar over the left of the content section, crossing the breadcrumbs. Could the error you found have something to do with that?

**Comment by mattsherman** [comment]
@becdetat Odd. I too can no longer reproduce this! I think the light gray bar was just an artifact of the screen recording (I didn't see this when experiencing the issue originally). Dropping this.
