### ISSUE TITLE
Replace Recommended sash with pill for WooCommerce Payments

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#4021]
And only when WooCommerce Payments is the Recommended option.

And update the card background to `$studio-woocommerce-purple-80`

<img width="563" alt="Screen Shot 2020-03-27 at 1 57 57 PM" src="https://user-images.githubusercontent.com/1595739/77799894-fb005480-7032-11ea-95d0-924c6a73581f.png">

cc @LevinMedia

**Comment by LevinMedia** [comment]
@allendav if you're going to be able to add the pill, you can keep it's background as transparent or purple to match the card background - I was only suggesting adding 1$studio-pink-50` to the sash if you couldn't implement the pill 👍
