### ISSUE TITLE
Hello!. The Dashboard of my WooCommerce generate a 503 ERROR

### ISSUE THREAD

**Issue by nicolasdelrio** [woocommerce/woocommerce-admin#4028]
Hello!,I'm creating a small store, without much data (15 products loaded so far), if I open the "Desktop" of woorcomerce, the server freezes and then I get a 503.
Has it happened to someone else?
I really am not going to use it, can it be disabled?

The wordpress version is 5.3.2 and woocommerce 4.0.1.

What files can help analysis?
Thanks!!

**Comment by becdetat** [comment]
Hi @nicolasdelrio and @RistoNiinemets,

We are currently working on some performance improvements to the dashboard that might address your issue. Eg., #4000, #4017.

Thanks for reporting the issue.

**Comment by timmyc** [comment]
I'm doing some issue cleanup and since we haven't heard back from any of the original reporters, I'm going to close this out. If you need further assistance - please do not hesitate to respond.
