### ISSUE TITLE
Woocommerce Dashboard Quarter to Date

### ISSUE THREAD

**Issue by svenauhagen** [woocommerce/woocommerce-admin#4032]
Hi,

in Woocommerce 4.0.1 when I use the Dashboard preset Quarter to Date the statistics percentage do not work and the PHP process goes to 100% CPU until the timeout is reached.

When I pick the dates manually for the quarter until today it works fine.
I attach a screenshot.

Best
Sven

<img width="1253" alt="Screenshot 2020-03-29 at 9 46 42 AM" src="https://user-images.githubusercontent.com/2235797/77843978-759bb200-71a2-11ea-9cd3-45be5ba9dfb8.png">

**Comment by becdetat** [comment]
Hi @svenauhagen @mrg-solutions @DarkAllMan @thomas-zg 

We're currently working on some performance issues around the dashboard queries, which should be resolved soon.

**Comment by timmyc** [comment]
I'm doing some issue cleanup and since we haven't heard back from any of the original reporters, I'm going to close this out. If you need further assistance - please do not hesitate to respond.
