### ISSUE TITLE
Component: EmptyCard

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#404]
[background](https://github.com/woocommerce/wc-admin/pull/365#discussion_r215695769)

As we being to build additional dashboard cards/blocks - it would make sense to have a set of components that can be used when there is no data to show for a specific stat/date range. This issue is for the creation of an `<EmptyCard />` component, which as @Aljullu pointed out:

> We might even modify the Card component to render EmptyCard when no children is passed in the props.

**Comment by psealock** [comment]
We have this now
