### ISSUE TITLE
Error with WooCommerce Admin update

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#4052]
There is a bug in the WooCommerce Admin update. 
If WooCommerce is already updated, after updating the WooCommerce Admin plugin, this warning message appears:

```
Your current version of WooCommerce Admin is outdated and a newer version is included with WooCommerce. We recommend deactivating the plugin and using the stable version included with WooCommerce.
```

And the plugin becomes deactivated.

**To Reproduce**

1. Install and activate the latest WooCommerce version and an old version of WooCommerce Admin (I used the [1.0.0](https://github.com/woocommerce/woocommerce-admin/releases/download/v1.0.0-plugin/woocommerce-admin.zip)) 
2. On the `WooCommerce`| `Dashboard` this warning will be visible: `Deactivate old WooCommerce Admin version`
3. Go to the plugins list and update `WooCommmerce Admin` to the latest version.
4. Go back to the `WooCommerce`| `Dashboard`. The warning shouldn't be visible anymore, but it is still there.
5. Go to the plugins list. The `WooCommerce Admin` plugin will now be deactivated and an error message appears :
```
The plugin woocommerce-admin-2/woocommerce-admin.php has been deactivated due to an error: Plugin file does not exist.
```

**Expected behavior**
After updating the `WooCommerce Admin` plugin, the warning message should disappear and the plugin shouldn't be deactivated.

**Screenshots**
![Screen Capture on 2020-04-03 at 11-54-25](https://user-images.githubusercontent.com/1314156/78374277-05c26880-75a2-11ea-8e23-19c0c9ce45cb.gif)

**Comment by thuautp** [comment]
I have a customer who has a similar issue with the message not going away after updating WooCommerce to 4.0.1 and they don't have WooCommerce Admin on their site.

Here's their screencast of the issue: https://monosnap.com/file/mWbJJuosUHNZSzLLQCIbpJ3Z8R6XIe

We tried to clear server cache, transient and checked wp-plugins to see WooCommerce Admin was there, but to no avail.

I also see some similar reports in the forum: https://wordpress.org/support/topic/your-current-version-of-woocommerce-admin-is-outdated-and-a-newer-version-is-inc/

**Comment by octaedro** [comment]
From what I can see, the available GitHub `WooCommerce` releases always are in `.zip` files that contain a single folder named: `woocommerce`. Inside we can find all the plugin's files.
Our releases are in `.zip` files too but with the plugin's files inside (we don't use a `woocommerce-admin` folder, we just zip the files directly).
It looks like with this structure, changing the `.zip` name will change the installed plugins folder name.
If we were to use a folder with the plugin's name inside the `.zip`, the `woocommerce-admin` folder's name in the site won't be affected if we change the `.zip` filename.

**Comment by octaedro** [comment]
Since it looks like a WP core plugin update problem, I will close this issue.
