### ISSUE TITLE
Theme selection step: missing Artisan theme image (WC-Admin 1.1 test)

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4055]
**Describe the bug**
In the Theme selection step is missing the image of the Artisan theme. See: https://d.pr/i/TpjgVJ

**To Reproduce**
1. Start the new onboarding and go to the Theme step
2. Check the Artisan theme card and see that the image is missing

**Comment by joshuatf** [comment]
The image has been added to the product data at WooCommerce.com.  The API appears to have caching in place, so I'll keep this issue open and retest when it comes through.

Note that the `wc_onboarding_themes` transient will need to be deleted as well to view the new changes.

**Comment by joshuatf** [comment]
The cache has cleared and the Artisan image is showing.  Closing this issue.

![Screen Shot 2020-05-04 at 5.07.09 PM.png](https://images.zenhubusercontent.com/5d7fd4b446611c000130d6f9/a2db8494-14dd-463c-9d82-5a57868a33ea)
