### ISSUE TITLE
Marketing tab: missing prompt to continue Google Ads setup

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4056]
**Describe the bug**
In the marketing tab is missing the prompt the finish the Google Ads setup, when the user has the plugin installed: https://d.pr/i/kZWpKZ

**To Reproduce**
1. Start the new onboarding
2. Install Google Ads in the Business details step
3. Visit the Marketing tab
4. See that's missing the prompt to continue the setup

**Comment by garymurray** [comment]
@jconroy I must have missed that is was not in when looking at the demo videos. Sorry.

It was meant to be included as per this comment: pbIy4N-B-p2#comment-12

**Comment by jconroy** [comment]
@garymurray s'all good. Ahh ok I didn't take that away from that comment and never made the connection for v1 (we  only ever investigated setup for facebook and mailchimp)

@danielbitzer we might need to divide and conquer on Monday

**Comment by jconroy** [comment]
WIP here https://github.com/woocommerce/woocommerce-admin/pull/4060
