### ISSUE TITLE
[1.1] In a multi site environment, clicking on setup menu takes me to root site instead of current site.

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce-admin#4069]
**Describe the bug**
In a multi site environment, clicking on setup menu takes me to root site instead of current site.

**To Reproduce**

1. In freshly installed site on a multi site network, go to OBW.
2. Setup link under WooCommerce menu will point root site instead of current site.

**Screenshots**

![image](https://user-images.githubusercontent.com/7571618/78696933-b66f9580-791d-11ea-835e-9f72e807cf1d.png)

**Comment by psealock** [comment]
This link is being removed in https://github.com/woocommerce/woocommerce-admin/pull/4085, which should close this issue.

**Comment by timmyc** [comment]
Indeed since 4085 has been merged and picked into the release branch I'm going to close this out.
