### ISSUE TITLE
Navigation changes

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4081]
With the implementation of the new home screen it will be necessary to implement the following changes in the navigation:

**Acceptance criteria:**
- [x] When the user clicks on "WooCommerce" it should be redirected to the new home screen
- [x] The user can also access the new home screen through a menu item called "Home" within WooCommerce
- [x] When the user clicks on "Analytics" it should be redirected to the Analytics dashboard (currently the main dashboard in WooCommerce)
- [x] The user can also access the Analytics dashboard through a menu item called "Overview" within Analytics

WooCommerce menu:
![Screenshot on 2020-04-08 at 11_03_37.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/9a5b7847-13b5-46e8-a19c-2c53a9b389b8)

Analytics menu:
![Captura de ecrã 2020-04-08, às 11.11.34.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/f57dcef4-0d2b-44ed-86f0-927100795a06)

**Comment by psealock** [comment]
It would be great to also wrap these changes in a feature flag so we can continue to develop and deploy before this feature is ready.

**Comment by psealock** [comment]
>The user can also access the Analytics dashboard through a menu item called "Dashboard" within Analytics

Just noting in the comments in pbIJXs-4Z-p2 this was changed to "Overview"

**Comment by pmcpinto** [comment]
Thanks for spotting that change, I just updated the issue description.
