### ISSUE TITLE
Quick Links (Manage your store) card 

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4082]
**User story:**
As a new merchant
I want to easily access specific areas when I finish the setup
So I can quickly fine-tune my store

![quick-links](https://user-images.githubusercontent.com/22080/79793014-bea7d780-8304-11ea-8373-6552db7ee335.png)

**Description:** we want to implement a simple way to redirect merchants to specific parts of WooCommerce after they complete or skip the store setup flow. This first version will be mainly focused on tasks for new merchants, but we think that some links can also be useful for existing users, so we'll roll it out to all the users.
In the future, we'll evaluate if we should tailor the quick links to different segments. This will depend on the adoption rate of this first version.

**Acceptance criteria:**
- [ ] When the user enters the home screen he will see the "Quick links" card
- [ ] The user can access each area by clicking on the chevron icon or in the title
- [ ] When the user clicks "Market my store" he will be redirected to WooCommerce - Marketing
- [ ] When the user clicks "Add products" he will be redirected to WooCommerce - Products
- [ ] When the user clicks "Personalize my store" he will be redirected to Appearance - Customize
- [ ] When the user clicks "Shipping settings" he will be redirected to WooCommerce - Settings - Shipping
- [ ] When the user clicks "Tax settings" he will be redirected to WooCommerce - Settings - Tax
- [ ] When the user clicks "Payment settings" he will be redirected to WooCommerce - Settings - Payments
- [ ] When the user clicks "Edit store details" he will be redirected to WooCommerce - Settings - General
- [ ] When the user clicks "View my store" he will be redirected to the site frontend

**Event tracking:**
Event name: wcadmin_home_quick_links_click
Event properties:
task_name (the name of each link that was clicked. Eg: Marketing, Add Products, etc)

**Additional links:**
P2 with final design: pbIJXs-4Z-p2
Designs https://www.figma.com/file/Z2PiNnkhjrUIiR7IrfJRnU/Home-Screen?node-id=970%3A0

**Comment by passatgt** [comment]
Is it possible to add a custom link from a plugin?

**Comment by pmcpinto** [comment]
> Is it possible to add a custom link from a plugin?

@passatgt not yet, but we plan to include it in an upcoming release. What plugin or plugins would you like to add to the "Manage your store" section?

**Comment by passatgt** [comment]
@pmcpinto I have an invoicing extension, which currently has a settings screen under WooCommerce / Settings / Integrations. Its a bit hard to find, so i wanted to include an item called "Invoice settings" or something like that as a shortcut.

**Comment by pmcpinto** [comment]
👍  Peter, thanks for your feedback!

**Comment by passatgt** [comment]
Is there any update on this? (adding custom links). Thanks!
