### ISSUE TITLE
New home screen pageview tracking

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4083]
We'll need to start tracking the number of page views on the new home screen. We also need to track is the user has Jetpack installed and/or connected, so I think that we have 2 options:

**Option 1:** 
- Adding a new value in the `path` event prop of the `wcadmin_page_view`. That value should have the following name: home_screen.
- Add three additional even props for Jetpack, same as we have in `wcadmin_task_view`: jetpack_active, jetpack_connected, jetpack_installed
I imagine that this probably would require us to check the Jetpack props in every wcadmin screen, hurting performance.

**Option 2:**
As an alternative, we can add a new event just for the home screen page views and checking Jetpack in this screen:
Event name: wcadmin_home_page_view
Event props:
jetpack_active (true/false)
jetpack_connected (true/false)
jetpack_installed (true/false)

**Comment by jeffstieler** [comment]
> Add three additional even props for Jetpack, same as we have in `wcadmin_task_view`:

@pmcpinto - should these be added to all tracks events, or just the home page?

**Comment by pmcpinto** [comment]
> @pmcpinto - should these be added to all tracks events, or just the home page?

@jeffstieler it would be enough if the event props for Jetpack are just added to the home page
