### ISSUE TITLE
[GlobalStep - 4.1 beta 1]On Business Details page, first value from drop down is highlighted by default irrespective of the selection from drop down. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4087]
**Steps to Reproduce:**
1. Create a test site using JN. 
2. Complete initial pages and go to section 4 i.e., "Business Details" page.
3. Select any value from any drop down.
4. Observe that first value from drop down is highlighted by default irrespective of the selection from drop down

**Actual Result:**
On Business Details page, first value from drop down is highlighted by default irrespective of the selection from drop down. 

**Expected Result:**
Only selected value should be highlighted.
![2  Dropdown Highlight](https://user-images.githubusercontent.com/41110392/78811166-0fefc700-79e7-11ea-9dbc-166086c45f4f.png)

**Comment by timmyc** [comment]
The highlight shown here is actually the visual indicator of which option your keyboard interaction will select if you hit `enter` - note if you use the arrow keys, the highlight will move up/down.

I'm going to close this out.
