### ISSUE TITLE
[GlobalStep - 4.1 beta 1]“Theme Installed Successfully” is displayed upon uploading theme. It should display “Theme Uploaded Successfully”.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4088]
**Steps to Reproduce:**
1. Create a test site using "https://jurassic.ninja/".
2. Complete initial pages and go to section 5 i.e., "Themes" page.
3. Scroll to the bottom of the page.
4. Click on "Upload a Theme".
5. Wait until the theme gets uploaded.
6. Observe that "Theme Installed Successfully" message is displayed.

**Actual Result:**
“Theme Installed Successfully” is displayed upon uploading theme. It should display “Theme Uploaded Successfully”.

**Expected Result:**
"Theme Uploaded Successfully" should be displayed instead of "Theme installed Successfully".
![3  Theme installed succesfully](https://user-images.githubusercontent.com/41110392/78811287-3f063880-79e7-11ea-9be5-cb07869f4553.png)

**Comment by timmyc** [comment]
I'm leaning towards closing this as while the action indeed "uploads" the theme, the ultimate/final and most important action is the theme is being installed. Thoughts @pmcpinto @jameskoster

**Comment by pmcpinto** [comment]
> I'm leaning towards closing this as while the action indeed "uploads" the theme, the ultimate/final and most important action is the theme is being installed. 

Sounds good to me
