### ISSUE TITLE
Chart: Add Ellipsis Menu Support Color Palette Support

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#409]
[inVision Design](https://automattic.invisionapp.com/d/main#/console/14672444/310038617/preview)

![image](https://user-images.githubusercontent.com/22080/45519555-714ba780-b76a-11e8-8b1d-5154bba3944d.png)

Breaking this task out of #361 to track it better. This task involves adding Ellipsis menu support to the chart header. The primary use for this now will be to toggle the color palette. I don't believe there will be any other use case ( /cc @LevinMedia to verify ).

__Questions__
- Should the color palette selection be sticky across all chart types by user?
- Or should palette selection persist on a per-chart basis?
- If indeed this is a "universal" color choice - does it make sense to display a kebab menu for it - it seems it wouldn't be used often and might be better suited for a user setting.

**Comment by justinshreve** [comment]
@LevinMedia Can you take a look at the questions here? This seems like a good candidate for another user setting since the color palate doesn't seem like an option we need to make available on every chart.

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
