### ISSUE TITLE
Inbox panel in the home screen

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4097]
**User story:**
As a merchant
I want to have access to insightful content when I enter WooCommerce
So I can create and manage my store more effectively

![image](https://user-images.githubusercontent.com/22080/79792721-3a555480-8304-11ea-8953-52fdffc1ef80.png)

**Description:** we’re going to take advantage of the inbox notifications system and try to guide the user through some of the most important tasks after they finish their store setup, motivate them through useful content and so on. The inbox panel will occupy a central place in the new home screen, allowing the user to quickly spot any new notifications. This will also introduce some dynamic to the home screen of users that don't have any sale or site visits.

**Acceptance criteria:**
- [ ] The inbox panel is going to be automatically displayed on the new home screen. This means that the inbox panel can be removed from the navbar when the user is on this screen. The new inbox panel layout is available in the Inbox notification epic.
- [ ] The user can easily identify how many new notifications exist through a counter next to the title. The timer is going to be updated every time a new notification it's displayed. 
- [ ] When the Inbox is totally “empty”, the right column will expand to fill the space.
- [ ] The inbox panel will have will “infinite scroll” as new content is delivered. The remaining cards will have a position fixed when the user is scrolling the inbox. (nice to have)

**Event tracking:**
We'll need to add a new even prop to `wcadmin_inbox_note_view` and `wcadmin_wcadmin_inbox_action_click` as a way to identify if the notification was viewed or clicked in the home screen or as a panel in another screen:
Event prop: `screen` (value: home screen, analytics_revenue, customers, etc)

**Additional links:**
P2 with final design: pbIJXs-4Z-p2
Designs: https://www.figma.com/file/Z2PiNnkhjrUIiR7IrfJRnU/Home-Screen?node-id=970%3A0

**Comment by pmcpinto** [comment]
@octaedro did you already check at how to merge the new inbox panel layout on the home screen?

**Comment by octaedro** [comment]
Hi @pmcpinto, I did a quick test and it's looking good. We will need some small modifications but it seems like it won't be anything big.
For now, I need to merge the inbox notification branch with master and after that, I will be able to continue with the integration.

**Comment by pmcpinto** [comment]
@octaedro thanks for the heads up. 

> For now, I need to merge the inbox notification branch with master and after that, I will be able to continue with the integration.

Do you have time to check this during this week? Ideally it should be ready at the beginning of the upcoming week, right on time to be merged for the WooCommerce Core 4.3 release.

**Comment by octaedro** [comment]
> Do you have time to check this during this week? Ideally it should be ready at the beginning of the upcoming week, right on time to be merged for the WooCommerce Core 4.3 release.

@pmcpinto Yes, I do. I think that it will be added on time.

**Comment by pmcpinto** [comment]
Ok thanks @octaedro
