### ISSUE TITLE
Inbox notification: layout changes

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4099]
![image](https://user-images.githubusercontent.com/22080/79793339-41309700-8305-11ea-877b-05fe4a912293.png)

Designs: https://www.figma.com/file/Pfw5Qa1UOw03RiJere3Wlo/Automattic-Components?node-id=4533%3A0

The inbox notification will remain fairly the same. It will be only necessary to implement the following changes:

- [ ] We're going to stop using icons and start using images. The images are optional and we'll only use them in some specific notifications
- [ ] Every notification will have a "Dismiss" button, allowing the user to remove the notification from their inbox. Clicking "Dismiss" will reveal a menu that prompts the user to choose whether to dismiss just this message or all messages. A dialog appears as a reminder that dismissed notifications cannot be accessed again, and a Snackbar confirms the action. We should keep the notification in the database, even if the user removes it in the frontend.
- [ ] The notification content can include links (I think this is already being covered, but I think it will be useful to have it here as remindrr to check this)
- [ ] The way to access the inbox panel in the home screen be slightly different (see #4097)
- [ ] We need to add additional even props in two events, to cover users that dismiss a notification and that view/click on them in the home screen:

`wcadmin_inbox_note_view`
New event prop: `screen` (value: home screen, analytics_revenue, customers, etc)

`wcadmin_wcadmin_inbox_action_click`*
New event prop: `screen` (value: home screen, analytics_revenue, customers, etc)
New event prop: `note_name_click` (name of the note that received a click in the main cta. eg: wc-admin-wc-helper). Instead of adding this new prop, we can also maintain the `note_name` for this
New event prop: `note_name_dismiss` (name of the note that was dismissed. eg: wc-admin-wc-helper)
New event prop: `note_name_dismiss_all` (`true` for dismiss all messages and `false` for dismiss this messages )
New event prop: `note_name_dismiss_all_confirmation` (`true` for yes I'm sure and `false` for cancel)

*: it would be great to remove the wcadmin duplication from the event name :)

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm working on this issue and I have a couple of questions about the notes:

- What should we do with the old messages that already have an icon?
- Should we show the icons as we do currently for these old notes?

Thanks!

**Comment by pmcpinto** [comment]
Hey @octaedro,

You can remove the icons on both options. 

I'm thinking that we should also have event tracking for when the user clicks in a link within the inbox message. What do you think should be the best approach?
The event tracking that I added in the AC is mainly focused on the main call to action and dismiss button.

**Comment by octaedro** [comment]
Excellent @pmcpinto, it's a good idea to add the event tracking you mentioned. I think that it's very helpful, especially to measure the conversion rate of the messages that look for an action. I will add it 🙂

**Comment by pmcpinto** [comment]
@octaedro can you outline how do you plan to implement that? Is it going to be a different event or just and event prop within `wcadmin_wcadmin_inbox_action_click`

**Comment by pmcpinto** [comment]
@octaedro, I added two additional event props, because we need to track is they choose to dismiss just one message or all the messages, after they click on dismiss, and then if they confirm this action in the modal. Let me know if it works this way or if it's better to just have a separate event.

**Comment by octaedro** [comment]
Hi @pmcpinto,
I can see a couple of options.
1. We can add a prop to `wcadmin_wcadmin_inbox_action_click`. It could have a name like `note_content_inner_link` (string). So the difference between the registries when the user presses the button or presses an inner link would be this attribute.  
2. We can create a different event with a prop for the links that are inside the inbox messages.

It looks like `option 1` would be a better solution, in order to have the data already related. Although I should study the data handling so I can give you a more accurate response.

**Comment by octaedro** [comment]
Hi @pmcpinto,
Great, I will add the additional event props.
Thank you

**Comment by pmcpinto** [comment]
@octaedro sorry for the late reply. So we'll go with option 1, correct?

> We can add a prop to wcadmin_wcadmin_inbox_action_click. It could have a name like note_content_inner_link (string). So the difference between the registries when the user presses the button or presses an inner link would be this attribute.

**Comment by octaedro** [comment]
@pmcpinto Yes, if it's ok I will go for this option.
Also, I want to ask -just to confirm- about the next step after the dismiss confirmation. A Snakbar should be visible with an `Undo` button to undo the action in both cases (for a specific message and for all), this is ok?

I'm following the flow that Jay published on [this P2](https://woostartp2.wordpress.com/2020/04/09/home-screen-mvp-i2/):

https://cldup.com/PUTihcIYWg.mp4

**Comment by pmcpinto** [comment]
@octaedro sorry for the late reply, but I was afk on Friday.

>  about the next step after the dismiss confirmation. A Snakbar should be visible with an Undo button to undo the action in both cases (for a specific message and for all), this is ok?

Yep, that's correct. We should display a snackbar to undo the action. I forgot to add that one to the acceptance criteria, nice catch. I'm going to update the issue description.

**Comment by octaedro** [comment]
Hi @pmcpinto I have a question about the event recording.

It looks like the notifications only will be visible in the `Home screen` since the icon will be removed from the navbar.
![home-screen-6](https://user-images.githubusercontent.com/1314156/81298009-8adde900-904a-11ea-81c4-9629c9c48893.png)

Do we need the prop: `screen`?

Because as I understand this will be a value that won't change since the inbox notifications only will be visible on the same screen.
But perhaps I misunderstood the design

**Comment by pmcpinto** [comment]
Hi @octaedro, the goal is to continue displaying the inbox panel as a sidebar on the other wcadmin screen.

Home screen: we hide the inbox option in the navbar and display the inbox notifications on the screen
Other wcadmin screens: we continue displaying the inbox option in the navbar and the sidebar behavior, as it happens right now. We only update the notifications' layout (including the dismiss button).

I'm sorry if this wasn't clear and let me know if you have more questions.

@jameskoster, do you have the mockup of the new notification layout in the sidebar on another wcadmin screen?

**Comment by octaedro** [comment]
Got it! No problem @pmcpinto.

I have another question: 
What do you think about adding another event prop to `wcadmin_wcadmin_inbox_action_click` with the action name?

Because now a note could have more than one action. Adding the prop `action_name` we would track the remaining user's interactions with the notes.

Would this make sense?

**Comment by pmcpinto** [comment]
Hey @octaedro, now that you mention that I think it would be more simple in terms of data analysis if we have one event for clicking in the notification and then another one for dismissing the notification:

- We would keep the existing `wcadmin_wcadmin_inbox_action_click`, keep the existing props and add a new one: `screen` (value: home screen, analytics_revenue, customers, etc)
- We would add a new event with the name `wcadmin_inbox_action_dismiss` to track when a user dismisses a notification, with the following props:
New event prop: `note_name` (name of the note that was dismissed. eg: wc-admin-wc-helper)
New event prop: `note_title` (title of the note that was dismissed)
New event prop: `note_name_dismiss_all` (true for dismiss all messages and false for dismiss this specific message)
New event prop: `note_name_dismiss_all_confirmation` (true for yes I'm sure and false for cancel)

If we keep everything under the same event it can quickly become messy. What do you think?

**Comment by octaedro** [comment]
Hi @pmcpinto sounds good to me, I like the idea 🙂

Should the prop for recording the click of a link inside of a message, named `note_content_inner_link`, go under `wcadmin_wcadmin_inbox_action_click`?

Also, forget what I said about the notes' actions, I didn't that we are recording the event on the API side.

Thank you

**Comment by pmcpinto** [comment]
> Justo confirm: the prop for recording the click of a link inside of a message, named note_content_inner_link, should go under wcadmin_wcadmin_inbox_action_click, yes?

Yes, I forgot to mention that one. Thanks for the reminder.

**Comment by octaedro** [comment]
Hi @pmcpinto, 
I was reviewing my PR code and I have a suggestion for one of the new event prop names.
Is it ok if we use `note_name_dismiss_confirmation` instead of `note_name_dismiss_all_confirmation`?
We could use this prop to register the confirmation of any of the two options. Otherwise, if we are only going to use the prop to record the `Dismiss all`, we should create a new one to record the confirmation (or cancelation) of an individual deletion.

**Comment by pmcpinto** [comment]
Hey @octaedro, that suggestion sounds good, pls move forward with that. Thanks!
