### ISSUE TITLE
OBW: "activated" success message upon continuing with existing theme

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-admin#4109]
After taking the primary "Continue with my active theme" action on the OBW theme step:

<img width="437" src="https://user-images.githubusercontent.com/1867547/78953151-ee094980-7aa5-11ea-8766-420d32c9401e.png">

…a message appears that it was "installed and activated on your site":

<img width="408" src="https://user-images.githubusercontent.com/1867547/78953219-23ae3280-7aa6-11ea-8fe2-35597dbaef34.png">

I would expect either no message or an acknowledgement that the theme was unchanged.

**Comment by timmyc** [comment]
@pmcpinto @jameskoster thoughts on this one?

**Comment by pmcpinto** [comment]
Removing the snackbar, in this case, seems to be a good option. @jameskoster @timmyc what do you think?

**Comment by jameskoster** [comment]
Yup, the snackbar should not display in this case as no process has been performed.
