### ISSUE TITLE
[WC 4.1 beta2] Set up Shipping Task: Set store location - countries in the dropdown list are in pink

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4110]
**Describe the bug**

Set up Shipping Task: Set store location - countries in the dropdown list are in pink.

**To Reproduce**

I can't always reproduce the behavior where the first step of `Set up shipping` task is not passed by default. Most of the time it does and you actually don't see the `Set store location` section. But when you do see it and have to fill out the details, the list of countries in the dropdown is in pink color when it should be black:

![pink](https://user-images.githubusercontent.com/19143190/79002700-04072080-7b1f-11ea-912a-b7195cd50aa7.jpg)

**Expected behavior**

The color of the countries in the dropdown should be black, not pink. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.4
* Browser: Chrome
* Version: 80.0.3987.163 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by jeffstieler** [comment]
This no longer occurs, closing.
