### ISSUE TITLE
CANNOT DISMISS NOTISE

### ISSUE THREAD

**Issue by wwmummygrab** [woocommerce/woocommerce-admin#4113]
**Screenshots** CANNOT DISMISS IT AFTER UPDATE IS DONE

**W
![WX2](https://user-images.githubusercontent.com/58280248/78961017-76c5cb00-7b22-11ea-861b-359d0eab17bf.png)
![WX](https://user-images.githubusercontent.com/58280248/78961028-804f3300-7b22-11ea-95c1-4d833403c655.png)

**Comment by timmyc** [comment]
@wwmummygrab apologies for this bug. We have a fix in progress for this, but I'm going to close this issue in favor of the original report #3497

If you would like, I've also created a quick plugin that will set the DB notice as "actioned" and remove it from your Woo pages.

The plugin can be found here: https://gist.github.com/timmyc/ee0c6f4cb3ed82620efaa16386e62c6b

You could copy that into any other plugin/functions file as well, but once it has run one time, you can disable/remove the code.

**Comment by wwmummygrab** [comment]
This is reply from my IT team :.

done. no effect.
i actually asked in forum previously and checked db
https://wordpress.org/support/topic/version-4-0-1-woocommerce-database-update-required-loop/
