### ISSUE TITLE
Customers, add telephone

### ISSUE THREAD

**Issue by eshimischi** [woocommerce/woocommerce-admin#4121]
<img width="1521" alt="Screenshot 2020-04-14 at 09 01 46" src="https://user-images.githubusercontent.com/983201/79191383-1b9c1d00-7e2f-11ea-98b3-e56884049977.png">

Any ways to add phone number for customers? And chance to download it in a report too. Thanks!

**Comment by timmyc** [comment]
@eshimischi we offer the ability to extend the new analytics reports like the customers report. But we currently do not have plans to add additional fields to this report.

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
