### ISSUE TITLE
WooCommerce Payments treated as active when navigating back to the site without completing the stripe KYC flow

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#4122]
**Describe the bug**
If you start the Stripe KYC flow, then using the back button to return to the payments task list, WooCommerce Payments is treated as active.

**To Reproduce**

1. Ensure your test site has a US address and Jetpack conected
2. From the payments task list screen, click "Setup" on the WooCommerce Payments card
3. Note you're directed to the KYC flow hosted on stripes server. 
4. Click the back button in the browser to return to the payments task list.
5. Note that WooCommerce payments is now treated as active.

**Screenshot**

<img width="1314" alt="Screen Shot 2020-04-14 at 9 10 29 AM" src="https://user-images.githubusercontent.com/4500952/79248598-df69bc00-7e30-11ea-8b80-e42038b7a495.png">

**Expected behavior**
The user should see the WooCommerce Payments card with the recommended styling, including the setup link to Stripe's KYC flow.

**Comment by timmyc** [comment]
@allendav is there a method that can be called in WC Pay that we can use to signal that WC Pay has been fully setup? We could then use that to determine if this setup is complete or not in the context of the setup checklist.

@LevinMedia - wondering what your thoughts are here from a design standpoint. So if someone has WC Pay installed + activated and not configured, what should we display?

**Comment by LevinMedia** [comment]
>not configured

@timmyc Configured, meaning they have a wp.com account, their site is connected to the wp.com servers, and they've completed the stripe KYC flow - if those conditions aren't all met, then it should always show the recommended purple card in the task list: 

<img width="740" alt="Screen Shot 2020-04-15 at 1 24 13 PM" src="https://user-images.githubusercontent.com/4500952/79384819-6b0c4700-7f1c-11ea-9187-117c0bf9be66.png">
