### ISSUE TITLE
[4.1 beta2]: Include filter to be able to disable the marketing menu item

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce-admin#4124]
Will there be a filter included in WooCommerce 4.1 to be able to disable the marketing menu item?

**Comment by timmyc** [comment]
Thanks for the request @lukecav - looping in the team that is working on that feature for thoughts @garymurray @jconroy

**Comment by jconroy** [comment]
Thanks @timmyc - at the moment there is a filter in place that [can be used to remove the marketing menu item/s](https://gist.github.com/jconroy/e21c146aefa4301397b65d430f80dc05) but we could add something more specific - thoughts @garymurray ?

**Comment by garymurray** [comment]
As mentioned in the [post on the WooCommerce Developer blog](https://woocommerce.wordpress.com/2020/03/31/coming-soon-woocommerce-marketing-hub/) - we will continue to iterate and add new features here.

Next up we are looking to consolidate coupons into the marketing hub so disabling it will not really be in the best interests of merchants.

**Comment by lukecav** [comment]
Any reason why coupons would be moved into the marketing hub out from the WooCommerce menu item?

**Comment by garymurray** [comment]
> Any reason why coupons would be moved into the marketing hub out from the WooCommerce menu item?

To consolidate all marketing related activities in one central place.

**Comment by lukecav** [comment]
In that case will orders move out from WooCommerce menu to their own menu item then?

**Comment by garymurray** [comment]
> In that case will orders move out from WooCommerce menu to their own menu item then?

@lukecav No there is no current plan to move orders into their own menu item.
