### ISSUE TITLE
Option to disable Dashboard for WooCommerce (Analytics)

### ISSUE THREAD

**Issue by DestructiveBurn** [woocommerce/woocommerce-admin#4125]
**Feature request related to a problem**
Hello, the latest versions of WooCommerce 4.0 / 4.0.1+ have introduced the new WooCommerce Admin / New Reports and Notification bar.  The problem is, it extremely resource-heavy and causes I/O Usage & Physical Memory Usage to run at max if you click anything in WooCommerce plugin.  This causes my site to go down.

**The Solution**
Add a feature button to disable these new features.
This will let us continue to use WooCommerce without it killing our processes and taking our site offline.

**Alternative**
The only option right now for smaller sites is to stay on WooCommerce Version 3.9.2 (which I am) or use a third-party plugin that does just that for now.  [https://wordpress.org/plugins/disable-dashboard-for-woocommerce/](url)

**Additional context**
It's just way too bloated with these features.  I personally have no use for them and I'm not the only person this is effecting.  I'm sure there are plenty of people and 12+ more here as well [https://wordpress.org/plugins/disable-dashboard-for-woocommerce/#reviews](url)

The solution,  If someone wants to use it, enable the features, if not keep it disabled.  Please don't ignore this.  It's causing a lot of problems for me and others.  WooCommerce Version 3.9.2 was the last known version that is not resource-heavy.

Thanks for reading.

**Comment by DestructiveBurn** [comment]
Ok, thanks @juliaamosova

**Comment by timmyc** [comment]
as @lukecav [pointed out above](https://github.com/woocommerce/woocommerce-admin/issues/4125#issuecomment-613680715) the filter is the option we are offering right now to disable the analytics functionality. 

As to the concerns around performance, we have a number of fixes coming out in the 1.1 release of woocommerce admin, and those will be bundled in WooCommerce 4.1 as well. 

> Hopefully, they add the option in the setting.

We have discussed this idea too, but have opted not to implement at this time. But thanks for the feedback on having a physical setting to control the Analytics feature ( cc @pmcpinto )

I'm going to close out this issue now with the filter that is available being the fix. If someone needs further help implementing this filter, please let us know.

**Comment by DestructiveBurn** [comment]
@timmyc 
> We have discussed this idea too, but have opted not to implement at this time. But thanks for the feedback on having a physical setting to control the Analytics feature ( cc @pmcpinto )

You're offering the filter to disable the analytics functionality to run in a custom snippet plugin (which has been done here already: ([https://github.com/woocommerce/woocommerce-admin/issues/url]) as an external option but won't build it into the settings to disable it?
I don't see the logic in that at all.

I bet it wouldn't take long at all just to create some checkbox that triggered `add_filter( 'woocommerce_admin_disabled', '__return_true' );` to disable it.  How long will this filter exist till you fade it out before it will no longer work?  Will we have a disabled button in the settings by then?

> As to the concerns around performance, we have a number of fixes coming out in the 1.1 release of woocommerce admin, and those will be bundled in WooCommerce 4.1 as well.
Hopefully, this will help out.  As for now.  It's extremely bad and completely unusable in smaller shops.  I can't even try it out without it running my I/O to the max, it's that bad.

My apologies if I sound a bit rude.  I'm not trying to be.  I'm just curious and a bit concerned about the future of WooCommerce if there will be no way to disable this in the future if it continues to run my site into the ground.
