### ISSUE TITLE
[WC 4.1 - beta.2] Move `Upload a theme` option to the top of the page for greater exposure

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4134]
Filing this issue on behalf of @denho. Reference: pb22l9-8V-p2#comment-387. 

**Is your feature request related to a problem? Please describe.**

Move `Upload a theme` option to the top of the page for greater exposure. Upload a theme option in Theme step is very useful. However, it felt like it lacks exposure as it is located at the very bottom of the themes list. User may not notice it at all unless scrolls down quite a lot:

![exceptional-hydrozoan jurassic ninja_wp-admin_admin php_page=wc-admin step=theme](https://user-images.githubusercontent.com/19143190/79356238-b159aa00-7f0c-11ea-8be0-069d2e7233c3.png)

**Describe the solution you'd like**

Move the `Upload a theme` option closer to the top of the page so that it could not be missed by the user. 

**Describe alternatives you've considered**

N/A

**Should this be prioritized? Why?**

I think it should so that users could use all the features that the new OBW provides. 

**Additional context**

N/A.

**Comment by timmyc** [comment]
I appreciate the feedback on this. I feel like this idea was discussed during the initial developer or has been mentioned by other testers before. I personally kind of feel this feature might not get used that much, but would be interested to see how it is performing in tracks @pmcpinto

**Comment by pmcpinto** [comment]
Thanks for the suggestion. Only ~2% of users are using that feature and we have ~90ish% conv. rate in the theme step. I feel that at this moment we don't have enough demand to revisit the layout in order to highlight the upload option. Also, it's preferable to display first the themes that we know for sure that will work well with WooCommerce.

**Comment by timmyc** [comment]
Thanks for the data check-in Pedro, going to close this out.
