### ISSUE TITLE
[WC 4.1 beta.2] Shipping set up Task: let users review store location

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4135]
Filing this issue on behalf of @denho. Reference: pb22l9-8V-p2#comment-387.

**Is your feature request related to a problem? Please describe.**

Shipping set up Task: let users review store location. On a Set up shipping task page it felt like it lacks an option to review and edit the previously submitted address:

![address](https://user-images.githubusercontent.com/19143190/79356823-57a5af80-7f0d-11ea-97aa-f7db049e43d6.png)

**Describe the solution you'd like**

Let users review the store location details before proceeding. 

**Describe alternatives you've considered**

N/A. 

**Should this be prioritized? Why?**

Not super urgent IMO. Rather a nice to have. 

**Additional context**

N/A.

**Comment by pmcpinto** [comment]
I'm going to close this issue as currently we allow the user to review their address within the task: https://d.pr/i/7fLFvN
