### ISSUE TITLE
Strings in wc-admin/setup wizard are not translating with MO file

### ISSUE THREAD

**Issue by arcangelini** [woocommerce/woocommerce-admin#4146]
**Describe the bug**
String translations are not working in the Setup Wizard. After installing the MO file in `wp-content/languages/woocommerce` the language file does not appear to apply to any of the setup process.

The strings are in the PO file from what I have searched. But are not being used. This is not isolated to one language. I tested multiple languages and on a couple different test sites.

**To Reproduce**

1. Download the MO file from [translate.wordpress.com](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/es/default/)
2. Install the file into `wp-content/languages/woocommerce`
3. Change language from WP-ADMIN ⇢ Settings ⇢ General
4. Go to WooCommerce and enable the setup wizard. The string translations appear for all of WooCommerce it seems except the Setup wizard.

**Expected behavior**
Setup-wizard should be translated as the rest of WooCommerce is using the MO file.

**Screenshots**
All of the following strings in these screenshot exist in the PO file I downloaded from [translate.wordpress.com](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/es/default/)

[![Screenshot](https://d.pr/i/mhp8TM+)](https://d.pr/i/mhp8TM)
[![Screenshot](https://d.pr/i/JRgC62+)](https://d.pr/i/JRgC62)
[![Screenshot](https://d.pr/i/MfVu4N+)](https://d.pr/i/MfVu4N)
[![Screenshot](https://d.pr/i/JRMFhf+)](https://d.pr/i/JRMFhf)
[![Screenshot](https://d.pr/i/nF0rp9+)](https://d.pr/i/nF0rp9)

**Additional context**

**Comment by rrennick** [comment]
@arcangelini Most of the strings in the setup wizard are in the `woocommerce-{locale}-{MD5-hash}.json` files. If you install a localized version of the WC Admin plugin you should have translated strings in the wizard.

The root issue is how the source translation file was being compiled in WC 4.0. The PR to address this is https://github.com/woocommerce/woocommerce/pull/25984 .
