### ISSUE TITLE
Pre-commit hook deletes changes on failure

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4151]
**Describe the bug**
When creating a commit, if the pre-commit hook fails, it's wiping out changes and work may be lost.

**To Reproduce**

1. Make some file changes.
1. Create a phpcs error (not sure if this also happens with JS linting).
1. Commit changes.
1. Note that file changes are gone.

**Expected behavior**
Expected to not lose all changes on commit failure.

**Comment by joshuatf** [comment]
@becdetat I'm now having a hard time recreating this on `master`.  Can you check and see if this still an issue in your environment?

**Comment by jeffstieler** [comment]
@becdetat can you provide any more specific instructions to reproduce this? E.g. - are multiple files needed to be changed and staged? Mix between PHP and JS? Which files should we expect to see lost?

**Comment by becdetat** [comment]
It was still happening for me, on the same commit that affected me yesterday, and on the next commit. The only thing I can think of is that my previous commit was amended. I checked out a new copy of the repo, applied my patch, and it works now.

I was getting this output, which seems to point to an error restoring the stash, which the pre-commit hook does. I couldn't find my changes in the stash, although that may have been due to still having changes in the working directory.

```
  ↓ Applying modifications... [skipped]
    → Skipped because of errors from tasks.
  ✖ Reverting to original state because of errors...
    → error: could not restore untracked files from stash
  ↓ Cleaning up... [skipped]
    → Skipped because of previous git error.

  ✖ lint-staged failed due to a git error.
  Any lost modifications can be restored from a git stash:

    > git stash list
    stash@{0}: On master: automatic lint-staged backup
    > git stash pop stash@{0}

[....]

 error: could not restore untracked files from stash
```

**Comment by jeffstieler** [comment]
> The only thing I can think of is that my previous commit was amended.

Interesting. Had the amended commit been pushed yet? Was the "next commit" also modifying the same file in the amended commit?

**Comment by jeffstieler** [comment]
Hmm, actually I think this is the key to the problem:

> error: could not restore untracked files from stash

Are you losing a new file that hasn't been added to the repo yet?

**Comment by becdetat** [comment]
>  Had the amended commit been pushed yet? 

Yes

> Was the "next commit" also modifying the same file in the amended commit?

Yes, it was modifying a few files

> Are you losing a new file that hasn't been added to the repo yet?

No, I was losing all staged files, none of them new.

**Comment by psealock** [comment]
We fixed this one
