### ISSUE TITLE
Changes in inbox message: marketing message

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4156]
We need to implement some changes in this inbox message:

**Timing:** it should be triggered right when the user activates the WC plugin (previously it was being triggered 2-3 after store creation)

**Message content:** We're here for you - get tips, product updates and inspiration straight to your email box

The rest stays the same.

**Comment by timmyc** [comment]
The particular note in question is [WC_Admin_Notes_Onboarding_Email_Marketing](https://github.com/woocommerce/woocommerce-admin/blob/master/src/Notes/WC_Admin_Notes_Onboarding_Email_Marketing.php)
