### ISSUE TITLE
[WC 4.1 beta.2] Make it more clear visually that the first 2 fields of `Tell us about your business` section are required

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4161]
Created this issue on behalf of Austin L.: Ref: Ref: pb22l9-8V-p2#comment-395. 

**Is your feature request related to a problem? Please describe.**

One idea for the design of the `Tell us about your business` step, it would be nice to have some sort of visual queue or even explicit messaging on the page for required elements. IIRC, `What's your current annual revenue?` only appears as you’re filling out the above questions. But visually when I see the product suggesting MailChimp, Google Ads, etc., that visually tells me to go past where the magic just populated those plugins. So I sat there for a good minute waiting for the `Continue` button to darken so I could click it. Then I realized it must be because I had left the revenue blank but that could be confusing.

**Describe the solution you'd like**

Mark first 2 fields as required in order to visually make it more clear as they are needed to be filled out before being able to continue. 

**Describe alternatives you've considered**

N/A. 

**Should this be prioritized? Why?**

**Additional context**

N/A.

**Comment by timmyc** [comment]
@jameskoster just flagging for you to see if you think we should take any action here or not.

**Comment by jameskoster** [comment]
Hmm, I'm not sure what the actual problem is here. I'm wondering if those fields have changed since this issue was opened, because currently it is not possible to leave them empty. They're both populated with a default option. Ergo there's no need to mark them as required.

**Comment by becdetat** [comment]
On a fresh store those fields aren't automatically populated and the Continue button isn't enabled, although it doesn't appear to be disabled:

![image](https://user-images.githubusercontent.com/224531/102292197-68bd2980-3f90-11eb-83af-10d8811909fd.png)

I think this is still a valid ticket.

**Comment by joelclimbsthings** [comment]
Closing this as we prepare for the merge, as it's been around for almost 2 years.
