### ISSUE TITLE
Add new event prop to wcadmin_wcadmin_tasklist_payment_choose_method

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4165]
We should add an event property to identify if the user created a Paypal account. Similar to what we have for the Stripe account creation

create_paypal_account: true/false

**Comment by becdetat** [comment]
@pmcpinto Are you sure that the `wcadmin_wcadmin_tasklist_payment_choose_method` event name is correct? I can't find it anywhere.

**Comment by pmcpinto** [comment]
Maybe they were removed by mistake during the latest changes in the payments step. cc @joshuatf

**Comment by pmcpinto** [comment]
Hey @becdetat, this event was replaced by `wcadmin_tasklist_payment_setup`. I'm going to close this issue
