### ISSUE TITLE
Create a WC Admin Note remover from DB

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#4168]
We need to delete all the inbox messages from the database that we don't want to use anymore.
We will have a list of _note names_ to delete and they will be removed from the database with a cron task.

**Comment by mattsherman** [comment]
The in-progress PR addressing #4153, #4154, and #4155 will remove those specific notes from the DB.

**Comment by mattsherman** [comment]
PR that removes specific notes is available: #4182

@octaedro @timmyc It is not clear to me why a cron would be needed. If this is in support for some other note removal needs, let me know. (Please comment on #4182 if it is related to the three notes that PR addresses.)

**Comment by mattsherman** [comment]
Dropping this one -- not needed at this point in time. Can be revisited in the future if we need a cron to perform periodic cleanup of notes.
