### ISSUE TITLE
Table cells should be left-aligned by default

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4175]
**Describe the bug**
In the `Table` component, cells are right-aligned by default to match the wc-admin UI styling.  However, this is specific to our report tables and may not match expectations for other packages importing a `Table` component.

* Left-align all columns by defaults.
* Right-align numbers and dates by default, unless it's a first column cell.
* Add an `isCenterAligned` option.

See p1587540899281400-slack-team-isotope for details

**To Reproduce**

1. View any report.
1. Note right-aligned columns unless the `isLeftAligned` prop is passed.

**Expected behavior**
Expected cells to be left-aligned by default, but styled to be right-aligned in wc-admin

**Screenshots**
<img width="886" alt="Screen Shot 2020-04-22 at 3 03 48 PM" src="https://user-images.githubusercontent.com/10561050/79979633-7d512c80-84aa-11ea-96bd-39548fc92333.png">

**Comment by naman03malhotra** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce-admin/pull/7431
