### ISSUE TITLE
Change Inbox message: Giving feedback

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4178]
We'll need to change the content, trigger and cadence this message (#1982) as a way to focus on the experience of new users.

**Title:** Give feedback
**Content:** Now that you’ve chosen us as a partner, our goal is to make sure we’re providing the right tools to meet your needs. We're looking forward to having your feedback on the store setup experience so we can improve it in the future.
**CTA leads to:** https://automattic.survey.fm/new-onboarding-survey
**CTA label:** Share feedback
**Timing:** 8 days after WooCommerce activation
**Cadence:** Once

**Comment by becdetat** [comment]
This message was removed in #4182, should this issue be closed @pmcpinto ?

**Comment by pmcpinto** [comment]
Hey @becdetat, this message should be implemented as it's going to replace the one that was removed. Thanks

**Comment by becdetat** [comment]
Ok, no worries
