### ISSUE TITLE
Stats API returns null for the date_start field

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-admin#4181]
Ref p90Yrv-1G7-p2#comment-3856

## Is your feature request related to a problem? Please describe.

The WooCommerce iOS app sometimes fails to load the site stats because the API returns a `null` value for the `date_start`. 

The issue seems to be related to DST. 

## Steps to reproduce

To reproduce (WC 4.1.0-beta.1):

1. Set the site timezone to UTC-6 (Edmonton time zone)
2. Create some orders on March 8, 2020 between 2AM and 3AM. March 8 is when Calgary’s DST starts.
3. Run this API request: `GET /rest/v1.1/jetpack-blogs/SITE_ID/rest-api/?json=true&path=/wc-analytics/reports/revenue/stats%26_method%3Dget%26after%3D2020-03-08T00%3A00%3A00%26before%3D2020-03-08T23%3A59%3A59%26interval%3Dhour%26per_page%3D58`

Here is a sample API request and response showing the `date_start` as `null`: https://paw.pt/e1REDJnW

## Describe the solution you'd like

Ideally, the `date_start` should not return `null` at all. 

## Describe alternatives you've considered

n/a

## Should this be prioritized? Why?

I believe this bug will happen again on the next DST date. 

## Additional context

n/a

**Comment by joelclimbsthings** [comment]
Closing this as it's close to 2 years old.
