### ISSUE TITLE
Autofill fills in wrong Country in OBW

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#4183]
**Describe the bug**
I have a couple of test addresses stored in Chrome to fill in fields on sites as checkout etc and the OBW gets it mostly right, but the country is wrong each time:

![Screenshot 2020-04-23 at 14 56 08](https://user-images.githubusercontent.com/2207451/80102081-98876f00-8572-11ea-896e-53c0cc25735e.png)
![Screenshot 2020-04-23 at 14 55 07](https://user-images.githubusercontent.com/2207451/80102083-99200580-8572-11ea-972d-2486f110f918.png)

**To Reproduce**

1. Install WC 4.1 rc.1 (but also stable one)
2. Start OBW
3. Try to use saved address from the browser

**Expected behavior**
See the correct country chosen, if possible.

**Desktop (please complete the following information):**

* OS: latest Mojave
* Browser Chrome
* Version 81.0.4044.113

**Comment by timmyc** [comment]
This feels a bit like an edge case to me, and since we haven't had any other reports, I'm going to close this as a won't fix.
