### ISSUE TITLE
Task List - Shipping and Tax tasks: store location

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4186]
**Describe the bug**
In previous versions the store location was automatically being confirmed in the Shipping and Tax tasks (if the user filled that info in the Store Profiler). Now, the user always needs to confirm the location in both steps, even if they already confirmed it before.
Shipping: https://d.pr/i/hUC4Hl
Tax: https://d.pr/i/YunpaJ

**To Reproduce**

1. Install woocommerce-4.1.0-rc.1
2. Complete the Store Details step in the Store Profiler
3. Visit the Shipping task and see that you need to confirm the store location
4. Then visit the Tax task and see that you need to confirm again the store location

**Comment by becdetat** [comment]
@pmcpinto This was done as part of a fix of a bug where the steps would double-skip. However the non-skipping of the address step was seen as an improvement by Julia (it felt like a bug that the address would be skipped). Can you check on what the desired behaviour is?

**Comment by pmcpinto** [comment]
Hey @becdetat thanks for providing more context. I think that it can be a bit tiresome for the user to confirm the location two times after providing it in the profiler. @jameskoster what do you think?

**Comment by jameskoster** [comment]
Yeah, no need to make users confirm information multiple times.

In the future we should probably work towards simply hiding the address step if it has already been set.
