### ISSUE TITLE
[GlobalStep - 4.1 RC]: "The response is not a valid JSON response" error message is displayed while uploading zip file in Themes

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4188]
Steps to Reproduce:
1. Create a test site using JN. 
2. Complete initial screens.
3. On theme screen try to upload business-street.1.2.4.zip or manasa.1.0.2.zip or punte.1.0.0.zip or pushan.1.0.0.zip.
4. Click on upload button.
5. Observe that "The response is not a valid JSON response" error message is displayed.

Actual Result:
"The response is not a valid JSON response" error message is displayed while uploading zip file in Themes.

Expected Result:
Theme should be uploaded and should be visible

![#26](https://user-images.githubusercontent.com/41110392/80130808-cee6dd80-85b6-11ea-957f-051b39c8ad45.jpg)

**Comment by juliaamosova** [comment]
Noting here that I am able to upload a theme Elizama that I downloaded from WordPress.org theme directory. Tested using WC 4.1 rc.2:

![Screen Shot 2020-04-29 at 4 34 12 PM](https://user-images.githubusercontent.com/19143190/80645407-10eda480-8a39-11ea-9424-79dac72acf9e.png)

**Comment by gglobalstep** [comment]
This issue is observed to be "**Open**" on WooCommerce - 4.2 Beta.

**Environment:**
**MAC Mojave v10.14.6:**
Safari(v13.0.5)
**Windows 10:**
Chrome(Version 81.0.4044.138 (64-bit))

**Comment by gglobalstep** [comment]
This issue is observed to be **Open** on WooCommerce 4.2 RC 1
**Environment:**
Windows
OS: 10
Browser: Chrome(Version 81.0.4044.138 (64-bit))

MAC
OS: Mojave v10.14.6
Browser: Safari(v13.0.5)

**Comment by gglobalstep** [comment]
This issue is observed to be **"Fixed"** on WooCommerce 4.3 Beta.

**Environment:**
**Windows 10**
Browser: Chrome(Version 83.0.4103.61)(64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)
**MacBook Pro Version 10.15.5 (19F101)**
Browser: Safari(Version 13.1.1)(15609.2.9.1.2)
