### ISSUE TITLE
[GlobalStep - 4.1 RC]: "Folder already present" error message is displayed while uploading theme.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4190]
Steps to Reproduce:
1. Create a test site using JN. 
2. Complete initial screens.
3. On theme screen try to upload business-street.1.2.4.zip or manasa.1.0.2.zip or punte.1.0.0.zip or pushan.1.0.0.zip.
4. Click on upload button.
5. Note that "The response is not a valid JSON response" error message is displayed.
6. Observe that "Folder already present" error message is displayed.

Note: User is unable to see uploaded folder.

Actual Result:
"Folder already present" error message is displayed while uploading theme.

Expected Result:
Theme should be uploaded and should be visible

**Comment by juliaamosova** [comment]
Adding one more testing report where the theme upload couldn't be completed by @andrewjkerr: pb22l9-8V-p2#comment-397. 

Quoting:

>For technical information, I am on MacOS 10.15.3 using Firefox 74.0 (using Burp Suite as a web proxy) for the first setup and then Chrome 81.0.4044.92 for the CBD store & subsequent test steps.

>First theme upload seemed to silently fail for me and then consistently failed

>I tried to upload the “Minamaze Emagazine” theme (it was the first one on the list :p) but I guess it failed to upload the first time and, every subsequent upload failed with this “Destination folder already exists.” error message. I tried a few times but I just kind of gave up after the fourth time.

![theme](https://user-images.githubusercontent.com/19143190/80526367-9ea99100-8960-11ea-8716-be00d3f7977c.png)

**Comment by gglobalstep** [comment]
This issue is observed to be "**Open**" on WooCommerce - 4.2 Beta.

**Environment:**
**MAC Mojave v10.14.6:**
Safari(v13.0.5)
**Windows 10:**
Chrome(Version 81.0.4044.138 (64-bit))

**Comment by gglobalstep** [comment]
This issue is observed to be **Open** on WooCommerce 4.2 RC 1
**Environment:**
Windows
OS: 10
Browser: Chrome(Version 81.0.4044.138 (64-bit))

MAC
OS: Mojave v10.14.6
Browser: Safari(v13.0.5)

**Comment by gglobalstep** [comment]
This issue is observed to be **"Fixed"** on WooCommerce 4.3 Beta.

**Environment:**
**Windows 10**
Browser: Chrome(Version 83.0.4103.61)(64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)
**MacBook Pro Version 10.15.5 (19F101)**
Browser: Safari(Version 13.1.1)(15609.2.9.1.2)

**Comment by timmyc** [comment]
Thanks for the update of this being fixed @gglobalstep
