### ISSUE TITLE
[GlobalStep - 4.1 RC]: “Page not found error 404” message is displayed for HubSpot for WooCommerce. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4192]
Steps to Reproduce:
1. Create a test site using JN. 
2. Complete initial screens.
3. On Dashboard click on "Marketing".
4. Click on "HubSpot for WooCommerce".
5. Observe that “Page not found error 404” message is displayed 

Actual Result:
“Page not found error 404” message is displayed for HubSpot for WooCommerce. 

Expected Result:
User should redirect to HubSpot for WooCommerce.

![#29](https://user-images.githubusercontent.com/41110392/80131011-3309a180-85b7-11ea-87e0-4fe07fc0a8f6.jpg)

**Comment by juliaamosova** [comment]
I experienced the same when testing on Jurassic Ninja multisite setup:

![hub](https://user-images.githubusercontent.com/19143190/80148305-d7252580-8582-11ea-94de-7ab34df2c538.jpg)

**Comment by gglobalstep** [comment]
Unable to check this issue on WooCommerce 4.2 Beta as in Marketing "Recommendation Extensions" fails to show "HubSpot for WooCommerce"

**Environment:**
**MAC Mojave v10.14.6:**
Safari(v13.0.5)
**Windows 10:**
Chrome(Version 81.0.4044.138 (64-bit))

**Comment by gglobalstep** [comment]
Unable to check this issue on WooCommerce 4.2 RC1 as in Marketing "Recommendation Extensions" fails to show "HubSpot for WooCommerce"

**Environment:**
MAC Mojave v10.14.6:
Safari(v13.0.5)
Windows 10:
Chrome(Version 81.0.4044.138 (64-bit))

**Comment by pmcpinto** [comment]
cc @garymurray @JPry

**Comment by jconroy** [comment]
HubSpot was [still marked as a private product](https://github.com/woocommerce/woocommerce-admin/issues/4159#issuecomment-616811348) during 4.1 and then later removed because before release it wasn't available.

It's only getting added back in this week.

**Comment by gglobalstep** [comment]
This issue is observed to be **"Fixed"** on WooCommerce 4.3 Beta.

**Environment:**
**Windows 10**
Browser: Chrome(Version 83.0.4103.61)(64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)
**MacBook Pro Version 10.15.5 (19F101)**
Browser: Safari(Version 13.1.1)(15609.2.9.1.2)
