### ISSUE TITLE
Navigation: Add navigation styling and menu item state

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4202]
This task will involve styling the currently unstyled navigation to match the new menu style as well as making sure basic menu item states, like hover, open submenus, and active menu items, exist.

Detecting active pages can probably be handled or modified from those used in wc-admin to set the active page for analytics pages.

* Sanitizing menu titles (see "Accounts Privacy" html entities)
* Default styling
* Hover styling
* Submenu open/closed
* Menu active

See p1586439404181400-slack-woo-start-manage for more discussion on submenu interaction.

### Curent
<img width="310" alt="Screen Shot 2020-04-24 at 3 55 09 PM" src="https://user-images.githubusercontent.com/10561050/80214804-1bc4c580-8644-11ea-9d77-81488e21aa52.png">

### Updated
<img width="614" alt="Screen Shot 2020-04-24 at 4 09 01 PM" src="https://user-images.githubusercontent.com/10561050/80216034-19636b00-8646-11ea-8102-eba9adfb3cd6.png">

**Comment by joshuatf** [comment]
@jameskoster Can you confirm the styling we'll use for this iteration or if it's the one depicted in the screenshot above?

**Comment by jameskoster** [comment]
@joshuatf you can find all the details of the new menu item components [here](https://www.figma.com/file/Pfw5Qa1UOw03RiJere3Wlo/Automattic-Components?node-id=5978%3A24478). Most of the styling should come from the core components we're using to create the menu items.

FYI the behaviour when opening the sub menus is still in flux a little - we might use drawers (like the screenshot above), but we're also exploring panels (a la the Customizer).

**Comment by psealock** [comment]
Issue moved to [woocommerce/navigation #5](https://github.com/woocommerce/navigation/issues/5) via [**ZenHub**](https://www.zenhub.com/)

**Comment by psealock** [comment]
Issue moved to [woocommerce/navigation #6](https://github.com/woocommerce/navigation/issues/6) via [**ZenHub**](https://www.zenhub.com/)
