### ISSUE TITLE
Navigation: Add non-core menu items

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4203]
The navigation will require manual opt-in from each plugin to the new menu.  This will be a gradual process, but in this task we will add menu items for:

* Analytics (wc-admin repo)
* Marketing (wc-admin repo)

<img width="153" alt="Screen Shot 2020-04-24 at 4 17 07 PM" src="https://user-images.githubusercontent.com/10561050/80216649-1026ce00-8647-11ea-9047-66e35707ff39.png">

See the Figma "Navigation" project for more details.

**Comment by psealock** [comment]
Issue moved to [woocommerce/navigation #3](https://github.com/woocommerce/navigation/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by psealock** [comment]
Issue moved to [woocommerce/navigation #4](https://github.com/woocommerce/navigation/issues/4) via [**ZenHub**](https://www.zenhub.com/)
