### ISSUE TITLE
Navigation: Migrate remaining menu items from WP menu

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4204]
Items underneath the original WP menu item "WooCommerce" should all be removed and migrated to the new menu.  The default category in the menu will be under the new "Setting" category if not specified.

We also need to make the sure the remaining "WooCommerce" item goes to the dashboard and shows the new menu.  This will probably be handled by Analytics settings migration in https://github.com/woocommerce/woocommerce-admin/issues/4203.

* Items not yet moved under that were previously under the original WooCommerce menu item can be migrated to the new "Settings" category.
* Update the  "WooCommerce" menu item to a single item that enters the new wc-nav experience.

<img width="237" alt="Screen Shot 2020-04-24 at 4 06 40 PM" src="https://user-images.githubusercontent.com/10561050/80215736-9c37f600-8645-11ea-831c-e7a979dbc58e.png">
<img width="458" alt="Screen Shot 2020-04-24 at 4 06 32 PM" src="https://user-images.githubusercontent.com/10561050/80215744-9f32e680-8645-11ea-9e1d-67314da9b401.png">

**Comment by psealock** [comment]
Issue moved to [woocommerce/navigation #9](https://github.com/woocommerce/navigation/issues/9) via [**ZenHub**](https://www.zenhub.com/)
