### ISSUE TITLE
Navigation: Registering post types

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4205]
The navigation project currently handles menu items and detects if we're on a WooCommerce screen by checking the screen ID.  This works well for registered pages with callbacks, but works a bit differently for post types.

In order for post types to work, we'll need to create a `Navigation::register_post_type()` method so we can detect if we're on a post type screen matching a post type.  Once this method is added, we can register:
* `shop_order`
* `product`
* `shop_coupon`

I think much like WP core's `register_post_type` function, there should be an option as to whether or not this should be included in the menu (see [show_in_menu](https://developer.wordpress.org/reference/functions/register_post_type/)).

@rrennick Did some great initial work on this [here](https://github.com/woocommerce/woocommerce-admin/blob/e6d4632eda55d04e272b663a8ad8c65dbe3dfeab/src/Features/Navigation.php#L160) that can be used to check the post type.

**Comment by psealock** [comment]
Issue moved to [woocommerce/navigation #8](https://github.com/woocommerce/navigation/issues/8) via [**ZenHub**](https://www.zenhub.com/)
