### ISSUE TITLE
Navigation: Separate tools, extensions, and settings menu

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4207]
As part of the design for the navigation, the "Settings," "Tools," and "Extensions" menu category items are separated from other menu items and towards the bottom of the navigation.

This task will involve:
* Creating a new method to register these items OR modifying the existing methods to allow this.
* Styling the navigation section to match this piece of the design.

<img width="300" alt="Screen Shot 2020-04-24 at 4 35 38 PM" src="https://user-images.githubusercontent.com/10561050/80218277-a5c35d00-8649-11ea-9e8b-cdefbb9fe033.png">

**Comment by psealock** [comment]
Issue moved to [woocommerce/navigation #7](https://github.com/woocommerce/navigation/issues/7) via [**ZenHub**](https://www.zenhub.com/)
