### ISSUE TITLE
New notification: Customize your online store with WooCommerce blocks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4212]
**Title:** Customize your online store with WooCommerce blocks
**Content:**  With our blocks, you can select and display products, categories, filters, and more virtually anywhere on your site — no need to use shortcodes or edit lines of code. Learn more about how to use each one of them.
**Segmentation:** 
New users with `setup_client`: `false` on `wcadmin_storeprofiler_store_details_continue`
AND that triggered 
`wcadmin_product_add_publish` or `wcadmin_product_import_complete`
**Timing:** 14 days after registration
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/posts/how-to-customize-your-online-store-with-woocommerce-blocks/?utm_source=inbox
**CTA label:** Learn more

**Comment by pmcpinto** [comment]
> I understand that this notification should be shown when the client has products, is this ok?

Yep, that's correct. This also needs to be taken into consideration: New users with setup_client: false on wcadmin_storeprofiler_store_details_continue

Thanks

**Comment by pmcpinto** [comment]
Hey @octaedro. This was shipped in 1.4, correct?

**Comment by octaedro** [comment]
Hi @pmcpinto,
I can't see that the [PR related to this issue](https://github.com/woocommerce/woocommerce-admin/pull/4616) has been shipped yet.

/cc: @timmyc

**Comment by timmyc** [comment]
@pmcpinto yes the notif was shipped in 1.4: https://github.com/woocommerce/woocommerce-admin/blob/release/1.4.0/src/Notes/WC_Admin_Notes_Customize_Store_With_Blocks.php
