### ISSUE TITLE
Enqueue js.stripe.com script in wcpay onboarding views

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#4216]
We are contractually obligated, as a fraud detection technique, to enqueue Stripe JS for WCPay onboarding related content.

**Comment by allendav** [comment]
We need to, however, not do so until merchants are given an opportunity to review our TOS.

**Comment by timmyc** [comment]
@allendav based upon your convo on the payments issue - looks like we would need to have the asset loaded *only* on the Dashboard page where the setup task list appears.

**Comment by timmyc** [comment]
@allendav Just seeing if this issue is still needed.

**Comment by becdetat** [comment]
@allendav Is this still needed, or can this issue be closed?

**Comment by allendav** [comment]
Yup - and as Timmy says - on the pages where the setup wcpay task appears

**Comment by moon0326** [comment]
I'm closing this as this has been stale and it looks like the requested feature has been merged in https://github.com/Automattic/woocommerce-payments/pull/617

Please feel free to re-open it if needed.
