### ISSUE TITLE
Access to Analytics for a user role restricted by the attribute

### ISSUE THREAD

**Issue by miketermos** [woocommerce/woocommerce-admin#4220]
Greetings,

I'm curious to give open report for certain users only for certain brands.
The brand is an attribute for certain SKU's. But I don't want to show the report for all items.

So when I assign specific user to this role he'll get to see the admin area only with Analytics enabled and a view based on aforementioned restrictions.

Please advise on how to implement this.

Thanks,
Mike

**Comment by timmyc** [comment]
@miketermos - the new analytics features require a user to have the "Shop Manager" role. If you are going to implement your own report, you would have full control over which permissions are required. I would say if you are going to utilize/extend any REST API analytics endpoints, keep in mind those endpoints are restricted to the shop manager role as well.

Beyond that, this repository is for tracking bugs/features for the "core" functionality of WooCommerce and the Analytics section, and we can't really provide in-depth code examples of how to implement bespoke reports.
