### ISSUE TITLE
New inbox notification: Your first product

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4223]
**Title:** 💪Your first product
**Content:**  That’s huge! You’re well on your way to building a successful online store — now it’s time to think about how you’ll fulfill your orders.
Read our shipping guide to learn best practices and options for putting together your shipping strategy. And for WooCommerce stores in the United States, you can print discounted shipping labels via USPS with [WooCommerce Shipping](https://href.li/?https://woocommerce.com/shipping).
**Segmentation:** New users
**Timing:** Trigger `wcadmin_product_add_publish` or `wcadmin_product_import_complete` (only physical products)
**Cadence:** once
**CTA leads to:** https://woocommerce.com/posts/abcs-shipping-fulfillment-need-consider/?utm_source=inbox
**CTA label:** Learn more

**Note:** this one should be added using the remote system (#4101)

**Comment by jeffstieler** [comment]
@pmcpinto @becdetat 

While testing this in https://github.com/woocommerce/woocommerce-admin/pull/4260 I realized that we aren't checking the product type.

As it currently sits, we'll show this inbox note even if the product is virtual/downloadable, and not a physical (shippable) item.

**Comment by pmcpinto** [comment]
@becdetat @jeffstieler thanks for the heads up. Is there a way to easily get that info when they publish the product or is it better to just use as filter the information that they share in the store profiler as the product type? Probably it won't be as accurate but it's better than not having a filter at all.

**Comment by mattsherman** [comment]
@becdetat I assigned you to this one, since based on the comments in here it sounds like you are already addressing this in 9bc9c06.

**Comment by becdetat** [comment]
Thanks @mattsherman, it should be addressed in #4260 however remote inbox notifications is also feature toggled off and this would need the `https://woocommerce.com/wp-json/wccom//inbox-notifications/1.0/notifications.json` present with the correct spec before this notification would be displayed.

**Comment by becdetat** [comment]
@pmcpinto:

> Is there a way to easily get that info when they publish the product or is it better to just use as filter the information that they share in the store profiler as the product type?

With the way I've set up the remote notifications it's not easy to get that info, however it is easy to get the store profile information.

**Comment by pmcpinto** [comment]
> With the way I've set up the remote notifications it's not easy to get the product type, however it is easy to get the store profile information.

Ok so let's go with the ones that selected `Physical` as `product_type` in the `wcadmin_storeprofiler_store_product_type_continue` event. It should cover any value that includes physical. Eg: `physical, downloads`. Thanks
