### ISSUE TITLE
New inbox notification: Get real time order alerts anywhere

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4225]
**Title:** Get real-time order alerts anywhere
**Content:**  Get notifications about store activity, including new orders and product reviews directly on your mobile devices with the Woo app
**Segmentation:** Existing users
**Timing:** 3 months after they created store (if they haven't downloaded the app)
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/mobile/?utm_source=inbox
**CTA label:** Learn more

**Note:** this one can be implemented by the mobile team

**Comment by timmyc** [comment]
@pmcpinto - how do we know if a site has downloaded the mobile app? @astralbodies do you happen to know if a site option or something similar gets set that we can check to see if the mobile app is already in use?

**Comment by pmcpinto** [comment]
> how do we know if a site has downloaded the mobile app?

Good question 😄 we could filter out the users that clicked in the notification that we display during the first days.

**Comment by joshuatf** [comment]
@pmcpinto So if they actioned the "Install Woo mobile app" note, we don't display this note, correct?

This is a good idea and will filter out a decent amount.  There's still always the possibility that the mobile app was downloaded and is being used anyway, but if we're okay with this overlap then I think checking against the mobile note action should be trivial.

**Comment by pmcpinto** [comment]
> @pmcpinto So if they actioned the "Install Woo mobile app" note, we don't display this note, correct?

Yep, that's correct. It won't be 100% accurate in terms of segmentation but it seems to be the easiest solution
