### ISSUE TITLE
New inbox notification: Edit products on the move

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4228]
**Title:** Edit products on the move
**Content:**  Edit and create new products from your mobile devices with the Woo app
**Segmentation:** Existing users
**Timing:** 1 year after they created store (if they haven't downloaded the app)
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/mobile/?utm_source=inbox
**CTA label:** Learn more

**Note:** this one can be implemented by the mobile team

**Comment by timmyc** [comment]
This is blocked too by the problem I [mentioned here](https://github.com/woocommerce/woocommerce-admin/issues/4227#issuecomment-657696088)

**Comment by becdetat** [comment]
As @pmcpinto [noted](https://github.com/woocommerce/woocommerce-admin/issues/4227#issuecomment-657699216) in #4227 I'm going to use the solution in #4541 - don't add the note if the Install Woo mobile app action] has been selected.
