### ISSUE TITLE
QUERY: Extension example "table-column" How to enable toggle?

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce-admin#4236]
In the extension example "table-column" two new columns "ID" and "Rating" are added. The two new columns show in the toggle bar, but when trying to toggle they switch back to "ON"

Desired behaviour: Ability to toggle the new columns to "OFF"

Query: What code is needed to enable toggling for the new columns?

Screenshot: https://www.dropbox.com/s/utxzh6igeidymj4/2020-04-28-table-column-toggle.png?dl=0

**Comment by EdithAllison** [comment]
I've retested this, and cannot replicate the error, toggle is now working for me correctly. I'm therefore closing this issue.

**Comment by EdithAllison** [comment]
Further tests show that toggle works fine in "Orders" report; but does not work in "Products" report. 

Screenshot shows attempt at toggling in "Products". Toggling the standard column "Status" works fine; but toggling custom column "Landed Cost" does not work. 

I'm stuck at getting this to work. Is this a bug or am I missing something in my code? 

![2020-05-20 15 51 42](https://user-images.githubusercontent.com/19706428/82454774-78d06180-9ab2-11ea-8249-4234403039f0.gif)

**Comment by rrennick** [comment]
@EdithAllison We've added this to our list to look at. If you could leave the issue open, that would be great.

**Comment by jeffstieler** [comment]
Thanks for the report @EdithAllison! We have a PR to fix: https://github.com/woocommerce/woocommerce-admin/pull/4964
