### ISSUE TITLE
`Create a custom homepage` is not complete/misleading 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4239]
**Is your feature request related to a problem? Please describe.**

Filing this on behalf of @andrewjkerr: pb22l9-8V-p2#comment-397.

Quoting:

>Clicking on the “Create a custom homepage” button doesn’t seem to do what I expected.

>When I clicked on “Create a custom homepage”, I expected there to be some additional prompts to, well, create my customized homepage. Instead, it just went to the next step so I found it a little bit confusing. 😅

![homepage](https://user-images.githubusercontent.com/19143190/80530579-39a56980-8967-11ea-82a0-25381b256be8.png)

I personally agree with it and had a similar experience when first tried it. 

**Describe the solution you'd like**

Maybe we can point the users where they can further customize their site after that page was created. 

**Describe alternatives you've considered**

The alternative would be to have users actually customize their homepage and perhaps be redirected to the customizer. 

**Should this be prioritized? Why?**

It is not a super high priority but it feels like this step is a bit redundant at the moment. It is hard to tell what will happen if you don't create a homepage and what happens when you do from the new user point of view. 

**Additional context**

N/A.

**Comment by pmcpinto** [comment]
cc @elizaan36 this issue covers some of the problems with the existing Customize Appearance task.

**Comment by elizaan36** [comment]
thanks for the ping @pmcpinto! I'll keep this in mind for the next round of updates that are more focused on the "Personalize your store" task.
