### ISSUE TITLE
The ‘toast’ messages showing up at the bottom of the screen after completing a setup step seem very disconnected

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4240]
**Is your feature request related to a problem? Please describe.**

Filing this on behalf of @andrewjkerr: pb22l9-8V-p2#comment-397.

Quoting:

>The ‘toast’ messages showing up at the bottom of the screen after completing a setup step seem very disconnected

>For example, when completing the “shipping” setup flow, these were the toasts that were shown that I actually completed it. 

>The fact that these were shown at the bottom of the window with all of this blank space made them pretty easy to miss.

![toast](https://user-images.githubusercontent.com/19143190/80532102-a15cb400-8969-11ea-8a5c-398ecd689c56.png)

I personally can't agree more with this. I find that when they appear, it is no immediately clear that they are related to what the user just did. Then after you realize they do, you have an urge to read it but they disappear too soon. 

**Describe the solution you'd like**

As an idea, they can be moved to the top of the page. 

**Describe alternatives you've considered**

They can be displayed via pop-up window with an action button such as `Ok` or something along those lines so the user could actually get a chance to read them. 

**Should this be prioritized? Why?**

Not the most important issue to work on but will be nice to have. 

**Additional context**

N/A.

**Comment by timmyc** [comment]
This is working as designed so closing out, but tagging @jameskoster for the general design feedback.

**Comment by jameskoster** [comment]
Just to clarify - we're following the example set by the block editor which places them at the bottom of the screen. Bottom left actually - we should probably update the position of our snackbars, and ensure we're using the [core component](https://wordpress.github.io/gutenberg/?path=/story/components-snackbar--default), if we aren't already.

I would agree this is a low priority change.
