### ISSUE TITLE
WooCommerce is giving me a fatal error

### ISSUE THREAD

**Issue by GodscreationLLC** [woocommerce/woocommerce-admin#4243]
**Describe the bug**
When I went to re-active my WooCommerce it gave me this error:
Plugin could not be activated because it triggered a fatal error.
Warning: require(/var/www/wp-content/plugins/woocommerce/src/Autoloader.php): failed to open stream: No such file or directory in /var/www/wp-content/plugins/woocommerce/woocommerce.php on line 31

**To Reproduce**

1. Go to '...' to my wordpresss hosting site to my site at godscreationll.com
2. Click on '....'I clicked on plugins
3. Scroll down to '....' I scrolled down to WooCommerce
I clicked on Active WooCommerce 
4. See error It gave me this error: Plugin could not be activated because it triggered a fatal error.

**Expected behavior**
I expected my plugin to be re-actived so i could add to my store

**Screenshots**
![image](https://user-images.githubusercontent.com/64504091/80544159-04ecde80-8976-11ea-883f-c67d9a0d79e4.png)

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by timmyc** [comment]
@GodscreationLLC sorry you are having this issue, and thanks for the detailed report. By chance do you recall if you had recently updated Woo, and if so which version? Also did the update happen via an auto-update?

At first glance, this looks like an incomplete version of the plugin being installed. If possible I'd try to upload a clean copy of the plugin.

**Comment by timmyc** [comment]
Since we haven't heard back from you @GodscreationLLC - I'm going to close this issue out.
