### ISSUE TITLE
Incorrect recommended treatment for WooCommerce Payments

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#4249]
**Describe the bug**
WooCommerce payments is missing the "Recommended" treatment in the payments task list

**To Reproduce**
1. Ensure jetpack is connected and the store based in the US.
2. Navigate to the payments task in the onboarding task list

**Expected behavior**
1. WooCommerce Payments should be noted as "recommended" and the setup button should use the primary action styles (pink) 
2. Stripe should no longer be noted as "Recommended" 

**Screenshots**

Observed:
<img width="1789" alt="Screen Shot 2020-04-28 at 9 12 05 PM" src="https://user-images.githubusercontent.com/4500952/80561540-ab96a680-8999-11ea-9d7f-10954739d4bd.png">

Expected:
<img width="825" alt="Screen Shot 2020-04-28 at 9 47 42 PM" src="https://user-images.githubusercontent.com/4500952/80561621-e993ca80-8999-11ea-96c2-76eb32eaff18.png">

the colors of the default buttons can be ignored in the second screen shot - it assumes https://github.com/woocommerce/woocommerce-admin/issues/3897 has been merged.

**Comment by joshuatf** [comment]
Hey @LevinMedia - I think I received the correct design when attempting to recreate this:

<img width="732" alt="Screen Shot 2020-04-29 at 6 55 21 PM" src="https://user-images.githubusercontent.com/10561050/80617677-1227cd00-8a4b-11ea-87e2-d11b6b011a9b.png">

Does that look right to you?  If so, can you double check on `master` to see if you still see this?

**Comment by timmyc** [comment]
Just verified this is working okay in RC2, so going to close this out. @LevinMedia if you are able to reproduce this again, could you reopen this and let us know steps on how to hit the bug? Thanks!

JN, 4.1 RC2:

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/22080/80988758-caa59600-8de8-11ea-8182-fcda8b01c551.png">

**Comment by dechov** [comment]
@LevinMedia has continued to report this with the 4.2 release, but it's not clear how many others, if any, could be encountering this.

Despite our inability to reproduce it, @DanReyLop was able to pinpoint the potential for this issue in the source (i.e. `isJetpackConnected` resolving late) and [offer a fix](https://github.com/woocommerce/woocommerce-admin/compare/fix/task-list-wcpay-recommended) – I think we can leave this open until that's addressed.

**Comment by timmyc** [comment]
That seems like a reasonable fix @dechov @DanReyLop - should we open up a PR with that change?

**Comment by joshuatf** [comment]
While I'm not opposed to a solution that checks in `componentDidUpdate`, `isJetpackConnected` should be a preloaded setting so it should not be resolving late.

**Comment by timmyc** [comment]
> While I'm not opposed to a solution that checks in componentDidUpdate, isJetpackConnected should be a preloaded setting so it should not be resolving late.

I feel like this is kind of a nod to why David might be hitting this bug as opposed to others - depending on the testing flow on a new site, I could see that perhaps if you go straight from connecting Jetpack on a new site, directly to the payments task, you would be more likely to hit the bug state seen here. If you perhaps went to a few other steps in the checklist first, then it is much less likely to be hit.

**Comment by DanReyLop** [comment]
> isJetpackConnected should be a preloaded setting so it should not be resolving late.

Yeah, I looked at the code and I can't for the life of me figure out why it's happening or how to reproduce... but I have a video of @LevinMedia reproducing that behaviour. So it wasn't a one-time fluke.

> depending on the testing flow on a new site, I could see that perhaps if you go straight from connecting Jetpack on a new site, directly to the payments task, you would be more likely to hit the bug state seen here.

In the video I watched, David had Jetpack already activated & connected, **then** he went to the Onboarding Wizard, and then he was dropped into the task list. So it's not like he connected Jetpack as part of the OBW or anything like that. I'm so so confused.

> should we open up a PR with that change?

Sure, I'll open a PR, if we're ok with the fact that we don't know why this bug is happening :)

**Comment by DanReyLop** [comment]
> I have a video of @LevinMedia reproducing that behaviour. So it wasn't a one-time fluke.

To be clear, the video shows how the payments screen loads with Stripe as the preferred method and no WCPay, and then like 1 second later the WCPay card shows (but Stripe is already "locked in" as the `recommendedMethod`). That's why I think that having to check for the Jetpack status with an AJAX request is somehow involved.

**Comment by DanReyLop** [comment]
Opened https://github.com/woocommerce/woocommerce-admin/pull/4345
