### ISSUE TITLE
Orphaned rows when manual SQL queries are run

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4250]
**Describe the bug**
There are cases when store owners or plugins will manually run SQL queries to remove old orders/products/etc.

When this happens, we can recommend that they resync under Analytics->Settings, unchecking the "Skip previously imported" option.  We'll need to make sure we delete old rows when this happens.

In an ideal world, we can just delete items that aren't in the new ones being imported, but based on the asynchronous nature of action scheduler imports, we may just want to wipe all the tables when importing again if the "Skip" button is unchecked.

See p1587965557275100-woo-start-manage-slack for more details.

**To Reproduce**

1. Delete an order from the `wp_posts` table directly.
1. Sync the wc-admin tables.
1. Note the old order still exists.

**Expected behavior**
Expected some way to delete old rows when a row is deleted manually.

**Screenshots**
<img width="567" alt="Screen Shot 2020-04-29 at 6 44 47 PM" src="https://user-images.githubusercontent.com/10561050/80616722-e9530800-8a49-11ea-8426-2216531a386d.png">

**Comment by rrennick** [comment]
Why not start with the delete previous if the `Skip previous` is unchecked?

<img width="346" alt="Screen Shot 2020-04-29 at 1 46 11 PM" src="https://user-images.githubusercontent.com/343847/80622958-e9d6a900-8a1f-11ea-942a-6e2b2e377ba1.png">
