### ISSUE TITLE
Too many actions being scheduled

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#4255]
**Describe the bug**
Originally reported in https://github.com/woocommerce/action-scheduler/issues/517. I was logged into customer site today that had this issue. The AS actions were all WC (upgrade tasks) or Historical Import. In the space of 5-10 minutes several hundred delete import batch actions were created.

Site orders:
<img width="82" alt="Screen Shot 2020-04-29 at 3 51 40 PM" src="https://user-images.githubusercontent.com/343847/80636459-e4835980-8a33-11ea-8541-28d306b6f97d.png">

Delete customer batch action creation should have stopped before this:
<img width="1053" alt="Screen Shot 2020-04-29 at 3 51 21 PM" src="https://user-images.githubusercontent.com/343847/80636489-f533cf80-8a33-11ea-86e9-c34238f4df7a.png">

**To Reproduce**

Requires investigation

**Comment by abhishek-pokhriyal** [comment]
Hello there,

Any chance a similar was reported with Follow-Up Emails? Our WooCommerce store is having an issue where the Follow-Ups actions (that too `complete` actions) increase at an abnormal rate. I ran the following query to find out if there are duplicate action for the same follow-up email

```sql
SELECT args,
       count(*)
FROM wp_actionscheduler_actions
WHERE hook = 'sfn_followup_emails'
  AND status = 'complete'
GROUP BY args
ORDER BY count(*) DESC; 
```

and to my surprise, I found this

![image](https://user-images.githubusercontent.com/11808845/82708905-0a9bc280-9c9d-11ea-85b2-d618e30580d5.png)

And that too when I deleted all the completed follow up actions a few hours.
