### ISSUE TITLE
Set up shipping task: `Country / Region` select options are not left aligned

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4271]
**Describe the bug**

Filing this on behalf of @Aljullu. Reference: pb22l9-8V-p2#comment-398.

In shipping task - The `Country / Region` select options are centered while in the setup wizard they were left-aligned. 

Setup Wizard (Store location section):

![Screen Shot 2020-05-01 at 12 22 59 PM](https://user-images.githubusercontent.com/19143190/80821369-92167a00-8ba6-11ea-9a47-b208eb54c063.png)

Shipping Task:

![Screen Shot 2020-05-01 at 12 09 06 PM](https://user-images.githubusercontent.com/19143190/80821275-65626280-8ba6-11ea-9b26-dc90874e9050.png)

**Comment by mattsherman** [comment]
Closing this -- no longer an issue.
