### ISSUE TITLE
Set up payments task: when introducing the email, pressing the `Enter` key doesn’t do anything

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4272]
**Is your feature request related to a problem? Please describe.**

Filing this on behalf of @Aljullu. Reference: pb22l9-8V-p2#comment-398.

Noticed it after installing Stripe, but it might affect other sections as well. When introducing the email, pressing the Enter key doesn’t do anything. For better accessibility, I think it should send the form:

![stripe](https://user-images.githubusercontent.com/19143190/80823074-e53dfc00-8ba9-11ea-9199-a7c6d0e3cc5a.png)

**Describe the solution you'd like**

Complete the step when hitting `Enter`. 

**Describe alternatives you've considered**

N/A. 

**Should this be prioritized? Why?**

Not a high priority IMO. 

**Additional context**

N/A.

**Comment by timmyc** [comment]
Since this part of the Stripe setup flow has been deprecated, I'm going to close this out since it is no longer valid.

**Comment by juliaamosova** [comment]
Makes sense, thanks @timmyc!
