### ISSUE TITLE
WooCommerce / Customers: add tooltip to `AOV` explaining what it means

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4273]
**Is your feature request related to a problem? Please describe.**

Filing this on behalf of @Aljullu. Reference: pb22l9-8V-p2#comment-398.

WooCommerce / Customers: add tooltip to `AOV` explaining what it means as it is not immediately clear at the moment:

![aov](https://user-images.githubusercontent.com/19143190/80832642-06f3af00-8bbb-11ea-81a2-2115303153c5.jpg)

**Describe the solution you'd like**

Question mark icon next to `AOV` that will reveal the meaning of the abbreviation when hovering over it. 

**Describe alternatives you've considered**

N/A. 

**Should this be prioritized? Why?**

It will be nice to implement sooner than later. 

**Additional context**

N/A.

**Comment by timmyc** [comment]
We do spell out what it means in the docs ( https://docs.woocommerce.com/document/woocommerce-analytics/#section-28 ), not sure if we want to introduce tool tips on reports or not and given we haven't had any other feedback about this I'm inclined to close this out with votes needed for now.

**Comment by juliaamosova** [comment]
Sounds good, thanks @timmyc! Good to know we have it in the docs.
