### ISSUE TITLE
[WC 4.1 RC.2] Issues with WooCommerce Services logic for countries other than the US

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4276]
**Describe the bug**

Props to @dougaitken for spotting this issue. Reference: pb22l9-8V-p2#comment-400. 

We are offering WooCommerce Services that supposed to activate automated tax calculations and shipping labels printing to shops that are not located in the US (and, therefore, can't use WooCommerce Services). 

I tested with a store based in the UK and in Russia using real addresses.

<hr>

**UK:** 

First of all, I was not offered CBD option - which is expected and correct:

![Screen Shot 2020-05-01 at 4 03 28 PM](https://user-images.githubusercontent.com/19143190/80841739-0e708380-8bce-11ea-9552-87f0359a8c33.png)

But I was offered WooCommerce Services:

![Screen Shot 2020-05-01 at 4 04 51 PM](https://user-images.githubusercontent.com/19143190/80841773-247e4400-8bce-11ea-99bc-2748e95e25ab.png)

**Why this is a problem?** 

Taxes:

While automated tax option works in the UK, we still recommend customers installing the `EU VAT Number` extension for more accuracy. See [our docs](https://docs.woocommerce.com/document/woocommerce-services/#section-10). So the customer is missing on the experience here as there is no notice to install `EU VAT Number`. 

Shipping:

When it comes to shipping, only US customers can use WooCommerce Services shipping. For UK customers we offer to install ShipStation which is fine but this is not WooCommerce Services as we claim would provide labels to customers during onboarding:

![uk](https://user-images.githubusercontent.com/19143190/80842387-6e1b5e80-8bcf-11ea-95c8-f49fcc8c2090.jpg)

Also note, that if you didn't connect Jetpack prior, you'd see a sentence as follows:

"Once you connect Jetpack you'll have access to ." - missing what they will have access to:

![jp1](https://user-images.githubusercontent.com/19143190/80843019-2dbce000-8bd1-11ea-9c38-fe684c4a2c1f.jpg)

And when you connect, you see "You can now enjoy ." - also missing what they can enjoy. 

Perhaps both missing points are connected to the fact that the services are actually not available for non-US stores.

![jp2](https://user-images.githubusercontent.com/19143190/80843172-986e1b80-8bd1-11ea-8bdc-b867819b8497.jpg)

<hr>

**RUSSIA:**

For Russia, the situation a bit more complicated than for the UK. 

I was not offered CBD which is expected and correct but I was offered to install WooCommerce Services. 

**Why this is a problem?** 

Taxes:

There is no option of calculating taxes automatically available for stores in Russia. 

Shipping:

There is no option of printing shipping labels available for stores in Russia. There is no alternative given either like ShipStation for the US. 

![Screen Shot 2020-05-01 at 4 41 04 PM](https://user-images.githubusercontent.com/19143190/80842882-bb4c0000-8bd0-11ea-867f-3235bb8a4997.png)

All in all, the whole mention of WooCommerce Services doesn't do anything to stores in Russia. Only confusing merchants. They will perhaps look for these after onboarding but won't be able to find them. 

<hr>

**Comment by timmyc** [comment]
Thanks for the detailed issue @juliaamosova - few of the items I think need to be directed towards WCS ( /cc @c-shultz ) specifically:

> "Once you connect Jetpack you'll have access to ." - missing what they will have access to:

and the following dialog shown:

> And when you connect, you see "You can now enjoy ." - also missing what they can enjoy.

But definitely the splash screen to install WCS + Jetpack should be more locale-aware.

**Comment by juliaamosova** [comment]
>few of the items I think need to be directed towards WCS ( /cc @c-shultz ) specifically:

Thanks for looping it @c-shultz here, @timmyc!

>But definitely the splash screen to install WCS + Jetpack should be more locale-aware.

👍

**Comment by c-shultz** [comment]
@juliaamosova, 

Nice catch! Can you raise an issue specific to the blanks text in the [WCS repo](https://github.com/Automattic/woocommerce-services/issues)?

**Comment by juliaamosova** [comment]
>Nice catch! Can you raise an issue specific to the blanks text in the WCS repo?

@c-shultz thanks! Opened the issue here: https://github.com/Automattic/woocommerce-services/issues/2022.

**Comment by juliaamosova** [comment]
@timmyc is it something your team can manage to fix for 4.2? It will be great if possible. cc @ObliviousHarmony as a 4.2 Release Lead.

**Comment by timmyc** [comment]
Since we've already missed the beta cut-off, not sure if this will make it into the release. Since this code has already been merged to core, this bug isn't technically part of code introduced in 4.2.

Couple of other things we need to consider on the fix for this:

- Do we still want to have the Jetpack nudge here for non-WCS locales?
- If we remove this step for all non US addresses, will it impact any flows for tracks? ( cc @pmcpinto ).
- And then thinking we should also have some e2e test updates around this too.

**Comment by pmcpinto** [comment]
> If we remove this step for all non US addresses, will it impact any flows for tracks? ( cc @pmcpinto ).

I think that would be too radical as we also have JP tied to that step. As I see it, the best option is:
- Trigger a notification for UE stores about the EU VAT Number plugin when they trigger automated taxes
- Keep the WCS screen but hide the print shipping labels benefit for non-US stores. @aleftick is there any additional WCS benefit that's useful for non-US stores?

**Comment by aleftick** [comment]
>Trigger a notification for UE stores about the EU VAT Number plugin when they trigger automated taxes
WCTax works for all the countries listed [here](https://developers.taxjar.com/api/reference/#countries). AFAIU, the EU VAT Number plugin is only valid in a B2B scenario. Why would we stop recommending WCTax for EU merchants and replace it with the EU VAT Number plugin?

>Keep the WCS screen but hide the print shipping labels benefit for non-US stores. @aleftick is there any additional WCS benefit that's useful for non-US stores?
Indeed WCShip is only relevant for US merchants. WCTax is relevant to US, CAD, AUS, UK and EU countries. 
WCS also [simplifies the payment connections to PayPal and Stripe](https://docs.woocommerce.com/document/woocommerce-services/). However, I know very little about it but I believe it's still relevant in our new onboarding experience. Although it might not be worth featuring as a reason to install it? @thenbrent might have more insights. 

> Accept PayPal Express Checkout payments with just your email address or simplify Stripe account setup.

**Comment by pmcpinto** [comment]
> Why would we stop recommending WCTax for EU merchants and replace it with the EU VAT Number plugin?

It's out of the question to stop recommending WCTax for EU. EU VAT Number plugin suggestion would work as a complement to that.

**Comment by aleftick** [comment]
>It's out of the question to stop recommending WCTax for EU. EU VAT Number plugin suggestion would work as a complement to that.

In that case, it could be a valuable addition. We could suggest to any business planning to do b2b.

**Comment by dougaitken** [comment]
Hey all - looks like I threw a spanner in the works for this. 

As I mentioned to @aleftick in Slack DM, I’ve only _just now_ realized that EU VAT Number and WCTax solve two different tax scenarios:

WCTax brings tax rates to the store
EU VAT Numbers allows sites to offer businesses paying VAT or removing it.

For my specific query, it was more around Labels. I wonder if we can split this "Enhance your store with WooCommerce Services" screen to be two and only combine if the locale is US where label printing is possible?
