### ISSUE TITLE
Allow users to turn-off extensions suggestions in the inbox panel

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4283]
**User story:**
As a merchant
I want to have an option to stop receiving promotional content
So I can turn it off if I'm not getting value from it

**Description:** we want to provide a way for users to completely turn off notifications with suggestions of extensions. We're going to use the Marketplace Suggestions setting that's available on WooCommerce -Settings - Advanced - WooCommerce.com

Acceptance criteria:
- [ ] If the user already opted out in the Marketplace Suggestions setting, he shouldn't receive any notification about extensions available in the marketplace.
- [ ] If the user is opted-in in the Marketplace Suggestions setting and then he opts out, he should stop receiving notification about extensions available in the marketplace since that moment.
- [ ] Remove _contextual_ in the setting description: "We show ~contextual~ suggestions for official extensions that may be helpful to your store."

This setting should remove promotional content both from the existing inbox messaging system and the remote one (#4101). What would be the best way to identify the promotional messages? Through the "type" data point?

**Comment by joshuatf** [comment]
>What would be the best way to identify the promotional messages? Through the "type" data point?

I'm thinking we can use the existing `type` field to track this.  Currently this is limited to `error`, `warning`, `update`, and `info`, but I think introducing a new type of `marketing` would be appropriate.

/cc @becdetat if you have any thoughts around this in regards to the RINDS PR.

**Comment by pmcpinto** [comment]
Ok, let me know if using `type` is the best way to move forward, so I can start adding a marketing or promotions label in the notifications that fall under that category
