### ISSUE TITLE
[GlobalStep - 4.1 RC]: Unable to complete Jetpack setup on Mac->Safari

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4290]
Steps to Reproduce:
1. Create Website / Tested on JN multisite  on Mac->Safari
2. Complete initial screens.
3. Click on Jetpack.
4. Click on Set up jetpack button.
5. Click on Approve.
6. Observe that Explore our jetpack screen fails to load.

Actual Result:
 Unable to complete Jetpack setup on Mac

Expected Result:
User should be able to setup Jetpack.

[#10.zip](https://github.com/woocommerce/woocommerce/files/4530606/10.zip)

**Comment by timmyc** [comment]
Going to close this as out of scope since this particular page is part of Jetpack and not WooCommerce Admin. I also feel that this might be related to the known "blips"/outages that happen on JN: https://github.com/woocommerce/woocommerce-admin/issues/4137#issuecomment-621511571
