### ISSUE TITLE
Releasing the new home screen on Core

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4303]
Now that Core moved to monthly releases it won’t make sense to ask users to install wcadmin to use the new home screen. So we should merge the feature directly on Core and have the following approach:

July release: new users have automatic access to the new home screen and we display a setting on `Settings - Advanced` that allows existing users to turn-on the new home screen. This setting should be turned on by default to new users and turned-off by default to existing users. The design/copy for this setting is coming soon.

We'll then make a decision of removing the setting and becoming the default experience for everyone in an upcoming release, based on the feedback/data that we'll gather between July and August/September.

EDIT: Make sure `wcadmin_settings_change` and `wcadmin_settings_view` or something similar is working so we can track usage.

**Comment by pmcpinto** [comment]
@timmyc I created this issue for the roll out plan of the new home screen on Core.

**Comment by timmyc** [comment]
This all looks good to me. Few questions/clarity items:

**1: Settings - Advanced**
Are we going to add a new "sub" menu item to this screen ( akin to WooCommerce.com ) for these types of settings? None of the current ones jump out to me as a logical place to add this:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/22080/81211698-9bc62600-8f88-11ea-9d47-b776348f82a3.png">

**2. on by default to new users and turned-off by default to existing users**
To turn it on by default for new users, should we chain this logic to completion of the profiler?

**Comment by pmcpinto** [comment]
> Are we going to add a new "sub" menu item to this screen ( akin to WooCommerce.com ) for these types of settings? None of the current ones jump out to me as a logical place to add this

Yes, @jameskoster is going to prepare the mockup.

> To turn it on by default for new users, should we chain this logic to completion of the profiler?

I think that we should display it independently if they complete the profiler, so we know for sure that all the new users access the home screen by default. This also makes it easier to compare different cohorts.

**Comment by jameskoster** [comment]
Latest concept here:

![features](https://cldup.com/vslHN_VVne-2000x2000.png)

**Comment by pmcpinto** [comment]
> Latest concept here:

@jameskoster I think that it would be helpful to include in the description a link to a support doc with more info about the new home. Sounds good?


@timmyc @psealock do we need to make any change on `wcadmin_settings_change` and `wcadmin_settings_view` to track the behavior of this new setting?

**Comment by jameskoster** [comment]
> I think that it would be helpful to include in the description a link to a support doc with more info about the new home. Sounds good?

Sure. Couldn't hurt to include a "Learn more" link at the end of the description.

**Comment by psealock** [comment]
>@timmyc @psealock do we need to make any change on wcadmin_settings_change and wcadmin_settings_view to track the behavior of this new setting?

I'm not sure offhand, but I will make tracking a deliverable on this ticket.

**Comment by pmcpinto** [comment]
> Sure. Couldn't hurt to include a "Learn more" link at the end of the description.

I'm going to work on the documentation next week, so we can include the link

**Comment by pmcpinto** [comment]
> Sure. Couldn't hurt to include a "Learn more" link at the end of the description.
Hey @psealock the permalink of the support doc will be this one: https://docs.woocommerce.com/document/home-screen/
