### ISSUE TITLE
How to disable Marketing menu?

### ISSUE THREAD

**Issue by poehaldur** [woocommerce/woocommerce-admin#4304]
Why is this even in core? After updating I have a main menu link to a page with useless welcome card and 6 blog posts that give 0 value to me. Me or my clients don't need any generic blog posts for selling products.
What is the filter snippet to disable this?

**Comment by jconroy** [comment]
Similar [thread here](https://github.com/woocommerce/woocommerce-admin/issues/4124) filter mentioned above is good to use.
