### ISSUE TITLE
Variations empt/not showing variation title

### ISSUE THREAD

**Issue by benjaminmateev** [woocommerce/woocommerce-admin#4308]
We have 4 products with many different variations and I was looking in the Analytics overview of products, going into one product and then looking variations. But in one of the products, the table is empty but the graph shows 4 different times the same product, which I guess are the different variations.

In another case the table is not empty but only shows the main product name without the variations titles.

**Expected behavior**
Expecting to see the variations in the overview for one product

**Screenshots**
<img width="1956" alt="Screenshot 2020-05-07 at 13 12 25" src="https://user-images.githubusercontent.com/172429/81291449-0dc26c00-906a-11ea-8544-94ec44ce10b5.png">

**Desktop (please complete the following information):**

* OS: [e.g. Mac]
* Browser [e.g. chrome]

**Additional context**
My suspicion is that it only shows variations in certain circumstances? Does a variation need to manage its own stock to show up in the Analytics? Or does it have to have its own SKU to show up? What are the requirements for the variations/titles to show up? I think it would help to display these if they don't exist so the user knows why the table is empty or looks broken.

And please let me know what is necessary so I can fix it for my setup :) 

Thank you so much for all the work you are putting into these fantastic products, its truly a blessing to be able to use them!

**Comment by benjaminmateev** [comment]
<img width="1792" alt="Screenshot 2020-05-07 at 17 30 42" src="https://user-images.githubusercontent.com/172429/81314518-81c03c80-9089-11ea-8f03-b6f58c0c83de.png">

I have found an issue where I am getting 500 response code, that might be the issue but I am not seeing anything in the server logs. I am suspecting that either something is misconfigured?

**Comment by psealock** [comment]
Thanks for the report @benjaminmateev 

I did some testing on my local setup and found that variations were named correctly in the Product Report, such as `My Variable - small, green`. I did however, find an instance of a product that appears exactly as you describe: only the parent name is visible. I'm looking into why that might be.

The 500 errors point to something else. There are lot of performance fixes in WooCommerce 4.1 and even more coming up in 4.2. Perhaps one of those updates can help. In the meantime, are there any related server error messages in your logs that you can share?

**Comment by psealock** [comment]
>I'm looking into why that might be.

There is some logic in WooCommerce Core that disregards attributes in variation titles if an attribute is more that one word. Can you change the attribute names to something with just one word? 

I think this may be a bug with WooCommerce. Hopefully I can follow up there.

**Comment by benjaminmateev** [comment]
Thanks, @psealock that's good feedback. I think it might be related to our variations having multiple words. I will try that. We are running the latest WooCoomerce on that Wordpress setup and no I don't see any server errors in the logs related to that 500 unfortunately.

**Comment by benjaminmateev** [comment]
@psealock Was there anything you could figure out or test? Happy to do some tests in-code on our setup in the analytics part to see what works and what doesn't. Maybe it can help you find a solution as well? Was there a suggestion on what we might want to change to make it work?

**Comment by psealock** [comment]
Here is the function in question, from WooCommerce Core:

https://github.com/woocommerce/woocommerce/blob/1d1413b4ee669cd37ee025c93972ce785a10a0b9/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L291-L314

The comments provide some insight into the logic:

>// Do not include attributes if the product has 3+ attributes.

>// Do not include attributes if an attribute name has 2+ words and the
// product has multiple attributes.

It looks like you can force it to show the variation titles regardless with the filter `woocommerce_product_variation_title_include_attributes`. I'd like to add it to wc-admin so it always shows, but in the meantime, maybe you can add it to your site?

**Comment by psealock** [comment]
And here is an alternative suggestion to investigate: https://github.com/woocommerce/woocommerce-admin/issues/4336#issuecomment-626992095

**Comment by benjaminmateev** [comment]
Oh nice, that hook seems helpful! I am just not sure right now how I make sure that it is being used in the analytics views as the variations are being shown on checkout and in the orders view. How would I make sure it is being applied to the analytics views?

**Comment by benjaminmateev** [comment]
One more thing I noticed, if you look at the total sold items for this one product on the screenshot and then at the numbers next to the variations, it seems not to match. Is this correct or could there be an issue with how it is being tracked and shown there?

<img width="1337" alt="Screenshot 2020-05-20 at 10 21 13" src="https://user-images.githubusercontent.com/172429/82423445-0b0d4100-9a84-11ea-9286-0e0bdf1e3090.png">

**Comment by benjaminmateev** [comment]
We moved the site to a new hoster and now I am getting some error.logs - this is what shows when see the 500 error in the javascript console when looking at products and variations - 

2020/06/24 10:55:35 [error] 15065#15065: *4779 FastCGI sent in stderr: "le, WC_Order_Export_Data_Extractor::fetch_order_data, WC_Order_Export_Data_Extractor::fetch_order_products, WC_Order_Export_Order_Product_Fields->get, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.PHP message: parent was called incorrectly. Product properties should not be accessed directly. Backtrace: do_action('wp_ajax_order_exporter'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Order_Export_Admin->ajax_gate, WC_Order_Export_Admin_Tab_Abstract->ajax_export_part, WC_Order_Export_Engine::build_file, WC_Order_Export_Data_Extractor::fetch_order_data, WC_Order_Export_Data_Extractor::fetch_order_products, WC_Order_Export_Order_Product_Fields->get, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.PHP message: parent was called incorrectly. Product properties should not be accessed directly. Backtrace: do_action('wp_ajax_order_exporter'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Order_Export_Admin->ajax_gate, WC_Order_Export_Admin_Tab_Abstract->ajax_export_part, WC_Order_Export_Engine::build_file, WC_Order_Export_Data_Extractor::fetch_order_data, WC_Order_Export_Data_Extractor::fetch_order_products, WC_Order_Export_Order_Product_Fields->get, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.PHP message: parent was called incorrectly. Product properties should not be accessed directly. Backtrace: do_action('wp_ajax_order_exporter'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Order_Export_Admin->ajax_gate, WC_Order_Export_Admin_Tab_Abstract->ajax_export_part, WC_Order_Export_Engine::build_file, WC_Order_Export_Data_Extractor::fetch_order_data, WC_Order_Export_Data_Extractor::fetch_order_products, WC_Order_Export_Order_Product_Fields->get, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.PHP message: parent was called incorrectly. Product properties should not be ac

**Comment by timmyc** [comment]
@benjaminmateev sorry for the silence on our end here - did you ever resolve this problem? Looks like `wp_ajax_order_exporter` might be from another plugin/extension you have installed on the site. I'm going to close out this issue, but if there is something we can help with further, please do reply back.
