### ISSUE TITLE
Payments step: auto create a PayPal account

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4310]
In the old onboarding we allowed to auto-create a PayPal account: https://d.pr/i/f1eCGy

![Screenshot on 2020-05-07 at 13_39_29](https://user-images.githubusercontent.com/63922/85746030-277c4900-b6d4-11ea-988c-4876bd3218c9.png)

It would be good to evaluate the amount of effort required to implement the same behavior in the new onboarding. The flow would be similar to what we had for Stripe: https://cloudup.com/cump6JLXXIG

<img width="594" alt="5lmtltPC9u-3000x3000" src="https://user-images.githubusercontent.com/63922/85746061-2d722a00-b6d4-11ea-8e38-9cabbcf87f2f.png">

**Comment by pmcpinto** [comment]
@joshuatf @timmyc is it possible to have a rough estimation of the work required to reimplement this in the new onboarding? PayPal is concerned with the fact that the number of accounts created decreased with the new experience. Thanks

**Comment by joshuatf** [comment]
It appears the old onboarding wizard just sets `ppec_paypal_reroute_requests` to `yes` and performs the WCS install.

Digging a little deeper, WCS appears to attempt and automatically set up API keys in `WC_Connect_PayPal_EC::init()`.

If that's all that's needed, this is probably a 1, but I'm going to add a little extra for the unknown problems that might pop up here.

Estimate: 2.

**Comment by jeffstieler** [comment]
I'm good with a 1-2 for this. However..

We're going to have to install WCS and let it continue to handle the PayPal requests. The class @joshuatf mentioned, [`WC_Connect_PayPal_EC`](https://github.com/Automattic/woocommerce-services/blob/29dfe0ba6fd3075afe08f917a6ff33c321502d9c/classes/class-wc-connect-paypal-ec.php#L14) reroutes the PayPal requests through the WCS server so it can add in some authorization/app headers.

**Comment by jeffstieler** [comment]
The old Stripe behavior referenced here did not present to users unless Jetpack and WooCommerce Services were installed and connected. Is that an OK precondition for this desired PayPal behavior as well?

If not, we'll have to add the installation of both Jetpack and WCS to this step.

**Comment by pmcpinto** [comment]
@jeffstieler in the old onboarding this step to create the PayPal account was displayed before the Jetpack and WCS installation. So when the user proceeded with the PayPal account creation the JP and WCS were installed and connected in the background?

**Comment by jeffstieler** [comment]
> in the old onboarding this step to create the PayPal account was displayed before the Jetpack and WCS installation. So when the user proceeded with the PayPal account creation the JP and WCS were installed and connected in the background?

@pmcpinto yes that's correct. Which differs from how we previously handled the Stripe account creation in the new onboarding - that's why I'm asking for clarification.

**Comment by pmcpinto** [comment]
👍 I think that we should apply the same principle used in the old onboarding:

- If the don't have JP and WCS installed and connected: display the PayPal account creation enabled with the following info below the call to action:

PayPal setup is powered by Jetpack and WooCommerce Services. The following plugins will be installed and activated for you: [WooCommerce Services](https://wordpress.org/plugins/woocommerce-services/), [Jetpack](https://wordpress.org/plugins/jetpack/)

- If they disable the checkbox, then the copy can be hidden and JP and WCS are not installed. Sounds good?

**Comment by jeffstieler** [comment]
![Screen Shot 2020-06-26 at 11 12 54 AM](https://user-images.githubusercontent.com/63922/85872965-77bfdd80-b79e-11ea-8c52-9f4997273706.png)

Yeah I think that works - it will be added to this view ☝️

**Comment by jeffstieler** [comment]
This is still super rough, but does this conceptually work?

![2020-06-30 14 46 28](https://user-images.githubusercontent.com/63922/86165625-8fba9880-bae1-11ea-9983-3e93471746c7.gif)

**Comment by pmcpinto** [comment]
> This is still super rough, but does this conceptually work?

Yep 👍 . It the user already has WCS and Jetpack connected it will display his email address in the input field, correct?

**Comment by jeffstieler** [comment]
@timmyc @pmcpinto should we be putting the PayPal gateway in "live" mode when completing this step?

**Comment by pmcpinto** [comment]
> @timmyc @pmcpinto should we be putting the PayPal gateway in "live" mode when completing this step?

Good question. In the old obw the live mode was enabled when completing a similar step and in the new onboarding is happening the same even if the user doesn't connect to a PP account. So I think that we should follow that logic and enable the live mode.

**Comment by jeffstieler** [comment]
Right now, I'm using the same check we had for Stripe: Jetpack is connected, and WCS is active.

There is still the possibility that the user hasn't accepted the WCS terms of service and has this banner in their admin:

![Screen Shot 2020-07-14 at 8 45 44 AM](https://user-images.githubusercontent.com/63922/87427285-90a5fc80-c5ae-11ea-955d-012c8489f2ed.png)

Should we try to incorporate the banner into the flow? Or perhaps check the TOS acceptance status before showing the "create an account for me" flow?

It may not be a big deal to leave this as is - but the store won't be able to actually accept payment until the "connect" button is clicked on that notice.

@timmyc @pmcpinto

**Comment by pmcpinto** [comment]
Checking the TOS acceptance status before showing the flow seems to be the best option.

Thanks for spotting that use case. There are always so many moving parts when it comes to features that require JP and WCS 😄
