### ISSUE TITLE
Inbox: Prompt to connect to woo.com is shown even after connection to woo.com is made

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4313]
**Describe the bug**

In the Inbox section, prompt to connect to woo.com is shown even after connection to woo.com is made. 

**To Reproduce**

1. Complete new onbaording;
2. Navigate to `WooCommerce/Extensions/WooCommerce.com Subscriptions`;
3. Click on `Connect` button and complete connection to WooCommerce.com account;
4. Click on Inbox and see that the prompt to connect to woocommerce.con account is still present:

![notice](https://user-images.githubusercontent.com/19143190/81335873-4cf6ba00-9076-11ea-820d-ddab1aae107c.jpg)

**Expected behavior**

I expect for the prompt in Inbox not to be displayed if the connection to woocommerce.com account had already been made. 

**Screenshots**

Above. 

**Desktop (please complete the following information):**

* OS: macOS Catalin 10.15.4
* Browser: Chrome
* Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by becdetat** [comment]
The note gets actioned when connecting to WooCommerce.com in WC 4.8.0, so I'm closing this.
