### ISSUE TITLE
Remove `Skip store setup` if all tasks are completed

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4315]
**Describe the bug**

Remove the `Skip store setup` if all tasks are completed. 

**To Reproduce**

1. Complete new onboarding;
2. Complete all tasks on the task list;
3. See that the option to `Skip store setup` is still shown but it is now redundant since the setup is completed and there is also an option for the merchant to hide the task list card:

![card](https://user-images.githubusercontent.com/19143190/81337028-56812180-9078-11ea-8e93-2b7114bcd7a0.jpg)

**Expected behavior**

I expect the `Skip store setup` option to be hidden if all tasks are completed. 

**Screenshots**

Above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.4
* Browser: Chrome
* Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by pmcpinto** [comment]
I'm closing this one as in the meantime we changed the task list UI and removed that link
