### ISSUE TITLE
Connection to PayPal message can be improved

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4316]
**Is your feature request related to a problem? Please describe.**

Our current message when connecting to PayPal account via Task list says the following:

`Connect a PayPal account to start accepting payments on WooCommerce Developers`:

![pp](https://user-images.githubusercontent.com/19143190/81339287-e70d3100-907b-11ea-9ca2-5937e154f82b.jpg)

In particular, the wording `WooCommerce Developers` doesn't sound user-friendly. It is also not clear what it means. 

You get to this message by selecting PayPal Checkout `Set up` via `Set up payments` task on the task list:

![Screen Shot 2020-05-07 at 3 57 11 PM](https://user-images.githubusercontent.com/19143190/81340116-4a4b9300-907d-11ea-99da-569195ed5e46.png)

![Screen Shot 2020-05-07 at 3 57 24 PM](https://user-images.githubusercontent.com/19143190/81340126-4fa8dd80-907d-11ea-9466-61a637d01c12.png)

**Describe the solution you'd like**

If we control what message is shown there, can we change it to:

`Connect a PayPal account to start accepting payments on WooCommerce site`

?

**Describe alternatives you've considered**

N/A. 

**Should this be prioritized? Why?**

Not a big deal. Rather nice to have. 

**Additional context**

 N/A.

**Comment by becdetat** [comment]
@juliaamosova This isn't set on our side, I think it has something to do with our PayPal partner settings. This is set relatively deep within  the PayPay page that shows the message:

```
&partner_name=WooCommerce%20Developers
```
which is not set anywhere in WooCommerce Admin. Possibly this would be better handled by the PayPal plugin devs.

**Comment by moon0326** [comment]
Closing this as this has been idle for long and the change can't be made in WC Admin.
