### ISSUE TITLE
Install timestamp reset every page load

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4322]
**Describe the bug**
When loading any admin page, the `woocommerce_admin_install_timestamp` is always reset to the current time.

This seems like it may be related to the migrated options.

**To Reproduce**

1. Remove the `wc_admin_install_timestamp` option if it exists.
1. Add the `woocommerce_admin_install_timestamp` if it doesn't exist.
1. Refresh the page.
1. Note the timestamp is updated every refresh.

**Expected behavior**
Expected the install time stamp to match the original install time.

**Comment by jeffstieler** [comment]
I'm unable to reproduce this. My store didn't have the `wc_admin_install_timestamp` option, but did have the `woocommerce_admin_install_timestamp` option - which isn't changing value at all.

There must be more to triggering this condition.
