### ISSUE TITLE
Filter Product and Order Reports by Variation 

### ISSUE THREAD

**Issue by gbruzzo** [woocommerce/woocommerce-admin#4330]
**Is your feature request related to a problem? Please describe.**

We would like to be able to **filter reports by product variation**. 

Our store sells products as variations. We are a record label; the parent product is usually a 'release' (an album release); what is actually SOLD are variations (e.g. formats), so VINYL, CD, Download, etc. It is therefore crucial for us to be able to **filter all reports by Variation**

1. **Orders reports** -  One can only filter by Parent Product:  Not only one cannot filter by variation, but the table returned after filtering by a parent product contains parent product names, not variation names. (column : product(s)), as does the CSV. That is of little use. 

2. **Products reports** - One can only filter by Parent Product (in Single Product and Comparison, as well as in the explicit Product Filter): It is true that the table returned contains all individual variations of a given parent product; Alas the 'Order' columns links to the Orders reports, which then only shows the parents again. Again, of very little use, as are the CSV reports.

**Describe the solution you'd like**

In order for Analytics to be of any use, we would need to be able to 

- Explicitly filter by **individual Variations**  in the Product and Order Reports. 

- Explicity filter by **specific Attribute** in the Product and Order Reports (e.g. in our case filter by 'CD' or by 'VINYL' or 'DOWNLOAD') 

- **Alternatively :** create an **ATTRIBUTE REPORT** (to sit side by side with the Category report)

- **When filtering Orders Reports by a parent product:** the table returned should specify all Variations bought in the Product(s) column, not just the Product Parent Name. 

- **Alternatively :** **when filtering Orders Reports by a parent product:** the table returned should contain an extra column with all Variations of the parent product in a given order.

All this information should be reflected and available in .csv

**Describe alternatives you've considered**

The alternative for us is currently to not use Woocommerce admin (it is wholly redundant). 

**Should this be prioritized? Why?**

Because, as it stands, Woocommerce Admin is incomplete and of little use. It burdens installations without offering the depth required (drilldown by Variation and other types of products). 

We currently keep Woocommerce Analytics (and Marketing for that matter) switched off via a filter. 

**Additional context**

Similar points raised in : https://github.com/woocommerce/woocommerce-admin/issues/3665 

Order Report Screenshot with comments 
![Screenshot_2020-05-09_at_16_03_37](https://user-images.githubusercontent.com/16798202/81477495-f1f8ca80-920f-11ea-8ff3-94b1eeca2f99.jpg)

Products Report Screenshot with comments 
![Screenshot_2020-05-09_at_16_04_16-2](https://user-images.githubusercontent.com/16798202/81477502-fc1ac900-920f-11ea-91a2-2bad156b3f7c.jpg)

**Comment by psealock** [comment]
This has been asked for previously in 
* https://github.com/woocommerce/woocommerce-admin/issues/3665
* https://github.com/woocommerce/woocommerce-admin/issues/3195
* https://github.com/woocommerce/woocommerce-admin/issues/1562

@pmcpinto What do you think about prioritising this request?

**Comment by pmcpinto** [comment]
@psealock I think that it can be evaluated for the next cycle. Do you have a rough estimation of how long it would take to implement this change? Thanks

**Comment by psealock** [comment]
>Do you have a rough estimation of how long it would take to implement this change?

The UI elements are already in place, so work would mainly be modification of the API and underlying queries. I think it would take one developer a week to develop and another week for testing.

**Comment by pmcpinto** [comment]
> The UI elements are already in place, so work would mainly be modification of the API and underlying queries. I think it would take one developer a week to develop and another week for testing.

👍

@gbruzzo thank you for taking the time to share this idea, we really appreciate your help. This is a good improvement and we’re going to evaluate if we’re able to implement in one of the upcoming cycles. Stay tuned for updates.

**Comment by gbruzzo** [comment]
@psealock @pmcpinto 

Thank you very much for your feedback. 

I hope you will be able to offer these drilldown options soon.

Recapping, these would  be 
1) The ability to drill-down products _and_ orders (in their respective reports) by **individual variation** (e.g. T-shirt - _red and XL_ /  Album - _CD_)
2) The ability to drill-down products _and_ orders (in their respective reports) reports by **attribute** (_Red_ or _XL_ or _CD_)

They would certainly be very useful to us, and hopefully to many others as well. 

Cheers

Giacomo Bruzzo

**Comment by apmwebdev** [comment]
Just wanted to jump in here to say that this feature is probably the #1 most common request that I see for WC Admin, and I definitely recommend prioritizing it if at all possible. There's another request for it [here](https://wordpress.org/support/topic/show-variations-in-products-list/).

**Comment by photogenic89** [comment]
I second the request. Without this feature Analytics is of little use to us. We're exporting sales sheets to make future sales predictions with a strong focus of which sizes or colors work and which don't. When I export the general list for stock management I’m therefor missing vital sales information. And to export every variable product separately, only to add them later to the same excel sheet seems like misused energy.

**Comment by apmwebdev** [comment]
Another request for this: #3036911-zen

**Comment by timmyc** [comment]
I concur with @psealock 's estimate above. 8-10.

**Comment by dw-herrmann** [comment]
Hi there,
2 Months later and the analytics are still not very usable for variable products.
Does anyone know how the status for this request is?

**Comment by arunsathiya** [comment]
3166746-zen - similar request to see variation info in product reports.

**Comment by jozeflambrecht** [comment]
@jeffstieler Thanks for all the work and effort you put into the variations report! Do you have an idea when this will be released?

**Comment by mybestrong** [comment]
I'm not sure that 4.8 actually included this enhancement or have I missed it? :)

https://github.com/woocommerce/woocommerce-admin/issues/3195#issuecomment-738734106

**Comment by jeffstieler** [comment]
Hello @mybestrong,

Yes, this feature was released in WooCommerce 4.8. Are you not seeing it? There should be a new Variations Report as well as a Product Attribute filter on the Orders Report.

**Comment by mybestrong** [comment]
I think I set my variations up incorrectly ;)

Sorry to be a pain!

**Comment by jeffstieler** [comment]
No problem @mybestrong. If you're having trouble don't hesitate to [open a new issue](https://github.com/woocommerce/woocommerce-admin/issues/new/choose) to ask questions.
