### ISSUE TITLE
Dashboard not showing any things

### ISSUE THREAD

**Issue by vietphongN** [woocommerce/woocommerce-admin#4331]
Hi would you help me out please? I have a big problem with the Woocommerce Admin Dashboard.
It didn't show up any thing.
I have few error message in the console "has been blocked by CORS policy".
Thank you very much!

![Bildschirmfoto 2020-05-09 um 17 27 46](https://user-images.githubusercontent.com/36244949/81483829-46686e00-9241-11ea-9be6-cb73905b1a00.png)

`
### WordPress Environment ###

WordPress address (URL): https://www.anloc-asiamarkt.de
Site address (URL): https://www.anloc-asiamarkt.de
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: ❌ 5.4 - Es ist eine neuere Version von WordPress verfügbar (5.4.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33-0ubuntu0.16.04.14 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisieren Sie Ihre PHP-Version

PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.30-0ubuntu0.16.04.1
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Ihr Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: anloc_
Datenbank-Gesamtgröße: 8.64MB
Datenbank-Datengröße: 6.35MB
Datenbank-Indexgröße: 2.29MB
anloc_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
anloc_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
anloc_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
anloc_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_actionscheduler_actions: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
anloc_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
anloc_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_options: Daten: 2.23MB + Index: 0.08MB + Engine InnoDB
anloc_postmeta: Daten: 1.39MB + Index: 0.77MB + Engine InnoDB
anloc_posts: Daten: 1.42MB + Index: 0.13MB + Engine InnoDB
anloc_revslider_css: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_css_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_layer_animations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_layer_animations_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_navigations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_navigations_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_sliders: Daten: 0.03MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_sliders_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_slides: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_slides_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_static_slides: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_revslider_static_slides_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_termmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
anloc_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_term_relationships: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
anloc_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
anloc_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
anloc_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
anloc_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
anloc_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
anloc_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
anloc_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_yith_wcwl: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
anloc_yith_wcwl_lists: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 105
block: 13
customize_changeset: 8
kp_size_chart: 5
mc4wp-form: 1
nav_menu_item: 27
page: 77
portfolio: 9
post: 16
product: 126
product_variation: 43
revision: 62
shop_order: 12
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Contact Form 7: von Takayuki Miyoshi – 5.1.7
WPBakery Page Builder: von Michael M - WPBakery.com – 6.1
Kapee Extensions: von PressLayouts – 1.0.7
Loco Translate: von Tim Whitlock – 2.3.3
MC4WP: Mailchimp for WordPress: von ibericode – 4.7.6
Slider Revolution: von ThemePunch – 6.2.2
WooCommerce Stripe-Gateway: von WooCommerce – 4.3.3
WooCommerce: von Automattic – 4.0.1 – 4.1.0 ist verfügbar
YITH WooCommerce Wishlist: von YITH – 3.0.9

### Inactive Plugins (1) ###

YITH WooCommerce Compare: von YITH – 2.3.20

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #1821 - /?page_id=1821
Warenkorb: #1822 - /?page_id=1822
Kasse: #1835 - /?page_id=1835
Mein Konto: #1836 - /?page_id=1836
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Kapee
Version: 1.2.1
Author URL: http://presslayouts.com/
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: kapee/woocommerce/cart/cart.php
kapee/woocommerce/cart/cross-sells.php
kapee/woocommerce/cart/mini-cart.php
kapee/woocommerce/checkout/form-checkout.php
kapee/woocommerce/content-product.php
kapee/woocommerce/content-product_cat.php
kapee/woocommerce/content-single-product.php
kapee/woocommerce/content-widget-product.php
kapee/woocommerce/global/quantity-input.php
kapee/woocommerce/loop/loop-end.php
kapee/woocommerce/loop/loop-start.php
kapee/woocommerce/loop/pagination.php
kapee/woocommerce/loop/result-count.php
kapee/woocommerce/myaccount/form-login.php
kapee/woocommerce/single-product/add-to-cart/variable.php
kapee/woocommerce/single-product/product-image.php
kapee/woocommerce/single-product/product-thumbnails.php
kapee/woocommerce/single-product/related.php
kapee/woocommerce/single-product/short-description.php
kapee/woocommerce/single-product/tabs/tabs.php
kapee/woocommerce/single-product/up-sells.php
kapee/woocommerce/single-product-reviews.php

### Action Scheduler ###

Ausstehend: 27
Oldest: 2020-04-10 23:29:54 +0200
Newest: 2020-05-09 16:35:18 +0200

`

**Comment by psealock** [comment]
The CORS error is due to a discrepancy between  the origin and where the request is made to: `https://www.anloc-asiamarkt.de` v. `https://anloc-asiamarkt.de`. Note the extra `www`.

I'm wondering if there is something in your setup or settings that includes the extra `www`?

**Comment by timmyc** [comment]
@vietphongN since we haven't heard back from you, I'm going to close out this issue.
