### ISSUE TITLE
Task List: Smaller margin between WC Admin nav bar and the Task List on smaller screens

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4338]
**Describe the bug**

The margin between WC Admin nav bar and the Task List appears to be smaller (narrower) on smaller screens. 

**To Reproduce**

1. Complete onboarding;
2. Check Task List on the regular desktop screen size - note the margin:

![mar1](https://user-images.githubusercontent.com/19143190/81590306-a1f14380-9388-11ea-8682-a7c7d469319a.jpg)

3. Reduce the size of the screen to smaller one - note that the height of the margin is much less:

![mar2](https://user-images.githubusercontent.com/19143190/81590432-c77e4d00-9388-11ea-8ab8-ea7a78db396b.jpg)

**Expected behavior**

I expect that the margin on the smaller screen will be bigger (higher). Please feel free to close this issue if it is per design. 

**Screenshots**

Above. 

**Desktop (please complete the following information):**

* OS: macOS Cataline 10.15.4
* Browser: Chrome
* Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

Filing this on behalf of @Aljullu. Reference: pb22l9-8V-p2#comment-398.

**Comment by becdetat** [comment]
This looks like it's resolved now:

![image](https://user-images.githubusercontent.com/224531/102300859-729b5880-3fa1-11eb-9b57-38b95ab4dc87.png)
