### ISSUE TITLE
Analytics: Command + Mouse Click doesn't open any section in the new tab as it should

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4339]
**Describe the bug**

Analytics: Command + Mouse Click (on Mac) doesn't open any section in the new tab as it should. Tested in Chrome and Firefox.  

**To Reproduce**

1. In the Analytics section, try to `Command + Mouse Click` on any section. You will see that the section will open up in the same tab instead of the new tab as expected:

![](http://g.recordit.co/zrkEmLjFay.gif)

2. Note that the same happens with the new `WooCommerce / Customers` section while all other sections under `WooCommerce` open up in the new tab upon `Command + Mouse Click` on it - see gif below (can't embed it for some reason):

http://g.recordit.co/N5ecFOY6GM.gif

**Expected behavior**

I expected for any section to be opened up in the new tab when `Command + Mouse Click` on it on Mac. 

**Screenshots**

Gifs above. 

**Desktop (please complete the following information):**

* OS: mac OS Catalina 10.15.4
* Browser: Chome
* Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

Filing this on behalf of @Aljullu. Reference: pb22l9-8V-p2#comment-398.

**Comment by timmyc** [comment]
Noting that this bug is still present in 1.4/4.4

**Comment by becdetat** [comment]
Still present in 1.8.1 / 4.8 and in the new navigation experience.
