### ISSUE TITLE
Import Historical Data: Make it more clear when the checkbox next to "Skip previously imported" is not selected

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4342]
**Is your feature request related to a problem? Please describe.**

Import Historical Data: Make it more clear when the checkbox next to "Skip previously imported" is not selected. If I didn’t know how WC Admin worked, I would not be sure if the checkbox is disabled or not without clicking on it:

![](http://g.recordit.co/E7sUXx9QBJ.gif)

**Describe the solution you'd like**

Not sure what could be done to improve it, but I think it’s a common practice that disabled checkboxes have a darker background? Took this image from the Internet:

![contact](https://user-images.githubusercontent.com/19143190/81594330-ba645c80-938e-11ea-8745-66e7fe82f8c6.png)

Here it’s clear that `Phone` and `Fax` are disabled.

**Describe alternatives you've considered**

N/A. 

**Should this be prioritized? Why?**

Not a high priority. 

**Additional context**

Filing this on behalf of @Aljullu. Reference: pb22l9-8V-p2#comment-398.

**Comment by joshuatf** [comment]
I agree that the unchecked styling is not very clear.  Gutenberg changes the styling on disabled inputs to 70% which we can see from this page is not quite enough to discern whether or not an individual input is disabled.

If we want to update this, I think we should tackle this upstream in Gutenberg as opposed to overriding `@wordpress/components` default styling in WooCommerce Admin.
