### ISSUE TITLE
SearchListControl style issues with lastest version of `@wordpress/components`

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#4349]
In WC Blocks we are facing several issues with the `<SearchListControl />` styles when the `@wordpress/components` version is the latest one (_aka_ Gutenberg plugin is enabled):
![imatge](https://user-images.githubusercontent.com/3616980/81668472-05d94200-9445-11ea-8145-3b8c7434f62f.png)

Some issues:
* `:focus` box-shadow is only visible on the top border, but not the bottom one.
* In Chrome, rows aren't correctly vertically aligned.

Before fixing this, I think we will need to update the `@wordpress/components` version of WC Admin to the latest one as well.

**Comment by Aljullu** [comment]
In WC Blocks we added a work-around for now, it might serve as an inspiration when fixing this issue:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/ec48c1ca65519a468de26d8dca634d1cc8ae05e1

**Comment by psealock** [comment]
>Before fixing this, I think we will need to update the @wordpress/components version of WC Admin to the latest one as well.

I have a PR ready to update https://github.com/woocommerce/woocommerce-admin/pull/4427

**Comment by timmyc** [comment]
Closing since 4427 was merged long ago.
