### ISSUE TITLE
Redirect the user to the JP account creation flow right after the plugin install

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4363]
Removing the JP account creation flow from the profiler caused a significant drop in terms of the number of JP accounts created coming from Woo (context here: p1HpG7-9c2-p2)

This drop is higher than expected so we'll need to start redirecting users again to the JP account creation flow right after they install the plugin:

![jetpack.gif](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/f1580f09-0c0a-4aa0-8e98-42af22df2480)

We don't need to display the install plugins screen. 

So the flow is going to be: store profiler - JP & WCS screen - JP account creation flow - task list

**Comment by pmcpinto** [comment]
@timmyc @joshuatf is it possible to implement this change quickly? We're going to see if it's possible to ship it in a fix release, alongside the event tracking fix, or in 4.2.

**Comment by joshuatf** [comment]
@pedro I think this is possible to release by end of week optimistically or beginning of next week if we reprioritize.  This might mean it's harder to tackle all of the items in our current sprint.

**Comment by pmcpinto** [comment]
Great! The event tracking issue and this one are top priorities. I can check with Timmy if it will be necessary to backlog some of the issues in this sprint.

PS: you pinged the wrong Pedro :)

**Comment by joshuatf** [comment]
>PS: you pinged the wrong Pedro :)

Haha, whoops.  Sorry to the other @pedro 😅
