### ISSUE TITLE
[GlobalStep - 4.2 Beta] Activate button is displayed for "Facebook", "MailChimp"  and "Google Ads" on WooCommerce ->Marketing tab. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4371]
**Environment:**
Windows 10- Google Chrome (Version 81.0.4044.138)
Mac Mojave-10.14.6-Safari(v13.0.5 )

**Steps to Reproduce:** 
1. Create a site using Ninja tool.
2. Install all the plugins.
3. Tap on "Run the Setup wizard".
4. Complete all the introductory tabs i.e., Store details, Industry ,Product types, Business details and Theme. 
5. Now on dashboard, tap on "Marketing".
6. Go to "Installed marketing extensions" section.
7. Observe that website shows "Activate" button instead of "Finish Setup" button for the plugins "Facebook", "MailChimp"  and "Google Ads".

**Note:** After tapping on "Activate" button it displays "Finish setUp" button.

**Actual Result:**
Activate button is displayed for "Facebook", "MailChimp"  and "Google Ads" on WooCommerce ->Marketing tab. 

**Expected Result:**
"Finish Setup" button should be displayed.

![#26497](https://user-images.githubusercontent.com/41110392/81834684-e6363c80-955e-11ea-9e53-7a23f4a704b5.jpg)

**Comment by juliaamosova** [comment]
I tested this as well on Jurassic Ninja and I am actually not getting prompts to finish setup for any of the marketing plugins. 

I decided not to select Facebook during onboarding in my test to see what happens:

![Screen Shot 2020-05-14 at 11 09 31 AM](https://user-images.githubusercontent.com/19143190/81951686-78782800-95d3-11ea-9f0d-76d8aef00820.png)

Here is how my Marketing section looks like:

![Screen Shot 2020-05-14 at 11 08 20 AM](https://user-images.githubusercontent.com/19143190/81951782-96458d00-95d3-11ea-8f9b-e361dff33e04.png)

Here is a gif as well:

![](http://g.recordit.co/ONckxLAz6z.gif)

**Comment by gglobalstep** [comment]
This issue is observed to be "Open" on WooCommerce - 4.2 Beta.

Environment:
MAC Mojave v10.14.6:
Safari(v13.0.5)
Windows 10:
Chrome(Version 81.0.4044.138 (64-bit))

**Comment by gglobalstep** [comment]
This issue is observed to be **Fixed** on WooCommerce 4.2 RC1.

**Environment:**
MAC Mojave v10.14.6:
Safari(v13.0.5)
Windows 10:
Chrome(v81.0.4044.138 (64-bit))

**Comment by gglobalstep** [comment]
This issue is observed to be **"Fixed"** on WooCommerce 4.3 Beta.

**Environment:**
**Windows 10**
Browser: Chrome(Version 83.0.4103.61)(64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)
**MacBook Pro Version 10.15.5 (19F101)**
Browser: Safari(Version 13.1.1)(15609.2.9.1.2)
