### ISSUE TITLE
Task List: No Shipping connection step when Jetpack is active

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-admin#4372]
**Describe the bug**

On a US store, when Jetpack is not active, the Shipping task includes a plugin installation/activation step for Jetpack and WooCommerce Services, as well as a Jetpack connection step.

However, if Jetpack _is_ already active, then no step is presented for connecting it [[code](https://github.com/woocommerce/woocommerce-admin/blob/742b532ea379b402f323d767b7356f8cfe99424d/client/dashboard/task-list/tasks/shipping/index.js#L282)] – unlike in the Tax task [[code](https://github.com/woocommerce/woocommerce-admin/blob/742b532ea379b402f323d767b7356f8cfe99424d/client/dashboard/task-list/tasks/tax.js#L347)].

(cc @pmcpinto re: p1HpG7-9c2-p2#comment-39069, though shipping labels isn't given as an example, so I can't be entirely certain whether it applies here.)

**To Reproduce**

1. Go through onboarding flow
2. Agree (at the end) to install and activate Jetpack and WooCommerce Services. (Note: As of 1.2.1, there is no connection flow here, but this is slated to change in https://github.com/woocommerce/woocommerce-admin/issues/4363)
3. "Set up shipping" in the task list
4. See only store location and shipping cost steps

**Expected behavior**

Since Jetpack can be connected in the case when it isn't yet active, I would expect to have the same opportunity to connect even if it's active already.

**Comment by pmcpinto** [comment]
Thanks for spotting this. It should display the step to connect to Jetpack, as it happens in the Tax step. It seems that this went unnoticed by all the testing that was done.

@joshuatf can you take a look at this when you have time?

**Comment by joshuatf** [comment]
Thanks for catching this, @dechov.

I think this may have been a regression introduced when changing how we detect plugins or the recent plugin data store updates.

**Comment by pmcpinto** [comment]
@joshuatf this fix is going to be shipped in WooCommerce Core 4.2, correct?

**Comment by joshuatf** [comment]
@pmcpinto I don't think this one made it into 4.2.  AFAIK only a couple of those urgent last minute bug fixes were cherry-picked in after the code freeze.

/cc @octaedro to confirm since he handled that release.

**Comment by octaedro** [comment]
Hi there!
Yes @joshuatf, you're right. The wc-admin `version 1.2.3` (released on May 22) only has a few updates to [WooCommerce Payments in Setup Checklist](https://github.com/woocommerce/woocommerce-admin/pull/4373).

/cc @pmcpinto

**Comment by pmcpinto** [comment]
@octaedro thanks for the heads up. So we'll need to wait for 4.3 (PR Freeze - June 12)
