### ISSUE TITLE
Show SKU column on orders report table

### ISSUE THREAD

**Issue by ahmer110** [woocommerce/woocommerce-admin#4375]
**Is your feature request related to a problem? Please describe.**
No. But it's a problem for me!

**Describe the solution you'd like**
I want to have a SKU column right after Products on Orders Report Table, and show same as in export file for products comma separated.

**Comment by timmyc** [comment]
Hi @ahmer110 
Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
