### ISSUE TITLE
[WC 4.2 beta.1] Marketing section: prompts to finish marketing plugins setup are not being displayed if Marketing section is being visited right after onboarding is completed

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4376]
**Describe the bug**

Marketing section: prompts to finish marketing plugins setup are not being displayed if the Marketing section is being visited right after onboarding is completed.

I tested this on Jurassic Ninja.

I decided not to select Facebook during onboarding in my test to see what happens:

![Screen Shot 2020-05-14 at 11 09 31 AM](https://user-images.githubusercontent.com/19143190/81951686-78782800-95d3-11ea-9f0d-76d8aef00820.png)

Here is how my Marketing section looks like:

![Screen Shot 2020-05-14 at 11 08 20 AM](https://user-images.githubusercontent.com/19143190/81951782-96458d00-95d3-11ea-8f9b-e361dff33e04.png)

Here is a gif as well:

![](http://g.recordit.co/ONckxLAz6z.gif)

I can reproduce it consistently on the Jurassic Ninja site. 

No errors in the console log:

![Screen Shot 2020-05-14 at 11 13 21 AM](https://user-images.githubusercontent.com/19143190/81952048-f805f700-95d3-11ea-9ad5-fe279fe08f04.png)

Both plugins (Mailchimp and Google Ads) are installed and activated:

![Screen Shot 2020-05-14 at 11 15 35 AM](https://user-images.githubusercontent.com/19143190/81952362-621e9c00-95d4-11ea-8fac-81c484395c60.png)

The issue appears to be resolved on page refresh. 

Also, if you visit other sections of WooCommerce Admin first after completing the onboarding and then visit the Marketing section, the prompts do appear. 

**To Reproduce**

1. Complete onboarding;
2. When you see Task List for the first time after onboarding, don't go through the list. Instead, navigate to the Marketing section. 
3. See that there are no prompts in the Marketing section. 

**Expected behavior**

I expect to see prompts to finish marketing plugins setup if I visit the Marketing section right after onboarding is completed. 

**Screenshots**

Above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.4
* Browser: Chrome
* Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

As per @timmyc' recommendation, cc @jconroy.

**Comment by psealock** [comment]
@jconroy  https://github.com/woocommerce/woocommerce-admin/pull/4362 doesn't fix this issue.

I think what is happening is installed plugins are gathered from `wcSettings` here: These will be out of date until a page refresh.

https://github.com/woocommerce/woocommerce-admin/blob/5c79ecdc1b291d13aabd3155d09384409aede50a/client/marketing/data/index.js#L18\

I think updating to the new Plugins data store is the best course of action.

**Comment by timmyc** [comment]
@jconroy not sure if you want to pursue this one further or not.

**Comment by moon0326** [comment]
I'm closing this as it has been stale and we no longer display marketing plugins during the onboarding.
