### ISSUE TITLE
[GlobalStep - 4.2 Beta] HTTP API Call error is displayed upon tapping "Verify details" button during WooCommerce Payment setup

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4385]
**Environment:**
Windows 10- Google Chrome (Version 81.0.4044.138)
Mac Mojave-10.14.6-Safari(v13.0.5 )

**Steps to Reproduce:** 
1. Create a site using Ninja tool.
2. Install all the plugins.
3. Tap on "Run the Setup wizard" and then tap on "Yes Please" button.
4. Complete all the introductory tabs i.e., Store details, Industry-Select anything (do not select CBD) ,Product types, Business details and Theme. 
5. Now on dashboard you will reach "Setup Checklist", Now  connect Jetpack First.
6. On wp-admin sidebar menu, tap on JetPack link.
7. Click "Set up Jetpack" button.
8. Go to "SetUp Payments".
9. Tap on "Set up" button for WooCommerce Payments option.
10. On the subsequent screen, the plugin will be installed and activated for WooCommerce Payments, Now click on "Verify details" button.
11. Go back to Dashboard WooCommerce Payment setup
12. Observe that  HTTP API Call error is displayed upon tapping "Verify details" button during WooCommerce Payment setup

**Actual Result:**
 HTTP API Call error is displayed upon tapping "Verify details" button during WooCommerce Payment setup. 

**Expected Result:**
For  WooCommerce Payment setup, API Call error should not be displayed upon tapping  "Verify details" button on Setup Payments Page. 

![#26513](https://user-images.githubusercontent.com/41110392/81951374-b6506d00-9622-11ea-8669-ddcda2270f3d.png)

**Comment by dechov** [comment]
This error was innocuous but has been addressed on the back-end to return a success response in this scenario. Thanks for reporting!

**Comment by gglobalstep** [comment]
This issue is observed to be "**Fixed**" on WooCommerce 4.2 RC 1
**Environment:**
Windows
OS: 10
Browser: Chrome(Version 81.0.4044.138 (64-bit))

MAC
OS: Mojave v10.14.6
Browser: Safari(v13.0.5)

**Comment by gglobalstep** [comment]
This issue is observed to be **"Fixed"** on WooCommerce 4.3 Beta.

**Environment:**
**Windows 10**
Browser: Chrome(Version 83.0.4103.61)(64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)
**MacBook Pro Version 10.15.5 (19F101)**
Browser: Safari(Version 13.1.1)(15609.2.9.1.2)
