### ISSUE TITLE
wp-json/wc-analytics endpoint documentation

### ISSUE THREAD

**Issue by CodeBrauer** [woocommerce/woocommerce-admin#4390]
**Is your feature request related to a problem? Please describe.**
I would like to get some analytics data from the woocommerce API. Currently, I use the undocumented route `wp-json/wc-analytics/reports/products` to get the _total count of sold products_

**Describe the solution you'd like**
Add wp-json/wc-analytics to your documentation _or_ provide more report endpoints to [the API](https://github.com/woocommerce/woocommerce-rest-api-docs).

**Describe alternatives you've considered**
Currently, I would have to go through all `/wp-json/wc/v3/orders` and navigate to all pages of orders, count them and group up by product.

**Should this be prioritized? Why?**
Don't know how many people would like to have store-stats somewhere else, but sure the will be some.

**Additional context**
-

**Comment by timmyc** [comment]
Hi @CodeBrauer 

Thank you for taking the time to share this idea, we really appreciate your help. 

The `wc-analytics` endpoints are considered "application specific" for the WooCommerce Analytics system still - this means they are unversioned, and still prone to changes. We hope to eventually finalize them and merge them into the `wc/vx` namespace at which point they would be fully documented and versioned.

Until then sending an `OPTIONS` request to any of the endpoints returns the detailed schema which can be used as a form of documentation.

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.

**Comment by justinwyllie** [comment]
I would like this as well. I need to know the overall range of endpoints e.g. I want to get data about postal regions for orders. (how many to each region). It would help to an an overview of all the endpoints at least.

**Comment by CodeBrauer** [comment]
@justinwyllie 
Take a look at the reports-API:
https://woocommerce.github.io/woocommerce-rest-api-docs/#reports

Maybe it suits your needs.

**Comment by Mister-A** [comment]
Also keen to see this documented as need access to data not currently available from reports api

**Comment by sanebg3** [comment]
Hello, I desperately need to be able to pull "yesterday's" data from Analytics or reports and "last 7 days"

How can I achieve that via API?

**Comment by Mister-A** [comment]
Well if reports will do what you want, read the docs here: https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction

If you need something from analytics then what you need depends on what data you're trying to get, once you've got yourself a consumer key and secret (instructions provided in the above docs) then GET 

`https://{your URL}/wp-json/wc-analytics?consumer_key={your ck_xxxx}&consumer_secret={your cs_xxxx}&options`

to retreive a list of end points and arguments to play with.

**Comment by justinwyllie** [comment]
Or - open Chrome developer tools and look at the network tab as you make requests for the reports.

**Comment by sanebg3** [comment]
For some reason, I cannot find the endpoint of Analytics Today's Revenue.

**Comment by Mister-A** [comment]
This is probably more a discussion for stackoverflow where you can show what you've tried and other may help guide you in the right direction, that said here's my last input in the hope it sends you in the right direction:

Following @justinwyllie 's recommendation we can see one of the calls Analytics makes when requesting today's revenue report is:

/wp-json/wc-analytics/reports/revenue/stats?orderby=date&order=desc&after=2021-09-21T00%3A00%3A00&before=2021-09-21T23%3A59%3A59&page=1&per_page=25&interval=day&_locale=user

It makes other calls too that you can see in developer tools in your browser.

**Comment by sanebg3** [comment]
Thank you! But I already did that and as you can see from the endpoint it doesn't show yesterday's data but imports date range data.

 I need to be able to see yesterday's data.  :) I will follow your advice and go to stackoverflow.

**Comment by sanebg3** [comment]
I'm really desperate. Can someone tell me how to figure out the end point for "yesterday" on Analytics? I will be very, very grateful.

**Comment by Mister-A** [comment]
I was watching on stackoverflow for your post so I could help, but I see you post anything with a woocommerce tag for a couple of days after your last post here.

Presuambly you're calling this from your own software.
Your own software will know what date it is.
Yesterday is today minus 1 day.

So if your software knows today is 2021-9-30 it just takes one day off the date and uses that in the call: 2021-9-29

Your call to the end point will be 

`/wp-json/wc-analytics/reports/revenue/stats?orderby=date&order=desc&after= 2021-09-29T00:00:00&before=2021-09-29T23:59:59&page=1&per_page=25&interval=day&_locale=user`

The call changes every day to "today minus 1 day" - your software that making the call has to calculate that.

**Note** in the example above I've included ":" in the time in the hope it helps you understand it, URL encoded the ":" becomes %3A so the real call if today was the 30th Sept to get data from yesterday is:

`/wp-json/wc-analytics/reports/revenue/stats?orderby=date&order=desc&after= 2021-09-29T00%3A00%3A00&before=2021-09-29T23%3A59%3A59&page=1&per_page=25&interval=day&_locale=user`

If it's now October 10th then the call changes to 2021-10-09T00:00:00   and   2021-10-09T23:59:59

**Comment by sanebg3** [comment]
> I was watching on stackoverflow for your post so I could help, but I didn't see you post anything with a woocommerce tag for a couple of days after your last post here.
> 
> Presuambly you're calling this from your own software. Your own software will know what date it is. Yesterday is today minus 1 day.
> 
> So if your software knows today is 2021-9-30 it just takes one day off the date and uses that in the call: 2021-9-29
> 
> Your call to the end point will be
> 
> `/wp-json/wc-analytics/reports/revenue/stats?orderby=date&order=desc&after= 2021-09-29T00:00:00&before=2021-09-29T23:59:59&page=1&per_page=25&interval=day&_locale=user`
> 
> The call changes every day to "today minus 1 day" - your software that making the call has to calculate that.
> 
> **Note** in the example above I've included ":" in the time in the hope it helps you understand it, URL encoded the ":" becomes %3A so the real call if today was the 30th Sept to get data from yesterday is:
> 
> `/wp-json/wc-analytics/reports/revenue/stats?orderby=date&order=desc&after= 2021-09-29T00%3A00%3A00&before=2021-09-29T23%3A59%3A59&page=1&per_page=25&interval=day&_locale=user`
> 
> If it's now October 10th then the call changes to 2021-10-09T00:00:00 and 2021-10-09T23:59:59

Hello, and thank you very much for trying to help.

I'm not using software, I'm scraping directly the API URL and send the data to somewhere else.

That's why I need the ability to directly have "last_week," yesterday" etc, because in reality there is no date in my software. Imagine If I directly open the URL in a browser and scrape the data that's there.

**Comment by Mister-A** [comment]
Then you've likely to need to contract a software developer to do this for you, the API doesn't have "yesterday" as far as I can see - it has a date range. The thing calling it works out what yesterday was from today - 1 day. Good luck.

**Comment by sanebg3** [comment]
I understand, thank you. But if you need last week's data? Not the last week from today but last monday to sunday for example (dynamically) , how can you achieve that with -1 days etc?

**Comment by sanebg3** [comment]
Btw the examples above don't work. It's 400 error, no matter the date.

**Comment by justinwyllie** [comment]
> I understand, thank you. But if you need last week's data? Not the last week from today but last monday to sunday for example (dynamically) , how can you achieve that with -1 days etc?

As far as I can see Analytics uses a component called ReportFilters (from @woocommerce/components). This does all the calculation of the dates client-side. E.g. you would choose the specific date range you want -  press "Custom" - and then - client-side - the widget generates the dates.  If you want to decode these requests so you can construct your own you will need to understand the uri encoding parts. (Plenty of online tools will decode/encode uri for you). 

If you want an example of how to format the date part of the request this tutorial provides examples which may help: https://gorohovsky.com/extending-woocommerce-javascript-react/ (tested - it works). See e.g. getQueryParameters

It isn't clear to me if you actually have a copy of Analytics installed? If so - does this work? If this works but your own requests don't then there is something wrong with the way you are building the requests. If you post a sample request which produces a 400 I will try to test it for you.

**Comment by Mister-A** [comment]
If you're not doing it in a browser with an authenticated session to the backend you need to provide key and secret as mentioned nearer the top of the thread. Or seek professional assistance.

**Comment by sanebg3** [comment]
Hello, thanks but yes, I do know how to use consumer secret and consumer key when I pull data from the API but there are many, many things that are unknown.

For example, how can I pull last month's data if there is no parameter "last month" that works?

**Comment by justinwyllie** [comment]
> For example, how can I pull last month's data if there is no parameter "last month" that works?

I think this has been mentioned quite a few times above. The formation of the request and the calculation of the date parameters _is done in the client_.  If you are composing the request yourself then it is your responsibility to calculate the before date and the after dates and put them into the right format when you build the request. 

This is an example I just got Analytics to do for 'Last Month'. Of course last month is now September and so the dates are for September:

https://domain/wp-json/wc-analytics/reports/products/stats?order=asc&interval=day&per_page=100&after=2021-09-01T00%3A00%3A00&before=2021-09-30T23%3A59%3A59&fields%5B0%5D=items_sold&fields%5B1%5D=net_revenue&fields%5B2%5D=orders_count&_locale=user

%3A is : 
%5B is [
%5D is ]

Pay attention to the after and before parameters and the format of the dates. 

Again - you have to do the computation. The computation is not done on the server. You have to pass the after and before dates to get the range you want.
