### ISSUE TITLE
New Setup Wizard disallows choosing themes with Uppercase names

### ISSUE THREAD

**Issue by Jronk** [woocommerce/woocommerce-admin#4393]
**Describe the bug**
After the recent WooCommerce v4 update, it now allows you to choose a Theme at the end of the setup wizard. When you choose Divi, it gives an Error: 

> The requested theme divi could not be installed. Theme API call failed. Not sure if we can do anything about this.

**Note:** We at Elegant Themes, the makers of Divi, are getting a lot of bug reports because of this issue, so we consider this very important to resolve as quick as possible.

**To Reproduce**
1. Install a fresh version of WooCommerce
2. Use the new Setup Wizard
3. On the 5th step you can choose a Theme, and if Divi is installed it will be listed. If you press Choose it will not work. and you will get the following error:
> The requested theme divi could not be installed. Theme API call failed. Not sure if we can do anything about this.

**Expected behavior**
The wizard should allow you to choose installed themes even if they have a capital letter in their name.

**Screenshots**

<img src="https://user-images.githubusercontent.com/16253818/76702064-82fb6b80-66cf-11ea-854d-cf836b14bc7b.png" />

First case: The default theme is active and not Divi
<img src="https://user-images.githubusercontent.com/17510033/77160955-85decd80-6ace-11ea-8308-2aa91a13b671.gif" />

Second case: Divi is activated before choosing the theme from new WooCommerce setup wizard
<img src="https://user-images.githubusercontent.com/17510033/77161069-cc342c80-6ace-11ea-9b18-8e558f676e8f.gif" />

**Additional context**
The Divi theme uses a capital first letter, so its directory in wp-content is in fact uppercase, and this is what is not being accounted for when the sanitization is applied, it's lowercasing `Divi` to `divi` which is causing the `in_array` check to fail here:

https://github.com/woocommerce/woocommerce-admin/blob/master/src/API/OnboardingThemes.php#L171-L177

*and here:*

https://github.com/woocommerce/woocommerce-admin/blob/master/src/API/OnboardingThemes.php#L95-L104

The theme is sanitized, and lowercased.

```
$slug = sanitize_key( $theme ); // `Divi` becomes `divi`
```

```
$installed_themes = wp_get_themes(); // returns Divi
```

Then in either case it will fail:

```
if ( in_array( $slug, array_keys( $installed_themes ), true ) ) // $slug is `divi`, so it fails
```
*and*
```
if ( ! in_array( $theme, array_keys( $installed_themes ), true ) ) { // $theme is `divi`, so it fails
```

So, all that needs to change is the use of `sanitize_key` (because it force lowercases the value, and instead you could use:

```
$theme = preg_replace( '/[^a-zA-Z0-9_\-]/', '', $theme );
```

This is based on, and almost the same as, `sanitize_key`, just without the lowercasing.

Note, the implementation on lines ~171-177 seems to have a further bug as the sanitized value `$slug` is not used but `$theme` is instead... 
<img width="1066" alt="Screen Shot 2020-05-18 at 12 21 27 PM" src="https://user-images.githubusercontent.com/1163441/82251755-a4ace500-9902-11ea-92b6-1d302ac28b08.png">

**Comment by psealock** [comment]
Thanks for the bug report @Jronk !

Maybe we could `sanitize_key` each result of `wp_get_themes()` before comparison?

This seems like an easy fix we can address in a few weeks. Since you've already done the hard work and solved the issue, would you like to make a pull request? I'd be happy to review and test for you.

**Comment by travisseitler** [comment]
@psealock, I went ahead and made a quick pull request for this one, but my PR doesn't use @Jronk's `preg_replace` suggestion. I found a case in WP Core where they ran into the same issue with theme directory names, and my PR adopts the approach they took.

**Comment by ayubadiputra** [comment]
Sorry for the delay @psealock. I just rebased the PR and Travis & tests pass now.
