### ISSUE TITLE
Create a script to execute deltaDB automatically

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#4401]
**Is your feature request related to a problem? Please describe.**
Currently, to trigger the dbDelta method there are two options:
1. Modifying the value of `woocommerce_admin_version` in the `wp_options` table.
2. Having `WP CLI` installed, using wp option delete `woocommerce_admin_version`.

**Describe the solution you'd like**
It would be great to have a script (or something) to execute `dbDelta` automatically when we start the server or with a composer install/update.

Doing this we wouldn't have to force the execution manually.

**Comment by joelclimbsthings** [comment]
Closing this prior to the merge as per [our guidelines](https://teamisotope.wordpress.com/2021/12/24/issue-triage-grooming-leading-up-to-the-merge%ef%b8%8f/).
