### ISSUE TITLE
Looker: add event props as dimensions 

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4409]
Now that we already have a [global event prop](https://github.com/Automattic/wc-calypso-bridge/pull/536) that allows identifying if the user is an eCommerce plan user it would be great to add this as a dimension, allowing us to filter the Looks by eCommerce plan user or core user. This would be particularly useful in the [Activation](https://looker.a8c.com/explore/isotope_kpis/wc_store_creation?qid=puUun4IgpWrtKBPRmMFk9y&origin_space=362&toggle=vis) look and [User Retention](https://looker.a8c.com/explore/isotope_kpis/wc_active_stores?qid=dQklzKazl9dt2c9m4mpZ26&origin_space=362&toggle=vis) look.

I also would like to know if it's feasible to introduce some event props that we have from the store profiler as dimensions. Eg: Industry, number of products, revenue. 

Thanks

**Comment by pmcpinto** [comment]
@joshuatf do you have time during the upcoming days to take a look at adding this? Thanks

**Comment by joshuatf** [comment]
Will do @pmcpinto!

**Comment by pmcpinto** [comment]
@joshuatf I think you ended up not having time to check this during the cooldown, so I'll add it to this Cycle

**Comment by joshuatf** [comment]
Sounds good, @pmcpinto.  Working on it this week.

**Comment by joshuatf** [comment]
Close via 578-gh-looker
