### ISSUE TITLE
Orders table summary has incorrect totals

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#4410]
**Describe the bug**
I noticed this with WC 4.1.1 and updated the site to WC 4.2 RC see if the issue still existed. Initially what I noticed was that the returning customers total was low. Here's a MTD screenshot with the `Returning Customers` filter applied:

<img width="552" alt="Screen Shot 2020-05-20 at 10 25 45 AM" src="https://user-images.githubusercontent.com/343847/82454971-cf28aa80-9a88-11ea-8735-795977768ce5.png">

**Steps to Reproduce**
- Create an order using new billing information
- Check the orders report for the day to verify it shows as a `New` customer
- Create a second order using the same billing information
- Check the orders report 
  - The table shows one `New` and one `Returning` order
  - The summary shows `1 new customer` and `0 returning customers`

The current calculation for `returning customers` deducts the count of new customers from the total customers. While it is technically correct that the report only contains new customers, it's a confusing UX as the table shows returning customers. 

In a YTD report a store might have more than half the orders made by returning customers who placed their first order in that year.

**Comment by becdetat** [comment]
There's an error in your first query - status `on-hold` instead of `wc-on-hold` - which I think is skewing your results.

I ran this:

```
SELECT count(*) as number_of_orders,
count(distinct(customer_id)) as number_of_customers,
COUNT( DISTINCT( CASE WHEN returning_customer = 0 THEN customer_id END ) ) AS num_new_customers,
( COUNT( DISTINCT( customer_id ) ) -  COUNT( DISTINCT( CASE WHEN returning_customer = 0 THEN customer_id END ) ) ) AS num_returning_customers
FROM `wp_wc_order_stats`
WHERE date_created >= '2020-01-01'
and status in ('wc-completed','wc-processing','wc-on-hold')
```

which gives the same results as the report summary for the same period.

`num_new_customers` and `num_returning_customers` make sense to me and they total to `number_of_customers`, so I don't _think_ there is a discrepancy. What do you think?

**Comment by rrennick** [comment]
@becdetat good catch. I updated the description with the steps to reproduce.
