### ISSUE TITLE
Connnecting to WP.com account step: message should be centered

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4413]
**Describe the bug**

It feels like the message letting users know what would happen by connecting their site to WP.com account should be centered. Right now it is left aligned which feels odd considering that all other elements on the page are centered. 

**To Reproduce**

1. Complete OBW;
2. On the benefits screen, select to proceed with Jetpack;
3. You should be redirected to the step where you would connect your site to WP.com account;
4. See issue there:

![centered?](https://user-images.githubusercontent.com/19143190/82480136-5bdf6280-9aa1-11ea-8522-486ce3952da3.jpg)

**Expected behavior**

The message should be centered. 

**Screenshots**

Above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.4
* Browser: Chrome
* Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by becdetat** [comment]
Hi @juliaamosova 

This is off the merchant's site, on wordpress.com/jetpack - we don't control this in wc-admin:

![image](https://user-images.githubusercontent.com/224531/82524366-19398b00-9b72-11ea-94b4-46b3d5e1fab5.png)

I couldn't find the correct team but someone in Jetpack involved in the connect flow would be the ones to talk to.
