### ISSUE TITLE
Setup Checklist: Remove Jetpack requirements for WC Pay

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce-admin#4416]
With #3930, WooCommerce Payments began to be shown as a recommended payment method in the new store task list for US stores. But only if Jetpack was active and connected (at least once #4092 was fixed).

Once WooCommerce Payments has a working Jetpack DNA / connection package bundled in to connect to WordPress.com, it will no longer require the Jetpack plugin, so this requirement can be removed.

We can't be sure exactly when the Jetpack DNA work will be finalized. But we know we want to no longer require the Jetpack plugin as soon as that happens, given the boost it will provide for adoption.

### Proposed Solution

The best solution for handling this seems to be to have the WC Pay plugin handle the Jetpack dependency, rather than WC Admin / WC core (which is beholden to monthly release cycles). 

An initial version of this was put together in https://github.com/woocommerce/woocommerce-admin/pull/4332 by @dechov.

If we could include that in WC 4.3, then no other work should be required in WC / WC Admin to drop the requirement. Ideally, we'd ship it in the first possible release in case the Jetpack DNA work is finished in June.

### Alternative Solutions

The only alternative I see is to wait for the WC release _after_ the Jetpack connection work is finished. The risk there is, if the Jetpack work is finished late in the WC release cycle, say June 15, we'll miss out on a month or more of adoption (if the PR freeze for WC 4.3 is before June 15th, we wouldn't be able to ship until 4.4 in August).

The impact of every week missed is significant.

### Additional context

I'll add this to Hydra's Sprint 13 project board for WC Pay so they can review and work on it in the hopes that we can get something finalized well before the 4.3 PR freeze. But I'm opening it here as the work will go into WC Admin.

**Comment by vbelolapotkov** [comment]
For reference: **WooCommerce 2020.7 (4.3) PR freeze**
June 12, 2020

**Comment by timmyc** [comment]
@thenbrent I really like your proposed solution of WCPay controlling whether or not requirements have been met to display it in the Setup Checklist. This would also allow for a much easier rollout "activating" this task when new countries are supported too.

One thought - If we have an idea of which version of WCPay that this might be present in, we could even get started on this right away by adding in a "is_wc_pay_supported" type of setting in our `wcSettings` object. And have the code behind that do a version sniff of the wc pay plugin and method check of whatever the method in WCPay would be used to determine if a site is connected and in a supported location.

The fallback logic would just be what we have now - verify JP connected + US address.

That would require at the very least committing to a function name, but would allow this to get going well ahead of the code freeze.

**Comment by rrennick** [comment]
> we could even get started on this right away by adding in a "is_wc_pay_supported" type of setting in our wcSettings object. 

See https://github.com/woocommerce/woocommerce-admin/pull/4418 as it might do the trick.

**Comment by thenbrent** [comment]
> much easier rollout "activating" this task when new countries are supported too.

Good thinking! Definitely worth incorporating that into how we approach this so we don't face the same challenges with new countries down the line.

> have the code behind that do a version sniff of the wc pay plugin and method check of whatever the method in WCPay would be used to determine if a site is connected and in a supported location.

Would the sniff on the wp.org files or the plugin installed on the site?

The changes proposed in #4332 required the plugin to be installed, which was fine because the Jetpack installation & connection was handled after WC Pay was installed. To handle country availability, we'd need to have that info before the card is displayed (and the plugin is installed).

> That would require at the very least committing to a function name

Depending on the answer to the above, would a constant be suitable? That's the approach @dechov used in #4332.

We'd want to use something more generic than `WCPAY_BUILTIN_JETPACK_CONNECTION`, but we'd be able to commit to a constant quickly.

> If we have an idea of which version of WCPay that this might be present in, we could even get started on this right away by adding in a "is_wc_pay_supported" type of setting in our wcSettings object.

If a version number is required, we could look at committing to use certain version numbers for different features and countries in future.
