### ISSUE TITLE
Fatal error due to product variation removal

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-admin#4421]
**Affected customers**
2968918-zen

**Describe the bug**
Customer is getting this error:

> 2020-05-13T00:35:04+00:00 CRITICAL Uncaught Error: Call to a member function get_file_download_path() on boolean in .../wp-content/plugins/woocommerce-admin/src/API/Reports/Downloads/Controller.php:112
> Stack trace:
> 0 .../wp-content/plugins/woocommerce-admin/src/API/Reports/Downloads/Controller.php(59): Automattic\WooCommerce\Admin\API\Reports\Downloads\Controller->prepare_item_for_response(Array, Object(WP_REST_Request))
> 1 .../wp-includes/rest-api/class-wp-rest-server.php(1015): Automattic\WooCommerce\Admin\API\Reports\Downloads\Controller->get_items(Object(WP_REST_Request))
> 2 .../wp-includes/rest-api/class-wp-rest-server.php(342): WP_REST_Server->dispatch(Object(WP_REST_Request))
> 3 .../wp-includes/rest-api.php(306): WP_REST_Server->serve_request('/wc-analytics/r...')
> 4 .../wp-includes/class-wp-hook.php(287): rest_api_loaded(Object(WP))
> 5 .../wp-includes/class-wp-hook.php( in .../wp-content/plugins/woocommerce-admin/src/API/Reports/Downloads/Controller.php on line 112

This is happening here:
https://github.com/woocommerce/woocommerce-admin/blob/v1.1.3/src/API/Reports/Downloads/Controller.php#L112

This is due to they had a Simple product, switched it to Variable (with downloads), had sales, customers downloaded, and then they switched the product back to Simple again. They are now trying to run download reports and due to the orders have the variation in them they are getting a fatal error. 

**To Reproduce**

1. Create a variable product with 1 variation that has a download attached.
1. Add variation to cart, purchase, and then download file. 
1. Go back to product, switch to simple.
1. This may not be needed, but I did it... Add download to simple product, add to cart, purchase, and download that file.
1. Go to Analytics > Downloads, and the report will not load correctly and fatal error will be logged.

**Expected behavior**
I am not sure if we can obtain proper data for the reports here, especially since this shouldn't happen, but we could check to make sure we have a `$_product` object before trying to use its methods. 

**Screenshots**
![](https://d.pr/i/v5Itcn+)
Image Link: https://d.pr/i/v5Itcn

**Comment by jessepearson** [comment]
In the meantime, can we suggest a work around for the customer?

**Comment by rrennick** [comment]
@jessepearson The download data for the report comes from the core download tables. The Download cleanup tool might remove those records.

**Comment by jessepearson** [comment]
@rrennick If you're referring to the below tool, I just tried and that did not work.

![](https://d.pr/i/wBgLdT+)
Image Link: https://d.pr/i/wBgLdT

I also tried going to Analytics > Settings and deleting historical data and importing again, but that did not correct the issue, I still receive a fatal locally when trying to go to Analytics > Downloads.

**Comment by rrennick** [comment]
@jessepearson Thanks for the follow up. 

> I also tried going to Analytics > Settings and deleting historical data and importing again

The download data itself isn't imported.
