### ISSUE TITLE
Add a max width to advanced filters input controls

### ISSUE THREAD

**Issue by luizreis** [woocommerce/woocommerce-admin#4424]
**Describe the solution you'd like**
Some ReportFilter controls, especially `SelectControl`, would look better on larger screens if they have a max-width set.

**Should this be prioritized? Why?**
No, it's a visual enhancement and does not impact any functionality.

**Additional context**

![image](https://user-images.githubusercontent.com/7714042/82605225-f87e2f00-9b8b-11ea-9da2-956fbf75aa53.png)

h/t @vbelolapotkov, @LevinMedia

**Comment by becdetat** [comment]
Pretty sure this has been done now, as at 1.8.1:

![image](https://user-images.githubusercontent.com/224531/102305438-d0cd3900-3fab-11eb-8a68-29763e444211.png)
