### ISSUE TITLE
Date picker only disappears after an outside click if you focus it first

### ISSUE THREAD

**Issue by luizreis** [woocommerce/woocommerce-admin#4425]
**Describe the bug**
The date picker only disappears after an outside click if you focus it first.

**To Reproduce**

1. Navigate to the customers report and toggle the advanced filters 
2. Add a date filter, such as `Registered`
3. Click on the text input to open the date picker
4. Click outside of the date picker
4. It doesn't close
5. Click on the date picker and then click outside
6. It closes

**Expected behavior**
The date picker should close on an outside click, even if it was not clicked before.

**Screenshots**
https://d.pr/i/4MddR3

h/t @dechov

**Comment by pmcpinto** [comment]
I'm going to close this one as it seems that it was fixed on #4567
