### ISSUE TITLE
Activity Panel - improve event tracking

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4432]
Currently we keep track of the number of times that the Activity Panel is opened and we have extensive tracking in the inbox panel, but we don't know if and how the user is taking advantage of the other panels.

**Orders panel:** 

Event name: wcadmin_activity_panel_orders_begin_fulfillment
Event prop: NA
Description: when the user clicks in the "Begin fulfillment" button

Event name: wcadmin_activity_panel_orders_manage
Event prop: NA
Description: when the user clicks in the "Manage orders" button

Event name: wcadmin_activity_panel_order_number
Event prop: NA
Description: when the user clicks in the order number link

Event name: wcadmin_activity_panel_customer_name
Event prop: NA
Description: when the user clicks in the customer name link

**Stock:** 

Event name: wcadmin_activity_panel_stock_product_name
Event prop: NA
Description: when the user clicks in the product name link

Event name: wcadmin_activity_panel_stock_update_stock
Event prop: NA
Description: when the user clicks in the "Update stock" button

Event name: wcadmin_activity_panel_stock_save
Event prop: the numbe of products added to the inventory
Description: when the user clicks in the "Save" button

Event name: wcadmin_activity_panel_stock_cancel
Event prop: NA
Description: when the user clicks in the "Cancel" button

**Reviews:** 

Event name: wcadmin_activity_panel_reviews_learn_more
Event prop: NA
Description: when the user clicks in the "Learn More" button in the empty state

Event name: wcadmin_activity_panel_reviews_view_reviews
Event prop: NA
Description: when the user clicks in the "View reviews" button in the empty state

Event name: wcadmin_activity_panel_reviews_moderate
Event prop: NA
Description: when the user clicks in the "Moderate" button

Event name: wcadmin_activity_panel_reviews_product
Event prop: NA
Description: when the user clicks in the product name

Event name: wcadmin_activity_panel_reviews_customer
Event prop: NA
Description: when the user clicks in the customer name

**Comment by becdetat** [comment]
Estimate: 3, because of the number of places events need to be placed

**Comment by jeffstieler** [comment]
Estimate: 2. It's quite a few events, but I'd expect to do this in a little over a day tops.

**Comment by pmcpinto** [comment]
The top priorities in terms of events are:

**Orders panel:**
Event name: wcadmin_activity_panel_orders_begin_fulfillment
Event prop: NA
Description: when the user clicks in the "Begin fulfillment" button

**Stock:**
Event name: wcadmin_activity_panel_stock_update_stock
Event prop: NA
Description: when the user clicks in the "Update stock" button

**Reviews:**
Event name: wcadmin_activity_panel_reviews_moderate
Event prop: NA
Description: when the user clicks in the "Moderate" button

**Comment by mattsherman** [comment]
I'd estimate 2.

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm working on this issue and I have a question about the `Moderate` button in the Review panel

>Reviews:
>Event name: wcadmin_activity_panel_reviews_moderate
>Event prop: NA
>Description: when the user clicks in the "Moderate" button

Currently, the button's name is `Manage`, and that button is already being recorded under the event name `wcadmin_review_manage_click`. Also, we're sending the date when the review was created and its status.
Is it ok if I leave the button and event like that or should I update them?

**Comment by pmcpinto** [comment]
> Currently, the button's name is Manage, and that button is already being recorded under the event name wcadmin_review_manage_click. Also, we're sending the date when the review was created and its status.
Is it ok if I leave the button and event like that or should I update them?

Ah I didn't know that event existed. Let's leave it as it is right now. Thanks!
