### ISSUE TITLE
Problem with displaying dates when site language is set to Dutch

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-admin#4453]
**Describe the bug**
When site language is set to Dutch, all dates displayed in WooCommerce Admin are showing JJJJ instead of the year.

**To Reproduce**

1. Go to **Settings > General** in WP Admin;
2. Change **Site language** to **Netherlands**
3. Open any WooCommerce Admin page, like WooCommerce > Dashboard, or Analytics > Revenue;

**Expected behavior**
All dates are displayed correctly in full.

**Screenshots**
![Screenshot](https://d.pr/i/rYUcBp+)
Screenshot: https://d.pr/i/rYUcBp

**Desktop (please complete the following information):**

* OS: OS X 10.14.6
* Browser: Chrome
* Version: 81

**Comment by madeincosmos** [comment]
Reported in 3009825-zen

**Comment by psealock** [comment]
It looks like momentjs translations are incorrect for Dutch:
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/nl/default/?filters%5Bterm%5D=YYYY&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

`MMMM D, YYYY` will be `MMMM D, YYYY` not `MMMM D, JJJJ`

**Comment by anant1811** [comment]
Another report in 3030134-zen

**Comment by psealock** [comment]
I made suggestions to change on https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/nl/default/?filters%5Bterm%5D=YYYY&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

I'm not sure what the process is from here.

**Comment by louwie17** [comment]
It appears that the translations have [been updated](https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/nl/default/?filters%5Bterm%5D=YYYY&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) from `DD/MM/JJJJ` to `DD/MM/YYYY`.

I tried to reproduce it, but couldn't, year seems to render properly now (see screenshot).
<img width="1534" alt="Screen Shot 2020-11-25 at 10 55 19 AM" src="https://user-images.githubusercontent.com/2240960/100244119-f7e49d80-2f0c-11eb-8f4c-8e081727f004.png">
