### ISSUE TITLE
[GlobalStep - 4.2 RC1][Windows]: API Call error is displayed while setting up CBD Vertical On boarding Flow

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4456]
**Environment:**
Windows 10

**Steps to Reproduce:**
1. Create a site using Ninja tool.
2. Install all the plugins.
3. Tap on "Run the Setup wizard".
4. Complete Store Details.
5. On Industry page select "CBD and other hemp-driver products".
6. Complete all the introductory tabs i.e., Product types, Business details and Theme.
4. Go to dashboard.
5. Tap on Setup Payment.
6. Tap on "Setup up" button next to Square.
7. Observe that API call error is displayed.

**Note:** Able to reproduce 2/5 times

**Actual Result:**
API Call error is displayed while setting up CBD Vertical On boarding Flow

**Expected Result:**
API Call error should not be displayed while setting up CBD Vertical On boarding Flow.

![#26620](https://user-images.githubusercontent.com/41110392/83046442-a8f4a300-a064-11ea-8fa9-f1bb16adfbb8.png)

**Comment by tammullen** [comment]
Hi @gglobalstep 

Thank you for reporting the issue. WooCommerce Admin task list is being developed in another repository: https://github.com/woocommerce/woocommerce-admin.
I am going to move your bug report there so that the right team could take a look further.

**Comment by timmyc** [comment]
I feel this might be related to JN issues, but we also have work in-flight for this in #4473  so am closing this out.
