### ISSUE TITLE
Looker: include Home screen events on Looker

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4463]
We need to include the new events included in the home screen in some of our Looker dashboards, as some actions will become part of the user day-to-day activity:

wcadmin_home_quick_links_click
wcadmin_statsoverview_indicators_toggle
wcadmin_statsoverview_indicators_click
wcadmin_statsoverview_date_picker_update

Those events should be included in the following measures:
- Active, Casual, Core (WC Engagement Look)
- Active stores (WC user retention Look)

**Comment by joshuatf** [comment]
@pmcpinto these events have been added in Looker to the existing open PR.

**Comment by joshuatf** [comment]
Looker PRs are now merged.
