### ISSUE TITLE
Print Shipping Label step - event tracking missing

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4464]
The event `wcadmin_tasklist_shipping_label_printing` was working properly a couple of months ago, but I was checking it on Tracks and I'm not able to get any info about it. It seems that it was removed.

I'm not sure if this is related to #4372

**Comment by pmcpinto** [comment]
@joshuatf when you have a bit of time, can you check if this is related to that bug in the Shipping step? Thanks!

**Comment by joshuatf** [comment]
@pmcpinto Just ran through this on `master` and received the expected event and props in both cases (skipping and installing).  

You're probably right in that this issue is likely related to https://github.com/woocommerce/woocommerce-admin/issues/4372 since this step wasn't shown if Jetpack was active, but not connected before.  But we can leave this issue open for now to make sure it's really resolved.

**Comment by pmcpinto** [comment]
Thanks for checking this. 

Yep, let's leave it open and I'll take a look at this event once the Core version that includes that fix is ready.

**Comment by pmcpinto** [comment]
This is a bit weird - the event seems to be triggered but then I'm not seeing it in Tracks 🤔 

<img width="1440" alt="Captura de ecrã 2020-08-14, às 10 23 32" src="https://user-images.githubusercontent.com/3380168/90235290-f806d480-de18-11ea-970e-6fa4e1db57fb.png">

**Comment by joshuatf** [comment]
I see the event in tracks (have to filter by rejected events though).  Can you double check and see if you're still not able to see it, @pmcpinto?

<img width="665" alt="Screen Shot 2020-08-17 at 3 27 15 PM" src="https://user-images.githubusercontent.com/10561050/90436184-e81d1800-e0d8-11ea-8090-43675297b503.png">

**Comment by psealock** [comment]
>have to filter by rejected events though

Yup, camelCase is not allowed.

https://github.com/woocommerce/woocommerce-admin/blob/d5ef23371e04a1602a1dae5d33e6c1a5e4cbbfb0/client/task-list/tasks/shipping/index.js#L254-L257

Estimate: 1

**Comment by pmcpinto** [comment]
> I see the event in tracks (have to filter by rejected events though). Can you double check and see if you're still not able to see it, @pmcpinto?

Thanks for checking. Now I'm seeing them on the rejected list.
