### ISSUE TITLE
Remove GoogleFonts from Woocommerce admin (fonts.googleapis.com)

### ISSUE THREAD

**Issue by jasomdotnet** [woocommerce/woocommerce-admin#4472]
Hi,
I like new Woo admin, great job! 

There is one thing that bothers me. I would be happy if you removed GoogleFonts. I have several reasons for that:

1. They are **not essential, just a cosmetic**. 
2. It is **additional request** for external domain (it **slows down the performance**).
3. It's (potential) **3th party tracker**.
4. Requests to Google's servers **increase GDPR complexity**.
5. Our company's **firewall block similar requests** so I see [this](https://i.imgur.com/m3omwX4.png).

 Suggested solutions:

1. **Use native Wordpress / Woocomerce** [icons](https://developer.wordpress.org/resource/dashicons/#menu) instead.
2. **Bundle the icon font with Woocommerce plugin**
3. Give people an **option to opt-our from using GoogleFonts** in Woo settings.

What's do you think?

**Comment by jasomdotnet** [comment]
@rrennick ok, so issue was reported, transferred to proper place and we will see what is going to happen next.

**Comment by timmyc** [comment]
@jameskoster given we use quite a few material icons throughout, curious for your thoughts here.

**Comment by jameskoster** [comment]
We should transition all icons to use the [WordPress Icons package](https://github.com/WordPress/gutenberg/tree/master/packages/icons). Once we've done that, we can remove any reliance on the Material icon font.

PRs are most welcome! :)

**Comment by jasomdotnet** [comment]
IMHO, since Woocommerce has additional [Conditionals Tags](https://docs.woocommerce.com/document/conditional-tags/), there should be additional svg pictograms aside [default WordPress ones](https://developer.wordpress.org/resource/dashicons/#menu).

**Comment by jasomdotnet** [comment]
Still an issue.

**Comment by samueljseay** [comment]
Thanks so much for your patience and for raising this @jasomdotnet 

We've removed GoogleFonts in #6343 and the fix will be in an upcoming release.
