### ISSUE TITLE
Some customers are not imported to Customers Report

### ISSUE THREAD

**Issue by webmaster444** [woocommerce/woocommerce-admin#4475]
Some customers in Users are not showing in Customers Report
In Users page it shows 4000+ customers but in woocommerce/customers page is showing only 50+ customers.
I have checked that db wc_customer_lookup and it has only 50+ rows.

Not sure why this is happening.

wp_users table has 5000+ rows and I already filtered by role and it has 4000+ customers.

Thanks.

**Comment by timmyc** [comment]
Hello @webmaster444 - I believe this might be related to the report in #4478 - but can you confirm that customers showing in the "Users" page and not showing in the customers report have never placed an order on the site? Customer table entries are driven by users ( and guest checkouts ) that actually place an order.

**Comment by timmyc** [comment]
@webmaster444 since we haven't heard back from you on this issue, I'm going to close out the issue. Please do feel free to comment again if we can assist with anything.
