### ISSUE TITLE
Store Profiler - Industry step: add two additional industries as options

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4476]
Since we implemented an input field when the user selects Other, there are 2 areas that stand out: 
- Education & learning
- Travel & tourism

So in order to have a clear picture of how many users are really operating in those industries, we should display them as options. They can be placed before the `Other` option.

**Comment by timmyc** [comment]
Estimate: 1

**Comment by joshuatf** [comment]
Agreed on estimate within WCA.  On a side note, we may want to look into how this is handled on WooCommerce.com.  See https://github.com/Automattic/woocommerce.com/pull/7730 for what happens each time we make a change to these options.

**Comment by mattsherman** [comment]
Agree with the estimate of 1. Doesn't seem like there is any hidden complexity here.
