### ISSUE TITLE
New inbox message: Selling online courses 

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4477]
**Title:** Do you want to sell online courses?
**Content:**  Online courses are a great solution for any business that can teach a new skill. Since courses don’t require physical product development or shipping, they’re affordable, fast to create, and can generate passive income for years to come. In this article, we provide you more information about selling courses using WooCommerce.
**Segmentation:** New users that selected `education-learning` as `store_industry`on `wcadmin_storeprofiler_store_industry_continue` (#4476 needs to be implemented first)
**Timing:** When they reach the home screen after coming through the store profiler
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/posts/how-to-sell-online-courses-wordpress/?utm_source=inbox
**CTA label:** Learn more
**Type:** promotional

**Comment by timmyc** [comment]
Removing this from the milestone since we won't be able to get to this prior to code freeze.

**Comment by becdetat** [comment]
This could just as easily be implemented as a remote notification once that goes live.

Either way my estimate is 1.

**Comment by becdetat** [comment]
@pmcpinto we don't have a 'promotional' type, but we do have a marketing type that doesn't add the note if the user has opted out of marketplace suggestions. Would that be the appropriate type here?

**Comment by pmcpinto** [comment]
Yep that works perfectly. Thanks!
