### ISSUE TITLE
New customers are not seen under WooCommerce > Customers

### ISSUE THREAD

**Issue by wronahau** [woocommerce/woocommerce-admin#4478]
**Describe the bug**
All registered customers are not visible in backend section WooCommerce >Customers.
They are visible in Users > All Users.
Shipping is turn off in WooCommerce settings as I am selling only Downloadable products.

**To Reproduce**
1. In WooCommerce configuration turn off shipping
2. Register some random customer
3. Open backend/admin panel and go to  Users > All Users, you will see customers. It's OK.
4. Now go to WooCommerce>Customers in backend's menu. They are not visible

**Screenshots**

**Expected behavior**
Customers should be visible in WooCommerce>Customers. 
They are only visible there if I edit them in backend and add a shipping address.

**Isolating the problem (mark completed items with an [x]):**
- [yes ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. 
- [ It doesn't matter what theme.] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). 
- [Yes ] I can reproduce this bug consistently using the steps above. 

**WordPress Environment**
<details>
```

WordPress address (URL): |   | http://hdrmapsw.localhost
-- | -- | --
Site address (URL): |   | http://hdrmapsw.localhost
WooCommerce version: |   | 4.1.1
WooCommerce REST API package: |   | 1.0.7 /mnt/c/www/hdrmapsw/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
WooCommerce Blocks package: |   | 2.5.16 /mnt/c/www/hdrmapsw/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler package: |   | 3.1.6 /mnt/c/www/hdrmapsw/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin package: |   | 1.1.3 /mnt/c/www/hdrmapsw/wp-content/plugins/woocommerce/packages/woocommerce-admin
Log directory writable: |   | /mnt/c/www/hdrmapsw/wp-content/uploads/wc-logs/
WordPress version: |   | 5.4.1
WordPress multisite: |   | –
WordPress memory limit: |   | 4 GB
WordPress debug mode: |   |  
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by anekola** [comment]
I'm tracking down an issue with this page as well – it's also loading completely blank for me.  I'm getting a Javascript error on this page, but no other pages for what it's worth. I'll update if I figure anything else out.

`Uncaught TypeError: Cannot read property 'bind' of undefined
    at wc.app.0 (index.min.js?ver=1.2.3:2)
    at index.min.js?ver=1.2.3:2`

**Comment by timmyc** [comment]
@anekola can you please open up a new issue with details of your problem specifically. Also please include a WooCommerce System Report.

@wronahau I believe this is the expected behavior based upon the current logic of the customers report. Entries in the customers reporting table are created based upon order creation events. So if a user just registers for the site, but does not place an order, there won't be any history of them as a customer since they have never placed an order.

cc @pmcpinto

**Comment by pmcpinto** [comment]
cc @garymurray @jconroy

**Comment by garymurray** [comment]
@wronahau I just wanted to check what your expectation was here with regards to users registered on your WordPress site, and customers registered by WooCommerce.

Currently, if someone creates an account during the checkout flow (even if they don't end up purchasing) they are added to the Customer list in WooCommerce - however, if you just register a new WP user - they do not appear in the Customer list - as they are not really WooCommerce customers.

Are you encountering a bug where someone going through the checkout flow and creating an account is not appearing - or as you expecting to see **all** WP users in the WooCommerce Customers list?

**Comment by timmyc** [comment]
Since we haven't heard back from @wronahau I'm going to close this issue out.
