### ISSUE TITLE
WooCommerce Admin pollutes WP Rest API Cache

### ISSUE THREAD

**Issue by joelpierre** [woocommerce/woocommerce-admin#4482]
**Describe the bug**
When the WP Rest API Cache plugin is activate WooCommerce Admin endpoints seem to take over completely and ruin the rest api cache and I get this error:
```
Fatal error: Uncaught Error: Call to a member function get_status() on array
in W:\xampp\htdocs\example\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\src\API\Reports\PerformanceIndicators\Controller.php on line 136
```

**To Reproduce**
Install WooCommerce (latest stable), WooCommerce Admin (latest stable), WP Rest API Cache plugin (by Aires Gonçalves) call any wp-json endpoint and the following will be shown after subsequent requests:

```
[
  {
     "slug": "performance-indicators",
     "description": "Batch endpoint for getting specific performance indicators from `stats`. 
    endpoints.",
"path": "/wc-analytics/reports/performance-indicators",
"_links": {
"self": [
{
"href": "https://www.example.com/wp-json/wc-analytics/reports/performance-indicators"
}
],
"report": [
{
"href": "/analytics/performance-indicators"
}
],
"collection": [
{
"href": "https://www.example.com/wp-json/wc-analytics/reports"
}
]
}
},
```

**Expected behavior**
I don't expect this endpoint to interfere with other rest api routes.

**Additional context**
I am using Wordpress and WooCommerce for a completely headless store so ideally I want to be able to cache responses to increase performance.

If you require more information let me know.

**Comment by timmyc** [comment]
@joelpierre thanks for the detailed report. I'm currently having issues reproducing this bug after following the steps above. I tried endpoints from WordPress core ( i.e. wp/v2/posts ) and the response looked okay.

/cc @jeffstieler in case anything might catch your eye here with your recent work on REST optimizations.

**Comment by joelpierre** [comment]
Hey @timmyc I can re-enable in my test environment and give you the api endpoint if that helps? But it is weird that the cached result includes wc-analytics endpoints

**Comment by timmyc** [comment]
@joelpierre that would be helpful since I can't reproduce myself. I'm a bit perplexed as to why the caching would be hanging on to that one wc-analytics endpoint response. Granted I'm not familiar with that caching plugin or how it is implemented.

**Comment by joelpierre** [comment]
@timmyc - [this is a route you can test](https://staging.gipsyhillbrewtech.net/wp-json/wp/v2/pages?slug=home) as you can see not the home page but rather wc-admin data is being returned. The only thing I have enabled is the WP Rest API Cache plugin if I disable it then it works likewise if I disable woocommerce the cache plugin works...?

**Comment by timmyc** [comment]
@joelpierre - thanks for that example. So I just setup a brand new site with only WooCommerce 4.2, and the WP REST API Cache plugin.

I setup a page with the slug of `home` to fully emulate the setup you have, and I'm still not seeing the same bug:

https://whispering-viper.jurassic.ninja/wp-json/wp/v2/pages?slug=home

Is there any sort of configuration that you have to do on the caching plugin? Or is there a way to omit a REST API namespace from being cached? Wondering if that might be an option to configure the analytics namespace to not be cached.

**Comment by joelpierre** [comment]
Sorry been busy, I am not sure what is is. I have spun up a few instances myself and get hit with the same error. Admittedly the Rest API Cache plugin hasn't been touched in a long while. However I still don't expect the type of response I am getting.
