### ISSUE TITLE
Analytics by Category is using wrong term_taxonomy_id = category_id relation.

### ISSUE THREAD

**Issue by smazur** [woocommerce/woocommerce-admin#4492]
**Describe the bug**

I got wrong analytics report by category. After digging the code I found that there is wrong left join clause for category relations. Here it is:

https://github.com/woocommerce/woocommerce-admin/blob/41baa85d4705e58e0e8a84ce40a1cb6b0b597c1e/src/API/Reports/Categories/DataStore.php#L97

So tables are joined on `term_taxonomy_id = category_id` what is wrong as `term_taxonomy_id` may not match `category_id`.

For some reason we have mismatching `term_taxonomy_id` and `term_id` in `term_taxonomy` table.

**Comment by timmyc** [comment]
Thanks for the report @smazur

**Comment by jeffstieler** [comment]
> For some reason we have mismatching `term_taxonomy_id` and `term_id` in `term_taxonomy` table.

Is it possible that your store has been around since WordPress 4.2 and the mismatched IDs are terms that have yet to be split? See: https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/

Either way, we should be able to correct this.

**Comment by slaFFik** [comment]
@jeffstieler Yes, that could be it. The project is live since WordPress 3.6 (perhaps even 3.7) and whatever latest WooCommerce was at that time (2.0 or so).
