### ISSUE TITLE
New inbox message: Complete WCPay/Stripe setup 

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4494]
Considering that a good amount of users churn when they're redirected to Stripe to complete the setup, it would be useful to trigger an inbox notification reminding them to finish it. We know when they click to install Stripe or WCPay and I'm wondering if there's an easy way to identify if the setup is completed, in order to avoid targeting users that already completed it cc @thenbrent @allendav  

**Title:** Complete the [Stripe/WooCommerce Payments] setup and start accepting credit and debit cards on your store
**Content:**  tbd
**Segmentation:**
**Timing:** tbd
**Cadence:** once
**CTA leads to:** tbd
**CTA label:** Complete setup
**Type:** tbd

**Comment by thenbrent** [comment]
> I'm wondering if there's an easy way to identify if the setup is completed, in order to avoid targeting users that already completed it

Yes, there is. I believe the `WC_Payment_Gateway_WCPay::needs_setup()` method is the best option, but correct me if I'm wrong @allendav.

See also some previous discussion on this here: https://github.com/woocommerce/woocommerce-admin/pull/4145#issuecomment-630240743 and woocommerce/woocommerce#32277
