### ISSUE TITLE
Data visualization problem : all datas on 0 🤔

### ISSUE THREAD

**Issue by vilm725** [woocommerce/woocommerce-admin#4514]
**Describe the bug**
Hi everyone 👋🏼

When I go to woocommerce analytics, the payment information is not displayed: all the data is at 0. It's the same for new customers, as for old data.

 You can see it in the images below:

![1](https://user-images.githubusercontent.com/64069744/83972489-c5080800-a8e0-11ea-90bc-e70cf9da4e4a.png)
![2](https://user-images.githubusercontent.com/64069744/83972491-c89b8f00-a8e0-11ea-96da-747401a5d06e.png)

I've test import and save in .har my console :
![import](https://user-images.githubusercontent.com/64069744/83972517-d6511480-a8e0-11ea-954b-b2c22b23af91.png)

Google Drive link (.har not support in github) : [https://drive.google.com/file/d/1FIwSnnWMnHp6clP3RmRWt9FkQEhEsjAi/view?usp=sharing](https://drive.google.com/file/d/1FIwSnnWMnHp6clP3RmRWt9FkQEhEsjAi/view?usp=sharing)

** Plugin **
All plugins desactivated except WooCommerce
![3](https://user-images.githubusercontent.com/64069744/83973033-fe8e4280-a8e3-11ea-8271-f7f73f853f49.png)

- [x] Add in my funtioncs.php add_filter( 'woocommerce_analytics_disable_action_scheduling', '__return_true' );

**Expected behavior**
Display the informations of client (Gross Sales, Net Sales, Total Sales, etc)

**Desktop (please complete the following information):**
* Windows 10 v2004
* Chrome Version 83.0.4103.97 (Build officiel) (64 bits)
* WooCommerce 4.2.0

<details>
<summary>WordPress Environment</summary>
`
### WordPress Environment ###

WordPress address (URL): https://validestapaces.local
Site address (URL): https://validestapaces.local
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Win32)
PHP Version: 7.4.1
PHP Post Max Size: 1 000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Taille totale de la base de données: 33.41MB
Taille de la base de données: 28.61MB
Taille de l’index: 4.80MB
wp_woocommerce_sessions: Données : 0.03MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.25MB + Index : 0.14MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.06MB + Index : 0.11MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
wp_caos_webfonts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_caos_webfonts_subsets: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.11MB + Index : 0.09MB + Moteur InnoDB
wp_es_deliverreport: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_es_emaillist: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_es_notification: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_es_sentdetails: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_failed_jobs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailchimp_carts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailchimp_jobs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_nxs_log: Données : 0.11MB + Index : 0.00MB + Moteur InnoDB
wp_nxs_query: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_options: Données : 3.05MB + Index : 0.13MB + Moteur InnoDB
wp_pmxe_exports: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_pmxe_google_cats: Données : 0.39MB + Index : 0.00MB + Moteur InnoDB
wp_pmxe_posts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_pmxe_templates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_postmeta: Données : 8.52MB + Index : 1.95MB + Moteur InnoDB
wp_posts: Données : 2.52MB + Index : 0.14MB + Moteur InnoDB
wp_queue: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_rank_math_404_logs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_rank_math_internal_links: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
wp_rank_math_internal_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_rank_math_redirections: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
wp_rank_math_redirections_cache: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_rank_math_sc_analytics: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_sib_model_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_sib_model_users: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_tm_taskmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_tm_tasks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_usermeta: Données : 0.13MB + Index : 0.11MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wcpdf_invoice_number: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_avatars_cache: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_comments_subscription: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.09MB + Index : 0.06MB + Moteur InnoDB
wp_wc_feedback_forms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_follow_users: Données : 0.02MB + Index : 0.13MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_phrases: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_users_rated: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_users_voted: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfblockediplog: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
wp_wfblocks7: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wfconfig: Données : 4.52MB + Index : 0.00MB + Moteur InnoDB
wp_wfcrawlers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wffilechanges: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wffilemods: Données : 3.52MB + Index : 0.00MB + Moteur InnoDB
wp_wfhits: Données : 0.25MB + Index : 0.08MB + Moteur InnoDB
wp_wfhoover: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wfknownfilelist: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
wp_wflivetraffichuman: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wflocs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wflogins: Données : 0.19MB + Index : 0.06MB + Moteur InnoDB
wp_wfnotifications: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfpendingissues: Données : 0.13MB + Index : 0.06MB + Moteur InnoDB
wp_wfreversecache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfsnipcache: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wfstatus: Données : 0.13MB + Index : 0.09MB + Moteur InnoDB
wp_wftrafficrates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wpfm_backup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_yoast_seo_links: Données : 0.08MB + Index : 0.02MB + Moteur InnoDB
wp_yoast_seo_meta: Données : 0.22MB + Index : 0.00MB + Moteur InnoDB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 299
custom_css: 3
elementor_library: 44
elementor-popup: 2
es_template: 2
feedzy_categories: 1
nav_menu_item: 8
oembed_cache: 18
page: 24
post: 50
product: 7
product_variation: 4
revision: 63
shop_coupon: 9
shop_order: 120
wpdiscuz_form: 1
wprss_feed: 1
wprss_feed_item: 9
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

WooCommerce PayPal Checkout Gateway: par WooCommerce – 2.0.2 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.2.0
WooCommerce Stripe Gateway: par WooCommerce – 4.4.0 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.2.0
WooCommerce Sendinblue Newsletter Subscription: par Sendinblue – 1.2.23 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.2.0
WooCommerce: par Automattic – 4.2.0

### Inactive Plugins (28) ###

Advanced Gutenberg Blocks: par maximebj – 1.9.8
All-in-One WP Migration: par ServMask – 7.23
All-in-One WP Migration File Extension: par ServMask
Inc. – 1.6

Asset CleanUp: Page Speed Booster: par Gabriel Livan – 1.3.6.4
Compress JPEG & PNG images: par TinyPNG – 3.2.1
Customer Reviews for WooCommerce: par Customer Reviews – 3.111 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.2.0
Disable Cart Fragments: par LittleBizzy – 1.3.0 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.2.0
Duplicate Page: par mndpsingh287 – 4.2
DynamicConditions: par RTO GmbH – 1.4.6
Elementor: par Elementor.com – 2.9.11
Elementor Pro: par Elementor.com – 2.9.5
Facebook for WooCommerce: par Facebook – 1.11.4
Google Tag Manager for Wordpress: par Thomas Geiger – 1.11.4 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.2.0
GutenBee: par The CSSIgniter Team – 2.4.0
Gutenberg: par Gutenberg Team – 8.2.1
ManageWP - Worker: par GoDaddy – 4.9.6
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: par Sendinblue – 2.9.16
Official Facebook Pixel: par Facebook – 2.0.2
Popup Trigger URL for Elementor Pro: par Suki WordPress Theme – 1.0.3
Rank Math SEO: par Rank Math – 1.0.43.1
Safe SVG: par Daryll Doyle – 1.9.9
Send Images to RSS: par Robin Cornett – 3.3.2
Wordfence Security: par Wordfence – 7.4.7
Worth The Read: par Well Done Marketing – 1.6
wpDiscuz: par gVectors Team – 7.0.2
WP Rocket: par WP Media – 3.5.5.1
WP Search with Algolia: par WebDevStudios – 1.3.0
WPS Hide Login: par WPServeur
NicolasKulka
tabrisrp – 1.5.6

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

1&1 Product Subdomain: par 1&1 – 1.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #1208 - /fiche-paces-fiche-paces-gratuite-fiche-anatomie/
Panier: ❌ La page ne contient pas le code court.
Validation de la commande: ❌ La page ne contient pas le code court.
Mon compte: ❌ La page ne contient pas le code court.
Conditions générales de vente et d’utilisation: #1291 - /cgv/

### Theme ###

Name: Twenty Seventeen
Version: 2.3
Author URL: https://wordpress.org/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Terminé: 114
Oldest: 2020-05-08 11:06:29 +0200
Newest: 2020-06-07 17:24:54 +0200

En attente: 1
Oldest: 2020-06-14 12:38:17 +0200
Newest: 2020-06-14 12:38:17 +0200

`
</details>

**Comment by timmyc** [comment]
@vilm725 I don't think you should have to add the filter for `woocommerce_analytics_disable_action_scheduling`, and wondering if that might actually be what is causing no historic data to appear. Can you try removing that filter and re-running the historical data import?

**Comment by vilm725** [comment]
Hi @timmyc 👋🏼

I've test this filter in my server test (http://51.210.120.198), I've deleted the filter immediately. I would like to see if after desactived filter, WAnalytics go working.

I wanted to solve this problem, **which has been going on for several months**, but this time in a local server (LocalByFlyWheel or my vps http://51.210.120.198), so as not to slow down my site.

The (production) website continue to accept paiement, you can see a multiple paiements :
![commande](https://user-images.githubusercontent.com/64069744/84240301-1f31e480-aafe-11ea-9afb-08a01ecba246.png)

When I would like see the analytics, to have an idea what's the best product sell, or simply to export all commands in CSV, **All Hitoric Data**, not just the paiement of today or yesterday display 0 in all  tables :
![woocommerce analytics](https://user-images.githubusercontent.com/64069744/84240441-4be5fc00-aafe-11ea-89a4-26b7dea7fcfd.png)
![wanalytics](https://user-images.githubusercontent.com/64069744/84240720-b9922800-aafe-11ea-83a8-801230f487ea.png)

For several months, despite the updates, this problem has not been resolved on my side.

Have you an idea ? 🤔

Export my website in LocalByFlyWheel  allow me tot test more things withiyt risking anything. Don't hesitate to share your opinions with me

**Comment by timmyc** [comment]
@vilm725 Removing the filter should allow for analytics to populate using ActionScheduler as background jobs, and population of historic data requires ActionScheduler to be operational. Based off the system report you sent, it looks like there are not a large number of pending ActionScheduler actions, so it is quite odd indeed.

Just to verify, have you tried re-importing the historical data?

**Comment by vilm725** [comment]
Hi @timmyc  👋🏼

First of all, thank you to be patient with this problem, it's not evident ... And sorry for my bad english.

As I said in my last post, I've delete the filtre in my functions.php (add_filter( 'woocommerce_analytics_disable_action_scheduling', '__return_true' );). Basically, I wanted to activate it, in order to deactivate it and see if the woocommerce scheduling system will re-operate in a normal way.

I've also have try to re-import data, but not work. Console display :
![{EDA5238A-CF8B-41A8-ABE9-832328D599C2}](https://user-images.githubusercontent.com/64069744/84355498-03dcdd00-abc3-11ea-81a9-c0b38c43175a.png)

My WooCommerce ActionScheduler :
![1-pendingactions](https://user-images.githubusercontent.com/64069744/84355328-b3657f80-abc2-11ea-90d4-b93f2c598862.png)

I've test in my vps sandbox server (http://51.210.120.198/) and in my production website.

When I go in WooCommerce Report, I can visualize all orders :
![woocommerce-report](https://user-images.githubusercontent.com/64069744/84355725-5fa76600-abc3-11ea-8ee8-227ef45193c9.png)

WooCommerce Report can visualize all orders and not WooCommerce Admin 🤔 ?

Do you think it's possible to desactivate WooCommerce Admin and re-install ?

**Comment by vilm725** [comment]
Hi everyone 👋🏼😃 

My problem with displaying data in the Woocommerce Admin table is still relevant.
Do you have a solution ?

**Comment by vilm725** [comment]
Hi 👋🏼 
Have you a solution, please ?

**Comment by timmyc** [comment]
@vilm725 sorry outside of disabling all other plugins on the site outside of WooCommerce, and using a theme like Storefront or twentytwenty it is really difficult for us to provide additional ideas without having direct access to the data/site. I would advise you to try and seek support in [the forums](https://wordpress.org/plugins/woocommerce/) or if you have any paid extensions through the WooCommerce.com marketplace, to [open up a support request](https://woocommerce.com/contact-us/). I'm going to close out this issue since this repository is more focused around development of features and we are not setup to provide direct customer support for environment specific bugs.
