### ISSUE TITLE
PHP Fatal error: require_once(): Failed opening required '.../woocommerce/packages/woocommerce-admin/src/Notes/WC_Admin_Notes_Welcome_Message.php'

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#4520]
**Describe the bug**
Based on https://wordpress.org/support/topic/php-fatal-error-after-update-to-4-2/ I noticed that `use \Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Welcome_Message;` has been added as part of https://github.com/woocommerce/woocommerce-admin/pull/4143, but I don't see the respective note. That being said, it could not have come from that PR, since it was merged only 4 days ago, while 4.2 is older and includes WCA 1.2.3.

Maybe it's related to https://github.com/woocommerce/woocommerce-admin/issues/1981 / https://github.com/woocommerce/woocommerce-admin/pull/2063?

**Comment by timmyc** [comment]
Thanks @peterfabian , I'm wondering if that might have been a merge conflict mistake. @becdetat could you look into this please?

**Comment by becdetat** [comment]
The `use` statement was definitely a merge conflict mistake however it wouldn't have caused this error - you could do `use \Foo\Bar;` and it wouldn't cause an error until you tried to use `Bar` in the code; even then it would be a different error. The message was removed by @mattsherman in #4182 and I can't see how this error could happen in that PR either. I'll dive deeper into this.

**Comment by becdetat** [comment]
I still can't see anything that could cause this in #4182. I can't even reproduce it. When [googling the error](https://www.google.com/search?rlz=1C5CHFA_enAU889AU889&q=autoload_packages+failed+opening+required&nfpr=1&sa=X&ved=2ahUKEwi92evT3_jpAhUwxzgGHQimDfAQvgUoAXoECAwQJw&biw=1792&bih=1041) the only relevant result is the original report. I'm at a loss as to what could have caused this.

**Comment by timmyc** [comment]
Fixed in #4550
