### ISSUE TITLE
Task list - group tasks

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#4529]
I've been playing with the task list feature for a while now and feel quite strongly that we should visually group complete / incomplete tasks. The zebra striping effect that occurs if you work through tasks in "the wrong order" is a bit disorientating. This issue will become more prominent when we implement the more aggressive smart defaults we've been talking about to preconfigure tasks. 

![tasks](https://cldup.com/4brh4sFXYM-2000x2000.png)

Ordering the tasks this way will also be beneficial for folks who navigate via keyboard or screen-reader, to have quicker access to incomplete tasks as well.

**Comment by joshuatf** [comment]
We can pretty easily sort by the `completed` property in tasks in `getAllTasks`.

Estimate: 1
