### ISSUE TITLE
Inconsistent color themes and style regressions

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#4544]
**Describe the bug**

There are many different (and clashing) color themes at play in `master` now (see screenshots). We need to decide what colors should replace the purples and pinks. (cc: @jameskoster)

Additionally there are style regressions that need to be fixed.

**Screenshots**

![Screen Shot 2020-06-10 at 1 31 32 PM](https://user-images.githubusercontent.com/63922/84311495-02f76d00-ab29-11ea-9838-f8c36edab946.png)

![Screen Shot 2020-06-10 at 1 31 44 PM](https://user-images.githubusercontent.com/63922/84311496-03900380-ab29-11ea-8ad3-b0d34eff43ff.png)

![Screen Shot 2020-06-10 at 1 32 00 PM](https://user-images.githubusercontent.com/63922/84311497-03900380-ab29-11ea-849e-ab5805b5b11d.png)

![Screen Shot 2020-06-10 at 1 44 30 PM](https://user-images.githubusercontent.com/63922/84311498-04289a00-ab29-11ea-9e23-2196c62575ce.png)

![Screen Shot 2020-06-10 at 1 44 59 PM](https://user-images.githubusercontent.com/63922/84311499-04289a00-ab29-11ea-8f05-874d90da30c6.png)

![Screen Shot 2020-06-10 at 2 26 05 PM](https://user-images.githubusercontent.com/63922/84311500-04289a00-ab29-11ea-878c-875e420132f4.png)

![Screen Shot 2020-06-10 at 2 26 33 PM](https://user-images.githubusercontent.com/63922/84311502-04c13080-ab29-11ea-991e-ae173430e30a.png)

![Screen Shot 2020-06-10 at 2 26 58 PM](https://user-images.githubusercontent.com/63922/84311503-04c13080-ab29-11ea-9449-b498f5154b1a.png)

![Screen Shot 2020-06-10 at 2 27 17 PM](https://user-images.githubusercontent.com/63922/84311505-04c13080-ab29-11ea-8006-603e389a6736.png)

![Screen Shot 2020-06-10 at 2 29 03 PM](https://user-images.githubusercontent.com/63922/84311507-0559c700-ab29-11ea-87ec-e3f3e24d15f6.png)

![Screen Shot 2020-06-10 at 2 30 13 PM](https://user-images.githubusercontent.com/63922/84311510-0559c700-ab29-11ea-849e-67f479afa44b.png)

![Screen Shot 2020-06-10 at 2 30 35 PM](https://user-images.githubusercontent.com/63922/84311512-0559c700-ab29-11ea-8310-bc5e82c4d682.png)

![Screen Shot 2020-06-10 at 2 32 19 PM](https://user-images.githubusercontent.com/63922/84311513-0559c700-ab29-11ea-98ae-26c503b4d147.png)

![Screen Shot 2020-06-10 at 2 40 36 PM](https://user-images.githubusercontent.com/63922/84311514-05f25d80-ab29-11ea-8896-39c9a09d4b07.png)

**Comment by jameskoster** [comment]
As @psealock says, in most cases we should be using `$theme-color` for any accent colors in our own components.

Ideally for core components - things like checkboxes, toggles, tabs, buttons, etc - we simply remove any overrides we've added and utilise their included styles.

For clarification around which colors to use for our own unique components (things like check list items, summary numbers, etc), please refer to [Figma](https://www.figma.com/file/Pfw5Qa1UOw03RiJere3Wlo/Automattic-Components?node-id=4533%3A0).

Text links should match core. Without looking I'm not sure exactly which color is used there, but highly likely to be `$theme-color` :)

**Comment by timmyc** [comment]
One more area looking a bit off too - and mentioned to @octaedro in a DM too:

![image](https://user-images.githubusercontent.com/22080/84450593-6951bd80-ac05-11ea-8172-2c13025dda65.png)

Thanks for adding this issue Jeff, I saw all the OBW on a fresh test site in JN
