### ISSUE TITLE
WooCommerce > Clients — Total Spend includes cancelled order => NOK !

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce-admin#4557]
Dear,

In the section “Clients” of WooCommerce, we have an overview of the total spent per client. However, for one of my clients, he had only 1 order which was cancelled from the start as he didn’t completed the payment.

However, the column still considers the order in the Total Spent and therefore in the AOV. This is incorrect and misleading calculations. Orders in status Cancelled, Refunded or Failed should not be included in the total.

Thanks

**Comment by jeffstieler** [comment]
Hello @gevcen, sorry for the delay in response.

You should be able to exclude the "cancelled" order status by going to Analytics > Settings.

![Screen Shot 2020-09-08 at 10 05 16 AM](https://user-images.githubusercontent.com/63922/92487141-e49e1d80-f1ba-11ea-92ca-b5814dc5c3f3.png)

**Comment by timmyc** [comment]
@gevcen since we haven't heard back from you on this issue, I'm going to close it out for now. Please do respond back if you need further assistance.
