### ISSUE TITLE
Store details step - add contextual information and skip link

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4566]
**User story:**
As a new merchant
I want to have more context on why I should add info about my store and having a way to skip those steps
So I can decide if I should provide that info or skip it entirely 

**Description:** with the removal of the splash screen we need to adjust the header to provide a more friendly welcome, add a skip link beneath the card and informational tooltips to provide more context.

![profiler-step-1-1.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/0e0cd1b8-931b-4f79-8e08-6dd976572e20)

**Acceptance Criteria:**
- [x] Update the header content
- [x] Add a tooltip in the subtitle explaining why it's important to provide this info
- [x] Add a link to skip the Store Profiler
- [x] Add a tooltip in the skip link reminding why merchants should avoid skipping it

**Event tracking:**
Event name: wcadmin_storeprofiler_store_details_skip
Event prop: NA
Description: when the user clicks to skip the profiler

**Additional links:**
[Design mockup](https://www.figma.com/file/JH9XMFUCOjfXdr3N09AHRD/On-boarding-iterations-June-'20?node-id=171%3A2)

**Comment by timmyc** [comment]
Estimate: If we build this leveraging the core [tooltip component](https://wordpress.github.io/gutenberg/?path=/story/components-tooltip--default) I feel like this could be a 1.

**Comment by mattsherman** [comment]
Estimate: 1, assuming as Timmy did, that an existing tooltip component is used without modification.

**Comment by timmyc** [comment]
Assigning this one to myself, to save for Sam. :)
