### ISSUE TITLE
Task List - Mark Store details step as incomplete when skipping the profiler

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4568]
**User story:**
As a new merchant
I want to be able to easily access the store profiler
So I can complete the store information after skipping it

**Description:** with the addition of a skip link in the profiler (#4566), the Store details step should be marked as incomplete if the user skips the store profiler flow.

I'm not sure if this logic was already implemented on #4096  

**Acceptance Criteria:**
- [ ] Display the Store details step as incomplete if the user skipped the store profiler flow.

**Event tracking:**
Currently, we don't have an event that tracks clicks in the task list, so probably is the easiest way to track if users are clicking on the Store Details step:

Event name: `wcadmin_tasklist_click`
Event prop: `task_name` (value: task name)
Event description: When the user clicks to access a specific task

**Comment by timmyc** [comment]
Looks like this is set via https://github.com/woocommerce/woocommerce-admin/blob/master/client/task-list/tasks.js#L74 which comes from the REST API, so I feel like we could mark the option as completed when skipping. 

Do we already have an issue to cover tracking the click of this link?

Estimate: 1

**Comment by joshuatf** [comment]
>so I feel like we could mark the option as completed when skipping.

Agreed.  I'm assuming we'll have some tracks issue for this as well, @pmcpinto?   If so, let's leave the `completed` property as is to keep complexity to a minimum.

Lack of other filled in information in the profiler will always let us retroactively see if the profiler was skipped or actually completed.

**Comment by pmcpinto** [comment]
> 'm assuming we'll have some tracks issue for this as well, @pmcpinto?

Nope, we only have when the profiler is completed (wcadmin_storeprofiler_complete)

We'll have one when these changes are implemented: #4566

**Comment by pmcpinto** [comment]
Update issue with event tracking
