### ISSUE TITLE
Store profiler - product types step change

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4577]
**Description:** we aim to iterate on the product types step, in order to increase the number of users that select useful extensions

![Product types.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/675ef778-b51e-44dd-b050-91a78c366148)

**Acceptance Criteria:**
- [ ] Toggle the “Physical products” checkbox on by default
- [ ] Remove the Composite products option
- [ ] Include [Product Bundles](https://woocommerce.com/products/product-bundles/) and [Product Add-ons](https://woocommerce.com/products/product-add-ons/) as options
- [ ] Display monthly pricing instead of annual (see mockup)
- [ ] Add tooltip with more info about the purchase (see mockup)

**Event tracking:**
Probably it won't be necessary additional tracking

**Additional links:**
[Design mockup](https://www.figma.com/file/JH9XMFUCOjfXdr3N09AHRD/On-boarding-iterations-June-'20?node-id=260%3A1491)

**Comment by becdetat** [comment]
Estimate: 2

**Comment by joshuatf** [comment]
Estimate: 2-3

My only concern is changing and formatting those prices from the wccom as monthly prices instead of annual.

**Comment by jeffstieler** [comment]
Agree on @becdetat 's estimate of 2 (assuming we can use our [existing `<Count />` component](https://woocommerce.github.io/woocommerce-admin/#/components/packages/count/README)), and share @joshuatf 's concerns about the potential need to change the WCCOM API. (or can we just divide by 12?)

Question for @jameskoster on the pill/count component color - we just removed a lot of purple from the UI.. are we using purple for this?

**Comment by joshuatf** [comment]
>(or can we just divide by 12?)

After dividing and parsing, I think we can.  It includes an encoded HTML entity for currency that needs to be stripped first and added back on.  Nothing too crazy, just not exactly what you'd expect from the API response:

https://woocommerce.com/wp-json/wccom-extensions/1.0/search?category=product-type

**Comment by jameskoster** [comment]
> Question for @jameskoster on the pill/count component color - we just removed a lot of purple from the UI.. are we using purple for this?

Most likely yes :) The thinking is to be way more intentional when we apply any in-product branding (using purple). The latest direction is essentially to use it around any features that require some interaction or connection with woocommerce.com or wordpress.com. IE purchasing / installing extensions, setting up WCPay, or WCServices.

**Comment by mattsherman** [comment]
> Display monthly pricing instead of annual

I know this is a much larger discussion, but I am definitely not a fan of our displaying of monthly prices when we bill annually. But, I get it.

Do any of the prices vary based on other options being selected on this screen? Or, are they all completely decoupled?

`<Count />` currently only shows a number, correct? So, we'd have to extend it to allow for a formatted string to be passed in. At which point, it isn't really a count anymore. So, it shares styling/layout with `<Count />`, but seems distinct.

I'd go with an estimate of 2.

**Comment by jeffstieler** [comment]
Duh! Thanks for catching that @mattsherman.

**Comment by timmyc** [comment]
With #4707 merged, I think we can close this out now.
