### ISSUE TITLE
Consider showing a non-error message for empty posts/extensions in marketing components

### ISSUE THREAD

**Issue by jconroy** [woocommerce/woocommerce-admin#4581]
**Describe the bug**

As a follow up to https://github.com/woocommerce/woocommerce-admin/pull/4526#issuecomment-644236289 - the knowledge base component currently shows an error message if no posts are available.

We also show a loading screen/icon while posts are fetched.

(re) consider updating the UI to only show the components if posts/extensions are available.

I believe this was discussed during initial development but the current approach was deemed preferable at the time.

**Comment by jconroy** [comment]
@j111q 👋 See my comment https://github.com/woocommerce/woocommerce-admin/pull/5411#pullrequestreview-511441681 

What are your thoughts on only showing marketing hub "Recommended Extensions" and "Knowledge Based Posts" if we are able to retrieve the posts?

Thinking A little hard I believe the main reason we didn't do it originally on the marketing hub page was because if the welcome card had been dismissed and the "Installed marketing extensions" was empty AND there were errors communicating with WCCOM for recommendations and posts then the whole page would be blank.

But if showed the errors then at least something would be visible on the page. Thoughts?

**Comment by ecgan** [comment]
@jconroy @j111q ,

Personally I always prefer to display something - when there is an error, convey that to the user and manage their expectations.

If we choose to hide the component / section, meaning to say: 

> (If) there were errors communicating with WCCOM for recommendations and posts then the whole page would be blank.

Users might end up thinking "previously I've seen the blog posts and today it is not showing up intermittently, WordPress / WooCommerce is a buggy and unreliable product" when the problem could be due to network issues.

**Comment by jconroy** [comment]
I think that is a good point @ecgan !

**Comment by j111q** [comment]
> Thinking A little harder I believe the main reason we didn't do it originally on the marketing hub page was because if the welcome card had been dismissed and the "Installed marketing extensions" was empty AND there were errors communicating with WCCOM for recommendations and posts then the whole page would be blank.

Yeah, this would be pretty awkward @jconroy, and agree that's a good point @ecgan.

My preference would be something like this:

![marketing-empty](https://user-images.githubusercontent.com/65582817/96531521-6904b580-12bc-11eb-8cef-80e6746cc8d0.png)

The link should lead to: https://woocommerce.com/blog/marketing/

So it's fairly unobstrusive but drives merchants to more knowledge if that's what they're looking for. 

Thoughts?

**Comment by jconroy** [comment]
Thanks @j111q works for me.

For coupons we pull from https://woocommerce.com/blog/marketing/coupons/ - not sure if you think we should link there for the coupons page

**Comment by j111q** [comment]
Sure that sounds good @jconroy ! Makes sense.

**Comment by ecgan** [comment]
@jconroy @j111q , I'll work on this then.
