### ISSUE TITLE
Display modal with more info about the new home screen

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4590]
**User story:**
As a merchant
I want to have more context when I arrive at the home screen
So I have a sense of what it's possible to do in this page

**Description:** now that we have the home screen implemented, it makes sense to display a modal providing more context about what to expect from this new screen and at the same time replace the current modal that we have for new users. We can replace the current modal with the [Guide component](https://href.li/?https://wordpress.github.io/gutenberg/?path=/story/components-guide--default) from WP Core.

![guide-1.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/41289d3c-be85-4687-9437-67f1dca887b1)

**Acceptance Criteria:**
- [ ] Display the intro guide when a new user visits the home screen for the first time, after completing or skipping the store profiler
- [x] Remove the existing modal that we display for new users 
- [ ] Display the intro guide when existing users visit the home screen for the first time
- [ ] The intro guide is going to have three different tabs (welcoming the user, content about the inbox panel and about the stats area)

**Event tracking:**
TBD

**Additional links:**
[Design mockup](https://www.figma.com/file/JH9XMFUCOjfXdr3N09AHRD/On-boarding-iterations-June-'20?node-id=545%3A20969)

**Comment by becdetat** [comment]
Estimate: 1

**Comment by joshuatf** [comment]
Do we have a component we can use for the carousel used inside the modal?  If yes, then probably a 1 for this, otherwise I might estimate closer to 3.

**Comment by timmyc** [comment]
Yes there is the [guide component](https://wordpress.github.io/gutenberg/?path=/story/components-guide--default) linked above. Also looks like there is only a prop for a callback when the guide is complete, and no way to hook in to per-page views. So from a tracks standpoint we could track the opening of the guide ( but in this case we open it by default ) and the closing of the guide only, but not individual page views... unless we have actions on those pages users might click on ( i.e. external links ). So I agree with the estimate of 1 on this too.

**Comment by pmcpinto** [comment]
> So from a tracks standpoint we could track the opening of the guide ( but in this case we open it by default ) and the closing of the guide only, but not individual page views... unless we have actions on those pages users might click on ( i.e. external links ).

👍 tracking that will be enough

**Comment by psealock** [comment]
I say closer to 3 depending on how the Guide component works out and how closely we want to match the design v. using whats available.

**Comment by mattsherman** [comment]
Gutenberg's `Guide` component seems to meet our needs, as Timmy pointed out. So, assuming that, I'd estimate a 1.

**Comment by jameskoster** [comment]
👋 

Two things that will likely affect the estimates here, one more than the other 🙈 

Firstly we might add another slide, and tweak the copy. More details in p2JRYi-4Ng

Secondly, I wonder if we might need to build some kind of wrapper component for the illustrations. Our intention is to treat illustrations as UI, which means their colors should adapt to user preferences just like other components (buttons etc). We're using SVG for these graphics, so my thinking was that a new illustration component could accept a color value (most likely `$theme-color`) and pass it on to all the relevant elements within the svg.

**Comment by timmyc** [comment]
One other comment here, we need to remember to not ship large image assets whenever possible. Guessing the SVGs will help, but just wanted to remind folks of our need to stay aware of our build size.

**Comment by jameskoster** [comment]
Thanks for the reminder @timmyc. Yeah the svgs should help a lot, I'm confident we can keep them in a 5 - 20kb size range. We're also assembling an illustration library so that we can re-use as much as possible, rather than adding new assets.

**Comment by jameskoster** [comment]
Updated illustrations available to download [here](https://cloudup.com/ch1jKvejrSs).

Updated content for the slides in [Figma](https://www.figma.com/file/JH9XMFUCOjfXdr3N09AHRD/On-boarding-iterations-June-20?node-id=545%3A20969) here.

**Comment by pmcpinto** [comment]
Updated issue description & title to cover both cases: new and existing users.
