### ISSUE TITLE
Task List - reorder tasks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4591]
**Description:** we should reorder the tasks based on the data that we've been gathering and its relevance to have a store up and running.

**Acceptance Criteria:**
- [ ] Reorder the tasks with the following order:
Store details
Purchase extensions
Add products
Set up payments
Set up tax
Set up shipping
Personalize store

**Event tracking:**
We don't need to implement additional event tracking

**Comment by becdetat** [comment]
Estimate: 1

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm working on this issue and wanted to ask you about the task item: `Connect your store to WooCommerce.com`. In which position do you think it should be?
This item will be visible when there are items purchased in the OBW and the store is not connected to `WooCommerce.com`.
For now, I will leave it between: `Purchase & install extensions` and `Add my products`.
Please, let me know if you want to change it.

**Comment by pmcpinto** [comment]
That's a good question. I completely forgot about that use case where we display that task. I feel that we have some redundancy by displaying `Connect your store to WooCommerce.com` and `Purchase & install extensions`, so perhaps we should just delete the `Connect your store to WooCommerce.com` task 🤔 @jameskoster what do you think?

**Comment by jameskoster** [comment]
Yeah, in the context of store setup it's super low priority. We could probably replace it with an Inbox notification that reminds them to connect so that they get access to extension updates etc.
