### ISSUE TITLE
Task List - tax task: automated taxes smart default

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4594]
**User story:**
As a new merchant
I want to focus on the most important setup tasks
So I can review some details later

**Description:** with Jetpack installed and connected, alongside WCS, we have the opportunity to set things up on the users' behalf, and ask them to review and confirm, rather than start from scratch and think.

**Acceptance Criteria:**
- [ ] If the store has JP installed and connected, WCS active and is located in a country covered by automated taxes, automatically turn on automated taxes and mark the step as completed
- [ ] Trigger the following notification:
**Title:** Confirm tax settings
**Content:**  Automated tax calculations are enabled on your store through WooCommerce Services. Learn more about automated taxes [here](https://docs.woocommerce.com/document/woocommerce-services/#section-10)
**Segmentation:** stores with automated taxes automatically enabled
**Timing:** when the task is marked as completed 
**Cadence:** once
**CTA leads to:** wp-admin/admin.php?page=wc-settings&tab=tax
**CTA label:** Edit tax settings

**Event tracking:**
We can use the event `wcadmin_tasklist_task_completed` and eventually add a new value to `task_name` when this happens: tax_automated

**Additional links:**
[Design mockup](https://www.figma.com/file/JH9XMFUCOjfXdr3N09AHRD/On-boarding-iterations-June-'20?node-id=1%3A9)

**Comment by becdetat** [comment]
I don't know what would be involved in automatically turning on automated taxes - is that something that would need to be triggered in Jetpack?

**Comment by joshuatf** [comment]
>I don't know what would be involved in automatically turning on automated taxes - is that something that would need to be triggered in Jetpack?

Turning on automatic taxes should be pretty straightforward if plugins are installed, Jetpack is connected, and TOS have been accepted.  In that case, we just need to update settings for `wc_connect_taxes_enabled` and `woocommerce_calc_taxes` to be `yes`.

Finding the right time to hook into the profiler and do this could be tricky (maybe under `completeProfiler()`), so I might estimate 2 for that reason.

Estimate: 2.

**Comment by timmyc** [comment]
I like the estimates above, but also want to re-iterate my thoughts on the smart shipping defaults too: https://github.com/woocommerce/woocommerce-admin/issues/4595#issuecomment-645631421

Again the more we tightly couple our code with extension logic, the more brittle things become. So I think we again make this "step" extensible, and allow for WCS to inject their own logic.

**Comment by mattsherman** [comment]
This feels around a 2 if we hard-code logic. I'm not sure how much more complexity would be added by making it extensible, but it deserves consideration since, as Timmy mentions, that may make things more robust (less brittle) in the future.

**Comment by becdetat** [comment]
Some prior art on setting shipping rates up in a similar way: https://github.com/woocommerce/woocommerce-admin/pull/4857

**Comment by samueljseay** [comment]
Just some context, that some of the front-end code in this area of the profiler is quite ripe for some refactoring and testing. I'm not 100% sure on how our mandate to fit in more testing and refactoring fits in for this issue, but it could be worth some consideration here.

**Comment by becdetat** [comment]
@pmcpinto Note that the link in the content is https://docs.woocommerce.com/document/woocommerce-services/#section-10, which currently links to "Schedule a pickup". I've changed this to https://docs.woocommerce.com/document/woocommerce-services/#section-12 which is the automated taxes section. It's worth noting that these links aren't evergreen, and would be better with named ids such as `/#automated-taxes`.
