### ISSUE TITLE
Task List - Payments task: add alert message

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4596]
**Description:** we want to reinforce the importance of setting up a payment method and increase user intent by adding an alert message about this topic

**Acceptance Criteria:**
- [ ] Add an alert message on each page of the Payments task reinforcing the fact that enabling a payment method is required to start accepting orders 

**Event tracking:**
NA 

**Additional links:**
[Design mockup](https://www.figma.com/file/JH9XMFUCOjfXdr3N09AHRD/On-boarding-iterations-June-'20?node-id=111%3A483)

**Comment by becdetat** [comment]
Estimate: 1

**Comment by joshuatf** [comment]
Is there an existing WordPress component for this type of alert/notice?  If yes, then maybe a 1, otherwise I may lean slightly towards a 2 due to potential layout headaches this may cause.

**Comment by timmyc** [comment]
Yes there is an existing component we can use for this - the [alert component](https://wordpress.github.io/gutenberg/?path=/story/components-notice--default). Zooming out a bit, @jameskoster is wanting us to replace our `<StoreAlert />` design with this component too, so any work we do here to ensure that alert component works here will help us transition on to that design for store alerts. I'd call this a 2 also just to be safe.

**Comment by joshuatf** [comment]
>Yes there is an existing component we can use for this - the alert component. 

Thanks, @timmyc!

>so any work we do here to ensure that alert component works here will help us transition on to that design for store alerts. 

It almost feels like that and an API/store to interact with the alerts are blocking tasks that needs to be handled first.

**Comment by mattsherman** [comment]
I'd estimate a 2 for this specific story. However...

> replace our <StoreAlert /> design with this component too

I strongly urge that we work to converge on a single alert style within our WooCommerce UI and only implement this once we have done so. Alternatively, implement this alert with our current store alerts style first and rely on a more general updating of alerts to bring this into line with the design.

**Comment by mattsherman** [comment]
@pmcpinto Is this still an issue that needs to be addressed?

**Comment by pmcpinto** [comment]
Yes. This not a top priority, but it can be framed as a nice to have for this cycle. And the best option seems to be this one:

> Alternatively, implement this alert with our current store alerts style first and rely on a more general updating of alerts to bring this into line with the design.

cc @elizaan36 for additional feedback

Can this be implemented without waiting for a core release, now that the "remote" payments task. Probably the answer is no, but it's good to clarify this 😄

**Comment by elizaan36** [comment]
I'd use the [Gutenberg component](https://wordpress.github.io/gutenberg/?path=/story/components-notice--default) for alerts like this going forward. I agree we should deprecate the <StoreAlert /> design since it's too large and can be overwhelming.

**Comment by joelclimbsthings** [comment]
Given the dialog in [the related pull request](https://github.com/woocommerce/woocommerce-admin/pull/4782) the decision was made that the UI wasn't ideal, and to pursue alternatives. Closing this issue.
