### ISSUE TITLE
Inbox panel  - inbox notifications disappear after clicking on the call to action

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4602]
**Describe the bug**
The inbox notifications are disappearing from the panel (both on the home screen and in the side panel) when clicking in the main call to action of a message

**To Reproduce**
1. Activate wcadmin 1.3.0 beta
2. Enable the home screen
3. Go to WooCommerce - Home and click on the main call to action of a notification
4. See that the notification disappears after clicking on it

**Expected behavior**
I expect to clear a notification only when I click to dismiss it

**Comment by pmcpinto** [comment]
Hi @octaedro I'm not sure if this is a bug, but the notifications should only be removed when the user shows the intent to dismiss it: clicking the dismiss button and then confirming the action. Removing the notification after clicking in the main cta can create a lot of confusion

**Comment by octaedro** [comment]
Hey @pmcpinto,
I think that what you said is a good idea. I will address the issue 👍
