### ISSUE TITLE
Home screen styling issues

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#4603]
In the interest of keeping this issue short(ish) I've written brief descriptions of the required changes. Hopefully they all make sense, but if more detail is required please don't hesitate to ask.

### Global

- All cards should have same border color, border radius, and padding values. If we can't use the [`Card`](https://wordpress.github.io/gutenberg/?path=/story/components-card--default) component, we should aim to match its styling consistently.
- There's a lot of inconsistencies in the text styling. Using the [`Text`](https://wordpress.github.io/gutenberg/?path=/story/components-text--default) component wherever possible would eliminate this, but I appreciate we might have to style things "manually" for now. I've included details of where we need to do this in the sections below. 
- Inbox tab in the Activity Panel should be hidden on the home screen

### Inbox

- Spacing in [header](https://cloudup.com/ctBQCm4qDqT) doesn't match [designs](https://cloudup.com/c3GmvprrGry) 
- "Inbox" header should use "Title Small" [`Text`](https://wordpress.github.io/gutenberg/?path=/story/components-text--default) style
- Secondary button color in notifications appears to be gray when it should be blue. Core [`Button`](https://wordpress.github.io/gutenberg/?path=/story/components-button--secondary) for reference.
- There should not be any primary buttons in Inbox notifications, only secondary and tertiary - https://cloudup.com/cvLEZnu52-M

### Task list (PR here: https://github.com/woocommerce/woocommerce-admin/pull/4627)

- I'm seeing [double ellipsis](https://cloudup.com/ceO7atYYQX4) (Brave, latest MacOS). For the "kebab" icon we should use the [core "more" icon](https://github.com/WordPress/gutenberg/blob/master/packages/icons/src/library/more.js)
- The [dismiss dropdown](https://cloudup.com/cPvhlR8-ZOt) styling is looking a bit funky. It should match the one in the [Inbox notifications](https://cloudup.com/cMQPPF1A5NY)
- Card header should use "Title Small" [`Text`](https://wordpress.github.io/gutenberg/?path=/story/components-text--default) style
- Card header padding should match the "medium" size in the core [`Card`](https://wordpress.github.io/gutenberg/?path=/story/components-card-header--default) component. 16px 24px. 
- Padding on task rows should be 16px 24px. That's my bad - the designs were incorrect.
- Task label should use "button" [`Text`](https://wordpress.github.io/gutenberg/?path=/story/components-text--default) style.
- Time estimate color should be [$medium-gray-text](https://github.com/WordPress/gutenberg/blob/master/packages/base-styles/_colors.scss#L30) 

### Stats card (PR here: https://github.com/woocommerce/woocommerce-admin/pull/4625)

- Card header should use "Title Small" [`Text`](https://wordpress.github.io/gutenberg/?path=/story/components-text--default) style
- Card header padding should match the "medium" size in the core [`Card`](https://wordpress.github.io/gutenberg/?path=/story/components-card-header--default) component. 16px 24px.
- Tabs should include comparison label - https://cloudup.com/ctRMMoD_UW7
- Text color in tabs should match the core [`TabPanel`](https://wordpress.github.io/gutenberg/?path=/story/components-tabpanel--default) component
- Text styles and colors of the Jetpack banner should match the Inbox notifications, as should the spacing in the actions buttons.
- "Connect Jetpack" button should be secondary instead of primary
- "View detailed stats" link should not be pink.
- Spacing in the "Display stats" dropdown should match the [dismiss menu on Inbox notifications](https://cloudup.com/cMQPPF1A5NY), and the toggles should be blue
- Ellipsis icon should use the [core "more" icon](https://github.com/WordPress/gutenberg/blob/master/packages/icons/src/library/more.js).
- There's a lag when clicking the toggles in the "Display stats" dropdown which makes them feel very odd to use. We should apply a loading state if we can't make this instant.

**Comment by psealock** [comment]
Hi @jameskoster, I'm finishing up the last of this with the Inbox and global items.

Do you have a link to Figma file that describes Inbox's `Text` sizes and colors? Similar to this one https://www.figma.com/file/Pfw5Qa1UOw03RiJere3Wlo/Automattic-Components?node-id=4533%3A712 ?

Here is a the branch I am working on so far https://github.com/woocommerce/woocommerce-admin/compare/fix/inbox-styles?expand=1.

<img width="454" alt="Screen Shot 2020-06-24 at 11 05 38 AM" src="https://user-images.githubusercontent.com/1922453/85476209-e7519380-b60b-11ea-8fec-2e2ed4a97022.png">

**Comment by jameskoster** [comment]
@psealock Not for that specific component I'm afraid.

The "Inbox" header should be `Title Small` and `$dark-gray-primary`. 

The "Insights and growth tips..." line should be `Body Small` and `$medium-gray-text`.

The count should be `Title Small`, the background color is `$medium-gray-text` and the text color `$white`.
