### ISSUE TITLE
UserPreferences: Update optimistically

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#4626]
In the Homescreen, there is a lag in selection of charts in Stats Overview due to userPreferences not updating until data returns from the server. This introduces a lag time for the UI to refresh.

We should optimistically handle changes by updating the store immediately and handling errors gracefully.

**Comment by joshuatf** [comment]
Just noting that this would be useful to have for all column/chart preferences in favor of storing items in the state for each component as it's handled now in components that aren't lagging.
