### ISSUE TITLE
[4.3] WooCommerce Payments card not displayed in task list

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce-admin#4628]
**Describe the bug**

With 4.3-beta-1, the WooCommerce Payments card is not displayed on first load of the payment setup task when Jetpack is not installed during the new store onboarding.

**To Reproduce**

1. Complete all 5 steps of the new store setup
1. Click **No thanks** for WCS & Jetpack
1. Click **Set up payments** task under **Finish setup**
1. Notice no WC Pay card is displayed
1. Refresh the page
1. Notice the WC Pay card is displayed

Video demo: https://d.pr/v/JQYnNn

**Expected behavior**

I expected the WooCommerce Payments card to be displayed as the first option for payment methods to a new store in the US not selling CBD products, even without the Jetpack plugin and connection.

**Screenshots**

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/235523/84978583-a3284400-b170-11ea-98c0-e58c577e84ff.png">

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Firefox
* Version: 76.0.1

**Comment by DanReyLop** [comment]
Thanks for testing this and the detailed steps to reproduce! I opened a fix: https://github.com/woocommerce/woocommerce-admin/pull/4647

I'm kicking myself a bit for not catching this during my testing. I ran through the whole setup wizard on a clean site, but I must have refreshed the page accidentally at some point... oh well, good thing we have a "Beta wagon" in the release train :)
