### ISSUE TITLE
Missing event prop when clicking in an inbox notification within the Home screen

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4633]
I was testing the new Home screen and I think that's missing the event prop: `screen` (value: home screen, analytics_revenue, customers, etc) on `wcadmin_wcadmin_inbox_action_click` (see #4099 for more context)

**Comment by pmcpinto** [comment]
@octaedro I think this missing this event prop. Can you confirm? Thanks

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm checking this out and you're right, we are not sending the `screen`. I will work on this fix now.
Thanks 🙂

**Comment by pmcpinto** [comment]
👍 Thanks!
