### ISSUE TITLE
Remove done/skip buttons in payments task

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4638]
As @jameskoster noted in https://github.com/woocommerce/woocommerce-admin/issues/4241 we should remove the "Done" and "Skip" buttons from payments.

This will mean relying on returning to the task list via:
* The home button
* The task list shortcut in https://github.com/woocommerce/woocommerce-admin/issues/4592
* The back button in https://github.com/woocommerce/woocommerce-admin/issues/2811

<img width="181" alt="Screen Shot 2020-06-19 at 8 14 33 AM" src="https://user-images.githubusercontent.com/10561050/85099016-f5b34000-b204-11ea-997d-5f158e1afc88.png">
<img width="694" alt="Screen Shot 2020-06-19 at 8 14 29 AM" src="https://user-images.githubusercontent.com/10561050/85099018-f6e46d00-b204-11ea-83f7-cc4b18d3544f.png">

Note that this will mean we'll no longer be able to check if the payments task has been skipped in notes like `WC_Admin_Notes_Onboarding_Payments` and rely purely on whether a gateway has been enabled or not. /cc @pmcpinto for any additional comments here.

This task will involve:
* Removing the done/skip buttons.
* Removing the active state on the "Home" link when in the payments task.
* Removing logic that makes use of `woocommerce_task_list_payments`.

**Comment by pmcpinto** [comment]
> Note that this will mean we'll no longer be able to check if the payments task has been skipped in notes like WC_Admin_Notes_Onboarding_Payments and rely purely on whether a gateway has been enabled or not. /cc @pmcpinto for any additional comments here.

Thanks for the heads up. I'll open a new GH issue to fix this change on the notifications using that event. We have 2
