### ISSUE TITLE
Jetpack connection URL should be resolved with promise

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4639]
In following https://github.com/woocommerce/woocommerce-admin/pull/4473, we should move away from using the `Connect` component where resolving the connection URL is needed without the added UI.

This currently happens on the benefits screen and the install Jetpack CTA.

In order to do this, we may want to look into using `__experimentalResolveSelect` (which seems relatively safe, but needs testing) and push changes upstream in gutenberg to move this away from experimental.  See p1592484873191100-slack-woo-merchandising for discussion on this.

* Remove `Connect` component on Benefits page and install Jetpack CTA.
* Replace with `__experimentalResolveSelect` to get the Jetpack connect URL.
* Remove `autoConnect` logic from `Connect`.
* Open an issue upstream in GB if the experimental selector works well to move this to non-experimental.

**Comment by mattsherman** [comment]
It seems like good timing to work on this refactor in conjunction with #4579.
