### ISSUE TITLE
HTML Entity for Currency not Rendered Correctly on Analytics Pages

### ISSUE THREAD

**Issue by damiannep** [woocommerce/woocommerce-admin#4646]
**Describe the bug**
We've had several reports in the forums of the Euro symbol not showing correctly on the back end of sites over several months but have not been able to replicate this:

- https://wordpress.org/support/topic/formatting-issue-euro-symbol/
- https://wordpress.org/support/topic/euro-symbol-broken/
- https://wordpress.org/support/topic/euro-symbol-not-showing-correctly-dashboard-statistics-etc/

This is happening on Analytics pages, but not in the Leaderboard: https://ibb.co/Q8fN4kR

Issue continued with upgrade to WC 4.2 as shown [here](https://wordpress.org/support/topic/euro-symbol-broken-in-admin/#post-12937670).

Status report from an affected user: https://cloud.studio-adhoc.de/index.php/s/3qmqkBYMZfa6YqS

**Screenshots**
https://prnt.sc/sto2p8 with WC 4.2 installed

One user said that they changed providers and the issue resolved. I've asked for more info [here](https://wordpress.org/support/topic/euro-symbol-broken-in-admin/page/2/#post-13012453).

**Desktop (please complete the following information):**
- https://www.whatsmybrowser.org/b/XIRZG (from 2 months ago)
- https://www.whatsmybrowser.org/b/7RGX3 (recent)

[Another user](https://wordpress.org/support/topic/euro-symbol-broken-in-admin/#post-12970486) said issue resolved when they changed hosts. Issue persists with conflict testing with all other plugins deactivated and one of our themes used, according user reports. What other information would be helpful to help us isolate the cause of this issue?

**Comment by raafael911** [comment]
Hi, I'm facing the exact issue in #4746. If I can provide any information please let me know.

**Comment by Christian-Roth** [comment]
Hi, the bug description isn't quite right:

> One user said that they changed providers and the issue resolved. I've asked for more info here.

I didn't said that we changed providers. I said that I'm maintaining two woocommerce installations at different hosting services. One is showing the currency symbols correctly, one doesn’t. Both are viewed in the same browser. 
[https://wordpress.org/support/topic/euro-symbol-broken-in-admin/#post-12789261](https://wordpress.org/support/topic/euro-symbol-broken-in-admin/#post-12789261)

All the best
Christian

**Comment by timmyc** [comment]
I can not replicate this issue on a site running Storefront and WooCommerce 4.3.1

<img width="688" alt="image" src="https://user-images.githubusercontent.com/22080/89466246-4edd2180-d728-11ea-90d6-7f557618c86d.png">

As such I am going to mark this as resolved.

**Comment by igestalten** [comment]
same problem for me - even in WC 4.3.2
might position of currency symbol be a point?

![wrongentity](https://user-images.githubusercontent.com/6428173/89877974-2e4a1700-dbc1-11ea-8a39-ebd28f723d34.jpg)

**Comment by timmyc** [comment]
@igestalten can you let me know your full currency settings in WC 4.3.2 so I can try and re-create the problem? Also maybe a WooCommerce System Status Report might yield some other clues.

I've played around with all the currency settings and still can't seem to reproduce the problem.

**Comment by fabbaf** [comment]
Same problem here. No €-symbol for me since version 4.0.0.

Status reports, screenshots, etc. are listed here: [https://wordpress.org/support/topic/euro-symbol-not-showing-correctly-dashboard-statistics-etc/#post-13481479]

**Comment by kakigorimochi** [comment]
I wrote a code to temporarily fix this problem for other users. 

Obviously, I ran into this problem as well. I am not sure if it would work for everyone else. Kindly let me know. 

The code written below is similar to what is posted in WooCoomerce's Docs:
https://docs.woocommerce.com/document/change-a-currency-symbol/

Instead of using `&nbsp;` for space (hard-coded in the plugin) I used ' ' and for my currency EUR with € not `&euro;`.

I am one of those users who has a server-sided/environmental problem.

Hope this helps.

```
/** --------------------------------------
 * Temporary Fix for &nbsp;, &euro; and other html entity problems for WooCoomerce Analytics.
 * DISCLAIMER: Use at your own risk, this is in-case of enviromental/server issues.
 * 
 * Usage: Paste this code in your child theme's functions.php
 * https://github.com/woocommerce/woocommerce-admin/issues/4646
 *  -------------------------------------- */

add_filter('woocommerce_currency_symbol', 'change_existing_currency_symbol', 10, 2);

function change_existing_currency_symbol( $currency_symbol, $currency ) {	
     switch( $currency ) {
          case 'EUR': $currency_symbol = '€'; break;
     }	
     return $currency_symbol;	
} 

add_filter('woocommerce_price_format', 'change_existing_price_format', 10, 2);

function change_existing_price_format( $format, $currency_pos ) {	
	switch ( $currency_pos ) {
		  case 'left_space': $format = '%1$s %2$s'; break;
		  case 'right_space': $format = '%2$s %1$s'; break;
	}	
	return $format;	
}
```


**< The Problem >**
![image](https://user-images.githubusercontent.com/16938949/109507575-d8e04380-7ad9-11eb-92cf-af475ae8eb17.png)

**< When Code is Applied >**
![image](https://user-images.githubusercontent.com/16938949/109507992-4e4c1400-7ada-11eb-9f42-dde0e811848f.png)

**Comment by fabbaf** [comment]
> > Hope this helps.
> 
> Worked perfectly for me! Thanks

For me too. Thank you!
