### ISSUE TITLE
Catalog Visibility Options: remove notification

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4652]
With the removal of the skip button on the Payments task (#4638) we should also remove this notification () as we won't have an easy way to identify if the user doesn't want to accept payments (#3794)

**Comment by joshuatf** [comment]
@pmcpinto It looks like https://github.com/woocommerce/woocommerce-admin/issues/3794 was never added.  Can we close this issue or is there something else we need to address with the done/skip removal?

**Comment by pmcpinto** [comment]
> @pmcpinto It looks like #3794 was never added. Can we close this issue or is there something else we need to address with the done/skip removal?

Tks for the heads up. I'll close it.
