### ISSUE TITLE
"Set up payments" reminder: change logic

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4653]
With the removal of a skip button (#4638) we need to update the logic of triggering the following message: #3791

**Store type**: New users
**Trigger**: 5 days after store creation without having a payment method enabled: /wp-admin/admin.php?page=wc-settings&tab=checkout

**Comment by octaedro** [comment]
Hi @pmcpinto,
Just to confirm, I'm working on this issue and I noticed that we are adding the note only if the task list is still shown. Is that correct?
Thanks 🙂

**Comment by pmcpinto** [comment]
> Just to confirm, I'm working on this issue and I noticed that we are adding the note only if the task list is still shown. Is that correct?

We should display it independently if the task list is shown or not. They can remove the checklist, without completing the payments task. Makes sense?

**Comment by octaedro** [comment]
> We should display it independently if the task list is shown or not. They can remove the checklist, without completing the payments task. Makes sense?

Got it! Thank you @pmcpinto 🙂
