### ISSUE TITLE
Banner - mobile app

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4654]
**User story:**
As a merchant
I want to be informed about the existence of a mobile app
So I can decide if continue using the mobile browser or install the app

**Description:** the mobile team asked to implement a banner informing users about the existence of a mobile app, which is a common practice among our competitors

![screen-shot-2020-05-14-at-4.19.09-pm.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/d10268a4-0de7-400b-9590-a782c92f4bd9)

Note: ignore the banner on wccom

**Acceptance Criteria:**
- [ ] Display the mobile banner below the 783px breakpoint (the same that exists for the Activity panels) 
- [ ] Dismiss the banner if the user clicks to install the app or dismiss the banner
- [ ] Redirect the user to https://woocommerce.com/mobile/ if they click to install the app

Nice to have
- [ ] Hide the banner from users that already clicked to install the app through the inbox notification
- [ ] Redirect the user to the [App Store](https://itunes.apple.com/us/app/id1389130815?pt=299112&ct=wcadmin_banner&mt=8) or [Google Play](https://play.google.com/store/apps/details?id=com.woocommerce.android&referrer=utm_source%3Dwcadmin_banner%26utm_medium%3Dpage%26utm_campaign%3Dmobile_app_launch), depending on the device OS

**Event tracking:**
Event name: `wcadmin_mobile_banner_click`
Event prop: `button`(values: `install` | `dismiss`)
Description: when the user clicks the mobile app banner

**Additional links:**
Design proposal: p91TBi-2LT-p2
[Design mockup](https://www.figma.com/file/mjrVSgBLeaJ5TOjQwplorK/Smart-app-banner?node-id=55%3A3723)

**Comment by timmyc** [comment]
Since we are seeking to have this code used in two places ( Woo installs and WooCommerce.com ) it kind of _feels_ like we should write this as a standalone package once, and allow it to be used in both spots. I'm going to estimate this at a 5.

**Comment by pmcpinto** [comment]
> Since we are seeking to have this code used in two places ( Woo installs and WooCommerce.com ) it kind of feels like we should write this as a standalone package once, and allow it to be used in both spots. I'm going to estimate this at a 5.

Should we check if the package can be implemented by Gerhard, as he's going to work on the woocommerce.com banner? That would decrease the effort on our side, right?

**Comment by mattsherman** [comment]
@pmcpinto We should consider making use of the [iOS Smart App Banner](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html).

**Comment by pmcpinto** [comment]
> @pmcpinto We should consider making use of the iOS Smart App Banner.

That's a good idea. @Garance91540 did you consider using this method on iOS?

**Comment by Garance91540** [comment]
>@pmcpinto We should consider making use of the iOS Smart App Banner.
That's a good idea. @Garance91540 did you consider using this method on iOS?

That was the original plan, and I don't remember why we went another way. I think a smart banner on iOS sounds great. Let me know if you need specific assets from me to implement it!
