### ISSUE TITLE
Fatal Error on Latest beta build

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce-admin#4658]
I just updated to the latest beta and got a fatal. I had to revert to 4.2. please advice.

Uncaught Error: Call to undefined method Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Deactivate_Plugin::possibly_add_note() in /var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php:56 Stack trace: #0 [internal function]: Automattic\WooCommerce\Admin\Composer\Package::init() woocommerce/woocommerce#1 /var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/src/Packages.php(72): call_user_func() woocommerce/woocommerce#2 /var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/src/Packages.php(48): Automattic\WooCommerce\Packages::load_packages() woocommerce/woocommerce#3 /var/docs/wptheme.tst/public/wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Packages::on_init() woocommerce/woocommerce#4 /var/docs/wptheme.tst/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() woocommerce/woocommerce#5 /var/docs/wptheme.tst/public/wp-includes/plugin.php(478): WP_Hook->do_action() woocommerce/woocommerce#6 /var/docs/wptheme.tst/public/wp-settings.php(411): do_action() woocommerce/woocommerce#7 /var/docs/wptheme.tst/public/wp-config.php(90): require_once('/var/docs/wpthe...') woocommerce/woocommerce#8 /var/docs/wptheme in /var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php on line 56

**Comment by timmyc** [comment]
@BackuPs thanks for opening the issue. I'm not able to reproduce, but just wanting to confirm that you hit this issue immediately upon updating - or had you performed a different action?

**Comment by dougaitken** [comment]
Hey @timmyc 

I just ran into this and can confirm it was when activating the plugin after updating to WooCommerce 4.3 beta 1

```
2020-06-23T12:24:18+00:00 CRITICAL Uncaught Error: Call to undefined method Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Deactivate_Plugin::possibly_add_note() in /srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php:56
Stack trace:
#0 [internal function]: Automattic\WooCommerce\Admin\Composer\Package::init()
#1 /srv/htdocs/wp-content/plugins/woocommerce/src/Packages.php(72): call_user_func(Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce/src/Packages.php(48): Automattic\WooCommerce\Packages::load_packages()
#3 /wordpress/core/5.4.2/wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Packages::on_init('')
#4 /wordpress/core/5.4.2/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /wordpress/core/5.4.2/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /wordpress/core/5.4.2/wp-settings.php(403): do_action('plugins_loaded')
#7 /srv/htdocs/wp-config.php(80): require_once('/wordpress/core...')
#8 /wordpress/core/5.4.2/wp-load.php(42): require_once('/srv/htdocs/wp-...')
#9 /wordpress/core/5.4.2/wp-admin/admin.php(34): require_once('/wordpress/core...')
#10 /wordpress/core/5.4.2/wp-admin/plugins.php(10): require_once('/wordpress/core...')
#11 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php on line 56
```

Force deleting it via FTP returned access to the site. 

Then reinstalling WooCommerce Admin 1.2.4 from the site plugins option, the site again fell over when activating the plugin. Reading log via FTP provided the exact same error. 

As a note - deleting the plugin each time via FTP took ~2 mins which to me seems long.

Installing 1.3.0-rc.1 had no problems - installed zip and activated without issue.

**Comment by timmyc** [comment]
@dougaitken - thanks for the report. How did you do the upgrade when you got the error? Beta tester plugin? Upload via FTP?

**Comment by becdetat** [comment]
I can reproduce this:

1. create a new site
2. install woocommerce-4.3.0-beta.1 from [here](https://github.com/woocommerce/woocommerce/releases/tag/4.3.0-beta.1)
3. install WooCommerce Admin from the plugins screen (version 1.2.4)

Stable WCAdmin 1.2.4 doesn't include `NoteTraits` which has been introduced in the version that will be bundled in WC 4.3.0 - it looks like the `Package.php` from woocommerce-4.3.0-beta.1 is running against the rest of the code in WooCommerce Admin 1.2.4. So this will be resolved as soon as a new version of WCAdmin drops. However to try to stop this happening before that we could add a check to the WCAdmin that will be bundled in 4.3.0 to make sure the function exists before trying to call it.

**Comment by BackuPs** [comment]
Hi

Yes i am using the beta tester plugin. And yes i got this instantly on updating. It was a fresh install of a website running also Woocommerce admin.

Kind regards

**Comment by dougaitken** [comment]
@timmyc beta tester plugin, I keep `beta.doug.press` up to date with WooCommerce betas so it was on the best and I had WC Admin already installed but deactivated. I then activated it and that's when it fataled.

During all my testing I didn't change the WooCommerce version

**Comment by BackuPs** [comment]
Yes it definitly happens only when woocommerce admin 1.24 or below is active.  Retested again with a clean install.  If not active i can update to the latest beta release.

Thanks all !
