### ISSUE TITLE
Onboarding Data Store: Potential stale data with old getSetting/setSetting

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#4662]
I haven't found a bug in the UI, but there are remnants of the old onboarding settings. A refactor or change may expose a bug due to stale data, so we should pro-actively fix this.

https://github.com/woocommerce/woocommerce-admin/blob/4da38966f4bc5a08d390e228b9f30420170dc67e/client/task-list/tasks.js#L38

https://github.com/woocommerce/woocommerce-admin/blob/4da38966f4bc5a08d390e228b9f30420170dc67e/client/task-list/tasks/tax.js#L223

**Comment by jeffstieler** [comment]
I thought I had a handle on the changes needed here - but where should we be getting "new" onboarding settings? I naively tried:

```js
const { getSettings } = select( SETTINGS_STORE_NAME );
const { onboarding } = getSettings( 'onboarding' );
```

That resulted in a `rest_setting_setting_group_invalid` error from the `/wc-analytics/settings/[group]` endpoint.

**Comment by psealock** [comment]
That would be 

```diff
- const { onboarding } = getSettings( 'onboarding' );
+ const { onboarding } = getSettings( 'wc_admin' );
```
The entire settings are hydrated here:

https://github.com/woocommerce/woocommerce-admin/blob/aecd050aff498d997adea9ec3e00a6bce8bd8a61/client/index.js#L27-L30

Why? Its been a long incremental cleanup of the way settings are used and gathered, which continues to need refinement. Not only did we jam everything into `window.wcSettings `, but different settings groups were used to and plugged into the global as well. 

I think the best course of action here is to reserve this settings data store for the `wc_admin`, `general`, and `tax` groups that already exist and pull out the onboarding settings and hydrate them as part of the onboarding data store. Those settings groups exist as grouped options and the persistence mechanism requires an option group name in the settings data store. The rest of the onboarding settings don't belong to a group and seem more applicable to the onboarding data store.

Does this make sense?

**Comment by jeffstieler** [comment]
Thanks for the background info @psealock!

> The rest of the onboarding settings don't belong to a group and seem more applicable to the onboarding data store.

So are you proposing that we move these values to perhaps a new endpoint like `onboarding/status`?:

https://github.com/woocommerce/woocommerce-admin/blob/edec32338488dd789c89766e3be8b801ff3ab0ef/src/Features/OnboardingTasks.php#L109-L127

**Comment by psealock** [comment]
I was thinking more of the client side gathering and updating these values in a single place. If a new endpoint makes sense for that, then yes. Lets look at one random example from what you listed above: 

```php
$settings['onboarding']['isAppearanceComplete'] = get_option( 'woocommerce_task_list_appearance_complete' ); 
```

Not only is it an option that can be gotten from the option data store, but it is made available on the wcSettings global:

https://github.com/woocommerce/woocommerce-admin/blob/0697cbab737329e72dab7a690e57dfc828f3216e/client/task-list/tasks.js#L62

When the time comes to update this option, the global and option BOTH need to be updated. This is done correctly below, but it takes some historical knowledge to know that you should do that.

https://github.com/woocommerce/woocommerce-admin/blob/0697cbab737329e72dab7a690e57dfc828f3216e/client/task-list/tasks/appearance.js#L236-L245
