### ISSUE TITLE
[WC 4.3 RC1] Home Screen: After completing `Purchase & install extensions`  step and returning back to the site - an OBW completion pop-up window is shown again

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4669]
**Describe the bug**

After completing `Purchase & install extensions`  step and returning back to the site - an OBW completion pop-up window is shown again. Feels like this pop-up should not be shown for the 2nd time and only be shown once after the user completed the onboarding. 

**To Reproduce**

1. Complete onboarding on the fresh install. Make sure to select one of the paid extensions to be purchased during onboarding. 
2. Observe that once you complete onboarding, you are redirected to the site and shown the `Woo hoo - you are almost there!` pop-up window. 
3. In the `Finish setup` section - click on `Purchase & install extensions` - complete the flow and wait to be redirected back to the site.
4. Observe that you are shown the `Woo hoo - you are almost there!` pop-up window again:

![woo-hoo](https://user-images.githubusercontent.com/19143190/85438330-d9dbd100-b559-11ea-8a39-a318afd2355f.jpg)

**Expected behavior**

I expected to be redirected back to the site after the extension was installed without seeing the Woo hoo - you are almost there!` pop-up window again. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.5
* Browser: Chrome
* Version: 83.0.4103.106 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by joshuatf** [comment]
This may no longer be an issue now that the `WelcomeModal` has been refactored.  If anyone can reproduce this, I would suspect issues with updating the option` woocommerce_task_list_welcome_modal_dismissed` and estimate a 1.

**Comment by becdetat** [comment]
I can't reproduce it. The code post-refactor seems pretty solid around only displaying once, so I think this can be closed.
