### ISSUE TITLE
[WC 4.3 RC1] Home Screen: After completing `Purchase & install extensions` step and returning back to the site, Inbox title shows the number of messages in the Inbox

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4670]
**Describe the bug**

Home Screen: After completing `Purchase & install extensions` step and returning back to the site, Inbox title shows the number of messages in the Inbox. It seems like a bug and the number of messages shouldn't be next to the title `Inbox`. 

**To Reproduce**

1. Complete onboarding on the fresh install. Make sure to select one of the paid extensions to be purchased during onboarding. 
2. In the `Finish setup` section - click on `Purchase & install extensions` - complete the flow and wait to be redirected back to the site.
3. Observe the number 3 in my case next to the title `Inbox` - it looks like `Inbox3` on my end. It seems to correspond to the number of messages in the Inbox section:

![inbox3](https://user-images.githubusercontent.com/19143190/85439648-3e4b6000-b55b-11ea-8691-5497ccbf9468.jpg)

**Expected behavior**

I expected the title of the Inbox section to remain `Inbox` (not `Inbox3`). 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.5
- Browser: Chrome
- Version: 83.0.4103.106 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by timmyc** [comment]
Fixed in #4681
