### ISSUE TITLE
[WC 4.3 RC1] Home Screen: Clicking on `Yes please!` for tips redirects user to the form where they are asked about WC install

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4672]
**Is your feature request related to a problem? Please describe.**

When the user clicks on `Yes please!` button  for tips, they are being redirected to our generic form for signing-up for tips which is fine but this form includes a question about how do they want to install WooCommerce and find it confusing for someone who already has a site with WooCommerce and just completed onboarding:

![yes, please](https://user-images.githubusercontent.com/19143190/85448687-f29db400-b564-11ea-8357-fe4638555468.jpg)

![?](https://user-images.githubusercontent.com/19143190/85448702-f6313b00-b564-11ea-9544-2e4a05fe0739.jpg)

**Describe the solution you'd like**

I realize the sign-up form is being used elsewhere in WooCommerce and in general a form to get our newsletters if I understand it correctly. Still, maybe better to create a separate form that doesn't include questions about WC Installation and Marketplace. 

**Describe alternatives you've considered**

N/A. 

**Should this be prioritized? Why?**

Not a super high priority. 

**Additional context**

N/A.

**Comment by becdetat** [comment]
The form that that button links to now only has the email address and first and last name, so I'll close this ticket 🍰
