### ISSUE TITLE
[WC 4.3 RC1] Home Screen: Card to connect to woo.com account is still shown after connecting to woo.com

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4673]
**Describe the bug**

After connecting to woo.com account through `Purchase & install extensions` step, the card to connect to woo.com is still shown. 

**To Reproduce**

1. Complete onboarding on the fresh install. Make sure to select one of the paid extensions to be purchased during onboarding. 
2. In the `Finish setup` section - click on `Purchase & install extensions` - complete the flow and wait to be redirected back to the site.
3. Navigate to `WooCommerce / Extensions / WooCommerce.com subscriptions` and confirm that you are connected to WooCommerce.com account:

![woocom](https://user-images.githubusercontent.com/19143190/85449758-1e6d6980-b566-11ea-8b36-a6abad9e9d2e.jpg)

4. Navigate back to Home Screen and note that the card to connect to woo.com account is still shown:

![woocom2](https://user-images.githubusercontent.com/19143190/85449894-4230af80-b566-11ea-842e-59d33d9a5dd1.jpg)

**Expected behavior**

I expected the card to connect to woo.com on the Home Screen not to show up after completing the `Purchase & install extensions` step. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.5
- Browser: Chrome
- Version: 83.0.4103.106 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by joshuatf** [comment]
Seems like the logic that calls `WC_Admin_Notes_Woo_Subscriptions_Notes::remove_notes()` may fall short somewhere.  Since this logic already exists and should be a matter of finding the bug that causes this within `update_option_woocommerce_helper_data`, I'd estimate this as a 2 to allow time for testing the WCCOM connection.
