### ISSUE TITLE
[4.3 RC1] Public function 'install_plugin' renamed to 'install_plugins'

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce-admin#4708]
**Describe the bug**

See https://github.com/woocommerce/woocommerce-admin/commit/bd394fd8bb4597813f47830f568324c43fb9f205#diff-21aca8e87b625c206696f3fe25c0162dR209

Renaming public functions makes it difficult for third parties to utilize the new `wc-admin` features. Pleeeease follow standard practices and deprecate replaced methods/functions. `wc-admin` is a vital part of WooCommerce now.

`install_plugin` should be preserved. If possible, transform old parameters and pass them to the new function as needed.

![2476666](https://user-images.githubusercontent.com/1783726/85834449-0da63900-b79c-11ea-9c55-fef4c918aee2.jpeg)

**Comment by franticpsyx** [comment]
Also: https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/WC_Admin_Notes_WooCommerce_Payments.php#L136

Won't this fail?

**Comment by timmyc** [comment]
Hey Manos - thanks so much for bringing this to our attention, and for finding a bug in that note as well. We will get this fixed up before 4.3 final. Curious to hear more about your usage of `install_plugin` too.

**Comment by timmyc** [comment]
And I really liked the photo to backup the need to fix this issue. It was a nice touch ❤️

**Comment by franticpsyx** [comment]
Hey @timmyc - thanks for looking into this!

> Curious to hear more about your usage of `install_plugin` too.

Our use case is almost identical to yours (WooCommerce core). Product Bundles has 2 popular feature plugins that are hosted on .org, and to make it easier for our users to discover (and, ideally, install) them we thought we' use the Inbox. Here's one example: https://a.cl.ly/Z4uY1qKZ
