### ISSUE TITLE
No user feedback after triggering the "Install now" note action to install a recommended plugin

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce-admin#4709]
**Describe the bug**

When clicking the **Install Now** primary note action to install a plugin (such as WooCommerce Payments), no feedback is provided to the user (success/failure). Instead, the entire Home page is reloaded and the plugin installation resumes/fails silently.

**Expected behavior**

Ideally, the page should not reload and the user should receive feedback. The code should ideally be re-usable in notes added by third parties.

**Comment by joshuatf** [comment]
Just to make a quick note here for fixing this issue- the `install_plugin` method should not be directly called from the note action and instead should dispatch a request to the plugins API endpoint.

See https://github.com/woocommerce/woocommerce-admin/pull/4411#issuecomment-650523744 for more detail on this change.
