### ISSUE TITLE
Onboarding: Benefits Page Broken on WordPress 5.3.x

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#4710]
**Describe the bug**
When transitioning from the theme selection step in the OBW to the benefits screen, the benefits screen fails to load and an exception is thrown:

![Home ‹ WooCommerce ‹ bend outdoors — WooCommerce 2020-06-26 10-32-27](https://user-images.githubusercontent.com/22080/85889897-30871c00-b7a1-11ea-88a1-13c72528b9b1.png)

The value of `getActivePlugins()` on the page is returning `undefined` instead of an array which results in the error above. I attempted to reproduce on a JN site, but it was working fine there. I checked out a few different revisions of wc-admin and determined the bug started happening after #4655 landed ( cc @joshuatf  ).

Perplexed, I did the dance of disabling all plugins except for woo/wca, and then realized that I was running an older version of WP on this particular site - 5.3.1 - compared to 5.4.2 which is on JN.

4655 added in the usage of `__experimentalResolveSelect` which appears to have been shipped in [version 4.10.0 of wp.data](https://github.com/WordPress/gutenberg/blob/release/7.1/packages/data/package.json#L3), and subsequently included in WordPress 5.4.x. So thinking that might the usage of `__experimentalResolveSelect` might be the root of the problem here, but I did not verify further.

I did verify that upgrading my site to 5.4.2 fixed the problem.

**To Reproduce**
Steps to reproduce the behavior, use a site running WordPress 5.3.1

1. Go through the onboarding wizard
2. Once you arrive at the benefits step, you should see the error above
**Additional context**

**Comment by psealock** [comment]
Ran into this today with [wc-admin 1.4.0-beta.1](https://github.com/woocommerce/woocommerce-admin/releases/tag/v1.4.0-beta.1-plugin).

One solution could be to bunble wp.data temporarily until we support only versions of WP that contain `__experimentalResolveSelect`.
