### ISSUE TITLE
Increase results returned when searching for products in the report table

### ISSUE THREAD

**Issue by thuautp** [woocommerce/woocommerce-admin#4720]
Original title: Analytics > Products doesn't show all products when a term is searched for

#3104915-zen

**Describe the bug**

when searching for a term, **Analytics > Products** doesn't return the correct number of products as when searched under Products. For instance, when customer searched for the term that is included in the product title, there were more than 10 products in the shop but only 10 products show up on Analytics page.

**To Reproduce**

1. Go to **Analytics > Products**
2. Enter a term to the Product search bar
3. See only 10 products returned without any pagination
4. From WordPress Dashboard, go to Products
5. Search for the same term, more than 10 products are returned (you'll need to have more than 10 products with the same term in the product titles)

**Expected behavior**
**Analytics > Products** should return all products that include the search term in the title

**Screenshots**

<img width="1253" alt="Screen Shot 2020-06-30 at 16 40 18" src="https://user-images.githubusercontent.com/13119409/86110997-766d1880-baf0-11ea-8a18-711695c2f620.png">
<img width="1229" alt="Screen Shot 2020-06-30 at 16 40 06" src="https://user-images.githubusercontent.com/13119409/86111014-7a009f80-baf0-11ea-838e-6839be183c1c.png">

**Comment by jeffstieler** [comment]
Currently, the autocompleter control for products (used for searching here) limits the request to 10 results: https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/search/autocompleters/product.js#L104

It's reasonable to increase this limit. I'm changing the issue type from "bug" to "enhancement" and recategorizing this as a feature request.
