### ISSUE TITLE
PHP notices on "WooCommerce Admin" when using WooCommerce with WPML after 4.0

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce-admin#4729]
`Notice: Undefined index: sitepress-style in /home/interges/novo.intergesso.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Loader.php on line 517

Notice: Trying to get property 'handle' of non-object in /home/interges/novo.intergesso.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Loader.php on line 485`

This happens on any WooCommerce admin page when using WooCommerce 4.0 (or above) with WPML.
Maybe this is a "WooCommerce Multilingual" issue and not a "WooCommerce" one.

**Comment by webdados** [comment]
Thanks @tammullen

**Comment by timmyc** [comment]
@webdados I'm having issues recreating this bug on WooCommerce 4.3.1 - I did install WooCommerce Multilingual from the .org repo ( I think this is the right extension ) and still can not see the message. 

Would it be possible to get a WooCommerce System Status report to see if we can reproduce?

**Comment by webdados** [comment]
Actually the notice is gone on my side too.

I'm going to close this for now and get back here if it shows up again.
