### ISSUE TITLE
Broken when SCRIPT_DEBUG is true due to lack of non-minified assets.

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce-admin#4738]
**Describe the bug**
When running WooCommerce 4.3.0-rc.2, which includes woocommerce-admin 1.3.0-rc.2 there are multiple errors on my test install due to missing non-minified versions of Javascript assets.

E.g.
With `SCRIPT_DEBUG` set to true, the following JS path is attempted to be loaded:
`/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/42.11cc196c5f0cb3a17439.js`

This fails as the non-minified JS was not included in the 1.3.0-rc.2 release (it was in 1.3.0-rc.1). 

Setting `SCRIPT_DEBUG` set to false (or not defined), the following JS path is attempted to be loaded which then works correctly:
`/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/42.11cc196c5f0cb3a17439.min.js`

**To Reproduce**

1. Install and set up WooCommerce 4.3.0-rc.2
2. Set `define('SCRIPT_DEBUG', true);` in your `wp-config.php`
3. Navigate to "WooCommerce" in the admin area of the WordPress install - you'll see a bank page instead of the WooCommerce home screen.

**Comment by becdetat** [comment]
Thanks @leewillis77, we just encountered this today internally. Currently the only workaround is, as you say, to set `SCRIPT_DEBUG` to false.

**Comment by fishtankmike** [comment]
I'm having this problem on the Analytics pages predominantly but there are similar error message on most pages in the admin area...

![Screen Shot 2021-03-02 at 10 22 30](https://user-images.githubusercontent.com/33543845/109635300-1d072e80-7b42-11eb-8c5b-37d09d3eb8c1.png)
