### ISSUE TITLE
Home Screen - store management section - extensibility

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4739]
**User story:**
As an extension developer
I want to be able to customize the Store Management section
So I can incorporate shortcuts to key flows in my extension 

**Description:** as the Home Screen is going to become the starting point every time a user enters WooCommerce, we should facilitate customization of the Store Management section by 3PDs.

**Acceptance Criteria:**
- [ ] Add a filter to the store management section so 3PDs can add shortcuts to different locations

**Comment by pmcpinto** [comment]
cc @timmyc

**Comment by lukecav** [comment]
Are there currently any filters to be able to replace the any of the existing store management links in the home screen of the WooCommerce Admin?

**Comment by timmyc** [comment]
@lukecav currently there are not any filters available to do so, but this issue would add in a filter to allow for items to be added/removed from the default list of store management links.

**Comment by lukecav** [comment]
@timmyc Thanks for the info.

**Comment by lukecav** [comment]
Any ETA on having any filters for the home screen?

**Comment by timmyc** [comment]
@lukecav we don't have this issue in our current sprint, so no ETA for this change currently. PRs are welcome though if this is something you would be keen on having access to.

**Comment by timmyc** [comment]
Looks like this was not closed out when we added in the [`woocommerce_admin_homescreen_quicklinks` filter](https://github.com/woocommerce/woocommerce-admin/blob/main/client/store-management-links/index.js#L162)
