### ISSUE TITLE
Onboarding - add a price toggle to the product selection step and move extension details to a popover

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#4741]
I've done a little exploration around ways we might display extension prices on a monthly basis, but still allow folks to view them annually as well. This will hopefully strike a better balance between transparency and value communication.

It also avoids some unnecessary repetition, and moving the extension details to a popover saves a lot of visual space.

### Before

![before](https://cldup.com/cXSen_C594-3000x3000.png)

### After

![design](https://cldup.com/aJCS8YW2cU.gif)

**Comment by joshuatf** [comment]
I think this is as simple as adding in a state property to determine which is shown and probably close to a 1, but I'll give this a 2 to be safe for any currency formatting and toggle styling.

Estimate: 2

**Comment by psealock** [comment]
Estimate: 1. Seems pretty simple implementation.

**Comment by becdetat** [comment]
I think it's a 1. The currency shouldn't be a problem, currently it's the annual price divided by 12 so we don't really need to worry about rounding issues.
