### ISSUE TITLE
Improvement of the Woocommerce reporting period

### ISSUE THREAD

**Issue by StephanHelbig** [woocommerce/woocommerce-admin#4748]
Here is a feature request regarding the new woocommerce reporting:

Additional to “last week” and “last month” the following periods would be very helpful:

Last 7 days
Last 14 days
Last 30 days

Stephan

**Comment by jamescl** [comment]
Hi - Came here to say the same thing! It's particularly frustrating to look at Month or Quarter to date for the first 15/45 days of the period!

I'd also like to see Last 90 and Last 365 to represent Quarter and Yearly.

**Comment by timmyc** [comment]
Hi @StephanHelbig 

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
