### ISSUE TITLE
Analytics: Sub-orders/Child Orders

### ISSUE THREAD

**Issue by yward** [woocommerce/woocommerce-admin#4749]
Hello there,

The issue is very simple, I'd like to exclude orders which parents aren't 0. so if parent = 0 show in the reports, if not exclude.

Any hint on how I can achieve that? As multiple plugins tend to create child orders to achieve functionality, which causes analytics to be inaccurate.

I'm very comfortable editing core code and/or using a code snippet. Perhaps add a "Parent" attribute to the advanced filters option?

**Comment by timmyc** [comment]
Hello there @yward - you could possibly look at utilizing [this filter](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Reports/Orders/Stats/Query.php#L57) to adjust the query logic on the reports. I'm going to close out this issue but feel free to comment back if we can be of further assistance.
