### ISSUE TITLE
Can't See WooCommerce Home

### ISSUE THREAD

**Issue by BFTrick** [woocommerce/woocommerce-admin#4753]
**Describe the bug**
I followed all of the steps to enable the WooCommerce Home screen but I don't see a Home screen.

**To Reproduce**

1. Start with an existing WooCommerce store.
2. Go to WooCommerce > Settings > Advanced > Features
3. Click on Home Screen
4. I don't see the new Home Screen 🤔

**Expected behavior**
See the home screen.

**Screenshots**
Screen capture: https://www.youtube.com/watch?v=_WZ8ffyi5ns

(I blacked out some sensitive information for a few seconds)

**Desktop (please complete the following information):**

* OS: MacOS Catalina 10.15.5
* Browser: Brave
* Version: 1.10.97

**Additional context**
`
### WordPress Environment ###

WordPress address (URL): ***redacted***
Site address (URL): ***redacted***
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ❌ Inactive 1.3.0-rc.2
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.17
PHP Post Max Size: 2 GB
PHP Time Limit: 600
PHP Max Input Vars: 16384
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.25-MariaDB
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_
Total Database Size: 8.64MB
Database Data Size: 6.46MB
Database Index Size: 2.18MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_ibx_wpfomo_conversion_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ibx_wpfomo_conversion_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 1.52MB + Index: 0.11MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.06MB + Index: 0.06MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 15
customize_changeset: 1
ibx_wpfomo: 2
nav_menu_item: 6
oembed_cache: 2
page: 10
post: 1
product: 1
product_variation: 2
revision: 14
shop_coupon: 2
shop_order: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Astra Pro: by Brainstorm Force – 2.5.1
Autoptimize: by Frank Goossens (futtta) – 2.7.3
Cache Enabler: by KeyCDN – 1.3.5
Disable Cart Fragments: by Optimocha – 1.21 – Installed version not tested with active version of WooCommerce 4.3.0
Disable WooCommerce Bloat: by ospiotr – 1.1 – Installed version not tested with active version of WooCommerce 4.3.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.11.0
iThemes Security Pro: by iThemes – 6.6.0
Jetpack by WordPress.com: by Automattic – 8.6.1
Ninja Forms: by Saturday Drive – 3.4.24.3
Product Feed PRO for WooCommerce: by AdTribes.io – 8.4.0 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Admin: by WooCommerce – 1.2.4 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.22 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Services: by Automattic – 1.23.2 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce: by Automattic – 4.3.0-rc.2
Yoast SEO: by Team Yoast – 14.4.1 – Installed version not tested with active version of WooCommerce 4.3.0
WP Disable: by optimisation.io - jody nesbitt – 1.6.0
WP Redis: by Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 1.0.1

Widget Disable: by required – 2.0.0
WPfomify: by IdeaBox Creations – 2.1.1.2
Sequential Order Numbers for WooCommerce: by WebToffee – 1.2.1 – Installed version not tested with active version of WooCommerce 4.3.0

### Inactive Plugins (7) ###

Asset CleanUp: Page Speed Booster: by Gabriel Livan – 1.3.6.5
Async JavaScript: by Frank Goossens (futtta) – 2.20.03.01
BJ Lazy Load: by Bjørn Johansen
Aron Tornberg
angrycreative – 1.0.9

Compress JPEG & PNG images: by TinyPNG – 3.2.1
WP All Import - User Import Add-On Pro: by Soflyy – 1.1.2
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.2.1 – Installed version not tested with active version of WooCommerce 4.3.0
WP All Import Pro: by Soflyy – 4.5.9

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

Nexcess Managed Apps: by Nexcess – 1.10.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 2.4.5
Author URL: https://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2020-07-06 08:42:15 -0600
Newest: 2020-07-06 08:42:15 -0600

Pending: 1
Oldest: 2020-07-07 08:42:15 -0600
Newest: 2020-07-07 08:42:15 -0600

`

**Comment by pmcpinto** [comment]
Hey @BFTrick, thanks for reporting this issue. It seems that you disabled the WooCommerce Admin pages, correct?

**Comment by BFTrick** [comment]
What pages exactly? Is there a setting I can check?

**Comment by pmcpinto** [comment]
Your system status shows that WC Admin is inactive: WC Admin Version: ❌ Inactive 1.3.0-rc.2

> What pages exactly?

When a user has WooCommerce Admin active, the default home is the Dashboard: https://d.pr/i/z4KFvL

> Is there a setting I can check?

We don't have a setting to enable/disable WooCommerce Admin. The only way is to download the following file and drop it in your wp-content/plugins folder to disable WooCommerce Admin: https://gist.github.com/joshuatf/006111b6f43c3ab3d2cad39e3443822b

Let me know if you have more questions.

**Comment by BFTrick** [comment]
I saw the notice about WC Admin being inactive... but the plugin is installed and active.

`WooCommerce Admin: by WooCommerce – 1.2.4`

If the plugin is already installed & active how could it be disabled? More importantly - how do I enable it?

**Comment by timmyc** [comment]
Hello @BFTrick - always nice to see you here on GitHub!

So its looking like the older version of the wc-admin plugin is being loaded:

> WooCommerce Admin: by WooCommerce – 1.2.4 – Installed version not tested with active version of WooCommerce 4.3.0

The plugin version takes preference over the bundled version of woocommerce-admin that ships with WooCommerce Core.

To test out this theory, could you disable the WooCommerce Admin plugin on the site? Version 1.2.4 of WooCommerce Admin does not have the home screen feature.

Alternatively, you could update WooCommerce Admin to version 1.3.0 which is the latest version in the .org repository, and that should fix it up too.

**Comment by pmcpinto** [comment]
@BFTrick were you able to enable the home screen?

**Comment by timmyc** [comment]
@BFTrick I'm going to close out this issue since we haven't heard back, but please do feel free to reopen if the problem is still persisting for you.

**Comment by BFTrick** [comment]
My bad. I haven't had time to dig in and see if it's still broken. Work is still pretty busy.

If I get a chance I'll investigate and leave another comment. 👍
