### ISSUE TITLE
Add Customer Name/Username to Orders tab in Analytics

### ISSUE THREAD

**Issue by spencerkphillips** [woocommerce/woocommerce-admin#4756]
**Is your feature request related to a problem? Please describe.**
In the orders tab of Analytics, you can see "Customer" but its only values are "New" or "Returning", this is confusing to some clients because you can't actually see who placed the order in this table.

**Describe the solution you'd like**
I would like to be able to see the customers name or username as a column in the table.

**Describe alternatives you've considered**
It could be an extension to the base Admin plugin for only those who need it and I have considered developing it myself but I am not quite experienced enough.

**Should this be prioritized? Why?**
I think it should be prioritized because it makes the data a bit more understandable and clear for the average user.

**Additional context**
If the column data was added or changed, it would still work fluidly and could be a toggle-able function.
![Analytics(Orders)](https://user-images.githubusercontent.com/34428007/86627887-039fe980-bf97-11ea-8de5-d9f6f9f05e6b.png)

**Comment by timmyc** [comment]
Hi @spencerkphillips 

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
