### ISSUE TITLE
Negative Net Sales Report on Refund

### ISSUE THREAD

**Issue by Frisoni** [woocommerce/woocommerce-admin#4757]
**Describe the bug**
When there is a refund, analytics panel subtract shipping value twice. Or sum twice, depending on your point of view :)

**To Reproduce**
1. Create an order with 1 item and shipping cost
2. Process order payment
3. Refund this order
4. You can still see shipping cost in analytics panel and Net Sales is subtracting Return ( item + shipping) and shipping, making shipping subtract twice.

**Expected behavior**
After return, net sales for that order should be zero.

**Screenshots**
Panel before order creation:
![image](https://user-images.githubusercontent.com/12817135/86641672-b2512380-bfb1-11ea-97dc-44ade17f5abb.png)

Created an order with one item ( R$ 249,90 ) plus shipping ( R$ 15,32 ).
Panel after order payment ok:
![image](https://user-images.githubusercontent.com/12817135/86641862-d4e33c80-bfb1-11ea-8458-38cda01f467a.png)

Refunded this order completely.
Panel after that:
![image](https://user-images.githubusercontent.com/12817135/86641935-e4fb1c00-bfb1-11ea-8e37-199d4cda34bb.png)

**Desktop (please complete the following information):**

* OS: Windows
* Browser Chrome
* Version 83.0.4103.116

**Comment by jeffstieler** [comment]
Hello @Frisoni, thanks for reporting an issue.

First off, my apologies for the delay in response.

I was unable to reproduce this issue on my test site. After refunding the order completely - making sure to enter the shipping refund amount in the shipping refund input - the report looks accurate:

![Screen Shot 2020-09-08 at 10 53 18 AM](https://user-images.githubusercontent.com/63922/92492755-b7a13900-f1c1-11ea-869e-c9c2fc2c7276.png)

Can you show the report table for your refund? Do you see a value in the shipping column for that refund, or perhaps was the total refund amount put into the "returns" column?

Thanks!

**Comment by Frisoni** [comment]
Hi Jeff,
thanks for your time.
I just did another example, this is my report table:
![image](https://user-images.githubusercontent.com/12817135/92493738-3e0e4880-f1cb-11ea-8cd5-f36fb3010b71.png)

One thing may be different in our tests.
To refund, I just open order, change status to refunded and save.
WooCommerce take care of refund process. Maybe this is an WooCommerce error refunding whole amount and not items and shipping separated?
Thats how it looks in my order (sorry it is in portuguese):
![image](https://user-images.githubusercontent.com/12817135/92494006-8ded0f80-f1cb-11ea-9c2f-f2c00c2f1064.png)

**Comment by jeffstieler** [comment]
Thanks for the clarification @Frisoni, that's very helpful!

We're tracking a potential enhancement to core WooCommerce to fix this here: https://github.com/woocommerce/woocommerce/issues/26563
