### ISSUE TITLE
Add Tracks to enable/disable Task List button

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4760]
**Description:** Add tracking to understand if the user is enabling/disabling the task list through the Help panel 
**Event name:** wcadmin_tasklist_toggled
**Even prop:** enable/disable

<img width="827" alt="Captura de ecrã 2020-07-07, às 11 27 43" src="https://user-images.githubusercontent.com/3380168/86768414-710a5380-c045-11ea-94b6-9f506ac3eabd.png">

**Comment by joshuatf** [comment]
Straightforward I believe.  Record an event in `reset_task_list()`.

Estimate: 1
