### ISSUE TITLE
Home screen as the default experience for every user

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4761]
**Description:** the time between 4.3 and 4.4 will be enough for existing users to experiment with the new home screen. This new screen should become the default home for everyone in the Core release that will be shipped in August.

**Acceptance Criteria:**
- [ ] Change the logic so the home screen becomes the default experience for everyone
~- [ ] Display an inbox notification about the new home screen for existing users, if #4590 isn't ready~

**Comment by lukecav** [comment]
Will there be a way to opt-out of using the new home screen in WooCommerce 4.4?

**Comment by pmcpinto** [comment]
Hey @lukecav we decided to postpone this change until 4.5.

**Comment by pmcpinto** [comment]
@lukecav can you share a bit more about why you want to remove the home screen? Is there anything else that you'd like to see there? We'd love to hear your thoughts :)

**Comment by lukecav** [comment]
@pmcpinto Just the number of requests on load in wp-admin on the home screen is all.

**Comment by pmcpinto** [comment]
> @pmcpinto Just the number of requests on load in wp-admin on the home screen is all.

👍 Thanks for your feedback

**Comment by claudiosanches** [comment]
@pmcpinto it need to be done in WC Admin side, I have already addressed #26972.

**Comment by jeffstieler** [comment]
Estimate: 1 - we don't need to add the inbox note.

**Comment by psealock** [comment]
Estimate: 1 - This is controlled by an option in core that is set to true on all new stores. This is just a matter of figuring out how to make the option `true` for existing stores while still allowing them to turn off the setting. And doing it in a backwards compatible way.
