### ISSUE TITLE
Admin pages "jump" after everything is loaded

### ISSUE THREAD

**Issue by Konamiman** [woocommerce/woocommerce-admin#4762]
**Describe the bug**

Most admin pages (all except "dashboard" and "customers", apparently) have their content loaded at a slightly lower position than usual, then after the page has finished loading the entire contents and assets it "jumps" up abruptly to its final position. It's not a critical bug but it's annoying.

**To Reproduce**

Just load any of the settings page in the admin area, except "dashboard" and "customers". Changing the tab in a tabbed page (e.g. settings) displays the same effect too.

**Screenshots**

(wait 9s after the tab is clicked)

![ScreenJumpsInAdmin](https://user-images.githubusercontent.com/937723/86787089-05d07980-c065-11ea-96e1-cc899e7417ad.gif)

**Desktop (please complete the following information):**

* OS: MacOS 10.15.5
* Browser Chrome 83

**Additional context**

Looks like it happens since WooCommerce 4.2

**Comment by becdetat** [comment]
Still happening in WooCommerce Admin 1.8.1
