### ISSUE TITLE
Latest updates crashes site

### ISSUE THREAD

**Issue by Milliways66** [woocommerce/woocommerce-admin#4777]
**Describe the bug**
The whole website is not accessible any more, since I installed the latest update (WooCommerce-admin 1.3.0). I had to deactivate wc-admin to be able to access the site again.

**To Reproduce**
1. Activate woocommerce-admin
2. that's it.

**Screenshots**
Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 127 der Datei /mnt/web218/d1/69/5145669/htdocs/anne-waterkant/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php verursacht. Fehlermeldung: Uncaught Exception: Ungültiger Datenspeicher für Administrator-Notiz. in /mnt/web218/d1/69/5145669/htdocs/anne-waterkant/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php:127
Stack trace:
#0 /mnt/web218/d1/69/5145669/htdocs/anne-waterkant/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
#1 /mnt/web218/d1/69/5145669/htdocs/anne-waterkant/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Note.php(87): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
#2 /mnt/web218/d1/69/5145669/htdocs/anne-waterkant/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes.php(109): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct('12')
#3 /mnt/web218/d1/69/5145669/htdocs/anne-waterkant/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Deactivate_Plugin.php(60): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes

WordPress-Version 5.4.2
Aktuelles Theme: Highlight PRO (Version 1.1.31)
Aktuelles Plugin: WooCommerce Admin (Version 1.3.0)
PHP-Version 7.3.18

**Comment by jfluna992** [comment]
I am getting the same error as described by you. I can only get the page to work while the plugin is inactive.

Error Details
=============
An error of type E_ERROR was caused in line 127 of the file /home/renovalc/public_html/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php. Error message: Uncaught Exception: Invalid data store for admin note. in /home/renovalc/public_html/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php:127
Stack trace:
#0 /home/renovalc/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
#1 /home/renovalc/public_html/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Note.php(87): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
#2 /home/renovalc/public_html/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes.php(109): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct('8')
#3 /home/renovalc/public_html/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Deactivate_Plugin.php(60): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes_with_name(Array)
#4 /home/renovalc/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php(6

**Comment by timmyc** [comment]
@Milliways66 and @jfluna992 sorry you have hit this issue - is there any chance you could share a WooCommerce System Status Report so we could investigate further?

Based off the stack trace, it seems there might be some corrupt data in the WooCommerce Notes table on the site.

**Comment by jeffstieler** [comment]
@Milliways66, @jfluna992, thanks for the report and I'm sorry this problem is affecting your stores.

Do you happen to know if your database user account is restricted from performing `ALTER` queries? That would cause the automatic database migrations to fail.

Thanks.

**Comment by timmyc** [comment]
Since we haven't heard back from you, we are going to close out this issue now. Please do respond back if you still need assistance.
