### ISSUE TITLE
Refresh button on every Analytics report page

### ISSUE THREAD

**Issue by Frisoni** [woocommerce/woocommerce-admin#4783]
**Is your feature request related to a problem? Please describe.**
When I get a new order and I'm already on Analytics Order page, and don't have any button to refresh data.
I can only achieve refresh by changing any filter option or by F5 browser page. 

**Describe the solution you'd like**
A nica button to refresh analytics data.

**Describe alternatives you've considered**

**Should this be prioritized? Why?**
No, but is it a nice feature.

**Comment by chihsuan** [comment]
@Frisoni Thanks for opening this issue! I understand that a fresh button can make it easier. However, I'm closing this since this has been here for a while and we can use F5 as a workaround. I think we can consider adding it whenever we have the bandwidth.
