### ISSUE TITLE
Activity Panel: Add a filter for extension developers

### ISSUE THREAD

**Issue by seb86** [woocommerce/woocommerce-admin#4785]
**Describe the solution you'd like**
Would be great for developers to extend the activity panel or hide the activity panels of their choosing when `wc_admin_connect_page` function is added to a custom page.

This filter would allow the following mock-up.

![mock-up](https://user-images.githubusercontent.com/497406/86993487-661a0500-c1a4-11ea-919c-979328310464.png)
> Mock-up of removing default panels and adding my own.

I am open to other suggestions if you have any.

**Should this be prioritized? Why?**
It's not a priority but would be great to give other developers possible ideas to use it for their own rather than just simply connecting.

**Comment by seb86** [comment]
Any updates on this being possible?

**Comment by jeffstieler** [comment]
Hello @seb86, thanks for opening an enhancement issue.

We're in the (design) process of moving elements around in the activity panels, so we don't want to introduce extensibility in an area that may not remain the same in the long term.

I'll keep this issue now and will follow up when there's more to share.
