### ISSUE TITLE
Home Screen - Jetpack prompt displayed if user already has JP installed

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4788]
**Describe the bug**
The prompt to install Jetpack is being displayed while I already have Jetpack installed and activated. In addition to that, I'm getting a weird message when I click to activate 

**To Reproduce**

1. Login in an existing store with WC 4.3 installed
2. Go to WooCommerce > Settings > Advanced > Features and activate the Home Screen
3. Go to the Home screen and see the Jetpack prompt
4. Click "Activate Jetpack" and see the following message in the snackbar: The requested plugin Jetpack is not in the list of allowed plugins.

**Expected behavior**
I was expecting to see the Stats Overview section without the JP prompt because I already have it installed and activated.

**Screenshots**
https://www.loom.com/share/10a26faa75f74163a0af276a528a2d71

**Comment by dougaitken** [comment]
I have replicated this for two stores. 

My main site is already Jetpack connected but shows "Activate Jetpack" even when that WordPress user is the main JP connection. Clicking Activate results in the message that Pedro mentions.

Second, to this, I activated the Jetpack on another site and "Activate Jetpack" changed to "Connect Jetpack" - is there a reason this extra step is needed, is there an authorization that is needed? 

After clicking "Connect Jetpack", I got the generic message:

<img width="504" alt="Screenshot 2020-07-14 at 07 01 52" src="https://user-images.githubusercontent.com/52214/87390622-23d83580-c5a1-11ea-98ed-36c078fbb4d8.png">

**Comment by pmcpinto** [comment]
Thanks Doug for checking this bug. Yep, AFAIK that step is required to approve the connection

**Comment by jeffstieler** [comment]
I was unable to reproduce this locally and on a JN site.

On the JN site I:
1. Installed and connected JP
1. Installed WC 4.2.2
1. Went through the setup wizard
1. Upgraded to WC 4.3
1. Enabled the home screen feature
1. Did not see the Jetpack prompt in the Stats widget on the home screen

**Comment by pmcpinto** [comment]
@jeffstieler I'll send you through Slack the access to an existing site where I'm getting this issue.

**Comment by jeffstieler** [comment]
Thanks for that @pmcpinto! I'm able to reproduce this now.

This occurs when onboarding is not enabled - either by turning off the feature, or by clicking "skip setup" on the core notice, or by clicking "not right now" on the full screen takeover.

**Comment by pmcpinto** [comment]
Great. Thanks for taking care of this issue!
