### ISSUE TITLE
Inbox Panel/Home Screen: messages targeted for new users being displayed in existing users inbox panel

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4789]
**Describe the bug**
I'm seeing new inbox notifications in a store that I created a couple of months ago that should only target new stores. Namely:
#4201
#4178
#4351

**To Reproduce**

1. Login in an existing store with WC 4.3 installed
2. Go to WooCommerce > Settings > Advanced > Features and activate the Home Screen
3. Go to the Home screen and see inbox notifications that should only target new users

**Screenshots**
https://d.pr/i/JT5HyC

**Comment by timmyc** [comment]
@pmcpinto I just checked a few of my sites that auto-updated to 4.3 and I'm not seeing similar behavior. So have a few thoughts about maybe how this happened...

Did you by chance use "Dismiss All" on this site during testing - or did you do any other operations against the note table to test things out? I know some PRs had instructions to do things like clear out your notes table.

The other part of this that I think we need to consider is introducing a date range on store age for notes. So right now we have a great deal of notes that are "show after a site has been online for x days" - but we need to introduce a range for those so established/long-running stores don't see all notes.

Either way, given I'm not seeing this myself on some sites, and to truly fix the root problem here ( which I think is having an upper-end date range ) I don't see us having the time to get a fix in place for 1.4

**Comment by pmcpinto** [comment]
> Did you by chance use "Dismiss All" on this site during testing - or did you do any other operations against the note table to test things out? 

AFAIR I didn't use the Dismiss all feature in this store. I just dismiss one or two messages

> The other part of this that I think we need to consider is introducing a date range on store age for notes. So right now we have a great deal of notes that are "show after a site has been online for x days" - but we need to introduce a range for those so established/long-running stores don't see all notes.

@timmyc what do you mean by date range? Most of the messages for new users refer to store creation date and not being online. Eg: Show message x days after the store creation

**Comment by timmyc** [comment]
@pmcpinto we currently set a timestamp when wc-admin is first installed to determine the "age" of a store ( [code here](https://github.com/woocommerce/woocommerce-admin/blob/a7eef57b50f02ba770a0e07328636d3ee096476a/src/Install.php#L173) ). So with that approach, sites that are established on Woo on an older version ( pre 4.0 ) could also be considered "new" based on this pattern. Likewise if someone had wc-admin disabled via a filter, then enabled it.

It is an okay approach to determine site age, but there are still edge cases where it might not be valid.

**Comment by pmcpinto** [comment]
Ok thanks for the clarification. So what would be the best way to start introducing a date range?

**Comment by joshuatf** [comment]
@pmcpinto We would need to establish an upper-end to all those dates.  For example, if we have a note that requires a site to be at least 10 days old, we'd need to add an upper limit, like 20 days, so that the site must be between 10 and 20 days old.

The reason some notes may not appear right away or could max out on the upper end is due to other conditions.  For example, a note may require that at least one product exists before being added.  So while the site may be only need to be 10 days old, the note might not get added until day 100 if that's the first day a product is added.

If you'd like, we can establish an upper limit for all those notes.  Here's a quick reference for the notes that take into account how long a site has been active for:

https://github.com/woocommerce/woocommerce-admin/search?q=wc_admin_active_for

**Comment by samueljseay** [comment]
+1 for @joshuatf 's comment here. I ran into this recently when reviewing newly introduced notes and I thought it was curious that we do a check like "is the store *at least this old*" for checking if a store is "new". 

One thing we could do is define a bunch of standard "activation times" and then go ahead and create a task to apply those to all existing notes. Something such as "new store (1-7 days)", "early days (14-21 days)", "seasoned store (1 year - 2 years)" Thats just a brainstorming type idea, one thing I notice about our current checks for activation time is that they're not too evenly distributed.

**Comment by pmcpinto** [comment]
That's a good idea. I think that with around 5 segments we can have good coverage. What's the amount of effort required to make this update?

**Comment by samueljseay** [comment]
@pmcpinto After specifying the 5 "segments" I would say its about 3-5 days of effort for 1 developer broken up as:

1-2 days: add the new segments functionality to notes
2-3 days: migrating all the existing notes, most of the effort here is just a lot of little PRs to get reviewed (or alternatively a few larger PRs)

**Just to clarify though, this does not cover the remote inbox, @becdetat can you get a date range by adding 2 "wc_admin_active_for" rules to remote inbox notifications?**. If we wanted to add a new "segment" type rule to remote inbox that would be extra effort I'm guessing (and I'm not sure if it makes as much sense there).

**Comment by pmcpinto** [comment]
@samueljseay thanks for providing a high-level estimation. I think we should move forward with it. Here it goes the segments:

- Week 1
- Week 2-4
- Month 1-3
- Month 3-6
- +6 months

I don't have any preferences in terms of naming them

**Comment by ilyasfoo** [comment]
Pinging @becdetat ICYMI

**Comment by samueljseay** [comment]
I'd like to revive this ticket, re-pinging @becdetat can we do date ranges on remote inbox notifications with 2 rules? 

Either way we can at least move forward with adding distribution to the non-remote inbox notifications, I think this will be a solid improvement to the inbox's usefulness.

**Comment by jeffstieler** [comment]
@louwie17 if https://github.com/woocommerce/woocommerce-admin/pull/6969 partially addressed this, what remains to be done?

**Comment by louwie17** [comment]
> @louwie17 if #6969 partially addressed this, what remains to be done?

Updating any other notes that make use of `self::wc_admin_active_for` and use the new date_range method instead (`is_wc_admin_active_in_date_range`), where applicable (although from my understanding the preference is to use this as the default ).

**Comment by mattsherman** [comment]
@louwie17 Is this still being actively worked on? Should we wrap it up, or shelve it for now?

**Comment by louwie17** [comment]
> @louwie17 Is this still being actively worked on? Should we wrap it up, or shelve it for now

Thanks for the reminder on this, this needs to be wrapped up. I should be able to do that relatively quickly.
