### ISSUE TITLE
Activity Panel Notes: Apply custom style

### ISSUE THREAD

**Issue by seb86** [woocommerce/woocommerce-admin#4791]
**Is your feature request related to a problem? Please describe.**
I find the notes a bit washed out.

**Describe the solution you'd like**
I would like to apply a style of my own for my notes but there is no class that identifies the note.

Should be fairly simple to apply like so.

![image](https://user-images.githubusercontent.com/497406/87075807-2f360480-c221-11ea-844f-e9a43256d5e1.png)

**Should this be prioritized? Why?**
Accessibility and branding possibilities.

**Comment by seb86** [comment]
Quick mock-up of applying a unique style to a note.

![image](https://user-images.githubusercontent.com/497406/87076319-dfa40880-c221-11ea-92e2-e4de21bc8474.png)

**Comment by pmcpinto** [comment]
Thanks for your suggestion. We already provide the option to include graphics/illustrations to notifications and we think that this will be enough to add some personality/branding to the message. I'm going to close this issue, but feel free to add additional feedback.

**Comment by seb86** [comment]
Really? How @pmcpinto ?

**Comment by pmcpinto** [comment]
@seb86 here you have an example that includes image: https://gist.github.com/octaedro/864315edaf9c6a2a6de71d297be1ed88

I hope this helps
