### ISSUE TITLE
Looker dashboard: filter out event props

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4797]
Some of the Tracks changes in 4.3 can potentially inflate some of the metrics that we're tracking on Looker:

**User Retention and Engagement dashboards:**

`wcadmin_page_view` now includes page views in any WC page, which can mess up with the stats that we have in the aforementioned dashboards and we're already tracking it through other events.

I'm wondering if we could add a filter or exclude the ones that start with `/wp-admin/` in the `path` prop.

**Activation dashboard:**

By displaying the Store Profiler as marked in the task list, leading to an increase of the `wcadmin_tasklist_task_completed` event, which will impact the Setup moment metric.

Can we exclude the `wcadmin_tasklist_task_completed` events that have `store_details` in the `task_name` prop?

**Comment by pmcpinto** [comment]
@joshuatf let me know if this is doable or if you have a different solution. Thanks

**Comment by joshuatf** [comment]
>Can we exclude the wcadmin_tasklist_task_completed events that have store_details in the task_name prop?

@pmcpinto does this mean it doesn't count towards the (3?) tasks required to match the criteria?

>I'm wondering if we could add a filter or exclude the ones that start with /wp-admin/ in the path prop.

I think this is pretty straightforward.

Estimate: 3 (pending confirmation on the above task completion question)

**Comment by pmcpinto** [comment]
> @pmcpinto does this mean it doesn't count towards the (3?) tasks required to match the criteria?

Yes. I think we only started including the store details once it was added as a task in the home screen, right?

> I'm wondering if we could add a filter or exclude the ones that start with /wp-admin/ in the path prop.

Regarding this, it would be better to have a filter instead of just excluding the events.

Thanks

**Comment by pmcpinto** [comment]
> Yes. I think we only started including the store details once it was added as a task in the home screen, right?

@joshuatf do you have some feedback regarding this? Thanks!

**Comment by pmcpinto** [comment]
I'm closing this one as it's going to be handled by Woo Data
