### ISSUE TITLE
Category report being generated incorrectly

### ISSUE THREAD

**Issue by GuerrillaCoder** [woocommerce/woocommerce-admin#4798]
**Describe the bug**
Category report is not being generated correctly.  I believe the wrong route is being used.

**To Reproduce**

1. Go to Analytics -> Categories
2. Select last month
3. Select a single category
4. Data is displayed correctly
5. Click download to generate an email report
6. Report data does not match the screen data

**Expected behavior**
The report should match the data shown.  In fact the data is completely different and seems to have all products.

**Additional context**

I believe the problem here is the front-end app is generating a request to the wrong route.  In dev tools I can capture the ajax request which is as follows:

```
Request URL: https://mydomain.com/wp-json/wc-analytics/reports/products/export?_locale=user

{"report_args":{"orderby":"items_sold","order":"desc","after":"2020-06-01T00:00:00","before":"2020-06-30T23:59:59","page":1,"per_page":25,"categories":"3801","extended_info":true,"segmentby":"product"},"email":true}
```

This is sending to the products report and not the categories report.  I believe if this directed to the correct endpoint then issue should be resolved

Also here is the event logged in console with debugging enabled

![image](https://user-images.githubusercontent.com/11444395/87191751-f5cacb00-c2ec-11ea-9307-2a56d5d9b868.png)

It also shows wrong report

**Comment by jeffstieler** [comment]
Hello @GuerrillaCoder, my apologies for the delayed response.

That is the correct endpoint for a Categories report that is in "Single Category" mode. When you are only reporting on one category, the query is for the Products in that Category, rather than just aggregate data for the chosen Category.

Can you elaborate on how the "Report data does not match the screen data"? Thanks!

**Comment by GuerrillaCoder** [comment]
I want to run a report that is a summary of the categories for previous month.  I run this report in the admin and can see the data I want.  When I click download it emails me the product report which I don't want.

I checked the endpoint it makes call to and it is the endpoint I gave in issue but this isn't the report I want and not the report I can see on screen.

I have done a workaround of copying the nonce and cookie into postman and hitting the correct endpoint with the payload manually but it is a bit annoying.  

Are you able to generate the category report for previous month?

**Comment by jeffstieler** [comment]
Here's a category report for the previous year alongside the emailed CSV export:

![Screen Shot 2020-09-08 at 11 21 34 AM](https://user-images.githubusercontent.com/63922/92500137-b6c0d500-f1ca-11ea-9dd0-3ba24d10ff7c.png)

Are you saying that without a single category select (so it says "All categories" under "show") that you're receiving a products report when clicking "download"?

Can you screenshot your report page before clicking download? Thank you!

**Comment by GuerrillaCoder** [comment]
It's working working now.  Maybe an update changed something since I last looked, I am not sure.  Thanks for looking at it.
