### ISSUE TITLE
Mailchimp redirect on onboarding profiler completion

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4819]
**Describe the bug**
On successful completion of the onboarding profiler when Jetpack is redirecting to the connection flow, Mailchimp sometimes catches the redirect and redirects to its own setup screen.

We may need to filter `mailchimp_woocommerce_plugin_do_activation_redirect` to prevent this from happening, at least on any `wc-admin` page.

**To Reproduce**

(There may be more steps to reproduce this)
1. On a fresh install, walk through the profiler, installing Mailchimp under the business extensions option.
1. Complete the profiler.
1. Note that you're redirected to Mailchimp (hopefully).

**Expected behavior**
Expected to reach the Jetpack connection flow.

**Comment by timmyc** [comment]
@joshuatf I reported this to the mailchimp devs last month and I believe they were going to work on a fix based upon OBW data... as-in if MC was installed during the OBW, they were not going to do the redirect anymore.

**Comment by joshuatf** [comment]
Thanks for the heads up @timmyc!

>MC was installed during the OBW

My fix was a similar one.  If OBW is still active, we prevent the redirect.  Do you think this is better handled outside WCA?

I suppose it's technically an issue with the Mailchimp plugin as this should probably only being adding redirects on the plugins page.  Any async installation is going to result in this odd redirect behavior currently.

**Comment by timmyc** [comment]
I'd prefer if we handle it outside of WCA, though since we are the ones installing it - I can see the reasoning for adding a fix in WCA too. I'll ping MailChimp to see if they implemented a fix yet based upon `woocommerce_onboarding_profile` values.

**Comment by timmyc** [comment]
Version 2.4.2 of MailChimp for WooCommerce will include a fix for this. The planned release date is Monday July 27 so we should test this out once it hits the .org repository... verify the fix is good, and then we can close this out.

**Comment by timmyc** [comment]
Closing this out since MailChinp fixed it.
