### ISSUE TITLE
Task List - Payments step: Include eWAY for AUS stores

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4822]
We need to include eWAY in the Payments step list as an option for stores located in Australia and New Zealand, as it's one of the extensions that was being promoted in the old obw.

We can use the same approach that we have for other local provides, such as Payfast in South Africa

- After automatically installing [eWAY ](https://wordpress.org/plugins/woocommerce-gateway-eway/) from .org we should display the 2nd step asking for the `eWAY Customer API Key` and the `eWAY Customer Password`.

Description for the Payments 1st step: The eWAY extension for WooCommerce allows you to take credit card payments directly on your store without redirecting your customers to a third party site to make payment.

The message "Your API details can be obtained from your eWAY account" should link to https://www.eway.com.au/.

The Payfast example in South Africa: https://d.pr/i/dpI3BD

**Comment by timmyc** [comment]
Prior art from Payfast integration: https://github.com/woocommerce/woocommerce-admin/pull/3738
