### ISSUE TITLE
Invalid data store for admin note after update to version 4.3.0, my site broken

### ISSUE THREAD

**Issue by cartoonistarif** [woocommerce/woocommerce-admin#4823]
After update to version 4.3.0, my site http://www.toonsmag.com broken. Not working, white screen. In the admin dashboard, it says, “There has been a critical error on your website. Please check your site admin email inbox for instructions”. In frontend “There has been a critical error on your website”.
Is there anyone who has an idea of how to fix the issue?

Site send me an email with the following message:

WordPress version 5.4.2
Current plugin: WooCommerce (version 4.3.0)
PHP version 7.2.31

Error Details
=============
An error of type E_ERROR was caused in line 127 of the file /home/toonsmag/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php. Error message: Uncaught Exception: Invalid data store for admin note. in /home/toonsmag/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php:127
Stack trace:
#0 /home/toonsmag/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
woocommerce/woocommerce#1 /home/toonsmag/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WC_Admin_Note.php(87): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
woocommerce/woocommerce#2 /home/toonsmag/public_html/wp-content/plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php(273): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct(‘1’)
woocommerce/woocommerce#3 /home/toonsmag/public_html/wp-includes/class-wp-hook.php(287): WC_Notes_Run_Db_Update::show_reminder(Object(WP_Screen))
woocommerce/woocommerce#4 /home/toonsmag/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
woocommerce/woocommerce#5 /home/toonsmag/p

**Comment by peterfabian** [comment]
Transferring as I believe the data store needs to handle failed upgrades more gracefully.

1. We should very rarely (or never) remove columns from the database (at least without long deprecation periods)
2. New columns added to the database need to have graceful failures when they don't exist. Some people have limited privileges to ALTER/CREATE TABLE. These errors are often fatal when not handled well.

**Comment by peterfabian** [comment]
We have seen several reports on this, I think it might be worth including this in 4.3.1 (along with the fixes for order cleanup job in Blocks: [draft cleanup behind a feature flag](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2874) and [belts and braces before removing orders](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2844)). What do you reckon, @timmyc ?

**Comment by peterfabian** [comment]
Looking at `Automattic\WooCommerce\Admin\Notes\DataStore`, it might be a bit more messy than just fixing the `read` and `update`, as some data store methods are not returning a subset of specific columns from the database (e.g. `get_notes`).

**Comment by timmyc** [comment]
@jeffstieler is looking into this.
