### ISSUE TITLE
Can't complete WooCommerce onboarding wizard with Divi theme

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-admin#4835]
**Describe the bug**
(Possibly related to #4123). When Divi theme is installed and active, there's no option to complete the WooCommerce onboarding wizard. At the last step when I click **Choose** under Divi, I'm only seeing an error message `Invalid theme divi`. The only option to proceed further is to install and activate another theme.

**To Reproduce**

1. Install and activate Divi theme on a clean site.
2. Install and activate WooCommerce.
3. Complete onboarding wizard steps 1-4.
4. At step 5, click Choose under currently active Divi theme.
5. Observe the error.

**Expected behavior**
I can continue and complete the onboarding wizard with the current theme I'm using. 

**Screenshots**
![Screenshot](https://d.pr/i/0y2vkN+)
Screenshot: https://d.pr/i/0y2vkN

**Desktop (please complete the following information):**

* OS: OS X 10.14.6
* Browser Chrome
* Version 83

**Additional context**
Reproduced on a clean installation, with WooCommerce 4.3 and Divi 4.5.1

**Comment by joshuatf** [comment]
@madeincosmos Thanks for reporting this issue!  Is your Divi theme folder under `wp-content/themes` capitalized or lowercase?

If it's capitalized then this issue may be related to https://github.com/woocommerce/woocommerce-admin/pull/4706 which is resolved on the current `main` branch.

**Comment by madeincosmos** [comment]
Thanks @joshuatf, I had the folder name capitalized the last time. Now that I changed it from `Divi` to `divi` on another test site, the setup wizard completed without any problems. Glad to hear there's a fix under way for capitalized theme names as well! 🎉

**Comment by timmyc** [comment]
Since #4706 has been merged, I am going to close this out.
