### ISSUE TITLE
Addition to Bug - Content editor toolbar is hidden by admin header #2337

### ISSUE THREAD

**Issue by PaulKaan** [woocommerce/woocommerce-admin#4838]
**Describe the bug**
Bug details are the same.

The only addition being that the 'Add Media' button on the edit product page is still hidden by the admin header requiring excessive scrolling to view and use the 'Add Media' button.

**To Reproduce**

**Expected behavior**
The 'Add Media'

**Screenshots**

**Desktop (please complete the following information):**

* OS: Mac OS 10.15.5
* Browser Chrome
* Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

**Comment by timmyc** [comment]
Confirmed this bug is present:

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/22080/89472630-b77ecb00-d735-11ea-8c4e-706124ebbb71.png">

It is best seen when scrolling in a longer product description.

**Comment by Dygerati** [comment]
Could I get a little clarity on the expected behavior/display here? I can see that the "Add Media" button is concealed, resulting in lots of scrolling; should it simply be fixed and visible above the other toolbar when scrolling?

Something like this:

![image](https://user-images.githubusercontent.com/444632/93833563-cd851400-fc2d-11ea-8766-6e4ce05ff076.png)

**Comment by timmyc** [comment]
@Dygerati I think that is the desired outcome to still be able to click the "Add Media" button when scrolled down within the body of a long product description.

**Comment by Dygerati** [comment]
In a recent conversation with Josh, he had some comments on this bug, and after perusing a bit I tend to agree. It's actually not an easy fix without touching WP core code, so may require a pull request in that direction.

To sum up, the code that controls this logic lives in the `editor-expand.js` file which belongs to core. The relevant lines on my local are on 623 & 640, and look like the following:

```
$tools.css({
    position: "fixed",
    top: heights.adminBarHeight,
    width: contentWrapWidth
});
```

This code is actually run on every scroll event, and the computed margin is based on this `heights.adminBarheight` property that's set further up in the file and based on the `$("#wpadminbar").outerHeight()`. 

There's no supported way to alter this. There _may_ be hacky way to do so but I'm actually not convinced of that. Any attempts to adjust any values that would effect this value (ie padding, margin isn't included in $.fn.outerHeight() by default) skew the UI as you might expect.
