### ISSUE TITLE
Diacritics stripped out from UI labels

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce-admin#4854]
**Describe the bug**
Various WooCommerce Admin UI elements labels do not handle diacritics properly. A preg_replace that handles escaping of those values strips out any non-latin letters. A simple workaround is to add an "u" PCRE_UTF8 modifier to preg_replace functions in Controllers.

Eg. Performance Indicators in Stats overview panel at the new Home screen. Correct polish translation for "Orders" is "Zamówienia" (notice that it's a single word, the "ó" letter in the middle). Then it is escaped improperly as "Zam wienia" (with a space instead of the diacritic letter, also suggesting that there are 2 words).

When adding "u" modifier to its regex at line 177 of the /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/PerformanceIndicators/Controller.php file, diacritics works fine.

I assume that the bug exists also in other places in the UI, eg. toggles in the three dots menu of the Stats overview panel and it's not limited to this particular screen or panel.

PS. I'm also wondering why the preg_replace escaping function in those Controllers is replacing non-valid characters with space, instead of just empty string? Is it on purpose, or it's an another bug?

**To Reproduce**

1. Switch WP translation to Polish (or other language using an alphabet with diacritics) 
2. Go to WooCommerce->Home.
3. See Orders label is incorrect in Performance Indicators of the Stats overview panel.

**Expected behavior**
Diacritics should not be stripped out from labels.

**Screenshots**
![Zrzut ekranu 2020-07-23 o 10 13 07](https://user-images.githubusercontent.com/27000783/88265268-77e3c800-cccd-11ea-8aff-32518649a03d.png)

**Additional context**
WC: 4.3.1
WP: 5.4.2
WC Admin: 1.3.1 (bundled with WC)

**Comment by starypop** [comment]
Hey @timmyc @joshuatf @psealock ,

As the new home screen is enabled for everyone by default since WC 4.6 version, this bug affects all site owners/managers. Could you guys please take a look at possible fix?

Thanks!

**Comment by psealock** [comment]
>I'm also wondering why the preg_replace escaping function in those Controllers is replacing non-valid characters with space, instead of just empty string? Is it on purpose, or it's an another bug?

Looking through the history, it appears to be a shortcut to change `Gross Sales.` into `Gross Sales` (remove the "."). I think this is an oversight. PR coming soon 😄
