### ISSUE TITLE
formatCurrency is not a function error on WooCommerce Payments pages

### ISSUE THREAD

**Issue by jrodger** [woocommerce/woocommerce-admin#4860]
**Describe the bug**
Opening a WooCommerce Payments page (let's say the Transactions page) with a version of WC Admin after 227898e712e9e3fc2fc06bd6409e782e7a695f97 (Currency package: make naming clearer) causes the page to not load and `Uncaught TypeError: ra.formatCurrency is not a function` in console.

**To Reproduce**

1. Site with WooCommerce Payments setup
2. Open Payments > Transactions from the nav
3. See error

The error is due to the `formatCurrency` function being renamed to `formatAmount`. I appreciate this is all about how we manage dependences across plugins, and this is more of a request for advise than an issue report.

The immediate problem is that on upgrading to a version of WooCommerce with this change in, a site with the current version of WooCommerce Payments will be unable to use the Payments screens.

That aside, I see a few options:

1. Keep the new version of the Currency package backwards compatible by adding `formatCurrency` back in as an alias for `formatAmount`. The obvious downside here is clutter in your code base.
2. WooCommerce Payments bundles a known version of `@woocommerce/currency`. We've been trying to avoid doing this due to package sizes concerns, but it is an option. It also doesn't help with the immediate problem because current WCPay versions use whatever WC Admin makes available.
3. WooCommerce Payments updates calls to `formatCurrency`, which fixes things for new installs but leaves a problem with supporting mixed versions of WooCommerce.

**Comment by timmyc** [comment]
@psealock could you look into this? Perhaps we should retain the legacy method, add a deprecation warning, and just have it call the new method name so we don't break any code that other developers have built on the old `formatCurrency()` method.

**Comment by psealock** [comment]
Thanks @jrodger for bringing this up. I think it highlights a few problems. 

First, we're behind on releasing packages. This at least announces breaking changes, ie https://github.com/woocommerce/woocommerce-admin/blob/main/packages/currency/CHANGELOG.md and gives things like Renovate to highlight a major version change.

Of course this doesn't help if you're simply using `@woocommerce/currency` found in whatever version of WC the user has installed. I think we should introduce a deprecation warning and alias `formatCurrency` as suggested above in option 1. Gutenberg likely has a precedent already set in this regard.

**Comment by jrodger** [comment]
Thanks @psealock!

Since this is a simple API change, perhaps we can use it as a test run in WCPay for how we go about moving off a deprecated method. I've created https://github.com/Automattic/woocommerce-payments/issues/809 so we can look into a process for that on our end.
