### ISSUE TITLE
Use wp.data controls as an alternative to `experimentalResolveSelect` in Jetpack CTA

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#4865]
`experimentalResolveSelect` is problematic to use on older versions of Wordpress because its not available on the wp.data global. For now we are bundling a copy of it.

The original work to add `experimentalResolveSelect` is in https://github.com/woocommerce/woocommerce-admin/pull/4655

To remove the bundled copy we could take an approach of implementing a `@wordpress/data` control instead. (see here for a good overview of the purpose of controls: https://unfoldingneurons.com/2020/wordpress-data-store-properties-controls).

**Comment by timmyc** [comment]
Thanks for logging this @samueljseay 🙇
