### ISSUE TITLE
[WC 4.4 beta1] OBW - Tell us about your business: make more clear what account is required to install recommended features

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4881]
**Is your feature request related to a problem? Please describe.**

During OBW on the `Tell us about your business` page, it is not clear what account is required to install recommended features:

![account](https://user-images.githubusercontent.com/19143190/88836294-766e4000-d1a4-11ea-9b25-6bdc5c61cebc.jpg)

**Describe the solution you'd like**

I assume that the WooCommerce account is required but it is not immediately clear and may not be clear to the new user. It will be great to specify what account is required such as `Requires a WooCommerce account`. 

Another thing that arises here is that even if there is a note regarding the type of account required, there is no indication if the user already has an account. In other words, it is hard to know what to do with this information. Do I need to create an account now? How can I do that? Do I need to exit OBW now to do that? If I exit, how do I go back? If I keep going with OBW, how can I make sure I get all these features later if I don't have an account? 

Would be nice to have a note on the `Tell us about your business` page that answers the questions above. 

**Describe alternatives you've considered**

N/A.

**Should this be prioritized? Why?**

IMO, it should be prioritized in order for the customers to have a clear understanding of the options they have at that exact moment they are on the `Tell us about your business` page based on whether or not they have an account. 

**Additional context**

N/A.

**Comment by jameskoster** [comment]
This line is actually referring to _all_ of the features we install here.

* Jetpack
* WooCommerce Services
* Facebook
* Mailchimp
* Google Ads

All require accounts. I wonder if it would help to combine the two paragraphs of small text to highlight that association? So instead of:

> The following plugins will be installed for free: Jetpack, WooCommerce Services, WooCommerce Payments, Facebook for WooCommerce, Mailchimp for WooCommerce, Google Ads

> An account is required to use these features

We display:

> The following plugins will be installed for free: Jetpack, WooCommerce Services, WooCommerce Payments, Facebook for WooCommerce, Mailchimp for WooCommerce, Google Ads. User accounts are required to use these features.

**Comment by juliaamosova** [comment]
Thanks for reviewing this @jameskoster! 

I like the clarification you propose as it is clear that separate accounts with each of these services are required:

>The following plugins will be installed for free: Jetpack, WooCommerce Services, WooCommerce Payments, Facebook for WooCommerce, Mailchimp for WooCommerce, Google Ads. User accounts are required to use these features.
