### ISSUE TITLE
[WC 4.4 beta1] Task List: `Set up WooCommerce payments` task is marked as done if you set up any other payment via `Set up additional payment providers` Inbox card.

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4884]
**Describe the bug**

If the user enters the US address during OBW and selects to install additional business features, the `Set up WooCommerce payments` task appears in the Task List when OBW is completed. So far so good. 

However, `Set up WooCommerce payments` task is marked as done if you set up any other payment via `Set up additional payment providers` Inbox card.

**To Reproduce**

1. Start OBW.
2. Enter the US address on the `Store details` section of the OBW. 
3. On the `Tell us about your business` page select `Install recommended free business features` checkbox.  
4. When OBW is completed, you should see `Set up WooCommerce payments` task on the Home screen as well as the `Set up additional payment providers` Inbox card:

![pay](https://user-images.githubusercontent.com/19143190/88845471-344bfb00-d1b2-11ea-89a8-2db75f191596.jpg)

5. Click on the `Set up WooCommerce payments` task and note that you would be prompted to set up WooCommerce Payments:

![ay2](https://user-images.githubusercontent.com/19143190/88845671-7ecd7780-d1b2-11ea-9aa3-52ebc7611f19.jpg)

6. Don't proceed. Go back to the Home page instead. The `Set up WooCommerce payments` task should still be not completed. 

7. Click on the `Set up additional payment providers` Inbox card. 
8. You will be redirected to the screen with different payment options setup. Select `Cash on delivery` option and click on the `Done` button:

![cod](https://user-images.githubusercontent.com/19143190/88845880-cf44d500-d1b2-11ea-8534-67a833526384.jpg)

9. You will be redirected back to the Home screen. 

10. Note here that even that you actually didn't set up WooCommerce payments, the `Set up WooCommerce payments` task is marked as completed which is confusing:

![done](https://user-images.githubusercontent.com/19143190/88846019-04512780-d1b3-11ea-9d44-41e9526e66b8.jpg)

**Expected behavior**

I expected the `Set up WooCommerce payments` task not be marked as completed if I go through the process of setting up any other payment method via `Set up additional payment providers` Inbox card.

Perhaps the `Set up WooCommerce payments` task should have a `Dismiss` option in case the user decides not to set it up right away but still wants to be done with the Task List. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.5
* Browser: Chrome
* Version: 84.0.4147.89 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by timmyc** [comment]
Great catch @juliaamosova - added to the milestone for 1.4

**Comment by octaedro** [comment]
It looks like this issue was solved with the [PR 4917](https://github.com/woocommerce/woocommerce-admin/pull/4917).
If it's ok with you, I will close this issue.

**Comment by becdetat** [comment]
I was testing this with an unrelated but similar ticket yesterday and noticed that this isn't happening. +1 to closing.

**Comment by jeffstieler** [comment]
I was also unable to reproduce this with the current `main` branch - closing!
