### ISSUE TITLE
[WC 4.4 beta1] Task List: `Set up tax` task needs to be completed again after `Purchase & install extensions` task is completed. 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4886]
**Describe the bug**

Upon finishing OBW and the `Set up tax` task is completed, the `Set up tax` task needs to be completed again after the `Purchase & install extensions` task is done.

**To Reproduce**

1. Start OBW.
2. Enter the US store address on the `Store details` section. 
2. On the `Product Types` page select one of the paid products such as `Subscriptions` (so that you could purchase them after OBW via task list).
3. On the `Business Details` page select checkbox next to `Install recommended free business features` to install all the needed plugins. 
4. Complete OBW. 
5. On the task list, select the `Set up tax` task. 
6. You should see the `Good news!` pop-up letting you know that you can set up taxes using Jetpack + WC Services:

![Screen Shot 2020-07-29 at 4 04 38 PM](https://user-images.githubusercontent.com/19143190/88847999-d9b49e00-d1b5-11ea-8a42-71dca8026817.png)

7. Click on the `Yes please` button to proceed. 
8. Note that `Set up tax` task is marked as done (I have a few more tasks completed here as well):

![tax](https://user-images.githubusercontent.com/19143190/88848209-20a29380-d1b6-11ea-99a1-45da2e636870.jpg)

9. Complete the rest of the tasks **except for the `Purchase & install extensions` task**:

![install](https://user-images.githubusercontent.com/19143190/88848469-8727b180-d1b6-11ea-944f-3eebdf3149db.jpg)

10. Click on to proceed with the `Purchase & install extensions` task. Complete it. 
11. Upon being redirected back to the Home screen, note that the `Purchase & install extensions` task is completed but the `Set up tax` task is marked as not completed even though we completed it in step 8:

![tax2](https://user-images.githubusercontent.com/19143190/88848743-e259a400-d1b6-11ea-852c-203d0a97c43e.jpg)

**Expected behavior**

I expected the task list to go away as I am redirected back to the Home screen after completing the `Purchase & install extensions` task. I didn't expect to complete the `Set up tax` task again. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.5
* Browser: Chrome
* Version: 84.0.4147.89 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by becdetat** [comment]
@juliaamosova I can reproduce this on WC 4.4.0-beta.1 but not on 4.5.2 stable or using the main branch of WooCommerce Admin. So I believe that this has been fixed. I'll close this for now. Thanks!
