### ISSUE TITLE
Remove chevrons from Task List items

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#4896]
As per [this update](https://github.com/woocommerce/woocommerce-admin/pull/4790) of the Store Management card, let's remove the chevrons from the Task List links as well.

<img width="528" alt="remove-chevrons" src="https://user-images.githubusercontent.com/22080/92421777-1e294700-f12f-11ea-9b7e-c6b86b650087.png">

**Comment by timmyc** [comment]
Reserving this one for Adrian.
