### ISSUE TITLE
Inconsistent card styling in OBW

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#4898]
This may be related to https://github.com/woocommerce/woocommerce-admin/issues/4002 so feel free to close if so.

I noticed that the styling of the card in the Store Details step during the OBW matches the styling of the core component:

![details](https://cldup.com/Fd7RldEsf0-3000x3000.png)

[Here's](https://wordpress.github.io/gutenberg/?path=/story/components-card--default) the core component for reference.

Note the border and lack of drop shadow.

The cards in all other steps do not match the Store Details step. Here's the industry step for an example:

![industry](https://cldup.com/h-Sg1DhMp7-3000x3000.png)

Here there is no border, and a shadow appears. Ideally the cards in all steps should match the Store Details step ito design.

**Comment by joshuatf** [comment]
Estimate: 1

**Comment by joshuatf** [comment]
This does appear to be related to https://github.com/woocommerce/woocommerce-admin/issues/4002; I'll close this issue so we can follow up there.
