### ISSUE TITLE
TableCard - Getting Undefined onQueryChange(...)

### ISSUE THREAD

**Issue by surajv** [woocommerce/woocommerce-admin#4916]
Hello,

I am trying to use the `TableCard` component but the console is throwing errors even though we are not passing any `onQueryChange`
https://i.mythemeshop.com/ZU0r9X
https://i.mythemeshop.com/FxjU7K

**Code:**
```
<TableCard
    className="rank-math-table"
    title={ __( 'Content', 'rank-math' ) }
    headers={ headers }
    downloadable={ true }
    rows={ processRows( rows ) }
    query={ query }
    rowsPerPage={ 10 }
    totalRows={ summary.total }
    summary={ tableSummary }
    showPageArrowsLabel={ false }
    onPageChange={ ( newPage ) => {
        history.push( '/analytics/' + newPage )
    } }
/>
```

Does anyone one why this is happening?

Thank you for your help.

**Comment by timmyc** [comment]
Greetings!

So that particular component does not require the `onQueryChange` prop to be supplied when using, it [sets the default](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/table/index.js#L340) to be a `noop`/empty function, so you shouldn't be seeing this error.

Do you have your entire code in a place where I could download and test it out?

It _should_ go away if you added a prop to your component call above like: `onQueryChange={ ()=>{} },` - but again that shouldn't be necessary given the default prop already does that on your behalf. But you could give that a try and see if it fixes things up.

**Comment by surajv** [comment]
Hello Timmy,

Thank you for the quick reply, unfortunately I can't share the full code but here is the file where we are using the component

https://gist.github.com/surajv/9018fd4a832528aed00e7c2da58ec698

Thank you for your time.

**Comment by timmyc** [comment]
@surajv no worries, totally understand about not being able to share the code. Can you try the solution I proposed above and see if that fixes the problem?

**Comment by surajv** [comment]
Actually we tried that already, and unfortunately, it is throwing the same error? Is there any way to debug this?

**Comment by timmyc** [comment]
Without having access to the code, it is really difficult for me to pinpoint why this is happening. Guessing you already have `define( 'SCRIPT_DEBUG', true );` in your wp-config file, with that if you install the plugin version of WooCommerce Admin from the .org repository ( or clone and `npm install && composer install && npm start` from the `main` branch here ), you will have unminified versions of the TableCard code running that might provide further clues.

We also have a [code example that uses the TableCard](https://github.com/woocommerce/woocommerce-admin/blob/0b68c1d7c0c5025789071022efa129126da1ded5/docs/examples/extensions/dashboard-section/js/upcoming-events.js#L24) in the repository here that can be [installed as an example extension locally](https://github.com/woocommerce/woocommerce-admin/tree/0b68c1d7c0c5025789071022efa129126da1ded5/docs/examples/extensions) to give some starts on how to use components like TableCard.

**Comment by loranallensmith** [comment]
Hi @surajv!  👋  My name is Allen, and I'm a developer advocate for WooCommerce.  I'm going to take a look at a few things and see if I can help troubleshoot this with you!  I'll let you know what I discover, but feel free to ping me here or in our Community Slack if you have questions or new any updates you'd like to share.

**Comment by surajv** [comment]
Hi Timmy & Allen,

Here are the findings:
Enabled `define( 'SCRIPT_DEBUG', true );` and we are using `npm` to include this component. As you can see the table is rendering perfectly https://i.mythemeshop.com/zEYnLE

This is the error https://i.mythemeshop.com/3XaEhk, line: https://github.com/woocommerce/woocommerce-admin/blob/0b68c1d7c0c5025789071022efa129126da1ded5/packages/components/src/table/index.js#L130

It looks like `onQueryChange` is not falling back to default noop function that is why console says `Uncaught TypeError: Cannot read property 'apply' of undefined`
https://github.com/woocommerce/woocommerce-admin/blob/0b68c1d7c0c5025789071022efa129126da1ded5/packages/components/src/table/index.js#L336

Thank you for your help.

**Comment by loranallensmith** [comment]
Hi @surajv!  I did a bit more testing on this last night and was able to reproduce the error you're seeing on my end.  I'm just using a really simple TableCard component that I put together, so my setup is probably different from yours.  Here's what I think is happening:

The TableCard component expects [`onQueryChange`](https://github.com/woocommerce/woocommerce-admin/tree/579e9d3b1635af5d608b8853f3ddc3f39d3b13d8/packages/components/src/table#props) to be a function that returns a callback function.  As it is right now, it's getting defined as the callback function itself (the [`noop`](https://lodash.com/docs/4.17.15#noop) function in lodash).  When the TableCard component tries to call `apply()`, it's calling it on the noop function when it should be calling it on a function that returns the noop function.   Does that make sense?

When I nest the noop logic for the `onQueryChange` one layer deeper, there are no errors.

```jsx
return (
    <TableCard title={'Top Rated Products'}
      headers={headers}
      rows={rows}
      rowsPerPage={5}
      totalRows={50}
      onPageChange={ (page) => {
        console.log("PageChange: ", page)
      }}
      onQueryChange={ () => {
        return () => {}
      }}
    />
  );
```

cc @timmyc on here too.  It might be worth updating the value of `onQueryChange` in the TableCard's defaultProps, but I'm not sure what kind of cascading effects that might have, and I haven't had a chance to test it out just yet. :smiley:

**Comment by loranallensmith** [comment]
Hi @surajv!  :wave:  I just wanted to follow up with you here to make sure you saw the Pull Request (#4959) above.  ☝️  I believe this PR should address the error that you're encountering.

Thanks a bunch for that fix @jeffstieler!  :sparkles:

**Comment by surajv** [comment]
Hi Allen,

Really sorry for the late reply. Perfect! The solution which you have provided worked and PR looks good.

Thank you for your help.
