### ISSUE TITLE
[WC 4.4 beta1] Create shipping label notice layout is a bit cramped

### ISSUE THREAD

**Issue by harriswong** [woocommerce/woocommerce-admin#4938]
**Describe the bug**

The message, the `Create shipping label` button and the close icon of the `Create shipping label` notice on the order page feel a bit cramped:

![services](https://user-images.githubusercontent.com/19143190/88853682-197f8380-d1be-11ea-96bd-4ebacf5bdc16.jpg)

**To Reproduce**
I tested using WooCommerce 4.4 beta1 and WordPress 5.5-RC1-48681. 

1. Start OBW.
2. Enter the US address in the `Store details` section during OBW. 
3. On the `Tell us about your business` page, select checkbox next to `Install recommended free business features` so that WC Services could be installed. 
4. Complete OBW.
5. Place an order on the site. 
6. Navigate to the order page and see the notice letting you know that you can create a shipping label with the cramped layout. 

**Expected behavior**
I think more space (padding) between the text, button, and the exit icon will make it for a nicer experience. Alternatively, the `Create shipping label` button can be placed under the message and centered. 

**Screenshots**
N/A

**Desktop (please complete the following information):**

OS: macOS Catalina 10.15.5
Browser: Chrome 84.0.4147.89 (Official Build) (64-bit)

**Additional context**
This was created in WooCommerce Service repo, please refer to the  comments in here: https://github.com/Automattic/woocommerce-services/issues/2106#issuecomment-669214992

**Comment by timmyc** [comment]
The metabox arrow part of this was fixed in #4914
