### ISSUE TITLE
[4.4 RC1] Benefits Screen Redirects to Jetpack When No Selected

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#4939]
**Describe the bug**
When on the benefits page in `main` or WooCommerce 4.4 RC1, if you select "No Thanks" to setup WCS and Jetpack - when Jetpack is installed + active, one is still redirected into the Jetpack Connection flow.

Worth noting the benefits page works as expected when Jetpack is not active, so when clicking no thanks then, you are sent to the homescreen as expected. As such this feels a bit like an edge case to me, but still would be nice to fix prior to 1.4/4.4 final.

**To Reproduce**

1. Create a new JN site with Jetpack active ( not connected ), and running RC1 of 4.4
2. Proceed through the onboarding profiler to the benefits page
3. Click "No Thanks" when prompted to setup/connect for Jetpack and WCS
4. Note you are redirected into the Jetpack connection flow still. 

**Expected behavior**
To be redirected to the WooCommerce homescreen.

**Comment by austress99** [comment]
Yes thank you for the opportunity and wellness program activity to help us with our new projects
