### ISSUE TITLE
Policy violation: contact with external server without consent

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce-admin#4955]
**Describe the bug**

A default install of WooCommerce (latest released version, 4.3.1), bundling WooCommerce admin, results in a scheduled weekly action `woocommerce_update_marketplace_suggestions`. This calls `WC_Marketplace_Updater::update_marketplace_suggestions()`, which fetches https://woocommerce.com/wp-json/wccom/marketplace-suggestions/1.0/suggestions.json .

This is contrary to the wordpress.org repository requirement https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#7-plugins-may-not-track-users-without-their-consent : "In the interest of protecting user privacy, plugins may not contact external servers without explicit and authorized consent. This is commonly done via an ‘opt in’ method, requiring registration with a service or a checkbox within the plugin settings. Documentation on how any user data is collected, and used, should be included in the plugin’s readme, preferably with a clearly stated privacy policy." WooCommerce Admin currently contacts the external server automatically without requesting consent.

**Comment by rrennick** [comment]
@DavidAnderson684 The policy prohibits sending data without consent. If you check the [code](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/marketplace-suggestions/class-wc-marketplace-updater.php), the marketplace suggestions call only includes a timestamp. You can contact the WordPress.org plugins team for clarification.

**Comment by timmyc** [comment]
@DavidAnderson684 thanks for taking the time to log your concern around this. The marketplace suggestions feature was shipped in version 3.6 of WooCommerce, and we were in close contact with the .org Plugin review team during development to ensure the feature did not violate any of the .org guidelines.

The feature can be turned off via the checkbox seen below ( WooCommerce > Settings > Advanced > WooCommerce.com ):

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/22080/91107046-2bbbd880-e629-11ea-8758-7ad1e4c15f3a.png">

Additionally, [there is a filter](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/marketplace-suggestions/class-wc-marketplace-suggestions.php#L187) that can be used to always turn the feature off even without using the checkbox in settings.

The code that powers this particular feature is in fact in the core Woo repository, so based upon that I'm going to close this out.
