### ISSUE TITLE
No data from last year (compare)

### ISSUE THREAD

**Issue by stm-hamburg** [woocommerce/woocommerce-admin#4957]
Hi,

i don´t get data from last year, there are definitely sales in this time.

How can i fix it?

Best,
Jan
![wcd](https://user-images.githubusercontent.com/69461708/89777733-8541e480-db0c-11ea-8b08-8f054fee7d0b.JPG)

**Comment by jeffstieler** [comment]
Hello @stm-hamburg, sorry for the delay in response.

If you haven't run a full "import" of historical data on your store, try that first. Head over to Analytics > Settings and scroll down to the "Import Historical Data" section. From there you can process all orders on your store for analytics.

See [Importing Historical Data](https://docs.woocommerce.com/document/woocommerce-analytics/#section-15) in our documentation for more info.
