### ISSUE TITLE
Add new event prop to wcadmin_tasklist_completed

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4973]
With the latest changes in the task list / home screen, if a user wants to dismiss the task list he needs to click on "Hide this", which triggers `wcadmin_tasklist_completed`. The interaction and tracking are working fine, however it doesn't tell us much about if they're closing the task because they don't find it useful, if they already completed all the tasks, etc.

Adding an even prop that counts the number of completed tasks is enough to identify the store's state when the user closes the list.

Event prop: tasks_completed: [number of tasks]

**Comment by joshuatf** [comment]
Estimate: 1
