### ISSUE TITLE
Non stop ALTER TABLE queries with WooCommerce 4.3.x (was ok with 4.2.0)

### ISSUE THREAD

**Issue by editocom** [woocommerce/woocommerce-admin#4981]
Hello,

Before the bug appearing, I was using MySQL 5.6 and Wordpress 5.4.2 with WooCommerce 4.2.2 and PHP 7.4.

- On July 9th, I updated WooCommerce from 4.2.2 to 4.3.0 
- On July 22th, I updated WooCommerce from 4.3.0 to 4.3.1

With WooCommerce 4.3.x I started to receive some alerts telling me that more than 50% of my SQL server's CPU was used. 

When I check the log of the database, I can see that multiple ALTER TABLE queries are being done all during the day, as follows:

<img width="1689" alt="Screenshot at Aug 05 16-06-16" src="https://user-images.githubusercontent.com/50528632/89429511-ec8f1b80-d73d-11ea-8eb8-2179dee23379.png">

The frontend and Woocommerce continue to work with no apparent issues. The database CPU charge is however a big issue.

When I rollback to WooCommerce 4.2.2 there is no database charge anymore and I don't see any ALTER TABLE queries anymore in the database log.

I thought that I needed to migrate to MySQL 5.7 to get rid off this ALTER TABLE queries issue. So I did the migration.

And I updated to WooCommerce 4.3.1 again and the same issue occurs again: Heavy database charge caused by non stop ALTER TABLE queries as on the screenshot above.

So I rollbacked again to WooCommerce 4.2.2 and the issue disappeared.

I don't understand what is happening with WooCommerce 4.3.x.

At this time I am sticked to WooCommerce 4.2.2 until this ALTER TABLE queries issue is fixed. 

Do you have an idea?

**Comment by timmyc** [comment]
@editocom I really appreciate you reaching out with this issue. I see you have an older version of the WooCommerce Admin plugin installed on your site - 1.2.4. Would it be possible for you to disable that plugin and see if things clear up, or update to the latest version that is available on the plugin repository which is 1.3.2? I feel that might really help things out. 

I would try the disabling of the WooCommerce Admin package first, and then attempt the update to 4.3.x of WooCommerce again ( preferably in a staging environment ).

**Comment by editocom** [comment]
Hello
When I upgrade to Woocommerce Admin 1.3.2, I have exactly the same issue with non stop ALTER TABLE queries all the time. It stops when I deactivate the plugin.

**Comment by timmyc** [comment]
So just wanting to confirm that deactivating WooCommerce Admin fixes the issue?

**Comment by editocom** [comment]
Yes, but even when WooCommerce Admin is deactivated, if I only upgrade Woocommerce to 4.3.1, the same issue happens

**Comment by editocom** [comment]
Everything is ok with:
- Woocommerce 4.2.2 and no Woocommerce Admin installed or Woocommerce Admin **de**activated (whatever version)

The issue happens either:
- with Woocommerce 4.2.2 and Woocommerce Admin 1.3.2 activated
- or Woocommerce 4.3.1 and Woocommerce Admin 1.3.2 **de**activated

I did not try yet with Woocommerce 4.3.1 and Woocommerce Admin 1.3.2 activated together

**Comment by timmyc** [comment]
Gotcha, that is quite interesting indeed. Would you be able to try one more thing with 4.3.1 - or 4.3.2 installed? Delete the following option from your install: `woocommerce_admin_version`? If you have command line access `wp option delete woocommerce_admin_version` is my preferred way to do this.

**Comment by editocom** [comment]
Yes, I have command line access. 
<img width="481" alt="Screenshot at Aug 13 17-01-07" src="https://user-images.githubusercontent.com/50528632/90151053-9d249d00-dd86-11ea-94ca-b2e2541820fb.png">

**Comment by editocom** [comment]
I just updated to Woocommerce 4.3.2 and Query Monitor reports the following database error: 
<img width="1025" alt="Screenshot at Aug 13 17-07-18" src="https://user-images.githubusercontent.com/50528632/90151994-9cd8d180-dd87-11ea-9b21-31508c775ee6.png">

**Comment by editocom** [comment]
I am deploying this server configuration on all the servers behing the load balancer and I will activate Woocommerce Admin 1.3.2 after that. I will let you know what happens

**Comment by editocom** [comment]
With Woocommerce 4.3.2 deployed and Woocommerce Admin 1.3.2 deactivated, the issue happens again:

<img width="1344" alt="Screenshot at Aug 13 17-26-24" src="https://user-images.githubusercontent.com/50528632/90154390-5a64c400-dd8a-11ea-9e25-f63ea31d5fd6.png">

**Comment by editocom** [comment]
This doesn't change anything if I activate Woocommerce Admin 1.3.2 or not

**Comment by editocom** [comment]
I am entering again the following once all the servers are deployed just to see: 
`wp option delete woocommerce_admin_version `

**Comment by editocom** [comment]
It's OK now, no more ALTER TABLE queries!

**Comment by editocom** [comment]
> Gotcha, that is quite interesting indeed. Would you be able to try one more thing with 4.3.1 - or 4.3.2 installed? Delete the following option from your install: `woocommerce_admin_version`? If you have command line access `wp option delete woocommerce_admin_version` is my preferred way to do this.

Thank you Timmy, this solved the issue (y)

**Comment by timmyc** [comment]
@editocom awesome!!! really happy that did the trick, and **thank you** for being so responsive and trying out these troubleshooting steps with me. I'm going to close out this issue, but please feel free to reopen if we can help out further.
