### ISSUE TITLE
Improve visibility of components package readme

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-admin#5005]
**Is your feature request related to a problem? Please describe.**
As a user of `@woocommerce/components` npm package, I would like to easily find out what's new & changed in each version. This will help me keep my project updated (note - I don't have a particular project in mind, other than [WooCommerce Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block)).

**Describe the solution you'd like**
Add a link to the changelog in a few places:

- [`/components` folder readme.](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/README.md) (yes, this is right next to the changelog file but might still raise awareness!!)
- [NPM package page](https://www.npmjs.com/package/@woocommerce/components) - I think would be covered by readme change?
- [Auto-generated interactive docs site](https://woocommerce.github.io/woocommerce-admin) - maybe just add some links back to the repo (I didn't find any back links), so easy to get "stuck" on the doc site.

**Should this be prioritized? Why?**
Not a high priority, nice-to-have :)

**Additional context**
I hit this when updating Woo Blocks to latest, but it looks like we don't need to consume as a package and we're about to [change to using external (WP global)](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2419). Still thought I'd report to help improve adoption/love for woo components :)

FYI @loranallensmith - dev docs related.

**Comment by adrianduffell** [comment]
These suggestions sound reasonable to me and appear to be low effort. Re-opening to tackle in a cooldown period.
