### ISSUE TITLE
woocommerce/components 5.0.0 "Plugin" component is tightly coupled to WooCommerce Admin code base

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-admin#5006]
**Describe the bug**
`@woocommerce/components` 5.0.0 doesn't work stand-alone, because the `Plugin` component has some dependencies in wc-admin. Here's the build errors I see:

```
ERROR in ./node_modules/@woocommerce/components/build-module/plugins/index.js
    Module not found: Error: Can't resolve '@woocommerce/data' in '/Users/haszari/_automattic/merch-repos/woocommerce-blocks/node_modules/@woocommerce/components/build-module/plugins'
    
ERROR in ./node_modules/@woocommerce/components/build-module/plugins/index.js
    Module not found: Error: Can't resolve 'lib/notices' in '/Users/haszari/_automattic/merch-repos/woocommerce-blocks/node_modules/@woocommerce/components/build-module/plugins'
```

I took a peek and I see there is a wizzy new `Plugins` component. Looking at the docs/use case (wrangling/installing WP plugins), I'm not surprised this is tightly coupled to Woo. So maybe the easiest fix is to move this component out of the package.

https://github.com/woocommerce/woocommerce-admin/blob/fdeade1887cfe9daa91b6657a8a1ac5aeb084d8e/packages/components/src/plugins/index.js#L9-L15

**To Reproduce**
I haven't reproduced this outside WooCommerce Blocks repo. Here's suggested minimal reproduce steps, but I haven't tried this!

- Bootstrap an [empty react app](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app) - e.g. `npx create-react-app woo-components-standalone-test`.
- Add & install `@woocommerce/components` dependency (`@5.0.0`).
- Import and use a Woo component.
- Build, should see build errors 🤞 

**Expected behavior**
`@woocommerce/components` can be used standalone, independent of WordPress or Woo.

### auto build test?
Long term it would be great if this type of issue could be caught by tooling. E.g. an automated travis build of a demo project (similar to reproduce scenario), or a magic dependency linter, or something even cooler.

- https://www.npmjs.com/package/dependency-check ?

**Comment by haszari** [comment]
Note - this was discovered when attempting to update WooCommerce Blocks, but we're planning on [consuming components lib via global now](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2419), so this isn't a blocker for us.

**Comment by psealock** [comment]
>Module not found: Error: Can't resolve 'lib/notices'

This has been fixed on `main` in https://github.com/woocommerce/woocommerce-admin/pull/4972

>Module not found: Error: Can't resolve '@woocommerce/data'

This is a dependency issue. Looks like an entry for `@woocommerce/data` is missing from the component's package.json
