### ISSUE TITLE
[GlobalStep-WooCommerce Admin 1.5.0 RC1][Mac] "Next", "Previous" and "Let's Go" options are misaligned.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#5011]
## Description:
"Next", "Previous" and "Let's Go" options are misaligned i.e., shifted towards the downside.

## Environment:
macOS Mojave:10.14.6 (18G103)
Safari: Version 13.1.1 (14609.2.9.1.3)

## Steps To Reproduce:
1. Create a Jurassic Ninja test site
1. Install and Activate the WooCommerce Plugin.
1. Upload, Install, and Activate WooCommerce Admin Plugin.
1. Click on "Run the Setup Wizard"
1. Complete the onBoarding process.
1. Note when you reach WooCommerce Dashboard, Display Modal will appear.
1. Observe that "Next", "Previous" and "Let's Go" options on Display modal fails to appear center aligned

## Actual Result:
"Next", "Previous" and "Let's Go" options are misaligned.

## Expected Result:
"Next", "Previous" and "Let's Go" options on Display modal should be center-aligned

## Artifact:
![#1_B](https://user-images.githubusercontent.com/41110392/90653287-9e5d3a80-e25c-11ea-85e3-21813d8e586d.png)
![#1_C](https://user-images.githubusercontent.com/41110392/90653291-9ef5d100-e25c-11ea-87d8-447e2f45f37d.png)
![#1_A](https://user-images.githubusercontent.com/41110392/90653280-9d2c0d80-e25c-11ea-9132-2b3f999d6baf.png)

**Comment by becdetat** [comment]
This appears to only be an issue on Safari - it doesn't happen in Edge, although I couldn't test in IE11
