### ISSUE TITLE
REST API: Add null checks to PerformanceIndicators Controller

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5020]
**Describe the bug**
This issue was originally reported in the [forums here](https://wordpress.org/support/topic/4-4-1-broke-my-site/), and appears to only cause an issue when the JWT Auth plugin is installed on a site. But looks like we could add some null checks to this logic to ensure that `$endpoint['slug']` and `$endpoint['path']` are defined before attempting to call endpoints for stats.

Exception occurs [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Reports/PerformanceIndicators/Controller.php#L149)

**Comment by timmyc** [comment]
I'm thinking this is still a valid bug stalebot

**Comment by joelclimbsthings** [comment]
Closing in preparation for the merge.
