### ISSUE TITLE
Support importing sample product data (starter content) in onboarding

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-admin#5022]
**Is your feature request related to a problem? Please describe.**
In Storefront, sample products can be easily imported during onboarding. This is helpful for setting up demo sites, evaluating the Woo platform, and of course for dev and testing. 

In other WP themes and plugins, and on other platforms, starter content like this can help get sites up and running quickly, and make it easier to get a site up that "looks like the demo".

This could be a useful part of WooCommerce core - I don't think this problem is unique to Storefront. "Products" as a data type are owned by woo core, so it makes sense that demo/sample products would be available as part of core (rather than a specific theme).

Note - [there is already a sample dataset, and documentation on how to use it](https://docs.woocommerce.com/document/importing-woocommerce-sample-data/). This request is about making this even easier to use - no need to manually download/upload a csv file or read docs.

**Describe the solution you'd like**
Add an "import sample products" one-click option to the `Products` section of the [store setup checklist](https://docs.woocommerce.com/document/woocommerce-setup-wizard/#section-12).

**Describe alternatives you've considered**
Lots of ways we could implement this. I'm not married to any specific approach; the goal is that a new merchant with WooCommerce Core can easily get a fully-functioning store up and running quickly.

**Should this be prioritized? Why?**
Not an urgent priority. When this is implemented, we could remove the current (hidden) feature in Storefront.

**Comment by pmcpinto** [comment]
We have that import option in the Customize Appearance task. However, I think it's worth considering moving this option to the Add Products task or have it in both tasks.

cc @jameskoster @joshuatf for additional feedback

**Comment by jameskoster** [comment]
We added sample data import as an option to the customisation task because without some products in the store it is difficult to perform visual customisation. 

When a user is adding their own products, what value does sample data bring? What issue would we actually be addressing by adding this? 

There seems to be a lot of overlap with the idea we've discussed (p90Yrv-1Lc-p2 comment-4015) of allowing folks to choose a "product template" when adding their products manually.

**Comment by haszari** [comment]
> When a user is adding their own products, what value does sample data bring? What issue would we actually be addressing by adding this?

Good question – my experience of this feature is for setting up demo or dev sites, I don't know how useful it would be for other purposes or real stores.

> There seems to be a lot of overlap with the idea we've discussed (p90Yrv-1Lc-p2 comment-4015) of allowing folks to choose a "product template" when adding their products manually.

Adding or importing "template" products is a subtle shift on the idea, and would indeed work well for the dev/demo use case AND be useful for merchants setting up a new store. I like that idea 😄 

Note - now that I know the sample import is available in `Customization` task, I'm happy for this bug to be closed. 

Also I noticed there's a [doc page related to importing sample data](https://docs.woocommerce.com/document/importing-woocommerce-sample-data/) - this could link to the [`Personalize your store`](https://docs.woocommerce.com/document/woocommerce-setup-wizard/#section-13) doc as an easier way to import sample data. I'll log a request for that on docs.

**Comment by jameskoster** [comment]
> my experience of this feature is for setting up demo or dev sites, I don't know how useful it would be for other purposes or real stores.

The primary objective of the task list is to help less technically savvy users get set up and ready to sell as quickly as possible. So considering that this feels like a more developer-oriented feature, I would lean towards leaving it out of the "add my products" task for now.

**Comment by pmcpinto** [comment]
Thanks y'all for your feedback. I'll close this one and open one specifically about the product templates
