### ISSUE TITLE
Find alternatives to resolution invalidation strategy re: `clearTaskStatusCache()`.

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#5031]
**Is your feature request related to a problem? Please describe.**

https://github.com/woocommerce/woocommerce-admin/pull/4998 introduced a data store for onboarding status data.

Some of that status data is derived from WooCommerce option values, which parts of the onboarding UI facilitate changing. When those `updateOptions()` calls are made, https://github.com/woocommerce/woocommerce-admin/pull/4998 introduced a cache busting call `clearTaskStatusCache()` that just invalidates the resolution of the onboarding status data (causing a new request).

This will likely cause jitters as data is updated on slower hosts.

**Describe the solution you'd like**

We should look into alternate approaches, perhaps like having multiple reducers hooked up to "update options" actions so that multiple resolutions (e.g. network requests) aren't needed to keep state derived from options in sync.

**Comment by joelclimbsthings** [comment]
Closing in preparation for the merge, as it's 1.5 years old.
