### ISSUE TITLE
Issue with filter by Customer Type in Order report

### ISSUE THREAD

**Issue by rwaynick** [woocommerce/woocommerce-admin#5033]
**Describe the bug**
When filtering the Order report by New vs Returning customers the data doesn't appear to change. 

**To Reproduce**

1. Have New and Returning customer orders on your site.
2. Go to WP-Admin > Analytics > Orders.
2. Click on Advanced Filters.
3. Choose Customer is New filter and notice sales data at top.
4. Choose Customer is Returning filter and notice sales data is unchanged.
5. Sales data at bottom appears to change but Totals at bottom still show all and aren't respective of specific filter.

**Expected behavior**
The filter should only show sales data for New customers when that filter is selected and data for Returning customers when that filter is selected.

**Screenshots**
![rw-at blog_wp-admin_admin php_page=wc-admin filter=advanced path=%2Fanalytics%2Forders customer_type=new](https://user-images.githubusercontent.com/10882502/91088598-4b9ace80-e620-11ea-9b26-32c53404c047.png)
![rw-at blog_wp-admin_admin php_page=wc-admin filter=advanced path=%2Fanalytics%2Forders](https://user-images.githubusercontent.com/10882502/91088602-4d649200-e620-11ea-890f-9b8336e7877c.png)

**Desktop (please complete the following information):**

macOS 10.15.6
Chrome 84.0.4147.135

**Additional context**
#customer-report

3253694-zd-woothemes

**Comment by jeffstieler** [comment]
Confirmed this as a bug. Looks like the order stats endpoint isn't using the `customer_type` parameter?

**Comment by guicmazeredo** [comment]
Another case in 3348698-zd

**Comment by DustinHartzler** [comment]
Came to report for user in 3479036-zd too.

**Comment by rwaynick** [comment]
I tested and can't reproduce anymore on the latest version of WC, 4.9.2. I think we can close this out.
