### ISSUE TITLE
Button: Disabled state not respected

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5046]
**Describe the bug**

Business logic sometimes places a `disabled` attribute to buttons. Visually, nothing happens so a button appears to still be enabled.

**To Reproduce**

1. Choose any button in wc-admin.
2. In the inspector, add the `disabled` attribute.
3. See the appearance unchanged, but the button isn't clickable.

**Expected behavior**

The button should be shaded or greyed out like it is on Core WP.

**Comment by becdetat** [comment]
This seems to be related to https://github.com/woocommerce/woocommerce-admin/issues/5052, the `:hover` state overrides the `disabled` attribute.
