### ISSUE TITLE
Infinite ALTER TABLE statements, backups breaking

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce-admin#5058]
**Describe the bug**

I have a site that I updated from WooCommerce 4.1.1 to 4.4.1. (Actually I have more than one, but only this one manifested the problem).

Immediately after the update (though I didn't investigate), backups began to fail (every time) due to this error:

`mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `wp_wc_category_lookup` at row: 0`

Googling indicated that this meant that something was altering the table in between the transaction lock (for the backup) being gained, and the actual dump of that table. And indeed, adding further logging showed that WooCommerce was running the following queries on every page load:

```
ALTER TABLE wp_wc_category_lookup CHANGE COLUMN `category_id` category_id BIGINT UNSIGNED NOT NULL
ALTER TABLE wp_wc_category_lookup CHANGE COLUMN `category_tree_id` category_tree_id BIGINT UNSIGNED NOT NULL
```

So, that pointed to the WooCommerce update routines. (N.B. The table had the desired definition, so the `ALTER TABLE` was a no-op).

With some logging we discovered the root cause:

1) In the database, the value of `woocommerce_admin_version` was `1.3.0` (rather than the `1.4.0` that goes with WooCommerce 4.4.1), which results in WC running the update routines.

2) But, there was a "complete" action in the action scheduler table, indicating that the action `woocommerce_run_update_callback` with argument `array('wc_admin_update_140_db_version')` had run successfully.

3) The code in WooCommerce admin will not update the database version number if 2) is the case.

Result: when loaded, WC always runs the update routines and hence the `ALTER TABLE` statements (breaking ability to backup and hurting performance), but never actually updates the database version number.

I'd say the root logic error there is that WC-Admin is using one check (does the version number in the database match our current version?) to decide whether to run the updates, but a different check (is there a completed action in the action scheduler table?) to decide whether to actually update the database version number.

I can only guess at caused the situation whereby the database version was not updated, but whereby the action was registered as having successfully run. I note that there are lots of "update DB version" methods in `includes/wc-admin-update-functions.php` for each successive version, so I suspect there was a concurrency issue: the `UPDATE` for `1.3.0` was the last SQL request to hit the DB, even after the 1.4.0 updates had been run, so `1.3.0` was the value that stuck. So presumably this can only be reproduced by updating between multiple versions when the DB server or PHP engine is experiencing load which results in concurrent/out-of-order updates.

**Comment by DavidAnderson684** [comment]
P.S. We resolved the issue by deleting the relevant "completed" action scheduler action. WC then scheduled a new action which, when it ran, successfully updated the DB version number.

**Comment by becdetat** [comment]
Thanks for reporting this @DavidAnderson684

**Comment by samueljseay** [comment]
I'm thinking we should close this for now, if we get any follow up's of other users facing this, then we can reopen.

**Comment by DavidAnderson684** [comment]
@samueljseay As someone who follows the Github issue tracker, I have seen multiple reports of problems resulting from the root bug that caused this when upgrading more than one WooCommerce release version at once.

**Comment by samueljseay** [comment]
@DavidAnderson684 apologies I wasn't aware of that. I'll reopen this.
