### ISSUE TITLE
Incorrect use of WP_Filesystem API, resulting in fatal errors

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce-admin#5062]
**Describe the bug**

Here - https://github.com/woocommerce/woocommerce-admin/blob/81685688fdfab3e501f44ff0afd6e11beff707a0/src/Loader.php#L576 - `WP_Filesystem()` is called without checking the result, and then the code proceeds to call other WP_Filesystem API methods as if it had succeeded. This is incorrect. If the user has set up WP_Filesystem to work via a remote access method (e.g. FTP, SFTP) and setup fails, then this will result in fatal errors. (See https://codex.wordpress.org/Filesystem_API for an example of proper use).

For example, in the code linked above, immediately afterwards, `WP_Filesystem::is_file()` is called. Since that API call can only return a boolean (true / false, either of which would be a wrong response, since a failure to set up the filesystem link means that the path is neither known to be a file nor not be a file), then the only way for errors to be signalled is to throw an error or exception. Since WooCommerce Admin also doesn't catch those, it crashes.

Examples of users experiencing this problem:
https://wordpress.org/support/topic/ssh-sftp-updater-support-woocommerce/#post-13338117

**Comment by timmyc** [comment]
cc @jeffstieler looks like this might have been introduced as part of the i18n file fix.

**Comment by DavidAnderson684** [comment]
I do maintain a plugin that adds SFTP support, yes, though the issue isn't specific to any particular filesystem access method. The woocommerce-admin code uses the WP_Filesystem API without any provision for needing to input credentials, or for connection setup failing (e.g. network/server error). You can reproduce the issue with WP's built-in FTP method.
