### ISSUE TITLE
Onboarding - Business Details: update Google Ads description

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5063]
The Google Ads extension was updated with new features, so we need to update the Google Ads header and description:

**New Header:** Drive traffic to your store with Google Ads & Marketing by Kliken
**New description:** Get in front of shoppers and drive traffic so you can grow your business with Smart Shopping Campaigns and free listings.

**Comment by pmcpinto** [comment]
@becdetat @timmyc can we include this in 1.5, considering that we're just updating the copy?

**Comment by pmcpinto** [comment]
@becdetat @timmyc can we include this change in 1.5? I need to inform the Partnerships team about this. Thanks!

**Comment by becdetat** [comment]
@pmcpinto I'm including this in 1.5.0-rc.4 which should go to globalstep for testing soon, then 1.5.0 should be released on Monday

**Comment by pmcpinto** [comment]
Thanks!
