### ISSUE TITLE
Store Profiler - Industry: remove Travel & Tourism

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5064]
The % of users completing the Industry step dropped after we added the two new industries. This can be due to the fact that the “Other” option and the “Continue” button are now showing up below the fold in some screens: https://d.pr/i/w7Rqrk

Let's remove "Travel and Tourism", which is the least selected option, so "Other" is visible on most desktop screens

**Comment by pmcpinto** [comment]
cc @timmyc @becdetat

**Comment by becdetat** [comment]
This has been included in 1.5.0-rc.3 which was released yesterday.
