### ISSUE TITLE
updateQueryString updates the page value to wc-admin, instead of custom value

### ISSUE THREAD

**Issue by raghavnarang** [woocommerce/woocommerce-admin#5077]
**Describe the bug**
https://github.com/woocommerce/woocommerce-admin/blob/1c05641d5fd5e2d85f6cbdffb9a403540b52a67c/packages/navigation/src/index.js#L102

If I try to use the updateQueryString(), I am unable to use my own WP-Admin page. It redirects me to 'wc-admin'. As I can see 'wc-admin' is hard set in the getNewPath() method which is used in updateQueryString.

It would be nice if I can set the page option from the query's page parameter.

**Comment by timmyc** [comment]
Indeed I think we should decouple the `page` attribute - perhaps we could make that the default value, but allow it to be over-ridden.
