### ISSUE TITLE
Task List - WCPayment task: include ToS agreement copy

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5078]
It's required to capture ToS agreement before the user starts setting up his WC Payments account. 

The easiest way to make sure that the user agrees is by adding the ToS agreement copy to the WCPayments task

![s0_ce1DtUW-900x900.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/9e49f1e5-461e-407e-9bb3-1c9fe44cc0c0)

By setting up, you are agreeing to the [Terms of Service](https://wordpress.com/tos/).

The other setup entry points are already covered by this ToS agreement copy.

Additional info: paJDYF-OD-p2

**Comment by becdetat** [comment]
@pmcpinto this is done and in 1.5.0-rc.5
