### ISSUE TITLE
Business details step: add copy to 1-click install flow

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5081]
We need to add the following copy in the 1-click install flow, at the end of the page:

By installing Jetpack and WooCommerce Services plugins for free you agree to our [Terms of Service](https://wordpress.com/tos/).

Here's the mockup: https://d.pr/i/7uvSg2

**Comment by pmcpinto** [comment]
@timmyc @becdetat it would be good to have this copy included in 1.5 🙏  Thanks

**Comment by becdetat** [comment]
😳 I didn't see this until now. It will be in 1.5.0-rc.6 tomorrow. Please ping me on slack if there are any other last minute additions so I can do them first thing tomorrow, otherwise they won't make the cut before stable is built on Monday.
