### ISSUE TITLE
Help panel: add a tooltip highlighting the panel

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5082]
**Description:** 
The Help Panel usage has been minimal, as the top-right corner can be a blind spot for users. On the other hand, there's a high % of users clicking in the support links when the open the panel. So we should have some additional investment highlighting the Help panel with a tooltip.

**Acceptance criteria:**
- [ ] Display the tooltip if the user visits a task for the 2nd time (if the task is not complete)
![task-list-help-panel](https://user-images.githubusercontent.com/3380168/94712319-3d3b8300-0341-11eb-91f2-63911a12b839.gif)
- [ ] The user should only see the tooltip once - if we already displayed the tooltip on the `Add Product` task we shouldn't display it again in other tasks, in order to avoid overwhelming users.

**Event tracking:**
View the tooltip:
`wcadmin_help_tooltip_view`
Prop: task - the task where the tooltip was displayed

Click the tooltip:
`wcadmin_help_tooltip_click`
Prop: task - the task where the tooltip was displayed

**Comment by becdetat** [comment]
@pmcpinto do you have any more information for this?

**Comment by pmcpinto** [comment]
> @pmcpinto do you have any more information for this?

The tooltip still needs to be designed, so we'll move it to the next cycle.

**Comment by pmcpinto** [comment]
Issue updated with the AC and design

**Comment by louwie17** [comment]
@pmcpinto is the design in the above gif available in Figma? if so, would you have a link? :)

**Comment by pmcpinto** [comment]
> @pmcpinto is the design in the above gif available in Figma? if so, would you have a link? :)

@elizaan36 can you share the link? I'm not finding it 🙏 

> In the gif it appears that the popup shows up after you click the Import task, a nested task of the add products task. Is this as intended, or should the popup appear after the user enters the add products task again?
*of-course the add products can refer to any of the other uncompleted tasks.

Good question. I think that we should display the tooltip when the user visits the **main screen** of a task for the 2nd time. Elizabeth, what do you think?

**Comment by elizaan36** [comment]
hey @louwie17 and @pmcpinto 
I just shared the Figma with Lourens in Slack. Also wanted to propose a slight tweak to the tooltip design (not a problem if the other design has already been implemented) because that circle on top of the modal started feeling strange. I updated it to a caret that points to the Help panel link. 

![Home - Help tooltip](https://user-images.githubusercontent.com/5121465/101222801-31758100-3650-11eb-983f-561dc9b9da23.png)

> I think that we should display the tooltip when the user visits the main screen of a task for the 2nd time.

Agreed.

**Comment by louwie17** [comment]
This is mostly just for future documentation, but @jeffstieler  and I were chatting about task click vs task view.
Which goes hand in hand with the recorded tracks `tasklist_click` and `task_view`, currently we are increasing the count on `tasklist_click` and also adding this count to the `tasklist_click` event.
Some pros/cons of each:
**Record on task list click:**
**Pro:**
- User consciously decided to visit a task by click in the task list
- User could easily see if the item was completed or not (from the task list)

**Cons:**
- Doesn't record if a user refreshes on a task view
- Doesn't record if a user visits the task by a direct link, or some other way (if added)
- Very much attached to task list (could be pro or con I suppose)

**Record on task view:**
**Pro:**
- We correctly track task visit count, as it also increases when the user refreshes (goes back), or accesses it by direct link
- Would work well if tasks can be accessed from somewhere outside of the task list

**Cons:**
- Can't necessary tell if task visit was a conscious decision or just a random refresh
