### ISSUE TITLE
Inbox Tip: Learn more about Product Settings leads to outdated video on YouTube

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5083]
**Is your feature request related to a problem? Please describe.**

I see that the `Learn more about Product Settings` Inbox tip was added not too long ago: https://github.com/woocommerce/woocommerce-admin/issues/4201:

![tutorial](https://user-images.githubusercontent.com/19143190/92032634-7a0f5c80-ed38-11ea-84b5-9114b26f588b.jpg)

However, the video is from 2017 and outdated - I see that recent comments by users state the same: https://www.youtube.com/watch?v=FEmwJsE8xDY&t=. 

I realize that creating a new video is not a part of your responsibilities directly and likely updating the video is in the works by the appropriate team but I wanted to create an issue so that the video URL could be updated once there is a new one. 

**Describe the solution you'd like**

It will be great to update the URL of the YouTube video that the user is redirected to after clicking on the `Watch Tutorial` button on the `Learn more about Product Settings` Inbox tip card. 

**Describe alternatives you've considered**

N/A

**Should this be prioritized? Why?**

It will be nice to have. 

**Additional context**

N/A.

**Comment by pmcpinto** [comment]
Julia, thanks for your feedback.

The goal with this notification was to evaluate if users find value in having access to tutorials through inbox messages. But I though that most of the content was up to date 😢 

Probably we won't have a new tutorial anytime soon, so maybe we should remove this notification. @elizaan36 @timmyc what do you think?

**Comment by juliaamosova** [comment]
I think it is probably best to remove the link at this point if you see in tracks that people actually use it? All the recent comments under the video on YouTube state that it is outdated. I don't think we are seen in a good light because of that. I watched the video myself and it is indeed pretty old 😬.

**Comment by elizaan36** [comment]
I'd agree, best to remove it for the time being until we have updated tutorials.

**Comment by pmcpinto** [comment]
@timmyc do you think it will be possible to remove it in 4.6?

**Comment by dougaitken** [comment]
Can we remove this as fast as possible? If you need support reviewing all content linked from these section, please reach out to Happiness or liase with @GeoJunkie @tsetend - we want to sure these help tips and such are as relevant and helpful as possible and not causing contact to Happiness

ref 23443177-hc
