### ISSUE TITLE
[WC 4.5 RC3] Home Screen: `Set up shipping`  task is missing a prompt to enable shipping labels creation provided via WC Services

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5088]
**Describe the bug**

After completing onboarding, on the Home Screen, the `Set up shipping`  task is missing a prompt to enable shipping labels creation provided via WooCommerce Services. 

**To Reproduce**

1. Start OBW on the brand new site. 
2. Fill in the `Store Details` section with the US address.  
3. Select `Fashion, apparel, and accessories` in the Industries section.
4. In the `Tell us about your business` section, select checkbox next to `Install recommended free business features` to install all the recommended plugins. 
5. On Home Screen, select `Set up shipping` task. The modal that looks like below will be open (missing the prompt to enable shipping labels creation):

![shipping](https://user-images.githubusercontent.com/19143190/92063532-531d4e80-ed69-11ea-87ad-532f841b7b7e.jpg)

**Expected behavior**

I expect to see the modal pop-up that includes the prompt to connect to WP.com account to enable shipping labels creation since I had WooCommerce Services + jetpack installed already:

![stpre](https://user-images.githubusercontent.com/19143190/92063620-91b30900-ed69-11ea-8bfd-e0641dea7ee1.jpg)

**Screenshots**

See above. 

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.6
- Browser: Chrome
- Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by timmyc** [comment]
From looking at the code, this is working as expected right now - but need to confirm @juliaamosova that you connected to Jetpack during the profile wizard flow?

If so, when a site is Jetpack connected, the prompt to connect to print labels is not shown.

**Comment by juliaamosova** [comment]
>From looking at the code, this is working as expected right now - but need to confirm @juliaamosova that you connected to Jetpack during the profile wizard flow?

>If so, when a site is Jetpack connected, the prompt to connect to print labels is not shown.

@timmyc you are right! And thanks for catching it! I indeed connected the site to Jetpack / WP.com account already right after completing OBW (you are redirected to the flow to connect to WP.com if you select to install free business extensions bundle during OBW). 

I think I am used to seeing the prompt to connect to WP.com when completing setting up the shipping task which is why not seeing the prompt raised a flag for me. Need to get used to that new flow of connecting to Jetpack right after completing OBW. 

This issue can be closed as a non-bug.

**Comment by timmyc** [comment]
Thanks for confirming @juliaamosova - I really appreciate it!
