### ISSUE TITLE
QUERY / REQUEST : Ability to customise the "Date Presets" for non-calendar financial year 

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce-admin#5091]
Hi Woo team,

In the reports you have Date Presets like "Last Quarter" or "Quarter To Date". This assumes that the financial year starts at 1 Jan of a calendar year, but this isn't true for all countries. 

Is there an option to modify what the reports assume to be the start of the financial year (eg a setting for "start of financial year" = x); or would you consider adding this in future? 

<img width="459" alt="dates" src="https://user-images.githubusercontent.com/19706428/92126228-31bb7180-ee00-11ea-8f67-71ec7e52b002.png">

Many thanks, Edith

**Comment by timmyc** [comment]
Hello @EdithAllison thanks for taking the time to open up an issue for this feature. Currently there isn't a way to customize these calendar based presets. You can set a custom default date range to be used when reports are opened via Analytics > Settings, but not to add custom presets like this.

We are going to add this idea to our "icebox" and see if there might be further interest from other users for this feature.
