### ISSUE TITLE
QUERY: Do you have documentation on adding totals / graph lines? 

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce-admin#5092]
Hi Woo team,

I could not find documentation how to add data to the Totals above the graph in reports; and how to add data to the graph itself. Is it possible to add data; and if yes, is there any documentation available online to point me in the right direction? 

<img width="1193" alt="graph" src="https://user-images.githubusercontent.com/19706428/92126946-17ce5e80-ee01-11ea-9f22-ef027f4e48ae.png">

Many thanks, Edith

**Comment by jeffstieler** [comment]
Hello @EdithAllison, thanks for your inquiry.

It _might_ be possible to add a new chart to the Orders Report, depending on how the underlying query might need to be modified. There is unlikely to be enough filters to modify the query without having to parse the entire thing. If you are unable to accomplish your goal, please follow up and let us know your specific use case so we can take that into account!

You can filter the configuration for the report charts here: https://github.com/woocommerce/woocommerce-admin/blob/701de1580689cbdc1fad541f6a82e1640d8dafd8/client/analytics/report/orders/config.js#L22

You can add columns to a report query using the `woocommerce_admin_report_columns` filter: https://github.com/woocommerce/woocommerce-admin/blob/701de1580689cbdc1fad541f6a82e1640d8dafd8/src/API/Reports/DataStore.php#L102-L107
(note you'd be in the `order_stats` context)

Define the same column(s) data type using the `woocommerce_rest_reports_column_types` filter: https://github.com/woocommerce/woocommerce-admin/blob/701de1580689cbdc1fad541f6a82e1640d8dafd8/src/API/Reports/DataStore.php#L535

If you're unable to modify the Order Stats query, you can inject your extra data using the `woocommerce_analytics_orders_stats_select_query` filter here: https://github.com/woocommerce/woocommerce-admin/blob/aecd050aff498d997adea9ec3e00a6bce8bd8a61/src/API/Reports/Categories/Query.php#L47

**Comment by timmyc** [comment]
@EdithAllison I hope what Jeff shared above was helpful for you. I'm going to close out this question for now but please do respond back if we can be of further assistance.
