### ISSUE TITLE
Same as (Error installing woocommerce services - No Error message #3871) on new install

### ISSUE THREAD

**Issue by BroPage** [woocommerce/woocommerce-admin#5093]
Error Installing woocommerce services following Installation guided plan. This is a completely new install as of Monday 08/31/20.

All components where installing correctly until we get to the JetPack and Tax section. Jetpack looks to work correctly then when I continue the install I get the attached message.

**To Reproduce**

1. I am following the finish setup steps on the WooCommerce / Home Page
2. Completed the "Set up WooCommerce Payments" step
3. That is where the Install Jetpack and WooCommerce service dialog is presented
4. When I click on the button to continue the install error occurs.
5. When the retry button is clicked same thing happened.

**Expected behavior**
Normal completion of installation

**Screenshots**
1. Error message 
2. the finish setup steps on the WooCommerce after the error.

**Desktop (please complete the following information):**

* OS Microsoft Windows 10 Pro Version	10.0.18363 Build 18363
* Browser Chrome
* Version Version 84.0.4147.135 (Official Build) (64-bit)

**Additional context**
I am willing to go back to Mondays Initial Install and reinstall WooCommerce from the start but I need specific instructions on how to install with out errors. I do not wish to waste another week.
<img width="261" alt="2020-09-03 13_55_55-Home ‹ WooCommerce ‹ Castleberry Distinctive Jewelry — WooCommerce" src="https://user-images.githubusercontent.com/47037645/92153143-c9659380-edf1-11ea-853b-165617cf697d.png">
<img width="550" alt="WooComm Install error 2020-09-03 13_39_37-2020-09-03 13_36_50-" src="https://user-images.githubusercontent.com/47037645/92153145-c9fe2a00-edf1-11ea-8bf3-24669eccbf53.png">

**Comment by timmyc** [comment]
@BroPage thanks for contacting us with this problem. The error message shown there makes me think that WooCommerce Services might have already been installed on the site, and possibly deleted but the old folder is still present in `wp-content/plugins`. I'm not able to personally recreate this error on a new install with WooCommerce 4.5 myself. So I'm going to close out this issue.
