### ISSUE TITLE
Navigation items in the wc nav should register click handlers

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#5098]
Note: wait on decision for compositional structure in https://github.com/WordPress/gutenberg/pull/25057 before tackling this issue.

WooCommerce Admin should register its own click handlers or components for use in the wc nav project.  Currently, clicking these links navigates to the page using a standard link without using the react router in WCA.

There's a filter for the menu items that can be used to modify the data: `woocommerce_navigation_menu_items`.  It's probably easiest to pass the component used for linking directly to the menu items using the `LinkComponent` prop.

```js
{
  id: 'menu-item',
  title: 'My menu item',
  LinkComponet: NavLink,
}
```

<img width="279" alt="Screen Shot 2020-09-04 at 11 54 09 AM" src="https://user-images.githubusercontent.com/10561050/92260144-22abf080-eee0-11ea-96b9-4110a04cb85f.png">

**Comment by psealock** [comment]
Closing this because we went with a composible approach in Gutenberg.
