### ISSUE TITLE
New inbox notification: Apple Pay

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5099]
**Title:** Apple Pay is now available on Stripe
**Content:** Boost sales by offering a fast, simple, and secure checkout experience with Apple Pay®!
**Segmentation:** Stores located in the US with Stripe installed and activated
**Timing:** When users update WooCommerce to the 4.7 version (Nov 10)
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/apple-pay/?utm_source=inbox
**CTA label:** Get started
**Type:** Marketing/promotion

More context: p7fD6U-3RJ-p2

**Comment by pmcpinto** [comment]
@becdetat @timmyc this is a good notification to be used in the remote system if we enable it in WC 4.6. Otherwise, we need to use the regular system. What do you think?

**Comment by becdetat** [comment]
Hi @pmcpinto, @adrianduffell and I have started on this and we realised part-way through that the title and content are TBD. Do you have any copy for this notification?

Also it can't use the remote system as we don't currently have a way of checking for the country, I'll create a ticket to add that rule into the remote system but it won't affect delivery of this notification.

**Comment by pmcpinto** [comment]
Hey, it was decided to postpone the introduction of this message until the WooCommerce 4.7 release. In the meantime, I'm going to get the final copy of this. I think that the code freeze for 4.7 will happen in the 1st or 2nd week of October.

**Comment by pmcpinto** [comment]
Just a heads up that I already updated the description with the new copy. The goal is to include it in the WC 4.7 release.

**Comment by adrianduffell** [comment]
I have now implemented the new copy in PR #5150 .

**Comment by pmcpinto** [comment]
We'll probably need to change the logic/content of this notification. Check the ongoing discussion here: paqDfi-HW-p2

**Comment by pmcpinto** [comment]
I'm closing this one as it was implemented by the Transact folks
