### ISSUE TITLE
T

### ISSUE THREAD

**Issue by austress99** [woocommerce/woocommerce-admin#5104]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by austress99** [comment]
https://user-images.githubusercontent.com/65765819/92423242-487e0300-f135-11ea-84d0-23e247224837

**Comment by austress99** [comment]
- #[y]() has

**Comment by jeffstieler** [comment]
Hi @austress99, can you provide more details on the issue you might be experiencing? I'm unable to see the image you've posted (permissions error). Thanks!

**Comment by samueljseay** [comment]
@jeffstieler This is a bot, I've seen spam from this in several other issues.
