### ISSUE TITLE
Charts: Improve keyboard accessibility

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-admin#511]
Currently when tabbing through the dashboard, you need to tab through every single point in a graph, which you can see in this [demo where it takes me 13 seconds to get through the graph](https://cloudup.com/cU5nIngN-t8).

Considering we could eventually have [50+ days worth of data with up to 9 lines](https://github.com/woocommerce/wc-admin/issues/505), this is basically a keyboard trap. Maybe we could have each line be a <kbd>tab</kbd>-able element, and allow for arrow key navigation of points on the line? There will also need to be design indication of which line is focused and which point is "active" (an active point is the one showing the hover card).

The bar chart has the same problem, maybe for that view we can group each day in a focusable element? I don't think each bar needs to be navigated though, since each bar in a group would show the same hover card.

We'll also want to make sure this doesn't conflict with the screen reader support.

**Comment by becdetat** [comment]
The dashboard doesn't include this chart now so I'm closing this.
