### ISSUE TITLE
Clear analytics cache debug tool translation string not registered

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce-admin#5115]
**Describe the bug**
A "Clear analytics cache" debug tool description is not registered as a string available for translations, it's always in English.

**To Reproduce**

1. Switch WP language to non-en.
2. Go to WooCommerce->Status->Tools.
3. Scroll down to Clear analytics cache section.

**Screenshots**
![Zrzut ekranu 2020-09-09 o 11 13 04](https://user-images.githubusercontent.com/27000783/92579641-bccbba00-f28d-11ea-9431-ad78228b3ed3.png)

WP 5.5.1
WC 4.5.0
WC Admin 1.5.0 (bundled with WC)

**Comment by timmyc** [comment]
@starypop that string is being run through the translation method [here](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/settings/historical-data/layout.js#L53-L56) - wondering if by having the string concatenated with the `+` might be resulting in it not appearing as available for translation?

**Comment by starypop** [comment]
@timmyc You've mentioned the wrong string, which is translated: https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/pl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9167962&filters%5Btranslation_id%5D=77020636

We're looking for the "**This tool will reset the cached values used in WooCommerce Analytics. If numbers still look off, try Reimporting Historical Data.**" string here and it's is not translatable: https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/pl/default/?filters%5Bterm%5D=This+tool+will+reset+the+cached&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=either&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=original_date_added&sort%5Bhow%5D=desc

**Comment by jeffstieler** [comment]
Thanks for the report @starypop! We've got a fix pending.
