### ISSUE TITLE
Inbox message: filter by product variations in order and product reports

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5116]
This notification should be shipped alongside #4330

**Title:** New - filter by product variations in orders and products reports
**Content:** One of the most awaited features has just arrived! You can now have insights into each product variation in the orders and products reports.  
**Segmentation:** Users that have at least one variable product
**Timing:** After the user updates to the WC version that includes this feature)
**Cadence:** Once
**CTA leads to:** the support doc about the new filter
**CTA label:** Learn more

**Comment by pmcpinto** [comment]
@timmyc do you think that we can implement this segmentation?

@jameskoster (sorry to bother you 😄 ) do you have the svg of the image that you shared on Slack?

**Comment by jameskoster** [comment]
Options are [here](https://www.figma.com/file/sB2FirvdUxuIiidXeY9TCB/Inbox-Notifications?node-id=0%3A1), incase @elizaan36 would like to riff on them some more.

**Comment by elizaan36** [comment]
hey all, let me know if this svg works for the inbox image.

[Banner.svg.zip](https://github.com/woocommerce/woocommerce-admin/files/5204920/Banner.svg.zip)

**Comment by pmcpinto** [comment]
@timmyc I think that the image is lightweight enough to include in Core, but I just want to confirm with you.

**Comment by becdetat** [comment]
@pmcpinto 

> do you think that we can implement this segmentation?

We can do that :-) it's a little out there but shouldn't be a problem.

> @timmyc I think that the image is lightweight enough to include in Core, but I just want to confirm with you.

It's 13kb uncompressed, 3kb compressed, so I think it can be included.

**Comment by becdetat** [comment]
@pmcpinto 

> I think that the image is lightweight enough to include in Core, but I just want to confirm with you

Actually, it looks like the note image system is designed for external images only. Is it possible to host it on the CDN? I don't know the process for that @timmyc

**Comment by becdetat** [comment]
Hi @elizaan36, something that I realised in implementing this is that the image was limited to 120px high, which in this case caused a heap of whitespace to the left and right of the image. I've removed the limit to fix that, it looks ok but it does look a bit big vertically. Probably not an issue with this one but it might bear keeping in mind that the image for an inbox note should be around 120px high :-)

**Comment by elizaan36** [comment]
Ok, thanks for that note @becdetat ! Let me know if you'd like me to take a look at anything.

**Comment by timmyc** [comment]
I spoke with @becdetat about the image in a recent chat and yes it seems small enough that we can ship in Woo core, much like how we include partnership logos for the OBW.

**Comment by pmcpinto** [comment]
@becdetat @samueljseay it would be great to include this notification in wcadmin 1.8, so it can be shipped in WC 4.9
