### ISSUE TITLE
[WC 4.5] `Store setup` option is still present after completing all tasks on Home Screen (Atomic only)

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5120]
**Describe the bug**

`Store setup` option is still present after completing all tasks on Home Screen. I can only see it happening on the Atomic site. Reproduced twice to make sure. It doesn't happen on the JN site. 

**To Reproduce**

0. Test on the Atomic site. 
1. Complete OBW.
2. Complete all the Home Screen tasks.
3. Navigate to `Orders` or `Products` sections.
4. See that `Store setup` option is present in the WC Admin nav bar but shouldn't be there since the setup is now completed. 
5. Click on `Store setup` option. You'd be taken to Home screen but there are no tasks to complete. 

**Expected behavior**

I expected `Store setup` option to not appear if all the Home Screen tasks are completed. 

**Screenshots**

See gif below:

http://g.recordit.co/IH1F5uzlFz.gif

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by timmyc** [comment]
I'm going to close this in favor of #5138 since we already have some debugging going there, and it is the same report ( happening on Atomic only )
