### ISSUE TITLE
Selecting custom date range greater than 5 years results in 503 Errors on VPS server (3 Cores / 6GB memory)

### ISSUE THREAD

**Issue by gbruzzo** [woocommerce/woocommerce-admin#5128]
**Describe the bug**
WP 5.5 / Woocommerce 4.5.1 
VPS 3 Cores / 6GB (Siteground)
only Woocommerce active (no other plugin)

We have recently started testing Woocommerce Admin on our staging site, with view to using it for in production. We have a sizeable user and order database (6k orders, 3k users) and an order history going back to July 2009. 

When selecting custom date intervals (in excess of 5 years, on the Revenue Report, for example) we are unable to retrieve the necessary statistics. 

- a message " There was an error getting your stats. Please try again." is displayed 

- Looking at the Dev Console in Chrome we observe multiple 500 then 503 Errors 
<img width="1263" alt="Screenshot 2020-09-11 at 13 17 23" src="https://user-images.githubusercontent.com/16798202/92924653-39e36480-f431-11ea-828d-facbe8cbf052.png">

- we spoke with support (Siteground), and increased the maximum allowed php processes from 40 to 140 - to no avail. 

**To Reproduce**

select a large date range (more than 6 years) 

**Expected behavior**

As noted above we have about 3k users and 6k orders spread over a 10 year range. 

We did not expect Woocommerce Admin to crash a VPS with 3 cores and 6GB (hosted by Siteground), in a basic configuration of Storefront + Woocommerce plugin only. 

Too many simultaneous queries overwhelm the server. As it stands, we unfortunately cannot use this in production. 
I would have no qualms if Woocommerce Admin was a plugin. But this is an integrated part of Woocommerce. 

- Do you have any suggestions? 
- Are you working on any optimisations? 
- Are there any optimisations we could require from our host?

Please Advise 

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
This is an instance of https://github.com/woocommerce/woocommerce-admin/issues/4919

**Comment by gbruzzo** [comment]
UPDATE 

Hello there 

I proceeded with further testing. As expected, the problem described above can be 'relieved' by selecting a lower data frequency (quarters, months or even weeks instead of days in our case). 

I can though imagine an installation on a shared server might run into trouble earlier. 

Suggestions welcome. 

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
@timmyc : noticed you engaged with https://github.com/woocommerce/woocommerce-admin/issues/4919

Might you have any suggestions in this case?  

Thanks in advance

Giacomo Bruzzo

**Comment by timmyc** [comment]
@gbruzzo indeed that is a _very large_ date range to process. In fact I thought we had a limitation on using the "day" interval when viewing a large date range for this very reason. I fear you are going to hit resource limitations like you have seen here with such a large date range, and a higher order/customer count site like you have described.

> As expected, the problem described above can be 'relieved' by selecting a lower data frequency (quarters, months or even weeks instead of days in our case).

Really I think this is your best course of action here. I guess I'm a bit curious why you are seeking to run the reports against legacy data on a 10 year date range like this? Is this something you do often - or are you trying to gather statistics to export to csv or ...?

Depending on the end goal here, another possible solution is to write some custom logic against the reporting REST API endpoints, but I'll wait to hear back more around your goals for pulling stats for 10 years of data.

**Comment by timmyc** [comment]
@gbruzzo - just wanted to follow up and see if I could be of further assistance here. I'm going to close this out for now but feel free to reply back with any further questions.

**Comment by gbruzzo** [comment]
Hello there @timmyc 

thanks for your response. 

Running reports on a ten year period would be interesting as we are a record label and have releases that are now up to ten years old. Reducing frequency of time series over longer time scales could be a solution, if none other is available. 
It would be useful though, to have to mechanism in place to stop a user from running a report that **crashes everything**, at least when it comes to defaults. 

Giacomo Bruzzo
