### ISSUE TITLE
Draft orders shouldn't be included on the store totals

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-admin#5131]
**Describe the bug**
I've branched this issue from here https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3132

The checkout block creates draft orders when someone visits checkout. When the shopper finishes the order, the status changes to the appropriate one.
It seems that reports will count draft orders as a valid order and count it in the total and store sales. Draft orders that didn't finish will get deleted after 24h, but I think the stats shouldn't include it anyway.

**To Reproduce**

1. Create a page with Checkout block (you will need to install WooCommerce Blocks plugin; this block is not available in core).
2. Add products to your cart, visit the checkout block, submit at least the email or any info, and leave.
3. Visit `Analytics -> Orders` you will see this order accounted for in the total.

**Expected behavior**
The order shouldn't be there until the checkout is done.

**Comment by senadir** [comment]
I see that there's this option
![image](https://user-images.githubusercontent.com/6165348/93027464-e164c080-f604-11ea-98b4-4d3a7b9b39e9.png)
With that in mind, I think that:
- Draft order should be considered a core status, not a custom one.
- Should be excluded by default and shouldn't be actionable.

**Comment by jimbardim** [comment]
> **Describe the bug**
> I've branched this issue from here [woocommerce/woocommerce-gutenberg-products-block#3132](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3132)
> 
> The checkout block creates draft orders when someone visits checkout. When the shopper finishes the order, the status changes to the appropriate one.
> It seems that reports will count draft orders as a valid order and count it in the total and store sales. Draft orders that didn't finish will get deleted after 24h, but I think the stats shouldn't include it anyway.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Create a page with Checkout block (you will need to install WooCommerce Blocks plugin; this block is not available in core).
> 2. Add products to your cart, visit the checkout block, submit at least the email or any info, and leave.
> 3. Visit `Analytics -> Orders` you will see this order accounted for in the total.
> 
> **Expected behavior**
> The order shouldn't be there until the checkout is done.

hi in my case the user either submit the info or leave it will be counted as a sale, i could understand if a visitor add his info and abandon (which again it shouldn't be included), but to record an order from just a visit is crazy!

**Comment by chihsuan** [comment]
I'm going to close this.

I've confirmed 'Draft order' has been excluded and there is no 'draft' status in the setting now.

![Screen Shot 2022-01-17 at 14 03 10](https://user-images.githubusercontent.com/4344253/149716064-c0fab1b1-4916-48d2-9235-3ead2c84f001.png)
