### ISSUE TITLE
Problem on woo commerce order tab 

### ISSUE THREAD

**Issue by mustafakamalmoss** [woocommerce/woocommerce-admin#5135]
On the woo commerce order tab on the top right corner i am unable to see the new order notifications and low stock notifications. Instead it is showing store setup.  
![Annotation 2020-09-12 130206](https://user-images.githubusercontent.com/51285981/93130399-48ad6e00-f6f4-11ea-980d-a70c6aec469b.png)

**Comment by mustafakamalmoss** [comment]
Okay thanks.

When i click on it, it gets stucked on this page even if i set up my tax.
![Annotation 2020-09-15 015905](https://user-images.githubusercontent.com/51285981/93132332-46004800-f6f7-11ea-95a0-bfa6f0443e34.png)

**Comment by timmyc** [comment]
@mustafakamalmoss thanks so much for taking the time to open the issue. We have been looking into this on #5138 - and am curious if you are able to share where your site is hosted at? We can only reproduce on WordPress.com hosting at the moment, but kind of interested to see if you might be able to share hosting details.

Also, if you click the "kebab" ... menu at the top of the Setup List, and select the option to hide the task list, does that fix the issue for you?

One final question: How have you setup taxes on the site? Just keen to learn a bit more about why that task is still appearing as not finished.

**Comment by timmyc** [comment]
@mustafakamalmoss since we haven't heard back from you I'm going to assume you were able to get things sorted out. If you still need assistance, please feel free to reopen the issue.
