### ISSUE TITLE
Store setup link persists after setup tasks are completed

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5138]
**Describe the bug**
After completing all store setup tasks and dismissing the Setup card on the home screen, the Store setup link in the app bar persists. Also, when clicking on the Store setup link it takes you back to the home screen with the Setup card showing again (after dismissing it.)

**To Reproduce**

1. Create a new test site and update to the latest release
2. Click on 'WooCommerce Home'
3. Complete all Store setup tasks and dismiss card
4. Click on 'Customers', 'Reports', etc
5. See the Store Setup link persist.

**Expected behavior**
Once the store setup task list is complete, the Store setup link in the app bar shouldn't appear at all.

**Screenshots**
Completed tasks 
<img width="1378" alt="Screen Shot 2020-09-15 at 8 31 42 AM" src="https://user-images.githubusercontent.com/5121465/93248820-fef56f80-f755-11ea-98e5-4a8e46240ec2.png">

Store setup link in Orders
<img width="1380" alt="Screen Shot 2020-09-15 at 8 32 13 AM" src="https://user-images.githubusercontent.com/5121465/93248958-3532ef00-f756-11ea-91f9-379a46b60f82.png">

Store setup link in Reports
<img width="1376" alt="Screen Shot 2020-09-15 at 8 32 41 AM" src="https://user-images.githubusercontent.com/5121465/93249051-5693db00-f756-11ea-851a-2ce0ef1ff431.png">

**Desktop (please complete the following information):**

- OS: Mac OS 10.15.6
- Browser: Firefox 80.0.1 and Chrome 85.0.4183.102

**Comment by timmyc** [comment]
@samueljseay could you take a look at this one?

**Comment by timmyc** [comment]
Looks like another report of this in #5135

**Comment by samueljseay** [comment]
@elizaan36 Could you confirm what version this is? I can't reproduce this locally or on a JN site.

Is it WC 4.5.2 like the other issue you raised?

**Comment by elizaan36** [comment]
Yep it's version 4.5.2 as well.

**Comment by elizaan36** [comment]
Based on #5120 it may only be Atomic sites
