### ISSUE TITLE
The Leaderboards in the Analytics > Dashboard report don't seem to be taking the correct currency formatting

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce-admin#5154]
Bug Description
--
I'm using a filter, written following your guidelines, to alter the currency formatting arguments depending on the currency selected on the reports. This ensures that amounts are formatted correctly on most reports, as well as most of the dashboard. However, the Leaderboards section deosn't seem to be taking the formatting arguments into account and always used the USD parameters (incidentally, USD is not even the shop's base currency).

How to reproduce the issue
--
1. Implement a currency filter like the one described in your documentation (see [Extending WC-Admin Reports](https://woocommerce.wordpress.com/2020/02/20/extending-wc-admin-reports/)).
2. Go to the Dashboard report.
3. Select a currency.
4. The currency in the dashboard reflects the selected one, while the Leaderboard shows amounts formatted as USD.

Expected behavior
--
The Leaderboard widgets should take the correct currency formatting arguments, like the other sections of the report.

Screenshots
--
1. Dashboard, amounts in the leaderboards are formatted incorrectly: https://prnt.sc/uitqwv
2. Orders report, correct: https://prnt.sc/uitp41
3. Products report, correct: https://prnt.sc/uitpib

**Note**: screenshots 2 and 3 are included for reference, to show that the currency filter works as it should in most places, and that only the leaderboards seem to ignore it.

System information
--
**Desktop (please complete the following information):**
* OS: Windows 10
* Browser Chrome
* Version 85

**Note**: the OS and browser are unimportant in this case, the issue occurs on all of them

Additional context
--
* The issue is related to filter `woocommerce_admin_report_currency` (JavaScript), which the Leaderboards seem not to trigger, or they might be ignoring the returned data.
* This issue might be linked to https://github.com/woocommerce/woocommerce-admin/issues/4491 (can't say for sure, as I haven't been able to debug the WC Admin JavaScript).

**Comment by octaedro** [comment]
Thank you @daigo75. I took a look at this and it definitely seems like a bug.

**Comment by daigo75** [comment]
@octaedro Thanks Fernando. Unfortunately, my knowledge of React/Webpack-based stuff is practically NIL, otherwise I would have been happy to go deeper in the investigation.

**Comment by dwainm** [comment]
Hi @octaedro, just wanted to highlight this issue again. We discovered it as we were working on adding Multi-Currency support to WooCommerce Payments.
