### ISSUE TITLE
Set up additional payment providers link in Inbox card not working on AT site

### ISSUE THREAD

**Issue by oneillo** [woocommerce/woocommerce-admin#5156]
**Describe the bug**
When I click on `Set up payments` in the `Set up additional payment providers` Inbox card, the page reloads back onto the same WCAdmin page. 

Here is the link it is trying to reach: https://<MYTESTSITENAME>.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&task=payments

The task list is not displayed on my WCAdmin page. I don't know if this is unique to AT sites.

**To Reproduce**

1. Create WPCOM site and upgrade to Business plan
2. Install WC plugin
3. Install WCPay plugin and activate
4. Visit WC Admin area
5. Click on `Set up payments` in the `Set up additional payment providers` Inbox card

**Expected behavior**
I expected the link to take me to the start of the Set Up Payments task.

**Screenshots**
Here is a GIF of the described behavior.
![Screen Capture on 2020-09-17 at 12-42-09](https://user-images.githubusercontent.com/730723/93524630-a22abe00-f8e9-11ea-9ba0-2a749226f4c8.gif)

https://d.pr/i/egXji7

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: Version 85.0.4183.102 (Official Build) (64-bit)
* WOO Version: 4.5.2

**Additional context**
N/A

**Comment by juliaamosova** [comment]
I can reproduce this issue in WC 4.7 RC (which contains WC Admin 1.6.3). 

>The task list is not displayed on my WCAdmin page.

This is an important bit here. `Set up additional payment providers` link doesn't work only when the Task List is completed/marked as hidden. I tested this with the Task List visible and the `Set up additional payment providers` link works in that case. 

>I don't know if this is unique to AT sites.

I could reproduce this on Atomic and JN sites. Gifs confirming that below:

**JN:**

![](http://g.recordit.co/7NhEUctFBI.gif)

**Atomic:**

http://g.recordit.co/39ZRT2I6OD.gif
