### ISSUE TITLE
New or returning customer is missing

### ISSUE THREAD

**Issue by ciszere** [woocommerce/woocommerce-admin#5181]
Hello,

Im not a pro in programing so bare with me here :) I love this plugin under the page Order i was able to see if the customer was an returning or an new customer. This was important to me since I add different packing (greeting cards, coupons etc) for new customers compared to old customer. Now I cannot find anyware this in an easy way. What happend here? :)

Thanks in advance. 
Best
Johan

**Comment by pmcpinto** [comment]
Hey @ciszere, can you share a screenshot?

**Comment by ciszere** [comment]
Hello,

Of course :) see attached image. In the marked area ut used to me an colum that said "Returning" or "new" customer. Now its gone and replaced by just "customer name"

<img width="1440" alt="Skärmavbild 2020-09-28 kl  08 51 23" src="https://user-images.githubusercontent.com/60106580/94399703-2b52b800-0168-11eb-9a8e-dacf610c6650.png">

**Comment by timmyc** [comment]
Hello @ciszere thanks so much for taking the time to open up this issue. It appears the status of the customer being new vs returning was removed on accident in #4430 when another bug around the totals of new vs returning customers in the footer of the table was being fixed.

I've added this bug to our current backlog so hopefully we can get a fix out for this in our next release which is due in November. Apologies for breaking this part of your workflow, and thanks again for taking the time to let us know.

**Comment by ciszere** [comment]
Hello,

Thanks a lot for your reply, happy to help. Looking forward to the new
update! :)

Thanks

Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den mån 5 okt. 2020 kl 22:15 skrev Timmy Crawford <notifications@github.com

**Comment by joshuatf** [comment]
This was actually removed intentionally (see comment - https://github.com/woocommerce/woocommerce-admin/pull/4430#issuecomment-636047352).

Though I don't see the harm in adding this column back in and allowing store owners to toggle it on or off if they like.  /cc @timmyc

**Comment by mdmoore** [comment]
Thanks for clarifying @joshuatf .  So it appears that there are 2 different CSVs that might be generated.  One is the instant download, when the file is small enough.  The other is email when the file is too large to be generated immediately.  The CSV from the immediate download matches the UI, with customer first/last name.  The CSV generated to be email still displays returning.  As a side note(possibly another bug), the emailed CSV headers are missing: 

**Emailed Version**
![https://d.pr/i/7Xe97L](https://d.pr/i/7Xe97L+)
Full Image: https://d.pr/i/7Xe97L

**Immediate Download Version**
![https://d.pr/i/xsu1j7](https://d.pr/i/xsu1j7+)
Full Image: https://d.pr/i/xsu1j7

**Comment by DustinHartzler** [comment]
This came up in live chat 23529134-hc.

The downloaded reports are missing the customer names (like @mdmoore highlights above) and has new or returning in the columns. And the instantly downloaded ones have the names but no column for new or returning customers.

**Comment by ZGrissom** [comment]
I understand the point that customers theoretically can come up in a report both as a New User and a Returning User and it seems like the feeling is that it is a flawed logic.  However, Consumer Acquisition Costs (CAC) are the heartbeat of ecommerce and I and i'm sure many others like the snapshot view of "how much is it costing me to acquire customers this month?" So, if we aren't going to have it agregate at the bottom of the table any more then please add it back in to the Immediate Download version of the table.

**Comment by zdenys** [comment]
Another case on the forum: https://wordpress.org/support/topic/order-reports-dont-include-customers-name/

**Comment by dchan168** [comment]
Does anyone know when this fix will be deployed?

**Comment by timmyc** [comment]
@dchan168 we don't have a fix in place yet for this, so no eta on it being shipped quite yet.

**Comment by ciszere** [comment]
Hello,

Thanks for letting me know. I found another issue that is related to this
error. When i try to filter customers - Advanced filters" - "Customer is
returning/new"
it doesn't work. it just shows all orders regarding if i filter for new or
returning. See attached screenshot.

If this filtering would work then I could use this until you have fixed the
initial issue :)

Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den ons 2 dec. 2020 kl 00:32 skrev Timmy Crawford <notifications@github.com

**Comment by becdetat** [comment]
Hi @ciszere,

Thanks for raising this issue. I'm about to address the issue with the new/returning column not appearing in the instantly downloaded CSV.

> I found another issue that is related to this
> error. When i try to filter customers - Advanced filters" - "Customer is
> returning/new"
> it doesn't work. it just shows all orders regarding if i filter for new or
> returning

Can you open another ticket for this issue? That will make it easier to track.

**Comment by ciszere** [comment]
Thanks a lot,
No problem, I will open an new ticket! :) thanks for great support

Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den tors 3 dec. 2020 kl 08:09 skrev Bec Scott <notifications@github.com>:

**Comment by becdetat** [comment]
Adding the Customer Type column to the orders report table and instantly generated CSV has been implemented and should be included in the WooCommerce Admin 1.8.0 release and the following WooCommerce 4.9 release, due in January 2020.

**Comment by ciszere** [comment]
Awesome, thanks!

Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den fre 4 dec. 2020 kl 06:46 skrev Bec Scott <notifications@github.com>:
