### ISSUE TITLE
WC 4.6 Beta 1: wrong title in the Store Details step

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5183]
Calling "Setup Wizard" to the store details task can be confusing and misleading: https://d.pr/i/CZeEkx

The title should be changed to "Store Details" as we currently have: https://d.pr/i/LSOHwB

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm working on this issue, is it ok if we also change the `Skip setup wizard` button to `Skip setup store details`?

![screenshot-one wordpress test-2020 09 23-16_22_17](https://user-images.githubusercontent.com/1314156/94059605-0b627380-fdb9-11ea-8b6c-883414dc1bc5.png)

**Comment by pmcpinto** [comment]
> I'm working on this issue, is it ok if we also change the Skip setup wizard button to Skip setup store details?

I think it will be more clear if we change the copy to `Skip setup store details`

**Comment by pmcpinto** [comment]
@octaedro I'm testing 4.6 RC1 and I'm still seeing "Setup Wizard" can you confirm if this was included or not?

https://d.pr/i/VkFPEJ

**Comment by octaedro** [comment]
Hi @pmcpinto,
I couldn't see the commits related to these changes (`f6b21e4` and `ee2ada3`) in `v1.6.0-rc.3`, which is used by WooCommerce `4.6.0-rc.1`.

cc @timmyc

**Comment by pmcpinto** [comment]
@octaedro @timmyc is it possible to include it in the next 1.6 release?
