### ISSUE TITLE
WooCommerce 4.6 Beta 1: Payments task - Stripe and Square missing

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5185]
**Describe the bug**
We're not displaying Stripe in the payments task and I think that Square is missing as well (if the user selected the US as the store location and physical products selected)

**To Reproduce**

1. Install WooCommerce 4.6 beta.1 in a new site
2. Complete the profiler flow with a store located in a country supported by Stripe (eg Portugal or UK)
3. Go to the Payments task in the home screen
4. See that the Stripe option is missing

**Expected behavior**
To see Stripe and Square* as an option 

*if the user selected the US as the store location and physical products

**Screenshots**
Store with Portugal as the location: https://d.pr/i/UxwLzM
Store with the US as the location and physical products selected: https://d.pr/i/dCrxO6

**Comment by pmcpinto** [comment]
@joshuatf do you know what can be causing this? I'm not sure if you were the last one making some changes in this step

**Comment by joshuatf** [comment]
It appears Stripe is not being shown because `stripeSupportedCountries` is empty in `methods.js`.   It looks like the new `tasks` REST API is missing this parameter so it will need to be added.

I'm seeing Square still showing up if you have a brick and mortar store and are in a Square supported country (e.g., US).

**Comment by octaedro** [comment]
Hi @pmcpinto,
Square is working well on my end too.
As I see in the bug description, a `physical product` was selected but we check with `physical stores`. Also, the countries supported by Square are:  `US`, `CA`, `JP`, `GB` and `AU`
Maybe those were the problems.

**Comment by pmcpinto** [comment]
> I'm seeing Square still showing up if you have a brick and mortar store and are in a Square supported country (e.g., US).

> As I see in the bug description, a physical product was selected but we check with physical stores. Also, the countries supported by Square are: US, CA, JP, GB and AU

I completely forgot that the logic was tied to physical stores and not products. Sorry!

**Comment by joshuatf** [comment]
No problem, @pmcpinto!  I had to go look at it again myself to double check.

The Stripe logic is fixed as of https://github.com/woocommerce/woocommerce-admin/pull/5197 and will be available in the next release.
