### ISSUE TITLE
Problem in Woocommerce after update 

### ISSUE THREAD

**Issue by khaliltws** [woocommerce/woocommerce-admin#5186]
After updating my theme and WooCommerce to latest versions 
I have problems in my website :
1- Dashbord of WooCommerce do not work anymore !
![image](https://user-images.githubusercontent.com/46076234/93917091-0ab6d800-fcfa-11ea-9c49-ca0c3eaf1e9a.png)
2- Editor to add or edit product also do not works anymore (I can only use text editor and not Visual one)
![image](https://user-images.githubusercontent.com/46076234/93917159-23bf8900-fcfa-11ea-9d4e-c37a8e03bb42.png)
Thanks !

**Comment by becdetat** [comment]
I've confirmed that the method shown as undefined in the above error message does exist in the latest released WooCommerce version (4.5.2) and hasn't been touched for at least 6 months.

@khaliltws can you confirm the version that you are upgrading from and the version that you have upgraded to, per above? That will help us to narrow down the problem. Thanks!
