### ISSUE TITLE
[WC 4.6 Beta] Tooltip is getting cut off

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5189]
**Describe the bug**
In the store profiler in Step 1, the text is no longer wrapping within the tooltips that appear on hover. The first one on step 1 is getting cut off since it's quite long.

**Expected behavior**
In the store profiler tooltips in Step 1, the text should wrap for better readability.

**Steps to reproduce the bug:**
- Create a new site or go to **Settings > Help > Setup Wizard** to access the setup wizard on an existing site
- Go to Step 1
- Hover over first tooltip and see error

**Screenshots**
Current tooltip in step 1:
<img width="1499" alt="Screen Shot 2020-09-23 at 12 31 57 PM" src="https://user-images.githubusercontent.com/5121465/94056187-933d8300-fda3-11ea-9ff4-fa8dc9a771a3.png">

What the tooltip looks like with text wrapping:
<img width="1678" alt="Screen Shot 2020-09-13 at 8 26 40 PM" src="https://user-images.githubusercontent.com/5121465/94056479-f6c7b080-fda3-11ea-8603-7ebd3df89162.png">

**Desktop (please complete the following information):**
* Mac 10.15.6 Firefox

**Comment by tammullen** [comment]
On Chrome 85 on Mac I am also seeing that tooltip move but other tooltips aren't.

![Screen Recording 2020-09-22 at 17 21 57 2020-09-22 17_55_11](https://user-images.githubusercontent.com/24649833/94148105-17f4d380-fe6e-11ea-93b7-abd9fc51cf9e.gif)

**Comment by tammullen** [comment]
Just noting that this wasn't included in 1.6 RC 1 so it would be great to get it included in the next 1.6 release
