### ISSUE TITLE
Advanced filter menu has broken styles

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#5191]
**Describe the bug**
When selecting an advanced filter to add to an analytics report, the style is broken. Noted while testing https://github.com/woocommerce/woocommerce-admin/pull/5167 however it reproduces in all reports with advanced filters. 

**To Reproduce**

1. Navigate to the orders report
2. In the "show" menu, switch to "Advanced filters"
3. Add a filter
4. Note the highlight only extends as far as the text, rather than across the width of the container

**Screenshots**
<img width="304" alt="Screen Shot 2020-09-23 at 9 30 22 PM" src="https://user-images.githubusercontent.com/4500952/94102125-3911e180-fde6-11ea-8a08-b7e99405f12f.png">

**Additional context**
We may want to consider switching this menu to use the same component / styles that are available in the block editor toolbar menu: 

<img width="679" alt="Screen Shot 2020-09-23 at 9 47 48 PM" src="https://user-images.githubusercontent.com/4500952/94102202-75454200-fde6-11ea-92be-b3e8b08a4313.png">

cc: @elizaan36

**Comment by elizaan36** [comment]
Hey, thanks for flagging this @LevinMedia ! Looks like the `div` inside the `components-popover_content` just needs to be set to `width: 100%`. I'll try and make that adjustment, but yeah in the longer term we should try to make a holistic switch to block editor components. Let's chat about that more.

**Comment by LevinMedia** [comment]
Sounds good! Thanks!
