### ISSUE TITLE
How to force csv report by email?

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [woocommerce/woocommerce-admin#5202]
Currently, if you click on the download button, you can get the csv report generated by javascript, if the amount of items is small or by email if the report table is bigger than the number of rows per page.

The problem is, when creating custom columns, I can only get them to be displayed on the email csv, not by javascript.
So, how can I force the csv to be sent by e-mail always regardless of the report table size?

**Comment by jeffstieler** [comment]
> The problem is, when creating custom columns, I can only get them to be displayed on the email csv, not by javascript.

I'd say that's a bug. Would the inclusion of your custom columns in the JS-powered CSV resolve the issue for you?

**Comment by pablo-sg-pacheco** [comment]
Yes it would @jeffstieler !
What do I have to do to create the custom columns in JS?
I supposed it would have to work right out of the box but that's not the case.

**Comment by jeffstieler** [comment]
If you haven't filtered in the column values in JS yet, that's why they aren't appearing in the report. Check out this example for a guide/reference: https://github.com/woocommerce/woocommerce-admin/blob/main/docs/examples/extensions/table-column/js/index.js

**Comment by pablo-sg-pacheco** [comment]
I did that already. 
The only thing it did for me was to add the custom columns I wanted on the Analytics page, but when I click on the download button, the CSV doesn't contain the columns.

The only way I could get the columns working on the CSV was using these filters:
`woocommerce_export_admin_orders_report_row_data`
`woocommerce_admin_orders_report_export_column_names`

But it only creates the columns in the CSV generated by the server.

**Comment by jeffstieler** [comment]
Ok cool - just wanted to double check that you had both the necessary PHP and JS in place. Sounds like this is a bug we need to fix - stay tuned for updates. Thank you for reporting this issue!

**Comment by cholosurfer** [comment]
In addition to this bug, when generating a Orders Report and it's emailed it loses custumers names, it prints something like a customer state but no names.

It would be nice that you can always download reports on-the-fly, because for some reason only Admins can receive those reports, why store managers can't receive them?

**Comment by jeffstieler** [comment]
Hi @cholosurfer 👋  - would you mind [creating a new issue](https://github.com/woocommerce/woocommerce-admin/issues/new/choose) for the customer names? Thank you.

**Comment by bowenac** [comment]
Any update on this possible bug? I'm having the same issue, I have added new columns to the order view which show up, but they're not showing in the CSV when exporting.

**Comment by becdetat** [comment]
As this is actually working mostly as designed, I've fixed the issue where the client side filter worked on the UI but not on the instant CSV download - #5787. The client side filter in conjunction with the existing server side filters should make it possible to add columns in all situations.
