### ISSUE TITLE
Home Screen - layout control

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5224]
**User story:**
As a merchant
I want to have more control over the layout
So I can tailor the page according to my needs

**Description:** as we iterate on the home screen we think that a single-column layout can be more effective. However, this can be an abrupt change for users, as they're getting used to the two-column layout. The best option seems to provide an intermediate step where we allow users to choose the layout that they want to use. In the future, this can also be used to show/hide specific home screen sections (under evaluation)

**Acceptance criteria:**
- [ ] The user is able to switch between the one-column and two-column layout through a Layout option in the navbar.

![screen-shot-2020-09-27-at-10.30.49-pm.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/1889cc17-60d8-4c44-ba0a-581a25eafcfc)

**Event tracking:**
Click the Display icon:
`wcadmin_homescreen_display_click`
Event props: none

Select one Display option:
`wcadmin_homescreen_display_option`
Even prop: `display_option` : `single_column` | `two_columns`

**Additional links:**
[P2 with link to Figma ](pbIJXs-ma-p2)

**Comment by samueljseay** [comment]
@pmcpinto clarification question on this, I assume we default to the single column layout and this would let them opt out?

**Comment by samueljseay** [comment]
In case anyone is looking the relevant logic for when single column or 2 column should display is in #5223
