### ISSUE TITLE
Task List: Allow task deep links even after list is hidden or completed

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-admin#5237]
**Is your feature request related to a problem? Please describe.**
It would be useful and convenient to be able to access the UI for individual tasks – even after the list itself is dismissed – from other areas of the app (such as installing and configuring a payment method via the Inbox).

**Describe the solution you'd like**
Currently, the Homescreen (columns) are displayed at `?page=wc-admin&task=payments&method=stripe` if the task list is not enabled. Would we be able to render the flow for that method – and then redirect to either a) Home, b) the Payments task and then Home, c) the Payments settings screen, or d) back where you came from – without adding much complexity?

**Describe alternatives you've considered**
Linking to the relevant extension on the Plugins screen.

**Should this be prioritized? Why?**
Hoping to introduce a seamless new extension install for existing merchants [paJDYF-QT-p2#comment-3611].

**Additional context**
–

**Comment by elizaan36** [comment]
As one possibility, this could be solved by including the ability to show/hide the setup task list from the display control in the app bar. This would allow merchants to go back to those tasks if they need to.

![Home - Setup tasks in display dropdown.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/d5a3a1c1-ac91-4b74-842e-ef2b1b3a076e)

**Comment by dechov** [comment]
The motivating root issue is being solved in an alternative way – directly from the Inbox note – so feel free to close this if not directly aligned with other objectives @samueljseay @pmcpinto

**Comment by samueljseay** [comment]
Thanks @dechov I do think this one will be too difficult for us to tackle right now.
