### ISSUE TITLE
Home Screen - migrate orders panel

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5238]
**User story:**
As a merchant
I want to easily see how many orders need my immediate attention when I enter WooCommerce
So I can manage them as soon as possible

**Description:** we’re going to migrate the orders panel features to the home screen, as managing orders is one of the most important store management tasks.

**Acceptance criteria:**
- [ ] Display a task in the home screen including up to 5 orders in reverse chronological order
![Home.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/9e9af75b-5fa8-4523-9d9e-1ac0374dd2e9)
Note: the task title will be different
- [ ] Display a `Manage all orders` CTA that redirects the user to the orders list
- [ ] The order card should include the same elements that we have now: order number, customer name, price, number of products, time, order status and call to action
- [ ] Redirect the user to the respective order if the user clicks in the order number or in the `Open` CTA
- [ ] Redirect the user to the Customer report filtered by the customer name if the user clicks in the customer name 
- [ ] Keep the logic in terms of displaying orders that are "actionable" and the Manage “actionable” order statuses settings at Analytics > Settings
- [ ] Change the copy displayed at Analytics > Settings > Actionable Status (https://d.pr/i/LA5p16) to "Orders with these statuses require action on behalf of the store admin. These orders will show up in the Home Screen - Orders task."

- [ ] The orders activity panel should be removed from the navbar once we have the same feature in the home screen

**Event tracking:**
Can we reuse the same event tracking that we have in the orders panel?

**Additional links:**
[P2 with links to the Figma file](pbIJXs-ma-p2)

**Comment by octaedro** [comment]
Hey @pmcpinto,
In the requirements you mentioned:
> The orders activity panel should be removed from the navbar once we have the same feature in the home screen

Just to confirm, the idea is to only see the orders panel on the `Home` screen, as is presented in the design. It won't be available in other places. Right?

**Comment by pmcpinto** [comment]
> Just to confirm, the idea is to only see the orders panel on the Home screen, as is presented in the design. It won't be available in other places. Right?

@octaedro yes, that's correct

**Comment by octaedro** [comment]
Hi @pmcpinto, 
I have two questions:
The acceptance criteria says:
> The order card should include the same elements that we have now: order number, customer name, price, number of products, time, order status and call to action.

But in the design, we don't have the `order status`. Is it ok if we remove it to follow the design?

**Comment by pmcpinto** [comment]
@octaedro thanks for the heads up.

@elizaan36 I don't know if you remember but we talked about adding the order status, because we have a setting that allows the user to select which orders should be displayed in the activity panel. Can you fine-tune the design?

**Comment by elizaan36** [comment]
here's the design with the order status to match what's existing in the current Orders panel.

![Home - All agenda items - Orders expanded](https://user-images.githubusercontent.com/5121465/97619074-c64fe380-19ed-11eb-80de-2ad69964fb89.png)

To clarify, in the original design the `Open` pill was the placeholder for the order status. This update will simply replace that with the existing `woocommerce-order-status_indicator` with the status label shown to the right.
