### ISSUE TITLE
Home Screen - migrate Stock panel

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5239]
**User story:**
As a merchant
I want to easily see how many products are low stock or out of stock when I enter WooCommerce
So I can restock inventory as soon as possible

**Description:** we’re going to migrate the stock panel features to the home screen, as managing inventory is one of the most important tasks for stores with Stock Management enabled

**Acceptance criteria:**
- [ ] Display a Stock task in the home screen in stores with [Stock Management](https://docs.woocommerce.com/document/managing-products/#inventory-tab) enabled
- [ ] Display up to 5 products that are either Low in Stock or Out of Stock
![Home (1).png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/0d5fd5eb-8b51-4388-b389-830cfe299a10)
- [ ] The product card should include the same elements that we have now: image, product name, current stock and `Update Stock` CTA. Ideally we should also add the last time that a product was ordered (nice to have)
- [ ] The user is redirected to the product page when clicking in the product name
- [ ] Clicking in the `Update Stock` CTA opens a modal allowing the user to update the product stock without leaving the home screen
![Home (2).png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/65163851-7fce-4253-9528-ecbfe4583637) 
- [ ] The stock activity panel should be removed from the navbar once we have the same feature in the home screen

**Event tracking:**
Can we reuse the same event tracking that we have in the stock panel?

**Additional links:**
[P2 with links to the Figma file](pbIJXs-ma-p2)

**Comment by jeffstieler** [comment]
Noting for my own sake that this is the most recent design of the card title:

![Uploading home-all-agenda-items.png…]()

**Comment by jeffstieler** [comment]
> The stock activity panel should be removed from the navbar once we have the same feature in the home screen

@pmcpinto @elizaan36 does that mean the stock panel will only be available on the homescreen? I see that Orders has been removed, but Inbox remains.

**Comment by pmcpinto** [comment]
> @pmcpinto @elizaan36 does that mean the stock panel will only be available on the homescreen? I see that Orders has been removed, but Inbox remains.
Yes, that's correct. @elizaan36 we should consider removing the inbox as well.

> Also - should the Stock panel be hidden when there are no low/out stock products?

I think the idea is to have a similar empty state that we also have for the orders panel, when the user has inventory management enabled. If it's disabled the panel should be hidden.

**Comment by elizaan36** [comment]
> @elizaan36 we should consider removing the inbox as well.

@pmcpinto Do you think we should remove the orders panel as a global element? It's not showing up on the Home screen for me.

> I think the idea is to have a similar empty state that we also have for the orders panel, when the user has inventory management enabled. If it's disabled the panel should be hidden.

Yep, here are those designs of the agenda panels with empty states.

Panels collapsed
![Home - Stock empty state](https://user-images.githubusercontent.com/5121465/99576757-00365900-29a0-11eb-97b2-68cb7477fbdd.png)

Orders empty state expanded
![Home - Stock empty state-1](https://user-images.githubusercontent.com/5121465/99576789-09bfc100-29a0-11eb-9959-c723d55a2cad.png)

So for Reviews and Stock, the panel will remain with the `0` count and no accordion. There won't be a link to `All inventory` in the same way that orders has the link to `All orders`, so no need for the accordion with the Stock empty state.

**Comment by elizaan36** [comment]
Here's an update based on my conversation with @jeffstieler earlier today. Essentially, the current functionality allows for in line editing of inventory and there's not a great reason to move away from that in favor of a modal.

[Stock inline editing](https://share.getcloudapp.com/qGulPLAP)
![Stock inline editing](https://user-images.githubusercontent.com/5121465/99585551-1ba76100-29ac-11eb-8287-1091e94ff9d4.gif)

- Inventory count appears as the `woocommerce-stock-activity-card_stock-quantity` with one tweak: If the inventory reaches `0` or any negative number the text color appears as `Primary-alert red` (with the same background.)
- Selecting `Update stock` will open the form field inline of the stock quantity and will have the same functionality as currently.
- Clicking save will update the stock quantity, change the text color back to gray and show a snackbar confirmation, "Stock updated. [Undo]". After a few seconds this updated product will disappear from the panel (potentially at the same time as the snackbar.)
- One other thing we discussed - There will be 5 items max in the Stock panel, and as products are updated (and disappear from the panel) other stock notifications will appear in their place (if there are more.)

All designs are in the Figma (i9)

**Comment by pmcpinto** [comment]
> @pmcpinto Do you think we should remove the orders panel as a global element? It's not showing up on the Home screen for me.

Yep, I think it should be better to simplify and just have it on the home screen. WDYT?

**Comment by elizaan36** [comment]
Oh I meant Inbox when I said orders panel. You think the Inbox should be removed as a global element then😆
I definitely think the Inbox should be removed from areas like Settings, but also don't see a huge benefit in areas outside of the Home screen.

**Comment by pmcpinto** [comment]
Ah yep I agree that the inbox should be removed as well.
