### ISSUE TITLE
Home Screen - migrate Reviews panel

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5240]
**User story:**
As a merchant
I want to easily see how many new reviews my store has when I enter WooCommerce
So I can review them as soon as possible

**Description:** we’re going to migrate the reviews panel features to the home screen, as managing reviews can be an important task for stores with Product Reviews enabled

**Acceptance criteria:**
- [ ] Display a Product Reviews task in the home screen in stores with [Product Reviews](https://docs.woocommerce.com/document/configuring-woocommerce-settings/#section-9) enabled
- [ ] Display up to 5 reviews pending moderation
![Home (3).png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/96c46fe7-eb96-41ed-905a-d57287046444)
- [ ] The review card should include the following elements: image, product name, customer name, rating, comment, time and the `approve`, `mark as spam` and `delete` actions
- [ ] The user is redirected to the product page when clicking in the product name and redirected to the Customer report filtered by the customer name if the user clicks in the customer name
- [ ] Include a `Manage all reviews` CTA at the bottom of the task that redirects the user to the reviews list
- [ ] The review activity panel should be removed from the navbar once we have the same feature in the home screen

**Event tracking:**
Can we reuse the same event tracking that we have in the reviews panel?
We also need to add on to cover the moderate actions:
`wcadmin_reviews_action`
Event prop: `action`- `approve` |`mark as spam` | `delete`

**Additional links:**
[P2 with links to the Figma file](pbIJXs-ma-p2)

**Comment by louwie17** [comment]
@pmcpinto I just have a couple small questions:

> The review activity panel should be removed from the navbar once we have the same feature in the home screen

 should the activity panel also be removed from the navbar on the other screens (products, orders, etc...) or just the homescreen?

In relation to #5552 where we don't show the orders tab if there are no orders, should the reviews panel also not be shown if there hasn't been any reviews yet? I know the panel will show a `Learn more` button in that case with a link to reviews best practices.

**Comment by pmcpinto** [comment]
> should the activity panel also be removed from the navbar on the other screens (products, orders, etc...) or just the homescreen?

Hey Laurens, it should be removed from all the screens
> where we don't show the orders tab if there are no orders, should the reviews panel also not be shown if there hasn't been any reviews yet? I know the panel will show a Learn more button in that case with a link to reviews best practices.

The idea is to show the panel and the 0 count without according as the empty state. See this [comment](https://github.com/woocommerce/woocommerce-admin/issues/5239#issuecomment-729897323) about the Stock panel
cc @elizaan36
