### ISSUE TITLE
Inbox Notification -> WooCommerce 4.6 Release

### ISSUE THREAD

**Issue by brentmackinnon** [woocommerce/woocommerce-admin#5241]
I'd like to begin notifying customers of minor releases in their inbox.

The next minor release is 4.6. So ... 

Timing: 
October 20

Headline:
WooCommerce 4.6 is here!

Body:
The latest version of WooCommerce has arrived. As usual, we have plenty of fixes and improvements along with exciting new features to help you get the most out of WooCommerce. Click to learn more about this release, and how to update.

Link: 
https://docs.woocommerce.com/document/how-to-update-woocommerce/ 

Let me know what other info you need.

**Comment by pmcpinto** [comment]
@brentmackinnon this aims to target all stores that don't have WooCommerce 4.6 installed, correct?

cc @becdetat

**Comment by brentmackinnon** [comment]
@pmcpinto yes, anyone that doesn't have 4.6 would be great.  also @becdetat, since the release is technically the 13th, it might make sense to schedule this for the 13th, rather than the 20th.  Is this doable?

**Comment by pmcpinto** [comment]
@brentmackinnon the modal is only displayed if users already updated to 4.6. Do you want to send one to users that have an older Woo version?

@becdetat I think it's possible to target users with a specific WooCommerce version, correct?

**Comment by becdetat** [comment]
@pmcpinto @brentmackinnon I'm sorry, I completely missed this conversation. From what I understand this would be a remote inbox notification, correct? We don't currently have any way of targeting users with a specific WooCommerce version, that would need to be added as a new rule type (which isn't a huge amount of work), which would need to go out with WC 4.8. That means that a notification could be sent out for WC 4.9 to merchants on WC 4.8 and so forth.

**Comment by becdetat** [comment]
So we already actually do have a plugin version rule. If we were to set this up via the WooCommerce.com feed the rule for the note spec would look like this:

```json
{
	"type": "plugin_version",
	"plugin": "woocommerce",
	"version": "4.6.0",
	"operator": "<"
}
```

This will target any stores with a WooCommerce version of less than 4.6.0.

**Comment by pmcpinto** [comment]
Same with this one
