### ISSUE TITLE
Home Screen - consolidate the task UI

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5243]
**Description:** we aim to consolidate some of the tasks' elements, in order to provide a cohesive experience when the user is completing the tasks displayed in the task list.

![Home (4).png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/3bfc31df-61f2-489d-b481-c37ceaffc0c8)

**Acceptance criteria:**
- [ ] Every task area needs to have a title, counter with the number of tasks, and an option to show/hide all the tasks
- [ ] The setup task area is the only one that can be dismissed
- [ ] Instead of showing the progress bar in the setup task area we should display the counter with the number of incomplete tasks
- [ ] The rest of the setup tasks UI can remain the same in this iteration: completed tasks checkmark, dismiss feature, etc
- [ ] The tasks should have the following order: setup, orders, stock, reviews, 3PDs

**Event tracking:**
NA

**Additional links:**
[P2 with links to the Figma file](pbIJXs-ma-p2)

**Comment by jeffstieler** [comment]
Lots of detail into how this should work and be implemented with certain components in this comment: pbIJXs-ma-p2#comment-861

**Comment by elizaan36** [comment]
Yup, I'll add the details from the P2 here and will share in GH only for these types of refinements in the future. 

Sounds like it makes sense to add this functionality to the [core card component](https://href.li/?https://wordpress.github.io/gutenberg/?path=/story/components-card--default) (but within wc-admin to start.) Looks like @octaedro has already made these updates in #5455 🎉

Along those lines, I'll share the updates to the design here to be more in line with the WordPress card component and minimize the required changes.

![Home - Setup tasks](https://user-images.githubusercontent.com/5121465/97031453-ebdc7900-1525-11eb-863d-53043f391f71.png)
Setup tasks only - Setup card can't be collapased (can be dismissed.) 

In the case there are orders that come in while the setup tasks are still incomplete the orders would show below the setup task card.

![Home - Setup tasks with orders](https://user-images.githubusercontent.com/5121465/97031806-71f8bf80-1526-11eb-9fa6-431ddf0d109a.png)
Setup tasks with orders. 

![Home - All agenda items - Orders expanded](https://user-images.githubusercontent.com/5121465/97031467-f5fe7780-1525-11eb-9d4d-8985feaf07e7.png)
Orders expanded with other task types collapsed

![Home - All agenda items](https://user-images.githubusercontent.com/5121465/97030054-df572100-1523-11eb-85f0-18d62e8efd27.png)
All agenda items collapsed

After reading through #5242 it sounds like extensibility of the task list will come later, so I won't go into that here.

**Comment by elizaan36** [comment]
Just to cover all the bases, I'm dropping a link to a comment where I shared the latest Orders panel design (with updated order status indicator.) https://github.com/woocommerce/woocommerce-admin/issues/5238#issuecomment-718954046

![Home - Orders expanded](https://user-images.githubusercontent.com/5121465/97907173-7c773e00-1d0a-11eb-9790-3f22d2afdc58.png)
