### ISSUE TITLE
Home Screen - reorganize Store Management section

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5244]
**Description:** we're going to reorganize the store management areas in different categories, making it easier for users to find the shortcut that they want to access

![Captura de ecrã 2020-10-01, às 15.18.41.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/0ae2f276-1d1b-4e24-aeff-7cd369609891)

**Acceptance criteria:**
- [ ] The Marketing & Merchandising category is going to include the following shortcuts: Marketing, Add Products, Personalize my Store, View my Store
- [ ] The Settings category is going to include the following shortcuts: Store Details, Payments, Tax, Shipping
- [ ] The Get Support shortcut is going to be included in the Help panel that's going to be added to the home screen
- [ ] In the new single-column layout, the Store management card should expand to 2 columns.

**Event tracking:**
NA

**Additional links:**
[P2 with links to the Figma file](pbIJXs-ma-p2)

**Comment by elizaan36** [comment]
Note that in the new single-column layout, the Store management card expands to 2 columns.

![Home - 1col setup tasks, stats empty state.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/5b57eced-78b8-4472-b4c6-b26256eae3ab)

So the organization of the card remains the same and section headers are still aligned left. The only change is that the links are distributed to 2 columns. This is in the Home Screen 2.0 Figma on the i9 page.

**Comment by samueljseay** [comment]
@elizaan36 I was just wondering do we have hover, focus, active states for the link items? What we have right now is using an existing component that has a hover state with a grey background for example, just keen to know the desired direction here.

**Comment by elizaan36** [comment]
hey @samueljseay thanks for clarifying this. Let's use the existing hover/focus/active states in the store management list components. That's the grey background on hover, and the blue outline for the focus/active states. These are aligned with the analytics components on the Home screen so would be worthwhile to take a holistic look if we wanted to change them eventually.

![image](https://user-images.githubusercontent.com/5121465/97211178-a372c480-178c-11eb-8a99-42ef7799cb6f.png)
