### ISSUE TITLE
Home Screen - store management extensibility

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5245]
**User story:**
As a 3PD
I want to easily extend the store management section
So I can add useful shortcuts to my extension

**Description:** our goal is to allow 3PDs to add store management shortcuts to their extensions

**Acceptance criteria:**
~~We have two options:~~

Let's go with the easiest path

- [ ] Allow them to add shortcuts to a new store management category called "Extensions"
~~- [ ] Allow them to add shortcuts to the existing categories (eg Settings). This will also require to implement a predefined list of categories so they're not limited to the existing categories~~

~~There's also a 3rd option, which is allowing them to create categories, but this one can easily get out of control. IE creating categories with different names for similar use cases.~~
**Event tracking:**
NA

**Additional links:**
[P2 with links to the Figma file](pbIJXs-ma-p2)

**Comment by samueljseay** [comment]
@pmcpinto currently our fixed list of store management links does include an external link. What do you think about *not* allowing external links here? Taking people away from their store to somewhere else is sometimes distracting, not always wanted and a way to spam users with unsolicited links, so my feeling is that we should not allow it.

**Comment by samueljseay** [comment]
As for what option we should choose I think we should lock in this one: " Allow them to add shortcuts to a new store management category called "Extensions"

Reasons:

1. Its simpler to implement
2. having a predefined set of categories locks us in future if we ever want to remove some then some store management links of 3dps will stop working, if we have a fixed category we don't need to worry about backwards compatibility as much.
3. I do however think we should design our API for this in a way that would allow to include a custom category feature in future.

**Comment by pmcpinto** [comment]
@samueljseay here's my feedback:

> @pmcpinto currently our fixed list of store management links does include an external link. What do you think about not allowing external links here? Taking people away from their store to somewhere else is sometimes distracting, not always wanted and a way to spam users with unsolicited links, so my feeling is that we should not allow it.

Yep that seems to be a great move to avoid folks from abusing from this area.

> As for what option we should choose I think we should lock in this one: " Allow them to add shortcuts to a new store management category called "Extensions"

Thanks for outlining your reasons 💯 . They all make sense to me, so let's keep them under "Extensions". In the future we can evaluate what you mentioned in the 3rd point, once we ship this and get feedback from the community.

**Comment by pmcpinto** [comment]
@samueljseay I think it could be useful to say something about extending the store management section in the post about the task list extensibility. What do you think?

**Comment by samueljseay** [comment]
@pmcpinto yes good point thanks for raising that. I'll have a look at writing something up
