### ISSUE TITLE
Home Screen - Help Panel

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5246]
**User story:**
As a merchant
I want to access more information about the home screen
So I can know what to expect from each feature 

**Description:** we're going to reuse the Help panel component in the home screen, as a way to allow the user to easily access more information about the home screen features

![home-help.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/6e757aee-bd8f-4f60-9f25-364a535a8b44)

**Acceptance criteria:**
- [ ] Include a Help panel in the Home screen navbar
- [ ] The panel should include the following links:
  Get Support: https://woocommerce.com/my-account/create-a-ticket/ (Core) and https://wordpress.com/help (eComm users)
  Rest of the links TBD

**Event tracking:**
Can we reuse the existing help panel tracking?

**Additional links:**
[P2 with links to the Figma file](pbIJXs-ma-p2)

**Comment by elizaan36** [comment]
Here's a help panel update with the correct Material icons and no search.

![Home - Help panel open .png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/00a9b463-0e4d-456d-8103-c7426452e2d0)

Added the link to the Store details wizard based on a conversation with @pmcpinto 
Besides "Get support", other Help links are still TBD.

**Comment by pmcpinto** [comment]
Here it goes the list of links that I think that we should include:

Home Screen: https://docs.woocommerce.com/document/home-screen
Inbox: https://docs.woocommerce.com/document/home-screen/#section-1
Stats Overview: https://docs.woocommerce.com/document/home-screen/#section-2
Store Management: https://docs.woocommerce.com/document/home-screen/#section-3
Store Setup Checklist: https://docs.woocommerce.com/document/woocommerce-setup-wizard/#section-9
