### ISSUE TITLE
Home Screen: remove Inbox read styling

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5247]
**Description:** the read / unread Inbox notification styling can be confusing and we don't have a way to identify if a notification was read by a user on the home screen.

**Acceptance criteria:**
- [ ] Remove the read styling from the inbox notifications

**Event tracking:**
NA

**Comment by samueljseay** [comment]
> Ideally we should add a visual cue (eg a new label) so the user can identify if there's a new message. The visual cue could be displayed only when a message is loaded for the first time in the home screen (tbd)

@pmcpinto do we have any further detail on this one yet? Would you like to remove the styling for now and defer to a new issue to handle the new visual cue when we have a design for it?

**Comment by pmcpinto** [comment]
> @pmcpinto do we have any further detail on this one yet? Would you like to remove the styling for now and defer to a new issue to handle the new visual cue when we have a design for it?

@samueljseay let's remove the read styling and in the future evaluate the visual cue, as I don't want to slow down the team with this. I removed that from the AC
