### ISSUE TITLE
Onboarding - tax task completed by default: missing inbox message

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5258]
**Describe the bug**
According to #4594 an inbox message should be triggered when the Tax task is completed by default, asking the user to confirm the settings

**To Reproduce**

1. Install WC 4.6 RC1
2. Complete the Store Profiler, including the connection to Jetpack
3. Go to the home screen and see the Tax task automatically completed
4. See that it's missing the inbox message suggesting to review the settings

**Expected behavior**
See the inbox message suggesting to review the settings when I reach the home screen with the Tax task automatically completed

**Screenshots**
https://d.pr/i/3fC833

**Comment by timmyc** [comment]
@pmcpinto I _think_ I might have experienced this myself when testing too. But upon a page refresh the tax note was indeed shown. I don't think it appears right away. Curious if you still have access to the test site to verify and/or try again and wait a bit to see if the note does appear eventually.

**Comment by becdetat** [comment]
> upon a page refresh the tax note was indeed shown

@timmyc this is very strange because @samueljseay and I both couldn't see the note - Sam did the original work and missed doing the note and I've just implemented it in #5279.

**Comment by pmcpinto** [comment]
> Curious if you still have access to the test site to verify and/or try again and wait a bit to see if the note does appear eventually.

Yep, I just checked again and this notification wasn't triggered. I can provide you the access to this JN site.
