### ISSUE TITLE
Customer Effort Score

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5259]
**Description:** Evaluating the health of the core store management features will help us understand if each feature is creating the expected value and prioritize which ones should be improved. It will allow us to compare the scores before and after making improvements in a specific feature.

**Acceptance criteria:**
- [ ] Trigger an in-product message to collect feedback from the user after he finishes a specific task (design tbd)
- [ ] Trigger it once per store in the same feature, avoiding overwhelming them with the same survey every time they complete the same task
- [ ] Trigger the survey in the following tasks:
Add a product (`wcadmin_product_add_publish`)
Update product (`wcadmin_product_update`)
Edit order (any of the edit order events)
Change setting (`wcadmin_settings_change`)
Filter analytics (any action on the analytics reports)
* ping me to get the events list for edit order and filter analytics

- [ ] Only target users with usage tracking enabled
- [ ] Collect the feedback using tracks
- [ ] Build the prompt as a separate package so it can be reused by other teams (see discussion here: pbIJXs-m0-p2#comment-890)
- [ ] The comments text field appears and is required only if Very difficult or Somewhat difficult is selected, and the comment will be recorded alongside the effort score.
- [ ] (nice to have for v1) abstract the data collection so it can use different collection targets

**Event tracking:**

Event: `wcadmin_ces_view`
Prop: `action` (action that triggered the survey – eg: wcadmin_product_add_publish)

Event: `wcadmin_ces_feedback`
Props:
`action` (action that triggered the survey – eg: wcadmin_product_add_publish)
`score`: [1-5]
`store_age`: [months]
`product_number`: [number of products]
`order_number`: [number of orders]

Event: `wcadmin_ces_snackbar_view`
Prop: `action` (action that triggered the survey – eg: wcadmin_product_add_publish)

Event: `wcadmin_ces_snackbar_click`
Prop: `action` (provide_feedback or dismiss)

**Additional links:** 
[Project Thread](pbIJXs-m0-p2)
[Final design](pbIJXs-px-p2)

**Comment by pmcpinto** [comment]
@becdetat @adrianduffell I added this to the AC:
> - [ ] The comments text field appears and is required only if Very difficult or Somewhat difficult is selected, and the comment will be recorded alongside the effort score

I'm still evaluating with Elizabeth if it should be required or optional. Feel free to give your feedback :)

**Comment by elizaan36** [comment]
> I'm still evaluating with Elizabeth if it should be required or optional.
It's ok if the Comments field for Very difficult or Somewhat difficult is optional. 

Some more notes on when the prompt will appear/not appear to ensure a good experience (we may have these sorted already but just in case):
- If the prompt is dismissed for a feature, it won’t appear again for that feature but can be shown for the others.
- If the merchant provides feedback, the prompt for that feature won’t appear again for their store.
- If the prompt is ignored, it won’t persist when the merchant navigates away or refreshes the page. (Since the regular snackbar component fades after a few seconds, had to mention this since this adaptation of that component must be dismissed by the merchant in order to be removed.)
- If the prompt is ignored it will appear again the next time the merchant completes that feature (and will appear for that feature until dismissed or feedback provided.)

**Comment by elizaan36** [comment]
Also wanted to post the modal design from the i2 here, which would impact #5337.

![CES modal](https://user-images.githubusercontent.com/5121465/97049277-12f47400-1541-11eb-9776-962b22e90c6f.gif)

Upon clicking "Give feedback" from the CES prompt, the modal appears with the emoji scale. Each emoji/label pair shows a light blue background on hover and active. The core modal component can be used here.

![Frame 40](https://user-images.githubusercontent.com/5121465/97049617-a0d05f00-1541-11eb-89ee-c5398bd1914a.png)
The optional comments text field appears only if Very difficult or Somewhat difficult is selected, and the comment will be recorded alongside the effort score.

![Frame 48](https://user-images.githubusercontent.com/5121465/97049673-bc3b6a00-1541-11eb-9a2d-add7eaa9b270.png)
If Neutral, Somewhat easy, or Very easy is selected, the comments field will not show and the effort score will be recorded on its own.

The comments field does not appear on hover.

The "Thank you for your feedback!" snackbar after submitting the feedback would fade like the normal snackbar component.
