### ISSUE TITLE
[WC 4.6 RC1] Task List - Browser back button during Extensions or WC Payments tasks marks some tasks incomplete

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-admin#5261]
**Describe the bug**
Using the browser back button during `Purchase & install extension` or `Set up WooCommerce Payments` tasks will change completed `Personalize my store` or `Set up payments` tasks to incomplete. 

**To Reproduce**

1. Create a brand new test site and upload WC 4.6 RC1.
2. Go through Onboarding Wizard
3. On `Product Types` select one or more paid extensions
4. Finish Wizard and arrive on Home screen
5. Complete `Personalize my store` task, observe task list shows it as complete.
6. If applicable complete `Set up payments` task (if you have `Set up WooCommerce Payments` task ignore this step), observe task list shows it as complete.
7. Open `Purchase & install extension` task
8. Use browser back button while on `woocommerce.com/cart` page
9. `Personalize my store` task (and if applicable `Set up payments` task) have changed to incomplete.
10. Refresh page and tasks will switch back to complete.
11. If applicable open `Set up WooCommerce Payments` task.
12. Use browser back button while on `wordpress.com` page
13. `Personalize my store` task has changed to incomplete.
14. Refresh page and `Personalize my store` task will switch back to complete.

**Expected behavior**
Completed tasks stay marked complete.

**Screenshots**
![Screenshot_2020-10-02_at_21_26_14](https://user-images.githubusercontent.com/24649833/94967773-a95fe780-04f7-11eb-8db7-73c458d6b74c.png)
![Screenshot_2020-10-02_at_21_26_29](https://user-images.githubusercontent.com/24649833/94967781-ac5ad800-04f7-11eb-9359-55d9de4f85c0.png)
![Screenshot_2020-10-02_at_21_26_39](https://user-images.githubusercontent.com/24649833/94967789-b086f580-04f7-11eb-92f0-1b1f7e88fb34.png)

If you have `Set up WooCommerce Payments`
![Screenshot_2020-10-02_at_21_24_09](https://user-images.githubusercontent.com/24649833/94967818-bbda2100-04f7-11eb-8784-6df2d4291a2e.png)
![Screenshot_2020-10-02_at_21_25_07](https://user-images.githubusercontent.com/24649833/94967826-bed51180-04f7-11eb-9ee8-af934334ac07.png)
![Screenshot_2020-10-02_at_21_24_45](https://user-images.githubusercontent.com/24649833/94967830-c1d00200-04f7-11eb-98ba-c5339d0e5d0a.png)

**Desktop (please complete the following information):**

OS: macOS 
Browser: Chrome

**Comment by timmyc** [comment]
Interesting find @tammullen - I agree this is not optimal, seems like a stale state of site option values is not being properly refreshed upon hitting the back button in both scenarios... since the problem is remedied with a hard refresh of the page. I'll drop this in the 1.6 milestone, though I imagine the same bug exists in prior versions of WooCommerce. This doesn't feel like a critical bug so not certain if we will try and implement a fix prior to 1.6/4.6 final or not.
