### ISSUE TITLE
[WC 4.6 RC1] Home Screen: WC Services Inbox Card name needs to be updated

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5262]
**Describe the bug**

WooCommerce Services Home Screen Inbox Card name needs to be updated from `WooCommerce Services` to `WooCommerce Shipping & Tax`. We already use the new name in the onboarding but the Inbox card reflects the old name:

Onboarding - where we use the new correct name - `WooCommerce Shipping & Tax`:

![shipping tax](https://user-images.githubusercontent.com/19143190/94969798-5c691a80-04d1-11eb-8364-044949cec3b7.jpg)

Inbox card - where we use the old incorrect name - `WooCommerce Services`:

![WC services card](https://user-images.githubusercontent.com/19143190/94969816-6428bf00-04d1-11eb-821f-cda27cda1ec6.jpg)

**To Reproduce**

1. Complete OBW on the new site and note the name of `WooCommerce Shipping & Tax` on the `Tell us about your business` page. 
2. Once your are on the Home Screen, note that the Inbox Card related to `WooCommerce Shipping & Tax` still says `WooCommerce Services`. 

**Expected behavior**

I expected the WooCommerce Services Home Screen Inbox Card name to match the name shown in the OBW which is `WooCommerce Shipping & Tax`. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

N/A

<hr>

 cc @pmcpinto

**Comment by timmyc** [comment]
Good catch @juliaamosova - this note is actually part of the remote inbox system and likely why it was missed in the updating of the WooCommerce Services verbiage.

Cool thing about this bug is we can fix independent of the release here: https://github.com/Automattic/woocommerce.com/blob/20947a3a232668ee6f1efe5c877e07ff3add502e/plugins/wccom-plugins/inbox-notifications/includes/notifications.json.php

**Comment by frosso** [comment]
Great catch, thanks for pointing it out! 💯

**Comment by jeffstieler** [comment]
@timmyc I'm admitted unfamiliar with the remote inbox code - will that WCCOM change update notes that have already been created on stores?

**Comment by timmyc** [comment]
> will that WCCOM change update notes that have already been created on stores?

I believe so, since the note name remains the same but cc @becdetat to confirm. But since the remote inbox is only enabled on ecomm sites, I don't think we should have many of these notes in the wild to be too concerned about. But I'm also just curious to know too.
