### ISSUE TITLE
[WC 4.6 RC1] `Connect to WP.com account` section is not shown at the end of onboarding

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5264]
**Describe the bug**

`Connect to WP.com account` section is not shown at the end of onboarding for the US store that installed free business features during onboarding. In WC 4.5.2, if the user enters the US address for the store during onboarding and installs all the recommended plugins (Jetpack, FB, Mailchimp etc), they will be presented with the flow to connect to WP.com account before they get to the Home Screen:

![dotcom](https://user-images.githubusercontent.com/19143190/94975277-2f236900-04df-11eb-9984-066f1bf2d724.jpg)

In WC 4.6 RC1, the user is not presented with that flow. Instead, they are redirected to the Home Screen right away. 

**To Reproduce**

1. Create a new site. 
2. Start onboarding and enter the US address for the store location. 
3. Select to install free business features (Jetpack, FB, Mailchimp etc).
4. On the Themes page, select to continue using an existing theme. 
5. Observe that you are redirected to Home Screen (connection to WP.com account is not offered). 

**Expected behavior**

I expected to go through `Connect to WP.com account` flow after selecting the theme and before getting to the Home Screen. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

N/A. 

<hr>

cc @pmcpinto

**Comment by timmyc** [comment]
Interesting one - if I had to venture a guess here, I'd imagine that the bundle install isn't populating something in the profile data that is causing [this jetpack connection logic](https://github.com/woocommerce/woocommerce-admin/blob/main/client/profile-wizard/index.js#L222-L225) to eval false, and thus skipping the connection step.

I do wonder though, would it be an abrupt flow to fix this without something similar to the benefits page being shown?

So the flow on the bundle install would be, plugins are installed as a bundle, then the user is shown the theme step. After hitting the theme step, the are then redirected to WordPress.com to create an account and connect Jetpack.

The benefits step kind of preps the user for that flow a bit better imho:

<img width="872" alt="Setup Wizard ‹ WooCommerce ‹ Hurt Nightingale — WooCommerce 2020-10-06 16-22-33" src="https://user-images.githubusercontent.com/22080/95271182-17efbe80-07f2-11eb-9d29-994ddc768e47.png">

If the user doesn't read the fine print on the benefits step ( even the tooltip window doesn't give a great amount of details about Jetpack or benefits ) they might not have any idea what Jetpack is:

<img width="541" alt="Setup Wizard ‹ WooCommerce ‹ Hurt Nightingale — WooCommerce 2020-10-06 16-22-55" src="https://user-images.githubusercontent.com/22080/95271228-30f86f80-07f2-11eb-86ac-952569976139.png">

I also just confirmed that this behavior already exists in 1.5/4.5 so this isn't a regression in 1.6 of WooCommerce Admin, rather working as designed currently.

My .02 is we consider leaving as-is for right now, and with the OBW changes slated for the next cycle, introduce a new "benefits-like" step which informs the user of the connection that is about to take place.

**Comment by timmyc** [comment]
Removing the high priority label, as I mentioned this is already the released behavior and not a regression.

**Comment by timmyc** [comment]
Just adding a bit of context to the removal from the milestone - @pmcpinto and I discussed this further in our 1:1 today and we have opted to remove from the 1.6 milestone because:

- It is not a regression, rather behavior introduced in 1.5/4.5
- While the original acceptance criteria for the bundle install asked for the JP connection to still happen, it was missed in review and was not flagged as a bug in 1.5/4.5
- Implementing a change right now could lead to other regressions so late in the release cycle
- This flow only impacts a small percentage of users because it is a targeted test for the Fashion industry only
- We have planned changes in the next sprint cycle to update the "Bundled" extension experience, and we can work on smoothing out this flow then.
