### ISSUE TITLE
WooCommerce Admin Customers not including Name / Link to user when order is entered manually 

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce-admin#5270]
Hi Woo team,

I've noticed in WP Admin > WooCommerce >Customers, the column for "Customer Name" which also includes the link to the WP User account is empty for orders which were created manually in WP Admin.

I've checked the manually created orders in WP Admin > WooCommerce > Orders > Edit Order; and the customer account is linked, in the dropdown the correct user account was selected. 

Error: Orders which are created manually in WP Admin don't populate the "first_name" and "last_name" columns in "dfs_wc_customer_lookup" table; even though the user was chosen from the user dropdown selection. 

Here is how a DB entry for a manually created order looks like (real example but personal data replaced with dummy data): 

```
INSERT` INTO `dfs_wc_customer_lookup` (`customer_id`, `user_id`, `username`, `first_name`, `last_name`, `email`, `date_last_active`, `date_registered`, `country`, `postcode`, `city`, `state`) 
VALUES (4605, 85425, 'USER', '', '', 'user@example.com', '2020-09-22 23:00:00', '2020-09-23 09:59:08', 'COUNTRY', 'POSTCODE', 'CITY', `'');
```

"user_id is correct"; but "first_name" and "last_name" are empty

This in turn means that the "WooCommerce > Customers" table cannot display the Customer Name & link to the User profile. And this the also means that any search on the customer's name returns an empty result. 

with kind regards, Edith

**Comment by pmcpinto** [comment]
hey @jconroy 👋 I think that the Customers area is being managed by Grow, right?

**Comment by jconroy** [comment]
Hey @pmcpinto 👋 ...sure 😄 I think this would be the first time we've looked at it.

**Comment by EdithAllison** [comment]
I can confirm this is still an issue. Tested on WooCommerce 4.9.2.
