### ISSUE TITLE
Help Panel - switch to a question mark icon

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5272]
We're going to use a question mark icon in the Help Panel instead of the safety ring as it's universally recognizable.

[https://app.zenhub.com/files/128732084/bcc88b3a-f598-4162-9fda-cf1c87ccfbfa/download](https://app.zenhub.com/files/128732084/bcc88b3a-f598-4162-9fda-cf1c87ccfbfa/download)

**Comment by pmcpinto** [comment]
@elizaan36 should we use the square or circle version?

**Comment by elizaan36** [comment]
Thanks @pmcpinto for getting these! Yeah, I think the circular version of the Help icon will work well. And it's fine even if we use the square layout icon adjacent.

**Comment by elizaan36** [comment]
hey, I'm sharing the correct version of the icons here. The stroke on the previous ones was a little too thin.
[new display and help icons.zip](https://github.com/woocommerce/woocommerce-admin/files/5373705/new.display.and.help.icons.zip)

Wanted to also mention the issue of allowing the container around the icon/label to expand based on the number of characters in the label.

In English:
<img width="328" alt="Screen Shot 2020-10-13 at 2 32 17 PM" src="https://user-images.githubusercontent.com/5121465/95907716-9653df80-0d61-11eb-837d-56e44a1fba58.png">

Example of what it would look like in Nahuatl:
<img width="288" alt="Screen Shot 2020-10-13 at 2 28 27 PM" src="https://user-images.githubusercontent.com/5121465/95907744-a370ce80-0d61-11eb-8ea4-b8b36e6a30fb.png">

So the icon stays vertically centered with the text, and the margin between the two icon/label containers remains constant.

**Comment by elizaan36** [comment]
Here are the correct icons to use for the display and Help links in the app bar - good old Material.

[home screen icons.zip](https://github.com/woocommerce/woocommerce-admin/files/5431346/home.screen.icons.zip)

**Comment by elizaan36** [comment]
@pmcpinto should this be labeled Home screen rather than onboarding?

**Comment by elizaan36** [comment]
I was going to update this issue with new icons but just saw that #5429 was merged already and the display icon looks fine there. In that case, we should probably use the Help icon from the same set above.

**Comment by louwie17** [comment]
@elizaan36 & @pmcpinto as part of #5246 I switched the help icon to use the @wordpress/icons [help icon](https://github.com/WordPress/gutenberg/blob/master/packages/icons/src/library/help.js) would we want to keep that icon or replace with the above?
<img width="69" alt="Screen Shot 2020-11-18 at 2 03 18 PM" src="https://user-images.githubusercontent.com/2240960/99570077-ce28f500-29a7-11eb-8d35-8f5a1b2023ec.png">

**Comment by elizaan36** [comment]
Good call switching to the @wordpress/icons, @louwie17! No need to replace.

**Comment by octaedro** [comment]
It seems that this issue was solved in the [PR 5538](https://github.com/woocommerce/woocommerce-admin/pull/5538) so I'll close it.
