### ISSUE TITLE
Store Profiler - include Creative Mail as a free extension

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5288]
**Description:** we'll need to start including Creative Mail as one of the free extensions that are promoted in the Store Profiler: https://wordpress.org/plugins/creative-mail-by-constant-contact/

**Acceptance Criteria:**
- [x] Include it in the main flow: https://d.pr/i/vV0S93
- [ ] Include in the one-click experiment #4579
- [ ] Include in the new experiment #5287
- [ ] Copy:
**Email marketing for WooCommerce with Creative Mail**
Create on-brand store campaigns, fast email promotions
and customer retargeting with Creative Mail.

**Additional Links:**
[Company logo
](https://drive.google.com/drive/folders/1GYEJenOlI4J4N9rWh0r0cfkdLvDvuuzj)

**Comment by joelclimbsthings** [comment]
Note that this will be broken into three separate PR's, with the priority being in the order that they're listed above.

**Comment by pmcpinto** [comment]
Hey @joelclimbsthings for the 1.7 release we'll only need to include it in the main flow: https://d.pr/i/vV0S93

Let me see if I can get the final copy today

**Comment by pmcpinto** [comment]
@joelclimbsthings here's the copy:

**Email marketing for WooCommerce with Creative Mail**
Create on-brand store campaigns, fast email promotions
and customer retargeting with Creative Mail.

**Comment by joelclimbsthings** [comment]
Note that this will be broken into three separate PR's, with the priority being in the order that they're listed above.

**Comment by joelclimbsthings** [comment]
Issue was autoclosed by PR, reopened for remaining tasks.

**Comment by timmyc** [comment]
Since we have delivered the targeted functionality for 1.7, i'm going to remove this from the milestone. Let me know if that works for you @pmcpinto

**Comment by joelclimbsthings** [comment]
For the oneclick & new experiments, should the copy resemble the one already provided @pmcpinto ? What exactly should it be?

Here's the onclick popover as it appears now:

![image](https://user-images.githubusercontent.com/444632/98744868-51729700-2367-11eb-9b84-d253226d5d91.png)

**Comment by pmcpinto** [comment]
@joelclimbsthings as I mention here, we don't need to include it in the flow that you mentioned:

> Hey @joelclimbsthings for the 1.7 release we'll only need to include it in the main flow: https://d.pr/i/vV0S93

**Comment by joelclimbsthings** [comment]
Hey @pmcpinto , understood. I actually just meant for further development outside of the release.

**Comment by pmcpinto** [comment]
I'm closing this issue, as Creative Mail was included in the Marketing task
