### ISSUE TITLE
Store Profiler - simplify usage tracking modal

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5294]
**Description:** we aim to streamline the usage tracking modal be removing one step if the user wants to opt-in to usage tracking

**Acceptance criteria:**
- [ ] Instead of having the users clicking `Yes, count me in!` and then `Continue` we should display two CTA: 
`No thanks` the user moves forward without opting-in for usage tracking
`Yes, count me in!` the user moves forward agreeing to share the usage tracking data

https://d.pr/i/Mv0VvA

**Event tracking:**
This shouldn't change the logic that we already have in place

**Comment by octaedro** [comment]
Hi @vbelolapotkov,
I assigned this issue to you since I understand the [PR 5248](https://github.com/woocommerce/woocommerce-admin/pull/5248) will solve it.
