### ISSUE TITLE
Task List: shipping task smart default: add exceptions

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5298]
According to the original issue (#4595), the shipping task should only be marked as completed if the user has JP and WCS installed and connected. Currently the task is being marked as completed even if the user doesn't have JP connected.

In addition, we have a partnership with Shipstation in Australia, Canada and United Kingdom where we display the prompt to install the extension in the Shipping step. It's necessary to add an exception to not mark it as completed in those countries.

**Comment by pmcpinto** [comment]
@becdetat @timmyc there's one thing that needs to be fixed here:

It seems that the logic is excluding AU, NZ, or UK but it should be Australia, Canada and United Kingdom

See the issue description:
> In addition, we have a partnership with Shipstation in Australia, Canada and United Kingdom

**Comment by becdetat** [comment]
Oh no, sorry I had NZ on my mind. I'll fix this ASAP.

**Comment by pmcpinto** [comment]
I'm going to close this one
