### ISSUE TITLE
Add your first product: email notification

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5300]
**User story:**
As a merchant
I want to have access to insightful content when I enter WooCommerce
So I can create and manage my store more effectively

**Description:** email can be a powerful tool to guide users and bring them back to the store setup flow. We want to validate this assumption by test sending an email notification to new users who haven't added products.

**Acceptance criteria:**
- [ ] Send an email notification to new users without any product in the 3rd day after the store creation (content TBD)
- [ ] The email CTA should redirect users to the Add Products task: wp-admin/admin.php?page=wc-admin&task=products
- [ ] Users should be able to disable this email notification on WooCommerce > Settings > Emails
Email title: Store setup
Email description: Store setup emails are sent to chosen recipient(s) with additional guidance to complete the basic store setup

**Event tracking:**
We should be able to track the following numbers:
Emails sent
Opened Emails
Emails clicked

**Comment by octaedro** [comment]
Hi @pmcpinto,
I have a few questions I'd like to ask:

> Send an email notification to new users without any product in the 3rd day after the store creation (content TBD)

Do we have a specific text and design for this?

> We should be able to track the following numbers:
...
Opened Emails

AFAIK this is possible but the method to do it is not very reliable. The way to do it is by sending a small image at the end of the email with the following structure: `<img src='http://www.domain.com/[url_to_record_the_event].php>`. Calling that API endpoint we'll know who opened the email but if the user has the images turned off by default we won't be able to track it.
Does that method work for you?

**Comment by pmcpinto** [comment]
> Do we have a specific text and design for this?
@elizaan36 I think that we could take advantage of the existing email templates instead of creating something better for an initial release. WDYT?

@octaedro what's the amount of effort required to implement this email notification?

**Comment by elizaan36** [comment]
Yes, let's use the core email notification template for now. I'll explore some ideas this week.

**Comment by octaedro** [comment]
Hi @pmcpinto,
I'm working on that and I think it will be done in a week.

I'm creating a new `Note` type `email` that will be pretty similar to the other notes but with the expected behavior described in this issue. That will give us the possibility to create new notifications also remotely.

**Comment by pmcpinto** [comment]
Thanks for the heads up. Let me know if you have questions

**Comment by octaedro** [comment]
Hi @pmcpinto,

I'm working on the email notifications configuration (under `WooCommerce > Settings > Emails`). Now that we're extending the inbox notification (and some can now be sent by email), what do you think about adding a new subtitle like `Email insights` and a checkbox to turn them on/off instead of adding the other setting under the `Email notifications`?

This type of notification is new, and maybe it would be worth underlining it to make the setting more visible.

Currently in `WooCommerce > Settings > Emails` we have 3 section titles: `Email notifications`, `Email sender options` and `Email template`. I would like to add another one named `Email insights` that would look like this:

![screenshot-one wordpress test-2020 12 21-13_44_09](https://user-images.githubusercontent.com/1314156/102800469-ace66a80-4392-11eb-995e-26a720662a1f.png)

**Comment by pmcpinto** [comment]
good idea. I think that could work well, but probably we need to be more specific in the title and description, so people don't think that we're going to spam them with marketing stuff.

Eg: 
Title: Store management insights
Description: Receive email notifications with additional guidance to complete the basic store setup and....

@elizaan36 what do you think?

**Comment by octaedro** [comment]
Hi @pmcpinto,
I wanted to ask you:
- Just to confirm, is it ok if the notification configuration looks like this:
![screenshot-one wordpress test-2020 12 28-12_06_58](https://user-images.githubusercontent.com/1314156/103229926-dc592200-4912-11eb-84a4-fbc443d46c5f.png)

- Also, I couldn't find the notification text. Should it say something like the ["Do you need help with adding your first product?" note](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/FirstProduct.php#L70)?

**Comment by pmcpinto** [comment]
> Just to confirm, is it ok if the notification configuration looks like this:

👍 

> Also, I couldn't find the notification text. Should it say something like the "Do you need help with adding your first product?" note?

IIRC @elizaan36 was going to take a look at this. Elizabeth, do you have time this week? Thanks

**Comment by elizaan36** [comment]
Here's a possible design for the store setup email.

![store setup email](https://user-images.githubusercontent.com/5121465/103315655-d84d0300-49eb-11eb-908d-7ff6fce46cd4.png)

Header: Store setup
[Illustration]
Body: Nice one, you’ve created a WooCommerce store! Now it’s time to add your first product.

There are three ways to add your products: you can create products manually, import them at once via CSV file, or migrate them from another service. 

[Explore our docs](https://docs.woocommerce.com/document/managing-products/?utm_source=help_panel) for more information, or just get started!

[Add a product]

--------

The notification configuration looks good to me too but I'd remove the `.` period at the end of the sentence.

**Comment by octaedro** [comment]
Hi @elizaan36,

> The notification configuration looks good to me too but I'd remove the `.` period at the end of the sentence.

Good idea!

Also, I wanted to ask, the dominant color by default in `WooCommerce` emails is plum but this is blue. Is the plan to keep the default color (plum) for the WC emails and only use the blue for the `merchant email notes`?

**Comment by octaedro** [comment]
Hey @elizaan36,

> ~~Also, I wanted to ask, the dominant color by default in WooCommerce emails is plum but this is blue. Is the plan to keep the default color (plum) for the WC emails and only use the blue for the merchant email notes?~~

Forget this, I realized that this is something configurable, so it will be configured by the user.
Thanks 🙂
