### ISSUE TITLE
Navigation: Match styles including mobile

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5326]
Figma files: https://www.figma.com/proto/QNNc834dBBNz1bL2qc9VZyq5/Navigation-experimental?node-id=2096%3A133298&viewport=-13770%2C-6863%2C0.7375516295433044&scaling=scale-down

**Comment by joshuatf** [comment]
@psealock What should this issue cover?  I'm not seeing any other mobile styles that need to be added in the above Figma file.

**Comment by psealock** [comment]
@jameskoster Are there any designs for how this collapses and behaves on mobile? Or maybe @elizaan36 do you know?

**Comment by jameskoster** [comment]
All the nav mechanics should be the same. The only difference I can think of is around how the nav panel interacts with "the rest" of the screen. 

On desktop when opened the nav reduces the width of the canvas to accomodate it, and you can still interact with everything on the screen. On mobile there won't be enough space to interact with the canvas when the nav is open, so the nav panel should probably just "push" the canvas over (like the current mobile wp-admin nav), or simply slide over it (whichever is easier to implement). Clicking the canvas should then close the nav.

**Comment by psealock** [comment]
@joelclimbsthings, clicking the site icon in the top left will toggle the Navigation. As you can see, there's some z-index issues going on.

<img width="459" alt="Screen Shot 2020-10-23 at 3 36 04 PM" src="https://user-images.githubusercontent.com/1922453/96949927-91531500-1545-11eb-8743-66b72cde2998.png">

Closed, it should look like the screenshot below, but with the logo centered.

<img width="1047" alt="Screen Shot 2020-10-23 at 3 39 08 PM" src="https://user-images.githubusercontent.com/1922453/96950075-f73f9c80-1545-11eb-92c1-3f920c2a3dad.png">

I agree with Jay about the interaction of squishing v. pushing or overlapping when the screen is narrow. Let me know if that doesn't make sense. 

Also, I think the menu will be collapsed by default on mobile.

### Acceptance Criteria

Just to re-iterate and make more clear, here are the criteria for this issue:

* A closed menu will appear as a square with the site logo of size equal to the wc-admin header bar. 
* With the navigation closed, wc-admin or embedded pages occupy the entire screen width
* On screens [$break-large: 960px](https://github.com/WordPress/gutenberg/blob/b0a5e0680158bc6dc3ee6c6aeb0c1eaa1e290702/packages/base-styles/_breakpoints.scss#L9) or below toggling the navigation pushes or overlaps the content, whichever is better.
* At the same breakpoint as above, the Navigation is collapsed by default.

Do all these sound correct to you @jameskoster ?
