### ISSUE TITLE
Navigation: Add wc-admin links

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5328]
Extend Navigation by adding WC Admin links which are router-aware.

**Comment by psealock** [comment]
I'm not sure where you are with this one, but adding custom links via slotFill on my 3rd party plugin isn't working. For some reason `useSlot` isn't recognising the presence of a Fill, even thought it is there.

https://github.com/woocommerce/woocommerce-admin/blob/77e8ea177f1c3eb4a9b7eafa291142b11cd69099/client/navigation/components/Item/index.js#L11

I'm curious to know if you got this working internally @joshuatf. I'll dive deeper tomorrow.

**Comment by joshuatf** [comment]
@psealock I have not yet; encountered the same issue that you did.  I think I have all the pages registered, but slot/fill isn't working as expected.
