### ISSUE TITLE
New navigation - getting feedback

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5334]
**User story:**
As a merchant
I want to have a way to provide feedback about the new navigation
So I can easily contact the WooCommerce team when I spot any bugs or potential improvements

**Description:** considering that this is a significant change in the experience we're thinking about an easy way to allow users to provide timely feedback about the new navigation (bugs, improvements), in order to shorten the feedback cycle.

**Acceptance criteria:**
- [ ] TBD

**Event tracking:**
TBD

**Comment by pmcpinto** [comment]
Last week I spoke with @elizaan36 about this and for the initial release we can take advantage of the inbox panel and trigger a message with a link to Crowdsignal to get feedback. We can then evaluate if it makes sense to add something more prominent before releasing it for WC Core users. Elizabeth, are you ok with this approach?

@joshuatf when do you need the inbox message content and survey link?

**Comment by joshuatf** [comment]
@pmcpinto The sooner the better, but as long as we have a few days buffer before we release to implement and test it should be fine.

**Comment by elizaan36** [comment]
> for the initial release we can take advantage of the inbox panel and trigger a message with a link to Crowdsignal to get feedback. We can then evaluate if it makes sense to add something more prominent before releasing it for WC Core users. Elizabeth, are you ok with this approach?

Yep the Inbox message seems like a good approach for ecom plan users, but I have a suspicion we'll need a bigger announcement as we widen the audience.

**Comment by pmcpinto** [comment]
> @pmcpinto The sooner the better, but as long as we have a few days buffer before we release to implement and test it should be fine.

👍 We'll have the inbox content and survey link during next week

**Comment by elizaan36** [comment]
Here's copy for the Inbox message:

Headline: **You have early access to the new WooCommerce navigation - share your feedback**
Body: We're introducing the new navigation to a select group of store owners in this first phase and we'd like to hear your thoughts.
CTA: [[Share feedback](https://automattic.survey.fm/new-navigation)]

Here's the link to the Crowdsignal survey for the CTA: https://automattic.survey.fm/new-navigation

**Comment by pmcpinto** [comment]
@elizaan36 when do you think that the survey should be triggered? 5 days after they start using the new navigation?

**Comment by elizaan36** [comment]
I'm updating this thread based on a convo with @pmcpinto just now - let me know how this copy looks to you.

Two Inbox notifications for feedback on the new nav, linking to the same survey: 
1. Immediately upon rollout of the new navigation
2. 5 days after rollout

For 1: 
Headline: You now have access to the new WooCommerce navigation
Body: We're introducing the new WooCommerce navigation for a more intuitive and improved user experience. We'd like to hear your thoughts and first impressions.
CTA: [Share feedback] https://automattic.survey.fm/new-navigation

For 2:
Headline: Share your thoughts on the new navigation
Body: We recently introduced the new navigation for a more intuitive and improved user experience. Now that you've had some time to give it a try, let us know how this will impact your store.
CTA: [Share feedback] https://automattic.survey.fm/new-navigation
