### ISSUE TITLE
Customer effort score: tracks event for showing the CES snackbar/notice

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#5341]
Part of #5259

Track displaying the CES notice and modal:

- track names `wcadmin_ces_view`, `wcadmin_snackbar_view`, `wcadmin_snackbar_dismiss`
- properties:
    - `action` the action that triggered the CES modal

**Comment by mattsherman** [comment]
@becdetat Should we log a Tracks event when the snackbar is shown as well, or only when the CES modal is shown?

There could be value in at least logging if the snackbar is explicitly dismissed without showing the CES modal.

**Comment by becdetat** [comment]
The language used is a little confusing, during the design phase snackbar and modal were used interchangeably. This tracks event should be triggered when the snackbar is displayed. As @pmcpinto has [specified](https://github.com/woocommerce/woocommerce-admin/issues/5259) there's no tracks event for when the _modal_ is actually displayed or if the snackbar is dismissed. I agree there would be value in recording them.

Can you start on implementing them and we'll get Pedro's feedback before landing this?

**Comment by mattsherman** [comment]
Sure thing... I've already started on it.

**Comment by pmcpinto** [comment]
@becdetat @mattsherman my suggestion is to use `wcadmin_ces_view` and `wcadmin_ces_feedback` in the modal and create two new tracks for the snackbar: `wcadmin_ces_snackbar_view` and `wcadmin_ces_snackbar_click`

Sounds good? I updated the #5259 description with this and more details about the props of each event. Thanks

**Comment by mattsherman** [comment]
Thanks @pmcpinto -- sounds good.

**Comment by mattsherman** [comment]
@pmcpinto Thinking about this a bit more...

How about `wcadmin_ces_snackbar_view` with `action` set as for `wcadmin_ces_view`, and `wcadmin_ces_snackbar_dismiss` with `action` also set as the others? We don't really need to handle the case where the user clicks the snackbar to provide feedback, as that directly results in `wcadmin_ces_view`.

By keeping `action` values consistent with the other CES tracks events, we will be able to easily see if there are differences between dismissal of the snackbar for different actions.

**Comment by mattsherman** [comment]
I've implemented things as I proposed above in https://github.com/woocommerce/woocommerce-admin/pull/5648

If we need to change things, we always can.

**Comment by pmcpinto** [comment]
> How about wcadmin_ces_snackbar_view with action set as for wcadmin_ces_view, and wcadmin_ces_snackbar_dismiss with action also set as the others? We don't really need to handle the case where the user clicks the snackbar to provide feedback, as that directly results in wcadmin_ces_view.

👍 makes sense. Thanks for the suggestion
