### ISSUE TITLE
Is /wc-analytics/reports/** meant for public consumption?

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce-admin#5344]
I haven't seen these endpoints documented anywhere, but it's in our current live build of WC.

More specifically I need the categories report, which the old v3 endpoints didn't support. I was hoping it would be time to retire those old endpoints.

Hope anyone can clarify.

**Comment by timmyc** [comment]
@larssn thanks for reaching out with this question. So currently we consider the `/wc-analytics` namespace a "private" application-specific set of endpoints - thus no version number is attached to that namespace. The reason for that is we wanted to maintain some flexibility with the new Analytics system for us to modify the endpoints further after the feature was merged to WooCommerce core in 4.0.

The endpoints can obviously be used from any application though on/off a Woo install. For example, our WooCommerce native apps for iOS and Android both leverage these endpoints already. And we haven't been modifying the endpoints for quite some time now, so I feel they are relatively stable to build against.

The plan is to at some point in the future ( no timeline decided yet ) is to roll these endpoints into the standard versioned `wc/vx` namespace. At which point they would become final, and would no longer be modified outside of a new version being released.

So I think you are pretty safe to leverage the categories endpoint as it is right now, but until they are final and versioned, it might be advisable to keep an eye on our changelog to see if any REST API changes land. We don't have any planned work in the analytics area right now, so I personally feel they are quite stable.
