### ISSUE TITLE
Customer effort score: Trigger when updating a product

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#5346]
Part of #5259

Trigger the customer effort score modal when updating a product - on the existing `wcadmin_product_update` tracks event.

Copy should be `How easy was it to edit your product?`

**Comment by mattsherman** [comment]
@becdetat This has been in place for a while. I think we can close this, unless there is a detail that is still outstanding.

**Comment by becdetat** [comment]
Good catch, closed
