### ISSUE TITLE
[WC 4.6 RC2] Home Screen: WC Shipping & Tax Inbox Card button needs updated URL

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-admin#5354]
**Describe the bug**
The URL of the `Learn more` button links to https://docs.woocommerce.com/document/woocommerce-services/?utm_source=inbox which no longer exists

**To Reproduce**

1. Complete OBW
2. Once your are on the Home Screen, note that the Inbox Card related to WooCommerce Shipping & Tax the `Learn more` button links to https://docs.woocommerce.com/document/woocommerce-services/?utm_source=inbox which no longer exists

**Screenshots**

![Screenshot_2020-10-13_at_14_57_47](https://user-images.githubusercontent.com/24649833/95870981-0b74e400-0d65-11eb-833f-d81a6040ddc9.png)
![Screenshot 2020-10-13 at 14 57 38](https://user-images.githubusercontent.com/24649833/95870988-0d3ea780-0d65-11eb-84a4-8d73bac93ae5.png)

I believe the URL is set in the remote inbox https://github.com/Automattic/woocommerce.com/blob/20947a3a232668ee6f1efe5c877e07ff3add502e/plugins/wccom-plugins/inbox-notifications/includes/notifications.json.php

**Comment by tammullen** [comment]
Update: the docs page has just been updated to have 301 redirects so the URL now works via redirect but probably should still be updated

**Comment by timmyc** [comment]
@frosso heads up on this one, looks like one more change is needed for the remote inbox [action url](https://github.com/Automattic/woocommerce.com/blob/34298d5d263ff9dd64fbc403f71c9667b0d015c2/plugins/wccom-plugins/inbox-notifications/includes/notifications.json.php#L77) needs to be updated.

**Comment by frosso** [comment]
Thanks! I updated the URL in the notifications file: https://github.com/Automattic/woocommerce.com/pull/8717
