### ISSUE TITLE
[WC 4.6 RC2] `Continue Store Setup` button in Inbox after completing Setup Wizard

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-admin#5355]
**Describe the bug**
On a new ephemeral atomic store after completing the setup wizard there is an inbox card with a `Continue Store Setup` button which launches the wizard again. 

**To Reproduce**

1. On a new ephemeral atomic store (I haven't been able to reproduce yet on JN) complete the setup wizard for a US based store
2. When re-directed to `Home` after finishing the setup wizard check the inbox cards.
3. There is an inbox card with a `Continue Store Setup` button
4. Click the `Continue Store Setup` button and the setup wizard launches again
5. Click the `Skip setup store details` link
6. When re-directed to `Home` in addition to the inbox card with a `Continue Store Setup` button there is also now the `Continue Store Setup` button in the `Welcome to WooCommerce` banner.

**Expected behavior**
That inbox card won't appear after completing wizard

**Screenshots**
![Screenshot_2020-10-13_at_14_13_00](https://user-images.githubusercontent.com/24649833/95873652-082f2780-0d68-11eb-966d-b6cb2c6acf09.png)
![Screenshot_2020-10-13_at_14_13_16](https://user-images.githubusercontent.com/24649833/95873669-0d8c7200-0d68-11eb-9c5a-3c345499a48b.png)
![Screenshot_2020-10-13_at_15_13_57](https://user-images.githubusercontent.com/24649833/95873677-0feecc00-0d68-11eb-91a4-62eca0458a8c.png)

**Desktop (please complete the following information):**

* Mac OS & Chrome

**Comment by timmyc** [comment]
@pmcpinto we spoke about removing this inbox notification. Should we schedule that work for this cycle since it should be a pretty quick task.

**Comment by pmcpinto** [comment]
> @pmcpinto we spoke about removing this inbox notification. Should we schedule that work for this cycle since it should be a pretty quick task.

Sounds good to me. There's also a couple of additional messages that it would be good to remove during this cycle as well.

**Comment by dechov** [comment]
Came here to raise this same issue after just having noticed it (on WC 4.7 RC1). The note gets marked as actioned [[source](https://github.com/woocommerce/woocommerce-admin/blob/fe5efe63ce0a5befccf11f990f540adb42e66864/client/profile-wizard/index.js#L227-L232)] and therefore does go away after refresh – not sure whether there's currently a way to have it disappear straight away, short of maybe deleting it which doesn't seem ideal.

**Comment by timmyc** [comment]
Going to close this out because the note has been removed completely in https://github.com/woocommerce/woocommerce-admin/pull/5499
