### ISSUE TITLE
[WC 4.6 RC2] `Confirm tax settings` inbox card says Automated taxes enabled when they aren't.

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-admin#5356]
**Describe the bug**
During tax setup after connecting to WPCOM to enable automated taxes you are given a 2nd chance to confirm you want to enable automated taxes. If you select `No thanks` at that stage automated taxes are disabled but an inbox card appears saying they are enabled.

**To Reproduce**

1. On a new ephemeral atomic store complete the setup wizard for a US based store and install WC S&T
2. Follow the `Set up tax` task list item
3. Connect to WPCOM to enable automated taxes
4. On the `Good News` step select `No thanks, I'll configure taxes manually`
5. Add a tax rate
6. When re-directed to `Home`an inbox card appears which says `Automated tax calculations are enabled`
7. Click `Edit tax settings` on that card and see that automated taxes are disabled.

**Screenshots**
![Screenshot_2020-10-13_at_15_48_22](https://user-images.githubusercontent.com/24649833/95878014-a624f100-0d6c-11eb-8b82-7de9d1c2ec10.png)
![Screenshot 2020-10-13 at 15 48 55](https://user-images.githubusercontent.com/24649833/95878024-a9b87800-0d6c-11eb-96f4-8581f80b52e6.png)
![Screenshot_2020-10-13_at_15_34_06](https://user-images.githubusercontent.com/24649833/95878044-afae5900-0d6c-11eb-9955-30a2c39cb36a.png)
![Screenshot_2020-10-13_at_15_34_52](https://user-images.githubusercontent.com/24649833/95878055-b3da7680-0d6c-11eb-99d8-83716f3a7b5f.png)
![Screenshot_2020-10-13_at_15_35_12](https://user-images.githubusercontent.com/24649833/95878075-b9d05780-0d6c-11eb-9001-2f01d1e4f85c.png)
![Screenshot_2020-10-13_at_15_35_37](https://user-images.githubusercontent.com/24649833/95878099-bfc63880-0d6c-11eb-8336-81db78c31a5c.png)

**Desktop (please complete the following information):**

Mac OS and Chrome

**Comment by ilyasfoo** [comment]
Hello @pmcpinto ! What would be the expectation for this task, do you think it's better to remove the inbox card altogether if automated tax is disabled?

**Comment by pmcpinto** [comment]
Hey @ilyasfoo, yep I agree that the best option is to not display the inbox message

**Comment by ilyasfoo** [comment]
This issue will no longer be relevant due to revert in https://github.com/woocommerce/woocommerce-admin/pull/5720.

Existing users might still have the inbox card displayed but since it's only a small inconvenience I think it's fine to ignore that.
