### ISSUE TITLE
Convert the marketing tab cards to use the new @wordpress/components Card component.

### ISSUE THREAD

**Issue by jconroy** [woocommerce/woocommerce-admin#5374]
Investigate moving the [Marketing tab cards](https://github.com/woocommerce/woocommerce-admin/tree/main/client/marketing) over to using the @wordpress/components Card component.

Currently, we use the woo card component.

Woo -> https://github.com/woocommerce/woocommerce-admin/tree/main/packages/components/src/card
Wp -> https://github.com/WordPress/gutenberg/tree/master/packages/components/src/card

My understanding is the WP card component is newer and wc-admin is shifting towards using the WP card moving forward.

Some of the recent work in the homescreen uses the WP card component 

https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/stats-overview/index.js

**Comment by ecgan** [comment]
More details and visuals:

The current Woo Card components in Marketing tab (https://example.test/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing):

![Markup 2020-10-20 at 01 13 37](https://user-images.githubusercontent.com/417342/96489162-a7c14e00-1271-11eb-92a4-9360c5edd8f6.png)

The newer WP Card component used in WooCommerce Home tab (https://example.test/wp-admin/admin.php?page=wc-admin):

![Markup 2020-10-20 at 01 20 51](https://user-images.githubusercontent.com/417342/96489822-89a81d80-1272-11eb-8410-fa100d18bda1.png)
