### ISSUE TITLE
Implement fancy placeholders style loaders for Marketing Tab

### ISSUE THREAD

**Issue by jconroy** [woocommerce/woocommerce-admin#5375]
"Fancy" placeholders (well fancier than what we currently use on the Marketing tab) are used within various areas of wc-admin

By way of example, we mimic this placeholder behavior/styles from wc-admin in AutomateWoo on the new presets list table screen (screenshot below capturing the placeholders - you might need to have good contrast to see it clearly)

<img width="1211" alt="Screen Shot 2020-10-14 at 11 05 21 pm" src="https://user-images.githubusercontent.com/355014/95989712-2a14d100-0e72-11eb-9fb6-be174e6a5337.png">

Investigate using a consistent approach to placeholders for the Marketing tab components while content is being loaded.

Currently, the Recommended Extensions and WooCommerce Knowledge Base cards will show a spinner when content loads which is not consistent with other areas of wc-admin.

<img width="828" alt="Screen Shot 2020-10-14 at 11 14 48 pm" src="https://user-images.githubusercontent.com/355014/95990622-4bc28800-0e73-11eb-9847-406ce6e23563.png">

Some reference links:
https://github.com/woocommerce/automatewoo/pull/747 (private AutoamteWoo exension repo)
https://github.com/woocommerce/woocommerce-admin/blob/7c1299c5e2b088d29d8158a3ad806672ef1d14ef/client/stylesheets/abstracts/_mixins.scss#L23-L35

**Comment by tomalec** [comment]
I started by creating more `*Placeholder` components, see #5611

**Comment by tomalec** [comment]
@jconroy If you mean unifying placeholders only in the Marketing tab, the PR is ready for the review, otherwise I'll work on the remaining spinners tomorrow.

**Comment by tomalec** [comment]
Besides `KnowledgebaseCardPost` and `RecommendedExtensionsItem` shown in the OP and covered in PR #5611, there is a number of places that still use the `Spinner` I was not able to reach all of them using UI, but from what it seems some of them are used in relatively small areas, like breadcrumbs, and select fields. I guess spinner may look better there than a grey box of a placeholder.

The only bigger area I found is the `Chart` component, like to one at `/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fcategories`:
![Spinner in the place of a chart](https://user-images.githubusercontent.com/17435/99291723-89cf1500-2840-11eb-8bd2-cd01cadb26dd.png)
I was trying to make a placeholder look like a grayed-out chart. However, I had some difficulties fiddling with it and getting some test data (https://github.com/woocommerce/woocommerce-admin/issues/5640).

Also, the Chart component itself is very customizable, therefore, I expect its look may vary heavily based on that customization, and I wonder whether it's the best UX to show a different kind of chart as a placeholder for the real one.

@jconroy if you would like me to cover also the other spinners, I'd appreciate some support with discovering them in UI and filling some sample data/look of chart placeholder.

**Comment by jconroy** [comment]
Hey @tomalec 

> if you would like me to cover also the other spinners, I'd appreciate some support with discovering them in UI and filling some sample data/look of chart placeholder.

Apologies meant to swing back to this thread yesterday but ran out of time.

Not need to worry about any other components - just the Marketing tab ones - I've updated the title to match "Investigate using a consistent approach to placeholders for the Marketing tab components while content is being loaded."

Thanks for the work on this!

**Comment by jconroy** [comment]
Closed with https://github.com/woocommerce/woocommerce-admin/pull/5611
