### ISSUE TITLE
[WC 4.6 Stable] Advanced filters in Analytics/Orders doesn't work as expected

### ISSUE THREAD

**Issue by Nea-Aristoteles** [woocommerce/woocommerce-admin#5384]
Description:
Advanced filters in Analytics/Orders doesn't catch all custom attributes 

**To Reproduce**

1. Go to Analytics / Orders
2. Click on "Show" and select "Advanced Filters"
3. Add a new filter and choose "Attributes" as a dimension
4. When choosing an attributes, only certain attributes are printed on the select dropdown.

**Expected behavior**
I expect to be able to find and filters for all the values of the custom attribute chosen.

**Screenshots**
<img width="1699" alt="screen bug" src="https://user-images.githubusercontent.com/72889367/96038381-5545f300-0e67-11eb-935b-b22fcf150576.png">

**Desktop (please complete the following information):**

* OS: Mac Os X 10.15
* Browser Chrome 
* Version 48

**Comment by Nea-Aristoteles** [comment]
I think there is a limit on the dropdown. The same issue happen on all the custom attributes. It seems to be limited to 10 VALUES. 

Maybe there is something with the API, maybe pagination in the response or something similar.

**Comment by jeffstieler** [comment]
Hello @Nea-Aristoteles,

Thanks for reporting the issue.

Are the attributes you're seeing missing "global" ones or "local" ones?

Global attributes are created at Products > Attributes and then applied to specific product variations (these are great for common variations across most of your products). Local attributes are created on individual products and are good for specific attributes of just one or a few products.

Currently, the attribute filter only searches "global" product attributes.

**Comment by Nea-Aristoteles** [comment]
Hello @jeffstieler. Those are "Global". In the specific example this is "Brand" (Custom global attribute) that I use on every product (ex: Nike, Adidas, Reebok).

I think that the dropdown has a limit to "show 10 items".

**Comment by jeffstieler** [comment]
@Nea-Aristoteles are you able to find the missing attributes by typing in the search box above the dropdown?

**Comment by Nea-Aristoteles** [comment]
> @Nea-Aristoteles are you able to find the missing attributes by typing in the search box above the dropdown?

No, I'm not. That's why I quickly reported it. It is not only a FE thing.

**Comment by jeffstieler** [comment]
> I think that the dropdown has a limit to "show 10 items".

Looks like this is being inherited from the base `WP_REST_Controller`: https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-controller.php#L351-L359

Nice catch @Nea-Aristoteles - thanks again for reporting!

**Comment by Nea-Aristoteles** [comment]
Do you think this is a though one?

**Comment by jeffstieler** [comment]
> Do you think this is a though one?

This hasn't been prioritized to be worked on yet - if you're referring to why it hasn't been resolved.

> > @Nea-Aristoteles are you able to find the missing attributes by typing in the search box above the dropdown?
> 
> No, I'm not. That's why I quickly reported it. It is not only a FE thing.

I think I missed the finer points in this while looking for the page size issue. No matter how specific your search term, are there attributes that _never_ show in the results? If so, what are the attribute values? (In my testing I saw the effect of the small page size of 10, but I was always able to find a specific attribute by typing it in)

**Comment by Nea-Aristoteles** [comment]
> I think I missed the finer points in this while looking for the page size issue. No matter how specific your search term, are there attributes that _never_ show in the results? If so, what are the attribute values? (In my testing I saw the effect of the small page size of 10, but I was always able to find a specific attribute by typing it in)

Yes, only the first 10 attributes (alphabetically ordered) are printed and you can not search for anything else. Even if you do, it shows nothing.

In this example, I have more than 30 "Produttori", which are basically "Brands". The dropdown only shows 10 of them. If I try to search for "Vinosia" (a wine "Produttori" that I have) it gives me nothing. 

<img width="1648" alt="Schermata 2020-10-27 alle 14 54 04" src="https://user-images.githubusercontent.com/72889367/97311214-6974f180-1864-11eb-84e6-927ec85d1435.png">
<img width="1675" alt="Schermata 2020-10-27 alle 14 54 09" src="https://user-images.githubusercontent.com/72889367/97311220-6b3eb500-1864-11eb-849c-3741ddf5ed3d.png">

**Comment by jeffstieler** [comment]
Hmm.. that actually appears to be a different bug entirely. If you [open your browser console](https://wordpress.com/support/browser-issues/advanced-browser-troubleshooting/#javascript-errors), do you see any errors?

**Comment by Nea-Aristoteles** [comment]
Nope, no errors, it the same problem @jeffstieler. It doesn't print more info because it doesn't have more info. Why do you think is a different issue?

**Comment by jeffstieler** [comment]
> Why do you think is a different issue?

I think it might be unrelated to the page size. When you type a search query into the dropdown field, a new API request should be made - so if you do have a "Vinosia" Produttori item, searching for "Vinosia" should match it and include it in a result set of 10 items. Since you are searching for the exact term value and still seeing no results, I'm guessing there's a bug somewhere.

**Comment by AlexPl81** [comment]
Hi, sorry if i'm missing something, as related bug is shown as resolved, but i have the latest Woocommerce 5.0.0 setup and i'm having the same issue only first 10 attribute values show up in the box (first 10 alphabetically) and i can not search for the rest, no errors are displayed in browser console.
