### ISSUE TITLE
Home Screen insights message date translation string not registered

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce-admin#5392]
**Describe the bug**
A Home Screen insight message date "day/days" phrase is not registered as a string available for translations, it's always in English.

**To Reproduce**

1. Switch WP language to non-en.
2. Go to WooCommerce->Home.
3. Look at the Insights section.

**Screenshots**
![Zrzut ekranu 2020-10-15 o 12 06 45](https://user-images.githubusercontent.com/27000783/96111577-ab577c80-0ee1-11eb-9843-881ff1557d3d.png)

WP 5.5.1
WC 4.6.0
WC Admin 1.6.1 (bundled with WC)

PS Similar bug has been submitted here: #5115 and #5391

**Comment by starypop** [comment]
FYI It also happens in Orders sidebar:
![Zrzut ekranu 2020-10-16 o 15 29 49](https://user-images.githubusercontent.com/27000783/96264740-cea72800-0fc4-11eb-94b5-eb8c027797fb.png)


There's also problem with **Begin filfillment** button. Its translation has been submited.

**Comment by timmyc** [comment]
This [is using](https://github.com/woocommerce/woocommerce-admin/blob/main/client/inbox-panel/card.js#L315) `moment`'s `fromNow()` which is added to the DOM from WordPress core. [Here is a list of those strings](https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/date/src/index.js#L56-L71) that are translatable for the output of the `fromNow()` call.

@starypop can you see if your language has those strings translated?

**Comment by starypop** [comment]
@timmyc 

Actually I couldn't find those strings at translate.wordpress.org in WooCommerce project and in WordPress core as well. It looks like they're not registered or they're not translatable.

Eg. '%d hours' or 'a few seconds'

**Comment by starypop** [comment]
The "Begin fllfillment" button translation is provided: https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/pl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9168215&filters%5Btranslation_id%5D=70815699

**Comment by timmyc** [comment]
Thanks for looking into the moment strings @starypop - I did a quick search in the Gutenberg repo and it appears that `fromNow()` is not in use there so that kind of makes sense. Seems like we might need to introduce all of those strings in wc-admin here to ensure they get translated properly. 

@psealock I feel like we may have discussed this before early on in wc-admin development. Do you recall any specifics around moment translations and how they are supposed to work either in WP core or in Woo?

**Comment by starypop** [comment]
@timmyc @psealock Hey guys, any updates on this issue?

**Comment by adrianduffell** [comment]
Hi @starypop, we have no updates on this yet unfortunately.

A fix seems like its on the way in WordPress core in [ticket 47373](https://core.trac.wordpress.org/ticket/47373). I'll investigate further.
