### ISSUE TITLE
New Home Screen Welcome modal translation strings not registered

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce-admin#5396]
**Describe the bug**
A Home Screen insight Welcome modal navigation phrases are not registered as a string available for translations, it's always in English.

**To Reproduce**

1. Switch WP language to non-en.
2. Go to WooCommerce->Home for the first time after lauching the new Home Screen.
3. Look at the Welcome modal.

**Screenshots**
![Zrzut ekranu 2020-10-15 o 15 46 25](https://user-images.githubusercontent.com/27000783/96138656-4b230380-0efe-11eb-9f08-c3864ee5ae95.png)
![Zrzut ekranu 2020-10-15 o 15 46 29](https://user-images.githubusercontent.com/27000783/96138678-50804e00-0efe-11eb-80e4-b52ea8152532.png)

WP 5.5.1
WC 4.6.0
WC Admin 1.6.1 (bundled with WC)

PS Similar bug has been submitted here: #5115, #5391 and #5392.

I'm strongly suggesting an overall review of EVERY admin screen of you, as the amount of this kind of internationalization bugs is kinda large…

**Comment by starypop** [comment]
Hey @timmyc @joshuatf @psealock ,

Could you guys please take a look at all those bugs that I've been submitted about i18n issues? And add them to your schedule? It would be great so we can deliver fully translated UI to store owners.

#5392 #5391 #5115 #5414

**Comment by timmyc** [comment]
Thanks for the ping @starypop - I'll see if we can get a few of these fixed up before our next release. Thanks for taking the time to log these issues!

**Comment by timmyc** [comment]
So looked into this one a bit, and it seems the `Previous` and `Next` buttons are in WP Core itself as part of the `<Guide/>` component we are using for this feature. The strings there [are run through a translation call](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/guide/index.js#L99-L122), but do not have a text domain established.

The "Let's Go" text is being [passed through translation here](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/welcome-modal/index.js#L82) in wc-admin, so perhaps is the .pot file missing that translation?

As for fixing the Previous / Next buttons, I think that might require working with Gutenberg upstream, so not sure we can fix this quickly for the next release.

**Comment by starypop** [comment]
@timmyc Yep, I can confirm that the "**Let's go**" button translation was not submited, because there was two versions of this string registered - with and without trailing explanation mark. I've submitted the new translation and it now works fine. Thanks for pointing that out!

So we've got the other buttons (** Previous**, **Next**) still not working then.
