### ISSUE TITLE
4.6.1 Illegal String Offset

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5398]
[Original Report in the forums](https://wordpress.org/support/topic/warning-illegal-string-offset-wccom_connected/)

![stringoffset](https://user-images.githubusercontent.com/22080/96149400-1f802900-0ebe-11eb-97e1-0915f903ed4c.png)

**Comment by octaedro** [comment]
I couldn't reproduce this error.
The `Warning` is thrown when a `string` or `integer` try to be accessed as if they were an `array`.
The weird thing is that this warning shouldn't be visible, since `wp_debug` is `disabled`.

**Comment by timmyc** [comment]
@octaedro thanks for checking this out. Yeah interesting that wp_debug is turned off by the user, but perhaps their host has something in place that is turning it on.

This code path was changed a bit in the release in https://github.com/woocommerce/woocommerce-admin/pull/5290 - So I'm wondering if we can repro this scenario by, turning wp_debug on, then setting the `woocommerce_onboarding_profile` to something other than an array ( `update_option( 'woocommerce_onboarding_profile', 'foo' )` ) and seeing if we can see the bug.

If so perhaps we need to cast the initial get_option call [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/Onboarding.php#L659) to be an array, or check if it is an array after we retrieve, and if it isn't, set the variable to an array 🤔
