### ISSUE TITLE
Improve Analytics / Products

### ISSUE THREAD

**Issue by Nea-Aristoteles** [woocommerce/woocommerce-admin#5399]
**Is your feature request related to a problem? Please describe.**
I can't do the simplest of the export task: I would like to export all the product sold of a single Brand (I've used Global Custom Attribute to store this).

**Describe the solution you'd like**
"Just" implement the same advanced filtering system brought in Analytics/Orders (with Woo-admin 1.6), into the view Analytics/Product.  So I could filter for << Attribute >> and choose << Nike >>. 

In this way all WooCommerce Users could really benefit from a useful export for the goods they're selling.

**Describe alternatives you've considered**
Buying a crappy plugin.

**Should this be prioritized? Why?**
The **impact could be huge** and the **effort seem low**, considered that this feature has already been added into another view of the same area.

<img width="910" alt="Schermata 2020-10-15 alle 17 27 28" src="https://user-images.githubusercontent.com/72889367/96151508-c0490580-0f0b-11eb-827c-1575def11561.png">
<img width="947" alt="Schermata 2020-10-15 alle 17 27 21" src="https://user-images.githubusercontent.com/72889367/96151513-c2ab5f80-0f0b-11eb-9412-773a0ba0f4a3.png">

**Comment by pmcpinto** [comment]
Hi @Nea-Aristoteles thanks for your suggestion. We really appreciate your feedback. In WooCommerce 4.8 we're going to release a brand-new Product Variations reports, that will allow users to use attributes as advanced filters: https://d.pr/i/Qw1wuZ

Let us know if this solves your need. Thanks

**Comment by Nea-Aristoteles** [comment]
I've just seen the update.

I think that the Variation report is broken on two points:

1- If I select "attribute is" "xxx" then on the dropdown menu in which I
have to select the attributes name, it only shows me the first 10
attributes - OLD REPORTED BUG
2- The filter engine seems to always put out "0" as results.

Il giorno ven 27 nov 2020 alle ore 19:03 Pedro Pinto <
notifications@github.com> ha scritto:

**Comment by pmcpinto** [comment]
@Nea-Aristoteles thanks for your feedback.

> 2- The filter engine seems to always put out "0" as results.

Can you add more details about this one? A screenshot or a short video. Thanks in advance!

**Comment by moon0326** [comment]
Closing this as this has been stale for 6+ months Please re-open it if needed.
