### ISSUE TITLE
Reports moved to Settings category in navigation

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#5401]
**Describe the bug**
"Reports" is included under "Settings" in the new navigation.  This is probably because it was left under the original WooCommerce menu item.

Do we want to keep these legacy Reports somewhere or exclude them from the new nav experience?  /cc @jameskoster @pmcpinto 

**To Reproduce**

1. Enable the nav feature.
1. Navigate to the "Settings" category.
1. Note "Reports."

**Screenshots**
<img width="369" alt="Screen Shot 2020-10-15 at 4 38 28 PM" src="https://user-images.githubusercontent.com/10561050/96183579-11a1c680-0f05-11eb-8ef0-b514a3a5f5c0.png">

**Comment by pmcpinto** [comment]
> Do we want to keep these legacy Reports somewhere or exclude them from the new nav experience?

Excluding them from the new experience could be a good starting point to sunset the legacy Reports 🤔 @timmyc @elizaan36  how do you feel about this?

**Comment by timmyc** [comment]
I think it would be an interesting approach to not register the legacy reports in the new nav. 👍
