### ISSUE TITLE
QUESTION: Display Revenue carts on frontend.

### ISSUE THREAD

**Issue by zzap** [woocommerce/woocommerce-admin#5424]
Hello,

This is not really a feature request but it could be. I'd like to recreate Analytics -> Revenue page on frontend and I'm wondering what would be the proper way of doing it. Should I use REST API?

So far I found this but I wonder if there's any faster way of building it:
```
$report = new \Automattic\WooCommerce\Admin\API\Reports\Revenue\Query( $args );
$mydata = $report->get_data();
```

Thank you very much for your time.

**Comment by timmyc** [comment]
@zzap There currently is not a way to render the revenue chart on the front end of the site without writing some custom code. It would be possible to do so using the REST API endpoints, and also reusing the React components like the chart, but no way to do it by default "out of the box"

**Comment by zzap** [comment]
Yeah, I thought so. Thank you.
