### ISSUE TITLE
Navigation Documentation: Add wc-admin doc

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5426]
Continuing with https://github.com/woocommerce/woocommerce-admin/issues/5421 to create a working example for 3PD to register into the Navigation, we'll need some documentation so that plugins can easily integrate.

### Deliverables

* Create a WC Admin README or doc.
* Explain the significance of the Navigation project.
* Provide step by step instructions on registering PHP as well as JS custom links and why that is useful for router-aware links.

cc @pmcpinto

**Comment by pmcpinto** [comment]
Also cc @loranallensmith so we can start collaborating on this

**Comment by psealock** [comment]
As part of this issue, a README added to the example plugin would be helpful.
https://github.com/woocommerce/woocommerce-admin/tree/main/docs/examples/extensions

**Comment by psealock** [comment]
A note to those following this issue, I split it into two: This issue to track documentation in wc-admin and https://github.com/woocommerce/woocommerce-admin/issues/5477 to track outbound communication with third party developers.
