### ISSUE TITLE
PHP Warning - woocommerce-admin

### ISSUE THREAD

**Issue by somethumb** [woocommerce/woocommerce-admin#5427]
**Describe the bug**
PHP Warning

**To Reproduce**
Steps to reproduce the behavior: Normal error log

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Windows 10
* Browser [e.g. chrome, safari] Firefox
* Version [e.g. 22] Latest

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**
Warning: array_search() expects parameter 2 to be array, null given in /home/stcnet/public_html/afdp/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/PerformanceIndicators/Controller.php on line 550

**Comment by ilyasfoo** [comment]
Hi @somethumb,

Thank you for submitting this issue. However, I was unable to reproduce the error you mentioned in the latest version of WooCommerce and WooCommerce Admin.

We would appreciate it if you can let us know what exact steps you took to reproduce this issue, and the WooCommerce and WooCommerce Admin version that you've used.

**Comment by becdetat** [comment]
Not enough information

**Comment by senadir** [comment]
Hey, I'm still seeing this error on regular rest requests, I'm running the code from WooCommerce core instead of the plugin directly, this is the full xdebug stack

```

Warning: Trying to access array offset on value of type int in /Users/nadir/quadragon/app/public/web/app/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/PerformanceIndicators/Controller.php on line 149
--


1 | 16836162608.6251 | 372528 | {main}( ) | .../index.php:0
2 | 16836162608.6251 | 372840 | require( '/Users/nadir/quadragon/app/public/web/wp/wp-blog-header.php ) | .../index.php:6
3 | 16836162608.6251 | 5643208 | wp( ) | .../wp-blog-header.php:16
4 | 16836162608.6251 | 5643272 | WP->main( ) | .../functions.php:1291
5 | 16836162608.6251 | 5643272 | WP->parse_request( ) | .../class-wp.php:745
6 | 16836162608.6251 | 5684216 | do_action_ref_array( ) | .../class-wp.php:388
7 | 16836162608.6251 | 5684216 | WP_Hook->do_action( ) | .../plugin.php:551
8 | 16836162608.6251 | 5684216 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:311
9 | 16836162608.6251 | 5685376 | rest_api_loaded( ) | .../class-wp-hook.php:287
10 | 16836162608.6251 | 5685400 | rest_get_server( ) | .../rest-api.php:347
11 | 16836162608.6251 | 5688176 | do_action( ) | .../rest-api.php:521
12 | 16836162608.6251 | 5688552 | WP_Hook->do_action( ) | .../plugin.php:484
13 | 16836162608.6251 | 5688552 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:311
14 | 16836162608.6251 | 6709872 | Automattic\WooCommerce\Admin\API\Init->rest_api_init( ) | .../class-wp-hook.php:287
15 | 16836162608.6251 | 8790808 | Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller->register_routes( ) | .../Init.php:107
16 | 16836162608.6251 | 8791992 | Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller->get_collection_params( ) | .../Controller.php:96
17 | 16836162608.6251 | 8791992 | Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller->get_indicator_data( ) | .../Controller.php:649
18 | 16836162608.6251 | 8791992 | Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller->get_analytics_report_data( ) | .../Controller.php:269

```
