### ISSUE TITLE
[WC 4.7 Beta1] No easy way to go back to the site once started WC Payments setup through the Home Screen Task 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5430]
**Describe the bug**

It seems there is no easy way to go back to the site once started WC Payments setup through the Home Screen Task. 

Please feel free to transfer this issue to WC Payments repo if it belongs there.  

**To Reproduce**

1. Create a new JN site. 
2. Upload WC 4.7 Beta1. 
3. Complete onboarding (US store + select to install free business extensions).
4. Once on the Home Screen, click on the task to set up WC Payments.
5. You will be presented with the modal to connect to WC.com/Jetpack - complete it. 
6. Next, you will see the beginning of the WC Payments setup process. 
7. At this point, try to go back to the site. The only way to do that seems to be using the browser's back button. 
8. Please see below the gif of what happens - basically, you get back to the WC.com/Jetpack modal - from there you can go back to the site using 2 different ways (through the button and the link) but none of these take you back to the site. Instead, you are taken back to the WC Payments setup modal:

![](http://g.recordit.co/nBteB0H9aj.gif)

**Expected behavior**

I expected to be able to easily go back to the site if I didn't want to set up WC Payments right away. 

**Screenshots**

See gif above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 86.0.4240.80 (Official Build) (x86_64)

**Additional context**

N/A.

**Comment by timmyc** [comment]
Thanks @juliaamosova - I think we might want to move this one to the WC Pay repo since the flow here is entirely controlled by the plugin, not wc-admin.

**Comment by juliaamosova** [comment]
Thanks @timmyc! I created the issue in the WC Payments repo: https://github.com/Automattic/woocommerce-payments/issues/1033. 

Closing this one.
