### ISSUE TITLE
[WC 4.7 Beta1] `Set up Tax` task gets completed if you try to set up WC Payments via Home Screen task before tax

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5431]
**Describe the bug**

`Set up Tax` task gets completed if you try to set up WC Payments via Home Screen task before tax. 

**To Reproduce**

1. Create a new JN site. 
2. Upload WC 4.7 Beta1. 
3. Complete onboarding (US store + select to install free business extensions).
4. Once on the Home Screen, note that the `Set up tax` task is not completed. Click on the task to set up WC Payments.
5. You will be presented with the modal to connect to WC.com/Jetpack - complete it. 
6. Next, you will see the beginning of the WC Payments setup process. Go back to the site without completing it. 
7. Note that the `Set up tax` task is now marked as completed on the Home Screen. 

It likely happens when the user is being presented with the WC.com/Jetpack connection modal. When the user completes it, Jetpack gets activated which in turn enabled automated tax set up via WC Shipping & Tax. But the user actually doesn't know about this so the flow is a bit strange. I was surprised to see that the `Set up tax` task was completed without me completing it. 

**Expected behavior**

I expected to get back to the site after trying to set up WC Payments through the Home Screen task and still see the `Set up Tax` task to not be completed. 

**Screenshots**

N/A. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 86.0.4240.80 (Official Build) (x86_64)

**Additional context**

N/A.

**Comment by timmyc** [comment]
@juliaamosova thanks for the detailed bug report. I _think_ this might be working as expected based on the parameters you have noted - specifically the step where you Jetpack connected that is what we hook into to setup the tax defaults. By chance do you still have the test site available? If so we could confirm this by seeing if there is an inbox note about tax defaults being setup for you.

**Comment by juliaamosova** [comment]
@timmyc thanks! Yes, I still have the site and I do see that card:

![tax](https://user-images.githubusercontent.com/19143190/96643860-2d86dd00-12f6-11eb-85a1-ab5ac2e76fe1.jpg)

It makes sense to me now so I think this can be closed as expected behavior. Thanks for clarifying!
