### ISSUE TITLE
[WC 4.7 Beta1] Atomic: `Store details` task gets undone after completing `Purchase & Install extensions` task

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5432]
**Describe the bug**

This seems to happen on Atomic only: the `Store details` task gets undone after completing the `Purchase & Install extensions` task. 

**To Reproduce**

1. Create a new Atomic site.
2. Upload WC 4.7 Beta1.
3. Complete onboarding (US store + select to install free business extensions).
4. Once on the Home Screen, note that the `Store details` task is not completed (it is always completed if you are done with the onboarding). Click on the task to `Purchase & Install extensions`. Complete it. 
5. When you are back to Home Screen, note that `Purchase & Install extensions` is marked as completed but the `Store details` task is undone:

![](http://g.recordit.co/htuOdZYOb2.gif)

**Expected behavior**

I expected the `Store details` task to stay completed after I was done with the `Purchase & Install extensions` task. 

**Screenshots**

See gif above. 

**Desktop (please complete the following information):**

OS: macOS Catalina 10.15.6
Browser: Chrome
Version: 86.0.4240.80 (Official Build) (x86_64)

**Additional context**

N/A

**Comment by becdetat** [comment]
I've confirmed this does not occur on a JN site with WC 4.7.1 - will test Atomic next

**Comment by becdetat** [comment]
I've also confirmed that this does not occur on an atomic site with WC 4.7.1 - the "Store details" step is left as completed after completing the "Purchase..." step. @juliaamosova can you retest this with 4.7.1? I may be missing something in the repro.
