### ISSUE TITLE
Icon issue in Recommended Coupon Extensions

### ISSUE THREAD

**Issue by ecgan** [woocommerce/woocommerce-admin#5449]
**Describe the bug**
After activating WooCommerce Admin, the icons in the Recommended Coupons Extensions look different from before and not showing up correctly on hover.

**To Reproduce**

1. Have WooCommerce activated and WooCommerce Admin **deactivated**.
2. Go to http://example.test/wp-admin/edit.php?post_type=shop_coupon
3. Take note of the icons and their hover state in the Recommended Coupon Extensions section. The icons have borders and they have blue background in hover state.
4. Activate WooCommerce Admin plugin.
5. Go to http://example.test/wp-admin/edit.php?post_type=shop_coupon
6. The icons do not have borders. When you hover over the items, the icons disappear.

**Expected behavior**
At least icons should not disappear on hover.

**Screenshots**

Before activating WooCommerce Admin (the Personalized Coupons is in hover state): 

![Screenshot on 2020-10-21 at 18-39-00](https://user-images.githubusercontent.com/417342/96709072-bb34fc00-13cc-11eb-8065-eacf8fa633cc.png)

After activating WooCommerce Admin (icon disappear on hover): 

![Screenshot on 2020-10-21 at 18-42-12](https://user-images.githubusercontent.com/417342/96709345-2979be80-13cd-11eb-9411-9d903514ea20.png)

**Desktop (please complete the following information):**

* OS: Mac OS
* Browser [e.g. chrome, safari]: FireFox
* Version [e.g. 22]: 81

**Additional context**

The site is create using Valet+, with fresh new `git clone` of WooCommerce and WooCommerce Admin.

**Comment by jconroy** [comment]
Just noting that I couldn't replicate.

Potentially related to changes in https://github.com/woocommerce/woocommerce-admin/commit/7c1299c5e2b088d29d8158a3ad806672ef1d14ef#diff-565206e9c8260d12438231620ec3e6b8349464bc599bdee42b6cd11555fcc6a3 (css variables not working) or something else causing the styles to not be applied

**Comment by jconroy** [comment]
Hey @becdetat just thought I'd see if you had any insight on this one - ([based purely on your chiming in re: styles here](https://github.com/woocommerce/woocommerce-admin/pull/5428#pullrequestreview-514308471)) 

I did some digging and some people on our team [saw similar issues previously](https://github.com/woocommerce/woocommerce-admin/pull/4794#pullrequestreview-449240908) with using the css variables - I couldn't replicate the issue previously either and decided to stick with the old approach that seemed to work for most people.

**Comment by ecgan** [comment]
Some findings: 

When you have WooCommerce plugin activated and WooCommerce Admin **deactivated**, things are working as expected. There is a CSS stylesheet loaded with the following rule:

Stylesheet URL: http://ganwp1.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/marketing-coupons/style.css?ver=1.6.2

```css
:root {
  --wp-admin-theme-color:#007cba;
  --wp-admin-theme-color-darker-10:#006ba1;
  --wp-admin-theme-color-darker-20:#005a87
}
```

![Screenshot on 2020-10-24 at 00-42-36](https://user-images.githubusercontent.com/417342/97030769-de5cd880-1591-11eb-8df8-3c2b96a0feec.png)

The icons would show up with WP admin theme color.

![Screenshot on 2020-10-24 at 00-45-09](https://user-images.githubusercontent.com/417342/97031059-47dce700-1592-11eb-9751-82f833599980.png)

When you have the WooCommerce Admin **activated**, the above stylesheet is not loaded, and there is another new stylesheet, and there is no rule for `:root`.

New stylesheet URL: http://ganwp1.test/wp-content/plugins/woocommerce-admin/dist/marketing-coupons/style.css?ver=1602685252

![Screenshot on 2020-10-24 at 00-49-56](https://user-images.githubusercontent.com/417342/97031448-e10bfd80-1592-11eb-81fe-b83a3b185375.png)

`--wp-admin-theme-color` is not set, which is why the icons seem to disappear - they are having white background with white text color.

![Screenshot on 2020-10-24 at 00-52-27](https://user-images.githubusercontent.com/417342/97031655-3942ff80-1593-11eb-8c61-a096fdc55e81.png)

**Comment by ecgan** [comment]
More findings: 

The WooCommerce plugin has the following dependency specified in `composer.json` file:

```
"woocommerce/woocommerce-admin": "1.6.2",
```

So based on this, I checked out WooCommerce-Admin release/1.6.2 branch, and there is no icon UI issue. Same goes with release/1.6.3 branch.

I did a git bisect to try to find out which commit causes the issue, with release/1.6.3 as the good commit and main branch (commit 38ceacedf) as the bad commit. For each commit that was being tested, I ran `npm install`, `composer install` and `npm run build`. Turns out the bad commit that introduces the icon issue is f6f376b6 which is to update version to 1.7.0-dev.

**Comment by becdetat** [comment]
@jconroy, sorry I took so long to reply.

> Hey @becdetat just thought I'd see if you had any insight on this one

No, sorry, I don't. I just knew that we were preferring variables over hard-coded ones.

We are seeing an [issue with styling](https://github.com/woocommerce/woocommerce-admin/issues/5345) that could be related to this but it seems unlikely.

**Comment by ecgan** [comment]
More findings: 

By using git bisect and looking into the http://ganwp1.test/wp-content/plugins/woocommerce-admin/dist/marketing-coupons/style.css file, the problem is introduced in the commit c27e2660 which changes the "@wordpress/base-styles" dependency from "2.0.0" to "3.1.0". In the package version 2.0.0, the file `_mixins.scss` has the following code: 

```css
:root {
	@include admin-scheme(#007cba);
}
```

In version 3.1.0, the code is no longer there in `_mixins.scss` but moved to [`_default-custom-properties.scss`](https://github.com/WordPress/gutenberg/blob/master/packages/base-styles/_default-custom-properties.scss). This is done in Gutenberg's [PR #24408](https://github.com/WordPress/gutenberg/pull/24408) and then [PR #24890](https://github.com/WordPress/gutenberg/pull/24890). This is why the marketing coupons CSS file end up missing the value for `--wp-admin-theme-color`.

**Comment by jconroy** [comment]
Nice work @ecgan 🙇
