### ISSUE TITLE
Navigation: Explore removing need for id in client side registration of wc-admin

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5458]
https://github.com/woocommerce/woocommerce-admin/pull/5445 introduced a need for plugins extending wc-admin to supply an `id` for filters `woocommerce_admin_reports_list` and `woocommerce_admin_pages_list` in order to match client side ids for purposes of slotFilling custom links.

>I needed to add id on the client side to results of getReports and getPages to match the id's registered in PHP so that Slot and Fill names can be correctly identified. This means that plugins currently using hooks like woocommerce_admin_pages_list to add pages will need to update. Since we have that information already from PHP, it feels like there is a better solution to investigate so that we can keep the filter API the same. Here is an example from WC Payments that would need updating.

https://github.com/Automattic/woocommerce-payments/blob/c7f9d58e2d20fc5fb10d3fa5d205f698bcf3b8c6/client/index.js#L24

This issue is to track exploring possibilities of refactoring the way pages and reports are calculated client side to automatically grab ids supplied by PHP. This will be useful to avoid changing the API requirements of those filters.

**Comment by joshuatf** [comment]
Another possible option here is to use the `path` property instead of adding an ID.  Since this is unique to pages added in WCA anyway, we could avoid adding the `id` property.

**Comment by psealock** [comment]
>Another possible option here is to use the path property instead of adding an ID

True, I'll need to access to the path property in PHP in that case. Its just a matter of syncing a slug or some other identifier between JS and PHP.
