### ISSUE TITLE
Inbox: Remove Store Setup Alert

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5460]
This was a request that came up during the final release testing of 1.6 from @pmcpinto - Now that we have the Activity Panel Store Setup link, this old Store Alert style notification feels quite redundant:

![image](https://user-images.githubusercontent.com/22080/96895999-e3ab0d80-1441-11eb-945d-a2cec795feee.png)

This fix might require two different PRs, one using `release/1.6.2` as a base branch, and another against `main` since notes have diverged between those two branches.

Tasks:

- [x] Remove `OnboardingProfiler` [note](https://github.com/woocommerce/woocommerce-admin/blob/6a59bc85703b784aeb0da25e264142fbb278e6f6/src/Notes/OnboardingProfiler.php)
- [x] In `main` we should also remove the related [deprecation facade](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/DeprecatedNotes.php#L545)
- [x] add entry to [delete_obsolete_notes](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Install.php#L469)

**Comment by mattsherman** [comment]
@timmyc Do we still need to address this issue in any branch other than `main`?

**Comment by timmyc** [comment]
@mattsherman `main` is great for now 👍
