### ISSUE TITLE
Task List: Add Brazil to list of allowed countries for Stripe

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5461]
The Transact and Partnerships team would like to add Brazil to the list of allowed countries for the Stripe payment gateway.

Context: pbIJXs-jy-p2

- [ ] Add `BR` to `get_stripe_supported_countries` [#](https://github.com/woocommerce/woocommerce-admin/blob/d5c7d26caa33fc079a87016f29338ce378532c71/src/Features/Onboarding.php#L674)
- [ ] Stretch goal, alphabetize the array of country codes there for ease of future reading/adding/deleting

**Comment by dechov** [comment]
The first point was addressed in https://github.com/woocommerce/woocommerce-admin/pull/5377 (noted further down in pbIJXs-jy-p2#comment-1010 – apologies for not linking it directly earlier).

The list is now in a [different file](https://github.com/woocommerce/woocommerce-admin/blob/aa2264d5cefa0ff0362479a2f3fed7980f263117/src/Features/OnboardingTasks.php#L309) – but it looks like `release/1.6.2` does already have it in that file so we should be able to cherry-pick the earlier change.

In any case, agreed that alphabetizing would be helpful (or else possibly matching the order at stripe.com/global).

**Comment by timmyc** [comment]
Thanks @dechov just saw your other PR. Flagged that one for cherry pick! I'm going to close this out since the most important piece was shipped in #5377
