### ISSUE TITLE
4.4.0-> 4.5.2 DB issues with wc_admin_notes and wp_wc_admin_note_actions tables

### ISSUE THREAD

**Issue by megaginge** [woocommerce/woocommerce-admin#5463]
Hello

Upgraded from 4.4.0 to 4.5.2 today.

UX is all fine but issues with column is_deleted in the wc_admin_notes table:

Unknown column 'is_deleted' in 'where clause']
SELECT * FROM wp_wc_admin_notes WHERE 1=1 AND name IN ('wc-admin-coupon-page-moved') AND is_deleted = 1 ORDER BY date_created DESC LIMIT 0, 10

WordPress database error: [Unknown column 'is_deleted' in 'where clause']
SELECT * FROM wp_wc_admin_notes WHERE 1=1 AND status IN ('unactioned') AND name IN ('wc-admin-coupon-page-moved') AND is_deleted = 0 ORDER BY date_created DESC LIMIT 0, 10

WordPress database error: [Unknown column 'actioned_text' in 'field list']
SELECT action_id, name, label, query, status, is_primary, actioned_text FROM wp_wc_admin_note_actions WHERE note_id = 0

Etc.

Presumably the patch between 4.4 and 4.5.2 has some issues.

For ref, I ran the below (After taking a backup) to suppress my local trouble:

alter table wp_wc_admin_notes  add column is_deleted bool;
alter table wp_wc_admin_note_actions  add column is_deleted bool;
alter table wp_wc_admin_note_actions  add column actioned_text varchar(255);
alter table wp_wc_admin_note_actions  add column layout varchar(255);
alter table wp_wc_admin_notes  add column layout varchar(255);
alter table wp_wc_admin_notes  add column image varchar(255);

I did run the wordpress DB update after updating the plugin, these issues persisted that. 

My issue seems resolved, though not ideal as I could not assume what you intended with your DB schema. So please advise? 

Thanks
Dave

**Comment by rrennick** [comment]
Transferring this issue to the WooCommerce Admin repository

**Comment by ilyasfoo** [comment]
I was unable to reproduce the issue by manually installing WooCommerce 4.4.0 and upgrading to 4.5.2 via upload plugin in wp-admin.

I want to also add that the column changes were added in WooCommerce 4.3.3, not 4.4.0, so there could be more context to this that's missing.
