### ISSUE TITLE
Customer effort score: Show comments section in survey

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#5468]
Part of #5259

Add a section for the user to add a comment to their feedback. The section should only be displayed if the user selects "Very difficult" or "Somewhat difficult". The comment is an *optional* field - add an "Optional" label per this screenshot (decided [here](https://woostartp2.wordpress.com/2020/10/16/customer-effort-score-design-i2/#comment-1070)).

![image.png](https://images.zenhubusercontent.com/5e4207fe3e11c3c09f1c2919/7eaed229-f0d2-49c0-887b-f8c3fd44377c)

If "Neutral", "Somewhat easy", or "Very easy is selected", the comments field will not show and the effort score will be recorded on its own.

![ces-update-1](https://user-images.githubusercontent.com/224531/96949974-8770e800-152c-11eb-98ce-355028271835.gif)

The [WP core component for the text area](https://wordpress.github.io/gutenberg/?path=/story/components-textareacontrol--default) can be used, with the label bumped up to the `Subtitle small` text component to provide better hierarchy in the modal. The CES prompt question is also displayed as `Subtitle small`.

See [this P2 post](https://woostartp2.wordpress.com/2020/10/16/customer-effort-score-design-i2/).

**Comment by adrianduffell** [comment]
@becdetat should there be a maximum character limit on this field?

**Comment by adrianduffell** [comment]
There are 2 PRs addressing the comments field:

- UI in https://github.com/woocommerce/woocommerce-admin/pull/5515
- Tracks Event in https://github.com/woocommerce/woocommerce-admin/pull/5621

**Comment by becdetat** [comment]
@adrianduffell 

> @becdetat should there be a maximum character limit on this field?

I'm not sure, none has been specified so I think not, however I've asked @elizaan36 here: https://woostartp2.wordpress.com/2020/10/16/customer-effort-score-design-i2/#comment-1177

**Comment by elizaan36** [comment]
Hey I'll respond here rather than P2 to keep everything in one place.

There isn't currently a character limit on that component I don't think, so we can leave it as-is for now. If it becomes a problem then we can revisit.😊
