### ISSUE TITLE
Customer effort score: Only show the survey in the correct screen

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#5482]
As built so far if there is a survey it could potentially be shown on any page per [this](https://github.com/woocommerce/woocommerce-admin/pull/5324#pullrequestreview-517724867).

The survey should only be shown in the correct screen. 

![](https://user-images.githubusercontent.com/63922/97312705-299a1400-183c-11eb-9316-cbbc718f72ad.gif)

Currently this will only be checking for the product edit screen (the target screen for both adding and editing a product) but the concept will be used for any new trigger actions.

**Comment by jeffstieler** [comment]
Even if just the product edit screen is targeted, it might still be possible for a different user to get the CSE modal when opening a different product to edit after another user has triggered the CSE modal for themselves.

**Comment by becdetat** [comment]
@jeffstieler 

> Even if just the product edit screen is targeted, it might still be possible for a different user to get the CSE modal when opening a different product to edit after another user has triggered the CSE modal for themselves.

This is a risk, although there is only a couple of seconds where this can happen because the queue is cleared. I'll keep this in mind though as I can't think of a way to fix this at the moment. Any suggestions would be welcome :-)

**Comment by jeffstieler** [comment]
> Any suggestions would be welcome 

I think switching to user meta instead of an option could solve this problem, see: https://github.com/woocommerce/woocommerce-admin/pull/5511#pullrequestreview-520979048
