### ISSUE TITLE
Add sub-navigation to "Payments"

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#5485]
**Describe the bug**
WooCommerce payments lacks the requite sub-navigation

**To Reproduce**
1. Ensure you're running WooCommerce payments on your store - you should see the Payments top level nav in the WP-admin nav. 
2. Enable the new navigation in WooCommerce-Admin
3. Note that payments lacks the requisite sub-navigation.

**Expected behavior**
The sub-navigation should include the following menu items: 

- Deposits
- Transactions
- Disputes
- Settings

**Comment by psealock** [comment]
I believe this is a wc-admin problem of extensions registering pages, but only the top level one is registered in Navigation. Maybe some of the existing [Example Extensions ](https://github.com/woocommerce/woocommerce-admin/tree/main/docs/examples/extensions) can be updated to mimic this use case involving subpages so we don't need to replicate the situation using WC Pay.

**Comment by joshuatf** [comment]
Now that we're going with the "Plugins" approach to the navigation, will these WC Pay items go under "Payments" in the core menu?  Or will the WC Pay plugin register under the "Extensions" menu?

**Comment by elizaan36** [comment]
Just poking in here to say that yes, with the "Plugins" approach we don't have a "Payments" top level item and the WCPay plugin will appear in the Extensions menu. Chatted with @LevinMedia about it yesterday.
