### ISSUE TITLE
[GlobalStep - WooCommerce 4.7.0-rc.1][Win] Buttons present on "Welcome to WooCommerce Store.." popup appears misaligned 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#5490]
## Bug Description:
Buttons present on "Welcome to WooCommerce Store.." popup appears misaligned  

## Environment:
Windows 10
Browser: Chrome(Version 86.0.4240.75 (64-bit))
Edge(Version 86.0.622.48)(64-bit)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Go to WooCommerce beta Tester.
1. Switch the WooCommerce version to 4.7.0-rc.1.
1. Click on “Home” from the side panel.
1. Note that "Welcome to WooCommerce Store.." popup appears
1. Click on "Next" button and "Previous" button
1. Observe that buttons on "Welcome to WooCommerce Store.." popup appears misaligned 

## Actual Result:
Buttons present on "Welcome to WooCommerce Store.." popup appears misaligned 

## Expected Result:
Buttons present on "Welcome to WooCommerce Store.."popup should be properly aligned 

## Artifacts:
[#5490.zip](https://github.com/woocommerce/woocommerce-admin/files/5452941/5490.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Hi @gglobalstep, I'm going to close this since I think the buttons are properly aligned now.

If you're still facing the issue. Please free feel to open this with a screenshot or a short video. Thanks!

![Screen Shot 2022-01-17 at 14 19 15](https://user-images.githubusercontent.com/4344253/149717785-406ef8c7-cc16-4565-a705-411f11bc2aac.png)
