### ISSUE TITLE
WC Admin Order does not handle custom order classes correctly

### ISSUE THREAD

**Issue by oneteamsoftware** [woocommerce/woocommerce-admin#5492]
**Describe the bug**
Customer has reported that they are seeing the following fatals errors in their logs:
CRITICAL Uncaught Error: Call to undefined method OneTeamSoftware\Woocommerce\PackageOrders\MainOrder::get_report_customer_id() in /nas/content/live/ugrtest/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Orders/Stats/DataStore.php:472
Stack trace:
#0 /nas/content/live/ugrtest/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Orders/Stats/DataStore.php(444): Automattic\WooCommerce\Admin\API\Reports\Orders\Stats\DataStore::update(Object(OneTeamSoftware\Woocommerce\PackageOrders\MainOrder))
#1 /nas/content/live/ugrtest/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/OrdersScheduler.php(160): Automattic\WooCommerce\Admin\API\Reports\Orders\Stats\DataStore::sync_order(443049)
#2 [internal function]: Automattic\WooCommerce\Admin\Schedulers\OrdersScheduler::import(443049)
#3 /nas/content/live/ugrtest/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/SchedulerTraits.php(267): call_user_func_array(Array, Array)
#4 /nas/content/li in /nas/content/live/ugrtest/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Orders/Stats/DataStore.php on line 472

Upon code investigation we have found that in:
Woocommerce/packages/woocommerce-admin/src/Overrides/Order.php:87

the following code override only standard instances of the orders:
public static function order_class_name( $classname, $order_type, $order_id ) {
		// @todo - Only substitute class when necessary (during sync).
		if ( 'WC_Order' === $classname ) {
			return '\Automattic\WooCommerce\Admin\Overrides\Order';
		} else {
			return $classname;
		}
	}

and then in:
Woocommerce/packages/woocommerce-admin/src/API/Reports/Orders/Stats/DataStore.php:472

$order->get_report_customer_id() is called unconditionally without checking if order actually implements required method.

**Possible Solutions**
1. modify DataStore::update method to check that input parameter is of expected type, for example:

if ( !($order instanceof \Automattic\WooCommerce\Admin\Overrides\Order) ) {
    return -1;
} 

2. Otherwise you can use a wrapper class instead of overriding class which will guarantee that you have all you need.

**Comment by ilyasfoo** [comment]
@oneteamsoftware Thank you for your report. We're not going to implement additional checking for method existence at this point. I'd suggest you extend the original Order class instead or however you feel best for your customer.

**Comment by oneteamsoftware** [comment]
That is very upsetting that you are not willing to verify input. Extending from your order make absolutely no sense
