### ISSUE TITLE
Inbox notification: WooCommece 4.7 Release 

### ISSUE THREAD

**Issue by brentmackinnon** [woocommerce/woocommerce-admin#5494]
@pmcpinto @becdetat 

It would be great to include a WC ADmin inbox notification to announce the next minor release:

I'm open to any input you have on who should be targeted. Perhaps any customer with 4.0 or later installed?

---
**Timing:**
November 10

**Headline:**
WooCommerce 4.7 has arrived!

**Body:**
The latest version of WooCommerce is here. As usual, we have plenty of fixes and improvements along with exciting new features to help you get the most out of WooCommerce. Click to learn more about this release, and how to update.

**Link:**
https://docs.woocommerce.com/document/how-to-update-woocommerce/
---
Let me know what other info you need.

**Comment by becdetat** [comment]
This would be a good candidate for the remote inbox notifications system, otherwise there's no way to deliver this. That means that it will only be available for sites already on 4.6.0 as that was when the remote inbox notifications system was enabled.

**Comment by pmcpinto** [comment]
@brentmackinnon do you still want to trigger this notification or repurpose it for WooCommerce 4.8?

**Comment by brentmackinnon** [comment]
> @brentmackinnon do you still want to trigger this notification or repurpose it for WooCommerce 4.8?

I'd be happy to repurpose the same update for each new release. 

Forgive me, I may have misunderstood the previous directions. — Should I work with @kloon for this, or is it something you all would execute? Is there anything required on my end to deploy this?

**Comment by pmcpinto** [comment]
@becdetat I think the message can be implemented by @kloon, right?

**Comment by becdetat** [comment]
@pmcpinto @brentmackinnon  Sorry, I missed this. Yes, anyone that can add the spec to woocommerce.com could release this note.

**Comment by pmcpinto** [comment]
I'm going to close this one as 4.7 was already released.
