### ISSUE TITLE
Categories Emailed Report contains items from order categories

### ISSUE THREAD

**Issue by damiannep** [woocommerce/woocommerce-admin#5503]
**Describe the bug**
The emailed report from Analytics > Categories does not match what's shown on the screen.

**To Reproduce**
1. Go to Analytics > Categories
2. Choose a single category to filter
3. If necessary, edit the rows per page to span several pages to trigger an email rather than a direct download
4. Notice that the emailed report includes additional products not in the selected category.

**Expected behavior**
I expect the emailed report to match what's on my screen.

What seems to be happening is that any products purchased together with products in that category are added to the emailed report even though they don't show up in the list on the screen.

**Screenshots**

**Desktop (please complete the following information):**

* OS: Mac OS Catalina
* Browser Chrome
* Version 83

**Additional context**
Reported in [the forums](https://wordpress.org/support/topic/analytics-export-direct-download-vs-email/).

**Replicated**
Screenshot: https://d.pr/i/jVS5Jv
CSV file: https://d.pr/f/cqt1rf

**Comment by IbrahimHd** [comment]
Any update on this issue please?
