### ISSUE TITLE
Fix WP_Filesystem warning when using FTP

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#5507]
> `Warning: ftp_fget() expects parameter 1 to be resource, null given` which is caused by > `$file_contents = $wp_filesystem->get_contents( $json_filename );` in the modifed file > in this PR. Happened 385k times on a site the last week.

It seems like using `$wp_filesystem->get_contents()` skips some filesystem checks when access directly like that.

_Originally posted by @kimmenbert in https://github.com/woocommerce/woocommerce-admin/pull/5094#issuecomment-693205470_

**Comment by becdetat** [comment]
It looks like this would be possible if [`$wp_filesystem->connect()`](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-admin/includes/class-wp-filesystem-ftpext.php#L87) isn't called before [`get_contents()`](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-admin/includes/class-wp-filesystem-ftpext.php#L146), meaning that `link` is null. However I can't see where `connect()` is called at all which doesn't seem to make sense.

**Comment by moon0326** [comment]
Closing this for now as it's been stale for 6+ months. Please feel free to re-open if needed.
