### ISSUE TITLE
Navigation: Implement Buckets 

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5518]
This formalizes the progress already made in https://github.com/woocommerce/woocommerce-admin/pull/5478 to create top level categories, or Buckets, for extensions to plug into.

Previously we spoke about adding logic to buckets so that singular children would end up being top level. I think we should stay away from this concept for now because it has a few assumptions built in. Lets make the first iteration as simple as possible.

### Deliverables

* Create categories going by the ones on WooCommerce.com under the "Marketplace" tab.
* Don't show a bucket if its not populated.
* Keep `wc_admin_register_page` the same. Since registration will temporarily occur in wc-calypso-bridge, we can provide an initial experience without asking extensions to change anything. This is useful in case we'd like to change the API.
* Add a default if no category is provided. Maybe at the beginning of "Extensions"?

**Comment by psealock** [comment]
@joshuatf I assigned to you since you've already made progress on this.

**Comment by pmcpinto** [comment]
This approach should be paused. I chatted a bit @elizaan36 yesterday, we're still not sure that this is the best path forward and this is one of those decisions that should be validated first with Product and Design. Pls see this comment: p90Yrv-1WM-p2#comment-4502 

Thanks!

**Comment by psealock** [comment]
Thanks, going with Plugins approach and closing this issue
