### ISSUE TITLE
Inbox notification missing about additional payments options

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5521]
**Describe the bug**
According to #4597 we should trigger an inbox notification with more info about additional payment gateways when WCPay is being installed during the profiler. But this is not happening since 4.6 was released.

**To Reproduce**

1. Create a new store
2. Choose the US as a country in the Store Details
3. Choose Fashion, apparel, and accessories as Industry
4. Install the extensions bundle in the Business details step (check that WCPay is included)
5. Visit the home screen and confirm that the inbox notification is missing

**Expected behavior**
To see an inbox notification that allows me to install other payment options.

**Comment by pmcpinto** [comment]
cc @timmyc as this should be fixed for 4.8

**Comment by timmyc** [comment]
@pmcpinto I just setup a new JN site with 4.6.1 + a test zip built from `main` of wc-admin. I went through the fashion industry to get WCPay installed by default. I can confirm when I first landed on the home screen after the OBW that the additional Payments note _was not shown_ but looked in the database, and saw the note was there.

I then did a hard refresh of the home screen page and confirmed that the inbox note was indeed then shown. So wondering if you might have hit the same flow where the note has yet to be created on your first view of the home screen:

![image](https://user-images.githubusercontent.com/22080/98027047-e6521f00-1dc0-11eb-8fb2-84b83863d713.png)

Wondering if a possible "fix" for this would be to trigger a fresh request to the notes endpoint after the final step of the OBW is completed.

**Comment by samueljseay** [comment]
@pmcpinto @timmyc if we can agree a refresh is a good solution here, I can go ahead and implement that.

**Comment by pmcpinto** [comment]
> @pmcpinto @timmyc if we can agree a refresh is a good solution here, I can go ahead and implement that.

@samueljseay sounds good to me. I just tested again and the notification was displayed after refreshing the page. Thanks

**Comment by timmyc** [comment]
Yeah I think that is a good work-around for now @samueljseay - I'm guessing we might have more inbox notes like this that get generated based upon OBW actions, so seems like a reasonable solution unless you can think of another one.
