### ISSUE TITLE
Analytics: Exception on Variations Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5536]
**Describe the bug**
While preparing some testing documentation for the release, I encountered an exception on the new Variations Report. 

![image](https://user-images.githubusercontent.com/22080/98277348-1ed23400-1f4c-11eb-92eb-7398ac1fb2d2.png)

Adding in some checks to the `@woocommerce/data` package locally allowed me to get past the exception, and have the report render:

```
diff --git a/packages/data/src/reports/utils.js b/packages/data/src/reports/utils.js
index 9e7f2e76..2be2c4c3 100644
--- a/packages/data/src/reports/utils.js
+++ b/packages/data/src/reports/utils.js
@@ -369,7 +369,9 @@ export function getReportChartData( options ) {
                }
 
                forEach( pagedData, function ( _data ) {
-                       intervals = intervals.concat( _data.data.intervals );
+                       if ( _data.data && _data.data.intervals && Array.isArray( _data.data.intervals ) ) {
+                               intervals = intervals.concat( _data.data.intervals );
+                       }
                } );
        }
```

I git blamed the above code, and looks like that hasn't changed in 2 years, so don't think this is a new exception, but perhaps something related to the variations intervals logic in the REST API.

This fix seems _okay_ but am curious if there is something with my local data that might be causing this, or also keen to see if others can reproduce this bug with the Variations Report

**To Reproduce**
For me I had to select last year as a date range to pull back some orders with variant data, so wondering perhaps if the bug is specific to longer time periods.

1. Variations Report
2. Open the date range picker and select "Last Year" as the range, or just use this url `wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fvariations&period=last_year&compare=previous_year`
3. There will likely be a few React warnings about required PropTypes to appear in your console ( which we should probably fix these too )
4. Then the exception should happen and the screen should go grey.

cc @jeffstieler

**Comment by timmyc** [comment]
Noting that I was *not able* to hit this when running the report for:

- Month compare | unit days `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fvariations&period=last_month&compare=previous_period`
- Single day compare | unit hours `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fvariations&period=custom&compare=previous_period&after=2020-10-31&before=2020-10-31`
- Week | unit days `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fvariations&period=custom&compare=previous_period&after=2020-10-19&before=2020-10-25`
- Quater | unit week, day, or month `wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fvariations&period=last_quarter&compare=previous_period`

**Comment by samueljseay** [comment]
@timmyc I just had a report today of this issue in the existing reports as well. If you go to a report and then choose the "year to date filter" the same exception arises.
