### ISSUE TITLE
Support custom actionable statuses in the new homescreen orders panel

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#5545]
As part of #5455 a bug was found with the existing orders fetching where it would flicker while trying to resolve the list of orders. This was due to a bug where the order statuses would change between renders and force the fetching of the orders twice.

For now, to resolve that issue, we have opted to use only the default order statuses, but this means that actionable statuses defined by third parties won't show in this panel for the first iteration.

Criteria: 

- [ ]  Enhance the new orders panel to support loading all defined actionable statuses when considering which orders to display. 
- [ ] Ensure that no regression of flickering is introduced.

**Comment by samueljseay** [comment]
@pmcpinto cc'ing you on this one, this issue arose during finishing the orders panel migration, I've made the call to push forward with releasing with this known caveat but we can reverse this decision if we need to. 

I'm not aware of how widespread the use of custom order statuses is, but my view was we could address this as an enhancement asap.

**Comment by pmcpinto** [comment]
Thanks. I agree that this feels more like a nice to have at this stage. The existing orders panel doesn't include custom order statues. In the meantime, I'll try to find some stats about custom order statuses creation

**Comment by pmcpinto** [comment]
About 10-15% of the orders have custom status. So I think we're good if we don't include this in this release

**Comment by octaedro** [comment]
Hi @pmcpinto and @samueljseay,
Since this was an issue "easy" to solve I created [this PR](https://github.com/woocommerce/woocommerce-admin/pull/5550) and now the solution is merged 🙂

**Comment by pmcpinto** [comment]
Awesome. Thanks for the update
