### ISSUE TITLE
Redirect to the Jetpack account creation page only happening after closing the home screen modal

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5551]
**Describe the bug**
The user is being redirected first to the home screen and the Jetpack account creation page redirect only happens after closing the welcome modal. Also, notice that the store profiler data is not being loaded if the user clicks in the browser back button

**To Reproduce**

1. Create a new store
2. Complete all the store profiler steps
3. Click "Yes please" in the Jetpack / WCS step 
4. See that you're redirected to the home screen instead of being redirected to the JP account creation page
5. Close the home screen welcome modal and see that the JP redirect only happens now
6. (bonus) click on the browser back button and see that you're redirected to the first step of the store profiler and the profiler data is not loading.

**Expected behavior**
To be redirected to the JP account creation page right after I click "Yes please" in the Jetpack / WCS step 

**Screenshots**
https://www.loom.com/share/fbd68859c3f74839a6e8bcd78072a33b

**Comment by timmyc** [comment]
I wasn't able to reproduce this myself in testing, and sounds like @pmcpinto could not either. So going to close this one out.
