### ISSUE TITLE
Setup Checklist: Exception when Clicking SnackBar Notif After Customizing Homepage

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5554]
**Describe the bug**
When testing a pre-build of 1.7.0-beta.1 I hit an issue when customizing the Home Page in the setup checklist. Upon making edits and saving the page, I clicked the link to take me back the Setup Checklist and it looks like an error in the JS console happened around tracks.

IIRC I did not opt into usage tracking, so guessing that might have something to do with it.

Setup: New JN Site, Woo 4.6.2, 1.7.0-pre-beta, Gutenberg Plugin, Safari

**To Reproduce**

1. Go through OBW
2. On the Customize Store task, create the homepage
3. Then customize the home page
4. After saving the page, click on the link in the snackbar notif to take you back to the homescreen.
5. See the error in the JS console

**Expected behavior**
To be redirected back to the home screen.

**Screenshots**
<img width="2218" alt="1 7 0-beta-1-safari-14-homepage-notif-error" src="https://user-images.githubusercontent.com/22080/98420529-41437a80-203c-11eb-8f84-b7308d1d52cf.png">

**Comment by timmyc** [comment]
I tested this same flow in 4.6.x and verified this bug exists there too. So this is not a recent regression in 1.7.0. Would be nice to fix, but going to give this a low priority over other bugs introduced in 1.7 and those around new features.

__WooCommerce 4.6.2 / WC Admin 1.6.2__
https://cloudup.com/cguJSKQnSMg

**Comment by becdetat** [comment]
@timmyc I'm having trouble getting to the customize homepage screen. Do you get to it via the "Personalize my store" task? When I try to customise the homepage it just spins for a little while then moves to the next task:
![image](https://user-images.githubusercontent.com/224531/98752269-95b87280-240d-11eb-854a-9d16ac071060.png)
If I refresh the page the custom homepage task doesn't appear at all.

**Comment by timmyc** [comment]
@becdetat yes sorry, this is kind of an obscure flow to follow. After the Create Custom Homepage task is completed, a SnackBar notice is shown that has a link to customize the page further. I think you have to follow that link in order to get the exception to occur.

**Comment by louwie17** [comment]
Found that issue was also present when _tracking_ was enabled, issue seemed to be with package context, as this code lives outside of the WooCommerce Admin context, and requires it's dependencies to be specifically defined. As [stated here](https://github.com/woocommerce/woocommerce-admin/blob/main/client/wp-admin-scripts/README.md)

As a fix will be adding `wc-tracks` as a dependency [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks.php#L255)
