### ISSUE TITLE
Navigation: Collapse menu on resize event

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5557]
The functionality to collapse the menu on small viewports should function on screen resize.

### Deliverables

* Resizing the screen should collapse/uncollapse the navigation

**Comment by joelclimbsthings** [comment]
@psealock Is this expected to auto-extend the menu if the screen size is larger than ~960px after a resize? Right now, with `orientationchange` event, we're currently supporting auto-collapsing when the viewport is made smaller, but don't respond to the viewport being made larger in any way.

**Comment by psealock** [comment]
>Is this expected to auto-extend the menu if the screen size is larger than ~960px after a resize?

Yeah, thats my understanding
