### ISSUE TITLE
Variations Report: Not all attributes available in advanced filters

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5560]
Some attributes are not available when using advanced filters.

I noticed this when using Woo's sample products, but went ahead and created my own variable product from scratch and noticed the same thing.

wc-admin [1.7.0-beta.1 ](https://github.com/woocommerce/woocommerce-admin/releases/tag/v1.7.0-beta.1)
woocommerce Version 4.6.2
Jurassic Ninja site

1. Create an order using Woo's sample product data variable Hoodie `/product/hoodie/?attribute_pa_color=green&attribute_logo=No`.
1. Confirm the Hoodie has variations "Logo" and "Color" in the Edit Product screen.
![Screen Shot 2020-11-09 at 2 41 49 PM](https://user-images.githubusercontent.com/1922453/98492226-0dff2680-229c-11eb-8fe1-4410569db953.png)
2. See the data from the purchase available in the Variations Report.
3. Advanced Filters > Add a filter > Attribute
4. See the "logo" attribute not available in the dropdown.
![Screen Shot 2020-11-09 at 2 41 36 PM](https://user-images.githubusercontent.com/1922453/98492319-5c142a00-229c-11eb-826f-d00feff8b732.png)

**Comment by jeffstieler** [comment]
Thanks for creating this issue @psealock! It had only been previously captured here: https://github.com/woocommerce/woocommerce-admin/issues/5384#issuecomment-709280308

**Comment by timmyc** [comment]
@jeffstieler do you have an ballpark on the level of effort to include non-global attributes? Seems like that could really be a non-performant query.

**Comment by jeffstieler** [comment]
> @jeffstieler do you have an ballpark on the level of effort to include non-global attributes? Seems like that could really be a non-performant query.

I haven't looked into it too deeply, but from what I recall it would require querying/parsing the `meta_value`s for all `_product_attributes` meta keys - so yeah... the potential for poor performance is quite high.

**Comment by timmyc** [comment]
Thanks for confirming my suspicions a bit. Based upon that, I'm going to clear this issue from the milestone. I suppose one thing we should do is make sure this known issue is part of the [Variations Report Doc](https://github.com/woocommerce/woocommerce-admin/blob/main/docs/woocommerce.com/analytics-variations-report.md) and also include this as a note to Happiness and maybe call it out in the 4.8 release post too where the new report will likely be called out as a new feature.

**Comment by jeffstieler** [comment]
@timmyc are we amenable to a new lookup table to support this feature? I'm thinking something akin to the `wc_category_lookup` table, but for custom/one-off attributes.

**Comment by jeffstieler** [comment]
Another potential solution might be to allow free text searches in the filter control.

**Comment by timmyc** [comment]
I think that sounds like a reasonable solution, but that sounds like a bit of an involved addition - so we should probably try to gauge the level of effort and see if we want to prioritize for a future sprint.

**Comment by jeffstieler** [comment]
Sorry for the lack of a follow up - I figured out a way to do this without a new table and am forging ahead.
