### ISSUE TITLE
Onboarding Wizard fails to install additional plugins with WooCommerce 3.6

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#5561]
**Describe the bug**

When WooCommerce v3.6 is installed, the onboarding wizard fails to install additional plugins.

**To Reproduce**

1. With a fresh site, install [WooCommerce 3.6](https://github.com/woocommerce/woocommerce/releases/tag/3.6.5) and WooCommerce Admin 1.7 beta 1.
2. Complete the activation wizard up to "Tell us a about your business"
3. On the "Tell us about your business" screen, complete the required fields and ensure additional plugins are selected to be installed.
4. Attempt to continue to next screen and see error.

**Expected behavior**

The additional plugins installed successfully.

**Screenshots**

![Screen Shot 2020-11-09 at 10 23 37 am](https://user-images.githubusercontent.com/9312929/98493546-aa620280-2275-11eb-8e24-5473e0745c94.png)

**Desktop (please complete the following information):**

* OS: macOS 10.14
* Browser Safari 14 & Chrome 86

**Comment by timmyc** [comment]
@adrianduffell thanks for testing back to 3.6!!! Was this the only issue you encountered? I'm personally thinking we should bump the min Woo version to _at least_ 4.0, but am thinking that maybe even 4.5 would be fine. @pmcpinto thoughts?

**Comment by adrianduffell** [comment]
@timmyc No problem, I only did a small amount of smoke testing against v3.6 but this was the only issue I encountered.

Agreed we could bump the min version to resolve the issue. I just tested and the additional plugins install correctly for v4.0 and v4.5.

**Comment by pmcpinto** [comment]
> I'm personally thinking we should bump the min Woo version to at least 4.0, but am thinking that maybe even 4.5 would be fine. @pmcpinto thoughts?

What's the biggest risk of bumping to 4.5 instead of 4.0?

**Comment by timmyc** [comment]
> What's the biggest risk of bumping to 4.5 instead of 4.0?

In the context of this issue, not much. If a site running an older version of Woo installs the wc-admin plugin, the Jetpack Autoloader will default to using the plugin version over the packaged version. But the site is likely already "setup" and wouldn't be impacted by the issue.

Overall I think this is more of a policy we need to adopt with the plugin and which versions of Woo we "support". I feel more than okay doing current release  - 3, so 4.5 seems quite generous to me. Ultimately wc-admin is part of Woo Core, so it seems like we should only have to support the latest version ;)

**Comment by timmyc** [comment]
^ PR to bump min supported woo version to 4.5
