### ISSUE TITLE
Nav jumps to Tools/Utilities after creating new product or order

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5575]
**Describe the bug**
After you create a new product or order, the new nav jumps to **Tools > Utilities**.

**To Reproduce**
1. Create a new product or order.
2. Click "Publish".
3. See nav jump to **Tools > Utilities**

**Expected behavior**
The navigation should stay on the existing item, `Add product` or `Add order`.

**Screenshots**
<img width="1022" alt="Screen Shot 2020-11-09 at 3 45 25 PM" src="https://user-images.githubusercontent.com/5121465/98600537-553ce580-22a3-11eb-921d-8ceebe2981bb.png">

<img width="1180" alt="Screen Shot 2020-11-09 at 3 32 39 PM" src="https://user-images.githubusercontent.com/5121465/98600546-59690300-22a3-11eb-9de0-0c41e9bfb6bb.png">

**Desktop (please complete the following information):**

* Tested on Chrome, Firefox, and Vivaldi.

**Comment by joshuatf** [comment]
I think this is due to the lack of matching URLs and how we try to "fuzzy" match active menu items.  Are we thinking the "Orders" menu item would remain active when on a specific order?  And if so, would this be true of all custom post types (show the main page as active when on a single item)?

Note that the "Add Order" item will be resolved by https://github.com/woocommerce/woocommerce-admin/issues/5539

**Comment by elizaan36** [comment]
> Are we thinking the "Orders" menu item would remain active when on a specific order?

Yeah, the "Orders" menu item should still be active when you're on "Edit Order". Ideally we can get the back button in the top bar soon to make that connection more clear for people. That was discussed in [this issue](https://github.com/woocommerce/woocommerce-admin/issues/3963).

> And if so, would this be true of all custom post types (show the main page as active when on a single item)?

Yes, I can't think of any reason why not. Can you think of any edge cases where it wouldn't work?

**Comment by elizaan36** [comment]
> Note that the "Add Order" item will be resolved by #5539

**Comment by joshuatf** [comment]
>Yes, I can't think of any reason why not. Can you think of any edge cases where it wouldn't work?

I currently can't either.  Seems like a reasonable change and we can re-address if we run into any exceptions in the future.
