### ISSUE TITLE
Navigation: Try to explore less brittle methods of assembling core menu items from post types

### ISSUE THREAD

**Issue by joelclimbsthings** [woocommerce/woocommerce-admin#5588]
**Describe the bug**

Right now, in the file `src/Features/Navigation/CoreMenu.php` we're manually addressing post type objects by index in order to add them to the navigation. As mentioned on [this earlier PR](https://github.com/woocommerce/woocommerce-admin/pull/5574) this could be fairly brittle and prone to breaking in the future, so we should explore better methods of adding these. 

![image](https://user-images.githubusercontent.com/444632/98710728-e8742a80-2338-11eb-8ed3-7f3228da1e2f.png)

**Comment by joshuatf** [comment]
@psealock @joelclimbsthings What do we consider brittle about this?  Is it purely the index used in response?  If so, we can update this return an associative array.

It would be great to address this sooner rather than later since I'm planning to use this in a separate repo in https://github.com/woocommerce/woocommerce-subscriptions/pull/3868

**Comment by joelclimbsthings** [comment]
Yes, it was primarily the addressing by index that _seemed_ brittle to me, and just a bit less clear in the code, but my guess is that this array is expected to be very stable? 

I'd support the change to associative array, that said.

**Comment by joshuatf** [comment]
I agree that sounds like a more stable way to reference the items.  Will put out an update- @psealock if you have any other areas of this you were wanting to change, feel free to chime in and I can update the PR accordingly.

**Comment by psealock** [comment]
+1 to the associative array. It may not have been brittle, but when reading the code it wasn't too clear and _felt_ brittle.
