### ISSUE TITLE
Fix data resolution strategies in the code base

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#5597]
Recently it was discovered that we have perpetuated a pattern with checking resolution status of data in React that is an anti-pattern. 

The anti pattern involves synchronously calling `isResolving` for some data straight after fetching it via a resolver. Due to state updates often being asynchronous, isResolving will not always accurately reflect whether resolution is in progress.

See https://github.com/woocommerce/woocommerce-admin/pull/5581 as an example of how this might be approached differently.

The idea of this issue is to hunt down places where we use this pattern and replace them with better patterns.

**Comment by adrianduffell** [comment]
I like the approach in the PR to use `hasFinishedResolution` since it more explicit. Does it still remain `false` if the resolver has an error fetching the data?

**Comment by samueljseay** [comment]
Closing this as I think it is just something we can be aware of going forward when we spot problems.
