### ISSUE TITLE
Fix Set up additional payment providers notice logic

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5601]
**Describe the bug**
The `Set up additional payment providers` inbox notice should only be triggered when WCPayments is installed in the store profiler. Currently is being triggered whenever WCPayments is installed: https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/SetUpAdditionalPaymentTypes.php

**To Reproduce**

1. Create a new store
2. Complete the store profiler with the US as location and Electronics and Computers as Industry
3. Install WooCommerce Payments through the Payments task
4. See the `Set up additional payment providers` inbox notice: https://d.pr/i/9Yiz1o

**Expected behavior**
To only see the `Set up additional payment providers` inbox notification when WCPayments is installed in the store profiler.

**Comment by timmyc** [comment]
I chatted with Pedro about this one today. I'm thinking we might be able to adjust the logic in the `onAcitvateWcpay()` [method](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/SetUpAdditionalPaymentTypes.php#L52) to check and see if WCPay was installed during the OBW via the `woocommerce_onboarding_profile` option data.

The logic would then be:

- If WCPay is included in the `woocommerce_onboarding_profile.business_extensions` array, show this note
- If WCPay is *not* in that list of extensions installed during the OBW, do not add this note.

**Comment by pmcpinto** [comment]
@timmyc just to confirm, this is going to be included in the wcadmin version shipped in WC 4.8, correct? Assuming that we'll ship a 1.7 fix release in the meantime
