### ISSUE TITLE
Add statistics "by payment method"

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce-admin#5625]
Hello,

It would be great to have a way to view turnover also summed by payment methods.

(Please correct me, if this is already possible, I just can't find this).

**Comment by Jussi-Korhonen** [comment]
Filterin out specific payment options, such as COD would be welcome indeed. Would be great to get this to move forward!

**Comment by ilyasfoo** [comment]
Closing this as this issue wasn't prioritized, we probably could revisit it in the future as I think it is a useful feature for merchants.
