### ISSUE TITLE
Undefined index: id in Loader.php:1019

### ISSUE THREAD

**Issue by BrianHenryIE** [woocommerce/woocommerce-admin#5631]
**Describe the bug**

Our logs are full of lots of:

```
PHP Notice:  Undefined index: id in /path/to/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Loader.php on line 1019
PHP Notice:  Undefined index: value in /path/to/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Loader.php on line 1019
```

[where Loader.php is preloading options](https://github.com/woocommerce/woocommerce-admin/blob/9c43b6fb8309ed3d366ba9466635d7db03075a3d/src/Loader.php#L1019).

I added in some extra logging:

`error_log((new Exception())->getTraceAsString());`

```
#0 /path/to/wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Admin\Loader::add_component_settings(Array)
#1 /path/to/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#2 /path/to/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(131): apply_filters('woocommerce_sha...', Array)
#3 /path/to/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(222): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->initialize_core_data()
#4 /path/to/wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->enqueue_asset_data('')
#5 /path/to/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#6 /path/to/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /path/to/wp-admin/admin-footer.php(95): do_action('admin_print_foo...')
#8 /path/to/wp-admin/edit.php(464): require_once('/home/customer/...')
#9 {main}
```

`error_log( $group );`

```
general
```

`error_log( json_encode( $group_settings) );`

```
{
	"errors": {
		"rest_setting_setting_group_invalid": ["Invalid setting group."]
	},
	"error_data": {
		"rest_setting_setting_group_invalid": {
			"status": 404
		}
	}
}
```

**To Reproduce**

~~Refresh a page. Orders page is a sure one. Probably more.~~

Refresh the admin orders list page.

**Expected behavior**

Clean logs.

**Environment:**

WooCommerce 4.7.0
Siteground WordPress hosting.
PHP 7.3

**Comment by moon0326** [comment]
@BrianHenryIE Thank you for submitting your bug report.

I was not able to reproduce the error with a fresh installation of WordPress + WooCommerce. However, I can see how this can happen since there is no error handling logic when an invalid group setting I.D is given. We will work on a fix.

**Comment by moon0326** [comment]
@BrianHenryIE Thank you for submitting your bug report. 

I was not able to reproduce the error with a fresh installation of WordPress + WooCommerce. However, I can see how this can happen since there is no error handling logic when an invalid group setting I.D is given. We will work on a fix.

**Comment by moon0326** [comment]
@BrianHenryIE  Hi :) 

Could you do me a favor, please? I would like to find out what's causing this error before we push out a fix.

1. Could you send me a list of activated plugins? You can get it by navigating to `Tools -> Site Health -> Info` and click [ Copy site info to clipboard ].
2. It would be also very helpful if you can print out the contents of `$preload_settings` variable in `Loader.php`. You can use the following snippet.

```
$preload_settings = apply_filters( 'woocommerce_admin_preload_settings', array() );
error_log( json_encode( $preload_settings) );
```

Thank you,
Moon

**Comment by dougaitken** [comment]
As a note, a customer came across this error and reached out in Live Chat - 25863716-hc - they let us know that deactivating and reactivating the core WooCommerce plugin removed the error

**Comment by moon0326** [comment]
@dougaitken  Thank you! I will read through the ticket and test it myself.

**Comment by BrianHenryIE** [comment]
Hi again, sorry for the delay.

I disabled our 70 plugins and enabled them one by one, refreshing the admin orders list page each time and checking the log file!

The problem is with the [WooCommerce Anti Fraud](https://woocommerce.com/products/woocommerce-anti-fraud/) plugin version 3.3 (latest), WooCommerce 4.7.1 & 4.8.0, and WordPress 5.5.3 (when no other plugins are active). Also occurs with WooCommerce Admin 1.7.2 plugin active.

I'll file a bug report with them too.

**Comment by BrianHenryIE** [comment]
An update has been released to WooCommerce Anti Fraud to address this problem. [Their changelog](https://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-anti-fraud/changelog.txt) says:

> 2020-12-17 version 3.4
>* PLUGINS-837 - Bug fixed: Filter on settings cause notice errors in Woocommerce Admin plugin

I haven't had time to make a diff to understand/explain it more (and probably won't unless someone is interested).
