### ISSUE TITLE
Data labels not translated

### ISSUE THREAD

**Issue by stephhjacq** [woocommerce/woocommerce-admin#5632]
3466520-zen

**Describe the bug**
On the page at Analytics > Revenue, the data labels do not follow the site language

**To Reproduce**

1. Change site language to something other than English, such as French
2. Click on Analytics > Revenue (Statistique > Revenu)
3. Data labels are not translated

**Expected behavior**
The data labels match the site's language

**Screenshots**
Labels in English:

![https://d.pr/i/VQ6oKw](https://d.pr/i/VQ6oKw+)
Full Image: https://d.pr/i/VQ6oKw

Translation is up to date
![https://d.pr/i/UYJgu3](https://d.pr/i/UYJgu3+)
Full Image: https://d.pr/i/UYJgu3

Labels shown correctly on Statistique > Vue d'ensemble
![https://d.pr/i/zDCMAD](https://d.pr/i/zDCMAD+)
Full Image: https://d.pr/i/zDCMAD 

**Desktop (please complete the following information):**

* OS: Mac OS Catalina
* Browser Chrome
* Version 86.0.4240.193

**Additional context**
I tried flushing the cache and clearing transients, but get same result. WooCommerce is the only plugin active.

**Comment by moon0326** [comment]
@stephhjacq Hi, thank you for submitting the bug report.

I've read through the Zendesk ticket and tried to reproduce it on three installations of WordPress + WooCommerce, but I wasn't able to reproduce it. 

Could you do me a favor and download the .po file from test site?

1. Navigate to Logo Translate -> Languages
2. Click on `French (France)`
3. Scroll down to the `Plugins` section and click on "WooCommerce"
4. Click on the PO download button (red square)
![Screen Shot 2020-11-18 at 8 47 55 PMth_](https://user-images.githubusercontent.com/4723145/99622660-75754e80-29df-11eb-95fb-54ea26890585.jpg)
5. Attach the file.

Thanks!
Moon

**Comment by stephhjacq** [comment]
Thanks for looking into this @moon0326 

When I went to download the PO file for you, I saw there was an update from yesterday. I've downloaded the historical file that was there before updating, for your reference.

I then updated the file, and saw over 1300 strings added. Now, when I go to check the report, the translation is complete. 

I will update the user to see if this is the same for them. 

[woocommerce-fr_FR.po.zip](https://github.com/woocommerce/woocommerce-admin/files/5570233/woocommerce-fr_FR.po.zip)

**Comment by moon0326** [comment]
@stephhjacq That's nice! Thank you 👍

**Comment by jessLundie** [comment]
Hi @moon0326 -

I'm working on this ticket and have tried the following on the customer's site with no success:

1. Re-sync Loco Translate
2. Reinstall WooCommerce v. 4.7.0 via FTP
3. Resync again
4. Activate / deactivate Loco Translate - no change either way

I was able to replicate this issue on two local test sites by updating WooCommerce to 4.7.0 with Loco Translate installed, but not active. One updated from WC 3.7.0, the other from WC 3.8.0. After updating my test site, I was not given any prompt to update translations via Dashboard > Updates - it just said all was up to date.

In Loco Translate on both of my test sites - where I am still seeing English in Analytics - I see this for translation for WooCommerce:

![https://d.pr/i/QgDDb6](https://d.pr/i/QgDDb6+)
Full Image: https://d.pr/i/QgDDb6

Customer's site:

![https://d.pr/i/ItrYiy](https://d.pr/i/ItrYiy+)
Full Image: https://d.pr/i/ItrYiy

I was not able to download the po file from the customer's site - it gave me a 404 error. Here is the po from one of the test sites where I was able to replicate this: 
[woocommerce-fr_FR.po.zip](https://github.com/woocommerce/woocommerce-admin/files/5586079/woocommerce-fr_FR.po.zip)

Any insight you can offer here would be so appreciated!
