### ISSUE TITLE
Unify naming convention for front-end files

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#5637]
_The discussion started at https://github.com/woocommerce/woocommerce-admin/pull/5611#issuecomment-726428767_

## **Is your feature request related to a problem? Please describe.**
AFAIK, we do not have written guidelines and conventions for naming front-end related files, in this plugin and in A8C in general. Currently, this plugin uses inconsistent approach:
 - some files that exports a single class, uses 
   - class name as filename, like [`ReadBlogMessage.js`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/marketing/components/knowledge-base/ReadBlogMessage.js)
   - some other common short name, like [`placeholder.js`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/header/activity-panel/activity-card/placeholder.js), and that name is re-used across many components (11 files).

As per https://github.com/woocommerce/woocommerce-admin/pull/5611, soon we will end up with even more `placeholder.js`es

Personally, I don't like having different files with different classes called the same way. It makes file searching harder <kbd>Ctrl</kbd> + <kbd>p</kbd>. In some previous projects, I used to work with conventions to call the file like the class it defines if it defines only one, or at least give it a somewhat-specific module name - `ActivityCardPlaceholder`.

@ecgan [shared the same concern](https://github.com/woocommerce/woocommerce-admin/pull/5611#issuecomment-727893067) for `index.js` and `style.scss` files
> I share the same opinion with you too. An example: when we do `CTRL + P` and search for `index.js`, a lot of files show up, including those from test folders. Also, it makes reading the editor tab title more difficult and takes up more space. Same thing goes with `style.scss` files.

## **Describe the solution you'd like**

In my opinion, files like `style.scss`, `index.js`, `placeholder.js` are fine when we are working in the context of a single specific module/component. They are short, descriptive enough, and unambiguous if we are in already narrowed scope. However, at the scale of dozens of components, it's no longer the case.

### 1. Component's additional JS file (`placeholder.js`)
Sometimes the component JS code is divided into many files, to make development easier to manage and more granular. That is the case for example for all `placeholder.js` files. I suspect the motivation behind calling it that way was to have the name short and describe its role. In my opinion, these should also be characteristics of the export's name.
 
As we maintain this module in a mono-repo with other components, I believe using a more specific and unambiguous name would improve DevX, like `ActivityCardPlaceholder.js`. Which is the default export name, or in general "module" name.

For example, when some other file uses
```js
import placeholderWhiteBackground from `./placeholder.js`;
import placeholderDarkBackground from `../placeholder.js`;
```
The developer that sees that could save some cognitive load on thinking which placeholder is which.

### 2. Main component JS entry point `index.js`
I suspect the use of it comes from the React and CommonJS convention that if you `import smth from "./path/to/folder"` it resolves it to `import smth from "./path/to/folder/index.js"`. Which is a sugar that derives from the very Web convention of `index.html` files. I appreciate its convenience and don't want to argue with that.

I see that for the cases when a component has many JS files, there is a single `index.js` that gathers them all to serve as the main entry point and the default export.
```
 . ActivityCard/
 +-- ActivityCardPlaceholder.js
 +-- ActivityCard.js
 +-- CutePuppy.js
 +-- index.js
```
Then someone who imports the `ActivityCard` would not have to bother which file to import, would just use `index.js` as default.

However, I'd prefer if the main code of ActivityCard would be in `ActivityCard.js`, and `index.js` would only gather `import`s and `export`s. Maybe with an exception where there is only one `.js` file, so we would not have to create `index.js` only to forward the `exports`.

### 3. Component styles `style.scss`

I think that `style` brings absolutely no ore information that `.scss` does :) So why can't we use the filename to actually bring some value?

## **Describe alternatives you've considered**
Alternatively, we could stick to the existing `index.js` and `style.scss`, and get used to having IDE with 4 tabs named `style.scss` and 3 `index.js` ;) 

But either way we go, it would be nice to have it written somewhere, like `CONTRIBUTING.md`, to at least have it consistent.

Also, if somebody has some VS Code extension that replaces `index.js` with `1stContainingFolder/index.js` I'd really appreciate this being mentioned here and in the readme 🙏 

## **Should this be prioritized? Why?**

No rush I think. 

## **Additional comments**
The main downside of the proposal above I see is the verbosity and redundancy between folder and file name: `ActivityCard/ActivityCard.js`. But if I'm about to make a trade off between
- duplicating module name `ActivityCard` in a folder and main file name **once when created**,
and 
- having to waste my cognitive load **every time I look** at the filename of the file I edit or import
I prefer to pay the first one, once.

Note, 
 - if we are using `index.js` to gather exports, `import * from "./ActivityCard";` is still enough, and you don't have to duplicate it, like `import * from "./ActivityCard/ActivityCard";`
 - IDEs should help out with typing long filenames

**Comment by adrianduffell** [comment]
Hi @tomalec ,
​
Thank you for taking the time to report this. We are going to discuss the topic internally as a team.

**Comment by tomalec** [comment]
FWIW, The issue was discussed also on P2 p6q8Tx-1Uk-p2

**Comment by samueljseay** [comment]
All of this seems pretty sane to me, I also have been trying to get us to move to named exports because I think it solves some of these problems when VSCode autofills imports for you.

My only issue is that I don't see this gaining traction as a cooldown task right now because it would be a large migration task with medium risk of breaking something. I wonder if this could morph into a written standard for code we write going forward instead.

**Comment by joelclimbsthings** [comment]
Agreed @samueljseay . I'd planned to dive in a bit more and produce a P2 with a bit more `wc-admin` specific context during the cool-down but I ran out of time. I'm still glad to do so for the next cool-down (or if I find the time sooner) and then we can generate some next steps from there. 

Feel free to jump in as well if you like.

**Comment by joelclimbsthings** [comment]
Created a recent P2 post which I consider the primary deliverable for this issue, so further discussion/actions will take place there. 

p90Yrv-2d4-p2
