### ISSUE TITLE
Problem with adding new product

### ISSUE THREAD

**Issue by MKRoaster** [woocommerce/woocommerce-admin#5639]
**Describe the bug**
Woocommerce 4.7:

When i'm opening page to add new product, and i see, that page loading is block because of `/wp-json/wc-analytics/admin/notes?page=1&per_page=25&type=error%2Cupdate&status=unactioned&_locale=user` script, which calls for:

``I	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
tryCatch	@	wp-polyfill.min.js?ver=7.4.4:1
invoke	@	wp-polyfill.min.js?ver=7.4.4:1
t.<computed>	@	wp-polyfill.min.js?ver=7.4.4:1
n	@	api-fetch.min.js?ver=8773a93…:2
a	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
G	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
p	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
G	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
p	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
t	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
C	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
(anonymous)	@	api-fetch.min.js?ver=8773a93…:2
R	@	api-fetch.min.js?ver=8773a93…:2
API_FETCH	@	data-controls.min.js?ver=59b9a16…:2
(anonymous)	@	redux-routine.min.js?ver=9c464c6…:2
(anonymous)	@	redux-routine.min.js?ver=9c464c6…:2
e	@	redux-routine.min.js?ver=9c464c6…:2
(anonymous)	@	redux-routine.min.js?ver=9c464c6…:2
c	@	redux-routine.min.js?ver=9c464c6…:2
t	@	redux-routine.min.js?ver=9c464c6…:2
(anonymous)	@	redux-routine.min.js?ver=9c464c6…:2
(anonymous)	@	redux-routine.min.js?ver=9c464c6…:2
(anonymous)	@	redux-routine.min.js?ver=9c464c6…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
tryCatch	@	wp-polyfill.min.js?ver=7.4.4:1
invoke	@	wp-polyfill.min.js?ver=7.4.4:1
t.<computed>	@	wp-polyfill.min.js?ver=7.4.4:1
n	@	data.min.js?ver=75f9035…:2
c	@	data.min.js?ver=75f9035…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
ee	@	data.min.js?ver=75f9035…:2
Z	@	data.min.js?ver=75f9035…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
tryCatch	@	wp-polyfill.min.js?ver=7.4.4:1
invoke	@	wp-polyfill.min.js?ver=7.4.4:1
t.<computed>	@	wp-polyfill.min.js?ver=7.4.4:1
n	@	data.min.js?ver=75f9035…:2
c	@	data.min.js?ver=75f9035…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
s	@	data.min.js?ver=75f9035…:2
a	@	data.min.js?ver=75f9035…:2
u	@	data.min.js?ver=75f9035…:2
(anonymous)	@	index.min.js?ver=1.6.3:2
(anonymous)	@	index.min.js?ver=1.6.3:2
(anonymous)	@	data.min.js?ver=75f9035…:2
Fe	@	data.min.js?ver=75f9035…:2
(anonymous)	@	data.min.js?ver=75f9035…:2
je	@	react-dom.min.js?ver=16.9.0:78
ph	@	react-dom.min.js?ver=16.9.0:215
lh	@	react-dom.min.js?ver=16.9.0:126
O	@	react-dom.min.js?ver=16.9.0:121
Sb	@	react-dom.min.js?ver=16.9.0:213
wh	@	react-dom.min.js?ver=16.9.0:160
fd	@	react-dom.min.js?ver=16.9.0:160
(anonymous)	@	react-dom.min.js?ver=16.9.0:163
kh	@	react-dom.min.js?ver=16.9.0:119
id	@	react-dom.min.js?ver=16.9.0:163
render	@	react-dom.min.js?ver=16.9.0:228
(anonymous)	@	index.min.js?ver=1.6.3:2
521	@	index.min.js?ver=1.6.3:2
o	@	index.min.js?ver=1.6.3:2
wc.app.0	@	index.min.js?ver=1.6.3:2
(anonymous)	@	index.min.js?ver=1.6.3:2`
`

I'm waiting about 15-20s because of it

**To Reproduce**

1. Add new product (it happening whe you opening this page)
2. Open dev tool in browser
3. Go to Network
4. You will see problems with load

**Expected behavior**
Script should not block page loading

**Screenshots**
![pic-wc](https://user-images.githubusercontent.com/36403678/99279618-b3804000-2830-11eb-9473-8df267d00993.jpg)

**Desktop (please complete the following information):**

* OS: Ubuntu 20.10
* Browser: Chrom, Opera

**Comment by adrianduffell** [comment]
Hi @MKRoaster ,
​
Thank you for taking the time to report this bug, we really appreciate your help. 

I wasn't able to reproduce the issue on my end. Could you please provide a [System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) here to help investigate this further?
