### ISSUE TITLE
Chart component is not displayed in the storybook.

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#5640]
**Describe the bug**
I was trying to explore, see a demo of, and fiddle with the `Chart` component. I noticed there is a [`.../chart/docs/example.js`](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/chart/docs/example.js) so I tried using that test data to the element on my page, but it failed. Then I discovered that after building a storybook, the Chart element is not displayed there.

**To Reproduce**

1. `npm run storybook`
2. Go to http://localhost:6007/
3. Search for "Chart"

**Expected behavior**
The component should be there with a demo example.

**Screenshots**
![image](https://user-images.githubusercontent.com/17435/99291128-9c951a00-283f-11eb-83be-632f9e68b9c1.png)

**Desktop (please complete the following information):**

* OS: iOS Version 10.15.7
* Browser Chrome
* Version `6.0.4240.198 (Official Build) (x86_64)`

**Comment by chihsuan** [comment]
I'm closing this since I can see the 'chart' in the storybook on the main branch now.

![Screen Shot 2022-01-13 at 16 21 31](https://user-images.githubusercontent.com/4344253/149292581-7bbfc711-5d86-44d6-a3e8-7c9fdeded75b.png)
