### ISSUE TITLE
PHP unit tests fail to run locally

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#5656]
**Describe the bug**
When trying to run `composer test` within VVV on my local machine it doesn't do anything, nor shows any errors.

Reason seems to be because of this [line](https://github.com/woocommerce/woocommerce-admin/blob/main/tests/bootstrap.php#L58) which contains `defined( 'ABSPATH' ) || exit;`. ABSPATH is undefined and thus it exists the tests.
This line was added to fix Travis builds in this PR: https://github.com/woocommerce/woocommerce-admin/pull/5603

**To Reproduce**

1. Try running `composer test` in your local environment with the latest of `main`
2. It should immediately be finishing.

**Expected behavior**
It should successfully run all the php unit tests.

**Comment by joshuatf** [comment]
Argh, it's back. https://github.com/woocommerce/woocommerce-admin/issues/2901

Such an easy bug to introduce.

**Comment by adrianduffell** [comment]
This was fixed in PR https://github.com/woocommerce/woocommerce-admin/pull/5650
