### ISSUE TITLE
Navigation: Make sure persisted queries are present on wc-admin links

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5684]
Persisted queries are query parameters that remain when navigating from report to report. They include things like `period` so users can view reports from the same vantage point.

https://github.com/woocommerce/woocommerce-admin/blob/2a382d72b85ada88df28005f91910294909587c6/packages/navigation/src/index.js#L42-L51

In the old nav, we update the links so that those query parameters are present when they should be.

https://github.com/woocommerce/woocommerce-admin/blob/2a382d72b85ada88df28005f91910294909587c6/client/layout/controller.js#L214

The new Nav needs to also have those parameters present.

### Deliverables

* When looking at a report with any of the persisted queries in the url, any link to another report or overview page should also include those parameters.

**Comment by joshuatf** [comment]
Did a little digging into this and it seems like the persisted queries are already added to the URL:
https://github.com/woocommerce/woocommerce-admin/blob/881467029a22f69e5a9be3a6f7159de0be8bce5f/client/layout/navigation.js#L42

The problem is that this component does not seem to re-render.  Even introducing our listener `addHistoryListener` and/or state to try and force this does not kick off a rerender.  Is there something special that needs to be done when a plugin is registered via `registerPlugin` or will we have to do something like `unregisterPlugin` and then re-register in history change? 😱

**Comment by psealock** [comment]
In our classic Nav, we update the urls on every page render using DOM manipulation 

https://github.com/woocommerce/woocommerce-admin/blob/d5c2f889199f0f24dd2ef709fb45892c76ed3021/client/layout/controller.js#L186

Maybe we can use the Context API to keep track of persistedQueries? At the very least, we can use the same function to update the items, although that feels very dirty to me.

**Comment by joshuatf** [comment]
Ya, I agree that  we should avoid updating the DOM manually if possible.  Passing the persisted query via context seems like a good option.

**Comment by joelclimbsthings** [comment]
Hey @psealock , @joshuatf ,

I've attached two potential PRs to resolve this issue. 

I managed a relatively simple quick fix using the history listener and a state change (not sure why this didn't work for you, Josh?), although I still have a soft spot for the router-based approach. 

**Router Based** ([link](https://github.com/woocommerce/woocommerce-admin/pull/5860))
- Consolidates logic for managing persisted queries, removing navigation-specific implementations
- No more DOM manipulation or functions added to `window`
- Could potentially support any other added features in the future without added logic.
- Currently doesn't support navigating to excluded screens and back (although I could actually fix this simply by removing the excluded screen logic, and it would function the same as the other approach)
- Touches fundamental logic that could impact other parts of `wc-admin` (although it shouldn't)

**Simple fix** ([link](https://github.com/woocommerce/woocommerce-admin/pull/5883))
- Doesn't touch any unrelated logic, minimal change
- Retains DOM manipulation/etc, and separate logic for old and new navigation
- Keeps the persisted query parameters in the URL even when navigating to other pages (for good or bad)

**Comment by adrianduffell** [comment]
> Con: Currently doesn't support retaining persisted queries when opening pages in new tabs from the navigation (ie middle-click). This could be addressed by actually merging both PRs.

This is a big con for me since I think as a user I would expect middle-click to open the same page as a normal click.

That said, I do lean towards the router approach, especially because of "No more DOM manipulation or functions added to window" 🙂

**Comment by psealock** [comment]
Very nice! And thanks for the run down of alternating approaches.

The Router based solution is great, but I'm wondering if its an optimisation for a problem that hasn't yet presented itself. In other words, removing the DOM manipulation and consolidating the logic is a nice improvement but I'm not sure warrants the modification of `history.push`. Changing the DOM certainly isn't ideal, but its a solution that will eventually disappear as Nav takes over. Besides persisted queries not being added when opening links on a new tab, they aren't visible on when hovering over links either.

The Simple Fix is working well for me and solves the issue at hand. Personally, I'm ok with the dual solutions and keeping the DOM manipulation around until the old nav is removed.

I see your point about the exclude logic not being applied. I think there is a solution to that, which I'll speak to on the PR.
