### ISSUE TITLE
Add columns to client-side generated CSV

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#5688]
**Is your feature request related to a problem? Please describe.**
I can't add columns to the CSV generated from an analytics table - the `woocommerce_report_[REPORT]_export_columns` and `woocommerce_report_[REPORT]_prepare_export_item` filters (added in #5134) allow me to add them to the server-generated CSV (with the link that is emailed out) but this doesn't make the new columns appear on the CSV generated on the client.

**Describe the solution you'd like**
The above hooks should go through to the client-generated CSV (but NOT displayed on the table - that should be considered out of the scope of this feature request), so that the server-generated CSV has the same data as the client-generated CSV.

**Comment by EdithAllison** [comment]
Thank you! I wasn't aware when I originally reported this issue that email download (server side) & direct download (client side) are two separate functions. From a user's point of view, I'd expect both CSVs to show the same information, as both are created via the same button ("download"). 

As for the "table"  report shown on screen, that's working well, it's already possible to add columns via the tutorials provided by the Woo team.

**Comment by bowenac** [comment]
@EdithAllison I totally agree, I find it extremely odd that the two ways of receiving reports would be different. I originally assumed once new columns were added to the reports "table" they would be exported... I mean, why wouldn't they. Then to find out, using the code examples I found for exporting the new columns only works when exporting via email, which I still don't even know how to get the report via email... how do you trigger a report to send to email?

I really hope we can get a solution to this... honestly seems like a common/basic feature that should be possible.

**Comment by EdithAllison** [comment]
@bowenac - the email / direct download is based on file size.

URL:  [https://docs.woocommerce.com/document/woocommerce-analytics/#analytics-basics__download-csv](url)

> Download (to CSV)
> 
> If you would like to download a copy of the data contained in the report table, you can do so by clicking the Download button in the table header. If the amount of data shown in the report is limited to one page ( e.g. there are no pagination options shown in the table footer ), the CSV file will download immediately.
> 
> If your selected date range results in a data set that spans more then one page in the table, your CSV download will be processed as a background job by WooCommerce. Once the data is ready to be downloaded, an email will be sent to the address that is attached to your WordPress account with a link to download the file.

**Comment by bowenac** [comment]
@EdithAllison Ya I hear you... I see Download button, and expected to download a CSV with all the columns in it. I'm working on a dev/staging environment that does not have a lot of test orders... I will place a bunch of test orders for the time being and verify if the new tables are in the csv report that is emailed. If they're in the emailed csv report, that will be fine from my understanding. As it won't take long for the reports to be long enough where it will require the email anyway.

Having said that though, it seems like maybe just emailing the report would always be the best option... I don't understand why they would process the data to export differently. Why even have the option of downloading client side but only for one page, and also not be identical to an emailed report csv.

**Comment by ilyasfoo** [comment]
Closing this as this issue wasn't prioritized, we probably could revisit it in the future as I think it is confusing for merchants to have different columns for the same export.
