### ISSUE TITLE
Navigation: plugins section is missing

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5694]
I'm not seeing the plugins section: https://d.pr/i/2udeXN

I'm not sure if this is still a wip, so it felt safer to open an issue about this just to confirm.

**Comment by joshuatf** [comment]
You'll need an extension that registers an item in the plugins menu.  There are some examples in https://github.com/woocommerce/woocommerce-admin/issues/5335 that you can checkout.  If no items are registered then the extensions section is not shown.

Closing this for now.

**Comment by pmcpinto** [comment]
@joshuatf thanks for the heads up. It seems that so far all the extensions hooked to the nav don't have a top-level menu item, correct?
