### ISSUE TITLE
Navigation: implement event tracking on menu item clicks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5695]
It could be useful to track menu item clicks as a complement to the pageviews tracking and to understand how many times the user is visiting the wp-admin pages, etc.

Event name: wcadmin_new_navigation_click
Event prop: menu_item: name

I assume that we're already a bit short of time to include this in the eComm release, so it's ok if we only implement it for the next stage.

**Comment by joshuatf** [comment]
@pmcpinto Are we interested only in menu items or also back buttons and category clicks?

**Comment by pmcpinto** [comment]
Having data about back buttons and category clicks can also be useful. Thanks!
