### ISSUE TITLE
[4.8-beta.1] Missing top padding on embedded activity panels

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5699]
**Describe the bug**
When viewing activity panels on embedded pages ( like the orders listing page ) it seems like we are missing some top margin/padding:

<img width="544" alt="missing-padding-embedded-inbox" src="https://user-images.githubusercontent.com/22080/99720385-874c0580-2a62-11eb-86de-74a922eac523.png">

With the Activity Panels slated to be fully migrated to the home screen, not sure if this is a super critical visual bug or not... though I think we will retain having the Inbox panel on the embedded headers so perhaps we should get this fixed up if we are doing another fix release for 4.7

**To Reproduce**

1. With 4.8-beta.1 installed
2. Visit the orders listing page, and click on the inbox activity panel
**Additional context**

Firefox 83 | OS X

**Comment by moon0326** [comment]
Related issue: https://github.com/woocommerce/woocommerce-admin/pull/4632/files#diff-df7d27b4ebc30d4a4d81884234868bda73e2ec29498d85bb6477e4725f28f46fR9 might have caused this issue (notice margin-top 0)
