### ISSUE TITLE
[4.8-beta.1] PHP Timeout TwentyTwentyOne/PHP8/WP 5.6 release 1

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5702]
**Describe the bug**
Logging an issue originally reported by @nerrad on slack today.

Screenshot because transcribing might be time consuming :)

<img width="994" alt="image" src="https://user-images.githubusercontent.com/22080/99734122-28dd5200-2a77-11eb-964a-c1e1d2be1853.png">

While I haven't attempted to repro the error myself, I'm wondering if we should look at adding another "bail early" clause to this onboarding logic so we only spend the cycles/time gathering the onboarding data for `wcSettings` if the active page is wc-admin... otherwise there really shouldn't be any other need to assemble a list of themes that support woo, and all the other bits we are doing to hydrate the state for the OBW.

**Comment by Aljullu** [comment]
I found this issue some times in the past too. In case it helps: I could reproduce it with several themes installed (I have over 16 themes) and when the onboarding task list is not complete yet.

**Comment by moon0326** [comment]
@timmyc or @Aljullu I'm trying to reproduce the issue with the following setup, but I could not. Do you have more information on the detailed steps to reproduce?

WordPress 5.6-RC1
WooCommerce 4.8.0-beta.1
Twenty Twenty Theme 1.5
PHP 8.0.0RC5

I tried adding/editing pages, but it worked fine without a timeout.

**Comment by Aljullu** [comment]
> Do you have more information on the detailed steps to reproduce?

@moon0326 I can constantly reproduce it in my testing site, but I have over 100 themes installed, so it's kind of an edge case. :smile: 

However, I think it can be reproduced with much fewer themes. I can't tell an exact number because that probably depends on your device or server, but the more themes the site has installed, the more time it needs to run `Onboarding::get_themes()` so more chances to reach the timeout.

I would suggest installing one or two dozens of themes and testing again, I think at that point the slowdown should be visible.

**Comment by timmyc** [comment]
So I think the edge case of having dozens of themes installed is something we should eventually look into - I'm thinking however that the more valuable optimization would be to not have this logic execute at all unless the active page is wc-admin/onboarding. Since that is the only flow that depends on this portion of `wcSettings` I think it would be great if we added logic to bail before this theme step entirely if you are on an unrelated page, like when editing a page, or even viewing any other WooCommerce page in wp-admin.

Granted if the site is no longer in a mode where the OBW will be shown, this code path isn't executed, seems like we should still optimize here a bit better.

**Comment by moon0326** [comment]
@Aljullu Thank you for the suggestion. No wonder why it worked fine for me 😄  I have just three themes installed. I will try to install more themes and see how it works.

**Comment by moon0326** [comment]
@timmyc Totally agree! I will try to see if I can find out more in time (since I'm new to this part, someone might have to jump in if we need to release it soon).
