### ISSUE TITLE
Detect if WCTax is installed for tax task

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5712]
**Describe the bug**
Can we detect if WCTax is already installed and change the copy in the tax task? I had gone through and installed WCShip&Tax during onboarding, but in the tax task it seemed like the extension hadn't been installed which could cause confusion. 

**To Reproduce**
Create a new site with WCShip & Tax installed but Jetpack not connected.

1. Go to the Home screen
2. Click on 'Set up task'
3. See that the copy shows "Install Jetpack and WC Tax"

**Expected behavior**
If WCTax is already installed, the copy should only say "Install Jetpack"

**Screenshots**
![detect if WCTax is installed](https://user-images.githubusercontent.com/5121465/99850662-614a6200-2b43-11eb-88c3-70b1eae9a0af.gif)

**Comment by moon0326** [comment]
@elizaan36 Hi, I have a question.

What should we do for the "Jetpack and WooCommerce Tax allow you to automate sales tax calculations" copy? Should we remove it?

![Screen Shot 2020-11-23 at 7 29 47 PM](https://user-images.githubusercontent.com/4723145/100043514-7123a980-2dc2-11eb-907b-5fc7d231ad25.jpg)

**Comment by elizaan36** [comment]
> What should we do for the "Jetpack and WooCommerce Tax allow you to automate sales tax calculations" copy? Should we remove it?

Hey @moon0326 thanks for bringing that up. I was thinking about that and it seems fine to leave the copy there since you'd need some context for this step. I think people who've already installed WCTax will understand that a) they're installing Jetpack and b) it needs to work with WooCommerce Tax (which is already installed.)

**Comment by moon0326** [comment]
@elizaan36 That makes sense 👍  Thank you for the explanation.
