### ISSUE TITLE
Navigation: Update wc_admin_register_page to handle nav_args

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5724]
Extensions hooking into wc-admin with `wc_admin_register_page` can also pass through to hook into the nav. Some explicit items must be passed it to make it land in the right place:

```php
'nav_args' => array(
    'parent' => 'woocommerce',
    'is_top_level' => true,
    'menuId' => 'plugins',
 ),
```

### Deliverables

* Keep the current setup where if no `nav_args` are supplied, it won't hook into the new Nav.
* Extensions should be the default section.
* Limit areas where extensions can hook up to: Extensions, Settings, Analytics, or any other category added by that extension or any other extension. Maybe just excluding areas would be easier?

**Comment by joshuatf** [comment]
https://github.com/woocommerce/woocommerce-admin/pull/5717 accomplishes this, but uses a slightly different approach.  It defaults to adding plugin items unless certain conditions are met.  Needs a follow-up for guardrails.

**Comment by psealock** [comment]
Closed by https://github.com/woocommerce/woocommerce-admin/pull/5717
