### ISSUE TITLE
Accessing/adding custom order meta, more extended info in reportTableData

### ISSUE THREAD

**Issue by bowenac** [woocommerce/woocommerce-admin#5730]
**Is your feature request related to a problem? Please describe.**
I'm trying to understand how to add more data to the reportTableData object, so that I can access this and add it to the orders table on client side, so I can then also have it exported etc. I'm currently able to add more data to the orders table, but only data that is already accessible via the reportTableData e.g. I've added customer_id, city, state, postcode etc. But I have a lot of other data I need in the reports that is not included in the reportTableData by default.

**Describe the solution you'd like**
More examples/documentation.

**Describe alternatives you've considered**
I've followed the table-column extension example, but it appears this is for the products schema... I tried changing products to orders but that doesn't work. e.g. 
woocommerce_rest_report_orders_schema
woocommerce_rest_reports_orders_extended_attributes

I've also followed the sql-modification example where they add the currency but this seems overly complex for what I'm trying to do, and honestly doesn't make a lot of sense, it's not that clear. I don't need filter/dropdowns for all the fields. I'm just trying to add more data to the reportTableData so I can access it client side since this has to be done via js etc.
Maybe this screenshot will make more sense, I'm trying to add more data to reportTableData so I can access it for each "item"... I'm console logging the item which is what is shown in the screenshot and is all the data that is available by default. As you can see this is where I added the customer id, city, state, postcode etc which works great... however I need more data.

    const newRows = reportTableData.rows.map( ( row, index ) => {
        const item = reportTableData.items.data[ index ];

        console.log(item);

        const newRow = [
            {
                display: item.customer_id,
                value: item.customer_id,
            },
            {
                display: item.extended_info.customer.city,
                value: item.extended_info.customer.city,
            },
            {
                display: item.extended_info.customer.state,
                value: item.extended_info.customer.state,
            },
            {
                display: item.extended_info.customer.postcode,
                value: item.extended_info.customer.postcode,
            },
            ...row,
        ];
        return newRow;
    } );

![reportTableData](https://user-images.githubusercontent.com/2638569/100127552-1460d700-2e34-11eb-98e0-f00d0ff9eebe.png)

Does anyone know or have an example of how to add more data to the reportTableData? Would love to see some examples of getting data for custom order_meta, customer phone, and product sku... I believe that would cover most areas as far as gettig access to that data... could be useful to a lot of people. Custom order meta would cover getting data from the order itself, customer phone would cover getting other fields/data from the customer, and product sku would cover getting other fields/data from the products etc.

**Comment by adrianduffell** [comment]
Hi @bowenac,

I'm sorry the available documentation wasn't able to give you all of the answers you're looking for.

@loranallensmith are you able to assist with this?

**Comment by loranallensmith** [comment]
Thanks for the ping here @adrianduffell!  :smiley:

Howdy @bowenac!  :wave:  Sorry to hear you're running into friction here.  I experimented with this today and I see what you mean about adding additional fields that aren't returned with the REST response by default.  I added your recommendation for these types of examples to our internal project board where we're tracking ongoing developer content curation.

In the meantime, if you're able to attend our next [Developer Office Hours](https://developer.woocommerce.com) (Wednesday at 14:00 UTC), let's see if we can find a community developer who might be able to offer some guidance.

**Comment by joshuatf** [comment]
@bowenac Were you able to get this working?   Can we offer any more help?

**Comment by bowenac** [comment]
@joshuatf No we ended up having to create our own custom reports due to time.

**Comment by joshuatf** [comment]
Ok, I'll close this issue for now then @bowenac, but feel free to reopen or reach out if you need any more help.

**Comment by kcfgl** [comment]
@joshuatf Hey there. I actually could use a solution to this very problem. I've been working with @psealock to extend the reports a bit more. But I've hit a roadblock adding custom meta columns. It would be extremely helpful to know how to get this accomplished with the standard reports. Thanks!

**Comment by joshuatf** [comment]
Hey @kcfgl 👋 

I'd be happy to take a look.  Do you have a PR somewhere I can take a look at your current progress?

**Comment by kcfgl** [comment]
hi @joshuatf thank you so much for offering to dig in. I actually don't have much headway made on this specific issue. What we were working on in 6529 was filtering the core reports (Revenue, Orders, etc) by custom metadata. We have numerous pieces of custom meta - like Ship Date for example - and I would love to be able to add custom columns to the stock reports. I have only determined that this chunk of code: 
```
const addTableColumn = reportTableData => {
    if ( 'orders' !== reportTableData.endpoint ) {
        return reportTableData;
    }

    const newHeaders = [
        {
            label: 'User Role',
            key: 'role',
        },
        ...reportTableData.headers,
    ];

    const newRows = reportTableData.rows.map( ( row, index ) => {
        const item = reportTableData.items.data[ index ];
          console.log(item);
        const newRow = [
            {
                display: item.role,
                value: item.role,
            },
            ...row,
        ];
        return newRow;
    } );

    reportTableData.headers = newHeaders;
    reportTableData.rows = newRows;

    return reportTableData;
};
```
Will not add a column showing the User Role - even though we are filtering the report now on User Role - because it is not returned in the reportTableData object (I verified that in the console). By the way, this User Role is a custom role and not the returning/new available in stock reports. 

I can provide anything else you need, but if you have a way to get more data returned in reportTableData, I think we will be golden. I've tried to dig around a bit to see if there is a clear way to request more fields in the call that populates reportTableData, but I haven't found it yet. Thanks!

**Comment by joshuatf** [comment]
@kcfgl  Were you following the example plugin in WooCommerce Admin?  If you haven't already, you can build it by running `npm run example -- --ext=sql-modification` in the WooCommerce Admin root directory.  This will create a working plugin you can start from.

Without seeing all of your code, I'm guessing that `addTableColumn` is applied to `woocommerce_admin_report_table`- is that right?

The frontend is agnostic to where the table data comes from, but if you want to include data from your server in `reportTableData`, then you'll need to add a PHP filter to include this data with the response somewhere.  There are multiple ways to do this, but you could join your data and select directly from the database as the example does on the `woocommerce_analytics_clauses_select_orders_subquery` hook.  Alternatively, you could simply modify the report data before it's returned by the server on the `woocommerce_rest_prepare_report_orders` hook.

```php
add_filter( 'woocommerce_rest_prepare_report_orders', function( $response ) {
    $response['ship_date'] = get_post_meta( $response['order_id'], 'your_custom_ship_date' ); // Get your custom data and append it to the response.
    return $response;
} );
```

Hope that helps!  If you need more help, I can help debug a bit if you end up pushing a PR with your current work.

**Comment by kcfgl** [comment]
@joshuatf Yep I was following the SQL modification example.  I have everything working except custom meta as columns. I can add columns like Currency, as in the example, or any other data included in the response, but not custom.  I just tried to drop in the woocommerce_rest_prepare_report_orders hook and I get a 500 error for the individual Order row blocks. The summary data works though. I've tried the hook in the plugin and just in functions.php.

I am also selecting User role as Role directly in the orders_subquery:

```
function add_select_subquery( $clauses ) {

	  if ( isset( $_GET['orderrole'] ) ) {
    	$clauses[] = ', order_user_role_postmeta.meta_value AS role';
		}

		if( isset( $_GET['Shipped_between'] ) ){
			$clauses[] = ', order_was_shipped_postmeta.meta_value AS order_was_shipped';
		}


    return $clauses;
}
add_filter( 'woocommerce_analytics_clauses_select_orders_subquery', 'add_select_subquery' );

```
But even when the value is set, Role is not added to reportTableData. So I'm still stuck it seems, but I'm guessing it is something very simple that is tripping me up. Thanks again for your support on this, its truly appreciated!

**Comment by kcfgl** [comment]
@joshuatf I'm so close. Actually, the whole problem seems to be right here in the Select. I cannot just add in the custom meta select clauses. If I try to add them, when the filters are not set, then the order report doesn't work. If I try to add the woocommerce_rest_prepare_report_orders, then I get a 500 error.

But if I have my filters setting the Order Role, or the Shipped Between (or both), then the data is available and is in the reportTableData and I can add it as a column.

```
function add_select_subquery( $clauses ) {

	  if ( isset( $_GET['orderrole'] ) ) {
    	$clauses[] = ', order_user_role_postmeta.meta_value AS role';
		}


		if( isset( $_GET['Shipped_between'] ) ){
			$clauses[] = ', order_was_shipped_postmeta.meta_value AS order_was_shipped';
		}


    return $clauses;
}
```

Any idea how I should be setting these clauses up so that I can select the custom meta even if I'm not filtering?

**Comment by joshuatf** [comment]
Glad to hear it, @kcfgl!  Feel free to reach out if you need any more help 😄
