### ISSUE TITLE
Setup Wizard Input Fields Allow White Space as Valid Input

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-admin#5747]
**Describe the bug**
Input fields in the Setup Wizard (including address fields and industry “other” description input fields) allow for white space as valid input, allowing a user to bypass required fields.

**To Reproduce**

1. Go to the 'Store Details' step in the Setup Wizard.
2. Attempt to submit the form without filling one or more required fields. Note you receive an error on submission.
3. Enter a white space into the required field and attempt to submit the form again.
4. Note that it allows you to submit the form without adding in the required fields.

**Expected behavior**
Required fields should still require some valid input before allowing the user to continue.

**Screenshots**

![image](https://user-images.githubusercontent.com/71906536/100389386-7b27f100-2fea-11eb-9d61-0a6cf8329b33.png)
☝️ For example, in this case I can click “Continue” and move forward.

**Desktop (please complete the following information):**

* OS: macOS Big Sur
* Browser FireFox, Chrome
* Version 83.0, 86

**Comment by moon0326** [comment]
@zhongruige  Thank you for taking the time to test and report this bug. We really appreciate it 👍.

I've opened a PR to fix this bug.

**Comment by zhongruige** [comment]
Thank you for the follow up @moon0326 !
