### ISSUE TITLE
Setup Wizard [UX]: Disabled state for buttons appears active

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-admin#5748]
**Describe the bug**
This is more of a UX consideration: The disabled state of the buttons isn’t clear; the button still appears active. A user may not notice the cursor change (that indicates the button is inactive) and could cause confusion.

**To Reproduce**

1. Go to the 'Store Details' on the setup Wizard
2. Fill out the form but leave one or more required fields empty.
3. Note that, outside of the cursor change, the 'Continue' button still looks active as if it can be interacted with.

**Expected behavior**
The button state changes from a 'disabled' state to an 'active' state when it's ready. Just as an example, Bootstrap's disabled state appears lighter compared to buttons with an active state: [Disabled State](https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state) | [Active State](https://getbootstrap.com/docs/4.0/components/buttons/#active-state)

**Screenshots**
![image](https://user-images.githubusercontent.com/71906536/100389867-d73f4500-2feb-11eb-84a3-0ba5712e057b.png)

**Desktop (please complete the following information):**

* OS: macOS Big Sur
* Browser FireFox, Chrome
* Version 83.0, 86

**Comment by joshuatf** [comment]
Thanks for opening this issue, @zhongruige!  

This should be resolved by https://github.com/woocommerce/woocommerce-admin/pull/6112.

**Comment by zhongruige** [comment]
> Thanks for opening this issue, @zhongruige!
> 
> This should be resolved by #6112.

Thank you for following up! :)
