### ISSUE TITLE
Store Management tasks - WooCommerce 4.8 - Doesn't redirect to configuration pages

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-admin#5757]
*Reference pb22l9-ce-p2*

**Testing Env:**

Atomic ephemeral
**WP:** Version 5.6-RC1
**WC:** WC 4.8.0-beta.1
**PHP:** 8.0.0RC3
macOS
Chrome
2021 theme

**Describe the bug**

Except for the marketing tab, none of the other options actually take me to the configuration pages. They just update the URL, but not redirect the user

Better explained in this .gif

![https://d.pr/i/0GI0HR+](https://d.pr/i/0GI0HR+)

**Comment by moon0326** [comment]
WooCommerce 4.8.0-beta.1 includes WooCommerce-Admin 1.7.0. 

I've confirmed that the bug exists in WooCommerce-Admin 1.7.0 and 1.7.1, but it is fixed in WooCommerce-Admin 1.7.2 (latest release).

**Comment by moon0326** [comment]
Closing it as this is already fixed in the latest release (1.7.2)
