### ISSUE TITLE
i18n locale information is not correctly set after Setup Wizard

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-admin#5760]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I installed woocommerce on a fresh wordpress installation.
I did the setup over the new wizard and choose country liechtenstein and also on a separate installation with country switzerland.

My old PR where i submitted the correct i18n informations: https://github.com/woocommerce/woocommerce/pull/27193

**Expected behavior**
Currency, position of currency, ... should be set based on the i18n predefined setup file.

**Actual behavior**
Basic US informations get set.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install woocommerce on a fresh wordpress site
2. work with the setup wizard and choose country liechtenstein
3. finish the wizard and change to settings
4. check if the currency is $ (then it doesnt work) or CHF (then it would work)

Thanks
Brian

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by masteradhoc** [comment]
Hey @pmcpinto 
could you check and confirm this please?

Thanks
Brian

**Comment by pmcpinto** [comment]
@masteradhoc thanks for opening the issue and creating the PR. We're going to try to take care of this as soon as possible, in order to include it in one of the upcoming releases.

**Comment by haszari** [comment]
I'm still seeing this with WooCommerce 5.1.0 - is the fix included in the wc-admin version in 5.1.0? My particular use case:

- Go through onboarding and set store address somewhere in New Zealand.
- After onboarding, the currency always defaults to GBP. 

<img width="985" alt="Screen Shot 2021-03-26 at 12 09 29 PM" src="https://user-images.githubusercontent.com/4167300/112555070-50309b00-8e2c-11eb-8d86-90df7bc1cc85.png">

<img width="786" alt="Screen Shot 2021-03-26 at 12 06 32 PM" src="https://user-images.githubusercontent.com/4167300/112555080-5757a900-8e2c-11eb-8164-6b0696da0e54.png">

<img width="851" alt="Screen Shot 2021-03-26 at 12 06 24 PM" src="https://user-images.githubusercontent.com/4167300/112555077-54f54f00-8e2c-11eb-9b38-882e0af1a10b.png">

Just mentioning in case I'm seeing a regression or different bug.
