### ISSUE TITLE
Reporting discrepancies with Net Sales and Refunds

### ISSUE THREAD

**Issue by joshguss** [woocommerce/woocommerce-admin#5766]
**Describe the bug**
1. **Net sales is incorrectlly reporting refunds:** As a sum, Net Sales does not take into account shipping or taxes paid, but once orders are refunded, Net Sales is decreased by a total refunded cost that's inclusive of the shipping and taxes on refunded orders.
2. **Net Sales is subtracting the value of refunds twice:** Net Sales incorrectly reflects the net revenue. It subtracts the refunded revenue from a total net revenue that does not take into account the original revenue of the refunded orders. 

**To Reproduce**

1. Create refund in store with existing orders
2. Look at the Analytics > Orders breakdown (example below should help illustrate)

**Expected behavior**
For example, if there are five (5) $20 orders, and one (1) order is a refunded order (i.e. $80 Net Sales), WooCommerce is calculating as follows:
- The list of orders includes five orders with a Net Sales column for each. 
- The Net Sales for the refunded order is -$20.
- The total Net Sales is summing the Net Sales column, adding $20 for the four non-refunded orders and subtracting $20 for the refunded order. 
- Thus, the total Net Sales equals $60, i.e. ($20 x 4) minus $20

_The expected behavior is that it should equal $80, i.e. ($20 x 5) minus $20_

**Screenshots**
This first screenshot shows that there is a negative value for Net Sales applied to refunds. Important to note that there is no positive value for these orders included in this data (i.e. no value for the refund to negate):
![Screen Shot 2020-11-30 at 1 13 27 PM](https://user-images.githubusercontent.com/2687263/100650027-4e891780-3311-11eb-9b86-33a7cb4ec952.png)

The following three screenshots all show that the amount refunded, which is subtracted from Net Sales, includes shipping. Yet Net Sales as a sum, does not include shipping (or taxes) for orders. Therefore, it is only including shipping when an amount is refunded and subtracted:
![Screen Shot 2020-11-30 at 1 15 49 PM](https://user-images.githubusercontent.com/2687263/100650090-6bbde600-3311-11eb-8797-b8c354f43e49.png)
![Screen Shot 2020-11-30 at 1 17 04 PM](https://user-images.githubusercontent.com/2687263/100650116-72e4f400-3311-11eb-98fa-97ad9a518326.png)
![Screen Shot 2020-11-30 at 1 17 14 PM](https://user-images.githubusercontent.com/2687263/100650131-76787b00-3311-11eb-8d2c-7afb336c8223.png)

**Desktop (please complete the following information):**

* OS: macOS Catalina (10.15.6)
* Browser: Chrome
* Version: 87.0.4280.67 

**Additional context**
[HERE IS A SPREADSHEET](https://docs.google.com/spreadsheets/d/1oXuVDI5k7vhi6xShoPQtA93ZdmL6bjX9yu0a9Wn2c_Q/edit?usp=sharing) containing actual data to further illustrate this. The first sheet is the data pulled from WooCommerce and is unedited (it includes a summary of the data to the right). The second sheet is updated to show how refunds should be calculated in reporting with a summary and our conclusions to the right.

**Comment by fylgjur** [comment]
I took a look at my own test site data (site running Storefront theme and internal plugins) and I'm unable to reproduce this at the moment.

Here is an order that was refunded including shipping at £195:

![https://d.pr/i/qaxpTO](https://d.pr/i/qaxpTO+) 
Full Size: https://d.pr/i/qaxpTO

And here is the same order as it displays in net sales, the pre-shipping price £170 displayed as a positive value:

![https://d.pr/i/Evcxik](https://d.pr/i/Evcxik+) 
Full Size: https://d.pr/i/Evcxik

And once refunded, the pre-shipping price displays in a separate row, this time as a negative number -£170:

![https://d.pr/i/s1z23N](https://d.pr/i/s1z23N+) 
Full Size: https://d.pr/i/s1z23N

The net sales total value is correct.

I have suggested a conflict test in 3535219-zen to rule out plugin conflict in this case before we proceed.

**Comment by damiannep** [comment]
I can replicate this issue on my test site with order refunds and cancellation:

![screenshot](https://d.pr/i/Y5Bcdl+)
*Click to see the full screenshot: https://d.pr/i/Y5Bcdl*

These are my tax settings:

![tax](https://d.pr/i/RiwgFd+)
*Click to see the full screenshot: https://d.pr/i/RiwgFd*
