### ISSUE TITLE
SummaryNumber component displays "N/A" when there is no delta

### ISSUE THREAD

**Issue by ecgan** [woocommerce/woocommerce-admin#5767]
**Describe the bug**

According to the [documentation for the `SummaryNumber` component](https://woocommerce.github.io/woocommerce-admin/#/components/packages/summary/README?id=summarynumber), for the `delta` props, it says "If omitted, no change value will display".

When I use it in my project, it displays "N/A" in the UI when there is no `delta`.

![image](https://user-images.githubusercontent.com/417342/100650988-bd04be80-337f-11eb-8aa0-8d4dfbbf9ed0.png)

**Expected behavior**

Do not display "N/A" when there is no `delta`.

**Comment by timmyc** [comment]
Hey @elizaan36 curious if you have any thoughts on this one? I suppose @LevinMedia might because I'm guessing we purposely opted to show `n/a` when no delta exists. Seems like we could update the documentation accordingly, or possibly add in a prop to allow for further customization, or change the default behavior.

**Comment by elizaan36** [comment]
I'm seeing this in the SummaryNumber component when there's no delta - it shows 0%. I haven't seen the N/A before, curious how would you get that?

![image](https://user-images.githubusercontent.com/5121465/101555731-d230ad00-397e-11eb-9a52-aeea5e39a18b.png)

**Comment by ecgan** [comment]
@elizaan36 , I'm using [@woocommerce/components npm package](https://www.npmjs.com/package/@woocommerce/components) current version 5.1.2, and below is a sample component to demonstrate this issue: 

```jsx
const Summaries = () => {
	return (
		<SummaryList>
			{ () => {
				return <SummaryNumber label="Test 1" value={ 123 } />;
			} }
		</SummaryList>
	);
};
```

Screenshot: 

![image](https://user-images.githubusercontent.com/417342/101623382-55bbce00-3a53-11eb-8c2b-ef9cf9d3f5ab.png)

**Comment by elizaan36** [comment]
thanks for that context, and for bringing up this issue @ecgan !

I think the component should read `0%` by default when there's no delta, rather than `N/A`. In that case we'd need an update to the component and docs. @timmyc what do you think?

**Comment by ecgan** [comment]
@elizaan36 , can we put in a way to make it not to display anything? e.g. display nothing by default or by passing `delta=""`? I like to have that kind of control. By not forcing a "percentage" display, it opens up for more possibility and reuse.

**Comment by timmyc** [comment]
@ecgan can you share with us some details around how you are planning to use this without a delta? I think that might help us arrive at the best solution.

But definitely we can make any changes that you need, just wanting to make sure we do the right thing that helps you and other devs utilize this component better.

**Comment by ecgan** [comment]
@timmyc , we would like to use this to display a _current status_ of things, see a sample screenshot below:

![Screenshot 2020-12-14 at 9 54 18 PM](https://user-images.githubusercontent.com/417342/102089337-07456f80-3e57-11eb-91be-3640acb083e2.png)

For our use case here, we don't have previous values (they are always current values) and therefore there is no delta.

> Also totally cool with you doing a PR with an implementation of a false prop being passed as delta and then having it not render at all.

I would love to, but right now I got to prioritize my commitment in my project first 😄

**Comment by timmyc** [comment]
Thanks @ecgan that is very helpful! Are you able to work around this bug using css perhaps? Just want to make sure you aren't blocked by this - if it is a blocker for you, please let me know and we can try and get someone to work on the component update.

**Comment by LevinMedia** [comment]
@timmyc @elizaan36 I'm wondering if we could maybe recycle whatever WCpay has done with it's "Summary Numbers" on the deposit details screen... There's no delta to display there. Unfortunately I'm not exactly sure where the code is in that repo - but it looks similar to what @ecgan is looking for:

<img width="1403" alt="Screen Shot 2020-12-15 at 6 44 46 PM" src="https://user-images.githubusercontent.com/4500952/102298354-d3755300-3f05-11eb-9ef3-658525550f13.png">

**Comment by LevinMedia** [comment]
I did a little digging, and I'm pretty sure WCpay his hiding it using CSS: 

https://github.com/Automattic/woocommerce-payments/blob/6c8f7f602db409b9e326ec693ae7d2ffc7dfe510/client/deposits/overview/style.scss#L28

**Comment by ecgan** [comment]
@timmyc , no worry, it's not a blocker for me, I created this GitHub issue so that there can be a future bug fix / enhancement. Yeah I can work around it using CSS. 

@LevinMedia , thanks for the suggestion and digging the code 🙂 👍

**Comment by becdetat** [comment]
To circle back on this, it seems that we could:

- if `false` is passed in as the delta value, don't show the delta (note: this needs to be a `===` check)
- rework and clarify the documentation on the delta value

**Comment by timmyc** [comment]
Added a feature label to prevent stalebot from closing.

**Comment by chihsuan** [comment]
I'm closing this since this is over 6 months old. Please reopen if anyone has the bandwidth to pick it up. (p90Yrv-2Bc-p2)
