### ISSUE TITLE
Category filter only works for the first 25 categories

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [woocommerce/woocommerce-admin#5789]
**Description**

When looking at the category reporting with 25+ categories, filtering doesn't work as expected when one or more fall outside the fetched categories overview.

I suspect this is because the `wc-analytics/reports/categories` requests `page_limit` is set to 25 and this request isn't repeated after searching for a category.

**To Reproduce**

1. Have a store with orders in 25+ categories
2. Click on Analytics->Categories
3. Search for a category with the lowest sales in the "Search by category name" input

**Expected behavior**

When searching for a specific category, it should show the actual sales in the categories overview.

**Screenshots**

![image](https://user-images.githubusercontent.com/3996119/100875395-3eef0780-34a6-11eb-8d08-92506db305b2.png)

**Note**

When increasing the page limit or clicking the next page button in the categories overview, it does show the correct sales for the category.

**Comment by moon0326** [comment]
Hi @ChristiaanScheermeijer,

Thank you for taking the time to report this bug, we really appreciate your help. I've confirmed the bug in my test environment.  We will start working on it soon.

**Comment by moon0326** [comment]
Hi @ChristiaanScheermeijer,

Thank you for taking the time to report this bug. I could not reproduce it in my test environment. I've added 28 categories and each category has at least 1 order. Please see my screenshot.
![Screen Shot 2020-12-02 at 7 58 48 PM](https://user-images.githubusercontent.com/4723145/100962447-2a783280-34d9-11eb-80ea-69856ca3b45a.jpg)

Could you please try clearing cache and see if it fixes the problem? You can clear the Analytics cache by navigating to WooCommerce -> Status -> Tools -> Click [ Clear ] at the bottom of the page where it says "Clear analytics cache"

**Comment by ChristiaanScheermeijer** [comment]
Hi @moon0326 , thank you for looking into this problem. Sorry for not responding earlier, I didn't get notified somehow.. 

I tried reproducing the issue this morning before trying your suggested solution, but miraculously, I don't see the problem anymore. 

Do you perhaps know why this problem occurs from time to time? I've seen this exact problem three months ago and could solve it by updating WooCommerce Admin.

Thanks for the tip regarding clearing the cache, I will try that next time when we see this problem.

**Comment by moon0326** [comment]
@ChristiaanScheermeijer No worries 👍 Thank you for testing the issue again. This might be related to an issue we are investigating at the moment. We haven't confirmed the issue yet, but there might be timezone related issue. That might explain why it does not work from time to time. I will link a PR here once we confirm the issue and have a fix.

**Comment by ChristiaanScheermeijer** [comment]
@moon0326 no problem! The mentioned issue sounds like a plausible cause. However, I can confirm that we were seeing this issue longer than a single day.

 I will try reproducing this and do some more debugging.
