### ISSUE TITLE
Can't Reach Product Taxonomy Pages in Navigation

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#5795]
**Describe the bug**

The new navigation feature is missing elements for Product Categories, Tags, and Attributes.

**To Reproduce**

1. Ensure the Navigation feature is enabled (WooCommerce > Settings > Advanced > Features)
2. Go to WooCommerce > Products
3. Verify there are no links for the taxonomies

**Expected behavior**

I expect to be able to reach the Product taxonomy management screens.

**Screenshots**

**Current nav:**

![Screen Shot 2020-12-02 at 12 03 27 PM](https://user-images.githubusercontent.com/63922/100924753-04d63380-34af-11eb-86ec-6968a9b7b610.png)

**New nav:**

![Screen Shot 2020-12-02 at 1 00 26 PM](https://user-images.githubusercontent.com/63922/100924831-21726b80-34af-11eb-8510-c2289ebb106a.png)

**Comment by joshuatf** [comment]
There were excluded from the designs, but I would also assume we'd need to add them in.  Any problems with directly adding these?  /cc @elizaan36 @pmcpinto

**Comment by elizaan36** [comment]
@joshuatf I don't see any problems with adding them in if we can, I think we should.

**Comment by elizaan36** [comment]
<img width="240" alt="Screen Shot 2020-12-02 at 8 48 54 PM" src="https://user-images.githubusercontent.com/5121465/100957321-d4f35400-34df-11eb-9967-3bd5effb0200.png">

Wanted to drop this in here because the `Add new` link would work best as the last item in the nav.
