### ISSUE TITLE
Advanced filters not working with new/returning customer

### ISSUE THREAD

**Issue by ciszere** [woocommerce/woocommerce-admin#5803]
**Describe the bug**
I found another issue that is related to my previous error about new/returning customer error. When I try to filter customers - Advanced filters" - "Customer is returning/new" it doesn't work. it just shows all orders regarding if I filter for new or returning

**To Reproduce**

1. Go to Analytics
2. Click on Orders
3. Click on Advanced filters
4. choose customers - Returning/new
5. The Customer list just shows all customers, no difference if i change returning or new

**Expected behavior**
I would see all returning customers when i click returning and so on. 

**Screenshots**

**Desktop (please complete the following information):**

Safari - Latest version
latest version of analytics

<img width="1440" alt="Skärmavbild 2020-12-02 kl  20 38 52" src="https://user-images.githubusercontent.com/60106580/100978089-2b917a00-3542-11eb-9edd-799420e898cc.png">

<img width="1440" alt="Skärmavbild 2020-12-02 kl  20 37 05" src="https://user-images.githubusercontent.com/60106580/100978090-2cc2a700-3542-11eb-8aa2-6f69395017ce.png">

**Comment by joelclimbsthings** [comment]
This definitely seems to be a legitimate bug, and a somewhat nasty one.

To elaborate a bit further, in the example above the table below reflects the correct orders, but the chart (in original screenshots) does not. Here's another screenshot that shows both:

![image](https://user-images.githubusercontent.com/444632/101097402-f43cc080-3575-11eb-8936-9b905d7d24dd.png)

While testing this I also encountered what might be a related issue, but reflects the opposite; in this example the chart reflects the _correct_ total, while the table shows all orders. The filter is for excluding a specific product (including works fine):

![image](https://user-images.githubusercontent.com/444632/101097639-64e3dd00-3576-11eb-98f0-ebda47ea0deb.png)

**Comment by joelclimbsthings** [comment]
I've added this to the `1.8.0` milestone, although we may have to defer to the next release at this point if a solution doesn't present itself pretty quickly.

**Comment by jeffstieler** [comment]
@ciszere just to confirm - by "latest version of analytics" do you mean you're using version `1.7.2` of WooCommerce Admin?

**Comment by ciszere** [comment]
Hello,

I have this version: 1.7.2 :)

Best regards,
Med vänlig hälsning,
Johan Forsberg, Founder

Phone: +46 768 08 82 32
Ciszere AB
Org.nr 559052-7346
www.ciszere.se


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

Den fre 4 dec. 2020 kl 02:26 skrev Jeff Stieler <notifications@github.com>:

**Comment by adrianduffell** [comment]
Closing this now as PRs #5822 and #5823 have addressed the issues raised here.

@ciszere these fixes are planned for the 1.8 release.
