### ISSUE TITLE
woocommerce admin dashboard blank?

### ISSUE THREAD

**Issue by blueberry217** [woocommerce/woocommerce-admin#5829]
Hi,

I am not sure if this is causing my plugins i have disabled all of them same issue persists, i show a screenshot below.

![Naamloos](https://user-images.githubusercontent.com/58176941/101241736-16ab1700-36f9-11eb-9b04-606ef27832f8.png)

thanks in advance

**Comment by mredwinsetiawan** [comment]
same issues

**Comment by mredwinsetiawan** [comment]
![image](https://user-images.githubusercontent.com/26828260/101272798-2b9fad00-37c2-11eb-91c9-a613d90664ec.png)

**Comment by ilyasfoo** [comment]
Hello @blueberry217 @mredwinsetiawan!

Thank you for posting this issue. I've tried to reproduce by installing a fresh WordPress site `5.5.3` with WooCommerce `4.7.1`, and wasn't able to. 
- Could you help to provide the exact steps? 
- What versions of WooCommerce and WordPress did you use?
- Was it working before an upgrade, or was it a fresh install? 
- Did you get any errors during WooCommerce plugin install?

**Comment by blueberry217** [comment]
WordPress i used 5.5.2 - 5.5.3 - 5.5 , WooCommerce  4.6.2 - 4.7.0 - 4.7.1
It was working before an upgrade
I did not get any errors while installing WooCommerce

**Comment by blueberry217** [comment]
it has been fixed it was an theme issue.

**Comment by mredwinsetiawan** [comment]
what theme did you use? 

> it has been fixed it was a theme issue.
