### ISSUE TITLE
get_automated_tax_supported_countries doesn't include UK

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-admin#5836]
**Describe the bug**
`get_automated_tax_supported_countries()` doesn't include UK as it uses WC_Countries::get_european_union_countries.
https://github.com/woocommerce/woocommerce-admin/blob/72b6301a45f5448262f117393d69c5fe16a2bfcf/src/Features/OnboardingTasks.php#L296

However UK is **currently** supported by TaxJar https://developers.taxjar.com/api/reference/#countries although TaxJar lists it under EU countries **so it is unclear if this TaxJar support will continue after Dec 31st 2020** when the Brexit transition period ends (https://ec.europa.eu/taxation_customs/uk_withdrawal_en).

This means a UK store which installed and activated WooCommerce Shipping & Tax during the OBW does not have the tax task completed.
![Screenshot_2020-12-07_at_20_51_18](https://user-images.githubusercontent.com/24649833/101404260-5119dd00-38ce-11eb-8fb3-442741efda92.png)
![Screenshot_2020-12-07_at_20_51_11](https://user-images.githubusercontent.com/24649833/101404264-524b0a00-38ce-11eb-828b-91d90b649ada.png)

**To Reproduce**
1. Install a fresh instance of WooCommerce
2. Enter United Kingdom as Country in Store Details in the setup wizard, choose to install & activate WooCommerce Shipping & Tax when offered.
3. Observe incomplete Set up tax item in task list.
4. Install a fresh instance of WooCommerce
5. Enter Germany as Country in Store Details in the setup wizard, choose to install & activate WooCommerce Shipping & Tax when offered.
6. Observe completed Set up tax item in task list.

**Comment by becdetat** [comment]
I've asked TaxJar if the UK will be supported after Dec 31. I've just used their support email address, we probably have a better contact there but at least a ball is rolling :-)

**Comment by tammullen** [comment]
Looks like TaxJar are continuing to support UK https://blog.taxjar.com/taxjar-will-continue-to-support-uk-and-eu-vat-post-brexit/

**Comment by joshuatf** [comment]
`get_european_union_countries()` includes a `$type` option that will add in `GB` along with `IM` and `MC`.

Seems like the simple and easy solution here is to add `GB` to the list of allowed countries in https://github.com/woocommerce/woocommerce-admin/blob/6dddef0cbcdd05b6e93347bfc87a830c08133928/src/Features/OnboardingTasks.php#L300
