### ISSUE TITLE
[WooCommerce 4.8.0] Console error on standard tax rate entry during task list

### ISSUE THREAD

**Issue by ObliviousHarmony** [woocommerce/woocommerce-admin#5839]
**Describe the bug**
After selecting "Set up tax rates manually" during the task list, console errors continue to be thrown on the standard rate entry page until the task has been completed.

**To Reproduce**

1. Prior to starting any tasks, visit the standard rate entry page and note there is no error.
2. Start the tax and select the manual option, note the console error.
3. Return to the dashboard and navigate back from the settings menu, note the console error.
4. Complete the shipping task, note the lack of errors.

**Expected behavior**
An error should not be thrown.

**Screenshots**
https://d.pr/i/p5u3CW

**Desktop (please complete the following information):**

* OS: [e.g. iOS] MacOS Big Sur
* Browser: [e.g. chrome, safari] Chrome
* Version [e.g. 22] 87.0.4280.88

**Comment by moon0326** [comment]
@ObliviousHarmony Thank you for reporting this bug 👍 

I was able to reproduce it with WC Admin version up to 1.7.3, but version 1.8.0 (including beta) worked without the error. As the error isn't blocking user interactions, I think we can wait for the fix in version 1.8.0.

**Comment by joshuatf** [comment]
@ObliviousHarmony would you be able to double check and see if this issue is resolved for you on the latest version?  If so, we'll close this one out.  Thanks!

**Comment by ObliviousHarmony** [comment]
@joshuatf I tested this with WooCommerce 5.1-beta.1 and did not experience the issue.
