### ISSUE TITLE
Partnerships: Creative.mail Attribution

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5841]
We recently shipped a change to the OBW to promote the Creative.mail plugin/service ( #5543 ) but we need to add in a little bit more logic to properly set an attribution that signals if the Creative.mail plugin was installed as part of the OBW process.

Jetpack has some prior art for us to follow to implement this in wc-admin:

https://github.com/Automattic/jetpack/pull/16818

- and a follow up PR which changed the option name to lower case - 

https://github.com/Automattic/jetpack/pull/16861

For our attribution tracking in wc-admin, we need to implement the following:

- **If a user opts to install Creative.mail during the OBW**
- We need to create/update a site option titled: `ce4wp_referred_by`
- The value of that site option should be ( based off of Jetpack's implementation )

```
	$option_info = array(
		'plugin'  => 'woocommerce',
		'version' => WC_VERSION,
		'time'    => time(),
		'source'  => 'onboarding',
	);
```

If the plugin is not installed during the OBW, the option should not be set at all.

cc @pmcpinto to make sure this all looks correct to you

**Comment by pmcpinto** [comment]
Sounds good to me. @MechielCouvaras, I think this fulfills the referral needs, correct?

**Comment by MechielCouvaras** [comment]
Yup, looks good to me, thanks @timmyc and @pmcpinto

**Comment by MechielCouvaras** [comment]
Hey @pmcpinto and @timmyc any idea which release this will be in? I'd like to give Creative Mail a target date. Thanks!

**Comment by timmyc** [comment]
@MechielCouvaras we have missed the code freeze date for the January release, so this will likely go out in the Feb release
