### ISSUE TITLE
Optimize ReportsTable component

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#5854]
**Describe the bug**
As I was testing #5787 I noticed that my test filter created by [following this blog post](https://becdetathome.wpcomstaging.com/2020/12/02/adding-columns-to-analytics-reports-and-csv-downloads/) was being called a lot, on initial render, and when hiding/removing columns (testing this on the Customers table, but reproducible wherever ReportsTable component is being used).

This is not noticeable on the UI too much, but once more 3PD's start integrating it could cause issues.
I think we should fix this.

**Fix suggestions**
- Make use of `useEffect` and `useState` to generate the headers, rows, summary. The useEffect probably only needs to run when `tableData` changes (can call the `applyFilters` within here).
- Have a look at the `withSelect` and see if we are not creating unnecessary immutable objects/arrays on every call.
 
**To Reproduce**

1. Create sample plugin using `npm run create-wc-extension`
2. Add the code as mentioned in [this blog post](https://becdetathome.wpcomstaging.com/2020/12/02/adding-columns-to-analytics-reports-and-csv-downloads/), in particular the Javascript code.
3. Add a console log inside the `woocommerce_admin_report_table` filter that you added, and navigate to **WC > Customers**
4. See that your filter is being called quite a lot, even before we get any data.

**Expected behavior**
_this is up for discussion_ but on initial render it should only be called twice, once with no data, and once when the data is retrieved.
Same goes for column changes, here it should only be called once.

**Screenshots**
![customer-report-table](https://user-images.githubusercontent.com/2240960/101646267-ad374b00-3a0d-11eb-9315-8dbfe4ddd393.gif)

**Comment by psealock** [comment]
NIce, this would be a good improvement

**Comment by chihsuan** [comment]
@louwie17 I'm going to close this since it has been a while. Please free feel to reopen it if you plan to fix it. Thanks!
