### ISSUE TITLE
Enable "Verified owner" label in Reviews panel

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5862]
hey @louwie17, this was an oversight on my part but while reviewing the [Reviews panel work](https://github.com/woocommerce/woocommerce-admin/pull/5706) today (responding to @timmyc on the issue with the interim flow), I noticed that we're missing the "Verified owner" label in the new Reviews panel.

In Product Settings, users can choose to show the "Verified owner" label, or only show reviews from "Verified owners" so it's a label that people will certainly expect to see.
<img width="663" alt="Screen Shot 2020-12-10 at 5 35 55 PM" src="https://user-images.githubusercontent.com/5121465/101843181-44d09280-3b0f-11eb-9f5f-22f1d1b362ba.png">

Here's a possible icon to use - also in the Figma designs.
<img width="961" alt="Screen Shot 2020-12-10 at 5 41 11 PM" src="https://user-images.githubusercontent.com/5121465/101843186-48641980-3b0f-11eb-88e2-70a38b7dd150.png">

Let me know if there's anything I can do here.

**Comment by louwie17** [comment]
Hey @elizaan36, no worries, I can update this to reflect the updated wireframes, currently it looks like this (from the original panel):
<img width="509" alt="Screen Shot 2020-12-11 at 9 51 14 AM" src="https://user-images.githubusercontent.com/2240960/101911505-d2a39080-3b96-11eb-8d5b-bff31d61165d.png">

One question I did have, when someone toggles the `Show "verified owner" label on customer reviews` I assume this just hides it on the front-end (within the store front) not here in the admin panel?

**Comment by elizaan36** [comment]
Thanks @louwie17 

> when someone toggles the Show "verified owner" label on customer reviews I assume this just hides it on the front-end (within the store front) not here in the admin panel?

Oh I had assumed that meant showing the label on the backend, but you're right that this settings area controls storefront side! Thanks for bringing that up, so it's not something we'd have to handle on the admin side.
