### ISSUE TITLE
wp-admin nav scrolls off screen on some pages

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5863]
**Describe the bug**
I noticed that the wp-admin navigation scrolls up with some pages, and in the case of a long scrolling page (like the Home screen) it scrolls completely out of view. Looks like this is only happening on WooCommerce Home, Analytics, and Marketing screens.

**To Reproduce**

1. Go to 'WooCommerce Home', Analytics, or Marketing
2. Scroll down the page
3. See error 

**Expected behavior**
On legacy screens, the wp-admin navigation menu stays fixed (stops scrolling) once the bottom of the nav reaches the bottom of the viewport, even when the screen content continues to scroll.

**Screenshots**
![nav scroll](https://user-images.githubusercontent.com/5121465/101846452-929cc900-3b16-11eb-9126-27d635e81dd5.gif)

**Additional context**
If someone could try and reproduce that would be great as my test sites have been bonkers lately - I tested on brand new JN sites in Firefox and Chrome and it was the same.

**Comment by becdetat** [comment]
I can reproduce this on a JN site:

- running WooCommerce 4.8.0 (and without WooCommerce Admin installed separately)
- running WC 4.8.0 with WooCommerce Admin main branch installed as a plugin

~But I _can't_ reproduce it on a local site running the latest main branch of WCA.~ I *can* reproduce it with the latest master version of WooCommerce. I couldn't when running WooCommerce as of 500 commits ago (I rarely update that clone). So this is going to be interesting to track down as there's some interaction between WC and WCA that started happening between now and 500 commits ago.
