### ISSUE TITLE
Add Table example and include pacakge.json in example plugin

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-admin#5870]
As soon as I add `import { Table } from '@woocommerce/components';` to my own script, I get the following error:
>Uncaught TypeError: _wordpress_components__WEBPACK_IMPORTED_MODULE_14__ is undefined`

So it would be great if there was a working example of the `Table` component. 

I'd also like to suggest that the `npm run example -- --ext=<example>` script copy the composer.json and package.json files to the new plugin so that plugin can actually be a functioning standalone that you can tinker on after you stop watching it from the `npm run example -- --ext=<example>` script.

Would also like to see the dependencies come from the `index.assets.php` file that is built by `npm run build`

**Comment by joelclimbsthings** [comment]
Closing this in preparation for the merge, as it's over a year old.
