### ISSUE TITLE
Navigation: WP 5.6 duplicate "back" buttons and wrong color

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5872]
With WP 5.6 there are two "back" buttons, which are also blue.

![Screen Shot 2020-12-14 at 1 46 55 PM](https://user-images.githubusercontent.com/1922453/102029351-0e4a8e80-3e13-11eb-97a2-127c536f96db.png)

## Deliverables

* Buttons should be white.
* Make sure there is only one "back" button and it has the correct text.
* Ensure that the button color isn't something affecting all of wc-admin and address it app-wide if it is.

**Comment by psealock** [comment]
Interestingly, when I deactivate `woocommerce-payments` the back button color goes back to what it should be. Not sure if the problem lies in this repo or that one.

**Comment by joelclimbsthings** [comment]
Hey @psealock , running WP 5.6 on my local with woocommerce-payments, but haven't been able to reproduce. 

Is this somehow related to [5753](https://github.com/woocommerce/woocommerce-admin/pull/5753)?

**Comment by psealock** [comment]
Yes! Sorry for not picking up on that. https://github.com/woocommerce/woocommerce-admin/pull/5753 uses the latest Gutenberg on 5.6. Another way to reproduce this is to bump `@wordpress/components` to `12.0.0` in package.json. So an update to base Nav component must be causing this.
