### ISSUE TITLE
Analytics -> Orders Export issue

### ISSUE THREAD

**Issue by artprojectgroup** [woocommerce/woocommerce-admin#5900]
Reported in https://wordpress.org/support/topic/analytics-orders-export-issue/

Tested in almost two websites.

When you export orders and send the CSV file by email the client column just show “new” or “recurrent”, not the full client name, but when the CSV file is downloaded directly, only when you select a small number of orders, that column show the client name.

Please fix this issue as soon as possible.

Thank you for your great job!

Kind regards.

**Comment by artprojectgroup** [comment]
Thank you.

**Comment by timmyc** [comment]
@artprojectgroup I believe this issue has already been reported, and a fix has shipped in #5181

As such I'm going to close this issue out, but if you still are experiencing an issue after updating to the latest version of WooCommerce with this feature, please do open this issue back up! Thanks for taking the time to report the bug - I appreciate it.
