### ISSUE TITLE
WooCommerce Setup Wizard: Missing Translation for "Choose any that apply"

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-admin#5902]
**Describe the bug**

While going through the WooCommerce setup wizard and noticed that "Choose any that apply" text is not translated (tested in Chinese and Korean so far) for the Industry and Product Type sections. It looks like they're both tagged correct for translation, for both the Industry and Product Type sections:

https://github.com/woocommerce/woocommerce-admin/blob/2fe04363fb3e2878580d9a4da589badeb183fd25/client/profile-wizard/steps/industry.js#L184

https://github.com/woocommerce/woocommerce-admin/blob/2fe04363fb3e2878580d9a4da589badeb183fd25/client/profile-wizard/steps/product-types/index.js#L117

It also appears to have a translated string, seen here: https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/ko/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9168148&filters%5Btranslation_id%5D=70713407

Is this just an issue with needing to run `xgettext` potentially? I am not sure how often those are generated files in the normal development/deployment workflow.

**To Reproduce**

1. Login to the WordPress admin console (with the WooCommerce plugin installed)
2. Go to: Dashboard > Settings > General and change the Site language to Korean.
3. Go to:  Dashboard > Updates and click on the button to update translations (`{base-url}/wp-admin/update-core.php`)
4. Open the WooCommerce Setup Wizard and navigate through to the industry (`{base-url}/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=industry`) and product types (`{base-url}/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=product-types`) pages
5. Note that "Choose any that apply" is still displayed in English

**Expected behavior**

All text should be translated into the target language that have 100% coverage (in this case, Korean: https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/ko/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=current)

**Screenshots**

![image](https://user-images.githubusercontent.com/71906536/102515469-0ecd6a00-404b-11eb-8eb1-1af61a891863.png)

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Chrome, FireFox
* Version: 87, 84

**Comment by moon0326** [comment]
Hi @zhongruige,

Thank you for taking the time to report this bug 👍 

I was able to reproduce it and found a possible cause. I will open a PR soon.

Possible cause:

`{ __( 'Choose any that apply' ) }` is missing namespace.

It should be

`{ __( 'Choose any that apply' , 'woocommerce-admin') }`

Thanks,
Moon

**Comment by zhongruige** [comment]
> Hi @zhongruige,
> 
> Thank you for taking the time to report this bug 👍
> 
> I was able to reproduce it and found a possible cause. I will open a PR soon.
> 
> Possible cause:
> 
> `{ __( 'Choose any that apply' ) }` is missing namespace.
> 
> It should be
> 
> `{ __( 'Choose any that apply' , 'woocommerce-admin') }`
> 
> Thanks,
> Moon

Thanks for the follow up @moon0326 !

**Comment by moon0326** [comment]
@zhongruige sure thing! [PR](https://github.com/woocommerce/woocommerce-admin/pull/5905) is open.

Thank you!
