### ISSUE TITLE
Deprecated usage of Jetpack’s JETPACK_MASTER_USER constant

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#5910]
**Describe the bug**
The codebase has deprecated [usage](https://github.com/woocommerce/woocommerce-admin/search?q=JETPACK_MASTER_USER&type=code) of [`JETPACK_MASTER_USER`](https://github.com/Automattic/jetpack/blob/fff3968a4ac99ef434ed6ea4e45854bd0bea0caf/jetpack.php#L21-L27) in logic for determining a Jetpack connection.

**Expected behavior**

Update usage of `JETPACK_MASTER_USER` to Jetpack's preferred approach for getting the user.

**Comment by adrianduffell** [comment]
The current usage might be broken, since Jetpack hardcodes a value of `true` for this value now instead of returning a user ID.

**Comment by adrianduffell** [comment]
@millerf This looks like it will be a simple change. I have started work on it in PR #5929.

**Comment by millerf** [comment]
That looks really promising! Seems like an easy fix!

**Comment by adrianduffell** [comment]
@millerf This is merged now in PR #5929.

It will ship in our upcoming 1.9 release, and in WooCommerce itself in the 5.0 release planned for early February.
