### ISSUE TITLE
Customer data not deleted from wc_customer_lookup on multisite

### ISSUE THREAD

**Issue by aheckler** [woocommerce/woocommerce-admin#5914]
**Describe the bug**

Thanks to https://github.com/woocommerce/woocommerce-admin/pull/4977, when a customer's user account is deleted from a single site, their data is deleted from `wp_wc_customer_lookup`. However, this does not work on multisite!

**To Reproduce**

1. Start with WP multisite, a subsite, WC installed, and a product published.
2. Configure your account settings to force account creation: https://d.pr/i/xpv5NQ/Sti6I3AsXl
3. Submit a test transaction, creating a test customer account in the process.
4. As the network super-admin, go to **My Sites > Network Admin > User**.
5. Delete the test user you just used to make the purchase, choosing to delete all content.
6. Back in the sub-site, look in **WooCommerce > Customers**. Their data remains.

**Expected behavior**

The record should be entirely deleted, even on multisite.

**Comment by joshuatf** [comment]
Estimate: 2

There are some oddities around how a user is deleted and I'm not sure the main `delete_user` action ever gets fired when deleting a multisite user.  See https://core.trac.wordpress.org/ticket/12720

We may want to look at using `remove_user_from_blog` or `wpmu_delete_user`.  Note that both of these events fire before the user is actually delete from `wp_users`.
