### ISSUE TITLE
Help tab inconsistent with site status

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#5918]
**Describe the bug**
I noticed two issues (see screenshot):

- In my local testing container I have the option to connect to wordpress.com onboarding. The site isn't on wordpress.com infrastructure and does not have Jetpack installed.
- I still have the option to `Disable` the task list after I have dismissed/hidden it on the home screen. Clicking `Disable` in the help screen doesn't toggle the setting so I have the option to re-enable the task list. 

**To Reproduce**

1. Go to WooCommerce -> Settings -> Help -> Setup Wizard
2. Click on `Disable` task list

**Expected behavior**
There should be a method a site owner could use to re-enable the task list. The WordPress.com option should only be shown on connected sites.

**Screenshots**
<img width="576" alt="Screen Shot 2020-12-21 at 1 53 58 PM" src="https://user-images.githubusercontent.com/343847/102806925-1ca92500-4394-11eb-9ac7-eb53a426716a.png">

**Comment by timmyc** [comment]
Quick note on some background of the feature via @joshuatf - this is a remnant from the initial development phase of the OBW when there was a good deal of work happening around Jetpack connectivity. As such, seems the most logical thing to do is to remove this.

**Comment by jeffstieler** [comment]
The Calypso section is included when the store has `WP_DEBUG` enabled. Removal should be super low impact.

> There should be a method a site owner could use to re-enable the task list

Perhaps we should move the setup wizard and task list toggles to the "help" menu on the homescreen?
