### ISSUE TITLE
Home Screen: layout refinements

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5931]
**Description:** after the 4.8 release we that a drop in the % of users interacting with the inbox messages (more context here: pbIJXs-vP-p2). This was expected as our main goal is to focus the user's attention on the store setup/management tasks. However, we think that users can completely miss all the notifications and we propose some refinements to the layout.

**Acceptance criteria:**

- [ ] In the two-column layout display the inbox panel below the setup and store management tasks: 
Left column: store setup and/or management tasks + inbox panel
Right column: stats overview + store management shortcuts
- [ ] In the single-column layout display the inbox panel above the stats overview if the user has the store setup tasks enabled. It should be in the following order: store setup tasks, inbox panel, stats overview.

**Comment by louwie17** [comment]
> In the single-column layout display the inbox panel above the stats overview if the user has the store setup tasks enabled. It should be in the following order: store setup tasks, inbox panel, stats overview.

@pmcpinto I assume the store management links will be at the very bottom in the single-column layout:
store setup tasks, inbox panel, stats overview, store management links (only showing when setup tasks isn't present)

**Comment by pmcpinto** [comment]
> @pmcpinto I assume the store management links will be at the very bottom in the single-column layout:
store setup tasks, inbox panel, stats overview, store management links (only showing when setup tasks isn't present)

Yes. That's correct.
