### ISSUE TITLE
Home Screen: Activity Panel JS Exception

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5933]
**Describe the bug**
When a store is in the setup state, and when viewed on a narrow viewport, clicking in the (w) activity panel icon results in a JS exception and a grey screen of death.

https://cldup.com/TEsM3Yfd2g.gif

**To Reproduce**

1. On a site where the setup checklist is shown
2. Emulate a mobile device by making the view port narrow
3. Click on the W icon to show the activity panels

I first encountered this behavior on 1.8 that is bundled in 4.8 - but tested locally against `main` and saw it happening there too. I've had the bug happen in both Mobile Chrome and Firefox.

**Expected behavior**
For the activity panels to be shown, which in this particular case is only the display settings on the home screen.

**Comment by samueljseay** [comment]
@timmyc I can't reproduce this on `main` now. Wondering if you could take another look at this with `main` on your local? I tried it with/without Gutenberg installed too just in case.

That said I see another bug where the menu that opens is visually broken. It works but barely and visually looks quite wrong. Wondering if we should close this and open a new one for the visual defect?

![Uploading Screenshot 2021-01-11 at 1.08.27 PM.png…]()

**Comment by timmyc** [comment]
Built a test zip from `main` and tried it out on a JN site and all seems well now.
