### ISSUE TITLE
New inbox message: Digital/Downloadable Product Handling

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5936]
**Title:** Learn more about digital/downloadable products
**Copy:** Congrats on adding your first digital product! You can learn more about how to handle digital or downloadable products in our documentation.
**Segmentation:** new users
**Timing:** After adding the first digital or downloadable product
**Cadence:** Once
**CTA leads to:** https://docs.woocommerce.com/document/digital-downloadable-product-handling/?utm_source=inbox
**CTA label:** Learn more

**Comment by moon0326** [comment]
@pmcpinto shouldn't the title be "Learn more about downloadable products"? Just double checking.

**Comment by pmcpinto** [comment]
> @pmcpinto shouldn't the title be "Learn more about downloadable products"? Just double checking.

@moon0326 you're right :) Thanks for the heads up. The title should be: Learn more about digital/downloadable products

I just fixed the issue description

**Comment by joshuatf** [comment]
Estimate: 1
