### ISSUE TITLE
[WC 4.9 with WC Admin 1.8.1] Help section on the Home Screen doesn't work if Onboarding is skipped

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5943]
**Describe the bug**

The `Help` section on the Home Screen (top right corner) doesn't work if Onboarding is skipped during the first step where the user needs to enter store address details. 

I tested in JN and Atomic - the issue was present in both cases. 

Note that if Onboarding is completed, the `Help` section works as expected. 

Below are gifs showcasing that `Help` doesn't work if Onboarding is skipped.

**JN:**

![](http://g.recordit.co/vFnS5JgOHm.gif)

**Atomic:**

![](http://g.recordit.co/jzX5sfoIJ9.gif)

**To Reproduce**

1. Create a brand new site.
2. Install and activate WooCommerce. Onboarding should start. 
3. On the first step of Onboarding (Store address details), click on `Skip setup wizard` option below the address field to skip the onboarding. 
4. You will be navigated to the Home Screen. 
5. Click on `Help` in the top right corner. 
6. You will see that the section will open but will never load. 

**Expected behavior**

I expected the `Help` section to work even if Onboarding is skipped. 

**Screenshots**

See gifs above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome 
* Version: 87.0.4280.88 (Official Build) (x86_64)

**Additional context**

N/A

**Comment by ilyasfoo** [comment]
Thanks for reporting @juliaamosova, I've successfully reproduced this in 1.8.1 and confirmed that this is fixed in 1.8.2 release.

PR: https://github.com/woocommerce/woocommerce-admin/pull/5941
