### ISSUE TITLE
Shipping task is automatically being marked as complete

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5953]
**Describe the bug**
The shipping task is automatically being marked as complete when I arrive at the home screen for the first time. This shouldn't happen as we reverted the smart defaults #5720 

**To Reproduce**

1. Complete the store profiler with the US as a country
2. Connect to Jetpack and WCS after completing the theme step
3. See that the shipping task is marked as complete when you arrive at the home screen. 

**Screenshots**
https://www.loom.com/share/4b455eacc1014474bc2fe7ceb08d1f22

**Comment by pmcpinto** [comment]
Hey @ilyasfoo I'm still getting this with 4.9 installed: https://www.loom.com/share/39259ce5462642788a6f147cb5d38fb6

AFAIR this was supposed to be fixed in 4.9, correct?

**Comment by ilyasfoo** [comment]
Hey @pmcpinto, it seems that this fix did not get included in wc-admin `1.8.3`. I wasn't aware that it did not get cherry-picked, terribly sorry 🙏  ! It seems the earliest it could get in is 5.0.

**Comment by pmcpinto** [comment]
@ilyasfoo now worries. AFAIK 1.9 is going to be included in 5.0
