### ISSUE TITLE
Update inbox message link: 💪Your first product message

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5954]
**Description:** We want to update the CTA link of the message that was implemented in #4223 as now there's an entire guide focused on shipping: https://woocommerce.com/posts/ecommerce-shipping-solutions-guide/?utm_source=inbox

**Comment by joshuatf** [comment]
@pmcpinto Since this is no longer a video, do we also want to update the copy in this note?

`This video tutorial will help you go through the process of adding your first product in WooCommerce.`

and

`Watch tutorial`

**Comment by pmcpinto** [comment]
@joshuatf sorry I mentioned the wrong inbox message. The message that needs to be updated is the one that was implemented in #4223

I'll update the issue title & description
