### ISSUE TITLE
New message: How to customize your product catalog

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5956]
**Title:** How to customize your product catalog
**Copy:** You want your product catalog and images to look great and align with your brand. This guide will give you all the tips you need to get your products looking great in your store.
**Segmentation:** new users
**Timing:** 1 day after adding the first product
**Cadence:** Once
**CTA leads to:** https://docs.woocommerce.com/document/woocommerce-customizer/?utm_source=inbox
**CTA label:** Learn more

**Comment by moon0326** [comment]
@pmcpinto Hey Pedro, what should happen if the user already has a few products and they are all 1+ old (existing stores)?

Let's say I have a store that is 20 days old and have 20 products then I upgrade WooCommerce with this change. What should happen?

I think we need one more condition. Maybe... the store is active for less than X days?

**Comment by pmcpinto** [comment]
That's a good question. Actually, there's another issue where we're discussing how to solve this across all the notifications: #4789

For this one let's add the following condition: the store is active for less than 14 days. Sounds good?

**Comment by moon0326** [comment]
@pmcpinto sounds good 👍
