### ISSUE TITLE
New message: New! Manage your store activity from the Home screen

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5957]
_Edit_ (@becdetat): implement a new remote inbox notifications rule to trigger on update (action `woocommerce_admin_updated`) and add the following note to WooCommerce.com's feed:

**Title:** New! Manage your store activity from the Home screen
**Copy:** Start your day knowing the next steps you need to take with your orders, products, and customer feedback. 

Read more about how to use the activity panels on the Home screen.
**Segmentation:** existing users
**Timing:** After updating WooCommerce to 4.9
**Cadence:** Once
**CTA leads to:** https://docs.woocommerce.com/document/home-screen/?utm_source=inbox
**CTA label:** Learn more

**Comment by pmcpinto** [comment]
@becdetat can we implement this one through the remote system and target existing users when they update to 4.9?

**Comment by becdetat** [comment]
> can we implement this one through the remote system and target existing users when they update to 4.9?

No, there's no existing rule that would trigger on update. It wouldn't be difficult to create one but obviously it would need to go out with a new version.

Unless you see a problem, I'll add a new rule to trigger on update and add the note to woocommerce.com's feed.

**Comment by pmcpinto** [comment]
@becdetat when do you think that we can trigger this notification?

**Comment by becdetat** [comment]
@pmcpinto I've run into a couple of minor wrinkles in the implementation of this. I think it would actually be better to include this in 1.9.0 for existing users and just remove it in 2.0.0 (if you only want to show this for users upgrading to WC 4.9 specifically).

**Comment by pmcpinto** [comment]
@becdetat but that means that the users will only see the message in 5.0 right? Because it's when we include 1.9.0

**Comment by becdetat** [comment]
@pmcpinto Oh bugger, I assumed that 1.9.0 was going in 4.9. There's no way around this, there is no way for remote inbox notifications to trigger on upgrade without a new version anyway.

**Comment by becdetat** [comment]
@pmcpinto This is handled by a new non-remote note in #6072 which has been cherry-picked into 1.9.0
