### ISSUE TITLE
New message: The first 5 things to customize in your store

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5958]
**Title:** The first 5 things to customize in your store
**Copy:** Deciding what to start with first is tricky. To help you properly prioritize, we’ve put together this short list of the first few things you should customize in WooCommerce.
**Segmentation:** new users
**Timing:** Two days after plugin install if wcadmin_tasklist_task_completed = 0
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/posts/first-things-customize-woocommerce/?utm_source=inbox
**CTA label:** Learn more

**Comment by joshuatf** [comment]
Estimate: 1

**Comment by moon0326** [comment]
PR is ready https://github.com/Automattic/woocommerce.com/pull/9266
