### ISSUE TITLE
New message: Optimizing the checkout flow

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5959]
**Title:** Optimizing the checkout flow
**Copy:** It’s crucial to get your store’s checkout as smooth as possible to avoid losing sales. Let’s take a look at how you can optimize the checkout experience for your shoppers.
**Segmentation:** new users
**Timing:** 3 days after wcadmin_tasklist_task_completed - task_name: payments
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/posts/optimizing-woocommerce-checkout?utm_source=inbox
**CTA label:** Learn more

**Comment by joshuatf** [comment]
Estimate: 3

I'm estimating this a bit on the high side because we currently have no way of knowing when the payments task was completed.  We could just store this as another option, or store meta information about all tasks, but this data requires a bit more thought.

**Comment by louwie17** [comment]
> we currently have no way of knowing when the payments task was completed.

Meaning, that we do know when a task is completed, but don't store on which date a task has been completed.
This would require us to store the task list completion somewhere.

**Comment by moon0326** [comment]
> Estimate: 3
> 
> I'm estimating this a bit on the high side because we currently have no way of knowing when the payments task was completed. We could just store this as another option, or store meta information about all tasks, but this data requires a bit more thought.
> 
> I'd estimate at a 1 if this is just using how long the store has been active for.

Pedro has confirmed that we can just use the following conditions.

1. The store has been active for at least 3+ days
2. User has completed `payments` task.

More on [here](https://github.com/Automattic/woocommerce.com/pull/9355)
