### ISSUE TITLE
How to make build of WC admin extension with custom analytics report

### ISSUE THREAD

**Issue by SanketChodavadiya** [woocommerce/woocommerce-admin#5988]
I am trying to create a new WC extension for the analytics report using this command `npm run create-wc-extension` and it successfully created all files and folders([Partially followed this guide](https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/)).

The problem is when I add this [https://github.com/woocommerce/woocommerce-admin/blob/main/docs/examples/extensions/add-report/js/index.js](https://github.com/woocommerce/woocommerce-admin/blob/main/docs/examples/extensions/add-report/js/index.js) code to the `src/index.js` file and run `npm run build` or `npm start` which creates `build/index.js`.

Then I try to browse this new report I am getting this console error and nothing is showing on the screen.

```Uncaught TypeError: Cannot read property 'ReportFilters' of undefined```

![image](https://user-images.githubusercontent.com/21277725/103398841-621fdc00-4b64-11eb-8013-294ec9c1aeba.png)

If there are any specific guidelines that I am missing here please point me out or anyone figured out how to do it.

**Comment by Ecknauer** [comment]
I have same issue following the guide and also this article:
https://gorohovsky.com/extending-woocommerce-javascript-react/

I've managed to register new report and woocommerce navigation bar. However, when simply trying to insert and render once component (e.g. Date picker) I have these errors in console
![screenshot-nimbus-capture-2021 01 11-12_28_55](https://user-images.githubusercontent.com/19519997/104219055-9a98a300-540b-11eb-9b8a-33b246ad4df7.png)

**Comment by Ecknauer** [comment]
> I am trying to create a new WC extension for the analytics report using this command `npm run create-wc-extension` and it successfully created all files and folders([Partially followed this guide](https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/)).
> 
> The problem is when I add this https://github.com/woocommerce/woocommerce-admin/blob/main/docs/examples/extensions/add-report/js/index.js code to the `src/index.js` file and run `npm run build` or `npm start` which creates `build/index.js`.
> 
> Then I try to browse this new report I am getting this console error and nothing is showing on the screen.
> 
> `Uncaught TypeError: Cannot read property 'ReportFilters' of undefined`
> 
> ![image](https://user-images.githubusercontent.com/21277725/103398841-621fdc00-4b64-11eb-8013-294ec9c1aeba.png)
> 
> If there are any specific guidelines that I am missing here please point me out or anyone figured out how to do it.

Hi, please check your index.js inside of build folder. The problem in my case was that whatever @woocommerce component was not well defined, for instance:

/***/ "@woocommerce/currency":
/*!*******************************************!*\
  !*** external {"this":["wc","currency"]} ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

(function() { module.exports = window[undefined]; }());

/***/ }),

Should be as

(function() { module.exports = window["wc"]["currency"]; }());

**Comment by SanketChodavadiya** [comment]
Hi @Ecknauer 
Yes, the same thing happens to me ```(function() { module.exports = window[undefined]; }());```

**Comment by Ecknauer** [comment]
> Hi @Ecknauer
> Yes, the same thing happens to me `(function() { module.exports = window[undefined]; }());`

If you change the values of [undefined] as on the screenshots above - you will be able to use components in your custom reports. However, you have always copy&paste these values as after every refresh the index.js is being recompiled again with [undefined]. I believe that something is wrong with WebPack config

**Comment by joshuatf** [comment]
Hi @SanketChodavadiya 👋 

In this case, the thing that was undefined was `@woocommerce/components`.  `wc-components` needs to be added as a dependency for your JS script and your Webpack config needs to be setup to attach this global to your `@woocommerce/components` import.

All that said, I recommend starting from one of the example components which has all of this done for you:

`npm run example -- --ext=add-report`

You can read about the setup for those and available examples [here](https://github.com/woocommerce/woocommerce-admin/tree/main/docs/examples/extensions) and feel free to ping me if you have any further questions!

**Comment by TobyOsborne** [comment]
Hi, @joshuatf 

I think the original issue is being caused by https://github.com/woocommerce/woocommerce-admin/blob/5c968f00382c6d356c1e53da019a8d4a9439f56e/packages/dependency-extraction-webpack-plugin/src/index.js#L77

Where it adds `this` changing the line to `return callback(null, externalRequest);` solves the problem, but I'm guessing it's like that for a reason?

**Comment by adrianduffell** [comment]
> Where it adds this. changing the line to return callback(null, externalRequest); solves the problem, but I'm guessing it's like that for a reason?

cc @psealock I think you might be best placed to answer this?

**Comment by psealock** [comment]
Thanks for the suggestions everyone. Lots has changed recently and the best way to get everything working, including 
WooCommerceDependencyExtractionWebpackPlugin is to use the `create-wc-extension` script. Here are steps to get an import from `@woocommerce/components` working.

1. `npm run create-wc-extension`
2. `cd` into the new directory
3. `npm install`
4. `npm install --save @woocommerce/components`
5. Add the following code to `src/index.js`
```js
/**
 * External dependencies
 */
import { ReportFilters } from '@woocommerce/components';

console.log( ReportFilters );
```
6. Activate the plugin and see ReportFilters function defined in the console
