### ISSUE TITLE
woocommerce_rest_prepare_product_object called when response is not product object

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce-admin#5989]
**Describe the bug**
The WooCommerce admin page triggers a call to the following URI:
/wp-json/wc-analytics/products?page=1&per_page=1&low_in_stock=true&status=publish&_fields%5B0%5D=id&_locale=user

If that returns matching products, then the `woocommerce_rest_prepare_product_object` filter is called for each of the products in order to enrich the response object. However, in this instance the response isn't a product object at all, it's just a product ID. 

It seems that either:

- A different filter should be invoked when the response is a set of product fields, rather than a full product object. That filter should include the response assembled by WooCommerce, the object, the request, and the requested fields
- There should be an easy way of retrieving the list of desired fields given the inputs available to that filter (as far as I can tell there's no easy way to get the list of requested fields given the current data passed to the filter without re-parsing the request?)

**Comment by chihsuan** [comment]
I'm closing this because the `woocommerce_rest_prepare_product_object` filter doesn't exist in our repo now.
