### ISSUE TITLE
Update to corejs 3 to fix polyfills

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#5991]
**Describe the bug**
To continue supporting older browsers, we need some of the polyfills provided in corejs.  https://github.com/woocommerce/woocommerce-admin/pull/5987 added a quick fix for this, but long-term it would be nice to not worry about ES6 support.

There has been some work around this before but I seem to recall some blockers to upgrading.  /cc @psealock

**Comment by samueljseay** [comment]
Excited to close this! I fixed this in https://github.com/woocommerce/woocommerce-admin/pull/6411
