### ISSUE TITLE
[WC 4.9 RC1] WooCommerce Admin translation files are not created during a new installation

### ISSUE THREAD

**Issue by shoheitanaka** [woocommerce/woocommerce-admin#6022]
**Describe the bug**
WooCommerce Admin translation files are not created during a new installation.
The woocommerce-ja-wc-admin-app.json file already exists and there is no problem when updating.

**To Reproduce**
Set WordPress to a language such as Japanese.
The woocommerce-ja-wc-admin-app.json file is not created when I install WooCommerce and run the setup wizard.
Not translated at the setup wizard.
Also, it is not partially translated in Json of WooCommerce Admin.

**Screenshots**
https://www.dropbox.com/s/v8o1lsvfhc1sh35/screenshot-2021-01-07.png?dl=0

**Expected behavior**
I want you to be translated.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

ホーム URL。: https://latest-wc.demo01web.info
サイト URL。: https://latest-wc.demo01web.info
WooCommerce バージョン。: 4.8.0
ログのディレクトリ。: /home/artws/demo01web.info/public_html/latest-wc/wp-content/uploads/wc-logs/
ログのディレクトリは書き込み可能ですか ?: yes
WordPress バージョン。: 5.6
WordPress はマルチサイトですか ?: no
WordPress メモリ制限。: 1073741824
WordPress デバッグ モードは有効ですか ?: no
WordPress cron ジョブは有効化済みですか ?: yes
WordPress の言語。: ja
External object cache: no
サーバー情報。: Apache
PHP バージョン。: 7.4.4
PHP POST サイズ上限。: 1073741824
PHP 最長実行時間。: 180
PHP の変数入力最大数。: 1000
cURL バージョン。: 7.29.0, NSS/3.36
SUHOSIN はインストールされていますか ?: no
最大アップロードサイズ。: 1073741824
MySQL バージョン。: 5.7.27
MySQL バージョン: 5.7.27
標準のタイムゾーン。: UTC
fsockopen/cURL は有効化済みですか ?: yes
SoapClient クラスは有効化済みですか ?: yes
DomDocument クラスは有効化済みですか ?: yes
GZip は有効化済みですか ?: yes
mbstring は有効化済みですか ?: yes
リモート POST 成功 ?: yes
リモート POST レスポンス。: 200
リモート GET 成功 ?: yes
リモート GET レスポンス。: 200

### Plugins ###

WooCommerce Beta Tester: by WooCommerce - 2.0.2 - 
WooCommerce: by Automattic - 4.8.0 - 

### Theme ###

Name: Storefront
Version: 3.1.0
Author URL: https://woocommerce.com/
Child Theme: No - If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme.
WooCommerce Support: Yes

</details>

**Comment by shoheitanaka** [comment]
Thanks juliaamosova!

**Comment by adrianduffell** [comment]
Fixed in https://github.com/woocommerce/woocommerce-admin/pull/6028
