### ISSUE TITLE
Navigation [1.9]: Disable Core feature flag

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6029]
EDIT: I realized I wasn't been very clear in what needs to happen and instead jumped to thinking about solutions. Below, I will rework the requirements and let the ticket owner sort out what needs to be done (if at all). I will keep the original description if anyone is curious.

## Deliverables

* Turn off feature flag for Core
* Keep feature flag on for Plugin and Dev builds
* Make sure feature toggle in Settings is **only visible** in Plugin and Dev builds

## Original Description

This is a touch confusing, so I'll go through my understanding and there may be a chance I'm thinking about it wrong:

1.9 Requirements in https://github.com/woocommerce/woocommerce-admin/issues/5942 dictate that only a subset of users will be able to turn on the Navigation.

Currently, we can control the feature flag and check in PHP via `Loader::is_feature_enabled( 'navigation' )`. That check uses the option `woocommerce_navigation_enabled` to determine if the feature is enabled.

We'll need a way to conditionally expose the feature toggle introduced in https://github.com/woocommerce/woocommerce-admin/pull/6007. Using the feature flag won't work because if the option is "no" or doesn't exist, the result will always be `false`.

I see two ways to handle this:

1. Separate the option and flag logic in the `Loader::is_feature_enabled( 'navigation' )` check.
2. Somehow use the environment (dev, plugin, production) to conditionally add the feature toggle. This seems to make the most sense because messing with the Loader function risks introducing a bug. Since the feature toggle will only be available to dev and plugin builds, maybe there is a way to handle this. Maybe a new flag `navigation-feature-toggle`? 

I'm open to ideas here.

**Comment by joshuatf** [comment]
I agree that the `is_feature_enabled()` method and the option check are confusing, partially because of the naming implications and partially because we tie them together in the case of the nav feature.

But I'm not quite sure I understand the issue hiding or showing the feature.  Aren't we able to add/remove this feature via `woocommerce_admin_features` as we do currently in the bridge?  Or am I missing something that's not working?

The bridge turns on the feature itself at the code level even if the build does not have the flag on by default.  It then allows the toggle to be used in addition to turning it on by default for ecomm plan users.

**Comment by psealock** [comment]
Thanks for the comments Josh. This is different this time because the differentiating element is plugin v. core build versions. 

If we wrap the feature toggle in `is_feature_enabled( 'navigation' )` then the feature toggle will disappear when the option is set to "no". This is why I think we need a new feature called `is_feature_enabled( 'navigation-feature-toggle' )` or something to handle just the feature toggle, not the feature itself.

Of course I may be wrong here or am trying to solve problems instead of outlining deliverables. Instead, I'll reword this issue to outline the deliverables and whoever grabs this can determine the best solution, if required.

**Comment by psealock** [comment]
Confirmed: This is working as expected, no changes required. Note: use `WC_ADMIN_PHASE=core npm run test:zip` to test a core build
