### ISSUE TITLE
Store Profiler - Industry step - error when I try to move past this step

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6041]
**Describe the bug**
I'm not able to move past the industry step, I'm getting an error message saying: There was a problem updating your industries

**To Reproduce**
1. Create a new Woo store using JN
2. Fill the store details in the 1st step of the profiler (I selected Germany as the country)
3. Select one or more industries
4. See error (I wasn't able to reproduce it though) 

**Expected behavior**
Select one or more industries and move on to the next step

**Screenshots**
https://www.loom.com/share/914c5443f44a4652994a696b1cebbf19
The error that I'm getting in the Chrome console: 
<img width="1431" alt="Captura de ecrã 2021-01-11, às 10 48 18" src="https://user-images.githubusercontent.com/3380168/104171459-9a43dc00-53fa-11eb-9ceb-da16a1fe9aaf.png">

**Comment by samueljseay** [comment]
Looking at your stack trace there it looks like a request to the server failed (503 means unavailable) and then the code crashed. Its good to see that we show an error message for this, but maybe some better error handling is needed. I am going to go out on a limb though and say its unlikely that this was a bug with wc-admin in this case.

**Comment by pmcpinto** [comment]
Thanks for the quick reply on this one. Interestingly, a couple of months ago we started seeing a drop in the Industries step conv. rate but we ended up not finding the root cause of that. Probably is not a bug like this or we would have noticed a long time ago. If you feel that this is not a bug with wc-admin we can close this one
