### ISSUE TITLE
Inconsistent button behavior/look in OBW steps

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#6044]
**Describe the bug**

The business details and theme selection steps in OBW use `isBusy` props to display animated busy state when the buttons are clicked while the previous steps don't as mentioned by @becdetat  in https://github.com/woocommerce/woocommerce-admin/pull/6002

**To Reproduce**

1. Install WooCommerce and start OBW
2. Notice buttons do not show disabled state or animation when you click until the business details step

**Expected behavior**

Buttons should have the same design/look at least in the OBW

**Screenshots**
Clicked button state in business details and theme selections steps
![Screen Shot 2021-01-11 at 5 38 39 PM](https://user-images.githubusercontent.com/4723145/104258200-dc3d4400-5433-11eb-9844-29605d53f638.jpg)

Clicked button state in other  steps:

![Screen Shot 2021-01-11 at 5 38 14 PM](https://user-images.githubusercontent.com/4723145/104258182-cdef2800-5433-11eb-9316-2b69d17a165f.jpg)

**Comment by moon0326** [comment]
@elizaan36 Hi ✋ Do you think it's okay to use the animation effect on the other buttons to make the buttons look consistent on all pages?

**Comment by elizaan36** [comment]
hey @moon0326 yes absolutely! The buttons in onboarding should all have the consistent loading state.
