### ISSUE TITLE
Append tags to new nav Crowdsignal survey

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6051]
Currently, we’re receiving feedback in [a Crowdsignal survey](http://automattic.survey.fm/new-navigation) from core users that enabled the nav through wcadmin 1.8.2 and in the upcoming weeks we’re also going to get feedback from eCommerce and Business plan users. However, we don’t have a way to segment their feedback.

Specifically, we're wondering if it’s possible to include a parameter indicating if the user is coming from either eCom, Business plan, or other place.

I reached out to the Crowdsignal folks and it would only be possible if we can [append the tags in the URL](https://crowdsignal.com/support/using-custom-tags-to-track-survey-responses/).

This issue is more of a exploration into whether or not we can construct the survey link based on the user account so the results contain the tags we need. If it works we'd lean towards something like that to identify people, rather than having multiple surveys or seeding the survey data with an additional question.

cc @pmcpinto @psealock

**Comment by pmcpinto** [comment]
@joshuatf do you know when this will be available? So we can start identifying if users are coming from the eCommerce plan, Business plan or Core

**Comment by joshuatf** [comment]
@pmcpinto This should be available in 1.9.0, we just need to use the `woocommerce_admin_survey_query` filter in the bridge to add any necessary data.

I'll open an issue there.

**Comment by joshuatf** [comment]
Issue created here - https://github.com/Automattic/wc-calypso-bridge/issues/636
