### ISSUE TITLE
Navigation: Update link colors with Gutenberg 9.7.1

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6052]
Gutenberg 9.7.1, which hasn't shipped yet, changes link colors. With the plugin activated, you can only see links on hover.

<img width="239" alt="Screen Shot 2021-01-13 at 9 08 40 AM" src="https://user-images.githubusercontent.com/1922453/104367080-2ed74700-557f-11eb-88a0-9d9f3f0ee443.png">

## To Reproduce

1. Run a development version of Gutenberg `master` branch.
2. Activate Gutenberg plugin
3. See `<a />` links not visible

## Deliverables

* Ensure links are visible and the correct colors with Gutenberg 9.7.1
* Makes sure it also works with Gutenberg plugin deactivated with WP 5.6

**Comment by joshuatf** [comment]
@psealock I wasn't able to repoduce this issue.  It seems like the item title is inside a `span` within the `Button` component and contains explicit color overrides:

```js
export const ItemUI = styled.div`
	...
	color: ${ G2.lightGray.ui };
`;
```

Is there anything else that needs to be done to reproduce this issue or are you seeing this color being overridden in your environment?

**Comment by joshuatf** [comment]
I can reproduce this now.  It only seems to occur on WCA pages with the GB dev plugin active for some reason.

Estimate: 1

**Comment by timmyc** [comment]
I placed this issue in the 2.0 milestone because the ecommerce plan receives auto-updates of gutenberg by default. And since these users are also opted in to nav by default, this could be a high impact bug there. I did not check the timeline for the release of gutenberg, but depending on when that is, we might even consider doing a css patch in _The Bridge_ just in case.

**Comment by psealock** [comment]
Here is a PR solving the root issue in Gutenberg https://github.com/WordPress/gutenberg/pull/28619

>but depending on when that is, we might even consider doing a css patch in The Bridge just in case.

I haven't done the calculation yet, but it may go the other way where the above fix goes out in the next wp.org release and we don't need to fix it anywhere else.

**Comment by psealock** [comment]
Version 9.8.3 of Gutenberg is already on wp.org, but I can't reproduce the on my eComm plan. Locally, 9.8.3 breaks which is odd. In any case, a Bridge fix may be in order.

**Comment by psealock** [comment]
I have duplicated the CSS overrides in wc-admin in https://github.com/woocommerce/woocommerce-admin/pull/6254. I think that with these changes going out in wc-admin 2.0, we won't need to also apply overrides in The Bridge because the changes in this repo will be deployed and published first.
