### ISSUE TITLE
Navigation [1.9]: Double Feature Toggles

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6056]
With the feature turned on, two checkboxes appear. I originally thought it may be coming from the bridge, but thats not the case. 

<img width="817" alt="Screen Shot 2021-01-13 at 2 13 29 PM" src="https://user-images.githubusercontent.com/1922453/104393927-6c9d9500-55aa-11eb-9131-772a70f515eb.png">

## Deliverables

* Make sure the option only appears once.

**Comment by psealock** [comment]
Noting that I can't reproduce on Jurassic Ninja. This may be related to my environment

**Comment by joshuatf** [comment]
Also wasn't able to reproduce.  My first suspicion would also be the bridge, but this bug persisted when the bridge plugin was deactivated, right @psealock?

**Comment by psealock** [comment]
Thats right. Thanks for confirming. I am seeing some really odd behaviour concerning options in my local install. I wonder if thats related.

<img width="647" alt="Screen Shot 2021-01-14 at 8 56 13 AM" src="https://user-images.githubusercontent.com/1922453/104503823-6ceb6e00-5646-11eb-8894-3a3f85cb0733.png">

I think its safe to say this is a problem I'm having so I will close this out
