### ISSUE TITLE
Search component does not accept static options Array in autocomplete

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6061]
**Describe the bug**
I'm not 100% sure whether it's a bug, the desired behavior, or just out-dated docs.

I'm trying to set up a `Search` component (actually a `FilterPicker` with `Search` inside), with a custom `type`.
The [wc-component docs](https://woocommerce.github.io/woocommerce-admin/#/components/packages/search/README?id=props) says that I need to provide an `autocompleter` and links to [Gutenberg's docs defining the interface](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/autocomplete#the-completer-interface)
Which states that `options` should be "Type: `Array|Function`".
When I provide an Array, it throws with 
```console
index.js:112 Uncaught TypeError: autocompleter.options is not a function
    at Search.fetchOptions (index.js:112)
    at SelectControl.updateFilteredOptions (index.js:241)
    at e (lodash.min.js?ver=4.17.19:86)
    at c (lodash.min.js?ver=4.17.19:87)
    at f (lodash.min.js?ver=4.17.19:87)
```

https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/search/index.js#L112
Obviously expect a function that returns a promise.

**To Reproduce**

1. Create `<Search>` with custom type and Array in autocomplete options, like the one given in [docs example](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/autocomplete#usage):
	```js
	{
			name: 'fruit',
			// The prefix that triggers this completer
			triggerPrefix: '~',
			// The option data
			options: [
				{ visual: '🍎', name: 'Apple', id: 1 },
				{ visual: '🍊', name: 'Orange', id: 2 },
				{ visual: '🍇', name: 'Grapes', id: 3 },
			],
			// Returns a label for an option like "🍊 Orange"
			getOptionLabel: option => (
				<span>
					<span className="icon" >{ option.visual }</span>{ option.name }
				</span>
			),
			// Declares that options should be matched by their name
			getOptionKeywords: option => [ option.name ],
			// Declares that the Grapes option is disabled
			isOptionDisabled: option => option.name === 'Grapes',
			// Declares completions should be inserted as abbreviations
			getOptionCompletion: option => (
				<abbr title={ option.name }>{ option.visual }</abbr>
			),
		}
	```

**Expected behavior**
The component should be rendered.

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Win10
* Browser [e.g. chrome, safari] Chrome, Firefox

**Comment by adrianduffell** [comment]
@tomalec this looks like a bug. I think it would be better to support all of the valid type of `options` possible for the `autocompleter`.

Are you interested in creating a PR for this?
