### ISSUE TITLE
WooCommerce dashboard notes are not translated after updating language

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#6063]
**Describe the bug**
Notes in WooCommerce dashboard do not get translated again after they are displayed. If someone updates the language after having gone through the OBW already, the initial notes will still be in the original language.

**To Reproduce**

1. Install latest WooCommerce (4.9 where Admin is 1.8.3)
2. Finish or skip through the OBW
3. Look at the notes, they should be the original language you selected
4. Go to **Settings > General** and update the language, to either (Spanish, Dutch, or German - Deutsch)
5. Go to **Dashboard > Updates** and select **Re-install the language pack**
6. Go to **WooCommerce > Home** and notice that everything is translated except for the title, description, and action button in the notes.

**Expected behavior**
Notes (title, description, and action button) should be translated as well when switching the language.

**Screenshots**
<img width="1253" alt="Screen Shot 2021-01-13 at 11 02 48 AM" src="https://user-images.githubusercontent.com/2240960/104469876-64842c00-558f-11eb-9ed6-eb81fbdf5ad0.png">

**Desktop (please complete the following information):**

* OS: OSx
* Browser: Chrome
* Version: Latest

**Additional context**

**Comment by ilyasfoo** [comment]
This is a tricky one, note contents are stored in database

**Comment by louwie17** [comment]
> This is a tricky one, note contents are stored in database

I did notice that, is there a particular reason why the title and content is stored in the database? It actually saves the locale as well.
Having the title, content, and locale in the DB seems unnecessary to me, given each note has a unique name that it can be looked up by.
I will have to try to find the original implementation.

**Comment by louwie17** [comment]
Had to go quite far back, but found the [original implementation of the notes datastore](https://github.com/woocommerce/woocommerce-admin/pull/464), in this PR it is tested by generating a Note through Woo, which would qualify the title, content, and locale being in the DB.
@timmyc would this still be relevant? (It seems kinda backwards to create notes in WooAdmin, when we only display it on WooAdmin).
Otherwise we did have to regenerate notes in the DB for a new locale, and respect that when loading them.

**Comment by becdetat** [comment]
Notes aren't just generated in code, there is also a remote inbox notifications system that generates notes and persists them in the database (via a feed coming from woocommerce.com - https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json). I think removing notes from the database would be next to impossible at this point.

**Comment by timmyc** [comment]
Good find on this issue @louwie17 - I would imagine the case of having a site set to one language, notes generated and persisted to the db, and then subsequently changing the site language was never considered in the initial implementation. I agree that the solution shared of deleting/regenerating the notes under the new language might be the one route forward here.

Also worth considering that this hasn't been reported by a user before, so perhaps it might not be a real-world case that happens too often.

**Comment by mattsherman** [comment]
Customer report of this in the WordPress.org forums:

https://wordpress.org/support/topic/some-strings-in-the-interface-are-not-translated/

**Comment by ilyasfoo** [comment]
Closing this as it's not prioritized at the moment.
