### ISSUE TITLE
[GlobalStep - WooCommerce 4.9] "Display" option fails to collapse upon invoking "Help" option on header tab for "WooCommerce->Home" Page

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6074]
## Bug Description:
"Display" option fails to collapse when "Help" option on header tab is invoked on "WooCommerce->Home" Page

## Environment:
Windows 10, macOS Mojave v10.14.6 (18G103)
Browser: Chrome(Version 87.0.4280.88 (64-bit))
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.1 (14609.2.9.1.3)
                
 
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard 
1. Goto WooCommerce->Home
1. Click on "Display" option
1. Click on "Help" option
1. Observe that "Display" option fails to collapse when "Help" option on header tab is invoked

## Actual Result:
"Display" option fails to collapse when "Help" option on header tab is invoked on "WooCommerce->Home" Page

## Expected Result:
"Display" option should collapse when "Help" option on header tab is invoked on "WooCommerce->Home" Page

## Video:

https://user-images.githubusercontent.com/41110392/104608568-0ac35500-56a8-11eb-9495-fdad1fc039fb.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by joshuatf** [comment]
Thanks for the issue @gglobalstep!  I think the issue description is reversed, but I can reproduce the "Help" tab not closing when the "Display" option is clicked as seen in the video.

It appears that we use `react-click-outside` to detect the click, but this event doesn't fire when clicking on the activity panel buttons.  We might consider removing this dependency and instead using `withFocusOutside` which may (or may not) solve the issue.

**Comment by hsingyuc** [comment]
I'll try this one

**Comment by gglobalstep** [comment]
@joshuatf "Display" option fails to collapse when the user clicks on it. 
(Note: For help option, it closes when user clicks on it) 

Environment:
Woocommerce Version : WooCommerce 5.2.2
WooCommerce Admin: v2.3.0 Beta 1
WordPress version: (v5.7)

PC:
Mac 10.14.6
Safari: v13.1.1
(Note: On Windows its working properly for both Help and Display option)

Please refer to the below Attachment

https://user-images.githubusercontent.com/41110392/115542241-b4287100-a2bd-11eb-91c1-57b24dae178d.mov
