### ISSUE TITLE
Nav: Add Order Button and Screen Options conflict

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6080]
**Describe the bug**

Original report in p7DVsv-ae2-p2

![image](https://user-images.githubusercontent.com/22080/104783283-88d03c00-573a-11eb-8b56-795e9629fc64.png)

**To Reproduce**
In a narrow viewport with nav enabled, visit the order listing page and note the overlap of the screen options drop down and the Add Order buttona

**Comment by louwie17** [comment]
This is (semi) related to #6148

**Comment by joshuatf** [comment]
Estimate: 1

However, I do think that maybe we should invest some time into thinking how to make the header height detectable across the entire app more easily.

This has become a source of bugs whenever something is changed and/or dynamic content exists.  Currently there are 4 issues addressing various problems with the header height.

Estimate: 3 if we decide to spend more time into more dynamic header heights.

**Comment by timmyc** [comment]
As @joshuatf noted in his last comment, we are opting to add #6235 to the sprint cycle instead of fixing this and other header height bugs. As such I'm going to put this in the backlog for now pending what is found in the spike.

**Comment by joshuatf** [comment]
<img width="430" alt="Screen Shot 2021-03-09 at 8 58 17 AM" src="https://user-images.githubusercontent.com/10561050/110481550-b2ac3c00-80b5-11eb-8a09-074d4c18ce83.png">

This appears fixed on the latest `main` after the header refactor.  Closing this issue.
