### ISSUE TITLE
Close tooltip in intro modals is whacky

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#6085]
**Describe the bug**
The intro modal's close tooltip is inconsistent; it goes offscreen, scrollbars are added, or it just doesn't get displayed at all.

Note that this uses the `Guide` component from `@wordpress/components` which is part of Gutenberg, so it may need to be fixed there.

Chrome:
![image](https://user-images.githubusercontent.com/224531/104862875-0c2e9f00-5980-11eb-939f-d4dc2885b45f.png)

Firefox:
![image](https://user-images.githubusercontent.com/224531/104863002-84956000-5980-11eb-9ac2-0ac8d34c43e9.png)

Safari doesn't show the tooltip at all.

You can display an intro modal by setting `shouldShowWelcomeModal = true` in `client/homescreen/layout.js`.

**Comment by moon0326** [comment]
I was able to reproduce it.

For those who are on mac and want to test it, make sure to change "Show scroll bars" option in Preferences -> General to "Always". It's not so obvious when other options are turned on.

![Screen Shot 2021-01-18 at 3 05 33 PM](https://user-images.githubusercontent.com/4723145/104969913-a00f6380-599e-11eb-8f3a-d5fe7605a58b.jpg)

**Comment by moon0326** [comment]
The tooltip comes from the [popover](https://wordpress.github.io/gutenberg/?path=/story/components-popover--default) component (Guide -> Modal -> Button -> Tooltip -> Popover). I think this is going to be a bit tricky to fix or at least take some time to find a proper solution.

In the meantime, we can disable the tooltip if that's okay for the accessibility. What do you think @becdetat? Is there anyone we can confirm it?

**Comment by moon0326** [comment]
The tooltip comes from the [popover](https://wordpress.github.io/gutenberg/?path=/story/components-popover--default) component (Guide -> Modal -> Button -> Tooltip -> Popover). The official Gutenberg modal has the same bug. You can see it on [here](https://wordpress.github.io/gutenberg/?path=/story/components-modal--default).

I think this is going to be a bit tricky to fix or at least take some time to find a proper fix. 

Is it an option to disable the popover as a temporary workaround while the component is being invested and fixed @becdetat?

**Comment by becdetat** [comment]
This does not need to be a blocker for launching sunsetting the store. It's an existing issue that just doesn't seem to have been discovered or addressed yet. I would rather not add in temporary workarounds in this case, they'll just mask the underlying issue.

**Comment by moon0326** [comment]
> This does not need to be a blocker for launching sunsetting the store. It's an existing issue that just doesn't seem to have been discovered or addressed yet. I would rather not add in temporary workarounds in this case, they'll just mask the underlying issue.

Cool 👍 I will open an issue in the Gutenberg repository for now.

**Comment by moon0326** [comment]
Opened issue: https://github.com/WordPress/gutenberg/issues/28311

**Comment by timmyc** [comment]
Just saw this issue, wondering if this might be what is causing a horizontal scroll bar to show when hovering over the close "x" in #6125

**Comment by moon0326** [comment]
@timmyc I think it is. I've opened an issue in Gutenberg repo a few days ago. I can look into it further we don't get an update soon.

**Comment by samueljseay** [comment]
This is resolved at least temporarily by https://github.com/woocommerce/woocommerce-admin/pull/6142 I believe? Feel free to reopen if I've made a mistake.
