### ISSUE TITLE
Cannot update the component docs

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6098]
**Describe the bug**
I tried to update the docs, by updating JSDocs of a component's prop, then running `npm run docs`, but nothing changed.

**To Reproduce**

1. Change the line https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/date-range-filter-picker/index.js#L178 to ` * Foo`
2. Run `npm run docs`
3. Check https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/date-range-filter-picker/index.js#L178

**Expected behavior**
The description should be changed to "Foo"
```
`onRangeSelect` | Function | `null` | Foo
```

**Additional context**
It seems that `generate-docs` has a check for that specifically https://github.com/woocommerce/woocommerce-admin/blob/main/bin/generate-docs/index.js#L102:L102
So it does not update the docs on purpose, but why?

Removing this particular check resulted in an even worse result with old docs concatenated with malformed new ones.

How can I update generate updated docs?

(I hope the answer is not: "Do it manually here and there". Except for the redundant, manual labor, it is so bug-prone, and a short way to get the docs out of sync & date.)

**Comment by samueljseay** [comment]
Just my 2 cents, I wasn't aware we were relying on this code and its likely to need some attention.

We're moving to TS for our components so prop types + react-docgen won't work for us going forward anyway. I see there is a TS library: https://github.com/styleguidist/react-docgen-typescript that could be a way forward.

It seems fair to say that component docs are completely broken in this state and we'll need any task to fix this to start by addressing how we want to do this going forward. I'd also be open to new solutions that are better than react-docgen, for example we have a storybook, which also needs some work, we could consolidate all component documentation to that instead.

I've probably made some naive assumptions here so keen to hear other feedback.

**Comment by tomalec** [comment]
> It seems fair to say that component docs are completely broken in this state and we'll need any task to fix this to start by addressing how we want to do this going forward. I'd also be open to new solutions that are better than react-docgen, for example we have a storybook, which also needs some work, we could consolidate all component documentation to that instead.

If I can put my opinion here, I'd say: 
1. Generate docs from code. To reduce the friction for devs to switch environment and cotext when writing features and documenting them.
2. Minimize the dependencies and the tool stack. If we can use the Storybook alone for all the docs, rather than the Storybook for one part, _{any-library}_ for another, I'd go for Storybook alone.

Less friction to write docs => happier devs & better docs => happier devs *2 ;)

**Comment by samueljseay** [comment]
> If I can put my opinion here

Your opinion is most welcome!

> Generate docs from code. To reduce the friction for devs to switch environment and cotext when writing features and documenting them.

Yes I agree, especially for any documenting of prop changes etc this needs to come from the code rather than being maintained manually. I believe there are ways we can automate this even for new components so we should explore that as part of this.

> Minimize the dependencies and the tool stack. If we can use the Storybook alone for all the docs, rather than the Storybook for one part, {any-library} for another, I'd go for Storybook alone.

I'm glad we agree there, I'd like to trim it down to one approach and Storybook makes sense
