### ISSUE TITLE
DateRangeFilterPicker's onRangeSelect is not documented

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6099]
**Describe the bug**
I was trying to use `DateRangeFilterPicker`'s `onRangeSelect` prop, but its arguments are not documented. I ended up digging the code, to figure out how to use it.

**To Reproduce**

1. Go to https://woocommerce.github.io/woocommerce-admin/#/components/packages/date-range-filter-picker/README?id=props
2. Check `onRangeSelect` arguments documentation.

**Expected behavior**
Function and its arguments should be documented.

**Screenshots**
![screenshot of the lack of docs](https://user-images.githubusercontent.com/17435/105081112-1214a500-5a92-11eb-91b1-509526d396b3.png)

**Additional context**
I tried to add it by myself but wasn't able to generate that https://github.com/woocommerce/woocommerce-admin/issues/6098.

**Comment by chihsuan** [comment]
I'm closing this since this is low impact feature. (see p90Yrv-2Bc-p2)
