### ISSUE TITLE
Plugin recommendations (e.g. Jetpack) appear for users who cannot install plugins

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce-admin#6124]
**Describe the bug**
Plugin recommendations appear for users who cannot install plugins in WooCommerce > Home (e.g. Jetpack). There is a prompt which appears in the home "Stats overview":

"Get traffic stats with Jetpack Keep an eye on your views and visitors metrics with Jetpack. Requires Jetpack plugin and a WordPress.com account."

This has a button which when clicked starts loading, I assume this is attempting to install the Jetpack plugin, if logged in as a shop manager this button does not work and displays an "undefined" error - which I think maybe because shop managers do not have permission to install plugins and therefore I would request this or other similar messages shouldn't show to users who do not have the required permissions.

**To Reproduce**

1. Login as a shop manager role user
2. Goto WooCommerce > Home
3. View Jetpack section in "Stats overview"
4. Click "Get Jetpack"

**Expected behavior**
Prompts to install plugins should only be shown to users who can install plugins.

**Screenshots**

![image](https://user-images.githubusercontent.com/56840277/105368861-dbf23500-5bf9-11eb-8ed9-c317d7f3310b.png)

**Comment by hsingyuc** [comment]
I'll give this a shot today.

**Comment by joshuatf** [comment]
Looks to have a PR already, but...

Estimate: 2

**Comment by timmyc** [comment]
Assigned @hsingyuc since a PR is in place, thank you!!!
