### ISSUE TITLE
Home Screen: Welcome Modal has Horizontal Scroll Bar

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6125]
**Describe the bug**
Reported by @roykho in slack - when one hovers their cursor over the [x] to close the welcome modal, a horizontal scroll bar appears at the bottom of the dialog:

![image](https://user-images.githubusercontent.com/22080/105375247-69fbfa80-5bbd-11eb-977e-3601f09fec7c.png)

This appears to be present in 1.8.x as well per @tammullen's comment in slack, so this doesn't seem to be a regression, but logging it as an issue for us to follow-up on. No details given on browser.

**Comment by timmyc** [comment]
Noting that I was not able to see this when using MS Edge ( Version 87.0.664.75 )

**Comment by hsingyuc** [comment]
I was not able to see this when using Chrome, Safari but on Firefox. I will try to fix it today.

**Comment by hsingyuc** [comment]
It looks like an issue on GB, here's the issue https://github.com/WordPress/gutenberg/issues/28311
Maybe we can hide it until it's fixed upstream.
