### ISSUE TITLE
Payments Task: Styling Regression in 1.9

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6126]
**Describe the bug**
Originally reported by @tammullen in slack:

![image](https://user-images.githubusercontent.com/22080/105375746-d4ad3600-5bbd-11eb-9e80-03646f8d6a63.png)

When viewing the payments task using the latest RC of 1.9, there appears to be a css regression.

**Comment by louwie17** [comment]
This seems to be related to the woocommerce components seperation, and replacing some components with the Wordpress/components.
Let me get a fix.
