### ISSUE TITLE
Fly-out menu items registration in WP menu

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6129]
As a part of the new navigation updates, we're adding top-level core menu items back to the flyout menu as well as favorited extensions.

This issues will involve grabbing the top-level core items and registering those items in the WP admin menu under "WooCommerce" or if it's a category, linking to the category's first menu item.

<img width="265" alt="screen-shot-2021-01-20-at-7 14 06-pm" src="https://user-images.githubusercontent.com/10561050/105386330-44cdb300-5be2-11eb-85ba-4611dfd69c38.png">

## Deliverables 

* Marketplace is added to flyout
* Favorited extensions are added to the flyout

**Comment by joshuatf** [comment]
Estimate: 2

**Comment by psealock** [comment]
Another thing to consider is the flyout menu in Calypso (ie, eComm and Business plan). This may require coding in Calypso and given that favorited extensions also appear in the flyout, an API request may be in order.

Estimate 5, unless we break out the extra Calypso bit to a separate issue.

**Comment by psealock** [comment]
@joshuatf I added a few deliverables in the original comment based on updates in pbIJXs-Ak-p2

**Comment by joshuatf** [comment]
I think separating the calypso flyout to its own issue is a good call.

>given that favorited extensions also appear in the flyout, an API request may be in order.

Building a REST API for nav items is a good idea.  This definitely will require a bit more exploration.
