### ISSUE TITLE
Navigation favorites registration API

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6131]
In order to allow items to be favorited, we'll need an API in the navigation to create, read, and update favorites.

<img width="616" alt="screen-shot-2021-01-18-at-2 24 23-pm" src="https://user-images.githubusercontent.com/10561050/105389534-f15d6400-5be5-11eb-81f3-070fc21e3e11.png">

This issue will involve creating those methods and an option to store the information in.

```php
Favorites::add_plugin($plugin );
Favorites::remove_plugin($plugin );
Favorites::get_all();
```

Note that using the plugin slug (or text-domain) here is probably better than using the menu item ID because this will allow plugins to easily change what item should be favorited when their plugin has been starred.

## Notes

* Extensions currently registered in Settings can’t be favorited

**Comment by joshuatf** [comment]
Estimate: 2

**Comment by psealock** [comment]
What if we did `Favorites::add_item($item );` instead? See p90Yrv-25S#comment-4858 for discussion

**Comment by joshuatf** [comment]
I think this is much simpler logic and prefer it if we go the direction of favoriting single items. With the current designs, favoriting is at the extension level, which adds confusion.

We'll hash out the design direction via p2 first.

**Comment by psealock** [comment]
@joelclimbsthings I added a note in the original comment based on updates in pbIJXs-Ak-p2
