### ISSUE TITLE
Navigation extensions link registration API

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6132]
As part of the new navigation extensions page, extensions should be able to add custom links to their extension item on the extensions page.

There is currently a WordPress API in place for doing this via the `plugin_action_links_{$plugin_file}` filter, however this may be somewhat limited given the need for a "More" menu and the fact that this won't work with modern routing (i.e. React Routing in the case of WCA).

<img width="1024" alt="screen-shot-2021-01-18-at-2 25 58-pm" src="https://user-images.githubusercontent.com/10561050/105390307-e525d680-5be6-11eb-81d2-966ad89a3d31.png">

I think we could probably use SlotFill to solve this issue and provide all the benefits of modern routing as well.

We should also make sure we have determined if we're using some kind of plugin slug or text-domain to identify plugins.

**Comment by joelclimbsthings** [comment]
Closing this for now due to the uncertainty around the navigation project, and the upcoming merge.
