### ISSUE TITLE
WooCommerce extensions REST endpoint

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6134]
Blocked by https://github.com/woocommerce/woocommerce-admin/issues/6130

To access the WooCommerce extensions that will be used on the extensions page, we'll need a REST endpoint to get all installed extensions.  We can do this with our existing `plugins` endpoint if we add a parameter to filter WooCommerce extensions.

I think it's also worth adding a couple parameters here to filter the retrieved extensions.

Method: `GET`
Endpoint: `wc-admin/plugins`
Params: `is_woocommerce|is_activated|query`

**Comment by joshuatf** [comment]
Estimate: 2

**Comment by joelclimbsthings** [comment]
Closing this prior to the merge, as the blocking issue has long since been closed.
