### ISSUE TITLE
Deactivate extension link

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6135]
The extensions page will include a link to deactivate an extension.  While I think this would be a really interesting idea to create a REST endpoint to deactivate plugins as I mentioned in p2-p90Yrv-25S this may cause too many issues without a page refresh since the plugin's server-side loaded files and assets would still be present until next page refresh.

<img width="355" alt="Screen Shot 2021-01-21 at 1 14 01 PM" src="https://user-images.githubusercontent.com/10561050/105394290-641d0e00-5beb-11eb-9320-4b2c282ee4cd.png">

The best short-term solution may be to just add the core deactivation link that causes a page refresh and try to redirect to catch the deactivation and redirect back to the WooCommerce extensions page after successful deactivation.

* Deactivation link.
* Redirect after successful deactivation.
* Notice for successful deactivation.

**Comment by joshuatf** [comment]
Estimate: 3 (assuming we use the traditional deactivation link) or 5 if we attempt the async deactivation.

**Comment by joelclimbsthings** [comment]
Closing prior to the merge as it's been on hold for over a year, and there's currently uncertainty around this project.
