### ISSUE TITLE
Extensions client page route and menu item

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6137]
The new navigation feature will include an extensions client page.

This issue will involve:

* Creating a new route in WooCommerce Admin for the extensions page to live.
* Showing an `All extensions` menu item under the new navigation.

![all-extensions-2](https://user-images.githubusercontent.com/10561050/105397023-8c5a3c00-5bee-11eb-8932-263e2dabae5d.png)

**Comment by joelclimbsthings** [comment]
Closing prior to the merge as it's been on hold for over a year, and there's uncertainty around this project.
