### ISSUE TITLE
Spike: Explore config-based Setup Checklist Payment Promotions

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6141]
We frequently have requests to add in new payment extensions to the Setup Checklist from the partnerships team, and while many times these tasks are pretty trivial to do in code, the timeline to implement and ship these changes in Woo Core result in challenges with partnership agreements.

Furthermore, it also _feels like_ this is an area of our code base that could potentially be DRY'ed up a bit, or abstracted out in such a way to make our lives easier to implement additions, and also to speed up the process of deploying these changes to new Woo stores.

@beaulebens also highlighted the possibility of improvements in this space in the following post: pbIJXs-wS-p2

[Here is an example](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/tasks/payments/methods.js#L242-L263) of our current front-end config that renders the payments list.

## Spike Goals

The goal of this spike/task is to spend some time to evaluate how we could make the payments task screen powered ( fully or partially ) by a REST endpoint, or configuration file, that is hosted on woocommerce.com.

<img width="1502" alt="payments-task" src="https://user-images.githubusercontent.com/22080/105404180-86f4f580-5bde-11eb-9e2d-11c84233d5b8.png">

### Things to Consider

- A possible solution will likely need to make it feasible for a hybrid approach to render the payments task. That could possibly look like augmenting the existing logic to pull in a remote list of other payment options, and rendering them alongside the existing "native" payment task options.
- Minimum Viable Loveable Features for this would be to have an endpoint that when POST'ed to with store details ( locale / country specifically for payments ) would return a list of payment options. These options would then render to the payments task, and the minimum action that would happen on each would be installation of the payment extension.
- The logic should be able to handle scenarios where the remote endpoint would return a suggested payment method, and the same payment method already exists in the wc-admin codebase. If this happens, the "native" integration in wc-admin should take priority.
- The WordPress.org plugin repository guidelines state that we can not load external assets - so we will also need to consider how to work with this guideline. Can we have the users "agree" to load in external resources/assets ( mainly this would be the extension logo ). Perhaps we could leverage the assets hosted in the WordPress.org plugin directory itself?
- Awesome to have: It would be interesting if the remote config/REST endpoint could possibly also return an array of settings objects that the payment method requires to be set. For example the RazorPay integration prompts for two strings to setup the extension, how fancy would it be if the remote config could fully build out the UI in the task list with all the needed settings. Yeah I think that would be cool too.

### Deliverables

- Completion of this spike should yield any assets detailing possible path(s) to implement a feature such as this.
- If inclined, and time permits, `try` branches displaying possibly implementations would be nice, but at the very least, a detailed p2 post with the exploration and findings would be ideal.
- Additionally, creation of issues needed to implement the feature would be great and help set us up to quickly act upon this feature in a future sprint cycle.

**Comment by joshuatf** [comment]
>Perhaps we could leverage the assets hosted in the WordPress.org plugin directory itself?

This is a pretty good idea that may work.

Estimate: 8

**Comment by louwie17** [comment]
After doing some work with the Paypal integration changes, I realized this might also require some Woo Core changes, given most/all payment gateways extend from the [WC_Payment_Gateway](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-payment-gateway.php) abstract class.
Which has several helper methods, like `needs_setup` or `init_settings`. Although I think the `needs_setup` focuses on if a plugin in general requires setup.

I think adding more helpful abstract classes to this would be very beneficial, like `is_setup( environment )`, or `update_settings(formdata) // form data comes from fields derived from a config`, etc...

Here is an example of where we get all the [payment gateway classes](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks.php#L91).

**Comment by thenbrent** [comment]
> Perhaps we could leverage the assets hosted in the WordPress.org plugin directory itself?

If we can load them from `https://plugins.svn.wordpress.org/woocommerce/assets/` or `https://plugins.svn.wordpress.org/woocommerce-admin/assets/`, that seems like a great approach.

**Comment by beaulebens** [comment]
Didn't we already try this with some images previously, and were asked not to do it again? @timmyc ?

**Comment by timmyc** [comment]
The side-loading route we took was to host the images on WPCOM servers, and then download the image to the local media library for use in the home page setup task. This was not considered okay per the wp.org review team.

Treating the wp.org repo as a CDN I think is frowned upon too, I also think that MailPoet was/is doing something similar and that was flagged as something we should stop doing in that plugin.

**Comment by joshuatf** [comment]
Relevant to this issue, we've also just used WP.org hosted images in https://github.com/woocommerce/woocommerce-admin/pull/6367.

Would be great if we had some kind of SoP for handling larger images and/or videos that hopefully doesn't destroy our bundle size.

**Comment by pmcpinto** [comment]
We're investing heavily in the bundle approach on the store profiler to drive WCPayments adoption: https://d.pr/i/OfaYE5

I think it would be good to assess the amount of effort required to use a REST endpoint or config file to power this part of the flow. This is particularly important as we gradually introduce WCPayments in new countries, so ideally we should be able to include WCPayments in the bundle without relying on a core release. In the bundle we don't need to deal with images

**Comment by thenbrent** [comment]
Summary of initial spike on this available here: pc2DNy-g3-p2

**Comment by timmyc** [comment]
@joshuatf just wanted to see if you had any thoughts on this issue? Since we didn't get too far along here in this cycle with this issue, and looking ahead to the next cycle I was thinking this one might land in Ghidorah's sprint as its looking like we will have Gezora working on some features in WC Pay.

So just wanted to kind of get a sense of where things are at here. Also forgot to link to a related post: p6q8Tx-24n-p2

**Comment by joshuatf** [comment]
@timmyc Here's a try branch using the remote inbox notification rules to process payment visibility and configuration - https://github.com/woocommerce/woocommerce-admin/pull/6830

And here's a post on the remaining technical challenges - p90Yrv-2g1-p2

I think getting some discussion there around the remaining issues and solutions would be good to help scope things out a bit before moving forward.  There are some decisions to be made about where "non-conforming" logic should live.

**Comment by psealock** [comment]
We can close this issue because the discovery phase of the project is completed and we have an Epic going with sub tasks https://github.com/woocommerce/woocommerce-admin/issues/6856
