### ISSUE TITLE
Search meta link is misaligned when the new nav is enabled

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#6148]
**Describe the bug**

Search meta links (screenshot below) have 26px+ empty space when the new nav is enabled.

**To Reproduce**

1. Make sure `woocommerce_marketplace_suggestions` in the `wp_options` is not set to see the search meta links.
2. Enable the new nav from Settings -> Advanced -> Features
3. Navigate to WooCommerce -> Orders and make sure you have the search meta links.
4. Open the inspector and change the view to a small mobile device (Pixel 2 is a good one)

**Screenshots**

![Screen Shot 2021-01-21 at 3 26 11 PM](https://user-images.githubusercontent.com/4723145/105426804-af8de700-5c00-11eb-9362-03681e0e8cfe.jpg)
![Screen Shot 2021-01-21 at 3 26 06 PM](https://user-images.githubusercontent.com/4723145/105426808-b0bf1400-5c00-11eb-8209-decae6045dee.jpg)

**Comment by joshuatf** [comment]
Estimate: 1.

Side note: It will be interesting to come up with a better way to determine nav height app-wide as I'm seeing a lot of issues stemming from unknown/variable nav heights.

**Comment by joshuatf** [comment]
The header refactor seems to have resolved this so going to close this issue.
