### ISSUE TITLE
Navigation: Add Sticky Footer

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6150]
Settings, Maketplace, and Tools will now be in a "sticky" footer that remains as the user scrolls

<img width="781" alt="Screen Shot 2021-01-22 at 1 23 48 PM" src="https://user-images.githubusercontent.com/1922453/105428816-18369b80-5cb5-11eb-89ea-b220f094d946.png">

### Deliverables

* The Settings group (with Settings, Marketplace, and Tools links) is fixed to the bottom of the viewport
* A 1px border divides this section from the main navigation
* Check that mobile works too
* Marketplace is the first item (image above is outdated)
* This section remains fixed on scroll

**Comment by pmcpinto** [comment]
Here's the updated image
![Uploading nav-layout-2.png…]()

**Comment by joshuatf** [comment]
Estimate: 2

I anticipate some height issues from doing this.
