### ISSUE TITLE
siteUrl button link - should it be homeUrl?

### ISSUE THREAD

**Issue by tivnet** [woocommerce/woocommerce-admin#6161]
https://github.com/woocommerce/woocommerce-admin/blob/d830378e8ca783449c739ab5b770fa819542ade4/client/navigation/components/header/index.js#L112

When WP is in a folder (composer/"skeleton" installation), the link points to 404.

**Comment by joshuatf** [comment]
It does seem like we're incorrectly using `siteUrl` when `homeUrl` would be a better fit for this link in non-traditional WordPress installs.

We should double check the usage of `siteUrl` as it's also being used in Store Management Links as well.

**Comment by hsingyuc** [comment]
I can fix it 🔨
