### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#6163]
Currently our release process is roughly:

1. Cut an initial RC
2. test
3. bugs are found, PRs are created and marked for cherry picking
4. we cherry pick those commits into a new RC
5. repeat steps until we have a stable ready thing
6. cut a final
7. one final is cut release to wp.org

Its very manual and slow right now consuming a lot of developer time to do this process. The goal of this task would be to automate *as much as possible* of the process.

Some things I'd like to achieve:

1. The release would not actually run on the dev's PC, it should run on a github action. completion or errors can be reported to a slack channel.
2. version bumping would be automated
3. changelog entry management would be automated

It turns out that https://github.com/woocommerce/woorelease does a lot of these things already so I'd like to build on top of that rather than start from scratch.

Here's my thought on how it could operate

1. When ready to make an RC, pull down latest main, run a new script like npm run release-rc --new. It does a version bump, checks out a new branch matching a pattern like release/<version number>-rc<rc number> or similar, and it pushes this new branch to Github.

2. Once the new branch is pushed to the rc branch, a github action kicks off that performs the release tasks that we do normally ourselves right now (build it, tag it, etc)
Once its done, it announces in a slack channel that a new RC was cut and that has a link to the zip generated by github

3. When you're ready to create the next RC run the script again but this time don't pass the `--new` flag. It will present you with existing recent RCs to cut the new one from.

4. Once you'ce chosen the RC to branch from, it will ask you to choose commits to cherry pick from `main` that don't exist in the RC currently. I'm thinking we could add some smarts for this (such as finding commits that have a label like cherry pick or something).

5. Once you're done, it will push the new RC branch up to github and do the release process as specified in step 2.

6. Once you're done cutting RC's its time to create a final. a separate script for this would be run, e.g. `npm run release-final`. This script would do many of the same steps as the other scripts, asking you which RC to cut the final from etc. It would then perform a final release on a github action. It would / could also do steps like releasing to wp.org but we could also leave those steps for now as manual.

### Extra credit

Some other things we'd like to tackle if there is time (or do in a next phase):

1. When producing the slack notification for the completed release, it'd be awesome if we could spin up a JN site somehow that has the plugin installed, allowing for devs to do some quick testing.

2. It'd be great to add an additional lint to our PRs that checks that the changelog entry was correctly added on the PR. This would ensure easy automation of changelog.

**Comment by joelclimbsthings** [comment]
I believe this will be obsolete as we merge with the core repo, so, as much as it saddens me, I'll close this one for now.
