### ISSUE TITLE
[Navigation] Regression: Settings missing

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6180]
Navigating from WooCommerce Home to Settings has some screens missing. 

<img width="237" alt="Screen Shot 2021-01-26 at 5 23 43 PM" src="https://user-images.githubusercontent.com/1922453/105800303-4e4c8600-5ffb-11eb-9d1d-58a32f44f0d0.png">

I can reproduce this locally and with WC 5.0.0-rc.1, but luckily this does not affect wc-admin 1.9.0-rc.3 release which does show items. Something changed between the release and now.

<img width="238" alt="Screen Shot 2021-01-26 at 5 20 57 PM" src="https://user-images.githubusercontent.com/1922453/105800442-92d82180-5ffb-11eb-8bb9-23a88c00ed44.png">

## To Reproduce

* Use `main` branch of wc-admin and WC 5.0.0
* Go to Settings and see the lack of items
* Check again, if you'd like, with branch `release/1.9.0-rc.3` and confirm the items are present.

**Comment by joshuatf** [comment]
Estimate: 2

I think this is related to https://github.com/woocommerce/woocommerce-admin/pull/6116.  If you're on a Settings page, all items show.  If not, then only some items show.

I vaguely recall this being why we didn't use the `woocommerce_settings_tabs_array` filter the first time.  Maybe we'll need a combination of both the `woocommerce_settings_tabs_array` filter and `WC_Admin_Settings::get_settings_pages();` and merging arrays with unique items to take advantage of plugins registering in either place.

**Comment by timmyc** [comment]
Thanks for the estimate @joshuatf - since this is breaking things on `main` thinking we need to have this issue at the top of the priority list for nav for first thing next week in order to get a fix in the 2.0 release. cc @psealock
