### ISSUE TITLE
Woocommerce Analytics not displaying recent/updated data

### ISSUE THREAD

**Issue by bb-teri-ba** [woocommerce/woocommerce-admin#6184]
**Describe the bug**
Orders have been processed and have been completed within the last few months. They have been tracked on the Woocommerce report section but data is not tracked or displaying in the Analytics section.

**To Reproduce**
1. I went to Woocommerce >> Orders I will be able to see all the orders their status within the last quarter for example. 
2. If I check Woocommerce >> Reports, I am able to see the revenue, gross sales etc within the last quarter.
3. When I go to the Analytics section, Analytics >> Overview I am unable to see any data from the last quarter, I am seeing incorrect data, it's displaying 0.
4. I tried Analytics >> Settings >> Import Historical Data but the site was unable to start this action
5. I cleared the scheduled actions sections and still nothing.

**Expected behavior**
When I go to Analytics I expect to see the same data I see in the Woocommerce >> Reports section, of all the orders and revenue generated within the last week, month quarter etc. However I am seeing data from the previous year.

**Desktop (please complete the following information):**

* OS: iOS
* Browser: Chrome

**Comment by joshuatf** [comment]
Hi @bb-teri-ba 👋  Sorry to hear that you're having trouble with your reports.

>I tried Analytics >> Settings >> Import Historical Data but the site was unable to start this action

This sounds like it may be the issue; I wonder if something is blocking your data from being imported.  When you say unable to start, did the button not work?  Are there any console errors you can share?

**Comment by bb-teri-ba** [comment]
Hello @joshuatf, thank you for responding. 

When I click 'start' nothing is being imported, the progress bar isn't moving to indicate that data is being imported, it doesn't matter what the settings are whether it be last 24 hours, last 7 days etc the the progress bar is unchanged. There are no visible console errors.

![Screenshot 2021-01-28 at 11 47 42](https://user-images.githubusercontent.com/68847629/106134587-a2bc4680-615e-11eb-813c-5d7b77c69f01.png)

**Comment by bb-teri-ba** [comment]
@joshuatf For better understanding I will display the console and XHR requests. The **status?_locale=user** request has been repeated several times but the response hasn’t changed or isn't updating. 

![Screenshot 2021-01-28 at 12 03 20](https://user-images.githubusercontent.com/68847629/106136779-ab624c00-6161-11eb-8974-af89a83edd3f.png)
![Screenshot 2021-01-28 at 12 01 39](https://user-images.githubusercontent.com/68847629/106136785-ac937900-6161-11eb-97e1-1d7375611c0f.png)

**Comment by joshuatf** [comment]
Thanks for that info @bb-teri-ba!  That narrows down the issue a bit.  Can you try the following:

1. Navigate to Tools -> Scheduled actions.
2. Search for any actions starting with `wc-admin_import_`.
3. Post here any completed/pending/failed actions that show up there.  If there are many of them, please let me know (no need to post all of them).

Also, which version of WooCommerce and/or WooCommerce Admin are you currently running?  Posting your system status report ( `wp-admin/admin.php?page=wc-status` ) here will show us that and any other potential plugin conflicts.

**Comment by bb-teri-ba** [comment]
Thanks for your response. 
The WooCommerce version is 4.9.2 and the WooCommerce Admin package version is 1.9.0.

![Screenshot 2021-02-02 at 10 10 47](https://user-images.githubusercontent.com/68847629/106585145-edfb9e00-653e-11eb-82d0-bedfc5104ffe.png)

There are a lot more canceled/failed actions as they hadn't updated for a long period of time, the competed ones I don't believe were imported correctly as the data is still unchanged and showing incorrect figures and graphs. The following are the pending actions. 

![Screenshot 2021-02-02 at 10 28 20](https://user-images.githubusercontent.com/68847629/106587335-619eaa80-6541-11eb-8ad5-eedbdd9f5124.png)

**Comment by bb-teri-ba** [comment]
@joshuatf Here is the system status report for full context. 

![Screenshot 2021-02-02 at 10 30 06](https://user-images.githubusercontent.com/68847629/106588475-bb53a480-6542-11eb-85f1-8bbee7034790.png)

Regards.

**Comment by quebec87** [comment]
Hi @bb-teri-ba did you resolve this issue? If so, can you let me know to do that? thanks.

I'm having the same issue that woocommerce analytics didn't get order data(it shows 0). 
And there are thousands scheduled actions due to the historical data import is not working:
![scheduled-actions](https://user-images.githubusercontent.com/10112394/118216059-5e527d80-b4a5-11eb-972f-06edbb761681.jpg)

attached woocommerce status
![woo-status](https://user-images.githubusercontent.com/10112394/118216498-31529a80-b4a6-11eb-8b6b-5b36c976ddde.jpg)
![woo-status2](https://user-images.githubusercontent.com/10112394/118216502-33b4f480-b4a6-11eb-9615-85571667a05a.jpg)
P.S. the wp-cron is disabled because we are using server-side cron jobs.
