### ISSUE TITLE
Country without locale info fails during setup wizard

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6187]
**Describe the bug**
When going through the setup wizard, a country not included in WC's default locale info results in an error when trying to proceed and breaks the OBW flow.

**To Reproduce**

1. Go to the setup wizard. `wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=store-details`
2. Select a country not included in `woocommerce/i18n/locale-info.php` (e.g., `Åland Islands`)
3. Click `Continue`.
4. Note the console error.

**Expected behavior**
Expected to be able to continue, even if currency/locale info is not found.

**Screenshots**
<img width="705" alt="Screen Shot 2021-01-26 at 3 55 48 PM" src="https://user-images.githubusercontent.com/10561050/105904331-0162b280-5fef-11eb-9e19-5021a12c67d4.png">

**Comment by hsingyuc** [comment]
I'll try this one

**Comment by tammullen** [comment]
Noting @gglobalstep reported this originally here https://github.com/woocommerce/woocommerce-admin/issues/6155

**Comment by joshuatf** [comment]
Will close this issue in favor of https://github.com/woocommerce/woocommerce-admin/issues/6155.  @hsingyuc I updated your PR to `Fixes #6155`.
