### ISSUE TITLE
PHP Warnings with PHP 8.0.1

### ISSUE THREAD

**Issue by damiannep** [woocommerce/woocommerce-admin#6195]
**Describe the bug**
After updating PHP to 8.0.1, anything that uses REST API does not function

**Error Message**
```
[27-Jan-2021 08:05:14 UTC] PHP Warning:  Trying to access array offset on value of type bool in /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/PerformanceIndicators/Controller.php on line 149

Stack trace:
#0 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/PerformanceIndicators/Controller.php(269): Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller->get_analytics_report_data()

#1 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/PerformanceIndicators/Controller.php(649): Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller->get_indicator_data()

#2 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/PerformanceIndicators/Controller.php(96): Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller->get_collection_params()

#3 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Init.php(107): Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller->register_routes()
#4 /wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Admin\API\Init->rest_api_init()
#5 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#6 /wp-includes/plugin.php(484): WP_Hook->do_action()
#7 /wp-includes/rest-api.php(521): do_action()
#8 /wp-includes/rest-api.php(347): rest_get_server()
#9 /wp-includes/class-wp-hook.php(287): rest_api_loaded()
#10 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#11 /wp-includes/plugin.php(551): WP_Hook->do_action()
#12 /wp-includes/class-wp.php(388): do_action_ref_array()
#13 /wp-includes/class-wp.php(745): WP->parse_request()
#14 /wp-includes/functions.php(1291): WP->main()
#15 /wp-blog-header.php(16): wp()
#16 /index.php(17): require('...')
#17 {main}
  thrown in /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/PerformanceIndicators/Controller.php on line 149
```

**Expected behavior**
I expect compatibility with PHP 8.0.1. Rolling back to PHP 7.4 resolves the issue.

**Additional context**
Reported in 27299738-hc

**Comment by joshuatf** [comment]
Thanks for opening the issue @damiannep - we definitely want to resolve any issues with PHP 8 asap if they exist.

I was not able to reproduce the issue on PHP 8.0.0.  Looking at the code, it appears to be stemming from a report endpoint not being retrieved:

https://github.com/woocommerce/woocommerce-admin/blob/c1b5bab937fef12ccb092c1d73ef8b46f6c42ef1/src/API/Reports/PerformanceIndicators/Controller.php#L149

Are there any other plugins on this site that may be extending reports?  If so, does disabling them have any effect?  Do the other reports all load correctly outside of performance indicators?

**Comment by damiannep** [comment]
Hi @joshuatf Thanks for checking. I did wonder if it could be a conflict but didn't get a chance to do any testing on a local site.

These are the extensions on the site with the issue:

Query Monitor: by John Blackbourn – 3.6.7
WP Missed Schedule (The Original): by sLaNGjIs Team – 2014.1231.2017.12
CrEngine: by Creative Novels + Web Dev Unit – 1.0.0
ACF to REST API: by Aires Gonçalves – 3.3.2
Ad Inserter: by Igor Funa – 2.6.20
Advanced Cron Manager: by BracketSpace – 2.4.0
Advanced Custom Fields PRO: by Elliot Condon – 5.9.4
Akismet Anti-Spam: by Automattic – 4.1.8
Cloudflare: by Cloudflare
Inc. – 3.8.9
Control Panel: by Creative Novels + Web Dev Unit – 1.0.0
Custom Post Type UI: by WebDevStudios – 1.8.2
GAinWP Google Analytics Integration for WordPress: by IntelligenceWP – 5.4.6
JWT Auth: by Useful Team – 1.4.2
Social Login: by OneAll Social Login – 5.7
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
User Menus: by Code Atlantic – 1.2.5
User Role Editor: by Vladimir Garagulya – 4.58.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.7.0
WooCommerce Memberships: by SkyVerge – 1.21.2
WooCommerce Subscriptions: by WooCommerce – 3.0.12
WooCommerce: by Automattic – 4.9.2
WP Content Filter: by David Gwyer – 3.0.1
WP Rocket: by WP Media – 3.8.3

I've sent a message to the user in 3691346-zen to respond directly here or by email.

**Comment by joshuatf** [comment]
Thanks, @damiannep!  Since I'm unable to recreate the issue, I think a good first step would be to disable all of those plugins with the exception of `WooCommerce` to see if this resolves the issue.

If that doesn't do the trick then we can continue digging into this to try and determine what's happening.

**Comment by damiannep** [comment]
No reply from the merchant so I'm going to go ahead and close this issue @joshuatf. We can reopen if needed.
