### ISSUE TITLE
The activity panel is not centered

### ISSUE THREAD

**Issue by hsingyuc** [woocommerce/woocommerce-admin#6199]
**Describe the bug**
The activity panel doesn't render after click the 'w' button(View Activity Panel) on home page

**To Reproduce**
1. Make screen responsive style
2. Go to WooCommerce home page
3. Click on 'w' button

**Expected behavior**
To see the activity panel like `Order` page

**Screenshots**
<img width="537" alt="before click" src="https://user-images.githubusercontent.com/56378160/106052714-e7d96d80-60b7-11eb-954f-ac0ed2d1092f.png">

<img width="539" alt="after click" src="https://user-images.githubusercontent.com/56378160/106052729-eb6cf480-60b7-11eb-8560-d89c790e650e.png">

**Desktop (please complete the following information):**
* OS: 10.13.6
* Browser chrome

**Comment by octaedro** [comment]
Hi @hsingyuc,
Thank you for reporting this bug. 
I was able to reproduce it. Definitely it seems like a CSS problem.

**Comment by hsingyuc** [comment]
fixed by https://github.com/woocommerce/woocommerce-admin/pull/6289
