### ISSUE TITLE
WordPress.com eCommerce plan doesn't install any WooCommerce pages after setup

### ISSUE THREAD

**Issue by kdevnel** [woocommerce/woocommerce-admin#6212]
**Describe the bug**
When you setup a new eCommerce plan with WordPress.com the setup flow doesn't lead to any WooCommerce store pages being setup.

**To Reproduce**

1. Create a new eCommerce plan site
2. Follow the WordPress.com signup flow and then complete the WooCommerce setup wizard
3. After completing the setup wizard there will be no WooCommerce pages installed

**Expected behavior**
I would expect the same behaviour as any other WooCommerce site - that there is the Cart, Checkout, My Account and Shop pages created on initial setup.

Referencing p1611648718078000-slack-C9K5T0XSP

cc: @timmyc @psealock

**Comment by psealock** [comment]
Thanks @kdevnel, we can use this issue in wc-calypso-bridge to track the issue https://github.com/Automattic/wc-calypso-bridge/issues/637, so I will close this out in favor of that one.
