### ISSUE TITLE
Favoriting extensions from the new navigation

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6213]
**User story:**
As a merchant
I want to favorite key extensions
So I can easily access them when I'm using WooCommerce

**Description:** we're going to move forward with just one favoriting method - from the extension title in the new nav.

![home.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/81a403fa-3152-482e-801d-6f12d73cdfc1)

![favoriting-in-the-nav.gif](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/40854f6e-e239-4fe1-a2a8-13ad3cef549c)

**Acceptance criteria:**
- [x] Upon clicking into the extension menu, a star icon is visible at the top to the right of the extension title, allowing users to favorite that specific extension https://github.com/woocommerce/woocommerce-admin/pull/6287
- [x] Selecting the star icon will change it from outlined to filled, and the extension item will appear in the top level of the nav https://github.com/woocommerce/woocommerce-admin/pull/6290
- [x] The favorited extension appears in the flyout menu from the wp-admin dashboard https://github.com/woocommerce/woocommerce-admin/pull/6290
- [ ] Display a tooltip about the new feature, when the user visits an extension menu for the first time 
- [x] When clicking in a favorited extension through the flyout menu, the user is redirected to the ~~page that 3PDs have identified the top-level page~~ first item under that extension's category https://github.com/woocommerce/woocommerce-admin/pull/6290
- [x] The favorite extensions should be stored as a user preference and not site-wide for all store managers https://github.com/woocommerce/woocommerce-admin/pull/6270
- [ ] Users can favorite a specific page (nice to have - requires more exploration)

**Event tracking:**
Event name: `wcadmin_navigation_favorite`
Event prop: `extension_name`
Event prop: `action` - favorite | unfavorite
Event description: triggered when the a user clicks to favorite or unfavorite an extension

**Comment by pmcpinto** [comment]
@elizaan36 pls check if I'm not missing anything

**Comment by joshuatf** [comment]
@elizaan36 @pmcpinto Does this mean:

1. We're really favoriting categories/menu items?  An extension could have multiple top-level categories if it chooses.
2. If the extension does not have a category, but a single top-level menu item, can it be favorited from the root of the menu?  How would this icon appear?

**Comment by elizaan36** [comment]
> We're really favoriting categories/menu items? An extension could have multiple top-level categories if it chooses.

In the thread on `pbIJXs-Ak` @psealock mentioned that this needs more exploration, but extension authors have identified a top level page that always loads first when the nav item is selected. For example `Dashboard` for AutomateWoo. I wonder if we can use that as an indication of what page should be favorited and load first?

> If the extension does not have a category, but a single top-level menu item, can it be favorited from the root of the menu? How would this icon appear?

With this direction the favorite feature won’t be available for extensions that only have one page. The submenu UI doesn’t appear with the favorite affordance, and there’s no other way to favorite.

**Comment by elizaan36** [comment]
Few other design notes:
- A tooltip on hover can be a helpful cue that the extension can be favorited or unfavorited.
- The outlined icon is using the grey nav text color: $gray-600
- And the filled star icon color: $alert-yellow

<img width="825" alt="Screen Shot 2021-01-28 at 10 20 53 PM" src="https://user-images.githubusercontent.com/5121465/106231352-1f7b0f00-61b7-11eb-9bf0-6bf216ae1473.png">

**Comment by joshuatf** [comment]
>but extension authors have identified a top level page that always loads first when the nav item is selected

Gotcha.  I still see a very large challenge with this approach (cc @psealock ): how do we limit (and identify) a plugin to only allowing one registered page?  We still don't have any way to identify which plugin registered a category.  I think this still needs to be at the category level, even if they are delegating a primary page for a category.

>With this direction the favorite feature won’t be available for extensions that only have one page. The submenu UI doesn’t appear with the favorite affordance, and there’s no other way to favorite.

This is unfortunate for plugins that only register a single item.  If I were a plugin author, I would intentionally create a category to get around this limitation.  Are we okay with this?

**Comment by joshuatf** [comment]
After some deliberation on a video chat, the first iteration of this will favorite by category and will lead to the first item registered in that category.

This removes the need for any additional API work around identifying extensions or their favorited pages.

**Comment by timmyc** [comment]
Since we have a direction to move towards here, do we have an estimate on this project? Or is it large enough to be split up into an epic with child tasks?

**Comment by timmyc** [comment]
@pmcpinto since we are using a single tracks event for the ⭐ click, shall we pass along in a prop the action taken in the click like _favorite_ and _unfavorite_.

Not sure if it ever got discussed, but I imagine extension authors might get in a habit of auto- 🌟 their own extensions upon install - 🙈

**Comment by pmcpinto** [comment]
That makes sense. I'll update the issue description

**Comment by psealock** [comment]
>the first iteration of this will favorite by category and will lead to the first item registered in that category.

Sounds good. I have a follow up question. What happens with the flyout menu? Placing the first item registered directly in the flyout could work.

>the first iteration

Sounds like we may be in a state of flux here. We could skip adding favorites to the flyout for the first cycle because an [API will be required](https://github.com/woocommerce/woocommerce-admin/issues/6223) to pass this information off to Calypso. By skipping this for now, we could prove the concept of favoriting first before diving into creating an API so Calypso can keep up. Thoughts?

**Comment by pmcpinto** [comment]
> Sounds like we may be in a state of flux here. We could skip adding favorites to the flyout for the first cycle because an API will be required to pass this information off to Calypso. By skipping this for now, we could prove the concept of favoriting first before diving into creating an API so Calypso can keep up. Thoughts?

👍 This seems to be the best approach. cc @elizaan36

**Comment by elizaan36** [comment]
@pmcpinto We'd need to create a 2nd API for favorites on top of the one already being created for the flyout? Or could we use the same API to pass the favorited extensions to Calypso?

> What happens with the flyout menu? Placing the first item registered directly in the flyout could work.
@psealock the name of the extension needs to appear in the flyout menu because if it's the first item it would be too generic (i.e. Dashboard, Overview, etc.)

**Comment by joshuatf** [comment]
>Sounds good. I have a follow up question. What happens with the flyout menu? Placing the first item registered directly in the flyout could work.

I figured as @elizaan36 noted that it would still be the name of the extension.

>Sounds like we may be in a state of flux here.

Sorry if I made this sound like we're in flux.  I think we're agreed on this, but I mention iteration since I believe it will continue to change over time based on user feedback.

>We could skip adding favorites to the flyout for the first cycle because an API will be required to pass this information off to Calypso. 

@psealock Are you concerned about time or the need for this API?  I'm very much in favor of moving to an API so we can access all nav items via the API instead of preloading all that data.

**Comment by psealock** [comment]
>the name of the extension needs to appear in the flyout menu because if it's the first item it would be too generic (i.e. Dashboard, Overview, etc.)

Thanks for the clarification @elizaan36, I got myself mixed up there.

>Are you concerned about time or the need for this API? I'm very much in favor of moving to an API so we can access all nav items via the API instead of preloading all that data.

I was trying to simplify the cycle for us and iteratively add this feature, whether using an API or preloaded data. However, you are right, we do seem focused on a direction so keeping with the API plan makes sense.

Thanks everyone
