### ISSUE TITLE
Filter customers by country not working

### ISSUE THREAD

**Issue by WLShop** [woocommerce/woocommerce-admin#6216]
**Description of the bug**
The advanced filter option in the customer list by country is not working at all. Whenever I try to filter by country I am not getting any fields like for all the other advanced filters but it just displays the following code: 
{title}}}Land / Region{{/title}}} {{{rule /}}} {{filter /}}}}

I have tested everything on my staging site with just woocommerce enabled (theme Storefront) so there is no plugin conflict causing this issue.

**To Reproduce**
1. Go to 'Woocommerce - Customers'
2. Click on 'advanced filters'
3. Select 'by country'
4. There is just some sort of code instead of an input field

**Expected behavior**
There should be a dropdown and an input field to search for the country and filter.

**Screenshots**
![advanced filter](https://user-images.githubusercontent.com/78145060/106122443-017ec180-6159-11eb-9df5-8dab8f4d476f.JPG)

**Comment by octaedro** [comment]
Hi @WLShop,
Thank you for reporting this bug.
 Could you tell me which `WooCommerce` and `WooCommerce Admin` version you are using?
I wasn't able to reproduce the bug using `WooCommerce v4.9.2` and `WooCommerce Admin v1.8.3`.

![Screen Capture on 2021-02-03 at 12-28-01](https://user-images.githubusercontent.com/1314156/106769992-4eacd880-661c-11eb-84c0-71e5d18a95d8.gif)


Thank you 🙂

**Comment by WLShop** [comment]
I am also using Woocommerce 4.9.2 and Woocommerce Admin 1.8.3 and I use Wordpress in German.

![image](https://user-images.githubusercontent.com/78145060/106799753-e7187c80-665f-11eb-8740-a98491db4237.png)

**Comment by ilyasfoo** [comment]
I was able to reproduce this issue with WooCommerce `5.1.0-dev` and WooCommerce Admin `1.9.0-dev`. It seems that this issue affects German translation, but there might be other affected languages. Digging deeper, the generated translation JSON file `wp-content/languages/plugins/woocommerce-admin-de_DE-wc-admin-app.json` seems to be faulty in the following key:

```json
"{{title}}Country / Region{{/title}} {{rule /}} {{filter /}}": [
    "{title}}}Land / Region{{/title}}} {{{rule /}}} {{filter /}}}}"
],
```

A working Spanish translation:

```json
"{{title}}Country / Region{{/title}} {{rule /}} {{filter /}}": [
    "{{title}}Pa\u00eds / Regi\u00f3n{{/title}} {{rule /}} {{filter /}}"
],
```

A good place to start debugging might be [where the translation chunks are processed](https://github.com/woocommerce/woocommerce-admin/blob/ec8471dcadc2a91f1e972c84c2d6970e5c84900a/src/Loader.php#L423).
