### ISSUE TITLE
[GlobalStep - WooCommerce 5.0 RC1][IE 11] Contents are misaligned on WooCommerce->Home/Customers screen.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6218]
## Bug Description:
Contents are misaligned on WooCommerce->Home/Customers screen.

## Environment:
Windows 10
Browser:IE11(version:11.00.18362.1)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins
1. Complete the Onboarding setup wizard.
1. Go to Orders and create some orders.
1. Go to WooCommerce->Home screen.
1. Note that Orders appears truncated.
1. Go to WooCommerce->Customers.
1. Note that Search field is overlapped with Customers heading.
1. Now Select Advanced filter under "Show" dropdown and select any filter.
1. Observe that Customer match and Advanced filters section appears misaligned.

## Actual Result:
Contents are misaligned on WooCommerce->Home/Customers screen.

## Expected Result:
Contents on WooCommerce->Home/Customers screen should be properly aligned.

## Screenshots:

![#6218_1](https://user-images.githubusercontent.com/41110392/106154827-06b62d80-61a6-11eb-86a8-51b59b565bbc.png)

![#6218_2](https://user-images.githubusercontent.com/41110392/106154843-0cac0e80-61a6-11eb-90e6-70c3586bdf97.png)

![#6218_3](https://user-images.githubusercontent.com/41110392/106154860-10d82c00-61a6-11eb-9b01-e19c97090fa2.png)

![#6218_4](https://user-images.githubusercontent.com/41110392/106154884-17ff3a00-61a6-11eb-9ae7-e960d535db51.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by octaedro** [comment]
I was able to reproduce this bug in IE 11. It's also happening on other pages like `Customers` or `Analytics`.
