### ISSUE TITLE
wcadmin_analytics_filter Tracking event is blind to variation filter changes.

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6221]
**Describe the bug**
I'm not sure if it's a bug or a desired behavior.

When I change the product variation filter value, the recorded event contains always:
```
{report: "products", filter: "single_product"}
```
even though I change the value to `"all", "compare"` for variations.

While recording at https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/components/report-filters/index.js the value of the variations filter is completely disregarded.

Is that the desired behavior?

**To Reproduce**

1. Go to 'http://localhost/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts'
2. Open browser console
3. Execute `localStorage.setItem( 'debug', 'wc-admin*' );` to make  tracking easier to inspect
3. Pick "Single product" and variable product
4. Change the value of the variation filter.

**Expected behavior**
I guess the respective values of the changed filter should be tracked.

**Actual behavior**
`{report: "products", filter: "single_product"}` is recorded for `"all", "compare", "select_variation"`

**Screenshots**
![Animation of reproduction steps, with visible event logging in the console.](https://user-images.githubusercontent.com/17435/106483859-484d1e00-64af-11eb-8126-1dd33afa4d7f.gif)

**Additional context**
I'm asking, as I'm about to implement similar tracking in another plugin, and would like to keep it consistent.

**Comment by adrianduffell** [comment]
cc @pmcpinto I think you are best placed to answer this?

**Comment by pmcpinto** [comment]
> cc @pmcpinto I think you are best placed to answer this?

Thanks for the ping. This looks like a bug. The event prop should show the filter type that was used: all_variations, single_variation and comparison

**Comment by adrianduffell** [comment]
Thanks for confirming @pmcpinto 

@tomalec Thanks for reporting this. I think you could implement the feature in your plugin with the expected behavior you describe. It will eventually be consistent with WC Admin once the bug is fixed here.
