### ISSUE TITLE
Navigation: Spike to investigate Header Height Solutions

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6235]
Per our discussion in the sprint cycle planning call today, @joshuatf noted that we have a high number of issues ( I'll try to get them all linked here ) that involve visual glitches due to a variety of reasons in new navigation: narrow viewports, presence of mobile app dialogs etc.

Instead of trying to work on these independently, and possibly breaking work done by others to fix various bugs in header height, the agreed path forward was to add this issue to the development cycle for someone to investigate possible solutions to manage header height and related css.

We agreed to timebox this spike to 3 "days"

While I have labeled this navigation, some of the bugs impact classic navigation in wc-admin too.

Related Issues

- #6080
- #5980

**Comment by joshuatf** [comment]
Spent a few minutes thinking about this and just wanted to jot down some initial thoughts.  The best way to see a summation of the current issues is with the new navigation enabled and the `MobileAppBanner` enabled:

<img width="604" alt="Screen Shot 2021-02-01 at 3 40 17 PM" src="https://user-images.githubusercontent.com/10561050/106515593-e935dc00-64a3-11eb-8feb-be79a3d2c00b.png">

All 3 of these items (header, nav, and banner) are blissfully unaware of each other and their impact on surrounding elements.  Two possible solutions pop out to me:

1. The navigation should be housed inside of the header.  These become aware of each other and it's easy to make adjustments to other body element's margin based on the current height/width of these elements.

2. The banner should not be a part of the header and the header remains a fixed height of 60px.  However, the more I think about this solution, the more I realize we're solving one problem to create more problems.  In this scenario we need some other means of the aggregate height of these elements.

**Comment by timmyc** [comment]
Another wrinkle to this one @joshuatf is height can change depending on scroll position on the page - which I think you may have alluded to above with regards to the mobile banner. But the other use case is how the navigation top bar is sticky as one scrolls down the page, but other elements in the header area might not be ( masterbar ), so this can end up with some jank when scrolling down the page currently in a narrow viewport. See video in p90Yrv-278-p2
