### ISSUE TITLE
wcadmin_analytics_filter events' value inconsistency

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6237]
**Describe the bug**
I'm not sure if it's a bug or a desired behavior.

Tracking event `wcadmin_analytics_filter` takes `filter` property that may have a number of values. There is an inconsistency in naming. We have `single_*` and `compare-*` (where `*` is one of `product, category, coupon, customer`. Snake case vs kebab case.

Is there a reason for that, or is it just a typo?

**To Reproduce**

1. Go to http://localhost/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts
2. Open browser console
3. Execute `localStorage.setItem( 'debug', 'wc-admin*' );` to make  tracking easier to inspect
3. Pick "Single product"
4. Change to "Comparison"

**Expected behavior**
Values follow the same casing convention.

**Screenshots**
Logged events for Products Report
![image](https://user-images.githubusercontent.com/17435/106488939-8436b200-64b4-11eb-8762-51be5aaff552.png)
Values observed in trend reports:
![image](https://user-images.githubusercontent.com/17435/106489187-c829b700-64b4-11eb-9b88-b7dbad3b1f45.png)

**Additional context**
I guess it may be a hard decision to change it right now, as it may make it hard to compare gathered data with a new one.

I'm asking as I'm implementing similar filters for another plugin, and wonder should I use unified casing, or follow the convention paved here.

**Comment by adrianduffell** [comment]
Thanks for raising this @tomalec, I asked the team about it, and it doesn't seem like there is a standard naming convention here to follow.

I see you ended up using kebab case in your filter. This LGTM 🙂
