### ISSUE TITLE
Setup Checklist: Appearance Task / Home Page Creation can over-write existing home page

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6241]
Many parts of the WooCommerce onboarding flow _assume_ that the WordPress install that is being used to setup WooCommerce is new, and we don't often consider if a user has already spent time customizing a theme or perhaps the home page.

My daughter discovered this while building her own store. She had already selected a theme from the wp.org repository, and customized the home page quite a bit. She then installed Woo, and proceeded through all the steps of the Setup Checklist ( all on her own! cool! ) but unfortunately this resulted in her home page she had setup being over-written by the one in the appearance task in the Setup Checklist.

**To Reproduce**

1. Before installing Woo, make customizations to your home page. Really get it all dialed in and fancy looking.
2. Install Woo, go through the OBW, and complete the setup checklist, making sure to do the homepage setup task.
3. Visit your site home page, and realize that all of your customizations have been hidden away on your old home page/post.

Not sure the ultimate fix here, but at the very least I think we need to make the appearance / home page setup task takes a look at the current home page post, and does a quick check to see how long it has been published, and maybe if there are a certain number of revisions made already, we remove the step to customize the home page. In its place, perhaps we can link out to documentation on adding Woo-centric bits and blocks to one's established home page.

**Comment by ilyasfoo** [comment]
> Check to see how long it has been published

> Certain number of revisions made already

I feel like these assumptions a bit sketchy, there's always that edge case user who does things slightly differently and wind up surprised by the outcome. Would it be better, if say we:

1. Make the step optional
2. Put a warning or note next to it?

**Comment by ilyasfoo** [comment]
> Check to see how long it has been published

> Certain number of revisions made already

I feel like these assumptions is a bit sketchy, there's always that edge case user who does things slightly differently and wind up surprised by the outcome. Would it be better, if say we:

1. Make the step optional
2. Put a warning or note next to it?

**Comment by ilyasfoo** [comment]
> Check to see how long it has been published

> Certain number of revisions made already

I feel like these assumptions is a bit sketchy, there's always that edge case user who does things slightly differently and wind up surprised by the outcome. Would it be better, if say we put a warning or note next to it?

**Comment by octaedro** [comment]
I like @ilyasfoo's idea. Perhaps we can ask the user if they want to override the home page (when there is one set already).
That would be a pretty simple fix that should take 1, maximum 2 days.

Maybe @elizaan36 could share her opinions about this issue.

**Comment by elizaan36** [comment]
Ideally we could detect if the user already has a homepage they've edited and present the warning conditionally. 

Would be better not to present a warning or confirmation of override to all users as it would cause confusion.

**Comment by timmyc** [comment]
Since we never landed on a proper direction for this issue, I'm going to remove from this sprint cycle.

**Comment by moon0326** [comment]
Closing this as this has been stale for 6+ months. Please re-open it if needed.
