### ISSUE TITLE
[Settings Page] Fatal Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6242]
<img width="526" alt="Screen Shot 2021-02-02 at 1 59 42 PM" src="https://user-images.githubusercontent.com/1922453/106537423-2a3ef680-655f-11eb-97ed-5904027f139f.png">

## Steps to Reproduce

1. Visit wc-admin settings page, `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fsettings`
2. See a fatal error

**Comment by psealock** [comment]
This seems to be isolated to my environment, so I will close this out and keep an eye on reports from users.

**Comment by wdgordon** [comment]
I am getting the same error when I visit the same page.

My system details:
Wordpress v5.6.1
WooCommerce v4.9.2
WooCommerce Admin Package 1.8.3

**Comment by psealock** [comment]
I just tried on my instance where I had the bug and it now works. Have you tried updating WooCommerce?

**Comment by tivendo** [comment]
I am having the same problem here too... :-/

**My system:**
WordPress 5.7
WooCommerce Version 5.1.0
WooCommerce Admin Package 2.0.2
![CleanShot 2021-03-13 at 00 00 34](https://user-images.githubusercontent.com/78300247/111007462-36547a00-838f-11eb-80f0-74978352c210.png)

**Comment by samueljseay** [comment]
@tivendo @wdgordon I believe this should be fixed by a recent bugfix: #6540 

This fix should be avaiable in the [2.1.2 release of wc-admin plugin](https://github.com/woocommerce/woocommerce-admin/releases/tag/v2.1.2). Is it possible for you to try this out and see if it solves the problem?
