### ISSUE TITLE
Marketing extension icons getting cut off on mobile

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6249]
**Describe the bug**
@LevinMedia not sure if you have any insight on this but I noticed that on mobile the extension icons are getting cut off in the "Installed marketing extensions" section of the Marketing page.

**To Reproduce**

1. Go to 'WooCommerce > Marketing' on a mobile device
2. Scroll down to 'Installed marketing extensions'
3. See error

**Expected behavior**
The icons should be fully visible and not cut off (they're the correct width on desktop.)

**Screenshots**
https://share.getcloudapp.com/z8uPqk8R

**Smartphone (please complete the following information):**

- Device: Pixel 4 XL
- OS: Android 11
- Browser: Chrome

**Comment by octaedro** [comment]
Thank you @elizaan36 for reporting this.
I just confirm that this is happening when the screen width is smaller than `979 px` (no matter the device).

**Comment by LevinMedia** [comment]
@elizaan36 definitely a bug! They should maintain their 1:1 aspect ratio on all viewport sizes. Added it to the trash pickup list.

**Comment by elizaan36** [comment]
we're still working on this, stale bot!😅

**Comment by moon0326** [comment]
@elizaan36 Hey ✋  I wasn't able to reproduce it on chrome using mobile view or android emulator


<img width="508" alt="Screen Shot 2021-04-29 at 12 07 28 AM" src="https://user-images.githubusercontent.com/4723145/116514012-4365f380-a87f-11eb-9ff8-5f4e52bd772c.png">

Could you please try it again on your device (Pixel 4 XL) when you get a chance, please?

**Comment by samueljseay** [comment]
@moon0326 @elizaan36 I believe this must have been fixed. I just tried a bunch of mobile device emulated screen sizes and even for *tiny* screens the icons display properly.

<img width="450" alt="Screenshot 2021-05-05 at 2 22 57 PM" src="https://user-images.githubusercontent.com/1281828/117090824-80fddb80-adad-11eb-8100-cfd12581c7fa.png">

**Comment by elizaan36** [comment]
ah hey, sorry I missed this one. That's great, we can close it then. Thank you!
