### ISSUE TITLE
Turn off product management onboarding on mobile

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6250]
**Describe the bug**
The product management tooltips are causing poor accessibility on mobile. Is this something we could easily turn off for smaller screen sizes?

**To Reproduce**

1. Go to 'WooCommerce > Products > Add new'
2. See error (Tooltips are misaligned and blocking areas of the navigation)

**Expected behavior**
I'd either expect the tooltips to align with the content they're referring to, or not see them at all.

**Screenshots**
https://share.getcloudapp.com/wbu9JY2G

**Smartphone (please complete the following information):**

- Device: Pixel 4 XL
- OS: Android 11
- Browser: Chrome

**Comment by octaedro** [comment]
I was able to reproduce this bug but with a small change to the reproduction steps.

**To Reproduce**
Steps to reproduce the behavior:

- Go to 'WooCommerce > Products > All Products'
- Press `Create Product`
- Open the sidebar.
![Captura de Pantalla 2021-02-03 a la(s) 15 59 05](https://user-images.githubusercontent.com/1314156/106795529-f46e4080-6638-11eb-8959-423cce94b7f9.png)

- See error (Tooltips are misaligned and blocking areas of the navigation)

**Comment by hsingyuc** [comment]
I'm also able to reproduce the bug but only works if starts from the WooCommerce home page task card.

To reproduce:
- Go to Woocommerce home page task card
-  Add products -> Add manually
-  See error

I also found the code in the Woocommerce repo, not WooCommerce Admin but I'm not sure if we should move this issue to WooCommerce or it's other changes from WooCommerce Admin causing the error.

**Comment by elizaan36** [comment]
Thanks @Ferdev and @hsingyuc for testing this and confirming the steps to reproduce. I'm moving to the WooCommerce repo and will close this issue. ☺️
