### ISSUE TITLE
Top bar slightly overlaps wp-admin navigation on mobile

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6251]
**Describe the bug**
One some screens the top bar slightly overlaps the wp-admin navigation on mobile

**To Reproduce**

1. Go to 'WooCommerce Home' or any top level page in WooCommerce on a mobile device
2. See error (When wp-admin menu is open, the top bar slightly overlaps)

**Expected behavior**
The top bar should not overlap the wp-admin navigation.

**Screenshots**
![Screenshot_20210202-131701](https://user-images.githubusercontent.com/5121465/106666325-11d5d880-656d-11eb-8446-49191ce67264.png)

**Smartphone (please complete the following information):**

- Device: Pixel 4 XL
- OS: Android 11
- Browser: Chrome

**Comment by hsingyuc** [comment]
I can fix it 🔨
