### ISSUE TITLE
Orders panel rows are showing two borders on mobile (and page title is blue)

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6252]
**Describe the bug**
When viewing the orders panel on mobile, I'm seeing two borders and the content of the row is shifted slightly lower than it should be. Also, I noticed that the page title and count badge turned blue rather than the dark grey color - this happens on desktop as well.

**To Reproduce**

1. Go to 'WooCommerce Home' on a mobile device in a store that has processing orders.
2. See error (double border between rows and blue header/count)

**Expected behavior**
Single border between the rows, row content aligned horizontally, and dark grey header text color.

**Screenshots**
![Screenshot_20210202-135436](https://user-images.githubusercontent.com/5121465/106666999-f15a4e00-656d-11eb-8682-df2420736602.png)

**Smartphone (please complete the following information):**

- Device: Pixel 4 XL
- OS: Android 11
- Browser: Chrome

I don't see the blue color change on a new JN site, only on my Ecom plan site.

**Comment by octaedro** [comment]
Hi @elizaan36,
I tried to reproduce the bug on Android, iOS, and on my Laptop but I couldn't.
Do you have more information about this bug?

![Captura de Pantalla 2021-02-03 a la(s) 17 02 18](https://user-images.githubusercontent.com/1314156/106802361-a0b42500-6641-11eb-87e1-1ee1afdfbfa6.png)

**Comment by elizaan36** [comment]
hi @octaedro, thanks for taking a look! 

I'm only able to reproduce the blue card title color on one site but I have a hunch this particular site isn't compiling the Gutenberg button style correctly. There's also an issue with the Display button - the width loses its' padding and it's showing the blue text color on hover. 

Blue card title
https://share.getcloudapp.com/8LukwYAN

Display icon width and blue hover state
https://share.getcloudapp.com/llu948wo

This could be something strange with my site, maybe because I have loads of plugins installed? May just be a weird anomaly with all the layers of styles!

**Comment by ilyasfoo** [comment]
I've tried with my e-commerce site on my iOS device, and couldn't reproduce either:

<img src="https://user-images.githubusercontent.com/3747241/109937693-2216da00-7d0a-11eb-8544-5b19e23078ae.png" width="300"/>

It might be something to do with your particular site's configuration @elizaan36. If it might help, can you also check your developer console to see if there are any asset loading errors?

**Comment by elizaan36** [comment]
thanks for taking a look @ilyasfoo. I just looked into this again and I may have found the issue but can't figure out how to fix it.

The double line only occurs when the top component panel item is selected/active, which means that component is separated slightly from the activity panel header. I found a 5px margin-bottom that probably doesn't need to be there, and that could be the culprit.

Here's a screenshot of the area with the dev tools open:
<img width="1097" alt="Screen Shot 2021-03-05 at 9 17 01 AM" src="https://user-images.githubusercontent.com/5121465/110135757-81213100-7d94-11eb-806c-d39348eb1511.png">

When I play around with the CSS properties in client/homescreen/activitypanel/style.scss/, nothing will change that extra 5px margin that's pushing down the first order row.

This is a very small detail so no worries if you don't have time, but I wonder if you have any ideas on how to remove that 5px?

**Comment by elizaan36** [comment]
Taking a look at the console, I am getting some errors but don't know if they're related.
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/5121465/110137163-24bf1100-7d96-11eb-9679-8b5dc8523e66.png">

**Comment by ilyasfoo** [comment]
@elizaan36 I was able to reproduce by adding forcing `:focus` state on the first element of `woocommerce-activity-card__button`, which simply adds a gray border around each active order and clearly showing the extra margin. Clicking right click on an order would also cause this to appear. 

We can remove the excess 5px margin by adding something like the following:
```scss
.components-panel__body.is-opened > .components-panel__body-title {
    margin-bottom: 0;
}
```

However, I'm curious if we have can make a better design for the "focus" state of the order list? The double line border on active does not look as appealing I might add.
