### ISSUE TITLE
Update to the Insight Inbox message

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6264]
The insight inbox message (#5937) needs a quick update for better readability and data.

Current message:
![image (1)](https://user-images.githubusercontent.com/5121465/106802644-d7ca0c80-6628-11eb-952b-14723c148e99.png)

Update:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/5121465/106803242-9d14a400-6629-11eb-8e1f-ef2bd6515310.png">

In the updated version, the "Do you find this useful" question is on a new line and there's a third action in the footer with a "No" option.

**Comment by octaedro** [comment]
Estimate: 1

The notes type `survey` accepts multiple options (`yes`, `no`, etc), so we only need to change the note content and add an action.
