### ISSUE TITLE
Emailed analytics for Orders has incorrect Customer data and missing Customer Type column

### ISSUE THREAD

**Issue by shaunkuschel** [woocommerce/woocommerce-admin#6274]
**Describe the bug**
When the Analytics > Orders download file is emailed (rather than immediately downloadable, due to the number of results), the "Customer" and "Customer Type" columns appear to be merged together into a single "Customer" column that incorrectly displays the data from the missing "Customer Type" column. The actual customer data (name) is not provided.

**To Reproduce**

1. Go to Analytics > Orders
2. Set the Date Range to something that produce enough results to email the data, such as "Last Year" compared to "Previous Year". 
3. Ensure that all columns are enabled and notice the separate columns for "Customer" and "Customer Type".
4. Click the "Download" button and see the email notification message.
5. Open the emailed file.
6. Notice that the "Customer Type" column is not included in the file. Instead, that data shows in the "Customer" column and the actual customer data is not included.

**Expected behavior**
The emailed file should include all of the columns that are enabled in the same way the instant download does, and the data should be shown in the correct columns.

**Screenshots**
Screenshot of the Analytics > Orders page, with both Customer columns enabled:

![](https://d.pr/i/3Ikvei+)
(Link to screenshot: https://d.pr/i/3Ikvei+)

Screenshot of the emailed file with the incorrect columns and missing data:

![](https://d.pr/i/ZH1xDu+)
(Link to screenshot: https://d.pr/i/ZH1xDu+)

**System info:**

* WC Version: 4.9.2
* REST API Version: ✔ 4.9.2
* WC Blocks Version: ✔ 4.0.0
* Action Scheduler Version: ✔ 3.1.6
* WC Admin Version: ✔ 1.8.3
* Log Directory Writable: ✔
* WP Version: 5.6.1
* OS: macOS Big Sur
* Browser Chrome
* Version 88.0.4324.96

**Additional info:**
Report: 3713244-zen

**Comment by adrianduffell** [comment]
Hi @shaunkuschel,

Thanks for reporting this. It should now be fixed in WooCommerce 5.3.

Related PRs: https://github.com/woocommerce/woocommerce-admin/pull/6556 and  https://github.com/woocommerce/woocommerce-admin/pull/6567

However please re-open this if you're still seeing the issue.
