### ISSUE TITLE
Unable to run a single test only in Docker PHP test suite

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#6279]
**Describe the bug**

It is not possible to run a single test anymore with `npm run test:php -- --filter=<name of test>`.

This is because the `--filter` option is sent to the last statement in the npm script `docker-compose -f docker/wc-admin-php-test-suite/docker-compose.yml down`.

**To Reproduce**

Run `npm run test:php -- --filter=foo`

This should **NOT** run any tests because none are named `foo`. Observe that all tests run.

**Expected behavior**

Only tests matching the filter should run.

**Comment by louwie17** [comment]
@adrianduffell my bad on creating this one, I added the second `docker-compose down` command so that the `mysql` container doesn't stay running. You could remove this, as keeping it running is not a huge deal, or create a small script.

**Comment by adrianduffell** [comment]
@louwie17 No worries, I've been wondering about using a [post script](https://docs.npmjs.com/cli/v6/using-npm/scripts#pre--post-scripts)  to continue running the second command. I dislike how it adds another entry to our `scripts` though 😅  

In the longer term, a script like you mentioned seems best to me.
