### ISSUE TITLE
Store management section is not showing until extended task list is hidden

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#6288]
**Describe the bug**
The store management link section should be displayed once the main setup task list is **hidden**. Currently this is not the case and it doesn't appear until the extended task list is also hidden.
Which a user can't hide unless they use the old help panel.

**To Reproduce**
1. Create a new Woo store and add the Woo Admin plugin (2.0.0 beta)
2. Finish the onboarding wizard
3. Dismiss the main task list
4. Management store links are not displayed on the homescreen, although the `Reviews` are (if you created a product)
5. Go to **WooCommerce > Reports** and click the **Help** button in the top right
6. Select **Setup wizard** on the left, and **Disable** the extended task list
7. Navigate back to the home screen, and see the management store links are displayed now

**Expected behavior**
Management store links should only be dependent on the Woo Admin task list hidden state, not the extended task list as well.

**Screenshots**
When just the main task list is hidden:
<img width="1624" alt="Screen Shot 2021-02-08 at 2 03 11 PM" src="https://user-images.githubusercontent.com/2240960/107262224-a7aeaf00-6a16-11eb-99cb-54d92855e623.png">

When the extended task list is set to hidden as well:
<img width="1624" alt="Screen Shot 2021-02-08 at 2 03 31 PM" src="https://user-images.githubusercontent.com/2240960/107262266-b5643480-6a16-11eb-84de-21e2df72d396.png">

cc: @pmcpinto @elizaan36

**Comment by louwie17** [comment]
I did create a PR for this already if we do decide the above **expected behaviour** is correct, we can update it if we decide to change it.

**Comment by pmcpinto** [comment]
I think that the best option is to only hide the store management area when the store setup task list is hidden and always display it if the extended task list is displayed. @louwie17 the extended task list is only displayed if an extension is using it, correct?

@elizaan36 what do you think?

**Comment by louwie17** [comment]
>  @louwie17 the extended task list is only displayed if an extension is using it, correct?

Yeah that is correct.

**Comment by elizaan36** [comment]
> I think that the best option is to only hide the store management area when the store setup task list is hidden and always display it if the extended task list is displayed.

+1 !
