### ISSUE TITLE
Add a back button to the top bar

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6293]
**Overview**
We want to give merchants the ability to easily navigate back to WooCommerce Home from a task list screen so they don't feel lost. Task list screens (accessed via the home screen task list) currently don’t have any indication of how to get back to where you came from and there may be a moment of confusion or feeling stuck before you decide on where to go next. One solution would be to complete the task list flow and route users back to the home screen, but a critical usability improvement in the meantime is to add a back button.

**Background**
[The original issue has since been closed](https://github.com/woocommerce/woocommerce-admin/issues/2811), which took a more holistic approach to reveal a back button on all tertiary screens (i.e. any screen not represented by a menu item in the navigation.) Depending on the effort involved, we could start with the task list screens only and move on to others such as the Edit Product and Edit Order screens, Settings, etc. or try to tackle everything in parallel.

**Screenshots**
![Home - Add my products](https://user-images.githubusercontent.com/5121465/107301882-f887cd00-6a41-11eb-868e-5615a65a2994.png)

Mobile
<img width="682" alt="Screen Shot 2021-02-08 at 7 08 56 PM" src="https://user-images.githubusercontent.com/5121465/107301889-fcb3ea80-6a41-11eb-86a9-7bd973d556b1.png">

**Details**
- The page title reflects the name in the task list (i.e. Add products)
- Task list screens include Add products, Add payment methods, Add tax rates, Set up shipping costs, and Personalize my store
- There's a tooltip on hover that indicates the page you'll navigate back to
- When clicked the back button should take the user directly back to the previous screen. Most of the time this will mean going up 1 level in app hierarchy, but in some cases it will go back to another origin screen. If the user lands on a tertiary screen directly (from an email or something similar) it will default to taking the user up 1 level in app hierarchy.
- More details on the component and anatomy are in Figma that I can share separately

cc @pmcpinto @timmyc 

**Event tracking**
Event name: `wcadmin_topbar_back_button`
Event prop: `page_name` - the page where the user clicked in the back button

**Comment by timmyc** [comment]
@elizaan36 this is looking good to me. The only thing that I could see being slightly confusing is having the two different `<` back arrows when the new navigation is active... and they are slightly different as the one in the nav sidebar shows the name for the "next level up" screen alongside the `<` whereas in the navigation bar, it is being shown by the current task/page title.

I'm likely picking nits though, I think we should add this in, make sure we have a tracks event be recorded upon click that includes the checklist step the user is currently on, and see how it gets used.

**Comment by elizaan36** [comment]
> The only thing that I could see being slightly confusing is having the two different < back arrows when the new navigation is active... and they are slightly different as the one in the nav sidebar shows the name for the "next level up" screen alongside the < whereas in the navigation bar, it is being shown by the current task/page title.

Thanks @timmyc. This was exactly my hesitation as well. (shared in pbIJXs-BQ) 
After some back and forth and design team collaboration, we feel good about this direction regardless of the two back arrows being visible for a couple reasons.
- The navigation back arrow only appears at larger screen sizes. On mobile the nav is dismissed so that only the top bar back arrow appears.
- The tooltip displays the page title of where you're going back to, so in some way it replicates the pattern in the nav.

**Comment by samueljseay** [comment]
It definitely feels quite difficult to approach this holistically, I'm thinking I'll just try tackle this for the task list but it raises a question for me.

> When clicked the back button should take the user directly back to the previous screen. Most of the time this will mean going up 1 level in app hierarchy, but in some cases it will go back to another origin screen.

@elizaan36 is this requirement still relevant if its *just* implemented for the task list? The only other way I can currently imagine getting to a task is to have a bookmark. If we always go back to the previous page, then if the user arrives at the task via a bookmark it would do nothing. but if we just made it always return to the home screen... would that be enough?

**Comment by pmcpinto** [comment]
> It definitely feels quite difficult to approach this holistically, I'm thinking I'll just try tackle this for the task list but it raises a question for me.

Focus on the task list seems to be a good starting point. We should also include tracking to keep an eye on usage. @samueljseay do you want me to add it to the description?

**Comment by elizaan36** [comment]
> @elizaan36 is this requirement still relevant if its just implemented for the task list? The only other way I can currently imagine getting to a task is to have a bookmark. If we always go back to the previous page, then if the user arrives at the task via a bookmark it would do nothing. but if we just made it always return to the home screen... would that be enough?

If there's no origin screen (in this case where people arrive via bookmark), the back button would navigate up one level. In this case, either way the back button would navigate to the Home screen so I think that simplifies things!

**Comment by samueljseay** [comment]
@pmcpinto thanks any details on tracking would be appreciated

**Comment by pmcpinto** [comment]
> @pmcpinto thanks any details on tracking would be appreciated

Done!
