### ISSUE TITLE
New message - Mollie notification

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6296]
**Description:** we want to test promoting Mollie through an inbox message while the payment gateway is not available in the Payments task (it will be included in 5.1).

**Title:** Effortless payments by Mollie
**Copy:** Offer global and local payment methods, get onboarded in minutes and supported in your language – try it now!
**Segmentation:** new users located in one of the following countries
Germany 
France
Netherlands 
Belgium
Spain 
Italy
Austria
Finland
Switzerland 
**Timing:** 3 days after store creation if the store doesn't have one of the following extensions installed
PayPal
Stripe
Klarna
**Cadence:** Once
**CTA leads to:** https://wordpress.org/plugins/mollie-payments-for-woocommerce/
**CTA label:** Install Mollie

**Comment by pmcpinto** [comment]
@becdetat do you think it's possible to release this notification early next week? AFAIK we don't have a way to auto-install extensions directly from an inbox message CTA, correct? I'm assuming that we need to send them to wp.org to install the extension.

@MechielCouvaras I think it will be better to give users a 2-3 days buffer after the store creation before displaying the message, giving them time to evaluate the options displayed in the payments task. Do you agree?

**Comment by becdetat** [comment]
@pmcpinto 

> do you think it's possible to release this notification early next week?

It should be possible, however we usually have a bit of a bottleneck with getting approval from woocommerce.com.

I'll add it to my list.

> AFAIK we don't have a way to auto-install extensions directly from an inbox message CTA, correct? I'm assuming that we need to send them to wp.org to install the extension.

That's correct. If this becomes a desired piece of functionality it is probably possible to add it but it would need some investigation first. Backwards compatibility (with older versions of WCA) also needs to be considered.

**Comment by pmcpinto** [comment]
> That's correct. If this becomes a desired piece of functionality it is probably possible to add it but it would need some investigation first. Backwards compatibility (with older versions of WCA) also needs to be considered

Ok. So let's keep it simple and redirect users to the URL. @MechielCouvaras do you prefer to redirect them to the [wp.org page](https://wordpress.org/plugins/mollie-payments-for-woocommerce/) or [wc.com page](https://woocommerce.com/products/mollie-payments-for-woocommerce/)?

**Comment by MechielCouvaras** [comment]
Sure @pmcpinto - I'm happy with the buffer as per your recommendation. If we are redirecting, let's go with the wc.com page.

**Comment by pmcpinto** [comment]
@moon0326 @becdetat just a heads up that the CTA should redirect to https://woocommerce.com/products/mollie-payments-for-woocommerce/

**Comment by pmcpinto** [comment]
@moon0326 @becdetat is it possible to release this notification this week?

**Comment by becdetat** [comment]
@pmcpinto, @moon0326 has done the work, it's waiting for a second approval from Alpha. Hopefully it will get approved and merged in the next 24 hours.

**Comment by pmcpinto** [comment]
@becdetat thanks for the update. Pls let me know when it's merged so I can start looking at the data.

**Comment by becdetat** [comment]
I've pinged Alpha again for their review

**Comment by pmcpinto** [comment]
@moon0326 @becdetat can you confirm that the notification is already being sent to users?

**Comment by pmcpinto** [comment]
@becdetat @moon0326 I forgot to mention that the notification should be removed after WC 5.1 is released, as the payments step is going to include Mollie. Do you want me to open a new issue about this?
