### ISSUE TITLE
Customer Effort Score: segmenting settings data

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6306]
**Description:** the settings management experience covers a wide range of use cases and just tracking the overall settings score doesn't give us a full picture of the settings that have the lowest scores and so on. We should find a way to improve the tracking, in order to get the score of specific settings areas (general, products, payments, etc).

I think that the easiest way to track this is through a new event prop just focused on settings (eg: `settings_area` : `general`, `products`..). But I'm open to evaluating other alternatives.

**Comment by becdetat** [comment]
@pmcpinto A new event prop would be the easiest way to segment on settings area. Is that going to be granular enough for you?

**Comment by pmcpinto** [comment]
Yes. Just to clarify, I'm talking about the top-level settings areas: https://d.pr/i/dHUgO6

Segmenting by subsections of specific settings areas can be done in the future, if we identify a settings area with a bad score :)

**Comment by pmcpinto** [comment]
@ilyasfoo is it possible to add an event prop for the WCPayments settings? /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments

I can open a new GH issue. I'm just wondering if it should live in the wc admin or wc payments repo

**Comment by ilyasfoo** [comment]
@pmcpinto That's a good question. Since the track is done in wc-admin, so you can create GH issue in this repo. We can add a new prop `section` to capture this. Should it apply to other sections as well? From the developer's perspective, it's easier to just track all section param.

**Comment by pmcpinto** [comment]
> Should it apply to other sections as well? From the developer's perspective, it's easier to just track all section param.

Sounds good to me. I just created the issue: #6717
