### ISSUE TITLE
Customer Effort Score: include additional features

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6307]
**Description:** we want to start triggering the Customer Effort in certain features that weren't included in the initial launch:

1. Import Products
2. Product Categories
3. Product Attributes
4. Product Tags
5. Search (orders, products, customers)

**Comment by pmcpinto** [comment]
@elizaan36 can you add the copy for each one during the next few days? Thanks in advance

**Comment by elizaan36** [comment]
Hey @pmcpinto, no problem. Here's copy for each:

**Import Products**
> How easy was it to import products?

**Product Categories**
> How easy was it to add a product category?

**Product Attributes**
> How easy was it to add a product attribute?

**Product Tags**
> How easy was it to add a product tag?

**Search (orders, products, customers)**
> How easy was it to use search?
