### ISSUE TITLE
Customer Effort Score: remove it from some features in WC 5.2 or 5.3

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6308]
**Description:** the scores collected between January and March will enough to gather insights on most of the features that we're tracking. We should disable the CES in the following features (ideally in WooCommerce 5.2):

- `product_update`
- `product_add_publish`
- `shop_order_update`

**Comment by pmcpinto** [comment]
@becdetat just to confirm. This is going to be released in WC 5.2, correct?

**Comment by becdetat** [comment]
@pmcpinto 

> This is going to be released in WC 5.2 

I believe that's correct, yes. It will be in WCA 2.1.0, which should be included in WC 5.2.
