### ISSUE TITLE
Total count of Downloads on WooCommerce Admin Analytics is incorrect

### ISSUE THREAD

**Issue by BowFarmer** [woocommerce/woocommerce-admin#6326]
The total count of downloads on the Downloads report on WooCommerce Admin Analytics is incorrect. I am using WooCommerce 5.0.0, however for as long as I can remember, the Downloads total WooCommerce shows has never been correct. I have been using WooCommerce since 2019.

The Downloads report appears to show the total number of downloads of all time, not the total download count for the time period of the report.

For example, here is a screen shot of downloads comparing February 1-10, 2021 and February 1-20, 2020.

The downloads are correct for each of the days.

2021: 68, 13, 29, 64, 46, 39, 15, 13, 6, 40, total = 333
2020: 35, 21, 21, 9, 43, 37, 47, 57, 26, 17, total = 313

However, the total downloads shows as 18,789 for both Feb 1-10, 2021, and Feb 1-10, 2020 time periods.

<img width="402" alt="WoocommerceDownloadCount" src="https://user-images.githubusercontent.com/70533824/107677366-078f9a80-6c4f-11eb-9add-7691a60aa690.png">

**Comment by joelclimbsthings** [comment]
I was able to confirm this on `wc-admin` 2.0. One simple way to generate the data is to do this following:
- Create downloadable product
- Create fake order with product
- Click this button on the Order Detail page:
![image](https://user-images.githubusercontent.com/444632/107996443-48601a00-6f95-11eb-8874-a03d664e4e44.png)
- Use the copied link to download a few times
- To ensure there are downloads under the comparison period (within the Chart), you can alter one of the timestamps in the `wp_wc_download_log` table. 
- Go to `Analytics->Reports->Downloads` and observe that the count for the comparison period is incorrectly the same as the original period. 

Also note that I suspect this _may_  be related to this other issue: https://github.com/woocommerce/woocommerce-admin/issues/6255

**Comment by melindahelt** [comment]
4209915-zen
