### ISSUE TITLE
Core settings pages broken in new navigation

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6327]
**Describe the bug**
When the new nav is turned on, the settings pages cannot be accessed.

Noticed when testing https://github.com/woocommerce/woocommerce-admin/pull/6319

**To Reproduce**

1. Turn on the new nav.
2. Navigate to a core settings page.
3. Note the error.

**Expected behavior**
Expected to be able to access the settings pages.

**Screenshots**
<img width="796" alt="Screen Shot 2021-02-11 at 4 17 23 PM" src="https://user-images.githubusercontent.com/10561050/107700380-67a13380-6c85-11eb-9216-16c0362b893b.png">

**Comment by phillipcornwell** [comment]
Another report in 25981552-hc

I was able to replicate it on my test site too.
