### ISSUE TITLE
Custom filter analytics / reports stopped working

### ISSUE THREAD

**Issue by BuroStaal** [woocommerce/woocommerce-admin#6339]
We have used the woocommerce_admin_products_report_filters to create a filter to split all the data based on user role. So we have the customers and the retailers and we can split the data for these orders. We have used this tutorial to create this functionality: https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/

It did work, but since today it stopped working for most of the tabs within WooCommerce Analytics. We get this notice: "Cannot read property ‘settings’ of undefined". I think this is caused by the update to WooCommerce 5.0. Any idea how to solve this?

**Comment by joelclimbsthings** [comment]
Hi @BuroStaal , thanks for reporting!

I'm currently wondering if it could have something to do with this line: https://github.com/woocommerce/woocommerce-admin/blob/087b9fad197c561119960def835650671e6f6e04/client/analytics/report/products/index.js#L80

But we'll need a bit more information to debug. Could you optionally provide the following?
- A code snippet of your filter itself (or at least the main properties on that object
- Screenshot of the error in the console
- Screenshot of the file that the error is originating in, if that's clear when you click on the link next to the error.

Just let us know and we'll see if we can figure this out.

**Comment by BuroStaal** [comment]
Thanks for your reply @joelclimbsthings ! Our developer will have a look at it next monday and provide you with the extra info you have asked for.

**Comment by jeffstieler** [comment]
Confirmed this bug in https://github.com/woocommerce/woocommerce-admin/issues/6842

**Comment by Sidlegionair** [comment]
@jeffstieler Thanks for looking into this! The solution given in #6842 works!
