### ISSUE TITLE
[WC 5.1 beta with WC Admin 2.0.1] `Store Setup` navigation option doesn't work when using it after skipping onboarding 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#6341]
**Describe the bug**

Discovered this bug as a part of WC 5.1 beta pre-release testing. If you skip the onboarding right at the beginning, you'd get to the Home screen of WooCommerce. From there, let's say you navigate to System Status Report and from there click on `Store Setup` option in the navigation menu in the top right corner, nothing seem to happen. There are no errors in the console but also seems to be no way to reload the page. 

This happens in both JN site and Atomic using Crome. See the gif below of the behavior on JN site:

![](http://g.recordit.co/xxyp7Nl2xX.gif)

**To Reproduce**

1. On the brand new JN or Atomic site, install & activate WC 5.1 - onboarding wizard will start automatically. 
2. Skip the onboarding on the very first screen (there is an option at the bottom of the form). 
3. You'll get to the Home screen of WooCommerce. From there, navigate to System Status Report. 
4. Click on the `Store Setup` option and observe that you stay on the same page and that page freezes. No errors in the console and seem to be no way to reload the page. 

**Expected behavior**

I expected to be able to click on the `Store Setup` option and be redirected back to the Home Screen of WooCommerce with the task list. 

**Screenshots**

See gif above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 88.0.4324.150 (Official Build) (x86_64)

**Additional context**

N/A.

**Comment by joelclimbsthings** [comment]
Definitely an issue. I was able to reproduce with WC 5.0 as well. The tab locks up entirely and has to be closed.

**Comment by timmyc** [comment]
Thanks for the report @juliaamosova and also @joelclimbsthings for verifying... sounds like it is not a regression with the 2.0 release so unsure if we should get a fix release queued up quite yet.

@becdetat do you think we should create a 2.0.1 milestone and track this and any other issues that come out of the 5.1 testing cycle?

**Comment by joelclimbsthings** [comment]
It actually looks like this was already fixed just a few hours ago in main by  https://github.com/woocommerce/woocommerce-admin/pull/6233.

We may want to promote that commit if we want to get this addressed as soon as possible @timmyc .

**Comment by becdetat** [comment]
@timmyc 

> @becdetat do you think we should create a 2.0.1 milestone and track this and any other issues that come out of the 5.1 testing cycle?

Yes, I'll do this today and cherry-pick #6233
