### ISSUE TITLE
Setup Checklist: Klarna Payments not Showing for UK Addresses

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6349]
**Describe the bug**
Reported in  pbIJXs-ub-p2, and a follow-up to #5869 - when using a UK based address, Klarna is not being shown as a recommended payment method in the Setup Checklist.

I think we have hit this bug before, possibly with Stripe, and I think it is due to us using the [UK country code](https://github.com/woocommerce/woocommerce-admin/blob/1e00908a7317f5185ceb25dd5befb54007104e53/client/task-list/tasks/payments/methods.js#L287) in the logic when the country code that gets persisted by Woo when "United Kingdom" is chosen on the OBW is `GB`. For example here is how we are using `GB` [for the Square payment method](https://github.com/woocommerce/woocommerce-admin/blob/1e00908a7317f5185ceb25dd5befb54007104e53/client/task-list/tasks/payments/methods.js#L328).

**To Reproduce**

1. Use a UK address during the onboarding wizard ( OBW )
2. After completing the OBW, click on the Setup Payments task in the checklist
3. Note that Klarna is not shown:
![image](https://user-images.githubusercontent.com/22080/108137304-78c8b680-7070-11eb-8e63-55f444ec93e1.png)

**Expected behavior**
Expected Klarna to be shown for UK addresses

**Comment by timmyc** [comment]
Should be a quick fix, estimate 1

**Comment by samueljseay** [comment]
@timmyc I already fixed this recently: https://github.com/woocommerce/woocommerce-admin/blob/aa96a3b3b75723cb14c813172336740dd7c2faf3/client/task-list/tasks/payments/methods.js#L199
