### ISSUE TITLE
Task List: Recommended Payment Banner missing in Safari 

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6351]
**Describe the bug**
Originally reported in pbIJXs-ub-p2 - when viewing the Payment Task on the Setup Checklist in Safari 14.0.2 - the recommended banner does not appear correctly:

![image](https://user-images.githubusercontent.com/22080/108138168-40c27300-7072-11eb-8b83-c07acfdb79ec.png)

I confirmed this on a fresh install of Woo 5.0 on JN

**Comment by hsingyuc** [comment]
I can fix it 🔨
