### ISSUE TITLE
Onboarding: Allow Steps to be filtered

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6352]
We have encountered challenges when working on customizing the onboarding flow for the eCommerce Plan on WordPress.com. I'm thinking it might be nice if we added in a filter to the `getSteps()` [method](https://github.com/woocommerce/woocommerce-admin/blob/main/client/profile-wizard/index.js#L109-L173) which is what derives the array of steps in the onboarding flow.

At the very least, this would allow for us to remove some steps, like themes for example, or even add in new steps as we see fit.

**Comment by psealock** [comment]
Estimate: 1

Adding a filter is simple enough, but what about the corresponding change on the Bridge 🤔 ??

OMG @joelclimbsthings 🎉 Here is the elusive motivation for including a proper front end environment in The Bridge! With that in place, changes in both repo can be done in one day.
