### ISSUE TITLE
Add product email notification - improve Tracks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6359]
The event tracking that was implemented is not working properly:

- There's a mismatch between the user id of each event, so when you create a funnel the conv. rate is always 0. More info here: p4qSXL-3LI-p2. The events are:
`wcadmin_wcadmin_email_note_sent`
`wcadmin_wcadmin_email_note_opened`
`wcadmin_wcadmin_inbox_action_click`- `action name` : `wc-admin-add-first-product-note`
- Also the `wcadmin_wcadmin_email_note_opened` seems to have some issues:
We have more `wcadmin_wcadmin_email_note_opened` than `wcadmin_wcadmin_email_note_sent` and the number of event `uniques` and `counts` look the same. Usually we should have more `counts`.

Here's the FG definition: 
Uniques – the number of distinct users associated with an event has been recorded in a timeframe
Counts – the number of times an event has been recorded in a timeframe

**Comment by octaedro** [comment]
Estimate: 1-2 
(probably one day but as it's not easy to test and something unexpected could appear, I added an extra day)

To get the user identity to record we're using the method `get_identity` in [WC_Tracks::record_event](https://github.com/woocommerce/woocommerce/blob/master/includes/tracks/class-wc-tracks.php#L98), and it uses the `$current_user` to get it.
A possible approach to solve this issue could be adding the current `user id` in the tracking and action URLs in the emails that we send and [set](https://developer.wordpress.org/reference/functions/wp_set_current_user/) the current user [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Notes.php#L478). After that, we can record the event and `unset` the user later.
Same [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/MerchantEmailNotifications/MerchantEmailNotifications.php#L85) and [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/MerchantEmailNotifications/MerchantEmailNotifications.php#L54).

**Comment by psealock** [comment]
Estimate: 2 It does sound simple enough, but agree with @octaedro that some testing could be time consuming.
