### ISSUE TITLE
Add product email notification: narrow down target audience

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6360]
We should narrow down the target audience of this email notification. Currently we're targeting store age: 3 - 30 days

Most likely a user that created a store 2-3 weeks ago without any products has low intent. So sending them an email is mainly going to hurt our open rate and conv. rate. Let's change the audience to store age: 2-5 days. We can widen the target audience in the future based on the results.

**Comment by ilyasfoo** [comment]
Scoper note: Changing this [line](https://github.com/woocommerce/woocommerce-admin/blob/d8af7b1310fc6a7bdef2bd5907e0e2188e0b01d5/src/Notes/AddFirstProduct.php#L33) should work.

Estimate: 1

**Comment by psealock** [comment]
Estimate: 1
