### ISSUE TITLE
Add product email notification: validate email

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6361]
We should test the email with mail-tester.com, as it will give us an indication of what spam filters think about the email and confirm if we're not missing anything important.

**Comment by psealock** [comment]
Estimate: 2

Validation seem simple enough to set up, but this will most likely take a few iterations

**Comment by joelclimbsthings** [comment]
Going ahead and closing this issue, as it's stale and seems to be of fairly low value.
