### ISSUE TITLE
Add product email notification: improve content

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6363]
We need to make some changes in the email content, as a way to decrease the likelihood of being marked as spam and increase the chances of having a good open rate and CTR:

- Subject: we need to be more specific in the subject. We should mention the goal of the email (add your first product) and ideally personalize the content with the store's name.
- Title: the title is too generic. We should be more specific here as well. Eg: Add your first product
- Content: we should try to personalize the email content with the store's name and inform users that they can disable this type of email notifications in the settings.

**Comment by pmcpinto** [comment]
cc @elizaan36 in case you have more ideas. Let's talk about this in our next call. Thanks

**Comment by psealock** [comment]
Estimate: 1

This should be simple enough once the copy is nailed down.

**Comment by elizaan36** [comment]
Here's an updated design for the email.
![Addyourfirstproduct](https://user-images.githubusercontent.com/5121465/109219794-b5399800-777d-11eb-83d0-e6c28e7c7c37.png)

Using the same illustration we're using in [#29174](https://github.com/woocommerce/woocommerce/pull/29174)

**Headline: Add your first product**

**Body:** 
Hi {{Admin first name}},

Nice one, you’ve created a WooCommerce store! Now it’s time to add your first product and get ready to start selling.

There are three ways to add your products: you can create products manually, import them at once via CSV file, or migrate them from another service. 

Explore our docs for more information, or just get started!

**CTA:** Add a product


And one more option with the headline "Get ready to start selling", which is what we're using on the home screen setup task list.

![getreadytostartselling](https://user-images.githubusercontent.com/5121465/109219993-f8940680-777d-11eb-8b5e-00da358a5e32.png)

**Comment by pmcpinto** [comment]
Thanks Elizabeth.

@octaedro do you know if it's possible to get the admin's 1st name?

**Comment by octaedro** [comment]
Hi @pmcpinto,

> @octaedro do you know if it's possible to get the admin's 1st name?

Yes, we can use the admin's first name with no problem. As that value is not required, maybe we should also think about an alternative in case the name is not available. Maybe when the first name is not set we can use the display_name (or something else).

**Comment by elizaan36** [comment]
display_name would work too!

Another option is to use "there" if the first name or display name doesn't exist. So the salutation would be "Hi there,"

**Comment by pmcpinto** [comment]
@octaedro is it possible to use the email notifications in WC Pay even with the Core setting disabled?

**Comment by octaedro** [comment]
Hi @pmcpinto,

No, it isn't. Now the merchant email notifications are turned off by default. So in order to be able to send email notifications by default we should turn them on in Core.
