### ISSUE TITLE
Database Update Done notices persist

### ISSUE THREAD

**Issue by gpenglase** [woocommerce/woocommerce-admin#6369]
WP5.6/WP5.6.1 installs with the latest Woocommerce Version 5.0.0
But this issue has been around since 3.5 and continues to resurface with every major update. The issue obviously hasn't been resolved.

https://github.com/woocommerce/woocommerce-admin/issues/4114
https://github.com/woocommerce/woocommerce-admin/issues/6211
https://github.com/woocommerce/woocommerce-admin/pull/3497

We've resorted to using Disable WooCommerce Bloat plugin for our WooCommerce clients which resolves this and other issues as well as bloat. Frankly, I think the newer stats/admin modules should be an option that you can disable since very few customers want it, and it just slows things down.

**Comment by joelclimbsthings** [comment]
Thanks for letting us know @gpenglase , and we appreciate the feedback.

It looks like the issue you're referring to has been fixed but won't be included until the `5.1.0` release in March, as per [this recent comment](https://github.com/woocommerce/woocommerce-admin/issues/4114#issuecomment-777874229).
