### ISSUE TITLE
Empty orders in analytics screen

### ISSUE THREAD

**Issue by pablolopezmestre** [woocommerce/woocommerce-admin#6370]
**Describe the bug**
Hi.

We are developing a store with WooCommerce. We have some test products and we have ordered some orders (completed), but the don't appear in Analytics / Orders Screen

However, in local dev I have some test orders from 2020, and those appear. But 2021 order don't.

**Expected behavior**
I expect that all orders appear.

**Screenshots**

<img width="970" alt="Captura de pantalla 2021-02-18 a las 11 51 51" src="https://user-images.githubusercontent.com/22821720/108346671-ea734280-71df-11eb-93a5-0a2904b32877.png">
<img width="938" alt="Captura de pantalla 2021-02-18 a las 11 50 53" src="https://user-images.githubusercontent.com/22821720/108346675-ecd59c80-71df-11eb-9deb-ebe62a786989.png">

**Comment by joelclimbsthings** [comment]
Thanks so much for reporting that, @pablolopezmestre . 

I don't see any clear reason why those orders would not be showing up. I also can't seem to reproduce anything similar on my end. This is my report after doing so, which is correct:

![image](https://user-images.githubusercontent.com/444632/108437872-ff150200-7202-11eb-9d60-0bd26935438f.png)

Can you provide any more information that may help us figure this out?

- Version of Wordpress & WooCommerce
- Any other relevant plugins that you're using
- Any other errors that you see (perhaps in the developer console)
- Anything else you think is relevant

**Comment by pablolopezmestre** [comment]
There is something wrong.
- I put the dev stage database in local env. In local works, but in dev doesn't
- In local stage I have latest version of WordPress and latest (5.0.0) for WooCommerce, and It works ok
- In dev stage We have latest version of WordPress and 4.9.2 for WooCommerce, and doesn´t work (screenshots)
- I have downgrade the WC version in my local t 4.9.2, and it works ok
- I have upgrade WC to 5.0.0 in dev stage
- Same theme and same plugins (versions too) in each environment

In dev doesn't work. We only see 2020 orders

**Comment by pablolopezmestre** [comment]
I found out what was going on. We had several tasks to execute in WooCommerce / Status / Scheduled Actions.

Do you know what could be the cause? Do you know if there is any command in WP-CLI to run them in batch?

Thanks!

**Comment by samueljseay** [comment]
Hi @pablolopezmestre I am not sure of the cause on that one sorry, but you can run batches of scheduled actions with the Action Scheduler wp cli commands: https://actionscheduler.org/wp-cli/

Hope that helps.
