### ISSUE TITLE
'Set up shipping' page does not retrieve values of previously saved shipping details

### ISSUE THREAD

**Issue by rodel-calasagsag** [woocommerce/woocommerce-admin#6387]
**Describe the bug**
In the 'Set up shipping' page, when you enter the shipping cost for US and Rest of the world, and save it, and then return to the 'Set up shipping' page, you would notice that the entire 'Set shipping costs' form is reset to their initial state instead of showing you the previous values you entered.

**Precondition**
1. Jetpack is installed and activated.
2. The selected 'Country/Region' in the Setup Wizard was 'United States - California' or any other US region.

**To Reproduce**

1. Go to 'Home'
4. Click on 'Set up shipping'
5. Type '1.23' in the 'Shipping cost' input box under the 'United States (US)' label.
3. Click the 'Rest of the world' toggle to toggle it on.
4. Type '4.56' in the 'Shipping cost' input box under the 'Rest of the world' label
5. Click on 'Complete task'.
6. Click on 'Set up shipping' again
7. Notice that the first 'Shipping cost' input box still shows '0.00'.
8. Notice that the 'Rest of the world' section is toggled off.
9. Click on the 'Rest of the world' toggle.
10. Notice that the 'Shipping cost' of the input box in the 'Rest of the world' section is also '0.00'.

**Expected behavior**
1. The 'Shipping cost' input box in the US section shows '1.23'.
2. The 'Shipping cost' input box in the 'Rest of the world' section shows '4.56'.
3. The 'Rest of the world' toggle is toggled 'ON'.

**Screenshots**
See screen video here:
https://user-images.githubusercontent.com/4509348/108621584-74d0d600-746e-11eb-8f2c-9b9eeeb3dcb5.mp4

**Desktop:**

* OS: Windows 10 64-bit
* Browser Firefox, Chrome
* Version FF v85.0.2 (64-bit), Chrome Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by timmyc** [comment]
@pmcpinto are you okay with moving forward with my suggested fix above:

> One other solution here is if the Shipping Task is completed, so after step 6 above, we change the target of the setup shipping task to direct users to the Shipping Settings page instead. This is one of those cases where the setup checklist not being the same flow/experience as the settings page is appearing.

**Comment by pmcpinto** [comment]
> @pmcpinto are you okay with moving forward with my suggested fix above:

Yes, it seems to be the best approach.
