### ISSUE TITLE
Chrome shows country code instead of the country's flag in the 'Set shipping costs' section

### ISSUE THREAD

**Issue by rodelgc** [woocommerce/woocommerce-admin#6388]
**Describe the bug**
When you view the 'Set shipping costs' section in Firefox, you would see the image of the country's flag to the left of the country name. But in Chrome, you would instead see the country code.

**Precondition**
User had already completed the Setup Wizard.

**To Reproduce**

1. Launch Firefox
2. Login to WordPress Admin
3. Go to 'WooCommerce > Home'
2. Click on 'Set up shipping'
3. In the 'Set shipping costs' section, notice that you can see an image of the flag of the country where your store belongs.
4. Launch Chrome.
5. Login to WordPress Admin.
6. Navigate to 'WooCommerce > Home'
7. Click on 'Set up shipping'
8. Notice that instead of a flag, you see the country code.

**Expected behavior**
Image of the flag should be shown on Chrome to make it consistent with other browsers.

**Screenshots**
<img width="1660" alt="chrome - US text shown instead of flag" src="https://user-images.githubusercontent.com/4509348/108621981-fde90c80-7470-11eb-88da-9f786d77d1a3.png">

**Desktop:**

* OS: Windows 10 Pro 64-bit
* Browser: Firefox, Chrome
* Version: FF v85.0.2 (64-bit), Chrome Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by ilyasfoo** [comment]
Thanks for reporting this issue, @rodel-calasagsag!

However, I'm not able to reproduce this with my Chrome version `88.0.4324.192`. As an added note, the US flag shown is an emoji 🇺🇸 using our [Flag component](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/flag/index.js), not an image.

![image](https://user-images.githubusercontent.com/3747241/109942395-1da0f000-7d0f-11eb-8709-05c7c5f678f5.png)

I think this is an OS/browser support issue, and not related to WooCommerce Admin. If you don't mind, I'm going to close it. Please feel free to reopen if you think it's a valid bug!

**Comment by tammullen** [comment]
Just noting I can reproduce this when using Chrome on Windows devices.

**Comment by adrianduffell** [comment]
A possible solution to this is re-enabling `print_emoji_detection_script ` [here](https://github.com/woocommerce/woocommerce-admin/blob/6468742c6e1df872ad99e907dfbe67473d52e2b1/src/Loader.php#L99-L103).

This was previously disabled in woocommerce/woocommerce-admin#1384:

> If a browser/OS doesn't support emojis, Core replaces them with an image using Twitter's Twemoji. It turns out, this functionality's check to see if emojis are supported always returns false for modern browsers.

> Gutenberg has disabled this feature in WordPress/gutenberg#6151 for separate reasons, but I feel ok doing the same until Core can update to allow modern browsers to keep emojis.

It would be good to check if this is resolved in Core now.

**Comment by ilyasfoo** [comment]
Thanks for taking a look, @adrianduffell! It seems the ticket for tracking the emoji in Gutenberg is still open https://github.com/WordPress/gutenberg/issues/7440, I think this issue isn't resolved yet.

**Comment by rodelgc** [comment]
Thank you very much for investigating this @ilyasfoo @adrianduffell. I just would like to ask if, once https://github.com/WordPress/gutenberg/issues/7440 is fixed, will there be any change needed on either the WC Admin or WC Core part for this issue to be resolved?

I'm asking because it has recently been re-discovered during GlobalStep testing. Internal link to conversation here: p1645527635496379-slack-C011ENB20Q1

**Comment by ilyasfoo** [comment]
@rodelgc As I understand it, the fix will not require any change in WCA or Core. A deployed fix in Gutenberg should immediately work on affected sites.

**Comment by rodelgc** [comment]
Thanks @ilyasfoo for clarifying! Will leave this issue closed then.
