### ISSUE TITLE
Close icon in help menu is cropped

### ISSUE THREAD

**Issue by rodel-calasagsag** [woocommerce/woocommerce-admin#6392]
**Describe the bug**
In mobile portrait view, when you open the Help menu, you would see a cropped "X" icon.

**To Reproduce**

1. Using a mobile device in portrait view, go to 'Home'
2. Click on the WooCommerce logo at the top-right area of the screen to open the Help menu
3. Notice that you would see a cropped "X" icon

**Expected behavior**
The "X" icon should be displayed completely

**Screenshots**
<img width="648" alt="close icon in help menu is cropped" src="https://user-images.githubusercontent.com/4509348/108623263-01809180-7479-11eb-8744-2992dc41eba9.png">

https://user-images.githubusercontent.com/2098816/112167803-20cd2480-8bc7-11eb-8690-7eea680c151a.mov

**Smartphone:**

* Device: Samsung Galaxy Note9
* OS: Android v10
* Browser: Firefox
* Version: 85.1.3

**Comment by ilyasfoo** [comment]
I wasn't able to reproduce this. I've tested Firefox and Chrome on Android and Mac. I've tested on WC 5.0 and WCA 2.1.0.

![image](https://user-images.githubusercontent.com/3747241/110074624-7c707300-7dbc-11eb-81a0-d2eec4c66988.png)

Can you confirm your WCA version please @rodel-calasagsag?

**Comment by mattsherman** [comment]
I am able to reproduce this with WooCommerce 5.1.0. I've updated the original issue description to include a video of the issue.

**Comment by mattsherman** [comment]
@elizaan36 @pmcpinto Is there a reason why we put the Help button inside of this WooCommerce icon menu? It seems like there would just be room to display the Help icon right in the header.

**Comment by elizaan36** [comment]
hey Matt, this was fixed in [#6539](https://github.com/woocommerce/woocommerce-admin/pull/6539)

**Comment by mattsherman** [comment]
@elizaan36 Ha, perfect... glad to see that!

Closing, as this was fixed by #6539
