### ISSUE TITLE
In mobile view, the description of each payment option is pushed all the way to the left

### ISSUE THREAD

**Issue by rodel-calasagsag** [woocommerce/woocommerce-admin#6393]
**Describe the bug**
When you view the payment options in the 'Set up payments' page in mobile portrait view, you would notice that all the text descriptions are pushed all the way to the left of the screen, looking like they have 0px left margin or padding.

**To Reproduce**

1. Using a mobile device in portrait mode, go to 'Home'
2. Click on 'Set up payments'
3. Notice that all the text descriptions are pushed to the left, already touching the left edge of the screen.

**Expected behavior**
The descriptions should have a comfortable left margin or padding.

**Screenshots**
![mobile - payment option contents have no left margin or padding](https://user-images.githubusercontent.com/4509348/108623409-ebbf9c00-7479-11eb-991c-6985a4940401.jpg)

**Smartphone:**

* Device: Samsung Galaxy Note9
* OS: Android v10
* Browser: Firefox
* Version: 85.1.3

**Comment by hsingyuc** [comment]
I'll fix this one.
