### ISSUE TITLE
Letters "p" and "g" in 'Shipping cost' are cropped

### ISSUE THREAD

**Issue by rodel-calasagsag** [woocommerce/woocommerce-admin#6394]
**Describe the bug**
In the 'Shipping cost' input box, notice that the letters "p" and "g" are cropped.

**To Reproduce**

1. Go to 'Home'
2. Click on 'Set up shipping'
3. Notice that the letters "p" and "g" in the "Shipping cost" text inside the input box are cropped

**Expected behavior**
The letters "p" and "g" in the "Shipping cost" text inside the input box should be shown completely.

**Screenshots**
<img width="784" alt="p and g bottom cropped" src="https://user-images.githubusercontent.com/4509348/108623598-bc5d5f00-747a-11eb-8732-85449d5b9b6a.png">

**Desktop:**

* OS: Windows 10 Pro 64-bit
* Browser: Firefox, Chrome
* Version: FF v85.0.2 (64-bit), Chrome Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by hsingyuc** [comment]
I'll fix this one
