### ISSUE TITLE
Navigation: Menu Title overlapped with latest Gutenberg

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6395]
Depending on the height of the Navigation, section titles may become overlapped with elements below it.

<img width="241" alt="Screen Shot 2021-02-22 at 10 26 31 AM" src="https://user-images.githubusercontent.com/1922453/108639304-b3ab6e00-74f8-11eb-977a-45ca10d7f06b.png">

## Steps to reproduce

1. Grab the latest Gutenberg (10.0.0 will do) and activate the plugin.
2. With Nav turned on, go to homescreen
2. Resize your browser window to see an overlap occur. You may need to activate some extensions to get the Nav long enough

**Comment by ilyasfoo** [comment]
I'm trying to reproduce on Chrome with latest `main`, but got vertical scroll instead. I've tried to install a couple of extensions but they're not adding any menu item, do you have an example of what extensions that you have?

<img width="301" src="https://user-images.githubusercontent.com/3747241/108652836-09cfdf80-7500-11eb-810f-2af44059e5c0.png">

**Comment by psealock** [comment]
Thanks @ilyasfoo for taking a look. After poking around, it appears to be a Gutenberg issue introduced on the latest development branch. I will update the test instructions, remove this from 2.1 milestone, and update the title.
