### ISSUE TITLE
New message: Inform wcadmin users about the new navigation

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6402]
**Description:** we're going to test trigger an inbox notification targeting wcadmin users with the latest version of the new navigation. Our goal is to collect feedback as soon as possible about the latest improvements. 

**Title:** TBD
**Copy:** TBD
**Segmentation:** users with wcadmin 2.1 installed
**Timing:** once they update wcadmin to the 2.1 version
**Cadence:** Once
**CTA leads to:** wp-admin/admin.php?page=wc-settings&tab=advanced&section=features
**CTA label:** TBD

**Comment by elizaan36** [comment]
Just to confirm, this Inbox notification won't appear for brand new users as the nav will already be enabled, is that correct?

Here's copy for the Inbox notification:

**Title:** **You now have access to the WooCommerce navigation**

**Copy:** We’re introducing a new navigation for a more intuitive and improved user experience. Enable it now for your store.

**CTA:** **Enable | Dismiss**

**Comment by pmcpinto** [comment]
> Just to confirm, this Inbox notification won't appear for brand new users as the nav will already be enabled, is that correct?

Nope. Currently is disabled by default for everyone outside of wpcom eComm plan users. I think that we should give a hint on what's going to happen after they click on the message CTA and that it will be possible to disable it again. Something like: you can enable the beta version of the new experience in the Advanced Settings.

**Comment by elizaan36** [comment]
Sounds good! I'm not sure we need to mention anything about disabling it in the message, but I added the sentence you suggested.💯

Here's updated copy:

**Title:** You now have access to the WooCommerce navigation

**Copy:** We’re introducing a new navigation for a more intuitive and improved user experience. You can enable the beta version of the new experience in the Advanced Settings. Enable it now for your store.

**CTA: Enable | Dismiss**

**Comment by octaedro** [comment]
Estimate: 1
