### ISSUE TITLE
Add feature documentation for the setup task list and store management link extensibility.

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#6416]
@loranallensmith pointed out that we don't have feature docs for information such as 97-gh-woocommerce/woocommerce-developer-advocacy/files/89864f581fbd50803abb367705788111a322d98b#r579372476 which was put together for the developer blog.

This issue is to track the need for some documentation for these features in `docs/features` that would more explicitly outline the required API than the code examples do.

**Comment by ilyasfoo** [comment]
Closing, p90Yrv-2Bc-p2
