### ISSUE TITLE
Hide free features step and paid product types for Ecom plan users

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6429]
When an Ecom plan user comes through the Setup wizard, they already have free extensions installed. Showing the list of free extensions is redundant and could also cause confusion thinking you're _not_ installing them when they're already installed.

This checkbox should be hidden:
<img width="935" alt="Screen Shot 2021-02-23 at 12 02 02 PM" src="https://user-images.githubusercontent.com/5121465/108886763-fa6b9780-75ce-11eb-9558-bb68fde424a7.png">

This should also apply to other versions of the free features step, such as this new one where steps are separated: https://share.getcloudapp.com/Jru1oyWY

Also, when there are no paid product types shown in this step we should hide the price toggle and helper text. This can be a very confusing moment for people, thinking they may need to pay for something.
<img width="754" alt="Screen Shot 2021-02-23 at 12 01 28 PM" src="https://user-images.githubusercontent.com/5121465/108886842-140cdf00-75cf-11eb-9e6b-36e3fb6ef771.png">

cc @pmcpinto @timmyc

**Comment by pmcpinto** [comment]
I going to close this one as we already have an [issue](https://github.com/Automattic/wc-calypso-bridge/issues/652) about this in Calypso Bridge :)
