### ISSUE TITLE
Create default WooCommerce pages for Ecom plan users

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6430]
Ecom plan users currently need to manually turn on default WooCommerce pages. It's an unexpected and technical task for brand new users, and they end up taking a lot of time talking to support to find the setting and configure the pages. The setting is currently in **Tools > Utilities** about halfway down the page.

<img width="2111" alt="Screen Shot 2021-02-23 at 12 15 23 PM" src="https://user-images.githubusercontent.com/5121465/108888825-5800e380-75d1-11eb-9340-17b4efe635e4.png">

I couldn't find the original issue where this was discussed but it's an ongoing pothole that people get stuck in so wanted to create this for discussion. This is automated for all WooCommerce sites except on the Ecom plan - Is there something we can do to make this more automated for Ecom plan users? Ideally it could happen with no effort on their part.

@timmyc @pmcpinto

**Comment by timmyc** [comment]
Thanks for logging this @elizaan36 - we have an issue in `wc-calypso-bridge` tracking this bug, and also have started a p2 conversation about it with Atomic as it only happens on that platform - so going to close this in favor of https://github.com/Automattic/wc-calypso-bridge/issues/637
