### ISSUE TITLE
GlobalStep - WooCommerce Admin 2.1 Beta 1] "Favorite" button is not available when multiple extensions are installed.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6431]
## Bug Description:
"Favorite" button is not available when multiple extensions are installed.

## Environment:
Windows 10, macOS High Sierra v10.13.6
Browser: Chrome(Version 88.0.4324.104) (64-bit)
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins
1. Install and activate WooCommerce Admin 2.1 Beta Plugin.
1. Activate multiple extensions that register WooCommerce extension categories.
1. Observe that "Favorite" button is not available for Extensions.

## Actual Result:
"Favorite" button is not available when multiple extensions are installed.

## Expected Result:
"Favorite" button should be available for Extensions.

## Attachment (Screenshot) :
![#29205](https://user-images.githubusercontent.com/41110392/108883226-303e6980-762b-11eb-92a3-6f7feb2e6b8f.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
Hi @gglobalstep,

I'm not sure if the instructions needed clarification, but only extensions with categories (menu children) will be able to be Favorited. From the screenshot, it looks like the extensions you have do not have child menu items. Automate Woo is an extension that should work.

**Comment by adrianduffell** [comment]
@psealock Perfect, thanks for clarifying. GlobalSteps’s [instructions](https://github.com/woocommerce/woocommerce-admin/blob/main/TESTING-INSTRUCTIONS.md#refactor-menu-item-mapping-and-sorting-6382) were missing the finer detail about it working only for extensions with categories.

I'll close this since the Favorites button appears for Automate Woo.
