### ISSUE TITLE
Orders task - close tab by default

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6449]
**Description:** As it was mentioned in the recap (pbIJXs-Fn-p2), the usage of the inventory and reviews dropped after we move them to the home screen. This can be influenced by the fact that the Orders task is opened by default when a user visits the home screen and eventually he doesn't notice that there are other tasks below orders: https://d.pr/i/JG3Vnz
We want to see if having the orders task closed when the user visits the home screen can increase the visibility of inventory and reviews, without decreasing the orders task usage.

**Acceptance criteria:**

- [ ] The orders tasks should be closed by default when the user visits the home screen: https://d.pr/i/1kUJxM
- [ ] When the user clicks in one of the tabs, trigger the `wcadmin_activity_panel_open` event. The `tab` event prop should include the name of the task that was opened.
- [ ] Add a new event tracking, so we can understand if the user has the tasks enabled:
Name: `wcadmin_home_screen_view`
Props:
`setup`: enabled | disabled (identify if the setup tasks are visible)
`orders`: enabled | disabled (identify if the orders task is visible)
`inventory`: enabled | disabled (identify if the inventory task is visible)
`reviews`: enabled | disabled (identify if the reviews task is visible)

**Comment by ilyasfoo** [comment]
Change default order panel state, add tracks and props.

Estimate: 1

**Comment by octaedro** [comment]
Estimate: 1

To set the `Orders` activity panel as closed by default, we should do it [here](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/panels.js#L34).

**Comment by psealock** [comment]
Seems pretty straightforward, estimate: 1
