### ISSUE TITLE
Fix help panel event value

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6451]
**Description:** in the `wcadmin_help_panel_click` and `wcadmin_help_panel_open` events we have an `undefined` value for the home screen interactions in the `task_name` prop. It would be great to add the correct name (home screen) in order to avoid misunderstandings when the data is used.

**Comment by ilyasfoo** [comment]
Most likely caused by improper prop passing.

Estimate: 1

**Comment by psealock** [comment]
Estimate 1
