### ISSUE TITLE
Remove Mollie notification

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6452]
**Description:** the Mollie notification (#6296) should be removed on March 9, as WC 5.1 includes Mollie as a payment option in the payments setup task.

**Comment by octaedro** [comment]
Estimate: 1

**Comment by ilyasfoo** [comment]
Removing this should be pretty straight forward.

Estimate: 1

**Comment by psealock** [comment]
Estimate: 1
