### ISSUE TITLE
Home Screen Welcome modal's last step description translation string isn't registered

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce-admin#6456]
**Describe the bug**
A Home Screen Welcome modal's last slide description is not registered as a string available for translations, it's always in English.

You can see here, that no __() function is used for this description: https://github.com/woocommerce/woocommerce-admin/blob/ef6aa388c40abffecb512e1af49c915ebe1449a6/client/homescreen/welcome-modal/index.js#L57

**To Reproduce**

1. Switch WP language to non-en.
2. Go to WooCommerce->Home for the first time after lauching the new Home Screen.
3. Look at the last step of the Welcome modal.

**Screenshots**
![Zrzut ekranu 2021-02-26 o 16 08 49](https://user-images.githubusercontent.com/27000783/109317900-80951180-784d-11eb-9334-a5bd0a75bbb6.png)

WP 5.6.2
WC 5.0.0
WC Admin 1.9.0. (bundled with WC)

PS Similar bug has been submitted here: #5392 but the date string are still not fixed.

**Comment by hsingyuc** [comment]
I'll try to fix this one
