### ISSUE TITLE
Use Gutenberg component to preview site in Personalize store task

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6457]
We know that store owners struggle to access the front end of their site during store setup. This has been a common theme in qualitative feedback we've received. In the Personalize your store task, an item in the stepper is to "Create a custom homepage" but it's not clear what's customized or what it even looks like. [People have described this step as "misleading".](https://github.com/woocommerce/woocommerce-admin/issues/4239)

To provide an easier way to check the front end after selecting the "Personalize your store" task, we can either provide a link out to their site building tool or directly to the front end. The challenge with providing a direct connection to a customizer is that we don't know exactly what tool people are using to customize the front end of the site. The challenge with providing a direct link to the front end is that we don't know exactly when the user will want to check the front end during this task - after all the steps, or after each step?

One solution given all of these unknowns is to provide a handy link to preview the front end of a site in a new tab. Given that this exact component exists in Gutenberg, we could benefit by reusing it for this purpose.

A new link to `Preview site` would appear in the top bar of only the Personalize your store step.
<img width="183" alt="image" src="https://user-images.githubusercontent.com/5121465/109324617-87566100-781a-11eb-8549-405bfff09b5f.png">

As the user continues through the task list steps, they can open their site in a new tab and keep checking progress.
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/5121465/109324940-f469f680-781a-11eb-963f-4fb94e259ef5.png">

Component in Gutenberg:
<img width="606" alt="Screen Shot 2021-02-20 at 8 15 00 PM" src="https://user-images.githubusercontent.com/5121465/109324316-1b73f880-781a-11eb-891e-71e017c40ed4.png">

I like this solution because it solves a real known problem _and_ the component exists already.

cc @timmyc @pmcpinto

**Comment by moon0326** [comment]
@elizaan36 Hi ✋ 

Do we temporarily remove the "Display" button in Personalize store task? I see both Help and Display in Personalize store task.

**Comment by elizaan36** [comment]
hey @moon0326 ! 
That's a bug actually. I see it now too on all the task lists, but the Display button should only appear on the home screen.

**Comment by moon0326** [comment]
> hey @moon0326 !
> That's a bug actually. I see it now too on all the task lists, but the Display button should only appear on the home screen.

Thank you for checking 👍 

One more thing I noticed is that changing the device type (Desktop, Tablet, and Mobile) only changes how the post looks on the Add Post / Edit Post page. When you click "Preview in new tab", it always takes you to `http://your-site/?p=:post-id&preview=true` regardless of your device type selection. Do we need device selection at all in this case?

**Comment by elizaan36** [comment]
Gotcha that makes sense actually. And that would simplify things. Let's remove the dropdown and add the button with `Preview`. Would clicking the Preview button open the shop homepage in a new tab?

**Comment by moon0326** [comment]
> Gotcha that makes sense actually. And that would simplify things. Let's remove the dropdown and add the button with `Preview`. Would clicking the Preview button open the shop homepage in a new tab?

Nice! Yup, it gets much simpler. Yeah, it should open a new tab 👍
