### ISSUE TITLE
Remove "W" icon in top bar on mobile

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6458]
On mobile devices, the "W" Woo logo is still showing as a link to open the activity panel. However, since we've removed all items in the activity panel and have no plans to reintroduce them, we should remove this extra click and user experience hurdle. 

### **Existing experience**

Two clicks to open help on the home screen:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/5121465/109330422-401f9e80-7821-11eb-8d46-12e1352b9f53.png">

Two clicks to open Inbox on other screens:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/5121465/109330281-1ebeb280-7821-11eb-82a8-299e71917179.png">

There's a significant amount of unused space that blocks users from accessing the important content on the screen in smaller viewports.

### **Solution**

One click to open help on home screen and task lists:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/5121465/109332303-85dd6680-7823-11eb-8d09-22a18e184e89.png">

On the home screen and task lists, only the Help icon is displayed on mobile. I'd propose using only the icon with no text label. Tapping this icon will open the help drawer with no additional step in between.

One click to open Inbox on all other screens:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/5121465/109332365-9d1c5400-7823-11eb-98bc-e8d070a97721.png">

On all other screens, only the Inbox link is displayed on mobile. 

Even if we included another link here (in case we made the Help menu global) there would be plenty of room in the top bar on mobile. There's no need for the extra work to open a new panel.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/5121465/109332401-ab6a7000-7823-11eb-9373-5ed3837adfc6.png">

cc @pmcpinto @timmyc

**Comment by psealock** [comment]
Estimate: 2

Its probably 1, but there's been lots of refactors in this space recently, and there may be more lurking behind this issue too.
