### ISSUE TITLE
Transition store alert notices to WP notice component

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6461]
After conversation in p9o2xV-1fS we're exploring some solutions for presenting high priority notices to users in WooCommerce. For reference, here's the design exploration to bring these into the task list: pbIJXs-Gg

In the interim, we can transition this extra large notice style to the new more compact WP core notice.

From this:
<img width="827" alt="Screen Shot 2021-02-26 at 11 34 12 AM" src="https://user-images.githubusercontent.com/5121465/109335930-51b87480-7828-11eb-90ae-9ee97e51fc16.png">

To this:
![Frame 2060](https://user-images.githubusercontent.com/5121465/109335946-5715bf00-7828-11eb-813b-68893334d96b.png)

cc @timmyc to add any details I've missed. FYI, this is the latest notice style in the WordPress design library, however I'm not sure what the status is on transitioning the legacy notice style over.

**Comment by timmyc** [comment]
@elizaan36 should these notices on the home screen be constrained to the horizontal width of the column(s) being shown? That was one piece of feedback in the original thread was how it took up a larger width then the home screen columns

**Comment by elizaan36** [comment]
The notice should be constrained based on the page body area to the right of the nav, not depending on the column width.

FYI I'm talking to the Gutenberg designers about this notice style and color contrast. Looks like the blue links are failing big time on color accessibility so I need to figure what will work better for us. I'm wondering if it might be better to tweak the CSS of the existing notice as you suggested in Slack. Will have a look!👀

**Comment by elizaan36** [comment]
I'll reiterate our Slack convo here for visibility. I'm going to focus on the task list solution for now as CSS tweaks (or even switching over to a new component) will likely not make enough of a difference to solve the problem.
