### ISSUE TITLE
Payment Task: Inform Users of Live Mode for PayPal

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6465]
This is a follow-up to an issue logged by Global Step during the 5.1 testing cycle: https://github.com/woocommerce/woocommerce-admin/issues/6385

The PayPal integration added in 2.0 prompts users with the following dialog in the setup checklist task:

![image](https://user-images.githubusercontent.com/22080/109366274-dc5c9c00-7847-11eb-8360-6c367254ad35.png)

The testers ended up entering in Sandbox credentials into this UI, and assumed things were configured and ready to test a front-end transaction in sandbox mode. But the setup task configures the PayPal gateway to be in LIVE mode via this form.

I think we should add a little bit of copy to this UI to explicitly state this form is for LIVE credentials only, and if a user wants to enter Sandbox credentials, direct them to the payment settings page. Alternatively, maybe we could add a toggle to the form that would allow either configuring in live _or_ test mode.

The copy change seems like it could be a quick win, so possibly we could try and put it into the next cycle. @louwie17 any thoughts on the other route of making the form usable in live or sandbox mode?

Other thing to consider here is I believe the long term plan was to create a more seamless flow for the connection so perhaps we take the easiest path right now and add text.

**Comment by ilyasfoo** [comment]
I believe this is no longer relevant, closing.
