### ISSUE TITLE
Payments Task: Showing Payment Options as Configured when they are not

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6466]
This is a follow-up issue from feedback received during the 5.1 test cycle.

Context and background: https://github.com/woocommerce/woocommerce-admin/issues/6384

Summary:
On payment gateways in the setup checklist where we are installing and activating the plugin, **but not configuring required settings** we still show the payment method as active in the payments task:

![image](https://user-images.githubusercontent.com/22080/109366627-c13e5c00-7848-11eb-88c4-f4656ae6eab7.png)

When in fact they are not fully active and available in the checkout flow until client keys are properly configured.

Wondering if we should introduce a design pattern for these scenarios since a number of our payment gateways are setup in this way ( install + activate the plugin only, and not configure ).

cc @pmcpinto @elizaan36

**Comment by pmcpinto** [comment]
I think the easiest way is to add a new paragraph in the Payment's description: Finish the [name of the gateway] configuration in the Settings (link to the gateway settings).

**Comment by elizaan36** [comment]
I agree with Pedro's suggestion here. After thinking through the flow, we'd run into a problem routing users deep into payment gateway settings then trying to re-route them back to the task list to complete the flow. Since we can't have control over how the gateway is configured, I think it's better to give people the link here to explore independently.

**Comment by elizaan36** [comment]
So the flow would look like this:

Mollie listing in the payments task list:
![Frame 2062](https://user-images.githubusercontent.com/5121465/109843998-4e9afb00-7c11-11eb-9543-ac17b0d67886.png)


I can create a new issue for this, but we'd like to move away from the toggle pattern for the payments task list. (would need to update Cash on delivery and probably others)

Choosing Set up from here will install the gateway, then a link appears to complete setup in Settings.
![Frame 2063](https://user-images.githubusercontent.com/5121465/109844027-55297280-7c11-11eb-8b5e-5b239ecaaebe.png)


Once that's complete, an `Enabled` indication appears next to the gateway name.
![Frame 2064](https://user-images.githubusercontent.com/5121465/109844047-59559000-7c11-11eb-9fd8-32f4e8203bf3.png)


@timmyc is that along the lines of what you were thinking?

**Comment by timmyc** [comment]
I really like the that @elizaan36 - I think it captures all possible states nicely. We may encounter some issues with detecting the middle state as payment methods are kind of unique in their implementation... but I suppose if the plugin is installed and activated, _but_ the payment method it provides is not enabled is how we could sniff this out.

My only concern is some plugins might allow for their method to be enabled even when setup has not been completed yet. I don't think there is a universal API in the payment method area that developers can signal if their method is fully configured and ready to roll. So this is something we might want to look into first.

**Comment by elizaan36** [comment]
Would be good to detect that middle step to present the link. Otherwise it would be confusing to see the gateway is enabled in addition to the link to finish setting up. I'll think about other solutions too and let me know what you find out!
