### ISSUE TITLE
Analyitcs report chart and table exclude 29th February for last month preset

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#6471]
**Describe the bug**
This is a follow-up to https://github.com/woocommerce/woocommerce-admin/pull/6470. Report charts and table do not include previous year's period because the primary period is used to map out the data.

**To Reproduce**

1. We need to be in March 2021
2. Have an order completed on 29th February 2020
3. Open Analytics > Revenue
4. In date range, select "Last Month" preset and compare to "Previous Year"
5. Observe that 29th February sales are excluded

**Screenshot**
![image](https://user-images.githubusercontent.com/3747241/109470613-a3703180-7aaa-11eb-9358-fe59a96fc048.png)
![image](https://user-images.githubusercontent.com/3747241/109471153-52147200-7aab-11eb-8b00-509a04353bc3.png)

**Expected behavior**
With "Last Month" preset on Feb 2021, we would expect the comparison would compare with the whole month of the previous period (i.e: **1 - 28th 2021** vs **1 - 29th 2020**).

**Comment by hsingyuc** [comment]
I have a fix for this; pushing shortly.
