### ISSUE TITLE
Store profiler: business details steps changes

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6480]
**Description:** we need to make some changes in the [business details step original flow](https://d.pr/i/1kO2wB), in order to include Mailpoet.

**Acceptance Criteria:**
- [ ] Include Mailpoet in the list:
Title: Email Marketing by WooCommerce
Description: The default all-in-one solution for WooCommerce email. Powered by MailPoet.
Logo: [Mailpoet logo](https://href.li/?https://www.mailpoet.com/wp-content/themes/theme-2018/assets/icons/logo.svg) 
Link do download extension: https://wordpress.org/plugins/mailpoet/
- [ ] Display extensions in the following order:
Mailpoet
Facebook
Google Ads
Mailchimp
Creative Mail
- [ ] The Creative Mail option should be toggled off by default

**Comment by pmcpinto** [comment]
@elizaan36 do you think that we should use the MP logo or ours?

**Comment by elizaan36** [comment]
The Mailpoet logo would make it a lot more clear what you're actually installing.☺️

**Comment by octaedro** [comment]
Hi @elizaan36,

> The Mailpoet logo would make it a lot more clear what you're actually installing.

I like the idea! I'm working on this issue and I wanted to ask you if you could give me a nice MailPoet logo that I could use here.
Thanks 🙂

**Comment by octaedro** [comment]
Hi @pmcpinto,

> we need to make some changes in the business details step original flow, in order to include Mailpoet.

Just to confirm, this change only will apply to the original flow
![screenshot-one wordpress test-2021 03 03-12_04_11](https://user-images.githubusercontent.com/1314156/109825509-a6893000-7c18-11eb-949d-b37c1a6cb6b4.png)



not this
![screenshot-one wordpress test-2021 03 03-11_55_53](https://user-images.githubusercontent.com/1314156/109824651-c8ce7e00-7c17-11eb-835f-c3d5ea93fa7b.png)


Is that correct?

**Comment by elizaan36** [comment]
[This folder](https://share.getcloudapp.com/rRukBKZQ) was provided by Tautvidas in the p2 thread.

I'd use the full Mailpoet logo rather than the symbol for consistency with the other logos in the list.

**Comment by pmcpinto** [comment]
> I'd use the full Mailpoet logo rather than the symbol for consistency with the other logos in the list.

Sounds good to me. 

> Just to confirm, this change only will apply to the original flow:

@octaedro it should be implemented in the original flow and on this one: #6489

We're going to remove the one that you mentioned.

**Comment by octaedro** [comment]
Thanks @elizaan36,

> This folder was provided by Tautvidas in the p2 thread.
> I'd use the full Mailpoet logo rather than the symbol for consistency with the other logos in the list.

I'm seeing the image that we should use [in the `.zip`](https://share.getcloudapp.com/rRukBKZQ) doesn't have the size or the proportions (200x55) we need. Would you be able to size these for me? I don't have an image editing program on my laptop.
Thank you 🙂

**Comment by elizaan36** [comment]
No problem. How does [this PNG](https://share.getcloudapp.com/mXu1zkP9) look?

**Comment by octaedro** [comment]
That image works great! Thanks @elizaan36
