### ISSUE TITLE
Payments task: include Square in Ireland [IE] (target: WC 5.3)

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6481]
**Description:** we're going to start including Square in more countries and the first one will be Ireland in WooCommerce 5.3 (code freeze: April 15)

**Acceptance criteria:**

- [ ] Display Square as an option in the payments task if the user selected Ireland (IE) as the country in the Store Details step and if he selected one of the following options in the Business details step - Currently selling elsewhere?
Yes, in person at physical stores and/or events
Yes, on another platform and in person at physical stores and/or events

**Comment by pmcpinto** [comment]
@timmyc I included this issue in this cycle, as I'm assuming that wcadmin 2.2 is going to be the version released in 5.3

**Comment by pmcpinto** [comment]
@ilyasfoo I'm reopening this issue as the Stripe launch in Ireland is only going to happen after the 5.3 release, so we should only include it in 5.4.

**Comment by ilyasfoo** [comment]
Noted @pmcpinto, I'll revert the changes

**Comment by pmcpinto** [comment]
> @ilyasfoo I'm reopening this issue as the Square launch in Ireland is only going to happen after the 5.3 release, so we should only include it in 5.4.

@ilyasfoo I'd like to confirm that this was shipped in 5.4. Thanks!

**Comment by ilyasfoo** [comment]
@pmcpinto Yes, I confirm it was shipped in 5.4. Just FYI, I've also checked that the rule is now in remote payment settings.
