### ISSUE TITLE
Business features step: fix JP flow

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6488]
**Description:** the experiment implemented in #5287 showed positive results. Recap here: pbIJXs-GS-p2. We need to fix a bug as we're not redirecting users to the Jetpack log in/account creation flow as expected in this flow

**Acceptance criteria:**
- [ ] If the user installs Jetpack ~~and WooCommerce Shipping & Tax~~, he should be redirected to the Jetpack sign up/log in flow at the end of the profiler. As we have now with the original flow

**Comment by samueljseay** [comment]
Our existing logic says both wc-services *and* jetpack must be installed to go to connection flow so I'm just adjusting the acceptance criteria to:
`If the user installs Jetpack and WooCommerce Shipping & Tax, ` (minus the "or")

**Comment by pmcpinto** [comment]
@samueljseay perhaps this logic is influenced by the fact that in the original flow we display JP and WCST together: https://d.pr/i/MWy3h4 🤔 

But in the flow where we include JP and WCST in the free extensions tab, users can just install one of them. So I think it would be better to change the AC to just `If the user installs Jetpack`. Makes sense?

**Comment by samueljseay** [comment]
@pmcpinto sounds good. I assumed it was some kind of technical limitation that we needed both. I'll make it just contingent on installing Jetpack

**Comment by pmcpinto** [comment]
>  I assumed it was some kind of technical limitation that we needed both. I'll make it just contingent on installing Jetpack

WooCommerce Shipping & Tax needs JP to work but in the [new UI](https://d.pr/i/VDXfAI) it was tricky to bundle them without confusing people. And once users install Shipping & Tax they'll see references about the need to install JP.
