### ISSUE TITLE
Business features step: improve WC Shipping & Tax logic

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6490]
**Description:** the experiment implemented in #5287 showed positive results. Recap here: pbIJXs-GS-p2. It will be necessary to improve the WC Shipping & Tax logic so we only target users that can get value from the extension.

**Acceptance Criteria:**
- [ ] Exclude the WooCommerce Shipping mention if the user is not in the US
- [ ] Exclude the WooCommerce Shipping mention if the user is the US but only selected digital products in the Product Types step
- [ ] Include WooCommerce Tax if the user is in one of the following countries: US | FR | GB | DE | CA | PL | AU | GR | BE | PT | DK | SE
- [ ] The WooCommerce Tax copy should be the following: Get automated sales tax with [WooCommerce Tax](https://woocommerce.com/products/tax/)

**Comment by moon0326** [comment]
Hey @pmcpinto,

I have questions.

1. I think the first and the third criteria conflict with each other.  Since both WooCommerce Shipping & Tax are included in the single plugin, users have to install WooCommerce Shipping if they want to include WooCommerce Tax (and vice versa). If we include WooCommerce Tax for US | FR | GB | DE | CA | PL | AU | GR | BE | PT | DK | SE countries, then the first criteria can't be done.

2. For the last criteria, where do we display the copy?

Thanks!

**Comment by pmcpinto** [comment]
> I think the first and the third criteria conflict with each other. Since both WooCommerce Shipping & Tax are included in the single plugin, users have to install WooCommerce Shipping if they want to include WooCommerce Tax (and vice versa). If we include WooCommerce Tax for US | FR | GB | DE | CA | PL | AU | GR | BE | PT | DK | SE countries, then the first criteria can't be done.

The goal with the 1st criteria is to only remove the copy `
Print shipping labels with WooCommerce Shipping`, in order to avoid creating the false expectation that they'll be able to print shipping labels. Makes sense?

> For the last criteria, where do we display the copy?

We can display it before the Jetpack copy

**Comment by moon0326** [comment]
> > I think the first and the third criteria conflict with each other. Since both WooCommerce Shipping & Tax are included in the single plugin, users have to install WooCommerce Shipping if they want to include WooCommerce Tax (and vice versa). If we include WooCommerce Tax for US | FR | GB | DE | CA | PL | AU | GR | BE | PT | DK | SE countries, then the first criteria can't be done.
> 
> The goal with the 1st criteria is to only remove the copy ` Print shipping labels with WooCommerce Shipping`, in order to avoid creating the false expectation that they'll be able to print shipping labels. Makes sense?
> 
> > For the last criteria, where do we display the copy?
> 
> We can display it before the Jetpack copy

Ah! That makes sense. Thank you for the clarification 👍

**Comment by moon0326** [comment]
Hi @pmcpinto ✋ 

I opened a PR for this issue but then realized that I should double confirm what "digital products" are referring to exactly.

I see the following product types from the Product Types step in OBW

Physical products, Downloads, Subscriptions, Memberships, Booking, Bundles, Customizable products.

Are we referring to "Downloads" by "digital products"?

Thanks!

**Comment by pmcpinto** [comment]
> Are we referring to "Downloads" by "digital products"?

@moon0326 yes. Sorry if the AC wasn't 100% clear.
