### ISSUE TITLE
Items sold summary number appears twice on the analytics overview screen

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#6502]
**Describe the bug**
The items sold summary number appears twice on the analytics overview, and each can be disabled using the menu. 

**To Reproduce**

1. View the overview screen for analytics
2. Note that "Items sold" appears twice. 

**Screenshots**
<img width="422" alt="Screen Shot 2021-03-03 at 8 36 24 AM" src="https://user-images.githubusercontent.com/4500952/109839388-e857ad80-7bfb-11eb-83f8-03922bf544bb.png">

**Comment by chihsuan** [comment]
I believe this has been fixed. 

I tried to reproduce and found two "Items sold" have been changed to "Products sold" and "Variations Sold".

![Screen Shot 2022-01-12 at 15 38 52](https://user-images.githubusercontent.com/4344253/149084207-90e95f9d-f569-4fb9-b883-08605dabb643.png)

I'm going to close this. Please reopen if you're still facing the issue. Thanks!
