### ISSUE TITLE
Notes: Filter notice type

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6511]
Follow up to https://github.com/Automattic/wc-calypso-bridge/pull/656

Add a filter to notice types so that a certain type can be added or removed.

The presence of notices is derived in PHP

https://github.com/woocommerce/woocommerce-admin/blob/ec8471dcadc2a91f1e972c84c2d6970e5c84900a/src/Features/ActivityPanels.php#L65

and the request is made in on the client.

https://github.com/woocommerce/woocommerce-admin/blob/ec8471dcadc2a91f1e972c84c2d6970e5c84900a/client/layout/store-alerts/index.js#L283-L288

The filter could be made in PHP and the result passed to client.

**Comment by timmyc** [comment]
Thanks for creating this issue @psealock - I think this will still be a valid feature once we implement the unified task feature that Elizabeth is exploring right now. One other possible solution is to add a filter in Woo Core for the db update messages specifically.
