### ISSUE TITLE
WooCommerce Admin Add Task Example includes unnecessary code

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce-admin#6522]
**Describe the bug**
The WooCommerce Admin Add Task Example includes [a deactivation hook](https://github.com/woocommerce/woocommerce-admin/blob/main/docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php#L57-L62) that simply calls `remove_filter`. As far as I can tell that's unneeded since it the code is deactivated, the filter won't be added anyway.  

**Expected behavior**
Example only includes necessary code.

**Comment by samueljseay** [comment]
@octaedro Could you take a look at this one?
