### ISSUE TITLE
Can’t disable Setup Wizard

### ISSUE THREAD

**Issue by onsterion** [woocommerce/woocommerce-admin#6533]
Hello everyone,

WP version: 5.6.2
WOO Version: 4.9.2

I can’t disable the Setup Wizard and I can’t track where it triggers, it’s supposed to trigger on:

\wp-content\plugins\woocommerce\packages\woocommerce-admin\src\Features\Onboarding.php line 158

But it never got to this line debugging the code.

My code:

```
// Disable Setup Wizard
function KsMWcExtenderAdminFilterWoocommerceEnableSetupWizard($true)
{
   return false;
};
add_filter('woocommerce_enable_setup_wizard', 'KsMWcExtenderAdminFilterWoocommerceEnableSetupWizard', 20, 1);

function KsMWcExtenderAdminFilterWoocommercePreventAutomaticWizardRedirect($false)
{
   return true;
}
add_filter('woocommerce_prevent_automatic_wizard_redirect', 'KsMWcExtenderAdminFilterWoocommercePreventAutomaticWizardRedirect', 20, 1);
```

Any suggestion?

Regards,
Lucas

**Comment by psealock** [comment]
Thanks for the question @onsterion 

To disable the Setup Wizard, you'll want this line to evaluate to `false`

https://github.com/woocommerce/woocommerce-admin/blob/c44f7ce3dc9512759fd3763406ad74df7eb78ea6/src/Features/Onboarding.php#L142

try  getting `KsMWcExtenderAdminFilterWoocommercePreventAutomaticWizardRedirect` to `return false;`

I'll close this issue, but if that doesn't fix the problem feel free to reopen.
