### ISSUE TITLE
Downloads: Emailed Customer names missing on Orders Report

### ISSUE THREAD

**Issue by johnbalili** [woocommerce/woocommerce-admin#6534]
Customer names were missing on analytics order report when the date range is big like a year.
sample of 1 month report
[orders_2021-03-05_page-wc-admin_path--analytics-orders.xlsx](https://github.com/woocommerce/woocommerce/files/6088533/orders_2021-03-05_page-wc-admin_path--analytics-orders.xlsx)

and sample of 1 year report
[wc-orders-report-export-16149203382307.xlsx](https://github.com/woocommerce/woocommerce/files/6088538/wc-orders-report-export-16149203382307.xlsx)

**Comment by hsingyuc** [comment]
I'll try to fix this one
