### ISSUE TITLE
In Analytics and Reports, the payment revenue is assigned to the date when an order is created rather than the date when a payment was made.

### ISSUE THREAD

**Issue by grig-23** [woocommerce/woocommerce-admin#6535]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
In Analytics and Reports, the payment revenue is assigned to the date when an order is created rather than the date when a payment was made.

**Expected behavior**
If an order is created on January 1st but it is only paid for on February 1st - I'd expect the reports to show the revenue on February 1st.
**Actual behavior**
Whenever the payment is made, reports will show it as if it happened on the same day as when the order was created.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Place an order but don't yet pay for it, e.g. via PayPal Standard.
2. Wait a day or two and then actually pay for an order.
3. Head t Reports and Analytics, check when the reports show the revenue.

**Screenshots**
![Screenshot](https://d.pr/i/ZoVOVZ+)
Screenshot direct link: https://d.pr/i/ZoVOVZ

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tivnet** [comment]
@tammullen Hi Tam, the issue might not be in the admin. If you look at the order edit, you will see that the invoice date and payment date are different. In report (old, new, etc.), the payment date reflects the cash flow.

**Comment by psealock** [comment]
I checked that this behaviour is the same as the legacy reports, which was the basis for Analytics.

@LevinMedia Do you have any thoughts on this? It makes sense to me, at least in the Revenue Report. Is it worth a departure from Legacy Reports? Thanks

**Comment by tivnet** [comment]
Or maybe it's a core issue and the order date should be updated to the payment date? What could be the consequences? In subscriptions, the new term starts on the payment date I believe. What they show as "invoice date" could remain as a `_invoice_date` meta.

**Comment by louwie17** [comment]
Re-pinging @LevinMedia for thoughts on changing the way the revenue items are ordered by paid date or completed date instead of created date?
cc: @pmcpinto

**Comment by tivnet** [comment]
@louwie17 For the cash flow, "completed" is irrelevant, I believe. The "paid" looks correct to me.

**Comment by moon0326** [comment]
re-pinging @LevinMedia as this issue has been idle for more than 26 days.

also cc: @pmcpinto
