### ISSUE TITLE
Payments task: include Mercado Pago in WC 5.3

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6537]
**Description:** we need to start including Mercado Pago (the most popular provider in LATAM) as a payment option in some LATAM countries (context here: pbIJXs-Jo-p2). The goal is to ship the inclusion in WooCommerce 5.3 (code freeze: April 15)

**Acceptance criteria:**
- [ ] Display Mercado Pago as an option in the Payments task in the following countries:
Mexico – MX
Brazil – BR
Argentina – AR
Chile – CL
Colombia – CO
Peru – Pe
Uruguay – UY
- [ ] The Mercado Pago option should be placed below Stripe and above PayPal
- [ ] The content should be the following
Title: Mercado Pago Checkout Pro & Custom
Content: Accept credit and debit cards, offline (cash or bank transfer) and logged-in payments with money in Mercado Pago. Safe and secure payments with the leading payment processor in LATAM.
Logo: TBD
WP.org link to download the plugin: https://wordpress.org/plugins/woocommerce-mercadopago/
- [ ] Add the `Recommended` pill (similar to what we have for Stripe) but change the copy to `Local Partner`

**Comment by pmcpinto** [comment]
@timmyc considering that they want to ship this in 5.3 I think it would be better to make this change during this week/cycle.
@samueljseay do you think that your team can work on this in the upcoming days? Considering that you're working on other store setup changes. Same for #6538. Thanks!

**Comment by timmyc** [comment]
> I think it would be better to make this change during this week/cycle.

I concur, should we move it to the top of the dev cycle pipeline?

**Comment by pmcpinto** [comment]
Done!

**Comment by octaedro** [comment]
Hi @pmcpinto,

Do we have more details about the title, content, and logo to use here?

I would need also the texts that appear after the plugin's installation to encourage the user to create a `Mercado Pago` account and set up the plugin. For now I copied the texts we are showing for `PayU India`, but changing names:
![screenshot-one wordpress test-2021 03 12-10_13_01](https://user-images.githubusercontent.com/1314156/110946100-3e73d180-831d-11eb-931f-d970a473d7ca.png)

I made a draft PR and as soon as I have the requested information I'll finish it up.

**Comment by pmcpinto** [comment]
> I would need also the texts that appear after the plugin's installation to encourage the user to create a Mercado Pago account and set up the plugin. For now I copied the texts we are showing for PayU India, but changing names:

We can use the same copy :)

**Comment by pmcpinto** [comment]
@octaedro sorry but there's one additional change that we need to make for the Mercado Pago inclusion. I just added it to the acceptance criteria:

> - [ ] Add the `Recommended` pill (similar to what we have for Stripe) but change the copy to `Local`

LMK if you have questions

**Comment by octaedro** [comment]
Hey @pmcpinto,

Just to confirm because we're currently using a `Ribbon` for Stripe
![screenshot-one wordpress test-2021 03 16-11_18_15](https://user-images.githubusercontent.com/1314156/111324770-d63d2c80-8649-11eb-99f0-f64c51dee87a.png)

What we want here is to add a pill like this, no?
![screenshot-one wordpress test-2021 03 16-11_20_00](https://user-images.githubusercontent.com/1314156/111324816-e05f2b00-8649-11eb-9171-71ce5b072fa0.png)

Also, I saw the text now will be `Local Partner` (pbIJXs-Jo-p2#comment-2284).

**Comment by pmcpinto** [comment]
> Also, I saw the text now will be Local Partner (pbIJXs-Jo-p2#comment-2284).

Correct. The latest copy is Local Partner.

> Just to confirm because we're currently using a Ribbon for Stripe

Good catch. Let's use the ribbon here as well. Thanks
