### ISSUE TITLE
Allow filter by time of day.

### ISSUE THREAD

**Issue by bowenac** [woocommerce/woocommerce-admin#6545]
Looks like this was a feature request back in 2019... but still has not been implemented.
https://github.com/woocommerce/woocommerce-admin/issues/2307

It would be nice to be able to specify in the date range the time of day as well as the day spread. e.g. Thursday 5pm - Friday 2pm etc.

Specifically looking for this in Analytics/Products, Date Range.

**Comment by psealock** [comment]
Thanks @bowenac for making this request, its good to know this is something people want. 

This would take some UI work to get fit custom time periods to accomodate time as well. From there, the mechanism for fetching data would remain the same.

Estimate: 2

**Comment by ilyasfoo** [comment]
Sorry but due to the lack of priority for this feature request and no contributors willing to step up, we're closing this issue for now.
