### ISSUE TITLE
Emailed Revenue Report does not include Gross Sales

### ISSUE THREAD

**Issue by damiannep** [woocommerce/woocommerce-admin#6558]
**Describe the bug**
When you receive a revenue report by email, it does not include Gross Sales.

**To Reproduce**

1. Go to Analytics > Revenue
2. Set the rows per page to have multiple pages - https://d.pr/i/gB9oCo
3. Make sure that Gross Sales are enabled - https://d.pr/i/jmjokm
4. Download report which will be sent by email
5. Notice there is no Gross Sales column in the report received by email

**Expected behavior**
I expected the emailed report to match the one seen on the page

**Additional context**
Reported in https://wordpress.org/support/topic/gross-sales-missing-from-revenue-csv-export/ and confirmed on my test site.

**Comment by hsingyuc** [comment]
I'll try to fix it. 🔨
