### ISSUE TITLE
woocommerce_admin_disabled filter hook not working as expected

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-admin#6571]
**Describe the bug**
When trying to use this filter such as `add_filter( 'woocommerce_admin_disabled', '__return_false' );` to disable WC Admin, it doesn't work. I believe this is because of the load order of plugins. Since this https://github.com/woocommerce/woocommerce-admin/blob/main/woocommerce-admin.php#L142 is called before `plugins_loaded` any plugins that loads after WC Admin the filter would not work.

WC 5.2.0-dev
WC Admin 2.2.0-dev stand alone

**To Reproduce**

1. Add `add_filter( 'woocommerce_admin_disabled', '__return_false' );` to the top of a plugin's main file such as Product Vendors extension. Or any plugin that loads after WC Admin.
2. Witness WC Admin is still loaded/enabled.

**Expected behavior**
I am expecting for the filter to work and that it would disable WC Admin.

Possible solution would be to move the filter to within https://github.com/woocommerce/woocommerce-admin/blob/main/src/FeaturePlugin.php#L133 as that is called after `plugins_loaded` or wrap https://github.com/woocommerce/woocommerce-admin/blob/main/woocommerce-admin.php#L142 within `plugins_loaded` however that is a heavier lift as things in https://github.com/woocommerce/woocommerce-admin/blob/main/src/FeaturePlugin.php#L62 would have to be adjusted such as remove `plugins_loaded` from there and also move the `register_activation_hook` out as it doesn't work well within `plugins_loaded`.

**Comment by psealock** [comment]
We're in the process of figuring out how to remove that filter in https://github.com/woocommerce/woocommerce-admin/pull/6568. Included in that change will be a mechanism to turn off certain features, like analytics or Navigation. I'll close this out and could you add to the conversation in that PR with what you are desiring specifically (turn of a feature? Go back to just WC Core?). That will be better for visibility. Thank you!
