### ISSUE TITLE
Flash of content on profile wizard initial load

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6598]
**Describe the bug**
There is a flash of content on the initial load when the profile wizard is loaded.

This results in a header that contains `/setup-wizard` for the title and looks a little janky.

Previously this was hidden prior to client load by a full screen class, but appears to no longer be working.

**To Reproduce**

1. Throttle your browser speed to see the content.
2. Load the setup wizard.
3. Note the header shown prior the profile wizard taking over.

**Expected behavior**
Expected the profile wizard to take over the screen immediately and not show the WCA header.

**Screenshots**
<img width="665" alt="Screen Shot 2021-03-15 at 7 33 28 PM" src="https://user-images.githubusercontent.com/10561050/111234629-566d7e80-85c5-11eb-9740-6397f612d523.png">

**Comment by samueljseay** [comment]
> Previously this was hidden prior to client load by a full screen class, but appears to no longer be working.

I think that must have been a long time ago, I have seen this for quite a few months now. Assumed it was known. Thanks for raising this.
