### ISSUE TITLE
OBW: Similar theme install and activation notices are shown, when a single notice would be clearer

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6599]
**Describe the bug**
When picking a new theme in the setup wizard, two similar notices are shown (one for installation and one for activation).

**To Reproduce**

1. Navigate to `/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=theme`
2. Install a new theme from the list.
3. Note the 2 success messages.

**Expected behavior**
Expected a single notice to be shown.

**Screenshots**
<img width="1117" alt="Screen Shot 2021-03-15 at 7 36 09 PM" src="https://user-images.githubusercontent.com/10561050/111234796-bd8b3300-85c5-11eb-8c0b-64d3c53ce9e9.png">

**Comment by samueljseay** [comment]
@joshuatf This definitely looks janky but its 2 separate notice. 1 for the install and 1 for activation.

I'm gonna label this as an enhancement if that sits well with you. 

For anyone coming to fix this, we have 2 separate promises for install and activation, one handles success and error for each. The solution would be to consolidate to a Promise.all with a single success/failure:

https://github.com/woocommerce/woocommerce-admin/blob/d0c909ffb60e17e46ca246ac7b17485631f8c97b/client/profile-wizard/steps/theme/index.js#L109

**Comment by joshuatf** [comment]
>I'm gonna label this as an enhancement if that sits well with you.

Definitely.  That's a better label; I was a bit too hasty in opening this issue.
