### ISSUE TITLE
Missing margin between cards and viewport in setup wizard

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6600]
**Describe the bug**
If a viewport is shorter, no margin separates the card and the bottom of the screen on some steps.

**To Reproduce**

1. Navigate to the setup wizard.
2. Narrow your viewport height.
3. Note the lack of margin on the Industry and the Business Details (if you uncheck "Install recommended free...") steps

**Expected behavior**
Expected some space between the bottom of the card and the edge of the screen.

**Screenshots**
<img width="649" alt="Screen Shot 2021-03-15 at 7 14 04 PM" src="https://user-images.githubusercontent.com/10561050/111234970-1a86e900-85c6-11eb-8577-81c6fe080909.png">

**Comment by vanduc1102** [comment]
Hi @joshuatf 
I created a PR #6620  for the issue, would you check when you available, thanks ?

**Comment by joelclimbsthings** [comment]
Came across this is the current dev cycle, but it looks like it should already be closed due to the [above PR](https://github.com/woocommerce/woocommerce-admin/pull/6620)? @mattsherman

**Comment by mattsherman** [comment]
@joelclimbsthings Good catch. Closing this, as it is fixed by #6620
