### ISSUE TITLE
Performance metrics don't match individual reports

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6601]
**Describe the bug**
When viewing the Overview page, the performance metrics don't seem to match the numbers on other reports.

**To Reproduce**

1. On a new site, create an order (I did so through the admin instead of the frontend if that makes a difference).
2. Go to Analytics->Overview.
3. Note the discrepancies.

**Expected behavior**
Expected numbers to match.

**Screenshots**
<img width="994" alt="Screen Shot 2021-03-15 at 7 23 51 PM" src="https://user-images.githubusercontent.com/10561050/111235130-6a65b000-85c6-11eb-813c-cb37dbf69491.png">

**Comment by samueljseay** [comment]
@louwie17 pointed out this is likely related to woocommerce/woocommerce#32273 I'll close this as duplicate for now, and we'll prioritise fixing this in 2.2.
