### ISSUE TITLE
WooCommerce Analytics Settings Screen is Blank

### ISSUE THREAD

**Issue by AmeliaBriscoe** [woocommerce/woocommerce-admin#6602]
**Describe the bug**
Navigating to **Analytics > Settings** shows a blank screen

**To Reproduce**

1. Go to 'WooCommerce > Analytics'
2. See error screenshot: https://d.pr/i/FgDG82
3. There are errors in the console related to React.

**Expected behavior**
Analytics settings should loads and show options as per docs: https://docs.woocommerce.com/document/woocommerce-analytics/#analytics-settings

**Screenshots**

* https://d.pr/i/FgDG82

**Desktop (please complete the following information):**

* OS: iOS Big Sur 11.2.2
* Browser: Chrome
* Version 89.0.4389.82 (Official Build) (x86_64)

**Additional context**
I am also replicating this on a Jurassic Ninja website.

**WC Status Report (if needed)**

`
### WordPress Environment ###

WordPress address (URL): https://mywoosubscriptions.com
Site address (URL): https://mywoosubscriptions.com
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.16
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.75.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 2.48MB
Database Data Size: 1.07MB
Database Index Size: 1.41MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
customize_changeset: 1
page: 6
post: 1
revision: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (7) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Jetpack by WordPress.com: by Automattic – 9.5.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Shipping & Tax: by Automattic – 1.25.8
WooCommerce Square: by WooCommerce – 2.3.4
WooCommerce Stripe Gateway: by WooCommerce – 4.9.0
WooCommerce Subscriptions: by WooCommerce – 3.0.13

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 33
Oldest: 2021-02-17 08:32:01 +1100
Newest: 2021-03-16 11:08:27 +1100

### Status report information ###

Generated at: 2021-03-16 11:12:44 +11:00
`

**Comment by samueljseay** [comment]
Hi @AmeliaBriscoe 😄 nice to see you!

We're aware of this one and really sorry for the inconvenience caused. The bug is fixed in https://github.com/woocommerce/woocommerce-admin/pull/6540 and the fix should be available in release 2.1.2 of wc-admin.

If it's possible could the store upgrade to that version? I'm closing this for now, but please if you need to continue the discussion feel free to repoen.

**Comment by AmeliaBriscoe** [comment]
Hi Sam! Thanks for the update. Someone let me know this was already reported so was coming back here to close it. Sorry for the duplicate :)

I don't have WC Admin active as a separate plugin - just what is in WooCommerce core. I can certainly try the 2.1.2 release,

**Comment by tripathimarut** [comment]
@AmeliaBriscoe Your query is resolved or not ? 
If yes then please tell me how because I am facing same problem in home and analytics page of Woocommerce 

![Screenshot (104)](https://user-images.githubusercontent.com/86621192/123752349-54aa9b00-d8d6-11eb-98b5-8f0677472000.png)

**Comment by samueljseay** [comment]
@tripathimarut could you let me know which version of woocommerce you have installed? (And if you have woocommerce admin installed separately what version of that?) 

This should have been fixed in recent versions but it's possible you have found a new bug.

**Comment by tripathimarut** [comment]
@samueljseay 5.4.1
