### ISSUE TITLE
Analytics showing removed/deleted orders in returns total?

### ISSUE THREAD

**Issue by DHVDave** [woocommerce/woocommerce-admin#6615]
We had ~4 test orders when the store was opening that we deleted. Everything is gone in the orders view, but Analytics still shows the total of these under retuns (-137.16) no matter what I do. 

Is this a bug, or is there a different table this is calculated on that we need to purge?

![image](https://user-images.githubusercontent.com/73902825/111527665-28577e00-872e-11eb-815f-86a7924cd9d7.png)
![image](https://user-images.githubusercontent.com/73902825/111527766-44f3b600-872e-11eb-8619-738d95c3a87f.png)

**Comment by louwie17** [comment]
Hi @DHVDave, thanks for creating an issue and getting in touch with us.
The table where these stats are coming from is the `wp_wc_order_stats` table, if you delete your test order data from there and flush the cache, it should show as empty.

To determine if this is a bug or not, I just have one question (with a follow up): 
- Did you delete the orders through **WooCommerce > Orders**? or from the database table?

what should happen is that the `wp_wc_order_stats` gets updated with the new status - `wc-trash`. And if you permantly delete an order, it should remove it from the `wp_wc_order_stats` table as well.
Setting an order to 'trashed' doesn't happen immediate, but is done in a scheduled task. You can see if any scheduled tasks are still pending or failed to update in **WooCommerce > Status > Scheduled Actions**, the status should say **Complete**, the hook to look for would be - `wc-admin_import_orders`

If the tasks do show that they are not completed or still pending let me know.

**Comment by DHVDave** [comment]
Hi @louwie17  thanks for your reply.

I did verify that all scheduled actions for `wc-admin_import_orders` are in Complete status. Upon looking at the `wc_order_stats` table I found the 4 rows that were causing this issue. Upon deleting those rows, everything ties.

Was it perhaps a bug that deleting the orders didn't clear these records?

**Comment by louwie17** [comment]
> Upon deleting those rows, everything ties.

Good to hear :)

> Was it perhaps a bug that deleting the orders didn't clear these records?

Not sure, I tried reproducing it on my end, but couldn't. Are you able to reproduce it on your end? and if so what are the exact steps you took?

We do have an issue present where the analytics data isn't always updated upon order creation - woocommerce/woocommerce#32273 and I am curious if it is related, but then for order deletion, it would involve the same update logic.
I will mention this in that ticket as well.
