### ISSUE TITLE
Update confirmation modal uses old purple and button style

### ISSUE THREAD

**Issue by danhauk** [woocommerce/woocommerce-admin#6619]
**Describe the bug**
When clicking to update WooCommerce from the plugins screen I got a confirmation modal about compatibility and some plugins being untested. This modal uses the old purple and old button style with the box shadow on it.

![Screenshot_2021-03-18 WordPress Updates ‹ wc playground — WordPress](https://user-images.githubusercontent.com/448298/111649799-17187b00-87db-11eb-89e5-e5fc5e854771.png)

**To Reproduce**

1. Run a site with an older version of WooCommerce (mine was 5.0) and Mailchimp for WooCommerce (tested up to WC 4.8)
2. Visit `/wp-admin/update-core.php` to update the plugins
3. Click the checkmark to update WooCommerce
4. View the modal

**Comment by elizaan36** [comment]
hey @danhauk, good find! I think this is in the woocommerce repo - I have an open issue here with some other examples, if it makes sense to you would you add this example as a comment on that thread? That way we can try to tackle everything in one go.

**Comment by ilyasfoo** [comment]
Thank you for filing this @danhauk. @elizaan36 is correct, the modal in question lives on WooCommerce core repository. I went ahead and edit the mentioned [issue](https://github.com/woocommerce/woocommerce/issues/29267) to include this report. I'm closing this now, have a great day!

**Comment by danhauk** [comment]
Thanks so much for filing to the correct repo! @ilyasfoo @elizaan36
