### ISSUE TITLE
New WC home navigation doesn't work

### ISSUE THREAD

**Issue by williamgh2019** [woocommerce/woocommerce-admin#6629]
Hello Everyone,

I have staging Dev site and production site but in my Dev Site has new WC new home navigation as below

Dev Site 👇👇

![image](https://user-images.githubusercontent.com/17005582/111019426-b7445d80-83f1-11eb-9826-13e02ce9b695.png)

But why in my production site doesn't work?

Production Site 👇👇

![image](https://user-images.githubusercontent.com/17005582/111019440-d2af6880-83f1-11eb-902e-d775a44c7e8a.png)

Noted: I have updated to latest and same version both Staging Dev Site and Production site.

**Comment by ilyasfoo** [comment]
Hi @williamgh2019, can you confirm that you have installed the latest version of [WooCommerce Admin plugin](https://wordpress.org/plugins/woocommerce-admin/)? The new navigation experience requires that plugin to be activated and the feature enabled in WooCommerce > Settings > Advanced.

**Comment by williamgh2019** [comment]
> Hi @williamgh2019, can you confirm that you have installed the latest version of [WooCommerce Admin plugin](https://wordpress.org/plugins/woocommerce-admin/)? The new navigation experience requires that plugin to be activated and the feature enabled in WooCommerce > Settings > Advanced.

This method is worked. Just need to enable option as you said in Advance Setting.

**Comment by ilyasfoo** [comment]
@williamgh2019 Glad that helps! 😄
