### ISSUE TITLE
Task list updates

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6633]
In order to figure out the scope of these changes, we're putting proposed extended task list improvements from `pbIJXs-IQ-p2` into this epic. 
- Some minor changes in functionality (move dismiss action to ellipses with remind me later) would apply to the store setup task list component.
- In the future, the extended task list (renamed "Things to do next" from "Extensions setup") could be used by extension authors on extension overview screens filtered by only their tasks (such as the WC Pay use case from `paJDYF-18j-p2`.
- The extended task list contains a hierarchy of three levels of priority tasks, also detailed in `pbIJXs-IQ-p2`.
- Also, presenting an abbreviated task and activity notification in the Inbox panel

**Comment by mattsherman** [comment]
@samueljseay Can this epic be closed? Asking because I see my new team members on a number of issues, and want to make sure we don't have further work to do!

**Comment by samueljseay** [comment]
@mattsherman Yes this epic specifically can be closed. Thanks :)
