### ISSUE TITLE
Industry step fails to load when no profile data exists

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6634]
**Describe the bug**
When the onboarding wizard hasn't been completed yet, the industry step gets broken.

It looks like `industries` data is missing from `onboarding` so maybe this data is getting preloaded on fresh sites.

**To Reproduce**

1. On a fresh site, go the onboarding wizard.
2. Complete the store details step.
3. Note the error after completing the first step.

**Expected behavior**
Expected the profiler to continue to work.

**Screenshots**
<img width="740" alt="Screen Shot 2021-03-22 at 6 16 31 PM" src="https://user-images.githubusercontent.com/10561050/112065542-2d0ba000-8b3b-11eb-9e6a-03f04d20f19f.png">

**Comment by samueljseay** [comment]
This is fixed now I believe.
