### ISSUE TITLE
Expand/collapse in task list footer

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6636]
This is an update to the extended task list on the home screen.

Details:
- Show two tasks maximum by default
- Add an accordion footer with a link and caret icon. Clicking will expand to show all tasks (if there are more than 2) and collapse to show only 2
- If there are only two tasks, the accordion footer won't appear
- The link in the footer shows the number of hidden tasks, "Show X more tasks". When expanded it shows a link "Show less"

![Screen Recording 2021-04-07 at 01.49.29 PM.gif](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/c25b2ca4-5340-4123-9481-522806c8406a)

More details in `pbIJXs-IQ-p2`

Tracks events:
`wcadmin_extended_tasklist_expand`
When the user expands the task list to view all tasks
`wcadmin_extended_tasklist_collapse`
When the user collapses the task list to show less tasks

**Comment by pmcpinto** [comment]
Just to add a reminder that we need to add event tracking to the new user actions.

**Comment by elizaan36** [comment]
I'm going to close this issue since any task list changes outside of copy are out of scope for the near future. Will revisit the designs once we're ready and create a new issue.

**Comment by elizaan36** [comment]
Thanks for reopening Pedro! I updated the issue with the Tracks events.

**Comment by samueljseay** [comment]
For the implementer: we're moving this functionality as a reusable component into `@woocommerce/components` <List> component. See #6772

**Comment by louwie17** [comment]
If we are making this a re-usable component, we would also want to allow the list to be fully collapsed, the conditions for this would have to be configurable. See https://github.com/automattic/woocommerce-payments/issues/1656#issuecomment-824840459 for more context.
