### ISSUE TITLE
Dismiss and Remind me later in task ellipses menu

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6637]
This is an update to the task list components on the home screen - Store setup and Extended task list.

- There's currently a `Dismiss` action that appears as a full word on the right side of a dismissible task. This update would move that action to an ellipses menu.
- The `Remind me later` action would set a count of 24 hours for the task to appear again in the list.
- The only tasks in the store setup task list that are dismissible are the paid extensions install tasks

![Screen Shot 2021-04-07 at 1.59.41 PM.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/945ce958-df8f-4e4c-ac36-19e84321c600)

Tracks events:
`wcadmin_extended_tasklist_task_click`
property: `task_name`
When user selects task
`wcadmin_extended_tasklist_task_dismiss`
property: `task_name`
When user dismisses task from ellipses menu
`wcadmin_extended_tasklist_task_remindmelater` 
property: `task_name`
When user selects "Remind me later" from ellipses menu

**Comment by pmcpinto** [comment]
Just to add a reminder that we need to add event tracking to the new user actions.

**Comment by elizaan36** [comment]
Thanks Pedro, do we already have Tracks set up for the extended task list? Would the event start with `wcadmin-extendedtasklist-...`?

**Comment by pmcpinto** [comment]
> Thanks Pedro, do we already have Tracks set up for the extended task list? Would the event start with wcadmin-extendedtasklist-...?

Not yet. Something like wcadmin_extended_tasklist_action works well

**Comment by elizaan36** [comment]
Updated the issue with Tracks events👍

**Comment by louwie17** [comment]
@elizaan36 currently we show a notice with `Task dismissed` when a user clicks `Dismiss`, do we want something similar for `Remind me later`?
Use `Task dismissed` as well, or something like `Task postponed`?

**Comment by louwie17** [comment]
@elizaan36 @pmcpinto one more question in relation to the track events.
We currently have the `tasklist_click` and `tasklist_dismiss_task` events, should I change these to follow the format listed above?
`tasklist_click`             -> `tasklist_task_click`
`tasklist_dismiss_task` -> `tasklist_task_dismiss`

**Comment by elizaan36** [comment]
> @elizaan36 currently we show a notice with Task dismissed when a user clicks Dismiss, do we want something similar for Remind me later?

Good question. We should provide more context so how about "Task postponed until tomorrow" for the snackbar notice?

> We currently have the tasklist_click and tasklist_dismiss_task events, should I change these to follow the format listed above?

I'm not sure on this one - @pmcpinto will this confuse the existing data if the event names are changes?

**Comment by louwie17** [comment]
@pmcpinto do you have thoughts on the above event names? Instead of changing the current event names, we could also update the events above to our current format:
`wcadmin_extended_tasklist_click`
`wcadmin_extended_tasklist_dismiss_task`
`wcadmin_extended_tasklist_remindmelater_task`

**Comment by pmcpinto** [comment]
@louwie17 sorry I missed your ping. It's better to update the new event names to our current format. Thanks!

**Comment by louwie17** [comment]
@pmcpinto all good, and thanks I will do that 😄

**Comment by samueljseay** [comment]
@elizaan36 One thing that feels ambiguous, maybe I missed a discussion point here, but:

Should *all* tasks be able to be set to "remind me later". or is it only for dismissable tasks?

**Comment by elizaan36** [comment]
Good call, don't think this was discussed anywhere. All tasks should be able to be set to "Remind me later", even the non-dismissable ones. The database update example comes to mind, where there's a secondary action for "Remind me later".

**Comment by louwie17** [comment]
> Good call, don't think this was discussed anywhere. All tasks should be able to be set to "Remind me later", even the non-dismissable ones. The database update example comes to mind, where there's a secondary action for "Remind me later".

@elizaan36 to follow up on this, is there any tasks that we have currently that should have "remind me later' or 'dismiss' enabled as part of this issue?
Or was this mostly to enable the **support** for remind me later, so a 3PD plugin (or ourselves) can use it in the future?

**Comment by elizaan36** [comment]
> Or was this mostly to enable the support for remind me later, so a 3PD plugin (or ourselves) can use it in the future?

I can't think of any existing tasks offhand that would require this if they don't have it already, so it's more about enabling the support as you said. This could encourage adoption since it gives 3PD's some more flexibility with these notices. Otherwise users only have the option to dismiss.
