### ISSUE TITLE
Show/hide task list and move completed tasks to bottom

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6638]
This is an update to the extended task list component on the home screen.

- As tasks are completed, they're moved to the bottom of the list.
- There’s a popover menu accessible from the card menu with the option to show/hide task list. The task list can be shown again from the Display menu in the top bar.
- Completed tasks can be deleted from the task ellipses menu (no confirmation needed)

<img width="523" alt="Screen Shot 2021-04-01 at 4 37 01 PM" src="https://user-images.githubusercontent.com/5121465/113356829-87112000-9308-11eb-94a3-42a46fba9687.png">

<img width="265" alt="Screen Shot 2021-04-01 at 4 35 50 PM" src="https://user-images.githubusercontent.com/5121465/113356723-5df08f80-9308-11eb-842a-0803dac7a34c.png">

<img width="522" alt="Screen Shot 2021-04-01 at 4 31 56 PM" src="https://user-images.githubusercontent.com/5121465/113356400-cee37780-9307-11eb-9587-74fafe3d9794.png">

Tracks events:
`wcadmin_extended_tasklist_view` 
property: task_name
When user views the Extended task list on the home screen
`wcadmin_extended_tasklist_hide`
When user hides the Extended task list from the card menu
`wcadmin_extended_tasklist_show`
When user shows the Extended task list from the Display dropdown

**Comment by elizaan36** [comment]
Thanks for reopening the issue, Pedro. I updated the description and screenshots based on the chat in Slack.

**Comment by jeffstieler** [comment]
> Completed tasks can be deleted from the task ellipses menu (no confirmation needed)

Instead of introducing "delete" as an action, can we show the "dismiss" option for completed tasks instead?

**Comment by jeffstieler** [comment]
@samueljseay do we know if it's safe to reintroduce the sort-by-completion? I see it was reverted in https://github.com/woocommerce/woocommerce-admin/pull/5721.

**Comment by elizaan36** [comment]
> Instead of introducing "delete" as an action, can we show the "dismiss" option for completed tasks instead?

That makes sense, @jeffstieler - no need to have two separate actions at this point. Let's use dismiss for both completed and not completed tasks.

**Comment by elizaan36** [comment]
Btw, the dismiss option for incomplete tasks is in [another issue](https://github.com/woocommerce/woocommerce-admin/issues/6637#issuecomment-813401492).

**Comment by jeffstieler** [comment]
@elizaan36 should there be an option for showing the extensions task list as well in the display options menu?

**Comment by elizaan36** [comment]
yeah, I've got that in the comment above😜

Let's call the item "Show things to do" to make sure there's no confusion with the store setup task list - what do you think? Plus, the store setup task list can only be enabled again in settings at the moment.

**Comment by jeffstieler** [comment]
Oh wow, I must have missed the part where this whole issue is scoped to the extended task list. 🤦‍♂️ 

So to be clear:
* The extended task list title is to change from "Extensions setup" to "Things to do next"
* The display options menu will show a toggle **just for the extended task list** labeled "Show things to do next"
* Only the extended task list items will sort by completion (or should the normal task list also do this?)

Is that correct?

**Comment by elizaan36** [comment]
No worries😆 Yep, this is scoped to only the extended task list.

> The extended task list title is to change from "Extensions setup" to "Things to do next"
Yep!

> The display options menu will show a toggle just for the extended task list labeled "Show things to do next"
👍

> Only the extended task list items will sort by completion (or should the normal task list also do this?)
Only the extended task list because we want to create more of a sense of progression with the store setup task list. ([More details on changes to that task list here](https://github.com/woocommerce/woocommerce-admin/issues/6639#issuecomment-816844512))

> Only the extended task list will allow completed item dismissal (or should the normal task list also do this?)
There's only one task in the store setup task list that can be dismissed - when you add a paid extension from the store profiler. The Dismiss and Remind me later update should apply to that task as well, I'll update that issue!

Since the store setup task list is contained there won't be the potential for a loooong list so it's not as important to dismiss those tasks. Once extensions start adopting this task list it has the potential to get unwieldy, hence introducing the accordion to collapse, moving the completed tasks, and allowing for the dismiss action.

**Comment by jeffstieler** [comment]
> `wcadmin_extended_tasklist_hide`
> When user hides the Extended task list from the card menu

Hiding a task list from the card menu already has tracking. For the extended list the event name is `extended_tasklist_completed` (with an `action` prop of `remove_card`).

Since the toggle in the display menu is new, we could use `wcadmin_extended_tasklist_show` and `wcadmin_extended_tasklist_hide` for on/off. Does that work?

**Comment by elizaan36** [comment]
> Since the toggle in the display menu is new, we could use `wcadmin_extended_tasklist_show` and `wcadmin_extended_tasklist_hide` for on/off. Does that work?

Yep, that works. That's what I had on there but didn't realize there was already an event for hiding the extended task list. The proposed events make a little more sense together.

**Comment by jeffstieler** [comment]
@elizaan36 should the "show things to do next" item be visible in the display options if there are no items in that list (e.g. no extensions have added tasks)?

![](https://user-images.githubusercontent.com/5121465/113356723-5df08f80-9308-11eb-842a-0803dac7a34c.png)

**Comment by elizaan36** [comment]
👋 If a store hasn't received any tasks in the extended task list, the option wouldn't be shown in the display dropdown. There's currently no empty state or anything to show.

If all tasks are completed, there should be an option to show the list in the dropdown. (There's currently no other way to show the completed tasks)
