### ISSUE TITLE
Task hierarchy for extended task list

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6639]
This update applies to the Extended task list only.

- Tasks can be registered in one of three categories: L1, L2, and L3 as shown in this table:

![image.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/056a1b0a-1288-461c-bc06-7a361b1ffe8f)

- L1 tasks have an icon and optional primary action. This level should only be used by WooCommerce.
- If L1 tasks appear in the list, the task list appears above the activity panel (orders, etc) on the home screen

More detailed guidelines are in a Google doc linked from `pbIJXs-IQ-p2`

- When hovering over the left border of the task, a tooltip appears with more information
![image.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/b225e4c0-216a-4c23-810a-9b7af4d21454)

**Comment by elizaan36** [comment]
Closing this for now and will revisit when we're ready.

**Comment by samueljseay** [comment]
@elizaan36 in the epic description it says

"In the future, the extended task list (renamed "Things to do next" from "Extensions setup") could be used by extension"

Shall I rename the extended task list as part of this? It can go on any one of the issues, but I want to track it if we need to do it.

**Comment by samueljseay** [comment]
Also @elizaan36 @pmcpinto I was just wondering for backward compatibility what level we should set any tasks to that don't choose a priority level? the lowest one? L3?

**Comment by pmcpinto** [comment]
The lowest one seems to be the best option

**Comment by elizaan36** [comment]
> Shall I rename the extended task list as part of this? It can go on any one of the issues, but I want to track it if we need to do it.

Would be great to rename the task list as well, wasn't sure if we needed a separate issue. Interested to hear thoughts on this but I think "Things to do next" makes the most sense. Reason being that after looking at the extended task list directly below the "Get ready to start selling" setup task list, adding the word "next" makes it clear that these are secondary tasks to complete after store setup.

**Comment by samueljseay** [comment]
@elizaan36 neither the wordpress "warning" icon or the gridicons "notice-outline" quite match the exclamation mark icon. Do you want to use one from figma or would the gridicons one suit? (I think its the closest of the too: https://automattic.github.io/gridicons/)

**Comment by elizaan36** [comment]
You're right, the Gridicons one is better than the WordPress icon. I think the red color is already pretty jarring so I'd rather go with the outline. 👍

**Comment by samueljseay** [comment]
Hey @pmcpinto 

I just wanted to bring some issues I've been having with this to your attention. I won't get too deep into the technical side of it (but feel free to ask for more information). 

I've been trying to implement this, it should be relatively simple, but I have had a lot of trouble with the current task list implementation. I thought maybe I could refactor the extended task list implementation but it was difficult in its current state. It started taking me a lot of time and touching a lot of areas.

I stepped back to try a different approach with our List component and some "hacks" but I found this too proved to be time consuming because of how that component is implemented.

What I've found is that the problems between List component and the extended task list are intertwined. To fix one I must fix the other.

If you're ok with it, I'd like to propose creating 2 new tickets to cover the work I believe we should do to fix the 2 items. I think the most significant piece of work will be fixing the extended task list.

Some estimates off the top of my head are 3 for the extended task list fixes, and 1-2 for the List component fixes.

I wanted to know how you felt about that approach.

cc @timmyc who I also talked to about this. 🙇

**Comment by pmcpinto** [comment]
> If you're ok with it, I'd like to propose creating 2 new tickets to cover the work I believe we should do to fix the 2 items. I think the most significant piece of work will be fixing the extended task list.
> Some estimates off the top of my head are 3 for the extended task list fixes, and 1-2 for the List component fixes.

@samueljseay thanks for the heads up. Sounds good to me.

**Comment by pmcpinto** [comment]
@samueljseay I forgot to mention that @elizaan36 is working on an update of the setup task list. The goal is to provide more context about each task. Considering that you're going to work on the List component I'm wondering if it makes sense to also include the changes that Elizabeth is preparing. What do y'all think?

**Comment by elizaan36** [comment]
Thanks for bringing that up, Pedro! I can share more details in slack/p2 but here's the mockup of the new design.

![Home - timeline stepper](https://user-images.githubusercontent.com/5121465/114219119-dfab7300-992f-11eb-8b08-7d2d7528f830.png)

Some things that work about this compared to the existing store setup task list:
- Upon landing on the home screen after completing the profiler, merchants see a clear next step. (The primary action to add products)
- This layout will adjust quite nicely between single column and two column layouts
- There's a sense of progression and cohesiveness with the vertical stepper component (which appears in the flow for some steps.)

Other details:
- Any task can be expanded at any time (the tasks don't have to be completed in order)
- Only one task can be expanded at a time
- Completed tasks won't expand, they'd go the settings area or task screen where data can be edited

I look forward to hearing your thoughts!

**Comment by samueljseay** [comment]
Thanks @elizaan36 @pmcpinto I think it'd be great to tackle this new design as part of the refactoring. 

Looking at these designs they reinforce the need to refactor the list 👍 

I'll create a few tickets to cover everything here.

**Comment by pmcpinto** [comment]
> Any task can be expanded at any time (the tasks don't have to be completed in order)

@elizaan36 what action is going to trigger this? Hovering the task or clicking on it? 

> Looking at these designs they reinforce the need to refactor the list 👍

I'm still assessing if we should a/b test this approach and use the existing task list as the control version. what impact could this have on the refactoring?

**Comment by elizaan36** [comment]
> @elizaan36 what action is going to trigger this? Hovering the task or clicking on it?

The next task will be open by default, and clicking/tapping will open another.

![Screen Recording 2021-04-12 at 07 28 59 PM](https://user-images.githubusercontent.com/5121465/114479190-9b390500-9bc5-11eb-87d1-30bdb8d49763.gif)
https://share.getcloudapp.com/z8u6YRRk

**Comment by samueljseay** [comment]
> I'm still assessing if we should a/b test this approach and use the existing task list as the control version. what impact could this have on the refactoring?

I think that would be ok. Everything we're refactoring is mostly a matter of code not behaviour. 

The refactoring will make it easier to show 2 completely different kinds of list items, so we can still do an a/b test with the old list item style.

**Comment by elizaan36** [comment]
Ah, good question! all tasks have the same completed state. Even L1 or L2 with the left red/yellow bar (L3 doesn't have a bar) change to the completed state with checkmark and gray title. Any additional description is removed as well.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/5121465/116711949-f7a76d00-a998-11eb-929f-853f453ffef1.png">

Yes, the completed tasks move to the bottom of the list👍
