### ISSUE TITLE
[WC 5.2 beta] Bundle flow not being displayed when user selects IE or NZ as country

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6646]
**Describe the bug**
According to #6487 we should display the bundle approach with WCPayments include if the user selects Ireland or New Zealand

**To Reproduce**

1. Install 5.2 beta 1
2. Add New Zealand or Ireland as the country in the store details step of the profiler 
3. Complete the industry and product types steps with any option
4. See that the business details flow displayed is not the one with the bundle approach: https://d.pr/i/OEVYMU

**Expected behavior**
To go to the bundle approach path in the business details step when I add Ireland or New Zealand as the store country

**Comment by pmcpinto** [comment]
cc @louwie17 (I think this was implemented by you) and @adrianduffell (I think you're the WooCommerce Admin 2.1.3 release lead)

**Comment by louwie17** [comment]
Nice catch @pmcpinto, it appears that [`NZ` and `IE` somehow missed the cut](https://github.com/woocommerce/woocommerce-admin/blob/main/client/profile-wizard/steps/business-details/data/segmentation.js#L8) (sorry about that, I must of just copied that initial list, which didn't include NZ and IE).

It's a pretty easy fix, let me push that up. @adrianduffell do you think we can do a 2.1.4?

**Comment by louwie17** [comment]
Pushed PR up: https://github.com/woocommerce/woocommerce-admin/pull/6649

**Comment by samueljseay** [comment]
@louwie17 I don't think this should go into the 2.1 release, since we now have 2.2 in flight. There are only 2 reasons I think we would do that at this stage:

1. A fixed contractual obligation (@pmcpinto I don't think thats the case here?)
2. A critical bug fix.

@louwie17 I suggest you mark your PR for cherry pick and add it to the 2.2 milestone

**Comment by pmcpinto** [comment]
> A fixed contractual obligation (@pmcpinto I don't think thats the case here?)

Yep, we kind of have a contractual obligation and waiting 4 weeks until 5.3 means that we'd miss hundreds of new users.

**Comment by pmcpinto** [comment]
@adrianduffell just to confirm. This will be included in 2.1.4, correct?

**Comment by adrianduffell** [comment]
@pmcpinto That's correct. I'm planning to release 2.1.4 today.

**Comment by louwie17** [comment]
Just tested and 2.1.4 looks to be working correctly in the new 5.1 rc release: https://developer.woocommerce.com/2021/03/30/woocommerce-5-2-release-candidate/
