### ISSUE TITLE
[Globalstep][IE11- WooCommerce Admin 2.2.0 Beta 2] Toggles and content appears misaligned on onboarding setup screen.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6650]
## Bug Description:
 Toggles and content appear misaligned on the onboarding setup screen.

## Environment:
Woocommerce Version : WooCommerce 5.1
WordPress version: (v5.7)
WooCommerce Admin version: v2.2.0

PC:
Windows 10
IE 11(Version 11.55.17763.0)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Observe that Toggles and content appear misaligned on the onboarding setup.

## Actual Result:
Toggles and content appear misaligned on onboarding setup.

## Expected Result:
Toggles and content should be properly aligned on onboarding setup.

## ScreenShots:
![#6650_1](https://user-images.githubusercontent.com/41110392/112187490-26a72200-8c28-11eb-8e6f-5079305fd9d3.png)
![#6650_2](https://user-images.githubusercontent.com/41110392/112187502-2a3aa900-8c28-11eb-9271-28e64f2cdf1e.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
As ugly as this looks, it seems to be visual only. We're phasing out IE11 support so, I think we should only tackle critical bugs in IE11. I'll close this one as won't fix.
