### ISSUE TITLE
Products: Start with a template selected radio button is mis-rendered

### ISSUE THREAD

**Issue by mattsherman** [woocommerce/woocommerce-admin#6651]
**Describe the bug**

The radio button for a selected template on the "Start with a template" modal when adding new products is mis-rendered.

**To Reproduce**

1. Go to Home
2. Click on 'Add my products'
3. Select 'Start with a template'

**Expected behavior**

The selected radio button to appear correct.

**Screenshots**

https://user-images.githubusercontent.com/2098816/112200961-29812300-8be6-11eb-89e5-798765c29887.mov

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Edge, Firefox

**Comment by hsingyuc** [comment]
I have a fix for this; push shortly.
