### ISSUE TITLE
Form's onChangeCallback is not documented.

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6667]
**Describe the bug**
I was trying to use the `Form` component and do some action whenever anything changes in its state. Coming from the Web Components world, I felt it natural to have change event bubbled/composed. So, at first, I tried to use `onChange` prop which I've seen in some other components. It occurred there is no such thing. Then, I checked the docs https://woocommerce.github.io/woocommerce-admin/#/components/packages/form/README?id=form but there is nothing about change event/callback. Then I tried to extend the component to add this feature. While reading the code to find a way to plug in, I noticed undocumented `onChangeCallback`.

I see few issues here:
1. The `onChangeCallback` is not documented, making it hard to discover and use.
2. Names are inconsistent across components: `onChange` vs. `onChangeCallback`
3. There is a mysterious `touched` prop without any docs.

 
**To Reproduce**

1. Go to https://woocommerce.github.io/woocommerce-admin/#/components/packages/form/README?id=form
2. Try to figure out, how to do something when any value changes.

**Expected behavior**
`onChangeCallback` should be mentioned there, ideally with some meaningful description, examples and documented arguments.

**Screenshots**
![Screenshot of current props documentation](https://user-images.githubusercontent.com/17435/112383168-0e4d0b00-8ced-11eb-8ab5-5042144ef18c.png)

**Additional context**
I tried to add it by myself but wasn't able to generate that https://github.com/woocommerce/woocommerce-admin/issues/6098.

**Comment by joshuatf** [comment]
Thanks for opening this issue, @tomalec!

>Names are inconsistent across components: onChange vs. onChangeCallback

I do like `onChange` as well as this is primarily what we use in other components.

>There is a mysterious touched prop without any docs.

This prop helps determine whether or not a field has been "touched" (received focus) or not.  We'll get the docs updated for this component.

**Comment by hsingyuc** [comment]
I'll work on this one.
