### ISSUE TITLE
Start date of range is missing when querying full year in Revenue

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-admin#6668]
**Describe the bug**

Choosing a year-long period in **Analytics > Revenue**, the report misses the first date on the site and in the download.

1st of April 2019 is missing when the date range is set 1st April 2019 > 31 March 2020
1st June is missing when date range is 1st June 2018 > 31st May 2019

**To Reproduce**

1. Go to **Analytics > Revenue**
2. Choose a date range covering a year from one year into the next.
3. Go to final page of the report, notice the first date is missing. i.e. 1st April
4. Export report, when it is emailed, open CSV and notice the same, first date is missing.

Using **Analytics > Orders** shows all dates.

**Expected behavior**

The report includes all dates selected.

**Additional context**

https://wordpress.org/support/topic/gross-sales-missing-from-revenue-csv-export/#post-14191562

**Comment by joshuatf** [comment]
@dougaitken I wasn't able to reproduce this issue.  Is your store's timezone (set under `wp-admin/options-general.php`) different than the timezone you were in when you experienced this issue?

If that's the case, it may be related to https://github.com/woocommerce/woocommerce-admin/pull/6632.

**Comment by dougaitken** [comment]
Hey @joshuatf - no, same time zone. I'm not travelling and my options-general.php is in London.

Should I set to UTC+1 instead of the time zone being a location?

**Comment by joshuatf** [comment]
>Should I set to UTC+1 instead of the time zone being a location?

If you don't mind trying a different time zone entirely, that may give us a hint as to what's happening.  And if you have the time, a quick screencast of the issue would be super helpful.

I tried spoofing my browser time and setting various timezones without any luck, although this does smell an awful lot like a timezone issue.

Maybe someone on @woocommerce/isotope in a different issue can give this a shot to see if they hit the same issue.

**Comment by dougaitken** [comment]
@joshuatf This is indeed timezone-based! I changed from `London` to `UTC+1` and the first date was shown. I then changed back to `London` refreshed the page and the first date disappeared. 

Unsure of the _why_ but I hope that helps clarify the cause of this.

**Comment by joshuatf** [comment]
Sorry for the very late response on this, @dougaitken!  I am able to reproduce this issue using a store with a London timezone setting.

The date range for revenue is likely being sent back from the server as UTC and formatted in the table based on the local store settings.  We'll look into getting this fixed.
