### ISSUE TITLE
Add Task example causes fatal error when WC Admin disabled

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#6673]
**Describe the bug**

In PR #6563 it was identified that example code for the [Setup Tasks](https://developer.woocommerce.com/2021/02/26/use-setup-tasks-to-provide-a-first-class-on-boarding-experience-for-merchants/) documentation causes a fatal error when WooCommerce Admin is disabled with `add_filter( 'woocommerce_admin_disabled', '__return_true' );`

A workaround was added in PR #6563, however this won't resolve the issue until the change lands in core 5.3, scheduled for May. 

**To Reproduce**

With WC Admin bundled with WooCommerce

2. Disable WC Admin with `add_filter( 'woocommerce_admin_disabled', '__return_true' );`
3. Add the [example plugin](https://github.com/woocommerce/woocommerce-admin/blob/main/docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php) linked to in the documentation.
4. See fatal error

**Expected behavior**

Example plugin should check if WC Admin is active, perhaps with `WC()->is_wc_admin_active()`.

**Comment by hsingyuc** [comment]
I couldn't reproduce the error. Could someone let me know if anything missing? Thank you!

To Reproduce 
1. Deactivate WC Admin plugin
1. Disable WC Admin with `add_filter( 'woocommerce_admin_disabled', '__return_true' );` in your theme `functions.php` file
1. Add the example plugin linked to by run `npm run example -- --ext=add-task`
1. Activate the plugin
1. Don’t see the fatal error

**Comment by adrianduffell** [comment]
Hi @hsingyuc 

Thanks for looking into this!

It seems like it matters where the filter is placed. I can reproduce it with your steps if I add the filter to a [must-use plugin](https://wordpress.org/support/article/must-use-plugins/). For example:

**`wp-content/mu-plugins/test.php`**
```
<?php

add_filter( 'woocommerce_admin_disabled', '__return_true' );
```


This gives the error:

<img width="776" alt="Screen Shot 2021-03-30 at 7 04 26 pm" src="https://user-images.githubusercontent.com/9312929/112979253-e8ab8000-918a-11eb-8461-054b635d1f01.png">
