### ISSUE TITLE
Taxes: Modified tax rates are not preserved in Analytics

### ISSUE THREAD

**Issue by tijosh** [woocommerce/woocommerce-admin#6675]
**Describe the bug**

When an entered tax rate is modified at **WooCommerce > Settings > Taxes > Standard Rates**, the **Analytics** module assumes that previous orders with the rate should *still be associated* with that rate. 

Example: if I have an order come through under the rate US-NY 10%, and then I change the existing rate to US-PA 8% and get a new order, both orders will show in reports as being under the US-PA 8% line item. However, each individual order's details will show the rate as it was at the time of purchase.

**To Reproduce**

1. Create a standard tax rate for one region (US-NY 10%)
2. Complete an order with an address for that region
3. Modify the existing rate to a different region (US-PA 8%)
4. Complete a new order with an address from the updated region
5. See in **Analytics > Taxes** that both orders appear under the US-PA 8% rate
6. Check the rates in each order to see that the correct region is preserved in the charged tax

**Expected behavior**

I'd expect the rates to be itemized and reported according to the rate charged for the order.

**Screenshots**

First order:

![Screenshot](https://d.pr/i/Adzrof+)
*Link to image: https://d.pr/i/Adzrof*

Second order, after modifying tax line item:

![Screenshot](https://d.pr/i/N9tvqp+)
*Link to image: https://d.pr/i/N9tvqp*

The tax line item of the first order:

![Screenshot](https://d.pr/i/OXFy7q+)
*Link to image: https://d.pr/i/OXFy7q*

**Comment by hsingyuc** [comment]
I can reproduce the issue.  The problem is the tax rate id in the database stays the same after editing.

To be able to render old tax codes, should we consider keeping the old taxes in the database and create a new id for the new (edited) tax rate?  Also, should we update the tax code to perhaps end with the id number?  For example:

`US-NY-TAX-118` (10%)
`US-NY-TAX-119` (8%)

This looks like an issue that needs to be handled upstream in WooCommerce.

**Comment by joshuatf** [comment]
I can also recreate this issue.

As @hsingyuc noted, the tax rate information for an order is tied to a single ID in the database.  Editing an existing tax rate just modifies the information for that tax rate.  The taxed amount is stored in the order meta information, but the associated tax rate name is still linked to the same row in the database.

@hsingyuc's solution sounds like a good one; we forcibly create a new row/ID whenever a tax rate is changed.  This requires now changes on the WooCommerce Admin side that I can see, but would require pretty extensive changes in WooCommerce core.

Another solution (not as ideal) would be to store the tax code as part of the order meta information when an order is created.  This would require changes to how we join data in WooCommerce Admin.

With either solution, the current tax code does not seem semantic or help differentiate between tax codes in similar regions. `${country}-${state}-TAX-${n}`.  I wonder if there was a reason for this convention.

**Comment by joshuatf** [comment]
The obvious short-term fix for store owners is to not modify an existing row if you don't want analytics data grouped together, but create a new row.  Though I definitely see this as confusing and easily error-prone so I'm hopeful we can get a better solution in place.

**Comment by dani-elo** [comment]
I'm leaving here a reference to the ticket from the user that highlighted this issue for us so that we can keep them updated in case there's a fix/release: 3840006-zen
