### ISSUE TITLE
Console errors on opening an advanced filter

### ISSUE THREAD

**Issue by jrodger** [woocommerce/woocommerce-admin#6676]
**Describe the bug**
Opening an advanced filter produces console errors and doesn't display correctly.

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>
```

I'm wondering if this issue was introduced when moving to the WordPress card component in https://github.com/woocommerce/woocommerce-admin/pull/5903. That eventually uses the [Text component](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/text/index.js), which renders the paragraph tag referenced in the console error. Then because we're trying to render a select component inside that, we get the error. Before moving to the WordPress card component this paragraph tag wasn't present so there wasn't a problem.

**To Reproduce**

1. Go to 'Analytics > Orders'
2. Click on 'Show' dropdown list and select 'Advanced Filters'
3. See the "Orders Match All Filters" string is split over a few lines and the console error appears

**Expected behavior**
No console errors and the "Orders Match All Filters" string is displayed on a single line (with the select box rendered in the middle).

**Screenshots**
![image](https://user-images.githubusercontent.com/686419/112517912-c7185600-8d90-11eb-9db7-236c4cea4359.png)

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Chrome 89 and Firefox 86

**Extra Information**

We also see this issue on the WooCommerce Payments transactions filter.

**Comment by joshuatf** [comment]
Thanks for reporting this issue, @jrodger!  I can reproduce as well using the provided instructions.

**Comment by chihsuan** [comment]
I believe this has been fixed on the main branch. I tried to reproduce the issue using the provided instructions, the `validateDOMNesting` warning is disappeared and the "Orders Match All Filters" string is shown properly as below.

![Screen Shot 2022-01-06 at 17 21 02](https://user-images.githubusercontent.com/4344253/148359867-b40957a8-2b8f-4d49-9c47-4cb928dbc3be.png)

I'm going to close this. Please feel free to reopen this if I'm wrong.

**Comment by jrodger** [comment]
Thanks for trying to reproduce this @chihsuan. I've re-tested and I'm also not seeing the issue anymore 🎉
