### ISSUE TITLE
Redesign Mercado Payments setup to take credentials.

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#6680]
Related to #6648 Mercado Payments disables itself if the credentials are not set, making for a frustrating user interaction where enabling it in the payments task list does not persist since the user has not entered credentials. This is partially improved in https://github.com/woocommerce/woocommerce-admin/pull/6677 but won't be solved until we have a flow for the user to enter credentials.

This would likely mimic the behaviour of other payment tasks like the Stripe one. It would be a multi step setup that takes and validates user credentials before enabling the plugin.

Example from the Stripe plugin:

<img width="722" alt="Screenshot 2021-03-26 at 9 58 24 AM" src="https://user-images.githubusercontent.com/1281828/112542760-d42d5780-8e19-11eb-8a97-d78b64ee359b.png">

Pinging @pmcpinto to confirm on this one.

**Comment by ilyasfoo** [comment]
Estimate: 2

**Comment by samueljseay** [comment]
This one is proving to be much more difficult than I thought it would be. The functionality of Mercado Pago is a black box to me, so I would have to start looking through the code to see how/why it behaves as it does, but I think we might have a problem solving this.

What I've found so far:

1. You can't enable the mercado pago payment options by clicking the toggle. It just hangs and does nothing. I assume this is because some creds are required inside the "setup" for each one.

2. When in the setup for each payment type afaict they all ask for the same things; a country, is it production?, inputs for test keys, inputs for production keys.

3. When I try input values for test keys or production keys (based on my choice for "production"), nothing I enter gets saved. I assume its some kind of validation of the keys maybe against their servers, but there is absolutely no validation, they just don't save. As a result you still can't enable the payment method because there are no values saved.

This above flow is problematic unless we actually talk to the authors of Mercado Pago about how it works and how best to integrate, because we won't have any idea of if the creds are valid, and if a user makes a mistake, all we can say is that we tried to save the settings, but maybe they didn't save and so we're back to the same problem we started with, which is that the plugin doesn't stay enabled.

@pmcpinto @elizaan36 obviously every payment provider is a bit different, so its hard to have a 1 size fits all approach. For these more complicated scenarios I was wondering about having a new intermediate state in the payment list for plugins that we cannot actually enable for the user. It could say something **like** "This payment method is not enabled yet, you'll need to set it up in the appropriate settings page" and link to the page where they do the setup. Also note though, that Mercado Pago has a few different ways to set it up, we could choose one sensible default or just link the user to the list of payment settings and they can find it? Screenshot of the different options below:

<img width="1209" alt="Screenshot 2021-04-06 at 2 19 53 PM" src="https://user-images.githubusercontent.com/1281828/113652469-f495c580-96e7-11eb-9066-2268fe4321a2.png">

Once the user actually manages to save some credentials that will be easier for us, we can show the enabled state in that case, but I think we can't always enable the plugin after install, so we'd need this new state to be introduced. Thoughts?

**Comment by pmcpinto** [comment]
Yep, having an installed/finish setup state is the best option. @elizaan36 proposed having an "Enabled payment methods" card in the payments task: https://user-images.githubusercontent.com/5121465/112881748-aeaa8300-9091-11eb-9610-8c836d81fe75.png. See issue #6683

I think there are two different alternatives to handle this without complicating too much:
- Add a new card to display "Installed payment methods" that are still not enabled
- Reframe "Enabled payment methods" to "Installed payment methods" with two different states: "Enabled" and "(Finish) setup required"

Thoughts?

**Comment by elizaan36** [comment]
Annnd a third option that I shared in #6699.☺️

- Use the two cards for `Enabled payment methods` and `Additional payment methods`
- In the `Additional payment methods` card, use a "Setup required" indication with "Finish setup" for extensions that have been installed but not fully set up yet.

I'd lean towards this direction rather than introducing a new card or reframing the existing card. What do y'all think?

**Comment by pmcpinto** [comment]
> I'd lean towards this direction rather than introducing a new card or reframing the existing card. What do y'all think?

Makes sense to me. @samueljseay what do you think?

**Comment by samueljseay** [comment]
@pmcpinto @elizaan36 This sounds like a good direction to me. It sounds like the scope of this will touch all payment methods correct? Perhaps this ticket can be closed and a new one opened that covers everything we've talked about here?

**Comment by pmcpinto** [comment]
Sounds good to me 👍

**Comment by mattsherman** [comment]
@samueljseay @octaedro What is the status of this issue? The latest comments reference it being closed, but it is still open currently.

**Comment by samueljseay** [comment]
I'd like to know if this is even still relevant with the remote payment work that has been done by Gezora...

I'll ask them.

**Comment by samueljseay** [comment]
ccing @joshuatf @psealock for opinions on this, I think the new fallback state for plugins that don't implement the new API is good enough for users?

**Comment by samueljseay** [comment]
I think the summary here is that this could be solved by the plugin author if they utilised the new API provided by @joshuatf et al. I'm closing this for now, we'll settle on the fallback behaviour until it can be implemented in the plugin
