### ISSUE TITLE
Payments task: improving how we surface WCPayments

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6683]
**Description:** the WooCommerce Payments card in the Payments task is not performing as expected. We're going to implement some changes in the card to provide additional information and reinforce the value prop.

![Choose payment methods](https://user-images.githubusercontent.com/5121465/113369717-95baff80-9327-11eb-973c-42b750064237.png)

![Completed setup task list](https://user-images.githubusercontent.com/5121465/113369500-1cbba800-9327-11eb-97aa-c2aa99803fb5.png)

**Acceptance criteria:** 

- [ ] Implement the new layout + copy
- [ ] "Learn more" should link to: https://woocommerce.com/payments/
- [ ] Clicking "Get started" will redirect users to the WCPayments KYC flow (as we have right now)
- [ ] All other payment methods are located in a separate card titled "Additional payment methods".
- [ ] Update the WCPayments card to the layout displayed above when the user completes the setup
- [ ] Update the WCPayments card with the following if the user visits the payments task after installing the extension but without completing the setup:
Switch the "recommended" pill to "Setup required"
Update the CTA copy to "Finish setup"
([mockup](https://github.com/woocommerce/woocommerce-admin/issues/6683#issuecomment-811173292) in this comment)
- [ ] Redirect to the WCPayments dashboard when the user clicks "Manage"

**Additional event tracking:**
`wcadmin_tasklist_payment_learn_more`: triggered when the user clicks in the WCPayments learn more link
`wcadmin_tasklist_payment_manage`: triggered when the user clicks in the WCPayments manage link

**Additional links:**
Project thread: paJDYF-1eJ-p2
[Design mockup](https://www.figma.com/file/7QOkvxzz1ylS3QBS4zqW8R/Payments-experiments?node-id=1424%3A327)

**Comment by psealock** [comment]
Estimate: 2. The layout changes seem fairly basic. One question that comes to mind is if the "Enabled payment methods" section works the same if a gateway is enabled thats not WC Pay. Assuming it is, what becomes of the WC Pay card.

**Comment by pmcpinto** [comment]
Good question. I think it makes sense "Enabled payment methods" section working the same way for any payment option. And if they enable another option than WCPay we should continue displaying the WCPay card below the "Enabled payment methods" section. @elizaan36 what do you think?

**Comment by elizaan36** [comment]
thanks for bringing this up, Paul. We could keep WCPay pinned to the top:

![Choose payment methods Stripe enabled](https://user-images.githubusercontent.com/5121465/112881748-aeaa8300-9091-11eb-9610-8c836d81fe75.png)

I tried an option with [WCPay below enabled gateways](https://share.getcloudapp.com/9ZuxrJj0) and it doesn't really add anything to the experience. Keeping in mind this isn't a settings screen, and the intention is only to facilitate setup. Once their preferred gateway is installed (if it's not WC Pay) it would be better for the WC Pay option to be located in the same place as a reminder rather than moving around the screen.

**Comment by elizaan36** [comment]
One other thing to mention on the payments task list. There's a use case where WC Pay has been installed but not set up yet and the user revisits this payments task screen. I'm exploring an indication (also mentioned in #6699) that setup is required to encourage action and improve clarity on the in-between state. Let me know your thoughts.

![Choose payment methods - setup required](https://user-images.githubusercontent.com/5121465/113173212-c8250980-920e-11eb-979d-0037ce9f95b3.png)

**Comment by pmcpinto** [comment]
Thanks Elizabeth. I just updated the AC with this use case

**Comment by joelclimbsthings** [comment]
So, for the current implementation WCPay is treated as a "recommended," method, and although I'm sure you all know this is how that looks, I'll show you again:

![image](https://user-images.githubusercontent.com/444632/113458923-d9197a80-93c8-11eb-9882-54c72d720b3a.png)

My question is regarding the fact that WCPay isn't the _only_ potential recommended gateway. It will recommend WCPay OR one called Mercado Pago, with a fallback to Stripe if neither are present. 

So, with the new design, how to we want to treat Mercado Pago and Stripe?

cc @pmcpinto @elizaan36

**Comment by pmcpinto** [comment]
Good question. We should only change how we recommend WCPay. As for Stripe and Mercado Pago, the idea is to keep the recommended ribbon.

**Comment by elizaan36** [comment]
Here's the layout for this screen on mobile - in Figma as well.

![Mobile Payments task](https://user-images.githubusercontent.com/5121465/113760274-a8448880-96db-11eb-969b-ea16512b4d66.png)

**Comment by joelclimbsthings** [comment]
Just wanted to confirm since it's seemed a little odd to me. We _do_ want the WCPay card to display _at the same time_ as the recommended banner on an alternative method such as Stripe? Like so:

![image](https://user-images.githubusercontent.com/444632/114212199-66ebed00-9916-11eb-8d12-45702da6da2f.png)

cc @elizaan36 @pmcpinto

**Comment by elizaan36** [comment]
I think we're required to use the `recommended` for both as part of the contract. Can we use the recommended pill (same that we're using for WCPay) rather than the ribbon? I find the ribbon to be quite jarring and would be confusing for users - they might be thinking, why is this recommendation different than the other one?

**Comment by joelclimbsthings** [comment]
Yeah, my thoughts as well. I thought that this might be determined by the contract, although FWIW the previous state seemed to only list one as recommended at a time:

![image](https://user-images.githubusercontent.com/444632/114234724-ff449a80-9933-11eb-972e-f41a982619ae.png)

Glad to change it to the pill if we want to keep it, though.

**Comment by pmcpinto** [comment]
> Just wanted to confirm since it's seemed a little odd to me. We do want the WCPay card to display at the same time as the recommended banner on an alternative method such as Stripe?

@joelclimbsthings @elizaan36 we don't need to display Stripe as the "recommended" option when WCPayments is promoted.

**Comment by bmccotter** [comment]
Hi @pmcpinto  @joelclimbsthings @elizaan36 reiterating what Pedro said, we don't need to place the recommended banner on Stripe when promoting WCPay. Stripe's "recommended" banner should only appear in markets where WCPay is not available. Per our agreement, Stripe is the second most prominently featured payment service provider. We are also not contractually required to have the "recommended" banner on the Stripe plugin.

**Comment by elizaan36** [comment]
@joelclimbsthings let me know if you need a higher resolution version of the WC Pay logo. Also, do you need the payments icons? I'm using ones from a community Figma file in the designs.

**Comment by joelclimbsthings** [comment]
Thanks @elizaan36 , I've actually already extracted the SVGs from the figma directly, which seemed to work. Still trying to bottom out on exactly how to host/handle them, but I've got the images I need 👍🏻
