### ISSUE TITLE
Payments settings: add recommended payment methods

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6684]
**Description:** we have a significant % of new users going to the payments settings without visiting the payments task or before installing a payments extension. This is a good moment to surface important payment options to medium/high intent users.

![Settings - WC Pay](https://user-images.githubusercontent.com/5121465/113032921-0ca09e80-9156-11eb-8142-e2a2d1f4dd45.png)

**Acceptance criteria:** 
- [ ] Introduce a new card in the Payments settings with the WCPayments, Stripe and PayPal as recommendations
- [ ] The card is displayed regardless they have a payments extension installed
- [ ] Ideally we should use the system that exists for marketplace suggestions. I'm assuming that this will allow us to tweak the content without relying on a core release
- [ ] Include a "See more options" link at the bottom of the card. The link should redirect users to https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/?utm_source=payments_recommendations
- [ ] Automatically install the extension if users click "Get started". I'm not sure if this is possible if feed the card through the marketplace
- [ ] Display it only in countries where WCPayments is available: US, AU, CA, GB, IE and NZ(let's assess the effectiveness of this approach before having it in all countries)
- [ ] The user can dismiss the recommendations card through the ellipsis icon
- [ ] Don't show the suggestions card if the user has the marketplace suggestions settings disabled (settings > advanced > woocommerce.com > Marketplace suggestions > Show Suggestions)

**Event tracking:**
`wcadmin_settings_payments_recommendations_setup`
When the user clicks "get started"
Event prop: `extension_selected`: extension name

`wcadmin_settings_payments_recommendations_dismiss`
When the user clicks "dismiss"

`wcadmin_settings_payments_recommendations_pageview`
When the user visits the payments settings with the recommendations card enabled

**Comment by ilyasfoo** [comment]
Estimate: 2

**Comment by louwie17** [comment]
> Ideally we should use the system that exists for marketplace suggestions. I'm assuming that this will allow us to tweak the content without relying on a core release

I did some digging on how this is being done, and I could find two different places:
- The woocommerce [marketplace suggestions](https://github.com/Automattic/woocommerce.com/tree/trunk/plugins/wccom-plugins/marketplace-suggestions), using [this json](https://woocommerce.com/wp-json/wccom/marketplace-suggestions/1.0/suggestions.json).
- The [popular extensions plugin](https://github.com/Automattic/woocommerce.com/tree/trunk/plugins/wccom-plugins/popular-extensions) actually used to render these top 4 items [listed here](https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/?categories=Payments%7CWooCommerce+Extensions&collections=product&page=1), this displays the featured (one's with selected star) payment plugins [in woocommerce.com](https://woocommerce.com/wp-admin/edit.php?s&post_status=all&post_type=product&action=-1&product_support_queue&seo_filter&readability_filter&product_cat=payment-gateways&product_visiblity=featured&product_type&stock_status&wcpv_product_vendors&filter_action=Filter&paged=1&action2=-1).

I could go two way's here, if there are favorites?
- As the first suggestion add a payment-suggestions.json.php similar as the current [suggestions.json.php](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/marketplace-suggestions/includes/suggestions.json.php) we just update this when we want to change it.

Or
- Extend the popular extensions plugin to add a rest endpoint to retrieve the favourited extensions, this could be edited on woocommerce.com, but would also mean the woocommerce.com marketplace reflects the exact same thing. So dependent on woocommerce.com.

I am currently leaning towards the first option as that would allow us to keep things more tailored to WC Admin, and not be dependant on woo.com

cc: @pmcpinto  @woocommerce/ghidorah

**Comment by louwie17** [comment]
@pmcpinto could we update the estimate on this one to a 3? As the marketplace suggestion part might take a little longer.

**Comment by pmcpinto** [comment]
> I am currently leaning towards the first option as that would allow us to keep things more tailored to WC Admin, and not be dependant on woo.com

👍 Sounds good to me

> @pmcpinto could we update the estimate on this one to a 3? 

Sure. Feel free to change the story points of any issue if you see that it will take longer than expected. Tks

**Comment by louwie17** [comment]
@pmcpinto do you have a link to the icons used for WC Pay, Stripe and paypal payments in the wireframe? I could get them from Figma, but wanted to see if we already have a link to them somewhere?

**Comment by pmcpinto** [comment]
@louwie17 I checked [here](https://github.com/woocommerce/woocommerce/tree/23710744c01ded649d6a94a4eaea8745e543159f/assets/images) and it seems that we only have the logos. @elizaan36 can you provide the icons?

**Comment by louwie17** [comment]
Thanks @pmcpinto, also one more question, when the user clicks `get started` should we show anything while we install the plugin? or redirect anywhere after it is finished?
Or would it be worth to navigate the user to our dashboard payments set up flow (for the particular payment option)?

**Comment by elizaan36** [comment]
Just shared the [zip file with icons](https://share.getcloudapp.com/P8u5RxOy).☺️

Pedro can confirm but when the user clicks "Get started", the button will show a loading state as the extension is installed. I'm not sure what the "dashboard payments set up flow" is, but the behavior should be the same as installing the extension from the existing payments task screen and would redirect to the existing set up flow for the payment option.

**Comment by louwie17** [comment]
Sounds good, and for "dashboard payments set up flow" I was referring to the **Dashboard > Set up payments > (payment provider)** setup, with the step through.

**Comment by pmcpinto** [comment]
> I'm not sure what the "dashboard payments set up flow" is, but the behavior should be the same as installing the extension from the existing payments task screen and would redirect to the existing set up flow for the payment option.

@louwie17 I chatted with @elizaan36 about this today. Considering that we don't know if the user has the task list enabled, it's better to redirect them to their setup flow, as if they installed the extension from the wp-admin extensions area. WCPay would redirect to its welcome screen. As for PayPal and Stripe, I'm not sure if they're redirecting the user to their settings page. Makes sense?

**Comment by louwie17** [comment]
@pmcpinto thanks for the clarification, that makes sense.

**Comment by elizaan36** [comment]
Here's a layout of the Recommended extensions card for smaller screens - also in the Figma.

![Mobile WooCommerce Payments Settings](https://user-images.githubusercontent.com/5121465/113758868-06706c00-96da-11eb-8c4f-ef4a6b7ab6a4.png)

**Comment by pmcpinto** [comment]
@louwie17 just a heads up that I just added a new item to the AC:

> - [ ] Don't show the suggestions card if the user has the marketplace suggestions settings disabled (settings > advanced > woocommerce.com > Marketplace suggestions > Show Suggestions)

Sorry, I completely forgot about this one when I created the issue.

**Comment by louwie17** [comment]
@pmcpinto & @elizaan36 thanks for looking over the .com PR, one last question I did have in regards to 9916-gh-Automattic/woocommerce.com
This will always show the plugin suggestions in english, even if the user had a different language selected, is this ok? Otherwise we could add a `locale` param that default to english if no other exists. Although the current marketing market place suggestions alway's shows in english.

**Comment by pmcpinto** [comment]
> This will always show the plugin suggestions in english, even if the user had a different language selected, is this ok?

Sounds good to me. We can assess if it makes sense to translate them based on the usage of the recommendations across different countries.

**Comment by louwie17** [comment]
> The card is displayed regardless they have a payments extension installed

@pmcpinto do you mean to say with this, that we keep the plugins displayed in the list although they might of been installed/activated?
At the moment I don't show them if a user activated the plugin, but I can easily change that.

**Comment by pmcpinto** [comment]
> @pmcpinto do you mean to say with this, that we keep the plugins displayed in the list although they might of been installed/activated?
> At the moment I don't show them if a user activated the plugin, but I can easily change that.

The goal is to display the recommended card even if they have a payment plugin installed. For example, if they have PayPal installed we should show the recommended card with WCPay and Stripe. Sorry if the description wasn't clear. Let me know if you have more questions.

**Comment by louwie17** [comment]
@pmcpinto thanks that makes sense, that is how I currently have implemented it :)
