### ISSUE TITLE
WCPayments task - tweak copy

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6690]
**Description:** we want to test a different copy in the WCPayments task in order to see if it has any impact on driving more users to the setup.

Is it possible to tweak the copy through the WCPayments plugin instead of doing it through wcadmin/core?

![Captura de ecrã 2021-03-26, às 17.31.27.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/acc78144-a0c0-468b-9f2b-6a2f761fc5d9)

**Acceptance criteria:**

- [ ] Change the copy to : Get paid with WooCommerce Payments. We should keep the legal message.

**Comment by pmcpinto** [comment]
cc @elizaan36 in case you have a different suggestion in terms of copy :)

**Comment by ilyasfoo** [comment]
Estimate: 1

**Comment by elizaan36** [comment]
sounds good to me!

**Comment by moon0326** [comment]
> Is it possible to tweak the copy through the WCPayments plugin instead of doing it through wcadmin/core?

@pmcpinto Since the copy lives in wcadmin, this change has to be done wcadmin for now. I think we can create a new ticket to work on adding hooks so that the task copies can be updated if needed.
