### ISSUE TITLE
Tax still included in analytics when order is refunded

### ISSUE THREAD

**Issue by giacogiaco** [woocommerce/woocommerce-admin#6692]
**Describe the bug**
If an order is refunded, the tax report still shows the tax from the order as having been paid.

This is problematic because it leads to wrong tax reports. If I rely on the WooCommerce tax reports, I'd pay sales tax for orders that basically don't exist (as they've been refunded).

This basically makes the tax reports useless.

**To Reproduce**
1. Create an order that includes sales tax
2. Go to Analytics > Revenue and check the tax amount for that day
3. Refund the order
4. Go to Analytics > Revenue again and recheck the tax amount for that day
-> The tax amount is the same as before

**Expected behavior**
When refunding an order, the revenue and tax amount should be the same as they were before the order was placed.

**Screenshots**

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Chrome / Safari

**Comment by ilyasfoo** [comment]
Hi @giacogiaco, thank you for reporting this. I am unable to reproduce the issue, the refunded orders should not reflect under the revenue and tax reports. I have tested this in WooCommerce `5.1.0` and WooCommerce Admin `2.2.0`.

Can you confirm that when refunding an order, you have specified the number of products to refund? Also, the order status should turn to `Refunded`. A refunded order should look like the following:

![image](https://user-images.githubusercontent.com/3747241/112822419-8125ff80-90ba-11eb-9414-d9ff2c1b45af.png)

**Comment by joshuatf** [comment]
The other thing I think worth clarifying here- were you expecting the tax to be `0` on the original order date?  If I understand correctly, the expectation is that the original date's values should remain unchanged and any refunded amount (including tax) should appear on the date refunded.

**Comment by giacogiaco** [comment]
Hi @joshuatf and @ilyasfoo,

to make it clearer and to reproduce the issue, please see the screenshots attached. For February 13th:

- gross revenue is 545€, should be 486€
- net revenue is 457,99€, should be 408,01€


**Can you confirm that when refunding an order, you have specified the number of products to refund?** 
I don't know. I refunded it via PayPal. The rest is done by WooCommerce (including changing the order status).

**were you expecting the tax to be 0 on the original order date?**
Yes. My tax consultant said that refunds are not counted as costs. They are counted by lowering the revenue (basically as if the revenue never happened). Therefore, the only logical thing would be to reduce the revenue (and the included tax) on the day the revenue happened.

![13 feb woocommerce](https://user-images.githubusercontent.com/28538647/114272583-0d1f1c00-9a17-11eb-9136-3e951ad4f51f.jpg)
<img width="1099" alt="orders_dashboard" src="https://user-images.githubusercontent.com/28538647/114272585-0e504900-9a17-11eb-81bc-aef77eeea544.png">
<img width="689" alt="orders_table" src="https://user-images.githubusercontent.com/28538647/114272587-0f817600-9a17-11eb-9a5c-aefb016d7778.png">

**Comment by joshuatf** [comment]
Thanks for the clarification and images, @giacogiaco!

>Yes. My tax consultant said that refunds are not counted as costs. They are counted by lowering the revenue (basically as if the revenue never happened).

This is an interesting issue that varies widely from place to place.  Even within the US, states differ on whether or not refunds should deduct from the original date (and an amended tax return should be filed) or if the refund deduct tax burden on the new day (and a credit should be given in a future filing).

That said, I don't think the goal behind WooCommerce Admin is to be a replacement for tax software.  I'd love to hear from others on this, but I would think knowing when a refund occurred would be more valuable analytical information for most store owners.

>Therefore, the only logical thing would be to reduce the revenue (and the included tax) on the day the revenue happened.

Mentioned [here](woocommerce/woocommerce#32263) but I don't think is usually the case from an accounting perspective.

Was your hope here to export revenue from a previous period that would allow quickly amending taxes in a previous period?  I can see this being a useful tool when filing. cc @timmyc in case any exploration around this has been done.

**Comment by joshuatf** [comment]
I'm closing this issue since I haven't heard back from you in a while, but please feel free to comment back here if you'd like to continue the discussion and we can reopen this!
