### ISSUE TITLE
Settings Tab does not work

### ISSUE THREAD

**Issue by giacogiaco** [woocommerce/woocommerce-admin#6695]
**Describe the bug**
I can't open the WooCommerce Analytics Settings. Clicking the tab also breaks all other tabs.

**To Reproduce**
1. Go to Analytics > Settings
2. The page turns blank (Admin bar and Side bar are still there and do still work)
3. Clicking all other tabs (Revenue, Orders, Products, Categories, etc.) of the Analytics section doesn't work anymore

**Expected behavior**

**Screenshots**
[![Woo-Commerce-Analytics-Settings.png](https://i.postimg.cc/3NG8v32P/Woo-Commerce-Analytics-Settings.png)](https://postimg.cc/vxQwRFqz)

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Chrome (Version 89.0.4389.90)

**Comment by samueljseay** [comment]
Hi @giacogiaco sorry you're experiencing this issue. Do you know which version of woocommerce-admin you have installed? 

I know we have fixed some similar issues recently so there could be a fix in later versions.

**Comment by giacogiaco** [comment]
Hi @samueljseay, in WooCommerce > Status it says WooCommerce Admin-Package: 2.0.2. 
Is this the version of woocommerce-admin? Thanks!

**Comment by samueljseay** [comment]
@giacogiaco that's the one and you've got the version just before this issue was fixed so I'm fairly confident updating should solve the problem for you. If you're able to do that, it was patched in 2.0.3.

**Comment by samueljseay** [comment]
@giacogiaco I should have clarified how to update woocommerce-admin.

If you don't have woocommerce-admin installed separately, then you need to go through the plugins page in Wordpress, search for "woocommerce-admin" and then install the latest version. This should override whichever version is bundled with woocommerce.

**Comment by giacogiaco** [comment]
@samueljseay thanks for following up. There is no plugin called "woocommerce-admin" – any other way to update it?

<img width="1730" alt="Bildschirmfoto 2021-03-28 um 16 59 33" src="https://user-images.githubusercontent.com/28538647/112756843-325b6580-8fe7-11eb-8b98-1fc9d3fa2cf1.png">

**Comment by samueljseay** [comment]
You'll need to install the latest version from the plugin listing page. This is the plugin: https://wordpress.org/plugins/woocommerce-admin/

**Comment by samueljseay** [comment]
You could also try updating the woocommerce plugin to it's latest version.

**Comment by luboslives** [comment]
Chiming in to say installing the standalone plugin fixes the error on the page

**Comment by dreamersdigital** [comment]
Hi Guys. I have the same problem: the analytics tab in WooCommerce displays a blank page. But what's strange, I have a multisite with two webshops, and one works fine, while the second one shows a blank page. 🤷‍♂️

I have the newest version of WC 5.1.0. I also installed WooCommerce Admin, but it didn't help.

This what shows up in the Console when trying to select the Analytics tab:
![Screenshot 2021-04-05 at 18 06 09](https://user-images.githubusercontent.com/64613942/113595870-dd000380-9639-11eb-8de3-cf8801eda8a4.jpg)

**Comment by giacogiaco** [comment]
Will this be fixed in the next version without having to install the standalone plugin? 
We're trying to keep the number of plugins at a minimum. 

Thanks!
