### ISSUE TITLE
Pause inbox message: GivingFeedbackNotes.php

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6697]
**Description:** we're going to pause sending this notification in order to focus on collecting feedback about the WCPay setup. Triggering two messages about setup could confuse users.

**Comment by joshuatf** [comment]
@pmcpinto Is this just temporary?  Should we leave the note in place in expectation of showing it again at a future date or is it better to remove entirely for now?

**Comment by pmcpinto** [comment]
Yes, the idea is to be a temporary removal, so probably it's better to leave the note in place. Thanks
