### ISSUE TITLE
Replacing toggles with buttons on the payments task screen

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6699]
I was going to add a comment on #6683, then realized this was probably better suited to it's own issue.

For some context, secondary actions should be used consistently on the payments task rather than toggles for a more coherent UX. For example, WooCommerce Payments, Stripe, and Cash on delivery currently both use toggles. 
<img width="871" alt="image" src="https://user-images.githubusercontent.com/5121465/112903856-b415c680-90ad-11eb-9b7b-38c213d7c39a.png">

The new design uses `Enable` as an action for a simple switch that doesn't require setup, and `Set up` for actions that require additional set up steps.

Before enabling Cash on delivery:
<img width="707" alt="Screen Shot 2021-04-01 at 8 51 20 PM" src="https://user-images.githubusercontent.com/5121465/113371463-0bc16580-932c-11eb-8030-8cd2cd4f18bf.png">

After enabling Cash on delivery:
![Completed setup task list - Cash on delivery enabled](https://user-images.githubusercontent.com/5121465/113371528-34e1f600-932c-11eb-90a0-387464ed32c7.png)

A snackbar appears to confirm once the payment method is enabled. The enabled payment method moves into an "Enabled payment methods" card, separate from "Additional payment methods". (If not enabled, WCPay remains a separate card pinned to the top even when other payment methods are enabled.)

`Manage` takes you to the payment methods settings screen. For WooCommerce Payments it's `WooCommerce Settings>Payments>WooCommerce Payments`, and for Cash on delivery it's `WooCommerce Settings>Payments>Cash on delivery`. Users will have to go to these settings screens to enable and disable the payment method at checkout, rather than being able to toggle on and off from this screen.

@pmcpinto @psealock let me know if you have any thoughts or questions on this.

**Comment by joshuatf** [comment]
Looks good to me.

Estimate: 2

Easy enough to handle, but some maintenance needed with existing payment methods to match this new UI.

**Comment by elizaan36** [comment]
👋 Thanks @joshuatf 

After chatting in `paJDYF-1eV#comment-5258` with @louwie17 there's another possible indication to include. After installing an extension and then dismissing the setup, there's an in-between state that should be accounted for.

I tried a new indication in the list for "Setup required" - this would be after installing the Stripe extension but before completing setup. I think this needs more exploration but just to illustrate the concept. The "Set up" action doesn't change.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/5121465/113160925-89d61d00-9203-11eb-913e-22d589e13227.png">

Currently, there are different behaviors for different extensions. In this screenshot, I've installed Stripe, Paypal, Klarna, and Mollie but not completed setup for any of them. The Stripe and Paypal tasks haven't changed (WCPay doesn't change either once installed) but the others show the toggle in the off position.

<img width="1165" alt="Screen Shot 2021-03-31 at 9 33 00 AM" src="https://user-images.githubusercontent.com/5121465/113161916-6f507380-9204-11eb-8c4e-d13817ac64ed.png">

Would be good to have a more consistent indication here, what do you think?
