### ISSUE TITLE
Note creation attempt causes fatal error if `woocommerce_admin_disabled` is true

### ISSUE THREAD

**Issue by waclawjacek** [woocommerce/woocommerce-admin#6703]
**Describe the bug**

When trying to create a note using `NoteTraits`, if WC Admin is disabled using this filter:

```php
add_filter( 'woocommerce_admin_disabled', '__return_true' );
```

The note creation will fail with a fatal error.

I ran into this issue while working on https://github.com/Automattic/woocommerce-services/pull/2402.

This has to be worked around by users of the `Automattic\WooCommerce\Admin\Notes\NoteTraits` trait or note classes by checking if either:

* `woocommerce_admin_disabled` is true,
* the `admin-note` data store exists.

It would be nice if users of the trait/classes would not have to worry about whether the data store is defined (which I guess is a bit of WC Admin's implementation detail) when trying to create a note.

Maybe WC Admin could catch `WC_Data_Store::load( 'admin-note' )` exceptions (or check for the data store existence otherwise) in each call to the trait's methods? I see this was already implemented for one note in #6532.

**To Reproduce**

1. Add this to a test site:

    ```php
    add_filter( 'woocommerce_admin_disabled', '__return_true' );
    ```
1. Try to create a note using the trait during the `plugins_loaded` hook.

**Expected behavior**

A fatal error is not thrown regardless of whether the `admin-note` data store is defined. Maybe a `WP_Error` or a custom exception could be thrown instead?

**Comment by adrianduffell** [comment]
Hi @waclawjacek , thanks for reporting this and sorry you were bitten by this bug.

It's a tricky one. Throwing an exception seems correct in that Admin Notes was used when it hasn't been initialized properly. I agree though the fatal error is not ideal and more could be done on the WP Admin side to prevent this. 

I'd recommend in your consuming code to first check if WC Admin is enabled. You can use `WC()->is_wc_admin_active()` and bail early if that returns `false`.

We're also looking to improve our documentation in issue https://github.com/woocommerce/woocommerce-admin/issues/6673

**Comment by waclawjacek** [comment]
Hi @adrianduffell, thanks so much for looking into it!

Adding information to the docs about having to check `WC()->is_wc_admin_active()` first will be super useful and generally if everyone knows they have to do this, this should be enough.

However, maybe adding a custom `WP_Error` instance (or a custom exception) to the list of possible return values from the calls to `Automattic\WooCommerce\Admin\Notes\NoteTraits` would still be useful? This way the consuming code doesn't have to check if WC Admin is enabled, just check if note creation succeeded (if at all).

One thing that will have to be checked is if both notes and the `is_wc_admin_active()` method were always a part of WC Admin. Otherwise some extra checks might be required to make sure a note can be added (e.g. `method_exists()`).

**Comment by adrianduffell** [comment]
> However, maybe adding a custom WP_Error instance (or a custom exception) to the list of possible return values from the calls to Automattic\WooCommerce\Admin\Notes\NoteTraits would still be useful? This way the consuming code doesn't have to check if WC Admin is enabled, just check if note creation succeeded (if at all).

This sounds good. Any chance are you interested in creating a PR for it?

I'd favor throwing a custom exception instead of WP_Error since we are now looking to catch the Notes exceptions in https://github.com/woocommerce/woocommerce-admin/issues/6749 and handle them better.

**Comment by waclawjacek** [comment]
I'll be happy to! I'll whip something up today or tomorrow and reference this issue.

**Comment by waclawjacek** [comment]
@adrianduffell I have a delay on the PR work. My apologies for that! I will publish the finished PR on Monday. In the meantime, here is a [draft PR](https://github.com/woocommerce/woocommerce-admin/pull/6771) implementing the gist of it.

**Comment by adrianduffell** [comment]
@waclawjacek Thanks, the PR is looking good! It's much appreciated.

Feel free to take your time with it if you need to prioritize other work. Our deadline for PRs to make the next release is the end of this week.

**Comment by waclawjacek** [comment]
@adrianduffell Thanks! I have just updated PR and marked it as ready for review.
