### ISSUE TITLE
Embedded root header not fullwidth

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#6719]
**Describe the bug**
The embedded root header is not full width when the wp-admin menu is collapsed in version 2.1.4

**To Reproduce**

1. Install the WooCommerce 5.2 RC - https://github.com/woocommerce/woocommerce/releases/tag/5.2.0-rc.1
2. Go to the WooCommerce -> Orders screen
3. Collapse the WP menu
4. See screenshot

**Expected behavior**
The header should be full width

**Screenshots**

<img width="1613" alt="Screen Shot 2021-03-31 at 2 46 08 PM" src="https://user-images.githubusercontent.com/343847/113189511-a5f0b300-9231-11eb-91f6-01b2da6197ac.png">

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Big Sur
* Browser [e.g. chrome, safari] Chrome
* Version [e.g. 22] 89.0.4389.90

**Comment by hsingyuc** [comment]
I have a fix for this; push shortly.
