### ISSUE TITLE
Onboarding wizard proceed button padding

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#6720]
**Describe the bug**
The continue/proceed button in the onboarding wizard is missing padding on the right of the button

**To Reproduce**

1. Install the WooCommerce 5.2 RC - https://github.com/woocommerce/woocommerce/releases/tag/5.2.0-rc.1
2. Go to the WooCommerce -> Orders screen
3. Use Help to start the onboarding wizard
4. See screenshot

**Expected behavior**
Consistent padding on the Continue/Proceed button

**Screenshots**

<img width="533" alt="Screen Shot 2021-03-31 at 2 48 05 PM" src="https://user-images.githubusercontent.com/343847/113190233-78f0d000-9232-11eb-8f0a-ca729e33e7f7.png">

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Big Sur
* Browser [e.g. chrome, safari] Chrome
* Version [e.g. 22] 89.0.4389.90

**Comment by joshuatf** [comment]
Thanks for the issue, @rrennick!

I tested locally and on JN and was not able to reproduce.  Are there other plugins that need to be installed to see this?  Perhaps a specific version of GB?

<img width="579" alt="Screen Shot 2021-03-31 at 6 11 14 PM" src="https://user-images.githubusercontent.com/10561050/113217926-a3e81d80-924c-11eb-8ab6-0cf3696a28eb.png">

**Comment by adrianduffell** [comment]
I'm also not able to reproduce this. 

<img width="530" alt="Screen Shot 2021-04-01 at 2 20 23 pm" src="https://user-images.githubusercontent.com/9312929/113251794-799e6a80-92f5-11eb-83a7-358f8dffa10f.png">

Tested with Chrome & Safari under macOS Catalina, WordPress 5.7, WooCommerce 5.2 RC 1.

**Comment by rrennick** [comment]
> Are there other plugins that need to be installed to see this?

It was with the core E2E docker test container. When I ran the tests in `-dev` mode, Chromium was also the sale. Plugins installed are in https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/docker/initialize.sh.

**Comment by rrennick** [comment]
@joshuatf I think this one is okay to close if there were no other reports. I haven't seen it in any of the test runs this week.

**Comment by rrennick** [comment]
Closing this as I haven't seen it again.
