### ISSUE TITLE
Reports in Analytics > Orders don't return variations with "Any X"

### ISSUE THREAD

**Issue by aheckler** [woocommerce/woocommerce-admin#6722]
When using a variable product with variation attributes set to `Any X`, like so:

![Markup on 2021-03-31 at 16:42:27](https://user-images.githubusercontent.com/5512652/113208728-21f1f780-9240-11eb-8fb3-3231d9d3e733.png)

... Analytics > Orders will not return correct data when you specify an specific attribute:

![Markup on 2021-03-31 at 16:42:39](https://user-images.githubusercontent.com/5512652/113208912-62ea0c00-9240-11eb-8326-f15f0ccf152c.png)

From @joshuatf in Slack:

> Can confirm the issue.  Seems like our filtering looks for specifically set attributes on products, which this type of "any" variation would not contain.

3849522-zen

**Comment by joshuatf** [comment]
Thanks again for creating this issue!

For some context on this issue, the "Any" value for an attribute seems to work by not assigning any attribute value to a product.

The orders data store accepts an `attribute_is` filter that uses `get_attribute_subqueries()` to create a segment of SQL query that joins product meta based on matching values.

https://github.com/woocommerce/woocommerce-admin/blob/4a019b2a9cb3353c3c98b4b5923b811f621a7ac6/src/API/Reports/DataStore.php#L1217

We might be able to resolve this by writing a union for products that have the attribute but no value defined.
