### ISSUE TITLE
Payments task - tracks missing

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6727]
**Describe the bug**
Some events are missing when the user is interacting with the Payments task.

**To Reproduce**

1. Create a new store with event tracking enabled
2. Select United Stats or UK as the store country
3. Visit the Payments task and click to setup Stripe or PayPal
4. See that we don't trigger a pageview when the user visits the payments stepper
5. Click "Connect" in the 2nd step of PayPal or Stripe
6. See that we don't trigger an event when the user clicks "Connect"

**Expected behavior**
- Trigger an event when they visit the payments stepper:
It can be a new event (`wcadmin_payments_task_stepper_view`) or a new `path` value (eg payments_stepper) in `wcadmin_page_view `
- Trigger `wcadmin_tasklist_payment_connect_method` when they click "Connect" in Stripe or PayPal (AFAIK this is the event that we're triggering when they click on the CTA of the 2nd step on other gateways, like Klarna or Mollie)

**Comment by joshuatf** [comment]
@pmcpinto I'm seeing the connection event that we trigger in others.  The only difference is that this is only fired upon successful connection when returning back from the payment provider's website.

<img width="540" alt="Screen Shot 2021-04-01 at 11 42 40 AM" src="https://user-images.githubusercontent.com/10561050/113319523-81ebab00-92df-11eb-8897-216e86b44188.png">

Were you expecting something different or does this event not fire for you at all?

**Comment by pmcpinto** [comment]
Gotcha. So ideally we should have a new event to track when they click to start the connection flow: `wcadmin_tasklist_payment_connect_start`
Event prop: `payment_method`: payment gateway name

Let me know if you have more questions. Thanks.

**Comment by octaedro** [comment]
Hi @pmcpinto,
I was working on this issue and just wanted to confirm that you checked out the event `wcadmin_tasklist_payment_setup`. That event will be recorded after pressing the `Set Up` button for a payment gateway, sending the selected option.

![Captura de Pantalla 2021-04-13 a la(s) 12 00 07](https://user-images.githubusercontent.com/1314156/114574664-d54ee900-9c4f-11eb-82db-c5881c5d6c3b.png)

The addition of the event `wcadmin_payments_task_stepper_view` only will be useful if the user refreshes that page, otherwise, it would be a little bit redundant.

Also, I wanted to confirm if we need to record the starting of every payment connection flow or only for PayPal and Stripe. I understood that we need it for each of them but just wanted to confirm.

**Comment by octaedro** [comment]
> Also, I wanted to confirm if we need to record the starting of every payment connection flow or only for PayPal and Stripe. I understood that we need it for each of them but just wanted to confirm.

I'm asking this because there are other connection flow beginnings that we are not tracking (like Square).

**Comment by pmcpinto** [comment]
@octaedro sorry, I missed your pings

> I was working on this issue and just wanted to confirm that you checked out the event wcadmin_tasklist_payment_setup. That event will be recorded after pressing the Set Up button for a payment gateway, sending the selected option.

That event is working properly. I was referring to the button on the 2nd step: https://d.pr/i/uqq8kX

> The addition of the event wcadmin_payments_task_stepper_view only will be useful if the user refreshes that page, otherwise, it would be a little bit redundant.

I'm suggesting adding this event because currently we don't have a way to identify how many pageviews the stepper is getting, if the users are visiting it more than once, etc. Unless I'm missing something

> Also, I wanted to confirm if we need to record the starting of every payment connection flow or only for PayPal and Stripe. I understood that we need it for each of them but just wanted to confirm.

Can you also include Square? i think it's the only one missing. Thanks!

**Comment by octaedro** [comment]
Hi @pmcpinto,

Thank you for your response.

> Can you also include Square? i think it's the only one missing.

Also, we're missing eWAY (for AU and NZ) and generic gateways like PayFast (for ZA) and PayStack (for ZA, GH, and NG).
I'll add the event recording to the starting of those connections flows too.
