### ISSUE TITLE
Showing an Inbox Notification even when it shouldn't

### ISSUE THREAD

**Issue by tgglv** [woocommerce/woocommerce-admin#6728]
**Describe the bug**
Once working on the PR https://github.com/Automattic/woocommerce.com/pull/9882, I've discovered that even when I added a `[ 'type' => 'fail' ]` rule, notifications were still shown after running a WC daily CRON job.

**To Reproduce**
Even though all the steps are described in the PR mentioned below, I'll write down an outline:
1. Prepare a `woocommerce.test` instance which will provide `notifications.json`
2. Add a [rule](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/inbox-notifications/includes/notifications.json.php#L13) that won't work (in the PR above, I used excluding date range, and also added `fail` type)
3. Dismiss all the messages on WC Home page (`/wp-admin/admin.php?page=wc-admin`) of a customer's WP
4. Run the WC daily CRON job on a customer's WP:
```sh
$ wp --allow-root option delete wc_remote_inbox_notifications_specs wc_remote_inbox_notifications_stored_state && \
wp --allow-root cron event run wc_admin_daily
```

5. You should see notification message that shouldn't be shown

**Expected behavior**
Instead of step 5th's result above, you shouldn't see notifications that shouldn't be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/15897544/113212058-efb3ba80-927e-11eb-86c0-f4ebcf740647.png)

**Additional context**
Debugging the code, I've found out that in `/src/RemoteInboxNotifications/EvaluateAndGetStatus.php` in `evaluate` function, despite the `$evaluated_result`'s value, I still had `unactioned` as status. And, as a result, a notification will be shown.

Indeed, I don't have experience in developing this extension, so get my findings with a pinch of salt 🧂.

Here is a list of debug output:
```
Rule: "publish_after_time", result: "true"
Rule: "publish_before_time", result: "true"
Rule: "plugins_activated", result: "true"
Rule: "or", result: "true"
Rule: "plugins_activated", result: "true"
Rule: "not", result: "false"
Rule: "plugin_version", result: "false"
Rule: "or", result: "false"

Evaluated result: "false"

Status: 'unactioned', Previous: 'unactioned'
```

Scheme of these calls:
- check start date: `true`
- check end date: `true`
- check OR:
  - check "plugins activated": `true` => OR returned `true`
- check OR:
  - check NOT
    - check "plugins activated": `true` => NOT returned `false`
  - check "plugin version": `false` => OR returned `false && false`
- Evaluation result: `false`

Despite that, in `/src/RemoteInboxNotifications/SpecRunner.php`, the `run_spec` function continues to show a notification. Anyway, maybe I got something wrong.

Please let me know if I could help with debugging or any other assistance.

**Comment by joshuatf** [comment]
Thanks so much for opening this issue and outlining your findings in detail @tgglv!

cc @becdetat on this issue as the resident expert on all things remote inbox 🥇

**Comment by becdetat** [comment]
@tgglv I'm so sorry, I missed @joshuatf 's ping. If I understand this correctly, you're displaying a notification, adding a fail rule, then re-running the engine, and expecting the notification to disappear?

By design, the rules are only evaluated to see if a notification should be displayed, not if it should be dismissed. So you can only add a notification via the rules engine, not delete it. There's no technical reason why we shouldn't be able to dismiss a displayed notification via the rules engine. Do you have a requirement to do this?

**Comment by tgglv** [comment]
Thanks for the answer, @becdetat.

>  If I understand this correctly, you're displaying a notification, adding a fail rule, then re-running the engine, and expecting the notification to disappear?

Originally, I saw a notification, clicked "Dismissed all" and then after re-running the engine it was shown again. But not I realized that the problem might be connected with the DB state (WP_PREFIX_wc_admin_notes table). Clearing that table resolves the problem I had.
