### ISSUE TITLE
Showing task and activity notifications in the Inbox panel

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6737]
As part of the task list updates, this is an update to the global Inbox panel. With the upcoming changes to the task list in #6633, the only place to view high priority and extension setup tasks will be the home screen. This notification will help to ensure that  these tasks won't be missed.

If there are new tasks in the extended task list, or any store activity such as orders to fulfill, stock notifications, or product reviews, an abbreviated card will appear at the top of the Inbox panel and will show a notification dot on the Inbox icon.

<img width="405" alt="Screen Shot 2021-04-01 at 5 17 12 PM" src="https://user-images.githubusercontent.com/5121465/113359788-2258c400-930e-11eb-843e-8b0215adb6db.png">

Choosing "Things to do next" will direct users to the home screen with the extended task list anchored to the top of the view.

Choosing "Orders to fulfill" will direct users to the Orders list filtered to `Processing`. Stock and Reviews will direct users to the home screen.

@pmcpinto @timmyc @samueljseay for feedback.

**Comment by timmyc** [comment]
This is looking good @elizaan36 

Since the mockup above doesn't show it, I wanted to confirm that the "unread indicator" in the Inbox Icon should also be "ON" for the following scenarios with this change:

- If there are unread/new inbox notifications ( current functionality )
- If there are any "Things to do next"
- If there are any Orders to process
- If there are any Reviews to moderate
- If there are any stock Notices
- If there are any Store Alerts

I think that covers all the scenarios?

**Comment by elizaan36** [comment]
Thanks, Timmy. Yep, that looks exactly right. 👍

**Comment by elizaan36** [comment]
@pmcpinto Is there a tracks event for the Inbox panel? I couldn't find it in the spreadsheet. I imagine we'll want to track clicks on each item in the list that Timmy shared, something like `Inboxpanel_Open`, `Inboxpanel_Task_Click`, etc.

**Comment by timmyc** [comment]
We do have track coverage on the Inbox Panel already: `wcadmin_activity_panel_open` and the notes have tracks coverage too. But the new items shown in the panel: things to do, orders to fulfill should get some tracks coverage indeed. Great call @elizaan36

**Comment by pmcpinto** [comment]
Yep. I think we can consolidate all the actions under one event: wcadmin_activity_panel_click and then have an event prop to identify the task that was clicked by the user: things to do, inbox message, etc. Makes sense?

**Comment by octaedro** [comment]
Hi @elizaan36,

I'm working on this issue and wanted to ask you about the copy and icon I should use for every abbreviated card.

In the design we already have the cards: "Things to do next" and Orders to process, and I would need: Reviews to moderate, stock Notices, and store Alerts.

Is there a P2 or Slack thread where I can get that information?
Thanks

**Comment by elizaan36** [comment]
👋 That was hidden in a Figma and I'll share the doc in Slack.

In this screenshot, rather than creating a new card for Store Alerts I'm indicating the # critical tasks (L1) on the Things to do task list. This count appears in a pill that would otherwise be hidden if there are no critical tasks.
<img width="242" alt="Screen Shot 2021-05-11 at 10 03 36 PM" src="https://user-images.githubusercontent.com/5121465/117912321-eae21d80-b2a4-11eb-8a3d-8c59a3969a6e.png">
In this example the total count is 6 things to do next, of which the critical alert is one of them. So there's a total of 6 tasks shown in the body copy.

Also want to confirm that if there is no store activity (tasks, orders, reviews, stock) their respective cards would be hidden. There's no empty state as that wouldn't be useful for merchants and would distract from the Inbox notes below.

I also reduced the padding between cards to create more visual cohesion with store activity more contained in its own section separately from the Inbox.

What do you think?

**Comment by octaedro** [comment]
Thank you for your answer @elizaan36.

To write down what we talked about by DM, the abbreviated panel design will be a little different and the Inbox panel width will be ~80px smaller.

Also, I would like to confirm what happens if the user clicks on one of the abbreviated panels but they didn't finish the store setup. In that case, the panels won't be visible until the setup task list was hidden. Should we show the selected panel anyway?

**Comment by elizaan36** [comment]
> To write down what we talked about by DM, the abbreviated panel design will be a little different and the Inbox panel width will be ~80px smaller.

Yep thanks for reiterating our chat, and here's a screenshot of the updated design to confirm. ☺️
![Home - Setup tasks extensibility](https://user-images.githubusercontent.com/5121465/118186525-72de3980-b403-11eb-9504-c6c182a643f4.png)

> I would like to confirm what happens if the user clicks on one of the abbreviated panels but they didn't finish the store setup.

The store activity abbreviated panels should be hidden until store setup is complete (to match the home screen behavior), but it's highly unlikely there would be much activity to show at this early stage.

The same doesn't apply to the things to do and critical tasks though, since the extended task list appears alongside the store setup task list.

**Comment by octaedro** [comment]
Hi @elizaan36,

Just to confirm, if the user has a new Store alert (`critical alert`) but the panel `Things to do next` hidden, the pill `# critical alert` won't be visible, no?

**Comment by elizaan36** [comment]
hey @octaedro , just created [this issue](woocommerce/woocommerce#32252) to address that. With this change, you wouldn't be able to dismiss the extended task list when there's a store alert. (Or if there's a required task.) What do you think?

**Comment by octaedro** [comment]
Great @elizaan36! Sounds good to me, I like the idea 👍
Thanks
