### ISSUE TITLE
Dismissing Inbox messages should not need triple confirmation

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-admin#6739]
**Is your feature request related to a problem? Please describe.**
To dismiss an inbox notification, you must click 1. Dismiss, 2. Dismiss this message, and 3. confirm you really do want to delete.

**Describe the solution you'd like**
A reduction to 2 clicks seems better, perhaps even 1. If you had  standalone "dismiss all" then you could get rid of the Step 2 I described above as clicking on "dismiss" could then prompt the confirmation modal.

**Additional context**
![Screen Recording 2021-04-02 at 10 07 21 05 AM](https://user-images.githubusercontent.com/507025/113433418-672b3c00-939c-11eb-9489-649a61ab2d34.gif)

**Comment by joshuatf** [comment]
Thanks for bringing this up, @helgatheviking!  This is an issue we have discussed before and I think most of us agree there are too many clicks necessary here to dismiss messages.

>If you had standalone "dismiss all" then you could get rid of the Step 2

💯  definitely feels a tiny bit odd to have "Dismiss All" under each note.

@elizaan36 Do you have any thoughts on this?  I think this would be a relatively quick and painless change that could improve UI.

**Comment by elizaan36** [comment]
Yes agreed on this, thanks for creating the issue @helgatheviking.

This is an issue I've had on my mind for a while as part of a larger scope project to improve the Inbox with additional filtering, categorization, and controls. HOWEVER, a "tiny win" could be to remove the confirmation modal upon dismissing an individual message. It's unnecessary and adds a bit of friction that doesn't provide any benefit to users. What do you think? @pmcpinto do you have any thoughts on this? I do think we should keep the confirmation modal when the user chooses to dismiss all messages.

> 💯 definitely feels a tiny bit odd to have "Dismiss All" under each note.

It's strange to have Dismiss all repeated with each note, but as I mentioned moving that action would have to be part of a more holistic UX update to the Inbox. For example, that action could be moved into an Inbox header where other filtering controls could be located.

**Comment by pmcpinto** [comment]
> HOWEVER, a "tiny win" could be to remove the confirmation modal upon dismissing an individual message. It's unnecessary and adds a bit of friction that doesn't provide any benefit to users. What do you think? @pmcpinto do you have any thoughts on this? I do think we should keep the confirmation modal when the user chooses to dismiss all messages.

Sounds good to me 👍

**Comment by rjchow** [comment]
I think this issue has been closed by https://github.com/woocommerce/woocommerce-admin/pull/7868
Can you confirm please? @moon0326

**Comment by moon0326** [comment]
> I think this issue has been closed by #7868 Can you confirm please? @moon0326

Yup! the suggested change has been made in #7868

**Comment by moon0326** [comment]
I'm closing this as the change has been made already.

Please feel free to re-open it if needed.
