### ISSUE TITLE
Minified React error on Analytics settings

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce-admin#6740]
Opening the WooCommerce Analytics settings page will show only a blank gray page. Safari console shows me this error in `react-dom.min.js:125` and `react.min.js:24:210`:

`Error: Minified React error woocommerce/woocommerce#185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

WP: 5.7
WC: 5.1
Browser: Safari 14.1

**Comment by moon0326** [comment]
Closing this as this issue has been fixed in https://github.com/woocommerce/woocommerce-admin/pull/6540
