### ISSUE TITLE
Note dates are not read as UTC and increment on every update

### ISSUE THREAD

**Issue by slightlyfaulty** [woocommerce/woocommerce-admin#6742]
**Describe the bug**
In [`Notes\DataStore::read()`](https://github.com/woocommerce/woocommerce-admin/blob/56f15c85720b764663cf76e3f60ec3a826bb00d2/src/Notes/DataStore.php#L109-L110) date values (`date_created` and `date_reminder`) are passed directly to [`WC_Data::set_date_prop()`](https://github.com/woocommerce/woocommerce/blob/1c40a28409a34b0c47f5167319d99ac6b1ddc779/includes/abstracts/abstract-wc-data.php#L811) causing them to be parsed as local date strings.

One noticeable side-effect is that `date_created` is incremented by the time difference between local and UTC whenever any note prop is updated.

**To Reproduce**
```php
use Automattic\WooCommerce\Admin\Notes\Notes;

for ($i = 0; $i < 5; $i++) {
	$note = Notes::get_note(123);

	echo $note->get_date_created()->format('Y-m-d H:i:s T'), '<br>';

	$note->set_status('actioned');
	$note->save();
}
```
Output:
```
2021-04-04 08:00:00 PDT
2021-04-04 15:00:00 PDT
2021-04-04 22:00:00 PDT
2021-04-05 05:00:00 PDT
2021-04-05 12:00:00 PDT
```

**Expected behavior**
UTC date strings should first be converted to timestamps before being passed through to `WC_Data::set_date_prop()` so that they are handled as UTC instead of local dates.

This is what the the [product data store](https://github.com/woocommerce/woocommerce/blob/1c40a28409a34b0c47f5167319d99ac6b1ddc779/includes/data-stores/class-wc-product-data-store-cpt.php#L174-L175) does for example.

**Comment by moon0326** [comment]
@slightlyfaulty Thank you for taking the time to report this bug, we really appreciate your help. Unfortunately, I wasn't able to reproduce this bug on my end with your example.

I see that `123` is just for an example, so I used an existing note I.D and I received UTC date as expected. 

This is the code I used (notice I replaced 123 to a note that is in my local D.B)

```
use Automattic\WooCommerce\Admin\Notes\Notes;

for ($i = 0; $i < 5; $i++) {
	$note = Notes::get_note(58);

	echo $note->get_date_created()->format('Y-m-d H:i:s T'), '<br>';

	$note->set_status('actioned');
	$note->save();
}
```

Output:

```
[13-Apr-2021 00:22:09 UTC] 2021-04-13 00:04:01 GMT+0000
[13-Apr-2021 00:22:09 UTC] 2021-04-13 00:04:01 GMT+0000
[13-Apr-2021 00:22:09 UTC] 2021-04-13 00:04:01 GMT+0000
[13-Apr-2021 00:22:10 UTC] 2021-04-13 00:04:01 GMT+0000
[13-Apr-2021 00:22:10 UTC] 2021-04-13 00:04:01 GMT+0000
```

I've tested it on WooCommerce 5.1.0 and the latest WooCommerce Admin.

Could you please provide a reproducible example so that we can be on the same page?

**Comment by slightlyfaulty** [comment]
@moon0326 Well of course you aren't able to reproduce it, your WP local timezone is set to UTC 😅

**Comment by moon0326** [comment]
> @moon0326 Well of course you aren't able to reproduce it, your WP local timezone is set to UTC 😅

🤦 That's a mistake on my end. I will try to reproduce it with a different timezone. Thank you for a quick reply 👍

**Comment by moon0326** [comment]
@slightlyfaulty Ok, I was able to reproduce it 👍 

We probably won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported, but I will try my best to include it in the upcoming release.

Thank you again for reporting this issue.
