### ISSUE TITLE
Content jump on page load for products and order admin lists

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-admin#6743]
**Describe the bug**

Related https://github.com/woocommerce/woocommerce/issues/29588

On page load/refresh, a content shift is visible on some admin pages such as Products and Orders lists. 
The content jumps when the page is loading, there is a shift between the top of the WP content area and the WC Admin white header. 

On the Products list, the `Import/Export` buttons load slower than the `Add` button, with WooCommerce Admin disabled, the jump isn't seen.

**To Reproduce**

1. Go to Products
2. Refresh page and notice page jump
3. Disable the WooCommerce Admin interface via a plugin - https://gist.github.com/joshuatf/006111b6f43c3ab3d2cad39e3443822b
4. Refresh and notice the jump is no longer present but the button load is still present

**Expected behavior**

All content is loaded at the same time. 

**Screenshots**

With WooCommerce Admin
![Page_load_jump_products_page](https://user-images.githubusercontent.com/52214/113552814-989b4600-95ee-11eb-9ca2-858a58854943.gif)

With WooCommerce Admin disabled:

![Import_Export_buttons_slower_loading](https://user-images.githubusercontent.com/52214/113552839-a3ee7180-95ee-11eb-9809-d78b49a5862c.gif)

**Desktop (please complete the following information):**

* OS: [e.g. iOS] - add
* Browser [e.g. chrome, safari] - all

**Comment by apmwebdev** [comment]
The user came back to note that the issue is "more pronounced when all of the plugins are enabled as some of the plugins add additional heading information to the page which causes a more pronounced shift."

**Comment by moon0326** [comment]
@dougaitken Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end.

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.
