### ISSUE TITLE
Configure packages modules that have TS types to publish the type declarations with the module.

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#6745]
Now that we're moving more code to TypeScript it makes sense to expose the type declarations so consumer's can use them.

There are a couple of things to do:

1. Each package.json in `packages` must add a `types` field pointing to its generated type declaration.
2. tsconfig.json currently is set to `"noEmit": true` but we'll need it to compile type declarations. Remove this prop and add `"emitDeclarationOnly": true`,and `"declaration": true,` which will only build type declarations.
3. I'm less certain of the exact steps here, but I think its best if we include a tsconfig per package as well. Each package can configure where it's type defs are built to. I'm looking at monorepos such as https://github.com/typescript-eslint/typescript-eslint for inspiration on this.

**Comment by psealock** [comment]
I just imported the new ExPlat package via `yarn link` into a new project to see if the lack of TS tooling affected anything. I'm using `@wordpress/scripts` v.12.2.1 and its working out of the box.

So I'm not going to let this hold up the release of packages, but it'll definitely be a nice improvement

**Comment by samueljseay** [comment]
Keep open
