### ISSUE TITLE
Uncaught WC_Data_Exception: The admin note title prop cannot be empty.

### ISSUE THREAD

**Issue by emreaakyuz** [woocommerce/woocommerce-admin#6747]
I get an error like the following on my website, all I did was want to add my_account shortcode to the header field. Later it gave this error and whatever I did didn’t fix it

Fatal error: Uncaught WC_Data_Exception: The admin note title prop cannot be empty. in /home/u9340248/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:856 Stack trace: #0 /home/u9340248/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Note.php(396): WC_Data->error('admin_note_inva...', 'The admin note ...') #1 /home/u9340248/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/CouponPageMoved.php(73): Automattic\WooCommerce\Admin\Notes\Note->set_title('') #2 /home/u9340248/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/NoteTraits.php(74): Automattic\WooCommerce\Admin\Notes\CouponPageMoved::get_note() #3 /home/u9340248/public_html/wp-includes/class-wp-hook.php(292): Automattic\WooCommerce\Admin\Notes\CouponPageMoved->possibly_add_note('') #4 /home/u9340248/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #5 /home/u9340248/public_html/wp-includes/plugin.php(484): WP_ in /home/u9340248/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php on line 856

**Comment by samueljseay** [comment]
Hi @emreaakyuz I'm sorry to hear you're having this issue. I was just wondering, could you possibly give some more information so we can try and track down the problem?

It would be useful to know:

1. Do you have the "WooCommerce Admin" plugin installed? If so what version is it?
2. If you just have the "WooCommerce" plugin installed, what version is it?

Thanks!

**Comment by emreaakyuz** [comment]
No I haven't installed the woocommerece admin plugin, the woocommerce version I use is 5.1.0 version

**Comment by samueljseay** [comment]
@emreaakyuz I still haven't gotten to the bottom of this, but if you have access to your database there is a workaround which is to dismiss the note.

You'll need to update the `is_deleted` column of the note to `1`.

This SQL is just a suggestion so please take caution updating the database, but it would be something like:

```
UPDATE wp_wc_admin_notes 
SET is_deleted = 1
WHERE name = 'wc-admin-coupon-page-moved'
```

**Comment by emreaakyuz** [comment]
Unfortunately nothing has changed, I ran the sql query you gave and then added it manually, but the result is the same

**Comment by samueljseay** [comment]
@adrianduffell Any chance you could assist here. Do you know the simplest way to stop the Note code from executing?

**Comment by adrianduffell** [comment]
@samueljseay I wonder if the SQL didn't work because the note isn't in the database yet (due to the error).

We can stop the code executing if the note already exists. Maybe we can try inserting the note with SQL 🤔

**Comment by adrianduffell** [comment]
@emreaakyuz could you please try running this SQL query? It should insert a  blank, deleted note into the database, which I think would stop the error you are seeing.

```
INSERT INTO `wp_wc_admin_notes` (`name`, `type`, `locale`, `title`, `content`, `content_data`, `status`, `source`, `date_created`, `date_reminder`, `is_snoozable`, `layout`, `image`, `is_deleted`, `icon`)
VALUES ('wc-admin-coupon-page-moved', 'info', 'en_US', '', '', '{}', 'unactioned', 'woocommerce-admin', '2021-04-07 13:33:27', NULL, 0, 'plain', '', 1, 'info');
```

**Comment by emreaakyuz** [comment]
Unfortunately that didn't work either

**Comment by adrianduffell** [comment]
@emreaakyuz Is it the exact same error as before?

To help me try to reproduce this, which language is your site in?

**Comment by emreaakyuz** [comment]
yes it is always the same mistake, the language of my site is Turkish, I use Turkish. Woocommerce in Turkish

**Comment by adrianduffell** [comment]
I've tested the note with the WP language set to Turkish and could not reproduce the error.

It's not clear to me why the title would be empty, as indicated by the error: `Uncaught WC_Data_Exception: The admin note title prop cannot be empty.`

@emreaakyuz I'm sorry you are seeing this issue. I think this requires troubleshooting your site directly.  Do you have access to [WooCommerce support](https://woocommerce.com/my-account/create-a-ticket/)? Alternatively there is a self-service guide [here](https://docs.woocommerce.com/document/woocommerce-self-service-guide/).
