### ISSUE TITLE
Failures in Notes should not crash wc-admin.

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#6749]
In #6747 wc admin crashes because for some reason the Note calls `set_title` without a translation, which I have not got to the bottom of, but I don't think the current approach of throwing an error that is uncaught is a good idea.

I think in this case we are too eager to throw a critical error, but crashing the plugin for the user for a failed note does not seem like a good experience.

My suggestion is that we catch all these errors generated from notes and warn instead and simply not show the note. To ensure that we don't miss critical errors during development, we could re-throw if we're in development mode.

**Comment by adrianduffell** [comment]
💯 

> My suggestion is that we catch all these errors generated from notes and warn instead and simply not show the note. 

To provide the warnings, maybe we could log it here `admin.php?page=wc-status&tab=logs`.

**Comment by samueljseay** [comment]
Not stale
