### ISSUE TITLE
Emailed Orders Report CSV have one column missing and misplaced data

### ISSUE THREAD

**Issue by Akinomotto** [woocommerce/woocommerce-admin#6759]
The Orders view from WC Dashboard contains two fields: **Customer** (Customer Name) and **Customer Type** (If new, recurring, etc)

If the table is not big enough, it will download a CSV directly, which contains those 2 fields without a problem.

However, if the table is bigger I'll get an email with a download link. This file will not only not contain the **Customer Type** column, but also will have the **Customer Type info** misplaced in the **Customer field**.

So the only way I had to export all that orders data was using an external plugin, cause I couldn't make it work on the native WooCommerce export feature.

Best regards, Akira.

**Comment by adrianduffell** [comment]
Hi @Akinomotto,

Thanks for reporting this. It is something we addressed in PR https://github.com/woocommerce/woocommerce-admin/issues/6534 however it is not released in WooCommerce yet.

If you have not already, you can preview the fix by using the [WooCommerce Admin plugin](https://wordpress.org/plugins/woocommerce-admin/) in the meantime. Does this work for you?
