### ISSUE TITLE
Make SelectControl accept disabled props

### ISSUE THREAD

**Issue by ecgan** [woocommerce/woocommerce-admin#6764]
**Is your feature request related to a problem? Please describe.**

I would like to render a disabled [SelectControl](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/components/src/select-control) component, but doing `<SelectControl disabled>` does not work, the users can still interact with the SelectControl.

**Describe the solution you'd like**

Make the SelectControl accept `disabled` props and pass it down to render `<input disabled>` element in the HTML.

The disabled SelectControl should also have related CSS to present a disabled UI.

**Describe alternatives you've considered**

Instead of rendering a disabled SelectControl, an alternative is to just render plaintext.

**Should this be prioritized? Why?**

Good to have.

**Additional context**

I would like to use this in my project. When users want to edit an existing object, some fields are not allowed to be edited, and we wanted to show it like in the below screenshot (the "United States" value is selected when creating new object and cannot be changed when editing):

![image](https://user-images.githubusercontent.com/417342/114070271-692c5800-98d2-11eb-891f-9414768f97b6.png)

**Comment by moon0326** [comment]
@ecgan Thank you for taking the time to report this bug, we really appreciate your help 👍 

We won’t be able to include this fix in the upcoming release as our next release is coming very soon, but I will try to include it in the next release.

**Comment by samueljseay** [comment]
This looks like a great one for my team to tackle. It should be low effort / high value. Adding it to our backlog for this or the next sprint.
