### ISSUE TITLE
Checkboxes in the variable product modal are mis-aligned

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#6768]
**Describe the bug**
Checkboxes in the variable product modal are mis-aligned.

**To Reproduce**
- Load up the latest WooCommerce store, and finish the onboarding flow
- visit the `Add products` task
- click `Start with a template`
- select one of the checkboxes.
Note that the checked circle is mis-aligned.

**Expected behavior**
Checkboxes should be aligned properly

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/2240960/114176353-66048c80-9911-11eb-8c1b-1a254d79a6cd.png)

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by mattsherman** [comment]
Issue #6651 for this already exists (with an open PR that should fix it)... closing this one in favor of that.
