### ISSUE TITLE
Analytics: Category list problem

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#6770]
**Describe the bug**

There is an oddity related to the `Analytics > Categories` list.
If a product category has checked a subcategory and also the parent category:

![product-categories](https://user-images.githubusercontent.com/1314156/114221805-22774600-9944-11eb-8642-7f998fd80c0a.png)

The sold child items will be added to the parent items, in the `Analytics > Categories` list.
The sold items with the child category will be counted twice.

Product only with the `child` category

![categories-list2](https://user-images.githubusercontent.com/1314156/114221929-518db780-9944-11eb-83ba-01c610541dbc.png)

Product with the `parent` and the `child` category selected

![categories-list2-2](https://user-images.githubusercontent.com/1314156/114222044-75e99400-9944-11eb-8915-a5fd3f63c401.png)

And the `parent` detail always will look the same:

![category-detail2](https://user-images.githubusercontent.com/1314156/114222442-f90aea00-9944-11eb-8235-c851e437e738.png)

 
Maybe this behavior is not incorrect but it's very confusing for the user. It would be a good idea to add the sold items to the parent category totals only when the parent category is not present with the child category in the product.

To make this issue more clear I'll use a practical example: having a parent category (e.g.: `Vehicles`) and 2 child categories (e.g.: `Bikes` and `Skates`). The parent category has 10 sold items, 3 bikes and 7 skates, but the skates also have the parent category selected (so the skate will have the categories: `Skates` and `Vehicles`).
The list will look like this:

| Category  | Items sold |
| ---------- | ---------- |
| Vehicles  | 17  |
| Bikes | 3  |
| Skates | 7  |

But we know that the vehicles sold really were 10. 

**To Reproduce**

0. Create 2 product categories named: `parent` and `child` (`child` should be a child of `parent`).
1. Go to `Analytics > Categories`
2. Create 2 products, one just with the category `parent` and the other product with the categories: `parent` and `child` selected.
3. Create 2 orders, one per product.
4. See the behavior related above.

**Expected behavior**
As I mentioned before
> It would be a good idea to add the sold items to the parent categories totals only when the parent category is not present with the child category in the product.

**Additional context**
This was an issue raised in Zendesk that @dani-elo  pointed out.

**Comment by dani-elo** [comment]
Reported in 3876165-zen. We can reach out to the user when this gets fixed.

**Comment by NathalyaVides** [comment]
Also occurring in 4349820-zen.

**Comment by darcie** [comment]
Reported in 4563461-zen also.

**Comment by chihsuan** [comment]
This is related to https://github.com/woocommerce/woocommerce-admin/issues/7710

Fixed in https://github.com/woocommerce/woocommerce-admin/pull/8153

Tested with Bikes also have the parent category (Vehicles) selected.

![Screen Shot 2022-01-17 at 10 51 51](https://user-images.githubusercontent.com/4344253/149700979-52e30bd2-3e80-49a2-8c2b-6b3d41766733.png)
