### ISSUE TITLE
Refactor `<TaskList>`  and `getAllTasks` to support the new `<List>` component

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#6773]
This is dependent on the completion of #6772 

`<TaskList>` (located here: https://github.com/woocommerce/woocommerce-admin/blob/39b5cb0130c9ad0da2401f9f35110ae1b1d0c213/client/task-list/list.js#L29) is sort of a master/detail component. It controls a list of items and the displaying of a corresponding set up task. It is used in both setup task list and extended task list but won't be able to do the work of both in its current state.

It relies on `getAllTasks` located here: https://github.com/woocommerce/woocommerce-admin/blob/39b5cb0130c9ad0da2401f9f35110ae1b1d0c213/client/task-list/tasks.js#L46 

`getAllTasks` is technical debt, it won't scale well for the upcoming complexity we're adding to the task list.
This is negotiable but I'm proposing as part of this we:

1. Do away with `getAllTasks`. Create a base `<TaskItem>` component that covers the current use cases and also can support proposed new functionality discussed here: https://github.com/woocommerce/woocommerce-admin/issues/6639#issuecomment-816844512 

2. Create a component for each task we currently have. Use the `<TaskItem>` component internally. Get the state needed to determine if/what the task should do in each individual component. This will remove the need for `getAllTasks`. Because we use a `container` prop for the detail currently, there's a question of how we'll handle the master/detail part here. I don't have an answer for this yet, I'm hoping a solution will present itself as we get into it.

3. Also note that the new designs for the setup task list mentioned in `1` deviate from the functionality we'll provide for the extended task list, so this is a good time to also render a different kind of `<TaskItem>` component for the extended task list items, at this stage they are simplified and cut down to just providing hierarchy information as described in https://github.com/woocommerce/woocommerce-admin/issues/6639

4. We'll need to retain the existing containers for each task (the detail part) otherwise the refactor will be too cumbersome.

**Important note:** Instead of deleting `<TaskList>` straight away we could keep it for use in the extended task list so we can implement https://github.com/woocommerce/woocommerce-admin/issues/6638 without waiting on this refactoring work.

**Comment by samueljseay** [comment]
Estimated this as a `5`. Its likely to be a significant refactoring effort.

**Comment by jeffstieler** [comment]
What should we do with the [`woocommerce_admin_onboarding_task_list` filter](https://github.com/woocommerce/woocommerce-admin/blob/c863e5d5c508d3de023df42a44e95557d5297890/client/task-list/tasks.js#L262)?

We could either change the data filtered to be an array of components, or perhaps replacing with a SlotFill would be better.

**Comment by louwie17** [comment]
> We could either change the data filtered to be an array of components, or perhaps replacing with a SlotFill would be better.

I think filtering by an array of components would be better. Given for the SlotFill to be useful we would have to put the `SlotFillProvider` at the top react Tree, and for a 3PD to use it they would have to have their React injected within our app somewhere.

**Comment by samueljseay** [comment]
Just adding some more comments on this one: It was not my intent to remove the task extension filter here, so if possible I'd like to keep that as backward compatible as possible.

It is my hope that we can just refactor the internals of `<TaskList>` to render the new `<List>` component.

Also not a deal breaker, we could keep `getAllTasks` if its easier and just try to get to a point where we can render the new `<List>`. This would be some adjustment of the code [here](https://github.com/woocommerce/woocommerce-admin/blob/4c298b5168998f12155bb828472a13d005232b32/client/task-list/list.js#L315-L316) from setting up a before and an after, to rendering some new markup to go inside our new `ListItem` component.

**Comment by louwie17** [comment]
> Also not a deal breaker, we could keep getAllTasks if its easier and just try to get to a point where we can render the new <List>. This would be some adjustment of the code here from setting up a before and an after, to rendering some new markup to go inside our new ListItem component.

@samueljseay at the moment I am leaning towards keeping `getAllTasks` around given that the functionality for each of our task items seems relatively the same.
Although I did create a separate `TaskItem` component consolidating most of that, and it would be pretty easy to change that if needed.

**Comment by samueljseay** [comment]
@louwie17 sounds like a pragmatic solution to me. Thank you!
