### ISSUE TITLE
Hook References: Update all filters to use the new JS Doc

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6777]
We have [a script](https://github.com/woocommerce/woocommerce-admin/blob/main/bin/hook-reference/index.js) to automatically compile filter JS Docs in to data file:

https://github.com/woocommerce/woocommerce-admin/blob/20766ce4286e90e7cff3db7a9c2d25b323d9cd62/bin/hook-reference/data.json#L1-L8

Only one filter has the correct jsDoc. This issue is to track expanding it to all existing filters

**Comment by joelclimbsthings** [comment]
Closing this, as it looks like it was already addressed via https://github.com/woocommerce/woocommerce-admin/pull/8004.
