### ISSUE TITLE
Update PayU Logo in Task List

### ISSUE THREAD

**Issue by MechielCouvaras** [woocommerce/woocommerce-admin#6780]
**Is your feature request related to a problem? Please describe.**
PayU have updated their logo and we need to update the logo in the Set Up Payments Task List.

**Describe the solution you'd like**
Please update the logo to[ this version](https://drive.google.com/file/d/1peeIC3JLL6vZxWTKj8LQ1EO_zTXGrQHM/view?usp=sharing).

**Describe alternatives you've considered**
We can keep using the current logo until the next release of Woo.

**Should this be prioritized? Why?**
No.

**Additional context**
Nope.

**Comment by moon0326** [comment]
Estimate: 1

**Comment by pmcpinto** [comment]
@timmyc is it possible to cherry-pick this to be included in WC 5.3?

cc @joshuatf I think you're handling the WC admin version that will be included in 5.3

**Comment by timmyc** [comment]
@pmcpinto seeing that we will likely be doing a 2.2.2 at some point between now and 5.3 final, that sounds fine to me. 

@joshuatf should we create an issue milestone for 2.2.2 and drop this one in there?
