### ISSUE TITLE
New Inbox message: PayPal feedback

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6813]
Title: Share your feedback on PayPal
Content: Share your feedback in this 2 minute survey about how we can make the process of accepting payments more useful for your store.
Segmentation: PayPal Standard installed / Stripe not installed
Cadence: Once
CTA leads to: http://automattic.survey.fm/paypal-feedback
CTA label: Share feedback

@pmcpinto Should we limit this to users with transactions or is just having the extension installed enough?

**Comment by pmcpinto** [comment]
> @pmcpinto Should we limit this to users with transactions or is just having the extension installed enough?

I think we don't have a way to filter by transactions with the remote inbox, so it would be better to keep it simple and target users with the extension installed.

**Comment by moon0326** [comment]
Estimate: 1
