### ISSUE TITLE
New Inbox message: Stripe and PayPal feedback

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6815]
Title: Share your feedback on Stripe and PayPal
Content: Share your feedback in this 2 minute survey about how we can make the process of accepting payments more useful for your store.
Segmentation: Stripe and PayPal Standard installed
Cadence: Once
CTA leads to: https://automattic.survey.fm/stripe-paypal-feedback
CTA label: Share feedback

**Comment by joelclimbsthings** [comment]
Closing this as we prepare for the merge as it's nearly a year old, and may not be relevant at this point.
