### ISSUE TITLE
Debug warning in E2E tests

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#6831]
We are seeing the following warning when running onboarding/setup E2E tests:

```
  console.warn
    `select` control in `@wordpress/data-controls` is deprecated. Please use built-in `resolveSelect` control in `@wordpress/data` instead.

      at Page.<anonymous> (../../../../../package/woocommerce/tests/e2e/env/src/setup/jest.setup.js:213:3)
```

The three uses of `@wordpress/data-controls` which [issues the warning](https://github.com/WordPress/gutenberg/blob/42dca2627c34410061ada3130eb0f75db128c7ef/packages/data-controls/src/index.js#L40) I found are:

- https://github.com/woocommerce/woocommerce-admin/blob/main/packages/data/src/plugins/actions.js#L4
- https://github.com/woocommerce/woocommerce-admin/blob/main/packages/data/src/plugins/resolvers.js#L4
- https://github.com/woocommerce/woocommerce-admin/blob/main/packages/data/src/settings/actions.js#L6

**Comment by samueljseay** [comment]
This could be a good cooldown issue for someone to look at.
