### ISSUE TITLE
Error if click Continue twice on business features.

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-admin#6836]
**Describe the bug**
On the business features step after clicking `Continue` the button busy animation is not shown if the cursor remains on the button. The button is not disabled so it is possible to click it again. If you click it again error messages are displayed and you can't continue unless you untick adding recommended business features.

**To Reproduce**

1. in OBW fill out store details with a USA address 
2. Click Continue and select Fashion, apparel, and accessories, 
3. Click Continue, and select Physical products, and continue.
4. The business details tab should show a Business details tab, and a Free features tab (disabled at first)
5. Select 1-10 for the first dropdown, and No for the second, and click Continue.
6. Make sure the "Add recommended business features to my site is ticked
7. Click Continue, before the page redirects click Continue again
8. See Errors on screen
9. Also in console in console
`500 error for wp-json/wc-admin/plugins/activate?_locale=user`
`502 error for wp-json/wc-admin/plugins/install?_locale=user`

**Expected behavior**
Continue buttons busy animation to be more obvious and to be displayed when the cursor is on the Continue button. No error should occur if clicking Continue again unless it is a small informative error that doesn't block installation or Continue button should be disabled to avoid being able to click it again.

**Screenshots**

![Screen Recording 2021-04-19 at 18 49 27 2021-04-20 19_56_00](https://user-images.githubusercontent.com/24649833/115450613-0c0a9d80-a214-11eb-80d3-863cca1fa3ea.gif)
![Screen Recording 2021-04-19 at 18 49 27 2021-04-20 19_54_10](https://user-images.githubusercontent.com/24649833/115450626-0dd46100-a214-11eb-8db0-e57f56e7211f.gif)

![Screenshot 2021-04-19 at 13 38 09](https://user-images.githubusercontent.com/24649833/115450444-ccdc4c80-a213-11eb-941b-3915e8d34158.png)
![Screenshot 2021-04-19 at 13 37 59](https://user-images.githubusercontent.com/24649833/115450449-cea61000-a213-11eb-875c-6f478f32d859.png)
![Screenshot 2021-04-19 at 13 37 51](https://user-images.githubusercontent.com/24649833/115450451-cf3ea680-a213-11eb-947e-7582ae99aee6.png)
![Screenshot 2021-04-19 at 13 37 41](https://user-images.githubusercontent.com/24649833/115450452-d06fd380-a213-11eb-95a9-27e13b42736d.png)

**Desktop (please complete the following information):**

MacOS, Chrome, WooCommerce 5.3 Beta 1

**Comment by joelclimbsthings** [comment]
I was able to reproduce this consistently on the latest `main`, and I'd consider it a fairly critical bug. Chrome will often display errors as pictured above, and Firefox seems to occasionally lock up entirely. This can leave the store in fairly rough shape, with errors/notices persisting.

My guess is that the simplest fix would simply be disabling the action during the busy state for this button.

**Comment by moon0326** [comment]
I'm gonna take it as I already worked on disabling the other buttons in OBW pages.

Estimate: 1
