### ISSUE TITLE
Use Jetpack Changelogger

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#6837]
Use [Jetpack Changelogger](https://github.com/Automattic/jetpack-changelogger) to mitigate merge conflict issue with changelogs. 

I think we can use the following workflow with a few customizations to Jetpack Changelogger.

1. Add our own types (Fix, Add, Update, Dev, Tweak, Performance). Jetpack Changelogger easily allows us to add the custom types via [configuration](https://github.com/Automattic/jetpack-changelogger#configuration). For the changelog filename, we can either use the default format from Jetpack Chagnelogger or come up with our own custom format. Maybe a PR #? 

2. For every PR, run `changelogger add` command to add a new changelog file to `./changelog/:log-file`. Running the command prompts us the following selections.
![Screen Shot 2021-04-20 at 2 44 24 PM](https://user-images.githubusercontent.com/4723145/115467813-f6cb4a00-a1e6-11eb-83b9-60c10f0644e3.jpg)

A sample changelog file output in `./changelog`:

```
Significance: minor
Type: Add

This is a test #23
```

3. When we're ready to release, run `changelogger write --use-version=:version`. The command collects files in `./changelog` -> format them -> add entires to [readme.txt](https://github.com/woocommerce/woocommerce-admin/blob/main/readme.txt). We need a custom class to do this step as the built-in class uses markdown and doesn't know how to inject changelog entires into readme.txt.

4. Jetpack Changelogger automatically deletes files in `./changelog` when you run `changelogger write`. I'm not sure if we want this to be done automatically 🤔

**Comment by adrianduffell** [comment]
This sounds good to me!

> We need a custom class to do this step as the built-in class uses markdown and doesn't know how to inject changelog entires into readme.txt.

It might be worth moving over to a standard `CHANGELOG` file anyway. It bothers me how long it is on the .org listing 😅 

https://wordpress.org/plugins/woocommerce-admin/

**Comment by moon0326** [comment]
> This sounds good to me!
> 
> > We need a custom class to do this step as the built-in class uses markdown and doesn't know how to inject changelog entires into readme.txt.
> 
> It might be worth moving over to a standard `CHANGELOG` file anyway. It bothers me how long it is on the .org listing 😅
> 
> https://wordpress.org/plugins/woocommerce-admin/

I think that's a good idea 👍

Yeah 👍 The description section on the plugin page is getting longer and longer 😄  

I'm going to make a PR first since I've already made a class that writes changelog to readme.txt, but we can discuss how we want to do it there I think.
