### ISSUE TITLE
Preloaded dependencies get added multiple times

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-admin#6841]
**Describe the bug**
When we have a plugin load a script which has `wc-components` as a dependency. It adds the preload link multiple times, ex:

```
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/style.css?ver=1618834704" as="style" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/style.css?ver=1618834704" as="style" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/style.css?ver=1618834704" as="style" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=1618834704" as="script" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=1618834704" as="script" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=1618834704" as="script" />
<link rel="preload" href="https://domain.test/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=1618834704" as="script" />
```

**To Reproduce**

1. Create a new plugin `npm run create-wc-extension`
2. Add `wc-components` as one of the script dependencies
3. `npm install && npm start` and activate the plugin
4. View the page source of a WooCommerce Admin pages such as Analytics > Overview
5. Notice that the preload link for `components/index.js` will be shown twice

**Expected behavior**
I'd expect the preload link to be added only once regardless of how many scripts use the same dependency.

**Additional context**
The problem comes from the way the loader loops through the dependencies and sub-dependencies, see: https://github.com/woocommerce/woocommerce-admin/blob/v2.2.0/src/Loader.php#L713-L730

The only requirement for the dependency to add a preload link is for it to be on the allowed list, it doesn't have any check to see if there was another script which already added the tag.

**Comment by jeffstieler** [comment]
Hi @mikkamp, I'm having trouble reproducing this.. can you put your example plugin in a gist?

**Comment by mikkamp** [comment]
The dependencies are stored in a generated php file, so they need to be added to the webpack config. To get around that I used the following code, to always add it as a dependency:

```
        wp_register_script(
                'extension-test',
                $script_url,
                array_merge( script_asset['dependencies'], array( 'wc-components' ) ),
                $script_asset['version'],
                true
        );
```
