### ISSUE TITLE
Remote Payment Recommendations: Hook up "Choose payment methods" UI

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6850]
Render a list of payment methods based off the Remote payment methods introduced in https://github.com/woocommerce/woocommerce-admin/pull/6830

The exception is the WC Pay card which has unique styling and logic.

<img width="988" alt="Screen Shot 2021-04-22 at 2 42 32 PM" src="https://user-images.githubusercontent.com/1922453/115649138-dc29da00-a37a-11eb-8efa-1238930d4515.png">

We can leverage the head start done by @chickenn00dle in https://github.com/woocommerce/woocommerce-admin/pull/6450, just derive the data from the `/wc-admin/onboarding/payments` endpoint instead.

**Comment by psealock** [comment]
Estimate 5: Although a good amount of groundwork has already happened for this issue, I think its the foundational piece to get this off the ground. It may be less, but a lot could get discovered in this one, so I'm conservatively going with 5.

**Comment by joshuatf** [comment]
Closed by https://github.com/woocommerce/woocommerce-admin/pull/6867
