### ISSUE TITLE
Remote Payment Recommendations: Hook up individual methods

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6851]
Render the payment method setup using data from `/wc-admin/onboarding/payments`.

<img width="992" alt="Screen Shot 2021-04-22 at 2 59 14 PM" src="https://user-images.githubusercontent.com/1922453/115649459-7722b400-a37b-11eb-940b-588108400426.png">

Below are relevant parts of the schema:

```
"fields": [ // Fields to be shown during the configuration step.
	{
		"type": "text",
		"label": "Client ID",
		"validate": "/([A-Z][a-z]+)/", // Regex to validate the input value.
		"option": "option_name" // An option to fetch and prefill this field as well as update.
	},
	{
		"type": "text",
		"label": "Secret Key",
		"validate": "/([A-Z][a-z]+)/",
		"option": "option_name"
	}
],
"plugins": [ "hello-dolly" ], // An array of plugin slugs to be installed.
"imageUrl": "https://…", // URL to method logo.
"manageUrl": "admin.php?page=wc-settings&section=...", // URL to manage the payment after configuration.
"connection": {
	"url": "/wp-json/my-extension/get_connection_url", // A REST endpoint which returns data for the connection URL.
	"property": [ "myProperty" ]
}
```

**Comment by psealock** [comment]
Estimate 5: Since a lot of the data is baked into the [payment methods themselves](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/tasks/payments/methods/stripe.js), this will require teasing that data and compiling all that logic to a single payment method that can accept a config object. If possible, this could remove lots of code.

**Comment by joshuatf** [comment]
Side note: some pieces of the above (`fields`, `manageUrl`, and `connection`) could be offloaded to the plugin to define.

**Comment by joelclimbsthings** [comment]
Closed by https://github.com/woocommerce/woocommerce-admin/pull/6867
