### ISSUE TITLE
Remote Payment Recommendations: Add a check to comply with .org guidelines

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6854]
The current thinking is that users opted into Marketplace suggestions will also be able to receive these suggestions for payment gateways. 

- [ ] Wrap Remote Payment Recommendations around a check for opted in users
- [ ] Include a local config for users that are opted out
- [ ] Gracefully hand a scenario where woocommerce.com is offline by falling back to the local config

**Comment by psealock** [comment]
Estimate 1: If the logic is agreed upon, this is fairly trivial. If that logic dictates a modal or any other mechanism for opting in users, it may be more. But it seems relying on the Marketplace Suggestions opt in will be sufficient.

**Comment by joshuatf** [comment]
@psealock @pmcpinto are we confirmed that this will follow the opt-in to marketplace logic?  Or will there be any additional prompts/modals during runtime?

**Comment by psealock** [comment]
>are we confirmed that this will follow the opt-in to marketplace logic?

yes, confirmed.

>will there be any additional prompts/modals during runtime?

No, but we need to ensure our system can fall back to a local copy of the config if wccom is offline. I updated the original comment to reflect this.
