### ISSUE TITLE
Remote Payment Recommendations: Create a default config

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6855]
Some users will have opted out of marketplace suggestions. As a result the `/wc-admin/onboarding/payments` endpoint will need to deliver defaults that are included in WC Admin instead of gathered from wc.com.

- [ ] Create default json data

Related to https://github.com/woocommerce/woocommerce-admin/issues/6854

**Comment by psealock** [comment]
Estimate 1: I think a default config will likely emerge from https://github.com/woocommerce/woocommerce-admin/issues/6850 and https://github.com/woocommerce/woocommerce-admin/issues/6851, so this issue may be just a formality to get it working.

**Comment by joshuatf** [comment]
@psealock What will the defaults include?  All of the current methods or just a select few?

**Comment by psealock** [comment]
All the current methods

**Comment by mattsherman** [comment]
@joshuatf @joelclimbsthings What remains on this issue?

**Comment by joshuatf** [comment]
These have all been completed.  Closing this issue.
