### ISSUE TITLE
Epic: Remote Payment Recommendations

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6856]
## Creating Remote Payment Recommendations powered by wc.com

Initial discussion: p6q8Tx-24n-p2
Technical spike: pc2DNy-g3-p2
Reusing Remote Inbox rules technical spike: p90Yrv-2g1-p2

Initial investigation: https://github.com/woocommerce/woocommerce-admin/pull/6450
Remote rules investigation: https://github.com/woocommerce/woocommerce-admin/pull/6830

**Comment by psealock** [comment]
@pmcpinto I've estimated this at 19 points and I think it will fit nicely in a Cycle for Gezora.

**Comment by pmcpinto** [comment]
Thanks @psealock. Considering that now we have this epic maybe we can close #6141.

I mentioned [here](https://github.com/woocommerce/woocommerce-admin/issues/6141#issuecomment-808377914) but I'm not sure if this was included in the initial spike: with the [WCPay inclusion in the free features step](https://d.pr/i/osNhwn), the bulk of new installs is coming from this flow, which is 4-5x more effective than the payments task. So this step should also be powered by the remote system. cc @joshuatf as you made the initial spike.

**Comment by joshuatf** [comment]
Thanks for putting this all together, @psealock!  I added a few more issues to the above.  I think the REST endpoint and data store are probably important to include, while updating external plugins could maybe fall into next sprint if we cant knock everything out.

**Comment by psealock** [comment]
>I'm not sure if this was included in the initial spike

This wasn't included in the initial spike and wasn't on my radar until now. We could query the same endpoint created for recommendations to populate this screen as well. Once the mechanism is in place, I think adding this to here would be another 3 estimation points. Would this be just for WC Pay or the whole lot? At first glance, I don't think it matters as far as dev time is concerned. Let me know and I'll create an issue for this as well.

**Comment by pmcpinto** [comment]
👍 It would be great to do it for the entire list.

**Comment by pmcpinto** [comment]
@joshuatf @joelclimbsthings just a check-in to see if you think that this epic is on track to be ready by the end of this cycle or if it will be necessary to cut scope. It's important to keep in mind that the most impactful part is the [WCPay promotion in the free features step](https://d.pr/i/osNhwn). More than 70% of WCPay installs are now coming from that part of the user journey. Thanks

**Comment by psealock** [comment]
>It's important to keep in mind that the most impactful part is the WCPay promotion in the free features step

In retrospect, it would have been good to start with this simpler step which doesn't involve some challenges around SlotFill, determining a Gateway's settings via API or determining a Gateway's essential fields. I didn't realise this was part of the Sprint nor its importance until development was underway.

Having said that, the team is making great progress working through some tough challenges, especially with some help from outside Gezora. I strongly recommend that we let those holding these problems at the forefront of their consciousness continue to do so. Stopping just to start up again in a month will be a huge loss of productivity. 

Instead of reducing scope, pulling in more help from Isotope would be much better. I'd consider the nuclear option of extending the sprint over stopping work on the challenges inherent to the Payment Recommendations portion of this Epic.

cc @timmyc

**Comment by pmcpinto** [comment]
> In retrospect, it would have been good to start with this simpler step which doesn't involve some challenges around SlotFill, determining a Gateway's settings via API or determining a Gateway's essential fields. I didn't realise this was part of the Sprint nor its importance until development was underway.

No problem. Sorry if there was some miscommunication from my side. 

> Stopping just to start up again in a month will be a huge loss of productivity.
> Instead of reducing scope, pulling in more help from Isotope would be much better. I'd consider the nuclear option of extending the sprint over stopping work on the challenges inherent to the Payment Recommendations portion of this Epic.

I think the team shouldn't stop this work but reassess if it makes sense to prioritize some pieces that can help accelerate the implementation of the same approach in the business details step. The goal is to have this in WC 5.4 to support the WCPay intl expansion. The code freeze is Jun 17, which means the work needs to be ready a couple of days before that date. So it would be good to be one step ahead and evaluate if it's necessary to fine-tune the scope, have more people working on this project, and how this can affect the upcoming wcadmin releases, so we don't miss the 5.4 train.

**Comment by thenbrent** [comment]
@pmcpinto @psealock has anyone confirmed with the WordPress.org team that the planned approach for remote recommendations will comply with the .org guidelines?

**Comment by psealock** [comment]
We are basing this off merchants who have opted in under Marketplace Suggestions, which we've deemed fundamentally the same thing. To answer your question, no... no one has reached out about this specifically.

**Comment by pmcpinto** [comment]
@joshuatf @joelclimbsthings I'd like to confirm that the event tracking that we have in the payments task is working as usual with the changes that are being implemented. Thanks!

**Comment by joelclimbsthings** [comment]
@pmcpinto Definitely should be. We've been copying over events to the new implementation as we go. If there's a good reference of what should fire when in this feature, I'm glad to audit it.

**Comment by pmcpinto** [comment]
@joelclimbsthings great! Here's the list of the most important events:

- View the task: `wcadmin_task_view` (check the additional props such as task_name)
Is it possible to add a new prop showing all the payment methods options the user is seeing when they visit the payments task? Similar to what we had in `wcadmin_tasklist_payment_setup`
- Click to enable a method: `wcadmin_tasklist_payment_install_method` (check the additional props such as plugins)
This is not working with BACS and COD but it should be fixed
- View the payments steps after install: `wcadmin_payments_task_stepper_view` (check the additional props)
- Click to connect to a payment method (2nd step of Stripe and PayPal): `wcadmin_tasklist_payment_connect_start` check the additional props)
- Finish the last step of setting up a payment method: `wcadmin_tasklist_payment_connect_method` (check the additional props)

Let me know if you have questions

**Comment by pmcpinto** [comment]
Can you also re-add `wcadmin_tasklist_payment_setup` in the new remote flow and fallback option? I think it was removed by mistake. cc @octaedro as we talked about this event in #6727

**Comment by mattsherman** [comment]
All work on this epic is complete, except for following up on third-party plugin updates, which is a longer-term chore and therefore has been moved out of this epic.
