### ISSUE TITLE
Comparison filter UI is broken

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#6865]
**Describe the bug**
When attempting to search and add entities to the comparison filter, they're not visible selecting them. Likewise, if you check a number of comparable entities from a table, then click compare - the comparison is made, however, you're unable to see the entities you've selected in the comparison filter above.  

**To Reproduce**

1. go to a report that allows you to compare entities - IE: the product report. 
2. change the show menu to "comparison"
3. search for a product to add to the comparison
4. select it
5. Note that once selected it's not visible as part of the comparison in the filter. 

1. refresh the page
2. check a number of products in the table, then click compare in the table header
3. note that the selected products don't appear in the comparison filter

**Expected behavior**
Products should appear in the comparison filter as chips as they're added to the comparison

**Screenshots**
Missing products in the comparison filter

<img width="1621" alt="Screen Shot 2021-04-22 at 1 15 47 PM" src="https://user-images.githubusercontent.com/4500952/115779590-070d3180-a36d-11eb-810f-3e8661a53305.png">

**Comment by jeffstieler** [comment]
This should be fixed by https://github.com/woocommerce/woocommerce-admin/pull/6862. Can you check again after updating your local copy?

**Comment by LevinMedia** [comment]
Yep, I see it now, thanks @jeffstieler
