### ISSUE TITLE
Redirect to WooCommerce home screen after completing WCPay KYC

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6873]
After installing and setting up WooCommerce Payments from the Choose payments task screen, users are redirected back to the task screen. 
<img width="902" alt="image" src="https://user-images.githubusercontent.com/5121465/115910767-dc85ac00-a432-11eb-89e4-2f9507ce76e1.png">

It’s not entirely clear at this point what to do, and this could feel like a dead end. Instead, the user should land on WooCommerce home after completing the KYC to continue on their path towards successful store setup.

I'm also going to create a related issue for installing from the welcome screen, that I think belongs in the WCPay repo. Will link here when I do.

cc @pmcpinto

**Comment by moon0326** [comment]
Estimate: 2

**Comment by moon0326** [comment]
@elizaan36 Do we also want to redirect users to the homescreen when they finish other payments setup as well? or is this only for WC Pay?

**Comment by elizaan36** [comment]
Good call, it would be best to redirect users to the home screen after all payments setup (not just WCPay) to help provide a clear next step.
