### ISSUE TITLE
OBW wizard resets country to "Afghanistan" when tabbing through fields

### ISSUE THREAD

**Issue by jonathansadowski** [woocommerce/woocommerce-admin#6879]
**Describe the bug**
When tabbing through the fields in the onboarding wizard, if I select a country, and then again tab through the fields, Afghanistan gets selected overriding my previous selection

**To Reproduce**

1. On the first step of the onboarding wizard, select a country (other than Afghanistan) from the dropdown
2. Use tab / shift+tab to navigate through the form fields, notice that the country you have previously selected gets reset to Afghanistan.

**Expected behavior**
I expected my previous country selection to have been retained.

**Screenshots**

https://user-images.githubusercontent.com/363749/115927158-9a1b9980-a449-11eb-897e-0d24e88df8ae.mov

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Chrome
* Version: 89

**Comment by ilyasfoo** [comment]
I was able to reproduce this behaviour with multiple `<SelectControl>` components.
