### ISSUE TITLE
[RestAPI] List all customer by username

### ISSUE THREAD

**Issue by hiagodotme** [woocommerce/woocommerce-admin#6881]
I did an integration of my system with WooCommerce. The only way to identify a user without storing his ID is by email. I did an integration where I create my user in woocommerce as "partner.**$MY_SYSTEM_ID**", however the only way currently to locate this user is through his email in my system. If my user changes the email I can no longer retrieve his history and I end up creating a new user. I could easily resolve this if I could search for the user by username.

**Comment by samueljseay** [comment]
I've added this to our feature request backlog. Thanks for suggesting this.

**Comment by samueljseay** [comment]
I actually just realised this functionality already exists. Our customer API endpoint can take username as a search param

Example request URL: `<hostname>/wp-json/wc-analytics/customers?search=someusername&searchby=username&per_page=10&_locale=user`
