### ISSUE TITLE
Store profiler: MailPoet business details changes

### ISSUE THREAD

**Issue by NeosinneR** [woocommerce/woocommerce-admin#6882]
**Is your feature request related to a problem? Please describe.**
In #6480, MailPoet was included in the [Business Details](https://d.pr/i/IgDi5u) section of Store Profiler. Since then, the MailPoet and Marketing team decided to stick with the `MailPoet` brand instead of `Email Marketing by WooCommerce`. 

**Describe the solution you'd like**
- Change _title_ from `Email Marketing by WooCommerce` to `MailPoet`
- Remove `Powered by MailPoet.` from the _description_.

**Should this be prioritized? Why?**
MailPoet in Store Profiler is to be first released in WC 5.3. Ideally, this change is included in 5.3, so the `Email Marketing by WooCommerce` is not used until WC 5.4 to confuse customers.

**Additional context**
I'm confirming with the Marketing team the exact copy. I'll also prepare the PR once confirmed. 

cc @pmcpinto @timmyc @joshuatf

**Comment by pmcpinto** [comment]
@joshuatf is it possible to include this in wcadmin 2.2.2? Assuming that we'll need to do one to disable the wcpay expansion (we're going to get the confirmation tomorrow).
