### ISSUE TITLE
Replace woocommerce_shared_settings filter hook usage (deprecated)

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-admin#6900]
Just surfacing this: https://developer.woocommerce.com/2021/04/28/woocommerce-blocks-5-0-0-release-notes/

In blocks, the `woocommerce_shared_settings` filter has been soft deprecated. Using the filter will produce a warning in the console rather than a visible notice.

[This is used 7 times across woo admin.](https://github.com/woocommerce/woocommerce-admin/search?q=woocommerce_shared_settings)

Instead of using the filter, settings should be added using the Asset Data Class in Blocks. So for example, this usage:

https://github.com/woocommerce/woocommerce-admin/blob/38fbb4aedd0f21cf21ddaa6af93e48564fd35324/src/Features/Marketing.php#L64

https://github.com/woocommerce/woocommerce-admin/blob/38fbb4aedd0f21cf21ddaa6af93e48564fd35324/src/Features/Marketing.php#L178-L187

Could become:

```
Automattic\WooCommerce\Blocks\Package::container()->get( Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::class )->add( 'installedExtensions', InstalledExtensions::get_data() );
```

In blocks we moved our logic in the same way so it would only be added when needed (for example, settings consumed by blocks are only added when the block types are rendered). This would likely be the approach needed in woo admin also. We'd also suggest trying to keep the settings under a single namespace to avoid conflicts.

cc @nerrad

**Comment by nerrad** [comment]
Noting that the changes here are also indirectly related to #5690 originally reported in this repository. We did some refactoring that included soft deprecating this filter (which was only in place for back compat reasons for the longest time).

**Comment by nerrad** [comment]
Also a related dev note: p90Yrv-1rG-p2

**Comment by nerrad** [comment]
Slight error with the provided example since it doesn't account for the `marketing` key. So it would be better represented as:

```php
Automattic\WooCommerce\Blocks\Package::container()
    ->get( Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::class )
    ->add( 'marketing', [ 'installedExtensions' => InstalledExtensions::get_data() ] );
```

**Comment by mikejolley** [comment]
@nerrad Thanks for calling this out. Just to note I did that intentionally so as not to infer you can add multiple duplicate keys - you can only add `marketing` once. If you tried again you'd get a duplicate key error (merging data is not supported). I imagine in the use case of woo-admin, `marketing` will be added once as an array of data somewhere, rather than using multiple calls to AssetDataRegistry::add.

**Comment by adrianduffell** [comment]
Thanks for surfacing this @mikejolley @nerrad. If you are interested, please feel free to submit a PR to update this.

Setting this to a high priority due to the console output.
