### ISSUE TITLE
[GlobalStep] "Visit My Store" link under Store Management section fails to open in new tab

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6907]
## Bug Description:
"Visit My Store" link under Store Management section fails to open in new tab in spite of having new tab icon.

## Environment:
Woocommerce Version : WooCommerce 5.2.2 and 5.3 RC 1
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard setup 
1. Hide the Setup task list on Home screen.
1. Note that Store Management section appears on Home screen.
1. Click on Visit My Store link.
1. Observe that "Visit My Store" link fails to open in new tab.

## Actual Result:
"Visit My Store" link under Store Management section fails to open in new tab inspite of having new tab icon.

## Expected Result:
"Visit My Store" link under Store Management section should get open in new tab.

## Video:
https://user-images.githubusercontent.com/41110392/116568040-ca6da700-a925-11eb-8ccb-5825b872d7e8.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment]
I'm not sure what to expect here though, should we remove the new tab icon, or should we make the link open in a new tab? cc @elizaan36 as I think you're the best to answer

**Comment by elizaan36** [comment]
Yes thanks, the "View my store" link should open in a new tab 👍
