### ISSUE TITLE
Remote Payment Recommendations: Add payment gateway data store

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6909]
Instead of using the options API, we're going to create a data store to cover fetching and updating gateways using the core `/wp-json/wc/v3/payment_gateways` endpoints.

https://woocommerce.github.io/woocommerce-rest-api-docs/#payment-gateways

This should include:
* Retrieving all payment gateways
* Updating a payment gateway

Nice to have:
* Fetch an individual gateway

**Comment by psealock** [comment]
Closing if favour of https://github.com/woocommerce/woocommerce-admin/issues/6912
