### ISSUE TITLE
Setup Checklist: Change Copy Back

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6943]
@pmcpinto would like to revert some of the text changes made to the Setup Checklist in #6298

Pedro, wanting to confirm the only items you would like to revert from the original PR are the text changes in the following files:

![image](https://user-images.githubusercontent.com/22080/117180374-f86d4400-ad88-11eb-9f91-3fb750bf3fa2.png)
 
and

![image](https://user-images.githubusercontent.com/22080/117180491-15a21280-ad89-11eb-8bd5-84c737069ec1.png)

There were quite a few other copy changes included in the original PR, but the above two files are the ones that resulted in changes to the setup checklist.

**Comment by samueljseay** [comment]
> Pedro, wanting to confirm the only items you would like to revert from the original PR are the text changes in the following files:

@pmcpinto bump on this just to confirm these are the only changes needed.

**Comment by pmcpinto** [comment]
> @pmcpinto bump on this just to confirm these are the only changes needed.

Yes. Thanks!
