### ISSUE TITLE
Refactor `<TaskList/>` to reusable component in a public package

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#6944]
**Is your feature request related to a problem? Please describe.**

The upcoming WC Pay overview page work features a task list:

<img width="526" alt="Screen Shot 2021-05-05 at 2 59 51 PM" src="https://user-images.githubusercontent.com/63922/117195121-24e18a00-ada2-11eb-8781-222af234e3f5.png">

Other issues in the epic have covered enhancements to our existing task list functionality, but haven't captured the need to make the `<TaskList />` component itself reusable. The WC Pay overview page will need the same visibility controls and event tracking as the current Home screen.

**Describe the solution you'd like**

Move the `<TaskList />` component to a package that will be used by the `/client` app and 3PDs to create task lists in a dashboard context.

Remove the `<TaskList />` component's knowledge of the differences between the `task_list` and `extended_task_list`.

Stretch goal: introduce a SlotFill for extending the task lists (WC Pay will add an item to the current "Get ready to start selling" list).

**Describe alternatives you've considered**

The alternative to this refactor is to duplicate much of the code we've written in `/client/task-list` in the WC Pay extension.

**Additional context**

Try branch for moving some task list items: https://github.com/woocommerce/woocommerce-admin/tree/try/task-list-slotfill

**Comment by samueljseay** [comment]
I think before we go down this path we need to clearly articulate what we *need* from the current task list. It may not be everything that's present in our wc-admin task list. I'd also like to not frame this as "a task list in dashboard" but rather an agnostic task list that can be placed anywhere. Any dashboard specific behaviours we have in our task list currently don't belong in this component.

Also we have some upcoming work to produce a task with progression: https://github.com/woocommerce/woocommerce-admin/issues/6774 we'll need to consider how we can implement that with this work in mind.

**Comment by jeffstieler** [comment]
Closing this, we're not taking on this work exactly as described and some elements have been taken care of in other PRs.
