### ISSUE TITLE
A/B test: new task list progression UI

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6949]
**Description:** we're going to A/B test the new task list UI that it's being implemented in #6774. Our goal is to increase the conversion rate of the store setup task list. The experiment checklist is available [here](https://github.com/Automattic/experimentation-platform/wiki/Experiment-Checklist).

**Comment by samueljseay** [comment]
As part of this we need to publish the experiment on p2, I imagine much of the experiment checklist will be used to formulate that post. @pmcpinto maybe whoever ends up writing that post could collaborate with you on any draft that is written?

**Comment by jeffstieler** [comment]
> Our goal is to increase the conversion rate of the store setup task list

This seems really broad of a goal (especially in the context of what looks to be a very specific checklist).

Can you fill out sections 1 and 2 from the checklist @pmcpinto ?

**Comment by pmcpinto** [comment]
> There is a lot changing in with the tweaks requested in #6774 - the expansion behavior, new conditional copy for some tasks (which depends on a lot of data getting wired up to the component), moving the cart modal UX to be inline in a task, and more that I'm missing and/or hasn't been discovered yet. Wrapping all of these changes in an A/B test will require the duplication of hundreds of lines of code, so it would be nice to know the specifics around what you'd like to test.

This is a valid concern. 

> Can you fill out sections 1 and 2 from the checklist @pmcpinto ? (perhaps you have on p2?)

Sure. Let's collaborate on this next week. The best option is to create a google doc with the checklist to get feedback from more people before publishing it in the experiments p2.
