### ISSUE TITLE
WooCommerce > Analytics will not complete job, locks up when asking to compare to previous year

### ISSUE THREAD

**Issue by spidercreations** [woocommerce/woocommerce-admin#6958]
**Describe the bug**
I found this was mentioned in https://github.com/woocommerce/woocommerce-admin/issues/3904

I'm still having this issue on a client's website. When I open up the Analytics > Overview page, the information loads with little issue as it shows the month to date as the default. Switch to Year to Date gets partial information, but the page locks up without showing any data. Occasionally it shows Top Categories and Top Products, but never Net Sales, Orders or Performance.

In the same browser, if I open another tab to open the front end of the website, the site will not load at all.

I'm running a pretty powerful server for this site, but there are a lot of orders. (More than 40,000 orders in the system.)

Console shows...
Unchecked runtime.lastError: The message port closed before a response was received.
VM240 admin.php:1 Error handling response: TypeError: Cannot read property 'loggedOut' of undefined
    at chrome-extension://kcnhkahnjcbndmmehfkdnkjomaanaooo/contentscript.js:167:137
DevTools failed to load SourceMap: Could not load content for https://grayguns.com/wp-content/plugins/authorize-net-emulation-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/payment-gateway/assets/dist/admin/sv-wc-payment-gateway-token-editor.js.map: Load canceled due to load timeout

The only way to get out of this issue is to completely shut down the current browser, or restart PHP-FPM service for Apache.

Open site in an incognito window, the front end of the site displays with no issue while normal Chrome browser is locked up.

**To Reproduce**

1. Go to Analytics > Overview
2. Click on .... actually change Date Range from default (current month total) to Year to Date
3. Page will not complete.

[07-May-2021 14:32:16 UTC] PHP Fatal error: Maximum execution time of 300 seconds exceeded in /home/grayguns/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/TimeInterval.php on line 321

Request URL: https://grayguns.com/wp-json/wc-analytics/reports/performance-indicators?after=2020-01-01T00%3A00%3A00&before=2020-05-06T23%3A59%3A59&stats=revenue%2Ftotal_sales%2Crevenue%2Fnet_revenue%2Corders%2Forders_count%2Cproducts%2Fitems_sold%2Cvariations%2Fitems_sold&_locale=user
Request Method: GET
Status Code: 500 

**Expected behavior**
It should show the data.

**Screenshots**

**Desktop (please complete the following information):**

* OS: Mac OS 11.2.3
* Browser Chrome
* Version 90.0.4430.93

**Additional context**

**Comment by samueljseay** [comment]
I did some investigation of this, and its a tricky one, because I can't reproduce it easily. I would probably need to reproduce an environment with a similar scale of orders over a similar disparate time frame.

One thing that I did notice is in the stack trace mentioned:

```
PHP Fatal error: Maximum execution time of 300 seconds exceeded in /home/grayguns/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/TimeInterval.php on line 321
```

It could totally be a red-herring, but line 321 is in the body of `next_day_start` which is called  just once within a `do/while` loop on line `337`. If there is a bug of some kind, this `do/while` could be an infinite loop which might explain the execution timeout. 

I've asked @jeffstieler for some help on this, especially keen just to get some ideas on how we might try and reproduce this issue.

**Comment by dnutbourne2** [comment]
Hi, we have also been experiencing this (or a similar) issue.

The analytics seem to be able to handle any filter for up to ~2 months of data, but fails at 'Last Quarter', etc.
Data fails to be displayed (shows 'There was an error getting your stats'), but we don't experience any lockup.
Approximately 11,000 orders in total. A second site of ours with ~1000 orders displays no issue.

Some examples from our logs:
```
PHP Fatal error / Exception has occurred in the http://xxxx.com/wp-json/wc-analytics/reports/performance-indicators?after=2021-01-01T00%3A00%3A00&before=2021-03-31T23%3A59%3A59&stats=revenue%2Ftotal_sales%2Crevenue%2Fnet_revenue%2Corders%2Forders_count%2Cproducts%2Fitems_sold%2Cvariations%2Fitems_sold&_locale=user. Error/Exception Message: Maximum execution time of 300 seconds exceeded (Line 321 in /var/www/xxxx.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/TimeInterval.php)

PHP Fatal error / Exception has occurred in the http://xxxx.com/wp-json/wc-analytics/reports/performance-indicators?after=2021-01-01T00%3A00%3A00&before=2021-03-31T23%3A59%3A59&stats=revenue%2Ftotal_sales%2Crevenue%2Fnet_revenue%2Corders%2Forders_count%2Cproducts%2Fitems_sold%2Cvariations%2Fitems_sold&_locale=user. Error/Exception Message: Maximum execution time of 300 seconds exceeded (Line 150 in /var/www/xxxx.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/TimeInterval.php)

PHP Fatal error / Exception has occurred in the http://xxxx.com/wp-json/wc-analytics/reports/performance-indicators?after=2021-01-01T00%3A00%3A00&before=2021-03-31T23%3A59%3A59&stats=revenue%2Ftotal_sales%2Crevenue%2Fnet_revenue%2Corders%2Forders_count%2Cproducts%2Fitems_sold%2Cvariations%2Fitems_sold&_locale=user. Error/Exception Message: Maximum execution time of 300 seconds exceeded (Line 154 in /var/www/xxxx.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/TimeInterval.php)

PHP Fatal error / Exception has occurred in the http://xxxx.com/wp-json/wc-analytics/reports/performance-indicators?after=2021-01-01T00%3A00%3A00&before=2021-03-31T23%3A59%3A59&stats=revenue%2Ftotal_sales%2Crevenue%2Fnet_revenue%2Corders%2Forders_count%2Cproducts%2Fitems_sold%2Cvariations%2Fitems_sold&_locale=user. Error/Exception Message: Maximum execution time of 300 seconds exceeded (Line 154 in /var/www/xxxx.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/TimeInterval.php)
```

**Web server:** Apache/2.4.6  (CentOS) OpenSSL/1.0.2k-fips mod_qos/11.64
**Memory limit:** 512M
**PHP version:** 7.4.20
**MySQL version:** 5.5.5
**Curl version:** 7.29.0 / SSL: NSS/3.53.1 / libz: 1.2.7
**OpenSSL version:** OpenSSL 1.0.2k  26 Jan 2017
