### ISSUE TITLE
Add skeleton loading to table summary component

### ISSUE THREAD

**Issue by naman03malhotra** [woocommerce/woocommerce-admin#6961]
Presently the table summary component does not have a check on the contents of the `data` object being passed to it. We ran into an issue with the transactions list component in WCPay client where the `summary.value` is being passed as `undefined` and it was rendered as-is. One of the ways to solve that was to pass a default value, more details here: https://github.com/Automattic/woocommerce-payments/issues/1639.

However, to maintain consistency with the table component we'd like a similar skeleton loader for the `TableSummary` as well. Which will be rendered while the data is still being loaded.

#### It should look something like this
<img width="888" alt="Screenshot 2021-04-23 at 2 47 28 AM" src="https://user-images.githubusercontent.com/15019298/115788343-1d54d500-a3e1-11eb-8a9a-ad030774d814.png">

The component will take `isLoading` as prop which will append a class that will enable skeleton loading animation.

**Comment by htdat** [comment]
@naman03malhotra  - I've done some research on this issue. I will also work on this issue too if you don't mind.
