### ISSUE TITLE
Component: Dashboard Block inserter

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#697]
The block inserter is used to add additional blocks to the dashboard. 

<img width="539" alt="screen shot 2018-10-25 at 8 23 41 pm" src="https://user-images.githubusercontent.com/4500952/47542811-fc54ad00-d893-11e8-8fe7-b90be2a437b3.png">

Specific interactions TBD depending on how much of this we can lift directly from Gutenberg

**Comment by psealock** [comment]
closed in https://github.com/woocommerce/woocommerce-admin/pull/2280
