### ISSUE TITLE
Include additional countries in the WCPay intl expansion

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6976]
**Description:** everything is on track to proceed with the international expansion in 5.4 and we're going to include four additional countries:  ES, FR, IT and DE. We need to include them in the list covering the expansion. To summarize: US, AU, CA, GB, IE, NZ, ES, FR, IT and DE

**Comment by pmcpinto** [comment]
More context about the expansion here: paJDYF-1CA-p2

**Comment by ilyasfoo** [comment]
Closing this, addressed in https://github.com/woocommerce/woocommerce-admin/pull/7048 and https://github.com/woocommerce/woocommerce-admin/pull/7050
