### ISSUE TITLE
Store profiler: remove business details step original flow

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6977]
**Description:** we have two different flows in the business details step segmented by the country selected in the first step of the store profiler. Without a proper a/b testing tool, we implemented this workaround to the new flow's impact (#6485). The data shows that we're moving in the right direction and we should remove the [original flow](https://d.pr/i/j8U2xe) to reduce maintenance and focus our efforts on improving the new one. 

**Acceptance criteria:**

- [ ] Remove the country condition we have to split the two business details step flows and remove the original flow.
- [ ] Make sure the [new Business details step](https://d.pr/i/SvUIhB) is the only available flow from now on 
- [ ] Confirm that WCPayments is only displayed in the countries outlined in #6976

**Comment by becdetat** [comment]
I've scoped this a bit:

- delete segmentation flag from `client/profile-wizard/steps/business-details/index.js:36`
- The version _without_ the toggles should be the only flow going forward
    - when segmentation flag is true
    - which is SelectiveFeaturesBusinessStep
- delete `BusinessDetailsStepWithExtensionList` - `client/profile-wizard/steps/business-details/flows/bundle/index.js` - this is the flow that is being removed
- delete BusinessExtensions `client/profile-wizard/steps/business-details/flows/selective-bundle/business-extensions/index.js` - doesn't appear to be used

Estimate: 2

**Comment by adrianduffell** [comment]
I think the [Smoke Test Checklist ](https://github.com/woocommerce/woocommerce-admin/wiki/Smoke-Test-Checklist#onboarding-profile-wizard-flows)will need a minor refresh as well. It currently has separate steps for testing the "standard flow" vs "Free business features flow".

**Comment by ilyasfoo** [comment]
I've [removed the "standard flow"](https://github.com/woocommerce/woocommerce-admin/wiki/Smoke-Test-Checklist/_compare/8ada26b225280d9d0f7d12872b88467e809267c2) from our smoke test checklist.
