### ISSUE TITLE
`getIdsFromQuery` does not get `0` as Id.

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6980]
**Describe the bug**
I'm trying to use `@woocommerce/navigation.getIdsFromQuery` to parse Ids from a query param. The param can take values like:
- `param=0`
- `param=0,5677`
In both cases `0` is ignored.

**To Reproduce**

```js
getIdsFromQuery( '0' );
getIdsFromQuery( '12,0,67' );
```

**Expected behavior**
`0` as a valid `Number` should be a valid Id.
Therefore, I should get `[0]` and `12,0,67` respectively.

### Technical

I guess at https://github.com/woocommerce/woocommerce-admin/blob/main/packages/navigation/src/index.js#L97 we should use `( id ) => ! isNaN( id )` instead of `Boolean`, as `parseInt` already identified numbers and not-numbers.

**Comment by samueljseay** [comment]
> I guess at https://github.com/woocommerce/woocommerce-admin/blob/main/packages/navigation/src/index.js#L97 we should use ( id ) => ! isNaN( id ) instead of Boolean, as parseInt already identified numbers and not-numbers.

Thanks @tomalec I agree with the proposed logic you've suggested here. This seems like it'll be small to fix and test. We'd welcome a PR for this but otherwise we can put it in the next sprint.

**Comment by tomalec** [comment]
Speaking of a small and easy fix, I wonder whether there might be somebody in a distant plugin relying on that "zero-stripping" behavior :confused:
