### ISSUE TITLE
Add MailPoet to Installed Marketing Extensions (and the recommended panel)

### ISSUE THREAD

**Issue by jconroy** [woocommerce/woocommerce-admin#6982]
**Description:**

As per the title, we should add support for MailPoet to the Installed Marketing Extensions panel on the Marketing Hub and also add it as a recommended extension (this requires changes to WCCOM).

<img width="1064" alt="Screen Shot 2021-05-13 at 3 28 13 pm" src="https://user-images.githubusercontent.com/355014/118084438-e2522a00-b3ff-11eb-9a2a-1497061cf068.png">

**Unknowns**

* Icon/s and text

**Acceptance Criteria:**

* [ ] Mailpoet listed in Marketing Extension with appropriate links to setup and documentation
* [ ] Mailpoet listed in Recommended Extensions

**Comment by joelclimbsthings** [comment]
Closing, as it's redundant with other issues that have already been implemented.
