### ISSUE TITLE
Business features step: improve extensions installation performance

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6988]
**Description:** we're going to remove the original business details step UI and focus on improving the new one where we consolidate all the free extensions promotion under the same step. See #6977. One of the first steps should be improving the performance of the install flow. We want to mitigate the risks of having users stuck while the extensions are being installed or if an issue occurs during the installation. 
Currently, we're installing [8 extensions](https://d.pr/i/ENSyVT)* and the "bundle" size surpasses 20MB.
One idea is to use Action Scheduler to install the extensions in the background while the user is going through the rest of the flow, but we can explore other alternatives. 

*- we're assessing the possibility of moving the email marketing extensions to a new task on the home screen and the Mailpoet team is exploring how to reduce the Mailpoet size. Still, it will take a while until we have news about the next steps in this regard.

**Comment by becdetat** [comment]
This will need some thought around how this will be presented in the UI. There is a new endpoint which allows installing and activating extensions (#6805) which could just be monitored during the remainder of the profiler. The question is what alerts should be shown and when? An alert per extension? or a single alert at the end of installation? or no alert at all, just keep it entirely in the background.

Either way is relatively similar. My estimate is 3.

**Comment by pmcpinto** [comment]
> The question is what alerts should be shown and when? 

Good question. @elizaan36 what do you think?

**Comment by elizaan36** [comment]
> or a single alert at the end of installation?

Yes, this! A single alert at the end of installation would be best, rather than multiple for each extension which can look buggy - the alert could say "Extensions were installed and activated".

**Comment by mattsherman** [comment]
@pmcpinto Is this still a priority? I'm thinking this could be a good issue for Mothra to tackle in Cycle 15.

**Comment by pmcpinto** [comment]
@mattsherman There were some changes after the creation of this issue that could impact the performance of the install flow:
- The free extensions promotion is now powered by the json file hosted on wc.com
- We're going to remove the marketing extensions from this step

I think it's worth exploring this, and it seems to be a low-effort change. But it would be good to evaluate how the flow is performing with the changes mentioned above to compare the before & after tackling this.

**Comment by joshuatf** [comment]
@pmcpinto Just checking in to see if this issue is still a priority.  We have just merged an asynchronous option to install plugins in https://github.com/woocommerce/woocommerce-admin/pull/8079 so we could potentially install and activate all plugins in the background.

**Comment by pmcpinto** [comment]
@joshuatf thanks for the heads up. That can be a good way to overcome this challenge

 I'll create a new issue regarding the idea of installing/activating the plugins in the background, to evaluate the pros & cons of doing this.
