### ISSUE TITLE
Store profiler: MailPoet business details changes

### ISSUE THREAD

**Issue by NeosinneR** [woocommerce/woocommerce-admin#6989]
**Is your feature request related to a problem? Please describe.**
In #6480, MailPoet was included in the [Business Details](https://d.pr/i/IgDi5u) section of Store Profiler and in #6882 the title and description were changed to keep the name MailPoet. However, the actual copy from the Marketing team wasn't confirmed until it was too late to be included in WC 5.3.

**Describe the solution you'd like**
- Change _title_ from `MailPoet` to `All-in-one email marketing by MailPoet`
- Change _description_ from `The default all-in-one solution for WooCommerce email.` to `Create and send purchase follow-up emails, newsletters, and promotional campaigns straight from your dashboard.`.

**Should this be prioritized? Why?**
Not urgent, ideally to be included in wcadmin 2.3.1 so it can get to WC 5.4.

**Additional context**
I'll prepare the PR. 

cc @pmcpinto

**Comment by pmcpinto** [comment]
@timmyc can we include this change in 2.3.1?

**Comment by timmyc** [comment]
Indeed we will get this in 2.3.1, thanks for opening the issue and for the PR @NeosinneR 🙌
