### ISSUE TITLE
Business details tab not saving selections

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7018]
**Describe the bug**
After entering selections in the Business details step of the store profiler, and navigating back via the tab, it seems that all selections are reset/not saved. (h/t Shiva in `p6riRB-6cW` for discovering this bug)

**To Reproduce**

1. Go to the store profiler, step 4
2. Enter selections for business details and choose "Continue"
3. Select the tab "Business details" to go back
4. See error (selections not saved)

**Expected behavior**
Selections made in the business details tab should be saved. When tabbing back and forth between business details and free features, the selections made should be persistent.

**Screenshots**
![Screen Recording 2021-05-19 at 10 25 07 AM](https://user-images.githubusercontent.com/5121465/118840479-0e9cf900-b88d-11eb-905b-0077c36fb0b4.gif)

@pmcpinto

**Comment by becdetat** [comment]
Can reproduce. No API call seems to be made with the updated business details when continuing, however there is a tracks event which contains the pre-updated business details.

This is a bug, I'll move it to the backlog.

**Comment by moon0326** [comment]
I can also reproduce. It looks like `state.savedValues` is not being saved/updated (see this [line](https://github.com/woocommerce/woocommerce-admin/blob/main/client/profile-wizard/steps/business-details/flows/selective-bundle/index.js#L262))

Estimate: 1
