### ISSUE TITLE
Display gross sale by product in the Analytics

### ISSUE THREAD

**Issue by tsetend** [woocommerce/woocommerce-admin#7033]
A user 4002650-zen wants to see Gross Sales by product in Analytics, not Net Sales. As discussed in the slack channel, posting it as an enhancement request here.

**Comment by chihsuan** [comment]
I'm not really sure about the potential impact of this request (p1621444162036400-slack-C7U3Y3VMY). The user didn't tell us why he want this feature. @adrianduffell I think we can close this. What do you think?

**Comment by adrianduffell** [comment]
@chihsuan Thanks for the ping, yes let's close it. I think it's an enhancement we're unable to prioritize at the moment.
