### ISSUE TITLE
Remote Configs: Write testing instructions

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#7039]
Remote Payment Recommendations and Remote Free Extensions List are features that will need test instructions written for Global Step. 

Flows will need to be established so that behaviour with and without Marketplace suggestions turned on are identical. We'll need to test scenarios where a remote config isn't accessible and ensure the rules are appropriately represented in remote configs.

**Comment by joshuatf** [comment]
@psealock I'm working on the testing instructions for payment gateways.  Do you happen to have any reference material we could use for the remote extensions list testing instructions?

**Comment by psealock** [comment]
Remote Free Extensions testing here: https://github.com/woocommerce/woocommerce-admin/blob/main/TESTING-INSTRUCTIONS.md#remote-fee-extensions-list-7144

**Comment by joshuatf** [comment]
Thanks, @psealock!  Going to close this issue as all testing instructions are now covered.
