### ISSUE TITLE
Negative values are not being exported correctly by csv-export module

### ISSUE THREAD

**Issue by naman03malhotra** [woocommerce/woocommerce-admin#7040]
**Describe the bug**
Presently if you try to export CSV which has negative values it adds an `'` in front of the value, this due to the `escapeCSVValue` function appends `'` in front of the `-` character to prevent CSV vulnerabilities.

Function responsible: https://github.com/woocommerce/woocommerce-admin/blob/e9879f3727433a9e11567e35c043bba2e6944df1/packages/csv-export/src/index.js#L13-L14

**To Reproduce**

1. Go to the Transactions page.
2. Make sure you have some -ve values, you can do this by creating a refund test transaction.
2. Click on Download.
3. You'll see a negative value represented as for example(`-70` as `'-70`) 

**Expected behavior**
Negative values should be rendered as-is during CSV export.

**Screenshots**
<img width="923" alt="Screenshot 2021-05-21 at 3 17 20 PM" src="https://user-images.githubusercontent.com/15019298/119118446-d1c93180-ba47-11eb-90ad-63cc089360c2.png">

**Desktop (please complete the following information):**
* OS: Mac
* Browser: Chrome
* Version: Latest

**Comment by naman03malhotra** [comment]
Reported this here, just to keep track: https://github.com/Automattic/woocommerce-payments/issues/1881

**Comment by moon0326** [comment]
Thank you @naman03malhotra for taking the time to report this bug. We'll work on it as soon as possible.

**Comment by moon0326** [comment]
For anyone who is interested in CSV vulnerabilities, these two articles are very interesting to read.

https://www.contextis.com/blog/comma-separated-vulnerabilities
http://georgemauer.net/2017/10/07/csv-injection.html

**Comment by samueljseay** [comment]
Further reading on owasp here too: https://owasp.org/www-community/attacks/CSV_Injection

What if we changed the ' to be a tab character instead? This should hopefully be sufficient for most programs importing the data to interpret it correctly?

**Comment by moon0326** [comment]
> Further reading on owasp here too: https://owasp.org/www-community/attacks/CSV_Injection
> 
> What if we changed the ' to be a tab character instead? This should hopefully be sufficient for most programs importing the data to interpret it correctly?

I was thinking about that as well. It also has a disadvantage (it is counted as a char), but I think it's better than  `'`  IMO.
