### ISSUE TITLE
Improve the presentation of Infinite delta in `SummaryNumber`

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#7042]
## **Is your feature request related to a problem? Please describe.**

Currently, when reviewing the performance in analytics, if for example, sales come from `0` to `$320k` - which is an extremely great improvement, UI shows a pretty sad message of grey `0%`.

That is problematic for two reasons:
- The performance is going great, even better than green `100%`, but we show it as neutral.
- `0%` denotes lack of change, which is actually far from the truth.

See https://d.pr/i/BCVj5v

## **Describe the solution you'd like**
I believe we should denote it as a good trend (or a bad trend if reversed) and show something like `max %` or `∞ %`
![Image of a Summary Number rendering green delta with `max%`](https://user-images.githubusercontent.com/65582817/114812883-7fab4580-9de3-11eb-853c-d6e5fb8c0fe7.png)

## **Describe alternatives you've considered**
In our GLA plugin, as we cannot provide a custom non-numeric value of the delta, we render it as a neutral `N/A` which is slightly more accurate that `0`, but still "sad".

## **Should this be prioritized? Why?**

I see no reason to rush, other than imperfect UX.

## **Additional context**

// cc and image credits for @j111q 

483-gh-woocommerce/google-listings-and-ads

**Comment by joshuatf** [comment]
I think this is a great idea, but will close this issue for now so we can focus more on activation for the next quarter.

We can revisit this at a later date and reopen then.
