### ISSUE TITLE
Add console commands to manage testing instructions

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#7059]
Similar to https://github.com/woocommerce/woocommerce-admin/issues/6837,

Add `add` and `write` commands to add testing instructions files and write them into `TESTING-INSTRUCTIONS.md` when ready.

New workflow would be:

1. Work on an issue and make a PR
2. Use `npm run tsi add`. The command asks to name the testing instruction and PR #. It also creates a markdown file in `/testing-instructions
3. Open the markdown file and add testing instructions as usual.
4. Commit the markdown file. 

When we're ready to release, the release lead executes `npm run tsi write :version` to merge the individual testing instruction files into `TESTING-INSTRUCTIONS.md`

**Comment by joelclimbsthings** [comment]
Hey @moon0326 , I like the sound of this addition, although we've had it kicking around for ~10 months without any motion, and I think team Atlas will be taking over some of these things after The Merge. 

I'm going to close it for now, but feel free to reopen if you feel strongly about it.
