### ISSUE TITLE
Access Sales Report and Analytics with just `view_woocommerce_reports` permission

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-admin#7061]
**Describe the bug**
Post-WooCommerce 5.2.0 (WooCommerce Admin 2.1.5?), users with just `view_woocommerce_reports` can only access Sales reports, and not Analytics.

**To Reproduce**
1. Create a user role with minimum permission:

    ```
		// Sales Manager role.
		add_role(
			'sales_manager',
			'Sales Manager',
			array(
				'edit_posts'             => true,
			)
		);

		$capabilities['core'] = array(
			'view_woocommerce_reports',
		);

		foreach ( $capabilities as $cap_group ) {
			foreach ( $cap_group as $cap ) {
				$wp_roles->add_cap( 'sales_manager', $cap );
			}
		}
    ```
2. Install WooCommerce 5.1 and notice that users with Sales manager role can access both Sales reports, and Analytics
    ![https://d.pr/i/LDY1Sw+](https://d.pr/i/LDY1Sw+)
3. Update to WooCommerce 5.2 or above to find that Sales reports can be accessed, but not Analytics
4. See error:
    ![https://d.pr/i/DmEAux+](https://d.pr/i/DmEAux+)

**Expected behavior**

Allow users with just `view_woocommerce_reports` permission to access all reports (including Analytics) as per [Roles and Capabilities - Documentation](https://docs.woocommerce.com/document/roles-capabilities/#section-2): 

> `view_woocommerce_reports`: Gives them access to all WooCommerce reports.

**Desktop (please complete the following information):** N/A
**Smartphone (please complete the following information):** N/A

**Additional context**

Originally discussed here: p1621835567099300-slack-woo-devs

*Edit: Sales reports can be accessed, but not Analytics in the latest version.*

**Comment by moon0326** [comment]
Thank you @AashikP for taking the time to report this bug. I was able to confirm it in my testing environment. We'll work on it.

**Comment by louwie17** [comment]
Pinging @joshuatf for this issue, I did a git bisect and it appears that [Move capability checks to client](https://github.com/woocommerce/woocommerce-admin/pull/6365) PR broke it, as it works in the [previous commit](https://github.com/woocommerce/woocommerce-admin/commit/544059c823fea1c8e6aa15da4b1fc2e3cb6fba92).
From looking at the changes I don't see an obvious reason why it broke then, as back-end changes are minimal. Josh hopefully you could shine some light on this? :)

**Comment by moon0326** [comment]
I looked into it a bit further. It looks like this [line](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/Homescreen.php#L84) is causing the problem.

When I try to access `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview`, I noticed that my browser visits WooCommerce -> Home then redirects to the Overview page immediately. That's when we get the access denied page.

**Comment by moon0326** [comment]
I don't think there is a workaround / quick fix for this one.

1. WooCommerce -> Home menu is registered at `wc-admin` path and requires `manage_woocommerce`.
2. Analytics -> * pages are registered at `wc-admin` with `path`. 

Accessing Analytic pages also require `manage_woocommerce` permission since it is also registered at `wc_admin`.

I think we probably want to update the documentation.

What do you think @louwie17 @joshuatf?

**Comment by louwie17** [comment]
> Accessing Analytic pages also require manage_woocommerce permission since it is also registered at wc_admin.
> I think the best solution is to update documentation in this case.

@moon0326 I don't think we want to just update the documentation, assuming that `manage_woocommerce` would also give a user several other permissions which we might not want them to have.
We should keep in line with how it used to work, where `view_woocommerce_reports` allows to see the analytics pages, I assume that capability was created for this specific reason.

I haven't looked into it further (I can though), but is there not an easy way around this? Or where the analytics pages accept both `manage_woocommerce` and `view_woocommerce_reports`. Or is the biggest bottle neck [this line you mentioned earlier](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/Homescreen.php#L84)?

**Comment by moon0326** [comment]
> > Accessing Analytic pages also require manage_woocommerce permission since it is also registered at wc_admin.
> > I think the best solution is to update documentation in this case.
> 
> @moon0326 I don't think we want to just update the documentation, assuming that `manage_woocommerce` would also give a user several other permissions which we might not want them to have.
> We should keep in line with how it used to work, where `view_woocommerce_reports` allows to see the analytics pages, I assume that capability was created for this specific reason.
> 
> I haven't looked into it further (I can though), but is there not an easy way around this? Or where the analytics pages accept both `manage_woocommerce` and `view_woocommerce_reports`. Or is the biggest bottle neck [this line you mentioned earlier](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/Homescreen.php#L84)?

I totally agree that we should try to keep it how it was, but there isn't a way to get around it when we assign `manage_woocomerce` to the home screen. If we remove `manage_woocommerce` from the home screen, then the users with only `view_woocommerce_reports` end up seeing "WooCommerce" menu, which they should not. 

I will try to see if we have other options, but we're in a tricky spot :(

**Comment by midweste** [comment]
Still broken and not completed
