### ISSUE TITLE
Products/Variations revenue stats not cached

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce-admin#7066]
**Describe the bug**

With https://github.com/woocommerce/woocommerce-admin/pull/2970, the caching mechanism utilized by the Analytics data stores was updated to rely on transients.

However, two data stores were not updated:

- API/Reports/Products/Stats/DataStore.php 
- API/Reports/Variations/Stats/DataStore.php 

**To Reproduce**

It would be awesome if the ability of these data stores to cache their own data was unit-tested, as testing `get/set_cached_data` would result in some nice failures here. Not sure if that's something you want to do though!

Otherwise a quick way to look at the problem would be to modify `Automattic\WooCommerce\Admin\API\Reports\DataStore::get_cached_data` to something like this: https://a.cl.ly/5zuYZz5E

Then:

1. Go to **Analytics > Products**.
2. Watch your console.
3. See the cache misses?
4. Refresh the page.
5. More cache misses.

Sending a PR in a few minutes :)

**Comment by moon0326** [comment]
Thank you @franticpsyx for taking the time to report this issue 👍 . We really appreciate it. It looks like you have opened a PR already. I will try to review it as soon as possible.
