### ISSUE TITLE
UX: Long blank screen during setup

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-admin#7068]
**Describe the bug**

During the OBW setup, the step right after clicking on the theme -- you see a blank screen while it is loading. This sometimes can take 10 to 20 seconds and it appears something has gone wrong if you don't notice the loading spinner in the browser tab.

Perhaps we could add a loading animation during this phase?

**To Reproduce**

1. Create a site on Jurassic Ninja.
2. Install latest WC.
3. Run through the OBW setup until theme selection.
4. Click on default theme or Storefront.
5. Witness a blank screen while it loads.

**Expected behavior**
I am expecting to know what is happening instead of blank screen.

**Comment by moon0326** [comment]
Thank you for taking the time to report @roykho 👍 I've tried Firefox, Safari, and Chrome to reproduce it, but I wasn't able to see a bank screen. However, I see that there is a delay while redirecting to WooCommerce Home after selecting a theme. Are you referring to the delay?

**Comment by moon0326** [comment]
Update: I actually confirmed the blank screen on the Jurassic Ninja site (I initially tested it on my local).
