### ISSUE TITLE
Analytics query transients filling up the options table

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce-admin#7069]
**Describe the bug**

While working with the Analytics API, I noticed that the caching implementation in https://github.com/woocommerce/woocommerce-admin/pull/2970 relies on storing a transient per analytics query.

While this is a tough problem to crack on systems without an external object cache, I have the impression that a second look at the current approach might be justified here, as:

- the count of these unique queries is un-bounded; they don't increase linearly with a known variable and the transient keys can change very often;
- to my best knowledge WC core does not clean up expired transients on a regular (e.g. cron) schedule -- it only cleans them up [with every update](https://github.com/woocommerce/woocommerce/blob/a5cd695e629e1c4c48b257646b60c0d92f479509/includes/wc-core-functions.php#L2320)

I am not sure if the best approach here would be to 

- leave things as is (am I missing something?), 
- update the caching logic, or 
- clean up the expired transients more frequently in WooCommerce core.

> update the caching logic

Here's an example:

```
			$transient         = get_transient( 'wc_report_' . $this->cache_key );
			$transient_version = WC_Cache_Helper::get_transient_version( 'wc_report_' . $this->cache_key );

			// Cache up to 100 items.
			$count = -100;

			if ( ! is_array( $transient ) ) {
				$transient = array();
			}

			$transient_keys = array_keys( $transient );

			// Take the opportunity to clean up stale data.
			foreach ( $transient as $cached_data_key => $cached_data ) {

				if ( ! isset( $cached_data[ 'version' ] ) || $cached_data[ 'version' ] !== $transient_version ) {
					unset( $transient[ $cached_data_key ] );
				}

				if ( $count > -1 ) {
					unset( $transient[ $transient_keys[ $count ] ] );
				}

				$count++;
			}

			$transient[ $cache_key ] = array(
				'version' => $transient_version,
				'value'   => $value,
			);

			set_transient( 'wc_report_' . $this->cache_key, $transient, WEEK_IN_SECONDS );
```

To make this work some bits and pieces in `Automattic\WooCommerce\Admin\API\Reports\Cache::set/get` and `Automattic\WooCommerce\Admin\API\Reports\DataStore::set/get_cached_data` would need to change. Note that the array is limited in size and cleaned up with every write to keep the [de]serialization overhead low.

I don't really like this approach, as it limits the number of cached data, and makes serialization/deserialization a bit heavy. It can be improved to fall back to the current approach when an external object cache exists. 

If we opt for the cleaning-up-expired-transients approach -- perhaps on a (weekly?) schedule -- we may want to do a PR in core so that other code can benefit from this.

**Comment by moon0326** [comment]
Thank you @franticpsyx for taking the time to test and report this issue 👍 I will try to test it myself later this week and see where we can go from here.
