### ISSUE TITLE
Offload remote inbox notifications engine for activated_plugin hook

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#7076]
This is a follow-up to #6995, specifically [this comment](https://github.com/woocommerce/woocommerce-admin/pull/6995#discussion_r638632216).

It relates to https://github.com/woocommerce/woocommerce-admin/issues/6189.

The remote inbox notifications engine should run asynchronously using action-scheduler for the `activated_plugin` hook, and the `woocommerce_activated_plugin` should be added as well.

**Comment by joelclimbsthings** [comment]
Closing this as we prepare for the merge, as it's low priority and nearly a year old.
