### ISSUE TITLE
Display dropdown appearing on the Personalize store task screen

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7083]
**Describe the bug**
The display dropdown appears on the "Personalize your store" task screen. Since this only controls the single column / two column layout on the home screen, it shouldn't appear on any other screen. The task screen only has a single column layout option.

**To Reproduce**

1. Navigate to WooCommerce home
2. Click on 'Personalize your store' in the store setup task list
3. See error

**Expected behavior**
Only the "Preview site" and "Help" links should appear in the top bar.

**Screenshots**
<img width="1024" alt="Screen Shot 2021-05-27 at 8 47 06 PM" src="https://user-images.githubusercontent.com/5121465/119918031-4d861b00-bf2d-11eb-9122-00350cbeb8bb.png">

This bug is appearing on two test sites - one ecommerce plan and one self hosted.

**Comment by samueljseay** [comment]
@elizaan36 multiple test sites on Jurassic Ninja? Which version? I can't reproduce this on latest `main`.

**Comment by elizaan36** [comment]
oh sorry for not providing more info. I can see it's not appearing on JN sites, and now I'm only seeing it on one test site (the screenshot above). It was showing up on the ecommerce plan site (but I had to update wc admin and it went away☺️). 

My self hosted site (hiddenstreets.io) is running the latest versions of everything - WordPress 5.7.2, WooCommerce 5.4 rc, and WC Admin 2.3.1. Do you think there's some conflict only on this site?
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/5121465/119919456-19602980-bf30-11eb-8924-2c99a24de490.png">

**Comment by elizaan36** [comment]
Something odd - [when I refresh the page](https://share.getcloudapp.com/BluKgxR4), the Display link disappears then reappears.

**Comment by elizaan36** [comment]
Here's what the console is telling me
On Firefox:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/5121465/119920062-482acf80-bf31-11eb-846e-9ede9c09dc33.png">

And Chrome:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/5121465/119920204-89bb7a80-bf31-11eb-9bd3-dc982178c6e2.png">

**Comment by moon0326** [comment]
@elizaan36 I tried to reproduce it on an ecom plan and local env, but I wasn't able to reproduce it 🤔 I tested it with WC 5.4.

Do you have any other plugins activated other than the plugins you mentioned in the earlier comment? It really looks like the icon is appearing according to your screenshot.

**Comment by elizaan36** [comment]
Hey Moon! When I disconnected and deactivated Jetpack, the display button disappeared! What a mess but at least we figured it out. The problem is that means sites that can't disconnect/deactivate Jetpack will see the display icon - these include all Ecommerce plan sites. Do you think I should create an issue in the Jetpack repo?

**Comment by moon0326** [comment]
@elizaan36 Sorry for the delay in response. I think it would be nice if we find a way to reproduce it before reporting to Jetpack repo. I still can't reproduce this bug. This is mysterious 🤔 

If your site (hiddenstreets.io) doesn't have a ton of data, is it possible for you to dump the database and send it to me in slack? I think that's the fastest way to reproduce it.
