### ISSUE TITLE
Last two E2E tests fail locally

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#7093]
**Describe the bug**
The last two tests are failing for me locally due to a popup. See screenshot

```
 FAIL  ../../../tests/e2e/specs/tasks/payment.test.js (43.929s)
  Payment setup task
    ✓ Can visit the payment setup task from the homescreen if the setup wizard has been skipped (1407ms)
    ✕ Saving valid bank account transfer details enables the payment method (30214ms)
    ✕ Enabling cash on delivery enables the payment method (865ms)

  ● Payment setup task › Saving valid bank account transfer details enables the payment method

    : Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Error:
```

**To Reproduce**

### Manually
1. Initialize a new E2E container without running any of the E2E tests
2. Complete onboarding
3. Go to set up payments from the task list
4. Set up BACS 
5. Once back on the home screen re-load the page

### With E2E
1. Run E2E with #7804 with `npx wc-e2e test:e2e-dev`
2. See screenshot on last two tests

**Screenshots**

<img width="1454" alt="Screen Shot 2021-05-31 at 1 01 27 PM" src="https://user-images.githubusercontent.com/343847/120218920-cc6ea280-c210-11eb-9f2b-d8bb3168f777.png">

**Additional context**
#7804 passes in CI. I want to finish #7804 without making any changes to test code so I created this issue for a PR to address this.

**Comment by samueljseay** [comment]
This one has been a constant frustration for me. I suspected it was because in some scenarios that modal "We're here for help" dialog, doesn't show up, or shows up really delayed.

**Comment by rrennick** [comment]
@samueljseay I update the description with the steps to reproduce manually.

**Comment by rrennick** [comment]
These are passing locally now so I will close the issue. It can be reopened if the issue recurs.
