### ISSUE TITLE
Marketing task - include Pinterest

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7127]
**Description:** we're going to start including Pinterest in the new marketing task the team is building (#7195). The team wants to start with a soft launch in August. They still don't have a date for the inclusion in the Marketing task, but I'll assign this to cycle 15 to make sure that it's on our radar. More info here: https://wp.me/pcTzPy-30

**Copy:** TBD
**Logo:** TBD
**wp.org link:** TBD

**Comment by joshuatf** [comment]
I believe the new remote extensions feature will be ready so we can use the WCCOM hosted file to include this.  Can you confirm @psealock?

**Comment by mattsherman** [comment]
Putting this under the marketing task epic.

**Comment by pmcpinto** [comment]
I chatted with the BizDev team about this and the inclusion will likely only happen during the 4th quarter or early next year.

**Comment by mattsherman** [comment]
> I chatted with the BizDev team about this and the inclusion will likely only happen during the 4th quarter or early next year.

@pmcpinto So, just to be clear -- we should not include this in Cycle 15?

**Comment by pmcpinto** [comment]
Yes. We can exclude it from this cycle.

**Comment by ilyasfoo** [comment]
Closing as I believe this was resolved by https://github.com/woocommerce/woocommerce-admin/pull/7417

**Comment by pmcpinto** [comment]
@ilyasfoo Pinterest hasn't been included in the task, but we also don't have an exact date for inclusion yet. So we can leave this issue closed.
