### ISSUE TITLE
"We're here for help" Pop-up Flickers on iPhone5 width Mobile

### ISSUE THREAD

**Issue by edwinho89** [woocommerce/woocommerce-admin#7135]
**Describe the bug**
The "We're here for help" pop-up flickers on iPhone5 width mobile.

**To Reproduce**

1. Install Woo on an AT site (Business plan)
2. Finish the setup wizard
3. Go to WooCommerce > Home
4. In the "Get ready to start selling" checklist click on any of the fields
5. Wait for "We're here for help" pop-up to appear.

**Expected behavior**
The "We're here for help" pop-up appears normally.

**Screenshots**

![image link 2](https://d.pr/i/kczO2D)
image link: https://d.pr/i/kczO2D

**Smartphone (please complete the following information):**

* Device: iPhone 5 width models

**Additional context**

From web inspector, by manually increasing width to 360px, the flickering does not occur.

Copied from #7090

**Comment by samueljseay** [comment]
@edwinho89 thanks for raising this. It sounds like you've installed latest Woo but can I just confirm a couple of details if possible?

1. What version of Woo/wc-admin are installed? (if you've just installed the woo plugin what version of that?)
2. Is gutenberg installed and if so what version?

The reason I'm asking is to try narrow down if this is related to https://github.com/WordPress/gutenberg/issues/24592 

Thanks.

**Comment by edwinho89** [comment]
Hi @samueljseay 

* Issue first occur most likely on Woo v.5.3.0 (did not obtain wc-admin version as I've just updated Woo), Gutenberg v10.7.2
* Just updated to Woo v5.4.0/wc-admin v2.3.1, Gutenberg v10.7.4 still reproducible.
* Deactivate Gutenberg plugin has no effect, as the result is consistent.

**Comment by joshuatf** [comment]
I was able to reproduce this issue at a 320px viewport.  It does seem related to https://github.com/WordPress/gutenberg/issues/24592 but I can confirm that fix has been shipped in the WP version I'm using and does not resolve the issue in this case.

It still appears this is an issue that needs to be fixed upstream in Gutenberg.  Thoughts @samueljseay?

**Comment by samueljseay** [comment]
@joshuatf I agree this is likely a fix that needs to happen upstream. Alternatively we should consider our own popover implementation if we can't get a fix in a reasonable time because this popover has been a constant source of problems.
