### ISSUE TITLE
RemoteFreeExtensions `DataSourcePoller` incorrectly handle fetch error

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#7138]
**Describe the bug**
It seems when an error occurs during fetch in [this line](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/RemoteFreeExtensions/DataSourcePoller.php#L70) will still store an empty array in the transient `woocommerce_admin_remote_free_extensions_specs`. This results in data stored as an empty array, and ends up the UI rendering empty list.

**To Reproduce**

1. In your local, edit the line [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/RemoteFreeExtensions/DataSourcePoller.php#L16) to a valid URL with a domain that doesn't exist.
2. Delete the transient `woocommerce_admin_remote_free_extensions_specs` if it exists
3. Try to load the list of free extensions in the Business Details step
4. Observe the empty list

**Expected behavior**
~~I think we need to either render the fallback list or at least display error for users.~~

Treat empty array like we're catching error [here](https://github.com/woocommerce/woocommerce-admin/blob/main/client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js#L421).

**Screenshots**
![image](https://user-images.githubusercontent.com/3747241/121132125-534ffa80-c863-11eb-852a-c215da5be34b.png)

**Additional context**
~~The response from [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/RemoteFreeExtensions/DataSourcePoller.php#L70) does contain an error, but I think we're not checking it correctly:~~

My bad, the error was caught correctly.

**Comment by ilyasfoo** [comment]
@samueljseay You're right, I just realized it did handle the error and returned the empty array. But still, we're not properly handling this case in the UI, which I think should render the fallback list instead

**Comment by samueljseay** [comment]
@ilyasfoo thats awesome thanks for digging on that. That probably makes coming up with a fix relatively easy.

**Comment by samueljseay** [comment]
@elizaan36 I feel like we've discussed this in the past without deciding on an approach, but do you have any suggestions how we could indicate an error here? I feel like we need a generic design for error states (maybe modal?) that could be put anywhere that we haven't considered designing an error state for yet because this comes up a bit.

**Comment by ilyasfoo** [comment]
@samueljseay For this case, we have a [catch here](https://github.com/woocommerce/woocommerce-admin/blob/main/client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js#L421), I'm thinking we can just add check for empty array and render the fallback instead

**Comment by samueljseay** [comment]
Oh! gotcha of course, silly me. Yes falling back to local data makes perfect sense.
