### ISSUE TITLE
Table rows and cells should not use index as keys

### ISSUE THREAD

**Issue by ecgan** [woocommerce/woocommerce-admin#7160]
**Describe the bug**

In `<Table>` component, array index is used as keys for table rows and cells:

https://github.com/woocommerce/woocommerce-admin/blob/66cdf344ea615e451428bb8c419f974cf413a44a/packages/components/src/table/table.js#L288-L289

https://github.com/woocommerce/woocommerce-admin/blob/66cdf344ea615e451428bb8c419f974cf413a44a/packages/components/src/table/table.js#L310-L316

If the `rows` array props has a more complex `display` with React, and the `rows` go through some _addition_ or _deletion_, the UI would end up rendering rows wrongly because of the use of array index as keys.

```js
// example of rows: (data would go through possible addition / deletion in the page)
			rows={ data.map( ( el ) => {
				return [
					{ display: el.title },
					{
						display: (
							<div className="program-actions">
								<EditProgramButton programId={ el.id } />
							</div>
						),
					},
				];
			} ) }
```

A workaround to this problem is to specify `key` in the `display`, using the array element's unique id:

```js
// example of rows: (data would go through possible addition / deletion in the page)
			rows={ data.map( ( el ) => {
				return [
					{ display: el.title },
					{
						display: (
							// specify key here, using the array element's unique id.
							<div key={ el.id } className="program-actions">
								<EditProgramButton programId={ el.id } />
							</div>
						),
					},
				];
			} ) }
```

For more info with animated gif screenshots, please see issue https://github.com/woocommerce/google-listings-and-ads/issues/762 and its PR https://github.com/woocommerce/google-listings-and-ads/pull/771.

**To Reproduce**
See the above description. Problem can be reproduced by:

1. Using the `Table` (or `TableCard`) component.
2. `rows` prop with complex `display` using React components.
3. `rows` goes through addition or deletion via event handler.

**Expected behavior**

Rows would display correctly after addition or deletion.

**Screenshots**

The following screenshot is from issue https://github.com/woocommerce/google-listings-and-ads/issues/762. We remove the second row, with the disabled toggle button. The third row has an enabled toggle button. After the deletion is complete, the third row becomes the second row, its toggle button should be rendered as enabled (expected behavior), but it is rendered as disabled (actual behavior).

![example](https://user-images.githubusercontent.com/17420811/121119588-7623e400-c84e-11eb-9cd2-7a560bd9d1a4.gif)

**Additional context**

React's documentation on [Lists and Keys](https://reactjs.org/docs/lists-and-keys.html) says:

> We don’t recommend using indexes for keys if the order of items may change. This can negatively impact performance and may cause issues with component state. 

[Ant Design Table](https://ant.design/components/table/) component can serve as a reference. They allow consumer to specify `key` in the `Table`'s `dataSource` and `columns` props.

**Comment by louwie17** [comment]
Thanks @ecgan for creating this issue. I do agree we should make use of an `id` of some kind instead of using index.
I did label it for a cool-down period as it is not huge priority and might require some refactoring of the table component.

We could add a `key` prop, that could be used for the row key and fall back to index-> `key={row[prop.key] || index}`

I do think we should move towards using `children` here and allow the user to add the `key` for each row, similar to [this example](https://codesandbox.io/s/htvjz?file=/demo.js), but I will leave that up to the implementor.

In the mean time, I do recommend making use of `useEffect` for any components that handles state internally, so that if an outside variable changes it updates correctly within, not only on row removal, but also for row updates (something the key addition won't fix).

**Comment by ecgan** [comment]
@louwie17 ,

> We could add a `key` prop, that could be used for the row key and fall back to index-> `key={row[prop.key] || index}`

`key` is a special reserved keyword for React. From [React's documentation](https://reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings):

> Keys serve as a hint to React but they don’t get passed to your components. If you need the same value in your component, pass it explicitly as a prop with a different name.

I'm thinking maybe a `rowKey` props like this would help: 

```js
rows={ [
	{
		id: 1,
		title: 'Program 1',
		amount: 111,
	},
] }
rowKey={(row, index) => {
	// row comes from the rows array above.
	return row.id
}}
```

> I do think we should move towards using `children` here and allow the user to add the `key` for each row, similar to [this example](https://codesandbox.io/s/htvjz?file=/demo.js), but I will leave that up to the implementor.

Thanks for the example, it looks pretty good. Just want to voice out that it does look pretty verbose if I were to compare with it with Ant Design Table. 😄

**Comment by louwie17** [comment]
Oops yeah forgot `key` would be the special keyword, `rowKey` sounds great.
I like the two types it supports -> string | function(record): string
