### ISSUE TITLE
[GlobalStep- 2.4.0 Beta 1] "Dismiss" button is not center aligned on tasks under "Things to do next". 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#7174]
## Bug Description:
"Dismiss" is not center aligned on "Three dot option" of "Set up Google listing and Ads" under "Things to do next". on WooCommerce->Home.

## Environment:
Woocommerce Version : WooCommerce 5.4.1
WordPress version: (v5.7.2)
WooCommerce Admin: v2.4.0 Beta 1.

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Install and activate WooCommerce Admin 2.4.1 beta 1 plugin.
1. Complete the OBW setup with selecting "Google listing and Ads" under free features tab.
1. Go to Woocommerce >> Home screen.
1. Click on  "Three dot option" of "Set up Google listing Ads" under "Things to do next". 
1. Observe that the "Dismiss" button is not center aligned.

## Actual Result:
"Dismiss" button is not center aligned on tasks under "Things to do next".

## Expected Result:
"Dismiss" button should be center aligned.

## Screenshot:
![#7174](https://user-images.githubusercontent.com/41110392/121715065-1ce0dc80-cafc-11eb-9048-4e1e49af5e84.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by louwie17** [comment]
The original ticket showed this as left aligned - https://github.com/woocommerce/woocommerce-admin/issues/6637#issue-838246349 
@elizaan36 do we want to center align this as well to match the `Hide this` ellipsis of the main task list?

**Comment by elizaan36** [comment]
Thanks for creating this issue!🌟

@louwie17 
I think we should leave it left-aligned because when there are other actions in the menu such as Remind me later, it would look worse if the items are centered.

Is there any way to have the popover only extend the width of the content so there isn't additional space on the right side, or expand the focus outline to the full width of the popover?

**Comment by louwie17** [comment]
> Is there any way to have the popover only extend the width of the content so there isn't additional space on the right side, or expand the focus outline to the full width of the popover?

@elizaan36 either one would work, when expanding the focus outline we would have to center the text to make it look better, as shown below:

<img width="247" alt="Screen Shot 2021-06-16 at 11 09 01 AM" src="https://user-images.githubusercontent.com/2240960/122234609-63835d80-ce93-11eb-8923-95fb5a59f0e9.png">
<img width="260" alt="Screen Shot 2021-06-16 at 11 08 54 AM" src="https://user-images.githubusercontent.com/2240960/122234623-667e4e00-ce93-11eb-8130-1376ce6b1dca.png">

We can certainly also extend the width to the content, if you are ok with the width being different depending on if `remind me later` is shown or not.

**Comment by elizaan36** [comment]
hey @louwie17 no idea how I missed this reply.

> @elizaan36 either one would work, when expanding the focus outline we would have to center the text to make it look better, as shown below

Your solution sounds great, expanding the focus outline to the content with centered text. It would definitely be an improvement!
