### ISSUE TITLE
Older published product when moved to draft still appears in reports

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-admin#7179]
**Describe the bug**
In this case with a customer we were looking at the Out of Stock report, but I imagine it might show up elsewhere as well?

Nonetheless, they'd taken an older product that's been published before and moved it's status to draft. Then when looking at their Out of Stock report it still appeared there.

**To Reproduce**

1. Go to a product you've had published before
2. Set it to out of stock
3. Set its status to Draft

**Expected behavior**
Normally a product that is set to Draft doesn't appear in any reports in the Analytics.

**Screenshots**
<img width="1430" alt="Screen Shot 2021-06-07 at 4 25 37 PM" src="https://user-images.githubusercontent.com/867748/121825601-63137880-cc81-11eb-8ea1-34539135a7ca.png">

<img width="1429" alt="Screen Shot 2021-06-07 at 4 24 34 PM" src="https://user-images.githubusercontent.com/867748/121825603-6575d280-cc81-11eb-9ad4-a4f903843883.png">

Looking at these two screenshots it's the product titled "Vanquest Gray/Tan/RACKIT - 36 Rifle Pack - Tan" as the product that is drafted but also showing in the Out Of Stock report.

**Comment by joshuatf** [comment]
Thanks for taking the time to outline this issue, @ryanr14!

I wasn't able to reproduce the issue and after setting a product to `draft`, it was no longer visible in the out of stock list. 

* Could you confirm the WooCommerce and WooCommerce Admin version you're using?  Are you using the feature plugin of WooCommerce Admin or the version bundled with WooCommerce?
* Do you have any other forms of caching enabled on your site?

Under the hood, this uses the `WP_Query` to find products, which defaults to only [published items](https://developer.wordpress.org/reference/classes/wp_query/#status-parameters) so I suspect there may be some level of caching occurring somewhere.

**Comment by theabhig** [comment]
Hi @joshuatf! I was able to replicate the issue on my own test but only with a variable product.

I had a published variable product, which I set to draft and out of stock and the variations still show in the Out of stock list.

When I tried it with a simple product, it was hidden from the out of stock list when I set it to draft and out of stock.

I tried using just WooCommerce 5.4.1, and then also tried with WooCommerce 5.4.1 + WooCommerce Admin 2.3.1.

I also tried clearing transients and analytics cache from _WooCommerce > Status > Tools_ to see if that had an impact.

**Comment by joshuatf** [comment]
That did it!  Thanks for the extra details 😄 

It appears that when a variable product is set to `draft` the children (variants) are always set to `publish`.  We may need to throw an extra check in here to get the parent's status if the product being checked is a variant.

**Comment by wpniall** [comment]
As far as I can tell, the same behavior seems to happen for **new** variable products too on a new Jurassic Ninja site: 

- I created a new variation, set up 3 attributes, and then created variations out of those attributes _without_ touching any stock settings (so they variations are `In stock` by default)
- I then saved as `Draft`.
- The variations appear in the `In stock` list
- I set 1 variation to `In stock`, 1 to `Out of stock`, and the 3rd to `On backorder`, then again saved as `Draft`. I see all three variations in the `Stock > All Products` analytics and their respective subcategories (i.e., the `In stock` variation appears under `Stock > In Stock`:

![https://d.pr/i/cSg1jU](https://d.pr/i/cSg1jU+) 
Full Size: https://d.pr/i/cSg1jU

After setting `Enable stock management at product level` with a `Stock quantity` of `0`, the variations still appear in the `Stock` analytics:

![https://d.pr/i/Y26eul](https://d.pr/i/Y26eul+) 
Full Size: https://d.pr/i/Y26eul

The same happens after setting the `Stock quantity` to `1`:

![https://d.pr/i/rm4D2E](https://d.pr/i/rm4D2E+) 
Full Size: https://d.pr/i/rm4D2E

The same behavior does not happen with simple products.

> It appears that when a variable product is set to draft the children (variants) are always set to publish.

Yes, my additional testing appears to show that too. After publishing the variable product I tested, the parent product appeared along with the children, which it did not when set to `Draft`:

![https://d.pr/i/2hX7mG](https://d.pr/i/2hX7mG+) 
Full Size: https://d.pr/i/2hX7mG
