### ISSUE TITLE
Business features step: include WCPayments in a new batch of EU countries

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7180]
**Description:** we already have the next batch of European countries where we want to promote WCPayments on the business features step. The goal is to start promoting WCPayments outside of the Core release (August 4), so we need to take advantage of the remote recommendations on the business features step to implement this promotion.

**Acceptance criteria:** 

- [ ] Include the WooCommerce Payments promotion on the business features step (https://d.pr/i/9KsBMb) in the following countries: AT, BE, NL, PL, PT, and CH
- [ ] Start the promotion on August 4

**Comment by joshuatf** [comment]
If this will go under the remote config, we'll need to make sure and coordinate with the WCCOM team to merge and deploy on that date.

**Comment by pmcpinto** [comment]
> If this will go under the remote config, we'll need to make sure and coordinate with the WCCOM team to merge and deploy on that date.

Good point. cc @mattyza, just so you're aware of this

**Comment by becdetat** [comment]
@pmcpinto @joshuatf What's the status of this? Was it implemented?

**Comment by pmcpinto** [comment]
The WCPay launch only happened a couple of days ago, so it should be implemented this week. I created a new [issue ](https://github.com/woocommerce/woocommerce-admin/issues/7862)about this in WC Admin.
cc @louwie17

**Comment by ilyasfoo** [comment]
Closing this as I believe it was done in 11640-gh-Automattic/woocommerce.com
