### ISSUE TITLE
Finish Setup state not working correctly with payment gateway suggestions feature

### ISSUE THREAD

**Issue by joelclimbsthings** [woocommerce/woocommerce-admin#7184]
With the `payment-gateway-suggestions` feature enabled, the "Finish Setup" state (pictured below) is not displaying as expected. 

![image](https://user-images.githubusercontent.com/444632/121969375-f9e74000-cd28-11eb-913c-e889ada28f3a.png)

~~May need some clarity on exactly how we want this to work in the payments task, and exactly how different statuses play a part; ie `enabled` and `configured`, which are used somewhat interchangeably at the moment.~~

In summary, we need to change the "Finish setup" state to be triggered by installation, not enabling/configuring. Also make any changes necessary to match the following states:

**Just suggested (not installed/enabled/configured)**
Currently this shows in the "Additional Gateways" list with "Setup" button.
No change needed.

**Installed, not enabled/configured**
Currently still the same as above, but this should trigger the "Finish Setup" state.

**Installed & Enabled but not configured**
This should still show the "Finish setup state"

**Configured but not enabled**
This should just show the "Manage" button.

**Comment by joshuatf** [comment]
@joelclimbsthings Curious to hear what's not working as expected.

My understanding of when each button should show is:

* Not enabled -> show "Set up"
* Enabled, but not configured -> Show "Finish setup"
* Enabled and configured -> Show "Manage"

**Comment by joelclimbsthings** [comment]
@joshuatf I need to confirm this, but I believe the issue is that we currently have no way to reach the 2nd state through the payment task alone. The only way we have to `enable` a gateway is the `markConfigured` function, which we only run if we are configuring the gateway within the task as well.

In that case, we skip from the 1st state to the 3rd. The only way they'll see the 2nd state is if they install the gateway through the payment task, navigate into the payment settings, enable a gateway there, and then return the task later. This doesn't feel quite right to me, but perhaps it's expected?

My hunch is that we should show the "Finish setup" state as soon as the plugin has been installed, ignoring the enabled state, and then only enable it if it's configured through the payment task as well (as we're currently doing).

Pinging @elizaan36 and @pmcpinto to clarify.

**Comment by elizaan36** [comment]
Thanks for bringing this up, Joel! Had a chat in Slack and wanted to clarify the use case for the "Finish setup" UI here. 
- "Finish setup" would appear if a plugin has already been installed but is not configured, and it would appear whether the gateway is enabled or not. 
- Once the payment method is configured, the "Manage" state would appear, also regardless of whether the method is enabled or not.

**Comment by joelclimbsthings** [comment]
Awesome, thanks for the clarification @elizaan36 . 

Just to summarize, we have these 4 states:

**Just suggested (not installed/enabled/configured)**
Currently this shows in the "Additional Gateways" list with "Setup" button.
No change needed.

**Installed, not enabled/configured**
Currently still the same as above, but this should trigger the "Finish Setup" state.

**Installed & Enabled but not configured**
This should still show the "Finish setup state"

**Configured but not enabled**
This should just show the "Manage" button.

**Comment by joshuatf** [comment]
>I believe the issue is that we currently have no way to reach the 2nd state through the payment task alone.

Correct, however keep in mind that redirection to the settings screen can and will occur for gateways.  A user may enable a gateway without configuring it, in which case the "Finish setup" should still be shown.

>My hunch is that we should show the "Finish setup" state as soon as the plugin has been installed, ignoring the enabled state, and then only enable it if it's configured through the payment task as well (as we're currently doing).

👍

**Comment by joelclimbsthings** [comment]
I'm a little unsure of how to handle BACS (direct bank transfer). Since it's included within WooCommerce itself, it's always flagged as "installed." As a result once I make these changes it will always show the "finish setup" state right off the bat:

![image](https://user-images.githubusercontent.com/444632/122145632-77cf4800-ce0a-11eb-8578-65ebf3199bdf.png)

As far as I can see this is the _only_ gateway that would have this issue, as it's the only one that is embedded within Woo and requires setup. I suppose we need to suppress this state, or perhaps only display it when "enabled" but not "configured." Again, this only applies to BACS, so it would require some special handling. Perhaps flagging it in some way in the configuration, or is there a way to surface that a gateway is installed by default? 

End of day for me now, but I'll think about this more tomorrow.

Any thoughts here @joshuatf @psealock ?

**Comment by joshuatf** [comment]
@joelclimbsthings Why don't we check to see if a gateway has `plugins`?  This seems to be the differentiator here.

```js
if ( ! plugins.length && ! isConfigured ) {
  // Set up button
}
```

**Comment by pmcpinto** [comment]
> I'm a little unsure of how to handle BACS (direct bank transfer). Since it's included within WooCommerce itself, it's always flagged as "installed." As a result once I make these changes it will always show the "finish setup" state right off the bat:
> As far as I can see this is the only gateway that would have this issue, as it's the only one that is embedded within Woo and requires setup. I suppose we need to suppress this state, or perhaps only display it when "enabled" but not "configured." Again, this only applies to BACS, so it would require some special handling. Perhaps flagging it in some way in the configuration, or is there a way to surface that a gateway is installed by default?

@joelclimbsthings we have the same issue with COD, right? Unless I'm missing something, it seems that both are disabled by default: https://d.pr/i/5gc245 Showing the "Finish setup" button with the method disabled can be confusing. If possible I'd show the "Setup" button. @elizaan36 any thoughts on this?

**Comment by joelclimbsthings** [comment]
> Why don't we check to see if a gateway has plugins? 

That's a great idea @joshuatf . I think that'll work 👍🏻 .

> we have the same issue with COD, right?

Not exactly, since as it is COD doesn't require any setup as is, and just displays an "Enable" button instead. 

![image](https://user-images.githubusercontent.com/444632/122250657-b0a90480-ce7e-11eb-89a9-6de31f6fdd08.png)

**Comment by elizaan36** [comment]
The "Finish setup" state would only apply to plugins, not the core payment methods. So if possible it wouldn't appear for Bacs or COD. I think @joshuatf 's suggestion makes perfect sense.

So it shows "Set up" for Bacs and "Enable" for COD (since there isn't any configuration required).
