### ISSUE TITLE
[GlobalStep] "Rate" Column appears misaligned on Analytics >Taxes screen. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#7198]
## Bug Description:
 "Rate" Column appears misaligned on Analytics >Taxes screen. 

## Environment:
Woocommerce Version : WooCommerce 5.4.1
WordPress version: (v5.7.2)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Add tax rates from woocommerce home screen.
1. Place order for any product from front end.
1. Go to Analytics > Taxes screen.
1. Observe that "Rate" Column appears misaligned. 

## Actual Result:
"Rate" Column appears misaligned on Analytics >Taxes screen. 

## Expected Result:
"Rate" Column should be properly align on Analytics >Taxes screen. 

## Screenshot:

![#7198](https://user-images.githubusercontent.com/41110392/122247843-49726b00-cee5-11eb-9846-c31ad74b43d8.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by joshuatf** [comment]
Thanks, @gglobalstep!

I can reproduce this as well.  For some reason the horizontal padding on the table items does not match the padding on the table headers leading to the visual offset.

**Comment by hsingyuc** [comment]
I'll push a PR shortly.
