### ISSUE TITLE
Misaligned Buttons in OBW under WP 5.5

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7207]
**Describe the bug**
Some of the the buttons, particularly "Continue", are misaligned in the Onboarding Wizard under WordPress 5.5 (see screenshots).

The buttons are still functional.

**To Reproduce**

On site under WordPress 5.5

1. Start the Onboarding Wizard.
2. See that the continue button is misaligned.
3. Continue to the theme selection screen.
4. See that buttons are misaligned.

**Expected behavior**
The text in the buttons to be center-aligned.

**Screenshots**
<img width="526" alt="Screen Shot 2021-06-18 at 9 41 42 am" src="https://user-images.githubusercontent.com/9312929/122493053-96eff480-d019-11eb-868e-b2b4f6237152.png">

<img width="416" alt="Screen Shot 2021-06-18 at 10 16 21 am" src="https://user-images.githubusercontent.com/9312929/122497745-7d05e000-d020-11eb-893a-142d6d6a73ff.png">

**Desktop (please complete the following information):**

* OS: macOS
* Browser Chrome, Firefox, Safari

**Comment by ilyasfoo** [comment]
Thanks for reporting this @adrianduffell!

It seems that in WordPress 5.5, there were some styling conflicts with WooCommerce. I'm not entirely sure where the origin of style came from, but I don't think there's any simple fix that we could do that won't also affect the latest WooCommerce:

![image](https://user-images.githubusercontent.com/3747241/122500746-ea683f80-d025-11eb-9ccd-9517ac499641.png)

I think it's best to not fix this for now
