### ISSUE TITLE
Onboarding other Industry field name translation string not registered

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce-admin#7211]
**Describe the bug**
A Onboarding wizard other Industry description field name translation string is not registered as a string available for translations, it's always in English.

**To Reproduce**

1. Switch WP language to non-en.
2. Turn on WooCommerce plugin and start a Onboarding wizard.
3. Go to step 2 - Industry and click on "Other" checkbox.
3. Look at the Description field's placeholder

**Expected behavior**
https://github.com/woocommerce/woocommerce-admin/blob/228bdb1b64b4cb3f719737a031bf6bc10960026b/src/Features/Onboarding.php#L407 
The description label should be registered as an tranlsation string `__( 'Description', 'woocommerce' )`

**Screenshots**
![Zrzut ekranu 2021-06-21 o 15 03 02](https://user-images.githubusercontent.com/27000783/122766435-cf096880-d2a1-11eb-8214-956f13dac546.png)

WP 5.7.2
WC 5.4.1
WC Admin 2.3.1 (bundled with WC)

**Comment by octaedro** [comment]
Thank you @starypop for reporting this bug.
I can reproduce it and the solution is almost exactly what you mentioned. [This line](https://github.com/woocommerce/woocommerce-admin/blob/228bdb1b64b4cb3f719737a031bf6bc10960026b/src/Features/Onboarding.php#L407) should be modified by:
`__( 'Description', 'woocommerce-admin' )`

**Comment by hsingyuc** [comment]
I'll push a PR shortly.
