### ISSUE TITLE
Onboarding Business features step translation strings not registered

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce-admin#7212]
**Describe the bug**
Onboarding business features step translation strings are not registered as a string available for translations, it's always in English.

**To Reproduce**

1. Switch WP language to non-en.
2. Turn on WooCommerce plugin and start a Onboarding wizard.
3. Go to "Included business features" tab at step 4.
3. Look at the Screenshot above to see what 3 fields are not registered:

- "**Add recommended business features to my site**" checkbox label
- "**Grow your store**" section label
- "**Continue**" button (it is translated correctly at other steps)

**Expected behavior**
Those 3 labels should be registered for translations.

**Screenshots**
![Zrzut ekranu 2021-06-21 o 15 36 57](https://user-images.githubusercontent.com/27000783/122772235-7341de00-d2a7-11eb-8b02-35ab89c407ef.png)

WP 5.7.2
WC 5.4.1
WC Admin 2.3.1 (bundled with WC)

**Comment by octaedro** [comment]
Thanks for reporting this error @starypop.

A fix for the `Grow your store` label is currently in place [in main](https://github.com/woocommerce/woocommerce-admin/blob/main/client/profile-wizard/steps/business-details/flows/selective-bundle/selective-extensions-bundle/index.js#L144), but the other 2 errors are still there.
