### ISSUE TITLE
Refunded Shipping Costs Are Not Reflected In WooCommerce Analytics Totals

### ISSUE THREAD

**Issue by theabhig** [woocommerce/woocommerce-admin#7227]
**Describe the bug**

When the shipping costs of an order are refunded, it should show a negative value in the Shipping column under Analytics > Revenue and be reflected in the total at the top of the page.

However it does not appear to update this correctly.

**To Reproduce**

1. Place an order which has a shipping cost
2. Confirm shipping cost has been added to Analytics > Revenue. It will show in the total at the top of the page and also on the date summary section.
3. Refund the shipping cost of the order
4. Review Analytics > Revenue. The total at the top of the page will still show the amount from before the refund, and the negative value of the refund will not be reflected in the day by day summary further down.

**Expected behavior**

As per the [documentation](https://docs.woocommerce.com/document/woocommerce-analytics/#analytics-basics__refunds): 

> Refunded shipping charges and refunded taxes are not included in the Refunds summary number or columns. They appear as negative values in the shipping and taxes summary numbers and columns respectively.

So we would expect the refunded cost to be removed from the shipping total at the top of the page and also a negative amount for the amount of the shipping cost refund to be reflected in the daily summary.

**Screenshots**

Test order where $1 shipping cost was refunded:

![Annotation on 2021-06-22 at 07-48-45](https://user-images.githubusercontent.com/75635198/123095303-db1e3300-d425-11eb-909a-a876aae3b558.png)

Analytics not reflecting $1 shipping cost refund from date of original order (15 May):

![Annotation on 2021-06-22 at 08-47-22](https://user-images.githubusercontent.com/75635198/123095431-f9842e80-d425-11eb-8c59-869b887b1f21.png)

Analytics not reflecting shipping cost refund on date refund was processed (22 June):

![Annotation on 2021-06-22 at 08-48-21](https://user-images.githubusercontent.com/75635198/123095527-10c31c00-d426-11eb-8ae4-06271ef2f8e6.png)

**Additional context**

Reported in 4075510-zen 

Feedback in Slack:

p1624345855072500-slack-C7U3Y3VMY

**Comment by octaedro** [comment]
Thank you for creating this issue @theabhig.
I was trying to reproduce the error with no luck. 
![Captura de Pantalla 2021-06-23 a la(s) 11 55 04](https://user-images.githubusercontent.com/1314156/123119779-334f3800-d41a-11eb-9490-64bd410c5ed0.png)

Do you have more details about the context of where it was happening?

**Comment by octaedro** [comment]
Hi @theabhig sorry for the back and forth.
I was taking a look at our opened issues and it seems that there is [another issue](https://github.com/woocommerce/woocommerce-admin/issues/7197) that has been created reporting this same bug and [a PR](https://github.com/woocommerce/woocommerce-admin/pull/7253) to solve it.
I'll close this issue now. Please let me know if I'm missing something and I'll reopen the issue.
