### ISSUE TITLE
Action to dismiss all notes with confirmation modal

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7243]

**Comment by elizaan36** [comment]
As a user I want to dismiss all Inbox notes from WooCommerce home to reduce clutter.

The Inbox header contains an ellipses menu with one option, "Dismiss all".
![Screen Shot 2021-06-24 at 2.10.35 PM.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/0a0d1769-8d82-4ee2-99ec-b4a934945a39)

Upon clicking "Dismiss all", a confirmation modal appears.
![Screen Shot 2021-06-24 at 2.11.31 PM.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/44eee226-0171-4153-96d3-8824fb33e3c3)

Choosing to dismiss all messages will remove the Inbox panel from the home screen. Once a new note is loaded, the panel will appear again.

More info in pbIJXs-TQ

**Comment by pmcpinto** [comment]
@elizaan36 all the issues in this epic look good to me. Great work.

I just think that we need to add new tracking to track this new behavior. Or repurpose the existing Tracks.

**Comment by elizaan36** [comment]
Thanks Pedro, I'll add a new Tracks into the comment above. And try to adjust the others.
