### ISSUE TITLE
Remove blue dots for Inbox unread state and add text/color changes to read state

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7244]

**Comment by elizaan36** [comment]
To make way for the recommended notes experiment, the unread state of Inbox notes will no longer include the blue notification dot. Instead, the read state will be differentiated in two ways:
- The title text weight changes from bold to regular
- The CTA link changes from the WP theme color to $gray-900

![Frame 696.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/6d0ff1a1-8d7a-4e92-b7f8-805c8137f2f2)

More info in pbIJXs-TQ

**Comment by moon0326** [comment]
This has been worked on in https://github.com/woocommerce/woocommerce-admin/pull/7896

**Comment by adrianduffell** [comment]
Fixed in PR https://github.com/woocommerce/woocommerce-admin/pull/7896
