### ISSUE TITLE
Change button style to tertiary and remove footer border

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7246]

**Comment by elizaan36** [comment]
To conserve space in the feed, the CTA for Inbox notes will be tertiary text links with the WP theme color. 
Also, the border separating the footer is removed so the gap between body copy and CTA is reduced.

![Screen Shot 2021-06-24 at 3.19.26 PM.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/d672ef4b-5092-42f8-a8b1-f900d9e932a2)

**Comment by ilyasfoo** [comment]
Hey @moon0326, can this be closed?
