### ISSUE TITLE
Introduce a 320 character limit for Inbox notes

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7247]

**Comment by elizaan36** [comment]
**Problem to solve**
There's currently no limit to the amount of content presented to users in Inbox notes. This can lead to a lot of noise and a poor user experience.

**Example**
![Screen Shot 2021-06-24 at 1.31.10 PM.png](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/85bd5be0-8159-4435-9159-6bec82245ac1)

**Solution**
To prevent this issue and to ensure the best user experience, we can introduce a 320 character limit for Inbox notes.

**Comment by moon0326** [comment]
@elizaan36 How do we handle the existing notes with more than 320 characters? Do we want to apply a 320 character limit only for the new notes?

**Comment by elizaan36** [comment]
It would be best to apply this to all notes. I'm wondering if we could surface an error message to indicate that the Inbox note has reached the character limit. What would you suggest is the best place for that?
