### ISSUE TITLE
Snackbar notices block clicks in adjacent content

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-admin#7252]
**Describe the bug**
When a snackbar is displayed, you can't click on any UI that is parallel with the snackbar.

I think it's because there's a container div which is capturing/blocking clicks.

Possibly this is a Gutenberg / wp components issue? I haven't explored deeper, definitely impacts Woo admin UI so reporting here.

**To Reproduce**
I initially noticed this in a Pinterest extension, using wc-admin snackbars, but can reproduce it in the main task list page. I'm guessing it affects any snackbar.

1. Go to `admin > WooCommerce` with some things to dismiss.
2. Dismiss something.
3. Snackbar appears.
4. Scroll so some other UI is next to the snack bar (in line horizontally).
5. Try to click the UI.

**Expected behavior**
Should be able to interact with any visible UI, snackbar should have no effect apart from whatever is obscured by it.

**Screenshots**
<img width="1458" alt="Screen Shot 2021-06-25 at 8 07 58 AM" src="https://user-images.githubusercontent.com/4167300/123327199-45ea7e00-d58e-11eb-9ff6-bef9ef2f365e.png">

Have seen this on Chrome and Safari on macOS, and in WooCommerce with and without current WooCommerce Admin (2.3.1) plugin active.

**Comment by octaedro** [comment]
Thank you @haszari for reporting this bug.
I can reproduce it. It looks like there is an overlap problem.
