### ISSUE TITLE
Custom filter query args not getting passed to wp-json calls

### ISSUE THREAD

**Issue by kaysersoze** [woocommerce/woocommerce-admin#7259]
**Describe the bug**
When adding a custom filter to a report (eg., Orders) the corresponding query string argument is appended, but the query string argument and value is not passed to the JSON (eg, /wp-json/wc-analytics/reports/orders). This occurs for both basic and advanced filters. It seems to work for built-in filters, ie. Customer Type, but not a custom filter.

**To Reproduce**
1. Create extension following example in https://github.com/woocommerce/woocommerce-admin/tree/main/docs/examples/extensions/sql-modification
2. Use custom filter to filter report data
3. Observe query argument added to browser URL bar
4. Observe subsequent XHRs not getting passed custom query string argument
5. Observe XHRs not triggered when changing custom filter value

**Expected behavior**
Selecting and changing custom filter values should pass query string argument and value to report XHRs as they do with built-in filters.

**Screenshots**
<img width="962" alt="Screen Shot 2021-06-27 at 11 48 31 PM" src="https://user-images.githubusercontent.com/735028/123595048-4ad54a80-d7a5-11eb-8d47-b3168d9acc8e.png">
<img width="1180" alt="Screen Shot 2021-06-27 at 11 49 55 PM" src="https://user-images.githubusercontent.com/735028/123595051-4b6de100-d7a5-11eb-8475-874e2d5d7bbb.png">
<img width="1185" alt="Screen Shot 2021-06-27 at 11 50 31 PM" src="https://user-images.githubusercontent.com/735028/123595056-4c9f0e00-d7a5-11eb-83a9-23bb79c2542d.png">

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Firefox Developer Edition
* Version: 90.0b12

**Additional context**
Any assistance with this would be greatly appreciated. If I manually replay the XHR call to `/wp-json/wc-analytics/reports/orders` and pass the custom argument `sale_type=wholesale`, it works and I see the SQL WHERE subquery get the value passed correctly, and returns the correctly filtered orders. I feel like I'm going crazy! I've already made sure that the query args are getting added in `woocommerce_analytics_orders_query_args` and `woocommerce_analytics_orders_stats_query_args` like in the example. This _seems_ like it should be working, but it just isn't. Could this be a caching issue with the DataStore? Is there query argument filtering somewhere non-obvious in WC-Admin?

**Comment by ilyasfoo** [comment]
Hi there @kaysersoze,

I think you may have used the incorrect filter for adding a custom filter. If you want to add a custom advanced filter in the orders report, you need to use `woocommerce_admin_orders_report_advanced_filters`. You can refer to the codes used to generate the config for the filter [here](https://github.com/woocommerce/woocommerce-admin/blob/d5a4d66a7218b11bbb00624d3ec0bfe10b4de739/client/analytics/report/orders/config.js#L67).

As an example, you can try the following code to the example extension and see if it adds a custom filter to advanced filters:
```js
addFilter(
  'woocommerce_admin_orders_report_advanced_filters',
  'plugin-domain',
  ( report ) => {
    return {
      ...report,
      filters: {
        ...report.filters,
        sale_type: {
          labels: {
            add: 'Sale Type',
            remove: 'Remove order custom filter',
            rule: 'Select an order status filter match',
            title:
              '{{title}}Custom filter{{/title}} {{rule /}} {{filter /}}',
            filter: 'Select an thing you want',
          },
          rules: [
            {
              value: 'is',
              label: 'Is',
            },
            {
              value: 'is_not',
              label: 'Is Not',
            },
          ],
          input: {
            component: 'SelectControl',
            options: [
              {
                value: 'value 1',
                label: 'label 1',
              },
              {
                value: 'value 2',
                label: 'label 2',
              },
            ],
          },
        },
      },
    };
  }
);
```

**Result:**

![image](https://user-images.githubusercontent.com/3747241/123943950-36749600-d9cf-11eb-882a-21304aac549f.png)

Hope that helps!

**Comment by kaysersoze** [comment]
Thanks @ilyasfoo, that actually helps a lot! 

For clarification: when implementing custom Advanced Filters, must the filters have is/is_not rules and subsequent query string arguments (ie. `sale_type_is`) in order to be passed to the wp-json calls correctly?

As soon as I did that, the arguments started being passed correctly - in other words, it's working as I would expect. I still have to implement the adjusted query logic, but now that I'm actually seeing the parameters, that's easy enough.

I think further obfuscating the issue was some really aggressive caching on the WP Engine side, so I've taken to disabling and re-enabling my plugin when I make changes for testing.

One additional question: shouldn't I be seeing an "Is/Is Not" selection in my filter, as per your example screenshot? It's working enough for me to continue developing for the "is" portion of the query, but I'm confused as to why your example is different than mine, even though the advanced filters are configured the same.

<img width="901" alt="Screen Shot 2021-06-30 at 9 27 01 AM" src="https://user-images.githubusercontent.com/735028/123998872-c3473180-d986-11eb-842b-7b11430d0096.png">
