### ISSUE TITLE
Database Update Done notices keep reappearing after dismissing

### ISSUE THREAD

**Issue by markpfaff** [woocommerce/woocommerce-admin#7264]
After completing WooCommerce database update, a message appears:
"WooCommerce database update done WooCommerce database update complete. Thank you for updating to the latest version!" 

Clicking the "Thanks" button dismisses the message but it just reappears. I tried clearing cache, clicking the button multiple times, and logging in and out. 

This issue has been "Closed" multiple times even though it isn't fixed. The last mention of it in issue [#6369](https://github.com/woocommerce/woocommerce-admin/issues/6369) promised a fix in the March WooCommerce 5.1.0 release which doesn't seem to have worked. Here are some past mentions:

[#4114](https://github.com/woocommerce/woocommerce-admin/issues/4114)
[#6211](https://github.com/woocommerce/woocommerce-admin/issues/6211)
[#3497](https://github.com/woocommerce/woocommerce-admin/pull/3497)
[#6369](https://github.com/woocommerce/woocommerce-admin/issues/6369)

This happens on WordPress 5.7.2 with WooCommerce 5.3.0 on multiple sites.

**Comment by ilyasfoo** [comment]
Hi @markpfaff, apologies for the back and forth. I have tried to reproduce this by doing the following:
1. In a fresh WordPress 5.7.2 site, install WooCommerce 5.4.1
2. Force a database update procedure by updating the option`woocommerce_db_version` to `4.4.0`
3. Refresh WooCommerce > Home and update database
4. Dismiss the thank you notice and the notice does not come back

![image](https://cdn-std.droplr.net/files/acc_1119691/yFx4V7)

Is it's possible for you to try updating to WooCommerce 5.4.1 and see if the problem persists? If it does, maybe you can look into your browser console or networks tab to see if there are any errors and paste them here if any.

**Comment by JakeQZ** [comment]
Not fixed in WC 5.6.0.

**Comment by JakeQZ** [comment]
After a few days, the notice has finally stopped coming back, without anything being done.  But I am sure the problem will be back after the next update.

I am using Firefox (on Windows 10) - this might be significant if you are only testing against Chromium-based browsers.

**Comment by ilyasfoo** [comment]
Thank you for the update @JakeQZ. Hope the error had gone for good, it could've been something that had persisted in your WordPress instance that made it stay there.

I'm going to close this issue for now, feel free to reopen if it ever happens again.
