### ISSUE TITLE
Inbox notes returns empty

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#7265]
**Describe the bug**
A recent change in admin notes has caused a regression, it seems that not all relevant notes are returned and API returns an empty array when it shouldn't. I was able to reproduce this with WooCommerce 5.4.1 paired with wcadmin 2.4.0.

I wasn't able to find out the exact cause, but reverting the PR commit https://github.com/woocommerce/woocommerce-admin/commit/68e1f50d26b79f4eef046ffe941cbb0bbda0b5fe seems to resolve the issue.

**To Reproduce**

1. In a fresh JN site, install WooCommerce 5.4.1 and wcadmin 2.4.0.
1. Go to OBW, complete the steps with installing WooCommerce Payments in Business Step (somehow having WCPay is important since otherwise there will be some notes displayed still)
1. Go to WooCommerce > Home
2. Observe empty inbox notes
3. Optionally, disable WCAdmin and observe that notes are displayed as they should

**Screenshots**
![image](https://user-images.githubusercontent.com/3747241/123754021-0359d600-d8ed-11eb-9f43-7b2b7f25136f.png)

**Comment by louwie17** [comment]
If it relies on WCPay it will probably be related to this change: https://github.com/Automattic/woocommerce-payments/pull/2053/files#diff-57ee486c4a3ba4bae478eb31255c9a968b5b4eccd04b27f512e4003440d6f821R562-R610

So it is technically a WC Pay bug

**Comment by louwie17** [comment]
Depending on time constraints reverting this PR commit out of the 2.4 release works as well, as it doesn't affect anything else, and WC Pay works without it.

**Comment by ilyasfoo** [comment]
Thanks for looking into this @louwie17! Since WCPay has already shipped 2.6 with the bug, I think it's best to revert the PR commit just for the wcadmin 2.4 release which hopefully will reduce the window for breakage when users update both plugins.

**Comment by ilyasfoo** [comment]
Closing, context [here](https://github.com/woocommerce/woocommerce-admin/pull/7275#issuecomment-871939161)
