### ISSUE TITLE
[GlobalStep] "Recommended Ways to Get Paid" header font size appears to be smaller upon updating WordPress to 5.8.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#7277]
## Bug Description:
"Recommended Ways to Get Paid" header font size appears to be smaller upon updating WordPress to 5.8.

## Environment:
Woocommerce Version : WooCommerce 5.5 RC 1 and 5.4.1
WordPress version: (v5.8 Beta 3)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate wordpress beta tester to switch v5.8 Beta 3.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Go to Woocommerce->Settings->>Payments.
1. Wait for few seconds until recommendations gets load.
1. Observe that "Recommended Ways to Get Paid" header font size appears to be smaller.

## Note:
Same scenario observed on "Coupons" screen as well.

## Actual Result:
"Recommended Ways to Get Paid" header font size appears to be smaller upon updating WordPress to 5.8.

## Expected Result:
"Recommended Ways to Get Paid" header font size should be consistent.

## Screenshot:

![#7277_1](https://user-images.githubusercontent.com/41110392/123986539-05529080-d9e4-11eb-9c66-fdb1b4e750b0.png)
![#7277_2](https://user-images.githubusercontent.com/41110392/123986555-08e61780-d9e4-11eb-98e6-6517e24c0757.png)

![#7277_3](https://user-images.githubusercontent.com/41110392/123987446-d0930900-d9e4-11eb-89f0-c7f80ba59b7a.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment]
Thanks for reporting this, we already have a fix https://github.com/woocommerce/woocommerce-admin/pull/7255 included in 2.4.0.
