### ISSUE TITLE
[GlobalStep] CSV downloaded from Analytics->Stocks screen has "Stock" status as single word.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#7283]
## Bug Description:
CSV downloaded from Analytics->Stocks screen has "Stock" status as single word e.g "out of stock" displayed as "outofstock" for all status for Stocks CSV.

## Environment:
Woocommerce Version : WooCommerce 5.5 RC 1 and 5.4.1
WordPress version: (v5.8 Beta 3)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Add Some Products.
1. Note that user has enabled stock for products.
1. Place orders from front end.
1. Go to Analytics->>Stocks.
1. Click on download CSV button and open the CSV.
1. Observe that "Status" of product is displayed as single word.

## Actual Result:
CSV downloaded from Analytics->Stocks screen has "Stock" status as single word .

## Expected Result:
Stock status should be appear properly in CSV.

## Screenshot:

![#7283_Products_CSV_Refrence](https://user-images.githubusercontent.com/41110392/124146168-229e6200-daab-11eb-86dd-eb8497e32eae.png)

![#7283_Stock_CSV](https://user-images.githubusercontent.com/41110392/124146187-27631600-daab-11eb-8bea-1a2ce3955dd7.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment]
@gglobalstep Thank you for taking the time to report this issue. I was able to reproduce it. We'll work on it shortly.
