### ISSUE TITLE
WCPay international expansion - add new countries (Aug 4)

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7295]
**Description:** on August 4th we need to start presenting WCPayments to additional European countries in the business features step and the payments task

**Acceptance criteria:**

- [ ] Present WooCommerce Payments to additional European countries (AT, BE, NL, PL, PT, and CH) in the Business features step using the remote endpoint
- [ ] Present WooCommerce Payments to additional European countries (AT, BE, NL, PL, PT, and CH) in the Payments task using the remote endpoint

**Comment by pmcpinto** [comment]
@becdetat just a reminder that we need to ship this next week. Who do you think should take care of this? Thanks

**Comment by becdetat** [comment]
Thanks for raising this @pmcpinto , I had noted it for this cycle but it didn't get assigned to a team. I'll raise it on Slack to get eyes on it.

cc @adrianduffell @mattsherman @samueljseay

**Comment by pmcpinto** [comment]
@ilyasfoo is this going to be released today?

**Comment by ilyasfoo** [comment]
@pmcpinto Yes, I've also responded in the [PR](https://github.com/woocommerce/woocommerce-admin/pull/7436)
