### ISSUE TITLE
WCPay international expansion - add new countries (Aug 25)

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7296]
**Description:** on August 25 we need to start presenting WCPayments to additional countries in the business features step and the payments task

**Acceptance criteria:**

- [ ] Present WooCommerce Payments to additional countries (HK, SG, MY) in the Business features step using the remote endpoint
- [ ] Present WooCommerce Payments to additional European countries (HK, SG, MY) in the Payments task using the remote endpoint

**Comment by ilyasfoo** [comment]
@pmcpinto Has this been done since you mentioned it for August?

**Comment by pmcpinto** [comment]
Yes. I'll close the issue
