### ISSUE TITLE
Add new events to the Analytics module

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7301]
**Description:** we want to take advantage of the existing Event Analytics module (p90Yrv-RL-p2) to improve our understanding of the shopper behavior at checkout and help merchants to improve their checkout conv. rate. We need to create a new event and update the woocommerceanalytics_product_purchase event to include more event props. 
Ventures made some updates in this tracking last year: pb0Spc-ou-p2

**Acceptance criteria:**

- [ ] we need to add a new event to track the checkout view and all the payment options available:

`woocommerceanalytics_product_checkout_view`
`payment_options`: an array with the options available. Eg [paypal, stripe, cod, amazon]
`express_checkou`t: an array with the options available. Eg [apple_pay] or [null] if they don’t display them
`guest_checkout`: Yes/No. Identify if the store allows users to checkout without an account
`create_account`: Yes/No Identify if the store allows users to create an account on checkout
`device`: mobile/desktop

- [ ] We can use the `woocommerceanalytics_product_purchase` event to track more information when the user finishes the purchase. We need to add the following event props:
`payment_option`: the option that was used. Eg Stripe or COD
`express_checkout`: if the express checkout option was used: Eg: Apple Pay or Null
`guest_checkout`: if the guest checkout was used
`create_account`: check if the shopper created an account (Y/N)
`device`: mobile/desktop

**Comment by pmcpinto** [comment]
@elizaan36 let me know if you think if there's something missing that we should also include.

**Comment by elizaan36** [comment]
looks perfect!

**Comment by samueljseay** [comment]
estimated as a 3

**Comment by moon0326** [comment]
@pmcpinto It looks like we already have `woocommerceanalytics_product_checkout` event on the checkout page. Could we use it instead of creating `woocommerceanalytics_product_checkout_view` ?

![Screen Shot 2021-07-23 at 7 15 41 PM](https://user-images.githubusercontent.com/4723145/126854735-570d8cd8-2475-4ddb-8f9e-5ef61a39722c.jpg)

**Comment by moon0326** [comment]
Hey @pmcpinto the event gets fired even when the user access/refresh the checkout page.


https://user-images.githubusercontent.com/4723145/127060256-f845082c-52ed-457b-9fbd-dfdbad3b101c.mp4

**Comment by pmcpinto** [comment]
Thanks for the clarification. The event description and notes made me think that it was only fired when the shopper was moving from the cart to the checkout:

> This event measures how many times product proceeds from cart to checkout.. It fires when User proceeds to checkout.
> One of these events is generated for each item in cart.

If `woocommerceanalytics_product_checkout` is fired on any checkout page view, then it makes sense to reuse it instead of creating a new one.

**Comment by moon0326** [comment]
Hey @pmcpinto after looking into the issue, I realized that it's going to be very hard to include `express_checkout` property for `woocommerceanalytics_product_checkout_view` event. The reason is that Apple or Google pay buttons are rendered in frontend via Stripe. WooCommerce Analytics doesn't have any information about them in the backend. We can inject JS, but it's going to be very hacky as we need to initialize Stripe in WooCommerce Analytics when WooCommerce Payments already initialized Stripe.

I think it's best to add a new method in WooCommerce Payments and use the method in WooCommerce Analytics. 

I can make an issue in WooCommerce Payments and work on it.

We can add `express_checkout` to `woocommerceanalytics_product_purchase` without a problem though.

What do you think?

**Comment by pmcpinto** [comment]
@moon0326 thanks for the feedback. This looks like the best path forward:

> I think it's best to add a new method in WooCommerce Payments and use the method in WooCommerce Analytics.

**Comment by moon0326** [comment]
> @moon0326 thanks for the feedback. This looks like the best path forward:
> 
> > I think it's best to add a new method in WooCommerce Payments and use the method in WooCommerce Analytics.

Sounds good. I've created https://github.com/Automattic/woocommerce-payments/issues/2608 to get started.

**Comment by moon0326** [comment]
@pmcpinto A minor nitpick, but could we make `express_checkout` property type to string instead of an array for `woocommerceanalytics_product_checkout_view` event? The value is one of Apple Pay, Google Pay, and null. It's always a single value.

**Comment by pmcpinto** [comment]
> @pmcpinto A minor nitpick, but could we make express_checkout property type as a string instead of an array for the woocommerceanalytics_product_checkout_view event? The value is one of Apple Pay, Google Pay, and null. It's always a single value.

Sure! That works for me

**Comment by pmcpinto** [comment]
@moon0326 I spoke with Rua today and he suggested that it would be helpful to double-check with Woo Data if they're ok with this approach. So let's wait until the upcoming JP release to ship everything. Do you agree?
If yes, can you share here a summary of the technical implementation? I'd like to share a post explaining this tomorrow or Wednesday and it would be great to include this summary. Thanks!

**Comment by pmcpinto** [comment]
Hey @moon0326 I don't know if you saw the comment I posted yesterday :)

**Comment by pmcpinto** [comment]
@moon0326 @haszari I chatted with @thenbrent this morning, and the sooner we start getting this data, the better. So let's move forward with this implementation and fine-tune it later if necessary. Moon, can you confirm that all the new props outlined in the description will be shipped? Thanks!
