### ISSUE TITLE
Audit tracks events with payment gateway suggestions feature and fix any issues

### ISSUE THREAD

**Issue by joelclimbsthings** [woocommerce/woocommerce-admin#7303]
### Description
Not all tracks events are being fire correctly for the payment gateway suggestions. This is a record of the primary events as @pmcpinto has laid out [elsewhere](https://github.com/woocommerce/woocommerce-admin/issues/6856#issuecomment-874606893):

- View the task: `wcadmin_task_view` (check the additional props such as task_name)
Is it possible to add a new prop showing all the payment methods options the user is seeing when they visit the payments task? Similar to what we had in `wcadmin_tasklist_payment_setup`
- Click to enable a method: `wcadmin_tasklist_payment_install_method` (check the additional props such as plugins)
This is not working with BACS and COD but it should be fixed
- View the payments steps after install: `wcadmin_payments_task_stepper_view` (check the additional props)
- Click to connect to a payment method (2nd step of Stripe and PayPal): `wcadmin_tasklist_payment_connect_start` check the additional props)
- Finish the last step of setting up a payment method: `wcadmin_tasklist_payment_connect_method` (check the additional props)

### To Reproduce

1. `localStorage.setItem( 'debug', 'wc-admin:*' );`
2. Walk through gateway suggestions flows.

**Comment by mattsherman** [comment]
@joelclimbsthings @pmcpinto Why were the Tracks events not being fired correctly? Were the Tracks events not clearly specified initially? Or, were they not tested/verified initially? Or, something else?

**Comment by joelclimbsthings** [comment]
Good question @mattsherman . These particular fixes were largely due to uncertainty and a typo (or two) while migrating the events to the new payment task feature. It's possible that some issues preexisted this change, as I'm not aware of any one "source of truth" on how these events are supposed to fire, or any regular audit/testing we do to ensure they're working as expected.

**Comment by pmcpinto** [comment]
I think most issues preexisted the changes implemented by Joel and Joshua. The root cause was a mix of lack of testing during the implementation and miscommunication between product (me) and engineering when we changed the payments task UI last year. We've tried to reuse the event tracking from the previous UI.

**Comment by mattsherman** [comment]
@joelclimbsthings @pmcpinto Thanks for the explanation. The validation that Tracks events are correct is something that we should definitely pay more attention to in the future, as it is really painful when we find out after the fact that we don't have the tracking we wanted! 😄

**Comment by pmcpinto** [comment]
I fully agree. I'm always a bit paranoid with event tracking as if something goes wrong, we need to wait a couple of weeks to fix it in the next release 😅 In this case, there was some oversight on my side while we were tweaking the UI and reusing the same event tracking.
