### ISSUE TITLE
Refunds chart shows the delta percentage as red when refunds are decreasing

### ISSUE THREAD

**Issue by raicem** [woocommerce/woocommerce-admin#7306]
### Describe the bug
This is mostly a UI concern. When the refund amounts are going down, this is reported as something bad and it is reported with the red-colored badge on the [`SummaryNumber` delta](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/summary/number.js#L162). To reduce confusion, I believe it should be green.  

### To Reproduce
1. Create an order, let's call it Order A, and refund 5 USD.
2. Create a second order, we'll call it Order B. Refund something larger than 5 USD.
3. To see the comparison on the revenue reporting page (`/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue&chart=refunds&orderby=refunds&order=desc&period=today&compare=previous_period`), we need to change the date of the order B as if it's done yesterday. I have done this on the database manually by updating the records on the `wp-posts` and on `wp_wc_order_stats` tables.
4. Go to the revenue reporting page and switch the date range to "today" and compare it to the "previous period".

### Actual behavior:
You'll now see the refunds are decreasing but it's shown with a red badge,.

### Screenshots
![image](https://user-images.githubusercontent.com/10389957/124753484-b780df80-df31-11eb-8113-63dda03f33a3.png)

### Expected behavior
When refunds are decreasing, it should be shown with a green badge, instead of a red one.

### Desktop (please complete the following information):

* OS: Ubuntu
* Browser: Firefox
* Version: 89.0.2

**Comment by joelclimbsthings** [comment]
Thanks @raicem ! This definitely makes sense to me. I'd like to run this by design for confirmation. 

cc @elizaan36

**Comment by elizaan36** [comment]
Thanks @raicem, makes perfect sense to me too. Decreasing returns should be green, while increasing returns would show as red.
