### ISSUE TITLE
Store conversion rate spike

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7309]
**Description:** A significant % of merchants are entirely unaware of their store conversion rate. Contrary to some of our competitors, we don't provide any reports out of the box about their store conversion rate, store traffic, etc. They always need to install a 3rd-party tool to access this information. We want to start exploring the possibility of providing the store conversion rate trends out of the box with WooCommerce. This spike should be focused on two different areas:
- Do we have the right infrastructure in place? If not, what's the effort required to build it or fine-tune the existing infrastructure to fit our needs?
- What's the effort required to build an mvp of a new report or widget showing the store conversion rate?

**Infrastructure:**
- We can take advantage of the Jetpack Woo Analytics module (p90Yrv-RL-p2), which tracks front-end events from the product page to the checkout. Last year there were some discussions around moving this module to WooCommerce Core (see this p2: pb0Spc-ou-p2). On the technical side, what are the pros/cons of each approach? What would be the effort required to move it to WC Core?
- The conversion rate is usually defined as the percentage of sessions that resulted in a purchase. It seems that Jetpack doesn't use the session's concept, only views and visitors (at least I wasn't able to find information about sessions). But it seems that the Data team recently introduce the session concept on Tracks (see the Tracks sessions page in the Field Guide). Can we follow the industry standard and use sessions to calculate the conversion rate or do we need to find a workaround? For example, using visitors
- Alternatively, we can show just the checkout conversion rate (checkout view/product purchase). I'm assuming that we can easily get this using the JP Woo module once we implement the event tracking outlined in #7301 but it would be good to validate this on the technical side. Ideally, we should be able to show both: store and checkout conversion rate. 
- Showing the conversion rate can be more effective if can compare it with a benchmark. Eg: your store conversion rate during the last week was 2.3%. 20% below the average conversion rate among WooCommerce stores operating in the Fashion industry.  What's the effort required to show the store/checkout conversion rate of a specific store alongside a benchmark with the average conversion rate of all Woo stores operating in the same industry? 

**MVP:**
- Get a high-level estimate of the effort required to show the store or checkout conversion rate in the Stats overview card of the home screen. And allow merchants to use the predefined date ranges: today, week to date and month to date
- Get a high-level estimate of the effort required to build a store or cart checkout report. As a starting point, the report would show the daily store or checkout conversion rate and allow merchants to use the date range picker to compare different dates. Just a super rough mockup of how the report could look like: https://d.pr/i/91brbT

**Comment by elizaan36** [comment]
Here's a design for creating a new summary number component. In this case there needs to be some context so I've added a tooltip that explains the new metric. I think the tooltip is helpful, but my only hesitation is that we haven't introduced the term session yet.

![Screen Recording 2021-07-15 at 09 24 36 AM](https://user-images.githubusercontent.com/5121465/125823326-40ff910b-2013-4cb4-97b3-46f3d45b1d7b.gif)

<img width="261" alt="Screen Shot 2021-07-15 at 9 30 49 AM" src="https://user-images.githubusercontent.com/5121465/125824112-26ec1172-26dc-4391-9af1-79188828109f.png">

<img width="337" alt="Screen Shot 2021-07-15 at 9 31 09 AM" src="https://user-images.githubusercontent.com/5121465/125824156-c2a67cbb-a2c2-4333-afa4-cd3dc4f50827.png">

The summary number only appears for Jetpack connected stores and stores that have opted into data tracking. For these stores, they would also have the option to toggle the conversion rate data on and off from the stats overview card dropdown.

![Frame 2652](https://user-images.githubusercontent.com/5121465/125824196-ddd98885-7941-4c5a-8c2f-85452e7a954d.png)

Will share the Figma in Slack.

**Comment by samueljseay** [comment]
This is my attempt to summarise the work to do for the spike into a task list.

- [ ] Explore the effort and legitimacy of merging woocommerce-analytics into wc core. See [this comment](pb0Spc-ou-p2#comment-599). 
- [ ] Explore effort/technical approach required to supply a benchmark number for store conversion rate by industry. 
- [ ] Estimate effort to build a report page for store conversion

At a high level I see some technical challenges that I'm not well acquainted with solving right now so we'd need to dig in. 

1. Merging woocommerce-analytics into core, this one is pretty well known
2. I don't know much about the way we store analytics data, how will we aggregate or query data to provide a "benchmark per industry"?
3. Once we have a benchmark per industry number, does this API need to live on wc.com?

Things like the report page and home screen summary number are much more well known I think. Reports is fairly reusable to create some more report screens so its really just a question of where this data comes from and how we query it.

> Can we follow the industry standard and use sessions to calculate the conversion rate or do we need to find a workaround? For example, using visitors

I'd like the rest of @woocommerce/ghidorah team to weigh in on this but it feels to me like we would get the most value from just using the woocommerce-analytics approach to begin with if visitors was an acceptable workaround. Maybe doing session tracking could be a follow up from this work.

**Comment by moon0326** [comment]
> * [ ]  Explore the effort and legitimacy of merging woocommerce-analytics into wc core. See [this comment](pb0Spc-ou-p2#comment-599).

The link is somehow linked to this issue page. The correct link is [this](https://wp.me/pb0Spc-ou-p2#comment-599).

**Comment by samueljseay** [comment]
@moon0326 thanks, its the tampermonkey script that I have that strips the host out so you have to form the url yourself.

**Comment by samueljseay** [comment]
From @adrianduffell : We could perhaps include woocommerce-analytics through composer instead of merging it core.

**Comment by samueljseay** [comment]
@pmcpinto one question that came up for us is around the legal implications of collecting user data. 

We assumed that Jetpack has handled this concern somehow, but if we include their analytics library in core (or bundle it in wc-admin) then users won't have to have Jetpack installed. Will we need to consider the legal implications for customers somehow as part of that?

**Comment by pmcpinto** [comment]
Good question. If we move this to Core we'd need to update our usage tracking documentation and probably ask users to opt-in again. 

But we can clarify all the details on the legal side after the make a decision of moving forward or not with this.

**Comment by ilyasfoo** [comment]
>From @adrianduffell : We could perhaps include woocommerce-analytics through composer instead of merging it core.

Unfortunately this is off the table, [woocommerce-analytics](https://github.com/Automattic/jetpack/tree/master/projects/plugins/jetpack/modules/woocommerce-analytics) is not a composer package.

**Comment by adrianduffell** [comment]
> > From @adrianduffell : We could perhaps include woocommerce-analytics through composer instead of merging it core.
> 
> Unfortunately this is off the table, [woocommerce-analytics](https://github.com/Automattic/jetpack/tree/master/projects/plugins/jetpack/modules/woocommerce-analytics) is not a composer package.

Never mind, thanks for investigating this avenue @ilyasfoo 🥀 👍

> They always need to install a 3rd-party tool to access this information. We want to start exploring the possibility of providing the store conversion rate trends out of the box with WooCommerce.

@pmcpinto Do we consider Jetpack a first party analytics tool? i.e. could we require Jetpack to be installed before reporting on the store conversion rate? When it's not installed, perhaps there could be placeholder prompting the store to install the Jetpack plugin.

I think I assumed we considered Jetpack to be 3rd party originally. On second read, to lower complexity I think we would want to make the supporting changes in the Jetpack module directly (like sessions), while updating WC Admin to consume and report on the data.

**Comment by pmcpinto** [comment]
> @pmcpinto Do we consider Jetpack a first party analytics tool? i.e. could we require Jetpack to be installed before reporting on the store conversion rate? When it's not installed, perhaps there could be placeholder prompting the store to install the Jetpack plugin.

Yes. We're already doing something similar in the Stats overview to display visitors and views: https://d.pr/i/WqaeEv
Moving the analytics module to Core would allow us to remove one dependency and remove friction from the flow as well. But it depends on the effort required to do it.

**Comment by ilyasfoo** [comment]
**Current status**

I've posted a question on WooData team here: p7Ldg5-1bI-p2. I'm still doing some more research and write-up for the spike.

**Comment by ilyasfoo** [comment]
Spike posted here: p90Yrv-2pu-p2
