### ISSUE TITLE
Update action notes documentation for the `is_primary` field (not being used atm)

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#7310]
We currently have a `is_primary` field in our wc_admin_note_actions table, the original intent of this was to make the action button a primary type, and secondary otherwise -> https://github.com/woocommerce/woocommerce-admin/blob/c93b9b821f7ca7113691657d132b0aec9df299a4/client/header/activity-panel/panels/inbox/action.js#L73-L74

This has changed over a year ago, and we don't use the `is_primary` field anymore within wc-admin ->
https://github.com/woocommerce/woocommerce-admin/pull/4692

This issue is to update the docs if we decide to keep the `is_primary` field and make it explicit that it's original intent was for the button styling.
OR
Depreciate the `is_primary` field and remove it from the `wp_wc_admin_note_actions` table.

**Comment by joshuatf** [comment]
I think we should go ahead and remove this.  It's not being used anywhere and removing should be relatively simple.
