### ISSUE TITLE
Show WooCommerce Payments Promotion in Payment Methods table before it is installed

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7319]
### User story

As a merchant setting up my payment methods, I'd like to see WooCommerce Payments listed directly in the payments table prior to it being installed, so that I can easily see that it is an option for me to use.

### Notes

This is a follow up to the payments recommendation card implemented in 5.4 (#6684). See early results in paJDYF-1eJ-p2#comment-6801.

We will experiment moving WooCommerce Payments from the recommendations card to the payments table (see design below), to see if that improves the WooCommerce Payments installation rate. The other payment methods currently in the recommendations card will remain (Stripe Payments and PayPal Payments).

See paqDfi-2af-p2 for details on using ExPlat to create an A/B experiment.

**_Note: Ghidorah will be making improvements to the tooling around ExPlat to help verify A/B tests work correctly. We can begin development of this experiment prior to that, but will want to wait to launch the experiment until this improved tooling is in place so that we ensure that our experiment functions as expected._**

### Current design

![Screen Shot 2021-08-11 at 10.40.38.png](https://images.zenhubusercontent.com/5e78cac2867c853084b981b0/12c66f87-397d-4d48-b360-fd7cc39517af)

### New design

![image (6).png](https://images.zenhubusercontent.com/5e78cac2867c853084b981b0/9dfb1fe5-1a3b-45f6-9615-1fda3f5147fa)

### Acceptance criteria

- [ ] Implement this change as an ExPlat experiment to validate that this change is having the expected impact
    - Control: current experience, with WooCommerce Payments in the Recommended Payments card
    - Treatment: WooCommerce Payments in the Payment Methods table
- [ ] Use the remote marketplace suggestions so we can tweak the copy and expand countries where this is shown without waiting for a release (as is done for the Recommended Payments card currently)
- [ ] Display WooCommerce Payments in the Payment Methods table only in countries where WooCommerce Payments is available
- [ ] Hide the "Enable" toggle when WooCommerce Payments is not installed
- [ ] Remove WCPay from the Recommended payments card that appears below the Payment Methods table
- [ ] When the user clicks in the "WooCommerce Payments" link before the install we should open a new tab with the following link: `https://woocommerce.com/payments/`
- [ ] When the user clicks on "terms of service" link, we should open a new tab with the following link: `https://wordpress.com/tos/`
- [ ] When the user clicks on "privacy policy" link, we should open a new table with the following link:`https://automattic.com/privacy/`
- [ ] Automatically install WooCommerce Payments if the user clicks "Install"
- [ ] While WooCommerce Payments is installing, the "Install" button should be in a loading state, similar to the current implementation in the recommendation card
- [ ] After installing WooCommerce Payments, It should follow the same flow as installing WCPay from the recommended payments card currently, which launches into the setup flow (either WP connection or KYC)

#### ExPlat prep
- [ ] Document the ExPlat experiment and have it reviewed
- [ ] Create an experiment in Abacus and have it reviewed

#### WooCommerce Admin

- [ ] Register a pseudo payment gateway for WooCommerce Payments if the real WooCommerce Payments isn't registered 
    - How can we guarantee that we check this after WooCommerce Payments has a chance to register?
- [ ] Set all options to disabled in the pseudo gateway so it doesn't show up elsewhere in the system
- [ ] Add/modify automated tests to help us verify that the pseudo gateway doesn't appear anywhere it isn't supposed to
- [ ] Hide this gateway's row via CSS using the data attribute `<tr data-gateway_id="woocommerce_payments_install" class="">`
- [ ] Mount react to this row, replacing the button's content with our "Install" option, and unhiding the row.
- [ ] Implement links for TOS and privacy policy
- [ ] Implement "Install" button action
    - Option 1: hard refresh after install to get WooCommerce Payments gateway to show up, or
    - Option 2: change DIV to set button to "Manage" and handle link to WC Payments manage UI
- [ ] Remove WooCommerce Payments from Recommended Payments card

#### ExPlat launch (can't launch until it is included in WCA 2.7/WooCommerce 5.8: October 12)

- [ ] Launch experiment

**Comment by mattsherman** [comment]
@pmcpinto Can you please check the acceptance criteria and make any necessary changes?

Also, what should happen after the extension is installed when the "Install" button is clicked?

@elizaan36 What are the icons on the WooCommerce Payments row? Are they static or do they vary based on any parameters (country, settings, etc.)?

**Comment by pmcpinto** [comment]
Thanks for completing the AC. I just added one item at the end of the AC and I think the only missing piece is clarifying this behavior: 

> what should happen after the extension is installed when the "Install" button is clicked?

I think that after install we should redirect users to the WCPayments welcome screen. It's the default behavior when you install WCPayments and click "Set up" on the Settings page. @elizaan36 what do you think?

> @elizaan36 What are the icons on the WooCommerce Payments row? Are they static or do they vary based on any parameters (country, settings, etc.)?

My vote goes to keep it simple and show the icons that we currently show when the extension is installed: https://d.pr/i/XsyfsM

**Comment by mattsherman** [comment]
> I think that after install we should redirect users to the WCPayments welcome screen. It's the default behavior when you install WCPayments and click "Set up" on the Settings page. @elizaan36 what do you think?

That sounds reasonable.

> My vote goes to keep it simple and show the icons that we currently show when the extension is installed: https://d.pr/i/XsyfsM

Makes sense.

**Comment by elizaan36** [comment]
> I think that after install we should redirect users to the WCPayments welcome screen. It's the default behavior when you install WCPayments and click "Set up" on the Settings page. @elizaan36 what do you think?

I can't think of any reason to change the flow for this update, unless I'm missing something @pmcpinto? It should follow the same flow as installing WCPay from the recommended payments card currently, which launches into the setup flow (either WP connection or KYC). Not sure why we'd make that change to redirect them to the welcome screen for this.

Sounds good about those icons! Here's the updated design with added legal copy.
![Frame 2651](https://user-images.githubusercontent.com/5121465/125694947-1c57e728-0cee-432a-a1d7-1dba538948de.png)

Also want to confirm that there will be the loading state on the Install button, similar to the current implementation. It sometimes takes a minute so would be good for users to have that feedback.

**Comment by elizaan36** [comment]
I'd add one more acceptance criteria to this as well - to remove WCPay from the Recommended payments card that appears below the table.

**Comment by mattsherman** [comment]
> I can't think of any reason to change the flow for this update, unless I'm missing something @pmcpinto? It should follow the same flow as installing WCPay from the recommended payments card currently

That makes sense to me.

> I'd add one more acceptance criteria to this as well - to remove WCPay from the Recommended payments card that appears below the table.

Definitely -- nice catch!

> Here's the updated design with added legal copy.

Thanks!

> Also want to confirm that there will be the loading state on the Install button, similar to the current implementation. It sometimes takes a minute so would be good for users to have that feedback.

I will explicitly call that out in the acceptance criteria and dev tasks, so that we don't forget about it.

**Comment by mattsherman** [comment]
@oneillo This feature will require an ExPlat experiment. How should we proceed with this? Do you usually write the experiment post up and have it reviewed, or is that something we (the delivery team) should do?

**Comment by oneillo** [comment]
Hey @mattsherman - I'm happy to write up the experiment and post it for review, so long as you don't mind it coming toward the end of next week. If you need it sooner, I can help whoever decides to write it up.

**Comment by mattsherman** [comment]
> Hey @mattsherman - I'm happy to write up the experiment and post it for review, so long as you don't mind it coming toward the end of next week. If you need it sooner, I can help whoever decides to write it up.

Thanks @oneillo. This involves changes to WooCommerce Admin *and* WooCommerce Core, so the experiment won't be able to be launched until the WooCommerce 5.7 release. I not sure when the date for that is, but I think we'd be looking at September. (/cc @pmcpinto)

/cc @louwie17 You added the recommended payment methods card, so please chime in if I am off-base in thinking that this will require both WooCommerce Admin *and* WooCommerce Core changes.

**Comment by louwie17** [comment]
> /cc @louwie17 You added the recommended payment methods card, so please chime in if I am off-base in thinking that this will require both WooCommerce Admin _and_ WooCommerce Core changes.

When mentioning `WooCommerce Core` are you referring to `woocommerce.com`? It should only involve `woocommerce.com` and WooCommerce Admin changes, counting on the fact that we can use a filter to add new items to the payment method table (otherwise we have to add that part in Woo Core).
I am not a 100% sure on this latter part, that will require some research (I assume it won't be too to difficult).

**Comment by mattsherman** [comment]
> When mentioning WooCommerce Core are you referring to woocommerce.com?

Nope, I was referring to `woocommerce/woocommerce` core.

> It should only involve woocommerce.com and WooCommerce Admin changes, counting on the fact that we can use a filter to add new items to the payment method table (otherwise we have to add that part in Woo Core).

Ah, filters... I always forget about them! 😄

Let's see...

There is a filter for the available payment gateways, `woocommerce_available_payment_gateways` ([src](https://github.com/woocommerce/woocommerce/blob/94bdcd0320fb374971003a201893df8b5060bc5e/includes/class-wc-payment-gateways.php#L160)).

That might let us put WooCommerce Payments in there before it is installed, but I don't know if there would be unintended consequences elsewhere in the system (I'm guessing, most definitely).

That filter ends up being used by the code that outputs the payment methods table ([src](https://github.com/woocommerce/woocommerce/blob/94bdcd0320fb374971003a201893df8b5060bc5e/includes/admin/settings/class-wc-settings-payment-gateways.php#L136)), but that code constructs each row based on the gateway properties, and doesn't have any concept of an "Install" action, so I'm thinking that we would have to modify Core to add support for the whole concept of listing a gateway that isn't already installed.

**Comment by pmcpinto** [comment]
> I can't think of any reason to change the flow for this update, unless I'm missing something @pmcpinto? It should follow the same flow as installing WCPay from the recommended payments card currently, which launches into the setup flow (either WP connection or KYC). Not sure why we'd make that change to redirect them to the welcome screen for this.

Currently, if you have WCPay installed and click "Set up" on the Settings page it will redirect you to the welcome screen. But I agree that it will be more effective to skip this and redirect the user to the KYC flow.

**Comment by mattsherman** [comment]
> Currently, if you have WCPay installed and click "Set up" on the Settings page it will redirect you to the welcome screen. But I agree that it will be more effective to skip this and redirect the user to the KYC flow.

@pmcpinto Are we changing the behavior when you click "Set up"? Or, are you just referring to what should happen when "Install" is clicked?

**Comment by louwie17** [comment]
> That might let us put WooCommerce Payments in there before it is installed, but I don't know if there would be unintended consequences elsewhere in the system. I'm guessing, most definitely, as the gateway we'd be adding isn't really there yet.
> 
> That filter ends up being used by the code that outputs the payment methods table ([src](https://github.com/woocommerce/woocommerce/blob/94bdcd0320fb374971003a201893df8b5060bc5e/includes/admin/settings/class-wc-settings-payment-gateways.php#L136)), 

Thanks for doing some digging, it does appear the `payment_gateways()` function [uses the local `payment_gateways`](https://github.com/woocommerce/woocommerce/blob/94bdcd0320fb374971003a201893df8b5060bc5e/includes/class-wc-payment-gateways.php#L120-L130),[ that is set on `init`](https://github.com/woocommerce/woocommerce/blob/94bdcd0320fb374971003a201893df8b5060bc5e/includes/class-wc-payment-gateways.php#L102-L108).
So I don't think we could use the `woocommerce_available_payment_gateways` filter.

> but that code constructs each row based on the gateway properties, and doesn't have any concept of an "Install" action, so I'm thinking that we would have to modify Core to add support for the whole concept of listing a gateway that isn't already installed.

I think this would be the best route, we would have to expose an extra filter to allow adding uninstalled payment methods to the table, and add the `Install` button support (small fix).

The other method I thought, would be to add a filter that just renders empty placeholder rows within the table, and we fill this with React on the wc-admin side. Similar in how the Recommended payment card works. This way we don't have to add explat support to woo core (if it isn't already available) and add this functionality to the [EmbeddedBodyLayout](https://github.com/woocommerce/woocommerce-admin/blob/main/client/embedded-body-layout/embedded-body-layout.tsx).

This option feels a little bit dirty, but allows for more customizability on the wc-admin end, as we have all of the required functionality already available. Given the component wouldn't rely on any other requests, it should look identical from a user perspective.

**Comment by pmcpinto** [comment]
> @pmcpinto Are we changing the behavior when you click "Set up"? Or, are you just referring to what should happen when "Install" is clicked?

Just when "Install" is clicked.

**Comment by mattsherman** [comment]
@elizaan36  @pmcpinto For WooCommerce Payments, if it isn't installed, do we show the "Enable" toggle? I would think we should just hide it. Or, do we want the toggle to also trigger the auto-install?

**Comment by pmcpinto** [comment]
I think that hiding it is the best option.

**Comment by LevinMedia** [comment]
Let's try to sync the content on this experiment with the designs that are being finalized for when we ship the UPE as part of WCpay in early August. The exact outcome of that design is being wrapped up now - however it will either look something like this: 

<img width="1820" alt="Screen Shot 2021-07-26 at 3 48 25 PM" src="https://user-images.githubusercontent.com/4500952/127068916-ed3da4a7-6521-4edb-ab9c-2bc3c56346a5.png">

I think we'll also need to disclose the TOS and privacy policy in this spot too, so I added it to the screenshot above. 

The other option we're considering for the UPE is not including the count of available payment methods. Discussion at: p1626985047012200-slack-C022N4CHJ65

cc @FangedParakeet @elizaan36 @pmcpinto

**Comment by elizaan36** [comment]
Are UPE payment methods shown dependent on base store location?

**Comment by pmcpinto** [comment]
I don't see a significant benefit in mentioning the number of payment methods: x payment methods. My initial impression is that it can raise more questions (which payment methods are we talking about?) and increase friction.

**Comment by mattsherman** [comment]
> I don't see a significant benefit in mentioning the number of payment methods: x payment methods. My initial impression is that it can raise more questions (which payment methods are we talking about?) and increase friction.

Agreed. I also find it confusing that the table is titled "Payment methods" and there is a single item in the list that says "6 payment methods". It seems like we are double-defining "payment method".

**Comment by oneillo** [comment]
Just an update on the ExPlat experiment post. I haven't had a chance to get to it, but it's still on my ToDo list. I've been pushing it back given the September launch date and other more urgent work, but I'll aim to get it written up next week.

**Comment by pmcpinto** [comment]
> Just an update on the ExPlat experiment post. I haven't had a chance to get to it, but it's still on my ToDo list. I've been pushing it back given the September launch date and other more urgent work, but I'll aim to get it written up next week.

Hey @oneillo the goal is to start having the engineering teams creating the experiment post with our assistance (similar to what we've done with the task list UI experiment). See this post about the topic: p90Yrv-2nZ-p2

**Comment by LevinMedia** [comment]
@pmcpinto @mattsherman thanks for the feedback - @FangedParakeet based on that, let's not include the number of payment methods - just show WooCommerce Payments in the gateway title.

**Comment by FangedParakeet** [comment]
Thanks for the discussion here, gang! The WCPay gateway settings, as hereby decreed, have been implemented in Automattic/woocommerce-payments#2530, as partner to the resolution of Automattic/woocommerce-payments#2433, so you can follow the progress in either of those spots from here on out.

**Comment by mattsherman** [comment]
@elizaan36 Do you have a final mockup/figma for this?

@pmcpinto @becdetat Given the release train, since WCA 2.6 already is in beta, we won't be able to launch this until WCA 2.7, which will be included in WC 5.8, which launches October 12.

**Comment by elizaan36** [comment]
I shared the final Figma mockup in Slack keeping the payment logos and adding the copy to include "popular payment methods" plus the TOS and Privacy policy.

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/5121465/129085776-d134bede-5f87-477e-8881-56f0a01aa9c9.png">

**Comment by mattsherman** [comment]
@louwie17 @joshuatf @octaedro @joelclimbsthings Please think about the two approaches we discussed (the "pseudo gateway" approach and the "DOM manipulation" approach) and comment with your thoughts on which way we should go. If there are additional tasks/details that you can think of for either approach, please update the description!

**Comment by joshuatf** [comment]
@mattsherman Here are my thoughts on the approaches:

### Pseudo gateway
I like the pseudo gateway approach here a lot because it mostly works out of the box with the existing system without interfering with other plugins or using DOM injection.

In a nutshell, we would create a new payment gateway just for the WC Pay installer and register it using the `woocommerce_payment_gateways` hook.  We should be careful to only do this on settings pages to avoid creating conflicts or edge cases with other plugins that make use of registered payment gateways.  From there, the gateway is loaded onto the page just like other items and the ordering will work out of the box, persisting the order of the gateway when the user uses the up/down arrows.

Unfortunately, the "Set up" and "Manage" buttons are hardcoded into WooCommerce core with no filters available, so we'd either have to:

a. Open a PR in core to allow this button to be filtered
b. Override this button via JS (but this means we lose some of the benefits of this method and risk FOUC)

### DOM Injection

With this method, we would render to the page using React and place the WC Pay item into the table.  We get full control of the render, however it's unlikely that `ui-sortable` will work immediately with our newly rendered table row.

We'd need to find a way to:
* Re-init sortable
* Pull (or preload 😞 ) the order of the gateways and inject in the right place

The good news is that the saving of the payment gateways order should work without any changes as there is not validation of the gateways on server-side.

### Hybrid

Both of these come with challenges, but maybe a mix between the two would be the best if we don't implement changes in core.  Rough tasks to accomplish this:

1. Register a pseudo gateway that shows up in the table.
2. Hide this gateway's row via CSS using the data attribute `<tr data-gateway_id="woocommerce_payments_install" class="">`
3. Mount react to this row, replacing the button's content with our "Install" option, and unhiding the row.

In this way, we get the default sort-ability working, avoid FOUC, and still get to use React to handle our button's action without modifying core.

**Comment by mattsherman** [comment]
@joshuatf I like that hybrid approach. I've updated the tasks to reflect this approach.

**Comment by louwie17** [comment]
I would be on-board with the hybrid approach as well, and it doesn't sound overly complicated to implement.

@joshuatf for the hybrid approach I assume we don't want to hide the entire row, as we still want the sort icons to be displayed. Would it be worth to only hide the `status` and `action` columns, and mount the react to the `action` column.

I guess we would also have to hide the `name` column to overwrite the default link ( as this is not very configurable ), unless we add a separate redirect filter for when the user navigates to the gateways settings page.

**Comment by octaedro** [comment]
Thank you @joshuatf  for the great summary!
The hybrid approach looks like the best for us now 👍

**Comment by joelclimbsthings** [comment]
Also in favor of the hybrid approach 👍🏻

**Comment by louwie17** [comment]
@elizaan36 @pmcpinto I have a question in relation to the copy.
Currently the copy displayed in the new design is different from both the recommended card in payment settings and the one displayed in the payment method task. This would require a new configuration (and maybe access point) in the market place suggestions API.
This will require some extra work and makes three different spots where we have wc pay copy, should we instead make use of one of the current pieces of copy? and maybe slightly alter it?
Given this experiment will be replacing WC Pay from the recommended payments card, I would suggest making use of that copy? (it's current copy can be seen here -> https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/marketplace-suggestions/includes/payment-suggestions.json.php#L16).

Having questioned that, I can certainly add new copy if that is also a vital part of the experiment.

**Comment by elizaan36** [comment]
👋 To reiterate what we chatted about in Slack, the copy is essential to the experiment so let's move forward with the new configuration if it's not a huge problem.

**Comment by pmcpinto** [comment]
@louwie17 do you think it will be possible to have this experiment launched right after the WC 5.8 release?

**Comment by louwie17** [comment]
> @louwie17 do you think it will be possible to have this experiment launched right after the WC 5.8 release?

Unfortunately I don't think so, the beta of 2.7 was cut at the beginning of last week already and went through Global step testing. I didn't get things done in time for the 2.7 beta cut. Although they will be done for `2.8` for sure (as the final piece is up for review).
I think we decided not to include any big refactors or features after the beta has been cut.

**Comment by pmcpinto** [comment]
Gotcha. Thanks for the clarification!

**Comment by pmcpinto** [comment]
@louwie17 I'd like to confirm if it's possible to include this in 2.8. Also, can you publish here a quick demo showing the changes? Thanks!

**Comment by louwie17** [comment]
> @louwie17 I'd like to confirm if it's possible to include this in 2.8. Also, can you publish here a quick demo showing the changes? Thanks!

Yes it will be included in `2.8`.
Here is the demo, let me know if you wanted a more detailed demo:

https://user-images.githubusercontent.com/2240960/134722020-04941322-827b-4cff-a832-b1afc6c87841.mp4

**Comment by pmcpinto** [comment]
Thanks, Lourens. It's looking good!

cc @elizaan36 so you can also check the demo.

**Comment by elizaan36** [comment]
Looks perfect to me!
