### ISSUE TITLE
Add marketing extension links to help panel

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7329]
### User story

As a merchant,
I want to be able to obtain help on setting up the marketing extensions,
so that I can successfully set them up.

### Description

Once the respective extensions are installed, the help panel should include links to get started with each of these extensions:

* [Get started with Mailpoet](https://kb.mailpoet.com/category/114-getting-started)
* [Set up Google Listing & Ads](https://docs.woocommerce.com/document/google-listings-and-ads/#get-started)
* [Connect Mailchimp for WooCommerce](https://mailchimp.com/help/connect-or-disconnect-mailchimp-for-woocommerce/)
* [Set up Creative Mail for WooCommerce](https://app.creativemail.com/kb/help/WooCommerce)

### Acceptance criteria

- [ ] The Help panel should include the following links
[Get started with Mailpoet](https://kb.mailpoet.com/category/114-getting-started)
[Set up Google Listing & Ads](https://docs.woocommerce.com/document/google-listings-and-ads/#get-started)
[Connect Mailchimp for WooCommerce](https://mailchimp.com/help/connect-or-disconnect-mailchimp-for-woocommerce/)
[Set up Creative Mail for WooCommerce](https://app.creativemail.com/kb/help/WooCommerce)

### Tasks

- [ ] Add links to the help panel

**Comment by joelclimbsthings** [comment]
So the links displayed in the help panel are contextual, giving differing links depending on the page. Is the intention to only present these links on [the new marketing task page](https://github.com/woocommerce/woocommerce-admin/issues/7313), or elsewhere?

@pmcpinto

**Comment by pmcpinto** [comment]
@joelclimbsthings the intention is to only present them on the new marketing task page. We're already doing this on the other tasks.
