### ISSUE TITLE
Remove init page loading spinner on the orders and products

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#7336]
**Is your suggestion related to a problem? Please describe.**

A spinner appears briefly on the orders and products page and it's causing a page flickering. Since the orders and products pages are not React pages, they don't need to have a page loading spinner in my opinion.

**Describe the solution you'd like**
I think we can safely remove the spinner from the orders and products pages.

**Alternative solution**

We can probably apply some CSS styles to fix the position of the spinner to prevent flickering. 

https://user-images.githubusercontent.com/4723145/125352828-998ef280-e316-11eb-8b4d-a4854a0c8d4e.mov

**Comment by mattsherman** [comment]
@moon0326 I see you assigned to this. Are you actively working on it?

**Comment by moon0326** [comment]
> @moon0326 I see you assigned to this. Are you actively working on it?

I was going to, but I'm currently working on other tickets. Would you like to take it?

**Comment by mattsherman** [comment]
> > @moon0326 I see you assigned to this. Are you actively working on it?
> 
> @mattsherman I was going to, but I'm currently working on other tickets. Would you like to take it?

Not right now.

> I've unassigned it for now.

Thanks! That way, it will be clear to others that it is available to be worked on.
