### ISSUE TITLE
White screen crash after disabling analytics feature

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#7339]
### Describe the bug
Disabling Analytics in WooCommerce > Settings > Advanced > Features causes white screen when loading WooCommerce home.

### To Reproduce
1. Go to WooCommerce > Settings > Advanced > Features.
2. Uncheck "Enables WooCommerce Analytics" and save.
3. Go to WooCommerce home.
4. Observe white screen.

### Screenshot
Console:

![image](https://user-images.githubusercontent.com/3747241/125417446-1cd5101e-1846-4737-9f9f-42554519e350.png)

I suspect the error is caused by `performanceIndicators` is undefined because it's not pre-loaded in `dataEndpoints` settings, but the way fallback data is handled it doesn't check for child object's existence:

![image](https://user-images.githubusercontent.com/3747241/125419129-cd4de201-3806-4239-8435-fff05bfeac88.png)

**Comment by ilyasfoo** [comment]
@octaedro I think this bug is quite a high priority since it causes a crash, and warrants to be cherry-picked to 2.5. What do you think?

**Comment by octaedro** [comment]
Thank you @ilyasfoo for reporting this bug.
I think the same as you. I just added the `high priority` label.
