### ISSUE TITLE
Payments task: include Square in France [FR] (target: WC 5.8)

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7360]
**Description:** In October we need to start including Square in the payments task for French stores (WooCommerce 5.8)

**Acceptance criteria:**

- [ ] Display Square as an option in the payments task if the user selected France (FR) as the country in the Store Details step and if he selected one of the following options in the Business details step - Currently selling elsewhere?
Yes, in person at physical stores and/or events
Yes, on another platform and in person at physical stores and/or events

**Comment by mattsherman** [comment]
Duplicate - closing this in favor of #7631
