### ISSUE TITLE
Create tasks REST API endpoint

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7365]
Tasks should be retrievable via a REST endpoint.  There is already a controller in place for onboarding tasks, so this will issue will involve adding an endpoint.

**Endpoint**
`GET` - `/wc-admin/onboarding/tasks`

**Schema**

Since we have multiple task lists, this endpoint will ideally return the tasks lists as an array with tasks already organized under each list.

```php
array(
    'id'         => <string>,
    'isComplete' => <bool>,
    'isHidden'   => <bool>,
    'title'      => <string>,
    'tasks'      => array(
        array(
            'id'          => <string>,
            'title'       => <string>,
            'content'     => <string>,
            'actionLabel' => <string>,
            'actionUrl'   => <string>,
            'isComplete'  => <bool>,
            'isVisible'   => <bool>,
            'time'        => <string>,
        )
    ),
)
```

https://github.com/woocommerce/woocommerce-admin/pull/7354 contains code for this endpoint, but will need additional tests and schema.

**Comment by louwie17** [comment]
It would be nice if we could also filter by at-least the task list type (id I think in the above example - ex: `core` or `extended`). The task list type might also have `wcpay` for example.

In the future we might want to sort by completed/visible/time state.

@joshuatf I wonder if we should make the top item a key->value instead of an array?
```
array( 'task_list_type_name' => array(
    'id'         => <string>,
    'isComplete' => <bool>,
    'isHidden'   => <bool>,
    'title'      => <string>,
    'tasks'      => array(
        array(
            'id'          => <string>,
            'title'       => <string>,
            'content'     => <string>,
            'actionLabel' => <string>,
            'actionUrl'   => <string>,
            'isComplete'  => <bool>,
            'isVisible'   => <bool>,
            'time'        => <string>,
        )
    ),
),
)
```

**Comment by joshuatf** [comment]
>It would be nice if we could also filter by at-least the task list type (id I think in the above example - ex: core or extended). The task list type might also have wcpay for example.

>In the future we might want to sort by completed/visible/time state.

All good ideas, @louwie17!  I think for this first iteration we should try to keep the scope to just the items we need while keeping the API flexible enough that these can be added in the future.  What do you think?

>I wonder if we should make the top item a key->value instead of an array?

I'm not opposed to this in theory, but if we're returning the associative array, it will be parsed to an object during JSON and we can't guarantee the order of the task lists.  I think since the number of lists is never going to be a very large number, there won't be a large performance impact here.

**Comment by louwie17** [comment]
> All good ideas, @louwie17! I think for this first iteration we should try to keep the scope to just the items we need while keeping the API flexible enough that these can be added in the future. What do you think?

I agree, keeping it simple for now.

> I'm not opposed to this in theory, but if we're returning the associative array, it will be parsed to an object during JSON and we can't guarantee the order of the task lists. I think since the number of lists is never going to be a very large number, there won't be a large performance impact here.

When you are talking about the orders of task lists do you mean the tasks themselves or the overarching task list (that includes tasks). I thought only the order of the tasks within a task list matter, but not the order of the overarching task lists.
Maybe I am reading into this too much.

I was thinking of the above in the same line as #7370 where we use `setup` & `extension` as the associated key, but keep the tasks within as an array.
