### ISSUE TITLE
Create dismiss task endpoint

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7369]
An endpoint should be created that allows tasks to be "dismissed."

Currently these options are stored in `woocommerce_task_list_dismissed_tasks`.  If we want to retain backwards compatibility, the data can remain in this option without affecting existing stores.

We will want to filter the task list created in https://github.com/woocommerce/woocommerce-admin/issues/7365 to include `isDismissed` in each of the tasks.

**Endpoint**

`POST` - `/wc-admin/onboarding/tasks/<task_id>/dismiss`

**Params**

None

**Response**

This endpoint can simply return a response message if successful or contain errors if there was a problem dismissing the task.

**Comment by louwie17** [comment]
Should we add the tracks event for this on the API as well? or keep that on that client?
If we do it on the API, it will be automatically recorded for any external plugins as well that use this.

**Comment by joshuatf** [comment]
Yes, for this one as well.
