### ISSUE TITLE
Invalidate task data store cache on task related actions

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7371]
When a task is updated or completed, we may want to refetch the tasks to verify completion or get updates to the tasks.

`invalidateResolution( 'getTasks' )`

Ideally we can hook into various data stores (such as profile items, plugins, payment gateways, etc) to invalidate the cache when updates occur.  However, I'm not sure that cross store detection is available in wp data so a simpler more general solution may be needed to invalidate the resolver.

Some thought should also be given here to extensibility and how resolver invalidation might work with a custom task added outside of WooCommerce Admin.

**Comment by louwie17** [comment]
I think we should try to use `invalidateResolution` sparingly, and instead make use of the update requests return values and use those to update the redux store.
For #7368 and #7369 for example, we could return the entire task object (that we updated) and update the store with that. This way things stay up to date and we don't have to make an extra request to get the entire task list again.

**Comment by joshuatf** [comment]
@louwie17 I think there might be a misunderstanding on what this issue is about.  

You are correct in that we should update the _task list/onboarding data store_ based on response (or even optimistically).   This issue is in regards to _other data stores_ that are updated.

For example, if a marketing extension plugin gets installed via another component outside the task list the marketing extensions task should be marked complete.  However the marketing task is unaware of what happens in the plugins data store.  We would need to invalidate the task list resolution in this case to make sure that accurate visibility and completion for tasks is reflected.

Did I explain that well enough?

**Comment by louwie17** [comment]
> Did I explain that well enough?

Yeah you did, sorry I did mis-understand you. We would have to make use of `invalidateResolution` for those use cases.

Makes me wonder if there isn't a nicer way of doing that, I guess first see how many of these cases we will run into.
