### ISSUE TITLE
Add SlotFill support for task list items and task cards

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7373]
After tasks have been resolved, they should have the option to slotfill the task list item and the task card itself.  See https://github.com/woocommerce/woocommerce-admin/pull/7354 for a working example.

* `WooOnboardingTask`
* `WooOnboardingTaskListItem`

Note that these slotfills could probably prove useful as exported components in the `onboarding` package.

**Comment by louwie17** [comment]
I voted slightly on the higher side, as this is important to be implemented well and relatively cleanly :)

**Comment by joshuatf** [comment]
Example of this is available in the try branch - https://github.com/woocommerce/woocommerce-admin/pull/7354.

It will need to be tested to verify the slotfills are working as expected.
