### ISSUE TITLE
Homepage orders panel does not load orders

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#7381]
### Describe the bug

On larger stores (tested this on stores where more than 1000) orders are present the Orders panel on the WooCommerce home page shows it has more than 1 item in the badge, but when opening the panel it thinks we have `fulfilled all your orders`.

### To Reproduce

1. Create a store that has upwards of a 1000 orders, make sure some are on-hold or processing.
2. Go to **WooCommerce > Home** and hide the task list
3. Take note of the badge amount in Orders
4. Expand the Orders panel, notice how it say's `You've fulfilled all your orders`.

### Screenshots
<img width="556" alt="Screen Shot 2021-07-20 at 2 02 08 PM" src="https://user-images.githubusercontent.com/2240960/126368836-f8385027-e499-4fe7-8060-f1ae917957a9.png">

### Expected behavior
It should show at-least 5 orders that require our attention.

### Additional context
I have only reproduced this on large stores, and am not sure what the exact trigger is.

**Comment by mattsherman** [comment]
@louwie17 This existed in 2.4 as well, correct?

**Comment by louwie17** [comment]
> @louwie17 This existed in 2.4 as well, correct?

Yeah, likely prior to that as well as this has not been touched in a little while.

**Comment by mattsherman** [comment]
Closing. Was fixed by #7395.
