### ISSUE TITLE
Add "low in stock" performance improvements to 2.5.0

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7390]
A few PRs need to be cherry-picked for 2.5.0 to address the "low in stock" performance issues seen in issue https://github.com/woocommerce/woocommerce-admin/issues/7358

I'm creating an issue here to reduce confusion because the PRs already have cherry-picking labels and milestone for 2.4.x release.

1. https://github.com/woocommerce/woocommerce-admin/pull/7377
2. https://github.com/woocommerce/woocommerce-admin/pull/7388
3. https://github.com/woocommerce/woocommerce-admin/pull/7389

## Commits to Cherry-Pick

I've listed the commits below in the chronological order they were merged to main. It is the same order as the PRs above.

1. 22024d7c247b240d11c23789ed70b424f62b222c
2. b74440fa90b149de7f221871882398dd35070e02
3. d5685d9fa2e2a3f33c42df3097163af54dd7807f

## Changelog

The changelog entries from 2.4.x should also be carried over to 2.5.0.

https://github.com/woocommerce/woocommerce-admin/blob/bb54b56ffca710fb69c3d74d9421854c36c822bb/readme.txt#L78-L86

## Testing Instructions

Please see the testing instructions in the core PR https://github.com/woocommerce/woocommerce/pull/30321

**Comment by adrianduffell** [comment]
@octaedro I think this is good to close out now? Thanks for adding it to 2.5 🙂

**Comment by octaedro** [comment]
Thank you @adrianduffell for the ping. I'm going to close this issue now.
