### ISSUE TITLE
Onboarding wizard is not shown and task list is hidden when creating new sub-site

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#7397]
### Describe the bug
When creating a new sub-site it doesn't kick-start the onboarding wizard and the task list seems to be hidden by default.
When going to **WooCommerce > Home** it shows the welcome to the dashboard modal instead.
When enabling the task list again, the **Store details** (onboarding wizard) shows up as finished, but when clicking on the **Store details** everything within the onboarding wizard is blank.
This is present on WC 5.5.1

### To Reproduce
- Create a multi-site and install WooCommerce
- Go to Network Admin > Sites and click Add New
- Fill out the details and click Add Site, notice how a success notice shows up at the top with View Dashboard
- Click on the View dashboard and go to **WooCommerce > Home**
- Notice how the **welcome to WooCoommerce store's online HQ** modal shows up, and the task list is not present.
- Go to **WooCommerce > Settings** and click the **Help** dropdown (top right), click **Setup wizard > Enable ( under Task List)**
- Go to **WooCommerce > Home** notice how **Store details** has a check mark
- Click on the **store details** task item, notice how the onboarding wizard is empty.

### Screenshots
![subsite-onboarding-missing](https://user-images.githubusercontent.com/2240960/126645373-d7f5ca84-0c55-4e7d-a02a-868cb18b5f6d.gif)

### Expected behavior
Should show the onboarding wizard and have the task list enabled.

**Comment by tammullen** [comment]
Noting that when I test with JN for both sub dirs and sub domain with WC 5.5.2 and 5.6.0 RC 2 I see this but WooCommerce > Home is blank

![Screenshot 2021-08-09 at 15 03 26](https://user-images.githubusercontent.com/24649833/128719341-fdbefd86-5368-4eb5-96d8-7162d090f4d7.png)

**Comment by tammullen** [comment]
Noting that with the fix in https://github.com/woocommerce/woocommerce-admin/pull/7489 I no longer see a blank screen but I still see the original issue.
- Network install and activate WC on Multisite
- Create Subsite
- On subsite go to WooCommerce > Home
- No task list or OBW unless enable them from help
Perhaps this is the expected behaviour for Network activation? I confirmed it also happens in 5.4.2
