### ISSUE TITLE
Fatal error when deleting user that is part of new sub-site

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#7398]
### Describe the bug

If WooCommerce is network activated, and we create a new user and a new sub-site for that user, when we try to delete that user we see a fatal error. This is related to https://github.com/woocommerce/woocommerce-admin/issues/7141, but was still reproducible after a fix was merged.

<details>
<summary>The actual fatal error can be seen here.</summary>

```
Fatal error: Uncaught RuntimeException: Error saving action: Table 'user5f4208c2-wp-blah.wp_8_actionscheduler_actions' doesn't exist in /srv/users/user5f4208c2/apps/user5f4208c2/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:85 Stack trace: 
#0 /srv/users/user5f4208c2/apps/user5f4208c2/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action)) 
#1 /srv/users/user5f4208c2/apps/user5f4208c2/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) 
#2 /srv/users/user5f4208c2/apps/user5f4208c2/public/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single('wc-admin_delete...', Array, 1626960792, 'wc-admin-data') 
#3 /srv/users/user5f4208c2/apps/user5f4208c2/public/wp-c in /srv/users/user5f4208c2/apps/user5f4208c2/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 85
```
</details>

### To Reproduce

1. Create a multi-site and network enable WC 5.5 and optionally add (WC admin 2.5 beta 2)
2. Go to Network admin > Users and create a new user.
2. Create a new subsite in Network admin > Sites and assign the new user.
3. Go to Network admin > Users and delete the user with the option "Delete all content." selected.
4. See fatal error, similar to: [#30266](https://github.com/woocommerce/woocommerce/issues/30266) fatal error.

### Screenshots
<img width="811" alt="Screen Shot 2021-07-22 at 10 33 14 AM" src="https://user-images.githubusercontent.com/2240960/126648797-04583ef9-4ebb-4e4f-80ef-de38638a0adf.png">

[debug-2.log](https://github.com/woocommerce/woocommerce-admin/files/6862619/debug-2.log)

### Expected behavior
Should delete user and attached site fine without erroring.

### Additional context

See this conversation and past issue for more context: https://github.com/woocommerce/woocommerce-admin/issues/7141#issuecomment-883438724

**Comment by christofervas** [comment]
I was hoping that this bug will be fixed in the newest WooCommerce 5.6 version but I tried the version 5.6 RC 2 and I get the same error when I am trying to delete a user. 

This is an important bug that affects the WordPress core functionality. Are there any plans to be fixed until the final 5.6 release?

**Comment by louwie17** [comment]
Hi @christofervas,
Sorry for not getting to this bug as fast as we fixed #7141 this will not be making it into the `5.6` release as that will be in tomorrow. I will emphasize this bug again and see if we can get it fixed for the next release.

**Comment by christofervas** [comment]
Thanks for your reply @louwie17 Is there any temporary fix even if we edit WooCommerce core files?

**Comment by joshuatf** [comment]
Hi @christofervas 👋 

A fix for this is on the way.  I would wait until https://github.com/woocommerce/woocommerce-admin/pull/7521 is approved and merged and you could build, install, and activate WooCommerce Admin from the `main` branch if you urgently need this fix.
