### ISSUE TITLE
Business features step and marketing task: include Mailpoet in both

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7449]
**Description:** Mailpoet needs to be included in the Business Features step, apart from the inclusion in the new marketing task (#7195)

**Acceptance criteria:**

- [ ] Display Mailpoet in the Business Features step. It can be the last option of the extensions list. We don't need to have a separate section just for Mailpoet
- [ ] Display Mailpoet in the Marketing task
- [ ] If Mailpoet was installed in the Business Features step, display it as installed in the Marketing task

**Comment by joshuatf** [comment]
Thanks for the ping @pmcpinto.  I previously added this to the WCCOM PR that adds the free extension 2.0 endpoint.

https://github.com/Automattic/woocommerce.com/pull/10826/files

**Comment by mattsherman** [comment]
Closing this as it has already been taken care of.
