### ISSUE TITLE
Store Profiler - Store details step: include newsletter sign up

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7450]
**Description:** if new users want to sign up for our email marketing communications, they need to do it through an inbox notification. This can easily go unnoticed and the notification redirects people to the Mailchimp confirmation page, which is a terrible experience. Signing up for email marketing should be a seamless experience (you just provide your email and that’s it!). We should try to incorporate the sign-up in the store setup experience and capture the email address in a way that would allow us to reuse it in other parts of the setup flow. For example, to streamline the WCPay account creation process. 

**Acceptance criteria:**
- [ ] Remove the inbox notification `WC_Admin_Notes_Onboarding_Email_Marketing.php`
- [ ] Move the `I'm setting up a store for a client` checkbox to the Business Details step
![Profiler step 4 with builder checkbox.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/4d8f3219-48ae-4f32-a79d-d12874f95615)
- [ ] Introduce the email address field in the Store Details step. Can we capture the email address in a way that would allow us to reuse it in other parts of the setup flow?
- [ ] Introduce a new checkbox below the email address (copy TBD). It should be checked by default
![Profiler step 1 with email opt-in.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/c05e8924-d605-4f6a-937d-7a3528f3294b)
- [ ] If the user clicks "Continue" with the checkbox checked, use the Mailchimp API to create a new subscriber.

**Event tracking:**
- Add a new event prop called `email_signup` to `wcadmin_storeprofiler_store_details_continue`. This prop should record if the user moved forward with the email marketing sign up: True|False
- Move the `setup_client` prop to `wcadmin_storeprofiler_store_business_details_continue_variant`. To follow the new placement of the `I'm setting up a store for a client` checkbox: True|False

**Comment by becdetat** [comment]
> Can we capture the email address in a way that would allow us to reuse it in other parts of the setup flow?

Yes, however we would need to know which other parts it makes sense to reuse the address first.

**Comment by pmcpinto** [comment]
> More than likely yes, however we would need to know which other parts it makes sense to reuse the address first.

The main ones are:
- Creating a Jetpack/WPCOM account
- WCPay KYC. The email address field is pre-populated after the wpcom account creation, so probably we don't need to consider this.

**Comment by ilyasfoo** [comment]
Adding some points we had in sprint planning discussion:
- The email address should be required if the checkbox is ticked

@pmcpinto Do we need to pre-fill the email address? I'm thinking if in case the user already had Jetpack connected we should. Also, maybe should we consider pre-fill it with the site's email settings if it's available?

**Comment by pmcpinto** [comment]
> @pmcpinto Do we need to pre-fill the email address? I'm thinking if in case the user already had Jetpack connected we should. Also, maybe should we consider pre-fill it with the site's email settings if it's available?

Pre-filling the email address is a good way to remove friction. So it would be great to do it in cases where we already have access to some email address. Thanks for the suggestion.

**Comment by adrianduffell** [comment]
@pmcpinto @becdetat I have a quick demo video hoping to get final sign-off ahead of the 2.7 beta release code freeze on Tuesday.

The video demonstrates pre-filling, email validation, and movement of the "client" checkbox.

https://user-images.githubusercontent.com/9312929/131343078-d1975b0a-f6af-4632-9b47-4d0f7882bc48.mov

A few notes:

### Pre-filling

- In this video, Jetpack is not connected so the email address is pre-filled using the WordPress email.
- When connected to Jetpack, the WordPress.com email address is used.

### Mailchimp Integration

- Once the step is completed, a background process is run within 24 hours to add the email address to Mailchimp (if consent given with checkbox).
- If the email address fails to be added due to technical error (e.g. woocommerce.com endpoint is unavailable), it will be retried again the next day.

### Data Storage

- The email address and checkbox data is stored in the site database for later re-use.

### Event Tracking

The tracks events changes have been made.

**Comment by adrianduffell** [comment]
Re-opening pending final approval ☝️

**Comment by pmcpinto** [comment]
@adrianduffell thanks for sharing the demo. It looks great!

We just need to add "Powered by Mailchimp" to the email marketing sign up copy:

![Profiler step 1 with email opt-in (1)](https://user-images.githubusercontent.com/3380168/131451315-23730747-be91-448a-b055-c868959a3665.png)

**Comment by pmcpinto** [comment]
@adrianduffell is this going to be included in wc admin 2.8 or 2.9?

**Comment by ilyasfoo** [comment]
@pmcpinto Actually we made it into 2.7. Hope that's ok? 😅

**Comment by adrianduffell** [comment]
Yep it should make it into the next 2.7 pre-release (beta 2 or RC).

**Comment by pmcpinto** [comment]
Perfect 😄 So it will be included in WC 5.8, correct?

**Comment by adrianduffell** [comment]
Yes, that's correct 🎉
