### ISSUE TITLE
Allow Revenue report to use orders as the base unit rather than days, or show tax and shipping revenue in Orders report

### ISSUE THREAD

**Issue by apmwebdev** [woocommerce/woocommerce-admin#7453]
### Is your feature request related to a problem? Please describe.
Apologies if there's already a request for this. I couldn't find one. We fairly often get requests from customers who would like to see tax and shipping data in regard to orders. This could take the form of offering an alternate view of the Revenue report that uses orders rather than days as rows in the table, or by adding those columns to the Orders report, but a fair number of store owners say that they need this data in this format for accounting purposes.

### Describe the solution you'd like
The simplest solution to this from a UI standpoint would be to add tax and shipping revenue as columns in the Orders table, possibly with a Total Sales column as well.

### Describe alternatives you've considered
I usually recommend the QuickBooks integration or Metorik as alternatives.

### Should this be prioritized? Why?
Yes, because we get this request fairly often. I could have sworn there was an existing issue for it, but maybe not. That being said, alternatives exist, so this is not a critical issue by any means.

### Additional context
This particular request was from 30650975-hc

**Comment by joshuatf** [comment]
Thanks for the issue, @apmwebdev!  I had to double take as I also thought this already existed.

While it's definitely possible to extend these reports via filters, I agree that this would be useful information to include out of the box.

**Comment by ilyasfoo** [comment]
This is a great feature suggestion, thank you. Unfortunately, I have to close it due to a lack of prioritization on our part since it isn't aligned with our current focus at the moment.

p90Yrv-2Bc-p2
