### ISSUE TITLE
WC Navigation: UI issue in WC Settings page

### ISSUE THREAD

**Issue by ecgan** [woocommerce/woocommerce-admin#7468]
### Describe the bug

I have a site hosted at pressable.com. When WooCommerce Navigation feature is enabled, it causes UI issue with WC Settings page - the side bar and top bar is not visible.

For context, this is the WC Home page, everything looks ok. 

![image](https://user-images.githubusercontent.com/417342/128387161-9019a4b3-d510-4642-91a8-7f6bc0e097f4.png)

This is the WC Settings page, with missing side bar and top bar.

![image](https://user-images.githubusercontent.com/417342/128387215-e60a170d-1f31-4723-a024-6c8de9ca4af3.png)

Here are the WC plugins I'm using: 

![image](https://user-images.githubusercontent.com/417342/128387320-c58179c8-ce69-41f5-9aa7-21429c7cc1b2.png)

### To Reproduce

1. Enable WooCommerce Navigation feature in `/wp-admin/admin.php?page=wc-settings&tab=advanced`.
2. Go to WooCommerce Settings page: `/wp-admin/admin.php?page=wc-settings&tab=general`

### Actual behavior:

Side bar and top bar is missing.

### Screenshots

See above.

### Expected behavior

Side bar and top bar should appear.

### Desktop (please complete the following information):

* OS: [e.g. iOS]: Mac OS.
* Browser [e.g. chrome, safari]: Chrome
* Version [e.g. 22]: 92.

**Comment by louwie17** [comment]
@ecgan thanks for creating an issue and trying out our latest rc build.
I am not able to reproduce this locally or on a Pressable site with the same WC versions. Do you have any other plugins enabled? Is this still happening when those are disabled?
Lastly do you have any errors displayed in your console window?

**Comment by ecgan** [comment]
@louwie17 , hey thanks for checking this out. I just did a conflict test and turns out this issue is caused by another plugin. I'll talk to the plugin developer on this. Sorry for the trouble. I'm closing this issue. 🙏
