### ISSUE TITLE
Refactor the `onFilterChange` method in the `AdvancedFilters` component

### ISSUE THREAD

**Issue by aprea** [woocommerce/woocommerce-admin#7470]
In #7423 I introduced a `shouldResetValue` parameter to the `onFilterChange` method in the `AdvancedFilters` component.

This was added to fix the bug described in #7422.

It was pointed out in the PR that this was not an ideal solution and instead we should refactor the `onFilterChange` method to remove the `property`, `value`, `shouldResetValue` params and instead accept an object that is used to update the `activeFilters` state in the component.

This would require a small refactor for the existing filter components (e.g. `AttributeFilter`, `NumberFilter`, `SearchFilter`, etc.) to use this new parameter.

**Acceptance Criteria**
- Remove the `property`, `value`, `shouldResetValue` params in the `onFilterChange` method in the `AdvancedFilters` component.
- Introduce a new object param.
- Update the `activeFilters` state with this new param.
- Refactor the existing filter components to use this new param.

**Comment by ilyasfoo** [comment]
I think it's good to fix this issue since it's I don't think it's too complex and the information & context are pretty clear.
