### ISSUE TITLE
[GlobalStep] Variation product images fails to load for variation filter suggestion results on "Analytics -> Orders" screen.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#7496]
## Bug Description:
Variations product images are fails to load on variation filter suggestion results over a " Analytics-> Orders" screen.

## Environment:
Woocommerce Version : WooCommerce 5.5.2 and 5.6.0 RC 2
WordPress version: v5.8

PC:
Windows 10, Mac 10.14.6
Chrome(Version 92.0.4515.131) 
Firefox(Version 90.0.2)
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the setup wizard.
1. Import the Products CSV on products screen.
1. Go to " Analytics-> Orders" screen.
1. Select Advance filter and click on "+" add a filter button.
1. Select Variation filter and search for any variation product.
1. Observe that Variations images are fails to load.

**Note:**
The same scenario observed on the Analytics->Variations screen.

## Actual Result:
Variation product images fails to load for variation filter suggestion results on "Analytics -> Orders" screen.

## Expected Result:
Variations images should be displayed on variation advance filter suggestions over a " Analytics-> Orders" screen.

## Screenshots:
![#7496_1](https://user-images.githubusercontent.com/41110392/129060664-c7296ed3-30f8-4707-b929-028424d43ea8.png)
![#7496_2](https://user-images.githubusercontent.com/41110392/129060676-f6f861a5-7c6a-4970-9a21-ab3758c64522.png)

**Comment by moon0326** [comment]
@gglobalstep Thank you for taking the time to report this issue. I was able to verify it on my end. We'll work on it soon.

**Comment by chihsuan** [comment]
I believe this is expected since variations are not associated with product images. 

![Screen Shot 2022-01-13 at 15 32 56](https://user-images.githubusercontent.com/4344253/149285548-50a82d2e-a7a6-41b5-b5c6-1274af07816a.png)

![Screen Shot 2022-01-13 at 15 34 57](https://user-images.githubusercontent.com/4344253/149285793-dc053a92-f4b5-459e-90a8-3a304f4483b0.png)


@moon0326  I think we can close this for now. What do you think?

**Comment by ilyasfoo** [comment]
I agree @chihsuan. Closing this
