### ISSUE TITLE
Customer Search Advanced Filters Custom Date Range Returning Blank Result

### ISSUE THREAD

**Issue by sukafia** [woocommerce/woocommerce-admin#7507]
### Describe the bug

When you navigate to WooCommerce > Customers and try to use the "Advanced Filters"  to filter "Registered" or "Last Active" customers by a date range, you get a blank result if you try to move to a month in the past or in the future using the calendar Prev/Next arrow.

Screencast: https://d.pr/i/DnTiuP

### To Reproduce

1. Go to WooCommerce > Customers
2. In the "Show" data field select "Advanced Filters"
3. Click "Add a filter" and select "Registered" or "Last Active"
4. Click the calendar field to open the calendar 
5. Click on the Next/Prev icon of the calendar and you'll get a blank result. 

### Actual behavior:

The calendar prev/next arrow returns a blank result

### Screenshots
https://d.pr/i/DnTiuP

### Expected behavior

Calendar prev/next icon should show the previous or next month. 

### Desktop (please complete the following information):

* OS: MacOS Bigsur
* Browser: Google Chrome
* Version 11.4

**Comment by moon0326** [comment]
Thank you @sukafia for taking the time to report this bug. I was able to reproduce it on my end. We'll work on it soon.

**Comment by sukafia** [comment]
4226313-zen

**Comment by urlund** [comment]
+1 for bug fix :)
