### ISSUE TITLE
Add filters to API orders queries

### ISSUE THREAD

**Issue by Malaiac** [woocommerce/woocommerce-admin#7520]
Context :
the shop is managing both standard web checkout orders, and customer service orders (created from Zoho via Zapier and WooCommerce REST API)
Those CS orders (identified by postmeta = '_created_via':'rest-api') are not linked to any real payment. They are created with the real products, so they have an '_order_total' and are stored in wc_order_stats with values.

I should be able to hook a filter to the DB class (ReportDataStore ?) to filter the reports to exclude any CS order.
( AND order_id NOT IN (SELECT post_id FROM wc_postmeta WHERE meta_key ='_created_via' AND meta_value = 'rest-api')

Right now, I've had to apply an ugly solution by nulling the _order_total, _order_tax and 'UPDATE {$wpdb->prefix}wc_order_stats SET total_sales = 0, tax_total = 0, net_total = 0 WHERE order_id = %d' for each CS order then rebuilding the stats cache

**Comment by joshuatf** [comment]
Hi @Malaiac 👋 

Have you tried to do this using one of the sql clauses filters?

https://github.com/woocommerce/woocommerce-admin/blob/43366ee48f9cb6d0e5a81115db21726a551172d7/src/API/Reports/SqlQuery.php#L120

You could hook into this and add your `where` clause on orders to accomplish this.  Let me know if you have any trouble implementing this.

**Comment by Malaiac** [comment]
@joshuatf The hooks don't seem to be triggered.
page context : /wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Forders
I hacked a few debug lines in woocommerce-admin/src/API/Reports/SqlQuery.php this file ( in the get_sql_clause method) without any output on the back office front

`protected function get_sql_clause( $type, $handling = 'unfiltered' ) {

		echo "\n " . __METHOD__ . " / type $type / $handling";`
= No output

**Comment by joshuatf** [comment]
@Malaiac could you give an example of the code you're running?

Adding the following, I'm able to manipulate the clauses from the orders query:

```php
add_filter( 'woocommerce_analytics_clauses_where_orders_subquery', function( $clauses ) {
	wp_die( print_r( $clauses ) );
} );
```

The REST endpoint ( `/wp-json/wc-analytics/reports/orders` ) then shows the `where` clauses being used and can be adjusted as needed.

**Comment by Malaiac** [comment]
It was that da****d woocommerce analytics cache messing with me. 

`

 
add_filter( 'woocommerce_analytics_clauses_where', 'ondilo_filter_sav_orders_out_of_analytics', 10, 2 );
function ondilo_filter_sav_orders_out_of_analytics( $clauses, $context ) {
	global $wpdb;
	$clauses[] = "
	AND {$wpdb->prefix}wc_order_stats.order_id NOT IN (SELECT post_id FROM $wpdb->postmeta WHERE meta_key = '_created_via' AND meta_value = 'rest-api') ";
	return $clauses;
	

}
`

SOLVED
