### ISSUE TITLE
Add woo_country_code param to ExPlat API request

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7527]
A new "custom segment" is planned in ExPlat to allow experiment segmentation based on the WooCommerce country setting.

The `@woocommerce/explat` package should be updated to send a `woo_country_code` parameter automatically in the REST API request made in `fetchExperimentAssignment` here:

https://github.com/woocommerce/woocommerce-admin/blob/4e2961e04a8c0ffe5f7d5156bb12c40b8eabb518/packages/explat/src/assignment.ts#L21-L28

The value should be in the form of `US:GA`. I _think_ this can be retrieved from `wcSettings.preloadSettings.general.woocommerce_default_country`.

**Comment by adrianduffell** [comment]
@ilyasfoo is using `wc.wcSettings.LOCALE` the right way to get this value?

<img width="553" alt="Screen Shot 2021-08-18 at 7 20 40 pm" src="https://user-images.githubusercontent.com/9312929/129889486-148101ea-28cf-4216-bbb4-43f672253b96.png">

**Comment by ilyasfoo** [comment]
@adrianduffell AFAIK we can use `wcSettings.preloadSettings.general.woocommerce_default_country` 
![image](https://user-images.githubusercontent.com/3747241/129899555-b071cb6b-173c-4e2d-abcc-8bee183f88a9.png)

**Comment by moon0326** [comment]
@adrianduffell @ilyasfoo It looks like `preloadSettings.general` is only available on the Home screen. I wasn't able to get the value outside of Home screen. I don't want to keep adding preloaded values, but I think `woocommerce_default_country` deserves to be included by default. What do you guys think?
