### ISSUE TITLE
[GlobalStep] Database errors are triggered upon installing and activating "WooCommerce" plugin on Multi-site.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#7528]
## Bug Description:
Database errors are triggered upon installing and activating "WooCommerce" plugin on Multi-site.

## Environment:
Woocommerce Version : WooCommerce 5.5.2 and 5.6.0
WordPress version: v5.8

PC:
Windows 10, Mac 10.14.6
Chrome(Version 92.0.4515.131) 
Firefox(Version 90.0.2)
Safari: v14.1.2

## Steps To Reproduce:
1. Set up multi-site.
1. Install and activate Query Monitor plugin.
1. Install WooCommerce and network activate it.
1. Observe that Database errors are triggered.

## Actual Result:
Database errors are triggered upon installing and activating "WooCommerce" plugin on Multi-site.

## Expected Result:
User should be able to install and activate "WooCommerce" plugin on Multi-site without any errors.

## Screenshot:

![#7528](https://user-images.githubusercontent.com/41110392/129920165-f8db562e-fcaa-4563-955f-4bea673734ca.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.22
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_
Total Database Size: 9.24MB
Database Data Size: 5.01MB
Database Index Size: 4.23MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_2_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Data: 0.41MB + Index: 0.03MB + Engine InnoDB
wp_2_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_2_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_2_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_3_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_3_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_options: Data: 0.39MB + Index: 0.03MB + Engine InnoDB
wp_3_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_3_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_3_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_3_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_3_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_3_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_3_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_3_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_3_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_3_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Companion Plugin: by Osk – 1.18
Jetpack: by Automattic – 10.0
Query Monitor: by John Blackbourn – 3.7.1
WooCommerce: by Automattic – 5.6.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2021-08-18 09:54:34 +0000
Newest: 2021-08-18 09:54:34 +0000

### Status report information ###

Generated at: 2021-08-18 14:39:23 +00:00
`

</details>

**Comment by joshuatf** [comment]
I believe the `DESCRIBE ${table_name}` comes from WordPress core and is just a quirk that occurs when using `dbDelta`.  I think this a non-issue since the errors are suppressed in production, but even if we wanted to address I believe the fix would be upstream.

cc @louwie17 for a sanity check before I close this issue.

**Comment by louwie17** [comment]
> I believe the `DESCRIBE ${table_name}` comes from WordPress core and is just a quirk that occurs when using `dbDelta`. I think this a non-issue since the errors are suppressed in production, but even if we wanted to address I believe the fix would be upstream.

I agree, the `DESCRIBE ${table_name}` is potentially coming from the `dbDelta` function, although when looking at the queries it correctly created the tables below this (see screenshot).
<img width="1405" alt="Screen Shot 2021-09-07 at 11 41 21 AM" src="https://user-images.githubusercontent.com/2240960/132364384-4b290b41-9ae4-43ee-820f-1d1daae3a9bc.png">

There was a similar issue in Woo Core and [their consensus was that it is actually a query monitor plugin issue](https://github.com/woocommerce/woocommerce/issues/28527#issuecomment-743436335).
Given this doesn't cause any errors or logs in the debug log and still creates the tables correctly, I am going to close this issue.
