### ISSUE TITLE
Add featured pill for MailPoet and Google Listings in marketing task

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7542]
## Description

It's currently not clear that MailPoet and Google Listings are WooCommerce products and is listed alongside Mailchimp and other more recognizable brands in the marketing task. This could lead store owners to bypass that option for brands they're familiar with.

As one solution to highlight MailPoet and Google Listings in the list, we can include a "Built by WooCommerce" pill to give them added emphasis over the other extensions in the list.

## Design

This shows the desired pill design:

<img width="728" alt="Screen Shot 2021-08-19 at 5 49 29 PM" src="https://user-images.githubusercontent.com/5121465/130154118-3f6f2564-8726-4288-acfe-c49efb790957.png">

## Acceptance criteria

- A "Built by WooCommerce" pill is shown for more MailPoet and Google Listings in the marketing task list

## Dev tasks

- [ ] Add a boolean to the data spec on wccom to indicate whether an extension is built by WooCommerce
- [ ] Update the fallback data in wc-admin to include the boolean
- [ ] Add  "Built by WooCommerce" pill to the MailPoet and Google Listings extensions in the marketing task list

**Comment by joshuatf** [comment]
Dev note: we should try to add this pill using the `title` property if possible to avoid introducing a new prop on the extension components.

**Comment by pmcpinto** [comment]
> @pmcpinto @becdetat and all - open to alternatives on the pill label copy if you have ideas on anything that could work better.

This solution looks good to me!

**Comment by becdetat** [comment]
@pmcpinto I see that you've added this to C16, however it wasn't scoped or included in C16 planning, so we won't be able to commit to it this sprint. There's a possibility of including it in the sprint if we meet the existing sprint goals.

**Comment by pmcpinto** [comment]
👍 I'm going to remove it from Cycle 16 but keep it in the needs scoping column, as we discussed.

**Comment by becdetat** [comment]
@pmcpinto should this be in scope for a release? It's still in the needs scoping column.

**Comment by pmcpinto** [comment]
> @pmcpinto should this be in scope for a release? It's still in the needs scoping column.
I'm going to add it to the cycle 19 backlog.

@elizaan36 the google listing and ads extension was also built by Woo. Do you think we should also include the pill?

**Comment by elizaan36** [comment]
Yes, thanks for catching that! Google listings would also have the `Built by WooCommerce` pill.

**Comment by mattsherman** [comment]
> Dev note: we should try to add this pill using the `title` property if possible to avoid introducing a new prop on the extension components.

@joshuatf I don't see a `title` property in the spec data. Can you please clarify what you mean by this suggestion.

**Comment by mattsherman** [comment]
@pmcpinto @elizaan36 Should these pills only be shown in the marketing task, or should they be shown in the OBW as well when these extensions are presented?

**Comment by elizaan36** [comment]
The pills should only appear in the marketing task if possible, to differentiate from non-Woo built ones. The OBW extensions are all Woo-built so there isn't a need for the pill there.

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7542?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro
