### ISSUE TITLE
OBW: Update WC Pay label on recommended extensions list

### ISSUE THREAD

**Issue by vbelolapotkov** [woocommerce/woocommerce-admin#7551]
### Is your feature request related to a problem? Please describe.
In recommended extensions list there is a label Accept credit cards with WooCommerce Payments. However with introduction of new Payment Methods the wording needs an update.

### Describe the solution you'd like
Something a bit more generic like Get paid with WooCommerce Payments might work.

### Additional context
Slack discussion: p1628758329126000/1628234436.374100-slack-CGGCLBN58

**Comment by pmcpinto** [comment]
@elizaan36 what do you think about the copy suggestion?

**Comment by elizaan36** [comment]
Thanks for calling this out, @vbelolapotkov. We should definitely have a look at updating this copy to reflect the expanded payment method options.

**Comment by vbelolapotkov** [comment]
@elizaan36 I think a flexible solution is needed here, because we may update supported payment methods pretty quickly. So the message updates with every release shouldn't be required.

**Comment by elizaan36** [comment]
@LevinMedia what are your thoughts on the copy above for WCPay in the onboarding wizard?

**Comment by LevinMedia** [comment]
@elizaan36 I think that will work great 👍
