### ISSUE TITLE
WC 5.7 & WC Admin 2.6 - Business Features step: auto-installing extensions who were excluded from the bundle

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7564]
### Describe the bug
Google Ads and Mailchimp are being auto-installed in the business features step

### To Reproduce

1. Create a new store with WC 5.7 beta installed
2. In the store details step, select a country where we should be promoting all the extensions to make sure they're being displayed in the business features step (eg. US)
3. Complete all the steps until the business features step
4. See that we mention Google Ads and Mailchimp in the footnote but they're not included in the bundle
5. Visit the marketing task
6. See that the Google Ads and Mailchimp were installed in the business features step

### Actual behavior:
We're installing Google Ads and Mailchimp in the business features step

### Screenshots
https://www.loom.com/share/fa71c99a82e04fe4827d2828626ad9ac

### Expected behavior
Google Ads and Mailchimp should not be installed in the business features step. Just in the marketing task

Epic about this initiative: #7195

**Comment by pmcpinto** [comment]
Hey @louwie17 I'm testing WC 5.7 rc2 and I'm still seeing this issue: https://d.pr/i/7JWku3

Can you double-check this?

**Comment by louwie17** [comment]
> Hey @louwie17 I'm testing WC 5.7 rc2 and I'm still seeing this issue: https://d.pr/i/7JWku3
> 
> Can you double-check this?

Thanks @pmcpinto for the ping, it does appear this fix has not been cherry-picked into the final 2.6 release and the subsequent patch releases. Hopefully we can add this to `2.6.3` if it hasn't been released yet.

**Comment by pmcpinto** [comment]
👍 Let me know if it's possible to add this to 2.6.3. The rest of the fixes were included, correct? Namely: #7565, #7566 and #7567

**Comment by louwie17** [comment]
@pmcpinto this fix made it into 2.6.4, which is included in 5.7, did you want to try it again and see if it's fine now? Then we can close this ticket again.

**Comment by pmcpinto** [comment]
I just tested 5.7 and it's working properly. Thanks!
