### ISSUE TITLE
Marketing task: tweak the task completion logic

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7567]
**Description:** the current logic marks the task as complete when one of the extensions is installed. After testing the flow, I think this can be misleading due to the following: If users install one of the marketing extensions before visiting the task, most likely they'll skip checking the task because it's marked as completed. We're installing the Mailpoet in the business features step bundle, so a significant % of users are going to be covered by this scenario

There are a couple of ways to fix this:
- We mark the task as completed when the user installs one extension and visits the task at least once
- We mark the task as completed when the user clicks to manage one of the extensions within the task
- As a temporary solution, we remove Mailpoet from the business features step bundle to ensure that most users see the task marked as incomplete when they visit the home screen

Epic about this initiative: #7195

**Comment by becdetat** [comment]
@pmcpinto I just saw that this is not a bug. We're in RC territory with the 2.6 release so I need to push back against it being included.

**Comment by pmcpinto** [comment]
@becdetat I know that we try to avoid this kind of change in the middle of the wcadmin release. If we don't tweak the logic, we risk seeing the number of installs dropping so much that we need to revert everything. We should mitigate as much as possible the risks that can jeopardize the success of the marketing task the products owned by other teams and partners. So it would be better to make an exception and move forward with this.

**Comment by pmcpinto** [comment]
@louwie17 is it possible to confirm that `wcadmin_tasklist_task_completed` is being fired when the task is marked as complete and the corresponding value of the `task_name` prop? I'm not getting this event when I'm testing the marketing task completion flow.
