### ISSUE TITLE
Undefined value in prop for the track `wcadmin_storeprofiler_store_details_continue`

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#7569]
### Describe the bug

The event prop [`derived_currency`](https://github.com/woocommerce/woocommerce-admin/blob/0d53d2fa16943befb0067ccbd62b87b3d05a8afe/client/profile-wizard/steps/store-details/index.js#L128) contained in the track `wcadmin_storeprofiler_store_details_continue` is recording a `null` value because `currencySettings.currency_code` is actually referring to a null value. I think the valid attribute should `currencySettings.code`.

However, it should be noted that the existing track data does record 1-10 rows per day that actually has a non-undefined value, last checked on August 2021. So maybe further investigation may be required to confirm so the fix will not cause a regression.

**Comment by chihsuan** [comment]
@ilyasfoo You're right. There is no `currency_code` attribute in the [`currencySettings`](https://github.com/woocommerce/woocommerce-admin/blob/0d53d2fa16943befb0067ccbd62b87b3d05a8afe/packages/currency/src/index.js#L124-L132). 

![Screen Shot 2022-01-19 at 16 18 16](https://user-images.githubusercontent.com/4344253/150091622-742a4adc-b74e-4594-b0b8-2a87116c1f76.png)

> However, it should be noted that the existing track data does record 1-10 rows per day that actually has a non-undefined value

I think it's most likely that some previous WooCommerce versions work.
