### ISSUE TITLE
Products Reports / Analytics - Product sales report CSV data is incorrect

### ISSUE THREAD

**Issue by Brandoning** [woocommerce/woocommerce-admin#7571]
### Describe the bug
When using the reporting / analytics screen we can filter by date to see the number of products sold within a timeframe.

This works fine in the web UI, but if we press download to get the CSV / spreadsheet version it won't match the data we see in the web UI.

There are duplicated rows and incorrect totals after adding the Net Revenue column up.

### To Reproduce
1. Log in to WP admin
2. Go to Analytics > Products
3. Set a custom date range (we were using 6th August - 12th August)
4. Click download for CSV report

### Actual behavior:
Duplicated / missing order and product rows in the resulting .csv download.

### Expected behavior
Data should match the figures in the web UI, rows should not be duplicated or deleted.

### Desktop (please complete the following information):

OS X
Chrome
Latest

### Additional context
**This can be fixed, but we're not sure why it works:** When exporting the product report CSV, make sure you have "Net Sales" ordered as descending in the web UI.

After exporting the CSV with Net Sales set to descending, all data matches the Web UI and is correct.

**Comment by jessLundie** [comment]
Also reported in 4251781-zen.
