### ISSUE TITLE
WC 5.7 Stats overview card is showing extra padding

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7576]
### Describe the bug
I'm seeing some extra padding around the summary number components in the Stats overview section on the home screen. In single column and 2 column layouts.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/5121465/131018996-7e7bca4b-5500-4290-88ff-b028a5447ce0.png">

### To Reproduce

    1. Create a new store with 5.7 beta installed
    2. Visit the home screen
    3. See the error

### Expected behavior
No padding around the summary numbers

<img width="534" alt="image" src="https://user-images.githubusercontent.com/5121465/131019235-adec5215-5cc0-4fc1-a21b-7aada92259b3.png">

I noticed that this css with added padding is hidden in previous versions, so it might be a matter of just hiding/removing that from the `components-card_body` element:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/5121465/131019663-b7af1d65-4cd6-4be6-aa94-4c5e89913d1c.png">

### Desktop (please complete the following information):

* OS: Mac 10.15.7
* Browser: Firefox 91.0.1

**Comment by moon0326** [comment]
> I was able to reproduce it. This error is not present on WooCommerce 5.6
> // cc @moon0326

Thank you for the ping @octaedro (sorry for the late reply).

This looks pretty simple to fix. I'll look into this today so we can ship it tomorrow.
