### ISSUE TITLE
Navigation: Turn on feature flag for Core

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#7581]
Turn on Navigation feature flag for Core builds.

See https://wp.me/pcShBQ-6u for more details

## Criteria

- [ ] The feature toggle should be available at WooCommerce > Settings > Advanced > Features
- [ ] Include copy explaining that the feature is in BETA
- [ ] The toggle should be disabled by default
- [ ] The toggle should respect a value that has already been set
- [ ] The feature should remain enabled for users of the e-commerce plan
- [ ] e-comm users who have opted out should remain opted out

**Comment by ilyasfoo** [comment]
Closing this until a decision is made for the direction of navigation feature pbIJXs-1aH-p2
