### ISSUE TITLE
Missing data from Settings properties for Customer effort score

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7592]
### Describe the bug
When filtering Tracks for `wcadmin_ces_feedback` and [`settings_section`](https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=wcadmin_ces_feedback&interval=day&prop=settings_section&startdate=20210731&stat=uniques), the top result is `null`. This should instead include the top level settings sections (Products, Payments, etc).
<img width="1354" alt="Screen Shot 2021-08-30 at 11 45 43 AM" src="https://user-images.githubusercontent.com/5121465/131374978-ac979308-6280-499b-a379-fcc61993f505.png">

The same issue is happening with the [`settings_area` property](https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=wcadmin_ces_feedback&interval=day&prop=settings_area&startdate=20210731&stat=uniques).
<img width="1354" alt="Screen Shot 2021-08-30 at 11 45 43 AM" src="https://user-images.githubusercontent.com/5121465/131375111-ff2716ae-8950-4edd-b5a1-a7c1aaac4bca.png">

Because the majority of results are coming in as `null`, we can't derive any meaningful info from these results in the settings to make improvements.

### Expected behavior
`settings_section` should contain all top level settings areas where users can encounter the CES modal, and `settings_area` would be all subsections within those areas.
cc @pmcpinto

**Comment by pmcpinto** [comment]
I'm going to add this to the cycle 19 backlog
