### ISSUE TITLE
Setup wizard stays in loading state indefinitely

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7604]
### Describe the bug
When navigating from the task list to the setup wizard, the initial step "Store details" does not load.

### To Reproduce

1. Open the task list and refresh the page.
2. Click on the first task to go to "Store details."
3. Note the infinite spinner.

### Actual behavior:
Setup wizard never loads.

### Screenshots
<img width="1036" alt="Screen Shot 2021-08-31 at 5 58 42 PM" src="https://user-images.githubusercontent.com/10561050/131581377-e89979a5-eee6-461f-af34-c7860bc13828.png">

### Expected behavior
Expected the store details step to appear.

**Comment by moon0326** [comment]
@joshuatf ✋ I wasn't able to reproduce it locally and on a JN site. If you still have the problem locally, do you have any errors by any chance?

**Comment by joshuatf** [comment]
@moon0326 I'm still able to reproduce this on a JN site.  No errors occur in the console or network.  I think there may be one extra step to reproduce, which is to complete the store profiler first and then do the above steps.

I'll test a bit more today and see if I can figure out the cause.

**Comment by joshuatf** [comment]
@moon0326 I was able to find the cause.  It has to do with the new store email field.  The loading state is dependent on its resolution, but it never gets called.
