### ISSUE TITLE
Extra copy in store setup task list

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7609]
### Describe the bug
The store setup task list is showing extra copy. I believe it's related to our conversation about the task list refactoring/bundling into WCPay/potential confusion with the previous task list experiment.

As we get closer to launching a new task list experiment, we need to make sure the control is back to normal for accurate results.

Here's the task list I'm seeing with extra copy:
![Screen Recording 9-1-2021 at 11 21 PM](https://user-images.githubusercontent.com/5121465/131781634-51e5e5fe-15b8-489f-bde6-7dcd2aeae8fb.gif)

### To Reproduce

1. Go to WooCommerce home in a new store
2. See error

### Expected behavior
The correct version of the task list shows the title and time estimate with no additional copy:
<img width="698" alt="Screen Shot 2021-09-01 at 11 28 13 PM" src="https://user-images.githubusercontent.com/5121465/131781913-6446264f-fe2e-4b02-9c80-ba0e5d89b761.png">

@becdetat @octaedro @louwie17 @pmcpinto

**Comment by pmcpinto** [comment]
@elizaan36 thanks for opening the issue. I think this was already fixed by @louwie17 in #7568. Lourens can you confirm this?  Thanks
