### ISSUE TITLE
Navigation: Orders badge is missing

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7641]
### Describe the bug
In the new WooCommerce navigation, the orders badge with number of unfulfilled orders isn't appearing in the navigation.
<img width="1038" alt="Screen Shot 2021-09-08 at 2 09 55 PM" src="https://user-images.githubusercontent.com/5121465/132572393-7646e40c-9dab-482a-9ba4-1ba4ab96369f.png">

### To Reproduce

1. Enable the new WooCommerce navigation
2. Navigate to WooCommerce home

### Expected behavior
The orders badge should appear with the count of unfulfilled orders in the store.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/5121465/132572113-dc74b93b-5cfa-40cc-8f6b-b7eaf285b953.png">

**Comment by mattsherman** [comment]
@pmcpinto This seems like a pretty big miss for the new nav. I'm not sure of the overall prioritization of the new nav though. What are your thoughts on how to prioritize this?

**Comment by pmcpinto** [comment]
> @pmcpinto This seems like a pretty big miss for the new nav. I'm not sure of the overall prioritization of the new nav though. What are your thoughts on how to prioritize this?

I agree. I think we should try to fix it during Cycle 18. It would be helpful to know the effort required to implement this fix.
