### ISSUE TITLE
Note is attempting to query for meta against wp_postmeta table, but it is not a post

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/woocommerce-admin#7660]
### Describe the bug
When a`Note` is loaded, it attempts to load the metadata of the note ([source](https://github.com/woocommerce/woocommerce-admin/blob/9a008e204683e80de00324ff55676e496e76849b/src/Notes/DataStore.php#L116)), however, a Note is not a post, it uses a custom table. Note meta should live in a separate custom table, that doesn't seem to exist - assuming that means notes have no meta... but definitely should not be querying the postmeta table for meta.

```
WC_Data_Store_WP->read_meta()
wp-content/plugins/woocommerce/includes/data-stores/class-wc-data-store-wp.php:94
WC_Data_Store->__call()
wp-content/plugins/woocommerce/includes/class-wc-data-store.php:207
WC_Data->read_meta_data()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:598
Automattic\W\A\N\DataStore->read()
wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php:116
WC_Data_Store->read()
wp-content/plugins/woocommerce/includes/class-wc-data-store.php:159
Automattic\W\A\N\Note->__construct()
wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Note.php:89
WC_Notes_Run_Db_Update::show_reminder()
wp-content/plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php:278
do_action('current_screen')
wp-includes/plugin.php:470
WP_Screen->set_current_screen()
wp-admin/includes/class-wp-screen.php:421
set_current_screen()
wp-admin/includes/screen.php:243
```

### To Reproduce
To reproduce I had to force a note to attempt to be displayed, I did this by simply calling `WC_Notes_Run_Db_Update::show_reminder();` and in doing so it would attempt to load the notes DB update reminder.

You can then see by using Query Monitor or your preferred alternative that a query is being made against the postmeta table, looking for meta using the ID of the note named `wc-update-db-reminder`.

### Screenshots
https://c.m6e.io/w2VDQe

### Expected behavior
I would not expect non post objects to call the default WP postmeta table for metadata.

### Additional context
Tested using the latest stable WooCommerce 5.6.0 which includes WooCommerce Admin 2.5.1.

**Comment by pmgarman** [comment]
I don't see any obvious calls to actually USING meta data, is this as simple as removing the 4 lines of code calling to read or save metadata? None of the Note, NoteTraits, and Notes classes call anything meta related.

**Comment by mattsherman** [comment]
@pmgarman Thanks for reporting this. I agree that appears that Notes do not actually use metadata, but I am not 100% sure.

@allendav I know it has been a while, but according to git, I think you are one of the original implementors of the Admin Notes data source. Do you happen to recall anything specific about the use (or non-use) of metadata by Notes?

**Comment by mattsherman** [comment]
@woocommerce/isotope Does anybody have any insight into whether Notes makes use of metadata?

**Comment by allendav** [comment]
> Do you happen to recall anything specific about the use (or non-use) of metadata by Notes?

Sorry, no, it has been far too long to recall

**Comment by louwie17** [comment]
For extra context, it looks we overwrote the `get_data` function here just to prevent calling `get_meta_data` -> https://github.com/woocommerce/woocommerce-admin/blame/main/src/Notes/Note.php#L165-L176

Which makes me lean towards this not being necessary.

**Comment by johnregan3** [comment]
@mattsherman  I can take this one.  Do I need to have this Issue assigned to me?

**Comment by johnregan3** [comment]
PR issued. [#7988](https://github.com/woocommerce/woocommerce-admin/pull/7988)

**Comment by mattsherman** [comment]
@johnregan3 Thanks for submitting a PR! I will make sure the team reviews this.
