### ISSUE TITLE
Composite Product reports breaks when WooCommerce Admin is acitvated. 

### ISSUE THREAD

**Issue by simplysaru** [woocommerce/woocommerce-admin#7668]
WooCommerce Admin messes up the reports for [Composite Products](https://woocommerce.com/products/composite-products/). The report works as expected when WooCommerce Admin is deactivated. 

### To Reproduce

1. Ensure the Composite Products and WooCommerce Admin plugin is active. 
2. Click on "Analytics > Composites"
3. The report will be missing any data.

### Actual behavior:
![FtEJOR](https://user-images.githubusercontent.com/2734132/133629609-880dee08-f8fa-4129-b350-3a9e58541bf9.png)

### Expected behavior
![ME31wy](https://user-images.githubusercontent.com/2734132/133629756-d63b5057-0245-4b4d-9b95-cc5aff2fd315.png)

### Desktop:

* OS: MacOs 11.6, 
* Browser Firefox 
* Version 93.

### Smartphone:

* Device: iPhone 11
* OS: iOS 15
* Browser: safari
* Version: 15

### Additional context

Here are some console errors we(Customer and I found)
<img width="1612" alt="Markup 2021-09-16 at 15 21 22" src="https://user-images.githubusercontent.com/2734132/133630643-7e86044a-c851-4a52-9f0d-9c32da56cfc9.png">

![wSM9cD](https://user-images.githubusercontent.com/2734132/133630837-6511a05f-5b90-4307-a153-1eb81f8a04eb.jpg)

**Comment by franticpsyx** [comment]
Hey all :) We've tracked the issue down to [this](https://github.com/woocommerce/woocommerce-admin/commit/643562121e4b9a6b016331a5993b638f84afccbf) change. I can see that we rely on the `ReportChart` component to implement the **Analytics > Composites** report. @xristos3490 is this something we can handle/anticipate on our end? Any ideas/suggestions on how we could make this change in `wc-admin` safer for those who extend the affected components?

**Comment by louwie17** [comment]
> Hey all :) We've tracked the issue down to [this](https://github.com/woocommerce/woocommerce-admin/commit/643562121e4b9a6b016331a5993b638f84afccbf) change. I can see that we rely on the `ReportChart` component to implement the **Analytics > Composites** report.

Thanks for doing some research into this issue @franticpsyx. I believe the error is directly related to the `getReportChartData` function as the structure for this changed (instead of passing the `select` function, we pass in the specific store selector functions). `ReportChart` is an internal component for us, so I assume the composite products plugin has a component with the same name?

> Any ideas/suggestions on how we could make this change in `wc-admin` safer for those who extend the affected components?

This should of been a place on our end where we make use of `depreciated` keeping the old format supported but showing a depreciated notice for it. Something we might still want to do, as there could be more plugins that use this.
cc @mattsherman @becdetat would the backwards compatibility with depreciated notice be worth adding in 2.6.3? It's related to the changes in the data package [here](https://github.com/woocommerce/woocommerce-admin/pull/7355/files).

**Comment by xristos3490** [comment]
Hey everyone!

Thanks @franticpsyx and @louwie17 for your insights on this! 

> `ReportChart` is an internal component for us, so I assume the composite products plugin has a component with the same name?

That's right! We do implement similar internal components _(e.g. `ReportChart`, `ReportTable`, `ReportError`, etc.)_ that are shared to all of our extensions. 

We could follow the data package changes introduced in this [PR](https://github.com/woocommerce/woocommerce-admin/pull/7355/files) and refactor the instance of `@wordpress/select` with the specific `@wordpress/select` response. 

Although, given that Composite Products should work with backwards compatibility in mind, i'm opting to leave the previous `select` param and introduce *one more* ( the `selector` ). Something like:
```js
const primaryData = getReportChartData( {
	endpoint,
	dataType: 'primary',
	query,
	// Hint: Leave this param for backwards compatibility WC-Admin lt 2.6.
	select,
	selector: reportStoreSelector,
	limitBy,
	filters,
	advancedFilters,
	defaultDateRange,
	fields,
} );
```
This way the data package (e.g. `getReportChartData`) will extract only what's needed -- depending on it's current version -- and move on. 

> would the backwards compatibility with depreciated notice be worth adding in 2.6.3? 

Deprecation notices seems like a good plan at first sight, but following the example above to handle previous WC and WC-admin versions, this would result to unnecessary deprecation notices.

Of course, if there's a better way to handle past versions i would love to discuss it further!
