### ISSUE TITLE
Inbox note: WCPay - Remind me later

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7670]
This note will be a reminder for users that view the Welcome screen in [#744](https://github.com/Automattic/wc-calypso-bridge/issues/744), then navigate away without installing WCPay.

Title: Save big with WooCommerce Payments
Content: Save up to 50% in fees by managing transactions in WooCommerce Payments. With WooCommerce Payments, you can securely accept major cards, Apple Pay, and payments in over 100 currencies.
Segmentation: Ecom and Business plan customers, Don't have WCPay installed, Haven't dismissed welcome screen
Timing: 3 days after viewing the WCPay welcome screen
Cadence: once
CTA leads to: Payments > Welcome screen
CTA label: Learn more

@pmcpinto I think this just needs the Tracks event for viewing the welcome screen. Also, feel free to add anything or edit the copy.

**Comment by ilyasfoo** [comment]
Hey @elizaan36, I have a couple of things for you to check to make sure we're on the same page:

1. Regarding note content, I'm assuming the correct text is "Save up to 50% in fees ..."
1. If the user has chosen to remove the welcome screen, the note should not show after 3 days

**Comment by elizaan36** [comment]
> Regarding note content, I'm assuming the correct text is "Save up to 50% in fees ..."

Yes, correct based on the changes discussed in the other issue.

> If the user has chosen to remove the welcome screen, should we still show the note?

No, we shouldn't show the note if the user has chosen to remove WCPay.

> WCPay in Core experiment is running for both Ecom and Biz plan users, but the note segmentation mentioned above is only for Ecom. Can you confirm if it should be both instead?

Yes, will be both.

I've updated the comment to reflect these changes. Thank you!
