### ISSUE TITLE
Wrong position of dismiss dropdown on Safari

### ISSUE THREAD

**Issue by leonardola** [woocommerce/woocommerce-admin#7672]
## Bug Description:
"Dismiss Message" popup appears misaligned on " Payments-> Overview" screen.

This bug has been fixed before in https://github.com/woocommerce/woocommerce-admin/pull/7278/files#diff-58e56c2da5e5510a46d6554511caf7a6f039428c49f6d052bcda89c8a00bf451R131

But reverted in https://github.com/woocommerce/woocommerce-admin/commit/2872f26bc70348abd2992f592cad7b1f232de020#diff-58e56c2da5e5510a46d6554511caf7a6f039428c49f6d052bcda89c8a00bf451L131

**The fix is to just add position: absolute; to .components-dropdown**

## Environment:
Woocommerce Version : WooCommerce 5.5.2
WooCommerce Payments - 2.9.0-test-1.

PC:
Mac 10.14.6
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site.
1. Install and activate all the required plugins.
1. Upload and activate the WooCommerce Payments v2.9.1 plugin. 
1. Complete the setup wizard.
1. Complete the KYC flow.
1. Go to Payments->Overview.
1. Click on "Dismiss" option on any of the inbox message.
1. Observe that "Dismiss Message" popup appears misaligned.

##Actual Result:
"Dismiss Message" popup appears misaligned on " Payments-> Overview" screen.

## Expected Result:
"Dismiss Message" popup should be properly aligned on " Payments-> Overview" screen.

## Video/Screenshot:

https://user-images.githubusercontent.com/41110392/128891612-a73398ab-e110-49c0-b066-ca333aaff0b5.mp4

![#2698_1](https://user-images.githubusercontent.com/41110392/128891623-ae91f5c6-0e83-4c83-9bbc-a102a6e9c654.png)

*Isolating the problem (mark completed items with an [x]):*
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by louwie17** [comment]
Hi @leonardola, thanks for creating both an issue and a fix right away for this issue.
I did some further digging and it appears this is not something in relation to our `woocommerce/experimental` package, but instead an issue within [woocommerce-payments](https://github.com/Automattic/woocommerce-payments), as you can see [here](https://github.com/Automattic/woocommerce-payments/blob/develop/webpack.config.js#L102-L103), they bundle their own version of `@wordpress/components`, which is actually [quite outdated - 11.1.5](https://github.com/Automattic/woocommerce-payments/blob/develop/package.json#L95) the latest is v17, updating wordpress/components on wc pay fixes the issue, but might also cause some other issues given the huge update.

I will transfer this issue over to the woocommerce-payments repo 🤞 (if that is possible, otherwise I will close it).

**Comment by louwie17** [comment]
@leonardola looks like I can't transfer it across another organization, are you able to re-create this issue in [woocommerce-payments](https://github.com/Automattic/woocommerce-payments)? 
The focus might have to change a bit to updating `wordpress/components`, or relying on the `wordpress/components` that is available under `window.wp.components` by [updating this](https://github.com/Automattic/woocommerce-payments/blob/develop/webpack.config.js#L102-L119).

**Comment by leonardola** [comment]
Hi @louwie17 the issue and PR created here were meant to fix an [issue](https://github.com/Automattic/woocommerce-payments/issues/2698) that already exists in woocommerce-payments. So no need to create another. I have not tried to update the wordpress-components. As the problem seemed to be introduced [here](https://github.com/woocommerce/woocommerce-admin/commit/2872f26bc70348abd2992f592cad7b1f232de020#diff-58e56c2da5e5510a46d6554511caf7a6f039428c49f6d052bcda89c8a00bf451L131). But I will try updating it and see how it goes.

**Comment by louwie17** [comment]
> Hi @louwie17 the issue and PR created here were meant to fix an [issue](https://github.com/Automattic/woocommerce-payments/issues/2698) that already exists in woocommerce-payments. So no need to create another. I have not tried to update the wordpress-components. As the problem seemed to be introduced [here](https://github.com/woocommerce/woocommerce-admin/commit/2872f26bc70348abd2992f592cad7b1f232de020#diff-58e56c2da5e5510a46d6554511caf7a6f039428c49f6d052bcda89c8a00bf451L131). But I will try updating it and see how it goes.

Thanks, yeah I would prefer not adding a fix within the package that was already fixed by a dependency update. You could always add the specific CSS on the woocommerce-payments side, making sure it is woocommerce-payment specific.
