### ISSUE TITLE
Add column total order value(per taxcode) in taxes section of analytics

### ISSUE THREAD

**Issue by John-belt** [woocommerce/woocommerce-admin#7674]
HI,
this is a small feature that kind of helps in tax filing. On the taxes section under analytics section, we have fields like taxcode, rate, total tax, shipping tax, Orders. Can we have total order amount(total sale) per tax code as well?? Yes this can be calculated from the rate and tax value but it would be nice addition to the whole report.

**Comment by mattsherman** [comment]
Hi @John-belt,

Thank you for taking the time to share this idea, we really appreciate your help. We’re going to add it to our backlog, where it will be considered for future releases.

**Comment by chihsuan** [comment]
I think this is relatively a low-impact task. Closing this for now. cc @pmcpinto
