### ISSUE TITLE
Marketing task: Activate button not working if extension is installed outside of task

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7690]
### Describe the bug
If an extension is installed outside the marketing task and not activated, the Activate button for that extension in the marketing task isn't working. There's no feedback or error when clicking on the action.

It could be a use case (not sure how common) to explore other areas and install marketing extensions prior to opening the marketing task. If the Activate action isn't working in the task it could be frustrating and users may not know how else to activate the extension.

### To Reproduce

1. Install the latest version of WCA with no other marketing plugins installed
2. Install MailPoet, Mailchimp, or Google Ads through the WP plugins area but don't activate them
3. Open the Marketing task from the home screen
4. Click activate and see error

### Expected behavior
If the extensions are installed in other locations, the Activate action should work via the marketing task.

**Comment by joshuatf** [comment]
Thanks, @elizaan36!  I'm able to reproduce this. 

Looks like the already installed functions are not being passed the required install/activate methods for plugins.  I'll put a fix out for this now.
