### ISSUE TITLE
Activity Panel Inbox: Allow for notes to be displayed to particular roles/caps or users

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#770]
An extension like WooCommerce Product Vendors would conceivably want to be able to show "New Sales Record" type notes to particular users (vendors). The note content would be driven only off of sales for that particular user (and, conversely, they should not see the global sales record note.)

Right now, all notes require manage_woocommerce capability (`get_items_permissions_check` https://github.com/woocommerce/wc-admin/blob/master/includes/api/class-wc-admin-rest-admin-notes-controller.php#L148 uses `wc_rest_check_manager_permissions` https://github.com/woocommerce/woocommerce/blob/b0b3ddccb0cf6964e2ff1c70b85dbd3b9764fa85/includes/wc-rest-functions.php#L340 )

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
