### ISSUE TITLE
Inbox notes: Complete store details, Edit store details

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7715]
This note will be a reminder for users to complete the store details (if the store profiler was skipped) or edit the store details if it was already filled out. **This only applies to the segment of users who are part of the task list UI experiment.**

[Skipped profiler]
Title: Add your store details to complete store setup
Content: Complete your store details with important information for setup such as your store's base address.
Segmentation: Users that have skipped the store profiler `wcadmin_storeprofiler_store_details_skip`
Timing: Immediately upon creating a new store
Cadence: once
CTA leads to: Launch store profiler on store details step
CTA label: Add store details

[Completed profiler]
Title: Edit your store details if you need to
Content: Nice work completing your store profile! You can always go back and edit the details you just shared, as needed.
Segmentation: Users that have completed the store profiler
Timing: Immediately upon creating a new store
Cadence: once
CTA leads to: Launch store profiler on store details step
CTA label: Update store details

@pmcpinto I think this just needs the Tracks event for skipping the store profiler. Also, feel free to add anything or edit the copy.

**Comment by pmcpinto** [comment]
> @pmcpinto I think this just needs the Tracks event for skipping the store profiler. Also, feel free to add anything or edit the copy.
Here's the event wcadmin_storeprofiler_store_details_skip
