### ISSUE TITLE
Improve discoverability of setting up other (non-WCPay) payment providers

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7720]
**Description:** users can easily miss the inbox notification informing them about other payments' solutions when we display the WCPayments task. We want to improve this by taking advantage of the "things to do next" task list

## Acceptance criteria
- If the WCPayments task is displayed, remove the `wc-admin-set-up-additional-payment-types` inbox message ([src](https://github.com/woocommerce/woocommerce-admin/blob/5eefe37ccd7bfbf39c96c72917c2f96f46e231ee/src/Notes/SetUpAdditionalPaymentTypes.php))
- If the WCPayments task is displayed, introduce a new "Set up additional payment providers" task in the "things to do next" task list.
    - This task should redirect users to the payments task.
    - Before WCPayments setup is complete, the task will direct users to the payment task screen with the WCPayments header card.
    - After WCPayments setup is complete, the task will direct users to the payment task screen with WCPayments enabled.
    - Upon completing the setup of Stripe or another payment provider, the user is directed back to the home screen with the task complete.
- When the user finishes the WCPayments setup, mark the WCPayments task as complete. Currently, we mark the "set up payments" task complete when this happens. The completed WCPayments task will direct users to the Payments Overview screen, as we're discouraging users to complete the KYC more than once.
- Do not show the WCPayments task currently shown in the extended task list after finishing the WCPayments setup.
    - This is being removed in https://github.com/Automattic/woocommerce-payments/issues/3060
- The "things to do next" list Tracks works properly (no new Tracks events or properties)

## Design

Before the WCPay setup is complete, the "Set up additional payment providers" task will direct users to the payment task screen with the WCPay header card.
![Screen Recording 11-22-2021 at 11 44 AM](https://user-images.githubusercontent.com/5121465/142910651-c78c25c8-589a-44a0-865e-0a1df11f285f.gif)

After WCPay setup is complete, the "Set up additional payment providers" task will direct users to the payment task screen with WCPay enabled. Upon completing setup of Stripe or another payment provider, the user is directed back to the home screen with the task complete.

![Screen Recording 11-22-2021 at 11 49 AM](https://user-images.githubusercontent.com/5121465/142910975-16b65fbd-6b07-419a-af27-dcc785cb47fe.gif)

## Dev tasks

- [ ] Remove the `wc-admin-set-up-additional-payment-types` inbox message if the WCPayments task is displayed
- [ ] Implement "Set up additional payment providers" task in the "things to do next" task list.

**Comment by pmcpinto** [comment]
@elizaan36 we can tweak the acceptance criteria once you have the designs ready. Thanks!

**Comment by elizaan36** [comment]
Updated the original comment with the design.

> Tweak the copy or remove the WCPayments task introduced in the extended task list after finishing the WCPayments setup. Decision TBD

Pretty sure @LevinMedia is removing the UPE task regardless. If not, we can revisit the copy.

**Comment by elizaan36** [comment]
The WCPay task in the extended task list is being removed in [#3060](https://github.com/Automattic/woocommerce-payments/issues/3060)

**Comment by mattsherman** [comment]
@pmcpinto @elizaan36 It is not clear what the flow is supposed to be for this change.

 https://github.com/Automattic/woocommerce-payments/issues/3060 seems to directly conflict with the second acceptance criteria

Can you please provide a Figma flow showing how things are supposed to work in the various scenarios?

**Comment by pmcpinto** [comment]
@mattsherman the TLDR is that we should replace the `wc-admin-set-up-additional-payment-types` inbox message with a new "things to do next" task. Let me know if you need further clarification. @elizaan36 maybe a rough mockup with the before and after can help.

**Comment by mattsherman** [comment]
I definitely need further clarification, and a mock-up or sketch of the flow would help.

**Comment by pmcpinto** [comment]
👍 let's wait until Elizabeth shares the flow

**Comment by elizaan36** [comment]
hey @mattsherman @pmcpinto here are details on the flow.

Before the WCPay setup is complete, the "Set up additional payment providers" task will direct users to the payment task screen with the WCPay header card.
![Screen Recording 11-22-2021 at 11 44 AM](https://user-images.githubusercontent.com/5121465/142910651-c78c25c8-589a-44a0-865e-0a1df11f285f.gif)

After WCPay setup is complete, the "Set up additional payment providers" task will direct users to the payment task screen with WCPay enabled. Upon completing setup of Stripe or another payment provider, the user is directed back to the home screen with the task complete.

![Screen Recording 11-22-2021 at 11 49 AM](https://user-images.githubusercontent.com/5121465/142910975-16b65fbd-6b07-419a-af27-dcc785cb47fe.gif)

**Comment by pmcpinto** [comment]
@mattsherman @joelclimbsthings we're thinking about running an a/b test with this change before releasing it to all users. We know that this change will eventually divert users from the WCPay setup flow, but it is impossible to know in advance the magnitude of its impact. Let me know what you think. Thanks!

**Comment by mattsherman** [comment]
> @mattsherman @joelclimbsthings we're thinking about running an a/b test with this change before releasing it to all users. We know that this change will eventually divert users from the WCPay setup flow, but it is impossible to know in advance the magnitude of its impact. Let me know what you think. Thanks!

@pmcpinto @joshuatf I missed this comment... sorry about that!

Hmm... Josh has made the change in #7980 without an experiment (as there was no experiment mentioned in the AC).

I wonder if it would be better to just run with the change and track the metrics to see if there is a significant drop. Since we are not removing the main WCPay task, and WCPay is still highlighted at the top of the additional payment providers screen if it isn't setup, I would think that the impact won't be significant. This feels like the sort of change that we should just make and observe.

Alternatively, we could create a followup PR to put the old behavior back, with an a/b test experiment. If you want that, @pmcpinto, please let us know.

**Comment by pmcpinto** [comment]
@mattsherman thanks for your feedback. To have a sense of the best way to mitigate the risks of this implementation:
- What's the effort required to implement the ab test?
- Can we easily roll back the changes if we release them to all users and the drop in the WCPay setup flow is higher than expected? I'm assuming that the biggest roadblock is complying with the Core release train.

**Comment by joshuatf** [comment]
cc @pmcpinto 

>What's the effort required to implement the ab test?

It's more than just modifying the existing task.  We'd probably need to create an additional task to house the logic instead of housing it in a single task.  This probably doubles the effort of the original task but I'm optimistic we could get it knocked out in a couple days for a beta 2 release if necessary.

But let me know sooner rather than later if possible so we can hit that goal in time.

**Comment by pmcpinto** [comment]
@joshuatf let's move forward without the a/b test. Thanks
