### ISSUE TITLE
Task list items cannot be expanded

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7729]
### Describe the bug
When the expandable experiment is added, the current task item is expanded, but others do not expand on click.

### To Reproduce

1. Set `isExpandable={ true }` in `client/tasks/tasks.tsx`
2. Load the task list
3. Click on other tasks

### Screenshots

<img width="726" alt="Screen Shot 2021-09-28 at 2 47 57 PM" src="https://user-images.githubusercontent.com/10561050/135147893-96f56a7b-e7fc-4064-9fe3-e7da87aa7bea.png">

### Expected behavior
Expected other task list items to expand on click.

**Comment by joshuatf** [comment]
Actually this seems to be working well on my end.  I didn't realize completed tasks could not be expanded.

Wouldn't mind a quick look from @louwie17 before we close this just to make sure all expandable issues are covered here.  Feel free to close this if so.

**Comment by louwie17** [comment]
> Wouldn't mind a quick look from @louwie17 before we close this just to make sure all expandable issues are covered here. Feel free to close this if so.

Correct they should not be expanded, see the requirements of the original issue - https://github.com/woocommerce/woocommerce-admin/issues/6774
