### ISSUE TITLE
Clean up old usage of task list options

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7751]
There are several areas around the app where we still make use of the old task list options.  We should instead rely on the API and data store as the source of truth for task list status.

* `woocommerce_task_list_hidden`
* `woocommerce_extended_task_list_hidden`
* `woocommerce_task_list_complete`
* `woocommerce_task_list_dismissed_tasks`

**Comment by strarsis** [comment]
+1, this also causes the normal WooCommerce status widget to disappear and an empty WooCommerce Setup widget is shown instead.

`woocommerce_task_list_hidden` is updated by WooCommerce Admin plugin, too.
But the WooCommerce plugin doesn't "heal" inconsistent `woocommerce_task_list_hidden option values on its own.

Related issue: https://github.com/woocommerce/woocommerce/issues/30347#issuecomment-956274027
