### ISSUE TITLE
method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given

### ISSUE THREAD

**Issue by davilera** [woocommerce/woocommerce-admin#7758]
### Describe the bug
Several users reported a bug that results in a fatal error when using WooCommerce with certain third-party plugins/themes:

* [Critical error thrown when trying to run the setup wizard](https://wordpress.org/support/topic/critical-error-thrown-when-trying-to-run-the-setup-wizard-2/)
* https://github.com/woocommerce/woocommerce/issues/30149 by @reardestani

This is the culprit:

```
An error like E_ERROR on line 359 from file …/woocommerce/packages/woocommerce-admin/src/PageController.php.
Error message: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given in …/woocommerce/packages/woocommerce-admin/src/PageController.php:359
```

### Actual behavior:
There's a fatal error.

### Expected behavior
The third-party plugin/theme should work as expected.

### To Reproduce
https://github.com/woocommerce/woocommerce/issues/30149 provided the steps to reproduce the issue with a premium theme (Jupiter). Unfortunately, the issue was dismissed because it seemed "to be caused by the 3rd party theme Jupiter" and not WooCommerce itself. However, I disagree.

If you [look at the source code](https://github.com/woocommerce/woocommerce-admin/blob/66603e6c34c9d2844e8a87abbb26efa7a29437a8/src/PageController.php#L357), you'll see the following:

```php
// Disable embed on the block editor.
$current_screen = did_action( 'current_screen' ) ? get_current_screen() : false;
if ( method_exists( $current_screen, 'is_block_editor' ) && $current_screen->is_block_editor() ) {
```

Clearly, `$current_screen` can be `false`, which means it's possible `method_exists` ends up being called with a `bool` value. When this occurs (and it does occur, albeit so far we've only identified this when used with third-party plugins/themes), a fatal error occurs.

### Proposed Solution

An extra check is required in the `if` statement. Something along the lines:

```php
if (
  ! empty( $current_screen ) &&
  method_exists( $current_screen, 'is_block_editor' ) &&
  $current_screen->is_block_editor()
) {
```

or:

```php
if (
  empty( $current_screen ) ||
  ( method_exists( $current_screen, 'is_block_editor' ) && $current_screen->is_block_editor() )
) {
```

I don't know for sure which one it is... but we can't call `method_exists` with a `bool`.

**Comment by ilyasfoo** [comment]
Hi there, @davilera. Thank you for reporting this issue! Your assessment is correct, this is indeed a bug since PHP 8 changed the way `method_exists` behaves as it now throws a fatal error on passing the first parameter with anything other than string or object. We should fix this to properly support PHP 8.

Additionally, I wonder if it's worth considering adding safety checks for other `method_exists` calls in this repo that pass dynamic variables for its first parameter such as [this](https://github.com/woocommerce/woocommerce-admin/blob/bf47959171558eeae55428960dceb0506203c44d/src/Schedulers/SchedulerTraits.php#L279).
