### ISSUE TITLE
Exporting address viewing WooCommerce > Customers

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-admin#7766]
### Is your feature request related to a problem? Please describe.
This is a feature request coming in via chat.

### Describe the solution you'd like
> I am looking to export customer details based on their last purchase date. 

>When you go to WooCommerce > Customers you can gather all the data and export it via CSV, the only limitation is that this list only generates the region, country and postcode. I however need the address line 1 & 2 aswell. 

>How easy would this be to implement? And do you have any documentation on it?
### Describe alternatives you've considered
Besides us implementing this ourselves, can we provide developer docs or examples on how to do this?

![https://d.pr/i/jLgqel](https://d.pr/i/jLgqel+)
Image link: https://d.pr/i/jLgqel

**Comment by ilyasfoo** [comment]
Hi there, @ryanr14. Unfortunately we don't have the documentation for this specific customization. We do have a filter that's able to modify the columns of exported CSV **but it only applies to the email version of export**.  Here's an example plugin that may be able to help: https://gist.github.com/becdetat/0de2f79672e768f4e72b43d7ab07e2e3.

The client-sided export isn't supported yet, there's open ticket for it [here](https://github.com/woocommerce/woocommerce-admin/issues/5688).

Hope that helps!
