### ISSUE TITLE
WC - Stuck on store Dashboard

### ISSUE THREAD

**Issue by kiritodragneel** [woocommerce/woocommerce-admin#7778]
On the latest version of WC if I activate the plugin I get stuck on the store dashboard, I can't got to any other page in the admin area of my website it just auto reloads to store dashboard. 

I can access the main site and navigate that fine but the admin area does not allow me to go anywhere else, even if i go direct to URL in a new window. 

I have also tried deactivating ALL plugins bare WC and the problem still exists 

Plugins active outside of WC are:  
- Branda Pro
- Defender Pro
- Forminator Pro
- Give - Donation Plugin
- Hummingbird Pro
- Oxygen 3.9 Beta 1
- Oxygen Gutenberg
- Oxygen Elements for WooCommerce 
- Recoda Worksplace for Oxygen
- Shipper Pro
- SmarCrawl Pro
- Smush Pro
- Snapshop Pro
- WPMU Dev Dashboard

**Comment by ilyasfoo** [comment]
Hi @kiritodragneel, thank you for reporting this issue. I haven't heard of this kind of problem before, does it still happen if you tried to install back the previous version of WooCommerce? Also, if you can copy and paste any error messages either in the browser console or WordPress log, would greatly help. Please remember to omit any confidential information if you decide to share anything.

If you can come back to us with a reliable way to reproduce, we'll gladly investigate this issue further. Thanks!
