### ISSUE TITLE
Refactor `next_week_start` logic to avoid while loops

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#7779]
### Describe the bug

This issue is a follow-up to https://github.com/woocommerce/woocommerce-admin/pull/7763. Currently, it uses a loop block that has a failsafe to prevent an infinite loop. This isn't ideal since the failsafe isn't a proper solution, it'll return a wrong result instead.

https://github.com/woocommerce/woocommerce-admin/blob/64782446712d32abe20414433d8f51077d9d5c74/src/API/Reports/TimeInterval.php#L331-L337

The ideal fix should avoid using while loops and possibly use date calculations instead. Unit tests are available for `next_week_start` which should help with confirming a potential solution working as it should be.

**Comment by joshuatf** [comment]
Agreed that this is not the best solution here and we should strive to clean this up.
