### ISSUE TITLE
[Setup Wizard] - Country/Region label alignment is off after country is selected

### ISSUE THREAD

**Issue by lanej0** [woocommerce/woocommerce-admin#7786]
### Describe the bug
After a country/region has been selected, the label for the field has too much left padding and is out of alignment with the value selected.

### To Reproduce

1. Go to /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard
2. Click on 'Country/Region' and select an option

### Actual behavior:
The left padding remains on the field label, throwing off the alignment (see screenshots)

### Screenshots

Before:

![Screen Shot 2021-10-11 at 1 53 09 PM](https://user-images.githubusercontent.com/80276/136854506-3837c90b-afc8-4a88-afad-dde30a42f939.png)

After:

![Screen Shot 2021-10-11 at 1 53 19 PM](https://user-images.githubusercontent.com/80276/136854550-20d731d2-b383-42ce-b746-e82531fb9314.png)

### Expected behavior

It appears that there is some padding/margin to the left of the field label in order to create space between it and the search icon.  Once a value is set, the value seems to have less padding than the label.  The two should be aligned on the left edge.

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome, Safari, Firefox
* Version: 94, 15.1, 82

**Comment by lanej0** [comment]
Still present in 5.8

**Comment by johnregan3** [comment]
Just to confirm: are these two assumptions correct?

1. Using the screenshot above, "Country / Region" should align with "Afghanistan" (not all the way to the left as with the other inputs)
2. Although not noted in the original issue, the vertical space between the label and text should also be the same as the other inputs

![Screen Shot 2021-12-01 at 10 49 30 AM](https://user-images.githubusercontent.com/2053940/144278088-a47aa239-85c0-4614-9292-72757a8d897e.png)

**Comment by lanej0** [comment]
@johnregan3 I think that your assumptions are correct.  I think aligning the label with the box would look funny.  The other possibility I could think of would be to have the search icon go away once a value is set, and have the label/value pair look just like all other text inputs.

**Comment by joshuatf** [comment]
@elizaan36 do you have any opinions on removing the search icon when a value exists?

**Comment by elizaan36** [comment]
Thanks for bringing this up @lanej0 ! 💜 The label should definitely be left aligned with the input.

> @elizaan36 do you have any opinions on removing the search icon when a value exists?

I like the search icon because it may prompt users to start typing (rather than doom scrolling through the endless list) 😆
I'd actually add left padding to the input (rather than removing it from the label) so that there's some breathing room from the search icon.

![Frame 2356](https://user-images.githubusercontent.com/5121465/145881978-0be3ec7c-fa10-4682-b94e-9f3f09ca6e69.png)
