### ISSUE TITLE
Inbox 2.0 Layouts

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7792]
### Requirements

- Adapts to each layouts: Inbox menu, Mobile, 1-column, 2-columns.

**Comment by moon0326** [comment]
Just tested all layouts with https://github.com/woocommerce/woocommerce-admin/pull/7864 and it looked good.

I think we don't need any changes for this issue.

**Comment by adrianduffell** [comment]
Thanks @moon0326 I'll close this out.
