### ISSUE TITLE
Inbox 2.0 Read State

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7793]
### Requirements

- Update the note state to "read" after action button clicked on.
- Remove previous functionality making notes read upon homepage view.

**Comment by moon0326** [comment]
@adrianduffell I'm a bit confused about `read` state.

Looking at this [line](https://github.com/woocommerce/woocommerce-admin/blob/main/client/inbox-panel/index.js#L167), we have a global timestamp for the `last_read` state.

It looks like we don't have a `read` state for each note. 

Since we want to set `read` state if the action button is clicked, I think we can re-purpose `status` column from the `wp_wc_admin_notes`. What do you think?

**Comment by adrianduffell** [comment]
> Since we want to set read state if the action button is clicked, I think we can re-purpose status column from the wp_wc_admin_notes. What do you think?

@moon0326 This sounds good. Would it be best to add a new `read` status value, or do you think using the existing statuses is possible?

**Comment by moon0326** [comment]
> > Since we want to set read state if the action button is clicked, I think we can re-purpose status column from the wp_wc_admin_notes. What do you think?
> 
> @moon0326 This sounds good. Would it be best to add a new `read` status value, or do you think using the existing statuses is possible?

I'm trying to see if we can use `actioned` and `unactioned`, but I'm a bit puzzled on how the value gets updated at the moment. I'll share what I find.

**Comment by moon0326** [comment]
@adrianduffell After looking at the code and how notes are considered `actioned`, I think `status` column isn't ideal to track the read state. Some notes are considered `actioned` once the CTA button is clicked, but some are not.

I think we have two options.

1. Add a new column to `wp_wc_admin_note_actions` table to track the `click` count. Column name could be `cta_btn_click_count`
2. Use an option to track a list of clicked notes.

I prefer option #1.

What do you think?

**Comment by adrianduffell** [comment]
Thanks for investigating this @moon0326 

I prefer adding a new column (option 1) as well. Is there a benefit to keeping track of the click count vs having a column like `is_read`, and updating the value to `true` when a CTA button is clicked?

I'm just not sure about sites that have opted out of tracking, where keeping a click count might go against their expectations.

**Comment by moon0326** [comment]
> I'm just not sure about sites that have opted out of tracking, where keeping a click count might go against their expectations.

That's a good insight 👍  I totally agree.

I thought we could possibly use the click count to find a note that users might have a problem with. Clicking a note CTA multiple times and not finishing might indicate a problem. 

I think `is_read` is a perfect naming for the purpose.
