### ISSUE TITLE
Marketing task - change Google Ads copy

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7796]
### Describe the bug
In the marketing task, we're installing the right Google Ads extension (Google Listings and Ads by Woo), but the copy presented is about other Google Ads extension we were promoting before our extension was created. 

### To Reproduce

1. Create a new store and go to the home screen
2. Click on the marketing task
3. See that the copy refers to the Google extension managed by Kliken
4. Click "get started" and confirm that we're installing the right extension: Google Listings and Ads by Woo

### Actual behavior:
We're showing the copy about the wrong Google Ads extension

### Screenshots
Screenshot here: https://d.pr/i/cVkeCO

### Expected behavior
Display the right copy about Google Listing and Ads:
Google Listings & Ads
Reach more shoppers and drive sales for your store. Integrate with Google to list your products for free and launch paid ad campaigns.

**Comment by mattsherman** [comment]
@woocommerce/mothra We should fix this ASAP as follows:

- Update remote endpoint to correct text
- Update local fallback to correct text and cherry-pick it into 2.8
