### ISSUE TITLE
Provide a new API for consumers affected by settings breaking change

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7802]
In WooCommerce 5.8.0 we shipped a breaking change in WC Admin:

> While we try to deliver releases that are free from breaking changes, it is worth highlighting a _potential_ breaking change within the WooCommerce Admin package, stemming from the removal of a [number of settings](https://github.com/woocommerce/woocommerce/blob/5.8.0/changelog.txt#L43) from the `wc_admin` namespace within the `wc/data` store. This _may_ impact some third party code that aims to integrate with WooCommerce Admin.

So far this is known to impact the `Google Listing and Ads` and `Pinterest for WooCommerce` extensions (see issue https://github.com/woocommerce/woocommerce-admin/issues/7781).

We should provide a future proof API for consumers to continue accessing the affected data.

**Comment by tomalec** [comment]
Is there any quick solution for the `woocommerceTranslation` setting?
The workaround of `window.wc.wcSettings.getSetting('woocommerceTranslation')` does sometimes return `false`. See https://github.com/woocommerce/pinterest-for-woocommerce/pull/224, https://github.com/woocommerce/google-listings-and-ads/pull/1042/files#diff-3aa09978cb18aff029d3dd6535a2b9ee0a8c4df561ceae68517deb6bac6ffa7aR25
