### ISSUE TITLE
Wordpress analytics reports doesn't translate the months

### ISSUE THREAD

**Issue by caiodigioia** [woocommerce/woocommerce-admin#7827]
Woocommerce is set to Portuguese (Brazil), but, on the chart, the months and the data format still in English.

![image](https://user-images.githubusercontent.com/81108520/137633436-da40d101-e70e-4ff7-b2d0-c675ff174d30.png)

Although they weren't translated by default, the other texts (e.g "Mês até hoje") I managed to translate using Loco Translate, but this was not possible in the chart.

Many thanks in advance!
Best regards!

**Comment by caiodigioia** [comment]
Hello...?

**Comment by moon0326** [comment]
Thank you @caiodigioia for taking the time to report this issue. I was able to reproduce it on my end. We'll work on it as soon as possible.

**Comment by caiodigioia** [comment]
Hey, @moon0326 !
Do you have news about the issue?

**Comment by caiodigioia** [comment]
Hello...?

**Comment by chihsuan** [comment]
The root cause is that we use `d3.timeFormat` to format the date string and we don't load d3 locale files. If we keep using `d3.timeFormat`, we need to load its locales. I think the best way to fix this is we use `@wordpress/date` or `moment` to handle this instead.
