### ISSUE TITLE
Taxes report is not displaying the exact amount.

### ISSUE THREAD

**Issue by lenamtl** [woocommerce/woocommerce-admin#7828]
Hi,

I'm having an issue with the taxes reports it not dislaying the correct amount compared to what is charged to clients.
I’m refering to this page page=wc-admin&path=%2Fanalytics%2Ftaxes
I don't know how come the records are not the same maybe this is a format issue.

**Report data:**
TVQ 174,23
TPS 87,33

**DB data** from wc_order_tax_lookup (this is corresponding to the Report)
TVQ 174,226346
TPS 87,3315

**Real Data from order page** (this is different from Report and DB)
**Real amount charged to customer** (this has been check 4 times to make sure there is no error)
TVQ 174,25
TPS 87,44

I know this is not big error but the store owner need the exact data.

So what can I do to get a report based on what was really charged to the customers.
Maybe woocommerce should save the exact taxes amount charged (rounded) in another table
I cannot do manual copy paste from each order page this is not making sense....

Any help is welcome, I don’t mind to make a PHP script, plugin, excel sheet or any other solution
I need a fix asap.

*Note the way it calculate the taxes on the order page seems good I made a few spot check.

**Comment by lenamtl** [comment]
Ok thanks, I was not aware...

**Comment by jacob-sewell** [comment]
Hello, @lenamtl. Thanks again for bringing this to our attention!

So far we have not been able to reproduce this behavior in our testing. Can you provide any details that might be helpful in reproducing the issue? (A dump of some relevant rows from `wp_wc_order_tax_lookup` and `wp_wc_order_stats`, and maybe the specifications for the TVQ and TPS tax rates seem like a reasonable place to start.)

**Comment by lenamtl** [comment]
Any news about this?
