### ISSUE TITLE
Store profiler: business details step - add number of employees field

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7854]
**Description:** most countries and organizations use headcount to categorize a business: micro, small, mid-size, etc. We want to start collecting this information about our users as we plan to use it to segment our user base in combination with other data points we're collecting. 

## Acceptance criteria
- In the Company Details step, if the user selects that they are selling elsewhere (any option other than "No"), display a new drop-down list with the following options:
How many employees do you have?
It's just me
<10
10-50 
50-250
+250
I'd rather not say
- This field should be displayed above the annual revenue field
- Update the `wcadmin_storeprofiler_store_business_details_continue_variant` Tracks event with a new prop:
`number_employees`
    - Values: "1", "<10", "10-50", "50-250", "+250", "not specified"

## Dev tasks

- [ ] Add the number of employees field to he Company Details step of the store profiler (OBW)
- [ ] Set the `number_employees` prop on the `wcadmin_store_profiler_store_business_details_continue_variant` Tracks event

**Comment by mattsherman** [comment]
Buckets seem like the way to go to me.

**Comment by pmcpinto** [comment]
Thanks for the feedback! Let's move forward with the buckets :)

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7854?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro
