### ISSUE TITLE
WCPay intl expansion: include new EU countries

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7862]
**Description:** WCPayments was launched today to more European countries: AT, BE, PT, PL, NL, CH. We need to start including WCPay in the setup flow of stores located in these geos. 

**Acceptance criteria:**

- [ ] Add AT, BE, PT, PL, NL, CH to the list of countries covered by the wccom remote config file. Ideally early next week
- [ ] Add AT, BE, PT, PL, NL, CH to the Core fallback option. Ideally in the next WC Core release

**Comment by pmcpinto** [comment]
@louwie17 has this already been updated in the wccom remote config file?

**Comment by louwie17** [comment]
@pmcpinto not yet, I will re-open this for now until that is merged.
