### ISSUE TITLE
Dismiss note immediately upon clicking 'dismiss' without prompting a popup

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#7867]
![Screen Shot 2021-10-28 at 6 15 52 PM](https://user-images.githubusercontent.com/4723145/139357259-1d93cfb6-2f63-45c8-8033-40b51e24e933.jpg)

1. Remove the dismiss popup when a user clicks "Dismiss" on a note
2. The note should be dismissed immediately without prompting the popup

**Comment by ilyasfoo** [comment]
Should we close this?

**Comment by adrianduffell** [comment]
Completed in https://github.com/woocommerce/woocommerce-admin/pull/7868
