### ISSUE TITLE
Repair WCPay Tracks event(s) in payment gateway setup

### ISSUE THREAD

**Issue by joelclimbsthings** [woocommerce/woocommerce-admin#7881]
The tracks event `wcadmin_tasklist_payment_setup` has failed to fire for WCPay since the switch over to remote payment gateways. For more background information you can see https://github.com/woocommerce/woocommerce-admin/issues/7836

## Tasks
- [ ]  Add `wcadmin_tasklist_payment_setup` to WCPay component, and ensure it's firing properly.

**Comment by pmcpinto** [comment]
@joelclimbsthings is it possible to implement this change in cycle 20?

**Comment by joelclimbsthings** [comment]
Shouldn't be a problem; perhaps we should bring in @mattsherman as well to confirm.

**Comment by mattsherman** [comment]
I think that is doable... I'll add this to our Cycle 20 backlog.
