### ISSUE TITLE
WooCommerce API calls needlessly call append_product_data in Onboarding.php

### ISSUE THREAD

**Issue by mtg169** [woocommerce/woocommerce-admin#7884]
### Describe the bug

Making WooCommerce API calls needlessly calls Onboarding::append_product_data every single API request. On certain sites where PRODUCT_DATA_TRANSIENT (wc_onboarding_product_data) does not exist, this also needlessly calls `wp_remote_get( 'https://woocommerce.com/wp-json/wccom-extensions/1.0/search' );` slowing down API calls and making an unnecessary and completely unrelated request for WooCommerce extensions. I have one client site where wc_onboarding_product_data is never set for some reason and repeatedly makes this unnecessary extensions search. I had to comment it out of Onboarding.php in order for their inventory updates to properly work.

### To Reproduce

1) Install WordPress with nothing else other than WooCommerce plugin
2) Keep on default Twenty Twenty-One theme
3) Create API key in WooCommerce
4) Create API request to /wp-json/wc/v3/products 

### Actual behavior:

Onboarding::append_product_data is called. If wc_onboarding_product_data is not set, a request is also made to https://woocommerce.com/wp-json/wccom-extensions/1.0/search

### Expected behavior

API endpoints should only make minimal and necessary function calls and return related data.

**Comment by moon0326** [comment]
Thank you @mtg169 for taking the time to test and report this issue. I was able to reproduce it on my end.

cc @woocommerce/mothra for further investigation.
