### ISSUE TITLE
[Setup Wizard] - Merchant is seeing two different currency type at two different pages of setup wizard.

### ISSUE THREAD

**Issue by raj007champ** [woocommerce/woocommerce-admin#7889]
### Describe the bug
When the user is navigated to the WooCommerce Setup Wizard flow and is on the Store Profiler page, There is no option to take preferred currency from the Merchant, Due to this issue, the merchant is seeing two different currencies at two different pages of the setup wizard flow. 
1. User is seeing prices in US dollars on the `What type of products will be listed?` page.
2. Again user is seeing the price in local currency on the `Tell us about your business page under What's your current annual revenue?` input field.

### To Reproduce

1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open
3. Navigate to the Product Types page and check for prices for paid option present on the page and notice that it is in US dollars.
4. Click on continue and navigate to the Business Details page and check for the `What's your current annual revenue?` field and notice the currency displayed in options.

### Actual behavior:
There is no option to take preferred currency from the Merchant at the start, Due to this issue, the merchant is seeing two different currencies at two different pages of the setup wizard flow. 

### Screenshots

https://user-images.githubusercontent.com/19307354/140172821-6bd47ce4-e682-4637-a068-e3c2ac6814b8.mp4

### Expected behavior
While setting up the store for the user, We should take the preferred currency from the user on the **Store Profiler page** itself so that we can show the consistent currency type for upcoming pages.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

**Comment by moon0326** [comment]
Thank you @raj007champ for taking the time to test and report this issue. I was able to reproduce it on my end. We'll work on it as soon as possible.

**Comment by joshuatf** [comment]
This is related to woocommerce/woocommerce#32230

For context, the annual revenues in the business details are rough ranges between the most commonly used currencies and converted locally.  The product types prices are pulled directly from WooCommerce.com and will need to be handled on that end to resolve this.

Unless we plan to remove the currency conversion from the business details step, I think we should close this issue and handle in woocommerce/woocommerce#32230.  Any thoughts @moon0326 ?

**Comment by chihsuan** [comment]
> Unless we plan to remove the currency conversion from the business details step, I think we should close this issue and handle in woocommerce/woocommerce#32230. Any thoughts @moon0326 ?

 Agreed on closing this issue and handling it in woocommerce/woocommerce#32230. Please feel free to reopen this if having other thoughts.
