### ISSUE TITLE
[Setup Wizard] User is allowed to make changes for their selected item or input fields but those changes are not getting saved.

### ISSUE THREAD

**Issue by raj007champ** [woocommerce/woocommerce-admin#7890]
### Describe the bug
In WooCommerce Setup Wizard flow user is allowed to move back to different sections of wizard flow (like Store Details, Industry, Product Types, Business Details and Theme) by clicking on those sections present at the top. Now once the user is on a particular section, He/She is allowed to make changes for their previously selected item or input fields but those changes are not getting saved if he moves back again to a different section by clicking on those sections present at the top.

### To Reproduce

1.  Install the WooCommerce plugin.
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open.
3. Complete the WooCommerce Setup Wizard flow by putting any values to the input field and selecting any options present on different pages.
4. Once the user is on the select theme section of the flow, Now again move back store details section by clicking the link present on top, Once the user is on the Store details section try to make some changes in the input fields like city, address, email etc. After making the changes move back to the theme section of the flow.
5. Once the user is back on the theme section, Now again move to the store details section of the flow by clicking the link present on the top and check whether user changes are saved or not which the user did in step-4.

**This issue is also reproducible if user moves back and forward using browser back and forward button.**

### Actual behavior:
Currently, the user is allowed to make changes on different sections of the wizard flow and those changes are not getting saved if he moves back to a different section of the setup flow.

### Screenshots

https://user-images.githubusercontent.com/19307354/140176932-94b7e9a6-3745-419f-aac2-ffebcbb95524.mp4

### Expected behavior
Either the user should not be allowed to make changes to existing fields or we should inform the user that the currently made changes are not saved when he tries to move to any other section of the page.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome 
* Version: 95.0.4638.69

**Comment by moon0326** [comment]
Thank you @raj007champ for taking the time to report this issue. I was able to reproduce it on my end.

We'll work on it as soon as possible.

**Comment by joshuatf** [comment]
I have mixed feelings on the expectations here.  I'm not entirely sure that navigating to a different tab without clicking "Continue" would warrant a save, but I could be wrong.

cc @elizaan36 @pmcpinto for your thoughts.

**Comment by pmcpinto** [comment]
> I'm not entirely sure that navigating to a different tab without clicking "Continue" would warrant a save

Yep. I have the same feeling. @elizaan36 @jarekmorawski what do you think?

**Comment by jarekmorawski** [comment]
Interesting. Can we save changes automatically? I believe that "Continue" isn't supposed to be a submit button, but a guidance that creates a scaffolding for the experience and gives people a sense of progress. Ideally, the changes would be saved automatically in the background and submitted at the last step of the profiler.

**Comment by elizaan36** [comment]
Agree with Josh on this one. I don't think the expectation will be that the form will save automatically, but it feels like what's missing is a warning that any changes made will be lost when using the stepper to navigate.

So if the merchant has made any changes to the step then tries to navigate away via the stepper without clicking "Continue", the warning modal would appear. If no changes are made to the form then no warning is necessary.

**Comment by jarekmorawski** [comment]
> So if the merchant has made any changes to the step then tries to navigate away via the stepper without clicking "Continue", the warning modal would appear. If no changes are made to the form then no warning is necessary.

Something like this, maybe?

![image](https://user-images.githubusercontent.com/79307566/147644854-41505640-483c-436c-a14b-e40bc79ded25.png)

If it was a warning asking them to save changes, people could fall into an endless feedback loop when they wanted to go to a preview step, but in order to save changes, they clicked `Continue` and went to the next step instead. In this version they can save or discard changes within the modal and continue switching to a different step.

Let me know if you have any thoughts!

**Comment by pmcpinto** [comment]
The modal would appear at any step where the user changes something, correct?

**Comment by jarekmorawski** [comment]
Yes. If I changed the contents of any field at the current step and proceeded to the next one, we'd show the modal. The only exception would be the "Continue" button, which would automatically save changes and take people to the next step.
