### ISSUE TITLE
[Setup Wizard] - Label for Country/Region input field present on Store Profiler page is distorted on Chrome browser (Windows 10)

### ISSUE THREAD

**Issue by raj007champ** [woocommerce/woocommerce-admin#7893]
### Describe the bug
Label for Country/Region input field present on Store Profiler page is distorted on Chrome browser (Windows 10), And it remains distorted at different zoom levels such as 70%, 90%, 100%, 120%, 150%.

### To Reproduce

1. Install chrome browser on Windows 10 OS.
2. Install WooCommerce plugin on WordPress
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open
3. Check the Label for the Country/Region input field present on the Store Profiler page at various zoom levels such as 70%, 90%, 100%, 120%, 150%.

### Actual behaviour:
Label for Country/Region input field present on Store Profiler page is distorted on Chrome browser

### Screenshots

https://user-images.githubusercontent.com/19307354/140181854-a2907bcc-52eb-4989-9620-9a603fd40504.mp4

### Expected behavior
Label for Country/Region input field present on Store Profiler page should not be distorted on Chrome browser

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

### Additional context
- This issue is specific to Chrome browser only.

**Comment by moon0326** [comment]
Thank you @raj007champ for taking the time to report this issue. I was able to reproduce it on my end.

It looks like `overflow: hidden` is the culprit. Disabling `overflow: hidden` fixes the problem. We'll look into it further soon.

![Screen Shot 2021-11-04 at 4 19 11 PM](https://user-images.githubusercontent.com/4723145/140433490-ea4fa096-6a8b-4aa7-b8a4-00614301adbe.jpg)
.
