### ISSUE TITLE
[Setup Wizard]- 'What is the platform name?' input fields present on the Business details page allow white space as valid input.

### ISSUE THREAD

**Issue by raj007champ** [woocommerce/woocommerce-admin#7907]
### Describe the bug
'What is the platform name?' input fields present on the Business Details page of Setup Wizard flow for white space as valid input, allowing a user to bypass required fields.

### To Reproduce
1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open.
3. Navigate to the Business details page.
4. Select `other `as an option for 'Which platform is the store using?' field.
5. Enter a white space into the required field and attempt to submit the form again.
6. Note that it allows you to submit the form without adding in the required fields.

### Actual behavior:
'What is the platform name?' input fields present on the Business details page allow white space as valid input.

### Screenshots

https://user-images.githubusercontent.com/19307354/140620534-2e559a56-663c-4f48-bf1c-87764c7de295.mp4

### Expected behavior
Required fields should still require some valid input before allowing the user to continue.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

**Comment by joelclimbsthings** [comment]
Thanks @raj007champ , confirmed that this is an issue.
