### ISSUE TITLE
Add meta property to admin notes for client-side filtering

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#7915]
### Is your feature request related to a problem? Please describe.
Currently there is no way to filter particular notes on the client side that shouldn't be displayed in specific clients. For example, the note promoting the mobile app should not be displayed when using the mobile app.

### Describe the solution you'd like
The addition of a `meta` property allowing the storage of arbitrary metadata about an admin note. For the example of the mobile app, the `meta` property might contain the following:

```
{
    'hide_on_mobile_app': true
}
```

### Describe alternatives you've considered
Extending remote inbox notification rules is not appropriate as they are processed on the server and only work as a filter for whether to push the note to the database or not. The scenario described has the note already in the database, it just needs to be filtered differently under different circumstances.

## Open issues

- Are these remote (wccom) or local? Or both?
    - Tentative answer (need to confirm): this should handle any note returned from the `/wc-analytics/admin/notes/` endpoint ()
- Are there any existing notes that need to be updated?

## Dev tasks (tentative)

- [ ] Update the `/wc-analytics/admin/notes/` endpoint handling to accommodate the `meta` properties

## References

- P2 discussion thread about filtering notes for mobile clients: pbIJXs-12m-p2#comment-2987

**Comment by mattsherman** [comment]
Notes:

- Are these wccom or local? Or both?
- Note: will still be shown until client is updated
- Note: we should have consistency for the "meta" information in various specs (have "additional data" and "additional info" in tasks)

**Comment by pmcpinto** [comment]
Will this change be included in the Inbox updates implemented by Ghidorah? @adrianduffell

**Comment by adrianduffell** [comment]
cc @mattsherman

@pmcpinto Mothra took this issue as we didn't have the resources to include it with the Inbox 2.0 work this cycle.

**Comment by mattsherman** [comment]
> cc @mattsherman
> 
> @pmcpinto Mothra took this issue as we didn't have the resources to include it with the Inbox 2.0 work this cycle.

Yes, we took this issue and aim to have it included in WCA 3.1.0 (the cutoff for WCA was too soon to the cycle start for us to get this in).

**Comment by joshuatf** [comment]
@becdetat I'm working on adding the meta property, but I stumbled across the `content_data` property in notes.

It seems this was originally intended as some form of localization helper, but is being used to store meta information about the note.  Is there any reason not to rely on that property?

**Comment by mattsherman** [comment]
@joshuatf Interesting about the `content_data` property. I would say that if it is already being used to story meta informatino about the note that gets passed on to the client, then we could definitely use it for this case.

**Comment by becdetat** [comment]
@joshuatf I agree, `content_data` looks ideal for this.

It would just need to be supported in remote inbox notifications and available client-side.
