### ISSUE TITLE
Track when WCPay is installed in product types step of store profiler

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7916]
**Description:** currently, we're not directly tracking when users install WCPay in the product types step (work implemented in #7445). We have `wcadmin_storeprofiler_store_product_type_continue` `product_type` : `subscriptions` to track this selection. However, this has some shortcomings: we were using this prop and value to track when users selected the subscriptions paid extension and we’re still using it to track the subscriptions paid extension among non-US users. We need to introduce a new prop to have an accurate view of the number of users installing the extension in this step.

## Acceptance criteria:

- `wcadmin_storeprofiler_store_product_type_continue` Tracks event has new prop set
    -  `wcpay_installed`: true | false

## Dev tasks

- [ ] Set `wcpay_installed` prop on `wcadmin_storeprofiler_store_product_type_continue` Tracks event

**Comment by pmcpinto** [comment]
@becdetat  @mattsherman we have to include this in cycle 19. Let me know if you have questions. Thanks!

**Comment by becdetat** [comment]
@pmcpinto Ok, I've put it in to scope for C19

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7916?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro

**Comment by pmcpinto** [comment]
@octaedro In which wc admin version will this be included? I'm not finding it in the 3.0 and 3.1 changelog

**Comment by becdetat** [comment]
@pmcpinto It doesn't look like this was added to the changelog. From what I can see it was included in 3.0.0.

**Comment by pmcpinto** [comment]
👍 thanks for the update
