### ISSUE TITLE
Returning customer counter

### ISSUE THREAD

**Issue by Mte90** [woocommerce/woocommerce-admin#7917]
### Describe the bug
I have a website where some orders mark wrongly the returning_customer flag in `wc_order_stats`. I am not able to debug better what is happening so I am trying why this should happen.

So I saw that code https://github.com/woocommerce/woocommerce-admin/blob/025d394ed3ac4ffd8c07c3df548777756c54842e/src/API/Reports/Orders/Stats/DataStore.php#L636 this code get the oldest order and check if the id is the same.
So there is a function `wc_get_customer_order_count` giving the user id https://github.com/woocommerce/woocommerce/blob/master/includes/wc-user-functions.php#L675 using this code https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php#L369 return the data from a meta value that is a counter.

It isn't more easy to use that counter instead to do all those queries? also because the other one has also a filter so it is possible to do a workaround.

**Comment by joelclimbsthings** [comment]
Hi @Mte90 , thanks for bringing this up!

I'm not all that familiar with that code, but it does look like that function carries out a few tasks that wouldn't be accomplished by utilizing the counter functions you're referencing. For instance, it's tracking `is_returning_customer` on a per-order basis, and updating that field per order by comparing it to the dates/statuses of other orders. 

For instance, if someone changes the date of an order to make it the first order the customer placed, it needs to update that field to reflect that for itself as well as other orders. 

Perhaps you could use the `woocommerce_analytics_update_order_stats_data` filter for any work-arounds here?

I'm closing this one for now, but let me know if you think I've missed something!

**Comment by Mte90** [comment]
> For instance, if someone changes the date of an order to make it the first order the customer placed, it needs to update that field to reflect that for itself as well as other orders.

This makes sense but probably to speed up for any order check for that counter can improve the performance too. I mean if the counter says zero is useless to do a query to find the oldest order.   
Instead if it is different then that do all those check.

For the filter seems a solution to force the counter to the real value until I find the cause of the issue.

**Comment by Mte90** [comment]
So to add more information, I am trying to send in the email to the admin after an order if the customer is new.
So in `admin-new-order.php` I had to add some check as seems that `is_returning_customer` report false but in the UI it is written that is returning.
My guess is that in that context doesn't always this data is saved.
My code:
```
$user = get_user_by( 'email', $order->get_billing_email() );
if ( !$order->is_returning_customer( $order ) || !is_object( $user ) ) {
    echo "<b>New Customer</b><br>";
}
```

The second check is to see if a guest customer has an account so have already an order. 
Right now is incomplete because doesn't check guest customers without an account and in this case the code fails.

**Comment by Mte90** [comment]
So the final code:
```
$email = esc_sql( $order->get_billing_email() );
global $wpdb;
$results = $wpdb->get_var( "SELECT COUNT(*) FROM wp_postmeta WHERE wp_postmeta.meta_key = '_billing_email' AND wp_postmeta.meta_value = '" . $email . "'" );
if ( intval( $results ) < 2 ) {
    echo "<b>New Customer</b><br>";
}
```
As during the email the native method is not thrustable and using other Woo methods for countings orders crash the request on the website (I have no idea why), a single query instead is more light for performance.

So I am not sure but maybe the order stats are generated after sending the emails in wordpress?

**Comment by Mte90** [comment]
A test case that is counted wrong by this api I saw now in returning_customer.
A customer with just one order processed and one in progress is marked as a new customer when it should be a new one.

**Comment by Mte90** [comment]
```
add_action( 'woocommerce_analytics_update_order_stats_data', 'jh_woo_order_update_stats' , 10, 2 );
function jh_woo_order_update_stats( $data, $order ) {
        $email = esc_sql( $order->get_billing_email() );
        global $wpdb;
        $results = $wpdb->get_var( "SELECT COUNT(wp_postmeta.post_id) FROM wp_postmeta, wp_posts WHERE wp_postmeta.meta_key = '_billing_email' AND wp_postmeta.meta_value = '" . $email . "' AND wp_postmeta.post_id = wp_posts.ID AND (wp_posts.post_status = 'wc-completed' OR wp_posts.post_status = 'wc-processing')" );
        if ( intval( $results ) < 2 ) {
            $data['returning_customer'] = 0;
        } else {
            $data['returning_customer'] = 1;
        }

		return $data;
}
```

Implemented that code in the filter and now should be work in the right way.

**Comment by louwie17** [comment]
> Implemented that code in the filter and now should be work in the right way.

Glad you got something working @Mte90, I would suggest to also check for the `post_modified` column to see if the order is older than the new order. 

After getting this fix do you still think this is a clear bug, or a custom use case for you? If you still think it's a bug, would you be able to write some test instructions on how to reproduce it and an easy way to see the error? Otherwise I will leave this issue closed.

**Comment by Mte90** [comment]
I see that this fixed the issue at all between emails and also in the Data Order view in the backend.
As those filters are executed in the moment the order is done counting them in my case fix all the cases.
