### ISSUE TITLE
Store profiler: Track extensions installation performance and failures

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#7919]
Business features step: spike to determine and implement some tracks to see if there are issues with extensions installation performance

- Time taken to install (buckets - something like '0-2s','3-4s','5-9s',... - TBC by @pmcpinto what the best solution is - if you could group by a range in tracks then an absolute time to install would be better)
- Instances of failed installs
- Instances of users dropping out at this step

**Comment by mattsherman** [comment]
Notes:

- If subscriptions is selected, WCPay is installed before this step
- Do we track the total duration for all extensions, or each extension individually (we can't do this client-side, since we make one call to the server)
- Do we just use something like Action Scheduler to do the installation?

**Comment by louwie17** [comment]
Estimating this as a 2, given it might take a little bit of tinkering with the timing and making sure things are recorded correctly and covering all the use cases.

**Comment by louwie17** [comment]
> Instances of users dropping out at this step

@becdetat I didn't tackle this one so far in my PR, as I am not sure how we would want to tackle this, a user can't quit the onboarding from the screen they would have to manually hit return or edit the url or close the tab/window all together. 
We do already trigger the `_step_complete` track for each step, so I wonder if we could look at that to determine if a user quit early?

**Comment by becdetat** [comment]
Sorry @louwie17 I didn't see this at the time you added your last comment. @pmcpinto can you confirm that not capturing users dropping out, or using `step_complete`, would be ok for this ticket?

**Comment by pmcpinto** [comment]
> Sorry @louwie17 I didn't see this at the time you added your last comment. @pmcpinto can you confirm that not capturing users dropping out, or using step_complete, would be ok for this ticket?

@becdetat @louwie17 using `wcadmin_storeprofiler_step_complete` makes sense. However, I think we only fire `step` : `business-features` when the user completes the two steps within the Business details: providing the business details info and installing the extensions. This makes it difficult to understand if they drop before/while they provide the business details or install the extensions. Is it possible to fine-tune the Tracks event to ensure we track the completion of the two steps? I'll reopen the issue until we clarify this.

**Comment by becdetat** [comment]
@louwie17 I'm going to have to defer to you as you're much closer to the code :-)

**Comment by louwie17** [comment]
> @becdetat @louwie17 using `wcadmin_storeprofiler_step_complete` makes sense. However, I think we only fire `step` : `business-features` when the user completes the two steps within the Business details: providing the business details info and installing the extensions. This makes it difficult to understand if they drop before/while they provide the business details or install the extensions. Is it possible to fine-tune the Tracks event to ensure we track the completion of the two steps? I'll reopen the issue until we clarify this.

@pmcpinto if using `wcadmin_storeprofiler_step_complete` will work, could we also trigger this track when a user finishes the business details part? We could call it `business-details`. And use the `business-features` track to determine if a user finished after the free features installation.

**Comment by pmcpinto** [comment]
> @pmcpinto if using wcadmin_storeprofiler_step_complete will work, could we also trigger this track when a user finishes the business details part? We could call it business-details. And use the business-features track to determine if a user finished after the free features installation.

Yes. This would be super helpful.

**Comment by mattsherman** [comment]
@louwie17 Since this was re-opened, I'm moving it back to In Progress. It might more clear to just open a new issue for whatever needs to be done.

**Comment by mattsherman** [comment]
@pmcpinto What is the priority on this additional change?

**Comment by pmcpinto** [comment]
> @pmcpinto What is the priority on this additional change?

Is it possible to include this change in wcadmin 3.2? It can wait until 3.3 if the team already has too many things in the pipeline during the upcoming days.

**Comment by louwie17** [comment]
> Is it possible to include this change in wcadmin 3.2? It can wait until 3.3 if the team already has too many things in the pipeline during the upcoming days.

I think so, given part of this issue is already in the repo, and this should be a relatively minimal change. I will add this today.
