### ISSUE TITLE
Code Examples: Follow-Up Emails Dashboard Widget

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#792]
Currently the follow-up emails extension adds a widget to the `wp-admin` dashboard that would be a pretty ideal candidate for Performance Indicators. And it also creates a custom report ( within its own nav structure 😱 ) that could be an interesting use-case for a component-build wc-admin report:

![image](https://user-images.githubusercontent.com/22080/48131287-68e08c00-e244-11e8-82c6-ec376451e0d9.png)

![image](https://user-images.githubusercontent.com/22080/48131302-77c73e80-e244-11e8-816c-04bd49cc8f5c.png)

Follow Up Emails does have a current set of REST API reporting endpoints that could help speed up the development a bit too.

**Comment by timmyc** [comment]
@justinshreve has a working example of this open https://github.com/woocommerce/woocommerce-follow-up-emails/pull/698

**Comment by psealock** [comment]
I'm closing this because it hasn't been a priority Performance Indicator.
