### ISSUE TITLE
Spike to investigate wrapping Settings/Product extensions HTML injection in a React app

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#7925]
A future plan with both Settings and Product Management is to reactify those pages and make them both faster and easier to use for the end user.

A major sticking point with recreating Settings and Product Management is supporting existing 3PD and Automattic extensions that currently generate and insert HTML into those pages.

This spike is intended to investigate what would be required to wrap the generated HTML in a way that it can be inserted into the new pages in a safe and React-friendly manner. Postbacks will also need to be considered.

- [ ] create a stub React application within Settings
- [ ] wrap a HTML insertion from an extension in some way
- [ ] insert the wrapped HTML into the React application
- [ ] provide a mechanism for posting back to the extension when the generated HTML is interacted with/submitted by the user
- [ ] verify that the same approach will work in Product Management (and Order Management if you have time)

**Comment by mattsherman** [comment]
@becdetat What do you mean by

> when the generated HTML is used

Do you mean when it is rendered in the browser? Or, when it is interacted with by a user? Or, something else?

**Comment by becdetat** [comment]
> @becdetat What do you mean by
> > when the generated HTML is used

When it is interacted with/submitted by the user. Sorry, could have been clearer.

**Comment by joshuatf** [comment]
Closing this issue.  Spike complete; notes can be found at p90Yrv-2B0-p2.
