### ISSUE TITLE
Add documentation about Inbox Notes 320 character limit

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7935]
A [developer advisory](https://developer.woocommerce.com/2021/11/10/introducing-a-320-character-limit-to-inbox-notes/) was created for the upcoming 320 character limit on notes.

We should include information about the limit in other areas of documentation

- [`woocommerce-admin/docs`](https://github.com/woocommerce/woocommerce-admin/tree/main/docs) (noting that this doesn’t seem to have any inbox documentation presently)
- https://developer.woocommerce.com/2020/10/16/using-the-admin-notes-inbox-in-woocommerce/

**Comment by ilyasfoo** [comment]
+ Add a detail for emojis not supported yet p1638849921063800-slack-C01SFMVEYAK

**Comment by ilyasfoo** [comment]
The developer blogpost has been updated with the following updates:

![https://d.pr/i/N3jTEo](https://d.pr/i/N3jTEo+) 
Full Size: https://d.pr/i/N3jTEo

![https://d.pr/i/qjAkZo](https://d.pr/i/qjAkZo+) 
Full Size: https://d.pr/i/qjAkZo

**Comment by ilyasfoo** [comment]
@woocommerce/ghidorah Appreciate it if you can check if what I did above is sufficient ⬆️

**Comment by adrianduffell** [comment]
> Appreciate it if you can check if what I did above is sufficient ⬆️

Looks great @ilyasfoo, thank you!
