### ISSUE TITLE
Payment gateway suggestion doc improvements and example extension

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7937]
To make it easier for 3PDs to implement the payment gateway suggestions, we should improve the documentation around how to add and slotfill payment gateway suggestions.  An example extension would also be very helpful to show this in action.

## Dev tasks

- [ ] Docs: Update references to the feature flag
- [ ] Docs: Filtering gateway suggestions
- [ ] Docs: Add more information around the SlotFill
- [ ] Docs: Add example for gateway config
- [ ] Create an example extension with a custom gateway configured solely through the server code
- [ ] Create an example extension with a custom gateway and slotfill

## Reference

- Existing 3rd party plugin PRs are listed in https://github.com/woocommerce/woocommerce-admin/issues/6878

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7937?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro

**Comment by pmcpinto** [comment]
@joshuatf @mattsherman I'm assuming that we can start sharing the update docs and example extension with our partners, right? Where can I find all the info that we should share with them?

**Comment by joshuatf** [comment]
@pmcpinto Yes, this is ready for use.  The docs can be found at https://github.com/woocommerce/woocommerce-admin/blob/main/docs/features/payment-gateway-suggestions.md.

This includes instructions for getting started with an example extension and all the details needed to customize the payment gateway suggestions experience.

Please keep me in the loop if you receive any feedback or if a 3PD needs help with setup.
