### ISSUE TITLE
Create new WC Pay promotion experiment with treatment 100% and update version in wc.com

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#7940]
Create new WC Pay promotion experiment with treatment 100% and update version in wc.com.

## Context

The WC Pay payment method experiment is showing clear signs that the [treatment is outperforming](https://experiments.a8c.com/experiments/20342-woocommerce-wc-pay-promotion-payment-methods-table-v2/results). Given we have to wait for a WC Admin release to remove the experiment, we will create a new experiment for now that shows the treatment a 100% of the time.
For more context see this Slack convo - p1637077555016100/1636629419.008100-slack-C01LPBCV4J1

## Acceptance criteria

- A new v3 experiment is enabled, with the treatment experience selected 100% of the time

## Dev tasks

- [ ] Clone the current experiment, updating the version number from `v2` to `v3` with an end date probably two months out, enough time for a new WC Core release. The start date can be immediately (or the next day).
- [ ] Update the experiment version in woocommerce.com to `v3` [here](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/payment-gateway-suggestions/includes/class-payment-method-promotions.php#L42)

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7940?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro

**Comment by louwie17** [comment]
Closing this as these changes will not be relevant anymore in favour of disabling the experiment for now and making it permanent in [this issue](https://github.com/woocommerce/woocommerce-admin/issues/7941).
Context: p1637326314022400/1636629419.008100-slack-C01LPBCV4J1
