### ISSUE TITLE
Remove use of `woocommerce_wc_pay_promotion_payment_methods_table` experiment

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#7941]
Remove use of `woocommerce_wc_pay_promotion_payment_methods_table` experiment and set it up so it's used all the time.

## context 

The WC Pay payment method experiment is showing clear signs that the [treatment is outperforming](https://experiments.a8c.com/experiments/20342-woocommerce-wc-pay-promotion-payment-methods-table-v2/results). We will make use of the treatment a 100% of the time and can remove the experiment.
For more context see this Slack convo - p1637077555016100/1636629419.008100-slack-C01LPBCV4J1

## Acceptance criteria

- The WCPay promotion is shown always in the payment methods table
- WCPay promotion is not shown in the recommendation card under the payment methods table

## Dev tasks

- [ ] Remove the treatment logic and make sure the wc pay promotion is shown always in the payment methods table. This should require minimal changes, removing [these lines](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/WcPayPromotion/Init.php#L104-L122) and returning `true` on [this line](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/WcPayPromotion/Init.php#L124) should be enough
- [ ] Make sure that WC Pay is not shown in the recommendation card under the payment methods table.

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7941?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro
