### ISSUE TITLE
Settings: show the first option when the payment recommendation card is enabled

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7942]
**Description:** the WC Pay recommendation experiment's treatment in the settings table is hiding the first option available in the list if a user has previously manually sorted the table's row and saved that order. It shouldn't hide any other options.

**Acceptance criteria:** 

- [x] Show the first option available in the payments settings table below the WC Pay recommendation

**Comment by louwie17** [comment]
@elizaan36 would you have suggestions for a minimal UI layout to dismiss the WC Pay promotion?
Here is the current look:
<img width="1452" alt="Screen Shot 2021-11-17 at 11 28 34 AM" src="https://user-images.githubusercontent.com/2240960/142229901-50a2b647-8739-49ed-a6fd-b773fe06d8fd.png">

**Comment by louwie17** [comment]
Re opening #7943 was only part of the fix.

**Comment by mattsherman** [comment]
Moving this back to Groom for the rest of the issue.

**Comment by mattsherman** [comment]
I decided to split out the dismissal part to a separate story: https://github.com/woocommerce/woocommerce-admin/issues/7951

**Comment by mattsherman** [comment]
@louwie17 Would it be possible to fix this for existing customers without them installing an updated, by disabling or changing the experiment in some fashion? Or, is the damage done once they are initially assigned an experiment option?

**Comment by mattsherman** [comment]
> @louwie17 Would it be possible to fix this for existing customers without them installing an updated, by disabling or changing the experiment in some fashion? Or, is the damage done once they are initially assigned an experiment option?

Answer: The experiment was already disabled, fixing this issue for existing customers!
