### ISSUE TITLE
Allow users to easily dismiss the recommendation without leaving the Payments settings page.

### ISSUE THREAD

**Issue by mattsherman** [woocommerce/woocommerce-admin#7951]
**Description:** We don't provide a way to easily dismiss the WCPay recommendation inline and should do that before using this approach outside the current experiment. Right now, dismissing it requires going to **WooCommerce > Settings > Advanced > WooCommerce.com** and disabling _Marketplace suggestions_ entirely.

## Acceptance criteria

- Users are able to easily dismiss the WCPay recommendation without leaving the Payment settings page
- Tracks event is recorded when user dismisses the WCPay recommendation

## Design

![Screen Recording 11-22-2021 at 11 30 AM](https://user-images.githubusercontent.com/5121465/142908081-ece46ff1-2154-46c0-a092-71c30f2c9e04.gif)
- An ellipses menu is shown to the left of the "Install" CTA
- A "Dismiss" menu item will remove the WCPay prompt

<img width="1258" alt="Screen Shot 2021-11-22 at 11 28 41 AM" src="https://user-images.githubusercontent.com/5121465/142908210-976f2064-4803-4f17-b6d3-2922843a24bf.png">

This is a temporary solution until WCPay is the default in core - at that point the dismiss action will be removed.

## Dev tasks

- [ ] Implement ellipsis menu with menu item to dismiss the WCPay recommendation
- [ ] Record Tracks event when WCPay recommendation is dismissed

**Comment by mattsherman** [comment]
@elizaan36 would you have suggestions for a minimal UI layout to dismiss the WC Pay promotion?
Here is the current look:
<img width="1452" alt="Screen Shot 2021-11-17 at 11 28 34 AM" src="https://user-images.githubusercontent.com/2240960/142229901-50a2b647-8739-49ed-a6fd-b773fe06d8fd.png">

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7951?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro

**Comment by pmcpinto** [comment]
@elizaan36 do you have time to check this early next week? Ideally, this should be included in wc admin 3.0 and the code freeze will be on Nov 30

**Comment by elizaan36** [comment]
Hey @mattsherman @pmcpinto, here's an option for the dismiss action.
![Screen Recording 11-22-2021 at 11 30 AM](https://user-images.githubusercontent.com/5121465/142908081-ece46ff1-2154-46c0-a092-71c30f2c9e04.gif)
- An ellipses menu is shown to the left of the "Install" CTA
- A "Dismiss" menu item will remove the WCPay prompt

<img width="1258" alt="Screen Shot 2021-11-22 at 11 28 41 AM" src="https://user-images.githubusercontent.com/5121465/142908210-976f2064-4803-4f17-b6d3-2922843a24bf.png">

This is a temporary solution until WCPay is the default in core - at that point the dismiss action will be removed.

**Comment by pmcpinto** [comment]
Elizabeth, thanks!

@mattsherman it would be good to also add Tracks to this action.
