### ISSUE TITLE
run_remote_notifications scheduled actions set to run at 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by csmcneill** [woocommerce/woocommerce-admin#7957]
### Describe the bug
Sometimes, when scheduled actions are not running, I have found that there are several `woocommerce_admin/stored_state_setup_for_products/async/run_remote_notifications` scheduled actions with a scheduled run date/time of `0000-00-00 00:00:00`.Because these actions have an erroneous date, they will never run.

While most sites experiencing this issue are running WooCommerce Subscriptions, I cannot determine if it is definitively caused by the WC Subscriptions extension.

This issue has been identified in the following tickets:

4430159-zen
4262593-zen
4153182-zen
4370603-zen
4403657-zen
4356383-zen
4219403-zen

And here are tickets where it may be a potential issue:
4372945-zen

Thus far, the only way we've found to clear these scheduled actions are to manually run them. Often times, this is relatively easy, but there have been cases where there are hundreds or thousands of these entries that all need to be run manually.

It was recommended that I create a bug report here per the following conversation: p1636131287202500-slack-C7U3Y3VMY

**Comment by adrianduffell** [comment]
Hi @csmcneill ,

Thanks for reporting this. I was able to reproduce the creation of multiple actions by importing the [products sample data](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/sample-data/sample_products.csv) and also observed these actions remain in a pending state.

<img width="1342" alt="Screen Shot 2021-11-22 at 3 24 56 pm" src="https://user-images.githubusercontent.com/9312929/142820602-4400ee30-8aee-43e3-b42b-b175475b4fe7.png">

The issue looks like it is in Woo Admin’s side in the Remote Inbox Engine, where an action is created with every new product added. I could imagine with a large active store, these actions could pile up with frequent product additions.

I'm wondering if we could avoid creating these actions altogether. Perhaps it would be equally as effective for our purposes to update the state (line 118 below), and just wait for the inbox engine to run as part of the daily cron.

https://github.com/woocommerce/woocommerce-admin/blob/441ec279d6a7d595ec1f64051ce744d18481f2d2/src/RemoteInboxNotifications/StoredStateSetupForProducts.php#L107-L129

**Comment by chihsuan** [comment]
Not very understand how RemoteInboxNotificationsEngine works. But maybe we can simply add a `$stored_state` check before we call `update_stored_state to avoid too many update actions`?

```php
$stored_state                         = RemoteInboxNotificationsEngine::get_stored_state();

if ( $stored_state->there_are_now_products == false ) {
	$stored_state->there_are_now_products = true;

	RemoteInboxNotificationsEngine::update_stored_state( $stored_state );

	self::enqueue_async_run_remote_notifications();
}
```

**Comment by russellgi** [comment]
Morning.  I have this issue, and there's over 460 of them pending without a date.  This is from importing products.  Do I have to manually run them all, or is there another way to do it?

**Comment by chihsuan** [comment]
> Not very familiar with this. However, can we simply add a $stored_state check to avoid too many update actions? For example:

I searched the `there_are_now_products` but found that we don't have code to set `there_are_now_products` to `false`. So the `there_are_now_products` is always true after a product is created.

Also, we have the stored state definition [here](https://github.com/woocommerce/woocommerce-admin/blob/402dc616d50bb0c21d07fdd6c007b4fc32039ce1/src/RemoteInboxNotifications/README.md#stored-state
) but it seems that neither of them is being used. 

@woocommerce/ghidorah Any thoughts on this?

**Comment by chihsuan** [comment]
> Morning. I have this issue, and there's over 460 of them pending without a date. This is from importing products. Do I have to manually run them all, or is there another way to do it?

Hi, @russellgi I think you can manually run all with bulk action.

**Comment by ilyasfoo** [comment]
>Not very familiar with this. However, can we simply add a $stored_state check to avoid too many update actions? For example:

This sounds like a good alternative! I think the original intention of running this every time was so that no inbox note is missed. For example, the store hasn't fetched remote inbox specifications but it has already created the product & run the action. Thus, notes that come after fetching will never be executed.

>I searched the there_are_now_products but found that we don't have code to set there_are_now_products to false. So the there_are_now_products is always true after a product is created.

As I understand, the state was only meant to be set once to flag that the store has created at least 1 product.

>Also, we have the stored state definition [here](https://github.com/woocommerce/woocommerce-admin/blob/402dc616d50bb0c21d07fdd6c007b4fc32039ce1/src/RemoteInboxNotifications/README.md#stored-state) but it seems that neither of them is being used.

AFAIK it can also be used by remote inbox & payment gateway suggestions.

**Comment by chihsuan** [comment]
>  I think the original intention of running this every time was so that no inbox note is missed.

I see. I just checked the code. I think it will fetch specifications first if it's empty and it seems that we will cache them for 7 days.

https://github.com/woocommerce/woocommerce-admin/blob/2b17ed166ac4d73264db243c5715c4d404ec95be/src/DataSourcePoller.php#L106-L112

https://github.com/woocommerce/woocommerce-admin/blob/2b17ed166ac4d73264db243c5715c4d404ec95be/src/DataSourcePoller.php#L66-L70

Perhaps we can record the last execution time and only run it after a period of time.

I also noticed that actions with the `0000-00-00 00:00:00` date/time still can be executed with a few products imports. 

![Screen Shot 2022-02-09 at 13 43 49](https://user-images.githubusercontent.com/4344253/153130072-b68ac55c-37ca-41ab-bf6d-729586335129.png)

**Comment by chihsuan** [comment]
I found a previous performance improvement issue https://github.com/woocommerce/woocommerce-admin/issues/6189 and PR https://github.com/woocommerce/woocommerce-admin/pull/6995. cc @becdetat if have some thoughts.

**Comment by ilyasfoo** [comment]
> Not very familiar with this. However, can we simply add a $stored_state check to avoid too many update actions? For example:

@chihsuan I just remembered better now, scratch my previous comment. The original intention for running `enqueue_async_run_remote_notifications` immediately is to have notes that use the stored states displayed immediately after making any change to the state. `your-first-product` note from remote inbox is an example that uses this.

I think we can safely assume remote inbox specs are fetched prior to running.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/3747241/153135985-eff33dbd-73c1-41ce-a32b-aef3a8b3820e.png">
 
> Perhaps we can record the last execution time and only run it after a period of time.

Though this sounds slightly more complicated. I like your previous idea of adding a check whether `stored_state` changed better.

**Comment by chihsuan** [comment]
> Though this sounds slightly more complicated. I like your previous idea of adding a check whether stored_state changed better.

@ilyasfoo Thanks for providing the context and feedback! Okay, I'll create a PR with a simple check. 🙌
