### ISSUE TITLE
Order Report should have advance filter for  country states also as required by every country tax filing

### ISSUE THREAD

**Issue by John-belt** [woocommerce/woocommerce-admin#7964]
### Is your feature request related to a problem? Please describe.
HI there has been a lot of issues related to taxing and reports in the analytics and for that reason, I want to use my third-party apps for tax filing and calculation.  The only data that is needed is filtered by states(like amount, total orders, total amount) for the whole month. There is no filter for that. Since the tax calculation and filing are different for different countries but all have this thing in common and there are a lot of external tools for tax calculation and filing. It would be a really good idea to have states as a filter in analytics too. 

### Describe the solution you'd like
It would be a really good idea to have state as a filter in analytics too.

**Comment by John-belt** [comment]
@psealock Read your comment on the support of the plugin.

**Comment by louwie17** [comment]
Hi @John-belt, thanks for creating an issue for this feature request. I agree that this would be beneficial. 
I am tagging this under votes needed for now as this could be more specific to the United States and Canada, I am not as familiar with tax laws under other countries and how they differ between states/provinces.

In the mean time we do allow for 3PDs to write their own advanced filter, which could be of benefit to you. One of our dev's wrote a blog post on how to do that -> https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/
Feel free to reply in here if you get stuck when attempting to write a custom filter.

**Comment by John-belt** [comment]
Hey, it is beneficial to other countries as well like Asian countries where each state has its own tax rates. So makes sense. Will try to write the filter as suggested in the blog.

**Comment by John-belt** [comment]
Hey guys any update on this?? Would rather appreciate if yu guys can implement this. There has been lot of taxing related issues like partial/full refund is not update in analytics and some other issues as well. It would be really great if we have a bit of flexibility and this really helps us.

**Comment by moon0326** [comment]
Hi @John-belt,

Sorry for the delay in response. I'm going to ping our team leads so they can take a look at it. 

Hey @adrianduffell and @mattsherman 👋 

It sounds like this is a nice feature to have. Could you guys look into it and see if we can work on it in the near future?

Thanks!

**Comment by ilyasfoo** [comment]
It seems we aren't able to prioritize this feature request at the moment, at least for the first quarter of 2022. I have to close this issue for now.

However, filtering by states is definitely a useful feature for merchants, we may come back and reevaluate this once we are able to allocate efforts into improving analytics.
