### ISSUE TITLE
Home screen default layout changed with wc admin 2.9-rc.2

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7967]
### Describe the bug
With wc admin 2.9-rc.2 the home screen for new users defaults to the two-column layout. The default should be the single-column

### To Reproduce
1. Create a new store using WooCommerce 6.0.0 Beta 1
2. Skip the store profiler and visit the home screen
3. See that the default layout is the two-column

### Actual behavior:
The home screen for new users defaults to the two-column layout

### Screenshots
<img width="1440" alt="Captura de ecrã 2021-11-25, às 16 54 25" src="https://user-images.githubusercontent.com/3380168/143479667-f4f1713d-ea5e-4b60-a90d-f9b340e2fee2.png">

### Expected behavior
The home screen default layout should be the single-column

**Comment by pmcpinto** [comment]
@adrianduffell afaik you're the 2.9 release lead. is it possible to fix this in time for it to be included in the final version of wcadmin 2.9?

cc @becdetat

**Comment by adrianduffell** [comment]
@pmcpinto I was able to reproduce this and aiming to have this fixed for the 2.9 final release.

**Comment by pmcpinto** [comment]
I've tested WC 6.0 RC1 this morning and the default layout is showing as expected. Thanks for fixing this so quickly.
