### ISSUE TITLE
Caching for get_notes

### ISSUE THREAD

**Issue by tgglv** [woocommerce/woocommerce-admin#7968]
### Description
During the first several hours of BlackCyber 2021, we noticed places in WC Admin that indirectly affected WCCOM's performance.

These 2 places were:
- Notes::possibly_delete_survey_notes
- Notes::possibly_add_note

They both uses `Automattic\WooCommerce\Admin\Notes\DataStore::get_notes()`.

The reason was in using `Automattic\WooCommerce\Admin\Notes\DataStore::get_notes_where_clauses()` under the hood that uses the `get_notes_where_clauses` filter. We used to have a heavy request (`get_notes_where_clauses` on images) joined to this filter.

### To Reproduce
Every `admin_ajax.php` call (on WCCOM we use such call for sending events to Tracks) or `admin_init` runs `Notes::possibly_delete_survey_notes`.

So, `Automattic\WooCommerce\Admin\Notes\DataStore::get_notes()` will be launched and everything that use `get_notes_where_clauses` filter will be called too.

#### Possible delete survey notes
![image](https://user-images.githubusercontent.com/15897544/143234935-e6c7804d-77e8-43ff-9491-7c5aeac0184c.png)

#### Possibly add note
![image](https://user-images.githubusercontent.com/15897544/143249367-c8fd9697-591a-4baf-865f-c6003178f914.png)

### Suggestion
To protect big stores from performance issues, it might be useful to add some sort of caching (e.g. transient based) for `DataStore::get_notes()` calls.

**Comment by louwie17** [comment]
@tgglv thanks for creating this issue. I have two initial thoughts/questions:
- From your screenshots it appears that the main bottleneck is the `get_terms` call used by the `filter_admin_notes_by_vendor_id` filter that is listening to the `woocommerce_note_where_clauses` filter. Could caching be added to this instead?
- Having a deeper look at the two notes that do trigger `get_notes`, it appears that their use cases are quite specific to the note, and calling `get_notes` might be overkill. We could have a more generic `get_notes` function only used for internal notes to retrieve data, or just use `$wpdb` within each of these notes. This should prevent any potential delay's by 3PD filters.

I will add this to our grooming for now.

**Comment by tgglv** [comment]
Hey @louwie17! 👋 

> From your screenshots it appears that the main bottleneck is the get_terms call used by the filter_admin_notes_by_vendor_id filter that is listening to the woocommerce_note_where_clauses filter. Could caching be added to this instead?

Indeed, we fix that by removing that expensive call for non-logged users.

> Having a deeper look at the two notes that do trigger get_notes, it appears that their use cases are quite specific to the note, and calling get_notes might be overkill. We could have a more generic get_notes function only used for internal notes to retrieve data, or just use $wpdb within each of these notes. This should prevent any potential delay's by 3PD filters.

Indeed. This issue is a kind of feedback to let you know how unexpectedly might behave a big store on the `get_notes` call. Since we've fixed that case locally please feel free to close the issue if you plan to do something with `get_notes` in a separate issue.

**Comment by louwie17** [comment]
> Indeed. This issue is a kind of feedback to let you know how unexpectedly might behave a big store on the `get_notes` call. Since we've fixed that case locally please feel free to close the issue if you plan to do something with `get_notes` in a separate issue.

Yeah we appreciate the feedback, as this will certainly be worth fixing. I will create two separate issues for this.

**Comment by louwie17** [comment]
Closing this in light of the above two issues (#7986, #7987 ) and that the immediate issue has been fixed:

> Indeed, we fix that by removing that expensive call for non-logged users.
