### ISSUE TITLE
Inbox notification: How to Migrate from Magento to WooCommerce

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7971]
**Title:** How to Migrate from Magento to WooCommerce
**Content:**  Changing platforms might seem like a big hurdle to overcome, but it is easier than you might think to move your products, customers, and orders to WooCommerce. This article will help you with going through this process.
**Segmentation:** 
New users with `setup_client`: `false` on `wcadmin_storeprofiler_store_details_continue` OR `setup_client`: `false` on `wcadmin_storeprofiler_store_business_details_continue_variant`
AND
`used_platform`: `magento` on `wcadmin_storeprofiler_store_business_details_continue_variant`

**Timing:** 5 minutes after plugin install
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/posts/how-migrate-from-magento-to-woocommerce/?utm_source=inbox
**CTA label:** Learn more

**Comment by joshuatf** [comment]
@pmcpinto We can set this up on our scheduled action that runs daily, but it won't be exactly 5 minutes after.   How important is that timing?

**Comment by pmcpinto** [comment]
We already trigger a couple of notifications when the plugin is installed/activated. The goal with the 5 min delay is to check is firing this notification later leads to better engagement. The 5 min timing is not critical, as long as we fire the notification during the first 60 minutes. Let me know if it's possible

**Comment by mattsherman** [comment]
> The goal with the 5 min delay is to test if firing this notification later leads to better engagement.

@pmcpinto Since this is a new inbox notification specific to merchants that indicated they used Magento, how are we measuring whether delaying the firing of this notification by 5-60 minutes leads to better engagement than firing it immediately?

We can certainly implement the inbox notification with a delay, but I just wanted to double-check this first to make sure that we understand how we will measure whether the delay was successful in increasing engagement.

**Comment by pmcpinto** [comment]
Hey Matt, good question. 

Our assumption is that we're triggering too many notifications at the same time when the store is created. Apart from removing low-performing notifications, we also think that spacing them out over time can lead to a better conversion rate. We aim to compare it with the other notifications that we trigger immediately. It won't be an apples to apples comparison but it can help with the initial validation of our assumption. I'm happy to consider other options :)

**Comment by mattsherman** [comment]
@pmcpinto Thanks. I feel that this particular notification is so specialized that I question how valid comparing it to other, more general, notifications would be. 

When the team discussed this issue, we all questioned whether, in real life scenarios, there would be much difference from a user perspective in the notification being delivered immediately vs after 5 minutes. If it takes a user nearly that long after installing to explore the home screen notifications, it wouldn't. 

I also would argue that when considering a migration, we would want to get this information in front of the merchant as soon as possible, as it is important that they understand their options and what the process would entail.

All that said, if you want a 5 minute delay, we can implement it. I don't think any of us are super opposed to it. 😀

**Comment by pmcpinto** [comment]
> I feel that this particular notification is so specialized that I question how valid comparing it to other, more general, notifications would be.

True. The best term of comparison is with the notification about the Shopify migration. 

> When the team discussed this issue, we all questioned whether, in real life scenarios, there would be much difference from a user perspective in the notification being delivered immediately vs after 5 minutes. If it takes a user nearly that long after installing to explore the home screen notifications, it wouldn't.

> I also would argue that when considering a migration, we would want to get this information in front of the merchant as soon as possible, as it is important that they understand their options and what the process would entail.

Good points. The main reason behind such a short delay was to ensure that the notification was placed at the top to increase the chances of it being read by the user. In the past, there have been some informal discussions about a sticky notification concept. But there are some risks, especially if we want to allow 3PDs to take advantage of this feature.
