### ISSUE TITLE
Slow query issue and AutomateWoo plugin

### ISSUE THREAD

**Issue by diegpl** [woocommerce/woocommerce-admin#7990]
Hi, I just bought AutomateWoo plugin from woocommerce.com and I realized it depends on Woocommerce Admin, a plugin with a deprecated soon warning. Could someone tell me why will it be deprecated and why AutomateWoo depends on it?

It also generated some slow query, as showed in the below image:
https://pasteboard.co/ftD4kyMOeKdQ.png

Tks! ;-)

**Comment by adrianduffell** [comment]
Hi @diegpl ,

Thanks for reporting this. Are you able to provide a screenshot of the deprecated warning you see to help investigate this further? [WooCommerce Admin is merging into the Core plugin soon](https://developer.woocommerce.com/2021/10/14/rfc-woocommerce-admin-is-merging-into-core/) but will retain compatibility with other plugins that depend on its features.

> It also generated some slow query, as showed in the below image

The times on these queries look reasonable, unless I misunderstand something? These queries form part of the install routine which runs when the plugin is installed or updated, so they won't occur very often.

**Comment by diegpl** [comment]
I`ve updated Woocommerce and the DB and toe problem is solved. The warning was in the old reports page if I am not misaken. The time is reasonable just in Query Monitor report, not real. I ll close this thread now. Tks for the attention! ;-)

**Comment by adrianduffell** [comment]
No problems, thanks @diegpl. I'm glad to hear the problem is solved now.
