### ISSUE TITLE
Changelog not displayed by WordPress

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7993]
### Describe the bug

With the move of changelog entries from `readme.txt` to `changelog.txt` , WordPress no longer displays a Changelog tab in the plugins UI.

### To Reproduce

1. Go to WordPress Plugins screen.
2. Search for WooCommerce Admin.
3. Click "More Details".
4. See that there is no "Changelog" tab.

### Actual behavior:

No Changelog tab on WordPress plugin screen.

### Screenshots

<img width="1436" alt="Screen Shot 2021-12-02 at 10 16 07 am" src="https://user-images.githubusercontent.com/9312929/144348004-3be7d70a-d9eb-4b59-981b-4dc63d8c3919.png">

☝️ WooCommerce Admin plugin, without a Changelog tab.

<img width="1339" alt="Screen Shot 2021-12-02 at 10 45 05 am" src="https://user-images.githubusercontent.com/9312929/144348236-3e1a1b97-c021-4c5f-931a-5338978b743c.png">

☝️ WooCommerce plugin, with a Changelog tab.

### Expected behavior

Include changelog information in readme.txt. With the [upcoming merge to core](https://developer.woocommerce.com/2021/10/14/rfc-woocommerce-admin-is-merging-into-core/) making this irrelevant soon, a simple fix until then might be to publish a link to the full changelog file on GitHub in the readme.txt changelog section.

### Additional context

Originally reported in WordPress forums https://wordpress.org/support/topic/changelog-192/

**Comment by psealock** [comment]
> With the move of changelog entries from readme.txt to changelog.txt , WordPress no longer displays a Changelog tab in the plugins UI.

WooCommerce Core gets around this by appending only the latest entries of `changelog.txt` into its `readme.txt`. Considering the pending merge to Core, we could close this issue out as this will be handled in that repo.

I wasn't aware however of this consequence so I've added it as an action item in https://github.com/woocommerce/woocommerce/issues/31135

**Comment by joelclimbsthings** [comment]
Closing this as it sounds like it will be handled as we merge into core.
