### ISSUE TITLE
Analytics: Tooltip to inform users that full refunds aren't deducted

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7997]
### Problem to solve
This is a temporary solution to inform users of a potential issue with analytics reporting where full refunds are not deducted from tax or net sales. This issue has been reported [here](https://github.com/woocommerce/woocommerce-admin/issues/7328) and @louwie17 has done research to discover the underlying problem in pbIJXs-Vz-p2. Full refund data is saved in such a way that it's not deducted from these totals, whereas partial refunds are.

### Solution
Additional research is required to determine if it’s a pain point for a large number of users, and it’s a good question for an accounting expert to understand the preferred way of handling refunds.

To solve for this potential confusion in the meantime, a tooltip can appear on the Tax and Net Sales summary number components in **Analytics > Revenue**. Hovering over the icon will bring up the tooltip.

Tooltip copy:
> Full refunds are not deducted from tax or net sales totals

![Refunds and tax totals icon](https://user-images.githubusercontent.com/5121465/144532226-463b92eb-4727-4a5b-9d05-ca52a1db57c7.png)
![Refunds and tax totals tooltip](https://user-images.githubusercontent.com/5121465/144532187-c4b8c666-9ff8-4498-90d0-374c18101202.png)

cc @pmcpinto @becdetat

**Comment by joshuatf** [comment]
Dev note: the `label` prop currently is set to accept a string.  We can either change this to pass in content or we can add a `tooltipText` prop to this component.
