### ISSUE TITLE
The order in Customers doesn't match the actual number of orders from a customer

### ISSUE THREAD

**Issue by tsetend** [woocommerce/woocommerce-admin#7998]
### Describe the bug
When we look at the number of orders for a customer in **WooCommerce > Orders** it doesn't match the number of orders for the customer in **WooCommerce > Customers**.

### To Reproduce

1. Go to 'WooCommerce > Orders'. Make sure you have at least one user with a number of different orders.
2. Filter the order with the customer's email address. 
3. Now open a different tab and open `WooCommerce > Customers` and filter the customer's reports via the customer name or email address.
4. See the differences.

### Screenshots
Screenshot of the order's page: 
![screenshot](https://d.pr/i/7qa6ea+) **Image Link:** https://d.pr/i/7qa6ea
Screeshot of the customer's page: 
![screenshot](https://d.pr/i/RzYGd7+) **Image Link:** https://d.pr/i/RzYGd7

### Expected behavior
The number of orders should match. Looking at the tests, it looks like the report in Customers is showing incorrect.

### Additional context
- I was able to replicate this behavior on my test site as well. For internal ref: 4565988-zen

**Comment by louwie17** [comment]
Hi @tsetend, thanks for creating a bug report for this.
I am currently having trouble replicating this bug. It only seems to be present when the action scheduler hasn't finished it's tasks yet under **WooCommerce > Status > Scheduled Actions**
The customers table is part of the analytics and relies on the scheduled actions having run, this can sometimes take a couple minutes.

Was this the case when you replicated it on your test site?
In the users screenshot it appears that quite a few orders are missing across several months, meaning some of the actions could have failed, are you able to check with the user if there are any failed actions under **WooCommerce > Status > Scheduled Actions** and also if there are many pending one's?

**Comment by joelclimbsthings** [comment]
Closing this for now as it's gone stale, but we can gladly reopen upon getting more information.
