### ISSUE TITLE
E2e Failing on main branch

### ISSUE THREAD

**Issue by puntope** [woocommerce/woocommerce-admin#7999]
### Describe the bug

I'm unable to make E2E pass in a fresh installation of WC Admin + WooCommerce using `main` branch.

### To Reproduce

1. Checkout main
2. `npm i`
3. `composer install`
4.  `npx wc-e2e docker:up`
5.  `px wc-e2e test:e2e`
6. Test didn't pass

### Screenshots

<img width="1150" alt="Screenshot 2021-12-03 at 12 56 26" src="https://user-images.githubusercontent.com/5908855/144598697-ed359a74-c0d0-44c8-9699-95c36debfcf6.png">

### Expected behaviour

1. Checkout main
2. `npm i`
3. `composer install`
4.  `px wc-e2e test:e2e`
5. Test pass

**Comment by louwie17** [comment]
Hi @puntope, thanks for creating an issue for this.
I couldn't re-produce what you are referring to above, although I did encounter an issue where it would be stuck on `Docker container is still being built` as the container failed to build, I am creating a [PR for this](https://github.com/woocommerce/woocommerce-admin/pull/8000).

One reason the tests could be failing is that wc-admin wasn't build yet, before running the tests it will require either a `npm run build` or `npm run start`.
Let me know if either of these were the issue?

**Comment by joelclimbsthings** [comment]
It looks like this is likely resolved, but let us know if none of the above comments did the trick and more information is available.
