### ISSUE TITLE
Inbox 2.0 character limit calculation support for multi-characters Unicode letters

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#8005]
### Describe the bug
Currently, our inbox notes HTML truncator will suffer from miscalculation when handling multi-character Unicode letters. The most common use case would be emojis, such as `🏳️‍🌈` will result in 6 characters count when in fact, it's represented as 1 letter visually. Another common use case would be languages that heavily use combining marks in their letters, such as Hindi's `अनुच्छेद` 8-characters 5 letter word.

Since we're using lodash's truncate, I should also add while it could handle the emoji case correctly, it is still susceptible to this issue as truncating the Hindi word would cut mid-way into the word.

Credits to @rjchow for discovering and surfacing the issue.

### To Reproduce

1. In your local repo, add the following test case to `client/inbox-panel/test/utils.js`:
    ```js
    test( 'it should work with multi-char letters', () => {
      const sampleWithUnicode = '<div>🏳️‍🌈</div>';
      expect( truncateRenderableHTML( sampleWithUnicode, 1 ) ).toBe(
        '<div>🏳️‍🌈</div>'
      );

      const hindiSample = '<div>अनुच्छेद</div>';
      expect( truncateRenderableHTML( hindiSample, 5 ) ).toBe(
      '<div>अनुच्छेद</div>'
      );
    } );
    ```
2. Run `npm run test:client -- client/inbox-panel/test/utils.js`
3. Observe the failed test case

### Suggestions for a fix

@rjchow also raised possible 2 ways to fix this:
1. Using the [grapheme-splitter](https://github.com/orling/grapheme-splitter) library
2. Use [polyfill for a proposed API](https://href.li/?https://www.npmjs.com/package/intl-segmenter-polyfill). However, we may have to add our own dictionaries if we use this.

I should also mention that while we can fix calculating character lengths without too much difficulty, truncating may require additional complexity since we can't simply re-combine letters after we've split them since combining marks may be lost.

Additionally, instead of using lodash's truncate, we'd also have to re-implement the truncate functionality to handle word preserving.

**Comment by chihsuan** [comment]
> since we can't simply re-combine letters after we've split them since combining marks may be lost

@ilyasfoo Are there any sample words you know we would lose combining marks?

Looks like [`grapheme-splitter`](https://github.com/orling/grapheme-splitter#background) will merge combining marks into user-perceived letters. So the joined letters are the same.

> "अनुच्छेद" is comprised of 5 letters and 3 combining marks

> अ + न + ु + च + ् + छ + े + द

> which is in fact just 5 user-perceived letters:

> अ + नु + च् + छे + द

```js
splitter.splitGraphemes("अनुच्छेद"); // returns ["अ","नु","च्","छे","द"]
```

```js
["अ","नु","च्","छे","द"].join('') === "अनुच्छेद" // true
```

**Comment by ilyasfoo** [comment]
@chihsuan Good point, I think the recombined character should just work. I don't remember why I made that point previously 😬
