### ISSUE TITLE
Free extensions list isn't updated after store location and industry is changed

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#8007]
### Describe the bug
In setup wizard, the free-extensions query was not re-queried despite going back to previous steps and changing store location and industry (which both could affect the resulting extensions listed). I think we should invalidate the free extensions state whenever these settings were changed.

### To Reproduce
1. In a new JN site with WooCommerce, install [WCAdmin 3.0.0-beta.1](https://github.com/woocommerce/woocommerce-admin/releases/tag/v3.0.0-beta.1)
1. Go to setup wizard
2. Choose any store location that supports WCPay, such as any state in US
3. In Industry step, make sure to **not** select CBD
4. Proceed through the setup until Business Details step
4. Go to "Free features" tab
5. Observe WooCommerce Payments is displayed in the suggested extensions
6. Without refreshing, go back to Industry step
7. Select CBD industry and click on continue until Business Details step again
8. In the extension list, observe that WooCommerce Payments is still suggested despite selecting CBD as industry

**Comment by joshuatf** [comment]
Also noting that there are many reasons that free extension data should be invalidated.  One easy option (but not necessarily performant) would be to invalidate cache on component mount.
