### ISSUE TITLE
New WooCommerce Navigation: Long Site Title Doesn't Fit Well And Gets Cut Off

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#8011]
Thanks to @zdenys for originally noting this issue!

### Steps to Reproduce

1. Start with an WordPress.com eCommerce Plan site with WooCommerce
2. Set a long site title (example: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`) in My Site → Settings → General → Site Title
3. Navigate to WooCommerce section

### What I expected to happen

Se the entire site title fit weel in the top left corner next to the W logowell

### What actually happened

The site title is cut off both at the beginning and the end, depending on its actual length

For example out of `eCommerce: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.` in my case, only  the middle part `consectetur adipiscing elit, sed do eiusmod tempor incididunt ut` is displayed.

![New WooCommerce Navigation - Long Site Titles Don't Fit Well](https://user-images.githubusercontent.com/39308239/131832106-ea0dce9e-4a66-4d8e-9d5d-4ab20c63155f.png)

![image](https://user-images.githubusercontent.com/39308239/131832200-96a68459-2890-49f4-8506-aedfa8edeffd.png)

### Context

Observed during a Quick Start session 4267078-zd-woothemes

### Operating System

macOS

### OS Version

BigSur 11.5.2

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Atomic

### Console and/or error logs

No

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

Set shorter site titles

### Reproducibility

Consistent

**Comment by joshuatf** [comment]
Thanks for the bug report @zdenys! I'm able to reproduce this issue with the new navigation turned on.

I wonder if truncating the site title with an ellipsis would be appropriate or if the full site title would always be preferred. My concern with displaying a full site title is pushing the rest of the menu out of alignment, but it is certainly an option. cc @pmcpinto @elizaan36

I'm going to move this into the WooCommerce Admin repo where it will be resolved.

**Comment by elizaan36** [comment]
> I wonder if truncating the site title with an ellipsis

**Comment by pmcpinto** [comment]
Truncating is a good solution 👍
