### ISSUE TITLE
[WC 6.0.0-rc.2] After clicking "Install & enable" in the "Enable shipping label printing" step, user is taken back to the task list instead of to the "Connect your store" step.

### ISSUE THREAD

**Issue by rodelgc** [woocommerce/woocommerce-admin#8027]
### Describe the bug
When I was testing the "Set up shipping" task in WC 6.0.0-rc.2, which contains WC Admin 2.9.1, I noticed that after clicking "Install & enable" in the "Enable shipping label printing" step, I was taken back to the task list in the home page instead of being taken to the 4th step "Connect your store". 

In WC 5.9, the user is being taken correctly to the "Connect your store" step after clicking "Install & enable" in the previous step.

### To Reproduce

1. Install WC 6.0.0-rc.2 and complete the onboarding wizard. Make sure that you:
    - Select physical products
    - Do not connect your WooCommerce.com account.
2. You should end up on the task list in home page. Navigate to it if you weren't.
3. Click on the 'Set up shipping' task.
4. Go through each step until you reach the "Enable shipping label printing" step.
5. Click "Install & enable".
6. In WC 5.9, you will be correctly taken to the next step "Connect your store". But here in WC 6.0, notice that you're taken back to the task list right away.

### Actual behavior:
After clicking "Install & enable", I was taken back to the task list instead of to the "Connect your store" step.

### Screenshots

https://user-images.githubusercontent.com/4509348/145421785-ef12954d-4462-437c-b15d-84ec2342e3f1.mov

### Expected behavior
After clicking "Install & enable", I should be taken to the "Connect your store" step just like in WC 5.9.

### Desktop (please complete the following information):

* OS: MacOS
* Browser: FF
* Version 94.0.2 (64-bit)

**Comment by joshuatf** [comment]
Thanks again for taking the time to outline this issue, @rodelgc!

This issue stems from the new task list REST API cache not being invalidated when `No thanks` is clicked.  We'll want to run the `onComplete` prop passed from the task fill when clicking this button as this is considered completion and will both optimistically complete the task and invalidate the cache.

**Comment by chihsuan** [comment]
Closed since this has been fixed in https://github.com/woocommerce/woocommerce-admin/pull/8031
