### ISSUE TITLE
Redirected to setup wizard from Home even after skipped setup

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#8029]
**Describe the bug**
This bug is intermittent and I'm unable to reproduce it reliably. However, I have a pretty good idea of what happens when it does. I also believe this issue had been around for a while. 

I think there's a race condition with `withOnboardingHydration`. There are cases when [`isResolving( 'getProfileItems', [] )`](https://github.com/woocommerce/woocommerce-admin/blob/33967a36c921dc533e24fee20841a155e6c2602c/packages/data/src/onboarding/with-onboarding-hydration.js#L41)  is `true` when another component has intiated resolution for `getProfileItems`.

As a result, both of these [conditions](https://github.com/woocommerce/woocommerce-admin/blob/33967a36c921dc533e24fee20841a155e6c2602c/client/homescreen/index.tsx#L27) will be `null` by the time of its first execution and it immediately redirects to setup wizard, despite having passed an initial value for hydration.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Use Safari browser as I find it to be the only browser where this issue can be observed
2. Open developer console and go to Network tab. Disable cache as I think this may help to reproduce the issue better
2. In a fresh JN site, install WCAdmin 2.9.0-beta.4
3. Skip setup wizard
4. Go to WooCommerce > Home
5. Retry the step above by refreshing may be up to 50 times. You should observe it at least once, redirecting to setup wizard if you've successfully reproduced the issue.

**Comment by peterfabian** [comment]
Moved to admin repo, as I assume that's where it belongs. Please let me know if I'm mistaken.

**Comment by ilyasfoo** [comment]
Thanks! I mistakenly reported in the wrong repo (one of the downfalls of having too many tabs opened).

**Comment by chihsuan** [comment]
@ilyasfoo Do you have any idea why we need both `withOnboardingHydration` and `withSelect` to get the profile items? 

Looks like `withOnboardingHydration` set the profile items from onboarding setting data but  The `getProfileItems()` inside the `withSelect` will still fetch the data via  `/onboarding/profile` API.

I'm trying to inject the `hasFinishedResolution` state to the home component but found that the **initial**`hasFinishedResolution` state is `true` if we use `withOnboardingHydration`.

https://github.com/woocommerce/woocommerce-admin/blob/33967a36c921dc533e24fee20841a155e6c2602c/client/homescreen/index.tsx#L45-L53

**Comment by ilyasfoo** [comment]
>Do you have any idea why we need both withOnboardingHydration and withSelect to get the profile items?

@chihsuan I don't have the full context of how the app evolved around this part, so please take what I'm saying with a grain of salt. If I understand correctly, hydration only serves as an initial population of onboarding data since its settings data is obtained from a global JS variable - so it's theoretically instant.

As for `withSelect`, if I'm not mistaken it's to fetch the latest data because the initial population may be outdated.

**Comment by chihsuan** [comment]
Okay, thanks for your explanation! I confirmed that using `withOnboardingHydration` can make our first-time redirection faster. 

I'll add a `hasFinishedResolution` check to ensure this. I just realized it's normal that the initial `hasFinishedResolution` state is true since it's very fast.
