### ISSUE TITLE
Remove the new user navigation feedback note

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#8043]
We're introducing a new Inbox note to get feedback from existing users of the WooCommerce navigation but there's a previous inbox note asking for feedback from a potentially overlapping audience.

To prevent any annoying overlap for users - there's the potential to get two notes at the same time if your store is >3 months old and you turn on the navigation - we need to remove the note that appears for new users (https://github.com/woocommerce/woocommerce-admin/pull/5475) in favor of the new note that's being implemented for existing users.

@pmcpinto will share more details as needed. I believe since this was implemented in wc-admin there isn't an easier way to remove the note.

**Comment by chihsuan** [comment]
https://github.com/woocommerce/woocommerce-admin/pull/8055 Closed.
