### ISSUE TITLE
Translation files BREAKS date selector

### ISSUE THREAD

**Issue by Warpsmith** [woocommerce/woocommerce-admin#8056]
### Describe the bug

The Swedish translation file is breaking the date selector at WooCommerce->Analytics->Revenue

Also, less important, the date format is hardcoded to US format, instead of following the date format set in the settings.

### To Reproduce

1. Go to: WooCommerce->Analytics->Revenue when using the swedish version.

### Actual behavior:

1. There is no year in the date, only ÅÅÅÅ
2. A year can not be selected, as it only return ÅÅÅÅ

The  reason the WooCommerce translation file is breaking the date selector, is because YYYY have been translated into \u00c5\u00c5\u00c5\u00c5 – and that returns ÅÅÅÅ instead of the actual year.

### Screenshots

This is the bug - ÅÅÅÅ instead of a year.
![NoDate](https://user-images.githubusercontent.com/11083732/146900369-18a6fa00-1a4d-4fc4-8304-bf8acb6f0081.jpg)

A search and replace fixed the problem:
![date-fix](https://user-images.githubusercontent.com/11083732/146900669-c7c8fb8c-3bea-4467-b125-f9b57871dba0.jpg)

After the fix, the expected behavioir:
![NoDate-fixed](https://user-images.githubusercontent.com/11083732/146900736-e39bfb64-b146-4aa6-9071-f48899304368.jpg)

(Although, the date format is still hardcoded to US format.

### Expected behavior

1: I expected to see a year in the date selector.
2: I expected that the date format to be according to the WordPress settings.

### Desktop (please complete the following information):

* OS: OSX 11.6
* Browser Firefox
* Version [e.g. 94.0.2]

### Smartphone (please complete the following information):

* Device: iPhone 12

**Comment by psealock** [comment]
Thanks for the bug report @Warpsmith 

I'm seeing the translation correctly to "YYYY" over at [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/woocommerce-admin/stable/sv/default/?filters%5Bterm%5D=YYYY&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) but perhaps I'm looking in the wrong place.

> I expected that the date format to be according to the WordPress settings.

In the same translation I linked above, it can be edited to the correct format for Swedish.

**Comment by Warpsmith** [comment]
I'm not sure. I don't quite understand that translate site.
The `\u00c5\u00c5\u00c5\u00c5` was found in the .json files in the folder wp-content>languages>plugins

**Comment by moon0326** [comment]
Thank you @Warpsmith for taking the time to report this issue.

I was able to reproduce it on my end. We'll look into it as soon as possible.

@psealock I was able to reproduce it on a JN site. It displays `ÅÅÅÅ` for me as well. I think this is an encoding-related issue. 
![Screen Shot 2021-12-21 at 4 14 22 PM](https://user-images.githubusercontent.com/4723145/147013815-e4c2d11e-df3f-438d-a09a-81b1be5cb515.jpg)

**Comment by Warpsmith** [comment]
I'm not a programmer, but I don't think it has to do with encoding. I think that the server expect to get `YYYY` to which it will return the year. But that some over-ambitious translator changed `YYYY` into `ÅÅÅÅ`, which the server doesn't understand and therefore return unchanged. I believe that `YYYY` shouldn't be translated at all.
That is just my guess though - as I said, I don't know anything about anything.

Any thoughts on the date formatting - why it doesn't pick up the formatting set in the WP settings?

**Comment by moon0326** [comment]
> I'm not a programmer, but I don't think it has to do with encoding. I think that the server expect to get `YYYY` to which it will return the year. But that some over-ambitious translator changed `YYYY` into `ÅÅÅÅ`, which the server doesn't understand and therefore return unchanged. I believe that `YYYY` shouldn't be translated at all. That is just my guess though - as I said, I don't know anything about anything.
> 

Thank you for the insights. We'll look into it further.

> Any thoughts on the date formatting - why it doesn't pick up the formatting set in the WP settings?

I haven't checked it on yet, but we'll make sure to look into it as well and try to support it in the next update.

**Comment by moon0326** [comment]
I've submitted new suggestions on https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/sv/default/?filters%5Bterm%5D=YYYY&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by moon0326** [comment]
The submitted translation has been accepted and the issue has been fixed.
![Screen Shot 2022-02-22 at 4 41 01 PM](https://user-images.githubusercontent.com/4723145/155243977-abe62183-03ff-46cb-8bf5-d13b770632aa.jpg)

**Comment by Warpsmith** [comment]
Awesome! And the hardcoded US date format have been changed to pick up the date formatting from the WordPress settings?

**Comment by moon0326** [comment]
> Awesome! And the hardcoded US date format have been changed to pick up the date formatting from the WordPress settings?

Unfortunately, that has not been fixed yet. We'll need more time to address the date format issue.

I'll create a new issue and link it here soon.
