### ISSUE TITLE
PHP constant throws error in PHP 8

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#8060]
### Describe the bug
Per https://www.php.net/manual/en/function.constant.php, `constant()` throws an error in PHP 8 when the constant is not defined. The place where I found this is https://github.com/woocommerce/woocommerce-admin/blob/main/src/Schedulers/MailchimpScheduler.php#L90. There may be other instances.

### To Reproduce

1. Update your test site to PHP 8.0
2. Load the onboarding profile
3. The following will be logged in the error log
```
CRITICAL Uncaught Error: Undefined constant "WP_ENVIRONMENT_TYPE" in wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/MailchimpScheduler.php:90
```

### Expected behavior
Support for PHP 8.0

**Comment by moon0326** [comment]
Thank you @rrennick for taking the time to report this issue. I was able to reproduce it on my end. We'll look into it as soon as possible.
