### ISSUE TITLE
Allow merchants to remove the WCPayments menu item if they don't want to adopt our product

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#8065]
The welcome page has a “No thanks” button.

![image](https://user-images.githubusercontent.com/9312929/124137527-56cc4f80-dab8-11eb-95f0-db1b0bb9e458.png)

When this button is pressed, the store should no longer display the Payments menu item. Additionally, an exit survey will appear (issue #694).

WC Calypso PR: https://github.com/Automattic/wc-calypso-bridge/pull/706

**Comment by ilyasfoo** [comment]
Potentially done in https://github.com/woocommerce/woocommerce-admin/compare/main...add/8064-add-wc-pay-welcome-screen
