### ISSUE TITLE
Add exit survey to WC Pay welcome screen

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#8066]
An exit survey should display upon clicking "No thanks" on the WC Pay welcome screen.

![image](https://user-images.githubusercontent.com/9312929/124138089-e540d100-dab8-11eb-98e5-328ea4f6414a.png)

The feedback should be collected with a Tracks event.

The approach for the [Customer Effort Score modal](https://github.com/woocommerce/woocommerce-admin/blob/de1c79df0efdac16eb83b337a2ba9cce8b352ae0/packages/customer-effort-score/src/customer-feedback-modal/index.tsx) could be used as a reference.

WC Calypso PR: https://github.com/Automattic/wc-calypso-bridge/pull/704

**Comment by ilyasfoo** [comment]
Potentially done in https://github.com/woocommerce/woocommerce-admin/compare/main...add/8064-add-wc-pay-welcome-screen since I've tested the exit survey modal in the PR
