### ISSUE TITLE
Reuse one of the financial incentives implemented for the new existing store acquisition experiment

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#8067]
Stores that set up WC Pay should have the "no transaction fees for 3 months" promo applied to their account.

WC Calypso issue for more details: https://github.com/automattic/wc-calypso-bridge/issues/689
WC Calypso PR: https://github.com/Automattic/wc-calypso-bridge/pull/705

**Comment by moon0326** [comment]
We need to confirm to see if the promo used in the PR is still active. The promo slug (`wcpay-promo-2021-6-incentive-2`) suggests that it is intended for 2021. We should find out if we want to use a new promo for 2022.

**Comment by ilyasfoo** [comment]
Hi @pmcpinto, do we reuse the same WCPay promo or do we need a new one as @moon0326 mentioned above?

**Comment by ilyasfoo** [comment]
Note: The API is included from the initial migration but needs work to make it work.  https://github.com/woocommerce/woocommerce-admin/pull/8083/files#diff-8a5274bc250a0e698f2589153a55b39c9bd845750ecbb4bd00d948cb37515d6dR128

**Comment by pmcpinto** [comment]
Good question. I think we can reuse the same promo. @thenbrent what do you think?

@ilyasfoo when do you need the answer on this?

**Comment by ilyasfoo** [comment]
@pmcpinto Best to have it by 3rd Jan, since on 4th I'll be including it in Beta 2 for GS testing.

**Comment by pmcpinto** [comment]
> @pmcpinto Best to have it before or by 3rd Jan, since on 4th we'll be including it in Beta 2 for GS testing.

Ok. So let's reuse the same promo. Thanks
