### ISSUE TITLE
Add payments setting

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#8069]
Users should be able to re-enable the Payments menu item after dismissing it with the "No, thanks" button.

A new WooCommerce setting needs to be added  for this called "Payments". We perhaps also need to switch our existing usage of the `wc_calypso_bridge_payments_dismissed` option to use this setting instead?

The exit survey states:

> This will remove WooCommerce Payments from the navigation. In order to enable it again, go to WooCommerce Settings > Payments

WC Calypso Bridge PR: https://github.com/Automattic/wc-calypso-bridge/pull/708

**Comment by ilyasfoo** [comment]
Potentially done in https://github.com/woocommerce/woocommerce-admin/compare/main...add/8064-add-wc-pay-welcome-screen since this task is simply text in the exit survey modal
