### ISSUE TITLE
Add capability for ExPlat integration to authenticate WPCOM users

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#8071]
### Description

Related P2 comment: pbmo2S-Un-p2#comment-2135

Our current implementation of ExPlat integration only supports anonymous users. We should add the capability to authenticate WPCOM users to support experiments that require it.

Optimally, this capability should be added to both JS and PHP implementation of ExPlat integration.

**Comment by ilyasfoo** [comment]
@pmcpinto This issue intends to add support for `New logged-in users only` audience filter in ExPlat. Do you think this is a need? Otherwise we could close this.

**Comment by pmcpinto** [comment]
Hey Ilyas, I think we should leave this one open. Eventually, we'll need to add this support in the future.

**Comment by chihsuan** [comment]
Looks like we need to retrieve a wp.com id and use it if available.

**PHP:**
https://github.com/woocommerce/woocommerce-admin/blob/281ae241d0c6d15f696c74cd6bd28294dee16a0f/includes/class-experimental-abtest.php#L158-L162

**JS:**
https://github.com/woocommerce/woocommerce-admin/blob/281ae241d0c6d15f696c74cd6bd28294dee16a0f/packages/explat/src/assignment.ts#L21-L29

From my understanding, we need to use the [getme API](https://developer.wordpress.com/docs/api/1.1/get/me/) to retrieve the wpcom user id but it requires an access token.

@ilyasfoo or @woocommerce/ghidorah Do you happen to know to get the access token or another way to get wpcom user id?  And I also would like to confirm should we add a new argument `"wpcom_id"` or overwrite the `anon_id`?

**Comment by ilyasfoo** [comment]
>From my understanding, we need to use the [getme API](https://developer.wordpress.com/docs/api/1.1/get/me/) to retrieve the wpcom user id but it requires an access token.

@chihsuan If I recall correctly, we only need an access token, so we don't have to call getme API to get the user ID as that would be redundant. 

> Do you happen to know to get the access token or another way to get wpcom user id?

For PHP, we can try to leverage Jetpack's methods for getting the token I've looked a bit at Jetpack's Connection Manager and I found a deprecated method to get the current user's access token [here](https://github.com/Automattic/jetpack-connection/blob/c4f0397109fc93765406eeee37b347e214792e5c/src/class-manager.php#L2173-L2176). I assume we can now use something like `$jetpack_connection_manager->get_tokens()->get_access_token()` to get the token. For your reference, [this is an example of us using Jetpack's class](https://github.com/woocommerce/woocommerce-admin/blob/0d303e7c7e89837c674fa491bd2f217a7ac46f05/src/API/OnboardingProfile.php#L185-L192).

We can try to use that and obtain the token and then pass it in `authorization` in request header.

For JS, I'm thinking we could pass the token from PHP to JS somehow. Though it could be somewhat exposed if we do it that way. Another way is to try to obtain it via REST API, but will have some performance impact.

>And I also would like to confirm should we add a new argument "wpcom_id" or overwrite the anon_id?

Nope, we'll have to pass user's token via the Auth header. Curl example:
```
curl \
 -H 'authorization: [auth_token_here]' \
 'https://public-api.wordpress.com/rest/v1/me/' 
```

**Comment by ilyasfoo** [comment]
>From my understanding, we need to use the [getme API](https://developer.wordpress.com/docs/api/1.1/get/me/) to retrieve the wpcom user id but it requires an access token.

@chihsuan If I recall correctly, we only need an access token, so we don't have to call getme API to get the user ID as that would be redundant. 

> Do you happen to know to get the access token or another way to get wpcom user id?

For PHP, we can try to leverage Jetpack's methods for getting the token. I've looked a bit at Jetpack's Connection Manager and I found a deprecated method to get the current user's access token [here](https://github.com/Automattic/jetpack-connection/blob/c4f0397109fc93765406eeee37b347e214792e5c/src/class-manager.php#L2173-L2176). I assume we can now use something like `$jetpack_connection_manager->get_tokens()->get_access_token()` to get the token. For your reference, [this is an example of us using Jetpack's class](https://github.com/woocommerce/woocommerce-admin/blob/0d303e7c7e89837c674fa491bd2f217a7ac46f05/src/API/OnboardingProfile.php#L185-L192).

For JS, I'm thinking we could pass the token from PHP to JS somehow. Though it could be somewhat exposed if we do it that way. Another way is to try to obtain it via REST API, but will have some performance impact.

>And I also would like to confirm should we add a new argument "wpcom_id" or overwrite the anon_id?

Nope, we'll have to pass user's token via request's `authorization` header.

**Comment by ilyasfoo** [comment]
@chihsuan I also want to add that it'll be more practical for you to test this with a sandbox. After setting that up, you could try to output the current authorized user to see if the request with auth works.

**Comment by chihsuan** [comment]
@ilyasfoo Thanks for providing more details! I'll check the links and set up the sandbox environment as you mentioned. 😃

**Comment by chihsuan** [comment]
I just unassigned myself and decided to have a break from working on issues and exploring the P2 posts first!

**Comment by chihsuan** [comment]
@ilyasfoo I've checked the Jetpack's [`get_access_token()`](https://github.com/Automattic/jetpack-connection/blob/master/src/class-tokens.php#L359). 🙌  

Looks like we cannot directly send the access token to wpcom because it requires [signing the request](https://github.com/Automattic/jetpack/blob/8f061c955bc87bf658a20c8e0fd594e62747ee29/projects/packages/connection/src/class-client.php#L56-L68
) first and we cannot use [`get_signed_token`](https://github.com/Automattic/jetpack-connection/blob/master/src/class-tokens.php#L522) either because it doesn't sign the arguments. 

However, I found we can call [`wpcom_json_api_request_as_user()`](https://github.com/Automattic/jetpack/blob/8f061c955bc87bf658a20c8e0fd594e62747ee29/projects/packages/connection/src/class-client.php#L394-L411) directly. WCPay also use it [here](https://github.com/Automattic/woocommerce-payments/blob/95c6c95f73bd68a0bece0baa14c2a81549856496/includes/wc-payment-api/class-wc-payments-http.php#L95).

For JS, I think we could probably create a proxy REST API that forwards the arguments to `wpcom_json_api_request_as_user`. So front end doesn't send requests to WPCOM directly but to backend instead. I think it's not worth implementing the signing parts in JS since then we need to maintain it and passing the token to JS might tend to have security issues.

What do you think?

**Comment by ilyasfoo** [comment]
You're right @chihsuan! Sorry I misunderstood before, it seems the access token obtained from Jetpack is not WPCOM's oauth access token, but it's Jetpacks' own authentication method.

>However, I found we can call [wpcom_json_api_request_as_user()](https://github.com/Automattic/jetpack/blob/8f061c955bc87bf658a20c8e0fd594e62747ee29/projects/packages/connection/src/class-client.php#L394-L411) directly. WCPay also use it [here](https://github.com/Automattic/woocommerce-payments/blob/95c6c95f73bd68a0bece0baa14c2a81549856496/includes/wc-payment-api/class-wc-payments-http.php#L95).

That's an excellent find! It seems like this is a more natural way to go too.

>For JS, I think we could probably create a proxy REST API that forwards the arguments to wpcom_json_api_request_as_user. So front end doesn't send requests to WPCOM directly but to backend instead. I think it's not worth implementing the signing parts in JS since then we need to maintain it and passing the token to JS might tend to have security issues.

I agree. With the performance implication of proxy request, I'm thinking JS auth should be optional since I suspect there would be cases where auth isn't as important as waiting to render the UI. Do you think it'll be okay to implement it that way?

**Comment by chihsuan** [comment]
>  I'm thinking JS auth should be optional since I suspect there would be cases where auth isn't as important as waiting to render the UI. Do you think it'll be okay to implement it that way?

Yes, sounds good to me! 

I just checked the code and found that `fetchExperimentAssignment ` is passed as a config to `exPlatClient`.

https://github.com/woocommerce/woocommerce-admin/blob/51877a5476ac91592ac95461945a312479f2fe60/packages/explat/src/index.ts#L30-L35


So I think we need to create another `exPlatClient` like this:

```js
const exPlatAuthClient = createExPlatClient( {
	fetchExperimentAssignmentWithAuth,
	getAnonId,
	logError,
	isDevelopmentMode,
} );

export const {
	loadExperimentAssignmentWithAuth,
	dangerouslyGetExperimentAssignmentWithAuth,
} = exPlatAuthClient;

export const {
	useExperimentWithAuth,,
	ExperimentWithAuth,,
	ProvideExperimentDataWithAuth,,
} = createExPlatClientReactHelpers( exPlatAuthClient );
```

```js
// To use it
import { useExperimentWithAuth } from '@woocommerce/explat';

const [ isLoadingExperiment, experimentAssignment ] = useExperimentWithAuth(
		'woocommerce_tasklist_progression'
	);
```

Let me know if you have other thoughts. Thanks!

**Comment by ilyasfoo** [comment]
@chihsuan That looks good to me
