### ISSUE TITLE
Change the reviews empty state panels logic

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8074]
**Description:** we're display the Reviews empty state panel when publishedProductCount > 0 && reviewsEnabled === 'yes'. Showing the Reviews empty state before receiving a review can be confusing, especially because we have stricter conditions to show the orders and inventory empty state panels.

**Acceptance criteria:**
- [ ] Update the Reviews panel condition to only be visible after getting the 1st review

**Comment by pmcpinto** [comment]
@joelclimbsthings I'm not sure when this regression was introduced. But if possible, it would be great to have it fixed on wc admin 3.0/wc core 6.1.

Let me know if it's doable. Thanks!

**Comment by octaedro** [comment]
Hi @pmcpinto,

I'll cut the `WC-Admin 3.0` final release on Tuesday.

I'm taking a look at this bug but I'm not sure that I understood it correctly.
As far as I know, the panels will be shown only when they [have something to show](https://github.com/woocommerce/woocommerce-admin/pull/5552#issuecomment-724041280).

The Orders panel will be shown [when `totalOrderCount > 0`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/panels.js#L29), the Stock panel will be shown [when `totalOrderCount > 0 && publishedProductCount > 0 && manageStock === 'yes'`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/panels.js#L43-L45) and the Reviews panel will be [visible when `publishedProductCount > 0 && reviewsEnabled === 'yes'`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/panels.js#L58-L59). 

Is that behavior incorrect?
Sorry if I missed something.

**Comment by pmcpinto** [comment]
Ah you're right. I've got confused because I was testing the task list flow and the Reviews panel empty state was displayed right after I dismissed the setup task list.

@jarekmorawski do you agree with this logic?

**Comment by jarekmorawski** [comment]
Yes, that makes sense. Following the logic originally suggested by Elizabeth, we want the panels to show up for the first time when we've got some information to display (an unfulfilled order or unpublished review), then show the empty state once the user clears the content (fulfills the order or publishes a review). In other cases, the panels should not be visible.

**Comment by pmcpinto** [comment]
> Yes, that makes sense. Following the logic originally suggested by Elizabeth, we want the panels to show up for the first time when we've got some information to display (an unfulfilled order or unpublished review), then show the empty state once the user clears the content (fulfills the order or publishes a review). In other cases, the panels should not be visible.

@jarekmorawski thanks for the feedback. What do you think about tweaking the logic of the Reviews panel? I feel it's a bit weird to show the Reviews panel empty state before getting any review. cc @octaedro for additional feedback

**Comment by jarekmorawski** [comment]
> I feel it's a bit weird to show the Reviews panel empty state before getting any review

Yes, definitely. If we're not showing Orders and Stock, we shouldn't show the Reviews, either. Ideally, it'd appear only when the first review is added.

**Comment by pmcpinto** [comment]
@octaedro I've updated the issue title and description to match our request. LMK if you have questions

**Comment by octaedro** [comment]
Thank you @pmcpinto for updating this issue.
Is it ok if we add this change to `WC-Admin 3.1` (the `beta.1` was released a week ago) or could it wait until `3.2`?

**Comment by pmcpinto** [comment]
Hey @octaedro it can wait until 3.2. Thanks!
