### ISSUE TITLE
sucuri and woocommerce incompatability

### ISSUE THREAD

**Issue by danemaster00** [woocommerce/woocommerce-admin#8076]
I can access wocommerce > orders
and marketing > coupons  
both from left side panel

but if I try to enter any other area such as analytics or woocommerce >home, I get 502 errors in my browser
this is the only plugin that generates these issues

all plugins disabled except for sucuri security - lastest version
wordpress multiside - addon domain and primary domain same issue
theme is "hello elementor"... also tried "storefront" to see the same issue

wordpress
<html><body>

Version | 5.8.2
-- | --
Site Language | en_US
User Language | en_US
Timezone | America/Chicago
Home URL | https://copathing.com
Site URL | https://copathing.com
Permalink structure | /%category%/%postname%/
Is this site using HTTPS? | Yes
Is this a multisite? | Yes
Can anyone register on this site? | No
Is this site discouraging search engines? | Yes
Default comment status | Open
Environment type | production
User count | 1
Site count | 2
Network count | 1
Communication with WordPress.org | WordPress.org is reachable

</body>
</html>

server
<html><body>

Server architecture | Linux 2.6.32-954.3.5.lve1.4.82.el6.x86_64 x86_64
-- | --
Web server | Apache
PHP version | 8.0.13 (Supports 64bit values)
PHP SAPI | litespeed
PHP max input variables | 1000
PHP time limit | 30
PHP memory limit | 128M
PHP memory limit (only for admin screens) | 256M
Max input time | 60
Upload max filesize | 32M
PHP post max size | 32M
cURL version | 7.71.0 OpenSSL/1.1.1d
Is SUHOSIN installed? | No
Is the Imagick library available? | Yes
Are pretty permalinks supported? | Yes
.htaccess rules | Custom rules have been added to your .htaccess file.

</body>
</html>

database
<html><body>

Extension | mysqli
-- | --
Server version | 5.7.36-cll-lve
Client version | 5.7.36

</body>
</html>

my htaccess is super standard

# BEGIN WP Rocket v3.9.3
# Use UTF-8 encoding for anything served text/plain or text/html
AddDefaultCharset UTF-8
# Force UTF-8 for a number of file formats
<IfModule mod_mime.c>
AddCharset UTF-8 .atom .css .js .json .rss .vtt .xml
</IfModule>

# FileETag None is not enough for every server.
<IfModule mod_headers.c>
Header unset ETag
</IfModule>

# Since we’re sending far-future expires, we don’t need ETags for static content.
# developer.yahoo.com/performance/rules.html#etags
FileETag None

<IfModule mod_alias.c>
<FilesMatch "\.(html|htm|rtf|rtx|txt|xsd|xsl|xml)$">
<IfModule mod_headers.c>
Header set X-Powered-By "WP Rocket/3.9.3"
Header unset Pragma
Header append Cache-Control "public"
Header unset Last-Modified
</IfModule>
</FilesMatch>

<FilesMatch "\.(css|htc|js|asf|asx|wax|wmv|wmx|avi|bmp|class|divx|doc|docx|eot|exe|gif|gz|gzip|ico|jpg|jpeg|jpe|json|mdb|mid|midi|mov|qt|mp3|m4a|mp4|m4v|mpeg|mpg|mpe|mpp|otf|odb|odc|odf|odg|odp|ods|odt|ogg|pdf|png|pot|pps|ppt|pptx|ra|ram|svg|svgz|swf|tar|tif|tiff|ttf|ttc|wav|wma|wri|xla|xls|xlsx|xlt|xlw|zip)$">
<IfModule mod_headers.c>
Header unset Pragma
Header append Cache-Control "public"
</IfModule>
</FilesMatch>
</IfModule>

# Expires headers (for better cache control)
<IfModule mod_expires.c>
	ExpiresActive on
	ExpiresDefault                              "access plus 1 month"
	# cache.appcache needs re-requests in FF 3.6 (thanks Remy ~Introducing HTML5)
	ExpiresByType text/cache-manifest           "access plus 0 seconds"
	# Your document html
	ExpiresByType text/html                     "access plus 0 seconds"
	# Data
	ExpiresByType text/xml                      "access plus 0 seconds"
	ExpiresByType application/xml               "access plus 0 seconds"
	ExpiresByType application/json              "access plus 0 seconds"
	# Feed
	ExpiresByType application/rss+xml           "access plus 1 hour"
	ExpiresByType application/atom+xml          "access plus 1 hour"
	# Favicon (cannot be renamed)
	ExpiresByType image/x-icon                  "access plus 1 week"
	# Media: images, video, audio
	ExpiresByType image/gif                     "access plus 4 months"
	ExpiresByType image/png                     "access plus 4 months"
	ExpiresByType image/jpeg                    "access plus 4 months"
	ExpiresByType image/webp                    "access plus 4 months"
	ExpiresByType video/ogg                     "access plus 4 months"
	ExpiresByType audio/ogg                     "access plus 4 months"
	ExpiresByType video/mp4                     "access plus 4 months"
	ExpiresByType video/webm                    "access plus 4 months"
	# HTC files  (css3pie)
	ExpiresByType text/x-component              "access plus 1 month"
	# Webfonts
	ExpiresByType font/ttf                      "access plus 4 months"
	ExpiresByType font/otf                      "access plus 4 months"
	ExpiresByType font/woff                     "access plus 4 months"
	ExpiresByType font/woff2                    "access plus 4 months"
	ExpiresByType image/svg+xml                 "access plus 1 month"
	ExpiresByType application/vnd.ms-fontobject "access plus 1 month"
	# CSS and JavaScript
	ExpiresByType text/css                      "access plus 1 year"
	ExpiresByType application/javascript        "access plus 1 year"
</IfModule>
# Gzip compression
<IfModule mod_deflate.c>
# Active compression
SetOutputFilter DEFLATE
# Force deflate for mangled headers
<IfModule mod_setenvif.c>
<IfModule mod_headers.c>
SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
# Don’t compress images and other uncompressible content
SetEnvIfNoCase Request_URI \
\.(?:gif|jpe?g|png|rar|zip|exe|flv|mov|wma|mp3|avi|swf|mp?g|mp4|webm|webp|pdf)$ no-gzip dont-vary
</IfModule>
</IfModule>

# Compress all output labeled with one of the following MIME-types
<IfModule mod_filter.c>
AddOutputFilterByType DEFLATE application/atom+xml \
		                          application/javascript \
		                          application/json \
		                          application/rss+xml \
		                          application/vnd.ms-fontobject \
		                          application/x-font-ttf \
		                          application/xhtml+xml \
		                          application/xml \
		                          font/opentype \
		                          image/svg+xml \
		                          image/x-icon \
		                          text/css \
		                          text/html \
		                          text/plain \
		                          text/x-component \
		                          text/xml
</IfModule>
<IfModule mod_headers.c>
Header append Vary: Accept-Encoding
</IfModule>
</IfModule>

# END WP Rocket

<IfModule mod_headers.c>
Header set Strict-Transport-Security "max-age=300; includeSubDomains; preload"
Header always set Content-Security-Policy "upgrade-insecure-requests"
</IfModule>

# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^wp-admin$ wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^(wp-(content|admin|includes).*) $1 [L]
RewriteRule ^(.*\.php)$ $1 [L]
RewriteRule . index.php [L]

# END WordPress
# BEGIN ShortPixel Adaptive Images
# The directives (lines) between "BEGIN ShortPixel Adaptive Images" and "END ShortPixel Adaptive Images" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.

# END ShortPixel Adaptive Images
# BEGIN ShortPixelWebp
# The directives (lines) between "BEGIN ShortPixelWebp" and "END ShortPixelWebp" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.

# END ShortPixelWebp

**Comment by danemaster00** [comment]
![image](https://user-images.githubusercontent.com/85789369/147198605-2c410925-c636-4a76-a7e3-0b0e7106d55c.png)

**Comment by danemaster00** [comment]
![image](https://user-images.githubusercontent.com/85789369/147198743-19b620b6-1619-4d72-be95-36d02220b73c.png)

**Comment by danemaster00** [comment]
woocommerce 6.0.0 is the one giving me issues
woocommerce 4.1.3 IS working with my website.
now im trying to find the most recent iteration which does not generate 502

**Comment by moon0326** [comment]
Hi @danemaster00 

Thank you for taking the time to report this issue.

Unfortunately, I wasn't able to reproduce the issue on my end.

I installed the latest WordPress + WooCommerce + Sucuri Security - Auditing, Malware Scanner and Hardening. However, I was still able to access all my pages.

 It would be helpful to investigate the issue if you could provide us the system report from WooCommerce -> Status

**Comment by danemaster00** [comment]
> Hi @danemaster00
> 
> Thank you for taking the time to report this issue.
> 
> Unfortunately, I wasn't able to reproduce the issue on my end.
> 
> I installed the latest WordPress + WooCommerce + Sucuri Security - Auditing, Malware Scanner and Hardening. However, I was still able to access all my pages.
> 
> It would be helpful to investigate the issue if you could provide us the system report from WooCommerce -> Status

are you using multipress?

**Comment by danemaster00** [comment]
interestingly it seems woocommerce is not alone on these issues.
gutenberg ultimate addons (templates) and alot of other imported templates from random gutenberg plugins, when imported to my page and saved, are causing the edit of the page to instantly hit a 502 error.

Its quite interesting that elementor templates arent having this issue. its quite strange and not sure what to do about it. 
but its definitely something regarding a basic firewall on the DNS's as I explain above.
no complicated forward stuff either, just https on a firewall.

**Comment by moon0326** [comment]
@danemaster00 sorry for the delay in response.

It's really hard for us to replicate the environment on our end. I understand that you have provided the setup, but there are a lot of other things involved in a server.

It sounds like this might not be related to WooCommerce at all when other plugins have the same problem. 502 gateway usually means server-side errors.

Have you checked your server log? You should have some errors related to 502 errors. I think we should find out the detailed error message before moving forward.

**Comment by joelclimbsthings** [comment]
So far this sounds like it may be a server-side issue that we cannot address on our end, so I'm closing for now.
