### ISSUE TITLE
Add Inbox note: WCPay - Remind me later

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#8077]
This note will be a reminder for users that view the Welcome screen in [#744](https://github.com/Automattic/wc-calypso-bridge/issues/744), then navigate away without installing WCPay.

Title: Save big with WooCommerce Payments
Content: Save up to 50% in fees by managing transactions in WooCommerce Payments. With WooCommerce Payments, you can securely accept major cards, Apple Pay, and payments in over 100 currencies.
Segmentation: Ecom and Business plan customers, Don't have WCPay installed, Haven't dismissed welcome screen
Timing: 3 days after viewing the WCPay welcome screen
Cadence: once
CTA leads to: Payments > Welcome screen
CTA label: Learn more

WC Calypso Bridge PR: https://github.com/Automattic/wc-calypso-bridge/pull/756

**Comment by moon0326** [comment]
Closing as the change has been merged.
