### ISSUE TITLE
WC Pay promotion error in PHP 8.0

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#8080]
### Describe the bug

We are seeing the following error on our PHP 8.0 smoke testing site:

```
RITICAL Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given in wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/WcPayPromotion/WCPaymentGatewayPreInstallWCPayPromotion.php:30
```

The `$wc_pay_spec` variable is used without being checked to confirm it is an object in https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/WcPayPromotion/WCPaymentGatewayPreInstallWCPayPromotion.php#L29:L33.

### To Reproduce

1. Update to PHP 8.0
2. Activate WooCommerce
3. Visit a WooCommerce page
4. The error above should be logged in the error log

**Comment by moon0326** [comment]
Howdy @rrennick  👋 

Thank you for taking the time to report this bug.

I wasn't able to reproduce it with the stopes provided, but I can see that the code potentially error out when `Init::get_wc_pay_promotion_spec()` returns non-object.

it's possible to get null or an empty array when one of the rules defined in `https://woocommerce.com/wp-json/wccom/payment-gateway-suggestions/1.0/payment-method/promotions.json` does not pass. 

We'll look into it further.

**Comment by rrennick** [comment]
> I wasn't able to reproduce it with the stopes provided

@moon0326 Sorry I wasn't able to provide accurate steps. We are getting the error in an E2E script that is updating the plugin using the dashboard plugin update screen. That may be triggering an attempt to create a note. I had hoped going to a WC screen would produce the same error. The E2E log doesn't provide any useful info to indicate which step is triggering the error.
