### ISSUE TITLE
Fatal Error Attempting to Log In to Admin

### ISSUE THREAD

**Issue by catsma97504** [woocommerce/woocommerce-admin#8082]
Unable to log directly into the Admin side with my username and password.  I get a fatal error.  However, I can log in through the store and use the Admin Toolbar to access the Admin Dashboard and then manage my site.

To reproduce, simply attempt to log in directly to wp-admin.php

Fatal Error:
PHP Fatal error: Uncaught Error: Call to undefined function wc_empty_cart() in /nas/content/live/everythingaq/wp-content/plugins/woocommerce/includes/class-wc-session-handler.php:300\nStack trace:\n#0 /nas/content/live/everythingaq/wp-content/plugins/woocommerce/includes/class-wc-session-handler.php(291): WC_Session_Handler->forget_session()\n#1 /nas/content/live/everythingaq/wp-content/plugins/woocommerce-wholesale-prices-premium/includes/class-wwpp-wholesale-login-logout.php(138): WC_Session_Handler->destroy_session()\n#2 /nas/content/live/everythingaq/wp-includes/class-wp-hook.php(303): WWPP_Wholesale_Login_Logout->initialize_session_and_cart('')\n#3 /nas/content/live/everythingaq/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)\n#4 /nas/content/live/everythingaq/wp-includes/plugin.php(470): WP_Hook->do_action(Array)\n#5 /nas/content/live/everythingaq/wp-settings.php(600): do_action('wp_loaded')\n#6 /nas/content/live/everythingaq/wp-config.php(117): require_once('/nas/content/li...')\n#7 /nas/content/live/eve in /nas/content/live/everythingaq/wp-content/plugins/woocommerce/includes/class-wc-session-handler.php on line 300, referer: https://everythingaq.wpengine.com/wp-login.php?redirect_to=https%3A%2F%2Feverythingaq.wpengine.com%2Fwp-admin%2F&reauth=1

Expected behavior, to actually log in directly to the Admin side

### Desktop (please complete the following information):

* OS: Windows 10
* Browser Firefox 95.0.2

### Smartphone (please complete the following information):

* Device: Samsung Galaxy Note 10
* OS: Android 11
* Browser Firefox Mobile, Chrome

Doesn't matter which device or browser is used.

**Comment by moon0326** [comment]
Hi @catsma97504,

Thank you for taking the time to report this issue. Unfortunately, I was not able to reproduce it on my end.

Could you give me more details on how to reproduce it?

Could you also disable your plugins, except WooCommerce, and see if it works? 

It would be also helpful if you can provide us with the system status report. You can retrieve it on WooCommerce -> Status page.

**Comment by catsma97504** [comment]
Here are the steps I take when attempting to log into Admin....

1.  Navigate to /wp-admin which takes me to the login screen at wp-login.php
2. Click the Login with Username and Password link
3. Enter my Username and Password and click the Remember Me box
4. Click the Login Button and get the error

After disabling all plugins, except for WooCommerce, I am able to login to Admin.  Now to figure out where the conflict is occurring. 

Status Report.....
`
### WordPress Environment ###

WordPress address (URL): https://everythingaq.wpengine.com
Site address (URL): https://everythingaq.wpengine.com
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.26
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.35-38-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 76.00MB
Database Data Size: 48.51MB
Database Index Size: 27.49MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.17MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acfw_virtual_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 1.47MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.05MB + Index: 1.31MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_braapf_product_stock_status_parent: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_braapf_product_variation_attributes: Data: 0.23MB + Index: 0.45MB + Engine InnoDB
wp_braapf_term_taxonomy_hierarchical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_variable_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_braapf_variation_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
wp_ebay_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_auctions: Data: 2.19MB + Index: 0.17MB + Engine InnoDB
wp_ebay_categories: Data: 2.52MB + Index: 3.33MB + Engine InnoDB
wp_ebay_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_log: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_ebay_messages: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_ebay_orders: Data: 4.52MB + Index: 0.03MB + Engine InnoDB
wp_ebay_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_profiles: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_ebay_shipping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_sites: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_ebay_stocks_log: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
wp_ebay_store_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ebay_transactions: Data: 3.52MB + Index: 0.05MB + Engine InnoDB
wp_et_divi_ab_testing_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.42MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.30MB + Index: 0.31MB + Engine InnoDB
wp_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 12.52MB + Index: 13.02MB + Engine InnoDB
wp_posts: Data: 1.48MB + Index: 0.64MB + Engine InnoDB
wp_rednao_wc_invoice: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rednao_wc_invoices_created: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rednao_wc_invoices_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.50MB + Index: 0.84MB + Engine InnoDB
wp_users: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.28MB + Index: 0.56MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfpklist_template_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

apifw_inv_templates: 1
attachment: 467
br_product_filter: 1
custom_css: 2
customize_changeset: 4
et_pb_layout: 13
ibfw_product_label: 1
nav_menu_item: 26
page: 11
post: 2
product: 156
product_variation: 1827
revision: 31
shipping_package: 4
shop_coupon: 18
shop_order: 709
shop_order_refund: 16
wc_conditional_fee: 6
wc_membership_plan: 4
wcpb_product_badge: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

ManageWP - Worker: by GoDaddy – 4.9.12
WooCommerce Enable Reviews - Bulk Edit: by Mário Valney – 1.0.0
Advanced Coupons for WooCommerce Free: by Rymera Web Co – 3.0.2
Advanced Coupons for WooCommerce Premium: by Rymera Web Co – 3.0.3
Akismet Anti-Spam: by Automattic – 4.2.1
Cost of Goods for WooCommerce Pro: by WPFactory – 2.4.9
Creative Mail by Constant Contact: by Constant Contact – 1.4.8
Divi Booster: by Dan Mossop – 3.6.8
Divi Logo Swap: by Tim Strifler – 1.0
Divi Rocket: by Divi Space – 1.0.48
Enhanced Media Library: by wpUXsolutions – 2.8.8
Flexible Shipping UPS: by WP Desk – 1.17.2
GA Google Analytics: by Jeff Starr – 20210719
Jetpack: by Automattic – 10.4
Mailchimp for WooCommerce: by Mailchimp – 2.5.4
Members: by MemberPress – 3.1.6
PW WooCommerce Bulk Edit: by Pimwick
LLC – 2.92

PW WooCommerce Gift Cards: by Pimwick
LLC – 1.196

Fixed Widget: by Thomas Maier
Max Bond – 5.3.0

Product Badges: by 99w – 2.1.5
Widget Context: by Kaspars Dambis – 1.3.2
Widget Importer & Exporter: by ChurchThemes.com – 1.6
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.8
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.6.1.1
WooCommerce Dynamic Pricing: by Element Stark – 3.1.26
WooCommerce PayPal Payments: by WooCommerce – 1.6.3
WooCommerce USPS Shipping: by WooCommerce – 4.4.68
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.48
WooCommerce Square: by WooCommerce – 2.7.0
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27.1
WooCommerce Wholesale Prices: by Rymera Web Co – 1.16
WooCommerce: by Automattic – 6.0.0
WP-Lister Pro for eBay: by WP Lab – 3.1.2
LiveChat: by LiveChat – 4.5.3
Smush Pro: by WPMU DEV – 3.8.8

### Inactive Plugins (0) ###


### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (10) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.1.2
Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
ManageWP - Worker Loader: by GoDaddy –
SSO: by Garth Mortensen
Mike Hansen – 0.3

WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.5
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #173905 - /shop/
Cart: #173906 - /cart/
Checkout: #15 - /checkout/
My account: #173907 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi
Version: 4.14.4
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Action Scheduler ###

Canceled: 1
Oldest: 2021-12-17 05:49:48 -0800
Newest: 2021-12-17 05:49:48 -0800

Complete: 4,027
Oldest: 2021-11-22 21:53:14 -0800
Newest: 2021-12-23 19:24:13 -0800

Failed: 1
Oldest: 2021-08-30 17:03:46 -0700
Newest: 2021-08-30 17:03:46 -0700

Pending: 4
Oldest: 2021-12-23 20:23:42 -0800
Newest: 2021-12-30 08:22:19 -0800


### Status report information ###

Generated at: 2021-12-23 20:24:27 -08:00
`

**Comment by moon0326** [comment]
@catsma97504 Thank you for providing the details 👍 

It looks like one of the plugins is causing the problem.

Could you enable other plugins one by one and find what's causing the error?

if it's one of our official plugins, we may be able to help.

**Comment by catsma97504** [comment]
Turned out to be the Wholesale plugin was the cause.  Figured out what was in conflict and got everything again working.  Sorry for the late response.  Been busy updating my site.
