### ISSUE TITLE
WooCommerce Docs link on the help menu does not work

### ISSUE THREAD

**Issue by chihsuan** [woocommerce/woocommerce-admin#8096]
### Describe the bug

When clicking the WooCommerce Docs link on the help menu of WooCommerce Admin, it redirects the page to https://woocommerce.com/?utm_source=help_panel&utm_medium=product instead of https://woocommerce.com/documentation/.

### To Reproduce

1. Go to /wp-admin/admin.php
2. Click the WooCommerce Docs  link on the Help menu

### Actual behavior:

 It redirects the page to ‘https://woocommerce.com/’ 

### Screenshots

![Screen Shot 2021-12-29 at 16 10 11](https://user-images.githubusercontent.com/4344253/147640892-e26fd810-090a-45d6-b025-98ea2376dd63.png)

### Expected behavior

redirect to https://woocommerce.com/documentation

### Additional context

Details: p1640760538072300-slack-C4E0DVDB2 | pb22l9-14Q-p2#comment-1085

**Comment by ilyasfoo** [comment]
Great catch on this one, @chihsuan! I think the best use of our effort here is to replace all old `docs.woocommerce.com` links with `woocommerce.com/documentation` since it looks the old domain is deprecated.
