### ISSUE TITLE
Cannot access Settings->Checkout after update to version 3.0.0

### ISSUE THREAD

**Issue by jakub50** [woocommerce/woocommerce-admin#8097]
### Describe the bug
**I have Czech localization** and so some error messages might be wrongly translated back into English.
The bug appeared after the update to version 3.0.0.

### To Reproduce
1.] Go to WooCommerce -> Settings -> Checkout
2.] Critical error page appears.

It is also impossible to make an order, which results in red message Internal server error in the last step.
When I try to modify any page and click on update button I see red message update failed.

### Screenshots
![image](https://user-images.githubusercontent.com/57262914/147652936-7b027648-6147-47dc-9550-036fa3449889.png)
![image](https://user-images.githubusercontent.com/57262914/147652673-74541772-a403-43d0-92f7-18fa7bd42447.png)
![image](https://user-images.githubusercontent.com/57262914/147652685-a9598c49-1ea8-4f45-b092-3121c0340d22.png)

### Expected behavior
Checkout to load correctly, orders to be created correctly and updates of pages to work.

### Desktop (please complete the following information):

* OS: Kubuntu
* Browser Firefox
* Version 95.0.1

### Smartphone (please complete the following information):

* Device: Motorola Moto G9 Plus 6/128GB
* OS: Android 11
* Browser Firefox
* Version 95.2.0
* Browser Chrome
* Version 96.0.4664.104

### Additional context
WooCommerce version 5.8.2
PHP version 8.0.12
Theme Envo eCommerce version 1.1.1

**Comment by jakub50** [comment]
Downgrading to version 2.9.4 fixed the problem.

**Comment by octaedro** [comment]
Thank you @jakub50 for reporting this error.
I wasn't able to reproduce the bug. Just to rule some things out, could you turn off your theme and try with [Twenty Twenty-One](https://wordpress.org/themes/twentytwentyone/)?
Please let me know if that doesn't resolve the issue.

**Comment by boskjoett** [comment]
I have the same issue with version 3.0.0, and had to rollback to version 2.9.4. I am running Woocommerce in Danish.

**Comment by octaedro** [comment]
Thank you @boskjoett and @jakub50,
Now I can reproduce the error. A fix will be included in `WooCommerce Admin 3.0.1`.
