### ISSUE TITLE
Wrong total value for "Items sold" and "Net sales" in Categories tables (leaderboard and all categories)

### ISSUE THREAD

**Issue by rafanectar** [woocommerce/woocommerce-admin#8098]
### Describe the bug
The total value for "Items sold" and "Net sales" for Categories reports is not correct when the main category and subcategories are selected at the same time. In that case, the total values shown both on the leaderboard table (Section "Analytics") and "Analytics > Categories" table are counted one time for each category/subcategory.

### Actual behavior:
We have this structure, with each total of items sold for example:

- Product X: 1 item sold, price 10€, has checked "Category A" and "Subcategory A1"
- Product Y: 1 item sold, price 20€, has checked "Category A", "Subcategory A1" and "Subcategory A2"

The items sold total list these incorrect values. The same applies:
- Category A (totals: 5 items sold, 80€) ---> 2 x Product X + 3 x Product Y (2x10€ + 3x20€ = 80€)
    - Subcategory A1 (total: 2 items sold, 30€)
    - Subcategory A2 (total: 1 item sold, 20€)

When you go to the filtered by category analysis report the totals are correct, the values are only wrong in the resumed lists.

### Expected behavior
Having the previous example, the total counter shown at leaderboard and categories tables should be:
- Category A (totals: 2 items sold, 30€) ---> 1 x Product X + 1 x Product Y (1x10€ + 1x20€ = 30€)
    - Subcategory A1 (total: 2 items sold, 30€)
    - Subcategory A2 (total: 1 item sold, 20€)

**Comment by octaedro** [comment]
Thank you @rafanectar for reporting this bug, we really appreciate your help.

This bug was already reported [here](https://github.com/woocommerce/woocommerce-admin/issues/7710). Since that one has more information on it, I’ll close this one out.
