### ISSUE TITLE
Use ExPlat to render the menu conditionally

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#8106]
Description: We want to show the WC Pay menu in NZ and IE only with our first release then expand to other countries later.

Implement ExPlat to render the menu conditionally only when users are in a specific experiment (TBD)

Please see [this issue](https://github.com/woocommerce/woocommerce-admin/issues/7931#issuecomment-1004280973) for the context.

**Comment by ilyasfoo** [comment]
I'll do the necessary WPCOM changes to add custom segments when the experiment names are confirmed

**Comment by moon0326** [comment]
> @moon0326 I'll do the necessary WPCOM changes to add custom segments when the experiment names are confirmed.

Thank you! The code change for this is ready. I'll start testing once we have the experiment names.
