### ISSUE TITLE
The activity panel is not visible after hiding the setup task list

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#8109]
### Describe the bug

The activity panel is not being shown after hiding the setup task list.
The activity panel should be visible when:
- The task list is hidden.
- There is at least an **order** with the state: `processing` or `on-hold` or a **review** not approved or a low **stock** product. 

### To Reproduce

1. Checkout the `main` branch.
2. Add a product.
3. Create an order with the state: `processing`.
4. Hide the setup task list.
5. The activity panel is not visible.

### Actual behavior

The activity panel should be shown but is not visible now.

### Screenshots

![Screen Capture on 2022-01-04 at 14-10-44](https://user-images.githubusercontent.com/1314156/148097275-ae6aaaf2-69b9-45c3-afc9-6e6c653c1bc4.gif)

### Expected behavior

The activity panel should be visible after hiding the setup task list (if there is an order with status `processing`).

**Comment by mattsherman** [comment]
@woocommerce/ghidorah Can somebody from Ghidorah please look into this? It seems related to the experiment in https://github.com/woocommerce/woocommerce-admin/issues/7659.

**Comment by octaedro** [comment]
Summarizing a couple of things I noticed:
- It seems that [countLowStockProducts, countUnapprovedReviews, and countUnreadOrders](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/index.js#L45-L47) are null, and this is why [the collapsible panels aren't being shown](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/index.js#L107).
- This is just happening with the new setup task list. When I hide the old setup task list, the activity panel is shown correctly.

**Comment by moon0326** [comment]
I'll take a look at it.
