### ISSUE TITLE
Extensibility: Refactor stat jobs to allow extensions to add new data points to stat storage

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#812]
**Describe the bug**

Our existing report jobs work well for our purposes (extracting data points out of orders and into our stats look up tables) but isn't readily extendable by others to add their own data points.

We saw this first-hand when hacking box office to integrate with our order report to add a "num tickets" data point.

Props to @c-shultz for a potential solution: the stat meta tables concept.

I've labeled this a bug because this breaks extensibility. Let's fix this asap.

cc @laurendavissmith

**Comment by jeffstieler** [comment]
Relevant discussions: p90Yrv-RE-p2, p75Izm-1zl-p2
