### ISSUE TITLE
Update WordPress.org readme.txt to clarify this is a feature plugin that shop owners don't need.

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce-admin#8125]
### Is your feature request related to a problem? Please describe.
The Wordpress.org page for this plugin doesn't make it clear when it is appropriate to install this plugin. Store owners are confused about whether they need this, and don't realize that stable versions are built into WooCommerce core.

This results in negative reviews that are probably by people who think this plugin is mandatory for analytics, such as these 1-star reviews:

- [Wheel of Death](https://wordpress.org/support/topic/wheel-of-death/)
- [Crashed my site twice when updating](https://wordpress.org/support/topic/crashed-my-site-twice-when-updating/)
- [Does nothing](https://wordpress.org/support/topic/does-nothing-112/)
- [Does nothing](https://wordpress.org/support/topic/does-nothing-111/) (Same title, different review)

### Describe the solution you'd like
I think the plugin description should tell people that this is a Feature plugin, and when it is appropriate to install / what to expect when installing it.

Here is some sample copy: 

---
#### Do I need this plugin?
This is a [feature plugin](https://woocommerce.com/document/what-is-a-woocommerce-feature-plugin/) for testing the latest analytics features for future versions of WooCommerce. A stable version of this plugin is packaged with WooCommerce since version 4.0, so you don't need to install this plugin for analytics in your WooCommerce shop.

Install this plugin if you want to test new analytics features before they are released in WooCommerce. If you have trouble, let us know in the [Support Forums]() and participate in its development on the public [GitHub repository](https://github.com/woocommerce/woocommerce-admin).

---

### Describe alternatives you've considered
1. A much briefer message, such as "Note that this is a [feature plugin](https://woocommerce.com/document/what-is-a-woocommerce-feature-plugin/) not necessary to use WooCommerce Analytics, and a stable version is already included in WooCommerce 4.0+."
1. Adding a message upon installation to describe the same information; that this is a feature plugin, and that a stable Admin version is already packaged in WooCommerce 4.0+

### Should this be prioritized? Why?
I think that this would be worth it, since it would be more professional and reduce confusion.

**Comment by moon0326** [comment]
Thank you for the suggestion @melek. I think this is a great suggestion. 

cc @woocommerce/isotope Does anyone have any objections?

@pmcpinto Could you review the copy, please?

**Comment by pmcpinto** [comment]
Thanks for the suggestion. Just some minor suggestions to the copy, as wc admin goes beyond Analytics: 

This is a feature plugin for testing the latest features, such as Analytics, for future versions of WooCommerce. A stable version of this plugin is packaged with WooCommerce since version 4.0, so you don't need to install this plugin for analytics in your WooCommerce store.

Install this plugin if you want to test new features before they are released in WooCommerce. If you have trouble, let us know in the Support Forums and participate in its development on the public GitHub repository.

**Comment by mattsherman** [comment]
@moon0326 Is this ready for a re-review by the team?

**Comment by ilyasfoo** [comment]
I just created a PR for this ^
