### ISSUE TITLE
Setup Wizard: Improve email UI validation

### ISSUE THREAD

**Issue by alopezari** [woocommerce/woocommerce-admin#8155]
### Context
The “Email address” field from the “Store Details” page provides a basic validation of the email format, showing an error message in the text box when the user doesn’t enter a correct email format. However, **the backend is doing the strong validation** here through the `POST /wp-json/wc-admin/onboarding/profile?_locale=user endpoint`, so we have two different levels of error feedback presented to the user: one in the “Email address” field and another when submitting the form, which comes from the backend, being the UI one softer.

### Improvement suggestion
From a UX point of view, I think it would be better if all validations were done all at the same level and as early as possible (before submitting the form). This would imply the **UI component to be more robust**, just as the backend does. And of course, it would still need the endpoint to keep validating the email so that it provided a backup validation.

### Priority
This is just a suggestion to improve the user experience. It doesn't fix anything broken or add a new feature, so I wouldn't consider it an urgent request.

### Additional context
Here you can see how both UI and backend validation work currently:

https://user-images.githubusercontent.com/45979455/149207402-044b26f0-aad6-4b0d-9144-0836803e0103.mp4

**Comment by joelclimbsthings** [comment]
Thanks @alopezari ! I'd agree that this should be addressed, but not entirely urgently. 👍🏻
