### ISSUE TITLE
Reintroduce the CES in key features

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8170]
**Description:** the leadership team wants to establish a high-level metric around user satisfaction and the customer effort score fits this purpose. We should reintroduce the CES in key store management features to ensure we're covering the most important actions of the Core experience.

**Acceptance criteria:** 
- [ ] Reintroduce the CES in the following actions:
Add a product (wcadmin_product_add_publish)
Update product (wcadmin_product_update)
Edit order (any of the edit order events)

**Comment by ilyasfoo** [comment]
We may be able to search for old implementations for some of these events and re-adapt them.
