### ISSUE TITLE
Deleting Products Adds Blank Space to Analytics Data

### ISSUE THREAD

**Issue by katinthehatsite** [woocommerce/woocommerce-admin#8191]
### Describe the bug

When you delete an old product with variations from the site, it removes it from the Analytics > Variations tab and adds a blank space instead. 

### To Reproduce

1. First, you would need to have a few variable products sold on the site and have data under Analytics > Variations
2. Then, delete one of the variable products recorded in the data and check what displays after under Analytics > Variations tab

### Actual behavior:

The products that were deleted on the site show blank space in the Analytics tab:

<img width="1203" alt="Screen Shot 2022-01-18 at 9 24 22 AM" src="https://user-images.githubusercontent.com/25575134/149955418-665b2db7-84e7-4696-b869-c4ac7e408c06.png">

When you delete just a variation of a product, it seems to remove the variation name and just add the name of the product instead but the product itself is still listed:

<img width="1189" alt="Screen Shot 2022-01-18 at 9 25 27 AM" src="https://user-images.githubusercontent.com/25575134/149955619-ab6da12c-f2da-4e02-9fa0-e4daf06c56c2.png">

### Expected behavior

I would have expected the products to be listed even after they were deleted from the site. 

### Additional context

`
### WordPress Environment ###

WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.80.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.31-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 47.22MB
Database Data Size: 39.18MB
Database Index Size: 8.04MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.25MB + Index: 0.23MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.31MB + Index: 0.47MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.28MB + Index: 0.19MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_auctions_for_woocommerce_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jckwds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 29.02MB + Index: 0.45MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.02MB + Engine InnoDB
wp_posts: Data: 0.31MB + Index: 0.19MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcch_page_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrp_rental_products_rentals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrs_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

addify_quote: 2
addify_rfq: 1
addify_rfq_fields: 3
attachment: 34
aw_workflow: 2
bookable_person: 2
bookable_resource: 4
event_ticket: 5
event_ticket_email: 2
follow_up_email: 5
global_product_addon: 1
jp_pay_product: 1
nav_menu_item: 2
page: 38
post: 1
product: 132
product_variation: 139
revision: 28
shop_coupon: 11
shop_order: 228
shop_order_refund: 15
shop_subscription: 18
wccc: 1
wc_booking: 17
wc_membership_plan: 5
wc_user_membership: 2
wishlist: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce: by Automattic – 6.1.0

### Inactive Plugins (88) ###

Akismet Anti-Spam: by Automattic – 4.2.1
Auctions for WooCommerce: by WPInstitut – 1.3
Auctions Made Easy for WooCommerce: by FantasticPlugins – 3.0
AutomateWoo: by WooCommerce – 5.5.8
Bookings Helper: by WooCommerce – 1.0.3
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.6.2
Classic Editor: by WordPress Contributors – 1.6.2
Donation For Woocommerce: by wpexpertsio – 2.1
Facebook for WooCommerce: by Facebook – 2.6.7
Follow-Up Emails: by WooCommerce – 4.9.16 (update to version 4.9.17 is available)
Google Listings and Ads: by WooCommerce – 1.6.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Homepage Control: by WooThemes – 2.0.3
Jetpack: by Automattic – 10.6-a.1
Loco Translate: by Tim Whitlock – 2.5.5
Mailchimp for WooCommerce: by Mailchimp – 2.5.3
Payment Plugins Braintree For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.2.29

Quote Request for WooCommerce: by FantasticPlugins – 1.4
Rental Products: by 99w – 2.5.3 (update to version 3.3.0 is available)
Request a Quote for WooCommerce: by Addify – 2.1.3 (update to version 2.4.0 is available)
Simply Show Hooks: by Stuart O'Brien
cxThemes – 1.2.1

Storefront Parallax Hero: by WooCommerce – 1.5.7
User Role Editor: by Vladimir Garagulya – 4.60.2
Wholesale For WooCommerce: by wpexpertsio – 1.8.5
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.25
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0
WooCommerce Admin: by WooCommerce – 2.7.2
WooCommerce Advanced Notifications: by WooCommerce – 1.2.28 (update to version 1.2.36 is available)
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.29 (update to version 2.4.31 is available)
WooCommerce AvaTax: by SkyVerge – 1.14.0 (update to version 1.15.0 is available)
WooCommerce AWeber Newsletter Subscription: by Themesquad – 3.3.0 (update to version 3.4.6 is available)
WooCommerce Bookings: by WooCommerce – 1.15.49
WooCommerce Bookings Availability: by WooCommerce – 1.1.19
WooCommerce Bookings Filters: by Codup – 1.2.0.21
WooCommerce Box Office: by WooCommerce – 1.1.36
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.27
WooCommerce Composite Products: by SomewhereWarm – 7.1.3 (update to version 8.3.6 is available)
WooCommerce Conditional Content: by Lucas Stark – 2.1.2 (update to version 2.1.8 is available)
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.10.0 (update to version 1.12.0 is available)
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.10.2
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.3
WooCommerce Customer History: by Brian Richards – 1.2.1
WooCommerce Delivery Slots by Iconic: by Iconic – 1.11.2
WooCommerce Deposits: by WooCommerce – 1.5.7
WooCommerce Distance Rate Shipping: by WooCommerce – 1.0.28 (update to version 1.0.30 is available)
WooCommerce Dropshipping: by WooCommerce – 2.8 (update to version 3.8 is available)
WooCommerce Dynamic Pricing: by Element Stark – 3.1.26 (update to version 3.1.27 is available)
WooCommerce Email Customizer: by WooCommerce – 1.1.19 (update to version 1.3.0 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.3.25 (update to version 2.4.1 is available)
WooCommerce FedEx Shipping: by WooCommerce – 3.4.39 (update to version 3.4.40 is available)
WooCommerce Force Sells: by WooCommerce – 1.1.27 (update to version 1.1.29 is available)
WooCommerce Memberships: by SkyVerge – 1.22.7 (update to version 1.22.9 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.24
WooCommerce Multi-currency: by TIV.NET INC – 2.14.1 (update to version 2.14.3 is available)
WooCommerce Order Delivery: by Themesquad – 1.9.4 (update to version 1.9.6 is available)
WooCommerce PayFast Gateway: by WooCommerce – 1.4.19
WooCommerce Payments: by Automattic – 3.4.0 (update to version 3.5.0 is available)
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Payments: by WooCommerce – 1.6.1 (update to version 1.6.4 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.7.2 (update to version 1.7.5 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.5.30
WooCommerce Product Add-ons: by WooCommerce – 4.3.0 (update to version 4.5.0 is available)
WooCommerce Product Bundles: by SomewhereWarm – 6.12.5 (update to version 6.13.3 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.39 (update to version 1.10.46 is available)
WooCommerce Products Compare: by WooCommerce – 1.0.24 (update to version 1.0.25 is available)
WooCommerce Product Vendors: by WooCommerce – 2.1.57 (update to version 2.1.58 is available)
WooCommerce Quick View: by WooCommerce – 1.3.1 (update to version 1.5.0 is available)
WooCommerce Referral System: by Codup.io – 1.3.4.19 (update to version 1.3.9.10 is available)
WooCommerce Royal Mail: by WooCommerce – 2.5.38 (update to version 2.5.39 is available)
WooCommerce Shipment Tracking: by WooCommerce – 1.6.29 (update to version 1.6.31 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.13 (update to version 2.3.17 is available)
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.22 (update to version 3.6.39 is available)
WooCommerce Smart Coupons: by StoreApps – 4.9.0 (update to version 4.34.0 is available)
WooCommerce Square: by WooCommerce – 2.6.0 (update to version 2.7.0 is available)
WooCommerce Stripe Gateway: by WooCommerce – 6.0.0
WooCommerce Subscriptions: by WooCommerce – 3.1.6
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.1
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.3
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.36
WooCommerce UPS Shipping: by WooCommerce – 3.2.36 (update to version 3.2.37 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.4.69
WooCommerce Warranty Requests: by WooCommerce – 1.9.30 (update to version 1.9.31 is available)
WooCommerce WishLists: by Element Stark – 2.2.5 (update to version 2.2.6 is available)
WP Mail Logging: by Wysija – 1.9.9
WP phpMyAdmin: by Puvox.software – 5.1.1.05
Yoast SEO: by Team Yoast – 17.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
auction (auction)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
wcs_ticket (wcs_ticket)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Galleria
Version: 2.2.19
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.9.0 – 3.9.1 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 2
Oldest: 2021-12-28 00:59:43 +0000
Newest: 2022-01-17 01:25:56 +0000

Complete: 955
Oldest: 2021-12-20 20:24:35 +0000
Newest: 2022-01-18 14:17:03 +0000

Failed: 6
Oldest: 2020-12-05 17:27:38 +0000
Newest: 2021-12-13 13:02:41 +0000

Pending: 11
Oldest: 2022-01-18 14:50:12 +0000
Newest: 2022-04-16 18:00:31 +0000

### Status report information ###

Generated at: 2022-01-18 09:27:16 -05:00
`

**Comment by katinthehatsite** [comment]
One question as well - is it possible to recover this Analytics data in some way? Thanks!

**Comment by mattsherman** [comment]
@katinthehatsite Thanks for alerting us to this issue. I can reproduce it and will have the team look into it further to determine how to best proceed.
 
At this point, it is unclear to me if this data can be recovered in some way.

**Comment by ilyasfoo** [comment]
@mattsherman Ghidorah can take this to be worked on C21 if you don't mind

**Comment by mattsherman** [comment]
@ilyasfoo Go for it!

**Comment by moon0326** [comment]
> One question as well - is it possible to recover this Analytics data in some way? Thanks!

@katinthehatsite Hi ✋ 

I just opened a [PR](https://github.com/woocommerce/woocommerce-admin/pull/8255) to address this issue. If the PR gets approval, it will recover the data.
