### ISSUE TITLE
Payments task: include Square in Spain

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8198]
**Description:** Square's launch in Spain is set for Jan 25 and we need to start including the extension in the payments task for spanish users.

**Acceptance criteria:**

- [ ] Display Square as an option in the payments task if the user selects Spain as the country in the Store Details step and if he selects one of the following options in the Business details step - Currently selling elsewhere?
Yes, in person at physical stores and/or events
Yes, on another platform and in person at physical stores and/or events
- [ ] The payments task update using the remote endpoint should be shipped ideally on Jan 25-26
- [ ] Ideally, we should ship the wc admin fallback option in WC Admin 3.3

**Comment by becdetat** [comment]
@pmcpinto 

> can you check if it's possible to do the update next week? 
Will do, I don't see this as an issue

> start including the extension in the payments task for french users
Do you mean "start including the extension in the payments task for *spanish* users"?

**Comment by pmcpinto** [comment]
> Do you mean "start including the extension in the payments task for spanish users"?

Yes. Thanks for spotting that. I was looking at the previous request to include Square when I wrote this issue :)

**Comment by ilyasfoo** [comment]
The remote endpoint is on schedule to be deployed on 25th. 

@pmcpinto We can include the fallback in WCAdmin `3.2` as well, would you think that's more ideal?

**Comment by pmcpinto** [comment]
> We can include the fallback in WCAdmin 3.2 as well, would you think that's more ideal?

Yes. that would be great. Thanks!
