### ISSUE TITLE
Task list experiment: remove 2col experiment code

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8204]
**Description:** The control outperformed the treatment version. See the results here: pbxNRc-ZP#comment-2935-p2

We’ll continue using the control version, for now, so the 2 column experiment code should be removed.

**Comment by pmcpinto** [comment]
cc @becdetat for inclusion in cycle 21

**Comment by adrianduffell** [comment]
@pmcpinto Can this be closed out now that we're re-running the experiment?

**Comment by pmcpinto** [comment]
Yes. I'll close the issue. Thanks for the heads up
