### ISSUE TITLE
OBW: WooCommerce Payments not suggested as a business feature for a store with a US address

### ISSUE THREAD

**Issue by jacob-sewell** [woocommerce/woocommerce-admin#8226]
### Describe the bug

On creating a new store with a US address, WooCommerce Payments was not suggested as a recommended business feature in the Free features step.
 
Initially found on a JN site during 3.2.0-beta.1 smoke test, but reproduced locally on Woo core 6.1.0 WC Admin 3.0.3.

### To Reproduce

1. Create a new store
2. Go through the Store Details screens. I used:
     * a Kansas address
     * no mailing list
     * no usage tracking
     * CBD products
     * Downloads
     * 1-10 products, not selling elsewhere, not setting up a store for a client
3. When you arrive at the "Included business features" form, expand the dropdown by "Add recommended business features to my site".

### Actual behavior:

The recommended business features are:

* Get the basics
  * WooCommerce Tax
  * Jetpack
* Grow your store
  * MailPoet
  * Google Listings and Ads

### Screenshots

![Screen Shot 2022-01-27 at 14 00 09](https://user-images.githubusercontent.com/890809/151434555-076f9d1c-cab1-4220-8d58-df12d39965b6.png)

### Expected behavior

Expected a US or PR store to have WooCommerce Payments suggested as a business feature in this step.

### Desktop (please complete the following information):

* OS: macOS 12.1
* Browser: Chrome
* Version: 97.0.4692.99

### Additional context

While investigating this I encountered an issue with the Store Details Country / Region form which may or may not be related: Issue #8225

**Comment by chihsuan** [comment]
> Go through the Store Details screens. I used:
>
>    a Kansas address
    no mailing list
    no usage tracking
    CBD products

Hi @jacob-sewell If I'm not mistaken, the`WooCommerce Payments` is expected to not be suggested if users select the **"CBD products"**. 

https://github.com/woocommerce/woocommerce-admin/blob/281ae241d0c6d15f696c74cd6bd28294dee16a0f/src/Features/RemoteFreeExtensions/DefaultFreeExtensions.php#L240-L244

**Comment by jacob-sewell** [comment]
> Hi @jacob-sewell If I'm not mistaken, the`WooCommerce Payments` is expected to not be suggested if users select the **"CBD products"**.

That explains it! I'll make a note to avoid that when smoke testing.

**Comment by mattsherman** [comment]
> > Hi @jacob-sewell If I'm not mistaken, the`WooCommerce Payments` is expected to not be suggested if users select the **"CBD products"**.
> 
> That explains it! I'll make a note to avoid that when smoke testing.

@jacob-sewell Can you update the smoke testing docs to make note of this, so others don't get tripped up by it in the future? Thanks!
