### ISSUE TITLE
Add `woocommerce_admin_install_timestamp` to ExPlat API calls

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#8227]
### Description

We don't have a good way to detect a new store for the Experimentation Platform since we [don't support WPCOM auth](https://github.com/woocommerce/woocommerce-admin/issues/8071). New store criteria for eligibility check is critical since it's a common use-case for experimenters.

A workaround I propose is to add the value stored in `woocommerce_admin_install_timestamp` to the ExPlat integrations:

**PHP integration:**
https://github.com/woocommerce/woocommerce-admin/blob/281ae241d0c6d15f696c74cd6bd28294dee16a0f/includes/class-experimental-abtest.php#L158-L162

**JS integration:**
https://github.com/woocommerce/woocommerce-admin/blob/281ae241d0c6d15f696c74cd6bd28294dee16a0f/packages/explat/src/assignment.ts#L21-L29

An appropriate parameter name would be `woo_wcadmin_install_timestamp`.

**Comment by ilyasfoo** [comment]
A potential challenge for JS is we may have to preload the option, which is a direction that we're generally trying to avoid since it may impact performance.

**Comment by moon0326** [comment]
@ilyasfoo What do you think about using a filter?

PHP:

```
$args = array(
	'experiment_name'  => $test_name,
	'anon_id'          => rawurlencode( $this->anon_id ),
	'woo_country_code' => rawurlencode( get_option( 'woocommerce_default_country', 'US:CA' ) ),
);

$args = apply_filters( 'woocommerce_explat_request_args', $args );
```

JS:

```
const params = applyFilters( 'woocommerce_explat_request_args', {
	experiment_name: experimentName,
	anon_id: anonId ?? undefined,
	woo_country_code:
		window.wcSettings?.preloadSettings?.general
			?.woocommerce_default_country ||
		window.wcSettings?.admin?.preloadSettings?.general
			?.woocommerce_default_country,
} );

const response = await window.fetch(
	`https://public-api.wordpress.com/wpcom/v2/experiments/${ EXPLAT_VERSION }/assignments/woocommerce?${ stringify(
		params
	) }`
```

We can then use `add_filter` to update the request args.

```
add_filter('woocommerce_explat_request_args', function($args){
	if ($args['experiment_name'] === 'my-experiment') {
		$args['woocommerce_admin_install_timestamp'] = get_option('woocommerce_admin_install_timestamp);	
	}

    return $args;
}, 1);

```

**Comment by ilyasfoo** [comment]
@moon0326 Nice, I really like the idea of using a filter, I can see how this could be useful! Another possible downside I'd say is that it'll somewhat limit a retroactive change on the backend if we ever need it, but I think the chances of that are minimal if we plan our experiments properly.

Also, in order for this to work with dynamic experiments, I think we'll need the filter to detect the baseline experiment name so that the dates won't affect it.

I agree with using the filter 👍

**Comment by moon0326** [comment]
> @moon0326 Nice, I really like the idea of using a filter, I can see how this could be useful! Another possible downside I'd say is that it'll somewhat limit a retroactive change on the backend if we ever need it, but I think the chances of that are minimal if we plan our experiments properly.
> 
> Also, in order for this to work with dynamic experiments, I think we'll need the filter to detect the baseline experiment name so that the dates won't affect it.
> 
> I agree with using the filter 👍

Nice!

Yup! I think filter can use `indexOf` (or regex) to test the dynamic experiment name.
