### ISSUE TITLE
Payments task: display the offline options always below the extensions

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8230]
### Describe the bug
In some countries, at least one payments extension is displayed below the offline payments options. 

### To Reproduce

1. Create a new store
2. Select India or Australia as country
3. Visit the Payments task
4. See that one of the payment extension is displayed below the offline payments options

### Actual behavior:
Some payment extensions are being displayed below the CoD and Direct Bank Transfer options

### Screenshots

![Captura de ecrã 2022-01-28, às 14.27.04.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/49cae8e0-d9cd-4e14-93d8-d213492a5cfd)

![Captura de ecrã 2022-01-28, às 14.26.23.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/e4389be2-8134-4284-8870-7b087714010f)

### Expected behavior
To show the offline payments options always below the payments extensions

**Comment by pmcpinto** [comment]
@becdetat added this to cycle 21.

@mattsherman AFAIR Mothra was the last team to work on the payments task space.

**Comment by ilyasfoo** [comment]
@pmcpinto Ghidorah should be able to work on this in C21
