### ISSUE TITLE
In the Shipping task, after completing the "Set store location" step, user is taken immediately to the "Enable shipping label printing" step, thereby skipping the "Set shipping costs" step

### ISSUE THREAD

**Issue by rodelgc** [woocommerce/woocommerce-admin#8239]
### Describe the bug
After filling up the "Set store location" step and submitting it, you should be taken to the next step (Set shipping costs). Instead, you're taken immediately to the "Enable shipping label printing" step. I observed this behavior in WooCommerce 6.1.1 and 6.2.0-rc.2.

### To Reproduce

1. On a fresh WooCommerce installation, skip setting up the store details.
2. In Products > Add New, create a new physical product.
3. Go back to WooCommerce > Home
4. Click "Set up shipping"
5. Fill up the "Set store location" step and submit it.
6. Notice that the "Set shipping costs" step is skipped. Instead, you're taken to the "Enable shipping label printing" step right away.

### Actual behavior:
User is being taken to the "Enable shipping label printing" step right away, thus skipping the "Set shipping costs" step.

### Screen recording

https://user-images.githubusercontent.com/4509348/151982993-3cc4ef4e-c23e-48c8-8ac3-f4ce69f379cc.mov

### Expected behavior
User should be taken to the "Set shipping costs" step.

### Desktop (please complete the following information):

* OS: macOS
* Browser: Firefox
* Version: 96.0.3

**Comment by louwie17** [comment]
Thanks for creating this @rodelgc, I was able to reproduce this as well and it does seem to be invalid behaviour.

**Comment by louwie17** [comment]
@mattsherman this might be worth adding to our current sprint or the following one, I would assume the solution should be fairly easy.

**Comment by mattsherman** [comment]
> @mattsherman this might be worth adding to our current sprint or the following one, I would assume the solution should be fairly easy.

Agreed. Thanks for just going ahead and fixing it! 🙌
