### ISSUE TITLE
Store setup - WooCommerce Payment Flow

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-admin#8251]
### Describe the bug
While setting up the store, I clicked on “Get paid with WooCommerce Payments” from the checklist on the home page and completed the flow. 

![image](https://user-images.githubusercontent.com/98944206/152309100-02bc47d0-b79d-4edb-aeee-492b13732bf1.png)

But once I finished the flow, I was redirected to an error page that stated “Sorry, you’re not allowed to access this page”.

![image](https://user-images.githubusercontent.com/98944206/152307650-f037354b-cf8d-4132-a010-ae90112f08d7.png)

In addition to that, the "Set up payment" task was still marked as a to-do and the task “Set up additional payment providers” from the section “Things to do next” disappeared (never dismissed). I double-checked in the settings and WooCommerce Payment was enabled correctly. 

![image](https://user-images.githubusercontent.com/98944206/152308256-290e7cbd-48ad-4cef-9842-873ae3d4d987.png)

### To Reproduce

1. Go to 'Home Page'
2. Click on 'Get paid with WooCommerce Payment'
3. Complete the flow
4. See the error message once completed the flow
5. Go to 'Home Page' and see the unchecked task + “Set up additional payment providers” disappeared.

### Expected behavior
Once completed the flow, the user is supposed to be addressed to the home page and see the WooCommerce Payment task as done.
The “Set up additional payment providers” from the section “Things to do next” is not supposed to disappear if not dismissed by the user.

### Desktop (please complete the following information):

* MacOS Monterey
* Chrome

CC @pmcpinto

**Comment by pmcpinto** [comment]
@becdetat @mattsherman is it possible to include this in cycle 21? This looks like a "critical" bug in one of the main setup flows. AFAIR Mothra was the last team implementing some changes around the payments task: #7720
Thanks!

**Comment by mattsherman** [comment]
@pmcpinto Mothra will take care of this in Cycle 21.

**Comment by becdetat** [comment]
Thanks @mattsherman , added to the cycle doc

**Comment by louwie17** [comment]
@verofasulo I can't re-produce the “Sorry, you’re not allowed to access this page” page that you are seeing, could I have some more information on what role your `user` is under `Users > All users`. Unless you are using a specific role plugin to manage your permissions.

The other two items I can reproduce, need to do some further investigation.

**Comment by verofasulo** [comment]
Hey @louwie17, sure! I attach a screenshot from the All users page:

![image](https://user-images.githubusercontent.com/98944206/152770179-02fb6623-cd37-4e98-a386-cf6a0475b258.png)
 
Hope this helps! Please let me know if more information is needed :)

**Comment by mattsherman** [comment]
@verofasulo This is a WordPress.com site, correct?

@louwie17 I wonder if that makes a difference.

**Comment by verofasulo** [comment]
@mattsherman Yes, exactly!

**Comment by verofasulo** [comment]
@louwie17 sorry for my late reply! I totally missed the ping.

> I did just try on a WordPress.com site myself with the latest WC versions and couldn't reproduce it. @verofasulo are you able to re-produce this by chance?

I checked again but I wasn't able to reproduce it actually. Not sure why it happened the first time, but everything seems ok now.

> In relation to the second issue of the WooCommerce Payments task disappearing and being replaced by Set up payments, this apparently got changed when working on the new task list (see https://github.com/woocommerce/woocommerce-admin/issues/7636#issuecomment-948515677), within https://github.com/woocommerce/woocommerce-admin/pull/7838 for reference.

Thanks for sharing this. But I've just seen that the interface has been changed and now we only have the task "Set up payments", instead of " Set up WooCommerce Payment" + "Set up additional payments". Could you confirm that this is correct? 

![image](https://user-images.githubusercontent.com/98944206/154051160-728f600f-a4ea-446a-ba4d-4f497fab07c1.png)

**Comment by louwie17** [comment]
> Thanks for sharing this. But I've just seen that the interface has been changed and now we only have the task "Set up payments", instead of " Set up WooCommerce Payment" + "Set up additional payments". Could you confirm that this is correct?
> 
> ![image](https://user-images.githubusercontent.com/98944206/154051160-728f600f-a4ea-446a-ba4d-4f497fab07c1.png)

@verofasulo that is correct, but it depends on the scenario. The "Set up WooCommerce Payment" + "Set up additional payments" tasks show up when a user selects "WooCommerce Payments" as one of the options in the free features section of the onboarding wizard. If the user doesn't install WooCommerce Payments during that time, they will be shown the "Set up payments" task (sneaky I know).

Now as you stated before that the "Set up WooCommerce Payment" disappeared once it was set up and connected is a bug, this was working in the original (above ) task list. This logic is a little different in the experimental task list worked on as part of this issue: https://github.com/woocommerce/woocommerce-admin/issues/7636.
Because both task lists use the same logic in the back end, this got changed in the current task list (which is technically a bug, as I don't think that was intended).

**Comment by verofasulo** [comment]
> If the user doesn't install WooCommerce Payments during that time, they will be shown the "Set up payments" task

Haaa I had no idea about these two different scenarios. It seems quite an aggressive promotion to prompt the user towards WooCommerce payment at this initial stage, only because they have installed it during the signup. But anyway, thanks for clarifying this point :) 

> I can change that part back, so the woocommerce payments task shows as completed and that should keep the Set up additional payments task listed below.

I think it makes sense, otherwise, it risks being a bit confusing for the user. Thank you!:)
