### ISSUE TITLE
Latest commit of Update store setup widget to use task list API #31755 generates fatal error

### ISSUE THREAD

**Issue by wplaunchify** [woocommerce/woocommerce-admin#8288]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This update throws a critical error in my multisite setup. See below:
When I go back to previous commit the error is resolved.

Fatal error: Uncaught Error: Call to a member function is_complete() on null in /home/387089.cloudwaysapps.com/jwmkkrtvnr/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php:173 Stack trace: #0 /home/387089.cloudwaysapps.com/jwmkkrtvnr/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php(44): WC_Admin_Dashboard_Setup->should_display_widget() https://github.com/woocommerce/woocommerce/issues/1 /home/387089.cloudwaysapps.com/jwmkkrtvnr/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php(181): WC_Admin_Dashboard_Setup->__construct() https://github.com/woocommerce/woocommerce/issues/2 /home/387089.cloudwaysapps.com/jwmkkrtvnr/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin.php(102): include('/home/387089.cl...') https://github.com/woocommerce/woocommerce/pull/3 /home/387089.cloudwaysapps.com/jwmkkrtvnr/public_html/wp-includes/class-wp-hook.php(307): WC_Admin->conditional_includes() https://github.com/woocommerce/woocommerce/issues/4 /home/387089.cloudwaysapps.com/jwmkkrtvnr/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() https://github.com/woocommerce/woocommerce/pull/5 /home/387089.cloudwaysa in /home/387089.cloudwaysapps.com/jwmkkrtvnr/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php on line 173
There has been a critical error on this website.

### Expected behavior

It shouldn't crash the site with a fatal error

### Actual behavior

it shows the error above

### Steps to reproduce

update to latest version where this commit was pushed.... line 173 throws the fatal error
https://github.com/woocommerce/woocommerce/pull/31755#issuecomment-1034168132

### WordPress Environment

Latest WP 5.9 with latest version of WooCommerce (from the commit)... I didn't pull the status report, because it happened on several of my sites and I was able to fix the issue by reverting the commit listed above to the prior version.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Jinksi** [comment]
4764004-zen

**Comment by joshuatf** [comment]
Resolved via https://github.com/woocommerce/woocommerce/pull/31884.
