### ISSUE TITLE
Wordpress 6.0 alpha fatals on loading Woocommerce admin

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce-admin#8291]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In wordpress 6.0 i get this notification error on the latest woocommerce beta running

Notice: Function add_menu_page was called incorrectly. The seventh parameter passed to add_menu_page() should be an integer representing menu position. Please see Debugging in WordPress for more information

Version 6.2.0-rc.1

class-wc-admin-menus.php is not using a integer but a float on line 64 & 76

![afbeelding](https://user-images.githubusercontent.com/6078370/151950165-2174a777-aadd-4c0d-b7f4-15e39e752ff1.png)

also in wp-content/plugins/woocommerce/packages/woocommerce-admin/src.WcPayWelcomePage.php line 51 & 75

![afbeelding](https://user-images.githubusercontent.com/6078370/151947740-880f57c3-2704-4dee-b5af-5540839b4c25.png)

also in/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/PageController.php line 441  should be intval($options['position'])

![afbeelding](https://user-images.githubusercontent.com/6078370/151949748-dc0fa6df-669e-4604-bc51-25d0a9db1f4e.png)

Please fix

### Expected behavior

change the float to a integer

### Actual behavior

just turn on debug mode and visit any admin page.

### Steps to reproduce

Just update to latest beta wp 6.0

### WordPress Environment

not needed

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rjchow** [comment]
Hello @BackuPs, thank you for reporting this issue!

I can confirm that this is reproducible by using the [trunk version of wordpress](https://github.com/WordPress/WordPress/) which is `6.0-alpha-52779` as of right now.

Specifically, the instructions to replicate it as I did was:

1. Clone a copy of latest Wordpress from above repo, take note of the path that you cloned it to
2. Clone a copy of this repo (woocommerce-admin)
3. Make a copy of `.wp-env.json` and name it `.wp-env.override.json`
4. Change the value of the key "core" to the path of the Wordpress install above, e.g:

```json
{
	"phpVersion": "7.4",
	"core": "/home/user/Automattic/WordPress",
	"plugins": [
		".",
		"https://downloads.wordpress.org/plugin/woocommerce.zip"
	],
	"config": {
		"JETPACK_AUTOLOAD_DEV": true,
		"WP_DEBUG_LOG": true,
		"WP_DEBUG_DISPLAY": true,
		"ALTERNATE_WP_CRON": true
	}
}

```
5. Follow the setup instructions in `./docker/wc-admin-wp-env/README.md` to get it running
6. When loading wp-admin you will see the error:
![image](https://user-images.githubusercontent.com/27843274/155068523-892b56f8-016d-4ccf-a55f-2fd27959f906.png)

7. When you click on "Woocommerce" menu on the left it will fail catastrophically:
![image](https://user-images.githubusercontent.com/27843274/155068606-f41bb810-fd96-4f5f-84ea-1fd51deb6820.png)

**Comment by BackuPs** [comment]
in Woocommerce 6.30 beta.1  the files that have issue with this changed.  See image. Why create more of these issues when new files are added and not fix it while creating these new files?

![afbeelding](https://user-images.githubusercontent.com/6078370/155154088-65b6e4b0-c91d-4faf-92d8-b3af6289856e.png)

**Comment by rjchow** [comment]
Again, I would like to express great appreciation for your effort making this report!

This issue came to our notice only yesterday and we do not generally do development against unrealeased versions of Wordpress. 

We will be addressing this issue shortly!

**Comment by BackuPs** [comment]
@rjchow i am sorry i did not know this. I was under the impression after seeying the reply of @ObliviousHarmony 13 days ago   that it was transfered to woocommerce admin and that you were already aware of these warnings. 

The file class-wc-admin-menus.php is part or woocommerce/includes/admin  and not part of the admin package which might have been the reason that it was transfered back in here?  I don't know, i am just guessing now.

Anyway i apologise for this.

**Comment by chihsuan** [comment]
> class-wc-admin-menus.php is not using a integer but a float on line 64 & 76

Looks like this https://github.com/woocommerce/woocommerce/commit/de57b39d8ec7afb76cd11fc52c8b81cd753ede66 commit has fixed the `class-wc-admin-menus.php` in WooCommerce core, but not release yet.

The others are in this repo. We'll fix them soon.

**Comment by ironprogrammer** [comment]
Hi, @chihsuan -- There is also a non-integer menu `$position` at /packages/woocommerce-admin/src/Features/WcPayWelcomePage.php:75 (`55.7`) that raises this same notice.

I couldn't find where that package is maintained, so apologies if this isn't the right place to report 😅

**Comment by chihsuan** [comment]
> There is also a non-integer menu $position at /packages/woocommerce-admin/src/Features/WcPayWelcomePage.php:75 (55.7) that raises this same notice.

Hi @ironprogrammer yea, we've fixed it in [this PR](https://github.com/woocommerce/woocommerce-admin/pull/8399/files#diff-2bcb7c61fe4978686e3ac45a54b5c4084508260729c1fb46089e3dde933c851aL75).

`src/Features/WcPayWelcomePage.php` has been moved to `src-internal/Admin/WcPayWelcomePage.php`. We will include the fix in the next release. Let me know if you still encounter the issue. Thanks! 🙂
