### ISSUE TITLE
Payments task: missing Tracks when users click "Finish setup" in the WCPay card

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8302]
### Describe the bug
We're not firing an event when users click to finish the WCPay setup in the Payments card. This makes it difficult to have a clear picture of the entire funnel

### To Reproduce

1. Create a new store
2. Install WC Payments in the Business Features step
3. Visit the Payments task
4. Visit "Set up additional payments" task
5. Click "Finish setup" in the WCPay card
6. See that we're not firing an event on click

### Actual behavior:
Not firing an event when users click to finish the WCPay setup

### Screenshots
<img width="1281" alt="Captura de ecrã 2022-02-11, às 11 02 00" src="https://user-images.githubusercontent.com/3380168/153581493-97d767da-550b-4a7f-a514-50527560bfee.png">

### Expected behavior
We should fire an event when users click to finish the WCPay setup. We can use:
`wcadmin_tasklist_payment_setup` `selected`: `woocommerce-payments`
Or `wcadmin_tasklist_payment_manage` `id`: `woocommerce-payments`. I'm seeing `woocommerce_payments:non-us`and `woocommerce_payments:us` as values of the `id` prop, but I don't know where we're firing this event.

**Comment by becdetat** [comment]
@adrianduffell Can you add this to Ghidorah's backlog for this cycle please? I understand if something else drops off because of this.

**Comment by becdetat** [comment]
@pmcpinto is this a bug as in this is something that was previously working and has stopped? Or new functionality?

**Comment by adrianduffell** [comment]
@becdetat No worries, I've now added it to our backlog.

**Comment by rjchow** [comment]
@pmcpinto, this was recently merged #8146 and will be released in 3.2.0
If you were using 3.2.0 or later and do not see the event either, then we will need to investigate further as a bug.

The event looks like `wcadmin_tasklist_payment_setup` `selected:` `wc-pay`

![wcpay setup tracks](https://user-images.githubusercontent.com/27843274/153815172-1f973586-5ae2-4259-bbc7-80c51275f435.gif)

**Comment by becdetat** [comment]
Thanks @rjchow :-) . @pmcpinto if this looks correct can you close this issue?

**Comment by rjchow** [comment]
> ### Engineering Note
> 
> As part of this, we should also add tests for the tracks event. Internal discussion: P90Yrv-2A1-p2
> 
> A recent PR with tests for tracks is #8002.

@adrianduffell I added a test for this yesterday while I was at it 😬 #8306

**Comment by adrianduffell** [comment]
> @adrianduffell I added a test for this yesterday while I was at it 😬 https://github.com/woocommerce/woocommerce-admin/pull/8306
Thanks for linking https://github.com/woocommerce/woocommerce-admin/pull/8002, it was very helpful

@rjchow That's great, thank you for boosting our test coverage! 👍

**Comment by pmcpinto** [comment]
> @pmcpinto, this was recently merged https://github.com/woocommerce/woocommerce-admin/pull/8146 and will be released in 3.2.0
> If you were using 3.2.0 or later and do not see the event either, then we will need to investigate further as a bug

Thanks for the clarification. I thought this was released with 3.1.

> @pmcpinto if this looks correct can you close this issue?
I tested the flow with 3.2 RC1 and it's working fine. I'll close the issue
