### ISSUE TITLE
Do not show extended task list item for "Setup additional payment providers" until after WCPayments is set up

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#8315]
When WooCommerce payments is installed via the onboarding wizard, we should not show the extended task list item for "Setup additional payment providers" until AFTER WooCommerce Payments is set up successfully. 

cc @pmcpinto @jarekmorawski 

<img width="753" alt="Screen Shot 2022-02-15 at 11 43 23 AM" src="https://user-images.githubusercontent.com/4500952/154136985-1fcfafb7-401a-4152-ae17-c202be7c2b7f.png">

**Comment by pmcpinto** [comment]
@adrianduffell can you confirm that this will be included in WC Admin 3.3? Thanks!

**Comment by adrianduffell** [comment]
@pmcpinto It's on track to be included in 3.3. The PR is now in review.

**Comment by adrianduffell** [comment]
@pmcpinto The fix is now merged and safely on board the 3.3 release train 😃

**Comment by pmcpinto** [comment]
Great! Thanks for the confirmation :)
