### ISSUE TITLE
Product type `Subscriptions` should be hidden when user selects CBD industry

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#8320]
### Describe the bug
In Setup Wizard's Product Types step, when a user has selected `CBD and other hemp-derived products`, we should hide `Subscriptions` from the selection and don't install WCPay.

Currently, if a user selects CBD, they can still select `Subscriptions` product type and install WCPay. 

pb22l9-182-p2#comment-1144

![gif](https://user-images.githubusercontent.com/3747241/154255150-abaf87d9-0e89-4dee-bbd8-4cbe29040ea3.gif)

### To Reproduce

1. Go to Setup Wizard
2. In Store Details step, select any state in the US and then continue
3. In Industry, select `CBD and other hemp-derived products`
4. In Product Types, select `Subscriptions`, and continue
5. Observe that WCPay is installed

### Actual behavior:
Subscriptions product type is displayed and WCPay is installed.

### Expected behavior
WCPay shouldn't be installed and Subscriptions product type should be hidden.

**Comment by pmcpinto** [comment]
@becdetat is it possible to resolve this bug in time to be included in the 3.2 final version? Btw, who should I contact in this type of situation? You, the release lead, or the lead of the team who implemented the latest changes?

**Comment by becdetat** [comment]
@pmcpinto Looks like @louwie17 has jumped on this :thanks: :-)

You probably should contact all three actually, that would stop any one of us from becoming a bottleneck as the decision could be made by any of those three (as long as it doesn't considerably affect the cycle).
