### ISSUE TITLE
Things to do next card appears in task sub-flows

### ISSUE THREAD

**Issue by jarekmorawski** [woocommerce/woocommerce-admin#8331]
### Describe the bug
Hey! I noticed that the `Things to do next` card started appearing inside sub-flows within each task. I can see it on my test site for each task, both complete and incomplete. Can you take a look, please?

### To Reproduce

1. Go to Home
2. Click on any task in the list.

### Screenshots
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/79307566/154674153-49a06c94-529e-4256-b123-7a7c9d4399e2.png">

### Expected behavior
`Things to do next` should only appear in the Home screen, not inside the sub-flows.

### Additional context
If it helps, my test site is Dotcom-hosted and has both the new navigation and the new task progression experiments enabled (randomly, I did not assign them manually).

**Comment by rjchow** [comment]
Hey @jarekmorawski thank you for reporting this issue! 

I confirmed that the issue could be reproduced on my end but only with woocommerce-admin 3.1.0. It seems to have been resolved at some point between then and now (3.2.0rc1).

3.2.0 is slated to be released next month, but if you're feeling adventurous you can install 3.2.0rc from [here](https://github.com/woocommerce/woocommerce-admin/releases) :smile:
