### ISSUE TITLE
Switch to pnpm

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#8337]
As part of merging this repo with `woocommerce/woocommerce` and forming the monorepo, we will need to switch to use pnpm. As @ObliviousHarmony has identified:

> The `woocommerce/woocommerce` repository uses [PNPM](https://pnpm.io/), which poses some interesting dependency issues for many JS projects. PNPM is a little strict about dependency usage, in short, you can't use dependencies you haven't actually required. Normally you can require dependencies in a parent node_modules directory, as well as dependencies that are transitive to some dependency you required. This is very fragile:
> - When you import a dependency from a parent `node_modules` folder, it isn't actually present in your distribution. This leads to packages that work locally but break when downloaded via NPM.
> - When you import a transitive dependency, you risk having the API change if the package that's really consuming it updates it. You can prevent these issues entirely by requiring the dependency yourself since the update would break due to a clear API incompatibility.
> Making these changes after the merge might be a little bit more difficult since we've already got a PNPM workspace in place. I know Jeff and Paul went through before and cleaned up a lot of this, so hopefully, there isn't a lot added since. Ultimately this just means:
> - Adding a PNPM workspace to the `woocommerce/woocommerce-admin` repository
> - Update all package.json scripts to use `pnpm` commands like `pnpx` and the like.
> - Add the same protection that Core has to prevent `npm` install from working. This is the best way to prevent anyone from accidentally using NPM.
> - Nuke `package-lock.json` files after
> - Build all of your JS and systematically add any missing dependencies to each of the packages.
> As a note, this doesn't actually change anything about your JS or imports or anything. The point is just that you can't import anything that you haven't explicitly required in a project's package.json file.

*Also please create an Isotope P2 explaining how to switch to use PNPM in development, including what command changes need to be made and what stays the same.*

**Comment by adrianduffell** [comment]
> PNPM is a little strict about dependency usage, in short, you can't use dependencies you haven't actually required. 

Glad this is going to be addressed. We can find instances of this by this running `npm run lint:js` and searching for warnings about the rule `import/no-extraneous-dependencies`.

For example:

```
/Users/xxx/woocommerce-admin/packages/navigation/src/index.js
    4:31  warning  '@wordpress/element' should be listed in the project's dependencies. Run 'npm i -S @wordpress/element' to add it              import/no-extraneous-dependencies
```

**Comment by becdetat** [comment]
I've updated this to request an explainer P2 to be created as part of this ticket

**Comment by chihsuan** [comment]
TODO:
- [ ] Add a PNPM workspace to repository
- [ ] Update all package.json scripts to use pnpm commands like pnpx and the like
- [ ] Add the same protection that Core has to prevent npm install from working
- [ ] Remove package-lock.json
- [ ] Add any missing dependencies to each of the packages
- [ ] Update dev document
- [ ] Create an Isotope P2
- [ ] Create a PR
