### ISSUE TITLE
Payments task: layout refinements

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8345]
**Description:** we plan to refine how we display additional payment gateway options, in order to minimize cognitive load and increase the focus on setting up WCPayments

**Acceptance criteria:**
- [ ] Hide list of additional payment gateways when WCPayments is available
- [ ] Apply low visual treatment to additional payment gateway options (PayPal, Stripe, etc) when WCPayments is available

Final mockups coming soon

**Event tracking:**
TBD

**Comment by adrianduffell** [comment]
Just blocking this until the final mockups are ready.

**Comment by pmcpinto** [comment]
We can close this one, as I created this epic with all the changes: woocommerce/woocommerce#32133
