### ISSUE TITLE
Inbox: reintroduce the auto dismiss behavior

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8393]
**Description:** we saw a decrease in the number of clicks after the release of the Inbox iteration at the beginning of January. At first, we thought it was a problem with tracking, but after revising the Inbox events we now think that this drop is being affected by some change in the UI. The main hypothesis is that now that we're not automatically dismissing actioned messages, and as a side effect users are less likely to scroll down and take action on more messages. We also saw a decrease in Inbox message views after the release.
We should revert this behavior to validate if it's the root cause of the drop. 

**Acceptance criteria:**
- [ ] Automatically dismiss the message after the user clicks on it

**Comment by pmcpinto** [comment]
@becdetat @adrianduffell @ilyasfoo we should try to include this in Cycle 22 and implement the change as soon as possible to be included in WC Admin 3.3. Let me know if it's doable.

**Comment by adrianduffell** [comment]
@ilyasfoo We could cut https://github.com/woocommerce/woocommerce-admin/issues/8071 from our sprint commitments to make room for this.

**Comment by ilyasfoo** [comment]
@adrianduffell My gut feel is we may have enough room for this since the work itself may not take that much. But to be safe, I agree, we can cut #8071 and put it in backlog since it's not a priority.

**Comment by adrianduffell** [comment]
@ilyasfoo Looks like your gut feel was right 👍 

I'm happy to keep https://github.com/woocommerce/woocommerce-admin/issues/8071 in place for the sprint.

**Comment by adrianduffell** [comment]
@pmcpinto The fix for this landed in time for the 3.3 release 😄

**Comment by pmcpinto** [comment]
Awesome. Thanks for taking care of this so quickly.
