### ISSUE TITLE
Cannot install paid themes via the Setup Wizard

### ISSUE THREAD

**Issue by adrianlbs** [woocommerce/woocommerce-admin#8397]
### Describe the bug
Stumbled upon an issue with the **Setup Wizard** — **cannot install paid themes**, can only install free. When trying to choose a paid theme, I am redirected to WooCommerce / Home, with no success or error message. 

### To Reproduce

1. Go to 'Setup Wizard'
2. Click on 'Themes / Choose'
3. Taken back to WooCommerce / Home and the UX breaks there with no success or error message.

### Actual behavior:
Not sure which was the process when it worked.

### Screencast
[▶ View Recording](https://d.pr/v/DUx8Ke)

### Expected behavior
As a user, I should be able to purchase one of the themes suggested.

**Comment by tammullen** [comment]
I can reproduce on Jurassic Ninja with WC 6.2.1 and 6.3 RC 2

**Comment by tammullen** [comment]
Looks like it stopped working from WC 6.0
<img width="729" alt="Screenshot 2022-03-03 at 11 10 05" src="https://user-images.githubusercontent.com/24649833/156553743-4db8c1fe-dbfd-4905-95ae-89971e1cff52.png">

WC 5.9
<img width="712" alt="Screenshot 2022-03-03 at 11 11 30" src="https://user-images.githubusercontent.com/24649833/156553728-7f1f60c2-a4cb-4180-b9fc-2c88b8ca32e9.png">

**Comment by rjchow** [comment]
Hey team, 

I've done some investigation on this -

- Managed to confirm a reproduce, regression was "introduced" in WooCommerce 6.0
- In 5.9 if you click on purchase theme button from the OBW, you end up back at WCA home with a new item added to the task list, that brings you to woocommerce.com to finish the purchase 
- In 6.0 we retired the task list status endpoint and started using the individual task items endpoint
- For some reason this is not displaying the "Add <theme> to my store" item in the task list. 
- Determined that it is likely for the bug to be caused somewhere in https://github.com/woocommerce/woocommerce-admin/blob/6820ede13107f4d00aabd09611ad45e4c9761155/src/Features/OnboardingTasks/Tasks/Purchase.php
- I don't have enough context to understand what [get_products()](https://github.com/woocommerce/woocommerce-admin/blob/6820ede13107f4d00aabd09611ad45e4c9761155/src/Features/OnboardingTasks/Tasks/Purchase.php#L147) is doing, but running a debugging session confused me with the values of $product_data (see screencap below)
![image](https://user-images.githubusercontent.com/27843274/156714914-f6db2405-be6f-459e-ba7b-7ed5d24b31c4.png)
- If I force the task to be returned by the endpoint, by setting [can_view()](https://github.com/woocommerce/woocommerce-admin/blob/6820ede13107f4d00aabd09611ad45e4c9761155/src/Features/OnboardingTasks/Tasks/Purchase.php#L137) to return true always, I get an item added to the task list
![image](https://user-images.githubusercontent.com/27843274/156715576-425dad54-16e3-4e82-8aba-38bdff3a9fb3.png)

- Task list's item name is vague but clicking on it does bring up the correct purchase modal with the theme in it, that subsequently brings me to woocommerce.com to finish the purchase correctly

**Comment by louwie17** [comment]
Thanks for sleuthing away on this @rjchow , you made some good progress!

> * Determined that it is likely for the bug to be caused somewhere in [Purchase.php](https://github.com/woocommerce/woocommerce-admin/blob/6820ede13107f4d00aabd09611ad45e4c9761155/src/Features/OnboardingTasks/Tasks/Purchase.php)

You are correct!

> * I don't have enough context to understand what [get_products()](https://github.com/woocommerce/woocommerce-admin/blob/6820ede13107f4d00aabd09611ad45e4c9761155/src/Features/OnboardingTasks/Tasks/Purchase.php#L147) is doing, but running a debugging session confused me with the values of $product_data (see screencap below)

For context, the purchase task in charge of handling all paid extensions, this includes the paid items that can be selected on the product types step. The products that you are seeing in your debugger is showing exactly that.
Now it appears that when we moved this logic to our back end, we never moved over the logic of handling themes. As you can see here in our original code (5.9) we also add each paid theme to our product list -> https://github.com/woocommerce/woocommerce-admin/blob/da80cca00877d47079a7be2ebfb39832c16ce469/client/dashboard/utils.js#L140-L151

This part was never added in the `Purchase.php` `get_products` function.

> * If I force the task to be returned by the endpoint, by setting [can_view()](https://github.com/woocommerce/woocommerce-admin/blob/6820ede13107f4d00aabd09611ad45e4c9761155/src/Features/OnboardingTasks/Tasks/Purchase.php#L137) to return true always, I get an item added to the task list

Correct, that part of the task is still handled on the front-end and would be using the same logic that the original task in 5.9 was using. That logic shouldn't of changed, but probably got moved around a bit.

I end up writing up a fix right away, it could maybe use a tiny bit of cleanup, but that is up to the reviewer.
