### ISSUE TITLE
Activity Panel: Inbox: Need a Means to Load More Notes

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#864]
Right now the activity inbox only displays up to 10 notes. If there are more (i.e. older) notes on the server, we need a means for the user to request the next page. Accessibility is a priority too, so we've set aside the idea of infinite scroll for now.

<img width="305" alt="screen_shot_2018-11-15_at_11_19_14_am" src="https://user-images.githubusercontent.com/1595739/48576206-bbffb200-e8c8-11e8-9606-851d5d89b278.png">

cc @LevinMedia  @ryelle 

Related: #176

**Comment by LevinMedia** [comment]
@allendav Can we use a simple secondary button, centered below the list on the darker grey background that says "Load more"?

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
