### ISSUE TITLE
Advanced Filters: Variations?

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#963]
The table in _Product Detail Report_ list variations of a single product. Order columns links to The Orders Report filtered by the parent product, which is sub-optimal because the user is given potentially many more orders than just the ones which they were looking for.

Should we have an Advanced Filter for variations so a Order Report can be filtered by one or more variations?

**Comment by LevinMedia** [comment]
Yes please! This would be a great addition when we have time to address.

**Comment by dreiris** [comment]
This ticket is being closed and the feature request is being moved to Monday.com. The feature will be evaluated with other feature requests and prioritized in Monday.com.
